//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmaRemotaManager.svcCalamaioRemoteSign {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://calamaio.gpi.it/services", ConfigurationName="svcCalamaioRemoteSign.SignServicesPortType")]
    internal interface SignServicesPortType {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FirmaRemotaManager.svcCalamaioRemoteSign.hsmMultiSignatureResponse hsmMultiSignature(FirmaRemotaManager.svcCalamaioRemoteSign.hsmMultiSignature request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<FirmaRemotaManager.svcCalamaioRemoteSign.hsmMultiSignatureResponse> hsmMultiSignatureAsync(FirmaRemotaManager.svcCalamaioRemoteSign.hsmMultiSignature request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FirmaRemotaManager.svcCalamaioRemoteSign.hsmSignatureResponse hsmSignature(FirmaRemotaManager.svcCalamaioRemoteSign.hsmSignature request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<FirmaRemotaManager.svcCalamaioRemoteSign.hsmSignatureResponse> hsmSignatureAsync(FirmaRemotaManager.svcCalamaioRemoteSign.hsmSignature request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://calamaio.gpi.it/services")]
    public partial class multiSignResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorCodeField;
        
        private string errorDescriptionField;
        
        private byte[][] signedDocumentsField;
        
        private bool successField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string errorDescription {
            get {
                return this.errorDescriptionField;
            }
            set {
                this.errorDescriptionField = value;
                this.RaisePropertyChanged("errorDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("document", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[][] signedDocuments {
            get {
                return this.signedDocumentsField;
            }
            set {
                this.signedDocumentsField = value;
                this.RaisePropertyChanged("signedDocuments");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("success");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://calamaio.gpi.it/services")]
    public partial class signResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorCodeField;
        
        private string errorDescriptionField;
        
        private byte[] signedDocumentField;
        
        private bool successField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string errorDescription {
            get {
                return this.errorDescriptionField;
            }
            set {
                this.errorDescriptionField = value;
                this.RaisePropertyChanged("errorDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=2)]
        public byte[] signedDocument {
            get {
                return this.signedDocumentField;
            }
            set {
                this.signedDocumentField = value;
                this.RaisePropertyChanged("signedDocument");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("success");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="hsmMultiSignature", WrapperNamespace="http://calamaio.gpi.it/services", IsWrapped=true)]
    internal partial class hsmMultiSignature {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://calamaio.gpi.it/services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string configurationId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://calamaio.gpi.it/services", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://calamaio.gpi.it/services", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://calamaio.gpi.it/services", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string otp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://calamaio.gpi.it/services", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string domain;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://calamaio.gpi.it/services", Order=5)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("document", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[][] documents;
        
        public hsmMultiSignature() {
        }
        
        public hsmMultiSignature(string configurationId, string user, string password, string otp, string domain, byte[][] documents) {
            this.configurationId = configurationId;
            this.user = user;
            this.password = password;
            this.otp = otp;
            this.domain = domain;
            this.documents = documents;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="hsmMultiSignatureResponse", WrapperNamespace="http://calamaio.gpi.it/services", IsWrapped=true)]
    internal partial class hsmMultiSignatureResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://calamaio.gpi.it/services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FirmaRemotaManager.svcCalamaioRemoteSign.multiSignResult @return;
        
        public hsmMultiSignatureResponse() {
        }
        
        public hsmMultiSignatureResponse(FirmaRemotaManager.svcCalamaioRemoteSign.multiSignResult @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="hsmSignature", WrapperNamespace="http://calamaio.gpi.it/services", IsWrapped=true)]
    internal partial class hsmSignature {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://calamaio.gpi.it/services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string configurationId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://calamaio.gpi.it/services", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://calamaio.gpi.it/services", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://calamaio.gpi.it/services", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string otp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://calamaio.gpi.it/services", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string domain;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://calamaio.gpi.it/services", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] document;
        
        public hsmSignature() {
        }
        
        public hsmSignature(string configurationId, string user, string password, string otp, string domain, byte[] document) {
            this.configurationId = configurationId;
            this.user = user;
            this.password = password;
            this.otp = otp;
            this.domain = domain;
            this.document = document;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="hsmSignatureResponse", WrapperNamespace="http://calamaio.gpi.it/services", IsWrapped=true)]
    internal partial class hsmSignatureResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://calamaio.gpi.it/services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FirmaRemotaManager.svcCalamaioRemoteSign.signResult @return;
        
        public hsmSignatureResponse() {
        }
        
        public hsmSignatureResponse(FirmaRemotaManager.svcCalamaioRemoteSign.signResult @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface SignServicesPortTypeChannel : FirmaRemotaManager.svcCalamaioRemoteSign.SignServicesPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class SignServicesPortTypeClient : System.ServiceModel.ClientBase<FirmaRemotaManager.svcCalamaioRemoteSign.SignServicesPortType>, FirmaRemotaManager.svcCalamaioRemoteSign.SignServicesPortType {
        
        public SignServicesPortTypeClient() {
        }
        
        public SignServicesPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SignServicesPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SignServicesPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SignServicesPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FirmaRemotaManager.svcCalamaioRemoteSign.hsmMultiSignatureResponse FirmaRemotaManager.svcCalamaioRemoteSign.SignServicesPortType.hsmMultiSignature(FirmaRemotaManager.svcCalamaioRemoteSign.hsmMultiSignature request) {
            return base.Channel.hsmMultiSignature(request);
        }
        
        public FirmaRemotaManager.svcCalamaioRemoteSign.multiSignResult hsmMultiSignature(string configurationId, string user, string password, string otp, string domain, byte[][] documents) {
            FirmaRemotaManager.svcCalamaioRemoteSign.hsmMultiSignature inValue = new FirmaRemotaManager.svcCalamaioRemoteSign.hsmMultiSignature();
            inValue.configurationId = configurationId;
            inValue.user = user;
            inValue.password = password;
            inValue.otp = otp;
            inValue.domain = domain;
            inValue.documents = documents;
            FirmaRemotaManager.svcCalamaioRemoteSign.hsmMultiSignatureResponse retVal = ((FirmaRemotaManager.svcCalamaioRemoteSign.SignServicesPortType)(this)).hsmMultiSignature(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FirmaRemotaManager.svcCalamaioRemoteSign.hsmMultiSignatureResponse> FirmaRemotaManager.svcCalamaioRemoteSign.SignServicesPortType.hsmMultiSignatureAsync(FirmaRemotaManager.svcCalamaioRemoteSign.hsmMultiSignature request) {
            return base.Channel.hsmMultiSignatureAsync(request);
        }
        
        public System.Threading.Tasks.Task<FirmaRemotaManager.svcCalamaioRemoteSign.hsmMultiSignatureResponse> hsmMultiSignatureAsync(string configurationId, string user, string password, string otp, string domain, byte[][] documents) {
            FirmaRemotaManager.svcCalamaioRemoteSign.hsmMultiSignature inValue = new FirmaRemotaManager.svcCalamaioRemoteSign.hsmMultiSignature();
            inValue.configurationId = configurationId;
            inValue.user = user;
            inValue.password = password;
            inValue.otp = otp;
            inValue.domain = domain;
            inValue.documents = documents;
            return ((FirmaRemotaManager.svcCalamaioRemoteSign.SignServicesPortType)(this)).hsmMultiSignatureAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FirmaRemotaManager.svcCalamaioRemoteSign.hsmSignatureResponse FirmaRemotaManager.svcCalamaioRemoteSign.SignServicesPortType.hsmSignature(FirmaRemotaManager.svcCalamaioRemoteSign.hsmSignature request) {
            return base.Channel.hsmSignature(request);
        }
        
        public FirmaRemotaManager.svcCalamaioRemoteSign.signResult hsmSignature(string configurationId, string user, string password, string otp, string domain, byte[] document) {
            FirmaRemotaManager.svcCalamaioRemoteSign.hsmSignature inValue = new FirmaRemotaManager.svcCalamaioRemoteSign.hsmSignature();
            inValue.configurationId = configurationId;
            inValue.user = user;
            inValue.password = password;
            inValue.otp = otp;
            inValue.domain = domain;
            inValue.document = document;
            FirmaRemotaManager.svcCalamaioRemoteSign.hsmSignatureResponse retVal = ((FirmaRemotaManager.svcCalamaioRemoteSign.SignServicesPortType)(this)).hsmSignature(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FirmaRemotaManager.svcCalamaioRemoteSign.hsmSignatureResponse> FirmaRemotaManager.svcCalamaioRemoteSign.SignServicesPortType.hsmSignatureAsync(FirmaRemotaManager.svcCalamaioRemoteSign.hsmSignature request) {
            return base.Channel.hsmSignatureAsync(request);
        }
        
        public System.Threading.Tasks.Task<FirmaRemotaManager.svcCalamaioRemoteSign.hsmSignatureResponse> hsmSignatureAsync(string configurationId, string user, string password, string otp, string domain, byte[] document) {
            FirmaRemotaManager.svcCalamaioRemoteSign.hsmSignature inValue = new FirmaRemotaManager.svcCalamaioRemoteSign.hsmSignature();
            inValue.configurationId = configurationId;
            inValue.user = user;
            inValue.password = password;
            inValue.otp = otp;
            inValue.domain = domain;
            inValue.document = document;
            return ((FirmaRemotaManager.svcCalamaioRemoteSign.SignServicesPortType)(this)).hsmSignatureAsync(inValue);
        }
    }
}
