CREATE PROCEDURE [dbo].[VerificaRendicontazionePagamentoSaldo_M111_B88]
(
	@ID_DOMANDA_PAGAMENTO INT
)
AS

--DECLARE @ID_DOMANDA_PAGAMENTO INT;SET @ID_DOMANDA_PAGAMENTO=251
--DEFINIZIONI
DECLARE @ID_VARIANTE INT,@ID_PROGETTO INT,@DATA_MODIFICA_PAGAMENTO DATETIME,@ID_INVESTIMENTO INT,
@IMPORTO_RENDICONTATO_ATTUALE DECIMAL(18,2),@CONTRIBUTO_RENDICONTATO_ATTUALE DECIMAL(18,2),@ID_FASCICOLO INT,
--ESITO VERIFICA
@TIPO_RISULTATO CHAR(1),@MESSAGGIO_RISULTATO VARCHAR(3000)
SET @TIPO_RISULTATO='S'
SET @MESSAGGIO_RISULTATO=''

--TROVO PROGETTO E ULTIMA VARIANTE RELATIVA A QUESTA DOMANDA DI PAGAMENTO
SELECT @DATA_MODIFICA_PAGAMENTO=DATA_MODIFICA,@ID_PROGETTO=D.ID_PROGETTO,@ID_FASCICOLO=ID_FASCICOLO FROM DOMANDA_DI_PAGAMENTO D
	INNER JOIN PROGETTO P ON D.ID_PROGETTO=P.ID_PROGETTO WHERE ID_DOMANDA_PAGAMENTO=@ID_DOMANDA_PAGAMENTO
SELECT @ID_VARIANTE=MAX(ID_VARIANTE) FROM VARIANTI WHERE ID_PROGETTO=@ID_PROGETTO AND APPROVATA=1 AND ANNULLATA=0 
	AND DATA_MODIFICA<@DATA_MODIFICA_PAGAMENTO

--CREO PIANO INVESTIMENTI VIRTUALE
DECLARE @INVESTIMENTI_TEMP TABLE ([ID_INVESTIMENTO] [int] NOT NULL,
	[ID_PROGETTO] [int] NULL,
	[ID_PROGRAMMAZIONE] [int] NULL,
	[DESCRIZIONE] [varchar](2000) NULL,
	[DATA_VARIAZIONE] [datetime] NULL,
	[OPERATORE_VARIAZIONE] [varchar](16) NULL,
	[COD_TIPO_INVESTIMENTO] [int] NULL,
	[COD_STP] [char](2) NULL,
	[ID_UNITA_MISURA] [int] NULL,
	[QUANTITA] [decimal](10, 2) NULL,
	[COSTO_INVESTIMENTO] [decimal](15, 2) NULL,
	[SPESE_GENERALI] [decimal](15, 2) NULL,
	[CONTRIBUTO_RICHIESTO] [decimal](15, 2) NULL,
	[QUOTA_CONTRIBUTO_RICHIESTO] [decimal](10, 2) NULL,
	[TASSO_ABBUONO] [decimal](10, 2) NULL,
	[ID_SETTORE_PRODUTTIVO] [int] NULL,
	[ID_PRIORITA_SETTORIALE] [int] NULL,
	[ID_OBIETTIVO_MISURA] [int] NULL,
	[ID_CODIFICA_INVESTIMENTO] [int] NULL,
	[ID_DETTAGLIO_INVESTIMENTO] [int] NULL,
	[ID_SPECIFICA_INVESTIMENTO] [int] NULL,
	[AMMESSO] [bit] NULL,
	[ISTRUTTORE] [varchar](16) NULL,
	[ID_INVESTIMENTO_ORIGINALE] [int] NULL,
	[DATA_VALUTAZIONE] [datetime] NULL,
	[VALUTAZIONE_INVESTIMENTO] [ntext] NULL,
	[ID_VARIANTE] [int] NULL,
	[COD_VARIAZIONE] [char](1),
	[NON_COFINANZIATO] [bit] NULL, 
	IMPORTO_TOTALE_RENDICONTATO DECIMAL(18,2),
	CONTRIBUTO_TOTALE_RENDICONTATO DECIMAL(18,2))	

INSERT INTO @INVESTIMENTI_TEMP
SELECT I.*,	dbo.calcoloTotaleImportoRendicontatoInvestimento(I.ID_INVESTIMENTO,@ID_DOMANDA_PAGAMENTO) AS IMPORTO_TOTALE_RENDICONTATO,
	dbo.calcoloTotaleContributoRendicontatoInvestimento(I.ID_INVESTIMENTO,@ID_DOMANDA_PAGAMENTO) AS CONTRIBUTO_TOTALE_RENDICONTATO 
FROM PROGETTO P INNER JOIN PIANO_INVESTIMENTI I ON P.ID_PROGETTO=I.ID_PROGETTO
WHERE ISNULL(P.ID_PROG_INTEGRATO,P.ID_PROGETTO)=@ID_PROGETTO AND
	((@ID_VARIANTE IS NULL AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND AMMESSO=1 AND ID_VARIANTE IS NULL) OR
	(ID_VARIANTE=@ID_VARIANTE AND ISNULL(COD_VARIAZIONE,'X')!='A')) ORDER BY COD_TIPO_INVESTIMENTO



/**********************************************************************************************************/
--INIZIO CONTROLLO STEP
---------------------------------------------------------------------------------------------------
--ATS - spesa progetto > 25.000,00 e < = 65.000,00 Euro
DECLARE @COSTO_INVESTIMENTI DECIMAL(18,2)
SELECT @COSTO_INVESTIMENTI=SUM(IMPORTO_TOTALE_RENDICONTATO) FROM @INVESTIMENTI_TEMP WHERE COD_TIPO_INVESTIMENTO=1
IF (@COSTO_INVESTIMENTI<25000  AND @COSTO_INVESTIMENTI>65000  )BEGIN
	SET @TIPO_RISULTATO='N'
	SET @MESSAGGIO_RISULTATO=@MESSAGGIO_RISULTATO+'<BR /> - L`ammontare rendicontato sulla misura 111 deve essere superiore a 25.000 € e minore di 65.000€.'
END
	
------------------------------------------------------------------------------------------------
DECLARE @COSTO_INVESTIMENTI_ABCD DECIMAL(18,2)
SELECT @COSTO_INVESTIMENTI_ABCD=SUM(IMPORTO_TOTALE_RENDICONTATO) 
FROM @INVESTIMENTI_TEMP WHERE COD_TIPO_INVESTIMENTO=1 AND
			ID_DETTAGLIO_INVESTIMENTO NOT  IN (722,727,732,737,742)
-----------------------------------------------------------------------------------------------------
--ATS - Spese generali  capitolo 6 par E inferiori/uguale al 12% delle spese A+B+C+D
DECLARE @COSTO_INVESTIMENTI_SPESE_GENERALI DECIMAL(18,2)
IF @COSTO_INVESTIMENTI>0 BEGIN
	SELECT @COSTO_INVESTIMENTI_SPESE_GENERALI=SUM(IMPORTO_TOTALE_RENDICONTATO) FROM @INVESTIMENTI_TEMP
					WHERE   ID_DETTAGLIO_INVESTIMENTO   IN (722,727,732,737,742)
					
	IF @COSTO_INVESTIMENTI_SPESE_GENERALI>(@COSTO_INVESTIMENTI_ABCD*0.12) BEGIN
		SET @TIPO_RISULTATO='N'
		SET @MESSAGGIO_RISULTATO=@MESSAGGIO_RISULTATO+'<BR /> - Le spese generali  capitolo 6 par E  devono essere inferiori/uguale al 12% delle spese A+B+C+D.'
	END
END

 ---------------------------------------------------------------------------------------------------------
--ATS - Spese per costi informatici e telefonici inferiore/uguale al 5% di A+B+C+D

DECLARE @COSTO_INVESTIMENTI_TELEFONICI DECIMAL(18,2)
IF @COSTO_INVESTIMENTI>0 BEGIN
	SELECT @COSTO_INVESTIMENTI_TELEFONICI=SUM(IMPORTO_TOTALE_RENDICONTATO) FROM @INVESTIMENTI_TEMP
					WHERE   ID_SPECIFICA_INVESTIMENTO IN (347,408,417,426,435 )
					
	IF @COSTO_INVESTIMENTI_TELEFONICI>(@COSTO_INVESTIMENTI_ABCD*0.05) BEGIN
		SET @TIPO_RISULTATO='N'
		SET @MESSAGGIO_RISULTATO=@MESSAGGIO_RISULTATO+'<BR /> - Le Spese per costi informatici e telefonici devono essere inferiore/uguale al 5% di A+B+C+D.'
	END
END

------------------------------------------------------------------------------

-- 3. --ATS - Spese per coordinamento inferiore/uguale al 5% di A+B+C+D

DECLARE @COSTO_INVESTIMENTI_CORDINAMENTO DECIMAL(18,2)
 
IF @COSTO_INVESTIMENTI>0 BEGIN
	SELECT @COSTO_INVESTIMENTI_CORDINAMENTO=SUM(IMPORTO_TOTALE_RENDICONTATO) FROM @INVESTIMENTI_TEMP
		WHERE  ID_SPECIFICA_INVESTIMENTO IN (348,409,418,427,436 )
					
	IF @COSTO_INVESTIMENTI_CORDINAMENTO>(@COSTO_INVESTIMENTI_ABCD*0.05) BEGIN
		SET @TIPO_RISULTATO='N'
		SET @MESSAGGIO_RISULTATO=@MESSAGGIO_RISULTATO+'<BR /> - Le Spese per coordinamento devono essere inferiore/uguale al 5% di A+B+C+D.'
	END
END


/*********************************************************************************************************/
IF @TIPO_RISULTATO='S' SET @MESSAGGIO_RISULTATO='VERIFICA DI AMMISSIBILITA DEGLI IMPORTI RENDICONTATI CONFERMATA'
ELSE SET @MESSAGGIO_RISULTATO='Si sono riscontrati i seguenti errori:'+@MESSAGGIO_RISULTATO
SELECT @TIPO_RISULTATO AS TIPO_RISULTATO, @MESSAGGIO_RISULTATO AS MESSAGGIO_RISULTATO
