CREATE PROCEDURE [dbo].[VerificaRendicontazionePagamentoSaldo_M125_B374]
(
	@ID_DOMANDA_PAGAMENTO INT
)
AS

--DECLARE @ID_DOMANDA_PAGAMENTO INT;SET @ID_DOMANDA_PAGAMENTO=251
--DEFINIZIONI
DECLARE @ID_VARIANTE INT,@ID_PROGETTO INT,@DATA_MODIFICA_PAGAMENTO DATETIME,@ID_INVESTIMENTO INT,
@IMPORTO_RENDICONTATO_ATTUALE DECIMAL(18,2),@CONTRIBUTO_RENDICONTATO_ATTUALE DECIMAL(18,2),@ID_FASCICOLO INT,
--ESITO VERIFICA
@TIPO_RISULTATO CHAR(1),@MESSAGGIO_RISULTATO VARCHAR(3000)
SET @TIPO_RISULTATO='S'
SET @MESSAGGIO_RISULTATO=''

--TROVO PROGETTO E ULTIMA VARIANTE RELATIVA A QUESTA DOMANDA DI PAGAMENTO
SELECT @DATA_MODIFICA_PAGAMENTO=DATA_MODIFICA,@ID_PROGETTO=D.ID_PROGETTO,@ID_FASCICOLO=ID_FASCICOLO FROM DOMANDA_DI_PAGAMENTO D
	INNER JOIN PROGETTO P ON D.ID_PROGETTO=P.ID_PROGETTO WHERE ID_DOMANDA_PAGAMENTO=@ID_DOMANDA_PAGAMENTO
SELECT @ID_VARIANTE=MAX(ID_VARIANTE) FROM VARIANTI WHERE ID_PROGETTO=@ID_PROGETTO AND APPROVATA=1 AND ANNULLATA=0 
	AND DATA_MODIFICA<@DATA_MODIFICA_PAGAMENTO

--CREO PIANO INVESTIMENTI VIRTUALE
DECLARE @INVESTIMENTI_TEMP TABLE ([ID_INVESTIMENTO] [int] NOT NULL,
	[ID_PROGETTO] [int] NULL,
	[ID_PROGRAMMAZIONE] [int] NULL,
	[DESCRIZIONE] [varchar](2000) NULL,
	[DATA_VARIAZIONE] [datetime] NULL,
	[OPERATORE_VARIAZIONE] [varchar](16) NULL,
	[COD_TIPO_INVESTIMENTO] [int] NULL,
	[COD_STP] [char](2) NULL,
	[ID_UNITA_MISURA] [int] NULL,
	[QUANTITA] [decimal](10, 2) NULL,
	[COSTO_INVESTIMENTO] [decimal](15, 2) NULL,
	[SPESE_GENERALI] [decimal](15, 2) NULL,
	[CONTRIBUTO_RICHIESTO] [decimal](15, 2) NULL,
	[QUOTA_CONTRIBUTO_RICHIESTO] [decimal](10, 2) NULL,
	[TASSO_ABBUONO] [decimal](10, 2) NULL,
	[ID_SETTORE_PRODUTTIVO] [int] NULL,
	[ID_PRIORITA_SETTORIALE] [int] NULL,
	[ID_OBIETTIVO_MISURA] [int] NULL,
	[ID_CODIFICA_INVESTIMENTO] [int] NULL,
	[ID_DETTAGLIO_INVESTIMENTO] [int] NULL,
	[ID_SPECIFICA_INVESTIMENTO] [int] NULL,
	[AMMESSO] [bit] NULL,
	[ISTRUTTORE] [varchar](16) NULL,
	[ID_INVESTIMENTO_ORIGINALE] [int] NULL,
	[DATA_VALUTAZIONE] [datetime] NULL,
	[VALUTAZIONE_INVESTIMENTO] [ntext] NULL,
	[ID_VARIANTE] [int] NULL,
	[COD_VARIAZIONE] [char](1),
	[NON_COFINANZIATO] [bit] NULL, 
	IMPORTO_TOTALE_RENDICONTATO DECIMAL(18,2),
	CONTRIBUTO_TOTALE_RENDICONTATO DECIMAL(18,2))	

INSERT INTO @INVESTIMENTI_TEMP
SELECT I.*,	dbo.calcoloTotaleImportoRendicontatoInvestimento(I.ID_INVESTIMENTO,@ID_DOMANDA_PAGAMENTO) AS IMPORTO_TOTALE_RENDICONTATO,
	dbo.calcoloTotaleContributoRendicontatoInvestimento(I.ID_INVESTIMENTO,@ID_DOMANDA_PAGAMENTO) AS CONTRIBUTO_TOTALE_RENDICONTATO 
FROM PROGETTO P INNER JOIN PIANO_INVESTIMENTI I ON P.ID_PROGETTO=I.ID_PROGETTO
WHERE ISNULL(P.ID_PROG_INTEGRATO,P.ID_PROGETTO)=@ID_PROGETTO AND
	((@ID_VARIANTE IS NULL AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND AMMESSO=1 AND ID_VARIANTE IS NULL) OR
	(ID_VARIANTE=@ID_VARIANTE AND ISNULL(COD_VARIAZIONE,'X')!='A')) ORDER BY COD_TIPO_INVESTIMENTO

/**********************************************************************************************************/
--INIZIO CONTROLLO STEP


DECLARE @COSTO_INVESTIMENTI DECIMAL(18,2)
--  Rispetto della percentuale massima per le Spese di PROGETTAZIONE e DIREZIONE LAVORI ammessa da bando nel caso di progettazione interna

DECLARE @COSTO_PROG DECIMAL(18,2)=0,@COSTO_DIREZIONE DECIMAL (18,2)=0 ,@RESULT int =1
		,@C_P INT =0, @C_D INT=0

SELECT @COSTO_INVESTIMENTI = SUM(IMPORTO_TOTALE_RENDICONTATO) FROM @INVESTIMENTI_TEMP INV INNER JOIN 
			CODIFICA_INVESTIMENTO CO ON INV.ID_CODIFICA_INVESTIMENTO = CO.ID_CODIFICA_INVESTIMENTO 
WHERE co.CODICE IN ('a','b')

IF((SELECT  COUNT(*) FROM PRIORITA_X_PROGETTO WHERE ID_PRIORITA = 1164 AND ID_PROGETTO = @ID_PROGETTO )>0)
BEGIN
	SET @C_P =1
 	SELECT @COSTO_PROG = SUM(IMPORTO_TOTALE_RENDICONTATO) 
 	FROM @INVESTIMENTI_TEMP INV 
 		INNER JOIN CODIFICA_INVESTIMENTO CO ON INV.ID_CODIFICA_INVESTIMENTO = CO.ID_CODIFICA_INVESTIMENTO 
 		INNER JOIN DETTAGLIO_INVESTIMENTI D ON D.ID_CODIFICA_INVESTIMENTO=INV.ID_CODIFICA_INVESTIMENTO AND D.ID_DETTAGLIO_INVESTIMENTO =INV.ID_DETTAGLIO_INVESTIMENTO 
	WHERE ID_PROGETTO = @ID_PROGETTO AND co.CODICE ='C' AND D.COD_DETTAGLIO ='C1' 	
	IF(@COSTO_PROG > (@COSTO_INVESTIMENTI *2)/100) SET @RESULT =0
END

IF((SELECT  COUNT(*) FROM PRIORITA_X_PROGETTO WHERE ID_PRIORITA = 1165 AND ID_PROGETTO = @ID_PROGETTO )>0)
BEGIN	
	SET @C_D=1
 	SELECT @COSTO_DIREZIONE = SUM(IMPORTO_TOTALE_RENDICONTATO) 
 	FROM @INVESTIMENTI_TEMP INV
 		iNNER JOIN CODIFICA_INVESTIMENTO CO ON INV.ID_CODIFICA_INVESTIMENTO = CO.ID_CODIFICA_INVESTIMENTO 
 		INNER JOIN DETTAGLIO_INVESTIMENTI D ON D.ID_CODIFICA_INVESTIMENTO=INV.ID_CODIFICA_INVESTIMENTO AND D.ID_DETTAGLIO_INVESTIMENTO =INV.ID_DETTAGLIO_INVESTIMENTO 
	WHERE   co.CODICE ='C' AND D.COD_DETTAGLIO ='C2'  
		 
	IF(@COSTO_DIREZIONE > (@COSTO_INVESTIMENTI *2)/100) SET @RESULT =0
END

IF(@C_P=1 AND @C_D =1 AND @RESULT = 1)
BEGIN 
	IF((@COSTO_PROG +@COSTO_DIREZIONE) > (@COSTO_INVESTIMENTi *2)/100) SET @RESULT =0
END


IF @RESULT = 0  BEGIN
	SET @TIPO_RISULTATO='N'
	SET @MESSAGGIO_RISULTATO=@MESSAGGIO_RISULTATO+'<BR /> - Non è rispettata la percentuale massima per le Spese di PROGETTAZIONE e DIREZIONE LAVORI ammessa da bando nel caso di progettazione interna.'
END 
 
 
----------------------------------------------------------------------------------
 -- Spese di PROGETTAZIONE e DIREZIONE LAVORI <= 10% totale investimenti
declare @SPESE_TECNICHE DECIMAL(18,2)
set @RESULT =1

	SELECT @SPESE_TECNICHE = SUM(IMPORTO_TOTALE_RENDICONTATO) 
 	FROM @INVESTIMENTI_TEMP INV
 		iNNER JOIN CODIFICA_INVESTIMENTO CO ON INV.ID_CODIFICA_INVESTIMENTO = CO.ID_CODIFICA_INVESTIMENTO  
	WHERE   co.CODICE ='C'  
	
IF((@SPESE_TECNICHE) > (@COSTO_INVESTIMENTI *10)/100) SET @RESULT =0

	IF @RESULT = 0  BEGIN
		SET @TIPO_RISULTATO='N'
		SET @MESSAGGIO_RISULTATO=@MESSAGGIO_RISULTATO+'<BR /> - Non è rispettata la percentuale massima per le Spese di Tecniche.'
	END 

/*********************************************************************************************************/
IF @TIPO_RISULTATO='S' SET @MESSAGGIO_RISULTATO='VERIFICA DI AMMISSIBILITA DEGLI IMPORTI RENDICONTATI CONFERMATA'
ELSE SET @MESSAGGIO_RISULTATO='Si sono riscontrati i seguenti errori:'+@MESSAGGIO_RISULTATO
SELECT @TIPO_RISULTATO AS TIPO_RISULTATO, @MESSAGGIO_RISULTATO AS MESSAGGIO_RISULTATO
