CREATE PROCEDURE [dbo].[VerificaRendicontazionePagamentoSaldo_M221_251]
(
	@ID_DOMANDA_PAGAMENTO INT
)
AS

--DECLARE @ID_DOMANDA_PAGAMENTO INT;SET @ID_DOMANDA_PAGAMENTO=...
--DEFINIZIONI
DECLARE @ID_VARIANTE INT,@ID_PROGETTO INT,@DATA_MODIFICA_PAGAMENTO DATETIME,@ID_INVESTIMENTO INT,
@IMPORTO_RENDICONTATO_ATTUALE DECIMAL(18,2),@CONTRIBUTO_RENDICONTATO_ATTUALE DECIMAL(18,2),@ID_FASCICOLO INT,
--ESITO VERIFICA
@TIPO_RISULTATO CHAR(1),@MESSAGGIO_RISULTATO VARCHAR(3000)
SET @TIPO_RISULTATO='S'
SET @MESSAGGIO_RISULTATO=''

--TROVO PROGETTO E ULTIMA VARIANTE RELATIVA A QUESTA DOMANDA DI PAGAMENTO
SELECT @DATA_MODIFICA_PAGAMENTO=DATA_MODIFICA,@ID_PROGETTO=D.ID_PROGETTO,@ID_FASCICOLO=ID_FASCICOLO FROM DOMANDA_DI_PAGAMENTO D
	INNER JOIN PROGETTO P ON D.ID_PROGETTO=P.ID_PROGETTO WHERE ID_DOMANDA_PAGAMENTO=@ID_DOMANDA_PAGAMENTO
SELECT @ID_VARIANTE=MAX(ID_VARIANTE) FROM VARIANTI WHERE ID_PROGETTO=@ID_PROGETTO AND APPROVATA=1 AND ANNULLATA=0 
	AND DATA_MODIFICA<@DATA_MODIFICA_PAGAMENTO

--CREO PIANO INVESTIMENTI VIRTUALE
DECLARE @INVESTIMENTI_TEMP TABLE ([ID_INVESTIMENTO] [int] NOT NULL,
	[ID_PROGETTO] [int] NULL,
	[ID_PROGRAMMAZIONE] [int] NULL,
	[DESCRIZIONE] [varchar](2000) NULL,
	[DATA_VARIAZIONE] [datetime] NULL,
	[OPERATORE_VARIAZIONE] [varchar](16) NULL,
	[COD_TIPO_INVESTIMENTO] [int] NULL,
	[COD_STP] [char](2) NULL,
	[ID_UNITA_MISURA] [int] NULL,
	[QUANTITA] [decimal](10, 2) NULL,
	[COSTO_INVESTIMENTO] [decimal](15, 2) NULL,
	[SPESE_GENERALI] [decimal](15, 2) NULL,
	[CONTRIBUTO_RICHIESTO] [decimal](15, 2) NULL,
	[QUOTA_CONTRIBUTO_RICHIESTO] [decimal](10, 2) NULL,
	[TASSO_ABBUONO] [decimal](10, 2) NULL,
	[ID_SETTORE_PRODUTTIVO] [int] NULL,
	[ID_PRIORITA_SETTORIALE] [int] NULL,
	[ID_OBIETTIVO_MISURA] [int] NULL,
	[ID_CODIFICA_INVESTIMENTO] [int] NULL,
	[ID_DETTAGLIO_INVESTIMENTO] [int] NULL,
	[ID_SPECIFICA_INVESTIMENTO] [int] NULL,
	[AMMESSO] [bit] NULL,
	[ISTRUTTORE] [varchar](16) NULL,
	[ID_INVESTIMENTO_ORIGINALE] [int] NULL,
	[DATA_VALUTAZIONE] [datetime] NULL,
	[VALUTAZIONE_INVESTIMENTO] [ntext] NULL,
	[ID_VARIANTE] [int] NULL,
	[COD_VARIAZIONE] [char](1),
	[NON_COFINANZIATO] [bit] NULL, 
	IMPORTO_TOTALE_RENDICONTATO DECIMAL(18,2),
	CONTRIBUTO_TOTALE_RENDICONTATO DECIMAL(18,2))	

INSERT INTO @INVESTIMENTI_TEMP
SELECT I.*,	dbo.calcoloTotaleImportoRendicontatoInvestimento(I.ID_INVESTIMENTO,@ID_DOMANDA_PAGAMENTO) AS IMPORTO_TOTALE_RENDICONTATO,
	dbo.calcoloTotaleContributoRendicontatoInvestimento(I.ID_INVESTIMENTO,@ID_DOMANDA_PAGAMENTO) AS CONTRIBUTO_TOTALE_RENDICONTATO 
FROM PROGETTO P INNER JOIN PIANO_INVESTIMENTI I ON P.ID_PROGETTO=I.ID_PROGETTO
WHERE ISNULL(P.ID_PROG_INTEGRATO,P.ID_PROGETTO)=@ID_PROGETTO AND
	((@ID_VARIANTE IS NULL AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND AMMESSO=1 AND ID_VARIANTE IS NULL) OR
	(ID_VARIANTE=@ID_VARIANTE AND ISNULL(COD_VARIAZIONE,'X')!='A')) ORDER BY COD_TIPO_INVESTIMENTO

/**********************************************************************************************************/
--INIZIO CONTROLLO STEP

---------------------------------------------------------------------------------------------------
-- recupero l'importo rendicontato per il progetto
DECLARE @COSTO_INVESTIMENTI DECIMAL(18,2)
SELECT @COSTO_INVESTIMENTI=SUM(IMPORTO_TOTALE_RENDICONTATO) FROM @INVESTIMENTI_TEMP WHERE COD_TIPO_INVESTIMENTO=1


------------------------------------------------------------------------------------------------------------
-- PREMIO manutenzione <= massimale annuo da bando            

DECLARE @COLLINALITORANEA int,
		@COLLINAINTERNA int,
		@MONTAGNAINTERNA int

IF (SELECT COUNT(ID_PRIORITA) FROM PRIORITA_X_PROGETTO WHERE ID_PROGETTO = @ID_PROGETTO AND ID_PRIORITA = 603) = 1
BEGIN
     SET @COLLINALITORANEA = 510
     SET @COLLINAINTERNA = 450
     SET @MONTAGNAINTERNA = 370
END
ELSE 
BEGIN
     SET @COLLINALITORANEA = 150
     SET @COLLINAINTERNA = 150
     SET @MONTAGNAINTERNA = 150
END

--- COLLINA LITORANEA)
DECLARE @A INT

SELECT @A=  COUNT(*) 
FROM (
                         SELECT SUM(DISTINCT ISNULL(IMPORTO_AMMESSO,0)) AS COSTO , VPI.DESCRIZIONE AS dDESCRIZIONE , VPI.CODICE, PXI_HA.VALORE AS SUPERFICIE 
                         FROM VPIANO_INVESTIMENTI VPI 
                                      inner join PRIORITA_X_INVESTIMENTI PXI ON VPI.ID_INVESTIMENTO = PXI.ID_INVESTIMENTO 
                                      INNER JOIN PRIORITA_X_INVESTIMENTI PXI_HA ON VPI.ID_INVESTIMENTO = PXI_HA.ID_INVESTIMENTO AND PXI_HA.ID_PRIORITA = 605
                                      INNER JOIN PAGAMENTI_RICHIESTI PR ON VPI.ID_INVESTIMENTO = PR.ID_INVESTIMENTO 
                          WHERE VPI.ID_PROGETTO = @ID_PROGETTO AND ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO  
                          AND VPI.ID_DETTAGLIO_INVESTIMENTO in 
                                      (SELECT ID_DETTAGLIO_INVESTIMENTO FROM CODIFICA_INVESTIMENTO CI INNER JOIN DETTAGLIO_INVESTIMENTI DI ON 
                                      (CI.ID_CODIFICA_INVESTIMENTO = DI.ID_CODIFICA_INVESTIMENTO) WHERE CI.ID_BANDO = 
                                      (SELECT ID_BANDO FROM PROGETTO WHERE ID_PROGETTO = @ID_PROGETTO) AND DI.COD_DETTAGLIO = 'd1')
                         AND ((@ID_VARIANTE IS NULL AND VPI.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND VPI.AMMESSO=1 AND ID_VARIANTE IS NULL) OR
                                      (ID_VARIANTE=@ID_VARIANTE AND ISNULL(COD_VARIAZIONE,'X')!='A'))
                         GROUP BY VPI.DESCRIZIONE , PXI_HA.VALORE, VPI.CODICE) AS DETT_INV
GROUP BY CODICE
HAVING (SUM(COSTO)/10) > (@COLLINALITORANEA * (SUM (SUPERFICIE)/10000)) AND COUNT(*) >0

 IF( @A IS NOT NULL OR @A> 0)                     
 BEGIN             
                      SET @TIPO_RISULTATO='N'
                      SET @MESSAGGIO_RISULTATO=@MESSAGGIO_RISULTATO+'<BR /> -  PREMIO perdita reddito <= massimale annuo da bando (COLLINA LITORANEA)'
END     
             
--- COLLINA INTERNA)
DECLARE @B INT

SELECT @B=  COUNT(*) 
FROM (
                         SELECT SUM(DISTINCT ISNULL(IMPORTO_AMMESSO,0)) AS COSTO, VPI.DESCRIZIONE AS dDESCRIZIONE , VPI.CODICE, PXI_HA.VALORE AS SUPERFICIE 
                         FROM VPIANO_INVESTIMENTI VPI 
                                      inner join PRIORITA_X_INVESTIMENTI PXI ON VPI.ID_INVESTIMENTO = PXI.ID_INVESTIMENTO 
                                      INNER JOIN PRIORITA_X_INVESTIMENTI PXI_HA ON VPI.ID_INVESTIMENTO = PXI_HA.ID_INVESTIMENTO AND PXI_HA.ID_PRIORITA = 605
                                      INNER JOIN PAGAMENTI_RICHIESTI PR ON VPI.ID_INVESTIMENTO = PR.ID_INVESTIMENTO 
                          WHERE VPI.ID_PROGETTO = @ID_PROGETTO AND ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO  
                          AND VPI.ID_DETTAGLIO_INVESTIMENTO in 
                                      (SELECT ID_DETTAGLIO_INVESTIMENTO FROM CODIFICA_INVESTIMENTO CI INNER JOIN DETTAGLIO_INVESTIMENTI DI ON 
                                      (CI.ID_CODIFICA_INVESTIMENTO = DI.ID_CODIFICA_INVESTIMENTO) WHERE CI.ID_BANDO = 
                                      (SELECT ID_BANDO FROM PROGETTO WHERE ID_PROGETTO = @ID_PROGETTO) AND DI.COD_DETTAGLIO = 'd2')
                         AND ((@ID_VARIANTE IS NULL AND VPI.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND VPI.AMMESSO=1 AND ID_VARIANTE IS NULL) OR
                                      (ID_VARIANTE=@ID_VARIANTE AND ISNULL(COD_VARIAZIONE,'X')!='A'))
                         GROUP BY VPI.DESCRIZIONE , PXI_HA.VALORE,VPI.CODICE) AS DETT_INV
GROUP BY CODICE
HAVING (SUM(COSTO)/10) > (@COLLINALITORANEA * (SUM (SUPERFICIE)/10000)) AND COUNT(*) >0

 IF( @B IS NOT NULL OR @B> 0)                     
 BEGIN             
                          SET @TIPO_RISULTATO='N'
                          SET @MESSAGGIO_RISULTATO=@MESSAGGIO_RISULTATO+'<BR /> -  PREMIO perdita reddito <= massimale annuo da bando (COLLINA INTERNA)'
END                  
             
             --- MONTAGNA INTERNA)
DECLARE @C INT

SELECT @C=  COUNT(*) 
FROM (
                         SELECT SUM(DISTINCT ISNULL(IMPORTO_AMMESSO,0)) AS COSTO, VPI.DESCRIZIONE AS dDESCRIZIONE , VPI.CODICE, PXI_HA.VALORE AS SUPERFICIE 
                         FROM VPIANO_INVESTIMENTI VPI 
                                      INNER JOIN PRIORITA_X_INVESTIMENTI PXI ON VPI.ID_INVESTIMENTO = PXI.ID_INVESTIMENTO 
                                      INNER JOIN PRIORITA_X_INVESTIMENTI PXI_HA ON VPI.ID_INVESTIMENTO = PXI_HA.ID_INVESTIMENTO AND PXI_HA.ID_PRIORITA = 605
                                      INNER JOIN PAGAMENTI_RICHIESTI PR ON VPI.ID_INVESTIMENTO = PR.ID_INVESTIMENTO 
                          WHERE VPI.ID_PROGETTO = @ID_PROGETTO AND ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO  
                          AND VPI.ID_DETTAGLIO_INVESTIMENTO in 
                                      (SELECT ID_DETTAGLIO_INVESTIMENTO FROM CODIFICA_INVESTIMENTO CI INNER JOIN DETTAGLIO_INVESTIMENTI DI ON 
                                      (CI.ID_CODIFICA_INVESTIMENTO = DI.ID_CODIFICA_INVESTIMENTO) WHERE CI.ID_BANDO = 
                                      (SELECT ID_BANDO FROM PROGETTO WHERE ID_PROGETTO = @ID_PROGETTO) AND DI.COD_DETTAGLIO = 'd3')
                         AND ((@ID_VARIANTE IS NULL AND VPI.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND VPI.AMMESSO=1 AND ID_VARIANTE IS NULL) OR
                                      (ID_VARIANTE=@ID_VARIANTE AND ISNULL(COD_VARIAZIONE,'X')!='A'))
                         GROUP BY VPI.DESCRIZIONE , PXI_HA.VALORE,VPI.CODICE) AS DETT_INV
GROUP BY CODICE
HAVING (SUM(COSTO)/10) > (@COLLINALITORANEA * (SUM (SUPERFICIE)/10000)) AND COUNT(*) >0

 IF( @C IS NOT NULL OR @B> 0)                     
 BEGIN             
                         SET @TIPO_RISULTATO='N'
                         SET @MESSAGGIO_RISULTATO=@MESSAGGIO_RISULTATO+'<BR /> -  PREMIO perdita reddito <= massimale annuo da bando (MONTAGNA INTERNA)'
END     



------------------------------------------------------------------------------------------------

-- Spese GENERALI di impianto <=10% Costi impianto

DECLARE @SPESEIMPIANTO DECIMAL (18,2) ,@SPESEGENERALI DECIMAL (18,2) , @ANNO INT, @DATA_ULTIMA_MODIFICA DATETIME

SET @SPESEIMPIANTO = 0 -- INIZIALIZZO LA VARIABILE		
SET @SPESEGENERALI = 0 -- INIZIALIZZO LA VARIABILE		

IF @COSTO_INVESTIMENTI>0 BEGIN
	SELECT @ID_PROGETTO =ID_PROGETTO, @DATA_ULTIMA_MODIFICA=DATA_MODIFICA FROM DOMANDA_DI_PAGAMENTO WHERE ID_DOMANDA_PAGAMENTO=@ID_DOMANDA_PAGAMENTO
	SET @ANNO = DATEPART(YEAR,@DATA_ULTIMA_MODIFICA)-1

	SET @SPESEIMPIANTO = (SELECT SUM( ISNULL(IMPORTO_AMMESSO, PR.IMPORTO_RICHIESTO) )
							FROM PIANO_INVESTIMENTI  PI inner join   PAGAMENTI_RICHIESTI  PR  ON PI.ID_INVESTIMENTO = PR.ID_INVESTIMENTO 
							WHERE ID_PROGETTO = @ID_PROGETTO  AND  ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO
								 AND PI.ID_CODIFICA_INVESTIMENTO IN (SELECT ID_CODIFICA_INVESTIMENTO FROM CODIFICA_INVESTIMENTO 
																	WHERE ID_BANDO = (SELECT ID_BANDO FROM PROGETTO WHERE ID_PROGETTO = @ID_PROGETTO)AND CODICE = 'a')
								 AND ((@ID_VARIANTE IS NULL AND PI.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND PI.AMMESSO=1 AND ID_VARIANTE IS NULL) OR
								     (ID_VARIANTE=@ID_VARIANTE AND ISNULL(COD_VARIAZIONE,'X')!='A'))
						)
							

	SET @SPESEGENERALI= (SELECT SUM( ISNULL(IMPORTO_AMMESSO, PR.IMPORTO_RICHIESTO) )
							FROM PIANO_INVESTIMENTI  PI inner join   PAGAMENTI_RICHIESTI  PR  ON PI.ID_INVESTIMENTO = PR.ID_INVESTIMENTO 
							WHERE ID_PROGETTO = @ID_PROGETTO  AND  ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO
								 AND PI.ID_CODIFICA_INVESTIMENTO IN (SELECT ID_CODIFICA_INVESTIMENTO FROM CODIFICA_INVESTIMENTO 
																	WHERE ID_BANDO = (SELECT ID_BANDO FROM PROGETTO WHERE ID_PROGETTO = @ID_PROGETTO)AND CODICE = 'b')
								 AND ((@ID_VARIANTE IS NULL AND PI.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND PI.AMMESSO=1 AND ID_VARIANTE IS NULL) OR
								    (ID_VARIANTE=@ID_VARIANTE AND ISNULL(COD_VARIAZIONE,'X')!='A'))
						)	

		IF(@SPESEGENERALI > ((@SPESEIMPIANTO*10)/100))BEGIN
				SET @TIPO_RISULTATO='N'
				SET @MESSAGGIO_RISULTATO=@MESSAGGIO_RISULTATO+'<BR /> -  Spese GENERALI di impianto maggiori del 10% dei Costi di impianto'
		END
END
 
-----------------------------------------------------------------------------------------

--- COSTO DI IMPIANTO <= costo massimo/Ha per tipologia a di impianto

DECLARE @RESULTA1 decimal,
		@RESULTA2 decimal,
		@RESULTA3 decimal

--a1 bando id 203 id dettaglio 4494 - bando id 233 id dettaglio 4935 
--a2 bando id 203 id dettaglio 4495 - bando id 233 id dettaglio 4936 
--a3 bando id 203 id dettaglio 4496 - bando id 233 id dettaglio 4937 

--- Costo di impianto <= costo massimo/Ha per tipologia a di impianto
--- TIPOLOGIA a1)

set @RESULTA1 = (SELECT ((SELECT ISNULL(SUM(COSTO_INVESTIMENTO),0) FROM PROGETTO P
							INNER JOIN VPIANO_INVESTIMENTI PI ON (P.ID_PROGETTO = PI.ID_PROGETTO) 
							INNER JOIN PAGAMENTI_RICHIESTI PR ON PI.ID_INVESTIMENTO = PR.ID_INVESTIMENTO
							WHERE ((@ID_VARIANTE IS NULL AND PI.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND PI.AMMESSO=1 AND ID_VARIANTE IS NULL) OR
								 (ID_VARIANTE=@ID_VARIANTE AND ISNULL(COD_VARIAZIONE,'X')!='A'))
							AND PI.CODICE = 'a' AND PI.ID_DETTAGLIO_INVESTIMENTO in 
								(SELECT ID_DETTAGLIO_INVESTIMENTO FROM CODIFICA_INVESTIMENTO CI INNER JOIN DETTAGLIO_INVESTIMENTI DI ON 
								(CI.ID_CODIFICA_INVESTIMENTO = DI.ID_CODIFICA_INVESTIMENTO) WHERE CI.ID_BANDO = 
								(SELECT ID_BANDO FROM PROGETTO WHERE ID_PROGETTO = @ID_PROGETTO) AND DI.COD_DETTAGLIO = 'a1')
							AND P.ID_PROGETTO = @ID_PROGETTO
							AND ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO) 
/
((SELECT ISNULL(SUM (VALORE), 1) AS Totale_Ha FROM PRIORITA_X_INVESTIMENTI PXI 
						  INNER JOIN VPIANO_INVESTIMENTI PI on PI.ID_INVESTIMENTO = PXI.ID_INVESTIMENTO 
						  INNER JOIN PAGAMENTI_RICHIESTI PR ON PI.ID_INVESTIMENTO = PR.ID_INVESTIMENTO 
							WHERE 
							((@ID_VARIANTE IS NULL AND PI.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND PI.AMMESSO=1 AND ID_VARIANTE IS NULL) OR
								 (ID_VARIANTE=@ID_VARIANTE AND ISNULL(COD_VARIAZIONE,'X')!='A'))
							AND PXI.ID_PRIORITA = 605  -- ottengo m2 e sotto gli ettari
							AND PI.ID_PROGETTO = @ID_PROGETTO 
							AND ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO) /10000)))


--- TIPOLOGIA a2)

set @RESULTA2 =  (SELECT ((SELECT ISNULL(SUM(COSTO_INVESTIMENTO),0) FROM PROGETTO P
							INNER JOIN VPIANO_INVESTIMENTI PI ON (P.ID_PROGETTO = PI.ID_PROGETTO) 
							INNER JOIN PAGAMENTI_RICHIESTI PR ON PI.ID_INVESTIMENTO = PR.ID_INVESTIMENTO
							WHERE
							((@ID_VARIANTE IS NULL AND PI.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND PI.AMMESSO=1 AND ID_VARIANTE IS NULL) OR
								 (ID_VARIANTE=@ID_VARIANTE AND ISNULL(COD_VARIAZIONE,'X')!='A'))
							AND PI.CODICE = 'a' AND PI.ID_DETTAGLIO_INVESTIMENTO in 
								(SELECT ID_DETTAGLIO_INVESTIMENTO FROM CODIFICA_INVESTIMENTO CI INNER JOIN DETTAGLIO_INVESTIMENTI DI ON 
								(CI.ID_CODIFICA_INVESTIMENTO = DI.ID_CODIFICA_INVESTIMENTO) WHERE CI.ID_BANDO = 
								(SELECT ID_BANDO FROM PROGETTO WHERE ID_PROGETTO = @ID_PROGETTO) AND DI.COD_DETTAGLIO = 'a2')
							AND P.ID_PROGETTO = @ID_PROGETTO
							AND ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO) 
/
((SELECT ISNULL(SUM (VALORE), 1) AS Totale_Ha FROM PRIORITA_X_INVESTIMENTI PXI 
					  INNER JOIN VPIANO_INVESTIMENTI PI on PI.ID_INVESTIMENTO = PXI.ID_INVESTIMENTO 
					  INNER JOIN PAGAMENTI_RICHIESTI PR ON PI.ID_INVESTIMENTO = PR.ID_INVESTIMENTO 
						WHERE  
						((@ID_VARIANTE IS NULL AND PI.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND PI.AMMESSO=1 AND ID_VARIANTE IS NULL) OR
							 (ID_VARIANTE=@ID_VARIANTE AND ISNULL(COD_VARIAZIONE,'X')!='A'))
						AND PXI.ID_PRIORITA = 605  -- ottengo m2 e sotto gli ettari
						AND PI.ID_PROGETTO = @ID_PROGETTO 
						AND ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO) /10000)))


--- TIPOLOGIA a3)

set @RESULTA3 =  (SELECT ((SELECT ISNULL(SUM(COSTO_INVESTIMENTO),0) FROM PROGETTO P
							INNER JOIN VPIANO_INVESTIMENTI PI ON (P.ID_PROGETTO = PI.ID_PROGETTO) 
							INNER JOIN PAGAMENTI_RICHIESTI PR ON PI.ID_INVESTIMENTO = PR.ID_INVESTIMENTO
								WHERE
								((@ID_VARIANTE IS NULL AND PI.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND PI.AMMESSO=1 AND ID_VARIANTE IS NULL) OR
									 (ID_VARIANTE=@ID_VARIANTE AND ISNULL(COD_VARIAZIONE,'X')!='A'))
								AND PI.CODICE = 'a' AND PI.ID_DETTAGLIO_INVESTIMENTO in 
									(SELECT ID_DETTAGLIO_INVESTIMENTO FROM CODIFICA_INVESTIMENTO CI INNER JOIN DETTAGLIO_INVESTIMENTI DI ON 
									(CI.ID_CODIFICA_INVESTIMENTO = DI.ID_CODIFICA_INVESTIMENTO) WHERE CI.ID_BANDO = 
									(SELECT ID_BANDO FROM PROGETTO WHERE ID_PROGETTO = @ID_PROGETTO) AND DI.COD_DETTAGLIO = 'a3')
								AND P.ID_PROGETTO = @ID_PROGETTO
								AND ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO) 
/
((SELECT ISNULL(SUM (VALORE), 1) AS Totale_Ha FROM PRIORITA_X_INVESTIMENTI PXI 
					  INNER JOIN VPIANO_INVESTIMENTI PI on PI.ID_INVESTIMENTO = PXI.ID_INVESTIMENTO 
					  INNER JOIN PAGAMENTI_RICHIESTI PR ON PI.ID_INVESTIMENTO = PR.ID_INVESTIMENTO 
						WHERE   
						((@ID_VARIANTE IS NULL AND PI.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND PI.AMMESSO=1 AND ID_VARIANTE IS NULL) OR
							 (ID_VARIANTE=@ID_VARIANTE AND ISNULL(COD_VARIAZIONE,'X')!='A'))
						AND PXI.ID_PRIORITA = 605  -- ottengo m2 e sotto gli ettari
						AND PI.ID_PROGETTO = @ID_PROGETTO 
						AND ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO) /10000)))


IF(@RESULTA1 > 8500 OR @RESULTA2 > 8500 OR @RESULTA3 > 7800)
 BEGIN             
                          SET @TIPO_RISULTATO='N'
                          SET @MESSAGGIO_RISULTATO=@MESSAGGIO_RISULTATO+'<BR /> -  COSTO DI IMPIANTO > costo massimo/Ha per tipologia a di impianto'
END  
-----------------------------------------------------------------------------------------
/*********************************************************************************************************/
IF @TIPO_RISULTATO='S' SET @MESSAGGIO_RISULTATO='VERIFICA DI AMMISSIBILITA DEGLI IMPORTI RENDICONTATI CONFERMATA'
ELSE SET @MESSAGGIO_RISULTATO='Si sono riscontrati i seguenti errori:'+@MESSAGGIO_RISULTATO
SELECT @TIPO_RISULTATO AS TIPO_RISULTATO, @MESSAGGIO_RISULTATO AS MESSAGGIO_RISULTATO
