CREATE PROCEDURE [dbo].[VerificaRendicontazionePagamentoSaldo_M111_B157]
(
	@ID_DOMANDA_PAGAMENTO INT
)
AS

--DECLARE @ID_DOMANDA_PAGAMENTO INT;SET @ID_DOMANDA_PAGAMENTO=251
--DEFINIZIONI
DECLARE @ID_VARIANTE INT,@ID_PROGETTO INT,@DATA_MODIFICA_PAGAMENTO DATETIME,@ID_INVESTIMENTO INT,
@IMPORTO_RENDICONTATO_ATTUALE DECIMAL(18,2),@CONTRIBUTO_RENDICONTATO_ATTUALE DECIMAL(18,2),@ID_FASCICOLO INT,
--ESITO VERIFICA
@TIPO_RISULTATO CHAR(1),@MESSAGGIO_RISULTATO VARCHAR(3000)
SET @TIPO_RISULTATO='S'
SET @MESSAGGIO_RISULTATO=''

--TROVO PROGETTO E ULTIMA VARIANTE RELATIVA A QUESTA DOMANDA DI PAGAMENTO
SELECT @DATA_MODIFICA_PAGAMENTO=DATA_MODIFICA,@ID_PROGETTO=D.ID_PROGETTO,@ID_FASCICOLO=ID_FASCICOLO FROM DOMANDA_DI_PAGAMENTO D
	INNER JOIN PROGETTO P ON D.ID_PROGETTO=P.ID_PROGETTO WHERE ID_DOMANDA_PAGAMENTO=@ID_DOMANDA_PAGAMENTO
SELECT @ID_VARIANTE=MAX(ID_VARIANTE) FROM VARIANTI WHERE ID_PROGETTO=@ID_PROGETTO AND APPROVATA=1 AND ANNULLATA=0 
	AND DATA_MODIFICA<@DATA_MODIFICA_PAGAMENTO

--CREO PIANO INVESTIMENTI VIRTUALE
DECLARE @INVESTIMENTI_TEMP TABLE ([ID_INVESTIMENTO] [int] NOT NULL,
	[ID_PROGETTO] [int] NULL,
	[ID_PROGRAMMAZIONE] [int] NULL,
	[DESCRIZIONE] [varchar](2000) NULL,
	[DATA_VARIAZIONE] [datetime] NULL,
	[OPERATORE_VARIAZIONE] [varchar](16) NULL,
	[COD_TIPO_INVESTIMENTO] [int] NULL,
	[COD_STP] [char](2) NULL,
	[ID_UNITA_MISURA] [int] NULL,
	[QUANTITA] [decimal](10, 2) NULL,
	[COSTO_INVESTIMENTO] [decimal](15, 2) NULL,
	[SPESE_GENERALI] [decimal](15, 2) NULL,
	[CONTRIBUTO_RICHIESTO] [decimal](15, 2) NULL,
	[QUOTA_CONTRIBUTO_RICHIESTO] [decimal](10, 2) NULL,
	[TASSO_ABBUONO] [decimal](10, 2) NULL,
	[ID_SETTORE_PRODUTTIVO] [int] NULL,
	[ID_PRIORITA_SETTORIALE] [int] NULL,
	[ID_OBIETTIVO_MISURA] [int] NULL,
	[ID_CODIFICA_INVESTIMENTO] [int] NULL,
	[ID_DETTAGLIO_INVESTIMENTO] [int] NULL,
	[ID_SPECIFICA_INVESTIMENTO] [int] NULL,
	[AMMESSO] [bit] NULL,
	[ISTRUTTORE] [varchar](16) NULL,
	[ID_INVESTIMENTO_ORIGINALE] [int] NULL,
	[DATA_VALUTAZIONE] [datetime] NULL,
	[VALUTAZIONE_INVESTIMENTO] [ntext] NULL,
	[ID_VARIANTE] [int] NULL,
	[COD_VARIAZIONE] [char](1),
	[NON_COFINANZIATO] [bit] NULL, 
	IMPORTO_TOTALE_RENDICONTATO DECIMAL(18,2),
	CONTRIBUTO_TOTALE_RENDICONTATO DECIMAL(18,2))	

INSERT INTO @INVESTIMENTI_TEMP
SELECT I.*,	dbo.calcoloTotaleImportoRendicontatoInvestimento(I.ID_INVESTIMENTO,@ID_DOMANDA_PAGAMENTO) AS IMPORTO_TOTALE_RENDICONTATO,
	dbo.calcoloTotaleContributoRendicontatoInvestimento(I.ID_INVESTIMENTO,@ID_DOMANDA_PAGAMENTO) AS CONTRIBUTO_TOTALE_RENDICONTATO 
FROM PROGETTO P INNER JOIN PIANO_INVESTIMENTI I ON P.ID_PROGETTO=I.ID_PROGETTO
WHERE ISNULL(P.ID_PROG_INTEGRATO,P.ID_PROGETTO)=@ID_PROGETTO AND
	((@ID_VARIANTE IS NULL AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND AMMESSO=1 AND ID_VARIANTE IS NULL) OR
	(ID_VARIANTE=@ID_VARIANTE AND ISNULL(COD_VARIAZIONE,'X')!='A')) ORDER BY COD_TIPO_INVESTIMENTO

/**********************************************************************************************************/
--INIZIO CONTROLLO STEP
---------------------------------------------------------------------------------------------------
DECLARE @COSTO_INVESTIMENTI DECIMAL(18,2)
SELECT @COSTO_INVESTIMENTI=SUM(IMPORTO_TOTALE_RENDICONTATO) FROM @INVESTIMENTI_TEMP WHERE COD_TIPO_INVESTIMENTO=1

------------------------------------------------------------------------------------------------
--  Il costo del personale interno non supera il 70% del costo del progetto.

DECLARE @COSTO_INVESTIMENTI_PERSONALE DECIMAL(18,2)
IF @COSTO_INVESTIMENTI>0 BEGIN
	SELECT @COSTO_INVESTIMENTI_PERSONALE=SUM(IMPORTO_TOTALE_RENDICONTATO) 
	FROM @INVESTIMENTI_TEMP INV	INNER JOIN DETTAGLIO_INVESTIMENTI DI ON (INV.ID_DETTAGLIO_INVESTIMENTO = DI.ID_DETTAGLIO_INVESTIMENTO)   
	WHERE DI.COD_DETTAGLIO IN( '1','6')
						
	IF @COSTO_INVESTIMENTI_PERSONALE>(@COSTO_INVESTIMENTI*0.70) BEGIN
		SET @TIPO_RISULTATO='N'
		SET @MESSAGGIO_RISULTATO=@MESSAGGIO_RISULTATO+'<BR /> - Il costo del personale supera il 70% del costo del progetto.'
	END
END
	
----------------------------------------------------------------------------------
-- 1. Le spese di coordinamento <= 5% totale domanda (Codifica investimento = 12)
 
DECLARE @COSTO_INVESTIMENTI_COORD DECIMAL(18,2)
 
IF @COSTO_INVESTIMENTI>0 BEGIN
	SELECT @COSTO_INVESTIMENTI_COORD=SUM(IMPORTO_TOTALE_RENDICONTATO) FROM @INVESTIMENTI_TEMP INV INNER JOIN 
			CODIFICA_INVESTIMENTO CO ON INV.ID_CODIFICA_INVESTIMENTO = CO.ID_CODIFICA_INVESTIMENTO 
	WHERE  CO.CODICE= '12'
					
	IF @COSTO_INVESTIMENTI_COORD>(@COSTO_INVESTIMENTI*0.05) BEGIN
		SET @TIPO_RISULTATO='N'
		SET @MESSAGGIO_RISULTATO=@MESSAGGIO_RISULTATO+'<BR /> - Il costo per coordinamento organizzativo supera il 5% del costo del progetto.'
	END
END

-----------------------------------------------------------------------------------------
  -- 2. Totale spese ricognizione <= 20% totale domanda (codifica investimento = 11)

DECLARE @COSTO_INVESTIMENTI_RICOG DECIMAL(18,2)
 
IF @COSTO_INVESTIMENTI>0 BEGIN
	SELECT @COSTO_INVESTIMENTI_RICOG=SUM(IMPORTO_TOTALE_RENDICONTATO) FROM @INVESTIMENTI_TEMP INV INNER JOIN 
		   CODIFICA_INVESTIMENTO CO ON INV.ID_CODIFICA_INVESTIMENTO = CO.ID_CODIFICA_INVESTIMENTO
	WHERE CODICE = '11' 
	IF @COSTO_INVESTIMENTI_RICOG>(@COSTO_INVESTIMENTI*0.2) BEGIN
		SET @TIPO_RISULTATO='N'
		SET @MESSAGGIO_RISULTATO=@MESSAGGIO_RISULTATO+'<BR /> -  Il costo delle spese ricognizione supera il 20% del costo del progetto.'
	END
END

-----------------------------------------------------------------------------------------
  -- 3.  Il costo delle spese generali non supera il 5% del costo del progetto (Codifica investimento = 13)

DECLARE @COSTO_INVESTIMENTI_GEN DECIMAL(18,2)
 
IF @COSTO_INVESTIMENTI>0 BEGIN
	SELECT @COSTO_INVESTIMENTI_GEN=SUM(IMPORTO_TOTALE_RENDICONTATO) FROM @INVESTIMENTI_TEMP INV INNER JOIN 
		   CODIFICA_INVESTIMENTO CO ON INV.ID_CODIFICA_INVESTIMENTO = CO.ID_CODIFICA_INVESTIMENTO
	WHERE CODICE = '13' 
					
	IF @COSTO_INVESTIMENTI_GEN>(@COSTO_INVESTIMENTI*0.05) BEGIN
		SET @TIPO_RISULTATO='N'
		SET @MESSAGGIO_RISULTATO=@MESSAGGIO_RISULTATO+'<BR /> -  Il costo delle spese generali supera il 5% del costo del progetto.'
	END
END

------------------------------------------------------------------------------

-- 4.  Spese per servizi esterni <= 10% del totale investimenti aventi la stessa codifica (dettaglio investimento = 5)
 
DECLARE @COSTO_INVESTIMENTI_SERVEST DECIMAL(18,2)
 
IF @COSTO_INVESTIMENTI>0 BEGIN
	SELECT @COSTO_INVESTIMENTI_SERVEST=SUM(IMPORTO_TOTALE_RENDICONTATO) 
	FROM @INVESTIMENTI_TEMP INV	INNER JOIN DETTAGLIO_INVESTIMENTI DI ON (INV.ID_DETTAGLIO_INVESTIMENTO = DI.ID_DETTAGLIO_INVESTIMENTO)   
	WHERE DI.COD_DETTAGLIO IN( '5')
	
	IF @COSTO_INVESTIMENTI_SERVEST>(@COSTO_INVESTIMENTI*0.10) BEGIN
		SET @TIPO_RISULTATO='N'
		SET @MESSAGGIO_RISULTATO=@MESSAGGIO_RISULTATO+'<BR /> - Il costo per servizi esterni supera il 10% del costo del progetto.'
	END
END

------------------------------------------------------------------------------

-- 5.  Filiere 111 b) c noleggio o costo di reintegrazione attrezzature <= 10%
 
DECLARE @COSTO_INVESTIMENTI_NOLEGGIO DECIMAL(18,2)
 
IF @COSTO_INVESTIMENTI>0 BEGIN
	SELECT @COSTO_INVESTIMENTI_NOLEGGIO=SUM(IMPORTO_TOTALE_RENDICONTATO) 
	FROM @INVESTIMENTI_TEMP INV	INNER JOIN DETTAGLIO_INVESTIMENTI DI ON (INV.ID_DETTAGLIO_INVESTIMENTO = DI.ID_DETTAGLIO_INVESTIMENTO)   
	WHERE DI.COD_DETTAGLIO IN( '7')
	
	IF @COSTO_INVESTIMENTI_NOLEGGIO>(@COSTO_INVESTIMENTI*0.10) BEGIN
		SET @TIPO_RISULTATO='N'
		SET @MESSAGGIO_RISULTATO=@MESSAGGIO_RISULTATO+'<BR /> - Il costo per il noleggio o costo di reintegrazione attrezzature supera il 10% del costo del progetto.'
	END
END


------------------------------------------------------------------------------
-- Verifica totale investimenti in domanda minimo di 10.000,00 e massimo di 50.000,00 euro

DECLARE @COSTO_INVESTIMENTI_TOTALE DECIMAL(18,2)
SELECT @COSTO_INVESTIMENTI_TOTALE =SUM(IMPORTO_TOTALE_RENDICONTATO) FROM @INVESTIMENTI_TEMP WHERE COD_TIPO_INVESTIMENTO=1
IF @COSTO_INVESTIMENTI<10000 BEGIN
	SET @TIPO_RISULTATO='N'
	SET @MESSAGGIO_RISULTATO=@MESSAGGIO_RISULTATO+'<BR /> - L`ammontare rendicontato per il progetto deve essere superiore a 10.000 €.'
END

IF @COSTO_INVESTIMENTI>50000 BEGIN
	SET @TIPO_RISULTATO='N'
	SET @MESSAGGIO_RISULTATO=@MESSAGGIO_RISULTATO+'<BR /> - L`ammontare rendicontato per il progetto deve essere inferiore a 50.000 €.'
END



/*********************************************************************************************************/
IF @TIPO_RISULTATO='S' SET @MESSAGGIO_RISULTATO='VERIFICA DI AMMISSIBILITA DEGLI IMPORTI RENDICONTATI CONFERMATA'
ELSE SET @MESSAGGIO_RISULTATO='Si sono riscontrati i seguenti errori:'+@MESSAGGIO_RISULTATO
SELECT @TIPO_RISULTATO AS TIPO_RISULTATO, @MESSAGGIO_RISULTATO AS MESSAGGIO_RISULTATO
