CREATE PROCEDURE [dbo].[Z_CODIFICA_GENERICA_FIND_FTIPO]
(
	@ID_TIPO_CODIFICAEQUALTHIS INT
)
AS
	declare @sql nvarchar(4000);
	declare @lensql int;
	set @lensql=0;
	SET @sql = 'SELECT ID, ID_TIPO_CODIFICA, DESCRIZIONE, VALORE_TXT, CODICE_TXT, VALORE_INT1, VALORE_INT2, VALORE_DEC1, VALORE_DEC2, FLAG, DATA_INIZIO_VALIDITA, DATA_FINE_VALIDITA, ID_PADRE, VALORE_TXT2, VALORE_TXT3 FROM VCODIFICA_GENERICA WHERE 1=1';
	IF (@ID_TIPO_CODIFICAEQUALTHIS IS NOT NULL) BEGIN SET @sql = @sql + ' AND (ID_TIPO_CODIFICA = @ID_TIPO_CODIFICAEQUALTHIS)'; set @lensql=@lensql+len(@ID_TIPO_CODIFICAEQUALTHIS);end;
	set @sql = @sql + 'ORDER BY ID';
	set @lensql=@lensql+len(@sql);
	if (@lensql<3000)
	exec sp_executesql @sql,N'@ID_TIPO_CODIFICAEQUALTHIS INT',@ID_TIPO_CODIFICAEQUALTHIS ;
	else
		SELECT ID, ID_TIPO_CODIFICA, DESCRIZIONE, VALORE_TXT, CODICE_TXT, VALORE_INT1, VALORE_INT2, VALORE_DEC1, VALORE_DEC2, FLAG, DATA_INIZIO_VALIDITA, DATA_FINE_VALIDITA, ID_PADRE, VALORE_TXT2, VALORE_TXT3
		FROM VCODIFICA_GENERICA
		WHERE 
			((@ID_TIPO_CODIFICAEQUALTHIS IS NULL) OR ID_TIPO_CODIFICA = @ID_TIPO_CODIFICAEQUALTHIS)
		ORDER BY ID


GO
EXECUTE sp_addextendedproperty @name = N'backup', @value = NULL, @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'PROCEDURE', @level1name = N'Z_CODIFICA_GENERICA_FIND_FTIPO';

