CREATE PROCEDURE [dbo].[Z_CODIFICA_GENERICA_FIND_FIND]
(
	@ID_TIPO_CODIFICAEQUALTHIS INT, 
	@IDEQGREATERTHANTHIS INT, 
	@IDEQLESSTHANTHIS INT, 
	@DESCRIZIONELIKETHIS NVARCHAR(4000), 
	@FLAGLIKETHIS VARCHAR(255)
)
AS
	declare @sql nvarchar(4000);
	declare @lensql int;
	set @lensql=0;
	SET @sql = 'SELECT ID, ID_TIPO_CODIFICA, DESCRIZIONE, VALORE_TXT, CODICE_TXT, VALORE_INT1, VALORE_INT2, VALORE_DEC1, VALORE_DEC2, FLAG, DATA_INIZIO_VALIDITA, DATA_FINE_VALIDITA, ID_PADRE, VALORE_TXT2, VALORE_TXT3 FROM VCODIFICA_GENERICA WHERE 1=1';
	IF (@ID_TIPO_CODIFICAEQUALTHIS IS NOT NULL) BEGIN SET @sql = @sql + ' AND (ID_TIPO_CODIFICA = @ID_TIPO_CODIFICAEQUALTHIS)'; set @lensql=@lensql+len(@ID_TIPO_CODIFICAEQUALTHIS);end;
	IF (@IDEQGREATERTHANTHIS IS NOT NULL) BEGIN SET @sql = @sql + ' AND (ID >= @IDEQGREATERTHANTHIS)'; set @lensql=@lensql+len(@IDEQGREATERTHANTHIS);end;
	IF (@IDEQLESSTHANTHIS IS NOT NULL) BEGIN SET @sql = @sql + ' AND (ID <= @IDEQLESSTHANTHIS)'; set @lensql=@lensql+len(@IDEQLESSTHANTHIS);end;
	IF (@DESCRIZIONELIKETHIS IS NOT NULL) BEGIN SET @sql = @sql + ' AND (DESCRIZIONE LIKE @DESCRIZIONELIKETHIS)'; set @lensql=@lensql+len(@DESCRIZIONELIKETHIS);end;
	IF (@FLAGLIKETHIS IS NOT NULL) BEGIN SET @sql = @sql + ' AND (FLAG LIKE @FLAGLIKETHIS)'; set @lensql=@lensql+len(@FLAGLIKETHIS);end;
	set @sql = @sql + 'ORDER BY ID';
	set @lensql=@lensql+len(@sql);
	if (@lensql<3000)
	exec sp_executesql @sql,N'@ID_TIPO_CODIFICAEQUALTHIS INT, @IDEQGREATERTHANTHIS INT, @IDEQLESSTHANTHIS INT, @DESCRIZIONELIKETHIS NVARCHAR(4000), @FLAGLIKETHIS VARCHAR(255)',@ID_TIPO_CODIFICAEQUALTHIS , @IDEQGREATERTHANTHIS , @IDEQLESSTHANTHIS , @DESCRIZIONELIKETHIS , @FLAGLIKETHIS ;
	else
		SELECT ID, ID_TIPO_CODIFICA, DESCRIZIONE, VALORE_TXT, CODICE_TXT, VALORE_INT1, VALORE_INT2, VALORE_DEC1, VALORE_DEC2, FLAG, DATA_INIZIO_VALIDITA, DATA_FINE_VALIDITA, ID_PADRE, VALORE_TXT2, VALORE_TXT3
		FROM VCODIFICA_GENERICA
		WHERE 
			((@ID_TIPO_CODIFICAEQUALTHIS IS NULL) OR ID_TIPO_CODIFICA = @ID_TIPO_CODIFICAEQUALTHIS) AND 
			((@IDEQGREATERTHANTHIS IS NULL) OR ID >= @IDEQGREATERTHANTHIS) AND 
			((@IDEQLESSTHANTHIS IS NULL) OR ID <= @IDEQLESSTHANTHIS) AND 
			((@DESCRIZIONELIKETHIS IS NULL) OR DESCRIZIONE LIKE @DESCRIZIONELIKETHIS) AND 
			((@FLAGLIKETHIS IS NULL) OR FLAG LIKE @FLAGLIKETHIS)
		ORDER BY ID


GO
EXECUTE sp_addextendedproperty @name = N'backup', @value = NULL, @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'PROCEDURE', @level1name = N'Z_CODIFICA_GENERICA_FIND_FIND';

