
CREATE PROCEDURE [dbo].[ZBilancioIndustrialeUpdate]
(
	@IdBilancioIndustriale INT, 
	@IdImpresa INT, 
	@IdProgetto INT, 
	@Anno INT, 
	@DataBilancio DATETIME, 
	@Previsionale BIT, 
	@DataModifica DATETIME, 
	@PlvRicaviVendita DECIMAL(15,2), 
	@PlvAltriRicavi DECIMAL(15,2), 
	@CpMateriePrime DECIMAL(15,2), 
	@CpServizi DECIMAL(15,2), 
	@CpBeniTerzi DECIMAL(15,2), 
	@CpPersonale DECIMAL(15,2), 
	@CpAmmSvalutazioni DECIMAL(15,2), 
	@CpVarRimanenze DECIMAL(15,2), 
	@CpOneri DECIMAL(15,2), 
	@PofAltriProventi DECIMAL(15,2), 
	@PofInteressiOneri DECIMAL(15,2), 
	@RettValAttFinanziarie DECIMAL(15,2), 
	@PosProventiStraord DECIMAL(15,2), 
	@PosOneriStraord DECIMAL(15,2), 
	@TotPrimaImposte DECIMAL(15,2), 
	@ImposteReddito DECIMAL(15,2), 
	@TaCreditiSoci DECIMAL(15,2), 
	@TaImmImmateriali DECIMAL(15,2), 
	@TaImmobMateriali DECIMAL(15,2), 
	@TaImmPartecipazioni DECIMAL(15,2), 
	@TaImmCrediti DECIMAL(15,2), 
	@TaAcRimanenze DECIMAL(15,2), 
	@TaAcCreditiClienti DECIMAL(15,2), 
	@TaAcCreditiAltri DECIMAL(15,2), 
	@TaAcDepPostali DECIMAL(15,2), 
	@TaAcDispoLiquide DECIMAL(15,2), 
	@TaRateiRisconti DECIMAL(15,2), 
	@TpPnCapitale DECIMAL(15,2), 
	@TpPnSovrapAzioni DECIMAL(15,2), 
	@TpPnRisRivalutazione DECIMAL(15,2), 
	@TpPnRisLegale DECIMAL(15,2), 
	@TpPnAzioniProprie DECIMAL(15,2), 
	@TpPnRiserva904 DECIMAL(15,2), 
	@TpPnRiserveStatutarie DECIMAL(15,2), 
	@TpPnAltreRiserve DECIMAL(15,2), 
	@TpPnUtiliPrecedenti DECIMAL(15,2), 
	@TpPnUtiliEsercizio DECIMAL(15,2), 
	@TpFondiRischiOneri DECIMAL(15,2), 
	@TpFineRapporto DECIMAL(15,2), 
	@TpDebitiBanche DECIMAL(15,2), 
	@TpDebitiFinanziatori DECIMAL(15,2), 
	@TpDebitiFornitori DECIMAL(15,2), 
	@TpDebitiIstPrevid DECIMAL(15,2), 
	@TpAltriDebiti DECIMAL(15,2), 
	@TpRateiRisconti DECIMAL(15,2),
	@NotaIntegrativa varchar(MAX)
)
AS
	--SET @DataModifica=getdate()
	UPDATE BILANCIO_INDUSTRIALE
	SET
		ID_IMPRESA = @IdImpresa, 
		ID_PROGETTO = @IdProgetto, 
		ANNO = @Anno, 
		DATA_BILANCIO = @DataBilancio, 
		PREVISIONALE = @Previsionale, 
		DATA_MODIFICA = @DataModifica, 
		PLV_RICAVI_VENDITA = @PlvRicaviVendita, 
		PLV_ALTRI_RICAVI = @PlvAltriRicavi, 
		CP_MATERIE_PRIME = @CpMateriePrime, 
		CP_SERVIZI = @CpServizi, 
		CP_BENI_TERZI = @CpBeniTerzi, 
		CP_PERSONALE = @CpPersonale, 
		CP_AMM_SVALUTAZIONI = @CpAmmSvalutazioni, 
		CP_VAR_RIMANENZE = @CpVarRimanenze, 
		CP_ONERI = @CpOneri, 
		POF_ALTRI_PROVENTI = @PofAltriProventi, 
		POF_INTERESSI_ONERI = @PofInteressiOneri, 
		RETT_VAL_ATT_FINANZIARIE = @RettValAttFinanziarie, 
		POS_PROVENTI_STRAORD = @PosProventiStraord, 
		POS_ONERI_STRAORD = @PosOneriStraord, 
		TOT_PRIMA_IMPOSTE = @TotPrimaImposte, 
		IMPOSTE_REDDITO = @ImposteReddito, 
		TA_CREDITI_SOCI = @TaCreditiSoci, 
		TA_IMM_IMMATERIALI = @TaImmImmateriali, 
		TA_IMMOB_MATERIALI = @TaImmobMateriali, 
		TA_IMM_PARTECIPAZIONI = @TaImmPartecipazioni, 
		TA_IMM_CREDITI = @TaImmCrediti, 
		TA_AC_RIMANENZE = @TaAcRimanenze, 
		TA_AC_CREDITI_CLIENTI = @TaAcCreditiClienti, 
		TA_AC_CREDITI_ALTRI = @TaAcCreditiAltri, 
		TA_AC_DEP_POSTALI = @TaAcDepPostali, 
		TA_AC_DISPO_LIQUIDE = @TaAcDispoLiquide, 
		TA_RATEI_RISCONTI = @TaRateiRisconti, 
		TP_PN_CAPITALE = @TpPnCapitale, 
		TP_PN_SOVRAP_AZIONI = @TpPnSovrapAzioni, 
		TP_PN_RIS_RIVALUTAZIONE = @TpPnRisRivalutazione, 
		TP_PN_RIS_LEGALE = @TpPnRisLegale, 
		TP_PN_AZIONI_PROPRIE = @TpPnAzioniProprie, 
		TP_PN_RISERVA_904 = @TpPnRiserva904, 
		TP_PN_RISERVE_STATUTARIE = @TpPnRiserveStatutarie, 
		TP_PN_ALTRE_RISERVE = @TpPnAltreRiserve, 
		TP_PN_UTILI_PRECEDENTI = @TpPnUtiliPrecedenti, 
		TP_PN_UTILI_ESERCIZIO = @TpPnUtiliEsercizio, 
		TP_FONDI_RISCHI_ONERI = @TpFondiRischiOneri, 
		TP_FINE_RAPPORTO = @TpFineRapporto, 
		TP_DEBITI_BANCHE = @TpDebitiBanche, 
		TP_DEBITI_FINANZIATORI = @TpDebitiFinanziatori, 
		TP_DEBITI_FORNITORI = @TpDebitiFornitori, 
		TP_DEBITI_IST_PREVID = @TpDebitiIstPrevid, 
		TP_ALTRI_DEBITI = @TpAltriDebiti, 
		TP_RATEI_RISCONTI = @TpRateiRisconti,
		NOTA_INTEGRATIVA = @NotaIntegrativa
	WHERE 
		(ID_BILANCIO_INDUSTRIALE = @IdBilancioIndustriale)
	SELECT @DataModifica;

