
CREATE PROCEDURE [dbo].[ZBilancioIndustrialeInsert]
(
	@IdImpresa INT, 
	@IdProgetto INT, 
	@Anno INT, 
	@DataBilancio DATETIME, 
	@Previsionale BIT, 
	@DataModifica DATETIME, 
	@PlvRicaviVendita DECIMAL(15,2), 
	@PlvAltriRicavi DECIMAL(15,2), 
	@CpMateriePrime DECIMAL(15,2), 
	@CpServizi DECIMAL(15,2), 
	@CpBeniTerzi DECIMAL(15,2), 
	@CpPersonale DECIMAL(15,2), 
	@CpAmmSvalutazioni DECIMAL(15,2), 
	@CpVarRimanenze DECIMAL(15,2), 
	@CpOneri DECIMAL(15,2), 
	@PofAltriProventi DECIMAL(15,2), 
	@PofInteressiOneri DECIMAL(15,2), 
	@RettValAttFinanziarie DECIMAL(15,2), 
	@PosProventiStraord DECIMAL(15,2), 
	@PosOneriStraord DECIMAL(15,2), 
	@TotPrimaImposte DECIMAL(15,2), 
	@ImposteReddito DECIMAL(15,2), 
	@TaCreditiSoci DECIMAL(15,2), 
	@TaImmImmateriali DECIMAL(15,2), 
	@TaImmobMateriali DECIMAL(15,2), 
	@TaImmPartecipazioni DECIMAL(15,2), 
	@TaImmCrediti DECIMAL(15,2), 
	@TaAcRimanenze DECIMAL(15,2), 
	@TaAcCreditiClienti DECIMAL(15,2), 
	@TaAcCreditiAltri DECIMAL(15,2), 
	@TaAcDepPostali DECIMAL(15,2), 
	@TaAcDispoLiquide DECIMAL(15,2), 
	@TaRateiRisconti DECIMAL(15,2), 
	@TpPnCapitale DECIMAL(15,2), 
	@TpPnSovrapAzioni DECIMAL(15,2), 
	@TpPnRisRivalutazione DECIMAL(15,2), 
	@TpPnRisLegale DECIMAL(15,2), 
	@TpPnAzioniProprie DECIMAL(15,2), 
	@TpPnRiserva904 DECIMAL(15,2), 
	@TpPnRiserveStatutarie DECIMAL(15,2), 
	@TpPnAltreRiserve DECIMAL(15,2), 
	@TpPnUtiliPrecedenti DECIMAL(15,2), 
	@TpPnUtiliEsercizio DECIMAL(15,2), 
	@TpFondiRischiOneri DECIMAL(15,2), 
	@TpFineRapporto DECIMAL(15,2), 
	@TpDebitiBanche DECIMAL(15,2), 
	@TpDebitiFinanziatori DECIMAL(15,2), 
	@TpDebitiFornitori DECIMAL(15,2), 
	@TpDebitiIstPrevid DECIMAL(15,2), 
	@TpAltriDebiti DECIMAL(15,2), 
	@TpRateiRisconti DECIMAL(15,2),
	@NotaIntegrativa varchar(MAX)
)
AS
	INSERT INTO BILANCIO_INDUSTRIALE
	(
		ID_IMPRESA, 
		ID_PROGETTO, 
		ANNO, 
		DATA_BILANCIO, 
		PREVISIONALE, 
		DATA_MODIFICA, 
		PLV_RICAVI_VENDITA, 
		PLV_ALTRI_RICAVI, 
		CP_MATERIE_PRIME, 
		CP_SERVIZI, 
		CP_BENI_TERZI, 
		CP_PERSONALE, 
		CP_AMM_SVALUTAZIONI, 
		CP_VAR_RIMANENZE, 
		CP_ONERI, 
		POF_ALTRI_PROVENTI, 
		POF_INTERESSI_ONERI, 
		RETT_VAL_ATT_FINANZIARIE, 
		POS_PROVENTI_STRAORD, 
		POS_ONERI_STRAORD, 
		TOT_PRIMA_IMPOSTE, 
		IMPOSTE_REDDITO, 
		TA_CREDITI_SOCI, 
		TA_IMM_IMMATERIALI, 
		TA_IMMOB_MATERIALI, 
		TA_IMM_PARTECIPAZIONI, 
		TA_IMM_CREDITI, 
		TA_AC_RIMANENZE, 
		TA_AC_CREDITI_CLIENTI, 
		TA_AC_CREDITI_ALTRI, 
		TA_AC_DEP_POSTALI, 
		TA_AC_DISPO_LIQUIDE, 
		TA_RATEI_RISCONTI, 
		TP_PN_CAPITALE, 
		TP_PN_SOVRAP_AZIONI, 
		TP_PN_RIS_RIVALUTAZIONE, 
		TP_PN_RIS_LEGALE, 
		TP_PN_AZIONI_PROPRIE, 
		TP_PN_RISERVA_904, 
		TP_PN_RISERVE_STATUTARIE, 
		TP_PN_ALTRE_RISERVE, 
		TP_PN_UTILI_PRECEDENTI, 
		TP_PN_UTILI_ESERCIZIO, 
		TP_FONDI_RISCHI_ONERI, 
		TP_FINE_RAPPORTO, 
		TP_DEBITI_BANCHE, 
		TP_DEBITI_FINANZIATORI, 
		TP_DEBITI_FORNITORI, 
		TP_DEBITI_IST_PREVID, 
		TP_ALTRI_DEBITI, 
		TP_RATEI_RISCONTI,
		NOTA_INTEGRATIVA
	)
	VALUES
	(
		@IdImpresa, 
		@IdProgetto, 
		@Anno, 
		@DataBilancio, 
		@Previsionale, 
		@DataModifica, 
		@PlvRicaviVendita, 
		@PlvAltriRicavi, 
		@CpMateriePrime, 
		@CpServizi, 
		@CpBeniTerzi, 
		@CpPersonale, 
		@CpAmmSvalutazioni, 
		@CpVarRimanenze, 
		@CpOneri, 
		@PofAltriProventi, 
		@PofInteressiOneri, 
		@RettValAttFinanziarie, 
		@PosProventiStraord, 
		@PosOneriStraord, 
		@TotPrimaImposte, 
		@ImposteReddito, 
		@TaCreditiSoci, 
		@TaImmImmateriali, 
		@TaImmobMateriali, 
		@TaImmPartecipazioni, 
		@TaImmCrediti, 
		@TaAcRimanenze, 
		@TaAcCreditiClienti, 
		@TaAcCreditiAltri, 
		@TaAcDepPostali, 
		@TaAcDispoLiquide, 
		@TaRateiRisconti, 
		@TpPnCapitale, 
		@TpPnSovrapAzioni, 
		@TpPnRisRivalutazione, 
		@TpPnRisLegale, 
		@TpPnAzioniProprie, 
		@TpPnRiserva904, 
		@TpPnRiserveStatutarie, 
		@TpPnAltreRiserve, 
		@TpPnUtiliPrecedenti, 
		@TpPnUtiliEsercizio, 
		@TpFondiRischiOneri, 
		@TpFineRapporto, 
		@TpDebitiBanche, 
		@TpDebitiFinanziatori, 
		@TpDebitiFornitori, 
		@TpDebitiIstPrevid, 
		@TpAltriDebiti, 
		@TpRateiRisconti,
		@NotaIntegrativa
	)
	SELECT SCOPE_IDENTITY() AS ID_BILANCIO_INDUSTRIALE

