CREATE PROCEDURE [dbo].[ZDomandaDiPagamentoUpdate]
(
	@IdDomandaPagamento INT, 
	@CodTipo VARCHAR(255), 
	@IdProgetto INT, 
	@DataInserimento DATETIME, 
	@DataModifica DATETIME, 
	@CodEnte VARCHAR(255), 
	@Segnatura VARCHAR(255), 
	@IdFidejussione INT, 
	@CfOperatore VARCHAR(255), 
	@SegnaturaAllegati VARCHAR(255), 
	@DataCertificazioneAntimafia DATETIME, 
	@Approvata BIT, 
	@SegnaturaApprovazione VARCHAR(255), 
	@CfIstruttore VARCHAR(255), 
	@DataApprovazione DATETIME, 
	@SegnaturaSecondaApprovazione VARCHAR(255), 
	@Annullata BIT, 
	@SegnaturaAnnullamento VARCHAR(255), 
	@CfOperatoreAnnullamento VARCHAR(255), 
	@DataAnnullamento DATETIME, 
	@ValiditaVersioneAdc BIT, 
	@IdVariazioneAccertata INT, 
	@PredispostaAControllo BIT, 
	@VisitaInsituEsito VARCHAR(255), 
	@VisitaInsituNote NTEXT, 
	@ControlloInlocoEsito VARCHAR(255), 
	@ControlloInlocoNote NTEXT, 
	@ValutazioneIstruttore NTEXT, 
	@VerificaPagamentiEsito VARCHAR(255), 
	@VerificaPagamentiMessaggio VARCHAR(3000), 
	@VerificaPagamentiData DATETIME, 
	@DataPredisposizioneAControllo DATETIME, 
	@FirmaPredisposta BIT, 
	@InIntegrazione BIT, 
	@FirmaPredispostaRup BIT
)
AS
	UPDATE DOMANDA_DI_PAGAMENTO
	SET
		COD_TIPO = @CodTipo, 
		ID_PROGETTO = @IdProgetto, 
		DATA_INSERIMENTO = @DataInserimento, 
		DATA_MODIFICA = @DataModifica, 
		COD_ENTE = @CodEnte, 
		SEGNATURA = @Segnatura, 
		ID_FIDEJUSSIONE = @IdFidejussione, 
		CF_OPERATORE = @CfOperatore, 
		SEGNATURA_ALLEGATI = @SegnaturaAllegati, 
		DATA_CERTIFICAZIONE_ANTIMAFIA = @DataCertificazioneAntimafia, 
		APPROVATA = @Approvata, 
		SEGNATURA_APPROVAZIONE = @SegnaturaApprovazione, 
		CF_ISTRUTTORE = @CfIstruttore, 
		DATA_APPROVAZIONE = @DataApprovazione, 
		SEGNATURA_SECONDA_APPROVAZIONE = @SegnaturaSecondaApprovazione, 
		ANNULLATA = @Annullata, 
		SEGNATURA_ANNULLAMENTO = @SegnaturaAnnullamento, 
		CF_OPERATORE_ANNULLAMENTO = @CfOperatoreAnnullamento, 
		DATA_ANNULLAMENTO = @DataAnnullamento, 
		VALIDITA_VERSIONE_ADC = @ValiditaVersioneAdc, 
		ID_VARIAZIONE_ACCERTATA = @IdVariazioneAccertata, 
		PREDISPOSTA_A_CONTROLLO = @PredispostaAControllo, 
		VISITA_INSITU_ESITO = @VisitaInsituEsito, 
		VISITA_INSITU_NOTE = @VisitaInsituNote, 
		CONTROLLO_INLOCO_ESITO = @ControlloInlocoEsito, 
		CONTROLLO_INLOCO_NOTE = @ControlloInlocoNote, 
		VALUTAZIONE_ISTRUTTORE = @ValutazioneIstruttore, 
		VERIFICA_PAGAMENTI_ESITO = @VerificaPagamentiEsito, 
		VERIFICA_PAGAMENTI_MESSAGGIO = @VerificaPagamentiMessaggio, 
		VERIFICA_PAGAMENTI_DATA = @VerificaPagamentiData, 
		DATA_PREDISPOSIZIONE_A_CONTROLLO = @DataPredisposizioneAControllo, 
		FIRMA_PREDISPOSTA = @FirmaPredisposta, 
		IN_INTEGRAZIONE = @InIntegrazione, 
		FIRMA_PREDISPOSTA_RUP = @FirmaPredispostaRup
	WHERE 
		(ID_DOMANDA_PAGAMENTO = @IdDomandaPagamento)


GO
EXECUTE sp_addextendedproperty @name = N'backup', @value = 'CREATE PROCEDURE [dbo].[ZDomandaDiPagamentoUpdate]
(
	@IdDomandaPagamento INT, 
	@CodTipo VARCHAR(255), 
	@IdProgetto INT, 
	@DataInserimento DATETIME, 
	@DataModifica DATETIME, 
	@CodEnte VARCHAR(255), 
	@Segnatura VARCHAR(255), 
	@IdFidejussione INT, 
	@CfOperatore VARCHAR(255), 
	@SegnaturaAllegati VARCHAR(255), 
	@DataCertificazioneAntimafia DATETIME, 
	@Approvata BIT, 
	@SegnaturaApprovazione VARCHAR(255), 
	@CfIstruttore VARCHAR(255), 
	@DataApprovazione DATETIME, 
	@SegnaturaSecondaApprovazione VARCHAR(255), 
	@Annullata BIT, 
	@SegnaturaAnnullamento VARCHAR(255), 
	@CfOperatoreAnnullamento VARCHAR(255), 
	@DataAnnullamento DATETIME, 
	@ValiditaVersioneAdc BIT, 
	@IdVariazioneAccertata INT, 
	@PredispostaAControllo BIT, 
	@VisitaInsituEsito VARCHAR(255), 
	@VisitaInsituNote NTEXT, 
	@ControlloInlocoEsito VARCHAR(255), 
	@ControlloInlocoNote NTEXT, 
	@ValutazioneIstruttore NTEXT, 
	@VerificaPagamentiEsito VARCHAR(255), 
	@VerificaPagamentiMessaggio VARCHAR(3000), 
	@VerificaPagamentiData DATETIME, 
	@DataPredisposizioneAControllo DATETIME, 
	@FirmaPredisposta BIT, 
	@InIntegrazione BIT
)
AS
	UPDATE DOMANDA_DI_PAGAMENTO
	SET
		COD_TIPO = @CodTipo, 
		ID_PROGETTO = @IdProgetto, 
		DATA_INSERIMENTO = @DataInserimento, 
		DATA_MODIFICA = @DataModifica, 
		COD_ENTE = @CodEnte, 
		SEGNATURA = @Segnatura, 
		ID_FIDEJUSSIONE = @IdFidejussione, 
		CF_OPERATORE = @CfOperatore, 
		SEGNATURA_ALLEGATI = @SegnaturaAllegati, 
		DATA_CERTIFICAZIONE_ANTIMAFIA = @DataCertificazioneAntimafia, 
		APPROVATA = @Approvata, 
		SEGNATURA_APPROVAZIONE = @SegnaturaApprovazione, 
		CF_ISTRUTTORE = @CfIstruttore, 
		DATA_APPROVAZIONE = @DataApprovazione, 
		SEGNATURA_SECONDA_APPROVAZIONE = @SegnaturaSecondaApprovazione, 
		ANNULLATA = @Annullata, 
		SEGNATURA_ANNULLAMENTO = @SegnaturaAnnullamento, 
		CF_OPERATORE_ANNULLAMENTO = @CfOperatoreAnnullamento, 
		DATA_ANNULLAMENTO = @DataAnnullamento, 
		VALIDITA_VERSIONE_ADC = @ValiditaVersioneAdc, 
		ID_VARIAZIONE_ACCERTATA = @IdVariazioneAccertata, 
		PREDISPOSTA_A_CONTROLLO = @PredispostaAControllo, 
		VISITA_INSITU_ESITO = @VisitaInsituEsito, 
		VISITA_INSITU_NOTE = @VisitaInsituNote, 
		CONTROLLO_INLOCO_ESITO = @ControlloInlocoEsito, 
		CONTROLLO_INLOCO_NOTE = @ControlloInlocoNote, 
		VALUTAZIONE_ISTRUTTORE = @ValutazioneIstruttore, 
		VERIFICA_PAGAMENTI_ESITO = @VerificaPagamentiEsito, 
		VERIFICA_PAGAMENTI_MESSAGGIO = @VerificaPagamentiMessaggio, 
		VERIFICA_PAGAMENTI_DATA = @VerificaPagamentiData, 
		DATA_PREDISPOSIZIONE_A_CONTROLLO = @DataPredisposizioneAControllo, 
		FIRMA_PREDISPOSTA = @FirmaPredisposta, 
		IN_INTEGRAZIONE = @InIntegrazione
	WHERE 
		(ID_DOMANDA_PAGAMENTO = @IdDomandaPagamento)

', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'PROCEDURE', @level1name = N'ZDomandaDiPagamentoUpdate';

