CREATE PROCEDURE [dbo].[ZDomandaDiPagamentoFindFind]
(
	@IdDomandaPagamentoequalthis INT, 
	@CodTipoequalthis VARCHAR(255), 
	@IdProgettoequalthis INT, 
	@CodFaseequalthis VARCHAR(255)
)
AS
	declare @sql nvarchar(4000);
	declare @lensql int;
	set @lensql=0;
	SET @sql = 'SELECT ID_DOMANDA_PAGAMENTO, COD_TIPO, ID_PROGETTO, DATA_INSERIMENTO, DATA_MODIFICA, COD_ENTE, SEGNATURA, DESCRIZIONE, COD_FASE, FASE, ORDINE, ID_FIDEJUSSIONE, OPERATORE, CF_OPERATORE, SEGNATURA_ALLEGATI, DATA_CERTIFICAZIONE_ANTIMAFIA, APPROVATA, SEGNATURA_APPROVAZIONE, CF_ISTRUTTORE, DATA_APPROVAZIONE, SEGNATURA_SECONDA_APPROVAZIONE, ANNULLATA, SEGNATURA_ANNULLAMENTO, CF_OPERATORE_ANNULLAMENTO, DATA_ANNULLAMENTO, VALIDITA_VERSIONE_ADC, ID_VARIAZIONE_ACCERTATA, PREDISPOSTA_A_CONTROLLO, VISITA_INSITU_ESITO, VISITA_INSITU_NOTE, CONTROLLO_INLOCO_ESITO, CONTROLLO_INLOCO_NOTE, VALUTAZIONE_ISTRUTTORE, VERIFICA_PAGAMENTI_ESITO, VERIFICA_PAGAMENTI_MESSAGGIO, VERIFICA_PAGAMENTI_DATA, DATA_PREDISPOSIZIONE_A_CONTROLLO, NOMINATIVO_OPERATORE_ANNULLAMENTO, ISTRUTTORE, FIRMA_PREDISPOSTA, IN_INTEGRAZIONE, FIRMA_PREDISPOSTA_RUP FROM vDOMANDA_DI_PAGAMENTO WHERE 1=1';
	IF (@IdDomandaPagamentoequalthis IS NOT NULL) BEGIN SET @sql = @sql + ' AND (ID_DOMANDA_PAGAMENTO = @IdDomandaPagamentoequalthis)'; set @lensql=@lensql+len(@IdDomandaPagamentoequalthis);end;
	IF (@CodTipoequalthis IS NOT NULL) BEGIN SET @sql = @sql + ' AND (COD_TIPO = @CodTipoequalthis)'; set @lensql=@lensql+len(@CodTipoequalthis);end;
	IF (@IdProgettoequalthis IS NOT NULL) BEGIN SET @sql = @sql + ' AND (ID_PROGETTO = @IdProgettoequalthis)'; set @lensql=@lensql+len(@IdProgettoequalthis);end;
	IF (@CodFaseequalthis IS NOT NULL) BEGIN SET @sql = @sql + ' AND (COD_FASE = @CodFaseequalthis)'; set @lensql=@lensql+len(@CodFaseequalthis);end;
	set @sql = @sql + 'ORDER BY ORDINE';
	set @lensql=@lensql+len(@sql);
	if (@lensql<3000)
	exec sp_executesql @sql,N'@IdDomandaPagamentoequalthis INT, @CodTipoequalthis VARCHAR(255), @IdProgettoequalthis INT, @CodFaseequalthis VARCHAR(255)',@IdDomandaPagamentoequalthis , @CodTipoequalthis , @IdProgettoequalthis , @CodFaseequalthis ;
	else
		SELECT ID_DOMANDA_PAGAMENTO, COD_TIPO, ID_PROGETTO, DATA_INSERIMENTO, DATA_MODIFICA, COD_ENTE, SEGNATURA, DESCRIZIONE, COD_FASE, FASE, ORDINE, ID_FIDEJUSSIONE, OPERATORE, CF_OPERATORE, SEGNATURA_ALLEGATI, DATA_CERTIFICAZIONE_ANTIMAFIA, APPROVATA, SEGNATURA_APPROVAZIONE, CF_ISTRUTTORE, DATA_APPROVAZIONE, SEGNATURA_SECONDA_APPROVAZIONE, ANNULLATA, SEGNATURA_ANNULLAMENTO, CF_OPERATORE_ANNULLAMENTO, DATA_ANNULLAMENTO, VALIDITA_VERSIONE_ADC, ID_VARIAZIONE_ACCERTATA, PREDISPOSTA_A_CONTROLLO, VISITA_INSITU_ESITO, VISITA_INSITU_NOTE, CONTROLLO_INLOCO_ESITO, CONTROLLO_INLOCO_NOTE, VALUTAZIONE_ISTRUTTORE, VERIFICA_PAGAMENTI_ESITO, VERIFICA_PAGAMENTI_MESSAGGIO, VERIFICA_PAGAMENTI_DATA, DATA_PREDISPOSIZIONE_A_CONTROLLO, NOMINATIVO_OPERATORE_ANNULLAMENTO, ISTRUTTORE, FIRMA_PREDISPOSTA, IN_INTEGRAZIONE, FIRMA_PREDISPOSTA_RUP
		FROM vDOMANDA_DI_PAGAMENTO
		WHERE 
			((@IdDomandaPagamentoequalthis IS NULL) OR ID_DOMANDA_PAGAMENTO = @IdDomandaPagamentoequalthis) AND 
			((@CodTipoequalthis IS NULL) OR COD_TIPO = @CodTipoequalthis) AND 
			((@IdProgettoequalthis IS NULL) OR ID_PROGETTO = @IdProgettoequalthis) AND 
			((@CodFaseequalthis IS NULL) OR COD_FASE = @CodFaseequalthis)
		ORDER BY ORDINE


GO
EXECUTE sp_addextendedproperty @name = N'backup', @value = 'CREATE PROCEDURE [dbo].[ZDomandaDiPagamentoFindFind]
(
	@IdDomandaPagamentoequalthis INT, 
	@CodTipoequalthis VARCHAR(255), 
	@IdProgettoequalthis INT, 
	@CodFaseequalthis VARCHAR(255)
)
AS
	declare @sql nvarchar(4000);
	declare @lensql int;
	set @lensql=0;
	SET @sql = ''SELECT ID_DOMANDA_PAGAMENTO, COD_TIPO, ID_PROGETTO, DATA_INSERIMENTO, DATA_MODIFICA, COD_ENTE, SEGNATURA, DESCRIZIONE, COD_FASE, FASE, ORDINE, ID_FIDEJUSSIONE, OPERATORE, CF_OPERATORE, SEGNATURA_ALLEGATI, DATA_CERTIFICAZIONE_ANTIMAFIA, APPROVATA, SEGNATURA_APPROVAZIONE, CF_ISTRUTTORE, DATA_APPROVAZIONE, SEGNATURA_SECONDA_APPROVAZIONE, ANNULLATA, SEGNATURA_ANNULLAMENTO, CF_OPERATORE_ANNULLAMENTO, DATA_ANNULLAMENTO, VALIDITA_VERSIONE_ADC, ID_VARIAZIONE_ACCERTATA, PREDISPOSTA_A_CONTROLLO, VISITA_INSITU_ESITO, VISITA_INSITU_NOTE, CONTROLLO_INLOCO_ESITO, CONTROLLO_INLOCO_NOTE, VALUTAZIONE_ISTRUTTORE, VERIFICA_PAGAMENTI_ESITO, VERIFICA_PAGAMENTI_MESSAGGIO, VERIFICA_PAGAMENTI_DATA, DATA_PREDISPOSIZIONE_A_CONTROLLO, NOMINATIVO_OPERATORE_ANNULLAMENTO, ISTRUTTORE, FIRMA_PREDISPOSTA, IN_INTEGRAZIONE FROM vDOMANDA_DI_PAGAMENTO WHERE 1=1'';
	IF (@IdDomandaPagamentoequalthis IS NOT NULL) BEGIN SET @sql = @sql + '' AND (ID_DOMANDA_PAGAMENTO = @IdDomandaPagamentoequalthis)''; set @lensql=@lensql+len(@IdDomandaPagamentoequalthis);end;
	IF (@CodTipoequalthis IS NOT NULL) BEGIN SET @sql = @sql + '' AND (COD_TIPO = @CodTipoequalthis)''; set @lensql=@lensql+len(@CodTipoequalthis);end;
	IF (@IdProgettoequalthis IS NOT NULL) BEGIN SET @sql = @sql + '' AND (ID_PROGETTO = @IdProgettoequalthis)''; set @lensql=@lensql+len(@IdProgettoequalthis);end;
	IF (@CodFaseequalthis IS NOT NULL) BEGIN SET @sql = @sql + '' AND (COD_FASE = @CodFaseequalthis)''; set @lensql=@lensql+len(@CodFaseequalthis);end;
	set @sql = @sql + ''ORDER BY ORDINE'';
	set @lensql=@lensql+len(@sql);
	if (@lensql<3000)
	exec sp_executesql @sql,N''@IdDomandaPagamentoequalthis INT, @CodTipoequalthis VARCHAR(255), @IdProgettoequalthis INT, @CodFaseequalthis VARCHAR(255)'',@IdDomandaPagamentoequalthis , @CodTipoequalthis , @IdProgettoequalthis , @CodFaseequalthis ;
	else
		SELECT ID_DOMANDA_PAGAMENTO, COD_TIPO, ID_PROGETTO, DATA_INSERIMENTO, DATA_MODIFICA, COD_ENTE, SEGNATURA, DESCRIZIONE, COD_FASE, FASE, ORDINE, ID_FIDEJUSSIONE, OPERATORE, CF_OPERATORE, SEGNATURA_ALLEGATI, DATA_CERTIFICAZIONE_ANTIMAFIA, APPROVATA, SEGNATURA_APPROVAZIONE, CF_ISTRUTTORE, DATA_APPROVAZIONE, SEGNATURA_SECONDA_APPROVAZIONE, ANNULLATA, SEGNATURA_ANNULLAMENTO, CF_OPERATORE_ANNULLAMENTO, DATA_ANNULLAMENTO, VALIDITA_VERSIONE_ADC, ID_VARIAZIONE_ACCERTATA, PREDISPOSTA_A_CONTROLLO, VISITA_INSITU_ESITO, VISITA_INSITU_NOTE, CONTROLLO_INLOCO_ESITO, CONTROLLO_INLOCO_NOTE, VALUTAZIONE_ISTRUTTORE, VERIFICA_PAGAMENTI_ESITO, VERIFICA_PAGAMENTI_MESSAGGIO, VERIFICA_PAGAMENTI_DATA, DATA_PREDISPOSIZIONE_A_CONTROLLO, NOMINATIVO_OPERATORE_ANNULLAMENTO, ISTRUTTORE, FIRMA_PREDISPOSTA, IN_INTEGRAZIONE
		FROM vDOMANDA_DI_PAGAMENTO
		WHERE 
			((@IdDomandaPagamentoequalthis IS NULL) OR ID_DOMANDA_PAGAMENTO = @IdDomandaPagamentoequalthis) AND 
			((@CodTipoequalthis IS NULL) OR COD_TIPO = @CodTipoequalthis) AND 
			((@IdProgettoequalthis IS NULL) OR ID_PROGETTO = @IdProgettoequalthis) AND 
			((@CodFaseequalthis IS NULL) OR COD_FASE = @CodFaseequalthis)
		ORDER BY ORDINE

', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'PROCEDURE', @level1name = N'ZDomandaDiPagamentoFindFind';

