CREATE PROCEDURE [dbo].[ZDomandaDiPagamentoInsert]
(
	@CodTipo VARCHAR(255), 
	@IdProgetto INT, 
	@DataInserimento DATETIME, 
	@DataModifica DATETIME, 
	@CodEnte VARCHAR(255), 
	@Segnatura VARCHAR(255), 
	@IdFidejussione INT, 
	@CfOperatore VARCHAR(255), 
	@SegnaturaAllegati VARCHAR(255), 
	@DataCertificazioneAntimafia DATETIME, 
	@Approvata BIT, 
	@SegnaturaApprovazione VARCHAR(255), 
	@CfIstruttore VARCHAR(255), 
	@DataApprovazione DATETIME, 
	@SegnaturaSecondaApprovazione VARCHAR(255), 
	@Annullata BIT, 
	@SegnaturaAnnullamento VARCHAR(255), 
	@CfOperatoreAnnullamento VARCHAR(255), 
	@DataAnnullamento DATETIME, 
	@ValiditaVersioneAdc BIT, 
	@IdVariazioneAccertata INT, 
	@PredispostaAControllo BIT, 
	@VisitaInsituEsito VARCHAR(255), 
	@VisitaInsituNote NTEXT, 
	@ControlloInlocoEsito VARCHAR(255), 
	@ControlloInlocoNote NTEXT, 
	@ValutazioneIstruttore NTEXT, 
	@VerificaPagamentiEsito VARCHAR(255), 
	@VerificaPagamentiMessaggio VARCHAR(3000), 
	@VerificaPagamentiData DATETIME, 
	@DataPredisposizioneAControllo DATETIME, 
	@FirmaPredisposta BIT, 
	@InIntegrazione BIT, 
	@FirmaPredispostaRup BIT
)
AS
	SET @Annullata = ISNULL(@Annullata,((0)))
	SET @ValiditaVersioneAdc = ISNULL(@ValiditaVersioneAdc,((0)))
	SET @PredispostaAControllo = ISNULL(@PredispostaAControllo,((0)))
	SET @FirmaPredisposta = ISNULL(@FirmaPredisposta,((0)))
	SET @InIntegrazione = ISNULL(@InIntegrazione,((0)))
	INSERT INTO DOMANDA_DI_PAGAMENTO
	(
		COD_TIPO, 
		ID_PROGETTO, 
		DATA_INSERIMENTO, 
		DATA_MODIFICA, 
		COD_ENTE, 
		SEGNATURA, 
		ID_FIDEJUSSIONE, 
		CF_OPERATORE, 
		SEGNATURA_ALLEGATI, 
		DATA_CERTIFICAZIONE_ANTIMAFIA, 
		APPROVATA, 
		SEGNATURA_APPROVAZIONE, 
		CF_ISTRUTTORE, 
		DATA_APPROVAZIONE, 
		SEGNATURA_SECONDA_APPROVAZIONE, 
		ANNULLATA, 
		SEGNATURA_ANNULLAMENTO, 
		CF_OPERATORE_ANNULLAMENTO, 
		DATA_ANNULLAMENTO, 
		VALIDITA_VERSIONE_ADC, 
		ID_VARIAZIONE_ACCERTATA, 
		PREDISPOSTA_A_CONTROLLO, 
		VISITA_INSITU_ESITO, 
		VISITA_INSITU_NOTE, 
		CONTROLLO_INLOCO_ESITO, 
		CONTROLLO_INLOCO_NOTE, 
		VALUTAZIONE_ISTRUTTORE, 
		VERIFICA_PAGAMENTI_ESITO, 
		VERIFICA_PAGAMENTI_MESSAGGIO, 
		VERIFICA_PAGAMENTI_DATA, 
		DATA_PREDISPOSIZIONE_A_CONTROLLO, 
		FIRMA_PREDISPOSTA, 
		IN_INTEGRAZIONE, 
		FIRMA_PREDISPOSTA_RUP
	)
	VALUES
	(
		@CodTipo, 
		@IdProgetto, 
		@DataInserimento, 
		@DataModifica, 
		@CodEnte, 
		@Segnatura, 
		@IdFidejussione, 
		@CfOperatore, 
		@SegnaturaAllegati, 
		@DataCertificazioneAntimafia, 
		@Approvata, 
		@SegnaturaApprovazione, 
		@CfIstruttore, 
		@DataApprovazione, 
		@SegnaturaSecondaApprovazione, 
		@Annullata, 
		@SegnaturaAnnullamento, 
		@CfOperatoreAnnullamento, 
		@DataAnnullamento, 
		@ValiditaVersioneAdc, 
		@IdVariazioneAccertata, 
		@PredispostaAControllo, 
		@VisitaInsituEsito, 
		@VisitaInsituNote, 
		@ControlloInlocoEsito, 
		@ControlloInlocoNote, 
		@ValutazioneIstruttore, 
		@VerificaPagamentiEsito, 
		@VerificaPagamentiMessaggio, 
		@VerificaPagamentiData, 
		@DataPredisposizioneAControllo, 
		@FirmaPredisposta, 
		@InIntegrazione, 
		@FirmaPredispostaRup
	)
	SELECT SCOPE_IDENTITY() AS ID_DOMANDA_PAGAMENTO, @Annullata AS ANNULLATA, @ValiditaVersioneAdc AS VALIDITA_VERSIONE_ADC, @PredispostaAControllo AS PREDISPOSTA_A_CONTROLLO, @FirmaPredisposta AS FIRMA_PREDISPOSTA, @InIntegrazione AS IN_INTEGRAZIONE


GO
EXECUTE sp_addextendedproperty @name = N'backup', @value = 'CREATE PROCEDURE [dbo].[ZDomandaDiPagamentoInsert]
(
	@CodTipo VARCHAR(255), 
	@IdProgetto INT, 
	@DataInserimento DATETIME, 
	@DataModifica DATETIME, 
	@CodEnte VARCHAR(255), 
	@Segnatura VARCHAR(255), 
	@IdFidejussione INT, 
	@CfOperatore VARCHAR(255), 
	@SegnaturaAllegati VARCHAR(255), 
	@DataCertificazioneAntimafia DATETIME, 
	@Approvata BIT, 
	@SegnaturaApprovazione VARCHAR(255), 
	@CfIstruttore VARCHAR(255), 
	@DataApprovazione DATETIME, 
	@SegnaturaSecondaApprovazione VARCHAR(255), 
	@Annullata BIT, 
	@SegnaturaAnnullamento VARCHAR(255), 
	@CfOperatoreAnnullamento VARCHAR(255), 
	@DataAnnullamento DATETIME, 
	@ValiditaVersioneAdc BIT, 
	@IdVariazioneAccertata INT, 
	@PredispostaAControllo BIT, 
	@VisitaInsituEsito VARCHAR(255), 
	@VisitaInsituNote NTEXT, 
	@ControlloInlocoEsito VARCHAR(255), 
	@ControlloInlocoNote NTEXT, 
	@ValutazioneIstruttore NTEXT, 
	@VerificaPagamentiEsito VARCHAR(255), 
	@VerificaPagamentiMessaggio VARCHAR(3000), 
	@VerificaPagamentiData DATETIME, 
	@DataPredisposizioneAControllo DATETIME, 
	@FirmaPredisposta BIT, 
	@InIntegrazione BIT
)
AS
	SET @Annullata = ISNULL(@Annullata,((0)))
	SET @ValiditaVersioneAdc = ISNULL(@ValiditaVersioneAdc,((0)))
	SET @PredispostaAControllo = ISNULL(@PredispostaAControllo,((0)))
	SET @InIntegrazione = ISNULL(@InIntegrazione,((0)))
	INSERT INTO DOMANDA_DI_PAGAMENTO
	(
		COD_TIPO, 
		ID_PROGETTO, 
		DATA_INSERIMENTO, 
		DATA_MODIFICA, 
		COD_ENTE, 
		SEGNATURA, 
		ID_FIDEJUSSIONE, 
		CF_OPERATORE, 
		SEGNATURA_ALLEGATI, 
		DATA_CERTIFICAZIONE_ANTIMAFIA, 
		APPROVATA, 
		SEGNATURA_APPROVAZIONE, 
		CF_ISTRUTTORE, 
		DATA_APPROVAZIONE, 
		SEGNATURA_SECONDA_APPROVAZIONE, 
		ANNULLATA, 
		SEGNATURA_ANNULLAMENTO, 
		CF_OPERATORE_ANNULLAMENTO, 
		DATA_ANNULLAMENTO, 
		VALIDITA_VERSIONE_ADC, 
		ID_VARIAZIONE_ACCERTATA, 
		PREDISPOSTA_A_CONTROLLO, 
		VISITA_INSITU_ESITO, 
		VISITA_INSITU_NOTE, 
		CONTROLLO_INLOCO_ESITO, 
		CONTROLLO_INLOCO_NOTE, 
		VALUTAZIONE_ISTRUTTORE, 
		VERIFICA_PAGAMENTI_ESITO, 
		VERIFICA_PAGAMENTI_MESSAGGIO, 
		VERIFICA_PAGAMENTI_DATA, 
		DATA_PREDISPOSIZIONE_A_CONTROLLO, 
		FIRMA_PREDISPOSTA, 
		IN_INTEGRAZIONE
	)
	VALUES
	(
		@CodTipo, 
		@IdProgetto, 
		@DataInserimento, 
		@DataModifica, 
		@CodEnte, 
		@Segnatura, 
		@IdFidejussione, 
		@CfOperatore, 
		@SegnaturaAllegati, 
		@DataCertificazioneAntimafia, 
		@Approvata, 
		@SegnaturaApprovazione, 
		@CfIstruttore, 
		@DataApprovazione, 
		@SegnaturaSecondaApprovazione, 
		@Annullata, 
		@SegnaturaAnnullamento, 
		@CfOperatoreAnnullamento, 
		@DataAnnullamento, 
		@ValiditaVersioneAdc, 
		@IdVariazioneAccertata, 
		@PredispostaAControllo, 
		@VisitaInsituEsito, 
		@VisitaInsituNote, 
		@ControlloInlocoEsito, 
		@ControlloInlocoNote, 
		@ValutazioneIstruttore, 
		@VerificaPagamentiEsito, 
		@VerificaPagamentiMessaggio, 
		@VerificaPagamentiData, 
		@DataPredisposizioneAControllo, 
		@FirmaPredisposta, 
		@InIntegrazione
	)
	SELECT SCOPE_IDENTITY() AS ID_DOMANDA_PAGAMENTO, @Annullata AS ANNULLATA, @ValiditaVersioneAdc AS VALIDITA_VERSIONE_ADC, @PredispostaAControllo AS PREDISPOSTA_A_CONTROLLO, @InIntegrazione AS IN_INTEGRAZIONE

', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'PROCEDURE', @level1name = N'ZDomandaDiPagamentoInsert';

