CREATE PROCEDURE [dbo].[ZFidejussioniFindFind]
(
	@Numeroequalthis VARCHAR(25), 
	@Barcodeequalthis VARCHAR(11), 
	@PivaGaranteequalthis VARCHAR(11)
)
AS
	declare @sql nvarchar(4000);
	declare @lensql int;
	set @lensql=0;
	SET @sql = 'SELECT ID_FIDEJUSSIONE, NUMERO, BARCODE, DATA_SOTTOSCRIZIONE, LUOGO_SOTTOSCRIZIONE, IMPORTO, AMMONTARE_RICHIESTO, DATA_FINE_LAVORI, DATA_SCADENZA, PROROGA_SCADENZA, PIVA_GARANTE, RAGIONE_SOCIALE_GARANTE, LOCALITA_GARANTE, NUMERO_REGISTRO_IMPRESE, COGNOME_RAPPLEGALE, NOME_RAPPLEGALE, CF_RAPPLEGALE, DATA_NASCITA_RAPPLEGALE, STAMPA_EFFETTUATA, DATA_RICHIESTA_VALIDITA, DATA_RICEVIMENTO_VALIDITA, PROTOCOLLO_FAX_VALIDITA, DATA_DECORRENZA_GARANZIA, CODICE_ABI_ENTE_GARANTE, CODICE_CAB_ENTE_GARANTE, BARCODE_CONFERMA_VALIDITA, COD_TIPO, UFFICIO_APPROVAZIONE, NUM_DECRETO_APPROVAZIONE, DATA_DECRETO_APPROVAZIONE FROM FIDEJUSSIONI WHERE 1=1';
	IF (@Numeroequalthis IS NOT NULL) BEGIN SET @sql = @sql + ' AND (NUMERO = @Numeroequalthis)'; set @lensql=@lensql+len(@Numeroequalthis);end;
	IF (@Barcodeequalthis IS NOT NULL) BEGIN SET @sql = @sql + ' AND (BARCODE = @Barcodeequalthis)'; set @lensql=@lensql+len(@Barcodeequalthis);end;
	IF (@PivaGaranteequalthis IS NOT NULL) BEGIN SET @sql = @sql + ' AND (PIVA_GARANTE = @PivaGaranteequalthis)'; set @lensql=@lensql+len(@PivaGaranteequalthis);end;
	set @lensql=@lensql+len(@sql);
	if (@lensql<3000)
	exec sp_executesql @sql,N'@Numeroequalthis VARCHAR(25), @Barcodeequalthis VARCHAR(11), @PivaGaranteequalthis VARCHAR(11)',@Numeroequalthis , @Barcodeequalthis , @PivaGaranteequalthis ;
	else
		SELECT ID_FIDEJUSSIONE, NUMERO, BARCODE, DATA_SOTTOSCRIZIONE, LUOGO_SOTTOSCRIZIONE, IMPORTO, AMMONTARE_RICHIESTO, DATA_FINE_LAVORI, DATA_SCADENZA, PROROGA_SCADENZA, PIVA_GARANTE, RAGIONE_SOCIALE_GARANTE, LOCALITA_GARANTE, NUMERO_REGISTRO_IMPRESE, COGNOME_RAPPLEGALE, NOME_RAPPLEGALE, CF_RAPPLEGALE, DATA_NASCITA_RAPPLEGALE, STAMPA_EFFETTUATA, DATA_RICHIESTA_VALIDITA, DATA_RICEVIMENTO_VALIDITA, PROTOCOLLO_FAX_VALIDITA, DATA_DECORRENZA_GARANZIA, CODICE_ABI_ENTE_GARANTE, CODICE_CAB_ENTE_GARANTE, BARCODE_CONFERMA_VALIDITA, COD_TIPO, UFFICIO_APPROVAZIONE, NUM_DECRETO_APPROVAZIONE, DATA_DECRETO_APPROVAZIONE
		FROM FIDEJUSSIONI
		WHERE 
			((@Numeroequalthis IS NULL) OR NUMERO = @Numeroequalthis) AND 
			((@Barcodeequalthis IS NULL) OR BARCODE = @Barcodeequalthis) AND 
			((@PivaGaranteequalthis IS NULL) OR PIVA_GARANTE = @PivaGaranteequalthis)

GO
EXECUTE sp_addextendedproperty @name = N'backup', @value = N'CREATE PROCEDURE [dbo].[ZFidejussioniFindFind]
(
	@Numeroequalthis VARCHAR(25), 
	@Barcodeequalthis VARCHAR(11), 
	@PivaGaranteequalthis VARCHAR(11)
)
AS
	declare @sql nvarchar(4000);
	declare @lensql int;
	set @lensql=0;
	SET @sql = ''SELECT ID_FIDEJUSSIONE, NUMERO, BARCODE, DATA_SOTTOSCRIZIONE, LUOGO_SOTTOSCRIZIONE, IMPORTO, AMMONTARE_RICHIESTO, DATA_FINE_LAVORI, DATA_SCADENZA, PROROGA_SCADENZA, PIVA_GARANTE, RAGIONE_SOCIALE_GARANTE, LOCALITA_GARANTE, NUMERO_REGISTRO_IMPRESE, COGNOME_RAPPLEGALE, NOME_RAPPLEGALE, CF_RAPPLEGALE, DATA_NASCITA_RAPPLEGALE, STAMPA_EFFETTUATA, DATA_RICHIESTA_VALIDITA, DATA_RICEVIMENTO_VALIDITA, PROTOCOLLO_FAX_VALIDITA, DATA_DECORRENZA_GARANZIA, CODICE_ABI_ENTE_GARANTE, CODICE_CAB_ENTE_GARANTE, BARCODE_CONFERMA_VALIDITA, COD_TIPO FROM FIDEJUSSIONI WHERE 1=1'';
	IF (@Numeroequalthis IS NOT NULL) BEGIN SET @sql = @sql + '' AND (NUMERO = @Numeroequalthis)''; set @lensql=@lensql+len(@Numeroequalthis);end;
	IF (@Barcodeequalthis IS NOT NULL) BEGIN SET @sql = @sql + '' AND (BARCODE = @Barcodeequalthis)''; set @lensql=@lensql+len(@Barcodeequalthis);end;
	IF (@PivaGaranteequalthis IS NOT NULL) BEGIN SET @sql = @sql + '' AND (PIVA_GARANTE = @PivaGaranteequalthis)''; set @lensql=@lensql+len(@PivaGaranteequalthis);end;
	set @lensql=@lensql+len(@sql);
	if (@lensql<3000)
	exec sp_executesql @sql,N''@Numeroequalthis VARCHAR(25), @Barcodeequalthis VARCHAR(11), @PivaGaranteequalthis VARCHAR(11)'',@Numeroequalthis , @Barcodeequalthis , @PivaGaranteequalthis ;
	else
		SELECT ID_FIDEJUSSIONE, NUMERO, BARCODE, DATA_SOTTOSCRIZIONE, LUOGO_SOTTOSCRIZIONE, IMPORTO, AMMONTARE_RICHIESTO, DATA_FINE_LAVORI, DATA_SCADENZA, PROROGA_SCADENZA, PIVA_GARANTE, RAGIONE_SOCIALE_GARANTE, LOCALITA_GARANTE, NUMERO_REGISTRO_IMPRESE, COGNOME_RAPPLEGALE, NOME_RAPPLEGALE, CF_RAPPLEGALE, DATA_NASCITA_RAPPLEGALE, STAMPA_EFFETTUATA, DATA_RICHIESTA_VALIDITA, DATA_RICEVIMENTO_VALIDITA, PROTOCOLLO_FAX_VALIDITA, DATA_DECORRENZA_GARANZIA, CODICE_ABI_ENTE_GARANTE, CODICE_CAB_ENTE_GARANTE, BARCODE_CONFERMA_VALIDITA, COD_TIPO
		FROM FIDEJUSSIONI
		WHERE 
			((@Numeroequalthis IS NULL) OR NUMERO = @Numeroequalthis) AND 
			((@Barcodeequalthis IS NULL) OR BARCODE = @Barcodeequalthis) AND 
			((@PivaGaranteequalthis IS NULL) OR PIVA_GARANTE = @PivaGaranteequalthis)
		

', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'PROCEDURE', @level1name = N'ZFidejussioniFindFind';

