
CREATE PROCEDURE [dbo].[ZGanttBandoInsert]
(
	@oggetto varchar(500), 
	@importo decimal(18,2), 
	@IMPORTO_PREVISTO decimal(18,2), 
	@IMPORTO_FINANZIATO decimal(18,2), 
	@IMPORTO_CERTIFICATO decimal(18,2), 
	@ID_PROGRAMMAZIONE INT 
)
AS
	INSERT INTO GANTT_BANDO
	(
		OGGETTO, 
		IMPORTO,
		IMPORTO_PREVISTO,
		IMPORTO_FINANZIATO,
		IMPORTO_CERTIFICATO,
		ID_PROGRAMMAZIONE
	)
	VALUES
	(
		@oggetto, 
		@importo, 
		@IMPORTO_PREVISTO,
		@IMPORTO_FINANZIATO,
		@IMPORTO_CERTIFICATO,
		@ID_PROGRAMMAZIONE
	)

