CREATE PROCEDURE [dbo].[zIgrueInsertMonitFN02]
( 
 @DataDa DATETIME,
 @DataA DATETIME,
 @IdInvio INT,
 @rNumber INT
)
AS
BEGIN

INSERT INTO IGRUE_MONIT.dbo.IGRUE_FN02
(
COD_LOCALE_PROGETTO,
VOCE_SPESA,
IMPORTO,
FLG_CANCELLAZIONE,
--OPERAZIONE,
ID_INVIO,
NR_RIGA_INVIO,
--NR_RIGA_CANCELLAZIONE
CODICE_FONDO
)

SELECT 
P.ID_PROGETTO AS COD_LOCALE_PROGETTO,
--VPI.CODICE AS VOCE_SPESA, --VERIFICARE TC37
--VPI.CONTRIBUTO_RICHIESTO AS IMPORTO,
VPA.VOCE_SPESA AS VOCE_SPESA, --VERIFICARE TC37
VPA.IMPORTO_AMMESSO AS IMPORTO,
NULL AS FLG_CANCELLAZIONE,
@IdInvio AS ID_INVIO,
ISNULL(@rNumber,0) + ROW_NUMBER() OVER(ORDER BY P.ID_PROGETTO ASC) AS NR_RIGA_INVIO,
'FESR20142020' AS CODICE_FONDO   
FROM vPROGETTO P 
INNER JOIN vBANDO B ON
P.ID_BANDO = B.ID_BANDO
INNER JOIN BANDO_PROGRAMMAZIONE BP ON
B.ID_BANDO = BP.ID_BANDO
INNER JOIN zPROGRAMMAZIONE PRG ON
BP.ID_PROGRAMMAZIONE = PRG.ID
INNER JOIN zPSR_ALBERO PA ON
PRG.COD_TIPO = PA.CODICE
INNER JOIN zPSR PSR ON
PA.COD_PSR = PSR.CODICE
INNER JOIN 
(
	SELECT 
	VP.ID_PROGETTO,
	--VP.ID_INVESTIMENTO,
	--CASE WHEN VP.COD_STP = '00' THEN VIC2.VOCE_SPESA ELSE VIC.VOCE_SPESA END VOCE_SPESA,
	VIC2.VOCE_SPESA,
	--VP.CONTRIBUTO_RICHIESTO,
	--DMF.CUP_NATURA,
	--VIC.CODICE_NATURA_CUP,
	--VIC.VOCE_SPESA,
	--vic.DESCRIZIONE_VOCE_SPESA
	--SUM(VP.CONTRIBUTO_RICHIESTO) AS IMPORTO_AMMESSO
	SUM(ISNULL(VP.COSTO_INVESTIMENTO,0)) AS IMPORTO_AMMESSO
	FROM
	vPIANO_INVESTIMENTI VP
	INNER JOIN DATI_MONITORAGGIO_FESR DMF ON
	VP.ID_PROGETTO = DMF.ID_PROGETTO 
	LEFT OUTER JOIN vIGRUE_VOCI_SPESA VIC ON 
	DMF.CUP_NATURA = VIC.CODICE_NATURA_CUP
	AND VP.COD_STP = VIC.VOCE_SPESA
	LEFT OUTER JOIN 
	(
		SELECT 
		VIC1.CODICE_NATURA_CUP, 
		VIC1.VOCE_SPESA 
		FROM 
		vIGRUE_VOCI_SPESA VIC1 
		WHERE 
		VIC1.DESCRIZIONE_VOCE_SPESA = 'Altro'
	) VIC2 ON
	DMF.CUP_NATURA = VIC2.CODICE_NATURA_CUP
	WHERE
	--VP.ISTRUTTORE IS NOT NULL
	--AND 
	VP.ID_INVESTIMENTO_ORIGINALE IS NOT NULL
	AND
	VP.ID_VARIANTE IS NULL
	--AND
	--VP.AMMESSO = 1
	--AND
	--VP.ID_PROGETTO = 10286
	GROUP BY 
	VP.ID_PROGETTO,
	--VP.COD_STP,
	--VIC.VOCE_SPESA,
	VIC2.VOCE_SPESA
) VPA ON 
P.ID_PROGETTO = VPA.ID_PROGETTO
--vPIANO_INVESTIMENTI VPI ON
--P.ID_PROGETTO = VPI.ID_PROGETTO
--AND 
--VPI.ISTRUTTORE IS NOT NULL
--AND 
--VPI.ID_INVESTIMENTO_ORIGINALE IS NOT NULL
--AND
--VPI.AMMESSO = 1 
WHERE 
P.COD_STATO IN ('F','V','S','O','T','X','C','Y','E','R') 
AND 
PSR.CODICE = 'POR20142020'
AND PRG.ID NOT IN (17,18,19)
AND 
BP.ID_PROGRAMMAZIONE NOT IN (17,18,19)
AND
P.COD_AGEA IS NOT NULL
--26/01/2018
--CLAUSOLA TEMPORANEA PER ESCLUDERE PROGETTO STRUMENTI FINANZIARI ARTIGIANCASSA
AND P.ID_PROGETTO <> 13301


--SELECT 
--P.ID_PROGETTO AS COD_LOCALE_PROGETTO,
--VPI.CODICE AS VOCE_SPESA, --VERIFICARE TC37
--VPI.CONTRIBUTO_RICHIESTO AS IMPORTO,
--NULL AS FLG_CANCELLAZIONE,
--@IdInvio AS ID_INVIO,
--ISNULL(@rNumber,0) + ROW_NUMBER() OVER(ORDER BY P.ID_PROGETTO ASC) AS NR_RIGA_INVIO,
--'FESR20142020' AS CODICE_FONDO   
--FROM vPROGETTO P 
--INNER JOIN vBANDO B ON
--P.ID_BANDO = B.ID_BANDO
--INNER JOIN BANDO_PROGRAMMAZIONE BP ON
--B.ID_BANDO = BP.ID_BANDO
--INNER JOIN zPROGRAMMAZIONE PRG ON
--BP.ID_PROGRAMMAZIONE = PRG.ID
--INNER JOIN zPSR_ALBERO PA ON
--PRG.COD_TIPO = PA.CODICE
--INNER JOIN zPSR PSR ON
--PA.COD_PSR = PSR.CODICE
--INNER JOIN vPIANO_INVESTIMENTI VPI ON
--P.ID_PROGETTO = VPI.ID_PROGETTO
--AND 
--VPI.ISTRUTTORE IS NOT NULL
--AND 
--VPI.ID_INVESTIMENTO_ORIGINALE IS NOT NULL
--AND
--VPI.AMMESSO = 1 
--WHERE 
--P.COD_STATO IN ('F','V','S','O','T','X','C','Y','E','R') 
--AND 
--PSR.CODICE = 'POR20142020'
--AND PRG.ID NOT IN (17,18,19)
--AND
--P.COD_AGEA IS NOT NULL


SELECT ISNULL(MAX(NR_RIGA_INVIO),0) FROM IGRUE_MONIT.dbo.IGRUE_FN02 WHERE ID_INVIO = @IdInvio

END
