CREATE PROCEDURE [dbo].[zIgrueInsertMonitAP04]
( 
 @DataDa DATETIME,
 @DataA DATETIME,
 @IdInvio INT,
 @rNumber INT
)
AS
BEGIN
INSERT INTO IGRUE_MONIT.dbo.IGRUE_AP04
(
COD_LOCALE_PROGETTO,
COD_PROGRAMMA,
STATO,
SPECIFICA_STATO,
--OPERAZIONE,
ID_INVIO,
NR_RIGA_INVIO,
--NR_RIGA_CANCELLAZIONE
CODICE_FONDO
)
SELECT 
P.ID_PROGETTO AS COD_LOCALE_PROGETTO,
'2014IT16RFOP013' AS COD_PROGRAMMA, 
CASE WHEN P.COD_STATO IN ('Y','E','R') THEN '2' 
ELSE '1'
END AS STATO,
CASE P.COD_STATO
WHEN 'R' THEN '4'
WHEN 'E' THEN '3'
WHEN 'Y' THEN '3'
ELSE NULL END AS SPECIFICA_STATO,
@IdInvio AS ID_INVIO,
ISNULL(@rNumber,0) + ROW_NUMBER() OVER(ORDER BY P.ID_PROGETTO ASC) AS NR_RIGA_INVIO,
'FESR20142020' AS CODICE_FONDO  
FROM vPROGETTO P
INNER JOIN vBANDO B ON
P.ID_BANDO = B.ID_BANDO
--INNER JOIN PROGETTO_STORICO PS ON
--P.ID_PROGETTO = PS.ID_PROGETTO
INNER JOIN zPROGRAMMAZIONE PRG ON
B.ID_PROGRAMMAZIONE = PRG.ID
INNER JOIN zPSR_ALBERO PA ON
PRG.COD_TIPO = PA.CODICE
INNER JOIN zPSR PSR ON
PA.COD_PSR = PSR.CODICE
--INNER JOIN BANDO_RESPONSABILI BR ON
--B.ID_BANDO = BR.ID_BANDO
WHERE 
P.COD_STATO IN ('F','V','S','O','T','X','C','Y','E','R') 
AND 
PSR.CODICE = 'POR20142020'
AND
P.COD_AGEA IS NOT NULL
--26/01/2018
--CLAUSOLA TEMPORANEA PER ESCLUDERE PROGETTO STRUMENTI FINANZIARI ARTIGIANCASSA
AND P.ID_PROGETTO <> 13301

--AND
--BR.ATTIVO = 1 AND BR.PROVINCIA IS NULL
--AND
--B.DATA_SCADENZA BETWEEN @DataDa AND @DataA

SELECT ISNULL(MAX(NR_RIGA_INVIO),0) FROM IGRUE_MONIT.dbo.IGRUE_AP04 WHERE ID_INVIO = @IdInvio

END


