CREATE PROCEDURE [dbo].[zIgrueInsertMonitFN06]
( 
 @DataDa DATETIME,
 @DataA DATETIME,
 @IdInvio INT,
 @rNumber INT
)
AS
BEGIN

WITH DECRETI_X_DOM_PAG_ESPORTAZIONE2 AS
(
	SELECT 
APE.ID_DECRETO,
APE.ID_DOMANDA_PAGAMENTO,
DP1.COD_TIPO,
APE.ID_PROGETTO,
DM.CUP_NATURA,
APE.IMPORTO
FROM 
DECRETI_X_DOM_PAG_ESPORTAZIONE APE
INNER JOIN 
DOMANDA_DI_PAGAMENTO_ESPORTAZIONE PE ON
APE.ID_DOMANDA_PAGAMENTO = PE.ID_DOMANDA_PAGAMENTO
INNER JOIN 
DATI_MONITORAGGIO_FESR DM ON
PE.ID_PROGETTO = DM.ID_PROGETTO
INNER JOIN 
DOMANDA_DI_PAGAMENTO DP1 ON
PE.ID_DOMANDA_PAGAMENTO = DP1.ID_DOMANDA_PAGAMENTO
WHERE NOT EXISTS
(
	SELECT 
	MIN(APE2.ID_DECRETO),
	APE2.ID_DOMANDA_PAGAMENTO,
	APE2.ID_PROGETTO
	FROM 
	DECRETI_X_DOM_PAG_ESPORTAZIONE APE2
	INNER JOIN 
	DATI_MONITORAGGIO_FESR DMFR ON
	APE2.ID_PROGETTO = DMFR.ID_PROGETTO
	INNER JOIN 
	DOMANDA_DI_PAGAMENTO DP ON
	APE2.ID_DOMANDA_PAGAMENTO = DP.ID_DOMANDA_PAGAMENTO
	WHERE 
	(
	 (DMFR.CUP_NATURA <> '07')
	  OR
	 (DMFR.CUP_NATURA <> '07' AND DP.COD_TIPO = 'ANT')
	)
	AND 
	DP.APPROVATA = 1
	AND 
	APE.ID_DOMANDA_PAGAMENTO = APE2.ID_DOMANDA_PAGAMENTO
	GROUP BY 
	APE2.ID_PROGETTO,
	APE2.ID_DOMANDA_PAGAMENTO
)

UNION 

SELECT 
	MIN(APE2.ID_DECRETO) ID_DECRETO,
	APE2.ID_DOMANDA_PAGAMENTO,
	DP.COD_TIPO,
	APE2.ID_PROGETTO,
	DMFR.CUP_NATURA,
	CASE WHEN DP.COD_TIPO = 'ANT' THEN
	SUM(APE2.IMPORTO) 
	ELSE 
	PRB.IMPORTO_AMMESSO END
	AS IMPORTO
	--NULL AS IMPORTO--APE2.IMPORTO  
	FROM 
	DECRETI_X_DOM_PAG_ESPORTAZIONE APE2
	INNER JOIN 
	DATI_MONITORAGGIO_FESR DMFR ON
	APE2.ID_PROGETTO = DMFR.ID_PROGETTO
	INNER JOIN 
	DOMANDA_DI_PAGAMENTO DP ON
	APE2.ID_DOMANDA_PAGAMENTO = DP.ID_DOMANDA_PAGAMENTO
	LEFT OUTER JOIN 
	(
		SELECT 
		PR.ID_DOMANDA_PAGAMENTO,
		SUM(ISNULL(PR.IMPORTO_AMMESSO,0)) AS IMPORTO_AMMESSO,
		SUM(ISNULL(PR.CONTRIBUTO_AMMESSO,0)) AS CONTRIBUTO_AMMESSO
		FROM 
		PAGAMENTI_RICHIESTI PR
		WHERE PR.IMPORTO_AMMESSO IS NOT NULL
		GROUP BY 
		PR.ID_DOMANDA_PAGAMENTO
	) PRB ON
	APE2.ID_DOMANDA_PAGAMENTO = PRB.ID_DOMANDA_PAGAMENTO
	WHERE 
	(
	 (DMFR.CUP_NATURA <> '07')
	  OR
	 (DMFR.CUP_NATURA <> '07' AND DP.COD_TIPO = 'ANT')
	)
	AND 
	DP.APPROVATA = 1
	--AND 
	--APE.ID_DOMANDA_PAGAMENTO = APE2.ID_DOMANDA_PAGAMENTO
	GROUP BY 
	APE2.ID_PROGETTO,
	DP.COD_TIPO,
	APE2.ID_DOMANDA_PAGAMENTO,
	DMFR.CUP_NATURA,
	PRB.IMPORTO_AMMESSO
	--APE2.IMPORTO
)

INSERT INTO IGRUE_MONIT.dbo.IGRUE_FN06
(
COD_LOCALE_PROGETTO,
COD_PAGAMENTO,
TIPOLOGIA_PAG,
DATA_PAGAMENTO,
IMPORTO_PAG,
CAUSALE_PAGAMENTO,
NOTE_PAG,
FLG_CANCELLAZIONE,
--OPERAZIONE,
ID_INVIO,
NR_RIGA_INVIO,
--NR_RIGA_CANCELLAZIONE
CODICE_FONDO
)

SELECT
P.ID_PROGETTO AS COD_LOCALE_PROGETTO,
--DPE.ID_DOMANDA_PAGAMENTO,
ATTI.NUMERO AS COD_PAGAMENTO, --VERIFICARE PRESENZA CAMPO
--'P' AS TIPOLOGIA_PAG, --VERIFICARE PRESENZA CAMPO
CASE WHEN BCA.VALORE = '04' THEN 'P-TR'
ELSE 
'P' END AS TIPOLOGIA_PAG,
--DMFR.CUP_NATURA,
dbo.DateToString_Igrue(ATTI.DATA) AS DATA_PAGAMENTO,  --VERIFICARE PRESENZA CAMPO
CASE 
WHEN DMFR.CUP_NATURA = '07' THEN DDPE.IMPORTO
WHEN DMFR.CUP_NATURA <> '07' AND DP.COD_TIPO='ANT' THEN DDPE.IMPORTO
ELSE PRB.IMPORTO_AMMESSO END AS IMPORTO_PAG,
--DDPE.IMPORTO,
--DPE.IMPORTO_AMMESSO,
--PRB.IMPORTO_AMMESSO PRB_IMPORTO_AMMESSO,
CASE DP.COD_TIPO 
WHEN 'ANT' THEN 'ANT'
WHEN 'SAL' THEN 'INT'
WHEN 'SLD' THEN 'SLD' END AS CAUSALE_PAG, -- VERIFICARE TC39
NULL AS NOTE_PAG,
NULL AS FLG_CANCELLAZIONE,
@IdInvio AS ID_INVIO,
ISNULL(@rNumber,0) + ROW_NUMBER() OVER(ORDER BY P.ID_PROGETTO ASC) AS NR_RIGA_INVIO,
'FESR20142020' AS CODICE_FONDO   
FROM vPROGETTO P 
INNER JOIN vBANDO B ON
P.ID_BANDO = B.ID_BANDO
INNER JOIN zPROGRAMMAZIONE PRG ON
B.ID_PROGRAMMAZIONE = PRG.ID
INNER JOIN zPSR_ALBERO PA ON
PRG.COD_TIPO = PA.CODICE
INNER JOIN zPSR PSR ON
PA.COD_PSR = PSR.CODICE
INNER JOIN DOMANDA_DI_PAGAMENTO_ESPORTAZIONE DPE ON
P.ID_PROGETTO = DPE.ID_PROGETTO
INNER JOIN DOMANDA_DI_PAGAMENTO DP ON
DPE.ID_DOMANDA_PAGAMENTO = DP.ID_DOMANDA_PAGAMENTO
AND
DP.APPROVATA = 1
AND 
DP.SEGNATURA IS NOT NULL
LEFT OUTER JOIN BANDO_CONFIG BCA ON
B.ID_BANDO = BCA.ID_BANDO 
AND 
BCA.COD_TIPO = 'TPAPPALTO'
AND 
BCA.ATTIVO = 1 
AND 
BCA.VALORE = '04'
LEFT OUTER JOIN 
(
	SELECT 
	PR.ID_DOMANDA_PAGAMENTO,
	SUM(ISNULL(PR.IMPORTO_AMMESSO,0)) AS IMPORTO_AMMESSO,
	SUM(ISNULL(PR.CONTRIBUTO_AMMESSO,0)) AS CONTRIBUTO_AMMESSO
	FROM 
	PAGAMENTI_RICHIESTI PR
	WHERE PR.IMPORTO_AMMESSO IS NOT NULL
	GROUP BY 
	PR.ID_DOMANDA_PAGAMENTO
) PRB ON
DPE.ID_DOMANDA_PAGAMENTO = PRB.ID_DOMANDA_PAGAMENTO
LEFT OUTER JOIN 
DECRETI_X_DOM_PAG_ESPORTAZIONE2 DDPE ON
DPE.ID_DOMANDA_PAGAMENTO = DDPE.ID_DOMANDA_PAGAMENTO
LEFT OUTER JOIN 
ATTI ON 
DDPE.ID_DECRETO = ATTI.ID_ATTO
LEFT OUTER JOIN
DATI_MONITORAGGIO_FESR DMFR ON
P.ID_PROGETTO = DMFR.ID_PROGETTO
WHERE 
P.COD_STATO IN ('F','V','S','O','T','X','C','Y','E','R') 
AND 
PSR.CODICE = 'POR20142020'
AND PRG.ID NOT IN (17,18,19)
AND
P.COD_AGEA IS NOT NULL
--26/01/2018
--CLAUSOLA TEMPORANEA PER ESCLUDERE PROGETTO STRUMENTI FINANZIARI ARTIGIANCASSA
AND P.ID_PROGETTO <> 13301
--CLAUSOLA TEMPORANEA PER TEST INVIO IGRUE
--AND ATTI.ID_ATTO IS NOT NULL 
AND DDPE.ID_DECRETO IS NOT NULL


SELECT ISNULL(MAX(NR_RIGA_INVIO),0) FROM IGRUE_MONIT.dbo.IGRUE_FN06 WHERE ID_INVIO = @IdInvio

END

--SELECT
--P.ID_PROGETTO AS COD_LOCALE_PROGETTO,
----CASE 
----WHEN DMFR.CUP_NATURA = '07' THEN ATTI.NUMERO
----ELSE DPE.ID_DOMANDA_PAGAMENTO END AS COD_PAGAMENTO, 
--ATTI.NUMERO AS COD_PAGAMENTO, --VERIFICARE PRESENZA CAMPO
--'P' AS TIPOLOGIA_PAG, --VERIFICARE PRESENZA CAMPO
----CASE 
----WHEN DMFR.CUP_NATURA = '07' THEN dbo.DateToString_Igrue(ATTI.DATA)
----ELSE dbo.DateToString_Igrue(DP.DATA_APPROVAZIONE) END AS DATA_PAGAMENTO,  --VERIFICARE PRESENZA CAMPO
--dbo.DateToString_Igrue(ATTI.DATA) AS DATA_PAGAMENTO,  --VERIFICARE PRESENZA CAMPO
--CASE 
--WHEN DMFR.CUP_NATURA = '07' THEN DPE.IMPORTO_AMMESSO
--WHEN DMFR.CUP_NATURA <> '07' AND DP.COD_TIPO='ANT' THEN DPE.IMPORTO_AMMESSO
--ELSE PRB.IMPORTO_AMMESSO END AS IMPORTO_PAG,
----DPE.IMPORTO_AMMESSO AS IMPORTO_PAG,
----PRB.IMPORTO_AMMESSO,
----DMFR.CUP_NATURA,
----DP.APPROVATA,
--CASE DP.COD_TIPO 
--WHEN 'ANT' THEN 'ANT'
--WHEN 'SAL' THEN 'INT'
--WHEN 'SLD' THEN 'SLD' END AS CAUSALE_PAG, -- VERIFICARE TC39
--NULL AS NOTE_PAG,
--NULL AS FLG_CANCELLAZIONE,
--@IdInvio AS ID_INVIO,
--ISNULL(@rNumber,0) + ROW_NUMBER() OVER(ORDER BY P.ID_PROGETTO ASC) AS NR_RIGA_INVIO,
--'FESR20142020' AS CODICE_FONDO   
--FROM vPROGETTO P 
--INNER JOIN vBANDO B ON
--P.ID_BANDO = B.ID_BANDO
----INNER JOIN BANDO_PROGRAMMAZIONE BP ON
----B.ID_BANDO = BP.ID_BANDO
--INNER JOIN zPROGRAMMAZIONE PRG ON
--B.ID_PROGRAMMAZIONE = PRG.ID
--INNER JOIN zPSR_ALBERO PA ON
--PRG.COD_TIPO = PA.CODICE
--INNER JOIN zPSR PSR ON
--PA.COD_PSR = PSR.CODICE
--INNER JOIN DOMANDA_DI_PAGAMENTO_ESPORTAZIONE DPE ON
--P.ID_PROGETTO = DPE.ID_PROGETTO
--INNER JOIN DOMANDA_DI_PAGAMENTO DP ON
--DPE.ID_DOMANDA_PAGAMENTO = DP.ID_DOMANDA_PAGAMENTO
--AND
--DP.APPROVATA = 1
--AND 
--DP.SEGNATURA IS NOT NULL
--LEFT OUTER JOIN 
--(
--	SELECT 
--	PR.ID_DOMANDA_PAGAMENTO,
--	SUM(ISNULL(PR.IMPORTO_AMMESSO,0)) AS IMPORTO_AMMESSO,
--	SUM(ISNULL(PR.CONTRIBUTO_AMMESSO,0)) AS CONTRIBUTO_AMMESSO
--	FROM 
--	PAGAMENTI_RICHIESTI PR
--	WHERE PR.IMPORTO_AMMESSO IS NOT NULL
--	GROUP BY 
--	PR.ID_DOMANDA_PAGAMENTO
--) PRB ON
--DPE.ID_DOMANDA_PAGAMENTO = PRB.ID_DOMANDA_PAGAMENTO
--LEFT OUTER JOIN 
--ATTI ON 
--DPE.ID_DECRETO = ATTI.ID_ATTO
--LEFT OUTER JOIN
--DATI_MONITORAGGIO_FESR DMFR ON
--P.ID_PROGETTO = DMFR.ID_PROGETTO
----AND 
----VPR.ISTRUTTORE IS NOT NULL
----AND 
----VPR.ID_INVESTIMENTO_ORIGINALE IS NOT NULL
----AND
----VPR.AMMESSO = 1 
--WHERE 
--P.COD_STATO IN ('F','V','S','O','T','X','C','Y','E','R') 
--AND 
--PSR.CODICE = 'POR20142020'
--AND PRG.ID NOT IN (17,18,19)
--AND
--P.COD_AGEA IS NOT NULL
----26/01/2018
----CLAUSOLA TEMPORANEA PER ESCLUDERE PROGETTO STRUMENTI FINANZIARI ARTIGIANCASSA
--AND P.ID_PROGETTO <> 13301
----CLAUSOLA TEMPORANEA PER TEST INVIO IGRUE
----AND ATTI.ID_ATTO IS NOT NULL 
--AND DPE.ID_DECRETO IS NOT NULL



--SELECT
--P.ID_PROGETTO AS COD_LOCALE_PROGETTO,
--ATTI.NUMERO AS COD_PAGAMENTO, --VERIFICARE PRESENZA CAMPO
--'P' AS TIPOLOGIA_PAG, --VERIFICARE PRESENZA CAMPO
--dbo.DateToString_Igrue(ATTI.DATA) AS DATA_PAGAMENTO,  --VERIFICARE PRESENZA CAMPO
--DPE.IMPORTO_AMMESSO AS IMPORTO_PAG,
----DP.APPROVATA,
--CASE DP.COD_TIPO 
--WHEN 'ANT' THEN 'ANT'
--WHEN 'SAL' THEN 'INT'
--WHEN 'SLD' THEN 'SLD' END AS CAUSALE_PAG, -- VERIFICARE TC39
--NULL AS NOTE_PAG,
--NULL AS FLG_CANCELLAZIONE,
--@IdInvio AS ID_INVIO,
--ISNULL(@rNumber,0) + ROW_NUMBER() OVER(ORDER BY P.ID_PROGETTO ASC) AS NR_RIGA_INVIO,
--'FESR20142020' AS CODICE_FONDO   
--FROM vPROGETTO P 
--INNER JOIN vBANDO B ON
--P.ID_BANDO = B.ID_BANDO
----INNER JOIN BANDO_PROGRAMMAZIONE BP ON
----B.ID_BANDO = BP.ID_BANDO
--INNER JOIN zPROGRAMMAZIONE PRG ON
--B.ID_PROGRAMMAZIONE = PRG.ID
--INNER JOIN zPSR_ALBERO PA ON
--PRG.COD_TIPO = PA.CODICE
--INNER JOIN zPSR PSR ON
--PA.COD_PSR = PSR.CODICE
--INNER JOIN DOMANDA_DI_PAGAMENTO_ESPORTAZIONE DPE ON
--P.ID_PROGETTO = DPE.ID_PROGETTO
--INNER JOIN DOMANDA_DI_PAGAMENTO DP ON
--DPE.ID_DOMANDA_PAGAMENTO = DP.ID_DOMANDA_PAGAMENTO
--AND
--DP.APPROVATA = 1
--AND 
--DP.SEGNATURA IS NOT NULL
--LEFT OUTER JOIN 
--ATTI ON 
--DPE.ID_DECRETO = ATTI.ID_ATTO
----AND 
----VPR.ISTRUTTORE IS NOT NULL
----AND 
----VPR.ID_INVESTIMENTO_ORIGINALE IS NOT NULL
----AND
----VPR.AMMESSO = 1 
--WHERE 
--P.COD_STATO IN ('F','V','S','O','T','X','C','Y','E','R') 
--AND 
--PSR.CODICE = 'POR20142020'
--AND PRG.ID NOT IN (17,18,19)
--AND
--P.COD_AGEA IS NOT NULL
----CLAUSOLA TEMPORANEA PER TEST INVIO IGRUE
--AND ATTI.ID_ATTO IS NOT NULL
----AND
----BR.ATTIVO = 1 AND BR.PROVINCIA IS NULL
----AND
----B.DATA_SCADENZA BETWEEN @DataDa AND @DataA


