CREATE PROCEDURE [dbo].[zIgrueInsertMonitFN04]
( 
 @DataDa DATETIME,
 @DataA DATETIME,
 @IdInvio INT,
 @rNumber INT
)
AS
BEGIN

WITH VPA AS (

SELECT 
	VPI.ID_PROGETTO,
	SUM(VPI.CONTRIBUTO_RICHIESTO) AS IMPORTO 
	FROM 
	vPIANO_INVESTIMENTI VPI
	WHERE 
	VPI.ID_INVESTIMENTO_ORIGINALE IS NOT NULL
	AND
	VPI.ID_VARIANTE IS NULL
	--AND
	--VPI.AMMESSO = 1
	GROUP BY VPI.ID_PROGETTO
)

INSERT INTO IGRUE_MONIT.dbo.IGRUE_FN04
(
COD_LOCALE_PROGETTO,
COD_IMPEGNO,
TIPOLOGIA_IMPEGNO,
DATA_IMPEGNO,
IMPORTO_IMPEGNO,
CAUSALE_DISIMPEGNO,
NOTE_IMPEGNO,
FLG_CANCELLAZIONE,
--OPERAZIONE,
ID_INVIO,
NR_RIGA_INVIO,
--NR_RIGA_CANCELLAZIONE
CODICE_FONDO
)

SELECT 
P.ID_PROGETTO AS COD_LOCALE_PROGETTO,
--B.ID_BANDO,
--BC.COD_TIPO,
--NULL AS COD_IMPEGNO, --VERIFICARE PRESENZA CAMPO
CASE WHEN BC.COD_TIPO IS NOT NULL 
THEN 
ATTI_P.NUMERO --AS COD_IMPEGNO,
ELSE 
ATTI_B.NUMERO END AS COD_IMPEGNO,
--ATTI_B.NUMERO AS COD_IMPEGNO_B,
--ATTI_P.NUMERO AS COD_IMPEGNO_P,
--P.COD_STATO,
--'I' AS TIPOLOGIA_IMPEGNO, --NULL AS TIPOLOGIA_IMPEGNO, --VERIFICARE PRESENZA CAMPO
CASE WHEN BCA.VALORE = '04' THEN 'I-TR'
ELSE 
'I' END AS TIPOLOGIA_IMPEGNO, --NULL AS TIPOLOGIA_IMPEGNO, --VERIFICARE PRESENZA CAMPO
--NULL AS DATA_IMPEGNO,  --VERIFICARE PRESENZA CAMPO
CASE WHEN BC.COD_TIPO IS NOT NULL 
THEN 
dbo.DateToString_Igrue(ATTI_P.DATA)--AS DATA_IMPEGNO,
ELSE
dbo.DateToString_Igrue(ATTI_B.DATA) END AS DATA_IMPEGNO,
--ELSE 
--dbo.DateToString_Igrue(ATTI_P.DATA) END AS DATA_IMPEGNO,
--GPR.CONTRIBUTO_TOTALE AS IMPORTO_IMPEGNO,
VPA.IMPORTO AS IMPORTO_IMPEGNO,
NULL AS CAUSALE_DISIMPEGNO, --VERIFICARE TC38
NULL AS NOTE_IMPEGNO,
NULL AS FLG_CANCELLAZIONE,
@IdInvio AS ID_INVIO,
ISNULL(@rNumber,0) + ROW_NUMBER() OVER(ORDER BY P.ID_PROGETTO ASC) AS NR_RIGA_INVIO,
'FESR20142020' AS CODICE_FONDO   
FROM vPROGETTO P 
INNER JOIN vBANDO B ON
P.ID_BANDO = B.ID_BANDO
--INNER JOIN BANDO_PROGRAMMAZIONE BP ON
--B.ID_BANDO = BP.ID_BANDO
INNER JOIN zPROGRAMMAZIONE PRG ON
B.ID_PROGRAMMAZIONE = PRG.ID
INNER JOIN zPSR_ALBERO PA ON
PRG.COD_TIPO = PA.CODICE
INNER JOIN zPSR PSR ON
PA.COD_PSR = PSR.CODICE
--LEFT JOIN vPAGAMENTI_RICHIESTI VPR ON
LEFT OUTER JOIN GRADUATORIA_PROGETTI GPR ON
P.ID_PROGETTO = GPR.ID_PROGETTO
LEFT OUTER JOIN BANDO_CONFIG BC ON
B.ID_BANDO = BC.ID_BANDO 
AND 
BC.COD_TIPO = 'ATTGRADBLOCCHI'
AND 
BC.ATTIVO = 1
LEFT OUTER JOIN BANDO_CONFIG BCA ON
B.ID_BANDO = BCA.ID_BANDO 
AND 
BCA.COD_TIPO = 'TPAPPALTO'
AND 
BCA.ATTIVO = 1 
AND 
BCA.VALORE = '04'
LEFT OUTER JOIN 
(
	SELECT 
	BS.ID_BANDO,
	MAX(BS.ID_ATTO) ID_ATTO
	FROM BANDO_STORICO BS 
	WHERE BS.COD_STATO = 'G'
	GROUP BY ID_BANDO) GB ON
	B.ID_BANDO = GB.ID_BANDO
	LEFT OUTER JOIN ATTI ATTI_B ON 
	GB.ID_ATTO = ATTI_B.ID_ATTO
	LEFT OUTER JOIN 
	(
		SELECT 
		PS.ID_PROGETTO,
		MAX(PS.ID_ATTO) ID_ATTO
		FROM PROGETTO_STORICO PS 
		WHERE PS.COD_STATO = 'F'
		GROUP BY ID_PROGETTO
	) GP ON
P.ID_PROGETTO = GP.ID_PROGETTO
LEFT OUTER JOIN ATTI ATTI_P ON
GP.ID_ATTO = ATTI_P.ID_ATTO
--AND 
--VPR.ISTRUTTORE IS NOT NULL
--AND 
--VPR.ID_INVESTIMENTO_ORIGINALE IS NOT NULL
--AND
--VPR.AMMESSO = 1 
LEFT OUTER JOIN VPA ON
P.ID_PROGETTO = VPA.ID_PROGETTO
WHERE 
P.COD_STATO IN ('F','V','S','O','T','X','C','Y','E','R') 
AND 
PSR.CODICE = 'POR20142020'
AND PRG.ID NOT IN (17,18,19)
AND
P.COD_AGEA IS NOT NULL
--26/01/2018
--CLAUSOLA TEMPORANEA PER ESCLUDERE PROGETTO STRUMENTI FINANZIARI ARTIGIANCASSA
AND P.ID_PROGETTO <> 13301
--CLAUSOLA TEMPORANEA PER TEST INVIO IGRUE
AND 
(COALESCE(ATTI_B.ID_ATTO, ATTI_P.ID_ATTO) IS NOT NULL)
--AND 
--GPR.CONTRIBUTO_TOTALE IS NOT NULL

SELECT ISNULL(MAX(NR_RIGA_INVIO),0) FROM IGRUE_MONIT.dbo.IGRUE_FN04 WHERE ID_INVIO = @IdInvio

END

--INSERT INTO IGRUE_MONIT.dbo.IGRUE_FN04
--(
--COD_LOCALE_PROGETTO,
--COD_IMPEGNO,
--TIPOLOGIA_IMPEGNO,
--DATA_IMPEGNO,
--IMPORTO_IMPEGNO,
--CAUSALE_DISIMPEGNO,
--NOTE_IMPEGNO,
--FLG_CANCELLAZIONE,
----OPERAZIONE,
--ID_INVIO,
--NR_RIGA_INVIO,
----NR_RIGA_CANCELLAZIONE
--CODICE_FONDO
--)


--SELECT 
--P.ID_PROGETTO AS COD_LOCALE_PROGETTO,
----B.ID_BANDO,
----BC.COD_TIPO,
----NULL AS COD_IMPEGNO, --VERIFICARE PRESENZA CAMPO
--CASE WHEN BC.COD_TIPO IS NOT NULL 
--THEN 
--ATTI_P.NUMERO --AS COD_IMPEGNO,
--ELSE 
--ATTI_B.NUMERO END AS COD_IMPEGNO,
----ATTI_B.NUMERO AS COD_IMPEGNO_B,
----ATTI_P.NUMERO AS COD_IMPEGNO_P,
----P.COD_STATO,
--'I' AS TIPOLOGIA_IMPEGNO, --NULL AS TIPOLOGIA_IMPEGNO, --VERIFICARE PRESENZA CAMPO
----NULL AS DATA_IMPEGNO,  --VERIFICARE PRESENZA CAMPO
--CASE WHEN BC.COD_TIPO IS NOT NULL 
--THEN 
--dbo.DateToString_Igrue(ATTI_P.DATA)--AS DATA_IMPEGNO,
--ELSE
--dbo.DateToString_Igrue(ATTI_B.DATA) END AS DATA_IMPEGNO,
----ELSE 
----dbo.DateToString_Igrue(ATTI_P.DATA) END AS DATA_IMPEGNO,
--GPR.CONTRIBUTO_TOTALE AS IMPORTO_IMPEGNO,
--NULL AS CAUSALE_DISIMPEGNO, --VERIFICARE TC38
--NULL AS NOTE_IMPEGNO,
--NULL AS FLG_CANCELLAZIONE,
--@IdInvio AS ID_INVIO,
--ISNULL(@rNumber,0) + ROW_NUMBER() OVER(ORDER BY P.ID_PROGETTO ASC) AS NR_RIGA_INVIO,
--'FESR20142020' AS CODICE_FONDO   
--FROM vPROGETTO P 
--INNER JOIN vBANDO B ON
--P.ID_BANDO = B.ID_BANDO
----INNER JOIN BANDO_PROGRAMMAZIONE BP ON
----B.ID_BANDO = BP.ID_BANDO
--INNER JOIN zPROGRAMMAZIONE PRG ON
--B.ID_PROGRAMMAZIONE = PRG.ID
--INNER JOIN zPSR_ALBERO PA ON
--PRG.COD_TIPO = PA.CODICE
--INNER JOIN zPSR PSR ON
--PA.COD_PSR = PSR.CODICE
----LEFT JOIN vPAGAMENTI_RICHIESTI VPR ON
--LEFT OUTER JOIN GRADUATORIA_PROGETTI GPR ON
--P.ID_PROGETTO = GPR.ID_PROGETTO
--LEFT OUTER JOIN BANDO_CONFIG BC ON
--B.ID_BANDO = BC.ID_BANDO 
--AND 
--BC.COD_TIPO = 'ATTGRADBLOCCHI'
--AND 
--BC.ATTIVO = 1
--LEFT OUTER JOIN 
--(SELECT 
--BS.ID_BANDO,
--MAX(BS.ID_ATTO) ID_ATTO
--FROM BANDO_STORICO BS 
--WHERE BS.COD_STATO = 'G'
--GROUP BY ID_BANDO) GB ON
--B.ID_BANDO = GB.ID_BANDO
--LEFT OUTER JOIN ATTI ATTI_B ON 
--GB.ID_ATTO = ATTI_B.ID_ATTO
--LEFT OUTER JOIN 
--(SELECT 
--PS.ID_PROGETTO,
--MAX(PS.ID_ATTO) ID_ATTO
--FROM PROGETTO_STORICO PS 
--WHERE PS.COD_STATO = 'F'
--GROUP BY ID_PROGETTO) GP ON
--P.ID_PROGETTO = GP.ID_PROGETTO
--LEFT OUTER JOIN ATTI ATTI_P ON
--GP.ID_ATTO = ATTI_P.ID_ATTO
----AND 
----VPR.ISTRUTTORE IS NOT NULL
----AND 
----VPR.ID_INVESTIMENTO_ORIGINALE IS NOT NULL
----AND
----VPR.AMMESSO = 1 
--WHERE 
--P.COD_STATO IN ('F','V','S','O','T','X','C','Y','E','R') 
--AND 
--PSR.CODICE = 'POR20142020'
--AND PRG.ID NOT IN (17,18,19)
--AND
--P.COD_AGEA IS NOT NULL
----CLAUSOLA TEMPORANEA PER TEST INVIO IGRUE
--AND 
--(COALESCE(ATTI_B.ID_ATTO, ATTI_P.ID_ATTO) IS NOT NULL)
--AND 
--GPR.CONTRIBUTO_TOTALE IS NOT NULL

----AND
----BR.ATTIVO = 1 AND BR.PROVINCIA IS NULL
----AND
----B.DATA_SCADENZA BETWEEN @DataDa AND @DataA

--SELECT ISNULL(MAX(NR_RIGA_INVIO),0) FROM IGRUE_MONIT.dbo.IGRUE_FN04 WHERE ID_INVIO = @IdInvio

--END
