CREATE PROCEDURE [dbo].[zIgrueInsertMonitPR00]
( 
 @DataDa DATETIME,
 @DataA DATETIME,
 @IdInvio INT,
 @rNumber INT
)
AS
BEGIN

WITH PSORD AS
(
	SELECT
	A.ID_PROGETTO,
	MAX(A.DATA) AS DATA,
	A.COD_STATO,
	ROW_NUMBER() OVER(PARTITION BY A.ID_PROGETTO ORDER BY MAX(A.DATA) ASC) AS NR_STATO 
	FROM 
	(
		SELECT 
		PS1.ID_PROGETTO,
		MAX(PS1.DATA) AS DATA,
		--DATEADD(DAY,1,MAX(PS1.DATA)) DATA,
		CASE WHEN PS1.COD_STATO IN ('V','S','T','E','R','Y','C','O','X') THEN 'V' ELSE PS1.COD_STATO END COD_STATO 
		FROM PROGETTO_STORICO PS1
		--WHERE 
		--PS1.COD_STATO IN ('P','L','F','V','S','O','T','C') 
		GROUP BY 
		PS1.ID_PROGETTO,
		PS1.COD_STATO
		UNION 
		SELECT 
		ID_PROGETTO,
		DATEADD(DAY,1,MAX(DATA)) DATA,
		'F1' AS COD_STATO
		FROM
		PROGETTO_STORICO
		WHERE 
		COD_STATO='F'
		AND NOT EXISTS
		(
		 SELECT NULL FROM PROGETTO_STORICO PS2
		 --WHERE PS2.COD_STATO IN ('V') AND 
		 WHERE PS2.COD_STATO IN ('V','S','T','E','R','Y','C','O','X') AND 
		 PS2.ID_PROGETTO = PROGETTO_STORICO.ID_PROGETTO
		)
		GROUP BY 
		ID_PROGETTO,
		COD_STATO
	) AS A
	WHERE A.COD_STATO IS NOT NULL
	--and A.ID_PROGETTO = 11592
	GROUP BY 
	A.ID_PROGETTO,
	A.COD_STATO
),

PSG AS 
(
	SELECT 
	B.ID_PROGETTO,
	B.COD_STATO,
	MAX(B.DATA) DATA
	FROM 
	(	
		SELECT 
		ID_PROGETTO,
		--COD_STATO,
		CASE WHEN COD_STATO IN ('V','S','T','E','R','Y','C','O','X') THEN 'V' ELSE COD_STATO END COD_STATO ,
		MAX(DATA) DATA
		FROM
		PROGETTO_STORICO 
		--WHERE 
		--COD_STATO IN ('P','L','F','V','S','O','T','C') 
		GROUP BY 
		ID_PROGETTO,
		COD_STATO
		UNION 
		SELECT 
		ID_PROGETTO,
		'F1' AS COD_STATO,
		--MAX(DATA) DATA
		DATEADD(DAY,1,MAX(DATA)) DATA
		FROM
		PROGETTO_STORICO
		WHERE 
		COD_STATO='F'
		AND NOT EXISTS
		(
		 SELECT NULL FROM PROGETTO_STORICO PS2
		 --WHERE PS2.COD_STATO IN ('V') AND 
		 WHERE PS2.COD_STATO IN ('V','S','T','E','R','Y','C','O','X') AND 
		 PS2.ID_PROGETTO = PROGETTO_STORICO.ID_PROGETTO
		)
		GROUP BY 
		ID_PROGETTO,
		COD_STATO
	) AS B
	GROUP BY 
	B.ID_PROGETTO,
	B.COD_STATO
)


INSERT INTO IGRUE_MONIT.dbo.IGRUE_PR00
(
COD_LOCALE_PROGETTO,
COD_FASE,
DATA_INIZIO_PREVISTA,
DATA_INIZIO_EFFETTIVA,
DATA_FINE_PREVISTA,
DATA_FINE_EFFETTIVA,
FLG_CANCELLAZIONE,
--OPERAZIONE,
ID_INVIO,
NR_RIGA_INVIO,
--NR_RIGA_CANCELLAZIONE
CODICE_FONDO
)


SELECT 
P.ID_PROGETTO AS COD_LOCALE_PROGETTO,
CASE
WHEN DMF.CUP_NATURA ='01' AND PS.COD_STATO IN ('F') THEN '0101'
WHEN DMF.CUP_NATURA ='01' AND PS.COD_STATO IN ('F1','V','S','T') THEN '0102'
WHEN DMF.CUP_NATURA ='02' AND PS.COD_STATO IN ('F') THEN '0201'
WHEN DMF.CUP_NATURA ='02' AND PS.COD_STATO IN ('F1','V','S','T') THEN '0202'
WHEN DMF.CUP_NATURA ='03' AND PS.COD_STATO IN ('P','L') THEN '0301'
WHEN DMF.CUP_NATURA ='03' AND PS.COD_STATO IN ('F') THEN '0305'
WHEN DMF.CUP_NATURA ='03' AND PS.COD_STATO IN ('F1','V','S','T') THEN '0306'
WHEN DMF.CUP_NATURA ='03' AND PS.COD_STATO IN ('C') THEN '0307'
WHEN DMF.CUP_NATURA ='06' AND PS.COD_STATO IN ('F') THEN '0601'
WHEN DMF.CUP_NATURA ='06' AND PS.COD_STATO IN ('F1','V','S','T') THEN '0602'
WHEN DMF.CUP_NATURA ='07' AND PS.COD_STATO IN ('F') THEN '0701'
WHEN DMF.CUP_NATURA ='07' AND PS.COD_STATO IN ('F1','V','S','T') THEN '0702'
END AS COD_FASE,
--PS.COD_STATO,
--PSORD1.COD_STATO COD_STATO_1,
dbo.DateToString_Igrue(PS.DATA) DATA_INIZIO_PREVISTA,
--PS.DATA AS DATA_INIZIO_EFFETTIVA,
NULL AS DATA_INIZIO_EFFETTIVA,
dbo.DateToString_Igrue(ISNULL(PSORD1.DATA, DATEADD(MONTH,18,PS.DATA))) DATA_FINE_PREVISTA,
--PSORD1.DATA DATA_FINE_EFFETTIVA,
NULL AS DATA_FINE_EFFETTIVA,
NULL AS FLG_CANCELLAZIONE,
--PSORD.COD_STATO,
--PSORD.NR_STATO,
--PSORD1.COD_STATO COD_STATO_SUCC,
--PSORD1.NR_STATO AS NR_STATO_SUCC,
@IdInvio AS ID_INVIO,
ISNULL(@rNumber,0) + ROW_NUMBER() OVER(ORDER BY P.ID_PROGETTO ASC) AS NR_RIGA_INVIO,
'FESR20142020' AS CODICE_FONDO 
FROM vPROGETTO P
INNER JOIN vBANDO B ON
P.ID_BANDO = B.ID_BANDO
--INNER JOIN PROGETTO_STORICO PS ON
--P.ID_PROGETTO = PS.ID_PROGETTO
INNER JOIN PSG PS ON
P.ID_PROGETTO = PS.ID_PROGETTO
INNER JOIN BANDO_PROGRAMMAZIONE BP ON
B.ID_BANDO = BP.ID_BANDO
INNER JOIN zPROGRAMMAZIONE PRG ON
BP.ID_PROGRAMMAZIONE = PRG.ID
INNER JOIN zPSR_ALBERO PA ON
PRG.COD_TIPO = PA.CODICE
INNER JOIN zPSR PSR ON
PA.COD_PSR = PSR.CODICE
--INNER JOIN BANDO_RESPONSABILI BR ON
--B.ID_BANDO = BR.ID_BANDO
INNER JOIN DATI_MONITORAGGIO_FESR DMF ON
P.ID_PROGETTO = DMF.ID_PROGETTO
INNER JOIN PSORD ON
PS.ID_PROGETTO = PSORD.ID_PROGETTO
AND
PS.COD_STATO = PSORD.COD_STATO
LEFT OUTER JOIN PSORD PSORD1 ON
PSORD1.ID_PROGETTO = PSORD.ID_PROGETTO
AND
PSORD1.NR_STATO = PSORD.NR_STATO + 1
WHERE 
PS.COD_STATO IN ('F','F1','V','S','O','T','X','C','Y','E','R') 
AND 
PSR.CODICE = 'POR20142020'
AND 
PRG.ID NOT IN (17,18,19)
AND
BP.ID_PROGRAMMAZIONE NOT IN (17,18,19)
AND
P.COD_AGEA IS NOT NULL
--26/01/2018
--CLAUSOLA TEMPORANEA PER ESCLUDERE PROGETTO STRUMENTI FINANZIARI ARTIGIANCASSA
AND P.ID_PROGETTO <> 13301
--ORDER BY P.ID_PROGETTO,
--COD_FASE
----AND
----BR.ATTIVO = 1 AND BR.PROVINCIA IS NULL
----AND
----B.DATA_SCADENZA BETWEEN @DataDa AND @DataA

SELECT ISNULL(MAX(NR_RIGA_INVIO),0) FROM IGRUE_MONIT.dbo.IGRUE_PR00 WHERE ID_INVIO = @IdInvio

END


--WITH PSORD AS
--(
--	SELECT 
--	A.*,
--	ROW_NUMBER() OVER(PARTITION BY A.ID_PROGETTO ORDER BY A.DATA ASC) AS NR_STATO 
--	FROM 
--	(
--		SELECT 
--		PS1.ID_PROGETTO,
--		MAX(PS1.DATA) AS DATA,
--		PS1.COD_STATO--,
--		--ROW_NUMBER() OVER(PARTITION BY PS1.ID_PROGETTO ORDER BY PS1.DATA ASC) AS NR_STATO
--		--ROW_NUMBER() OVER(PARTITION BY PS1.ID_PROGETTO) AS NR_STATO
--		FROM PROGETTO_STORICO PS1
--		--WHERE 
--		--PS1.COD_STATO IN ('P','L','F','V','S','O','T','X','C','Y','E','R') 
--		GROUP BY 
--		PS1.ID_PROGETTO,
--		PS1.COD_STATO
--	) AS A
--),

--PSG AS 
--(
--	SELECT 
--	ID_PROGETTO,
--	COD_STATO,
--	MAX(DATA) DATA
--	FROM
--	PROGETTO_STORICO 
--	GROUP BY 
--	ID_PROGETTO,
--	COD_STATO
--)


--INSERT INTO IGRUE_MONIT.dbo.IGRUE_PR00
--(
--COD_LOCALE_PROGETTO,
--COD_FASE,
--DATA_INIZIO_PREVISTA,
--DATA_INIZIO_EFFETTIVA,
--DATA_FINE_PREVISTA,
--DATA_FINE_EFFETTIVA,
--FLG_CANCELLAZIONE,
----OPERAZIONE,
--ID_INVIO,
--NR_RIGA_INVIO,
----NR_RIGA_CANCELLAZIONE
--CODICE_FONDO
--)




--SELECT ISNULL(MAX(NR_RIGA_INVIO),0) FROM IGRUE_MONIT.dbo.IGRUE_PR00 WHERE ID_INVIO = @IdInvio



--END


--SELECT 
--P.ID_PROGETTO AS COD_LOCALE_PROGETTO,
--CASE
--WHEN DMF.CUP_NATURA ='01' AND PS.COD_STATO IN ('F') THEN '0101'
--WHEN DMF.CUP_NATURA ='01' AND PS.COD_STATO IN ('V','S','T') THEN '0102'
--WHEN DMF.CUP_NATURA ='02' AND PS.COD_STATO IN ('F') THEN '0201'
--WHEN DMF.CUP_NATURA ='02' AND PS.COD_STATO IN ('V','S','T') THEN '0202'
--WHEN DMF.CUP_NATURA ='03' AND PS.COD_STATO IN ('P','L') THEN '0301'
--WHEN DMF.CUP_NATURA ='03' AND PS.COD_STATO IN ('F') THEN '0305'
--WHEN DMF.CUP_NATURA ='03' AND PS.COD_STATO IN ('V','S','T') THEN '0306'
--WHEN DMF.CUP_NATURA ='03' AND PS.COD_STATO IN ('C') THEN '0307'
--WHEN DMF.CUP_NATURA ='06' AND PS.COD_STATO IN ('F') THEN '0601'
--WHEN DMF.CUP_NATURA ='06' AND PS.COD_STATO IN ('V','S','T') THEN '0602'
--WHEN DMF.CUP_NATURA ='07' AND PS.COD_STATO IN ('F') THEN '0701'
--WHEN DMF.CUP_NATURA ='07' AND PS.COD_STATO IN ('V','S','T') THEN '0702'
--END AS COD_FASE,
--dbo.DateToString_Igrue(PS.DATA) DATA_INIZIO_PREVISTA,
----PS.DATA AS DATA_INIZIO_EFFETTIVA,
--NULL AS DATA_INIZIO_EFFETTIVA,
--dbo.DateToString_Igrue(ISNULL(PSORD1.DATA, DATEADD(MONTH,18,PS.DATA))) DATA_FINE_PREVISTA,
----PSORD1.DATA DATA_FINE_EFFETTIVA,
--NULL AS DATA_FINE_EFFETTIVA,
--NULL AS FLG_CANCELLAZIONE,
----PSORD.COD_STATO,
----PSORD.NR_STATO,
----PSORD1.COD_STATO COD_STATO_SUCC,
----PSORD1.NR_STATO AS NR_STATO_SUCC,
--@IdInvio AS ID_INVIO,
--ISNULL(@rNumber,0) + ROW_NUMBER() OVER(ORDER BY P.ID_PROGETTO ASC) AS NR_RIGA_INVIO,
--'FESR20142020' AS CODICE_FONDO 
--FROM vPROGETTO P
--INNER JOIN vBANDO B ON
--P.ID_BANDO = B.ID_BANDO
----INNER JOIN PROGETTO_STORICO PS ON
----P.ID_PROGETTO = PS.ID_PROGETTO
--INNER JOIN PSG PS ON
--P.ID_PROGETTO = PS.ID_PROGETTO
--INNER JOIN BANDO_PROGRAMMAZIONE BP ON
--B.ID_BANDO = BP.ID_BANDO
--INNER JOIN zPROGRAMMAZIONE PRG ON
--BP.ID_PROGRAMMAZIONE = PRG.ID
--INNER JOIN zPSR_ALBERO PA ON
--PRG.COD_TIPO = PA.CODICE
--INNER JOIN zPSR PSR ON
--PA.COD_PSR = PSR.CODICE
----INNER JOIN BANDO_RESPONSABILI BR ON
----B.ID_BANDO = BR.ID_BANDO
--INNER JOIN DATI_MONITORAGGIO_FESR DMF ON
--P.ID_PROGETTO = DMF.ID_PROGETTO
--INNER JOIN PSORD ON
--PS.ID_PROGETTO = PSORD.ID_PROGETTO
--AND
--PS.COD_STATO = PSORD.COD_STATO
--LEFT OUTER JOIN PSORD PSORD1 ON
--PSORD1.ID_PROGETTO = PSORD.ID_PROGETTO
--AND
--PSORD1.NR_STATO = PSORD.NR_STATO + 1
--WHERE 
--PS.COD_STATO IN ('F','V','S','O','T','X','C','Y','E','R') 
--AND 
--PSR.CODICE = 'POR20142020'
--AND 
--PRG.ID NOT IN (17,18,19)
--AND
--BP.ID_PROGRAMMAZIONE NOT IN (17,18,19)
--AND
--P.COD_AGEA IS NOT NULL
----26/01/2018
----CLAUSOLA TEMPORANEA PER ESCLUDERE PROGETTO STRUMENTI FINANZIARI ARTIGIANCASSA
--AND P.ID_PROGETTO <> 13301
------AND
------BR.ATTIVO = 1 AND BR.PROVINCIA IS NULL
------AND
------B.DATA_SCADENZA BETWEEN @DataDa AND @DataA

--SELECT ISNULL(MAX(NR_RIGA_INVIO),0) FROM IGRUE_MONIT.dbo.IGRUE_PR00 WHERE ID_INVIO = @IdInvio



--END


--WITH PSORD AS
--(
--SELECT 
--PS1.ID_PROGETTO,
--PS1.DATA,
--PS1.COD_STATO,
--ROW_NUMBER() OVER(PARTITION BY PS1.ID_PROGETTO ORDER BY PS1.DATA ASC) AS NR_STATO
--FROM PROGETTO_STORICO PS1
--)

--INSERT INTO IGRUE_MONIT.dbo.IGRUE_PR00
--(
--COD_LOCALE_PROGETTO,
--COD_FASE,
--DATA_INIZIO_PREVISTA,
--DATA_INIZIO_EFFETTIVA,
--DATA_FINE_PREVISTA,
--DATA_FINE_EFFETTIVA,
--FLG_CANCELLAZIONE,
----OPERAZIONE,
--ID_INVIO,
--NR_RIGA_INVIO,
----NR_RIGA_CANCELLAZIONE
--CODICE_FONDO
--)


--SELECT 
--P.ID_PROGETTO AS COD_LOCALE_PROGETTO,
--CASE
--WHEN DMF.CUP_NATURA ='01' AND PS.COD_STATO IN ('F') THEN '0101'
--WHEN DMF.CUP_NATURA ='01' AND PS.COD_STATO IN ('V','S','T') THEN '0102'
--WHEN DMF.CUP_NATURA ='02' AND PS.COD_STATO IN ('F') THEN '0201'
--WHEN DMF.CUP_NATURA ='02' AND PS.COD_STATO IN ('V','S','T') THEN '0202'
--WHEN DMF.CUP_NATURA ='03' AND PS.COD_STATO IN ('P','L') THEN '0301'
--WHEN DMF.CUP_NATURA ='03' AND PS.COD_STATO IN ('F') THEN '0305'
--WHEN DMF.CUP_NATURA ='03' AND PS.COD_STATO IN ('V','S','T') THEN '0306'
--WHEN DMF.CUP_NATURA ='03' AND PS.COD_STATO IN ('C') THEN '0307'
--WHEN DMF.CUP_NATURA ='06' AND PS.COD_STATO IN ('F') THEN '0601'
--WHEN DMF.CUP_NATURA ='06' AND PS.COD_STATO IN ('V','S','T') THEN '0602'
--WHEN DMF.CUP_NATURA ='07' AND PS.COD_STATO IN ('F') THEN '0701'
--WHEN DMF.CUP_NATURA ='07' AND PS.COD_STATO IN ('V','S','T') THEN '0702'
--END AS COD_FASE,
--PS.DATA DATA_INIZIO_PREVISTA,
--PS.DATA AS DATA_INIZIO_EFFETTIVA,
--ISNULL(PSORD1.DATA, DATEADD(MONTH,2,PS.DATA)) DATA_FINE_PREVISTA,
--PSORD1.DATA DATA_FINE_EFFETTIVA,
--NULL AS FLG_CANCELLAZIONE,
----PSORD.COD_STATO,
----PSORD.NR_STATO,
----PSORD1.COD_STATO COD_STATO_SUCC,
----PSORD1.NR_STATO AS NR_STATO_SUCC,
--@IdInvio AS ID_INVIO,
--ISNULL(@rNumber,0) + ROW_NUMBER() OVER(ORDER BY P.ID_PROGETTO ASC) AS NR_RIGA_INVIO,
--'FESR20142020' AS CODICE_FONDO 
--FROM vPROGETTO P
--INNER JOIN vBANDO B ON
--P.ID_BANDO = B.ID_BANDO
--INNER JOIN PROGETTO_STORICO PS ON
--P.ID_PROGETTO = PS.ID_PROGETTO
--INNER JOIN BANDO_PROGRAMMAZIONE BP ON
--B.ID_BANDO = BP.ID_BANDO
--INNER JOIN zPROGRAMMAZIONE PRG ON
--BP.ID_PROGRAMMAZIONE = PRG.ID
--INNER JOIN zPSR_ALBERO PA ON
--PRG.COD_TIPO = PA.CODICE
--INNER JOIN zPSR PSR ON
--PA.COD_PSR = PSR.CODICE
----INNER JOIN BANDO_RESPONSABILI BR ON
----B.ID_BANDO = BR.ID_BANDO
--INNER JOIN DATI_MONITORAGGIO_FESR DMF ON
--P.ID_PROGETTO = DMF.ID_PROGETTO
--INNER JOIN PSORD ON
--PS.ID_PROGETTO = PSORD.ID_PROGETTO
--AND
--PS.COD_STATO = PSORD.COD_STATO
--LEFT OUTER JOIN PSORD PSORD1 ON
--PSORD1.ID_PROGETTO = PSORD.ID_PROGETTO
--AND
--PSORD1.NR_STATO = PSORD.NR_STATO + 1
--WHERE 
--PS.COD_STATO IN ('F','V','S','O','T','X','C','Y','E','R') 
--AND 
--PSR.CODICE = 'POR20142020'
--AND 
--PRG.ID NOT IN (17,18,19)
--AND
--BP.ID_PROGRAMMAZIONE NOT IN (17,18,19)
--AND
--P.COD_AGEA IS NOT NULL
----AND
----BR.ATTIVO = 1 AND BR.PROVINCIA IS NULL
----AND
----B.DATA_SCADENZA BETWEEN @DataDa AND @DataA

--SELECT ISNULL(MAX(NR_RIGA_INVIO),0) FROM IGRUE_MONIT.dbo.IGRUE_PR00 WHERE ID_INVIO = @IdInvio