CREATE PROCEDURE [dbo].[zIgrueGetColumnNames]
( 
	@NomeTabella VARCHAR(50)
)
AS
BEGIN

SELECT COLUMN_NAME AS Field 
FROM 
IGRUE_MONIT.INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'IGRUE_' + @NomeTabella

END
