CREATE PROCEDURE [dbo].[zIgrueInsertMonitPA00]
( 
 @DataDa DATETIME,
 @DataA DATETIME,
 @IdInvio INT,
 @rNumber INT
)
AS
BEGIN
INSERT INTO IGRUE_MONIT.dbo.IGRUE_PA00
(
COD_PROC_ATT,
COD_PROC_ATT_LOCALE,
COD_AIUTO_RNA,
TIP_PROCEDURA_ATT,
FLAG_AIUTI,
DESCR_PROCEDURA_ATT,
COD_TIPO_RESP_PROC,
DENOM_RESP_PROC,
DATA_AVVIO_PROCEDURA,
DATA_FINE_PROCEDURA,
FLG_CANCELLAZIONE,
--OPERAZIONE,
ID_INVIO,
NR_RIGA_INVIO,
--NR_RIGA_CANCELLAZIONE
CODICE_FONDO
)
SELECT 
BCA.COD_PROCEDURA_ATTIVAZIONE AS COD_PROC_ATT, --Modificare con valore preso da db
B.ID_BANDO AS COD_PROC_ATT_LOCALE,
NULL AS COD_AIUTO_RNA,
--'1' AS TIP_PROCEDURA_ATT,				--COLLEGARE A TABELLA TC2
ISNULL(BC.VALORE,'1') AS TIP_PROCEDURA_ATT,
'N' AS FLAG_AIUTI, --VERIFICARE SE VALORE FISSO 'S'
REPLACE(REPLACE(REPLACE(REPLACE(LEFT(B.DESCRIZIONE,255),CHAR(10),' '),CHAR(13),' '),'#',' '),'|',' ') AS DESCR_PROCEDURA_ATT,
--B.COD_ENTE,								--estrarre record univoco per ruolo TC3
1 AS COD_ENTE,
--ENTE.DESCRIZIONE AS DENOM_RESP_PROC,	--estrarre record univoco per ruolo TC3
'Regione' AS DENOM_RESP_PROC,
--B.NOMINATIVO AS DENOM_RESP_PROC,
dbo.DateToString_Igrue(B.DATA_APERTURA) AS DATA_AVVIO_PROCEDURA,
dbo.DateToString_Igrue(B.DATA_SCADENZA) AS DATA_FINE_PROCEDURA,
--BI.DATA_SCADENZA AS DATA_FINE_PROCEDURA,
NULL AS FLG_CANCELLAZIONE,
@IdInvio AS ID_INVIO,
ISNULL(@rNumber, 0) + ROW_NUMBER() OVER(ORDER BY B.ID_BANDO ASC) AS NR_RIGA_INVIO,
'FESR20142020' AS CODICE_FONDO
FROM vBANDO B
--INNER JOIN BANDO_RESPONSABILI BR ON
--B.ID_BANDO = BR.ID_BANDO
INNER JOIN zPROGRAMMAZIONE P ON
B.ID_PROGRAMMAZIONE = P.ID
INNER JOIN zPSR_ALBERO PA ON
P.COD_TIPO = PA.CODICE
INNER JOIN zPSR PSR ON
PA.COD_PSR = PSR.CODICE
INNER JOIN ENTE ON
B.COD_ENTE = ENTE.COD_ENTE
--PARTE TEMPORANEA PER REPERIRE IL CODICE DI ATTIVAZIONE
INNER JOIN BANDO_CODICI_ATTIVAZIONE BCA ON
B.ID_BANDO = BCA.ID_BANDO
LEFT OUTER JOIN BANDO_CONFIG BC ON
B.ID_BANDO = BC.ID_BANDO
AND 
BC.ATTIVO = 1
AND
BC.COD_TIPO = 'TPPROCATT'
WHERE 
--BR.ATTIVO = 1 AND BR.PROVINCIA IS NULL
--AND 
PSR.CODICE = 'POR20142020'
AND 
B.COD_STATO <> 'P'
AND B.DISPOSIZIONI_ATTUATIVE = 0
--AND
--B.DATA_SCADENZA BETWEEN @DataDa AND @DataA
SELECT ISNULL(MAX(NR_RIGA_INVIO),0) FROM IGRUE_MONIT.dbo.IGRUE_PA00 WHERE ID_INVIO = @IdInvio

END

