CREATE PROCEDURE [dbo].[ZImpresaCertificazioneAntimafiaFindFind]
(
	@IdImpresaequalthis INT
)
AS
	declare @sql nvarchar(4000);
	declare @lensql int;
	set @lensql=0;
	SET @sql = 'SELECT ID, ID_IMPRESA, ESENZIONE_CERTIFICAZIONE, DATA_INIZIO_VALIDITA, DATA_FINE_VALIDITA, NUMERO_PROTOCOLLO_RICHIESTA, DATA_PROTOCOLLO_RICHIESTA, NUMERO_PROTOCOLLO_CAMERALE, DATA_CERTIFICATO_CAMERALE, ESITO_CERTIFICATO_CAMERALE, NUMERO_PROTOCOLLO_PREFETTIZIO, DATA_CERTIFICATO_PREFETTIZIO, ESITO_CERTIFICATO_PREFETTIZIO, NUMERO_PROTOCOLLO_COMUNICAZIONE, DATA_PROTOCOLLO_COMUNICAZIONE, DATA_ACQUISIZIONE_ANTIMAFIA, NUMERO_PROTOCOLLO_ACQUISIZIONE_ANTIMAFIA FROM IMPRESA_CERTIFICAZIONE_ANTIMAFIA WHERE 1=1';
	IF (@IdImpresaequalthis IS NOT NULL) BEGIN SET @sql = @sql + ' AND (ID_IMPRESA = @IdImpresaequalthis)'; set @lensql=@lensql+len(@IdImpresaequalthis);end;
	set @lensql=@lensql+len(@sql);
	if (@lensql<3000)
	exec sp_executesql @sql,N'@IdImpresaequalthis INT',@IdImpresaequalthis ;
	else
		SELECT ID, ID_IMPRESA, ESENZIONE_CERTIFICAZIONE, DATA_INIZIO_VALIDITA, DATA_FINE_VALIDITA, NUMERO_PROTOCOLLO_RICHIESTA, DATA_PROTOCOLLO_RICHIESTA, NUMERO_PROTOCOLLO_CAMERALE, DATA_CERTIFICATO_CAMERALE, ESITO_CERTIFICATO_CAMERALE, NUMERO_PROTOCOLLO_PREFETTIZIO, DATA_CERTIFICATO_PREFETTIZIO, ESITO_CERTIFICATO_PREFETTIZIO, NUMERO_PROTOCOLLO_COMUNICAZIONE, DATA_PROTOCOLLO_COMUNICAZIONE, DATA_ACQUISIZIONE_ANTIMAFIA, NUMERO_PROTOCOLLO_ACQUISIZIONE_ANTIMAFIA
		FROM IMPRESA_CERTIFICAZIONE_ANTIMAFIA
		WHERE 
			((@IdImpresaequalthis IS NULL) OR ID_IMPRESA = @IdImpresaequalthis)

GO
EXECUTE sp_addextendedproperty @name = N'backup', @value = NULL, @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'PROCEDURE', @level1name = N'ZImpresaCertificazioneAntimafiaFindFind';

