CREATE PROCEDURE [dbo].[ZIndirizzoInsert]
(
	@VIA VARCHAR(500), 
	@LOCALITA VARCHAR(500), 
	@ID_COMUNE INT, 
	@DENOMINAZIONE VARCHAR(255)
)
AS
	INSERT INTO INDIRIZZO
	(
		VIA, 
		LOCALITA, 
		ID_COMUNE, 
		DENOMINAZIONE
	)
	VALUES
	(
		@VIA, 
		@LOCALITA, 
		@ID_COMUNE, 
		@DENOMINAZIONE
	)
	SELECT SCOPE_IDENTITY() AS ID_INDIRIZZO
