CREATE PROCEDURE [dbo].[ZIntegrazioniPerDomandaDiPagamentoFindFind]
(
	@IdIntegrazioneDomandaDiPagamentoequalthis INT, 
	@IdDomandaPagamentoequalthis INT, 
	@IntegrazioneCompletaequalthis BIT, 
	@IdProgettoequalthis INT
)
AS
	declare @sql nvarchar(4000);
	declare @lensql int;
	set @lensql=0;
	SET @sql = 'SELECT ID_INTEGRAZIONE_DOMANDA_DI_PAGAMENTO, ID_DOMANDA_PAGAMENTO, DATA_INSERIMENTO, DATA_MODIFICA, ISTANZA_DOMANDA_PAGAMENTO, INTEGRAZIONE_COMPLETA, NOTE_INTEGRAZIONE_DOMANDA, CF_ISTRUTTORE, DATA_RICHIESTA_INTEGRAZIONE_DOMANDA, SEGNATURA_ISTRUTTORE, CF_BENFICIARIO, SEGNATURA_BENEFICIARIO, DATA_CONCLUSIONE_INTEGRAZIONE, COD_TIPO, ID_PROGETTO, DATA_INSERIMENTO_DOMANDA, CF_OPERATORE_DOMANDA, DATA_MODIFICA_DOMANDA, COD_ENTE, SEGNATURA, SEGNATURA_ALLEGATI, ID_FIDEJUSSIONE, DATA_CERTIFICAZIONE_ANTIMAFIA, APPROVATA, SEGNATURA_APPROVAZIONE, SEGNATURA_SECONDA_APPROVAZIONE, CF_ISTRUTTORE_DOMANDA, DATA_APPROVAZIONE, VALUTAZIONE_ISTRUTTORE, ANNULLATA, SEGNATURA_ANNULLAMENTO, CF_OPERATORE_ANNULLAMENTO, DATA_ANNULLAMENTO, VALIDITA_VERSIONE_ADC, ID_VARIAZIONE_ACCERTATA, PREDISPOSTA_A_CONTROLLO, DATA_PREDISPOSIZIONE_A_CONTROLLO, VISITA_INSITU_ESITO, VISITA_INSITU_NOTE, CONTROLLO_INLOCO_ESITO, CONTROLLO_INLOCO_NOTE, VERIFICA_PAGAMENTI_ESITO, VERIFICA_PAGAMENTI_MESSAGGIO, VERIFICA_PAGAMENTI_DATA, FIRMA_PREDISPOSTA, IN_INTEGRAZIONE, ID_DOMANDA_PAGAMENTO_DOMANDA FROM VINTEGRAZIONI_PER_DOMANDA_DI_PAGAMENTO WHERE 1=1';
	IF (@IdIntegrazioneDomandaDiPagamentoequalthis IS NOT NULL) BEGIN SET @sql = @sql + ' AND (ID_INTEGRAZIONE_DOMANDA_DI_PAGAMENTO = @IdIntegrazioneDomandaDiPagamentoequalthis)'; set @lensql=@lensql+len(@IdIntegrazioneDomandaDiPagamentoequalthis);end;
	IF (@IdDomandaPagamentoequalthis IS NOT NULL) BEGIN SET @sql = @sql + ' AND (ID_DOMANDA_PAGAMENTO = @IdDomandaPagamentoequalthis)'; set @lensql=@lensql+len(@IdDomandaPagamentoequalthis);end;
	IF (@IntegrazioneCompletaequalthis IS NOT NULL) BEGIN SET @sql = @sql + ' AND (INTEGRAZIONE_COMPLETA = @IntegrazioneCompletaequalthis)'; set @lensql=@lensql+len(@IntegrazioneCompletaequalthis);end;
	IF (@IdProgettoequalthis IS NOT NULL) BEGIN SET @sql = @sql + ' AND (ID_PROGETTO = @IdProgettoequalthis)'; set @lensql=@lensql+len(@IdProgettoequalthis);end;
	set @lensql=@lensql+len(@sql);
	if (@lensql<3000)
	exec sp_executesql @sql,N'@IdIntegrazioneDomandaDiPagamentoequalthis INT, @IdDomandaPagamentoequalthis INT, @IntegrazioneCompletaequalthis BIT, @IdProgettoequalthis INT',@IdIntegrazioneDomandaDiPagamentoequalthis , @IdDomandaPagamentoequalthis , @IntegrazioneCompletaequalthis , @IdProgettoequalthis ;
	else
		SELECT ID_INTEGRAZIONE_DOMANDA_DI_PAGAMENTO, ID_DOMANDA_PAGAMENTO, DATA_INSERIMENTO, DATA_MODIFICA, ISTANZA_DOMANDA_PAGAMENTO, INTEGRAZIONE_COMPLETA, NOTE_INTEGRAZIONE_DOMANDA, CF_ISTRUTTORE, DATA_RICHIESTA_INTEGRAZIONE_DOMANDA, SEGNATURA_ISTRUTTORE, CF_BENFICIARIO, SEGNATURA_BENEFICIARIO, DATA_CONCLUSIONE_INTEGRAZIONE, COD_TIPO, ID_PROGETTO, DATA_INSERIMENTO_DOMANDA, CF_OPERATORE_DOMANDA, DATA_MODIFICA_DOMANDA, COD_ENTE, SEGNATURA, SEGNATURA_ALLEGATI, ID_FIDEJUSSIONE, DATA_CERTIFICAZIONE_ANTIMAFIA, APPROVATA, SEGNATURA_APPROVAZIONE, SEGNATURA_SECONDA_APPROVAZIONE, CF_ISTRUTTORE_DOMANDA, DATA_APPROVAZIONE, VALUTAZIONE_ISTRUTTORE, ANNULLATA, SEGNATURA_ANNULLAMENTO, CF_OPERATORE_ANNULLAMENTO, DATA_ANNULLAMENTO, VALIDITA_VERSIONE_ADC, ID_VARIAZIONE_ACCERTATA, PREDISPOSTA_A_CONTROLLO, DATA_PREDISPOSIZIONE_A_CONTROLLO, VISITA_INSITU_ESITO, VISITA_INSITU_NOTE, CONTROLLO_INLOCO_ESITO, CONTROLLO_INLOCO_NOTE, VERIFICA_PAGAMENTI_ESITO, VERIFICA_PAGAMENTI_MESSAGGIO, VERIFICA_PAGAMENTI_DATA, FIRMA_PREDISPOSTA, IN_INTEGRAZIONE, ID_DOMANDA_PAGAMENTO_DOMANDA
		FROM VINTEGRAZIONI_PER_DOMANDA_DI_PAGAMENTO
		WHERE 
			((@IdIntegrazioneDomandaDiPagamentoequalthis IS NULL) OR ID_INTEGRAZIONE_DOMANDA_DI_PAGAMENTO = @IdIntegrazioneDomandaDiPagamentoequalthis) AND 
			((@IdDomandaPagamentoequalthis IS NULL) OR ID_DOMANDA_PAGAMENTO = @IdDomandaPagamentoequalthis) AND 
			((@IntegrazioneCompletaequalthis IS NULL) OR INTEGRAZIONE_COMPLETA = @IntegrazioneCompletaequalthis) AND 
			((@IdProgettoequalthis IS NULL) OR ID_PROGETTO = @IdProgettoequalthis)
		


GO
EXECUTE sp_addextendedproperty @name = N'backup', @value = 'CREATE PROCEDURE [dbo].[ZIntegrazioniPerDomandaDiPagamentoFindFind]
(
	@IdIntegrazioneDomandaDiPagamentoequalthis INT, 
	@IdDomandaPagamentoequalthis INT, 
	@IntegrazioneCompletaequalthis BIT, 
	@IdProgettoequalthis INT
)
AS
	declare @sql nvarchar(4000);
	declare @lensql int;
	set @lensql=0;
	SET @sql = ''SELECT ID_INTEGRAZIONE_DOMANDA_DI_PAGAMENTO, ID_DOMANDA_PAGAMENTO, DATA_INSERIMENTO, DATA_MODIFICA, ISTANZA_DOMANDA_PAGAMENTO, INTEGRAZIONE_COMPLETA, NOTE_INTEGRAZIONE_DOMANDA, CF_ISTRUTTORE, DATA_RICHIESTA_INTEGRAZIONE_DOMANDA, SEGNATURA_ISTRUTTORE, CF_BENFICIARIO, SEGNATURA_BENEFICIARIO, DATA_CONCLUSIONE_INTEGRAZIONE, ID_DOMANDA_PAGAMENTO_DOMANDA, COD_TIPO, ID_PROGETTO, DATA_INSERIMENTO_DOMANDA, CF_OPERATORE_DOMANDA, DATA_MODIFICA_DOMANDA, COD_ENTE, SEGNATURA, SEGNATURA_ALLEGATI, ID_FIDEJUSSIONE, DATA_CERTIFICAZIONE_ANTIMAFIA, APPROVATA, SEGNATURA_APPROVAZIONE, SEGNATURA_SECONDA_APPROVAZIONE, CF_ISTRUTTORE_DOMANDA, DATA_APPROVAZIONE, VALUTAZIONE_ISTRUTTORE, ANNULLATA, SEGNATURA_ANNULLAMENTO, CF_OPERATORE_ANNULLAMENTO, DATA_ANNULLAMENTO, VALIDITA_VERSIONE_ADC, ID_VARIAZIONE_ACCERTATA, PREDISPOSTA_A_CONTROLLO, DATA_PREDISPOSIZIONE_A_CONTROLLO, VISITA_INSITU_ESITO, VISITA_INSITU_NOTE, CONTROLLO_INLOCO_ESITO, CONTROLLO_INLOCO_NOTE, VERIFICA_PAGAMENTI_ESITO, VERIFICA_PAGAMENTI_MESSAGGIO, VERIFICA_PAGAMENTI_DATA, FIRMA_PREDISPOSTA, IN_INTEGRAZIONE FROM VINTEGRAZIONI_PER_DOMANDA_DI_PAGAMENTO WHERE 1=1'';
	IF (@IdIntegrazioneDomandaDiPagamentoequalthis IS NOT NULL) BEGIN SET @sql = @sql + '' AND (ID_INTEGRAZIONE_DOMANDA_DI_PAGAMENTO = @IdIntegrazioneDomandaDiPagamentoequalthis)''; set @lensql=@lensql+len(@IdIntegrazioneDomandaDiPagamentoequalthis);end;
	IF (@IdDomandaPagamentoequalthis IS NOT NULL) BEGIN SET @sql = @sql + '' AND (ID_DOMANDA_PAGAMENTO = @IdDomandaPagamentoequalthis)''; set @lensql=@lensql+len(@IdDomandaPagamentoequalthis);end;
	IF (@IntegrazioneCompletaequalthis IS NOT NULL) BEGIN SET @sql = @sql + '' AND (INTEGRAZIONE_COMPLETA = @IntegrazioneCompletaequalthis)''; set @lensql=@lensql+len(@IntegrazioneCompletaequalthis);end;
	IF (@IdProgettoequalthis IS NOT NULL) BEGIN SET @sql = @sql + '' AND (ID_PROGETTO = @IdProgettoequalthis)''; set @lensql=@lensql+len(@IdProgettoequalthis);end;
	set @lensql=@lensql+len(@sql);
	if (@lensql<3000)
	exec sp_executesql @sql,N''@IdIntegrazioneDomandaDiPagamentoequalthis INT, @IdDomandaPagamentoequalthis INT, @IntegrazioneCompletaequalthis BIT, @IdProgettoequalthis INT'',@IdIntegrazioneDomandaDiPagamentoequalthis , @IdDomandaPagamentoequalthis , @IntegrazioneCompletaequalthis , @IdProgettoequalthis ;
	else
		SELECT ID_INTEGRAZIONE_DOMANDA_DI_PAGAMENTO, ID_DOMANDA_PAGAMENTO, DATA_INSERIMENTO, DATA_MODIFICA, ISTANZA_DOMANDA_PAGAMENTO, INTEGRAZIONE_COMPLETA, NOTE_INTEGRAZIONE_DOMANDA, CF_ISTRUTTORE, DATA_RICHIESTA_INTEGRAZIONE_DOMANDA, SEGNATURA_ISTRUTTORE, CF_BENFICIARIO, SEGNATURA_BENEFICIARIO, DATA_CONCLUSIONE_INTEGRAZIONE, ID_DOMANDA_PAGAMENTO_DOMANDA, COD_TIPO, ID_PROGETTO, DATA_INSERIMENTO_DOMANDA, CF_OPERATORE_DOMANDA, DATA_MODIFICA_DOMANDA, COD_ENTE, SEGNATURA, SEGNATURA_ALLEGATI, ID_FIDEJUSSIONE, DATA_CERTIFICAZIONE_ANTIMAFIA, APPROVATA, SEGNATURA_APPROVAZIONE, SEGNATURA_SECONDA_APPROVAZIONE, CF_ISTRUTTORE_DOMANDA, DATA_APPROVAZIONE, VALUTAZIONE_ISTRUTTORE, ANNULLATA, SEGNATURA_ANNULLAMENTO, CF_OPERATORE_ANNULLAMENTO, DATA_ANNULLAMENTO, VALIDITA_VERSIONE_ADC, ID_VARIAZIONE_ACCERTATA, PREDISPOSTA_A_CONTROLLO, DATA_PREDISPOSIZIONE_A_CONTROLLO, VISITA_INSITU_ESITO, VISITA_INSITU_NOTE, CONTROLLO_INLOCO_ESITO, CONTROLLO_INLOCO_NOTE, VERIFICA_PAGAMENTI_ESITO, VERIFICA_PAGAMENTI_MESSAGGIO, VERIFICA_PAGAMENTI_DATA, FIRMA_PREDISPOSTA, IN_INTEGRAZIONE
		FROM VINTEGRAZIONI_PER_DOMANDA_DI_PAGAMENTO
		WHERE 
			((@IdIntegrazioneDomandaDiPagamentoequalthis IS NULL) OR ID_INTEGRAZIONE_DOMANDA_DI_PAGAMENTO = @IdIntegrazioneDomandaDiPagamentoequalthis) AND 
			((@IdDomandaPagamentoequalthis IS NULL) OR ID_DOMANDA_PAGAMENTO = @IdDomandaPagamentoequalthis) AND 
			((@IntegrazioneComple', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'PROCEDURE', @level1name = N'ZIntegrazioniPerDomandaDiPagamentoFindFind';

