CREATE PROCEDURE [dbo].[ZPagamentiRichiestiFindFind]
(
	@IdPagamentoRichiestoequalthis INT, 
	@IdInvestimentoequalthis INT, 
	@IdProgettoequalthis INT, 
	@IdDomandaPagamentoequalthis INT
)
AS
	declare @sql nvarchar(4000);
	declare @lensql int;
	set @lensql=0;
	SET @sql = 'SELECT ID_PAGAMENTO_RICHIESTO, ID_INVESTIMENTO, DATA_RICHIESTA_PAGAMENTO, CONTRIBUTO_RICHIESTO, CONTRIBUTO_AMMESSO, AMMESSO, ISTRUTTORE, DATA_VALUTAZIONE, IMPORTO_COMPUTO_METRICO, IMPORTO_RICHIESTO, IMPORTO_AMMESSO, ID_PROGETTO, ID_DOMANDA_PAGAMENTO, ID_PROGRAMMAZIONE, DESCRIZIONE, DATA_VARIAZIONE, OPERATORE_VARIAZIONE, COD_TIPO_INVESTIMENTO, COD_STP, ID_UNITA_MISURA, QUANTITA, COSTO_INVESTIMENTO, SPESE_GENERALI, CONTRIBUTO_RICHIESTO_INVESTIMENTO, QUOTA_CONTRIBUTO_RICHIESTO, ID_SETTORE_PRODUTTIVO, ID_PRIORITA_SETTORIALE, ID_OBIETTIVO_MISURA, ID_CODIFICA_INVESTIMENTO, ID_DETTAGLIO_INVESTIMENTO, ID_SPECIFICA_INVESTIMENTO, INVESTIMENTO_AMMESSO, ISTRUTTORE_INVESTIMENTO, ID_INVESTIMENTO_ORIGINALE, DATA_VALUTAZIONE_INVESTIMENTO, VALUTAZIONE_INVESTIMENTO, ID_VARIANTE, IMPORTO_COMPUTO_METRICO_AMMESSO, CONTRIBUTO_RICHIESTO_RECUPERO_ANTICIPO, CONTRIBUTO_AMMESSO_RECUPERO_ANTICIPO, NOTE_ISTRUTTORE, COD_SANZIONE_VARIAZIONE_INVESTIMENTI, IMPORTO_DISAVANZO_COSTI_AMMESSI, CONTRIBUTO_DISAVANZO_COSTI_AMMESSI, CONTRIBUTO_RICHIESTO_ALTRE_FONTI, CONTRIBUTO_AMMESSO_ALTRE_FONTI FROM vPAGAMENTI_RICHIESTI WHERE 1=1';
	IF (@IdPagamentoRichiestoequalthis IS NOT NULL) BEGIN SET @sql = @sql + ' AND (ID_PAGAMENTO_RICHIESTO = @IdPagamentoRichiestoequalthis)'; set @lensql=@lensql+len(@IdPagamentoRichiestoequalthis);end;
	IF (@IdInvestimentoequalthis IS NOT NULL) BEGIN SET @sql = @sql + ' AND (ID_INVESTIMENTO = @IdInvestimentoequalthis)'; set @lensql=@lensql+len(@IdInvestimentoequalthis);end;
	IF (@IdProgettoequalthis IS NOT NULL) BEGIN SET @sql = @sql + ' AND (ID_PROGETTO = @IdProgettoequalthis)'; set @lensql=@lensql+len(@IdProgettoequalthis);end;
	IF (@IdDomandaPagamentoequalthis IS NOT NULL) BEGIN SET @sql = @sql + ' AND (ID_DOMANDA_PAGAMENTO = @IdDomandaPagamentoequalthis)'; set @lensql=@lensql+len(@IdDomandaPagamentoequalthis);end;
	set @sql = @sql + 'ORDER BY ID_DOMANDA_PAGAMENTO, DATA_RICHIESTA_PAGAMENTO';
	set @lensql=@lensql+len(@sql);
	if (@lensql<3000)
	exec sp_executesql @sql,N'@IdPagamentoRichiestoequalthis INT, @IdInvestimentoequalthis INT, @IdProgettoequalthis INT, @IdDomandaPagamentoequalthis INT',@IdPagamentoRichiestoequalthis , @IdInvestimentoequalthis , @IdProgettoequalthis , @IdDomandaPagamentoequalthis ;
	else
		SELECT ID_PAGAMENTO_RICHIESTO, ID_INVESTIMENTO, DATA_RICHIESTA_PAGAMENTO, CONTRIBUTO_RICHIESTO, CONTRIBUTO_AMMESSO, AMMESSO, ISTRUTTORE, DATA_VALUTAZIONE, IMPORTO_COMPUTO_METRICO, IMPORTO_RICHIESTO, IMPORTO_AMMESSO, ID_PROGETTO, ID_DOMANDA_PAGAMENTO, ID_PROGRAMMAZIONE, DESCRIZIONE, DATA_VARIAZIONE, OPERATORE_VARIAZIONE, COD_TIPO_INVESTIMENTO, COD_STP, ID_UNITA_MISURA, QUANTITA, COSTO_INVESTIMENTO, SPESE_GENERALI, CONTRIBUTO_RICHIESTO_INVESTIMENTO, QUOTA_CONTRIBUTO_RICHIESTO, ID_SETTORE_PRODUTTIVO, ID_PRIORITA_SETTORIALE, ID_OBIETTIVO_MISURA, ID_CODIFICA_INVESTIMENTO, ID_DETTAGLIO_INVESTIMENTO, ID_SPECIFICA_INVESTIMENTO, INVESTIMENTO_AMMESSO, ISTRUTTORE_INVESTIMENTO, ID_INVESTIMENTO_ORIGINALE, DATA_VALUTAZIONE_INVESTIMENTO, VALUTAZIONE_INVESTIMENTO, ID_VARIANTE, IMPORTO_COMPUTO_METRICO_AMMESSO, CONTRIBUTO_RICHIESTO_RECUPERO_ANTICIPO, CONTRIBUTO_AMMESSO_RECUPERO_ANTICIPO, NOTE_ISTRUTTORE, COD_SANZIONE_VARIAZIONE_INVESTIMENTI, IMPORTO_DISAVANZO_COSTI_AMMESSI, CONTRIBUTO_DISAVANZO_COSTI_AMMESSI, CONTRIBUTO_RICHIESTO_ALTRE_FONTI, CONTRIBUTO_AMMESSO_ALTRE_FONTI
		FROM vPAGAMENTI_RICHIESTI
		WHERE 
			((@IdPagamentoRichiestoequalthis IS NULL) OR ID_PAGAMENTO_RICHIESTO = @IdPagamentoRichiestoequalthis) AND 
			((@IdInvestimentoequalthis IS NULL) OR ID_INVESTIMENTO = @IdInvestimentoequalthis) AND 
			((@IdProgettoequalthis IS NULL) OR ID_PROGETTO = @IdProgettoequalthis) AND 
			((@IdDomandaPagamentoequalthis IS NULL) OR ID_DOMANDA_PAGAMENTO = @IdDomandaPagamentoequalthis)
		ORDER BY ID_DOMANDA_PAGAMENTO, DATA_RICHIESTA_PAGAMENTO


GO
EXECUTE sp_addextendedproperty @name = N'backup', @value = NULL, @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'PROCEDURE', @level1name = N'ZPagamentiRichiestiFindFind';

