CREATE PROCEDURE [dbo].[ZQuadrodomandaInsert]
(
	@DENOMINAZIONE VARCHAR(70), 
	@DESCRIZIONE VARCHAR(500), 
	@METODO_REPORT VARCHAR(50)
)
AS
	INSERT INTO QUADRO_DOMANDA
	(
		DENOMINAZIONE, 
		DESCRIZIONE, 
		METODO_REPORT
	)
	VALUES
	(
		@DENOMINAZIONE, 
		@DESCRIZIONE, 
		@METODO_REPORT
	)
	SELECT SCOPE_IDENTITY() AS ID_QUADRO
