CREATE PROCEDURE [dbo].[ZRegistroIrregolaritaInsert]
(
	@SegnalazioneOlaf BIT, 
	@DataSegnalazione DATETIME, 
	@TrimestreSegnalazione VARCHAR(255), 
	@DataModifica DATETIME, 
	@CfModifica VARCHAR(255), 
	@DataInserimento DATETIME, 
	@CfInserimento VARCHAR(255), 
	@IdProgetto INT, 
	@NumeroRiferimentoOlaf VARCHAR(255), 
	@SospettoFrode BIT, 
	@ImportoIrregolareCertificato DECIMAL(15,2), 
	@ImportoIrregolareDaRecuperare DECIMAL(15,2), 
	@Anno INT, 
	@PeriodoProgrammazione VARCHAR(500), 
	@NumeroRiferimentoNazionale VARCHAR(255), 
	@AzionePenale BIT, 
	@DataCreazioneIdentificazione DATETIME, 
	@TrimestreIdentificazione VARCHAR(255), 
	@ProcedimentoAmministrativo BIT, 
	@AzioneGiudiziaria BIT, 
	@DataPrimaInformazioneSospetto DATETIME, 
	@FontePrimaInformazioneSospetto VARCHAR(255), 
	@DataIrregolarita DATETIME, 
	@DataIrregolaritaDa DATETIME, 
	@DataIrregolaritaA DATETIME, 
	@CommessaA VARCHAR(max), 
	@IdCategoriaIrregolarita INT, 
	@IdTipoIrregolarita INT, 
	@ModusOperandi VARCHAR(max), 
	@DichiarazioneOperatore VARCHAR(max), 
	@AccertamentiAmministratore VARCHAR(max), 
	@IdClassificazioneIrregolarita INT, 
	@DataPrimoAttoConstatazioneAmministrativo DATETIME, 
	@IdMotivoEsecuzioneControllo INT, 
	@IdTipoControllo INT, 
	@IdControlloPrimaDopoPagamento INT, 
	@AutoritaControllo VARCHAR(255), 
	@IndagineOlaf BIT, 
	@ImportoSpesaUe DECIMAL(15,2), 
	@ImportoSpesaNazionale DECIMAL(15,2), 
	@ImportoSpesaPubblico DECIMAL(15,2), 
	@ImportoSpesaPrivato DECIMAL(15,2), 
	@ImportoSpesaTotale DECIMAL(15,2), 
	@ImportoIrregolaritaUe DECIMAL(15,2), 
	@ImportoIrregolaritaNazionale DECIMAL(15,2), 
	@ImportoIrregolaritaPubblico DECIMAL(15,2), 
	@ImportoIrregolaritaPrivato DECIMAL(15,2), 
	@ImportoIrregolaritaTotale DECIMAL(15,2), 
	@ImportoIrregolaritaNonPagatoUe DECIMAL(15,2), 
	@ImportoIrregolaritaNonPagatoNazionale DECIMAL(15,2), 
	@ImportoIrregolaritaNonPagatoPubblico DECIMAL(15,2), 
	@ImportoIrregolaritaNonPagatoPrivato DECIMAL(15,2), 
	@ImportoIrregolaritaNonPagatoTotale DECIMAL(15,2), 
	@ImportoIrregolaritaPagatoUe DECIMAL(15,2), 
	@ImportoIrregolaritaPagatoNazionale DECIMAL(15,2), 
	@ImportoIrregolaritaPagatoPubblico DECIMAL(15,2), 
	@ImportoIrregolaritaPagatoPrivato DECIMAL(15,2), 
	@ImportoIrregolaritaPagatoTotale DECIMAL(15,2), 
	@ImportoDaRecuperareUe DECIMAL(15,2), 
	@ImportoDaRecuperareNazionale DECIMAL(15,2), 
	@ImportoDaRecuperarePubblico DECIMAL(15,2), 
	@ImportoDaRecuperarePrivato DECIMAL(15,2), 
	@ImportoDaRecuperareTotale DECIMAL(15,2), 
	@SpesaDecertificata BIT, 
	@CommentiImpattoFinanziario VARCHAR(max), 
	@IdFondo INT, 
	@IdControlloOrigine INT, 
	@IdStatoFinanziario INT, 
	@DescrizioneControlloEsterno VARCHAR(max), 
	@IdImpresaCommessaDa INT, 
	@NoteCommessaDa VARCHAR(max), 
	@StabilitaOperazioni BIT, 
	@IdDomandaPagamento INT
)
AS
	SET @DataSegnalazione = ISNULL(@DataSegnalazione,(getdate()))
	SET @DataModifica = ISNULL(@DataModifica,(getdate()))
	SET @DataInserimento = ISNULL(@DataInserimento,(getdate()))
	INSERT INTO REGISTRO_IRREGOLARITA
	(
		SEGNALAZIONE_OLAF, 
		DATA_SEGNALAZIONE, 
		TRIMESTRE_SEGNALAZIONE, 
		DATA_MODIFICA, 
		CF_MODIFICA, 
		DATA_INSERIMENTO, 
		CF_INSERIMENTO, 
		ID_PROGETTO, 
		NUMERO_RIFERIMENTO_OLAF, 
		SOSPETTO_FRODE, 
		IMPORTO_IRREGOLARE_CERTIFICATO, 
		IMPORTO_IRREGOLARE_DA_RECUPERARE, 
		ANNO, 
		PERIODO_PROGRAMMAZIONE, 
		NUMERO_RIFERIMENTO_NAZIONALE, 
		AZIONE_PENALE, 
		DATA_CREAZIONE_IDENTIFICAZIONE, 
		TRIMESTRE_IDENTIFICAZIONE, 
		PROCEDIMENTO_AMMINISTRATIVO, 
		AZIONE_GIUDIZIARIA, 
		DATA_PRIMA_INFORMAZIONE_SOSPETTO, 
		FONTE_PRIMA_INFORMAZIONE_SOSPETTO, 
		DATA_IRREGOLARITA, 
		DATA_IRREGOLARITA_DA, 
		DATA_IRREGOLARITA_A, 
		COMMESSA_A, 
		ID_CATEGORIA_IRREGOLARITA, 
		ID_TIPO_IRREGOLARITA, 
		MODUS_OPERANDI, 
		DICHIARAZIONE_OPERATORE, 
		ACCERTAMENTI_AMMINISTRATORE, 
		ID_CLASSIFICAZIONE_IRREGOLARITA, 
		DATA_PRIMO_ATTO_CONSTATAZIONE_AMMINISTRATIVO, 
		ID_MOTIVO_ESECUZIONE_CONTROLLO, 
		ID_TIPO_CONTROLLO, 
		ID_CONTROLLO_PRIMA_DOPO_PAGAMENTO, 
		AUTORITA_CONTROLLO, 
		INDAGINE_OLAF, 
		IMPORTO_SPESA_UE, 
		IMPORTO_SPESA_NAZIONALE, 
		IMPORTO_SPESA_PUBBLICO, 
		IMPORTO_SPESA_PRIVATO, 
		IMPORTO_SPESA_TOTALE, 
		IMPORTO_IRREGOLARITA_UE, 
		IMPORTO_IRREGOLARITA_NAZIONALE, 
		IMPORTO_IRREGOLARITA_PUBBLICO, 
		IMPORTO_IRREGOLARITA_PRIVATO, 
		IMPORTO_IRREGOLARITA_TOTALE, 
		IMPORTO_IRREGOLARITA_NON_PAGATO_UE, 
		IMPORTO_IRREGOLARITA_NON_PAGATO_NAZIONALE, 
		IMPORTO_IRREGOLARITA_NON_PAGATO_PUBBLICO, 
		IMPORTO_IRREGOLARITA_NON_PAGATO_PRIVATO, 
		IMPORTO_IRREGOLARITA_NON_PAGATO_TOTALE, 
		IMPORTO_IRREGOLARITA_PAGATO_UE, 
		IMPORTO_IRREGOLARITA_PAGATO_NAZIONALE, 
		IMPORTO_IRREGOLARITA_PAGATO_PUBBLICO, 
		IMPORTO_IRREGOLARITA_PAGATO_PRIVATO, 
		IMPORTO_IRREGOLARITA_PAGATO_TOTALE, 
		IMPORTO_DA_RECUPERARE_UE, 
		IMPORTO_DA_RECUPERARE_NAZIONALE, 
		IMPORTO_DA_RECUPERARE_PUBBLICO, 
		IMPORTO_DA_RECUPERARE_PRIVATO, 
		IMPORTO_DA_RECUPERARE_TOTALE, 
		SPESA_DECERTIFICATA, 
		COMMENTI_IMPATTO_FINANZIARIO, 
		ID_FONDO, 
		ID_CONTROLLO_ORIGINE, 
		ID_STATO_FINANZIARIO, 
		DESCRIZIONE_CONTROLLO_ESTERNO, 
		ID_IMPRESA_COMMESSA_DA, 
		NOTE_COMMESSA_DA, 
		STABILITA_OPERAZIONI, 
		ID_DOMANDA_PAGAMENTO
	)
	VALUES
	(
		@SegnalazioneOlaf, 
		@DataSegnalazione, 
		@TrimestreSegnalazione, 
		@DataModifica, 
		@CfModifica, 
		@DataInserimento, 
		@CfInserimento, 
		@IdProgetto, 
		@NumeroRiferimentoOlaf, 
		@SospettoFrode, 
		@ImportoIrregolareCertificato, 
		@ImportoIrregolareDaRecuperare, 
		@Anno, 
		@PeriodoProgrammazione, 
		@NumeroRiferimentoNazionale, 
		@AzionePenale, 
		@DataCreazioneIdentificazione, 
		@TrimestreIdentificazione, 
		@ProcedimentoAmministrativo, 
		@AzioneGiudiziaria, 
		@DataPrimaInformazioneSospetto, 
		@FontePrimaInformazioneSospetto, 
		@DataIrregolarita, 
		@DataIrregolaritaDa, 
		@DataIrregolaritaA, 
		@CommessaA, 
		@IdCategoriaIrregolarita, 
		@IdTipoIrregolarita, 
		@ModusOperandi, 
		@DichiarazioneOperatore, 
		@AccertamentiAmministratore, 
		@IdClassificazioneIrregolarita, 
		@DataPrimoAttoConstatazioneAmministrativo, 
		@IdMotivoEsecuzioneControllo, 
		@IdTipoControllo, 
		@IdControlloPrimaDopoPagamento, 
		@AutoritaControllo, 
		@IndagineOlaf, 
		@ImportoSpesaUe, 
		@ImportoSpesaNazionale, 
		@ImportoSpesaPubblico, 
		@ImportoSpesaPrivato, 
		@ImportoSpesaTotale, 
		@ImportoIrregolaritaUe, 
		@ImportoIrregolaritaNazionale, 
		@ImportoIrregolaritaPubblico, 
		@ImportoIrregolaritaPrivato, 
		@ImportoIrregolaritaTotale, 
		@ImportoIrregolaritaNonPagatoUe, 
		@ImportoIrregolaritaNonPagatoNazionale, 
		@ImportoIrregolaritaNonPagatoPubblico, 
		@ImportoIrregolaritaNonPagatoPrivato, 
		@ImportoIrregolaritaNonPagatoTotale, 
		@ImportoIrregolaritaPagatoUe, 
		@ImportoIrregolaritaPagatoNazionale, 
		@ImportoIrregolaritaPagatoPubblico, 
		@ImportoIrregolaritaPagatoPrivato, 
		@ImportoIrregolaritaPagatoTotale, 
		@ImportoDaRecuperareUe, 
		@ImportoDaRecuperareNazionale, 
		@ImportoDaRecuperarePubblico, 
		@ImportoDaRecuperarePrivato, 
		@ImportoDaRecuperareTotale, 
		@SpesaDecertificata, 
		@CommentiImpattoFinanziario, 
		@IdFondo, 
		@IdControlloOrigine, 
		@IdStatoFinanziario, 
		@DescrizioneControlloEsterno, 
		@IdImpresaCommessaDa, 
		@NoteCommessaDa, 
		@StabilitaOperazioni, 
		@IdDomandaPagamento
	)
	SELECT @DataSegnalazione AS DATA_SEGNALAZIONE, @DataModifica AS DATA_MODIFICA, @DataInserimento AS DATA_INSERIMENTO, SCOPE_IDENTITY() AS ID_IRREGOLARITA


GO
EXECUTE sp_addextendedproperty @name = N'backup', @value = 'CREATE PROCEDURE [dbo].[ZRegistroIrregolaritaInsert]
(
	@SegnalazioneOlaf BIT, 
	@DataSegnalazione DATETIME, 
	@TrimestreSegnalazione VARCHAR(255), 
	@DataModifica DATETIME, 
	@CfModifica VARCHAR(255), 
	@DataInserimento DATETIME, 
	@CfInserimento VARCHAR(255), 
	@IdProgetto INT, 
	@NumeroRiferimentoOlaf VARCHAR(255), 
	@SospettoFrode BIT, 
	@ImportoIrregolareCertificato DECIMAL(15,2), 
	@ImportoIrregolareDaRecuperare DECIMAL(15,2), 
	@Anno INT, 
	@PeriodoProgrammazione VARCHAR(500), 
	@NumeroRiferimentoNazionale VARCHAR(255), 
	@AzionePenale BIT, 
	@DataCreazioneIdentificazione DATETIME, 
	@TrimestreIdentificazione VARCHAR(255), 
	@ProcedimentoAmministrativo BIT, 
	@AzioneGiudiziaria BIT, 
	@DataPrimaInformazioneSospetto DATETIME, 
	@FontePrimaInformazioneSospetto VARCHAR(255), 
	@DataIrregolarita DATETIME, 
	@DataIrregolaritaDa DATETIME, 
	@DataIrregolaritaA DATETIME, 
	@CommessaA VARCHAR(max), 
	@IdCategoriaIrregolarita INT, 
	@IdTipoIrregolarita INT, 
	@ModusOperandi VARCHAR(max), 
	@DichiarazioneOperatore VARCHAR(max), 
	@AccertamentiAmministratore VARCHAR(max), 
	@IdClassificazioneIrregolarita INT, 
	@DataPrimoAttoConstatazioneAmministrativo DATETIME, 
	@IdMotivoEsecuzioneControllo INT, 
	@IdTipoControllo INT, 
	@IdControlloPrimaDopoPagamento INT, 
	@AutoritaControllo VARCHAR(255), 
	@IndagineOlaf BIT, 
	@ImportoSpesaUe DECIMAL(15,2), 
	@ImportoSpesaNazionale DECIMAL(15,2), 
	@ImportoSpesaPubblico DECIMAL(15,2), 
	@ImportoSpesaPrivato DECIMAL(15,2), 
	@ImportoSpesaTotale DECIMAL(15,2), 
	@ImportoIrregolaritaUe DECIMAL(15,2), 
	@ImportoIrregolaritaNazionale DECIMAL(15,2), 
	@ImportoIrregolaritaPubblico DECIMAL(15,2), 
	@ImportoIrregolaritaPrivato DECIMAL(15,2), 
	@ImportoIrregolaritaTotale DECIMAL(15,2), 
	@ImportoIrregolaritaNonPagatoUe DECIMAL(15,2), 
	@ImportoIrregolaritaNonPagatoNazionale DECIMAL(15,2), 
	@ImportoIrregolaritaNonPagatoPubblico DECIMAL(15,2), 
	@ImportoIrregolaritaNonPagatoPrivato DECIMAL(15,2), 
	@ImportoIrregolaritaNonPagatoTotale DECIMAL(15,2), 
	@ImportoIrregolaritaPagatoUe DECIMAL(15,2), 
	@ImportoIrregolaritaPagatoNazionale DECIMAL(15,2), 
	@ImportoIrregolaritaPagatoPubblico DECIMAL(15,2), 
	@ImportoIrregolaritaPagatoPrivato DECIMAL(15,2), 
	@ImportoIrregolaritaPagatoTotale DECIMAL(15,2), 
	@ImportoDaRecuperareUe DECIMAL(15,2), 
	@ImportoDaRecuperareNazionale DECIMAL(15,2), 
	@ImportoDaRecuperarePubblico DECIMAL(15,2), 
	@ImportoDaRecuperarePrivato DECIMAL(15,2), 
	@ImportoDaRecuperareTotale DECIMAL(15,2), 
	@SpesaDecertificata BIT, 
	@CommentiImpattoFinanziario VARCHAR(max), 
	@IdFondo INT, 
	@IdControlloOrigine INT, 
	@IdStatoFinanziario INT, 
	@DescrizioneControlloEsterno VARCHAR(max), 
	@IdImpresaCommessaDa INT, 
	@NoteCommessaDa VARCHAR(max), 
	@StabilitaOperazioni BIT
)
AS
	SET @DataSegnalazione = ISNULL(@DataSegnalazione,(getdate()))
	SET @DataModifica = ISNULL(@DataModifica,(getdate()))
	SET @DataInserimento = ISNULL(@DataInserimento,(getdate()))
	INSERT INTO REGISTRO_IRREGOLARITA
	(
		SEGNALAZIONE_OLAF, 
		DATA_SEGNALAZIONE, 
		TRIMESTRE_SEGNALAZIONE, 
		DATA_MODIFICA, 
		CF_MODIFICA, 
		DATA_INSERIMENTO, 
		CF_INSERIMENTO, 
		ID_PROGETTO, 
		NUMERO_RIFERIMENTO_OLAF, 
		SOSPETTO_FRODE, 
		IMPORTO_IRREGOLARE_CERTIFICATO, 
		IMPORTO_IRREGOLARE_DA_RECUPERARE, 
		ANNO, 
		PERIODO_PROGRAMMAZIONE, 
		NUMERO_RIFERIMENTO_NAZIONALE, 
		AZIONE_PENALE, 
		DATA_CREAZIONE_IDENTIFICAZIONE, 
		TRIMESTRE_IDENTIFICAZIONE, 
		PROCEDIMENTO_AMMINISTRATIVO, 
		AZIONE_GIUDIZIARIA, 
		DATA_PRIMA_INFORMAZIONE_SOSPETTO, 
		FONTE_PRIMA_INFORMAZIONE_SOSPETTO, 
		DATA_IRREGOLARITA, 
		DATA_IRREGOLARITA_DA, 
		DATA_IRREGOLARITA_A, 
		COMMESSA_A, 
		ID_CATEGORIA_IRREGOLARITA, 
		ID_TIPO_IRREGOLARITA, 
		MODUS_OPERANDI, 
		DICHIARAZIONE_OPERATORE, 
		ACCERTAMENTI_AMMINISTRATORE, 
		ID_CLASSIFICAZIONE_IRREGOLARITA, 
		DATA_PRIMO_ATTO_CONSTATAZIONE_AMMINISTRATIVO, 
		ID_MOTIVO_ESECUZIONE_CONTROLLO, 
		ID_TIP', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'PROCEDURE', @level1name = N'ZRegistroIrregolaritaInsert';

