CREATE PROCEDURE [dbo].[ZRegistroRecuperoInsert]
(
	@DataInserimento DATETIME, 
	@CfInserimento VARCHAR(255), 
	@DataModifica DATETIME, 
	@CfModifica VARCHAR(255), 
	@IdRegistroIrregolarita INT, 
	@DataAvvio DATETIME, 
	@DataProbabileConclusione DATETIME, 
	@ImportoDaRecuperareUe DECIMAL(15,2), 
	@ImportoDaRecuperareNazionale DECIMAL(15,2), 
	@ImportoDaRecuperarePubblico DECIMAL(15,2), 
	@ImportoDetrattoUe DECIMAL(15,2), 
	@ImportoDetrattoNazionale DECIMAL(15,2), 
	@ImportoDetrattoPubblico DECIMAL(15,2), 
	@ImportoRecuperatoUe DECIMAL(15,2), 
	@ImportoRecuperatoPubblico DECIMAL(15,2), 
	@ImportoRecuperatoNazionale DECIMAL(15,2), 
	@SaldoDaRecuperareUe DECIMAL(15,2), 
	@SaldoDaRecuperareNazionale DECIMAL(15,2), 
	@SaldoDaRecuperarePubblico DECIMAL(15,2), 
	@ImportoVersatoUe DECIMAL(15,2), 
	@ImportoRitenutoStato DECIMAL(15,2), 
	@DataConclusione DATETIME, 
	@IdProcedureAvviate INT, 
	@IdTipoProcedureAvviate INT, 
	@DataAvvioProcedure DATETIME, 
	@DataProbabileConclusioneProcedure DATETIME, 
	@IdTipoRecupero INT, 
	@IdOrigineRecupero INT, 
	@IdStoricoRecuperoPrecedente INT, 
	@IdProgetto INT, 
	@Storico BIT, 
	@ImportoInteressiLegali DECIMAL(15,2), 
	@ImportoInteressiMora DECIMAL(15,2), 
	@ImportoGestionePratica DECIMAL(15,2), 
	@DataRegistrazioneRitiro DATETIME, 
	@DataCertificazioneRecupero DATETIME, 
	@DataCertificazioneRitiro DATETIME, 
	@GestioneRate BIT, 
	@NumeroRate INT, 
	@DataInizioRate DATETIME, 
	@ImportoRata DECIMAL(15,2), 
	@IntervalloRateMesi INT, 
	@ImportoDaRecuperarePrivato DECIMAL(15,2), 
	@ImportoDaRecuperareTotale DECIMAL(15,2), 
	@ImportoDetrattoPrivato DECIMAL(15,2), 
	@ImportoRecuperatoPrivato DECIMAL(15,2), 
	@ImportoRecuperatoTotale DECIMAL(15,2), 
	@SaldoDaRecuperarePrivato DECIMAL(15,2), 
	@SaldoDaRecuperareTotale DECIMAL(15,2), 
	@SoggettoRevocaFinanziamento VARCHAR(2000), 
	@IdAttoRecupero INT, 
	@IdAttoRitiro INT, 
	@IdAttoNonRecuperabilita INT, 
	@Recuperabile BIT, 
	@ImportoDetrattoTotale DECIMAL(15,2), 
	@DataCertificazioneNonRecuperabilita DATETIME, 
	@DataRegistrazioneNonRecuperabilita DATETIME, 
	@DataSegnatura DATETIME, 
	@Segnatura VARCHAR(255)
)
AS
	SET @DataInserimento = ISNULL(@DataInserimento,(getdate()))
	SET @DataModifica = ISNULL(@DataModifica,(getdate()))
	SET @Storico = ISNULL(@Storico,((0)))
	SET @GestioneRate = ISNULL(@GestioneRate,((0)))
	SET @IntervalloRateMesi = ISNULL(@IntervalloRateMesi,((1)))
	SET @Recuperabile = ISNULL(@Recuperabile,((1)))
	INSERT INTO REGISTRO_RECUPERO
	(
		DATA_INSERIMENTO, 
		CF_INSERIMENTO, 
		DATA_MODIFICA, 
		CF_MODIFICA, 
		ID_REGISTRO_IRREGOLARITA, 
		DATA_AVVIO, 
		DATA_PROBABILE_CONCLUSIONE, 
		IMPORTO_DA_RECUPERARE_UE, 
		IMPORTO_DA_RECUPERARE_NAZIONALE, 
		IMPORTO_DA_RECUPERARE_PUBBLICO, 
		IMPORTO_DETRATTO_UE, 
		IMPORTO_DETRATTO_NAZIONALE, 
		IMPORTO_DETRATTO_PUBBLICO, 
		IMPORTO_RECUPERATO_UE, 
		IMPORTO_RECUPERATO_PUBBLICO, 
		IMPORTO_RECUPERATO_NAZIONALE, 
		SALDO_DA_RECUPERARE_UE, 
		SALDO_DA_RECUPERARE_NAZIONALE, 
		SALDO_DA_RECUPERARE_PUBBLICO, 
		IMPORTO_VERSATO_UE, 
		IMPORTO_RITENUTO_STATO, 
		DATA_CONCLUSIONE, 
		ID_PROCEDURE_AVVIATE, 
		ID_TIPO_PROCEDURE_AVVIATE, 
		DATA_AVVIO_PROCEDURE, 
		DATA_PROBABILE_CONCLUSIONE_PROCEDURE, 
		ID_TIPO_RECUPERO, 
		ID_ORIGINE_RECUPERO, 
		ID_STORICO_RECUPERO_PRECEDENTE, 
		ID_PROGETTO, 
		STORICO, 
		IMPORTO_INTERESSI_LEGALI, 
		IMPORTO_INTERESSI_MORA, 
		IMPORTO_GESTIONE_PRATICA, 
		DATA_REGISTRAZIONE_RITIRO, 
		DATA_CERTIFICAZIONE_RECUPERO, 
		DATA_CERTIFICAZIONE_RITIRO, 
		GESTIONE_RATE, 
		NUMERO_RATE, 
		DATA_INIZIO_RATE, 
		IMPORTO_RATA, 
		INTERVALLO_RATE_MESI, 
		IMPORTO_DA_RECUPERARE_PRIVATO, 
		IMPORTO_DA_RECUPERARE_TOTALE, 
		IMPORTO_DETRATTO_PRIVATO, 
		IMPORTO_RECUPERATO_PRIVATO, 
		IMPORTO_RECUPERATO_TOTALE, 
		SALDO_DA_RECUPERARE_PRIVATO, 
		SALDO_DA_RECUPERARE_TOTALE, 
		SOGGETTO_REVOCA_FINANZIAMENTO, 
		ID_ATTO_RECUPERO, 
		ID_ATTO_RITIRO, 
		ID_ATTO_NON_RECUPERABILITA, 
		RECUPERABILE, 
		IMPORTO_DETRATTO_TOTALE, 
		DATA_CERTIFICAZIONE_NON_RECUPERABILITA, 
		DATA_REGISTRAZIONE_NON_RECUPERABILITA, 
		DATA_SEGNATURA, 
		SEGNATURA
	)
	VALUES
	(
		@DataInserimento, 
		@CfInserimento, 
		@DataModifica, 
		@CfModifica, 
		@IdRegistroIrregolarita, 
		@DataAvvio, 
		@DataProbabileConclusione, 
		@ImportoDaRecuperareUe, 
		@ImportoDaRecuperareNazionale, 
		@ImportoDaRecuperarePubblico, 
		@ImportoDetrattoUe, 
		@ImportoDetrattoNazionale, 
		@ImportoDetrattoPubblico, 
		@ImportoRecuperatoUe, 
		@ImportoRecuperatoPubblico, 
		@ImportoRecuperatoNazionale, 
		@SaldoDaRecuperareUe, 
		@SaldoDaRecuperareNazionale, 
		@SaldoDaRecuperarePubblico, 
		@ImportoVersatoUe, 
		@ImportoRitenutoStato, 
		@DataConclusione, 
		@IdProcedureAvviate, 
		@IdTipoProcedureAvviate, 
		@DataAvvioProcedure, 
		@DataProbabileConclusioneProcedure, 
		@IdTipoRecupero, 
		@IdOrigineRecupero, 
		@IdStoricoRecuperoPrecedente, 
		@IdProgetto, 
		@Storico, 
		@ImportoInteressiLegali, 
		@ImportoInteressiMora, 
		@ImportoGestionePratica, 
		@DataRegistrazioneRitiro, 
		@DataCertificazioneRecupero, 
		@DataCertificazioneRitiro, 
		@GestioneRate, 
		@NumeroRate, 
		@DataInizioRate, 
		@ImportoRata, 
		@IntervalloRateMesi, 
		@ImportoDaRecuperarePrivato, 
		@ImportoDaRecuperareTotale, 
		@ImportoDetrattoPrivato, 
		@ImportoRecuperatoPrivato, 
		@ImportoRecuperatoTotale, 
		@SaldoDaRecuperarePrivato, 
		@SaldoDaRecuperareTotale, 
		@SoggettoRevocaFinanziamento, 
		@IdAttoRecupero, 
		@IdAttoRitiro, 
		@IdAttoNonRecuperabilita, 
		@Recuperabile, 
		@ImportoDetrattoTotale, 
		@DataCertificazioneNonRecuperabilita, 
		@DataRegistrazioneNonRecuperabilita, 
		@DataSegnatura, 
		@Segnatura
	)
	SELECT SCOPE_IDENTITY() AS ID_REGISTRO_RECUPERO, @DataInserimento AS DATA_INSERIMENTO, @DataModifica AS DATA_MODIFICA, @Storico AS STORICO, @GestioneRate AS GESTIONE_RATE, @IntervalloRateMesi AS INTERVALLO_RATE_MESI, @Recuperabile AS RECUPERABILE


GO
EXECUTE sp_addextendedproperty @name = N'backup', @value = 'CREATE PROCEDURE [dbo].[ZRegistroRecuperoInsert]
(
	@DataInserimento DATETIME, 
	@CfInserimento VARCHAR(255), 
	@DataModifica DATETIME, 
	@CfModifica VARCHAR(255), 
	@IdRegistroIrregolarita INT, 
	@DataAvvio DATETIME, 
	@DataProbabileConclusione DATETIME, 
	@ImportoDaRecuperareUe DECIMAL(15,2), 
	@ImportoDaRecuperareNazionale DECIMAL(15,2), 
	@ImportoDaRecuperarePubblico DECIMAL(15,2), 
	@ImportoDetrattoUe DECIMAL(15,2), 
	@ImportoDetrattoNazionale DECIMAL(15,2), 
	@ImportoDetrattoPubblico DECIMAL(15,2), 
	@ImportoRecuperatoUe DECIMAL(15,2), 
	@ImportoRecuperatoPubblico DECIMAL(15,2), 
	@ImportoRecuperatoNazionale DECIMAL(15,2), 
	@SaldoDaRecuperareUe DECIMAL(15,2), 
	@SaldoDaRecuperareNazionale DECIMAL(15,2), 
	@SaldoDaRecuperarePubblico DECIMAL(15,2), 
	@ImportoVersatoUe DECIMAL(15,2), 
	@ImportoRitenutoStato DECIMAL(15,2), 
	@DataConclusione DATETIME, 
	@IdProcedureAvviate INT, 
	@IdTipoProcedureAvviate INT, 
	@DataAvvioProcedure DATETIME, 
	@DataProbabileConclusioneProcedure DATETIME, 
	@IdTipoRecupero INT, 
	@IdOrigineRecupero INT, 
	@IdStoricoRecuperoPrecedente INT, 
	@IdProgetto INT, 
	@Storico BIT, 
	@ImportoInteressiLegali DECIMAL(15,2), 
	@ImportoInteressiMora DECIMAL(15,2), 
	@ImportoGestionePratica DECIMAL(15,2), 
	@DataRegistrazioneRitiro DATETIME, 
	@DataCertificazioneRecupero DATETIME, 
	@DataCertificazioneRitiro DATETIME, 
	@GestioneRate BIT, 
	@NumeroRate INT, 
	@DataInizioRate DATETIME, 
	@ImportoRata DECIMAL(15,2), 
	@IntervalloRateMesi INT, 
	@ImportoDaRecuperarePrivato DECIMAL(15,2), 
	@ImportoDaRecuperareTotale DECIMAL(15,2), 
	@ImportoDetrattoPrivato DECIMAL(15,2), 
	@ImportoRecuperatoPrivato DECIMAL(15,2), 
	@ImportoRecuperatoTotale DECIMAL(15,2), 
	@SaldoDaRecuperarePrivato DECIMAL(15,2), 
	@SaldoDaRecuperareTotale DECIMAL(15,2), 
	@SoggettoRevocaFinanziamento VARCHAR(2000), 
	@IdAttoRecupero INT, 
	@IdAttoRitiro INT, 
	@IdAttoNonRecuperabilita INT, 
	@Recuperabile BIT, 
	@ImportoDetrattoTotale DECIMAL(15,2), 
	@DataCertificazioneNonRecuperabilita DATETIME, 
	@DataRegistrazioneNonRecuperabilita DATETIME
)
AS
	SET @DataInserimento = ISNULL(@DataInserimento,(getdate()))
	SET @DataModifica = ISNULL(@DataModifica,(getdate()))
	SET @Storico = ISNULL(@Storico,((0)))
	SET @GestioneRate = ISNULL(@GestioneRate,((0)))
	SET @IntervalloRateMesi = ISNULL(@IntervalloRateMesi,((1)))
	SET @Recuperabile = ISNULL(@Recuperabile,((1)))
	INSERT INTO REGISTRO_RECUPERO
	(
		DATA_INSERIMENTO, 
		CF_INSERIMENTO, 
		DATA_MODIFICA, 
		CF_MODIFICA, 
		ID_REGISTRO_IRREGOLARITA, 
		DATA_AVVIO, 
		DATA_PROBABILE_CONCLUSIONE, 
		IMPORTO_DA_RECUPERARE_UE, 
		IMPORTO_DA_RECUPERARE_NAZIONALE, 
		IMPORTO_DA_RECUPERARE_PUBBLICO, 
		IMPORTO_DETRATTO_UE, 
		IMPORTO_DETRATTO_NAZIONALE, 
		IMPORTO_DETRATTO_PUBBLICO, 
		IMPORTO_RECUPERATO_UE, 
		IMPORTO_RECUPERATO_PUBBLICO, 
		IMPORTO_RECUPERATO_NAZIONALE, 
		SALDO_DA_RECUPERARE_UE, 
		SALDO_DA_RECUPERARE_NAZIONALE, 
		SALDO_DA_RECUPERARE_PUBBLICO, 
		IMPORTO_VERSATO_UE, 
		IMPORTO_RITENUTO_STATO, 
		DATA_CONCLUSIONE, 
		ID_PROCEDURE_AVVIATE, 
		ID_TIPO_PROCEDURE_AVVIATE, 
		DATA_AVVIO_PROCEDURE, 
		DATA_PROBABILE_CONCLUSIONE_PROCEDURE, 
		ID_TIPO_RECUPERO, 
		ID_ORIGINE_RECUPERO, 
		ID_STORICO_RECUPERO_PRECEDENTE, 
		ID_PROGETTO, 
		STORICO, 
		IMPORTO_INTERESSI_LEGALI, 
		IMPORTO_INTERESSI_MORA, 
		IMPORTO_GESTIONE_PRATICA, 
		DATA_REGISTRAZIONE_RITIRO, 
		DATA_CERTIFICAZIONE_RECUPERO, 
		DATA_CERTIFICAZIONE_RITIRO, 
		GESTIONE_RATE, 
		NUMERO_RATE, 
		DATA_INIZIO_RATE, 
		IMPORTO_RATA, 
		INTERVALLO_RATE_MESI, 
		IMPORTO_DA_RECUPERARE_PRIVATO, 
		IMPORTO_DA_RECUPERARE_TOTALE, 
		IMPORTO_DETRATTO_PRIVATO, 
		IMPORTO_RECUPERATO_PRIVATO, 
		IMPORTO_RECUPERATO_TOTALE, 
		SALDO_DA_RECUPERARE_PRIVATO, 
		SALDO_DA_RECUPERARE_TOTALE, 
		SOGGETTO_REVOCA_FINANZIAMENTO, 
		ID_ATTO_RECUPERO, 
		ID_ATTO_RITIRO, 
		ID_ATTO_NON_RECUPERABILITA, 
		RECUPERABILE, 
		IMPORTO_DETRATTO_TOTA', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'PROCEDURE', @level1name = N'ZRegistroRecuperoInsert';

