CREATE PROCEDURE [dbo].[ZRegistroIrregolaritaUpdate]
(
	@SegnalazioneOlaf BIT, 
	@DataSegnalazione DATETIME, 
	@TrimestreSegnalazione VARCHAR(255), 
	@DataModifica DATETIME, 
	@CfModifica VARCHAR(255), 
	@DataInserimento DATETIME, 
	@CfInserimento VARCHAR(255), 
	@IdProgetto INT, 
	@IdIrregolarita INT, 
	@NumeroRiferimentoOlaf VARCHAR(255), 
	@SospettoFrode BIT, 
	@ImportoIrregolareCertificato DECIMAL(15,2), 
	@ImportoIrregolareDaRecuperare DECIMAL(15,2), 
	@Anno INT, 
	@PeriodoProgrammazione VARCHAR(500), 
	@NumeroRiferimentoNazionale VARCHAR(255), 
	@AzionePenale BIT, 
	@DataCreazioneIdentificazione DATETIME, 
	@TrimestreIdentificazione VARCHAR(255), 
	@ProcedimentoAmministrativo BIT, 
	@AzioneGiudiziaria BIT, 
	@DataPrimaInformazioneSospetto DATETIME, 
	@FontePrimaInformazioneSospetto VARCHAR(255), 
	@DataIrregolarita DATETIME, 
	@DataIrregolaritaDa DATETIME, 
	@DataIrregolaritaA DATETIME, 
	@CommessaA VARCHAR(max), 
	@IdCategoriaIrregolarita INT, 
	@IdTipoIrregolarita INT, 
	@ModusOperandi VARCHAR(max), 
	@DichiarazioneOperatore VARCHAR(max), 
	@AccertamentiAmministratore VARCHAR(max), 
	@IdClassificazioneIrregolarita INT, 
	@DataPrimoAttoConstatazioneAmministrativo DATETIME, 
	@IdMotivoEsecuzioneControllo INT, 
	@IdTipoControllo INT, 
	@IdControlloPrimaDopoPagamento INT, 
	@AutoritaControllo VARCHAR(255), 
	@IndagineOlaf BIT, 
	@ImportoSpesaUe DECIMAL(15,2), 
	@ImportoSpesaNazionale DECIMAL(15,2), 
	@ImportoSpesaPubblico DECIMAL(15,2), 
	@ImportoSpesaPrivato DECIMAL(15,2), 
	@ImportoSpesaTotale DECIMAL(15,2), 
	@ImportoIrregolaritaUe DECIMAL(15,2), 
	@ImportoIrregolaritaNazionale DECIMAL(15,2), 
	@ImportoIrregolaritaPubblico DECIMAL(15,2), 
	@ImportoIrregolaritaPrivato DECIMAL(15,2), 
	@ImportoIrregolaritaTotale DECIMAL(15,2), 
	@ImportoIrregolaritaNonPagatoUe DECIMAL(15,2), 
	@ImportoIrregolaritaNonPagatoNazionale DECIMAL(15,2), 
	@ImportoIrregolaritaNonPagatoPubblico DECIMAL(15,2), 
	@ImportoIrregolaritaNonPagatoPrivato DECIMAL(15,2), 
	@ImportoIrregolaritaNonPagatoTotale DECIMAL(15,2), 
	@ImportoIrregolaritaPagatoUe DECIMAL(15,2), 
	@ImportoIrregolaritaPagatoNazionale DECIMAL(15,2), 
	@ImportoIrregolaritaPagatoPubblico DECIMAL(15,2), 
	@ImportoIrregolaritaPagatoPrivato DECIMAL(15,2), 
	@ImportoIrregolaritaPagatoTotale DECIMAL(15,2), 
	@ImportoDaRecuperareUe DECIMAL(15,2), 
	@ImportoDaRecuperareNazionale DECIMAL(15,2), 
	@ImportoDaRecuperarePubblico DECIMAL(15,2), 
	@ImportoDaRecuperarePrivato DECIMAL(15,2), 
	@ImportoDaRecuperareTotale DECIMAL(15,2), 
	@SpesaDecertificata BIT, 
	@CommentiImpattoFinanziario VARCHAR(max), 
	@IdFondo INT, 
	@IdControlloOrigine INT, 
	@IdStatoFinanziario INT, 
	@DescrizioneControlloEsterno VARCHAR(max), 
	@IdImpresaCommessaDa INT, 
	@NoteCommessaDa VARCHAR(max), 
	@StabilitaOperazioni BIT, 
	@IdDomandaPagamento INT
)
AS
	SET @DataModifica=getdate()
	UPDATE REGISTRO_IRREGOLARITA
	SET
		SEGNALAZIONE_OLAF = @SegnalazioneOlaf, 
		DATA_SEGNALAZIONE = @DataSegnalazione, 
		TRIMESTRE_SEGNALAZIONE = @TrimestreSegnalazione, 
		DATA_MODIFICA = @DataModifica, 
		CF_MODIFICA = @CfModifica, 
		DATA_INSERIMENTO = @DataInserimento, 
		CF_INSERIMENTO = @CfInserimento, 
		ID_PROGETTO = @IdProgetto, 
		NUMERO_RIFERIMENTO_OLAF = @NumeroRiferimentoOlaf, 
		SOSPETTO_FRODE = @SospettoFrode, 
		IMPORTO_IRREGOLARE_CERTIFICATO = @ImportoIrregolareCertificato, 
		IMPORTO_IRREGOLARE_DA_RECUPERARE = @ImportoIrregolareDaRecuperare, 
		ANNO = @Anno, 
		PERIODO_PROGRAMMAZIONE = @PeriodoProgrammazione, 
		NUMERO_RIFERIMENTO_NAZIONALE = @NumeroRiferimentoNazionale, 
		AZIONE_PENALE = @AzionePenale, 
		DATA_CREAZIONE_IDENTIFICAZIONE = @DataCreazioneIdentificazione, 
		TRIMESTRE_IDENTIFICAZIONE = @TrimestreIdentificazione, 
		PROCEDIMENTO_AMMINISTRATIVO = @ProcedimentoAmministrativo, 
		AZIONE_GIUDIZIARIA = @AzioneGiudiziaria, 
		DATA_PRIMA_INFORMAZIONE_SOSPETTO = @DataPrimaInformazioneSospetto, 
		FONTE_PRIMA_INFORMAZIONE_SOSPETTO = @FontePrimaInformazioneSospetto, 
		DATA_IRREGOLARITA = @DataIrregolarita, 
		DATA_IRREGOLARITA_DA = @DataIrregolaritaDa, 
		DATA_IRREGOLARITA_A = @DataIrregolaritaA, 
		COMMESSA_A = @CommessaA, 
		ID_CATEGORIA_IRREGOLARITA = @IdCategoriaIrregolarita, 
		ID_TIPO_IRREGOLARITA = @IdTipoIrregolarita, 
		MODUS_OPERANDI = @ModusOperandi, 
		DICHIARAZIONE_OPERATORE = @DichiarazioneOperatore, 
		ACCERTAMENTI_AMMINISTRATORE = @AccertamentiAmministratore, 
		ID_CLASSIFICAZIONE_IRREGOLARITA = @IdClassificazioneIrregolarita, 
		DATA_PRIMO_ATTO_CONSTATAZIONE_AMMINISTRATIVO = @DataPrimoAttoConstatazioneAmministrativo, 
		ID_MOTIVO_ESECUZIONE_CONTROLLO = @IdMotivoEsecuzioneControllo, 
		ID_TIPO_CONTROLLO = @IdTipoControllo, 
		ID_CONTROLLO_PRIMA_DOPO_PAGAMENTO = @IdControlloPrimaDopoPagamento, 
		AUTORITA_CONTROLLO = @AutoritaControllo, 
		INDAGINE_OLAF = @IndagineOlaf, 
		IMPORTO_SPESA_UE = @ImportoSpesaUe, 
		IMPORTO_SPESA_NAZIONALE = @ImportoSpesaNazionale, 
		IMPORTO_SPESA_PUBBLICO = @ImportoSpesaPubblico, 
		IMPORTO_SPESA_PRIVATO = @ImportoSpesaPrivato, 
		IMPORTO_SPESA_TOTALE = @ImportoSpesaTotale, 
		IMPORTO_IRREGOLARITA_UE = @ImportoIrregolaritaUe, 
		IMPORTO_IRREGOLARITA_NAZIONALE = @ImportoIrregolaritaNazionale, 
		IMPORTO_IRREGOLARITA_PUBBLICO = @ImportoIrregolaritaPubblico, 
		IMPORTO_IRREGOLARITA_PRIVATO = @ImportoIrregolaritaPrivato, 
		IMPORTO_IRREGOLARITA_TOTALE = @ImportoIrregolaritaTotale, 
		IMPORTO_IRREGOLARITA_NON_PAGATO_UE = @ImportoIrregolaritaNonPagatoUe, 
		IMPORTO_IRREGOLARITA_NON_PAGATO_NAZIONALE = @ImportoIrregolaritaNonPagatoNazionale, 
		IMPORTO_IRREGOLARITA_NON_PAGATO_PUBBLICO = @ImportoIrregolaritaNonPagatoPubblico, 
		IMPORTO_IRREGOLARITA_NON_PAGATO_PRIVATO = @ImportoIrregolaritaNonPagatoPrivato, 
		IMPORTO_IRREGOLARITA_NON_PAGATO_TOTALE = @ImportoIrregolaritaNonPagatoTotale, 
		IMPORTO_IRREGOLARITA_PAGATO_UE = @ImportoIrregolaritaPagatoUe, 
		IMPORTO_IRREGOLARITA_PAGATO_NAZIONALE = @ImportoIrregolaritaPagatoNazionale, 
		IMPORTO_IRREGOLARITA_PAGATO_PUBBLICO = @ImportoIrregolaritaPagatoPubblico, 
		IMPORTO_IRREGOLARITA_PAGATO_PRIVATO = @ImportoIrregolaritaPagatoPrivato, 
		IMPORTO_IRREGOLARITA_PAGATO_TOTALE = @ImportoIrregolaritaPagatoTotale, 
		IMPORTO_DA_RECUPERARE_UE = @ImportoDaRecuperareUe, 
		IMPORTO_DA_RECUPERARE_NAZIONALE = @ImportoDaRecuperareNazionale, 
		IMPORTO_DA_RECUPERARE_PUBBLICO = @ImportoDaRecuperarePubblico, 
		IMPORTO_DA_RECUPERARE_PRIVATO = @ImportoDaRecuperarePrivato, 
		IMPORTO_DA_RECUPERARE_TOTALE = @ImportoDaRecuperareTotale, 
		SPESA_DECERTIFICATA = @SpesaDecertificata, 
		COMMENTI_IMPATTO_FINANZIARIO = @CommentiImpattoFinanziario, 
		ID_FONDO = @IdFondo, 
		ID_CONTROLLO_ORIGINE = @IdControlloOrigine, 
		ID_STATO_FINANZIARIO = @IdStatoFinanziario, 
		DESCRIZIONE_CONTROLLO_ESTERNO = @DescrizioneControlloEsterno, 
		ID_IMPRESA_COMMESSA_DA = @IdImpresaCommessaDa, 
		NOTE_COMMESSA_DA = @NoteCommessaDa, 
		STABILITA_OPERAZIONI = @StabilitaOperazioni, 
		ID_DOMANDA_PAGAMENTO = @IdDomandaPagamento
	WHERE 
		(ID_IRREGOLARITA = @IdIrregolarita)
	SELECT @DataModifica;


GO
EXECUTE sp_addextendedproperty @name = N'backup', @value = 'CREATE PROCEDURE [dbo].[ZRegistroIrregolaritaUpdate]
(
	@SegnalazioneOlaf BIT, 
	@DataSegnalazione DATETIME, 
	@TrimestreSegnalazione VARCHAR(255), 
	@DataModifica DATETIME, 
	@CfModifica VARCHAR(255), 
	@DataInserimento DATETIME, 
	@CfInserimento VARCHAR(255), 
	@IdProgetto INT, 
	@IdIrregolarita INT, 
	@NumeroRiferimentoOlaf VARCHAR(255), 
	@SospettoFrode BIT, 
	@ImportoIrregolareCertificato DECIMAL(15,2), 
	@ImportoIrregolareDaRecuperare DECIMAL(15,2), 
	@Anno INT, 
	@PeriodoProgrammazione VARCHAR(500), 
	@NumeroRiferimentoNazionale VARCHAR(255), 
	@AzionePenale BIT, 
	@DataCreazioneIdentificazione DATETIME, 
	@TrimestreIdentificazione VARCHAR(255), 
	@ProcedimentoAmministrativo BIT, 
	@AzioneGiudiziaria BIT, 
	@DataPrimaInformazioneSospetto DATETIME, 
	@FontePrimaInformazioneSospetto VARCHAR(255), 
	@DataIrregolarita DATETIME, 
	@DataIrregolaritaDa DATETIME, 
	@DataIrregolaritaA DATETIME, 
	@CommessaA VARCHAR(max), 
	@IdCategoriaIrregolarita INT, 
	@IdTipoIrregolarita INT, 
	@ModusOperandi VARCHAR(max), 
	@DichiarazioneOperatore VARCHAR(max), 
	@AccertamentiAmministratore VARCHAR(max), 
	@IdClassificazioneIrregolarita INT, 
	@DataPrimoAttoConstatazioneAmministrativo DATETIME, 
	@IdMotivoEsecuzioneControllo INT, 
	@IdTipoControllo INT, 
	@IdControlloPrimaDopoPagamento INT, 
	@AutoritaControllo VARCHAR(255), 
	@IndagineOlaf BIT, 
	@ImportoSpesaUe DECIMAL(15,2), 
	@ImportoSpesaNazionale DECIMAL(15,2), 
	@ImportoSpesaPubblico DECIMAL(15,2), 
	@ImportoSpesaPrivato DECIMAL(15,2), 
	@ImportoSpesaTotale DECIMAL(15,2), 
	@ImportoIrregolaritaUe DECIMAL(15,2), 
	@ImportoIrregolaritaNazionale DECIMAL(15,2), 
	@ImportoIrregolaritaPubblico DECIMAL(15,2), 
	@ImportoIrregolaritaPrivato DECIMAL(15,2), 
	@ImportoIrregolaritaTotale DECIMAL(15,2), 
	@ImportoIrregolaritaNonPagatoUe DECIMAL(15,2), 
	@ImportoIrregolaritaNonPagatoNazionale DECIMAL(15,2), 
	@ImportoIrregolaritaNonPagatoPubblico DECIMAL(15,2), 
	@ImportoIrregolaritaNonPagatoPrivato DECIMAL(15,2), 
	@ImportoIrregolaritaNonPagatoTotale DECIMAL(15,2), 
	@ImportoIrregolaritaPagatoUe DECIMAL(15,2), 
	@ImportoIrregolaritaPagatoNazionale DECIMAL(15,2), 
	@ImportoIrregolaritaPagatoPubblico DECIMAL(15,2), 
	@ImportoIrregolaritaPagatoPrivato DECIMAL(15,2), 
	@ImportoIrregolaritaPagatoTotale DECIMAL(15,2), 
	@ImportoDaRecuperareUe DECIMAL(15,2), 
	@ImportoDaRecuperareNazionale DECIMAL(15,2), 
	@ImportoDaRecuperarePubblico DECIMAL(15,2), 
	@ImportoDaRecuperarePrivato DECIMAL(15,2), 
	@ImportoDaRecuperareTotale DECIMAL(15,2), 
	@SpesaDecertificata BIT, 
	@CommentiImpattoFinanziario VARCHAR(max), 
	@IdFondo INT, 
	@IdControlloOrigine INT, 
	@IdStatoFinanziario INT, 
	@DescrizioneControlloEsterno VARCHAR(max), 
	@IdImpresaCommessaDa INT, 
	@NoteCommessaDa VARCHAR(max), 
	@StabilitaOperazioni BIT
)
AS
	SET @DataModifica=getdate()
	UPDATE REGISTRO_IRREGOLARITA
	SET
		SEGNALAZIONE_OLAF = @SegnalazioneOlaf, 
		DATA_SEGNALAZIONE = @DataSegnalazione, 
		TRIMESTRE_SEGNALAZIONE = @TrimestreSegnalazione, 
		DATA_MODIFICA = @DataModifica, 
		CF_MODIFICA = @CfModifica, 
		DATA_INSERIMENTO = @DataInserimento, 
		CF_INSERIMENTO = @CfInserimento, 
		ID_PROGETTO = @IdProgetto, 
		NUMERO_RIFERIMENTO_OLAF = @NumeroRiferimentoOlaf, 
		SOSPETTO_FRODE = @SospettoFrode, 
		IMPORTO_IRREGOLARE_CERTIFICATO = @ImportoIrregolareCertificato, 
		IMPORTO_IRREGOLARE_DA_RECUPERARE = @ImportoIrregolareDaRecuperare, 
		ANNO = @Anno, 
		PERIODO_PROGRAMMAZIONE = @PeriodoProgrammazione, 
		NUMERO_RIFERIMENTO_NAZIONALE = @NumeroRiferimentoNazionale, 
		AZIONE_PENALE = @AzionePenale, 
		DATA_CREAZIONE_IDENTIFICAZIONE = @DataCreazioneIdentificazione, 
		TRIMESTRE_IDENTIFICAZIONE = @TrimestreIdentificazione, 
		PROCEDIMENTO_AMMINISTRATIVO = @ProcedimentoAmministrativo, 
		AZIONE_GIUDIZIARIA = @AzioneGiudiziaria, 
		DATA_PRIMA_INFORMAZIONE_SOSPETTO = @DataPrimaInformazioneSospetto, 
		FONTE_PRIMA_INFORMAZIONE_SOSPETTO = @FontePrimaInform', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'PROCEDURE', @level1name = N'ZRegistroIrregolaritaUpdate';

