CREATE PROCEDURE [dbo].[ZRevisioneDomandaPagamentoFindFindbylottoapprovata]
(
	@IdLottoequalthis INT, 
	@Approvatanotequalthis BIT
)
AS
		SELECT ID_DOMANDA_PAGAMENTO, TIPO_DOMANDA_PAGAMENTO, COD_FASE, DATA_PRESENTAZIONE_DOMANDA_PAGAMENTO, DOMANDA_APPROVATA, ID_PROGETTO, ID_LOTTO, DATA_INSERIMENTO, DATA_MODIFICA, CF_OPERATORE, SELEZIONATA_X_REVISIONE, APPROVATA, NUMERO_ESTRAZIONE, ORDINE, SEGNATURA_REVISIONE, SEGNATURA_SECONDA_REVISIONE, DATA_VALIDAZIONE, COD_TIPO, DATA_APPROVAZIONE, ID_BANDO, PROVINCIA_DI_PRESENTAZIONE
		FROM vREVISIONE_DOMANDA_PAGAMENTO
		WHERE 
			((@IdLottoequalthis IS NULL) OR ID_LOTTO = @IdLottoequalthis) AND 
			((@Approvatanotequalthis IS NULL) OR APPROVATA <> @Approvatanotequalthis or APPROVATA is null)
		