CREATE PROCEDURE SpGetContrattiDomandaPagamento (
	@ID_DOMANDA_PAGAMENTO INT,
	@SEGNATURA VARCHAR(100) = NULL,
	@DATA_STIPULA DATETIME = NULL
)
AS 
(

--DECLARE @ID_DOMANDA_PAGAMENTO INT;
--DECLARE @SEGNATURA VARCHAR(100);
--DECLARE @DATA_STIPULA DATETIME;

--SET @ID_DOMANDA_PAGAMENTO = 98;

/* -- OLD VERSION
SELECT DISTINCT CON.*
FROM vCONTRATTI_FEM CON
	JOIN CONTRATTI_FEM_PAGAMENTI PAG ON PAG.ID_CONTRATTO_FEM = CON.ID_CONTRATTO_FEM
WHERE 1 = 1 
    AND PAG.ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO 
    AND (@SEGNATURA IS NULL OR @SEGNATURA = CON.SEGNATURA) 
    AND (@DATA_STIPULA IS NULL OR @DATA_STIPULA = CON.DATA_STIPULA_CONTRATTO)
*/

SELECT CON.*
FROM vCONTRATTI_FEM CON
WHERE 1 = 1
	AND (@SEGNATURA IS NULL OR @SEGNATURA = CON.SEGNATURA) 
    AND (@DATA_STIPULA IS NULL OR @DATA_STIPULA = CON.DATA_STIPULA_CONTRATTO)
	AND CON.ID_CONTRATTO_FEM IN (SELECT DISTINCT ID_CONTRATTO_FEM
									FROM CONTRATTI_FEM_PAGAMENTI PAG
									WHERE 1 = 1 
										AND PAG.ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO)
)