CREATE VIEW [dbo].[VRICERCA_SPESE_IRREGOLARI]
AS
SELECT 
		PB.ID_PAGAMENTO_BENEFICIARIO,
		PB.ID_PAGAMENTO_RICHIESTO,
		PB.IMPORTO_RICHIESTO,
		PB.IMPORTO_AMMESSO,
		PB.CONTRIBUTO_AMMESSO,
		INV.QUOTA_CONTRIBUTO_RICHIESTO,
		'' AS ID_SPESA,--SP.ID_SPESA,
		GIU.ID_GIUSTIFICATIVO, --SP.ID_GIUSTIFICATIVO, 
		'' AS COD_TIPO_SPESA, --SP.COD_TIPO AS COD_TIPO_SPESA, 
		'' AS ESTREMI_SPESA, --SP.ESTREMI AS ESTREMI_SPESA, 
		'' AS DATA_SPESA, --SP.DATA AS DATA_SPESA, 
		'' AS IMPORTO_SPESA, --SP.IMPORTO AS IMPORTO_SPESA, 
		'' AS NETTO_SPESA, --SP.NETTO AS NETTO_SPESA, 
		'' AS TIPO_SPESA, --TIPS.DESCRIZIONE AS TIPO_SPESA,
		DOM.ID_DOMANDA_PAGAMENTO,
		DOM.COD_TIPO AS COD_TIPO_DOMANDA,
		DOM.DESCRIZIONE AS TIPO_DOMANDA,
		GIU.ID_PROGETTO,
		GIU.NUMERO AS NUMERO_GIUSTIFICATIVO, 
		GIU.COD_TIPO AS COD_TIPO_GIUSTIFICATIVO, 
		GIU.DATA AS DATA_GIUSTIFICATIVO, 
		GIU.NUMERO_DOCTRASPORTO AS NUMERO_DOCTRASPORTO_GIUSTIFICATIVO, 
		GIU.IMPONIBILE AS IMPONIBILE_GIUSTIFICATIVO,
		GIU.IVA AS IVA_GIUSTIFICATIVO, 
		GIU.IVA_NON_RECUPERABILE AS IVA_NON_RECUPERABILE_GIUSTIFICATIVO,
		GIU.DESCRIZIONE AS DESCRIZIONE_GIUSTIFICATIVO,
		GIU.CF_FORNITORE AS CF_FORNITORE_GIUSTIFICATIVO,
		GIU.DESCRIZIONE_FORNITORE AS DESCRIZIONE_FORNITORE_GIUSTIFICATIVO,
		TIPG.DESCRIZIONE AS TIPO_GIUSTIFICATIVO,
		CERT_T.IdCertSp AS ID_LOTTO_CERTIFICAZIONE,
		CERT_T.CodPsr AS COD_PSR_CERTIFICAZIONE,
		CERT_T.DataInizio AS DATA_INIZIO_LOTTO_CERTIFICAZIONE,
		CERT_T.DataFine AS DATA_FINE_LOTTO_CERTIFICAZIONE
		FROM 
		PAGAMENTI_BENEFICIARIO PB JOIN
        GIUSTIFICATIVI GIU ON PB.ID_GIUSTIFICATIVO = GIU.ID_GIUSTIFICATIVO JOIN
        TIPO_GIUSTIFICATIVO TIPG ON GIU.COD_TIPO = TIPG.COD_TIPO JOIN
        PAGAMENTI_RICHIESTI PR ON PB.ID_PAGAMENTO_RICHIESTO = PR.ID_PAGAMENTO_RICHIESTO JOIN
        PIANO_INVESTIMENTI INV ON INV.ID_INVESTIMENTO = PR.ID_INVESTIMENTO JOIN
        VDOMANDA_DI_PAGAMENTO DOM ON PR.ID_DOMANDA_PAGAMENTO = DOM.ID_DOMANDA_PAGAMENTO LEFT JOIN 
        vCertSp_Dettaglio CERT_D ON DOM.ID_DOMANDA_PAGAMENTO = CERT_D.Id_Domanda_Pagamento LEFT JOIN
        CertSp_Testa CERT_T ON CERT_D.IdCertSp = CERT_T.IdCertSp 
GO