CREATE VIEW [dbo].[vBANDO_STORICO]
AS
SELECT     dbo.BANDO_STORICO.ID, dbo.BANDO_STORICO.ID_BANDO, dbo.BANDO_STORICO.COD_STATO, dbo.BANDO_STORICO.DATA, dbo.BANDO_STORICO.OPERATORE, 
                      dbo.BANDO_STORICO.SEGNATURA, dbo.BANDO_STORICO.ID_ATTO, dbo.BANDO_TIPO_STATO.DESCRIZIONE AS STATO, 
                      dbo.BANDO_TIPO_STATO.ORDINE AS ORDINE_STATO, dbo.vUTENTI.PROFILO, dbo.vUTENTI.NOMINATIVO, dbo.ATTI.NUMERO AS NUMERO_ATTO, 
                      dbo.ATTI.DATA AS DATA_ATTO
FROM         dbo.BANDO_STORICO INNER JOIN
                      dbo.BANDO_TIPO_STATO ON dbo.BANDO_STORICO.COD_STATO = dbo.BANDO_TIPO_STATO.CODICE INNER JOIN
                      dbo.vUTENTI ON dbo.BANDO_STORICO.OPERATORE = dbo.vUTENTI.ID_UTENTE LEFT OUTER JOIN
                      dbo.ATTI ON dbo.BANDO_STORICO.ID_ATTO = dbo.ATTI.ID_ATTO
