CREATE VIEW [dbo].[vBANDO_MASSIMALI]
AS
SELECT     dbo.BANDO_MASSIMALI.ID, dbo.BANDO_MASSIMALI.ID_BANDO, dbo.BANDO_MASSIMALI.ID_PROGRAMMAZIONE, dbo.BANDO_MASSIMALI.QUOTA, 
                      dbo.BANDO_MASSIMALI.IMPORTO, dbo.zPROGRAMMAZIONE.CODICE, dbo.zPROGRAMMAZIONE.DESCRIZIONE
FROM         dbo.BANDO_MASSIMALI INNER JOIN
                      dbo.zPROGRAMMAZIONE ON dbo.BANDO_MASSIMALI.ID_PROGRAMMAZIONE = dbo.zPROGRAMMAZIONE.ID
