CREATE VIEW [dbo].[vBANDO_X_SETTORE_PRODUTTIVO]
AS
SELECT     dbo.BANDO_X_SETTORE_PRODUTTIVO.ID_BANDO_X_SETTORE_PRODUTTIVO, dbo.BANDO_X_SETTORE_PRODUTTIVO.ID_BANDO, 
                      dbo.BANDO_X_SETTORE_PRODUTTIVO.ID_SETTORE_PRODUTTIVO, dbo.BANDO_X_SETTORE_PRODUTTIVO.ID_PRIORITA_SETTORIALE, 
                      dbo.SETTORI_PRODUTTIVI.DESCRIZIONE AS SETTORE_PRODUTTIVO, dbo.PRIORITA_SETTORIALI.DESCRIZIONE AS PRIORITA_SETTORIALE
FROM         dbo.BANDO_X_SETTORE_PRODUTTIVO LEFT OUTER JOIN
                      dbo.PRIORITA_SETTORIALI ON 
                      dbo.BANDO_X_SETTORE_PRODUTTIVO.ID_PRIORITA_SETTORIALE = dbo.PRIORITA_SETTORIALI.ID_PRIORITA_SETTORIALE LEFT OUTER JOIN
                      dbo.SETTORI_PRODUTTIVI ON 
                      dbo.BANDO_X_SETTORE_PRODUTTIVO.ID_SETTORE_PRODUTTIVO = dbo.SETTORI_PRODUTTIVI.ID_SETTORE_PRODUTTIVO
