
CREATE VIEW dbo.vBANDO_VALIDATORI
AS
SELECT     dbo.BANDO_VALIDATORI.ID, dbo.BANDO_VALIDATORI.ID_BANDO, dbo.BANDO_VALIDATORI.ID_UTENTE, dbo.BANDO_VALIDATORI.RESPONSABILE, 
                      dbo.BANDO_VALIDATORI.ATTIVO, dbo.BANDO_VALIDATORI.DATA_INIZIO, dbo.BANDO_VALIDATORI.OPERATORE_INIZIO, dbo.BANDO_VALIDATORI.DATA_FINE, 
                      dbo.BANDO_VALIDATORI.OPERATORE_FINE, dbo.vUTENTI.NOMINATIVO, dbo.vUTENTI.PROFILO, dbo.vUTENTI.ENTE, dbo.vUTENTI.COD_ENTE
FROM         dbo.BANDO_VALIDATORI INNER JOIN
                      dbo.vUTENTI ON dbo.BANDO_VALIDATORI.ID_UTENTE = dbo.vUTENTI.ID_UTENTE

