


CREATE VIEW [dbo].[vBANDO_CONFIG]
AS
SELECT     dbo.BANDO_CONFIG.ID, dbo.BANDO_CONFIG.ID_BANDO, dbo.BANDO_CONFIG.COD_TIPO, dbo.BANDO_CONFIG.VALORE, dbo.BANDO_CONFIG.ATTIVO, 
                      dbo.BANDO_CONFIG.DATA_INIZIO, dbo.BANDO_CONFIG.OPERATORE_INIZIO, dbo.BANDO_CONFIG.DATA_FINE, dbo.BANDO_CONFIG.OPERATORE_FINE, 
                      dbo.BANDO_CONFIG_TIPO.COD_MACROTIPO, dbo.BANDO_CONFIG_TIPO.FORMATO, dbo.BANDO_CONFIG_TIPO.DESCRIZIONE, 
                      dbo.BANDO_CONFIG_TIPO.ATTIVO AS TIPO_ATTIVO, dbo.BANDO_CONFIG_TIPO.ORDINE, 
                      dbo.BANDO_CONFIG_TIPO_PARAMETRI.DESCRIZIONE AS VALORE_DESCRIZIONE
FROM         dbo.BANDO_CONFIG INNER JOIN
                      dbo.BANDO_CONFIG_TIPO ON dbo.BANDO_CONFIG.COD_TIPO = dbo.BANDO_CONFIG_TIPO.CODICE LEFT OUTER JOIN
                      dbo.BANDO_CONFIG_TIPO_PARAMETRI ON dbo.BANDO_CONFIG.VALORE = dbo.BANDO_CONFIG_TIPO_PARAMETRI.CODICE AND 
                      dbo.BANDO_CONFIG.COD_TIPO = dbo.BANDO_CONFIG_TIPO_PARAMETRI.COD_TIPO



