CREATE VIEW [dbo].[vBANDO_PROGRAMMAZIONE]
AS
SELECT     dbo.BANDO_PROGRAMMAZIONE.ID, dbo.BANDO_PROGRAMMAZIONE.ID_BANDO, dbo.BANDO_PROGRAMMAZIONE.ID_PROGRAMMAZIONE, 
                      dbo.BANDO_PROGRAMMAZIONE.MISURA_PREVALENTE, dbo.BANDO_PROGRAMMAZIONE.ID_DISPOSIZIONI_ATTUATIVE, dbo.vzPROGRAMMAZIONE.COD_TIPO, 
                      dbo.vzPROGRAMMAZIONE.CODICE, dbo.vzPROGRAMMAZIONE.DESCRIZIONE, dbo.vzPROGRAMMAZIONE.ID_PADRE, dbo.vzPROGRAMMAZIONE.COD_PSR, 
                      dbo.vzPROGRAMMAZIONE.TIPO, dbo.vzPROGRAMMAZIONE.LIVELLO
FROM         dbo.BANDO_PROGRAMMAZIONE INNER JOIN
                      dbo.vzPROGRAMMAZIONE ON dbo.BANDO_PROGRAMMAZIONE.ID_PROGRAMMAZIONE = dbo.vzPROGRAMMAZIONE.ID
