CREATE VIEW [dbo].[vBANDO_TIPO_INVESTIMENTI]
AS
SELECT     dbo.BANDO_TIPO_INVESTIMENTI.ID_TIPO_INVESTIMENTO, dbo.BANDO_TIPO_INVESTIMENTI.ID_BANDO, 
                      dbo.BANDO_TIPO_INVESTIMENTI.COD_TIPO_INVESTIMENTO, dbo.BANDO_TIPO_INVESTIMENTI.IMPORTO_MAX, 
                      dbo.BANDO_TIPO_INVESTIMENTI.IMPORTO_MIN, dbo.BANDO_TIPO_INVESTIMENTI.QUOTA_MAX, dbo.BANDO_TIPO_INVESTIMENTI.NOTE, 
                      dbo.BANDO_TIPO_INVESTIMENTI.PREMIO, dbo.TIPO_INVESTIMENTO.DESCRIZIONE, dbo.TIPO_INVESTIMENTO.URL, 
                      dbo.TIPO_INVESTIMENTO.TEXT
FROM         dbo.BANDO_TIPO_INVESTIMENTI INNER JOIN
                      dbo.TIPO_INVESTIMENTO ON dbo.BANDO_TIPO_INVESTIMENTI.COD_TIPO_INVESTIMENTO = dbo.TIPO_INVESTIMENTO.COD_TIPO_INVESTIMENTO
