CREATE VIEW [dbo].[vCOMUNI]
AS
SELECT     dbo.COMUNI.ID_COMUNE, dbo.COMUNI.COD_BELFIORE, dbo.COMUNI.DENOMINAZIONE, dbo.COMUNI.COD_PROVINCIA, dbo.COMUNI.SIGLA, dbo.COMUNI.CAP, 
                      dbo.COMUNI.ISTAT, dbo.COMUNI.TIPO_AREA, dbo.COMUNI.COD_RUBRICA_PALEO, dbo.COMUNI.ATTIVO, dbo.COMUNI.DATA_INIZIO_VALIDITA, 
                      dbo.COMUNI.DATA_FINE_VALIDITA, dbo.COMUNI.ID_OPERATORE_INIZIO, dbo.COMUNI.ID_OPERATORE_FINE, dbo.PROVINCE.COD_CITTA_METROPOLITANA, 
                      dbo.PROVINCE.DENOMINAZIONE AS PROVINCIA, dbo.PROVINCE.COD_REGIONE, dbo.REGIONI.DENOMINAZIONE AS REGIONE
FROM         dbo.COMUNI INNER JOIN
                      dbo.PROVINCE ON dbo.COMUNI.COD_PROVINCIA = dbo.PROVINCE.CODICE INNER JOIN
                      dbo.REGIONI ON dbo.PROVINCE.COD_REGIONE = dbo.REGIONI.CODICE
