
CREATE VIEW dbo.vDICHIARAZIONI
AS
SELECT     dbo.DICHIARAZIONI_X_DOMANDA.ID_DICHIARAZIONE, dbo.DICHIARAZIONI_X_DOMANDA.ID_DOMANDA, dbo.DICHIARAZIONI_X_DOMANDA.ORDINE, 
                      dbo.CATALOGO_DICHIARAZIONI.DESCRIZIONE, dbo.CATALOGO_DICHIARAZIONI.MISURA, dbo.DICHIARAZIONI_X_DOMANDA.OBBLIGATORIO
FROM         dbo.DICHIARAZIONI_X_DOMANDA INNER JOIN
                      dbo.CATALOGO_DICHIARAZIONI ON dbo.DICHIARAZIONI_X_DOMANDA.ID_DICHIARAZIONE = dbo.CATALOGO_DICHIARAZIONI.ID_DICHIARAZIONE

