
/*
SELECT * 
FROM DOMANDA_DI_PAGAMENTO_ESPORTAZIONE ESPORT;

SELECT TOP 20 *
FROM DOMANDA_DI_PAGAMENTO DOM;
*/

CREATE VIEW [dbo].[VDOMANDA_DI_PAGAMENTO_ESPORTAZIONE] AS (
SELECT ESPORT.*, 
DOM.COD_TIPO,
DOM.DATA_INSERIMENTO,
DOM.CF_OPERATORE,
DOM.DATA_MODIFICA,
DOM.COD_ENTE,
DOM.SEGNATURA,
DOM.SEGNATURA_ALLEGATI,
DOM.ID_FIDEJUSSIONE,
DOM.DATA_CERTIFICAZIONE_ANTIMAFIA,
DOM.APPROVATA,
DOM.SEGNATURA_APPROVAZIONE,
DOM.SEGNATURA_SECONDA_APPROVAZIONE,
DOM.CF_ISTRUTTORE,
DOM.DATA_APPROVAZIONE,
DOM.VALUTAZIONE_ISTRUTTORE,
DOM.ANNULLATA,
DOM.SEGNATURA_ANNULLAMENTO,
DOM.CF_OPERATORE_ANNULLAMENTO,
DOM.DATA_ANNULLAMENTO,
DOM.VALIDITA_VERSIONE_ADC,
DOM.ID_VARIAZIONE_ACCERTATA,
DOM.PREDISPOSTA_A_CONTROLLO,
DOM.DATA_PREDISPOSIZIONE_A_CONTROLLO,
DOM.VISITA_INSITU_ESITO,
DOM.VISITA_INSITU_NOTE,
DOM.CONTROLLO_INLOCO_ESITO,
DOM.CONTROLLO_INLOCO_NOTE,
DOM.VERIFICA_PAGAMENTI_ESITO,
DOM.VERIFICA_PAGAMENTI_MESSAGGIO,
DOM.VERIFICA_PAGAMENTI_DATA,
DOM.FIRMA_PREDISPOSTA,
DOM.IN_INTEGRAZIONE 
FROM DOMANDA_DI_PAGAMENTO_ESPORTAZIONE ESPORT
INNER JOIN DOMANDA_DI_PAGAMENTO DOM 
ON ESPORT.ID_DOMANDA_PAGAMENTO = DOM.ID_DOMANDA_PAGAMENTO 
AND ESPORT.ID_PROGETTO = DOM.ID_PROGETTO
);
