


CREATE VIEW [dbo].[vPAGE_HELP]
AS
SELECT     dbo.PAGE_HELP.ID, dbo.PAGE_HELP.PAGE, dbo.PAGE_HELP.PARAMETRI, dbo.PAGE_HELP.ID_DOC, dbo.PAGE_HELP.ID_PDF, dbo.PAGE_HELP.OPERATORE, 
                      dbo.PAGE_HELP.DATA, dbo.PAGE_HELP.ATTIVO, dbo.ARCHIVIO_FILE.TIPO, dbo.ARCHIVIO_FILE.NOME_FILE, dbo.ARCHIVIO_FILE.DIMENSIONE
FROM         dbo.PAGE_HELP INNER JOIN
                      dbo.ARCHIVIO_FILE ON dbo.PAGE_HELP.ID_PDF = dbo.ARCHIVIO_FILE.ID



