

CREATE VIEW [dbo].[vPROGETTO_COMUNICAZIONI_DOCUMENTI]
AS
SELECT PCD.ID, PCD.ID_COMUNICAZIONE, PCD.ID_DOMANDA_PAGAMENTO_ALLEGATI, PCD.ID_VARIANTE_ALLEGATI, PCD.COD_TIPO_DOCUMENTO, PCD.ID_FILE, 
               PCD.COD_ENTE_EMETTITORE, PCD.ID_COMUNE, PCD.NUMERO, PCD.DATA, PCD.DESCRIZIONE, PCD.ID_NOTE_COMUNICAZIONE, 
               TIPO_DOCUMENTO.FORMATO, TIPO_DOCUMENTO.DESCRIZIONE AS DESCRIZIONE_DOCUMENTO, TIPO_DOCUMENTO.ATTIVO, 
               CASE WHEN PCD.ID_COMUNE IS NULL 
               THEN dbo.ENTE.DESCRIZIONE ELSE 'COMUNE DI ' + dbo.COMUNI.DENOMINAZIONE + ' (' + dbo.COMUNI.SIGLA + ')' END AS ENTE, ENTE.COD_TIPO_ENTE, 
               NOTE.TESTO AS NOTE
FROM  PROGETTO_COMUNICAZIONI_DOCUMENTI AS PCD LEFT OUTER JOIN
               TIPO_DOCUMENTO ON PCD.COD_TIPO_DOCUMENTO = TIPO_DOCUMENTO.CODICE LEFT OUTER JOIN
               NOTE ON PCD.ID_NOTE_COMUNICAZIONE = NOTE.ID LEFT OUTER JOIN
               COMUNI ON PCD.ID_COMUNE = COMUNI.ID_COMUNE LEFT OUTER JOIN
               ENTE ON PCD.COD_ENTE_EMETTITORE = ENTE.COD_ENTE
WHERE PCD.ID_DOMANDA_PAGAMENTO_ALLEGATI IS NULL AND PCD.ID_VARIANTE_ALLEGATI IS NULL
UNION
SELECT PCD.ID, PCD.ID_COMUNICAZIONE, PCD.ID_DOMANDA_PAGAMENTO_ALLEGATI, PCD.ID_VARIANTE_ALLEGATI, DPA.COD_TIPO_DOCUMENTO, DPA.ID_FILE, 
               DPA.COD_ENTE_EMETTITORE, DPA.ID_COMUNE, DPA.NUMERO, DPA.DATA, DPA.DESCRIZIONE, PCD.ID_NOTE_COMUNICAZIONE, 
               TIPO_DOCUMENTO.FORMATO, TIPO_DOCUMENTO.DESCRIZIONE AS DESCRIZIONE_DOCUMENTO, TIPO_DOCUMENTO.ATTIVO, DPA.ENTE, 
               DPA.COD_ENTE_EMETTITORE, NOTE.TESTO AS NOTE
FROM  PROGETTO_COMUNICAZIONI_DOCUMENTI AS PCD LEFT OUTER JOIN
               vDOMANDA_PAGAMENTO_ALLEGATI DPA ON DPA.ID_ALLEGATO = PCD.ID_DOMANDA_PAGAMENTO_ALLEGATI LEFT OUTER JOIN
               TIPO_DOCUMENTO ON DPA.COD_TIPO_DOCUMENTO = TIPO_DOCUMENTO.CODICE LEFT OUTER JOIN
               NOTE ON PCD.ID_NOTE_COMUNICAZIONE = NOTE.ID
WHERE PCD.ID_DOMANDA_PAGAMENTO_ALLEGATI IS NOT NULL
UNION
SELECT PCD.ID, PCD.ID_COMUNICAZIONE, PCD.ID_DOMANDA_PAGAMENTO_ALLEGATI, PCD.ID_VARIANTE_ALLEGATI, VAL.COD_TIPO_DOCUMENTO, VAL.ID_FILE, 
               VAL.COD_ENTE_EMETTITORE, VAL.ID_COMUNE, VAL.NUMERO, VAL.DATA, VAL.DESCRIZIONE, PCD.ID_NOTE_COMUNICAZIONE, TIPO_DOCUMENTO.FORMATO, 
               TIPO_DOCUMENTO.DESCRIZIONE AS DESCRIZIONE_DOCUMENTO, TIPO_DOCUMENTO.ATTIVO, VAL.ENTE, VAL.COD_ENTE_EMETTITORE, 
               NOTE.TESTO AS NOTE
FROM  PROGETTO_COMUNICAZIONI_DOCUMENTI AS PCD LEFT OUTER JOIN
               vVARIANTI_ALLEGATI VAL ON VAL.ID_ALLEGATO = PCD.ID_VARIANTE_ALLEGATI LEFT OUTER JOIN

               TIPO_DOCUMENTO ON VAL.COD_TIPO_DOCUMENTO = TIPO_DOCUMENTO.CODICE LEFT OUTER JOIN
               NOTE ON PCD.ID_NOTE_COMUNICAZIONE = NOTE.ID
WHERE PCD.ID_VARIANTE_ALLEGATI IS NOT NULL


