CREATE VIEW [dbo].[vPROGETTO_RELAZIONE_TECNICA]
AS
SELECT     dbo.PROGETTO_RELAZIONE_TECNICA.ID_PARAGRAFO, dbo.PROGETTO_RELAZIONE_TECNICA.ID_PROGETTO, dbo.PROGETTO_RELAZIONE_TECNICA.TESTO, 
                      dbo.BANDO_RELAZIONE_TECNICA.ID_BANDO, dbo.BANDO_RELAZIONE_TECNICA.DESCRIZIONE, dbo.BANDO_RELAZIONE_TECNICA.TITOLO, 
                      dbo.BANDO_RELAZIONE_TECNICA.ORDINE
FROM         dbo.PROGETTO_RELAZIONE_TECNICA INNER JOIN
                      dbo.BANDO_RELAZIONE_TECNICA ON dbo.PROGETTO_RELAZIONE_TECNICA.ID_PARAGRAFO = dbo.BANDO_RELAZIONE_TECNICA.ID_PARAGRAFO
