



CREATE VIEW [dbo].[vPROGETTO_ALLEGATI]
AS
SELECT     dbo.PROGETTO_ALLEGATI.ID, dbo.PROGETTO_ALLEGATI.ID_PROGETTO, dbo.PROGETTO_ALLEGATI.ID_ALLEGATO, dbo.PROGETTO_ALLEGATI.ID_FILE, 
                      dbo.PROGETTO_ALLEGATI.DESCRIZIONE_BREVE, dbo.PROGETTO_ALLEGATI.COD_ENTE_EMETTITORE, dbo.PROGETTO_ALLEGATI.ID_COMUNE, 
                      dbo.PROGETTO_ALLEGATI.NUMERO, dbo.PROGETTO_ALLEGATI.DATA, dbo.PROGETTO_ALLEGATI.GIA_PRESENTATO, 
                      dbo.PROGETTO_ALLEGATI.COD_ESITO_ISTRUTTORIA, dbo.PROGETTO_ALLEGATI.NOTE_ISTRUTTORIA, dbo.ALLEGATI.DESCRIZIONE AS ALLEGATO, 
                      dbo.ALLEGATI.MISURA, dbo.ALLEGATI.COD_TIPO_ENTE_EMETTITORE, dbo.ESITI_STEP.DESCRIZIONE AS ESITO, dbo.ESITI_STEP.ESITO_POSITIVO, 
                      ISNULL(dbo.ALLEGATI.COD_TIPO, 'C') AS COD_TIPO, ISNULL(dbo.TIPO_ALLEGATO.DESCRIZIONE, 'Supporto Cartaceo') AS TIPO_ALLEGATO, 
                      CASE WHEN dbo.PROGETTO_ALLEGATI.ID_COMUNE IS NULL 
                      THEN dbo.ENTE.DESCRIZIONE ELSE 'COMUNE DI ' + dbo.COMUNI.DENOMINAZIONE + ' (' + dbo.COMUNI.SIGLA + ')' END AS ENTE, 
                      dbo.ARCHIVIO_FILE.DIMENSIONE / 1024 AS DIMENSIONE_FILE
FROM         dbo.PROGETTO_ALLEGATI LEFT OUTER JOIN
                      dbo.ARCHIVIO_FILE ON dbo.PROGETTO_ALLEGATI.ID_FILE = dbo.ARCHIVIO_FILE.ID LEFT OUTER JOIN
                      dbo.ENTE ON dbo.PROGETTO_ALLEGATI.COD_ENTE_EMETTITORE = dbo.ENTE.COD_ENTE LEFT OUTER JOIN
                      dbo.COMUNI ON dbo.PROGETTO_ALLEGATI.ID_COMUNE = dbo.COMUNI.ID_COMUNE LEFT OUTER JOIN
                      dbo.ALLEGATI ON dbo.PROGETTO_ALLEGATI.ID_ALLEGATO = dbo.ALLEGATI.ID_ALLEGATO LEFT OUTER JOIN
                      dbo.ESITI_STEP ON dbo.PROGETTO_ALLEGATI.COD_ESITO_ISTRUTTORIA = dbo.ESITI_STEP.COD_ESITO LEFT OUTER JOIN
                      dbo.TIPO_ALLEGATO ON dbo.ALLEGATI.COD_TIPO = dbo.TIPO_ALLEGATO.CODICE




