CREATE VIEW [dbo].[vPROGETTO_SEGNATURE]
AS
SELECT     dbo.PROGETTO_SEGNATURE.ID_PROGETTO, dbo.PROGETTO_SEGNATURE.COD_TIPO, dbo.PROGETTO_SEGNATURE.DATA, 
                      dbo.PROGETTO_SEGNATURE.OPERATORE, dbo.PROGETTO_SEGNATURE.SEGNATURA, dbo.TIPO_SEGNATURA.DESCRIZIONE AS TIPO_SEGNATURA, 
                      dbo.vUTENTI.PROFILO, dbo.vUTENTI.ENTE, dbo.vUTENTI.ID_PROFILO, dbo.vUTENTI.NOMINATIVO, dbo.vUTENTI.COD_ENTE, dbo.vUTENTI.PROVINCIA, 
                      dbo.PROGETTO_SEGNATURE.RIAPRI_DOMANDA, dbo.PROGETTO_SEGNATURE.MOTIVAZIONE
FROM         dbo.PROGETTO_SEGNATURE INNER JOIN
                      dbo.TIPO_SEGNATURA ON dbo.PROGETTO_SEGNATURE.COD_TIPO = dbo.TIPO_SEGNATURA.COD_TIPO INNER JOIN
                      dbo.vUTENTI ON dbo.PROGETTO_SEGNATURE.OPERATORE = dbo.vUTENTI.CF_UTENTE
