CREATE VIEW VRECUPERO_INVESTIMENTI AS (
SELECT 
	ID_ACCORPAMENTO_INVESTIMENTI,
	ref.value('ID_INVESTIMENTO[1]', 'INT') AS ID_INVESTIMENTO,
	ref.value('ID_PROGETTO[1]', 'INT') AS ID_PROGETTO,
	ref.value('ID_PROGRAMMAZIONE[1]', 'INT') AS ID_PROGRAMMAZIONE,
	ref.value('DESCRIZIONE[1]', 'VARCHAR(MAX)') AS DESCRIZIONE,
	CASE 
		WHEN ref.value('DATA_VARIAZIONE[1]', 'VARCHAR(MAX)') = ''
		THEN null
		ELSE ref.value('DATA_VARIAZIONE[1]', 'DATETIME')
	END AS DATA_VARIAZIONE,
	CASE 
		WHEN ref.value('OPERATORE_VARIAZIONE[1]', 'VARCHAR(MAX)') = ''
		THEN null
		ELSE ref.value('OPERATORE_VARIAZIONE[1]', 'VARCHAR(MAX)')
	END AS OPERATORE_VARIAZIONE,
	ref.value('COD_TIPO_INVESTIMENTO[1]', 'INT') AS COD_TIPO_INVESTIMENTO,
	ref.value('COD_STP[1]', 'VARCHAR(MAX)') AS COD_STP,
	ref.value('ID_UNITA_MISURA[1]', 'INT') AS ID_UNITA_MISURA,
	ref.value('QUANTITA[1]', 'DECIMAL(10,2)') AS QUANTITA,
	ref.value('COSTO_INVESTIMENTO[1]', 'DECIMAL(15,2)') AS COSTO_INVESTIMENTO,
	ref.value('SPESE_GENERALI[1]', 'DECIMAL(15,2)') AS SPESE_GENERALI,
	ref.value('CONTRIBUTO_RICHIESTO[1]', 'DECIMAL(15,2)') AS CONTRIBUTO_RICHIESTO,
	ref.value('QUOTA_CONTRIBUTO_RICHIESTO[1]', 'DECIMAL(15,12)') AS QUOTA_CONTRIBUTO_RICHIESTO,
	CASE 
		WHEN ref.value('CONTRIBUTO_ALTRE_FONTI[1]', 'VARCHAR(MAX)') = ''
		THEN null
		ELSE ref.value('CONTRIBUTO_ALTRE_FONTI[1]', 'DECIMAL(10,2)')
	END AS CONTRIBUTO_ALTRE_FONTI,
	CASE 
		WHEN ref.value('QUOTA_CONTRIBUTO_ALTRE_FONTI[1]', 'VARCHAR(MAX)') = ''
		THEN null
		ELSE ref.value('QUOTA_CONTRIBUTO_ALTRE_FONTI[1]', 'DECIMAL(10,2)')
	END AS QUOTA_CONTRIBUTO_ALTRE_FONTI,
	CASE 
		WHEN ref.value('TASSO_ABBUONO[1]', 'VARCHAR(MAX)') = ''
		THEN null
		ELSE ref.value('TASSO_ABBUONO[1]', 'DECIMAL(10,2)')
	END AS TASSO_ABBUONO,
	ref.value('ID_SETTORE_PRODUTTIVO[1]', 'INT') AS ID_SETTORE_PRODUTTIVO,
	ref.value('ID_PRIORITA_SETTORIALE[1]', 'INT') AS ID_PRIORITA_SETTORIALE,
	ref.value('ID_OBIETTIVO_MISURA[1]', 'INT') AS ID_OBIETTIVO_MISURA,
	ref.value('ID_CODIFICA_INVESTIMENTO[1]', 'INT') AS ID_CODIFICA_INVESTIMENTO,
	ref.value('ID_DETTAGLIO_INVESTIMENTO[1]', 'INT') AS ID_DETTAGLIO_INVESTIMENTO,
	CASE 
		WHEN ref.value('ID_SPECIFICA_INVESTIMENTO[1]', 'VARCHAR(MAX)') = ''
		THEN null
		ELSE ref.value('ID_SPECIFICA_INVESTIMENTO[1]', 'INT')
	END AS ID_SPECIFICA_INVESTIMENTO,
	CASE 
		WHEN ref.value('AMMESSO[1]', 'VARCHAR(MAX)') = ''
		THEN null
		ELSE ref.value('AMMESSO[1]', 'BIT')
	END AS AMMESSO,
	CASE 
		WHEN ref.value('ISTRUTTORE[1]', 'VARCHAR(MAX)') = ''
		THEN null
		ELSE ref.value('ISTRUTTORE[1]', 'VARCHAR(MAX)')
	END AS ISTRUTTORE,
	CASE 
		WHEN ref.value('ID_INVESTIMENTO_ORIGINALE[1]', 'VARCHAR(MAX)') = ''
		THEN null
		ELSE ref.value('ID_INVESTIMENTO_ORIGINALE[1]', 'INT')
	END AS ID_INVESTIMENTO_ORIGINALE,
	CASE 
		WHEN ref.value('DATA_VALUTAZIONE[1]', 'VARCHAR(MAX)') = ''
		THEN null
		ELSE ref.value('DATA_VALUTAZIONE[1]', 'DATETIME')
	END AS DATA_VALUTAZIONE,
	CASE 
		WHEN ref.value('VALUTAZIONE_INVESTIMENTO[1]', 'VARCHAR(MAX)') = ''
		THEN null
		ELSE ref.value('VALUTAZIONE_INVESTIMENTO[1]', 'VARCHAR(MAX)')
	END AS VALUTAZIONE_INVESTIMENTO,
	CASE 
		WHEN ref.value('ID_VARIANTE[1]', 'VARCHAR(MAX)') = ''
		THEN null
		ELSE ref.value('ID_VARIANTE[1]', 'INT')
	END AS ID_VARIANTE,
	CASE 
		WHEN ref.value('COD_VARIAZIONE[1]', 'CHAR(1)') = ''
		THEN null
		ELSE ref.value('COD_VARIAZIONE[1]', 'CHAR(1)')
	END AS COD_VARIAZIONE,
	ref.value('NON_CONFINANZIATO[1]', 'BIT') as NON_COFINANZIATO
FROM ACCORPAMENTO_INVESTIMENTI I
	CROSS APPLY
	I.ISTANZA_PIANO_INVESTIMENTI.nodes('//IstanzaPianoInvestimenti/PIANO_INVESTIMENTI/PIANO_INVESTIMENTI') AS PIANO_INVESTIMENTI1(ref)
WHERE 1 = 1);
go