CREATE VIEW VRNA_COSTI_X_CODIFICA AS
	SELECT
		CC.ID_COSTI_X_CODIFICA,
		CC.COD_TIPO_SPESA,
		CC.ID_CODIFICA_INVESTIMENTO,
		CI.ID_BANDO,
		TCA.SPESA,
		CI.DESCRIZIONE AS DESCRIZIONE_INVESTIMENTO
	FROM
		RNA_COSTI_X_CODIFICA CC INNER JOIN
		RNA_TIPO_COSTO_AMMISSIBILE TCA ON CC.COD_TIPO_SPESA = TCA.COD_TIPO_SPESA INNER JOIN
		CODIFICA_INVESTIMENTO CI ON CC.ID_CODIFICA_INVESTIMENTO = CI.ID_CODIFICA_INVESTIMENTO