CREATE VIEW [dbo].[vWORKFLOW_PROCEDURE]
AS
SELECT     dbo.WORKFLOW_PROCEDURE.COD_TIPO_PROCEDURA, dbo.WORKFLOW_PROCEDURE.COD_WORKFLOW, dbo.WORKFLOW_PROCEDURE.ORDINE, 
                      dbo.WORKFLOW_PROCEDURE.OBBLIGATORIO, dbo.WORKFLOW.DESCRIZIONE, dbo.WORKFLOW.URL
FROM         dbo.WORKFLOW_PROCEDURE INNER JOIN
                      dbo.WORKFLOW ON dbo.WORKFLOW_PROCEDURE.COD_WORKFLOW = dbo.WORKFLOW.COD_WORKFLOW
