
CREATE VIEW [dbo].[vzDIMENSIONI_ESTRAZIONI_T]
AS
SELECT        ID_ESTRAZIONE, DATA_INIZIO, DATA_FINE, COD_PSR, BLOCCATO, TIPO_INDICATORI, YEAR(DATA_INIZIO) AS ANNO
FROM            dbo.zDIMENSIONI_ESTRAZIONI_T

