
CREATE VIEW [dbo].[vzDIMENSIONI_INDICATORI_X_PRIORITAI]
AS
SELECT DISTINCT 
                         TOP (100) PERCENT dbo.vzPROGRAMMAZIONE.COD_PSR, dbo.zDIMENSIONI.ID AS ID_DIM_PRIORITA, dbo.zDIMENSIONI.CODICE AS CodPriorita, 
                         dbo.zDIMENSIONI.DESCRIZIONE AS DesPriorita, dbo.zDIMENSIONI.ORDINE AS OrdPriorita, 
                         dbo.zDIMENSIONI_X_PROGRAMMAZIONE.ID_DIMENSIONE AS ID_DIM_INDICATORE, zDIMENSIONI_1.DESCRIZIONE AS DesIndicatore, 
                         zDIMENSIONI_1.CODICE AS CodIndicatore, dbo.vzDIMENSIONI_VALPROGRAMMATO.VALORE_PF, dbo.vzDIMENSIONI_VALPROGRAMMATO.VALORE_F, 
                         dbo.vzDIMENSIONI_VALPROGRAMMATO.DATA_PF, dbo.vzDIMENSIONI_VALPROGRAMMATO.DATA_F, 0 AS ID_ESTRAZIONE, NULL AS DATA_ESTRAZIONE, 
                         zDIMENSIONI_1.ORDINE AS OrdIndicatore, 0 AS VALORE_RTOT, zDIMENSIONI_1.UM
FROM            dbo.zDIMENSIONI AS zDIMENSIONI_1 INNER JOIN
                         dbo.zDIMENSIONI_X_PROGRAMMAZIONE ON zDIMENSIONI_1.ID = dbo.zDIMENSIONI_X_PROGRAMMAZIONE.ID_DIMENSIONE INNER JOIN
                         dbo.zDIMENSIONI_X_PROGRAMMAZIONE AS zDIMENSIONI_X_PROGRAMMAZIONE_1 INNER JOIN
                         dbo.vzPROGRAMMAZIONE ON zDIMENSIONI_X_PROGRAMMAZIONE_1.ID_PROGRAMMAZIONE = dbo.vzPROGRAMMAZIONE.ID_PADRE INNER JOIN
                         dbo.zDIMENSIONI ON zDIMENSIONI_X_PROGRAMMAZIONE_1.ID_DIMENSIONE = dbo.zDIMENSIONI.ID ON 
                         dbo.zDIMENSIONI_X_PROGRAMMAZIONE.ID_PROGRAMMAZIONE = dbo.vzPROGRAMMAZIONE.ID LEFT OUTER JOIN
                         dbo.vzDIMENSIONI_VALPROGRAMMATO ON zDIMENSIONI_1.ID = dbo.vzDIMENSIONI_VALPROGRAMMATO.ID_DIM_INDICATORE AND 
                         dbo.zDIMENSIONI.ID = dbo.vzDIMENSIONI_VALPROGRAMMATO.ID_DIM_PRIORITA
WHERE        (dbo.zDIMENSIONI.COD_DIM = 'PI') AND (zDIMENSIONI_1.COD_DIM = 'IOC' OR
                         zDIMENSIONI_1.COD_DIM = 'IOS')

