CREATE VIEW [dbo].[vzSTP]
AS
SELECT     dbo.zSTP.ID, dbo.zSTP.ID_PROGRAMMAZIONE, dbo.zSTP.CODICE, dbo.zSTP.DESCRIZIONE,
  			SUBSTRING(dbo.vzPROGRAMMAZIONE.TIPO+' '+dbo.vzPROGRAMMAZIONE.CODICE+' - '+
					  dbo.vzPROGRAMMAZIONE.DESCRIZIONE,0,140) AS PROGRAMMAZIONE,
			dbo.zPSR.DESCRIZIONE+' '+CAST(ANNO_DA AS CHAR(4))+' - '+CAST(ANNO_A AS CHAR(4)) AS PSR,
			zPSR.ANNO_DA, zPSR.ANNO_A
                       
FROM         dbo.zSTP 
			INNER JOIN dbo.vzPROGRAMMAZIONE 
				ON dbo.zSTP.ID_PROGRAMMAZIONE = dbo.vzPROGRAMMAZIONE.ID			
			INNER JOIN zPSR 
				ON dbo.vzPROGRAMMAZIONE.COD_PSR=dbo.zPSR.CODICE
