-- DROP TABLE TESTATA_VALIDAZIONE
CREATE TABLE TESTATA_VALIDAZIONE
(
	ID_TESTATA INT IDENTITY (1, 1) NOT NULL PRIMARY KEY,
	CF_INSERIMENTO VARCHAR(16) NOT NULL,
	DATA_INSERIMENTO DATETIME NOT NULL,
	CF_MODIFICA VARCHAR(16) NOT NULL,
	DATA_MODIFICA DATETIME NOT NULL DEFAULT GETDATE(),

	--ID_ISTANZA_CHECKLIST_GENERICA INT NULL,

	ID_LOTTO INT NULL,
	ID_DOMANDA_PAGAMENTO INT NOT NULL,
	CF_VALIDATORE VARCHAR(16) NULL,
	SELEZIONATA_X_REVISIONE BIT NULL DEFAULT 0,
	APPROVATA BIT NULL,
	NUMERO_ESTRAZIONE INT NULL DEFAULT 0,
	ORDINE INT NULL,
	SEGNATURA_REVISIONE VARCHAR(100) NULL,
	SEGNATURA_SECONDA_REVISIONE VARCHAR(100) NULL,
	DATA_VALIDAZIONE DATETIME NULL,
	AUTOVALUTAZIONE BIT DEFAULT(0) NOT NULL
);

ALTER TABLE TESTATA_VALIDAZIONE  WITH CHECK ADD  CONSTRAINT FK_TESTATA_VALIDAZIONE_DOMANDA_DI_PAGAMENTO FOREIGN KEY(ID_DOMANDA_PAGAMENTO)
REFERENCES DOMANDA_DI_PAGAMENTO (ID_DOMANDA_PAGAMENTO)
GO

ALTER TABLE TESTATA_VALIDAZIONE CHECK CONSTRAINT FK_TESTATA_VALIDAZIONE_DOMANDA_DI_PAGAMENTO
GO

ALTER TABLE TESTATA_VALIDAZIONE  WITH CHECK ADD  CONSTRAINT FK_TESTATA_VALIDAZIONE_LOTTO_DI_REVISIONE FOREIGN KEY(ID_LOTTO)
REFERENCES LOTTO_DI_REVISIONE (ID_LOTTO)
GO

ALTER TABLE TESTATA_VALIDAZIONE CHECK CONSTRAINT FK_TESTATA_VALIDAZIONE_LOTTO_DI_REVISIONE
GO
