-- DROP TABLE TESTATA_VALIDAZIONE_X_ISTANZA
CREATE TABLE TESTATA_VALIDAZIONE_X_ISTANZA
(
	ID_TESTATA_VALIDAZIONE_X_ISTANZA INT IDENTITY (1, 1) NOT NULL PRIMARY KEY,
	CF_INSERIMENTO VARCHAR(16) NOT NULL,
	DATA_INSERIMENTO DATETIME NOT NULL,
	CF_MODIFICA VARCHAR(16) NOT NULL,
	DATA_MODIFICA DATETIME NOT NULL DEFAULT GETDATE(),

	ID_TESTATA_VALIDAZIONE INT NOT NULL,
	ID_ISTANZA_CHECKLIST_GENERICA INT NULL,
	ORDINE INT DEFAULT(1) NOT NULL,
	NOTE VARCHAR(MAX) NULL
)

ALTER TABLE TESTATA_VALIDAZIONE_X_ISTANZA  WITH CHECK ADD  CONSTRAINT FK_TESTATA_VALIDAZIONE_X_ISTANZA_TESTATA_VALIDAZIONE FOREIGN KEY(ID_TESTATA_VALIDAZIONE)
REFERENCES TESTATA_VALIDAZIONE (ID_TESTATA)
GO

ALTER TABLE TESTATA_VALIDAZIONE_X_ISTANZA CHECK CONSTRAINT FK_TESTATA_VALIDAZIONE_X_ISTANZA_TESTATA_VALIDAZIONE
GO

ALTER TABLE TESTATA_VALIDAZIONE_X_ISTANZA  WITH CHECK ADD  CONSTRAINT FK_TESTATA_VALIDAZIONE_X_ISTANZA_ISTANZA_CHECKLIST_GENERICA FOREIGN KEY(ID_ISTANZA_CHECKLIST_GENERICA)
REFERENCES ISTANZA_CHECKLIST_GENERICA (ID_ISTANZA_GENERICA)
GO

ALTER TABLE TESTATA_VALIDAZIONE_X_ISTANZA CHECK CONSTRAINT FK_TESTATA_VALIDAZIONE_X_ISTANZA_ISTANZA_CHECKLIST_GENERICA
GO