//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace web.CONTROLS {
    
    
    public partial class AdminCUPCategoriaSoggetto {
        
        /// <summary>
        /// cmbCategoria control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SiarLibrary.Web.ComboCUPCategoriaSoggetto cmbCategoria;
        
        /// <summary>
        /// cmbCategoriaSub control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SiarLibrary.Web.ComboCUPCategoriaSoggettoSub cmbCategoriaSub;
        
        /// <summary>
        /// hdnsavedatimonitoraggioCategoriaSub control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden hdnsavedatimonitoraggioCategoriaSub;
    }
}
