//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4984
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web.CONTROLS {
    
    
    public partial class InvestimentoDettaglioMutuoTip2 {
        
        /// <summary>
        /// btnPostBack control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SiarLibrary.Web.Button btnPostBack;
        
        /// <summary>
        /// dgDomandaPsr control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SiarLibrary.Web.DataGrid dgDomandaPsr;
        
        /// <summary>
        /// btnVisualizzaPianoInvestimentiSelezionata control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputButton btnVisualizzaPianoInvestimentiSelezionata;
        
        /// <summary>
        /// txtAmmontareInvestimenti control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SiarLibrary.Web.CurrencyBox txtAmmontareInvestimenti;
        
        /// <summary>
        /// txtAmmontare control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SiarLibrary.Web.CurrencyBox txtAmmontare;
        
        /// <summary>
        /// txtAttualizzazione control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SiarLibrary.Web.CurrencyBox txtAttualizzazione;
        
        /// <summary>
        /// lstAnni control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SiarLibrary.Web.ComboBase lstAnni;
        
        /// <summary>
        /// txtTasso control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SiarLibrary.Web.CurrencyBox txtTasso;
        
        /// <summary>
        /// btnCalcolaContributo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SiarLibrary.Web.Button btnCalcolaContributo;
        
        /// <summary>
        /// txtRateAnnuali control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SiarLibrary.Web.CurrencyBox txtRateAnnuali;
        
        /// <summary>
        /// txtContributoAmmissibile control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SiarLibrary.Web.CurrencyBox txtContributoAmmissibile;
        
        /// <summary>
        /// rowContributoMessaggio control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell rowContributoMessaggio;
        
        /// <summary>
        /// tableValutazione control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTable tableValutazione;
        
        /// <summary>
        /// txtValutazioneLunga control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SiarLibrary.Web.TextArea txtValutazioneLunga;
        
        /// <summary>
        /// btnVisualizzaOriginale control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputButton btnVisualizzaOriginale;
    }
}
