-- =============================================

CREATE FUNCTION [dbo].[calcoloContributoInvestimentiProgetto] 
(
	@ID_PROGETTO INT, --ID DEL PROGETTO INTEGRATO
	@FASE_ISTRUTTORIA BIT =0, --SE 0 CALCOLO PER GLI INVESTIMENTI ORIGINALI ALTRIMENTI PER GLI AMMESSI IN ISTRUTTORIA
	@ID_VARIANTE INT =NULL -- SE NON NULLA CALCOLO PER LA VARIAZIONE
)
RETURNS DECIMAL(18,2)
AS BEGIN
 /*
DECLARE @ID_PROGETTO INT, @FASE_ISTRUTTORIA BIT,@ID_VARIANTE INT
SET @ID_PROGETTO= 792
SET	@FASE_ISTRUTTORIA =0
SET @ID_VARIANTE=NULL */

 RETURN    (SELECT SUM ( CONTRIBUTO_INVESTIMENTI ) AS CONTRIBUTO_INVESTIMENTI 
          FROM 
(SELECT  (CASE
		 WHEN (IMPORTO_MAX IS NOT NULL AND IMPORTO_MAX<(CONTRIBUTO_INVESTIMENTI+CONTRIBUTO_SPESE)) 
						THEN IMPORTO_MAX-CONTRIBUTO_SPESE  
/* 		WHEN ( ISNULL(IMPORTO_MAX,0)=0 AND (SELECT COUNT(*) FROM PROGETTO  WHERE ID_BANDO IN (114,165) AND ID_PROGETTO = @ID_PROGETTO ) > 0 AND (SELECT COUNT(*) FROM PRIORITA_X_PROGETTO WHERE ID_PROGETTO = @ID_PROGETTO AND ID_PRIORITA IN ( 185 ))= 0 AND  --MASSIMALI PER IL 311 B PSR AZIONE D PER INVESTIMENTI IN BIOGAS
	                (CONTRIBUTO_INVESTIMENTI+CONTRIBUTO_SPESE)  > 200000 )THEN 200000  - CONTRIBUTO_SPESE
		WHEN ( ISNULL(IMPORTO_MAX,0)=0   AND  (SELECT COUNT(*) FROM PROGETTO  WHERE ID_BANDO IN (114,165) AND ID_PROGETTO = @ID_PROGETTO ) > 0 AND (SELECT COUNT(*) FROM PRIORITA_X_PROGETTO WHERE ID_PROGETTO = @ID_PROGETTO AND ID_PRIORITA IN ( 185 ))> 0 AND
	                (CONTRIBUTO_INVESTIMENTI+CONTRIBUTO_SPESE)  > 500000 )THEN 500000  - CONTRIBUTO_SPESE 
		WHEN ( ISNULL(IMPORTO_MAX,0)=0   AND (SELECT COUNT(*) FROM PRIORITA_X_PROGETTO WHERE ID_PROGETTO = @ID_PROGETTO AND ID_PRIORITA IN ( 141,144 ))> 0 AND   --MASSIMALE BANDO 311B PABS 
	                (CONTRIBUTO_INVESTIMENTI+CONTRIBUTO_SPESE)  > 200000 )THEN 200000  - CONTRIBUTO_SPESE 
		WHEN ( ISNULL(IMPORTO_MAX,0)=0 AND  (SELECT COUNT(*) FROM PROGETTO  WHERE ID_BANDO IN (260) AND ID_PROGETTO = @ID_PROGETTO ) > 0 
			   AND ((CONTRIBUTO_INVESTIMENTI+CONTRIBUTO_SPESE) - ISNULL((SELECT ISNULL( VALORE,0) FROM PROGETTO PP LEFT JOIN  PRIORITA_X_PROGETTO P ON P.ID_PROGETTO = PP.ID_PROGETTO AND ( P.ID_PRIORITA IN (786)) WHERE (PP.ID_PROGETTO = @ID_PROGETTO)),0)) >= 250000) --massimale bando strutture 
							 THEN 250000
	    WHEN (ISNULL(IMPORTO_MAX,0)=0 AND  (SELECT COUNT(*) FROM PROGETTO  WHERE ID_BANDO IN (260) AND ID_PROGETTO = @ID_PROGETTO ) > 0 
				AND (CONTRIBUTO_INVESTIMENTI+CONTRIBUTO_SPESE) > 0 AND (CONTRIBUTO_INVESTIMENTI+CONTRIBUTO_SPESE)-(SELECT ISNULL( VALORE,0) FROM PROGETTO PP LEFT JOIN  PRIORITA_X_PROGETTO P ON P.ID_PROGETTO = PP.ID_PROGETTO AND ( P.ID_PRIORITA IN (786)) WHERE (PP.ID_PROGETTO = @ID_PROGETTO)) < 250000 )
							 THEN (CONTRIBUTO_INVESTIMENTI+CONTRIBUTO_SPESE)-ISNULL((SELECT ISNULL(VALORE,0) FROM PRIORITA_X_PROGETTO WHERE ID_PROGETTO = @ID_PROGETTO AND ID_PRIORITA IN (786)), 0)
	    
	    WHEN (ISNULL(IMPORTO_MAX,0)=0 AND  (SELECT COUNT(*) FROM PROGETTO  WHERE ID_BANDO IN (261) AND ID_PROGETTO = @ID_PROGETTO ) > 0 
			   AND ((CONTRIBUTO_INVESTIMENTI+CONTRIBUTO_SPESE) -(SELECT ISNULL(VALORE,0) FROM PRIORITA_X_PROGETTO WHERE ID_PROGETTO = @ID_PROGETTO AND ID_PRIORITA IN (786))) >= 100000) --massimale bando 
							 THEN 100000
		WHEN (ISNULL(IMPORTO_MAX,0)=0 AND  (SELECT COUNT(*) FROM PROGETTO  WHERE ID_BANDO IN (261) AND ID_PROGETTO = @ID_PROGETTO ) > 0 
				AND (CONTRIBUTO_INVESTIMENTI+CONTRIBUTO_SPESE) > 0 AND (CONTRIBUTO_INVESTIMENTI+CONTRIBUTO_SPESE)-(SELECT ISNULL(VALORE,0) FROM PRIORITA_X_PROGETTO WHERE ID_PROGETTO = @ID_PROGETTO AND ID_PRIORITA IN (786)) < 100000 )
							 THEN (CONTRIBUTO_INVESTIMENTI+CONTRIBUTO_SPESE)-(SELECT ISNULL(VALORE,0) FROM PRIORITA_X_PROGETTO WHERE ID_PROGETTO = @ID_PROGETTO AND ID_PRIORITA IN (786))
		WHEN (ISNULL(IMPORTO_MAX,0)=0 AND --311 2013 PRESENZA INVESTIMENTI NELLA IV SCADENZA GIOVANI
			 (SELECT COUNT(*) FROM PROGETTO  WHERE ID_BANDO IN (385) AND ID_PROGETTO = @ID_PROGETTO ) > 0 	AND 
			 (SELECT COUNT(*) FROM VPROGETTO P INNER JOIN PIANO_INVESTIMENTI INV ON INV.ID_PROGETTO = P.ID_PROGETTO AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL  
			  WHERE ID_BANDO = 138 AND P.COD_STATO ='N' AND COSTO_INVESTIMENTO >0 AND ID_IMPRESA = (SELECT ID_IMPRESA FROM PROGETTO WHERE ID_PROGETTO = @ID_PROGETTO) )> 0
				AND (CONTRIBUTO_INVESTIMENTI+CONTRIBUTO_SPESE)  > 140000 ) THEN 140000 - CONTRIBUTO_SPESE
		WHEN (ISNULL(IMPORTO_MAX,0)=0 AND --311 2013 - NUOVI BENEFICIARI
				(SELECT COUNT(*) FROM PROGETTO  WHERE ID_BANDO IN (385) AND ID_PROGETTO = @ID_PROGETTO ) > 0 	AND 
				(SELECT COUNT(*) FROM VPROGETTO P INNER JOIN PIANO_INVESTIMENTI INV ON INV.ID_PROGETTO = P.ID_PROGETTO AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL 
				 WHERE ID_BANDO = 138 AND P.COD_STATO ='N' AND COSTO_INVESTIMENTO >0 AND ID_IMPRESA = (SELECT ID_IMPRESA FROM PROGETTO WHERE ID_PROGETTO = @ID_PROGETTO) )= 0
				AND (CONTRIBUTO_INVESTIMENTI+CONTRIBUTO_SPESE)  > 50000 ) THEN 50000 - CONTRIBUTO_SPESE
		WHEN (ISNULL(IMPORTO_MAX,0)=0 AND --121 2013 PRESENZA INVESTIMENTI NELLA IV SCADENZA GIOVANI
			(SELECT COUNT(*) FROM PROGETTO  WHERE ID_BANDO IN (370) AND ID_PROGETTO = @ID_PROGETTO ) > 0 	AND 
				(SELECT COUNT(*) FROM VPROGETTO P INNER JOIN PIANO_INVESTIMENTI INV ON INV.ID_PROGETTO = P.ID_PROGETTO AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL 
				 WHERE ID_BANDO = 136 AND P.COD_STATO ='N' AND COSTO_INVESTIMENTO >0 AND ID_IMPRESA = (SELECT ID_IMPRESA FROM PROGETTO WHERE ID_PROGETTO = @ID_PROGETTO) )> 0
				AND (CONTRIBUTO_INVESTIMENTI+CONTRIBUTO_SPESE)  > 250000 ) THEN 250000 - CONTRIBUTO_SPESE
		WHEN (ISNULL(IMPORTO_MAX,0)=0 AND -- 121 2013 - NUOVI BENEFICIARI
			(SELECT COUNT(*) FROM PROGETTO  WHERE ID_BANDO IN (370) AND ID_PROGETTO = @ID_PROGETTO ) > 0 	AND 
				(SELECT COUNT(*) FROM VPROGETTO P INNER JOIN PIANO_INVESTIMENTI INV ON INV.ID_PROGETTO = P.ID_PROGETTO AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL 
				 WHERE ID_BANDO = 136 AND P.COD_STATO ='N' AND COSTO_INVESTIMENTO >0 AND ID_IMPRESA = (SELECT ID_IMPRESA FROM PROGETTO WHERE ID_PROGETTO = @ID_PROGETTO) )= 0
				AND (CONTRIBUTO_INVESTIMENTI+CONTRIBUTO_SPESE)  > 145000 ) THEN 145000 - CONTRIBUTO_SPESE */
		
		
		ELSE CONTRIBUTO_INVESTIMENTI END )AS CONTRIBUTO_INVESTIMENTI FROM
		( SELECT I.ID_PROGETTO,B.IMPORTO_MAX,
		SUM(CASE 
          WHEN I.COD_TIPO_INVESTIMENTO=1 THEN  ISNULL(CONTRIBUTO_RICHIESTO,0)END) AS CONTRIBUTO_INVESTIMENTI,
          ISNULL(SUM(CASE WHEN I.COD_TIPO_INVESTIMENTO!=1 THEN ISNULL(CONTRIBUTO_RICHIESTO,0)END), 0) AS CONTRIBUTO_SPESE
		FROM PIANO_INVESTIMENTI I INNER JOIN PROGETTO P ON I.ID_PROGETTO=P.ID_PROGETTO
		LEFT JOIN BANDO_TIPO_INVESTIMENTI B ON P.ID_BANDO=B.ID_BANDO AND B.COD_TIPO_INVESTIMENTO=7
			WHERE ((P.ID_PROG_INTEGRATO IS NULL AND P.ID_PROGETTO=@ID_PROGETTO) OR P.ID_PROG_INTEGRATO=@ID_PROGETTO) AND
	   ((@FASE_ISTRUTTORIA=0 AND ID_INVESTIMENTO_ORIGINALE IS NULL AND ID_VARIANTE IS NULL) OR 
		(@FASE_ISTRUTTORIA=1 AND ((@ID_VARIANTE IS NULL AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL) 
		OR (ID_VARIANTE=@ID_VARIANTE AND ISNULL(COD_VARIAZIONE,'x')!='A'))))
		GROUP BY I.ID_PROGETTO,B.IMPORTO_MAX)AS Q1) AS Q2)END
