CREATE FUNCTION calcoloPercentualeCompletamentoRevisionePagamenti
(
	@ID_LOTTO INT
)
RETURNS INT --RITORNA 0: OK, ALTRIMENTI NR DOMANDE ANCORA IN SOSPESO
AS
BEGIN
	/*
	DECLARE @ID_LOTTO INT
	SET @ID_LOTTO= 26*/

	DECLARE @RETVAL INT, @NR_DOMANDE_LOTTO INT, @QUOTA_ESTRAZIONE DECIMAL(10,6), @CAMPIONE INT

	SELECT @QUOTA_ESTRAZIONE=CAST(VALORE AS DECIMAL(10,6)) 
	FROM BANDO_CONFIG C 
		JOIN LOTTO_DI_REVISIONE L ON C.ID_BANDO=L.ID_BANDO 
	WHERE C.COD_TIPO = 'QUOTESTRCAMPVALID' 
		AND L.ID_LOTTO=@ID_LOTTO

	SET @QUOTA_ESTRAZIONE = ISNULL(@QUOTA_ESTRAZIONE, 100); -- IMPONGO QUOTA PREVISTA DAL FESR

	SELECT @NR_DOMANDE_LOTTO = COUNT(ID_DOMANDA_PAGAMENTO) 
	FROM CTE_TESTATA_VALIDAZIONE 
	WHERE 1 = 1
		AND ID_LOTTO = @ID_LOTTO

	SET @CAMPIONE = CEILING(ISNULL(@NR_DOMANDE_LOTTO * @QUOTA_ESTRAZIONE / 100, 0))

	IF @CAMPIONE > @NR_DOMANDE_LOTTO 
		SET @CAMPIONE = @NR_DOMANDE_LOTTO;
	
	SELECT @RETVAL = @CAMPIONE - (SELECT COUNT(*) 
									FROM CTE_TESTATA_VALIDAZIONE R 
										JOIN DOMANDA_DI_PAGAMENTO D ON R.ID_DOMANDA_PAGAMENTO = D.ID_DOMANDA_PAGAMENTO
									WHERE 1 = 1
										AND R.ID_LOTTO = @ID_LOTTO 
										AND R.SELEZIONATA_X_REVISIONE = 1 
										AND R.APPROVATA = 1)

	RETURN ISNULL(@RETVAL, 0)
END
GO
