-- =============================================
--
CREATE FUNCTION [dbo].[calcoloContributoTotaleProgetto] 
(
	@ID_PROGETTO INT, --ID DEL PROGETTO INTEGRATO
	@FASE_ISTRUTTORIA BIT =0, --SE 0 CALCOLO PER GLI INVESTIMENTI ORIGINALI ALTRIMENTI PER GLI AMMESSI IN ISTRUTTORIA
	@ID_VARIANTE INT =NULL -- SE NON NULLA CALCOLO PER LA VARIAZIONE
)
RETURNS DECIMAL(18,2)
AS BEGIN

--DECLARE @ID_PROGETTO INT, @FASE_ISTRUTTORIA BIT,@ID_VARIANTE INT
--SET @ID_PROGETTO= 6367
--SET	@FASE_ISTRUTTORIA =1
--SET @ID_VARIANTE=NULL

RETURN
 (SELECT ISNULL(SUM( Q1.CONTRIBUTO),0)--+DBO.calcoloPremioContoCapitale(@ID_PROGETTO,@FASE_ISTRUTTORIA) 
FROM (SELECT I.ID_PROGETTO,B.IMPORTO_MAX,CONTRIBUTO=CASE 

	----BANDO 311B DE MINIMIS SOLO PER PROGETTI CON REQUISITO SOGGETTIVO 144 O 141 SELEZIONATO 
	--WHEN P.ID_BANDO =89 AND ISNULL(B.IMPORTO_MAX,0)=0 AND (PP.ID_PRIORITA IN (144) OR PP141.ID_PRIORITA IS NOT NULL) AND ISNULL(SUM(CONTRIBUTO_RICHIESTO),0) > 200000 THEN 200000 
	
	-- --BANDO 311B PSR AZIONE D)  DE MINIMIS SOLO PER PROGETTI CON REQUISITO SOGGETTIVO NON IN BIOGAS 200000
	--WHEN P.ID_BANDO IN (114,165) AND ISNULL(B.IMPORTO_MAX,0)=0 AND PP.ID_PRIORITA = 185 AND ISNULL(SUM(CONTRIBUTO_RICHIESTO),0) > 500000 THEN 500000 	 
	 
	----BANDO 311B PSR AZIONE C)  DE MINIMIS SOLO PER PROGETTI CON REQUISITO SOGGETTIVO NON IN BIOGAS 200000	 
	--WHEN P.ID_BANDO IN (114,165) AND ISNULL(B.IMPORTO_MAX,0)=0 AND ISNULL(PP.ID_PRIORITA,0) != 185 AND ISNULL(SUM(CONTRIBUTO_RICHIESTO),0) > 200000 THEN 200000 
	 
	----WHEN  B.ID_BANDO = 128 AND --BANDO 311B PSR AZIONE C)  DE MINIMIS SOLO PER PROGETTI presentati OLTRE IL  31/12/2010
	----	  DATEDIFF(day, (SELECT  DATA_ULTIMA_MODIFICA FROM PROGETTO WHERE ID_PROGETTO = @ID_PROGETTO ) , cast ('2010-31-12 00:00:00' as datetime )) <0  AND
	----	 ISNULL(SUM(ISNULL(CONTRIBUTO_RICHIESTO,0)),0) >200000THEN 200000 
	
	----BANDO 126 CALAMITà IL CONTRIBUTO VIENE DETRATTO DELLA QUOTA DI INDENNITà ASSICURATIVA ID_PRIORITA = 786 
	--WHEN P.ID_BANDO IN (260) AND ISNULL(B.IMPORTO_MAX,0)=0  AND ISNULL(SUM(CONTRIBUTO_RICHIESTO),0)- ISNULL(PP.VALORE,0) >= 250000 THEN 250000
		
	--WHEN P.ID_BANDO IN (260) AND ISNULL(B.IMPORTO_MAX,0)=0  AND ISNULL(SUM(CONTRIBUTO_RICHIESTO),0) > 0 AND ISNULL(SUM(CONTRIBUTO_RICHIESTO),0)-(ISNULL( PP.VALORE,0)) < 250000 
	--							 THEN ISNULL(SUM( CONTRIBUTO_RICHIESTO),0)-(ISNULL( PP.VALORE,0))
								 
	--WHEN P.ID_BANDO IN (261) AND ISNULL(B.IMPORTO_MAX,0)=0 AND ISNULL(SUM(CONTRIBUTO_RICHIESTO),0)- ISNULL(PP.VALORE,0) >= 100000 THEN 100000
	
	--WHEN P.ID_BANDO IN (261) AND ISNULL(B.IMPORTO_MAX,0)=0 AND ISNULL(SUM(CONTRIBUTO_RICHIESTO),0) > 0 AND ISNULL(SUM(CONTRIBUTO_RICHIESTO),0)-ISNULL(PP.VALORE,0)< 100000 
	--							 THEN ISNULL(SUM(CONTRIBUTO_RICHIESTO),0)-ISNULL( PP.VALORE,0)
	
	----311 2013 PRESENZA INVESTIMENTI NELLA IV SCADENZA GIOVANI  
	--WHEN p.ID_BANDO IN (385,429) AND (ISNULL(IMPORTO_MAX,0)=0 AND 
	--				 (SELECT COUNT(*) FROM PROGETTO P112 INNER JOIN PROGETTO_STORICO PS ON PS.ID_PROGETTO =P112.ID_PROGETTO AND PS.COD_STATO ='N'
	--								  INNER JOIN PIANO_INVESTIMENTI INV ON INV.ID_PROGETTO = P112.ID_PROGETTO AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL AND COSTO_INVESTIMENTO >0 					
	--				 WHERE P112.ID_BANDO = 138 AND P112.ID_IMPRESA = P.ID_IMPRESA )> 0 AND SUM(ISNULL(CONTRIBUTO_RICHIESTO,0)) > 140000 ) THEN 140000
	
	----311 2013 - NUOVI BENEFICIARI
	--WHEN P.ID_BANDO IN (385,429) AND (ISNULL(IMPORTO_MAX,0)=0 AND 
	--				(SELECT COUNT(*) FROM PROGETTO P112 INNER JOIN PROGETTO_STORICO PS ON PS.ID_PROGETTO =P112.ID_PROGETTO AND PS.COD_STATO ='N'
	--								  INNER JOIN PIANO_INVESTIMENTI INV ON INV.ID_PROGETTO = P112.ID_PROGETTO AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL AND COSTO_INVESTIMENTO >0 					
	--				 WHERE P112.ID_BANDO = 138 AND P112.ID_IMPRESA = P.ID_IMPRESA)= 0 AND SUM(ISNULL(CONTRIBUTO_RICHIESTO,0))> 50000 ) THEN 50000 
	
	----121 2013 PRESENZA INVESTIMENTI NELLA IV SCADENZA GIOVANI
	--WHEN P. ID_BANDO IN (370) AND  ISNULL(IMPORTO_MAX,0)=0 AND
	--							  (SELECT COUNT(*) FROM PROGETTO P112 INNER JOIN PROGETTO_STORICO PS ON PS.ID_PROGETTO =P112.ID_PROGETTO AND PS.COD_STATO ='N' 
	--											   INNER JOIN PIANO_INVESTIMENTI INV ON INV.ID_PROGETTO = P112.ID_PROGETTO AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL AND COSTO_INVESTIMENTO >0
	--							   WHERE P112.ID_BANDO = 136 AND ID_IMPRESA = P.ID_IMPRESA )> 0 AND SUM(ISNULL(CONTRIBUTO_RICHIESTO,0)) >250000 THEN 250000  
	
	---- 121 2013 - NUOVI BENEFICIARI
	--WHEN P.ID_BANDO IN (370) AND ISNULL(IMPORTO_MAX,0)=0 AND 
	--							 (SELECT COUNT(*) FROM PROGETTO P112 INNER JOIN PROGETTO_STORICO PS ON PS.ID_PROGETTO =P112.ID_PROGETTO AND PS.COD_STATO ='N' 
	--											  INNER JOIN PIANO_INVESTIMENTI INV ON INV.ID_PROGETTO = P112.ID_PROGETTO AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL AND COSTO_INVESTIMENTO >0 
	--							 WHERE P112.ID_BANDO = 136 AND ID_IMPRESA = P.ID_IMPRESA ) = 0 AND SUM(ISNULL(CONTRIBUTO_RICHIESTO,0))  > 145000 THEN 145000 	  
	  
	WHEN ISNULL(B.IMPORTO_MAX,0)=0 THEN ISNULL(SUM( CONTRIBUTO_RICHIESTO),0) 
	
	WHEN ISNULL(B.IMPORTO_MAX,0)<ISNULL(SUM(CONTRIBUTO_RICHIESTO),0) THEN ISNULL(B.IMPORTO_MAX,0) 
	
	ELSE ISNULL(SUM(CONTRIBUTO_RICHIESTO ),0) END
FROM PROGETTO P
	INNER JOIN PIANO_INVESTIMENTI I  ON I.ID_PROGETTO=P.ID_PROGETTO
	LEFT JOIN BANDO_TIPO_INVESTIMENTI B ON P.ID_BANDO=B.ID_BANDO AND B.COD_TIPO_INVESTIMENTO=7
	LEFT JOIN PRIORITA_X_PROGETTO PP ON PP.ID_PROGETTO = P.ID_PROGETTO AND ID_PRIORITA IN (144,185,786)
	LEFT JOIN PRIORITA_X_PROGETTO PP141 ON PP141.ID_PROGETTO = P.ID_PROGETTO AND PP141.ID_PRIORITA IN (141)
WHERE ((P.ID_PROG_INTEGRATO IS NULL AND P.ID_PROGETTO=@ID_PROGETTO) OR P.ID_PROG_INTEGRATO=@ID_PROGETTO) AND
	  ((@FASE_ISTRUTTORIA=0 AND ID_INVESTIMENTO_ORIGINALE IS NULL AND ID_VARIANTE IS NULL) OR 
		(@FASE_ISTRUTTORIA=1 AND ((@ID_VARIANTE IS NULL AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL) 
		OR (ID_VARIANTE=@ID_VARIANTE AND ISNULL(COD_VARIAZIONE,'x')!='A'))))	
GROUP BY I.ID_PROGETTO,B.IMPORTO_MAX , B.ID_BANDO, P.ID_BANDO, pp.ID_PRIORITA, pp.VALORE , P.ID_IMPRESA, PP141.ID_PRIORITA  ) AS Q1)  END
