
CREATE FUNCTION [dbo].[calcoloIndicatoriGetPrioritaInv](@IdInterv int)
RETURNS INT
AS
BEGIN
DECLARE @ESITO INT=0
SELECT  TOP 1   @ESITO = DIM.ID 
FROM           zDIMENSIONI_X_PROGRAMMAZIONE DP INNER JOIN
               zDIMENSIONI DIM ON DP.ID_DIMENSIONE = DIM.ID INNER JOIN
               zPROGRAMMAZIONE PR ON DP.ID_PROGRAMMAZIONE = PR.ID_PADRE
WHERE        (DIM.COD_DIM = 'PI') AND PR.ID = @IdInterv

RETURN @ESITO
END
