CREATE FUNCTION [dbo].[controlliInLocoDomandaPagamento] 
(
	@ID_DOMANDA_PAGAMENTO INT
)
RETURNS CHAR(2) --SI:controlli in loco terminati o non necessari, NO: ancora da effettuare
AS
BEGIN
 --eseguita in istruttoria della domanda di pagamento dopo predisposizione a controllo 
 /*
DECLARE @ID_DOMANDA_PAGAMENTO INT
SET @ID_DOMANDA_PAGAMENTO =189*/

DECLARE @RETURN_VALUE CHAR(2),@SELEZIONATA_X_CONTROLLO BIT,@CONTROLLO_CONCLUSO BIT
SET @RETURN_VALUE='SI'

SELECT TOP 1 @SELEZIONATA_X_CONTROLLO=SELEZIONATA_X_CONTROLLO,@CONTROLLO_CONCLUSO=C.CONTROLLO_CONCLUSO 
FROM CONTROLLI_DOMANDE_PAGAMENTO C INNER JOIN CONTROLLI_LOCO_LOTTO L ON C.ID_LOTTO=L.ID_LOTTO 
WHERE ID_DOMANDA_PAGAMENTO=@ID_DOMANDA_PAGAMENTO AND NUMERO_ESTRAZIONI>0 ORDER BY C.ID_LOTTO DESC

IF(@SELEZIONATA_X_CONTROLLO IS NULL OR (@SELEZIONATA_X_CONTROLLO=1 AND @CONTROLLO_CONCLUSO=0)) SET @RETURN_VALUE='NO'
--SELECT @RETURN_VALUE
RETURN @RETURN_VALUE
END
