
CREATE FUNCTION [dbo].[controlloMassimaliPagamento] 
(
	@ID_PROGETTO INT, --ID_PROGETTO INTEGRATO
	@ID_DOMANDA_PAGAMENTO INT
)
RETURNS INT --0: OK, 1: MINIMO NON RAGGIUNTO, 2: MASSIMO SUPERATO, 3: MINIMO>MASSIMO RICHIEDIBILE
AS
BEGIN
	-- USATA SOLO IN PRESENTAZIONE DOMANDA DI PAGAMENTO PER BLOCCARE IL WORKFLOW
	
	--DECLARE @ID_PROGETTO INT,@ID_DOMANDA_PAGAMENTO INT;SET @ID_PROGETTO=250;SET @ID_DOMANDA_PAGAMENTO=257

	DECLARE @NATURA_CUP VARCHAR(2) = NULL
	SELECT @NATURA_CUP = CUP_NATURA FROM DATI_MONITORAGGIO_FESR WHERE ID_PROGETTO =  @ID_PROGETTO
	DECLARE @ID_VARIANTE INT,@DATA_MODIFICA_PAGAMENTO DATETIME,@COD_TIPO CHAR(3)
	SELECT @DATA_MODIFICA_PAGAMENTO=DATA_MODIFICA,@COD_TIPO=COD_TIPO FROM DOMANDA_DI_PAGAMENTO WHERE ID_DOMANDA_PAGAMENTO=@ID_DOMANDA_PAGAMENTO
	SELECT @ID_VARIANTE=MAX(ID_VARIANTE) FROM VARIANTI WHERE ID_PROGETTO=@ID_PROGETTO AND APPROVATA=1 AND ANNULLATA=0 AND DATA_MODIFICA<@DATA_MODIFICA_PAGAMENTO

	DECLARE @ID_PROGETTO_CORRELATO INT,@ID_BANDO INT,@RETURN_VALUE INT=0
	DECLARE @QUOTA_MINIMA DECIMAL(10,2),@QUOTA_MASSIMA DECIMAL(10,2),@IMPORTO_MINIMO DECIMAL(18,2),@IMPORTO_MASSIMO DECIMAL(18,2),
		@CONTRIBUTO_TOTALE DECIMAL(18,2),@CONTRIBUTO_DOMANDA DECIMAL(18,2),@PREMIO_CONTO_CAPITALE DECIMAL(18,2),
		@CONTRIBUTO_EROGATO DECIMAL(18,2),@ANTICIPO_EROGATO DECIMAL(18,2),@ANTICIPO_RECUPERATO DECIMAL(18,2),@ANTICIPO_RECUPERABILE DECIMAL(18,2),
		@IMPORTO_RECUPERO_ANTICIPO_A_SAL DECIMAL(18,2),@QUOTA_RECUPERO_ANTICIPO_A_SAL DECIMAL(18,2)	
		
	DECLARE PROGETTI CURSOR FOR 
		SELECT ID_PROGETTO,ID_BANDO FROM PROGETTO WHERE ISNULL(ID_PROG_INTEGRATO,ID_PROGETTO)=@ID_PROGETTO
	OPEN PROGETTI
	FETCH NEXT FROM PROGETTI INTO @ID_PROGETTO_CORRELATO,@ID_BANDO 
	WHILE @@FETCH_STATUS=0 BEGIN
		IF @RETURN_VALUE=0 BEGIN
			-- ANNULLO LE VARIABILI
			SET @CONTRIBUTO_TOTALE=NULL;SET @CONTRIBUTO_DOMANDA=NULL;SET @QUOTA_MASSIMA=NULL;SET @QUOTA_MINIMA=NULL;
			SET @IMPORTO_MASSIMO=NULL;SET @IMPORTO_MINIMO=NULL;SET @CONTRIBUTO_EROGATO=NULL;SET @ANTICIPO_EROGATO=NULL;
			SET @ANTICIPO_RECUPERATO=NULL;SET @IMPORTO_RECUPERO_ANTICIPO_A_SAL=NULL;SET @QUOTA_RECUPERO_ANTICIPO_A_SAL=NULL;
			SET @ANTICIPO_RECUPERABILE=NULL
					
			--CARICO IL CONTRIBUTO TOTALE E QUELLO DI PAGAMENTO PER LA MISURA
			SELECT @CONTRIBUTO_TOTALE=SUM(I.CONTRIBUTO_RICHIESTO),@CONTRIBUTO_DOMANDA=SUM(P.CONTRIBUTO_RICHIESTO)		
			FROM PIANO_INVESTIMENTI I LEFT JOIN PAGAMENTI_RICHIESTI P ON I.ID_INVESTIMENTO=P.ID_INVESTIMENTO AND P.ID_DOMANDA_PAGAMENTO=@ID_DOMANDA_PAGAMENTO
			WHERE ID_PROGETTO=@ID_PROGETTO_CORRELATO AND ((@ID_VARIANTE IS NULL AND ID_VARIANTE IS NULL AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL) 
				OR (ID_VARIANTE=@ID_VARIANTE AND ISNULL(COD_VARIAZIONE,'X')!='A'))		
				
			--SE MISURA PREVALENTE E SALDO AGGIUNGO IL CONTO CAPITALE IN PAGAMENTO
			IF @ID_PROGETTO_CORRELATO=@ID_PROGETTO AND @COD_TIPO='SLD' BEGIN
				SET @PREMIO_CONTO_CAPITALE=ISNULL(DBO.calcoloPremioContoCapitaleSaldo(@ID_DOMANDA_PAGAMENTO,0),0)
				IF @PREMIO_CONTO_CAPITALE>0 BEGIN
					SET @CONTRIBUTO_TOTALE=ISNULL(@CONTRIBUTO_TOTALE,0)+@PREMIO_CONTO_CAPITALE
					SET @CONTRIBUTO_DOMANDA=ISNULL(@CONTRIBUTO_DOMANDA,0)+@PREMIO_CONTO_CAPITALE
				END
			END
			
			IF(@CONTRIBUTO_TOTALE>0 AND @CONTRIBUTO_DOMANDA>0) BEGIN
				--CARICO I MASSIMALI DELLA MISURA
				SELECT @QUOTA_MASSIMA=ISNULL(QUOTA_MAX,100),@QUOTA_MINIMA=ISNULL(QUOTA_MIN,0),@IMPORTO_MASSIMO=ISNULL(IMPORTO_MAX,100000000),
					@IMPORTO_MINIMO=ISNULL(IMPORTO_MIN,0) FROM BANDO_TIPO_PAGAMENTO WHERE ID_BANDO=@ID_BANDO AND COD_TIPO=@COD_TIPO		
				-- CONTROLLO CHE LA MISURA CORRELATA PUO' ESSERE PAGATA
				IF @@ROWCOUNT=0 SET @RETURN_VALUE=2
				-- CONTROLLO I MASSIMALI IN VALORE ASSOLUTO
				ELSE IF(@CONTRIBUTO_DOMANDA<@IMPORTO_MINIMO) SET @RETURN_VALUE=1
				ELSE IF(@IMPORTO_MASSIMO>0 AND @CONTRIBUTO_DOMANDA>@IMPORTO_MASSIMO) SET @RETURN_VALUE=2
				ELSE BEGIN
					--CARICO I CONTRIBUTI LIQUIDATI NELLE DOMANDE DI PAGAMENTO PRECEDENTI CONTANDO GLI ANTICIPI
					SELECT @CONTRIBUTO_EROGATO=SUM(IMPORTO_AMMISSIBILE),@ANTICIPO_RECUPERATO=SUM(IMPORTO_RECUPERO_ANTICIPO),
						@ANTICIPO_EROGATO=SUM(CASE WHEN D.COD_TIPO='ANT' THEN IMPORTO_AMMISSIBILE ELSE 0 END)					
					FROM DOMANDA_DI_PAGAMENTO_ESPORTAZIONE E INNER JOIN DOMANDA_DI_PAGAMENTO D ON E.ID_DOMANDA_PAGAMENTO=D.ID_DOMANDA_PAGAMENTO
					WHERE E.ID_PROGETTO=@ID_PROGETTO_CORRELATO AND D.ID_DOMANDA_PAGAMENTO<@ID_DOMANDA_PAGAMENTO AND D.APPROVATA=1 AND D.ANNULLATA=0
					
					-- CALCOLO L'EFFETTIVO CONTRIBUTO PAGAMENTO RICHIESTO
					SELECT @IMPORTO_RECUPERO_ANTICIPO_A_SAL=ISNULL(IMPORTO_MAX,0),@QUOTA_RECUPERO_ANTICIPO_A_SAL=ISNULL(QUOTA_MAX,0) 
					FROM BANDO_TIPO_INVESTIMENTI WHERE COD_TIPO_INVESTIMENTO=8 AND ID_BANDO=@ID_BANDO
					--SELECT @IMPORTO_RECUPERO_ANTICIPO_A_SAL,@QUOTA_RECUPERO_ANTICIPO_A_SAL
					
					-- CALCOLO LA QUOTA DI ANTICIPO RECUPERABILE E ANCORA DA EROGARE IN QUESTA DOMANDA DI PAGAMENTO
					IF @ANTICIPO_EROGATO>0 AND dbo.SIAR_MAX(@IMPORTO_RECUPERO_ANTICIPO_A_SAL,@QUOTA_RECUPERO_ANTICIPO_A_SAL)>0 AND @NATURA_CUP IN ('06','07') BEGIN
						IF @QUOTA_RECUPERO_ANTICIPO_A_SAL>0 SET @QUOTA_RECUPERO_ANTICIPO_A_SAL=@ANTICIPO_EROGATO*@QUOTA_RECUPERO_ANTICIPO_A_SAL/100
						IF @IMPORTO_RECUPERO_ANTICIPO_A_SAL>0 AND @QUOTA_RECUPERO_ANTICIPO_A_SAL>0
							SET @ANTICIPO_RECUPERABILE=dbo.SIAR_MIN(@IMPORTO_RECUPERO_ANTICIPO_A_SAL,@QUOTA_RECUPERO_ANTICIPO_A_SAL)
						ELSE SET @ANTICIPO_RECUPERABILE=dbo.SIAR_MAX(@IMPORTO_RECUPERO_ANTICIPO_A_SAL,@QUOTA_RECUPERO_ANTICIPO_A_SAL)						
						IF @ANTICIPO_RECUPERABILE>@ANTICIPO_EROGATO-@ANTICIPO_RECUPERATO
							SET @ANTICIPO_RECUPERABILE=@ANTICIPO_EROGATO-@ANTICIPO_RECUPERATO
					END
					
					-- CI SONO 4(3) CASI ORA
					IF @COD_TIPO='SAL' AND @NATURA_CUP IN ('06','07') BEGIN
						-- SE A SAL E' IMPOSTATO IL RECUPERO ANTICIPO
						IF @ANTICIPO_RECUPERABILE>0 SET @CONTRIBUTO_DOMANDA=@CONTRIBUTO_DOMANDA+ISNULL(@CONTRIBUTO_EROGATO,0)
								-ISNULL(@ANTICIPO_RECUPERATO,0)-@ANTICIPO_RECUPERABILE
						-- SE IL RECUPERO ANTICIPO E' SOLO A SALDO
						ELSE SET @CONTRIBUTO_DOMANDA=@CONTRIBUTO_DOMANDA+ISNULL(@CONTRIBUTO_EROGATO,0)
					END
					-- A SALDO, SIA SE RECUPERO A SAL O NO
					ELSE 
					IF @NATURA_CUP IN ('06','07') BEGIN
					SET @CONTRIBUTO_DOMANDA=@CONTRIBUTO_DOMANDA-ISNULL(@ANTICIPO_EROGATO,0)+ISNULL(@ANTICIPO_RECUPERATO,0)
					END ELSE
					SET @CONTRIBUTO_DOMANDA=@CONTRIBUTO_DOMANDA
					--END
					--da commentare  -- 10807
				   --IF(@ID_PROGETTO = 10031  ) IF @CONTRIBUTO_DOMANDA<0 SET @CONTRIBUTO_DOMANDA=0
					
					--CONTROLLI 
					DECLARE @MINIMO DECIMAL(18,2),@MASSIMO DECIMAL(18,2)
					SET @MINIMO=@CONTRIBUTO_TOTALE*@QUOTA_MINIMA/100
					SET @MASSIMO=@CONTRIBUTO_TOTALE*@QUOTA_MASSIMA/100
					IF(@MASSIMO>0 AND @CONTRIBUTO_DOMANDA>@MASSIMO) SET @RETURN_VALUE=2
					ELSE IF(@CONTRIBUTO_DOMANDA<@MINIMO) SET @RETURN_VALUE=1
				END
			 END
		--SELECT @CONTRIBUTO_TOTALE AS CONTRIBUTO_TOTALE,@CONTRIBUTO_DOMANDA AS CONTRIBUTO_DOMANDA,@MINIMO AS MINIMO,@MASSIMO AS MASSIMO,
		--@QUOTA_MASSIMA AS QUOTA_MASSIMA,@QUOTA_MINIMA AS QUOTA_MINIMA,@IMPORTO_MINIMO AS IMPORTO_MINIMO,@IMPORTO_MASSIMO AS IMPORTO_MASSIMO,
		--@CONTRIBUTO_EROGATO AS CONTRIBUTO_EROGATO,@ANTICIPO_RECUPERATO AS ANTICIPO_RECUPERATO,@ANTICIPO_EROGATO AS ANTICIPO_EROGATO,
		--@ANTICIPO_RECUPERABILE AS ANTICIPO_RECUPERABILE
		END
		FETCH NEXT FROM PROGETTI INTO @ID_PROGETTO_CORRELATO,@ID_BANDO  
	END
	CLOSE PROGETTI
	DEALLOCATE PROGETTI
	RETURN @RETURN_VALUE
END