CREATE FUNCTION [dbo].[ConvertNumberToDigit] 
(
	@NUMERO DECIMAL(18,5)
)
RETURNS VARCHAR(700)
AS
BEGIN
	/*DECLARE @NUMERO DECIMAL(18,5)
	SET @NUMERO = 1234567.806*/
	
	DECLARE @PARTE_INTERA INT,@PARTE_DECIMALE DECIMAL(10,5),@SUFFISSO_DECIMALE CHAR(3),@STRINGA_PARTE_INTERA VARCHAR(50),@ORDINE_TERZINA INT,
		@STRINGA_FINALE VARCHAR(700)		

	SET @PARTE_INTERA=ROUND(@NUMERO,0,1)
	SET @PARTE_DECIMALE=ROUND(@NUMERO-@PARTE_INTERA,2)
	SET @SUFFISSO_DECIMALE='/'+SUBSTRING(CAST(@PARTE_DECIMALE AS VARCHAR(10)),3,2)
	SET @STRINGA_PARTE_INTERA=CAST(@PARTE_INTERA AS VARCHAR(50))
	SET @ORDINE_TERZINA=1

	WHILE LEN(@STRINGA_PARTE_INTERA)>3 BEGIN	
		SET @STRINGA_FINALE=dbo.ConvertNumberToDigit_Terzina(SUBSTRING(@STRINGA_PARTE_INTERA,LEN(@STRINGA_PARTE_INTERA)-2,3),@ORDINE_TERZINA)
			+ISNULL(@STRINGA_FINALE,'')
		SET @STRINGA_PARTE_INTERA=SUBSTRING(@STRINGA_PARTE_INTERA,0,LEN(@STRINGA_PARTE_INTERA)-2)
		SET @ORDINE_TERZINA=@ORDINE_TERZINA+1
	END
	SET @STRINGA_FINALE=dbo.ConvertNumberToDigit_Terzina(@STRINGA_PARTE_INTERA,@ORDINE_TERZINA)+ISNULL(@STRINGA_FINALE,'')	
	RETURN @STRINGA_FINALE+@SUFFISSO_DECIMALE
END
