CREATE FUNCTION [dbo].[fnGetNrFirmatariProgetto]
(
	@ID_PROGETTO INT,
	@ISTRUTTORIA BIT
)
RETURNS INT
AS BEGIN
	DECLARE @NR_FIRMATARI INT
	IF (SELECT COUNT(*) FROM PROGETTO P INNER JOIN BUSINESS_PLAN B ON B.ID_BANDO=P.ID_BANDO 
		WHERE ID_PROGETTO=@ID_PROGETTO AND ID_QUADRO=29)>0 BEGIN
		-- CONTO I COFIRMATARI
		SELECT @NR_FIRMATARI=COUNT(*) FROM PROGETTO P INNER JOIN PERSONE_X_IMPRESE PXP ON P.ID_IMPRESA=PXP.ID_IMPRESA
		WHERE ID_PROGETTO=@ID_PROGETTO AND COD_RUOLO='C' AND DATA_FINE IS NULL --AND (@ISTRUTTORIA=0 OR (@ISTRUTTORIA=1 AND PXP.AMMESSO=1))
	END
	SET @NR_FIRMATARI=ISNULL(@NR_FIRMATARI,0)+1 -- AGGIUNGO IL RAPPRESENTANTE LEGALE
	RETURN @NR_FIRMATARI
END
