CREATE FUNCTION [dbo].[SIAR_MIN] 
(
	@TPARAGONE1 DECIMAL(18,5), 
	@TPARAGONE2 DECIMAL(18,5)
)
RETURNS DECIMAL(18,5)
AS
BEGIN
	IF @TPARAGONE1>@TPARAGONE2 RETURN @TPARAGONE2
	RETURN @TPARAGONE1
END
