CREATE FUNCTION [dbo].[SIAR_COMPARE_STRING]
(
	@STR1 VARCHAR(50),
	@STR2 VARCHAR(50)
)
RETURNS INT
AS BEGIN
	DECLARE @RETVAL INT
	SELECT @RETVAL=ABS(LEN(@STR1)-LEN(@STR2))
	IF @RETVAL=0 BEGIN
		WHILE LEN(@STR1)>0 BEGIN
			IF SUBSTRING(@STR1,1,1)!=SUBSTRING(@STR2,1,1) SET @RETVAL=@RETVAL+1	
			SET @STR1=SUBSTRING(@STR1,2,50)
			SET @STR2=SUBSTRING(@STR2,2,50)
		END
	END
	RETURN @RETVAL
END
