//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:2.0.50727.8762
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web.Private.Istruttoria {
    
    
    public partial class GraduatoriaDettaglio {
        
        /// <summary>
        /// Controllo ucInfoDomanda.
        /// </summary>
        /// <remarks>
        /// Campo generato automaticamente.
        /// Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
        /// </remarks>
        protected global::web.CONTROLS.InfoDomanda ucInfoDomanda;
        
        /// <summary>
        /// Controllo lblFinanziabilita.
        /// </summary>
        /// <remarks>
        /// Campo generato automaticamente.
        /// Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
        /// </remarks>
        protected global::SiarLibrary.Web.Label lblFinanziabilita;
        
        /// <summary>
        /// Controllo dg.
        /// </summary>
        /// <remarks>
        /// Campo generato automaticamente.
        /// Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
        /// </remarks>
        protected global::SiarLibrary.Web.DataGrid dg;
        
        /// <summary>
        /// Controllo btnConferma.
        /// </summary>
        /// <remarks>
        /// Campo generato automaticamente.
        /// Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
        /// </remarks>
        protected global::SiarLibrary.Web.Button btnConferma;
        
        /// <summary>
        /// Controllo btnAnnullaContributo.
        /// </summary>
        /// <remarks>
        /// Campo generato automaticamente.
        /// Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
        /// </remarks>
        protected global::SiarLibrary.Web.Button btnAnnullaContributo;
        
        /// <summary>
        /// Controllo txtFondoRiservaTotale.
        /// </summary>
        /// <remarks>
        /// Campo generato automaticamente.
        /// Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
        /// </remarks>
        protected global::SiarLibrary.Web.CurrencyBox txtFondoRiservaTotale;
        
        /// <summary>
        /// Controllo txtFondoRiservaUtilizzato.
        /// </summary>
        /// <remarks>
        /// Campo generato automaticamente.
        /// Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
        /// </remarks>
        protected global::SiarLibrary.Web.CurrencyBox txtFondoRiservaUtilizzato;
        
        /// <summary>
        /// Controllo txtFondoRiservaDisponibile.
        /// </summary>
        /// <remarks>
        /// Campo generato automaticamente.
        /// Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
        /// </remarks>
        protected global::SiarLibrary.Web.CurrencyBox txtFondoRiservaDisponibile;
        
        /// <summary>
        /// Controllo txtContributoTotaleDomanda.
        /// </summary>
        /// <remarks>
        /// Campo generato automaticamente.
        /// Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
        /// </remarks>
        protected global::SiarLibrary.Web.CurrencyBox txtContributoTotaleDomanda;
        
        /// <summary>
        /// Controllo txtFondoRiservaDomanda.
        /// </summary>
        /// <remarks>
        /// Campo generato automaticamente.
        /// Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
        /// </remarks>
        protected global::SiarLibrary.Web.CurrencyBox txtFondoRiservaDomanda;
        
        /// <summary>
        /// Controllo btnUtilizzaRiserva.
        /// </summary>
        /// <remarks>
        /// Campo generato automaticamente.
        /// Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
        /// </remarks>
        protected global::SiarLibrary.Web.Button btnUtilizzaRiserva;
        
        /// <summary>
        /// Controllo btnRevocaRiserva.
        /// </summary>
        /// <remarks>
        /// Campo generato automaticamente.
        /// Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
        /// </remarks>
        protected global::SiarLibrary.Web.Button btnRevocaRiserva;
    }
}
