CREATE TABLE [dbo].[MODIFICA_DATI_GENERALE](
	[ID_MODIFICA] [int] IDENTITY(1,1) NOT NULL,
	[ID_PROGETTO] [int] NOT NULL,
	[ID_DOMANDA] [int] NULL,
	[ID_VARIANTE] [int] NULL,
	[ID_UTENTE_MODIFICA] [int] NOT NULL,
	[DATA_MODIFICA] [datetime] NOT NULL,
	[COD_TIPO_MODIFICA] [int] NULL,
	[NOTE] VARCHAR(MAX) NULL,
	[ISTANZA_PRECEDENTE] [xml] NULL,
	[ISTANZA_NUOVO] [xml] NULL,
 CONSTRAINT [PK_MODIFICA_DATI_GENERALE] PRIMARY KEY CLUSTERED 
(
	[ID_MODIFICA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[MODIFICA_DATI_GENERALE] ADD  CONSTRAINT [DF_MODIFICA_DATI_GENERALE_DATA_MODIFICA]  DEFAULT (getdate()) FOR [DATA_MODIFICA]
GO

ALTER TABLE [dbo].[MODIFICA_DATI_GENERALE]  WITH CHECK ADD  CONSTRAINT [FK_MODIFICA_DATI_GENERALE_DOMANDA_DI_PAGAMENTO] FOREIGN KEY([ID_DOMANDA])
REFERENCES [dbo].[DOMANDA_DI_PAGAMENTO] ([ID_DOMANDA_PAGAMENTO])
GO

ALTER TABLE [dbo].[MODIFICA_DATI_GENERALE] CHECK CONSTRAINT [FK_MODIFICA_DATI_GENERALE_DOMANDA_DI_PAGAMENTO]
GO

ALTER TABLE [dbo].[MODIFICA_DATI_GENERALE]  WITH CHECK ADD  CONSTRAINT [FK_MODIFICA_DATI_GENERALE_PROGETTO] FOREIGN KEY([ID_PROGETTO])
REFERENCES [dbo].[PROGETTO] ([ID_PROGETTO])
GO

ALTER TABLE [dbo].[MODIFICA_DATI_GENERALE] CHECK CONSTRAINT [FK_MODIFICA_DATI_GENERALE_PROGETTO]
GO

ALTER TABLE [dbo].[MODIFICA_DATI_GENERALE]  WITH CHECK ADD  CONSTRAINT [FK_MODIFICA_DATI_GENERALE_TIPO_MODIFICA_GENERALE] FOREIGN KEY([COD_TIPO_MODIFICA])
REFERENCES [dbo].[TIPO_MODIFICA_GENERALE] ([ID_TIPO_MODIFICA])
GO

ALTER TABLE [dbo].[MODIFICA_DATI_GENERALE] CHECK CONSTRAINT [FK_MODIFICA_DATI_GENERALE_TIPO_MODIFICA_GENERALE]
GO

ALTER TABLE [dbo].[MODIFICA_DATI_GENERALE]  WITH CHECK ADD  CONSTRAINT [FK_MODIFICA_DATI_GENERALE_UTENTI] FOREIGN KEY([ID_UTENTE_MODIFICA])
REFERENCES [dbo].[UTENTI] ([ID_UTENTE])
GO

ALTER TABLE [dbo].[MODIFICA_DATI_GENERALE] CHECK CONSTRAINT [FK_MODIFICA_DATI_GENERALE_UTENTI]
GO

ALTER TABLE [dbo].[MODIFICA_DATI_GENERALE]  WITH CHECK ADD  CONSTRAINT [FK_MODIFICA_DATI_GENERALE_VARIANTI] FOREIGN KEY([ID_VARIANTE])
REFERENCES [dbo].[VARIANTI] ([ID_VARIANTE])
GO

ALTER TABLE [dbo].[MODIFICA_DATI_GENERALE] CHECK CONSTRAINT [FK_MODIFICA_DATI_GENERALE_VARIANTI]
GO
