CREATE TABLE PAGAMENTI_RICHIESTI_FEM(
	ID_PAGAMENTO_RICHIESTO_FEM int IDENTITY(1,1) NOT NULL,
	DATA_INSERIMENTO datetime NULL,
	CF_INSERIMENTO varchar(16) NULL,
	ID_CONTRATTO int NULL,
	ID_INVESTIMENTO int NOT NULL,
	IMPORTO_RICHIESTO decimal(18, 2) NULL,
	IMPORTO_AMMESSO decimal(18, 2) NULL,
	AMMESSO bit NOT NULL,
	CF_ISTRUTTORE varchar(16) NULL,
	DATA_VALUTAZIONE datetime NULL,
	DATA_MODIFICA datetime NULL,
	CF_MODIFICA varchar(16) NULL,
	NOTE_ISTRUTTORE varchar(max) NULL,
	ID_DOMANDA_PAGAMENTO int NULL,
	ID_GIUSTIFICATIVO int NULL,
 CONSTRAINT PK_PAGAMENTI_RICHIESTI_FEM PRIMARY KEY CLUSTERED 
(
	ID_PAGAMENTO_RICHIESTO_FEM ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON PRIMARY
) ON PRIMARY TEXTIMAGE_ON PRIMARY
GO

ALTER TABLE PAGAMENTI_RICHIESTI_FEM ADD  CONSTRAINT DF_PAGAMENTI_RICHIESTI_FEM_AMMESSO  DEFAULT ((0)) FOR AMMESSO
GO

ALTER TABLE PAGAMENTI_RICHIESTI_FEM ADD  CONSTRAINT DF_PAGAMENTI_RICHIESTI_FEM_DATA_MODIFICA  DEFAULT (getdate()) FOR DATA_MODIFICA
GO

ALTER TABLE PAGAMENTI_RICHIESTI_FEM  WITH CHECK ADD FOREIGN KEY(ID_DOMANDA_PAGAMENTO)
REFERENCES DOMANDA_DI_PAGAMENTO (ID_DOMANDA_PAGAMENTO)
GO

ALTER TABLE PAGAMENTI_RICHIESTI_FEM  WITH CHECK ADD  CONSTRAINT FK_PAGAMENTI_RICHIESTI_FEM_CONTRATTI_FEM FOREIGN KEY(ID_CONTRATTO)
REFERENCES CONTRATTI_FEM (ID_CONTRATTO_FEM)
GO

ALTER TABLE PAGAMENTI_RICHIESTI_FEM CHECK CONSTRAINT FK_PAGAMENTI_RICHIESTI_FEM_CONTRATTI_FEM
GO

ALTER TABLE PAGAMENTI_RICHIESTI_FEM  WITH CHECK ADD  CONSTRAINT FK_PAGAMENTI_RICHIESTI_FEM_GIUSTIFICATIVI FOREIGN KEY(ID_GIUSTIFICATIVO)
REFERENCES GIUSTIFICATIVI (ID_GIUSTIFICATIVO)
GO

ALTER TABLE PAGAMENTI_RICHIESTI_FEM CHECK CONSTRAINT FK_PAGAMENTI_RICHIESTI_FEM_GIUSTIFICATIVI
GO

ALTER TABLE PAGAMENTI_RICHIESTI_FEM  WITH CHECK ADD  CONSTRAINT FK_PAGAMENTI_RICHIESTI_FEM_PIANO_INVESTIMENTI FOREIGN KEY(ID_INVESTIMENTO)
REFERENCES PIANO_INVESTIMENTI (ID_INVESTIMENTO)
GO

ALTER TABLE PAGAMENTI_RICHIESTI_FEM CHECK CONSTRAINT FK_PAGAMENTI_RICHIESTI_FEM_PIANO_INVESTIMENTI
GO


