-- DROP VIEW VIRREGOLARITA;
CREATE VIEW VIRREGOLARITA
AS
	SELECT
		IRR.*, 
		TIP.TIPO AS TIPO_IRREGOLARITA, 
		TIP.ATTIVO AS ATTIVO_TIPO_IRREGOLARITA, 
		PROG.ID_BANDO, 
		PROG.COD_STATO AS COD_STATO_PROGETTO, 
		PROG.STATO AS STATO_PROGETTO, 
		PROG.COD_FASE AS COD_FASE_PROGETTO, 
		PROG.FASE AS FASE_PROGETTO, 
		PROG.ID_IMPRESA AS ID_IMPRESA_PROGETTO, 
		IMP.CUAA AS CUAA_IMPRESA_IRREGOLARITA, 
		IMP.CODICE_FISCALE AS CODICE_FISCALE_IMPRESA_IRREGOLARITA, 
		IMP.RAGIONE_SOCIALE AS RAGIONE_SOCIALE_IMPRESA_IRREGOLARITA, 
		COD_CATEGORIA.DESCRIZIONE AS DESCRIZIONE_CATEGORIA, 
		COD_CONTROLLO.DESCRIZIONE AS DESCRIZIONE_CONTROLLO_ORIGINE, 
		COD_TIPO.DESCRIZIONE AS DESCRIZIONE_TIPO, 
		COD_CLASSIFICAZIONE.DESCRIZIONE AS DESCRIZIONE_CLASSIFICAZIONE, 
		COD_STATO_FINANZIARIO.DESCRIZIONE AS DESCRIZIONE_STATO_FINANZIARIO
	FROM IRREGOLARITA IRR 
		JOIN TIPO_IRREGOLARITA TIP ON IRR.ID_TIPO_IRREGOLARITA = TIP.ID_TIPO 
		JOIN vPROGETTO PROG ON IRR.ID_PROGETTO = PROG.ID_PROGETTO 
		JOIN vIMPRESA IMP ON IRR.ID_IMPRESA_COMMESSA_DA = IMP.ID_IMPRESA 
		JOIN CODIFICA_GENERICA COD_CONTROLLO ON IRR.ID_CONTROLLO_ORIGINE = COD_CONTROLLO.ID 
		JOIN CODIFICA_GENERICA COD_CATEGORIA ON IRR.ID_CATEGORIA = COD_CATEGORIA.ID 
		JOIN CODIFICA_GENERICA COD_TIPO ON IRR.ID_TIPO = COD_TIPO.ID 
		JOIN CODIFICA_GENERICA COD_CLASSIFICAZIONE ON IRR.ID_CLASSIFICAZIONE = COD_CLASSIFICAZIONE.ID 
		JOIN CODIFICA_GENERICA COD_STATO_FINANZIARIO ON IRR.ID_STATO_FINANZIARIO = COD_STATO_FINANZIARIO.ID;

GO