CREATE PROCEDURE [dbo].[ZVcruscottoBandiProcAttivazioneFindFind]
(
	@IdBandoequalthis INT, 
	@IdUtenteRupequalthis INT
)
AS
	declare @sql nvarchar(4000);
	declare @lensql int;
	set @lensql=0;
	SET @sql = 'SELECT ID_BANDO, COD_ENTE, DESCRIZIONE, PAROLE_CHIAVE, DATA_INSERIMENTO, DISPOSIZIONI_ATTUATIVE, ID_SCHEDA_VALUTAZIONE, MULTIPROGETTO, MULTIMISURA, INTERESSE_FILIERA, FASCICOLO_RICHIESTO, ID_STORICO_ULTIMO, DATA_APERTURA, ID_MODELLO_DOMANDA, ID_PROGRAMMAZIONE, ID_INTEGRAZIONE_ULTIMA, DATA_SCADENZA, IMPORTO, IMPORTO_DI_MISURA, QUOTA_RISERVA, ID_ATTO_INTEGRAZIONE, COD_STATO, DATA, OPERATORE, SEGNATURA, ID_ATTO, ORDINE_STATO, STATO, PROFILO, NOMINATIVO, COD_TIPO_ENTE, ENTE, FIRMA_RICHIESTA, ABILITA_VALUTAZIONE, AGGREGAZIONE, ID_UTENTE_RUP, CF_RUP, RUP FROM VCRUSCOTTO_BANDI_PROC_ATTIVAZIONE WHERE 1=1';
	IF (@IdBandoequalthis IS NOT NULL) BEGIN SET @sql = @sql + ' AND (ID_BANDO = @IdBandoequalthis)'; set @lensql=@lensql+len(@IdBandoequalthis);end;
	IF (@IdUtenteRupequalthis IS NOT NULL) BEGIN SET @sql = @sql + ' AND (ID_UTENTE_RUP = @IdUtenteRupequalthis)'; set @lensql=@lensql+len(@IdUtenteRupequalthis);end;
	set @sql = @sql + 'ORDER BY DATA_SCADENZA ASC';
	set @lensql=@lensql+len(@sql);
	if (@lensql<3000)
	exec sp_executesql @sql,N'@IdBandoequalthis INT, @IdUtenteRupequalthis INT',@IdBandoequalthis , @IdUtenteRupequalthis ;
	else
		SELECT ID_BANDO, COD_ENTE, DESCRIZIONE, PAROLE_CHIAVE, DATA_INSERIMENTO, DISPOSIZIONI_ATTUATIVE, ID_SCHEDA_VALUTAZIONE, MULTIPROGETTO, MULTIMISURA, INTERESSE_FILIERA, FASCICOLO_RICHIESTO, ID_STORICO_ULTIMO, DATA_APERTURA, ID_MODELLO_DOMANDA, ID_PROGRAMMAZIONE, ID_INTEGRAZIONE_ULTIMA, DATA_SCADENZA, IMPORTO, IMPORTO_DI_MISURA, QUOTA_RISERVA, ID_ATTO_INTEGRAZIONE, COD_STATO, DATA, OPERATORE, SEGNATURA, ID_ATTO, ORDINE_STATO, STATO, PROFILO, NOMINATIVO, COD_TIPO_ENTE, ENTE, FIRMA_RICHIESTA, ABILITA_VALUTAZIONE, AGGREGAZIONE, ID_UTENTE_RUP, CF_RUP, RUP
		FROM VCRUSCOTTO_BANDI_PROC_ATTIVAZIONE
		WHERE 
			((@IdBandoequalthis IS NULL) OR ID_BANDO = @IdBandoequalthis) AND 
			((@IdUtenteRupequalthis IS NULL) OR ID_UTENTE_RUP = @IdUtenteRupequalthis)
		ORDER BY DATA_SCADENZA ASC

GO