CREATE VIEW VTESTATA_VALIDAZIONE
AS
SELECT  VAL.ID_TESTATA,
	--VAL.ID_ISTANZA_CHECKLIST_GENERICA,
	DOM.ID_DOMANDA_PAGAMENTO, 
    TD.DESCRIZIONE AS TIPO_DOMANDA_PAGAMENTO, 
    TD.COD_FASE, 
    DOM.DATA_MODIFICA AS DATA_PRESENTAZIONE_DOMANDA_PAGAMENTO, 
    DOM.APPROVATA AS DOMANDA_APPROVATA, 
	DOM.SEGNATURA_APPROVAZIONE AS SEGNATURA_APPROVAZIONE_DOMANDA,
    DOM.ID_PROGETTO, 
    VAL.ID_LOTTO, 
	VAL.CF_INSERIMENTO, 
    VAL.DATA_INSERIMENTO,
	VAL.CF_MODIFICA,  
    VAL.DATA_MODIFICA, 
	VAL.CF_VALIDATORE,
	UT.NOMINATIVO AS NOMINATIVO_VALIDATORE,
    VAL.SELEZIONATA_X_REVISIONE, 
    VAL.APPROVATA, 
    VAL.NUMERO_ESTRAZIONE, 
    VAL.ORDINE, 
    VAL.SEGNATURA_REVISIONE, 
    VAL.SEGNATURA_SECONDA_REVISIONE, 
    VAL.DATA_VALIDAZIONE,
	VAL.AUTOVALUTAZIONE,
    DOM.COD_TIPO, 
    DOM.DATA_APPROVAZIONE, 
    PROG.ID_BANDO, 
    PROG.PROVINCIA_DI_PRESENTAZIONE
FROM DOMANDA_DI_PAGAMENTO DOM
     JOIN TIPO_DOMANDA_PAGAMENTO TD ON DOM.COD_TIPO = TD.COD_TIPO 
     JOIN PROGETTO PROG ON DOM.ID_PROGETTO = PROG.ID_PROGETTO 
     LEFT JOIN TESTATA_VALIDAZIONE VAL ON DOM.ID_DOMANDA_PAGAMENTO = VAL.ID_DOMANDA_PAGAMENTO
	 LEFT JOIN VUTENTI UT ON VAL.CF_VALIDATORE = UT.CF_UTENTE
--WHERE DOM.SEGNATURA_APPROVAZIONE IS NOT NULL