CREATE  PROCEDURE [dbo].[calcoloStepVariante133_1]
@ID_VARIANTE int
AS
BEGIN
--
--DECLARE @ID_VARIANTE int 
--SET @ID_VARIANTE = 5

-- modifiche all'interno della stessa Codifica investimento 

DECLARE   @IdProgetto INT, @ID_CODIFICA_NOW INT , @ID_CODIFICA_PREC INT,
					  @COSTO_NOW DECIMAL (18,2), @COSTO_PREC DECIMAL (18,2), @ID_VARIANTE_PREC INT, @RESULT INT

SET @RESULT = 1 --- PONGO VERIFICATO

SET @IdProgetto = (SELECT ID_PROGETTO FROM VARIANTI WHERE ID_VARIANTE = @ID_VARIANTE )

SET @ID_VARIANTE_PREC = (  SELECT MAX ( ID_VARIANTE )  FROM VARIANTI WHERE ID_PROGETTO = @IdProgetto  AND APPROVATA = 1
															 AND  DATA_APPROVAZIONE < ( SELECT DATA_MODIFICA FROM VARIANTI WHERE ID_VARIANTE = @ID_VARIANTE   )   )

DECLARE SPESE_CODIFICA CURSOR FOR
	(
		 SELECT   PI.ID_CODIFICA_INVESTIMENTO , SUM( pi.COSTO_INVESTIMENTO) AS  COSTO_INVESTIMENTO 
		FROM  PIANO_INVESTIMENTI  PI   WHERE (( @ID_VARIANTE_PREC IS NOT NULL  AND   PI.ID_VARIANTE = @ID_VARIANTE_PREC AND isnull(COD_VARIAZIONE,'x')!='A') 
		OR (  @ID_VARIANTE_PREC IS  NULL AND  PI.ID_INVESTIMENTO_ORIGINALE IS NOT NULL  AND ID_VARIANTE IS NULL AND ID_PROGETTO IN (SELECT ID_PROGETTO FROM PROGETTO WHERE ID_PROG_INTEGRATO = 788) )  )
		GROUP BY  PI.ID_CODIFICA_INVESTIMENTO 
	)
 
OPEN  SPESE_CODIFICA
FETCH NEXT FROM SPESE_CODIFICA 
INTO    @ID_CODIFICA_PREC, @COSTO_PREC
WHILE @@FETCH_STATUS = 0
BEGIN
  SET @COSTO_NOW =( SELECT  SUM( pi.COSTO_INVESTIMENTO) AS  COSTO_INVESTIMENTO 
					FROM  PIANO_INVESTIMENTI  PI   WHERE  ID_VARIANTE = @ID_VARIANTE AND isnull(COD_VARIAZIONE,'x')!='A' AND ID_CODIFICA_INVESTIMENTO = @ID_CODIFICA_PREC
					GROUP BY  PI.ID_CODIFICA_INVESTIMENTO)
	 IF (  @COSTO_NOW > @COSTO_PREC )
			BEGIN
			 SET @RESULT =0
			 BREAK
			END
	FETCH NEXT FROM SPESE_CODIFICA
INTO @ID_CODIFICA_PREC,@COSTO_PREC 
END
 

 CLOSE SPESE_CODIFICA
DEALLOCATE SPESE_CODIFICA 

 SELECT  @RESULT AS RESULT
 

END
