




CREATE PROCEDURE [dbo].[calcoloIndicatoriInvestPrivati] 
(
	@ID_PROGETTO int, 
	@FASE_ISTRUTTORIA BIT =0, --SE FASE ISTRUTTORIA TRUE, ALTRIMENTI DEVO CALCOLARE PER GLI INVESTIMENTI ORIGINALI
	@ID_VARIANTE INT =NULL
)
AS

SELECT dbo.calcoloCostoTotaleProgetto(@ID_PROGETTO,@FASE_ISTRUTTORIA,@ID_VARIANTE)
	- dbo.calcoloContributoTotaleProgetto(@ID_PROGETTO,@FASE_ISTRUTTORIA,@ID_VARIANTE) AS ValoreRTot


