CREATE PROCEDURE [dbo].[calcoloStep221_1]
(
@IdProgetto int,
@FASE_ISTRUTTORIA bit =0
)
AS
BEGIN
	
-- Premio manutenzione <= massimale annuo da bando
-- TIPOLOGIA A) (C1)  anni 1°,2° € 640  anni 3°,4°,5° € 490
-- TIPOLOGIA B) (C2)  anni 1°,2° € 700  anni 3°,4°,5° € 550
-- TIPOLOGIA C) (C3)  anni 1°,2° € 640  anni 3°,4°,5° € 490
-- PRIORITA' 604 --> ANNO di manutenzione dell`impianto
-- PRIORITA' 605 --> ETTARI
-- ID_CODIFICA_INVESTIMENTO = C 1172  MANUTENZIONE
-- ID_DETTAGLIO_INVESTIMENTO C1 4499,C2 4500,C3 4501  MANUTENZIONE  ( id bando 233 -  4939, 4940, 4941)


--BANDO ID 251 ANNUALITA 2010
--Tipologia a) 540 390
--Tipologia b) 450 350
--Tipologia c) 550 400


DECLARE @loopANNO int,
		@RESULT int,@RESULTA int,@RESULTB int,@RESULTC int,
		@MAX_A_1 INT, @MAX_A_3 INT,@MAX_B_1 INT,@MAX_B_3 INT, @MAX_C_1 INT,@MAX_C_3 INT,
		@ID_BANDO INT 
		
SET @RESULT = 1 -- PONGO LO STEP IN STATO VERIFICATO
SELECT @ID_BANDO = ID_BANDO FROM PROGETTO WHERE ID_PROGETTO =@IdProgetto
if(@ID_BANDO=251)
BEGIN 
	SET @MAX_A_1=540 SET @MAX_A_3 = 390
	SET @MAX_B_1=450 SET @MAX_B_3 = 350
	SET @MAX_C_1=550 SET @MAX_C_3 = 400
	
END
ELSE
BEGIN 
	SET @MAX_A_1=640 SET @MAX_A_3 = 490
	SET @MAX_B_1=700 SET @MAX_B_3 = 550
	SET @MAX_C_1=640 SET @MAX_C_3 = 490
	
END

--- TIPOLOGIA A)
DECLARE @A INT -- SE NULLO ALLORA VA BENE!!!!

SELECT  @A = COUNT(*)
 FROM (
     SELECT SUM(ISNULL(COSTO_INVESTIMENTO,0)) AS COSTO,  
            SUM(ISNULL(COSTO_INVESTIMENTO,0))/isnull(nullif((PXI_HA.VALORE/10000),0),1) AS COSTO_X_HA , --QUI FAI LA SPESA PER ETTARO PER INVESTIMENTO
			VP.DESCRIZIONE AS ANNO , VP.CODICE, PXI_HA.VALORE AS SUPERFICIE, 
            CASE WHEN VP.CODICE IN (1,2) THEN @MAX_A_1  ELSE @MAX_A_3 END MASSIMO
    FROM PIANO_INVESTIMENTI INV 
         inner join PRIORITA_X_INVESTIMENTI PXI ON INV.ID_INVESTIMENTO = PXI.ID_INVESTIMENTO AND PXI.ID_PRIORITA = 604
        INNER JOIN VALORI_PRIORITA VP on PXI.ID_VALORE = VP.ID_VALORE 
       INNER JOIN  PRIORITA_X_INVESTIMENTI PXI_HA ON INV.ID_INVESTIMENTO = PXI_HA.ID_INVESTIMENTO AND PXI_HA.ID_PRIORITA = 605
    WHERE INV.ID_PROGETTO = @IdProgetto  AND INV.ID_DETTAGLIO_INVESTIMENTO in 
-- inizio modifica per riaperture future   
(SELECT ID_DETTAGLIO_INVESTIMENTO FROM CODIFICA_INVESTIMENTO CI INNER JOIN DETTAGLIO_INVESTIMENTI DI ON 
(CI.ID_CODIFICA_INVESTIMENTO = DI.ID_CODIFICA_INVESTIMENTO) WHERE CI.ID_BANDO = @ID_BANDO AND DI.COD_DETTAGLIO = 'c1')
-- fine modifica per riaperture future       
AND ((INV.ID_INVESTIMENTO_ORIGINALE IS NULL AND @FASE_ISTRUTTORIA=0 AND ID_VARIANTE IS NULL)OR(INV.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND @FASE_ISTRUTTORIA =1 AND ID_VARIANTE IS NULL))
    GROUP BY VP.DESCRIZIONE , PXI_HA.VALORE,VP.CODICE, INV.ID_INVESTIMENTO)AS T
GROUP BY ANNO, CODICE, MASSIMO
HAVING SUM(COSTO_X_HA)> MASSIMO and COUNT(*) >0 -- IL COSTO X ETTARO DEVE STARE SOTTO AL MASSIMO
 
 IF( @A IS NOT NULL OR @A> 0) SET @RESULTA =0 --NON VA BENE
 ELSE SET @RESULTA =1
 
 
--- TIPOLOGIA B)
DECLARE @B INT -- SE NULLO ALLORA VA BENE!!!!

 SELECT  @B =COUNT(*)
 FROM (
     SELECT SUM(ISNULL(COSTO_INVESTIMENTO,0)) AS COSTO,  
            SUM(ISNULL(COSTO_INVESTIMENTO,0))/isnull(nullif((PXI_HA.VALORE/10000),0),1) AS COSTO_X_HA , --QUI FAI LA SPESA PER ETTARO PER INVESTIMENTO
     VP.DESCRIZIONE AS ANNO , VP.CODICE, PXI_HA.VALORE AS SUPERFICIE, 
            CASE 
                WHEN VP.CODICE IN (1,2) THEN @MAX_B_1 
                ELSE @MAX_B_3  
            END MASSIMO
    FROM PIANO_INVESTIMENTI INV INNER JOIN 
        PRIORITA_X_INVESTIMENTI PXI ON INV.ID_INVESTIMENTO = PXI.ID_INVESTIMENTO AND PXI.ID_PRIORITA = 604 inner join
        VALORI_PRIORITA VP on PXI.ID_VALORE = VP.ID_VALORE INNER JOIN 
        PRIORITA_X_INVESTIMENTI PXI_HA ON INV.ID_INVESTIMENTO = PXI_HA.ID_INVESTIMENTO AND PXI_HA.ID_PRIORITA = 605
    WHERE INV.ID_PROGETTO = @IdProgetto  AND INV.ID_DETTAGLIO_INVESTIMENTO in 
 -- inizio modifica per riaperture future     
    (SELECT ID_DETTAGLIO_INVESTIMENTO FROM CODIFICA_INVESTIMENTO CI INNER JOIN DETTAGLIO_INVESTIMENTI DI ON 
(CI.ID_CODIFICA_INVESTIMENTO = DI.ID_CODIFICA_INVESTIMENTO) WHERE CI.ID_BANDO = @ID_BANDO AND DI.COD_DETTAGLIO = 'c2')
 -- fine modifica per riaperture future     
    AND
    ((INV.ID_INVESTIMENTO_ORIGINALE IS NULL AND @FASE_ISTRUTTORIA=0 AND ID_VARIANTE IS NULL)OR(INV.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND @FASE_ISTRUTTORIA =1 AND ID_VARIANTE IS NULL))
    GROUP BY VP.DESCRIZIONE , PXI_HA.VALORE,VP.CODICE, INV.ID_INVESTIMENTO)AS T
GROUP BY ANNO, CODICE, MASSIMO
HAVING SUM(COSTO_X_HA)> MASSIMO and COUNT(*) >0 -- IL COSTO X ETTARO DEVE STARE SOTTO AL MASSIMO
 
 IF( @B IS NOT NULL OR @B> 0) SET @RESULTB =0
ELSE SET @RESULTB =1

--- TIPOLOGIA C) -- FATTA DA SILVIA -- BASE DA CUI PARTIRE
DECLARE @C INT -- SE NULLO ALLORA VA BENE!!!!

 SELECT  @C = COUNT(*)
 FROM (
     SELECT SUM(ISNULL(COSTO_INVESTIMENTO,0)) AS COSTO,  
            SUM(ISNULL(COSTO_INVESTIMENTO,0))/isnull(nullif((PXI_HA.VALORE/10000),0),1) AS COSTO_X_HA , --QUI FAI LA SPESA PER ETTARO PER INVESTIMENTO
     VP.DESCRIZIONE AS ANNO , VP.CODICE, PXI_HA.VALORE AS SUPERFICIE, 
            CASE 
                WHEN VP.CODICE IN (1,2) THEN @MAX_C_1 
                ELSE @MAX_C_3  
            END MASSIMO
    FROM PIANO_INVESTIMENTI INV INNER JOIN 
        PRIORITA_X_INVESTIMENTI PXI ON INV.ID_INVESTIMENTO = PXI.ID_INVESTIMENTO AND PXI.ID_PRIORITA = 604 inner join
        VALORI_PRIORITA VP on PXI.ID_VALORE = VP.ID_VALORE INNER JOIN 
        PRIORITA_X_INVESTIMENTI PXI_HA ON INV.ID_INVESTIMENTO = PXI_HA.ID_INVESTIMENTO AND PXI_HA.ID_PRIORITA = 605
    WHERE INV.ID_PROGETTO = @IdProgetto  AND INV.ID_DETTAGLIO_INVESTIMENTO in    
     -- inizio modifica per riaperture future     
    (SELECT ID_DETTAGLIO_INVESTIMENTO FROM CODIFICA_INVESTIMENTO CI INNER JOIN DETTAGLIO_INVESTIMENTI DI ON 
	(CI.ID_CODIFICA_INVESTIMENTO = DI.ID_CODIFICA_INVESTIMENTO) WHERE CI.ID_BANDO =@ID_BANDO AND DI.COD_DETTAGLIO = 'c3')
 -- fine modifica per riaperture future    
AND ((INV.ID_INVESTIMENTO_ORIGINALE IS NULL AND @FASE_ISTRUTTORIA=0 AND ID_VARIANTE IS NULL)OR(INV.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND @FASE_ISTRUTTORIA =1 AND ID_VARIANTE IS NULL))
 GROUP BY VP.DESCRIZIONE , PXI_HA.VALORE,VP.CODICE, INV.ID_INVESTIMENTO)AS T
GROUP BY ANNO, CODICE, MASSIMO
HAVING SUM(COSTO_X_HA)> MASSIMO and COUNT(*) >0 -- IL COSTO X ETTARO DEVE STARE SOTTO AL MASSIMO
 
IF( @C IS NOT NULL OR @C> 0) SET @RESULTC =0
ELSE SET @RESULTC =1
IF(@RESULTA =0 OR @RESULTB =0 OR @RESULTC =0)SET @RESULT =0

SELECT @RESULT
END
