CREATE PROCEDURE [dbo].[calcoloStep911_9]
(
	@IdProgetto int,
	@FASE_ISTRUTTORIA int 
)
AS
BEGIN
/*
univocità del progetto/tipologia vigneto
1223	Denominazioni di Origine Protetta dei vini (DOP) della regione Marche
1234	Indicazione Geografica Protetta dei vini (IGP) della regione Marche
*/
	DECLARE @Risultato INT =1 , @C INT, @NUM_PROG INT, @ID_BANDO INT,@ID_IMPRESA INT
	
	SELECT  @ID_BANDO =  ID_BANDO, @ID_IMPRESA = ID_IMPRESA   FROM PROGETTO WHERE ID_PROGETTO=@IdProgetto 	
	
	SELECT @C= SUM(DISTINCT PXI.ID_PRIORITA) 
	FROM PRIORITA_X_INVESTIMENTI PXI 
		INNER JOIN PIANO_INVESTIMENTI AS pi1 ON pi1.ID_INVESTIMENTO = PXI.ID_INVESTIMENTO	
	WHERE PXI.ID_PRIORITA IN (1223,1234) AND ID_PROGETTO=@IdProgetto
		AND  ((@FASE_ISTRUTTORIA=0 AND pi1.ID_INVESTIMENTO_ORIGINALE IS NULL)OR(@FASE_ISTRUTTORIA=1 AND pi1.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL))
	
	IF(@C>1234) SET @Risultato =0
	ELSE BEGIN
		   	SELECT @NUM_PROG= COUNT(DISTINCT pi1.ID_PROGETTO )  
	     	FROM PRIORITA_X_INVESTIMENTI PXI 
				INNER JOIN PIANO_INVESTIMENTI AS pi1 ON pi1.ID_INVESTIMENTO = PXI.ID_INVESTIMENTO	
				INNER JOIN vPROGETTO AS p ON p.ID_PROGETTO = pi1.ID_PROGETTO
	     	WHERE pi1.ID_PROGETTO!=@IdProgetto AND P.ID_BANDO =@ID_BANDO AND P.ID_IMPRESA  =  @ID_IMPRESA AND PXI.ID_PRIORITA = @C
	     	 	AND (@FASE_ISTRUTTORIA=1 AND pi1.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL)	  
	     	 	
	     	 IF @NUM_PROG >0 SET @Risultato = 0	     	   	
	END
	
	SELECT @Risultato 
END
