CREATE PROCEDURE [dbo].[calcoloStepVariante413_B273]
@ID_VARIANTE int
AS
BEGIN
-- BANDO misura 413 PSR
-- Controllo validO per MANTENIMENTO PUNTEGGIO MINIMO PER LA GRADUATORIA: 
-- i punteggi in graduatoria sono relativi a 100 --> non divido per 100 

--822	Investimenti relizzati nelle aree D e C3 del territorio del GAL	SELECT COUNT(*) FROM PRIORITA_X_PROGETTO WHERE ID_PROGETTO = @IdProgetto AND ID_PRIORITA = 822
--823	Investimenti realizzati nelle aree Natura 2000 ed altre aree protette	SELECT COUNT(*) FROM PRIORITA_X_PROGETTO WHERE ID_PROGETTO = @IdProgetto AND ID_PRIORITA = 823
--824	Investimenti realizzati da imprenditrici	SELECT COUNT(ID_PRIORITA) AS VALORE   FROM PRIORITA_X_PROGETTO  WHERE ID_PRIORITA = 824 AND ID_PROGETTO = @IdProgetto
--825	Investimenti destinati a creare occupazione	SELECT PUNTEGGIO = CASE  WHEN VP.CODICE = '1' THEN 1    WHEN VP.CODICE = '2' THEN 0.5  ELSE 0  END   FROM PRIORITA_X_PROGETTO PP INNER JOIN VALORI_PRIORITA VP ON (PP.ID_VALORE = VP.ID_VALORE) WHERE  PP.ID_PROGETTO = @IdProgetto AND  PP.ID_PRIORITA = 825
--826	Rappresentatività del soggetto proponente sia in termini di territorio che di popolazione o di operatori residenti in area GAL	SELECT PUNTEGGIO = CASE  WHEN VP.CODICE = '1' THEN 1    WHEN VP.CODICE = '2' THEN 0.75  WHEN VP.CODICE = '3' THEN 0.5  WHEN VP.CODICE = '4' THEN 0.25  ELSE 0  END   FROM PRIORITA_X_PROGETTO PP INNER JOIN VALORI_PRIORITA VP ON (PP.ID_VALORE = VP.ID_VALORE) WHERE  PP.ID_PROGETTO = @IdProgetto AND  PP.ID_PRIORITA = 826
--827	Uso di tecniche di ingegneria naturalistica, tecniche di bioarchitettura e interventi finalizzate al risparmio energetico	SELECT PUNTEGGIO = CASE  WHEN VP.CODICE = '1' THEN 1    WHEN VP.CODICE = '2' THEN 0.75  WHEN VP.CODICE = '3' THEN 0.5  ELSE 0  END   FROM PRIORITA_X_PROGETTO PP INNER JOIN VALORI_PRIORITA VP ON (PP.ID_VALORE = VP.ID_VALORE) WHERE  PP.ID_PROGETTO = @IdProgetto AND  PP.ID_PRIORITA = 827

--declare @ID_VARIANTE int
--SET @ID_VARIANTE = 
DECLARE @IdSchedaValutazione int, @IdProgetto int, @ID_BANDO INT
DECLARE @MINIMO_GRADUATORIA DECIMAL(18,4)

SET @IdProgetto= (SELECT ID_PROGETTO FROM VARIANTI WHERE ID_VARIANTE = @ID_VARIANTE)
SET @ID_BANDO = (SELECT ID_BANDO FROM PROGETTO WHERE ID_PROGETTO = @IdProgetto)

SET @MINIMO_GRADUATORIA = (SELECT TOP(1) PUNTEGGIO FROM  GRADUATORIA_PROGETTI WHERE ID_BANDO = @ID_BANDO AND FINANZIABILITA ='N' ORDER BY PUNTEGGIO DESC)
--SELECT @MINIMO_GRADUATORIA AS M
SET @IdSchedaValutazione = (SELECT ID_SCHEDA_VALUTAZIONE FROM BANDO B INNER JOIN PROGETTO P ON (B.ID_BANDO = P.ID_BANDO) WHERE P.ID_PROGETTO = @IdProgetto)

-- priorita A  	
-- Investimenti relizzati nelle aree D e C3 del territorio del GAL -- SELECT COUNT(*) FROM PRIORITA_X_PROGETTO WHERE ID_PROGETTO = @IdProgetto AND ID_PRIORITA = 822
DECLARE @PunteggioPrioritaA decimal(10,2)
DECLARE @PesoPrioritaA decimal(10,2)
DECLARE @ValoreMAXPrioritaA decimal(10,2)
DECLARE @ValorePrioritaA decimal(10,2)

SET @PesoPrioritaA= (SELECT ISNULL(PESO,0) FROM vSCHEDA_X_PRIORITA WHERE ID_PRIORITA = 822 AND ID_SCHEDA_VALUTAZIONE = @IdSchedaValutazione)
SET @ValoreMAXPrioritaA = (SELECT ISNULL(VALORE_MAX,100) FROM vSCHEDA_X_PRIORITA WHERE ID_PRIORITA = 822 AND ID_SCHEDA_VALUTAZIONE = @IdSchedaValutazione)
SET @ValorePrioritaA =  (SELECT COUNT(*) FROM PRIORITA_X_PROGETTO WHERE ID_PROGETTO = @IdProgetto AND ID_PRIORITA = 822)
SET @PunteggioPrioritaA = ((@ValorePrioritaA ) * @PesoPrioritaA)
   
-- Priorità B
-- Investimenti realizzati nelle aree Natura 2000 ed altre aree protette --	SELECT COUNT(*) FROM PRIORITA_X_PROGETTO WHERE ID_PROGETTO = @IdProgetto AND ID_PRIORITA = 823

DECLARE @PesoPrioritaB decimal(10,2)
DECLARE @ValoreMAXPrioritaB decimal(10,2)
DECLARE @ValorePrioritaB decimal(10,2)
DECLARE @PunteggioPrioritaB decimal(10,2)

SET @PesoPrioritaB = (SELECT ISNULL(PESO,0) FROM vSCHEDA_X_PRIORITA WHERE ID_PRIORITA = 823 AND ID_SCHEDA_VALUTAZIONE = @IdSchedaValutazione)
SET @ValoreMAXPrioritaB = (SELECT ISNULL(VALORE_MAX,100) FROM vSCHEDA_X_PRIORITA WHERE ID_PRIORITA = 823 AND ID_SCHEDA_VALUTAZIONE = @IdSchedaValutazione)
SET @ValorePrioritaB = (SELECT COUNT(*) FROM PRIORITA_X_PROGETTO WHERE ID_PROGETTO = @IdProgetto AND ID_PRIORITA = 823)
SET @PunteggioPrioritaB = ((@ValorePrioritaB ) * @PesoPrioritaB) 

-- Priorità C
-- Investimenti realizzati da imprenditrici	-- SELECT COUNT(ID_PRIORITA) AS VALORE FROM PRIORITA_X_PROGETTO  WHERE ID_PRIORITA = 824 AND ID_PROGETTO = @IdProgetto
DECLARE @PesoPrioritaC decimal(10,2)
DECLARE @ValoreMAXPrioritaC decimal(10,2)
DECLARE @ValorePrioritaC decimal(10,2)
DECLARE @PunteggioPrioritaC decimal(10,2)

SET @PesoPrioritaC = (SELECT ISNULL(PESO,0) FROM vSCHEDA_X_PRIORITA WHERE ID_PRIORITA = 824 AND ID_SCHEDA_VALUTAZIONE = @IdSchedaValutazione)
SET @ValoreMAXPrioritaC = (SELECT ISNULL(VALORE_MAX,100) FROM vSCHEDA_X_PRIORITA WHERE ID_PRIORITA = 824 AND ID_SCHEDA_VALUTAZIONE = @IdSchedaValutazione)
SET @ValorePrioritaC = (SELECT COUNT(ID_PRIORITA) AS VALORE FROM PRIORITA_X_PROGETTO  WHERE ID_PRIORITA = 824 AND ID_PROGETTO = @IdProgetto)
SET @PunteggioPrioritaC = ((@ValorePrioritaC ) * @PesoPrioritaC) 

-- Priorità D
-- Investimenti destinati a creare occupazione -- SELECT PUNTEGGIO = CASE  WHEN VP.CODICE = '1' THEN 1    WHEN VP.CODICE = '2' THEN 0.5  ELSE 0  END   FROM PRIORITA_X_PROGETTO PP INNER JOIN VALORI_PRIORITA VP ON (PP.ID_VALORE = VP.ID_VALORE) WHERE  PP.ID_PROGETTO = @IdProgetto AND  PP.ID_PRIORITA = 825
DECLARE @PesoPrioritaD decimal(10,2)
DECLARE @ValoreMAXPrioritaD decimal(10,2)
DECLARE @ValorePrioritaD decimal(10,2)
DECLARE @PunteggioPrioritaD decimal(10,2)

SET @PesoPrioritaD = (SELECT ISNULL(PESO,0) FROM vSCHEDA_X_PRIORITA WHERE ID_PRIORITA = 825 AND ID_SCHEDA_VALUTAZIONE = @IdSchedaValutazione)
SET @ValoreMAXPrioritaD = (SELECT ISNULL(VALORE_MAX,100) FROM vSCHEDA_X_PRIORITA WHERE ID_PRIORITA = 825 AND ID_SCHEDA_VALUTAZIONE = @IdSchedaValutazione)
SET @ValorePrioritaD = (SELECT PUNTEGGIO = CASE  WHEN VP.CODICE = '1' THEN 1 WHEN VP.CODICE = '2' THEN 0.5 ELSE 0 END FROM PRIORITA_X_PROGETTO PP INNER JOIN VALORI_PRIORITA VP ON (PP.ID_VALORE = VP.ID_VALORE) WHERE  PP.ID_PROGETTO = @IdProgetto AND  PP.ID_PRIORITA = 825)
SET @PunteggioPrioritaD = (@ValorePrioritaD * @PesoPrioritaD)  


-- Priorità E
-- Rappresentatività del soggetto proponente sia in termini di territorio che di popolazione o di operatori residenti in area GAL -- SELECT PUNTEGGIO = CASE  WHEN VP.CODICE = '1' THEN 1    WHEN VP.CODICE = '2' THEN 0.75  WHEN VP.CODICE = '3' THEN 0.5  WHEN VP.CODICE = '4' THEN 0.25  ELSE 0  END   FROM PRIORITA_X_PROGETTO PP INNER JOIN VALORI_PRIORITA VP ON (PP.ID_VALORE = VP.ID_VALORE) WHERE  PP.ID_PROGETTO = @IdProgetto AND  PP.ID_PRIORITA = 826
DECLARE @PunteggioPrioritaE decimal(10,2)
DECLARE @PesoPrioritaE decimal(10,2)
DECLARE @ValoreMAXPrioritaE decimal(10,2)
DECLARE @ValorePrioritaE decimal(10,2)

SET @PesoPrioritaE = (SELECT ISNULL(PESO,0) FROM vSCHEDA_X_PRIORITA WHERE ID_PRIORITA = 826 AND ID_SCHEDA_VALUTAZIONE = @IdSchedaValutazione)
SET @ValoreMAXPrioritaE = (SELECT ISNULL(VALORE_MAX,100) FROM vSCHEDA_X_PRIORITA WHERE ID_PRIORITA = 826 AND ID_SCHEDA_VALUTAZIONE = @IdSchedaValutazione)
SET @ValorePrioritaE = (SELECT PUNTEGGIO = CASE  WHEN VP.CODICE = '1' THEN 1    WHEN VP.CODICE = '2' THEN 0.75  WHEN VP.CODICE = '3' THEN 0.5  WHEN VP.CODICE = '4' THEN 0.25  ELSE 0  END   FROM PRIORITA_X_PROGETTO PP INNER JOIN VALORI_PRIORITA VP ON (PP.ID_VALORE = VP.ID_VALORE) WHERE  PP.ID_PROGETTO = @IdProgetto AND  PP.ID_PRIORITA = 826)
SET @PunteggioPrioritaE =  (@ValorePrioritaE * @PesoPrioritaE)  

-- Priorità F
-- Uso di tecniche di ingegneria naturalistica, tecniche di bioarchitettura e interventi finalizzate al risparmio energetico	SELECT PUNTEGGIO = CASE  WHEN VP.CODICE = '1' THEN 1    WHEN VP.CODICE = '2' THEN 0.75  WHEN VP.CODICE = '3' THEN 0.5  ELSE 0  END   FROM PRIORITA_X_PROGETTO PP INNER JOIN VALORI_PRIORITA VP ON (PP.ID_VALORE = VP.ID_VALORE) WHERE  PP.ID_PROGETTO = @IdProgetto AND  PP.ID_PRIORITA = 827
DECLARE @PunteggioPrioritaF decimal(10,2)
DECLARE @PesoPrioritaF decimal(10,2)
DECLARE @ValoreMAXPrioritaF decimal(10,2)
DECLARE @ValorePrioritaF decimal(10,2)
 
SET @PesoPrioritaF = (SELECT ISNULL(PESO,0) FROM vSCHEDA_X_PRIORITA WHERE ID_PRIORITA = 827 AND ID_SCHEDA_VALUTAZIONE = @IdSchedaValutazione)
SET @ValoreMAXPrioritaF = (SELECT ISNULL(VALORE_MAX,100) FROM vSCHEDA_X_PRIORITA WHERE ID_PRIORITA = 827 AND ID_SCHEDA_VALUTAZIONE = @IdSchedaValutazione)
SET @ValorePrioritaF = (SELECT PUNTEGGIO = CASE  WHEN VP.CODICE = '1' THEN 1    WHEN VP.CODICE = '2' THEN 0.75  WHEN VP.CODICE = '3' THEN 0.5  ELSE 0  END   FROM PRIORITA_X_PROGETTO PP INNER JOIN VALORI_PRIORITA VP ON (PP.ID_VALORE = VP.ID_VALORE) WHERE  PP.ID_PROGETTO = @IdProgetto AND  PP.ID_PRIORITA = 827)
SET @PunteggioPrioritaF =  (@ValorePrioritaF* @PesoPrioritaF)  

DECLARE @PUNTEGGIO_VARIANTE DECIMAL(18,4)

SET @PUNTEGGIO_VARIANTE = (SELECT(ISNULL(@PunteggioPrioritaA,0) +ISNULL(@PunteggioPrioritaB,0) +ISNULL(@PunteggioPrioritaC,0) +
									ISNULL(@PunteggioPrioritaD,0) +ISNULL(@PunteggioPrioritaE,0) + ISNULL(@PunteggioPrioritaF,0)))
 
if(@MINIMO_GRADUATORIA is not null)	 begin
	IF(@PUNTEGGIO_VARIANTE > ISNULL(@MINIMO_GRADUATORIA,0))SELECT 1 AS RESULT
	ELSE SELECT 0 AS RESULT
	end
else select 1
END
