CREATE  PROCEDURE [dbo].[calcoloStepMF_1]
@IdProgetto int,
@FASE_ISTRUTTORIA INT =0 
AS
BEGIN

 DECLARE @COD_FIL VARCHAR(10), @RESULT INT, @ID_BANDO INT
 --DECLARE @IdProgetto INT =8030 
SET  @RESULT =0   -- NON APPROVATO

--PROGETTO CUAA VALIDATO DAL PROMOTORE
 SET @COD_FIL = (SELECT VP.CODICE FROM PRIORITA_X_PROGETTO PP INNER JOIN VALORI_PRIORITA VP ON PP.ID_VALORE=VP.ID_VALORE 
				 WHERE PP.ID_PRIORITA in ( 374,406,798,1191)AND ID_PROGETTO = @IdProgetto)
 SET @RESULT = (SELECT COUNT(*) FROM PARTECIPANTI_X_FILIERA PF WHERE PF.ID_PROGETTO_VALIDATO = @IdProgetto AND COD_FILIERA = @COD_FIL AND  AMMESSO = 1) 
 SELECT @ID_BANDO=ID_BANDO FROM PROGETTO WHERE ID_PROGETTO =@IdProgetto 
 
 IF(@RESULT=0 AND @ID_BANDO IN (225,226,267)) BEGIN -- MODIFICA DEL 19/04/2012 PER I NUOVI BANDI DELLA 133
	DECLARE @ID_IMPRESA_PROMOTORE INT, @ID_IMPRESA_PROGETTO INT
 	
 	SELECT @ID_IMPRESA_PROMOTORE = P.ID_IMPRESA 
	FROM PROGETTO P INNER JOIN 
		PRIORITA_X_PROGETTO PP ON P.ID_PROGETTO=PP.ID_PROGETTO AND PP.ID_PRIORITA IN(374,406) 
		INNER JOIN VALORI_PRIORITA VP ON PP.ID_PRIORITA = VP.ID_PRIORITA 
	WHERE VP.CODICE =@COD_FIL AND ID_BANDO IN (144,164,198)
    SELECT @ID_IMPRESA_PROGETTO = ID_IMPRESA  FROM PROGETTO  WHERE ID_PROGETTO = @IdProgetto
	IF(@ID_IMPRESA_PROGETTO=@ID_IMPRESA_PROMOTORE )SET @RESULT =1
 END
SELECT  @RESULT AS RESULT
END
