create PROCEDURE [dbo].[calcoloStepVariante911_4]
(
	 @ID_VARIANTE int
)
AS
BEGIN
/*
SUP A NON UTILIZZATA < DI QUELLA DA RICHIESTA

*/
	DECLARE @ID_FASCICOLO int, @SUP_PORT_NON_USATA DECIMAL(18,4), @SUP_PORT_USATA DECIMAL(18,2),@Risultato INT =0,@GIOVANE INT,
			@TOT_SUP DECIMAL(18,2), @TotSupVitata decimal (10,2), @MQ_CONVERSIONE DECIMAL(18,2), @MQ_IMPIANTO DECIMAL(18,2),
	        @IdProgetto INT
			
	  SET @IdProgetto =( SELECT ID_PROGETTO FROM VARIANTI V WHERE ID_VARIANTE = @ID_VARIANTE)
		
		SELECT @SUP_PORT_NON_USATA = VALORE FROM PRIORITA_X_PROGETTO WHERE ID_PROGETTO =@IdProgetto AND ID_PRIORITA = 1219
	   	IF(@SUP_PORT_NON_USATA IS NULL )SET @Risultato =0		
		ELSE BEGIN 
			SELECT @MQ_CONVERSIONE=SUM(QUANTITA)
			FROM vPIANO_INVESTIMENTI INV 
				INNER JOIN DETTAGLIO_INVESTIMENTI D ON D.ID_DETTAGLIO_INVESTIMENTO = INV.ID_DETTAGLIO_INVESTIMENTO AND D.ID_CODIFICA_INVESTIMENTO = INV.ID_CODIFICA_INVESTIMENTO AND COD_DETTAGLIO = 'BB'
			WHERE ID_PROGETTO = @IdProgetto AND ID_VARIANTE = @ID_VARIANTE AND   isnull(COD_VARIAZIONE,'x')!='A' 
					
			SELECT @MQ_IMPIANTO=SUM(QUANTITA)
			FROM PIANO_INVESTIMENTI INV 
				INNER JOIN DETTAGLIO_INVESTIMENTI D ON D.ID_DETTAGLIO_INVESTIMENTO = INV.ID_DETTAGLIO_INVESTIMENTO AND D.ID_CODIFICA_INVESTIMENTO = INV.ID_CODIFICA_INVESTIMENTO AND COD_DETTAGLIO = 'AA'
			WHERE ID_PROGETTO = @IdProgetto AND ID_VARIANTE = @ID_VARIANTE AND   isnull(COD_VARIAZIONE,'x')!='A' 


	   		IF (@SUP_PORT_NON_USATA < (ISNULL(@MQ_CONVERSIONE,0) + ISNULL(@MQ_IMPIANTO ,0))) SET @Risultato=1
	   		ELSE SET @Risultato=0
		END	 	
	 
	SELECT @Risultato AS PUNTEGGIO
END
