CREATE  PROCEDURE [dbo].[calcoloStepPagamento_A_112_1]
@IdProgetto int,
@IdDomandaPagamento int =NULL
 AS
BEGIN

-- ANTICIPO Certificato Antimafia BANDO 112
-- Verifica presenza Certificato CCIAA valido con dicitura Antimafia - Antimafia Prefettura (per TOTALE progetto > 154.937,07)
-- verificare anche validità documento (max 6 mesi dal rilascio)	 
-- ANTICIPO Certificato Antimafia BANDO 112
-- Verifica presenza Certificato CCIAA valido con dicitura Antimafia - Antimafia Prefettura (per TOTALE progetto > 154.937,07)
-- verificare anche validità documento (max 6 mesi dal rilascio)	 
--DECLARE @IdProgetto int = 400,
--@IdDomandaPagamento int =386

DECLARE	@RESULT INT, @ID_IMPRESA INT, @DATA_FINE_ISTRUTTORIA DATETIME, @CONTRIBUTO_PROGETTO DECIMAL(16,2), @ID_VARIANTE INT
					--@DATA_CERTIFICAZIONE_ANTIMAFIA DATETIME,
					--@ID_VARIANTE int, 
					--@CONTRIBUTO_PROGETTO decimal(10,2),
					--@DATA_FINE_ISTRUTTORIA DATETIME ,
					--@DATA_MODIFICA_PAGAMENTO DATETIME,@COD_TIPO CHAR(3)
 
--declare @IdProgetto int,@IdDomandaPagamento int
--set @IdProgetto =1776 
--set @IdDomandaPagamento = (SELECT ID_DOMANDA_PAGAMENTO FROM DOMANDA_DI_PAGAMENTO WHERE ID_PROGETTO = @IdProgetto AND COD_TIPO= 'SLD' )
/*
  IMPONGO LO STEP NON VERIFICATO	
	SET @RESULT = 0
 
  SELECT @DATA_CERTIFICAZIONE_ANTIMAFIA = DATA_CERTIFICAZIONE_ANTIMAFIA, @DATA_FINE_ISTRUTTORIA = ISNULL(DATA_APPROVAZIONE,GETDATE())  FROM DOMANDA_DI_PAGAMENTO WHERE ID_DOMANDA_PAGAMENTO = @IdDomandaPagamento  
 
 IF( @DATA_CERTIFICAZIONE_ANTIMAFIA IS NULL  )
	BEGIN 
			SELECT @DATA_MODIFICA_PAGAMENTO=DATA_MODIFICA,@COD_TIPO=COD_TIPO,@ID_VARIANTE=ID_VARIAZIONE_ACCERTATA FROM DOMANDA_DI_PAGAMENTO 
								WHERE ID_DOMANDA_PAGAMENTO=@IdDomandaPagamento

		    SELECT @ID_VARIANTE=MAX(ID_VARIANTE) FROM VARIANTI WHERE ID_PROGETTO=@IdProgetto AND APPROVATA=1 AND ANNULLATA=0 AND DATA_MODIFICA<@DATA_MODIFICA_PAGAMENTO
 	
	 	SET @CONTRIBUTO_PROGETTO =  (SELECT  ISNULL( dbo.[calcoloContributoTotaleProgetto] (@IdProgetto, 1, @ID_VARIANTE),0) )--  ISNULL(dbo.[calcoloPremioContoCapitale] (@IdProgetto, 1, @ID_VARIANTE ) ,0))
		 	IF( @CONTRIBUTO_PROGETTO > (SELECT SUM(CONTRIBUTO_DI_MISURA) AS CONTRIBUTO_DI_MISURA FROM GRADUATORIA_PROGETTI_FINANZIABILITA GPF WHERE ID_PROG_INTEGRATO = @IdProgetto))
					SET @CONTRIBUTO_PROGETTO = (SELECT SUM(CONTRIBUTO_DI_MISURA) AS CONTRIBUTO_DI_MISURA FROM GRADUATORIA_PROGETTI_FINANZIABILITA GPF WHERE ID_PROG_INTEGRATO = @IdProgetto)
			IF (@CONTRIBUTO_PROGETTO <=  154937.07 )
					SET @RESULT =1
	END
ELSE 
BEGIN
	IF( DATEDIFF( day,  DATEADD (month, 6 , @DATA_CERTIFICAZIONE_ANTIMAFIA ), @DATA_FINE_ISTRUTTORIA ) <= 0 )	
 	 SET @RESULT=1
	END  
return @RESULT
 */
 -- modifica del 04-04-2013: controllo antimafia sotto i 150000 €
 
 -- IMPONGO LO STEP NON VERIFICATO	
SET @RESULT = 0 
SELECT @DATA_FINE_ISTRUTTORIA = ISNULL(DATA_APPROVAZIONE,GETDATE())  FROM DOMANDA_DI_PAGAMENTO WHERE ID_DOMANDA_PAGAMENTO = @IdDomandaPagamento  
SELECT @ID_IMPRESA = ID_IMPRESA FROM PROGETTO P   WHERE ID_PROGETTO = @IdProgetto
SELECT @ID_VARIANTE=MAX(ID_VARIANTE) FROM VARIANTI WHERE ID_PROGETTO=@IdProgetto AND APPROVATA=1 AND ANNULLATA=0 AND DATA_MODIFICA<=@DATA_FINE_ISTRUTTORIA
SET @CONTRIBUTO_PROGETTO =  (SELECT  ISNULL( dbo.[calcoloContributoTotaleProgetto] (@IdProgetto, 1, @ID_VARIANTE),0) +  ISNULL(dbo.[calcoloPremioContoCapitale] (@IdProgetto, 1, @ID_VARIANTE ) ,0))
IF( @CONTRIBUTO_PROGETTO > (SELECT SUM(CONTRIBUTO_DI_MISURA) AS CONTRIBUTO_DI_MISURA FROM GRADUATORIA_PROGETTI_FINANZIABILITA GPF WHERE ID_PROG_INTEGRATO = @IdProgetto))
	SET @CONTRIBUTO_PROGETTO = (SELECT SUM(CONTRIBUTO_DI_MISURA) AS CONTRIBUTO_DI_MISURA FROM GRADUATORIA_PROGETTI_FINANZIABILITA GPF WHERE ID_PROG_INTEGRATO = @IdProgetto)
IF (@CONTRIBUTO_PROGETTO <=  150000 )
	SET @RESULT =1
	ELSE EXEC @RESULT = SpControlloAntimafia @ID_IMPRESA, @DATA_FINE_ISTRUTTORIA
/**	 test se funziona
ELSE 
	BEGIN
		CREATE TABLE #TMP (RESULT INT)
		INSERT INTO #TMP EXEC SpControlloAntimafia @ID_IMPRESA, @DATA_FINE_ISTRUTTORIA
		SELECT @RESULT = RESULT FROM #TMP
		DROP TABLE #TMP
	END

*/
SELECT @RESULT
END
