CREATE PROCEDURE [dbo].[calcoloStep112_311_A1]
@IdProgetto int
AS
/*
  
DECLARE @IdProgetto INT
SET @IdProgetto =1862*/


DECLARE @ID_PROG_CORRENTE_311 INT, @ID_BANDO_311 INT 

SELECT DISTINCT @ID_PROG_CORRENTE_311 = p.ID_PROGETTO, @ID_BANDO_311=P.ID_BANDO FROM PROGETTO P
		INNER JOIN BANDO B ON B.ID_BANDO = P.ID_BANDO INNER JOIN ZPROGRAMMAZIONE ZP ON ZP.ID =B.ID_PROGRAMMAZIONE AND CODICE = '3.1.1.A'
WHERE ID_PROG_INTEGRATO = @IdProgetto

DECLARE @RESULT INT
SET  @RESULT=1

DECLARE @TOTALE_INVESTIMENTI DECIMAL(18,2)
SET @TOTALE_INVESTIMENTI=(SELECT ISNULL(SUM(COSTO_INVESTIMENTO),0) 
						  FROM PIANO_INVESTIMENTI WHERE ID_PROGETTO=@ID_PROG_CORRENTE_311 
								AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL)
IF @TOTALE_INVESTIMENTI>0 BEGIN
---CONTROLLO STEP
	IF (SELECT COUNT(*) FROM ITER_PROGETTO WHERE ID_PROGETTO=@IdProgetto AND ID_STEP IN (161,171,172) AND COD_ESITO='NO')>0
		SET @RESULT=0
END 
SELECT @RESULT
