CREATE  PROCEDURE [dbo].[calcoloStep123_FIL_6]
@IdProgetto int
AS
BEGIN


-- Controllo completa compilazione  del bilancio n-3 e materie prime

DECLARE @Result int,
		@DATA datetime ,
		@COUNT_B INT , @COUNT_MAT INT 
		 

SET @Result = 1 -- Impongo lo Step  verificato

IF(( SELECT COUNT(*)  FROM PRIORITA_X_PROGETTO WHERE ID_PRIORITA = 261 AND ID_PROGETTO =@IdProgetto  )>0 )
BEGIN
 SELECT @DATA =DATA
 FROM PROGETTO P  INNER JOIN PROGETTO_STORICO S ON  P.ID_PROGETTO = S.ID_PROGETTO 
 where P.ID_PROGETTO = @IdProgetto AND COD_STATO IN ('P','L')
 ORDER BY S.ID DESC 
 
 SET @COUNT_MAT  =(SELECT COUNT(ANNO) FROM  PRODOTTI_VENDITE 
					WHERE MATERIA_PRIMA=1  AND  ID_PROGETTO =@IdProgetto AND  ANNO <  year(@DATA)  )
SET @COUNT_B = ( SELECT COUNT ( ANNO ) FROM  BILANCIO_INDUSTRIALE  
				WHERE PREVISIONALE = 0 AND  ANNO <  year(@DATA) AND ID_IMPRESA IN ( SELECT TOP(1) ID_IMPRESA FROM  IMPRESA WHERE CUAA = ( SELECT CUAA FROM PROGETTO WHERE ID_PROGETTO = @IdProgetto  )    ))
 IF ( @COUNT_MAT < 3 OR  @COUNT_B <3) SET @Result =0
END
SELECT @Result AS RESULT
END
