--- Per l’intervento di cui al punto 2) del bando (centri unici di teleprenotazione), SE PRESENTI interventi di importo superiore ai 15.000,00 €.
--- GAL FLAMINIA CESANO

CREATE PROCEDURE [dbo].[calcoloStep4132c_FC_1]
@IdProgetto int, 
@FASE_ISTRUTTORIA INT = 0
AS
BEGIN

DECLARE @result int, @CONTAC2 int, @CONTA_ARREDI int, @COSTO_C2 int
SET @result = 0
	
SELECT @COSTO_C2 = (SELECT (ISNULL(SUM(COSTO_INVESTIMENTO),0) + ISNULL(SUM(SPESE_GENERALI),0)) AS Totale_Investimenti FROM PROGETTO P INNER JOIN
			vPIANO_INVESTIMENTI VPI ON P.ID_PROGETTO=VPI.ID_PROGETTO WHERE
			VPI.COD_TIPO_INVESTIMENTO = 1 AND
			((VPI.ID_INVESTIMENTO_ORIGINALE IS NULL AND @FASE_ISTRUTTORIA=0 AND ID_VARIANTE IS NULL)OR
			(VPI.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND @FASE_ISTRUTTORIA =1 AND ID_VARIANTE IS NULL)) AND			
			VPI.CODICE IN ('C2','2') AND
			P.ID_PROGETTO=@IdProgetto)
			
IF (@COSTO_C2 > 15000 OR @COSTO_C2 = 0 )
SET @result = 1

SELECT @result AS RESULT
END
