CREATE PROCEDURE [dbo].[calcoloStep133_11]
(
	@IdProgetto int,
	@FASE_ISTRUTTORIA INT =0
)
AS
BEGIN
-- CONTROLLO CUAA - ID_PROGETTO - SCADENZA MICRO
/*
275	Misura 133 - PROMOZIONE nelle MICRO FILIERE
299	Misura 133 - PROMOZIONE nelle MICRO FILIERE SECONDA SCADENZA
343	Misura 133 - PROMOZIONE nelle MICRO FILIERE TERZA SCADENZA
396	Misura 133 - PROMOZIONE nelle MICRO FILIERE QUARTA SCADENZA
*/
DECLARE @RESULT INT, @ID_IMPRESA int, @ID_PROGETTO_PLURI INT  , @ID_BANDO_PLURI INT , @ID_BANDO_ANNUALE INT
		
--SET @IdProgetto = 9023
SET @RESULT =0 --PONGO LO STEP NON VERIFICATO

SELECT @ID_IMPRESA = P.ID_IMPRESA , @ID_BANDO_ANNUALE =ID_BANDO
FROM PROGETTO P INNER JOIN IMPRESA IMP ON IMP.ID_IMPRESA = P.ID_IMPRESA  WHERE ID_PROGETTO = @IdProgetto 

SELECT @ID_PROGETTO_PLURI= VALORE FROM PRIORITA_X_PROGETTO PP WHERE ID_PROGETTO = @IdProgetto AND ID_PRIORITA =757

IF(@ID_PROGETTO_PLURI IS NULL) SET @RESULT=0
ELSE BEGIN 
	SELECT @ID_BANDO_PLURI = ID_BANDO FROM vPROGETTO WHERE ID_PROGETTO = @ID_PROGETTO_PLURI AND ID_IMPRESA=@ID_IMPRESA AND COD_STATO IN ('A', 'F')
	IF(ISNULL(@ID_BANDO_ANNUALE,0) = 402 AND ISNULL(@ID_BANDO_PLURI,0)= 275) SET @RESULT=1
	ELSE IF(ISNULL(@ID_BANDO_ANNUALE,0) = 403 AND ISNULL(@ID_BANDO_PLURI,0)= 299) SET @RESULT=1
	ELSE IF(ISNULL(@ID_BANDO_ANNUALE,0) = 435 AND ISNULL(@ID_BANDO_PLURI,0)=343) SET @RESULT=1
		
END

SELECT @RESULT 
END
