--Investimenti completi di indicazione dell`annualità di PROGETTO e di REALIZZAZIONE

CREATE   PROCEDURE [dbo].[calcoloStep133_7] 
(
@IdProgetto int,
@FASE_ISTRUTTORIA INT =0
)
AS
BEGIN
 

--declare @IdProgetto int,
-- @FASE_ISTRUTTORIA INT  
--
--set @IdProgetto=7343
--set @FASE_ISTRUTTORIA=0

DECLARE @NUM_INVESTIMENTI INT,@NUM_ANNO INT,@NUM_REALIZZAZIONE INT ,@RESULT INT =1, @COUNT_ANNO_R INT

SELECT @NUM_INVESTIMENTI = COUNT(*) FROM PIANO_INVESTIMENTI PI  
WHERE ID_PROGETTO = @IdProgetto AND ((@FASE_ISTRUTTORIA=0 AND ID_INVESTIMENTO_ORIGINALE IS NULL AND ID_VARIANTE IS NULL) OR(@FASE_ISTRUTTORIA=1 AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL))

SELECT @NUM_REALIZZAZIONE= COUNT(*) FROM  PIANO_INVESTIMENTI AS PI INNER JOIN PRIORITA_X_INVESTIMENTI ON PI.ID_INVESTIMENTO = PRIORITA_X_INVESTIMENTI.ID_INVESTIMENTO 
WHERE (PI.ID_PROGETTO = @IdProgetto ) AND ID_PRIORITA = 768 AND 
		((@FASE_ISTRUTTORIA=0 AND ID_INVESTIMENTO_ORIGINALE IS NULL AND ID_VARIANTE IS NULL) OR(@FASE_ISTRUTTORIA=1 AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL))

SELECT @COUNT_ANNO_R=COUNT(*) FROM (
			SELECT COUNT(*) AS TIPO_NUM FROM PIANO_INVESTIMENTI AS PI 
				INNER JOIN PRIORITA_X_INVESTIMENTI ON PI.ID_INVESTIMENTO = PRIORITA_X_INVESTIMENTI.ID_INVESTIMENTO 
			WHERE (PI.ID_PROGETTO = @IdProgetto) AND ID_PRIORITA = 768 AND 
					((@FASE_ISTRUTTORIA=0 AND ID_INVESTIMENTO_ORIGINALE IS NULL AND ID_VARIANTE IS NULL) OR(@FASE_ISTRUTTORIA=1 AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL))
			GROUP BY ID_VALORE )AS T

IF(@NUM_INVESTIMENTI!=@NUM_REALIZZAZIONE OR @COUNT_ANNO_R > 1) SET @RESULT =0
ELSE BEGIN
		SELECT @NUM_ANNO = COUNT(*) FROM  PIANO_INVESTIMENTI AS PI 
				INNER JOIN PRIORITA_X_INVESTIMENTI ON PI.ID_INVESTIMENTO = PRIORITA_X_INVESTIMENTI.ID_INVESTIMENTO 
		WHERE (PI.ID_PROGETTO = @IdProgetto ) AND ID_PRIORITA = 404 AND 
				((@FASE_ISTRUTTORIA=0 AND ID_INVESTIMENTO_ORIGINALE IS NULL AND ID_VARIANTE IS NULL) OR (@FASE_ISTRUTTORIA=1 AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL))
		IF(@NUM_INVESTIMENTI!=@NUM_ANNO) SET @RESULT =0
	 END 
END
