CREATE PROCEDURE [dbo].[calcoloRequisitoPagamento413_F]
@ID_DOMANDA_PAGAMENTO int
AS
BEGIN

-- GAL FERMANO
-- ANTICIPO
-- 184	Data di ricezione della comunicazione di finanziabilità
-- 185	Data inizio interventi programmati
-- 186	Richiesta proroga di 60 giorni per l`inizio lavori

--DECLARE @ID_DOMANDA_PAGAMENTO int
--SET @ID_DOMANDA_PAGAMENTO = 1
DECLARE @ID_PROGETTO INT, 
					@RESULT INT,
					@DIFFERENZA INT,
					@DIFFERENZA_PROROGA DECIMAL (18,2),
					@PROROGA INT
					
					
SELECT @DIFFERENZA = DATEDIFF(DAY, DATEADD(DD,120,(select VAL_DATA from DOMANDA_PAGAMENTO_REQUISITI where 
														ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO  and ID_REQUISITO =184)
												 ) , (select VAL_DATA from DOMANDA_PAGAMENTO_REQUISITI where
												        ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO  and ID_REQUISITO =185))

-- PROROGATO DI 60 GIORNI
SELECT @DIFFERENZA_PROROGA = DATEDIFF(DAY, DATEADD(DD,180,(select VAL_DATA from DOMANDA_PAGAMENTO_REQUISITI where 
														ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO  and ID_REQUISITO = 184)
												 ) , (select VAL_DATA from DOMANDA_PAGAMENTO_REQUISITI where
												        ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO  and ID_REQUISITO = 185)) 

							
SELECT @PROROGA = count(ID_REQUISITO) FROM  DOMANDA_PAGAMENTO_REQUISITI where ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO  AND ID_REQUISITO = 186


IF (((@DIFFERENZA <= 0) AND (@PROROGA = 0)) OR ((@DIFFERENZA_PROROGA <= 0) AND (@PROROGA = 1)))
SET @RESULT = 1 	
	 ELSE SET @RESULT = 0 	

SELECT @RESULT
END
