CREATE PROCEDURE [dbo].[calcoloRequisitoPagamento_B243_1]
@ID_DOMANDA_PAGAMENTO int
AS
BEGIN

-- SALDO
--==== Richiesta di saldo ===--

--448	Richiesta di saldo (entro 18 mesi dalla data di ricezione della comunicazione della finanziabilità oltre eventuali proroghe per la fine lavori ma comunque non oltre il 30/06/2015)
--450	Eseguito il controllo di ammissibilità dopo aver compilato la rendicontazione richiesta
--451	Richiesta proroga massima concedibile.
--453	Data di ricevimento dell`atto di concessione dell`aiuto

--DECLARE @ID_DOMANDA_PAGAMENTO int
--SET @ID_DOMANDA_PAGAMENTO = 1
DECLARE @ID_PROGETTO INT, 
					@RESULT INT,
					@DATA_ULTIMA DATETIME = '2015-06-30 00:00:00.000',
					@PROROGA INT,
					@DATA_RICHIESTA_SALDO DATETIME,
					@DATA_COM_FINAN DATETIME


SELECT @DATA_RICHIESTA_SALDO = DATA_MODIFICA FROM DOMANDA_DI_PAGAMENTO WHERE ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO
SELECT @DATA_COM_FINAN = VAL_DATA FROM DOMANDA_PAGAMENTO_REQUISITI WHERE ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO AND ID_REQUISITO = 453
								
SELECT @PROROGA=CASE WHEN COUNT(*)>0 THEN 1 ELSE 0 END FROM DOMANDA_PAGAMENTO_REQUISITI WHERE ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO  AND ID_REQUISITO = 451

if (@PROROGA = 0) 
	SET @RESULT=(SELECT 'DIFF'= CASE WHEN DATEDIFF(DAY, DATEADD(MM,18,(@DATA_COM_FINAN)), @DATA_RICHIESTA_SALDO)<=0 THEN 1 ELSE 0 END)
else
	SET @RESULT=(SELECT 'DIFF'= CASE WHEN DATEDIFF(DAY, @DATA_ULTIMA, @DATA_RICHIESTA_SALDO)<=0 THEN 1 ELSE 0 END)

SELECT @RESULT
END
