CREATE  PROCEDURE [dbo].[calcoloStepPagamento_B306]
@IdProgetto INT ,
@ID_DOMANDA_PAGAMENTO int
AS
BEGIN

-- La spesa rendicontata ammissibile è >= ad euro 25.000

--DECLARE @IdProgetto INT , @ID_DOMANDA_PAGAMENTO int
--SET @ID_DOMANDA_PAGAMENTO =  1181
--SET @IdProgetto =2896 
 
DECLARE @result INT, @COSTO_INVESTIMENTO_SALDO DECIMAL (18,2), @COSTO_INVESTIMENTO_SAL DECIMAL (18,2)
SET @result =0

-- importo ammesso totale
SET @COSTO_INVESTIMENTO_SALDO = 
(SELECT  SUM(ISNULL(IMPORTO_AMMESSO,0)) 
 FROM PAGAMENTI_RICHIESTI P  WHERE ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO  )

SET @COSTO_INVESTIMENTO_SAL = 
(SELECT SUM(ISNULL(IMPORTO_AMMESSO,0)) FROM PAGAMENTI_RICHIESTI P 
		INNER JOIN DOMANDA_DI_PAGAMENTO dp on dp.ID_DOMANDA_PAGAMENTO = p.ID_DOMANDA_PAGAMENTO 
WHERE dp.ID_DOMANDA_PAGAMENTO < @ID_DOMANDA_PAGAMENTO AND dp.ID_PROGETTO=@IdProgetto and 
		dp.APPROVATA = 1 and ANNULLATA =0)
		 
IF ((@COSTO_INVESTIMENTO_SALDO +  ISNULL(@COSTO_INVESTIMENTO_SAL,0)) >= 25000) SET @RESULT = 1 --- VERIFICATO

SELECT @RESULT AS RESULT

END
