---- Corrispondenza tra tipo beneficiario e dichiarazione GAL PICENO
CREATE PROCEDURE [dbo].[calcoloStep4135_GP]
@IdProgetto int, 
@FASE_ISTRUTTORIA INT = 0
AS
BEGIN

DECLARE @result int , @SOGGETTOPUBBLICO int, @SOGGETTOPRIVATO int, @DICHIARAPriv int, @DICHIARAPub int
SET @result = 0

SELECT @SOGGETTOPUBBLICO = (SELECT COUNT(ID_DICHIARAZIONE) FROM DICHIARAZIONI_X_PROGETTO WHERE ID_PROGETTO = @IdProgetto AND ID_DICHIARAZIONE in (508))
SELECT @SOGGETTOPRIVATO = (SELECT COUNT(ID_DICHIARAZIONE) FROM DICHIARAZIONI_X_PROGETTO WHERE ID_PROGETTO = @IdProgetto AND ID_DICHIARAZIONE in (509))

SELECT @DICHIARAPriv = (SELECT COUNT(ID_DICHIARAZIONE) FROM DICHIARAZIONI_X_PROGETTO WHERE ID_PROGETTO = @IdProgetto AND ID_DICHIARAZIONE in (510,511))
SELECT @DICHIARAPub = (SELECT COUNT(ID_DICHIARAZIONE) FROM DICHIARAZIONI_X_PROGETTO WHERE ID_PROGETTO = @IdProgetto AND ID_DICHIARAZIONE = 512)

IF  (
	(ISNULL(@SOGGETTOPRIVATO,0) = 1 AND @DICHIARAPriv = 2) OR
	(ISNULL(@SOGGETTOPUBBLICO,0) = 1 AND @DICHIARAPub = 1 AND @DICHIARAPriv = 0)
	)
SET @result = 1
ELSE SET @result = 0

SELECT @result AS RESULT
END
