CREATE PROCEDURE [dbo].[calcoloStep124_1]
@IdProgetto int,
@fase_istruttoria int =0
AS
BEGIN

--    124 - Costo massimo unitario per codifica

DECLARE @Result int,@ID_BANDO INT
SET @Result = 1 -- Impongo lo Step verificato
--------------------------------------------------------------------------------------------------------------

-- 1. Incontri informativi collegiali

SELECT @ID_BANDO = ID_BANDO, @IdProgetto=P.ID_PROGETTO 
FROM PROGETTO P WHERE ID_PROGETTO =@IdProgetto 

DECLARE @SpeseIncontri  decimal (10,2)
DECLARE @NumeroIncontri int
 

IF(@ID_BANDO =414) BEGIN 
	SET @SpeseIncontri  = ( SELECT ISNULL(SUM(PI.COSTO_INVESTIMENTO),0)
							FROM PIANO_INVESTIMENTI PI INNER JOIN PROGETTO P ON (PI.ID_PROGETTO = P.ID_PROGETTO)
								INNER JOIN DETTAGLIO_INVESTIMENTI D ON D.ID_CODIFICA_INVESTIMENTO = pi.ID_CODIFICA_INVESTIMENTO and d.ID_DETTAGLIO_INVESTIMENTO = pi.ID_DETTAGLIO_INVESTIMENTO 
							WHERE PI.COD_TIPO_INVESTIMENTO = 1 AND PI.ID_PROGETTO  = @IdProgetto AND 
							 ((PI.ID_INVESTIMENTO_ORIGINALE IS NULL AND @fase_istruttoria=0) OR 
								(PI.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL AND @fase_istruttoria=1))
							  AND COD_DETTAGLIO  = '5') 
END 
ELSE BEGIN
	SET @SpeseIncontri  = ( SELECT ISNULL(SUM(PI.COSTO_INVESTIMENTO),0)
							FROM PIANO_INVESTIMENTI PI INNER JOIN PROGETTO P ON (PI.ID_PROGETTO = P.ID_PROGETTO)
							WHERE (P.ID_PROGETTO=@IdProgetto OR P.ID_PROG_INTEGRATO=@IdProgetto) AND PI.COD_TIPO_INVESTIMENTO = 1 AND
								((PI.ID_INVESTIMENTO_ORIGINALE IS NULL AND @fase_istruttoria=0) OR (PI.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL AND @fase_istruttoria=1))
								AND PI.ID_CODIFICA_INVESTIMENTO IN (SELECT ID_CODIFICA_INVESTIMENTO FROM CODIFICA_INVESTIMENTO
																	WHERE ID_BANDO = (SELECT ID_BANDO FROM PROGETTO WHERE ID_PROGETTO = @IdProgetto)AND CODICE = '5'))
END
--Priorita  393
SET @NumeroIncontri = (SELECT ISNULL( PP.VALORE ,0)FROM PRIORITA_X_PROGETTO PP WHERE PP.ID_PROGETTO = @IdProgetto AND PP.ID_PRIORITA = 393)
IF (@SpeseIncontri > (200 * ISNULL(@NumeroIncontri,0))) SET @Result = 0
 
 --------------------------------------------------------------------------------------------------------------
 --Seminari informativi

DECLARE @SpeseSeminari decimal (10,2)
DECLARE @NumeroSeminari int


IF(@ID_BANDO =414) BEGIN 
	SET @SpeseSeminari  = ( SELECT ISNULL(SUM(PI.COSTO_INVESTIMENTO),0)
							FROM PIANO_INVESTIMENTI PI INNER JOIN PROGETTO P ON (PI.ID_PROGETTO = P.ID_PROGETTO)
								INNER JOIN DETTAGLIO_INVESTIMENTI D ON D.ID_CODIFICA_INVESTIMENTO = pi.ID_CODIFICA_INVESTIMENTO and d.ID_DETTAGLIO_INVESTIMENTO = pi.ID_DETTAGLIO_INVESTIMENTO 
							WHERE PI.COD_TIPO_INVESTIMENTO = 1 AND PI.ID_PROGETTO  = @IdProgetto AND 
							 ((PI.ID_INVESTIMENTO_ORIGINALE IS NULL AND @fase_istruttoria=0) OR 
								(PI.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL AND @fase_istruttoria=1))
							  AND COD_DETTAGLIO  = '6') 
END 
ELSE BEGIN 
	SET @SpeseSeminari  = ( SELECT ISNULL(SUM(PI.COSTO_INVESTIMENTO),0)
							FROM PIANO_INVESTIMENTI PI INNER JOIN PROGETTO P ON (PI.ID_PROGETTO = P.ID_PROGETTO)
							WHERE (P.ID_PROGETTO=@IdProgetto OR P.ID_PROG_INTEGRATO=@IdProgetto) AND PI.COD_TIPO_INVESTIMENTO = 1 AND
								((PI.ID_INVESTIMENTO_ORIGINALE IS NULL AND @fase_istruttoria=0) OR (PI.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL AND @fase_istruttoria=1))
								AND PI.ID_CODIFICA_INVESTIMENTO IN (SELECT ID_CODIFICA_INVESTIMENTO FROM CODIFICA_INVESTIMENTO															
																	WHERE ID_BANDO = (SELECT ID_BANDO FROM PROGETTO WHERE ID_PROGETTO = @IdProgetto)AND CODICE = '6'))
END
--Priorita  394
SET @NumeroSeminari = (SELECT ISNULL( PP.VALORE ,0)FROM PRIORITA_X_PROGETTO PP WHERE PP.ID_PROGETTO = @IdProgetto AND PP.ID_PRIORITA = 394)
IF (@SpeseSeminari > (800 * ISNULL(@NumeroSeminari,0))) SET @Result = 0

 --------------------------------------------------------------------------------------------------------------
 -- Visite guidate, campi dimostrativi, Open day

DECLARE @SpeseVisite decimal (10,2)
DECLARE @NumeroVisite  int
 
IF(@ID_BANDO =414) BEGIN 
	SET @SpeseVisite  = ( SELECT ISNULL(SUM(PI.COSTO_INVESTIMENTO),0)
							FROM PIANO_INVESTIMENTI PI INNER JOIN PROGETTO P ON (PI.ID_PROGETTO = P.ID_PROGETTO)
								INNER JOIN DETTAGLIO_INVESTIMENTI D ON D.ID_CODIFICA_INVESTIMENTO = pi.ID_CODIFICA_INVESTIMENTO and d.ID_DETTAGLIO_INVESTIMENTO = pi.ID_DETTAGLIO_INVESTIMENTO 
							WHERE PI.COD_TIPO_INVESTIMENTO = 1 AND PI.ID_PROGETTO  = @IdProgetto AND 
							 ((PI.ID_INVESTIMENTO_ORIGINALE IS NULL AND @fase_istruttoria=0) OR 
								(PI.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL AND @fase_istruttoria=1))
							  AND COD_DETTAGLIO  = '7') 
END 
ELSE BEGIN
SET @SpeseVisite  = ( SELECT ISNULL(SUM(PI.COSTO_INVESTIMENTO),0)
						FROM PIANO_INVESTIMENTI PI INNER JOIN PROGETTO P ON (PI.ID_PROGETTO = P.ID_PROGETTO)
						WHERE (P.ID_PROGETTO=@IdProgetto OR P.ID_PROG_INTEGRATO=@IdProgetto) AND PI.COD_TIPO_INVESTIMENTO = 1 AND
							((PI.ID_INVESTIMENTO_ORIGINALE IS NULL AND @fase_istruttoria=0) OR (PI.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL AND @fase_istruttoria=1))
							AND PI.ID_CODIFICA_INVESTIMENTO IN (SELECT ID_CODIFICA_INVESTIMENTO	FROM CODIFICA_INVESTIMENTO
																WHERE ID_BANDO = (SELECT ID_BANDO FROM PROGETTO WHERE ID_PROGETTO = @IdProgetto) AND CODICE = '7'))
END

--Priorita  394
SET @NumeroVisite = (SELECT ISNULL( PP.VALORE ,0)FROM PRIORITA_X_PROGETTO PP WHERE PP.ID_PROGETTO = @IdProgetto AND PP.ID_PRIORITA = 395)
IF (@SpeseVisite > (1500 * ISNULL(@NumeroVisite,0))) SET @Result = 0
--------------------------------------------------------------------------------------------------------------
 -- Visite guidate, campi dimostrativi, Open day

DECLARE @SpeseVisiteGui decimal (10,2)
DECLARE @NumeroVisiteGui int


IF(@ID_BANDO =414) BEGIN 
	SET @SpeseVisiteGui  = ( SELECT ISNULL(SUM(PI.COSTO_INVESTIMENTO),0)
							FROM PIANO_INVESTIMENTI PI INNER JOIN PROGETTO P ON (PI.ID_PROGETTO = P.ID_PROGETTO)
								INNER JOIN DETTAGLIO_INVESTIMENTI D ON D.ID_CODIFICA_INVESTIMENTO = pi.ID_CODIFICA_INVESTIMENTO and d.ID_DETTAGLIO_INVESTIMENTO = pi.ID_DETTAGLIO_INVESTIMENTO 
							WHERE PI.COD_TIPO_INVESTIMENTO = 1 AND PI.ID_PROGETTO  = @IdProgetto AND 
							 ((PI.ID_INVESTIMENTO_ORIGINALE IS NULL AND @fase_istruttoria=0) OR 
								(PI.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL AND @fase_istruttoria=1))
							  AND COD_DETTAGLIO  = '8') 
END 
ELSE BEGIN
SET @SpeseVisiteGui  = ( SELECT ISNULL(SUM(PI.COSTO_INVESTIMENTO),0)
						FROM PIANO_INVESTIMENTI PI INNER JOIN PROGETTO P ON (PI.ID_PROGETTO = P.ID_PROGETTO)
						WHERE (P.ID_PROGETTO=@IdProgetto OR P.ID_PROG_INTEGRATO=@IdProgetto) AND PI.COD_TIPO_INVESTIMENTO = 1 AND
						((PI.ID_INVESTIMENTO_ORIGINALE IS NULL AND @fase_istruttoria=0) OR (PI.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL AND @fase_istruttoria=1))
						AND PI.ID_CODIFICA_INVESTIMENTO IN (SELECT ID_CODIFICA_INVESTIMENTO FROM CODIFICA_INVESTIMENTO
															WHERE ID_BANDO = (SELECT ID_BANDO FROM PROGETTO WHERE ID_PROGETTO = @IdProgetto)AND CODICE = '8'))
END
--Priorita  396
SET @NumeroVisiteGui = (SELECT ISNULL( PP.VALORE ,0)FROM PRIORITA_X_PROGETTO PP WHERE PP.ID_PROGETTO = @IdProgetto AND PP.ID_PRIORITA = 396)
IF (@SpeseVisiteGui > (1500 * ISNULL(@NumeroVisiteGui,0))) SET @Result = 0
SELECT @Result AS RESULT
END
