CREATE   PROCEDURE [dbo].[calcoloStep125_1]
@IdProgetto int
AS
BEGIN
 
--- 125   controllo degli allegati obbligatori
 
 
DECLARE @RESULT int,	@CODICE VARCHAR(10)	 , @COUNT_OBB INT , @COUNT_SAF INT, @COUNT_COM INT
 
SET @RESULT = 1  -- Impongo lo Step   verificato
--------------------------------------------------------------------------------------------------------------
 SET @CODICE = (SELECT CODICE FROM VALORI_PRIORITA VP INNER JOIN PRIORITA_X_PROGETTO PP ON PP.ID_VALORE = VP.ID_VALORE WHERE PP.ID_PRIORITA = 378 AND PP.ID_PROGETTO = @IdProgetto )
 SET @COUNT_OBB =(SELECT COUNT (* ) FROM ALLEGATI_X_PROGETTO A WHERE ID_PROGETTO = @IdProgetto AND ID_ALLEGATO IN (205,206,208,217,218,221,222,224,226, 227))
IF( @CODICE IS NULL OR  @COUNT_OBB != 10 )
		SET @RESULT =0

IF(  @CODICE IN ('CM','Com','EPNE')  )

BEGIN 
IF ( (SELECT COUNT (* ) FROM ALLEGATI_X_PROGETTO A WHERE ID_PROGETTO = @IdProgetto AND ID_ALLEGATO IN  (210,211, 214,215,225)) !=5 ) 	SET @RESULT =0
IF(    (SELECT COUNT (*)  FROM PIANO_INVESTIMENTI I  WHERE ID_PROGETTO = @IdProgetto AND ID_INVESTIMENTO_ORIGINALE IS NULL AND  ID_CODIFICA_INVESTIMENTO= 778 ) >0)
	        BEGIN     IF ( (SELECT COUNT (* ) FROM ALLEGATI_X_PROGETTO A WHERE ID_PROGETTO = @IdProgetto AND ID_ALLEGATO IN ( 212)) !=1 )  	SET @RESULT =0    END 
IF(  @CODICE IN ('CM','Com','EPNE')   AND  (SELECT sum(COSTO_INVESTIMENTO)  as COSTO_INVESTIMENTO FROM PIANO_INVESTIMENTI I  WHERE ID_PROGETTO = @IdProgetto AND ID_INVESTIMENTO_ORIGINALE IS NULL   ) > 100000)
	   BEGIN   IF ( (SELECT COUNT (* ) FROM ALLEGATI_X_PROGETTO A WHERE ID_PROGETTO = @IdProgetto AND ID_ALLEGATO IN ( 213)) !=1 )  	SET @RESULT =0   END 
END

IF ( @CODICE IN ('SAF') AND (SELECT COUNT (* ) FROM ALLEGATI_X_PROGETTO A WHERE ID_PROGETTO = @IdProgetto AND ID_ALLEGATO IN ( 207,209)) !=2 )
  	SET @RESULT =0

SELECT @RESULT
 END
