CREATE PROCEDURE [dbo].[calcoloRequisitoPagamentoATS_3]
@ID_DOMANDA_PAGAMENTO int
AS
BEGIN

--DECLARE @ID_DOMANDA_PAGAMENTO int
--SET @ID_DOMANDA_PAGAMENTO = 1050

-- 	ATS - Spese per costi informatici e telefonici inferiore/uguale al 5% di A+B+C+D

DECLARE @result int , @ID_PROGETTO INT,
					@IMPORTO_AMMESSO decimal(18,2),@IMPORTO_DOMANDA_ATTUALE DECIMAL(18,2),
					@IMPORTO_DOMANDA_ATTUALE_E decimal(18,2), @IMPORTO_AMMESSO_E DECIMAL (18,2)

SET @ID_PROGETTO = ( SELECT ID_PROGETTO FROM DOMANDA_DI_PAGAMENTO WHERE ID_DOMANDA_PAGAMENTO=@ID_DOMANDA_PAGAMENTO  )	
SET @result =1 -- PONGO LO STEP VERIFICATO 

SET @IMPORTO_AMMESSO = ( SELECT     ISNULL(SUM(ISNULL(PB.IMPORTO_AMMESSO, 0) + ISNULL(PB.SPESA_TECNICA_AMMESSA, 0)), 0) AS Expr1
															FROM PAGAMENTI_BENEFICIARIO AS PB INNER JOIN
																				  PAGAMENTI_RICHIESTI AS PR ON PB.ID_PAGAMENTO_RICHIESTO = PR.ID_PAGAMENTO_RICHIESTO INNER JOIN
																				  PIANO_INVESTIMENTI AS INV ON PR.ID_INVESTIMENTO = INV.ID_INVESTIMENTO
															WHERE  (PR.ID_DOMANDA_PAGAMENTO IN (SELECT ID_DOMANDA_PAGAMENTO FROM DOMANDA_DI_PAGAMENTO WHERE (ID_PROGETTO = @ID_PROGETTO) AND (APPROVATA = 1) AND (ANNULLATA = 0)))AND   
																				 ID_DETTAGLIO_INVESTIMENTO NOT IN (722,727,732,737,742))	

 SET @IMPORTO_DOMANDA_ATTUALE= ( SELECT     ISNULL(SUM(ISNULL(PB.IMPORTO_RICHIESTO, 0) + ISNULL(PB.SPESA_TECNICA_RICHIESTA, 0)), 0) AS Expr1
																				FROM PAGAMENTI_BENEFICIARIO AS PB INNER JOIN
																									  PAGAMENTI_RICHIESTI AS PR ON PB.ID_PAGAMENTO_RICHIESTO = PR.ID_PAGAMENTO_RICHIESTO INNER JOIN
																									  PIANO_INVESTIMENTI AS INV ON PR.ID_INVESTIMENTO = INV.ID_INVESTIMENTO
																				WHERE   ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO AND ID_DETTAGLIO_INVESTIMENTO NOT IN (722,727,732,737,742))	

 

SET @IMPORTO_AMMESSO_E = ( SELECT     ISNULL(SUM(ISNULL(PB.IMPORTO_AMMESSO, 0) + ISNULL(PB.SPESA_TECNICA_AMMESSA, 0)), 0) AS Expr1
															    FROM PAGAMENTI_BENEFICIARIO AS PB INNER JOIN
																			PAGAMENTI_RICHIESTI AS PR ON PB.ID_PAGAMENTO_RICHIESTO = PR.ID_PAGAMENTO_RICHIESTO INNER JOIN
																			PIANO_INVESTIMENTI AS INV ON PR.ID_INVESTIMENTO = INV.ID_INVESTIMENTO
															   WHERE  (PR.ID_DOMANDA_PAGAMENTO IN  (SELECT     ID_DOMANDA_PAGAMENTO FROM DOMANDA_DI_PAGAMENTO WHERE (ID_PROGETTO = @ID_PROGETTO) AND (APPROVATA = 1) AND (ANNULLATA = 0)))AND   
																			ID_SPECIFICA_INVESTIMENTO IN (347,408,417,426,435 ))	

 SET @IMPORTO_DOMANDA_ATTUALE_E= ( SELECT ISNULL(SUM(ISNULL(PB.IMPORTO_RICHIESTO, 0) + ISNULL(PB.SPESA_TECNICA_RICHIESTA, 0)), 0) AS Expr1
																				    FROM PAGAMENTI_BENEFICIARIO AS PB INNER JOIN
																								PAGAMENTI_RICHIESTI AS PR ON PB.ID_PAGAMENTO_RICHIESTO = PR.ID_PAGAMENTO_RICHIESTO INNER JOIN
																								PIANO_INVESTIMENTI AS INV ON PR.ID_INVESTIMENTO = INV.ID_INVESTIMENTO
																				WHERE   ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO AND ID_SPECIFICA_INVESTIMENTO IN (347,408,417,426,435 ))	

IF((ISNULL(@IMPORTO_AMMESSO_E,0)+ISNULL(@IMPORTO_DOMANDA_ATTUALE_E,0)) > (@IMPORTO_DOMANDA_ATTUALE+ @IMPORTO_AMMESSO)*0.5 )SET @result =0 
SELECT @result AS RESULT
END
