--SALDO 121 PABS
-- SALDO 121 PSR
CREATE  PROCEDURE [dbo].[calcoloRequisitoPagamento121_2]
@ID_DOMANDA_PAGAMENTO int
AS
BEGIN
	--	Verifica totale investimenti in domanda >= 25.000,00 €
	--  Requisiti pagamento esito positivo =1 
	
	DECLARE @ID_PROGETTO INT , @IMPORTO_AMMESSO DECIMAL (18,2), @IMPORTO_DOMANDA_ATTUALE DECIMAL (18,2)
	DECLARE @RESULT INT

SET @RESULT = 0 -- IMPONGO LO STEP NON VERIFICATO		 

SET @ID_PROGETTO = ( SELECT ID_PROGETTO FROM DOMANDA_DI_PAGAMENTO WHERE ID_DOMANDA_PAGAMENTO=@ID_DOMANDA_PAGAMENTO  )	

--COSTO INVESTIMENTO AMMESSO NELLE DOMANDE PRECEDENTI
SET @IMPORTO_AMMESSO = ( 
						SELECT  SUM( ISNULL( PB.IMPORTO_AMMESSO,0 ))
						 FROM    PAGAMENTI_BENEFICIARIO PB INNER JOIN
								  PAGAMENTI_RICHIESTI PR ON PB.ID_PAGAMENTO_RICHIESTO = PR.ID_PAGAMENTO_RICHIESTO
						 WHERE ID_DOMANDA_PAGAMENTO  IN (SELECT ID_DOMANDA_PAGAMENTO FROM DOMANDA_DI_PAGAMENTO 
															WHERE ID_PROGETTO = @ID_PROGETTO AND APPROVATA = 1  AND ANNULLATA=0 AND ID_DOMANDA_PAGAMENTO <@ID_DOMANDA_PAGAMENTO
														  ) 
						 AND SPESA_TECNICA_RICHIESTA =0 
					   )	

SET @IMPORTO_DOMANDA_ATTUALE =  ( SELECT  SUM( ISNULL( PB.IMPORTO_RICHIESTO,0 ))
								  FROM    PAGAMENTI_BENEFICIARIO PB INNER JOIN
										  PAGAMENTI_RICHIESTI PR ON PB.ID_PAGAMENTO_RICHIESTO = PR.ID_PAGAMENTO_RICHIESTO
								  WHERE ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO  AND SPESA_TECNICA_RICHIESTA =0 )  

IF((@IMPORTO_DOMANDA_ATTUALE + isnull(@IMPORTO_AMMESSO,0))>=25000 )
	SET @RESULT = 1

SELECT @RESULT
END
