CREATE  PROCEDURE [dbo].[calcoloStepPagamento133_1]
@IdProgetto int,
@IdDomandaPagamento int =NULL
AS
 BEGIN
--	E` possibile presentare domanda di SAL (spesa rendicontata >= 50% di quella autorizzata per il progetto annuale)
--  Requisiti pagamento esito positivo =1 
-- anno =228
--	
DECLARE  @ANNO VARCHAR(4), @DATA_MODIFICA DATETIME,@ID_VARIANTE INT, 
						@IMPORTO_RICHIESTO DECIMAL (18,2), @IMPORTO_AMMESSO DECIMAL (18,2), 
						@COSTO_INVESTIMENTO DECIMAL(18,2), @COSTO_TOTALE DECIMAL (18,2)
	DECLARE @RESULT INT

SET @RESULT = 1 -- IMPONGO LO STEP  VERIFICATO
SET @IMPORTO_RICHIESTO= 0 	 
SELECT  @DATA_MODIFICA =DATA_MODIFICA FROM DOMANDA_DI_PAGAMENTO WHERE ID_DOMANDA_PAGAMENTO=@IdDomandaPagamento 	
SELECT @ID_VARIANTE= MAX(ID_VARIANTE) FROM VARIANTI WHERE ID_PROGETTO =@IdProgetto AND APPROVATA = 1 AND ANNULLATA =0 
 -- CONTROLLO PER OGNI ANNO RENDICONTATO
DECLARE ANNI CURSOR FOR
( SELECT PXI.DESCRIZIONE FROM PAGAMENTI_RICHIESTI PR INNER JOIN 
				PIANO_INVESTIMENTI INV ON PR.ID_INVESTIMENTO= INV.ID_INVESTIMENTO AND PR.ID_DOMANDA_PAGAMENTO = @IdDomandaPagamento INNER JOIN 
				vPRIORITA_X_INVESTIMENTI PXI ON INV.ID_INVESTIMENTO = PXI.ID_INVESTIMENTO AND PXI.ID_PRIORITA = 228
	WHERE PXI.DESCRIZIONE <= CAST( DATEPART(YYYY,@DATA_MODIFICA) AS VARCHAR(4)) GROUP BY PXI.DESCRIZIONE)

OPEN ANNI
FETCH NEXT FROM ANNI 
INTO  @ANNO
WHILE @@FETCH_STATUS = 0
BEGIN
SET @COSTO_TOTALE =0
 SELECT  @COSTO_TOTALE=  SUM(COSTO_INVESTIMENTO+ISNULL(SPESE_GENERALI,0))   , 
@IMPORTO_RICHIESTO=SUM(IMPORTO_RICHIESTO)  ,
@IMPORTO_AMMESSO=SUM(ISNULL(IMPORTO_AMMESSO,0))  
			FROM PIANO_INVESTIMENTI INV INNER JOIN 
						vPRIORITA_X_INVESTIMENTI PXI ON INV.ID_INVESTIMENTO = PXI.ID_INVESTIMENTO AND PXI.ID_PRIORITA = 228 INNER JOIN 
						PAGAMENTI_RICHIESTI PR ON PR.ID_INVESTIMENTO= INV.ID_INVESTIMENTO
			WHERE ((@ID_VARIANTE IS NULL AND ID_VARIANTE IS NULL AND ID_PROGETTO =@IdProgetto AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL)OR
							(@ID_VARIANTE IS NOT NULL AND ID_VARIANTE=@ID_VARIANTE AND ISNULL(COD_VARIAZIONE,'X') != 'A')) AND	PXI.DESCRIZIONE = @ANNO

 IF(ISNULL(@IMPORTO_AMMESSO,0) < @COSTO_TOTALE/2)    SET @RESULT = 0    
FETCH NEXT FROM ANNI
INTO @ANNO 
END

CLOSE ANNI
DEALLOCATE ANNI 

SELECT @RESULT
 

END
