CREATE PROCEDURE [dbo].[calcoloStep413_3_S]
@IdProgetto int, 
@FASE_ISTRUTTORIA INT =0
AS
BEGIN
--Acquisto e posa in opera di arredi e attrezzature per l’esterno, nel limite massimo del 5% della spesa ammissibile, escluse le spese tecniche
-- ******* ESCLUSE SPESE TECNICHE ******* 

--declare @IdProgetto int, 
--@FASE_ISTRUTTORIA INT 

--set @IdProgetto = 834 
-- set @FASE_ISTRUTTORIA =0

DECLARE @result int , @COSTO_INVESTIMENTO DECIMAL(18,2),  @SPESE_ACQUISTI DECIMAL (18,2)
SET @result = 1

SELECT @COSTO_INVESTIMENTO=SUM(ISNULL(COSTO_INVESTIMENTO,0))  
 FROM vPIANO_INVESTIMENTI INV 
	WHERE ID_PROGETTO = @IdProgetto AND
	(
	(@FASE_ISTRUTTORIA=0 AND ID_INVESTIMENTO_ORIGINALE IS NULL AND ID_VARIANTE IS NULL) OR 
	(@FASE_ISTRUTTORIA=1 AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL)
	)
	AND INV.CODICE IN ('1','3')
  
SELECT @SPESE_ACQUISTI= SUM(ISNULL(COSTO_INVESTIMENTO,0)) 
 FROM VPIANO_INVESTIMENTI INV INNER JOIN DETTAGLIO_INVESTIMENTI D ON D.ID_DETTAGLIO_INVESTIMENTO = INV.ID_DETTAGLIO_INVESTIMENTO 
	WHERE ID_PROGETTO = @IdProgetto AND
	(
	(@FASE_ISTRUTTORIA=0 AND ID_INVESTIMENTO_ORIGINALE IS NULL AND ID_VARIANTE IS NULL)OR
	(@FASE_ISTRUTTORIA=1 AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL)
	)
	AND D.COD_DETTAGLIO IN ('e')

IF(   ISNULL(@SPESE_ACQUISTI,0) > @COSTO_INVESTIMENTO*5 /100) 
SET @result = 0

SELECT @result AS RESULT
END
