CREATE PROCEDURE [dbo].[calcoloRequisitoPagamento_PIT]
@ID_DOMANDA_PAGAMENTO int
AS
BEGIN

-- SALDO

--DECLARE @ID_DOMANDA_PAGAMENTO int
--SET @ID_DOMANDA_PAGAMENTO = 1
DECLARE @ID_PROGETTO INT, @RESULT INT,
		@REQ1 INT,@REQ2 INT,@REQ3 INT
					
SET @RESULT = 0 -- IMPONGO LO STEP NON VERIFICATO
-- PER IL CHECK DEVI VEDERE IL SELEZIONATO = 1 
-- PER IL TESTO INVECE VEDI CHE VAL_TESTO SIA != NULL 


SELECT @REQ1 = CASE WHEN COUNT(*)>= 1 THEN 1 ELSE 0 END FROM DOMANDA_PAGAMENTO_REQUISITI WHERE ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO AND ID_REQUISITO IN ('466','467') AND (SELEZIONATO = 1 OR VAL_TESTO IS NOT NULL)
SELECT @REQ2 = CASE WHEN COUNT(*)>= 1 THEN 1 ELSE 0 END FROM DOMANDA_PAGAMENTO_REQUISITI WHERE ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO AND ID_REQUISITO IN ('468','469') AND (SELEZIONATO = 1 OR VAL_TESTO IS NOT NULL)
SELECT @REQ3 = CASE WHEN COUNT(*)>= 1 THEN 1 ELSE 0 END FROM DOMANDA_PAGAMENTO_REQUISITI WHERE ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO AND ID_REQUISITO IN ('470','471') AND (SELEZIONATO = 1 OR VAL_TESTO IS NOT NULL)

IF (@REQ1+@REQ2+@REQ3 >= 3) SET @RESULT=1

SELECT @RESULT
END
