CREATE  PROCEDURE [dbo].[calcoloRequisitoPagamento133_2]
@ID_DOMANDA_PAGAMENTO int
AS
BEGIN
--	E` possibile presentare domanda di SAL (spesa rendicontata >= 50% di quella autorizzata per il progetto annuale)
--  Requisiti pagamento esito positivo =1 
-- anno =228
--	
--DECLARE @ID_DOMANDA_PAGAMENTO int
--SET @ID_DOMANDA_PAGAMENTO  =1224
	DECLARE @ID_PROGETTO INT, @COUNT INT, @ANNO VARCHAR(4), @DATA_MODIFICA DATETIME
					 
	DECLARE @RESULT INT

SET @RESULT = 1 -- IMPONGO LO STEP  VERIFICATO
  
SELECT @ID_PROGETTO =  ID_PROGETTO, @DATA_MODIFICA =DATA_MODIFICA 
FROM DOMANDA_DI_PAGAMENTO WHERE ID_DOMANDA_PAGAMENTO=@ID_DOMANDA_PAGAMENTO 	
 
SELECT @COUNT=  COUNT(*) FROM PAGAMENTI_RICHIESTI PR INNER JOIN 
				PIANO_INVESTIMENTI INV ON PR.ID_INVESTIMENTO= INV.ID_INVESTIMENTO AND PR.ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO INNER JOIN 
				vPRIORITA_X_INVESTIMENTI PXI ON INV.ID_INVESTIMENTO = PXI.ID_INVESTIMENTO AND PXI.ID_PRIORITA in ( 228,1130,1237)
WHERE PXI.DESCRIZIONE > CAST( DATEPART(YYYY,@DATA_MODIFICA) AS VARCHAR(4)) GROUP BY PXI.DESCRIZIONE
 
IF(@COUNT >0 ) SET @RESULT =0
 
 
SELECT @RESULT
END
