-- Controllo massimale di spesa su Beni strumentali (Dettaglio = 04 max 10% totale domanda)
-- UNICO BENEFICIARIO ASSAM CUAA= 01491360424
CREATE  PROCEDURE [dbo].[calcoloRequisitoPagamento214_2]
@ID_DOMANDA_PAGAMENTO int
AS
BEGIN
 
DECLARE 
		@RESULT INT, 
		@COSTO_BENI_STRUMENTALI DECIMAL(18,2),
		@COSTO_TOTALE DECIMAL (18,2), @IdProgetto INT


SET @RESULT =1 --PONGO LO STEP NN VERIFICATO
SET @IdProgetto = (SELECT ID_PROGETTO FROM DOMANDA_DI_PAGAMENTO WHERE ID_DOMANDA_PAGAMENTO =@ID_DOMANDA_PAGAMENTO   )
 
IF ((SELECT ID_IMPRESA FROM PROGETTO WHERE ID_PROGETTO = @IdProgetto) = 2447)
	BEGIN
	SET @COSTO_TOTALE =(SELECT SUM( ISNULL(IMPORTO_AMMESSO, PR.IMPORTO_RICHIESTO) )
			FROM PAGAMENTI_RICHIESTI AS PR
                  INNER JOIN PIANO_INVESTIMENTI AS PI ON PI.ID_INVESTIMENTO = PR.ID_INVESTIMENTO
			WHERE (PR.ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO) )

	SET @COSTO_BENI_STRUMENTALI = (SELECT SUM( ISNULL(IMPORTO_AMMESSO, PR.IMPORTO_RICHIESTO) )
									FROM PAGAMENTI_RICHIESTI AS PR 
										INNER JOIN PIANO_INVESTIMENTI INV ON INV.ID_INVESTIMENTO = PR.ID_INVESTIMENTO
										INNER JOIN DETTAGLIO_INVESTIMENTI D on D.ID_DETTAGLIO_INVESTIMENTO = INV.ID_DETTAGLIO_INVESTIMENTO and D.ID_CODIFICA_INVESTIMENTO =INV.ID_CODIFICA_INVESTIMENTO
									WHERE D.COD_DETTAGLIO ='04' AND ID_DOMANDA_PAGAMENTO =@ID_DOMANDA_PAGAMENTO )
									
    IF(ISNULL(@COSTO_BENI_STRUMENTALI,0) > (ISNULL(@COSTO_TOTALE,0)* 0.10) )SET @RESULT = 0 
END
ELSE SET @RESULT = 0 
SELECT @RESULT AS RESULT
END
