CREATE PROCEDURE [dbo].[calcoloStepVariante112_5]
@ID_VARIANTE int
AS
BEGIN

-- BANDO 112
-- Controllo valido per MANTENIMENTO PUNTEGGIO MINIMO PER LA GRADUATORIA:
 
--DECLARE @ID_VARIANTE INT
--SET  @ID_VARIANTE = 1094

DECLARE @IdSchedaValutazione int, @IdProgetto int, @PunteggioPriorita112A decimal(10,4) , @RESULT INT, @COUNT_PARZIALE INT,
					@ID_BANDO int ,  @ID_PROGETTO_ULTIMO_GRADUATORIA INT, @MINIMO_GRADUATORIA_NON_FIN  DECIMAL(18,4),@ID_PROGETTO_PRIMO_NON_FINANZIATO INT
DECLARE @MINIMO_GRADUATORIA DECIMAL(18,4), @PesoPriorita112A DECIMAL(18,4), @ValoreMAXPriorita112A DECIMAL(18,4), @ValorePriorita112A DECIMAL(18,4),
					@PesoPriorita112C DECIMAL(18,4), @ValoreMAXPriorita112C DECIMAL(18,4), @ValorePriorita112C DECIMAL(18,4),
					@PesoPriorita112D DECIMAL(18,4), @ValoreMAXPriorita112D DECIMAL(18,4), @ValorePriorita112D DECIMAL(18,4) 

SET @RESULT = 1 -- VERIFICATO
 
SET @IdProgetto= ( SELECT ID_PROGETTO FROM VARIANTI WHERE ID_VARIANTE= @ID_VARIANTE )
SET @ID_BANDO = (SELECT ID_BANDO FROM PROGETTO WHERE ID_PROGETTO= @IdProgetto)

SELECT TOP(1)@MINIMO_GRADUATORIA = PUNTEGGIO, @ID_PROGETTO_ULTIMO_GRADUATORIA =ID_PROGETTO FROM  GRADUATORIA_PROGETTI WHERE ID_BANDO = @ID_BANDO AND FINANZIABILITA ='S' ORDER BY PUNTEGGIO ASC 
SELECT TOP(1)@MINIMO_GRADUATORIA_NON_FIN =   PUNTEGGIO,@ID_PROGETTO_PRIMO_NON_FINANZIATO=ID_PROGETTO FROM GRADUATORIA_PROGETTI WHERE ID_BANDO = @ID_BANDO AND FINANZIABILITA ='N' ORDER BY PUNTEGGIO DESC 
SET @COUNT_PARZIALE = ( SELECT COUNT (*) CONTA  FROM  GRADUATORIA_PROGETTI WHERE ID_BANDO = @ID_BANDO AND FINANZIABILITA ='P'  )
 
SET @IdSchedaValutazione = (SELECT ID_SCHEDA_VALUTAZIONE FROM BANDO B INNER JOIN PROGETTO P ON (B.ID_BANDO = P.ID_BANDO) WHERE P.ID_PROGETTO = @IdProgetto)

 -- A  112 -  Qualità e livello degli obiettivi previsti dal business plan aziendale
SET @PesoPriorita112A= (SELECT ISNULL(PESO,0) FROM vSCHEDA_X_PRIORITA WHERE ID_PRIORITA = 98 AND ID_SCHEDA_VALUTAZIONE = @IdSchedaValutazione)
SET @ValoreMAXPriorita112A = (SELECT ISNULL(VALORE_MAX,0) FROM vSCHEDA_X_PRIORITA WHERE ID_PRIORITA = 98 AND ID_SCHEDA_VALUTAZIONE = @IdSchedaValutazione)

EXEC @ValorePriorita112A =  calcoloPrioritaVariante112_3  @ID_VARIANTE, @IdProgetto
SET @PunteggioPriorita112A = ( ((@ValorePriorita112A /100)*@PesoPriorita112A) /@ValoreMAXPriorita112A  ) 
 
-- B.	 112 - insediamento effettuato da giovane imprenditrice
DECLARE @PunteggioPriorita112B DECIMAL (18,6)
 DECLARE @PesoPrioritaB decimal(10,2)
DECLARE @ValoreMAXPrioritaB decimal(10,2)
DECLARE @ValorePrioritaB decimal(10,2)

SET @PesoPrioritaB = (SELECT ISNULL(PESO,0) FROM vSCHEDA_X_PRIORITA WHERE ID_PRIORITA = 95 AND ID_SCHEDA_VALUTAZIONE = @IdSchedaValutazione)
SET @ValoreMAXPrioritaB = (SELECT ISNULL(VALORE_MAX,100) FROM vSCHEDA_X_PRIORITA WHERE ID_PRIORITA = 95 AND ID_SCHEDA_VALUTAZIONE = @IdSchedaValutazione)
SET  @ValorePrioritaB = ( SELECT COUNT(ID_PRIORITA) AS PUNTEGGIO   FROM PRIORITA_X_PROGETTO PP   WHERE PP.ID_PROGETTO = @IdProgetto AND PP.ID_PRIORITA = 95)
set @PunteggioPriorita112B = (@ValorePrioritaB* @PesoPrioritaB)  


-- C.	 112 - insediamento effettuato nelle aree svantaggiate e montane
 DECLARE @PunteggioPriorita112C DECIMAL (18,6)
set @PunteggioPriorita112C = (SELECT PUNTEGGIO FROM  GRADUATORIA_PROGETTI_DETTAGLIO WHERE ID_PRIORITA = 96 AND ID_PROGETTO=@IdProgetto )

--  D  112 - insediamento con acquisizione in proprietà dell`azienda
DECLARE @PunteggioPriorita112D DECIMAL (18,6)
SET @PunteggioPriorita112D = (SELECT PUNTEGGIO FROM  GRADUATORIA_PROGETTI_DETTAGLIO WHERE ID_PRIORITA =  97 AND ID_PROGETTO=@IdProgetto )
 
-- SELECT @ID_PROGETTO_ULTIMO_GRADUATORIA,@COUNT_PARZIALE,@MINIMO_GRADUATORIA_NON_FIN,@MINIMO_GRADUATORIA
DECLARE @PUNTEGGIO_VARIANTE DECIMAL(18,4)
SET @PUNTEGGIO_VARIANTE = ( SELECT ( ISNULL(@PunteggioPriorita112A,0) +ISNULL(@PunteggioPriorita112B,0) +ISNULL(@PunteggioPriorita112C,0) +ISNULL(@PunteggioPriorita112D,0)  ) )
IF(@PUNTEGGIO_VARIANTE >@MINIMO_GRADUATORIA ) SET @RESULT = 1 -- MAGGIORE DELL'ULTIMO FINANZIABILE
ELSE IF(@MINIMO_GRADUATORIA_NON_FIN != @MINIMO_GRADUATORIA) -- NON ESISTE PARITA DI PUNTEGGIO QUINDI MAGGIORE DEL PRIMO NON FINANZIIABILE
	 BEGIN IF(@PUNTEGGIO_VARIANTE > @MINIMO_GRADUATORIA_NON_FIN) SET @RESULT=1 
			ELSE SET @RESULT=0 END
	 ELSE 
		BEGIN
			DECLARE @DATA_NASCITA_ULTIMO DATETIME,@DATA_NASCITA DATETIME
			IF( @PUNTEGGIO_VARIANTE = @MINIMO_GRADUATORIA  AND @ID_PROGETTO_ULTIMO_GRADUATORIA = @IdProgetto ) BEGIN SET @RESULT = 1 END
			ELSE BEGIN 
			     IF(@PUNTEGGIO_VARIANTE = @MINIMO_GRADUATORIA)BEGIN 
					SELECT @DATA_NASCITA_ULTIMO =DATA_NASCITA FROM vIMPRESA I INNER JOIN vPERSONE_X_IMPRESE PE ON PE.ID_PERSONE_X_IMPRESE =I.ID_RAPPRLEGALE_ULTIMO 
												 WHERE CUAA =(SELECT CUAA FROM PROGETTO WHERE ID_PROGETTO=@ID_PROGETTO_PRIMO_NON_FINANZIATO ) 
				   SELECT @DATA_NASCITA=DATA_NASCITA FROM vIMPRESA I INNER JOIN vPERSONE_X_IMPRESE PE ON PE.ID_PERSONE_X_IMPRESE =I.ID_RAPPRLEGALE_ULTIMO 
												 WHERE CUAA =(SELECT CUAA FROM PROGETTO WHERE ID_PROGETTO=@IdProgetto  )    
												 SELECT @DATA_NASCITA,@DATA_NASCITA_ULTIMO ,@ID_PROGETTO_ULTIMO_GRADUATORIA
					IF(@DATA_NASCITA > @DATA_NASCITA_ULTIMO) SET @RESULT = 1
					ELSE SET @RESULT = 0		 
			     END
			 END
		END
END
SELECT @RESULT AS RESULT
