CREATE PROCEDURE [dbo].[calcoloPriorita61_3]
(
	@IdProgetto int,
	@fase_istruttoria bit,
	@IdVariante int =NULL
)
AS
BEGIN
 DECLARE @PUNTEGGIO INT, @ULA_TOTALE_ANTE DECIMAL(18,2), @ULA_TOTALE_POST DECIMAL(18,2)
 
 SELECT @ULA_TOTALE_ANTE = SUM (ULA_TOTALE )
 FROM PRODUZIONE_STANDARD PS INNER JOIN PRODUZIONE_STANDARD_DETTAGLIO PSD ON PS.ID= PSD.ID_PS 
 WHERE ID_PROGETTO = @IdProgetto AND AMMESSO = @fase_istruttoria AND PREVISIONALE =0
 
 SELECT @ULA_TOTALE_POST = SUM (ULA_TOTALE )
 FROM PRODUZIONE_STANDARD PS INNER JOIN PRODUZIONE_STANDARD_DETTAGLIO PSD ON PS.ID= PSD.ID_PS 
 WHERE ID_PROGETTO = @IdProgetto AND AMMESSO = @fase_istruttoria AND PREVISIONALE =1
 
 IF(@ULA_TOTALE_POST =0) SET @PUNTEGGIO=0
 ELSE IF((@ULA_TOTALE_POST- @ULA_TOTALE_ANTE )>=1) SET @PUNTEGGIO=1
 ELSE IF((@ULA_TOTALE_POST- @ULA_TOTALE_ANTE )>=0.75) SET @PUNTEGGIO=0.8
 ELSE IF((@ULA_TOTALE_POST- @ULA_TOTALE_ANTE )>=0.5)  SET @PUNTEGGIO=0.5
 ELSE IF((@ULA_TOTALE_POST- @ULA_TOTALE_ANTE )>=0.25) SET @PUNTEGGIO=0.3
 ELSE SET @PUNTEGGIO =0
 
 SELECT @PUNTEGGIO 
 
END
