CREATE PROCEDURE [dbo].[calcoloRequisitoPagamento4136_MF]
@ID_DOMANDA_PAGAMENTO int
AS
BEGIN

-- GAL montefeltro
-- SAL
-- 207	Data inizio interventi programmati deve essere al massimo il 2012-12-21 00:00:00.000

--DECLARE @ID_DOMANDA_PAGAMENTO int
--SET @ID_DOMANDA_PAGAMENTO = 1
DECLARE @ID_PROGETTO INT, 
					@RESULT INT,
					@DATAINSERITA DATEtime
					
					
SELECT @DATAINSERITA = (select VAL_DATA from DOMANDA_PAGAMENTO_REQUISITI where ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO and ID_REQUISITO = 207)	


IF (@DATAINSERITA  <= '2012-12-21 00:00:00.000') 
SET @RESULT = 1 	
	 ELSE SET @RESULT = 0 	

SELECT @RESULT
END
