CREATE PROCEDURE [dbo].[calcoloRequisitoPagamento112_PLV] 
@ID_DOMANDA_PAGAMENTO int
AS
BEGIN
	SET NOCOUNT ON;
    	
--DECLARE @ID_DOMANDA_PAGAMENTO int
--SET @ID_DOMANDA_PAGAMENTO = 1202
    	
DECLARE @Count int, @AnnoPresentazione int, @Result int, @ID_Domanda INT , @ANNO_CORRENTE INT
SET @Result = 1
SET @ANNO_CORRENTE = YEAR (GETDATE())
SET @ID_Domanda = (SELECT ID_PROGETTO FROM DOMANDA_DI_PAGAMENTO WHERE ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO)
SET @AnnoPresentazione = (SELECT YEAR(data) FROM PROGETTO_STORICO ps  WHERE ID_PROGETTO = @ID_Domanda and COD_STATO ='L')

 
SET @Count = (SELECT COUNT(ID_PLV) FROM vPLV_AZIENDALE WHERE ID_PROGETTO = @ID_Domanda AND PREVISIONALE = 0 AND (ANNO > @AnnoPresentazione OR ANNO= @ANNO_CORRENTE)) 					
IF (isnull(@Count,0) = 0) SET @Result = 0 
SELECT @RESULT AS RESULT

END
