CREATE PROCEDURE [dbo].[calcoloStepPagamento_A_431_1]
@IdProgetto int,
@IdDomandaPagamento int =NULL
AS
BEGIN
 
--- massimale di intervento A
 
 
DECLARE @RESULT int,		 
		@CONTRIBUTO_RICHIESTO_PROGETTO_A DECIMAL (10,2),	 
	 	@CONTRIBUTO_ANTICIPO  DECIMAL(10,2)
	
SET @RESULT = 0  -- Impongo lo Step NON verificato
--------------------------------------------------------------------------------------------------------------

SET @CONTRIBUTO_RICHIESTO_PROGETTO_A = (SELECT     SUM(PI.CONTRIBUTO_RICHIESTO) AS CONTRIBUTO
									  FROM PIANO_INVESTIMENTI PI INNER JOIN
										PROGETTO ON PI.ID_PROGETTO = PROGETTO.ID_PROGETTO
									  WHERE     (PI.ID_PROGETTO = @IdProgetto) AND PI.ID_PROGRAMMAZIONE = 325 AND
									  (  (PI.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND PROGETTO.FLAG_DEFINITIVO =1 AND ID_VARIANTE IS NULL)))

SET @CONTRIBUTO_ANTICIPO = ( SELECT  ISNULL(CONTRIBUTO_AMMESSO,0) FROM ANTICIPI_RICHIESTI WHERE ID_DOMANDA_PAGAMENTO = @IdDomandaPagamento  )
 
 IF (  @CONTRIBUTO_ANTICIPO <= ( ISNULL(@CONTRIBUTO_RICHIESTO_PROGETTO_A ,0 ) * 0.2 ) )
				SET @RESULT = 1
 
 SELECT @RESULT
 END
