CREATE PROCEDURE [dbo].[calcoloStep112_R1]
@IdProgetto int
AS
-- 112 - ETA' DEL BENEFICIARIO <40 O PREDOMANDA DEFINITIVA E RICEVIBILE
/*
DECLARE @IdProgetto INT
SET @IdProgetto=857
*/
DECLARE @RESULT INT
SET @RESULT =0

SET @RESULT=(SELECT CASE WHEN DATEDIFF(day, DATEADD(year, 40, PERSONA_FISICA.DATA_NASCITA), PS.DATA) >= 0 THEN 0 ELSE 1 END
			 FROM PERSONA_FISICA 
				INNER JOIN PERSONE_X_IMPRESE ON PERSONA_FISICA.ID_PERSONA = PERSONE_X_IMPRESE.ID_PERSONA AND PERSONE_X_IMPRESE.COD_RUOLO = 'R'
				INNER JOIN IMPRESA ON PERSONE_X_IMPRESE.ID_IMPRESA = IMPRESA.ID_IMPRESA 
				INNER JOIN PROGETTO P ON IMPRESA.ID_IMPRESA=P.ID_IMPRESA 
				INNER JOIN PROGETTO_STORICO PS ON PS.ID_PROGETTO = P.ID_PROGETTO AND COD_STATO ='P'
			 WHERE P.ID_PROGETTO=@IdProgetto AND (PERSONE_X_IMPRESE.DATA_FINE IS NULL OR PERSONE_X_IMPRESE.DATA_FINE>PS.DATA  
				AND PERSONE_X_IMPRESE.DATA_INIZIO<=PS.DATA ))

--SELECT @RESULT

IF(@RESULT=0) BEGIN
	IF( SELECT COUNT(*) FROM PROGETTO WHERE FLAG_PREADESIONE = 1 AND FLAG_DEFINITIVO = 1 AND ID_BANDO = 55 and ID_IMPRESA IN (SELECT ID_IMPRESA FROM PROGETTO WHERE ID_PROGETTO=@IdProgetto) )>0 
	BEGIN
			IF ((SELECT COUNT(*) FROM VITER_PROGETTO WHERE ID_STEP=128 AND ID_PROGETTO=@IdProgetto AND ESITO_POSITIVO_ISTRUTTORE=1)>0) SET @RESULT =1
	END
END
SELECT @RESULT
