CREATE PROCEDURE [dbo].[calcoloPriorita61_2]
(
	@IdProgetto int,
	@fase_istruttoria bit,
	@IdVariante int =NULL
)
AS
BEGIN 
   /*DECLARE @IdProgetto INT , @fase_istruttoria BIT=0*/
   DECLARE @TIPO_AREA VARCHAR(2), @SUP_D INT, @SUP_C3 INT, 
			@SUP_ALTRA INT, @SUP_REGIONE INT, 
			@RESULT INT=0
 
   /* D) D.	Ubicazione in area montana dell’azienda di nuovo insediamento. */
   SELECT @SUP_D=P.D, @SUP_C3 =P.C3, @SUP_ALTRA = P.A + P.C1 + P.C2
   FROM (
	SELECT T.TIPO_AREA, UT.SUPERFICIE_ELIGIBILE 
	FROM vTERRITORIO T
		INNER JOIN PROGETTO P ON P.ID_FASCICOLO  = T.ID_FASCICOLO 
		INNER JOIN UTILIZZO_TERRA UT ON UT.ID_TERRITORIO = T.ID_TERRITORIO 
		INNER JOIN MACROUSI M ON M.COD_MACROUSO = UT.COD_MACROUSO AND M.CONCORRE_SAU_AZIENDALE =1
	WHERE ID_PROGETTO =@IdProgetto AND t.PROVINCIA IN ('MC','AN','PU','AP','FM')
		  AND (COD_TIPO_CONDUZIONE =1 OR (COD_TIPO_CONDUZIONE=2 AND T.DATA_FINE_CONDUZIONE > DATEADD(YEAR,8, DATEADD(DD,120,GETDATE()))))
	) AS T  PIVOT ( SUM(SUPERFICIE_ELIGIBILE) FOR TIPO_AREA IN ([D],[A],[C1],[C2],[C3])) AS P  
	

	
	IF(@SUP_D+@SUP_C3>@SUP_REGIONE *0.5)BEGIN 
		IF(@SUP_D>@SUP_C3)SET @RESULT=1
		ELSE SET @RESULT = 0.6
	END

 SELECT @RESULT 
END
