CREATE PROCEDURE [dbo].[calcoloStep221_2]
(
@IdProgetto int,
@FASE_ISTRUTTORIA INT =0
)
AS
BEGIN
	
-- Spese di sistemazione terreno <= 10% delle spese di impianto per tipologia di impianto
-- codifica investiomento TIPOLOGIA A (a), 
--- dettagli investimento per TIPOLOGIA A (a1 - a2 - a3)
--- specifica investimento per dettagli investimento per TIPOLOGIA A (4)

--- id_specifica_investimento di impianti 1796, 1797, 1798 tipologia A (bando id 233 - 1876, 1877, 1878)
--- Sistemazione terreno a --> 1799 (bando id 233 - 1879)

--- id_specifica_investimento di impianti 1800, 1801, 1802 tipologia B ( bando id 233 - 1880, 1881, 1882)
--- Sistemazione terreno B --> 1819 (bando id 233 - 1883)

--- id_specifica_investimento di impianti 1803, 1804, 1805 tipologia C ( bando id 233 - 1884, 1885, 1886)
--- Sistemazione terreno C --> 1820 (bando id 233 - 1887)


--DECLARE @IdProgetto INT = 8820,@FASE_ISTRUTTORIA INT =1

DECLARE @RESULT int, @RESULTA1 int,@RESULTA2 int,@RESULTA3 int, @ID_BANDO INT

SET @RESULT = 0 -- PONGO LO STEP IN STATO NON VERIFICATO
SET @RESULTA1 = 0 -- INIZIALIZZO LA VARIABILE		
SET @RESULTA2 = 0 -- INIZIALIZZO LA VARIABILE		
SET @RESULTA3 = 0 -- INIZIALIZZO LA VARIABILE		

DECLARE @COSTO_A1 DECIMAL(18,2), @COSTO_TOTALE_A1 DECIMAL(18,2),
		@COSTO_A2 DECIMAL(18,2), @COSTO_TOTALE_A2 DECIMAL(18,2),
		@COSTO_A3 DECIMAL(18,2), @COSTO_TOTALE_A3 DECIMAL(18,2)

SELECT  @ID_BANDO =  ID_BANDO FROM PROGETTO WHERE ID_PROGETTO = @IdProgetto

SELECT @COSTO_A1 =  ISNULL(SUM(COSTO_INVESTIMENTO),0) 
FROM PROGETTO P
	INNER JOIN VPIANO_INVESTIMENTI I ON (P.ID_PROGETTO=I.ID_PROGETTO)
 WHERE I.COD_TIPO_INVESTIMENTO = 1 AND ((I.ID_INVESTIMENTO_ORIGINALE IS NULL AND @FASE_ISTRUTTORIA=0 AND ID_VARIANTE IS NULL)OR(I.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND @FASE_ISTRUTTORIA =1 AND ID_VARIANTE IS NULL)) AND
		(P.ID_PROGETTO=@IdProgetto OR P.ID_PROG_INTEGRATO=@IdProgetto) AND
		-- inizio modifica riapertura
		I.COD_SPECIFICA in ('4') AND 
		i.ID_DETTAGLIO_INVESTIMENTO in 
		(SELECT ID_DETTAGLIO_INVESTIMENTO FROM CODIFICA_INVESTIMENTO CI INNER JOIN DETTAGLIO_INVESTIMENTI DI ON 
		(CI.ID_CODIFICA_INVESTIMENTO = DI.ID_CODIFICA_INVESTIMENTO) WHERE CI.ID_BANDO = @ID_BANDO AND DI.COD_DETTAGLIO = 'a1')
		-- fine modifica riapertura
	 
IF @COSTO_A1 >0 BEGIN 
	SELECT @COSTO_TOTALE_A1=  ISNULL(SUM(COSTO_INVESTIMENTO),1) 
	FROM PROGETTO P 
			INNER JOIN VPIANO_INVESTIMENTI I ON (P.ID_PROGETTO=I.ID_PROGETTO)
	WHERE I.COD_TIPO_INVESTIMENTO = 1 AND
	((I.ID_INVESTIMENTO_ORIGINALE IS NULL AND @FASE_ISTRUTTORIA=0 AND ID_VARIANTE IS NULL)OR(I.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND @FASE_ISTRUTTORIA =1 AND ID_VARIANTE IS NULL)) AND
	(P.ID_PROGETTO=@IdProgetto OR P.ID_PROG_INTEGRATO=@IdProgetto) AND
	-- inizio modifica riapertura
	I.COD_SPECIFICA in ('1','2','3') AND 
	i.ID_DETTAGLIO_INVESTIMENTO in (SELECT ID_DETTAGLIO_INVESTIMENTO FROM CODIFICA_INVESTIMENTO CI 
									INNER JOIN DETTAGLIO_INVESTIMENTI DI ON (CI.ID_CODIFICA_INVESTIMENTO = DI.ID_CODIFICA_INVESTIMENTO) 
									WHERE CI.ID_BANDO = @ID_BANDO AND DI.COD_DETTAGLIO = 'a1')
	-- fine modifica riapertura
	IF (@COSTO_TOTALE_A1 =0) SET @COSTO_TOTALE_A1 =1
	SET @RESULTA1 = @COSTO_A1 *100/@COSTO_TOTALE_A1
 
 END

--- TIPOLOGIA A2)
SELECT @COSTO_A2 =  ISNULL(SUM(COSTO_INVESTIMENTO),0) 
FROM PROGETTO P
	INNER JOIN VPIANO_INVESTIMENTI I ON (P.ID_PROGETTO=I.ID_PROGETTO)
 WHERE I.COD_TIPO_INVESTIMENTO = 1 AND ((I.ID_INVESTIMENTO_ORIGINALE IS NULL AND @FASE_ISTRUTTORIA=0 AND ID_VARIANTE IS NULL)OR(I.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND @FASE_ISTRUTTORIA =1 AND ID_VARIANTE IS NULL)) AND
		(P.ID_PROGETTO=@IdProgetto OR P.ID_PROG_INTEGRATO=@IdProgetto) AND
		-- inizio modifica riapertura
		I.COD_SPECIFICA in ('4') AND 
		i.ID_DETTAGLIO_INVESTIMENTO in 
		(SELECT ID_DETTAGLIO_INVESTIMENTO FROM CODIFICA_INVESTIMENTO CI INNER JOIN DETTAGLIO_INVESTIMENTI DI ON 
		(CI.ID_CODIFICA_INVESTIMENTO = DI.ID_CODIFICA_INVESTIMENTO) WHERE CI.ID_BANDO = @ID_BANDO AND DI.COD_DETTAGLIO = 'a2')
		-- fine modifica riapertura
	 
IF @COSTO_A2 >0 BEGIN 
	SELECT @COSTO_TOTALE_A2=  ISNULL(SUM(COSTO_INVESTIMENTO),1) 
	FROM PROGETTO P 
			INNER JOIN VPIANO_INVESTIMENTI I ON (P.ID_PROGETTO=I.ID_PROGETTO)
	WHERE I.COD_TIPO_INVESTIMENTO = 1 AND
	((I.ID_INVESTIMENTO_ORIGINALE IS NULL AND @FASE_ISTRUTTORIA=0 AND ID_VARIANTE IS NULL)OR(I.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND @FASE_ISTRUTTORIA =1 AND ID_VARIANTE IS NULL)) AND
	(P.ID_PROGETTO=@IdProgetto OR P.ID_PROG_INTEGRATO=@IdProgetto) AND
	-- inizio modifica riapertura
	I.COD_SPECIFICA in ('1','2','3') AND 
	i.ID_DETTAGLIO_INVESTIMENTO in (SELECT ID_DETTAGLIO_INVESTIMENTO FROM CODIFICA_INVESTIMENTO CI 
									INNER JOIN DETTAGLIO_INVESTIMENTI DI ON (CI.ID_CODIFICA_INVESTIMENTO = DI.ID_CODIFICA_INVESTIMENTO) 
									WHERE CI.ID_BANDO = @ID_BANDO AND DI.COD_DETTAGLIO = 'a2')
	-- fine modifica riapertura
	IF (@COSTO_TOTALE_A2 =0) SET @COSTO_TOTALE_A2 =1
	SET @RESULTA2 = @COSTO_A2 *100/@COSTO_TOTALE_A2
 
 END


 --- TIPOLOGIA A3)
SELECT @COSTO_A3 =  ISNULL(SUM(COSTO_INVESTIMENTO),0) 
FROM PROGETTO P
	INNER JOIN VPIANO_INVESTIMENTI I ON (P.ID_PROGETTO=I.ID_PROGETTO)
 WHERE I.COD_TIPO_INVESTIMENTO = 1 AND ((I.ID_INVESTIMENTO_ORIGINALE IS NULL AND @FASE_ISTRUTTORIA=0 AND ID_VARIANTE IS NULL)OR(I.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND @FASE_ISTRUTTORIA =1 AND ID_VARIANTE IS NULL)) AND
		(P.ID_PROGETTO=@IdProgetto OR P.ID_PROG_INTEGRATO=@IdProgetto) AND
		-- inizio modifica riapertura
		I.COD_SPECIFICA in ('4') AND 
		i.ID_DETTAGLIO_INVESTIMENTO in 
		(SELECT ID_DETTAGLIO_INVESTIMENTO FROM CODIFICA_INVESTIMENTO CI INNER JOIN DETTAGLIO_INVESTIMENTI DI ON 
		(CI.ID_CODIFICA_INVESTIMENTO = DI.ID_CODIFICA_INVESTIMENTO) WHERE CI.ID_BANDO = @ID_BANDO AND DI.COD_DETTAGLIO = 'a3')
		-- fine modifica riapertura
	 
IF @COSTO_A3 >0 BEGIN 
	SELECT @COSTO_TOTALE_A3=  ISNULL(SUM(COSTO_INVESTIMENTO),1) 
	FROM PROGETTO P 
			INNER JOIN VPIANO_INVESTIMENTI I ON (P.ID_PROGETTO=I.ID_PROGETTO)
	WHERE I.COD_TIPO_INVESTIMENTO = 1 AND
	((I.ID_INVESTIMENTO_ORIGINALE IS NULL AND @FASE_ISTRUTTORIA=0 AND ID_VARIANTE IS NULL)OR(I.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND @FASE_ISTRUTTORIA =1 AND ID_VARIANTE IS NULL)) AND
	(P.ID_PROGETTO=@IdProgetto OR P.ID_PROG_INTEGRATO=@IdProgetto) AND
	-- inizio modifica riapertura
	I.COD_SPECIFICA in ('1','2','3') AND 
	i.ID_DETTAGLIO_INVESTIMENTO in (SELECT ID_DETTAGLIO_INVESTIMENTO FROM CODIFICA_INVESTIMENTO CI 
									INNER JOIN DETTAGLIO_INVESTIMENTI DI ON (CI.ID_CODIFICA_INVESTIMENTO = DI.ID_CODIFICA_INVESTIMENTO) 
									WHERE CI.ID_BANDO = @ID_BANDO AND DI.COD_DETTAGLIO = 'a3')
	-- fine modifica riapertura
	IF (@COSTO_TOTALE_A3 =0) SET @COSTO_TOTALE_A3 =1
	SET @RESULTA3 = @COSTO_A3 *100/@COSTO_TOTALE_A3
 
 END
 
 IF(@RESULTA1 <= 10 AND @RESULTA2 <=10 AND @RESULTA3 <=10)
    SET @RESULT =1
ELSE  SET @RESULT=0

SELECT @RESULT
END
