CREATE PROCEDURE [dbo].[calcoloStepATS_3]
@IdProgetto int
AS
BEGIN


DECLARE @result int
DECLARE @TOTALE_INVESTIMENTO decimal(10,2)
 DECLARE @TOTALE_8 decimal(10,2)
 
SET @result =1 -- PONGO LO STEP VERIFICATO 

SET @TOTALE_INVESTIMENTO = ( SELECT     SUM(PIANO_INVESTIMENTI.COSTO_INVESTIMENTO) AS COSTO_INVESTIMENTO
							FROM  PROGETTO INNER JOIN PIANO_INVESTIMENTI ON PROGETTO.ID_PROGETTO = PIANO_INVESTIMENTI.ID_PROGETTO 
							WHERE  PROGETTO.ID_PROGETTO= @IdProgetto AND
							PIANO_INVESTIMENTI.COD_TIPO_INVESTIMENTO = 1  AND  ID_DETTAGLIO_INVESTIMENTO NOT IN (722,727,732,737,742)   
							AND ((PIANO_INVESTIMENTI.ID_INVESTIMENTO_ORIGINALE IS NULL AND PROGETTO.FLAG_DEFINITIVO = 0 ) 
								OR (PIANO_INVESTIMENTI.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND PROGETTO.FLAG_DEFINITIVO = 1 AND ID_VARIANTE IS NULL) )
 )

SET @TOTALE_8 = ( SELECT ISNULL(SUM(PI.COSTO_INVESTIMENTO),0)
				FROM PIANO_INVESTIMENTI PI INNER JOIN PROGETTO P ON (PI.ID_PROGETTO = P.ID_PROGETTO)
				WHERE (P.ID_PROGETTO=@IdProgetto OR P.ID_PROG_INTEGRATO=@IdProgetto) AND
				PI.COD_TIPO_INVESTIMENTO = 1 AND ((PI.ID_INVESTIMENTO_ORIGINALE IS NULL AND P.FLAG_DEFINITIVO = 0 ) 
								OR (PI.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND P.FLAG_DEFINITIVO = 1 AND ID_VARIANTE IS NULL) )
				AND PI.ID_SPECIFICA_INVESTIMENTO IN (347,408,417,426,435 ))
  
IF(@TOTALE_8 > @TOTALE_INVESTIMENTO*0.05 )SET @result =0 
 

SELECT @result AS RESULT

END
