CREATE PROCEDURE [dbo].[calcoloStep112_114_3]
@IdProgetto int, @FASE_ISTRUTTORIA INT = 0
AS
-- CONTROLLO SU ALLEGATI OBBLIGATORI  114
 
/*
DECLARE @IdProgetto INT
SET @IdProgetto=375
*/
DECLARE @RESULT INT =1
DECLARE @ID_PROG_INTEG_114 INT
SELECT DISTINCT @ID_PROG_INTEG_114 = p.ID_PROGETTO FROM PROGETTO P
INNER JOIN BANDO B ON B.ID_BANDO = P.ID_BANDO INNER JOIN ZPROGRAMMAZIONE ZP ON ZP.ID =B.ID_PROGRAMMAZIONE AND CODICE = '1.1.4.'
WHERE ID_PROG_INTEGRATO = @IdProgetto

IF @ID_PROG_INTEG_114 IS NULL SET @RESULT=2
ELSE BEGIN
	DECLARE @COSTO_114 DECIMAL(18,2), @C INT

	SELECT @COSTO_114 = SUM(COSTO_INVESTIMENTO) FROM PIANO_INVESTIMENTI I INNER JOIN PROGETTO P ON P.ID_PROGETTO = I.ID_PROGETTO   
	  WHERE P.ID_PROG_INTEGRATO = @IdProgetto AND  I.ID_PROGETTO = @ID_PROG_INTEG_114  AND ((@FASE_ISTRUTTORIA=0 AND ID_INVESTIMENTO_ORIGINALE IS NULL AND ID_VARIANTE  IS NULL)OR(@FASE_ISTRUTTORIA= 1 AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE  IS NULL)) 
		AND COSTO_INVESTIMENTO  >0
	IF(ISNULL(@COSTO_114,0) >0) BEGIN 
		 SELECT @C =COUNT(*) FROM PRIORITA_X_PROGETTO WHERE ID_PRIORITA = 245 AND ID_PROGETTO IN (@ID_PROG_INTEG_114, @IdProgetto )  
	IF(ISNULL(@C,0) =0 ) SET @RESULT =0
	END 
END
SELECT @RESULT
