-- 
CREATE PROCEDURE [dbo].[calcoloStepVariante133_3]
@ID_VARIANTE int
AS
BEGIN
-- COMPLETEZZA DEL PIANO INVESTIMENTI DI : NUMERO INIZIATIVA E SOGGETTO ATTUATORE

DECLARE @COUNT_SOGG INT, @COUNT_INIZIATIVA INT, @RESULT INT
-- 398	Soggetto attuatore dell`iniziativa
-- 858	Codice univoco d’iniziativa PER LE MICRO

--declare @IdProgetto int,@FASE_ISTRUTTORIA INT
--set @IdProgetto =7343

SET @RESULT =1 --PONGO LO STEP  VERIFICATO

SET @COUNT_SOGG=(
		SELECT ((SELECT   COUNT(*) AS A  FROM  PIANO_INVESTIMENTI PI  
  		WHERE ID_VARIANTE=@ID_VARIANTE AND cod_tipo_investimento = 1)
		 - (SELECT COUNT(*) FROM PIANO_INVESTIMENTI AS PI 
							INNER JOIN PRIORITA_X_INVESTIMENTI ON PI.ID_INVESTIMENTO = PRIORITA_X_INVESTIMENTI.ID_INVESTIMENTO 
			WHERE (PI.ID_VARIANTE = @ID_VARIANTE ) AND COD_TIPO_INVESTIMENTO = 1 AND ID_PRIORITA = 398)))
			
SET @COUNT_INIZIATIVA=( 
		SELECT((SELECT COUNT(*) AS A  FROM  PIANO_INVESTIMENTI PI
		WHERE ID_VARIANTE=@ID_VARIANTE AND cod_tipo_investimento = 1) 
		- ( SELECT COUNT(*) FROM PIANO_INVESTIMENTI AS PI 
				INNER JOIN PRIORITA_X_INVESTIMENTI ON PI.ID_INVESTIMENTO = PRIORITA_X_INVESTIMENTI.ID_INVESTIMENTO 
			WHERE (ID_VARIANTE = @ID_VARIANTE ) AND COD_TIPO_INVESTIMENTO = 1 AND ID_PRIORITA IN(399,858))))

IF(@COUNT_SOGG >0 OR @COUNT_INIZIATIVA >0 ) SET @RESULT =0
ELSE BEGIN
	DECLARE @C_SOGG_INIZ INT,@NUM_INI INT
	
	SET @NUM_INI =(SELECT COUNT (DISTINCT VALORE )AS INIZIATIVE
					FROM PIANO_INVESTIMENTI AS PI 
						INNER JOIN PRIORITA_X_INVESTIMENTI AS PXI ON PI.ID_INVESTIMENTO = PXI.ID_INVESTIMENTO AND PXI.ID_PRIORITA IN( 399,858)
					WHERE (PI.ID_VARIANTE = @ID_VARIANTE) AND COD_TIPO_INVESTIMENTO =1)
	 
	SET @C_SOGG_INIZ = (SELECT COUNT(*) FROM 
						(SELECT DISTINCT ISNULL( SOGG.ID_VALORE,0) ID_VALORE ,PXI.VALORE 
						 FROM PIANO_INVESTIMENTI AS PI 
							INNER JOIN PRIORITA_X_INVESTIMENTI AS PXI ON PI.ID_INVESTIMENTO = PXI.ID_INVESTIMENTO AND PXI.ID_PRIORITA IN( 399,858)
							LEFT JOIN ((SELECT I.ID_INVESTIMENTO, I.ID_PROGETTO, PXI.ID_PRIORITA,   PXI.ID_VALORE, PXI.SCELTO, PXI.VALORE 
										FROM PIANO_INVESTIMENTI I INNER JOIN PRIORITA_X_INVESTIMENTI PXI ON I.ID_INVESTIMENTO = PXI.ID_INVESTIMENTO AND ID_PRIORITA = 398
										WHERE ID_VARIANTE = @ID_VARIANTE AND COD_TIPO_INVESTIMENTO =1 ))  AS SOGG ON SOGG.ID_INVESTIMENTO= PI.ID_INVESTIMENTO
						 WHERE (PI.ID_VARIANTE = @ID_VARIANTE )AND PI.COD_TIPO_INVESTIMENTO =1 ) AS SOGG)
						
	IF(@NUM_INI!=@C_SOGG_INIZ) SET @RESULT =0
END
SELECT @RESULT AS RESULT
END
