CREATE PROCEDURE [dbo].[calcoloPriorita413_2_S]
(
@IdProgetto int,
@FASE_ISTRUTTORIA bit = 0,
@IdVariante INT
)
AS
BEGIN

--Spese relative all’utilizzo di tecnologie di informazione e comunicazione di importo totale pari ad almeno il 2% sul totale
--Punteggio 1 

DECLARE @result int , @COSTO_INVESTIMENTO DECIMAL(18,2), 
@SPESE_TIC DECIMAL (18,2)
SET @result = 1

SELECT @COSTO_INVESTIMENTO=SUM(ISNULL(COSTO_INVESTIMENTO,0)) FROM PIANO_INVESTIMENTI I 
WHERE ID_PROGETTO = @IdProgetto AND id_codifica_investimento in (1091,1093) AND( (@FASE_ISTRUTTORIA=0 AND ID_INVESTIMENTO_ORIGINALE IS NULL AND ID_VARIANTE IS NULL) OR
(@fase_istruttoria=1 AND (I.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE  IS NULL AND @IdVariante IS NULL) 
	OR	(ID_VARIANTE  = @IdVariante AND @IdVariante IS NOT NULL AND ISNULL(COD_VARIAZIONE, 'X' ) != 'A')))
  
SELECT @SPESE_TIC=SUM(ISNULL(COSTO_INVESTIMENTO,0)) 
FROM VPIANO_INVESTIMENTI I INNER JOIN DETTAGLIO_INVESTIMENTI D ON D.ID_DETTAGLIO_INVESTIMENTO = I.ID_DETTAGLIO_INVESTIMENTO 
WHERE ID_PROGETTO = @IdProgetto
		AND D.COD_DETTAGLIO IN ('d')
		AND ((@fase_istruttoria=0 AND I.ID_INVESTIMENTO_ORIGINALE IS NULL AND ID_VARIANTE IS NULL )
				OR (@fase_istruttoria=1 AND (I.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE  IS NULL AND @IdVariante IS NULL) 
				OR (ID_VARIANTE  = @IdVariante AND @IdVariante IS NOT NULL AND ISNULL(COD_VARIAZIONE, 'X' ) != 'A' )))
 
 IF(ISNULL(@SPESE_TIC,0) < @COSTO_INVESTIMENTO*2 /100) 
SET @result = 0

SELECT @result AS RESULT
END
