CREATE  PROCEDURE [dbo].[calcoloStepPagamento_Antimafia]
@IdProgetto int,
@IdDomandaPagamento int =NULL
AS
BEGIN

--Certificato Antimafia 

--DECLARE @IdProgetto int,@IdDomandaPagamento int
--SET @IdProgetto =4839
--SET @IdDomandaPagamento=1213

DECLARE	@RESULT INT, @ID_IMPRESA INT,
		@ESENZIONE_CERTIFICAZIONE bit, @ESITO_CERTIFICATO_PREFETTIZIO bit,
		@DATA_CERTIFICAZIONE_ANTIMAFIA DATETIME, @DATA_FINE_ISTRUTTORIA DATETIME 

SET @RESULT = 0 -- IMPONGO LO STEP NON VERIFICATO	
SELECT @ID_IMPRESA = ID_IMPRESA FROM IMPRESA WHERE CUAA = (SELECT CUAA FROM PROGETTO WHERE ID_PROGETTO = @IdProgetto)
SELECT @DATA_FINE_ISTRUTTORIA = ISNULL(DATA_APPROVAZIONE,GETDATE())  FROM DOMANDA_DI_PAGAMENTO WHERE ID_DOMANDA_PAGAMENTO = @IdDomandaPagamento  

EXEC @RESULT = SpControlloAntimafia @ID_IMPRESA, @DATA_FINE_ISTRUTTORIA
SELECT @RESULT

END
