CREATE  PROCEDURE [dbo].[calcoloStepVariante111_22]
@ID_VARIANTE INT
AS
-- 111 - Verifica massimali da intervento su corsi di formazione   BANDO 2014 - SICUREZZA
 
DECLARE @Result INT ,@COSTO DECIMAL(18,2),@COD_CODIFICA VARCHAR(2)
SET @Result = 1
 
 DECLARE CORSO_SEDE CURSOR FOR
  ( 
		SELECT COSTO_INVESTIMENTO AS COSTO , C.CODICE 
		FROM PIANO_INVESTIMENTI PI 
			 INNER JOIN CODIFICA_INVESTIMENTO C ON C.ID_CODIFICA_INVESTIMENTO =PI.ID_CODIFICA_INVESTIMENTO  
		WHERE ID_VARIANTE =@ID_VARIANTE AND ISNULL(COD_VARIAZIONE,0) != 'A'
			 
   ) 
 
OPEN CORSO_SEDE
FETCH NEXT FROM CORSO_SEDE 
INTO @COSTO, @COD_CODIFICA 
WHILE @@FETCH_STATUS = 0
	BEGIN
	
	IF(@COD_CODIFICA IN ('63', '69', '70','77','94','99','B1','B4') AND (@COSTO>200 OR @COSTO < 80)) SET @Result =0
	ELSE IF (@COD_CODIFICA IN ('62','72','76','A1') AND (@COSTO>325 OR @COSTO < 130))SET @Result =0
	ELSE IF (@COD_CODIFICA IN ('64') AND (@COSTO>750 OR @COSTO < 300))SET @Result =0
	ELSE IF (@COD_CODIFICA IN ('65','74','79','86','98', 'B2','B7') AND (@COSTO>300 OR @COSTO < 120))SET @Result =0
	ELSE IF (@COD_CODIFICA IN ('67','78','84','87','92','97','B5') AND (@COSTO>775 OR @COSTO < 310))SET @Result =0
    ELSE IF (@COD_CODIFICA IN ('71') AND (@COSTO>737 OR @COSTO < 295))SET @Result =0
	ELSE IF (@COD_CODIFICA IN ('80','85') AND (@COSTO>450 OR @COSTO < 180))SET @Result =0
	ELSE IF (@COD_CODIFICA IN ('81','95','B3','B8') AND (@COSTO>400 OR @COSTO < 160))SET @Result =0
	ELSE IF (@COD_CODIFICA IN ('82') AND (@COSTO>468 OR @COSTO < 187))SET @Result =0
	ELSE IF (@COD_CODIFICA IN ('83') AND (@COSTO>769 OR @COSTO < 307))SET @Result =0
	ELSE IF (@COD_CODIFICA IN ('88') AND (@COSTO>225 OR @COSTO < 90))SET @Result  =0
	ELSE IF (@COD_CODIFICA IN ('89') AND (@COSTO>292 OR @COSTO < 117))SET @Result =0
	ELSE IF (@COD_CODIFICA IN ('90') AND (@COSTO>360 OR @COSTO < 144))SET @Result =0
	ELSE IF (@COD_CODIFICA IN ('93','B6', '68') AND (@COSTO>250 OR @COSTO < 100))SET @Result =0
	ELSE IF (@COD_CODIFICA IN ('91') AND (@COSTO>270 OR @COSTO < 108))SET @Result =0
	ELSE IF (@COD_CODIFICA IN ('96') AND (@COSTO>247 OR @COSTO < 99))SET @Result  =0
	ELSE IF (@COD_CODIFICA IN ('A3') AND (@COSTO>324 OR @COSTO < 129))SET @Result =0
	ELSE IF (@COD_CODIFICA IN ('A2') AND (@COSTO>597 OR @COSTO < 239))SET @Result =0
	ELSE IF (@COD_CODIFICA IN ('66','75','73','61') AND (@COSTO>125 OR @COSTO < 50))SET @Result =0
	
	IF(@Result =0 ) BREAK
	
	FETCH NEXT FROM CORSO_SEDE
	INTO @COSTO , @COD_CODIFICA 
END

CLOSE CORSO_SEDE
DEALLOCATE CORSO_SEDE

 
SELECT @Result AS RESULT
