CREATE PROCEDURE [dbo].[calcoloStepPagamentoGAL_ANT]
@IdProgetto int,
@IdDomandaPagamento int = NULL
AS
BEGIN
 -- E’ stata confermata la convalida della polizza fidejussoria - ANTICIPO
 
DECLARE @FORMA_GIURIDICA varchar(6), @CONF_CONV_POLIZZA INT,@CONF_CONV_POLIZZA_PUB INT, @RESULT INT

SET @RESULT = 0  -- IMPOSTO STEP NON VERIFICATO

SELECT @FORMA_GIURIDICA = vp.COD_FORMA_GIURIDICA
FROM PROGETTO P 
--	INNER JOIN vIMPRESA vP on vp.CUAA = p.CUAA  --  vecchia versione prima dell'aggiornamento
	INNER JOIN vIMPRESA vP on vp.id_impresa = p.ID_IMPRESA
WHERE ID_PROGETTO = @IdProgetto -- 1.* SONO PRIVATI -- 2* SONO PUBBLICI

IF (ISNULL(@FORMA_GIURIDICA,0) LIKE '1.%') -- SE PRIVATI
 BEGIN
-- L'ISTRUTTORE DEVE INSERIRE QUESTI DATI
	SELECT @CONF_CONV_POLIZZA = COUNT(*) 
	FROM DOMANDA_DI_PAGAMENTO DD 
		inner JOIN FIDEJUSSIONI F on F.ID_FIDEJUSSIONE = DD.ID_FIDEJUSSIONE  
	WHERE ID_DOMANDA_PAGAMENTO = @IdDomandaPagamento AND F.DATA_RICHIESTA_VALIDITA IS NOT NULL AND F.DATA_RICEVIMENTO_VALIDITA  IS NOT NULL 
			AND F.PROTOCOLLO_FAX_VALIDITA IS NOT NULL AND F.DATA_DECORRENZA_GARANZIA IS NOT NULL
	IF(ISNULL(@CONF_CONV_POLIZZA,0) = 1) SET @RESULT = 1
 END

ELSE IF (ISNULL(@FORMA_GIURIDICA,0) LIKE '2.%') -- SE PUBBLICO
 BEGIN
-- L'ISTRUTTORE DEVE INSERIRE QUESTI DATI SE NON LI HA INSERITI L'ENTE
	SELECT @CONF_CONV_POLIZZA_PUB = COUNT(*) 
	FROM DOMANDA_DI_PAGAMENTO DD 
		inner JOIN FIDEJUSSIONI F on F.ID_FIDEJUSSIONE = DD.ID_FIDEJUSSIONE  
	WHERE ID_DOMANDA_PAGAMENTO = @IdDomandaPagamento AND F.UFFICIO_APPROVAZIONE IS NOT NULL AND F.NUM_DECRETO_APPROVAZIONE IS NOT NULL 
			AND F.DATA_DECRETO_APPROVAZIONE IS NOT NULL
	IF(ISNULL(@CONF_CONV_POLIZZA_PUB,0) = 1) SET @RESULT = 1
 END
		 
SELECT @RESULT
END
