CREATE PROCEDURE [dbo].[calcoloStep221_5]
(
@IdProgetto int,
@FASE_ISTRUTTORIA INT =0
)
AS
BEGIN
DECLARE @CUAA VARCHAR(16),@DATA_VALIDITA DATETIME,
		@ID_IMPRESA INT, @RESULT INT, @SUPERFICIE_COLTURA INT

SET @RESULT = 0-- PONGO LO STEP IN STATO VERIFICATO
SELECT @CUAA=IMP.CUAA, @ID_IMPRESA= IMP.ID_IMPRESA , @DATA_VALIDITA= PS.DATA
FROM PROGETTO P 
	INNER JOIN vIMPRESA IMP ON IMP.ID_IMPRESA =P.ID_IMPRESA 
	 INNER JOIN PROGETTO_STORICO PS ON PS.ID_PROGETTO = P.ID_PROGETTO AND  PS.COD_STATO IN ('P')
WHERE P.ID_PROGETTO = @IdProgetto 

sELECT @SUPERFICIE_COLTURA = SUM(PC.SUPERFICIE_COLTURA) 
FROM PIANO_COLTURALE_DETTAGLIO PC 
	INNER JOIN (SELECT MAX (id_rif) ID_RIF, ID_IMPRESA FROM PIANO_COLTURALE_STORICO WHERE ID_IMPRESA=@ID_IMPRESA GROUP BY ID_IMPRESA ) AS PIANO_STO ON PIANO_STO.ID_RIF= PC.ID_RIF  
WHERE PC.SUPERFICIE_COLTURA >0 AND (PC.DATA_FINE_VALIDITA IS NULL  OR PC.DATA_FINE_VALIDITA >@DATA_VALIDITA) 
 
IF(@SUPERFICIE_COLTURA > 5000) SET @RESULT= 1	

SELECT @RESULT
END
