--- COSTO totale progetto <= 25.000 in presenza di un solo intervento (codifica)
--- COSTO totale progetto <= 40.000 in presenza di un più intervento (codifica)
--- GAL FLAMINIA CESANO

CREATE PROCEDURE [dbo].[calcoloStep4132c_FC]
@IdProgetto int, 
@FASE_ISTRUTTORIA INT = 0
AS
BEGIN

DECLARE @result int, @CONTAC1 int, @CONTAC2 int, @CONTAC3 int, @CONTA_ARREDI int, @COSTO_PROGETTO int
SET @result = 0

SELECT @CONTAC1 = (SELECT (ISNULL(COUNT(DISTINCT(VPI.CODICE)),0)) AS Conta_Investimenti_C1 FROM PROGETTO P INNER JOIN
			vPIANO_INVESTIMENTI VPI ON P.ID_PROGETTO=VPI.ID_PROGETTO WHERE
			VPI.COD_TIPO_INVESTIMENTO = 1 AND
			((VPI.ID_INVESTIMENTO_ORIGINALE IS NULL AND @FASE_ISTRUTTORIA=0 AND ID_VARIANTE IS NULL)OR
			(VPI.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND @FASE_ISTRUTTORIA =1 AND ID_VARIANTE IS NULL)) AND					
			VPI.CODICE = 'C1' AND
			P.ID_PROGETTO=@IdProgetto)

SELECT @CONTAC2 = (SELECT (ISNULL(COUNT(DISTINCT(VPI.CODICE)),0)) AS Conta_Investimenti_C2 FROM PROGETTO P INNER JOIN
			vPIANO_INVESTIMENTI VPI ON P.ID_PROGETTO=VPI.ID_PROGETTO WHERE
			VPI.COD_TIPO_INVESTIMENTO = 1 AND
			((VPI.ID_INVESTIMENTO_ORIGINALE IS NULL AND @FASE_ISTRUTTORIA=0 AND ID_VARIANTE IS NULL)OR
			(VPI.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND @FASE_ISTRUTTORIA =1 AND ID_VARIANTE IS NULL)) AND
			VPI.CODICE = 'C2' AND
			P.ID_PROGETTO=@IdProgetto)
			
SELECT @CONTAC3 = (SELECT (ISNULL(COUNT(DISTINCT(VPI.CODICE)),0)) AS Conta_Investimenti_C3 FROM PROGETTO P INNER JOIN
			vPIANO_INVESTIMENTI VPI ON P.ID_PROGETTO=VPI.ID_PROGETTO WHERE
			VPI.COD_TIPO_INVESTIMENTO = 1 AND
			((VPI.ID_INVESTIMENTO_ORIGINALE IS NULL AND @FASE_ISTRUTTORIA=0 AND ID_VARIANTE IS NULL)OR
			(VPI.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND @FASE_ISTRUTTORIA =1 AND ID_VARIANTE IS NULL)) AND
			VPI.CODICE = 'C3' AND
			P.ID_PROGETTO=@IdProgetto)
			
SELECT @CONTA_ARREDI = (SELECT(ISNULL(COUNT(DISTINCT(VPI.CODICE)),0)) AS Conta_ARREDI FROM PROGETTO P INNER JOIN
			vPIANO_INVESTIMENTI VPI ON P.ID_PROGETTO=VPI.ID_PROGETTO WHERE
			VPI.COD_TIPO_INVESTIMENTO = 1 AND
			((VPI.ID_INVESTIMENTO_ORIGINALE IS NULL AND @FASE_ISTRUTTORIA=0 AND ID_VARIANTE IS NULL)OR
			(VPI.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND @FASE_ISTRUTTORIA =1 AND ID_VARIANTE IS NULL)) AND
			VPI.CODICE = '2' AND
			P.ID_PROGETTO=@IdProgetto)
			
SELECT @COSTO_PROGETTO = (SELECT (ISNULL(SUM(COSTO_INVESTIMENTO),0) + ISNULL(SUM(SPESE_GENERALI),0)) AS Totale_Investimenti FROM PROGETTO P INNER JOIN
			vPIANO_INVESTIMENTI VPI ON P.ID_PROGETTO=VPI.ID_PROGETTO WHERE
			VPI.COD_TIPO_INVESTIMENTO = 1 AND
			((VPI.ID_INVESTIMENTO_ORIGINALE IS NULL AND @FASE_ISTRUTTORIA=0 AND ID_VARIANTE IS NULL)OR
			(VPI.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND @FASE_ISTRUTTORIA =1 AND ID_VARIANTE IS NULL)) AND
			P.ID_PROGETTO=@IdProgetto)
			
IF (
(((((@CONTAC1 + @CONTAC3) >= 1) and ((@CONTAC2 + @CONTA_ARREDI >= 1))) or (((@CONTAC1 + @CONTAC3) > 1) and ((@CONTAC2 + @CONTA_ARREDI = 0)))) and (@COSTO_PROGETTO <= 40000))
or
(((((@CONTAC1 + @CONTAC3) = 1) and ((@CONTAC2 + @CONTA_ARREDI = 0))) or (((@CONTAC1 + @CONTAC3) = 0) and (@CONTAC2 + @CONTA_ARREDI >= 1))) and (@COSTO_PROGETTO <= 25000))
) 
SET @result = 1

SELECT @result AS RESULT
END
