CREATE PROCEDURE [dbo].[calcoloStep123_5]
@IdProgetto int
AS
BEGIN

-- 123 PABS - Controllo Materia Prima La QUANTITA_DA_BACINO_BIETICOLO almeno il 50% della QUANTITA_EXTRA.

DECLARE @Result int,
		@DATA  datetime , 
		@QUANTITA_DA_BACINO_BIETICOLO decimal(10,2) , 
		@QUANTITA_EXTRA decimal(10,2)

SET @Result = 1 -- Impongo lo Step  verificato

 SELECT @DATA =DATA
 FROM PROGETTO P  INNER JOIN PROGETTO_STORICO S ON  P.ID_PROGETTO = S.ID_PROGETTO 
 where P.ID_PROGETTO = @IdProgetto AND COD_STATO IN ('P','L')
 ORDER BY S.ID DESC 


DECLARE MATERIA_PRIMA CURSOR  FOR 
select   isnull( SUM ( QUANTITA_EXTRA) ,0) ,   isnull( SUM ( QUANTITA_DA_BACINO_BIETICOLO) ,0)
from PRODOTTI_VENDITE where MATERIA_PRIMA=1 and Id_Progetto =@IdProgetto and anno >= year(@DATA ) group by anno 


OPEN MATERIA_PRIMA
FETCH NEXT FROM MATERIA_PRIMA 
INTO  @QUANTITA_EXTRA , @QUANTITA_DA_BACINO_BIETICOLO
WHILE @@FETCH_STATUS = 0
BEGIN
	IF( @QUANTITA_DA_BACINO_BIETICOLO <  @QUANTITA_EXTRA  * 0.5 )
	BEGIN 
		Set @Result =0
		
	END
FETCH NEXT FROM MATERIA_PRIMA 
INTO  @QUANTITA_EXTRA , @QUANTITA_DA_BACINO_BIETICOLO
END

CLOSE MATERIA_PRIMA
DEALLOCATE MATERIA_PRIMA 

 
SELECT @Result AS RESULT
 
END
