CREATE PROCEDURE [dbo].[calcoloStep4132_C_PI]
(
@IdProgetto int,
@FASE_ISTRUTTORIA INT =0
)
AS
BEGIN
DECLARE @RESULT int,
		@CODIFICAC1 int,
		@CODIFICAC2 int,
		@DICHIARAZIONIC1 int,
		@DICHIARAZIONIC2 int
		
--- gal Piceno
-- Verifica rilascio dichairazioni in base a codifica investimenti

SET @result = 0 -- INIZIALIZZO A FALSE

SET @DICHIARAZIONIC1 =(SELECT COUNT(*) FROM DICHIARAZIONI_X_PROGETTO WHERE ID_PROGETTO=@IdProgetto AND ID_DICHIARAZIONE IN (798))

SET @DICHIARAZIONIC2 =(SELECT COUNT(*) FROM DICHIARAZIONI_X_PROGETTO WHERE ID_PROGETTO=@IdProgetto AND ID_DICHIARAZIONE IN (795,801))

SET @CODIFICAC1 = (SELECT ISNULL(COUNT(*),0)  as conta FROM  VPIANO_INVESTIMENTI WHERE ID_INVESTIMENTO_ORIGINALE IS NULL AND  CODICE in ('C1') AND  ID_PROGETTO = @IdProgetto)
SET @CODIFICAC2 = (SELECT ISNULL(COUNT(*),0)  as conta FROM  VPIANO_INVESTIMENTI WHERE ID_INVESTIMENTO_ORIGINALE IS NULL AND  CODICE in ('C2') AND  ID_PROGETTO = @IdProgetto)

IF((((ISNULL(@DICHIARAZIONIC1,0) = 0) AND (ISNULL(@CODIFICAC1,0) = 0)) OR ((ISNULL(@DICHIARAZIONIC1,0) > 0) AND (ISNULL(@CODIFICAC1,0) > 0))) AND
   (((ISNULL(@DICHIARAZIONIC2,0) = 0) AND (ISNULL(@CODIFICAC2,0) = 0)) OR ((ISNULL(@DICHIARAZIONIC2,0) > 0) AND (ISNULL(@CODIFICAC2,0) > 0))))                  
	SET @Result=1
  ELSE 
	SET @Result=0

SELECT @result AS RESULT

END
