CREATE PROCEDURE [dbo].[calcoloPrioritaM41_1]
@IdProgetto int , 
@fase_istruttoria bit =0,
@IdVariante INT = NULL
AS
BEGIN

/*Priorita B: M4.1  -  Realizzazione di investimenti relativi a tipologie indicate come prioritarie dal PSR per i diversi settori produttivi */

DECLARE @COSTO_INVESTIMENTI DECIMAL (18,2),@COSTO_INVESTIMENTI_PRIORITARI DECIMAL (18,2),
		@ValorePrioritaB decimal(10,4) 
		
  SELECT @COSTO_INVESTIMENTI = SUM(COSTO_INVESTIMENTO)FROM PIANO_INVESTIMENTI INV  
  WHERE ID_PROGETTO = @IdProgetto AND ((@fase_istruttoria =0 AND ID_VARIANTE IS NULL AND ID_INVESTIMENTO_ORIGINALE IS NULL)OR
		(@fase_istruttoria =1 AND (@IdVariante IS NULL AND ID_VARIANTE IS NULL AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL)
								OR(@IdVariante IS NOT NULL AND ID_VARIANTE =@IdVariante AND ISNULL(INV.COD_VARIAZIONE,'X') !='A' )))
  
  SELECT @COSTO_INVESTIMENTI_PRIORITARI = SUM(COSTO_INVESTIMENTO)FROM PIANO_INVESTIMENTI INV  
  WHERE ID_PROGETTO = @IdProgetto AND ID_PRIORITA_SETTORIALE IS NOT NULL 
		AND ((@fase_istruttoria =0 AND ID_VARIANTE IS NULL AND ID_INVESTIMENTO_ORIGINALE IS NULL)OR
			 (@fase_istruttoria =1 AND (@IdVariante IS NULL AND ID_VARIANTE IS NULL AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL)
								  OR(@IdVariante IS NOT NULL AND ID_VARIANTE =@IdVariante AND ISNULL(INV.COD_VARIAZIONE,'X') !='A' )))
		
  
  IF (@COSTO_INVESTIMENTI_PRIORITARI = 0 )SET @ValorePrioritaB = 0 
  ELSE IF (((@COSTO_INVESTIMENTI_PRIORITARI/@COSTO_INVESTIMENTI)*100) >= 70) SET @ValorePrioritaB = 1  
  ELSE IF (((@COSTO_INVESTIMENTI_PRIORITARI/@COSTO_INVESTIMENTI)*100) >= 50) SET @ValorePrioritaB = 0.75 
  ELSE IF (((@COSTO_INVESTIMENTI_PRIORITARI/@COSTO_INVESTIMENTI)*100) >= 30) SET @ValorePrioritaB = 0.5 
  ELSE SET @ValorePrioritaB = 0   
  
  SELECT  @ValorePrioritaB
 

END
