CREATE PROCEDURE [dbo].[calcoloStepVariante112_114_4]
@ID_VARIANTE int
AS
-- 112-114 -  Il servizio di consulenza erogato comprende almeno una delle tipologie obbligatorie (condizionalità e sicurezza sul lavoro)? 

 DECLARE @RESULT INT
 SET @RESULT =1

DECLARE @ID_PROGETTO INT,@ID_PROGETTO_114 INT ,@COUNT_INV INT 

SET @ID_PROGETTO  = (SELECT ID_PROGETTO FROM VARIANTI WHERE ID_VARIANTE = @ID_VARIANTE)
SELECT DISTINCT @ID_PROGETTO_114 = p.ID_PROGETTO  FROM PROGETTO P
	INNER JOIN BANDO B ON B.ID_BANDO = P.ID_BANDO INNER JOIN ZPROGRAMMAZIONE ZP ON ZP.ID =B.ID_PROGRAMMAZIONE AND CODICE = '1.1.4.'
WHERE ID_PROG_INTEGRATO = @ID_PROGETTO

--SOLO SE LA VARIANTE è PER LA 114
SET @COUNT_INV =(SELECT COUNT (*) FROM  PIANO_INVESTIMENTI I 
				WHERE ID_VARIANTE = @ID_VARIANTE AND ID_PROGETTO = @ID_PROGETTO_114 AND 
				ISNULL(COD_VARIAZIONE, 'X' )!='A' AND COSTO_INVESTIMENTO >0 AND COD_VARIAZIONE IS NOT NULL)

IF( @COUNT_INV >0 )
BEGIN
 SET @RESULT =( SELECT COUNT(*) FROM VPIANO_INVESTIMENTI I WHERE ID_VARIANTE = @ID_VARIANTE AND 
				ISNULL(COD_VARIAZIONE , 'X') != 'A' AND COSTO_INVESTIMENTO  >0 AND CODICE IN ('CG', 'BC','FO','SI') AND I.ID_PROGETTO = @ID_PROGETTO_114 )
 END

SELECT @RESULT AS RESULT
