CREATE PROCEDURE [dbo].[calcoloStepVariante132_4]
(
@ID_VARIANTE int
)
AS
BEGIN


--
-- ANNUALITA
 --ID Priorita per anno : 375

DECLARE  @result int
SET @RESULT =0 --PONGO LO STEP VERIFICATO

 DECLARE @COUNT_A  INT, @COUNT_B INT

 SELECT @COUNT_A=COUNT(DISTINCT PXI.DESCRIZIONE)
 FROM PIANO_INVESTIMENTI AS PI INNER JOIN  
			 VPRIORITA_X_INVESTIMENTI PXI  ON PI.ID_INVESTIMENTO = PXI.ID_INVESTIMENTO  
 WHERE PI.ID_VARIANTE = @ID_VARIANTE AND ISNULL(COD_VARIAZIONE,'x') !='A' AND ID_PRIORITA = 375   

IF ( @COUNT_A = 3 ) SET @RESULT= 1
SELECT @RESULT AS RESULT
END
