CREATE PROCEDURE [dbo].[calcoloStep112_114_2]
@IdProgetto int, @FASE_ISTRUTTORIA INT = 0
AS
-- CONTROLLO SU ALLEGATI OBBLIGATORI  114
  
/*
DECLARE @IdProgetto INT
SET @IdProgetto=375
*/
DECLARE @RESULT INT

DECLARE @ID_PROG_INTEG_114 INT

SELECT DISTINCT @ID_PROG_INTEG_114 = p.ID_PROGETTO FROM PROGETTO P
INNER JOIN BANDO B ON B.ID_BANDO = P.ID_BANDO INNER JOIN ZPROGRAMMAZIONE ZP ON ZP.ID =B.ID_PROGRAMMAZIONE AND CODICE = '1.1.4.'
WHERE ID_PROG_INTEGRATO = @IdProgetto

IF @ID_PROG_INTEG_114 IS NULL SET @RESULT=2
ELSE BEGIN
	SELECT  @RESULT  =  CASE  	WHEN SUM(COSTO_INVESTIMENTO) > 0   THEN COUNT(*) ELSE 1  END      
	FROM VPIANO_INVESTIMENTI I    
 WHERE ID_PROGETTO  = @ID_PROG_INTEG_114  AND ((@FASE_ISTRUTTORIA=0 AND ID_INVESTIMENTO_ORIGINALE IS NULL AND ID_VARIANTE  IS NULL)OR(@FASE_ISTRUTTORIA= 1 AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE  IS NULL)) 
	 AND CODICE IN ( 'CG', 'BC','FO','SI' )

END
SELECT @RESULT
