CREATE PROCEDURE [dbo].[calcoloPrioritaVariante311_B_2]
(
  @ID_VARIANTE INT 
)
AS
BEGIN

-- 147 -  EFFICIENZA  ENERGETICA
 
DECLARE @CONTRIBUTO decimal(10,2)
DECLARE @Investimenti decimal(10,2)
DECLARE @ID_CODIFICA_INVESTIMENTO INT
DECLARE @IdProgetto INT

SET @IdProgetto = (SELECT ID_PROGETTO FROM VARIANTI WHERE ID_VARIANTE = @ID_VARIANTE )

DECLARE CONTRIBUTO CURSOR FOR

SELECT       SUM(PI.CONTRIBUTO_RICHIESTO )  , PI.ID_CODIFICA_INVESTIMENTO
FROM         PIANO_INVESTIMENTI  pi
WHERE       ID_CODIFICA_INVESTIMENTO IS NOT NULL AND  PI.ID_VARIANTE = @ID_VARIANTE   AND isnull(COD_VARIAZIONE,'x')!='A' 
group by  PI.ID_CODIFICA_INVESTIMENTO 
ORDER BY    SUM(PI.CONTRIBUTO_RICHIESTO ) desc

		OPEN CONTRIBUTO
		FETCH NEXT FROM CONTRIBUTO INTO @CONTRIBUTO, @ID_CODIFICA_INVESTIMENTO
		CLOSE CONTRIBUTO
		DEALLOCATE CONTRIBUTO

DECLARE @Punteggio decimal (10,2)

set @Punteggio= (SELECT  top (1)   VALORI_PRIORITA.PUNTEGGIO FROM PRIORITA_X_INVESTIMENTI INNER JOIN
                 VALORI_PRIORITA ON 
				 PRIORITA_X_INVESTIMENTI.ID_VALORE = VALORI_PRIORITA.ID_VALORE INNER JOIN
                 PIANO_INVESTIMENTI ON PRIORITA_X_INVESTIMENTI.ID_INVESTIMENTO = PIANO_INVESTIMENTI.ID_INVESTIMENTO
				 WHERE PIANO_INVESTIMENTI.ID_PROGETTO = @IdProgetto AND PIANO_INVESTIMENTI.ID_CODIFICA_INVESTIMENTO =@ID_CODIFICA_INVESTIMENTO 
				 AND PRIORITA_X_INVESTIMENTI.ID_PRIORITA = 147  AND PIANO_INVESTIMENTI.ID_VARIANTE = @ID_VARIANTE  
				 AND isnull(COD_VARIAZIONE,'x')!='A' )

 SELECT @Punteggio AS PUNTEGGIO
RETURN (@Punteggio * 100)

END
