--SAL  111 a assam   
-- spese di coordinamento (max 5%)

CREATE   PROCEDURE [dbo].[calcoloRequisitoPagamento111_3]
@ID_DOMANDA_PAGAMENTO int
AS
BEGIN
-- DECLARE  @ID_DOMANDA_PAGAMENTO int
--SET  @ID_DOMANDA_PAGAMENTO = 626
DECLARE @ID_PROGETTO INT , @IMPORTO_RICHIESTO DECIMAL (18,2) , @ANNO INT, @IMPORTO_TOTALE  DECIMAL (18,2)
DECLARE @RESULT INT

SET @RESULT =1  -- IMPONGO LO STEP   VERIFICATO		 
SET @ANNO = DATEPART(YEAR,GETDATE())-1
SET @ID_PROGETTO = ( SELECT ID_PROGETTO FROM DOMANDA_DI_PAGAMENTO WHERE ID_DOMANDA_PAGAMENTO=@ID_DOMANDA_PAGAMENTO  )	
SET @IMPORTO_RICHIESTO= (SELECT SUM(ISNULL(IMPORTO_RICHIESTO,0))
	FROM PIANO_INVESTIMENTI  PI inner join   PAGAMENTI_RICHIESTI  PR  ON PI.ID_INVESTIMENTO = PR.ID_INVESTIMENTO 
	WHERE ID_PROGETTO = @ID_PROGETTO  AND  ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO
		 AND DESCRIZIONE   LIKE  '%'+CAST (@ANNO  AS  CHAR(4)) + '%' AND PI.COD_TIPO_INVESTIMENTO = 1   
		 AND PI.ID_CODIFICA_INVESTIMENTO IN (SELECT ID_CODIFICA_INVESTIMENTO FROM CODIFICA_INVESTIMENTO 
											WHERE ID_BANDO = (SELECT ID_BANDO FROM PROGETTO WHERE ID_PROGETTO = @ID_PROGETTO)AND CODICE = '26'))
SET @IMPORTO_TOTALE =  ( SELECT SUM(ISNULL(IMPORTO_RICHIESTO,0) )
						 FROM  PIANO_INVESTIMENTI  PI INNER JOIN PAGAMENTI_RICHIESTI  PR  ON PI.ID_INVESTIMENTO = PR.ID_INVESTIMENTO 
						 WHERE ID_PROGETTO = @ID_PROGETTO AND ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO
							AND DESCRIZIONE LIKE '%'+CAST (@ANNO  AS  CHAR(4))+ '%' AND PI.COD_TIPO_INVESTIMENTO = 1 )  
															 
IF( ISNULL( @IMPORTO_RICHIESTO,0) >(@IMPORTO_TOTALE * 0.05) )  SET @RESULT=0
SELECT @RESULT
END
