CREATE PROCEDURE [dbo].[calcoloStep221_13]
(
	@IdProgetto int,
	@FASE_ISTRUTTORIA INT =0
)
AS
BEGIN
--DECLARE @IdProgetto int =8908,
-- 	@FASE_ISTRUTTORIA INT =1 
 
 --CONTROLLO STORICIZZAZIONE DEL PIANO COLTURALE
DECLARE @RESULT int, @ID_IMPRESA INT, @DATA_ULTIMA_MODIFICA DATETIME,@DATA_STO DATETIME
SET @RESULT = 1 -- PONGO LO STEP IN STATO VERIFICATO



-----
SELECT @ID_IMPRESA=ID_IMPRESA FROM PROGETTO P WHERE ID_PROGETTO = @IdProgetto
IF(@FASE_ISTRUTTORIA =0)
BEGIN 
  SELECT @DATA_ULTIMA_MODIFICA =P.DATA FROM PROGETTO_STORICO P WHERE P.ID_PROGETTO =@IdProgetto AND COD_STATO = 'P'
  SELECT @DATA_STO = P.DATA_FINE FROM (SELECT MAX(PCS.ID_RIF) ID_PS_MAX
  FROM PIANO_COLTURALE_STORICO PCS INNER JOIN PIANO_COLTURALE_DETTAGLIO PC ON PC.ID_RIF = PCS.ID_RIF
   WHERE PCS.ID_IMPRESA=@ID_IMPRESA AND (DATA_INIZIO <GETDATE()) AND PC.ID_CATASTO IS NOT NULL) PS INNER JOIN PIANO_COLTURALE_STORICO P ON P.ID_RIF =PS.ID_PS_MAX 
  -- FROM PIANO_COLTURALE_STORICO  
  -- WHERE ID_IMPRESA=@ID_IMPRESA AND (DATA_INIZIO <GETDATE()))PS INNER JOIN PIANO_COLTURALE_STORICO P ON P.ID_RIF =PS.ID_PS_MAX 
  IF(@DATA_STO IS NULL)SET @RESULT =0 
END
ELSE BEGIN 
 SELECT @DATA_ULTIMA_MODIFICA =DATA FROM PROGETTO_STORICO P WHERE P.ID_PROGETTO =@IdProgetto AND COD_STATO IN ('A','B') ORDER BY ID DESC
 IF(@DATA_ULTIMA_MODIFICA IS NULL ) SET @DATA_ULTIMA_MODIFICA =GETDATE()
 SELECT @DATA_STO = P.DATA_FINE FROM (SELECT MAX(PCS.ID_RIF) ID_PS_MAX 
 FROM PIANO_COLTURALE_STORICO PCS INNER JOIN PIANO_COLTURALE_DETTAGLIO PC ON PC.ID_RIF = PCS.ID_RIF WHERE PCS.ID_IMPRESA=@ID_IMPRESA AND PC.ID_CATASTO IS NOT NULL AND (DATA_INIZIO <@DATA_ULTIMA_MODIFICA ))PS INNER JOIN PIANO_COLTURALE_STORICO P ON P.ID_RIF =PS.ID_PS_MAX 
 IF(@DATA_STO IS NULL)SET @RESULT =0 

 
END
SELECT @RESULT
END
