CREATE  PROCEDURE [dbo].[calcoloStepPagamento311_4]
@IdProgetto int,
@IdDomandaPagamento int 
AS
BEGIN
 -- DATA INIZIO LAVORI 6MESI DALLA DATA DI COMUNICAZIONE FINANZIABILITà
 
DECLARE  @COUNT INT,	
					@RESULT INT, 
					@DATE_FIN AS DATETIME

select @IdDomandaPagamento = id_DOMANDA_PAGAMENTO FROM DOMANDA_DI_PAGAMENTO where ID_PROGETTO = @IdProgetto AND COD_TIPO= 'SLD'
SET @DATE_FIN =  (SELECT  VAL_DATA FROM  DOMANDA_PAGAMENTO_REQUISITI where ID_DOMANDA_PAGAMENTO = @IdDomandaPagamento  AND ID_REQUISITO =152)
IF(@DATE_FIN IS NULL )SET @RESULT =0
ELSE 
SET @RESULT =(SELECT 'DIFF'= CASE 
								 WHEN   DATEDIFF(DAY, DATEADD(MM,6,@DATE_FIN ) , 
																	(SELECT  VAL_DATA FROM DOMANDA_PAGAMENTO_REQUISITI WHERE ID_DOMANDA_PAGAMENTO = @IdDomandaPagamento  AND ID_REQUISITO =1) ) <=0 THEN 1 	
								 ELSE  0 END)

 SELECT @RESULT  
END
