CREATE PROCEDURE [dbo].[calcoloStep221_12]
@IdProgetto int, 
@FASE_ISTRUTTORIA INT =0
AS
BEGIN
-- deminimis

DECLARE @RESULT int,
		@RESULTA int,
		@RESULTB int

SET @RESULT = 0 -- PONGO LO STEP IN STATO NON VERIFICATO
SET @RESULTA = 0 -- PONGO LO STEP IN STATO NON VERIFICATO
SET @RESULTB = 0 -- PONGO LO STEP IN STATO NON VERIFICATO


SET @RESULTA = (SELECT ISNULL (VALORE,0) from PRIORITA_X_PROGETTO WHERE ID_PRIORITA = 600 AND ID_PROGETTO = @IdProgetto)  
SET @RESULTB = (SELECT ISNULL(SUM(CONTRIBUTO_RICHIESTO),0) 
				FROM PROGETTO P  
					 INNER JOIN PIANO_INVESTIMENTI I ON (P.ID_PROGETTO=I.ID_PROGETTO) 
				 WHERE(P.ID_PROGETTO=@IdProgetto OR P.ID_PROG_INTEGRATO=@IdProgetto) AND
				 ((@FASE_ISTRUTTORIA=0 AND I.ID_INVESTIMENTO_ORIGINALE IS NULL)OR
					(@FASE_ISTRUTTORIA=1 AND I.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL)))

IF ((ISNULL (@RESULTA,0) + @RESULTB) <= 200000)SET @RESULT=1
SELECT @RESULT AS RESULT

END
