CREATE PROCEDURE [dbo].[calcoloPrioritaM41_3]
    @IdProgetto INT , 
	@fase_istruttoria BIT =0,
	@IdVariante INT = NULL
AS
BEGIN

/* Priorita C: M4.1 - Dimensione Aziendale e Produzione Standard (PS) */

DECLARE @PROD_STANDARD DECIMAL(18,2), @ValorePrioritaC DECIMAL(10,4) 
DECLARE   @PROD_STANDARD_ATT_CONNESSE DECIMAL(18,2)	
		
SELECT @PROD_STANDARD=SUM(PS) 
FROM ( SELECT CASE WHEN I.CODICE IS NOT NULL THEN SUM(PSD.PS_REALE) ELSE SUM(PS_STANDARD) END AS PS
		FROM PRODUZIONE_STANDARD PS INNER JOIN PRODUZIONE_STANDARD_DETTAGLIO PSD ON PSD.ID_PS = PS.ID
			LEFT JOIN INEA_PRODUZIONE_STANDARD I ON I.ID = PSD.ID_TRASFORMAZIONE AND I.CODICE IN ('T10','T12') 
		WHERE PS.ID_PROGETTO =@IdProgetto AND PREVISIONALE = 0 AND AMMESSO = @fase_istruttoria AND COD_TIPO IN ('V','Z') 
		GROUP BY I.CODICE ) TT 
	
SELECT @PROD_STANDARD_ATT_CONNESSE=SUM(PSD.PS_REALE) 
FROM PRODUZIONE_STANDARD PS INNER JOIN PRODUZIONE_STANDARD_DETTAGLIO PSD ON PSD.ID_PS = PS.ID
	INNER JOIN INEA_PRODUZIONE_STANDARD I ON I.ID = PSD.ID_ATTIVITA_CONNESSA  AND I.SETTORE IN ('CZ','CV')
WHERE PS.ID_PROGETTO =@IdProgetto AND PREVISIONALE = 0 AND AMMESSO = @fase_istruttoria AND COD_TIPO IN ('C') 

SET @PROD_STANDARD= @PROD_STANDARD+ ISNULL(@PROD_STANDARD_ATT_CONNESSE ,0)

 IF(@PROD_STANDARD=0) SET @ValorePrioritaC=0
 ELSE IF(@PROD_STANDARD < 12000) SET @ValorePrioritaC=0 
 ELSE IF(@PROD_STANDARD <= 25000) SET @ValorePrioritaC=1 
 ELSE IF(@PROD_STANDARD <= 70000) SET @ValorePrioritaC=0.6
 ELSE IF(@PROD_STANDARD <= 100000) SET @ValorePrioritaC=0.3
 ELSE SET @ValorePrioritaC=0  
 
 SELECT @ValorePrioritaC 
END


/*
/*verifico che abbiamo fatto salva nella PS*/

	
	SELECT @PROD_STANDARD=SUM(PS) 
	FROM ( SELECT CASE WHEN I.CODICE IS NOT NULL THEN SUM(PSD.PS_REALE) ELSE SUM(PS_STANDARD) END AS PS
			FROM PRODUZIONE_STANDARD PS INNER JOIN PRODUZIONE_STANDARD_DETTAGLIO PSD ON PSD.ID_PS = PS.ID
				LEFT JOIN INEA_PRODUZIONE_STANDARD I ON I.ID = PSD.ID_TRASFORMAZIONE AND I.CODICE IN ('T10','T12') 
			WHERE PS.ID_PROGETTO =@IdProgetto AND PREVISIONALE = 0 AND AMMESSO = @ISTRUTTORIA AND COD_TIPO IN ('V','Z') GROUP BY I.CODICE ) TT 
	
	SELECT @PROD_STANDARD_ATT_CONNESSE=SUM(PSD.PS_REALE) 
	FROM PRODUZIONE_STANDARD PS INNER JOIN PRODUZIONE_STANDARD_DETTAGLIO PSD ON PSD.ID_PS = PS.ID
		INNER JOIN INEA_PRODUZIONE_STANDARD I ON I.ID = PSD.ID_ATTIVITA_CONNESSA  AND I.SETTORE IN ('CZ','CV')
	WHERE PS.ID_PROGETTO =@IdProgetto AND PREVISIONALE = 0 AND AMMESSO = @ISTRUTTORIA AND COD_TIPO IN ('C') 
	

 
	IF(@PROD_STANDARD=0) SET @ValorePrioritaC=0   
	ELSE IF(@PROD_STANDARD < 12000) SET @ValorePrioritaC=0     
	ELSE IF(@PROD_STANDARD <= 25000) SET @ValorePrioritaC=1
	ELSE IF(@PROD_STANDARD <= 70000) SET @ValorePrioritaC=0.6
	ELSE IF(@PROD_STANDARD <= 100000) SET @ValorePrioritaC=0.3  
	ELSE SET @ValorePrioritaC=0     
	SET @PunteggioPrioritaC = (@ValorePrioritaC * @PesoPrioritaC)    

*/
