--
CREATE PROCEDURE [dbo].[calcoloStep313ab_PR_FM]
(
@IdProgetto int,
@FASE_ISTRUTTORIA INT =0
)
AS
BEGIN

-- PROVINCIA FERMO misura 313ab
-- Il beneficiario ha inserito investimenti per un solo intervento
DECLARE @result int

SET @RESULT = 0 --PONGO LO STEP IN STATO NON VERIFICATO

DECLARE @INTERVENTO_A int,
		@INTERVENTO_B int

select @INTERVENTO_A = (SELECT ISNULL(COUNT(DISTINCT(I.CODICE)),0)  FROM PROGETTO P INNER JOIN VPIANO_INVESTIMENTI I ON P.ID_PROGETTO=I.ID_PROGETTO WHERE
						I.ID_INVESTIMENTO_ORIGINALE IS NULL AND
						I.COD_TIPO_INVESTIMENTO = 1 AND
						I.CODICE IN ('A1','A2') AND
						P.ID_PROGETTO = @IdProgetto AND 
						((I.ID_INVESTIMENTO_ORIGINALE IS NULL AND @FASE_ISTRUTTORIA=0 AND ID_VARIANTE IS NULL) OR
						 (I.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND @FASE_ISTRUTTORIA =1 AND ID_VARIANTE IS NULL)))
						 
select @INTERVENTO_B = (SELECT ISNULL(COUNT(DISTINCT(I.CODICE)),0)  FROM PROGETTO P INNER JOIN VPIANO_INVESTIMENTI I ON P.ID_PROGETTO=I.ID_PROGETTO WHERE
						I.ID_INVESTIMENTO_ORIGINALE IS NULL AND
						I.COD_TIPO_INVESTIMENTO = 1 AND
						I.CODICE IN ('B1','B2') AND
						P.ID_PROGETTO = @IdProgetto AND 
						((I.ID_INVESTIMENTO_ORIGINALE IS NULL AND @FASE_ISTRUTTORIA=0 AND ID_VARIANTE IS NULL) OR
						 (I.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND @FASE_ISTRUTTORIA =1 AND ID_VARIANTE IS NULL)))

 
IF(((ISNULL(@INTERVENTO_A,0) >= 1) AND (ISNULL(@INTERVENTO_B,0) = 0)) OR ((ISNULL(@INTERVENTO_A,0) = 0) AND (ISNULL(@INTERVENTO_B,0) >= 1))) 
	SET @result = 1 
	
	SELECT @result AS RESULT
END
