CREATE   PROCEDURE [dbo].[calcoloStep133_5]
(
@IdProgetto int,
@FASE_ISTRUTTORIA INT =0
)
AS
BEGIN
-- CORRETTA % DEI COSTI DI DIREZIONE

DECLARE @COSTO_INIZIATIVA DECIMAL(18,2),  @NUM_INIZIATIVA INT,   @SOGGETTO CHAR(1),@COSTO_DIREZIONE DECIMAL(18,2),  @RESULT INT 
SET @RESULT =1 --PONGO LO STEP  VERIFICATO

DECLARE COST_INIZ CURSOR FOR
(SELECT    SUM(ISNULL( SPESE_TOTALI,1))   AS COSTO_TOTALE , VALORE
 FROM ( SELECT   PXI.VALORE, 'SPESE_TOTALI' =  CASE   WHEN   I.CODICE NOT IN ('4','8','12','16', '20')  THEN  SUM(COSTO_INVESTIMENTO) END 
				FROM VPIANO_INVESTIMENTI AS I INNER JOIN  PRIORITA_X_INVESTIMENTI PXI ON I.ID_INVESTIMENTO = PXI.ID_INVESTIMENTO AND ID_PRIORITA = 399    
				WHERE   ID_PROGETTO =@IdProgetto AND ((@fase_istruttoria =0 and ID_INVESTIMENTO_ORIGINALE  is null and id_variante is null ) or (@fase_istruttoria =1 and ID_INVESTIMENTO_ORIGINALE  is not null and id_variante is null )  )   
				GROUP BY  PXI.VALORE, CODICE) AS T 
 GROUP BY VALORE )

OPEN COST_INIZ
FETCH NEXT FROM COST_INIZ 
INTO @COSTO_INIZIATIVA , @NUM_INIZIATIVA
WHILE @@FETCH_STATUS = 0
BEGIN
 SET @SOGGETTO= ( SELECT TOP(1) ID_VALORE FROM ( SELECT   PXI.ID_INVESTIMENTO FROM PIANO_INVESTIMENTI AS I INNER JOIN
										  PRIORITA_X_INVESTIMENTI AS PXI ON I.ID_INVESTIMENTO = PXI.ID_INVESTIMENTO AND PXI.ID_PRIORITA = 399  AND VALORE = @NUM_INIZIATIVA
									      WHERE   ID_PROGETTO =@IdProgetto AND ((@fase_istruttoria =0 and ID_INVESTIMENTO_ORIGINALE  is null and id_variante is null ) or (@fase_istruttoria =1 and ID_INVESTIMENTO_ORIGINALE  is not null and id_variante is null ))) AS INIZ  
										  INNER JOIN PRIORITA_X_INVESTIMENTI AS PXI_SOGG ON INIZ.ID_INVESTIMENTO = PXI_SOGG.ID_INVESTIMENTO AND PXI_SOGG.ID_PRIORITA = 398 )

IF(@SOGGETTO= 571 ) -- SOGGETTO ESTERNO
	BEGIN 
		SET @COSTO_DIREZIONE= 
						( SELECT  SUM(COSTO_INVESTIMENTO) COSTO_DIREZIONE
						   FROM PIANO_INVESTIMENTI AS I INNER JOIN  
										 PRIORITA_X_INVESTIMENTI PXI ON I.ID_INVESTIMENTO = PXI.ID_INVESTIMENTO AND ID_PRIORITA = 399  AND VALORE =@NUM_INIZIATIVA INNER JOIN 
										 DETTAGLIO_INVESTIMENTI DI ON DI.ID_DETTAGLIO_INVESTIMENTO = I.ID_DETTAGLIO_INVESTIMENTO
							WHERE   ID_PROGETTO =@IdProgetto AND ((@fase_istruttoria =0 and ID_INVESTIMENTO_ORIGINALE  is null and id_variante is null ) or
											 (@fase_istruttoria =1 and ID_INVESTIMENTO_ORIGINALE  is not null and id_variante is null ))  AND COD_DETTAGLIO = '42' )
			IF(((ISNULL(@COSTO_DIREZIONE ,0) *100)/ ISNULL(@COSTO_INIZIATIVA,0)   ) > 1) SET @RESULT =0
	END
ELSE 
BEGIN
	IF(@SOGGETTO= 572 ) -- SOGGETTO IN PROPRIO
	BEGIN 
 				SET @COSTO_DIREZIONE= 
						( SELECT  SUM(COSTO_INVESTIMENTO) COSTO_DIREZIONE
						   FROM PIANO_INVESTIMENTI AS I INNER JOIN  
										 PRIORITA_X_INVESTIMENTI PXI ON I.ID_INVESTIMENTO = PXI.ID_INVESTIMENTO AND ID_PRIORITA = 399  AND VALORE =@NUM_INIZIATIVA INNER JOIN 
										 DETTAGLIO_INVESTIMENTI DI ON DI.ID_DETTAGLIO_INVESTIMENTO = I.ID_DETTAGLIO_INVESTIMENTO
							WHERE   ID_PROGETTO =@IdProgetto AND ((@fase_istruttoria =0 and ID_INVESTIMENTO_ORIGINALE  is null and id_variante is null ) or
											 (@fase_istruttoria =1 and ID_INVESTIMENTO_ORIGINALE  is not null and id_variante is null ))  AND COD_DETTAGLIO = '42' )
					IF(((ISNULL(@COSTO_DIREZIONE ,0) *100)/ ISNULL(@COSTO_INIZIATIVA,0)   ) > 6) SET @RESULT =0
 
	END
END
FETCH NEXT FROM COST_INIZ
INTO @COSTO_INIZIATIVA,   @NUM_INIZIATIVA
END

CLOSE COST_INIZ
DEALLOCATE COST_INIZ 
SELECT @RESULT AS RESULT
END
