create  PROCEDURE [dbo].[calcoloStepVariante_B316]
@ID_VARIANTE int

AS
BEGIN

DECLARE @result int,@COUNT int, @SCARTO int

--- Costo singolo Hotspot <= 15.000€
--- ID PRIORITA 1066 A LIVELLO DI INVESTIMENTO CHE PERMETTERE L'INSERIMENTO DEL NUMERO UNIVOCO CHE IDENTIFICA L'HOTSPOT
--- 

SET @result = 0 -- LO PONGO NON VERIFICATO 

SET @SCARTO  = (SELECT((SELECT COUNT(*) AS A FROM PIANO_INVESTIMENTI WHERE ID_VARIANTE = @ID_VARIANTE AND isnull(COD_VARIAZIONE,'x') != 'A')
					-
					(SELECT COUNT(*) AS B FROM  PIANO_INVESTIMENTI AS PI INNER JOIN PRIORITA_X_INVESTIMENTI PXI ON PI.ID_INVESTIMENTO = PXI.ID_INVESTIMENTO 
					 WHERE PXI.ID_PRIORITA = 1066 AND ID_VARIANTE = @ID_VARIANTE AND isnull(COD_VARIAZIONE,'x') != 'A')))

SELECT @COUNT = COUNT(*) FROM PROGETTO P INNER JOIN VPIANO_INVESTIMENTI I ON P.ID_PROGETTO=I.ID_PROGETTO 
						INNER JOIN PRIORITA_X_INVESTIMENTI PXI ON PXI.ID_INVESTIMENTO = I.ID_INVESTIMENTO
					WHERE ID_VARIANTE = @ID_VARIANTE AND isnull(COD_VARIAZIONE,'x') != 'A' AND PXI.ID_PRIORITA = 1066
					GROUP BY PXI.VALORE
					HAVING ISNULL(SUM(CONTRIBUTO_RICHIESTO),0) > 15000

IF ((ISNULL(@COUNT,0) = 0 ) AND (ISNULL(@SCARTO,0) = 0)) SET @result = 1
SELECT @result AS RESULT
END
