CREATE  PROCEDURE [dbo].[calcoloStepVariante123_7]
@ID_VARIANTE int
AS
BEGIN

--  123 - Totale inivestimenti per interventi legati alla trasformazione e commercializzazione > = 100.000,00 €
-- IMPORTO MODIFICATO DICEMBRE 2010


DECLARE @Count int, 
					@COSTO DECIMAL (20,2),
					@RESULT INT
SET @RESULT =0  --- NON VERIFICATO

SET @Count = (SELECT COUNT(ID_INVESTIMENTO)
		      FROM PROGETTO P INNER JOIN VPIANO_INVESTIMENTI I ON (P.ID_PROGETTO=I.ID_PROGETTO) 
		      WHERE ID_VARIANTE= @ID_VARIANTE AND ISNULL(COD_VARIAZIONE,'x')!='A'  AND (CODICE IN ( '66','67')))
 
--SELECT @Count 
IF (ISNULL(@Count,0) > 0) 
BEGIN 
	SET @COSTO=(SELECT ISNULL( SUM (COSTO_INVESTIMENTO + SPESE_GENERALI) , 0) AS Totale_Investimenti  
				FROM PROGETTO P INNER JOIN  vPIANO_INVESTIMENTI I ON (P.ID_PROGETTO=I.ID_PROGETTO)
				WHERE ID_VARIANTE= @ID_VARIANTE AND ISNULL(COD_VARIAZIONE,'x')!='A' AND CODICE IN ('64','65','66','67'))
	IF(@COSTO > 100000)SET @RESULT=1
END
 ELSE SET @RESULT =1
SELECT @RESULT AS RESULT
END
