CREATE   PROCEDURE [dbo].[calcoloStepVariante132_2]
(
@ID_VARIANTE int
 )
AS
BEGIN

-- ANNUALITA
 --ID Priorita per anno : 375

DECLARE  @result int
SET @RESULT =1 --PONGO LO STEP VERIFICATO

 DECLARE @COUNT_A  INT, @COUNT_B INT
SET  @COUNT_A = (SELECT COUNT(*)  FROM 
					PIANO_INVESTIMENTI AS PI INNER JOIN
					VPRIORITA_X_INVESTIMENTI PXI  ON PI.ID_INVESTIMENTO = PXI.ID_INVESTIMENTO  
				WHERE ID_VARIANTE = @ID_VARIANTE AND ISNULL(COD_VARIAZIONE,'X') != 'A' AND id_priorita = 375  AND  PXI.DESCRIZIONE  ='2011' )

SET  @COUNT_B = (SELECT COUNT(*)  FROM  PIANO_INVESTIMENTI AS PI INNER JOIN  
										VPRIORITA_X_INVESTIMENTI PXI  ON PI.ID_INVESTIMENTO = PXI.ID_INVESTIMENTO  
										WHERE ID_VARIANTE = @ID_VARIANTE AND ISNULL(COD_VARIAZIONE,'X') != 'A' AND id_priorita = 375  AND  PXI.DESCRIZIONE  ='2014' )

IF ( @COUNT_A > 0  AND @COUNT_B >0 ) SET @RESULT= 0
SELECT @RESULT AS RESULT
END
