CREATE PROCEDURE [dbo].[calcoloStep431_1]
@IdProgetto int
AS
BEGIN
 
--- massimale di intervento A
 
 
DECLARE @RESULT int,		 
		@CONTRIBUTO_RICHIESTO_PROGETTO_A DECIMAL (10,2),	 
		@CONTRIBUTO_RICHIESTO_PASSATO_A DECIMAL (10,2), 
	 	@QUOTA_CONTRIBUTO_TOTALE_A DECIMAL(10,2), 
		@ID_IMPRESA INT, @CUAA VARCHAR(16)

SET @RESULT = 0  -- Impongo lo Step NON verificato
--------------------------------------------------------------------------------------------------------------
SELECT @ID_IMPRESA = P.ID_IMPRESA , @CUAA = imp.CUAA 
FROM PROGETTO P INNER JOIN IMPRESA IMP ON IMP.ID_IMPRESA = P.ID_IMPRESA  WHERE ID_PROGETTO = @IdProgetto 

SET @CONTRIBUTO_RICHIESTO_PROGETTO_A = (SELECT SUM(PI.CONTRIBUTO_RICHIESTO) AS CONTRIBUTO
										FROM PIANO_INVESTIMENTI PI 
											INNER JOIN PROGETTO ON PI.ID_PROGETTO = PROGETTO.ID_PROGETTO
										WHERE (PI.ID_PROGETTO = @IdProgetto) AND PI.ID_PROGRAMMAZIONE = 325 AND
											 ((PI.ID_INVESTIMENTO_ORIGINALE IS NULL AND PROGETTO.FLAG_DEFINITIVO =0 ) 
											or (PI.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND PROGETTO.FLAG_DEFINITIVO =1 AND ID_VARIANTE IS NULL)))


--ID_BANDO = 106

SET @CONTRIBUTO_RICHIESTO_PASSATO_A = (SELECT SUM(CONTRIBUTO_RICHIESTO) AS CONTRIBUTO
									   FROM  PIANO_INVESTIMENTI 
									   WHERE ID_INVESTIMENTO_ORIGINALE IS NOT NULL 
											 AND ID_PROGRAMMAZIONE = 325  AND  ID_PROGETTO IN 
														( SELECT ID_PROGETTO FROM PROGETTO 
														  WHERE ID_IMPRESA=@ID_IMPRESA  AND FLAG_DEFINITIVO =1 AND  ID_PROGETTO <> @IdProgetto  AND ID_BANDO = 106 ) )      
 

SET @QUOTA_CONTRIBUTO_TOTALE_A = (ISNULL(@CONTRIBUTO_RICHIESTO_PROGETTO_A,0) + ISNULL(@CONTRIBUTO_RICHIESTO_PASSATO_A,0)   )
 

select @QUOTA_CONTRIBUTO_TOTALE_A
  
-- A	Alta Valmarecchia    TOTALE  € 852.045,08 	 
IF (@CUAA =  '01119560439'  AND   @QUOTA_CONTRIBUTO_TOTALE_A  <=  639033.81    )
	 SET @RESULT = 1
-- B	Montefeltro Sviluppo 	 TOTALE  € 836.048,86 

ELSE IF ((@CUAA = '01377860414' ) AND   @QUOTA_CONTRIBUTO_TOTALE_A   <=   627036.65     )  
	  SET @RESULT = 1

-- C	Sibilla 	   € 920.633,20 
ELSE IF (@CUAA = '01451540437' AND   @QUOTA_CONTRIBUTO_TOTALE_A   <=  690474.90   )  
	  SET @RESULT = 1

--D1	Flaminia Cesano 	 € 655.201,44 
ELSE IF (@CUAA = '01377760416' AND  @QUOTA_CONTRIBUTO_TOTALE_A  <=  491401.08    ) 
	  SET @RESULT = 1

--D2	Piceno     € 660.202,29 

ELSE IF (@CUAA = '01502360447' AND  @QUOTA_CONTRIBUTO_TOTALE_A  <=   495151.72   )  
	  SET @RESULT = 1

-- E	Fermano Leader  € 674.050,97 


ELSE IF (@CUAA = '01944950441' AND  @QUOTA_CONTRIBUTO_TOTALE_A  <=  505538.23      )  
	  SET @RESULT = 1
 
 SELECT @RESULT
 END
