CREATE PROCEDURE [dbo].[calcoloStep413_F_1]
@IdProgetto int,
@fase_istruttoria int =0
AS
BEGIN
--
--declare @IdProgetto int,@fase_istruttoria int
--set @fase_istruttoria =0
--set @IdProgetto=858

DECLARE @Result int,
		@COSTO_INV decimal(18,2) , 
		@BB INT 

SET @Result = 1 -- Impongo lo Step  verificato
SELECT @COSTO_INV=SUM(ISNULL(COSTO_INVESTIMENTO,0))  + SUM(ISNULL(SPESE_GENERALI,0)) FROM PIANO_INVESTIMENTI
				 WHERE ID_PROGETTO = @IDPROGETTO AND ((@FASE_ISTRUTTORIA= 0 AND ID_VARIANTE IS NULL AND ID_INVESTIMENTO_ORIGINALE IS NULL)OR
								(@FASE_ISTRUTTORIA= 1 AND ID_VARIANTE IS NULL AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL))
 SELECT @BB=COUNT(ID_PRIORITA) FROM PRIORITA_X_PROGETTO PP WHERE ID_PROGETTO = @IdProgetto AND ID_PRIORITA = 537
   
IF(ISNULL(@BB, 0) >0 )
	BEGIN
		IF (@COSTO_INV > 35000) SET @Result=0
	END
ELSE 
BEGIN
		IF (@COSTO_INV >90000) SET @Result=0
	END
SELECT @Result AS RESULT
END
