CREATE PROCEDURE [dbo].[calcoloStep133_1]
(
	@IdProgetto int,
	@FASE_ISTRUTTORIA INT =0
)
AS
BEGIN

-- Verificato che non è stato presentato dal richiedente una domanda di aiuto a valere sulla medesima misura 1.3.3. ricompresa in un progetto di filiera.
 
DECLARE  @result int, @ID_IMPRESA INT

SET @RESULT =1 --PONGO LO STEP VERIFICATO

DECLARE @COUNT_P INT
SELECT @ID_IMPRESA = ID_IMPRESA FROM PROGETTO WHERE ID_PROGETTO = @IdProgetto 

SET @COUNT_P = (SELECT COUNT(*)
	            FROM ( SELECT DISTINCT PROGETTO.ID_PROGETTO, FLAG_DEFINITIVO 
						FROM PROGETTO 
							INNER JOIN PRIORITA_X_PROGETTO PP ON PP.ID_PROGETTO = PROGETTO.ID_PROGETTO AND ID_PRIORITA IN (406,374,798) 
							INNER JOIN PROGETTO_STORICO PS ON PROGETTO.ID_PROGETTO = PS.ID_PROGETTO AND PS.COD_STATO IN ('F')
			    		WHERE ID_IMPRESA = @ID_IMPRESA AND PROGETTO.ID_PROGETTO NOT IN (@IdProgetto )
								AND FLAG_PREADESIONE =0 
								AND PROGETTO.ID_BANDO IN (SELECT ID_BANDO FROM BANDO AS B INNER JOIN vzPROGRAMMAZIONE PR ON B.ID_PROGRAMMAZIONE = PR.ID 
														  WHERE COD_PSR LIKE 'PSR%' AND PR.CODICE LIKE '1.3.3%'
													      GROUP BY ID_BANDO, B.DESCRIZIONE)
					 )AS PROG   
			WHERE ( FLAG_DEFINITIVO =1) )
IF(@COUNT_P > 0 ) SET @RESULT = 0
SELECT @RESULT AS RESULT
END
