CREATE PROCEDURE [dbo].[calcoloStep111_17]
@IdProgetto int, @FASE_ISTRUTTORIA INT=0
AS
BEGIN

-- 111 a -  Domande presentate da beneficiari della misura 221
-- FATTO!!! 

DECLARE @Result INT, @CODICE_CODIFICA VARCHAR(5), @SPESA DECIMAL(18,2),  @SPESA_CODIFICA DECIMAL(18,2)

SET @Result =1 -- VERIFICATO

DECLARE SPESE_SERVIZI CURSOR FOR
SELECT SUM(INV.COSTO_INVESTIMENTO) , INV.CODICE 
FROM DETTAGLIO_INVESTIMENTI D  
	INNER JOIN vPIANO_INVESTIMENTI INV ON INV.ID_DETTAGLIO_INVESTIMENTO = D.ID_DETTAGLIO_INVESTIMENTO AND INV.ID_CODIFICA_INVESTIMENTO = D.ID_DETTAGLIO_INVESTIMENTO
WHERE D.COD_DETTAGLIO ='5'AND ID_PROGETTO = @IdProgetto AND 
	((ID_INVESTIMENTO_ORIGINALE IS NULL AND @FASE_ISTRUTTORIA =0 AND ID_VARIANTE IS NULL)OR(ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND @FASE_ISTRUTTORIA =1 AND ID_VARIANTE IS NULL))
GROUP BY INV.CODICE 
	

OPEN SPESE_SERVIZI
FETCH NEXT FROM SPESE_SERVIZI 
INTO @SPESA, @CODICE_CODIFICA 
WHILE @@FETCH_STATUS = 0
BEGIN
		
	SELECT @SPESA_CODIFICA = SUM(INV.COSTO_INVESTIMENTO) 
	FROM  vPIANO_INVESTIMENTI INV  
	WHERE INV.CODICE  =@CODICE_CODIFICA AND ID_PROGETTO = @IdProgetto AND 
		((ID_INVESTIMENTO_ORIGINALE IS NULL AND @FASE_ISTRUTTORIA =0 AND ID_VARIANTE IS NULL)OR(ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND @FASE_ISTRUTTORIA =1 AND ID_VARIANTE IS NULL))
	
	IF(@SPESA >= @SPESA_CODIFICA * 0.10) SET @Result =0

  	FETCH NEXT FROM SPESE_SERVIZI
	INTO @SPESA, @CODICE_CODIFICA 
END

CLOSE SPESE_SERVIZI
DEALLOCATE SPESE_SERVIZI 
 
SELECT @Result AS RESULT
END
