CREATE PROCEDURE [dbo].[calcoloStep911_2]
(
	@IdProgetto int,
	@FASE_ISTRUTTORIA int 
)
AS
BEGIN
/*
DIRITTI RICHIESTI MAX 2HA E MIN 1HA

*/
	DECLARE @Risultato INT =0,
	@TOT_SUP DECIMAL(18,2), @TotSupVitata decimal (10,2), @MQ_CONVERSIONE DECIMAL(18,2), @MQ_IMPIANTO DECIMAL(18,2)
	-- sommo gli HA scritti in quantità dell'investimento

	SELECT @MQ_CONVERSIONE=SUM(QUANTITA)
	FROM vPIANO_INVESTIMENTI INV 
		INNER JOIN DETTAGLIO_INVESTIMENTI D ON D.ID_DETTAGLIO_INVESTIMENTO = INV.ID_DETTAGLIO_INVESTIMENTO AND D.ID_CODIFICA_INVESTIMENTO = INV.ID_CODIFICA_INVESTIMENTO AND COD_DETTAGLIO = 'BB'
	WHERE ID_PROGETTO = @IdProgetto AND ((@FASE_ISTRUTTORIA=0 AND INV.ID_INVESTIMENTO_ORIGINALE IS NULL)OR(@FASE_ISTRUTTORIA=1 AND INV.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL)) 
		
	SELECT @MQ_IMPIANTO=SUM(QUANTITA)
	FROM PIANO_INVESTIMENTI INV 
		INNER JOIN DETTAGLIO_INVESTIMENTI D ON D.ID_DETTAGLIO_INVESTIMENTO = INV.ID_DETTAGLIO_INVESTIMENTO AND D.ID_CODIFICA_INVESTIMENTO = INV.ID_CODIFICA_INVESTIMENTO AND COD_DETTAGLIO = 'AA'
	WHERE ID_PROGETTO = @IdProgetto AND ((@FASE_ISTRUTTORIA=0 AND INV.ID_INVESTIMENTO_ORIGINALE IS NULL)OR(@FASE_ISTRUTTORIA=1 AND INV.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL)) 


	SET @TOT_SUP= ISNULL(@MQ_CONVERSIONE ,0)  + ISNULL(@MQ_IMPIANTO ,0)
		
	IF (@TOT_SUP >=10000 AND @TOT_SUP <=20000) SET @Risultato=1
	ELSE SET @Risultato=0
	SELECT @Risultato AS PUNTEGGIO
END
