CREATE   PROCEDURE [dbo].[calcoloStepVariante112_114_1]
@ID_VARIANTE int
AS
 
-- MODIFICHE APPORTATE SOLO AGLI INVESTIMENTI 114 FATTO!!! 

DECLARE @RESULT INT
SET @RESULT =0

DECLARE @ID_PROGETTO INT, @COUNT_A INT,@COUNT_B INT, @COUNT_CODIFICA INT

SET @ID_PROGETTO  = (SELECT ID_PROGETTO FROM VARIANTI WHERE ID_VARIANTE = @ID_VARIANTE)
DECLARE @ID_PROG_CORRENTE_114 INT 

SELECT DISTINCT @ID_PROG_CORRENTE_114 = p.ID_PROGETTO FROM PROGETTO P
	INNER JOIN BANDO B ON B.ID_BANDO = P.ID_BANDO INNER JOIN ZPROGRAMMAZIONE ZP ON ZP.ID =B.ID_PROGRAMMAZIONE AND CODICE = '1.1.4.'
WHERE ID_PROG_INTEGRATO = @ID_PROGETTO

SET @COUNT_A = (SELECT COUNT (*) FROM PIANO_INVESTIMENTI PI WHERE COD_VARIAZIONE IS NOT NULL AND ID_VARIANTE = @ID_VARIANTE )
SET @COUNT_B= (SELECT COUNT (*) FROM PIANO_INVESTIMENTI PI WHERE COD_VARIAZIONE IS NOT NULL AND ID_VARIANTE = @ID_VARIANTE AND ID_PROGETTO = @ID_PROG_CORRENTE_114)

--CORRETTEZZA DELLA CODIFICA MISURA 114
SET @COUNT_CODIFICA = (SELECT COUNT (*) FROM PIANO_INVESTIMENTI PI 
WHERE COD_VARIAZIONE IS NOT NULL AND ID_VARIANTE = @ID_VARIANTE AND ID_PROGETTO = @ID_PROG_CORRENTE_114 AND ID_CODIFICA_INVESTIMENTO IN (228,154) AND ISNULL(COD_VARIAZIONE,'x') != 'A'   )

 IF (@COUNT_CODIFICA >0) SET @RESULT = 0
 ELSE IF (ISNULL(@COUNT_A,0) = ISNULL(@COUNT_B,0)) SET @RESULT = 1
 
SELECT @RESULT AS RESULT
