-- Controllo massimale di spesa su Spese generali (Dettaglio = 06 max 5% totale domanda)
-- UNICO BENEFICIARIO ASSAM CUAA= 01491360424

create PROCEDURE [dbo].[calcoloStepVariante214_3]
@ID_VARIANTE int 
AS
BEGIN

DECLARE @RESULT INT, @COSTO_SPESE_GENERALI DECIMAL(18,2),@IdProgetto int,
		@COSTO_TOTALE DECIMAL (18,2), @CUAA VARCHAR(16)
select @IdProgetto = id_progetto from varianti where id_variante = @ID_VARIANTE



SET @RESULT =1 --PONGO LO STEP NN VERIFICATO
 SELECT @CUAA= IMP.CUAA FROM PROGETTO P INNER JOIN IMPRESA IMP ON P.ID_IMPRESA =IMP.ID_IMPRESA  WHERE ID_PROGETTO = @IdProgetto

IF (@CUAA  = '01491360424')
	BEGIN

	SET @COSTO_TOTALE = (SELECT SUM (ISNULL(COSTO_INVESTIMENTO,0)) FROM PIANO_INVESTIMENTI I			 
						 WHERE I.ID_VARIANTE = @ID_VARIANTE and isnull(COD_VARIAZIONE,'x') !='A')

	SET @COSTO_SPESE_GENERALI = (SELECT SUM (ISNULL(COSTO_INVESTIMENTO,0)) FROM PIANO_INVESTIMENTI PI
									INNER JOIN VPROGETTO P ON P.ID_PROGETTO = PI.ID_PROGETTO 
									INNER JOIN CODIFICA_INVESTIMENTO C ON C.ID_CODIFICA_INVESTIMENTO = PI.ID_CODIFICA_INVESTIMENTO 
									INNER JOIN DETTAGLIO_INVESTIMENTI D ON C.ID_CODIFICA_INVESTIMENTO = D.ID_CODIFICA_INVESTIMENTO and d.ID_DETTAGLIO_INVESTIMENTO =pi.ID_DETTAGLIO_INVESTIMENTO  AND D.COD_DETTAGLIO ='06' 
									WHERE pI.ID_VARIANTE = @ID_VARIANTE and isnull(COD_VARIAZIONE,'x') !='A')
							 
 
    IF(isnull(@COSTO_SPESE_GENERALI,0) > (isnull(@COSTO_TOTALE,0) * 0.05) )SET @RESULT = 0 
		 
	END
 ELSE SET @RESULT = 0 

 SELECT   @RESULT AS RESULT
	
END
