CREATE  PROCEDURE [dbo].[calcoloStep123_20]
@IdProgetto int, 
@FASE_ISTRUTTORIA INT = 0
AS
BEGIN

--  123 - CONTROLLO % PREVISTA PER ATTIVITà ct

DECLARE @FATTURATO_PRODOTTI DECIMAL (20,2), @RESULT INT,  @FATTURATO_CT DECIMAL(18,2), @ANNO_PRES INT
SET @RESULT =0  --- NON VERIFICATO

SELECT @FATTURATO_CT = PP.VALORE
FROM PRIORITA_X_PROGETTO PP 
WHERE ID_PROGETTO = @IdProgetto AND PP.ID_PRIORITA = 1172

IF (@FATTURATO_CT IS NULL )SET @RESULT=0
ELSE BEGIN
   SELECT @ANNO_PRES =YEAR(DATA)
   FROM PROGETTO P  INNER JOIN PROGETTO_STORICO S ON  P.ID_PROGETTO = S.ID_PROGETTO 
   where P.ID_PROGETTO = @IdProgetto AND COD_STATO IN ('P','L')
   ORDER BY S.ID DESC 	
  
	 SELECT @FATTURATO_PRODOTTI = SUM(FATTURATO)/SUM(C_ANNO)
	 FROM ( SELECT SUM(isnull(PV.VALORE_PROPRIO,0) + isnull(PV.VALORE_DA_ACCORDI,0)) FATTURATO , COUNT(DISTINCT ANNO ) C_ANNO
			FROM PRODOTTI_VENDITE PV 
			WHERE PV.ID_PROGETTO = @IdProgetto AND MATERIA_PRIMA = 0 AND ANNO > @ANNO_PRES 
			GROUP BY ANNO 
	 ) AS PROD
  
	  IF(@FATTURATO_CT >= @FATTURATO_PRODOTTI/2) SET @RESULT=0
	  ELSE SET @RESULT=1
END
 
SELECT @RESULT AS RESULT
END
