--SAL  111 a assam   
-- noleggio o costo di reintegrazione di attrezzature, mezzi di trasporto, strumenti didattici ed informatici, macchine e strumenti dimostrativi per un massimo del 10% del costo del progetto

CREATE   PROCEDURE [dbo].[calcoloRequisitoPagamento111_5]
@ID_DOMANDA_PAGAMENTO int
AS
BEGIN
-- DECLARE  @ID_DOMANDA_PAGAMENTO int
--SET  @ID_DOMANDA_PAGAMENTO = 1183
	DECLARE @ID_PROGETTO INT , @IMPORTO_RICHIESTO DECIMAL (18,2) , @ANNO INT, @IMPORTO_TOTALE  DECIMAL (18,2), @DATA_ULTIMA_MODIFICA DATETIME
	DECLARE @RESULT INT

SET @RESULT =1  -- IMPONGO LO STEP   VERIFICATO
SELECT @ID_PROGETTO =ID_PROGETTO, @DATA_ULTIMA_MODIFICA=DATA_MODIFICA FROM DOMANDA_DI_PAGAMENTO WHERE ID_DOMANDA_PAGAMENTO=@ID_DOMANDA_PAGAMENTO
SET @ANNO =DATEPART(YEAR,@DATA_ULTIMA_MODIFICA)-1
 
SET @IMPORTO_RICHIESTO=(SELECT SUM(ISNULL(IMPORTO_RICHIESTO,0) )
						FROM  PIANO_INVESTIMENTI  PI inner join   
							PAGAMENTI_RICHIESTI  PR  ON PI.ID_INVESTIMENTO = PR.ID_INVESTIMENTO 
						WHERE ID_PROGETTO = @ID_PROGETTO  AND  ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO AND
							  DESCRIZIONE LIKE  '%'+CAST (@ANNO  AS  CHAR(4)) + '%'    AND PI.COD_TIPO_INVESTIMENTO = 1 AND  
							  ID_DETTAGLIO_INVESTIMENTO IN (SELECT ID_DETTAGLIO_INVESTIMENTO 
															FROM CODIFICA_INVESTIMENTO CI INNER JOIN 
																DETTAGLIO_INVESTIMENTI DI ON (CI.ID_CODIFICA_INVESTIMENTO = DI.ID_CODIFICA_INVESTIMENTO)   
														    WHERE CI.ID_BANDO = (SELECT ID_BANDO FROM PROGETTO WHERE ID_PROGETTO = @ID_PROGETTO) AND DI.COD_DETTAGLIO = '5'))
SET @IMPORTO_TOTALE =(SELECT SUM(ISNULL(IMPORTO_RICHIESTO,0) )
					  FROM PIANO_INVESTIMENTI  PI INNER JOIN 
							PAGAMENTI_RICHIESTI  PR  ON PI.ID_INVESTIMENTO = PR.ID_INVESTIMENTO 
						WHERE ID_PROGETTO = @ID_PROGETTO  AND  ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO AND 
							 DESCRIZIONE LIKE '%'+CAST(@ANNO AS CHAR(4))+ '%' AND PI.COD_TIPO_INVESTIMENTO = 1 )   
			
IF( ISNULL( @IMPORTO_RICHIESTO,0) >(@IMPORTO_TOTALE * 0.10) )  SET @RESULT=0
SELECT @RESULT
END
