CREATE PROCEDURE [dbo].[calcoloStepVarianteATS_3]
@ID_VARIANTE int
AS
BEGIN

DECLARE @result int, @TOTALE_INVESTIMENTO decimal(10,2), @TOTALE_8 decimal(10,2)
SET @result =1 -- PONGO LO STEP VERIFICATO 

SET @TOTALE_INVESTIMENTO = (SELECT SUM(PIANO_INVESTIMENTI.COSTO_INVESTIMENTO) AS COSTO_INVESTIMENTO
							FROM  PIANO_INVESTIMENTI 
							WHERE PIANO_INVESTIMENTI.COD_TIPO_INVESTIMENTO = 1 AND  
								 ID_DETTAGLIO_INVESTIMENTO NOT IN (722,727,732,737,742) AND ID_VARIANTE = @ID_VARIANTE  AND isnull( COD_VARIAZIONE,'x')!='A' )
 
SET @TOTALE_8 =(SELECT ISNULL(SUM(PI.COSTO_INVESTIMENTO),0)
				FROM PIANO_INVESTIMENTI PI 
				WHERE PI.COD_TIPO_INVESTIMENTO = 1 AND ID_VARIANTE =@ID_VARIANTE  AND isnull(PI.COD_VARIAZIONE,'x')!='A' 
				AND PI.ID_SPECIFICA_INVESTIMENTO IN (347,408,417,426,435 ))
  
IF(@TOTALE_8 > @TOTALE_INVESTIMENTO*0.05 ) SET @result =0 

SELECT @result AS RESULT

END
