CREATE PROCEDURE [dbo].[calcoloStep4132_A1_B]
@IdProgetto int,
@fase_istruttoria int =0
AS
BEGIN
--

DECLARE @Result int,
		@CONTAA1 INT, 
		@CONTAB INT

SET @Result = 1 -- Impongo lo Step  verificato
SELECT @CONTAA1= (select COUNT(*) AS CONTAa1 FROM vPIANO_INVESTIMENTI I WHERE 
((I.ID_INVESTIMENTO_ORIGINALE IS NULL AND @FASE_ISTRUTTORIA=0 AND ID_VARIANTE IS NULL)OR( I.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND @FASE_ISTRUTTORIA =1 AND ID_VARIANTE IS NULL) )
AND (I.COD_TIPO_INVESTIMENTO = 1) AND (I.ID_PROGETTO = @IdProgetto) AND CODICE IN ('A1','AC'))

SELECT @CONTAB= (select COUNT(*) AS CONTAa1 FROM vPIANO_INVESTIMENTI I WHERE 
((I.ID_INVESTIMENTO_ORIGINALE IS NULL AND @FASE_ISTRUTTORIA=0 AND ID_VARIANTE IS NULL)OR( I.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND @FASE_ISTRUTTORIA =1 AND ID_VARIANTE IS NULL) )
AND (I.COD_TIPO_INVESTIMENTO = 1) AND (I.ID_PROGETTO = @IdProgetto) AND CODICE IN ('B1','B2','BC'))

    
IF((ISNULL(@CONTAA1, 0) >0) AND (ISNULL(@CONTAB, 0) = 0)) OR ((ISNULL(@CONTAA1, 0) =0) AND (ISNULL(@CONTAB, 0) > 0))
 SET @Result = 1
 ELSE SET @Result = 0
 
SELECT @Result AS RESULT
END
