CREATE PROCEDURE [dbo].[calcoloRequisitoPagamento112_Fatturato]
@ID_DOMANDA_PAGAMENTO int
AS
BEGIN

-- 112 - bloccare bilancio

DECLARE @Result int,@IdProgetto int,@IdImpresa INT,@ID_FATTURATO INT,@DATA_PRESENTAZIONE DATETIME 
 
SET @Result = 1 -- Impongo lo Step VERIFICATO
SET @IdProgetto= (SELECT ID_PROGETTO FROM DOMANDA_DI_PAGAMENTO WHERE ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO)
SET @IdImpresa = (SELECT TOP(1) ID_IMPRESA FROM PROGETTO WHERE ID_PROGETTO =@IdProgetto  )

IF( (SELECT COUNT (*) FROM FATTURATO_AZIENDA WHERE ID_IMPRESA = @IdImpresa ) >0)
BEGIN 
SELECT TOP(1) @ID_FATTURATO = ID_FATTURATO, @DATA_PRESENTAZIONE =DATA_MODIFICA 
FROM FATTURATO_AZIENDA WHERE ID_IMPRESA =@IdImpresa  ORDER BY ANNO DESC
	IF(DATEPART(yyyy,@DATA_PRESENTAZIONE)>= (SELECT DATEPART(yyyy,DATA_MODIFICA)-1 FROM DOMANDA_DI_PAGAMENTO WHERE ID_DOMANDA_PAGAMENTO =@ID_DOMANDA_PAGAMENTO))
		SET @Result = 1 
	ELSE 
		SET @Result = 0
END ELSE 
		SET @Result = 0
SELECT @Result AS RESULT
END
