CREATE PROCEDURE [dbo].[calcoloStepVariante124pabs]
(
 @ID_VARIANTE int
)
AS
BEGIN

DECLARE @RESULT int,@SPESEQUOTA int,@SPESE int,@SPESENOQUOTA int

--- Inserito valore quota per divulgazione ASSAM dove previsto 124PABS
SET @RESULT = 0 -- PONGO LO STEP IN STATO NON VERIFICATO

SELECT @SPESEQUOTA= COUNT(VALORE)
FROM PRIORITA_X_INVESTIMENTI PI 
	INNER JOIN vPIANO_INVESTIMENTI VPI on VPI.ID_INVESTIMENTO = PI.ID_INVESTIMENTO 
WHERE VPI.ID_VARIANTE =@ID_VARIANTE AND ISNULL(COD_VARIAZIONE,'x' )!='A' AND
	PI.ID_PRIORITA = 733 AND VPI.CODICE in ('1A','1B','1C','1D','1E','1F','1G','1H','1I','1L','1M','1N','1O') AND VALORE IS NOT NULL 
	
 SELECT @SPESE =  COUNT(ID_INVESTIMENTO)
 FROM VPIANO_INVESTIMENTI VPI
 WHERE VPI.ID_VARIANTE =@ID_VARIANTE AND ISNULL(COD_VARIAZIONE,'x' )!='A' AND
	 CODICE in ('1A','1B','1C','1D','1E','1F','1G','1H','1I','1L','1M','1N','1O') 
 
 SELECT @SPESENOQUOTA= COUNT(VALORE) 
 FROM PRIORITA_X_INVESTIMENTI PI 
		INNER JOIN vPIANO_INVESTIMENTI VPI on VPI.ID_INVESTIMENTO = PI.ID_INVESTIMENTO
		INNER JOIN DETTAGLIO_INVESTIMENTI DI ON (DI.ID_DETTAGLIO_INVESTIMENTO=VPI.ID_DETTAGLIO_INVESTIMENTO) 
WHERE VPI.ID_VARIANTE =@ID_VARIANTE AND ISNULL(COD_VARIAZIONE,'x' )!='A' AND
      PI.ID_PRIORITA = 733 AND VPI.CODICE in ('A','B','C','D','E','F','G','H','I','L','M','N','O','P') AND 
	  VALORE IS NOT NULL AND VALORE != 0


IF((@SPESEQUOTA  = @SPESE) and (@SPESENOQUOTA =0))SET @RESULT =1
ELSE  SET @RESULT=0
SELECT @RESULT
END
