CREATE  PROCEDURE [dbo].[calcoloRequisitoPagamento112_5]
@ID_DOMANDA_PAGAMENTO int
AS
BEGIN

DECLARE @ID_PROGETTO INT, @CODICE INT,@RESULT INT,@PROROGA_12 int =0,
		@DATA_FINE_INTERVENTI DATETIME,@DATA_GRADUATORIA DATETIME, @PROROGA_6 INT=0
SET @RESULT = 0 -- IMPONGO LO STEP NON VERIFICATO		 
--la data specificata di fine interventi programmati deve essere > della data di inizio rendicontazione perchè è un saldo
-- proroga di 6 mesi id_requisito = 156
 
SELECT @DATA_GRADUATORIA= VAL_DATA FROM DOMANDA_PAGAMENTO_REQUISITI WHERE ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO AND ID_REQUISITO =144
SELECT @DATA_FINE_INTERVENTI=VAL_DATA FROM DOMANDA_PAGAMENTO_REQUISITI WHERE ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO  AND ID_REQUISITO =135
SELECT @PROROGA_6=CASE WHEN COUNT(*)>0 THEN 6 ELSE 0 END  FROM DOMANDA_PAGAMENTO_REQUISITI WHERE ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO  AND ID_REQUISITO =156
SELECT @PROROGA_12=CASE WHEN COUNT(*)>0 THEN 12 ELSE 0 END  FROM DOMANDA_PAGAMENTO_REQUISITI WHERE ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO AND ID_REQUISITO =168
IF(@PROROGA_6 >0 AND @PROROGA_12>0)SET @PROROGA_6 =0 
 
IF((@DATA_FINE_INTERVENTI)<=(SELECT DATA_MODIFICA FROM DOMANDA_DI_PAGAMENTO WHERE ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO ))
	BEGIN 
	 SET @RESULT=(SELECT 'DIFF' = CASE WHEN DATEDIFF(DAY, DATEADD(MM,36+@PROROGA_6+@PROROGA_12 ,(@DATA_GRADUATORIA)),(@DATA_FINE_INTERVENTI))<=0 THEN 1 ELSE 0 END)
	END 
-- autorizzazione data da Sileoni con mail data Sat, 8 Mar 2014 11:54:34 - prot. 35518
	IF (@ID_DOMANDA_PAGAMENTO=2746) SET @RESULT=1
SELECT @RESULT
END
