CREATE PROCEDURE [dbo].[calcoloStepVariante221_13]
(
	@IdProgetto int,
	@ID_VARIANTE int,
	@FASE_ISTRUTTORIA INT =0
)
AS
BEGIN
 
 --CONTROLLO STORICIZZAZIONE DEL PIANO COLTURALE
DECLARE @RESULT int, @ID_IMPRESA INT, @DATA_ULTIMA_MODIFICA DATETIME,@DATA_STO DATETIME
SET @RESULT = 1 -- PONGO LO STEP IN STATO VERIFICATO

SET @IdProgetto= ( SELECT ID_PROGETTO FROM VARIANTI WHERE ID_VARIANTE= @ID_VARIANTE )


SELECT @ID_IMPRESA=ID_IMPRESA FROM PROGETTO P WHERE ID_PROGETTO = @IdProgetto 
IF(@FASE_ISTRUTTORIA =0)
BEGIN 
  SELECT @DATA_ULTIMA_MODIFICA =P.DATA FROM PROGETTO_STORICO P WHERE P.ID_PROGETTO =@IdProgetto AND COD_STATO = 'P'
  SELECT  @DATA_STO = P.DATA_FINE FROM (SELECT MAX(ID_RIF) ID_PS_MAX
  FROM PIANO_COLTURALE_STORICO WHERE ID_IMPRESA=@ID_IMPRESA AND (DATA_INIZIO <GETDATE()))PS INNER JOIN PIANO_COLTURALE_STORICO P ON P.ID_RIF =PS.ID_PS_MAX 
  IF(@DATA_STO IS NULL)SET @RESULT =0 
END
ELSE BEGIN 
 SELECT @DATA_ULTIMA_MODIFICA =DATA FROM PROGETTO_STORICO P WHERE P.ID_PROGETTO =@IdProgetto AND COD_STATO IN ('A','B') ORDER BY ID DESC
 SELECT @DATA_STO = P.DATA_FINE FROM (SELECT MAX(ID_RIF) ID_PS_MAX FROM PIANO_COLTURALE_STORICO WHERE ID_IMPRESA=@ID_IMPRESA AND (DATA_INIZIO <@DATA_ULTIMA_MODIFICA))PS INNER JOIN PIANO_COLTURALE_STORICO P ON P.ID_RIF =PS.ID_PS_MAX 
 IF(@DATA_STO IS NULL)SET @RESULT =0 

END
SELECT @RESULT
END
