CREATE PROCEDURE [dbo].[calcoloStepVariante123_8]
 @ID_VARIANTE int
AS
BEGIN

-- 123 a) verifica sostenibilità economica investimento: (tot. FISSI/30 + tot. MOBILI/10) < 15% Fatturato ex-post

DECLARE @result int, @COUNT_BILANCI INT,@IdProgetto INT 
DECLARE @Rata  decimal(15,2)
DECLARE @PLV_RICAVI_VENDITA decimal(15,2)

SELECT @IdProgetto = ID_PROGETTO FROM VARIANTI WHERE ID_VARIANTE =@ID_VARIANTE

SET @Rata = (SELECT ISNULL(SUM((CASE I.MOBILE
					WHEN 1 THEN   (I.COSTO_INVESTIMENTO + I.SPESE_GENERALI)  / 10 
					WHEN 0 THEN (I.COSTO_INVESTIMENTO + I.SPESE_GENERALI)  / 30
					ELSE (I.COSTO_INVESTIMENTO + I.SPESE_GENERALI)  / 30
					END)) , 0)
			FROM VPIANO_INVESTIMENTI I  
				WHERE I.ID_VARIANTE =@ID_VARIANTE AND  isnull(COD_VARIAZIONE,'x')!='A' AND I.COD_TIPO_INVESTIMENTO = 1                     )	
SET @PLV_RICAVI_VENDITA= (SELECT   ISNULL(SUM(PLV_RICAVI_VENDITA),0)/COUNT(*) AS RICAVI 
FROM BILANCIO_INDUSTRIALE WHERE PREVISIONALE = 1 AND ID_PROGETTO = @IdProgetto )

IF (@Rata < (@PLV_RICAVI_VENDITA * 0.15)) SET @result = 1
ELSE SET @result = 0

SELECT @result AS RESULT

END
