--311 b - Progetto con spesa per investimento + spese tecniche > a € 1.300.000,00 e presenza di impianti fotovoltaici

CREATE PROCEDURE [dbo].[calcoloStep311_B_3]
@IdProgetto int
AS
BEGIN
 
DECLARE @result INT, @COSTO_INVESTIMENTO DECIMAL (18,2), @count int
SET @result =1
 
SET @COSTO_INVESTIMENTO = ( SELECT     SUM(PIANO_INVESTIMENTI.COSTO_INVESTIMENTO + PIANO_INVESTIMENTI.SPESE_GENERALI ) AS COSTO  
							FROM  PIANO_INVESTIMENTI INNER JOIN PROGETTO ON PIANO_INVESTIMENTI.ID_PROGETTO = PROGETTO.ID_PROGETTO
							WHERE PROGETTO.ID_PROGETTO = @IdProgetto AND PIANO_INVESTIMENTI.ID_INVESTIMENTO_ORIGINALE is null )

 
IF(@COSTO_INVESTIMENTO >1300000 )
begin 			 
set @count = (SELECT    count(*) 
			 FROM  PIANO_INVESTIMENTI INNER JOIN PROGETTO ON PIANO_INVESTIMENTI.ID_PROGETTO = PROGETTO.ID_PROGETTO
			 WHERE PROGETTO.ID_PROGETTO = @IdProgetto AND 
				PIANO_INVESTIMENTI.ID_INVESTIMENTO_ORIGINALE is null and PIANO_INVESTIMENTI.ID_CODIFICA_INVESTIMENTO  =234)
if(@count>0)
		set @result =0
end 
SELECT @result AS RESULT

END
