CREATE PROCEDURE [dbo].[calcoloStepVariante112_121_3]
@ID_VARIANTE int
AS
	-- 112 - 121 - verifica massimale investimento fotovoltaico:
	-- a) La somma degli investimenti aventi come specifica "fotovoltaico" non può superare i 400000€
    -- b) Il contributo ammissibile sul fotovoltatico non può superare il 30% del contributo ammissibile totale
    

DECLARE @RESULT INT
--SET @RESULT =1

DECLARE @IdProgetto INT
/*SET @IdProgetto=356*/
SET @IdProgetto = ( SELECT ID_PROGETTO FROM VARIANTI WHERE ID_VARIANTE = @ID_VARIANTE )

-- TROVO IL PROGETTO INTEGRATO

DECLARE @ID_PROG_CORRENTE_121 INT, @ID_BANDO_121 INT 

SELECT DISTINCT @ID_PROG_CORRENTE_121 = p.ID_PROGETTO, @ID_BANDO_121=P.ID_BANDO FROM PROGETTO P
	INNER JOIN BANDO B ON B.ID_BANDO = P.ID_BANDO INNER JOIN ZPROGRAMMAZIONE ZP ON ZP.ID =B.ID_PROGRAMMAZIONE AND CODICE = '1.2.1.'
WHERE ID_PROG_INTEGRATO = @IdProgetto

DECLARE @COSTO_INVESTIMENTI_FOTOVOLTAICI DECIMAL(18,2)
DECLARE @COSTO_INVESTIMENTI_TOTALE DECIMAL(18,2)
DECLARE @COSTO_INVESTIMENTO DECIMAL(18,2)
DECLARE @ID_SPECIFICA INT

DECLARE INVESTIMENTO CURSOR FOR
(	SELECT COSTO_INVESTIMENTO,/*CONTRIBUTO_RICHIESTO,*/ID_SPECIFICA_INVESTIMENTO 
	FROM PIANO_INVESTIMENTI I
	WHERE I.ID_PROGETTO=@ID_PROG_CORRENTE_121 AND COD_TIPO_INVESTIMENTO = 1 
		AND I.ID_VARIANTE = @ID_VARIANTE AND isnull(COD_VARIAZIONE,'x')!='A'  
 )

OPEN INVESTIMENTO
FETCH NEXT FROM INVESTIMENTO
INTO @COSTO_INVESTIMENTO,/*@CONTRIBUTO,*/@ID_SPECIFICA
WHILE @@FETCH_STATUS = 0
BEGIN
	SET @COSTO_INVESTIMENTI_TOTALE=@COSTO_INVESTIMENTI_TOTALE+@COSTO_INVESTIMENTO
	--SET @CONTRIBUTO_TOTALE=@CONTRIBUTO_TOTALE+@CONTRIBUTO
	IF(@ID_SPECIFICA=238 or @ID_SPECIFICA=326  OR @ID_SPECIFICA =879 OR @ID_SPECIFICA=1395 )
	BEGIN
		SET @COSTO_INVESTIMENTI_FOTOVOLTAICI=@COSTO_INVESTIMENTI_FOTOVOLTAICI+@COSTO_INVESTIMENTO
		--SET @CONTRIBUTO_INVESTIMENTI_FOTOVOLTAICI=@CONTRIBUTO_INVESTIMENTI_FOTOVOLTAICI+@CONTRIBUTO
	END
	FETCH NEXT FROM INVESTIMENTO
	INTO @COSTO_INVESTIMENTI_TOTALE,/*@CONTRIBUTO_TOTALE,*/@ID_SPECIFICA
END
CLOSE INVESTIMENTO
DEALLOCATE INVESTIMENTO

SET @RESULT=CASE WHEN @COSTO_INVESTIMENTI_FOTOVOLTAICI>400000 OR
				--@CONTRIBUTO_INVESTIMENTI_FOTOVOLTAICI>(@CONTRIBUTO_TOTALE*0.3)THEN 0
				@COSTO_INVESTIMENTI_FOTOVOLTAICI>(@COSTO_INVESTIMENTI_TOTALE*0.3)THEN 0
				ELSE 1 END
SELECT @RESULT
