CREATE PROCEDURE [dbo].[calcoloPriorita413_2]
(
@IdProgetto int,
@fase_istruttoria bit,
@IdVariante INT 
)
AS
BEGIN

-- - Investimenti nelle aree D e C3 x il 51% sul totale degli investimenti utilizzato da gal piceno
--declare @IdProgetto int, 
--@FASE_ISTRUTTORIA INT 
--set @IdProgetto  = 834 
-- set @FASE_ISTRUTTORIA   =0

DECLARE  @Punteggio decimal(10,2), 
		 @COSTO DECIMAL(18,2),
		 @TIPO_AREA CHAR(2),
		 @SPESE_D_C3 decimal(18,2),
		 @SPESE_ALTRO decimal(18,2),
		 @COSTO_PROGETTO decimal (18,2)
 
-- Calcolo delle ore totali per le attività connesse
DECLARE COMUNI_TIPO_AREA CURSOR FOR
	SELECT SUM(ISNULL(COSTO_INVESTIMENTO,0)) ,TIPO_AREA
	FROM PIANO_INVESTIMENTI AS I INNER JOIN
	(SELECT MAX(LOC.ID_LOCALIZZAZIONE) AS ID_LOCALIZZAZIONE, LOC.ID_INVESTIMENTO
	 FROM LOCALIZZAZIONE_INVESTIMENTO AS LOC INNER JOIN
		PIANO_INVESTIMENTI AS PI ON LOC.ID_INVESTIMENTO = PI.ID_INVESTIMENTO
	 WHERE (PI.ID_PROGETTO = @IdProgetto)  AND ((@fase_istruttoria=0 AND PI.ID_INVESTIMENTO_ORIGINALE IS NULL AND ID_VARIANTE IS NULL )OR 
		(@fase_istruttoria=1 AND (PI.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL AND @IdVariante IS NULL) OR 
		(ID_VARIANTE = @IdVariante AND @IdVariante IS NOT NULL AND ISNULL(COD_VARIAZIONE, 'X' ) != 'A'  ) ) )
	GROUP BY LOC.ID_INVESTIMENTO) AS LOCAL ON LOCAL.ID_INVESTIMENTO = I.ID_INVESTIMENTO INNER JOIN
	vLOCALIZZAZIONE_INVESTIMENTO AS L ON L.ID_LOCALIZZAZIONE = LOCAL.ID_LOCALIZZAZIONE INNER JOIN
	vCOMUNI ON L.ID_COMUNE = vCOMUNI.ID_COMUNE  
	GROUP BY TIPO_AREA

OPEN COMUNI_TIPO_AREA
FETCH NEXT FROM COMUNI_TIPO_AREA 
INTO @COSTO,@TIPO_AREA
WHILE @@FETCH_STATUS = 0
BEGIN
	 IF ( @TIPO_AREA = 'C3' OR @TIPO_AREA= 'D')  
		 SET @SPESE_D_C3 = ISNULL(@SPESE_D_C3,0) + @COSTO
	ELSE SET @SPESE_ALTRO =ISNULL(@SPESE_ALTRO,0) + @COSTO
	FETCH NEXT FROM COMUNI_TIPO_AREA
	INTO @COSTO,@TIPO_AREA
END
CLOSE COMUNI_TIPO_AREA
DEALLOCATE COMUNI_TIPO_AREA 

SELECT @COSTO_PROGETTO = SUM(ISNULL(COSTO_INVESTIMENTO,0))FROM PIANO_INVESTIMENTI PI WHERE
	   (PI.ID_PROGETTO = @IdProgetto)  AND ((@fase_istruttoria=0 AND PI.ID_INVESTIMENTO_ORIGINALE IS NULL AND ID_VARIANTE IS NULL )OR 
		(@fase_istruttoria=1 AND (PI.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL AND @IdVariante IS NULL) OR 
		(ID_VARIANTE = @IdVariante AND @IdVariante IS NOT NULL AND ISNULL(COD_VARIAZIONE, 'X' ) != 'A'  ) ) )

IF (ISNULL(@SPESE_D_C3,0) > (ISNULL(@COSTO_PROGETTO,0) )/2) SET @Punteggio = 1
ELSE SET  @Punteggio= 0
SELECT @Punteggio AS PUNTEGGIO
END
