CREATE PROCEDURE [dbo].[calcoloPriorita413_1_S]
	(@IdProgetto int,
	@fase_istruttoria bit,
	@IdVariante int =NULL)
AS
BEGIN
--Spese relative all’utilizzo di tecnologie di informazione e comunicazione di importo totale pari ad almeno il 4% sul totale
-- non obbligatorio

--declare @IdProgetto int, 
--@FASE_ISTRUTTORIA INT 

--set @IdProgetto = 834 
-- set @FASE_ISTRUTTORIA =0

DECLARE @result int , @COSTO_INVESTIMENTO DECIMAL(18,2), 
@SPESE_TIC DECIMAL (18,2)
SET @result = 1

SELECT @COSTO_INVESTIMENTO=SUM(ISNULL(COSTO_INVESTIMENTO,0))  FROM PIANO_INVESTIMENTI INV 
WHERE ID_PROGETTO = @IdProgetto AND 
	  (( @FASE_ISTRUTTORIA=0 AND INV.ID_INVESTIMENTO_ORIGINALE IS NULL AND ID_VARIANTE IS NULL ) OR
	  (@FASE_ISTRUTTORIA = 1 AND (INV.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND @IdVariante IS NULL AND  ID_VARIANTE IS NULL ) OR 
								 (@IdVariante IS NOT NULL  AND  ID_VARIANTE=@IdVariante AND ISNULL(COD_VARIAZIONE, 'X' ) != 'A' )))
  
SELECT @SPESE_TIC= SUM(ISNULL(COSTO_INVESTIMENTO,0)) 
	 FROM VPIANO_INVESTIMENTI INV INNER JOIN DETTAGLIO_INVESTIMENTI D ON D.ID_DETTAGLIO_INVESTIMENTO = INV.ID_DETTAGLIO_INVESTIMENTO 
	 WHERE ID_PROGETTO = @IdProgetto AND D.COD_DETTAGLIO IN ('b','d')AND 	 
	  (( @FASE_ISTRUTTORIA=0 AND INV.ID_INVESTIMENTO_ORIGINALE IS NULL AND ID_VARIANTE IS NULL ) OR
	  (@FASE_ISTRUTTORIA = 1 AND (INV.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND @IdVariante IS NULL AND  ID_VARIANTE IS NULL ) OR 
								 (@IdVariante IS NOT NULL  AND  ID_VARIANTE=@IdVariante AND ISNULL(COD_VARIAZIONE, 'X' ) != 'A' )))
IF(ISNULL(@SPESE_TIC,0) < (@COSTO_INVESTIMENTO*4 /100)) 
SET @result = 0

SELECT @result AS RESULT
END
