CREATE  PROCEDURE [dbo].[calcoloStep321a_PR_AP]
@IdProgetto int, 
@FASE_ISTRUTTORIA INT =0
AS
BEGIN

DECLARE @result int, 
		@ZONA INT,
		@COSTO_TOT_PROGETTO INT

--- ID PRIORITA' () 986 PLURIVALORE CHE IDENTIFICA LA ZONA 
--- ZONA D ---> ID_VALORE 1034
--- ZONA C --> ID_VALORE 1035

SET @result = 0 -- NON VERIFICATO

SET @ZONA = (select ID_VALORE from priorita_x_progetto WHERE ID_PROGETTO = @IdProgetto and ID_PRIORITA = 1043)

SET @COSTO_TOT_PROGETTO = (SELECT ISNULL(SUM(COSTO_INVESTIMENTO),0) + ISNULL( SUM (SPESE_GENERALI),0)  AS Totale_Investimenti FROM PROGETTO P INNER JOIN VPIANO_INVESTIMENTI I ON (P.ID_PROGETTO=I.ID_PROGETTO) WHERE I.ID_INVESTIMENTO_ORIGINALE IS NULL AND I.COD_TIPO_INVESTIMENTO = 1 AND (P.ID_PROGETTO=@IdProgetto))

IF ((@ZONA = '1034' AND @COSTO_TOT_PROGETTO <= 60000) OR (@ZONA = '1035' AND @COSTO_TOT_PROGETTO <= 40000))
	  SET @result = 1
ELSE
	SET @result = 0			

SELECT @result AS RESULT
END
