CREATE   PROCEDURE [dbo].[calcoloStep132_5]
(
@IdProgetto int,
@FASE_ISTRUTTORIA INT=0
)
AS
BEGIN

--DECLARE @IdProgetto int =9407,  @FASE_ISTRUTTORIA INT =1
-- ANNUALITA
 --ID Priorita per anno : 375 - 

DECLARE  @result int
SET @RESULT =1 --PONGO LO STEP VERIFICATO

 DECLARE @COUNT_A  INT, @COUNT_B INT,@COUNT_C int,@COUNT_D int
SET  @COUNT_A = (SELECT COUNT(*)  FROM  PIANO_INVESTIMENTI AS PI INNER JOIN
									   VPRIORITA_X_INVESTIMENTI PXI  ON PI.ID_INVESTIMENTO = PXI.ID_INVESTIMENTO  
									   WHERE (PI.ID_PROGETTO = @IdProgetto )  AND ((PI.ID_INVESTIMENTO_ORIGINALE IS NULL AND @FASE_ISTRUTTORIA =0 AND ID_VARIANTE IS NULL ) OR
											 (PI.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND @FASE_ISTRUTTORIA =1 AND ID_VARIANTE IS NULL) AND ID_PRIORITA IN(799,864,1081)) AND  PXI.DESCRIZIONE  ='2012' )

SET  @COUNT_B = (SELECT COUNT(*)  FROM  PIANO_INVESTIMENTI AS PI INNER JOIN  
										VPRIORITA_X_INVESTIMENTI PXI  ON PI.ID_INVESTIMENTO = PXI.ID_INVESTIMENTO  
										WHERE (PI.ID_PROGETTO = @IdProgetto) AND  ((PI.ID_INVESTIMENTO_ORIGINALE IS NULL AND @FASE_ISTRUTTORIA =0 AND ID_VARIANTE IS NULL ) OR
										(PI.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND @FASE_ISTRUTTORIA =1 AND ID_VARIANTE IS NULL)) AND ID_PRIORITA IN(799,864,1081) AND  PXI.DESCRIZIONE  ='2013' )

SET  @COUNT_C = (SELECT COUNT(*)  FROM  PIANO_INVESTIMENTI AS PI INNER JOIN  
										VPRIORITA_X_INVESTIMENTI PXI  ON PI.ID_INVESTIMENTO = PXI.ID_INVESTIMENTO  
										WHERE (PI.ID_PROGETTO = @IdProgetto) AND  ((PI.ID_INVESTIMENTO_ORIGINALE IS NULL AND @FASE_ISTRUTTORIA =0 AND ID_VARIANTE IS NULL ) OR
										(PI.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND @FASE_ISTRUTTORIA =1 AND ID_VARIANTE IS NULL)) AND ID_PRIORITA IN(799,864,1081) AND  PXI.DESCRIZIONE  ='2014' )
										
SET  @COUNT_D = (SELECT COUNT(*)  FROM  PIANO_INVESTIMENTI AS PI INNER JOIN  
										VPRIORITA_X_INVESTIMENTI PXI  ON PI.ID_INVESTIMENTO = PXI.ID_INVESTIMENTO  
										WHERE (PI.ID_PROGETTO = @IdProgetto) AND  ((PI.ID_INVESTIMENTO_ORIGINALE IS NULL AND @FASE_ISTRUTTORIA =0 AND ID_VARIANTE IS NULL ) OR
										(PI.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND @FASE_ISTRUTTORIA =1 AND ID_VARIANTE IS NULL)) AND ID_PRIORITA IN(799,864,1081) AND  PXI.DESCRIZIONE  ='2015' )

--SELECT @COUNT_A ,@COUNT_B,@COUNT_C,@COUNT_D

IF (ISNULL(@COUNT_A,0)> 0 AND ISNULL(@COUNT_B,0) >0 AND ISNULL(@COUNT_C,0)>0 AND ISNULL(@COUNT_D,0)>0)BEGIN SET @RESULT= 0 END
ELSE IF(ISNULL(@COUNT_A,0)> 0 AND ISNULL(@COUNT_C,0)>0)SET @RESULT=0
ELSE IF(ISNULL(@COUNT_B,0)> 0 AND ISNULL(@COUNT_D,0)>0)SET @RESULT=0

SELECT @RESULT AS RESULT
END
