CREATE PROCEDURE [dbo].[calcoloStep125_3]
@IdProgetto int,
@FASE_ISTRUTTORIA INT
AS
BEGIN
 
--  RISPETTO DEL 10% SPESE TECNICHE
 
DECLARE @RESULT int, @COSTO_INVESTIMENTO DECIMAL (10,2)

SET @RESULT = 1 -- Impongo lo Step verificato
--------------------------------------------------------------------------------------------------------------
DECLARE @COSTO_SPESE_TEC DECIMAL(18,2)=0 

SELECT @COSTO_INVESTIMENTO = SUM(COSTO_INVESTIMENTO) FROM vPIANO_INVESTIMENTI 
WHERE ID_PROGETTO = @IdProgetto AND CODICE IN ('2','3') AND 
		((@FASE_ISTRUTTORIA=0 AND ID_INVESTIMENTO_ORIGINALE IS NULL )OR(@FASE_ISTRUTTORIA=1 AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL))	

SELECT @COSTO_SPESE_TEC = SUM(COSTO_INVESTIMENTO) FROM vPIANO_INVESTIMENTI 
WHERE ID_PROGETTO = @IdProgetto AND CODICE IN ('4') AND 
		((@FASE_ISTRUTTORIA=0 AND ID_INVESTIMENTO_ORIGINALE IS NULL )OR(@FASE_ISTRUTTORIA=1 AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL))			

IF((@COSTO_SPESE_TEC) > (@COSTO_INVESTIMENTO *10)/100) SET @RESULT =0
SELECT @RESULT

END
