CREATE  PROCEDURE [dbo].[calcoloRequisitoPagamento121_1]
@ID_DOMANDA_PAGAMENTO int
AS
BEGIN

	-- 121 Raggiungimento del minimo contributo concesso in graduatoria necessario per richiedere SAL.
	-- Requisiti pagamento esito positivo =1 

	-- USATA anche per la 311 a) e 311 b az. c  ANTICIPO ; 123 SAL

	DECLARE @ID_PROGETTO INT, @ID_VARIANTE INT, @RESULT INT
    DECLARE @CONTRIBUTO_PROGETTO decimal(10,2)

SET @RESULT = 0 -- IMPONGO LO STEP NON VERIFICATO		 

SET @ID_PROGETTO = ( SELECT ID_PROGETTO FROM DOMANDA_DI_PAGAMENTO WHERE ID_DOMANDA_PAGAMENTO=@ID_DOMANDA_PAGAMENTO  )	
--CONTROLLO SE ESISTE UNA VARIANTE
SET @ID_VARIANTE =  (SELECT MAX(ID_VARIANTE) FROM VARIANTI WHERE ID_PROGETTO = @ID_PROGETTO AND APPROVATA =1  AND ANNULLATA =0
)
 
SET @CONTRIBUTO_PROGETTO = ISNULL((SELECT dbo.[calcoloContributoTotaleProgettoCorrelato] (@ID_PROGETTO, 1, @ID_VARIANTE)), 0)
 IF (@CONTRIBUTO_PROGETTO >= 50000)SET @RESULT =1
ELSE SET @RESULT=0
	 
SELECT @RESULT
END
