CREATE PROCEDURE [dbo].[calcoloStepVariante123_16]
@ID_VARIANTE INT 
AS
BEGIN
--  123 - Totale inivestimenti per interventi legati al fotovoltaico

DECLARE  @COSTO_FOTOVOLTAICO DECIMAL (20,2)
		,@RESULT INT, @COSTO DECIMAL(18,2),@IdProgetto INT
		

SET @RESULT =0  --- NON VERIFICATO
SET @COSTO_FOTOVOLTAICO = (SELECT ISNULL( SUM (COSTO_INVESTIMENTO + SPESE_GENERALI) , 0) AS Totale_Investimenti  
				FROM PROGETTO P INNER JOIN  
					vPIANO_INVESTIMENTI I ON (P.ID_PROGETTO=I.ID_PROGETTO)
				WHERE i.ID_VARIANTE =@ID_VARIANTE AND I.COD_TIPO_INVESTIMENTO = 1 AND COD_SPECIFICA IN ('80'))
SELECT @IdProgetto = id_progetto FROM VARIANTI WHERE ID_VARIANTE=@ID_VARIANTE
				
SELECT @COSTO = dbo.calcoloCostoTotaleProgetto (@IdProgetto, 1, @ID_VARIANTE)							

IF(@COSTO_FOTOVOLTAICO > @COSTO * 0.30) SET @RESULT =0
ELSE SET @RESULT =1 

SELECT @RESULT AS RESULT
END
