-- SALDO  221 
-- Spese GENERALI di impianto <=10% Costi impianto
-- Controllo in PRESENAZIONE

CREATE  PROCEDURE [dbo].[calcoloRequisitoPagamento221_2]
@ID_DOMANDA_PAGAMENTO int
AS
BEGIN

-- DECLARE  @ID_DOMANDA_PAGAMENTO int
--SET  @ID_DOMANDA_PAGAMENTO = 626
DECLARE @ID_PROGETTO INT , @SPESEIMPIANTO DECIMAL (18,2) ,@SPESEGENERALI DECIMAL (18,2) , @ANNO INT, @DATA_ULTIMA_MODIFICA DATETIME
DECLARE @RESULT INT


---- IMPORTO_AMMESSO, IMPORTO_RICHIESTO
SET @SPESEIMPIANTO = 0 -- INIZIALIZZO LA VARIABILE		
SET @SPESEGENERALI = 0 -- INIZIALIZZO LA VARIABILE		

SET @RESULT = 0  -- IMPONGO LO STEP NON  VERIFICATO		 
SELECT @ID_PROGETTO =ID_PROGETTO, @DATA_ULTIMA_MODIFICA=DATA_MODIFICA FROM DOMANDA_DI_PAGAMENTO WHERE ID_DOMANDA_PAGAMENTO=@ID_DOMANDA_PAGAMENTO
SET @ANNO =DATEPART(YEAR,@DATA_ULTIMA_MODIFICA)-1

SET @SPESEIMPIANTO = (SELECT SUM( ISNULL(IMPORTO_AMMESSO, PR.IMPORTO_RICHIESTO) )
						FROM PIANO_INVESTIMENTI  PI inner join   PAGAMENTI_RICHIESTI  PR  ON PI.ID_INVESTIMENTO = PR.ID_INVESTIMENTO 
						WHERE ID_PROGETTO = @ID_PROGETTO  AND  ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO
							 AND PI.COD_TIPO_INVESTIMENTO = 1   
							 AND PI.ID_CODIFICA_INVESTIMENTO IN (SELECT ID_CODIFICA_INVESTIMENTO FROM CODIFICA_INVESTIMENTO 
																WHERE ID_BANDO = (SELECT ID_BANDO FROM PROGETTO WHERE ID_PROGETTO = @ID_PROGETTO)AND CODICE = 'a'))
						

SET @SPESEGENERALI= (SELECT SUM( ISNULL(IMPORTO_AMMESSO, PR.IMPORTO_RICHIESTO) )
						FROM PIANO_INVESTIMENTI  PI inner join   PAGAMENTI_RICHIESTI  PR  ON PI.ID_INVESTIMENTO = PR.ID_INVESTIMENTO 
						WHERE ID_PROGETTO = @ID_PROGETTO  AND  ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO
							 AND PI.COD_TIPO_INVESTIMENTO = 1   
							 AND PI.ID_CODIFICA_INVESTIMENTO IN (SELECT ID_CODIFICA_INVESTIMENTO FROM CODIFICA_INVESTIMENTO 
																WHERE ID_BANDO = (SELECT ID_BANDO FROM PROGETTO WHERE ID_PROGETTO = @ID_PROGETTO)AND CODICE = 'b'))																									

IF(@SPESEGENERALI <= ((@SPESEIMPIANTO*10)/100))SET @RESULT=1
SELECT @RESULT
END
