CREATE  PROCEDURE [dbo].[calcoloStep111_121_1]
@IdProgetto int
AS
BEGIN

-- MASSIMALE PER CORSO FORMATIVO

DECLARE @Result int, @ID_CODIFICA_INVESTIMENTO INT , @COSTO DECIMAL (18,2)
SET @Result = 1 -- Impongo lo Step verificato
--------------------------------------------------------------------------------------------------------------
    
 DECLARE CORSO CURSOR FOR
  ( 
		SELECT SUM(COSTO_INVESTIMENTO) AS COSTO , ID_CODIFICA_INVESTIMENTO
		FROM PIANO_INVESTIMENTI PI WHERE ID_PROGETTO =@IdProgetto AND ID_INVESTIMENTO_ORIGINALE IS NULL
		GROUP BY ID_CODIFICA_INVESTIMENTO
   ) 
 
 
OPEN CORSO
FETCH NEXT FROM CORSO 
INTO   @COSTO   ,  @ID_CODIFICA_INVESTIMENTO 
WHILE @@FETCH_STATUS = 0
	BEGIN
	IF (@ID_CODIFICA_INVESTIMENTO IN (410,411,412,413,414,415,416,418,419,420,421,422 )) -- MIN 150;  MAX  281,25
		BEGIN 
			IF(@COSTO<150 OR @COSTO >281.25) SET @Result =0
		END
	 ELSE 
		BEGIN
						IF (@ID_CODIFICA_INVESTIMENTO IN (417))
							BEGIN
								IF(@COSTO<141.25 OR @COSTO >264.84) SET @Result =0
							END
		END 			

	FETCH NEXT FROM CORSO
INTO @COSTO   ,  @ID_CODIFICA_INVESTIMENTO 
END

CLOSE CORSO
DEALLOCATE CORSO 
 
SELECT @Result AS RESULT


END
