create PROCEDURE [dbo].[calcoloStep311_B_2]
@IdProgetto int
AS
BEGIN

-- Nella checklist presentazione la condizione da verificare è la seguente:
-- Tutti gli investimenti fissi 

DECLARE @COSTO_INVESTIMENTO decimal (10,2) , 
		@TOTALE_SPESE decimal (10,2), 
		@SPESE_GENERALI DECIMAL(10,2), 
		@result INT

SET @result = 1 -- IMPONGO LO STEP VERIFICATO

DECLARE SPESE_TECNICHE CURSOR FOR
		( SELECT COSTO_INVESTIMENTO, SPESE_GENERALI FROM vPiano_investimenti where MOBILE = 0 and ID_PROGETTO =  @IdProgetto and ID_INVESTIMENTO_ORIGINALE is NULL )
		
        OPEN SPESE_TECNICHE
		FETCH NEXT FROM SPESE_TECNICHE INTO @COSTO_INVESTIMENTO, @TOTALE_SPESE
		WHILE @@FETCH_STATUS=0 BEGIN
		SELECT 	@COSTO_INVESTIMENTO AS  COSTO_INVESTIMENTO 
          
		 IF (@COSTO_INVESTIMENTO > 200000 )	
				BEGIN 
				SET @SPESE_GENERALI = 200000 * 0.1
				SET @COSTO_INVESTIMENTO = @COSTO_INVESTIMENTO - 200000
					IF(@COSTO_INVESTIMENTO > 300000 )	
						BEGIN 	
							SET @SPESE_GENERALI = @SPESE_GENERALI + (300000 * 0.06)
							SET @COSTO_INVESTIMENTO = @COSTO_INVESTIMENTO - 300000
							SET @SPESE_GENERALI = @SPESE_GENERALI + (@COSTO_INVESTIMENTO * 0.03)
						END
					ELSE 
					SET @SPESE_GENERALI = @SPESE_GENERALI + (@COSTO_INVESTIMENTO * 0.06)

				IF( @SPESE_GENERALI <= @TOTALE_SPESE ) 
					BEGIN 
						SET @result = 0
						break
						END
			
 
				END		 
			
  		FETCH NEXT FROM SPESE_TECNICHE INTO @COSTO_INVESTIMENTO, @TOTALE_SPESE
		END
		CLOSE SPESE_TECNICHE
		DEALLOCATE SPESE_TECNICHE

SELECT @result AS RESULT

END
