CREATE   PROCEDURE [dbo].[calcoloStep133_6] 
(
@IdProgetto int,
@FASE_ISTRUTTORIA INT =0
)
AS
BEGIN
---- CONTROLLO DOTAZIONE FIN 
--§  Limite               0 di Euro per la macrofiliere dei cereali;--
--§  Limite 1.000.000 di Euro per la macrofiliere della carne bovina;--
--§  Limite    500.000 di Euro per la macrofiliere della carne suina;--
--§  Limite 1.000.000 di Euro per la macrofiliere del latte bovino;--
--§  Limite 3.000.000 di Eur, o per la macrofiliere dei prodotti biologici.

--declare @IdProgetto int,
-- @FASE_ISTRUTTORIA INT  
--
--set @IdProgetto=7343
--set @FASE_ISTRUTTORIA=0


DECLARE @CONTRIBUTO_RICHIESTO DECIMAL(18,2),     
@RESULT INT ,
@COD_FILIERA CHAR(3), 
@COSTO_FILIERA DECIMAL(18,2), 
@CUAA_PROMOTORE VARCHAR(16),
@CODICE varchar(3)

SET @RESULT =1 --PONGO LO STEP  VERIFICATO
DECLARE @ID_MANIF INT, @id_filiera int

-- SOLO IL PROMOTORE
SET @ID_MANIF = ( SELECT VP.PUNTEGGIO FROM PRIORITA_X_PROGETTO PP  INNER JOIN VALORI_PRIORITA VP ON VP.ID_PRIORITA = PP.ID_PRIORITA AND VP.ID_PRIORITA= 374 AND PP.ID_VALORE= VP.ID_VALORE
								WHERE  PP.ID_PRIORITA = 374 AND ID_PROGETTO = @IdProgetto  )
SET @CUAA_PROMOTORE =(SELECT  CUAA  FROM  MANIFESTAZIONE_DI_INTERESSE  WHERE ID_BANDO = 116 AND ID_MANIFESTAZIONE = @ID_MANIF)
set @id_filiera =(SELECT  id_filiera  FROM  MANIFESTAZIONE_DI_INTERESSE  WHERE ID_BANDO = 116 AND ID_MANIFESTAZIONE = @ID_MANIF)
  
IF(@CUAA_PROMOTORE != ( SELECT IMP.CUAA FROM PROGETTO P INNER JOIN IMPRESA IMP ON IMP.ID_IMPRESA =P.ID_IMPRESA WHERE ID_PROGETTO = @IdProgetto )) SET @RESULT =0


SET @CONTRIBUTO_RICHIESTO = ( SELECT SUM(isnull(CONTRIBUTO_RICHIESTO ,0)) AS COSTO FROM PIANO_INVESTIMENTI I WHERE ID_PROGETTO = @IdProgetto AND
															 ((@fase_istruttoria =0 AND ID_INVESTIMENTO_ORIGINALE  is null and id_variante is null ) 
															or (@fase_istruttoria =1 AND ID_INVESTIMENTO_ORIGINALE  is not null and id_variante is null )))    
 
SET @CODICE=(SELECT  COD_TIPO_FILIERA FROM FILIERA WHERE ID_FILIERA =@id_filiera  )
 
	IF( @CODICE= 'CBO') BEGIN IF( @CONTRIBUTO_RICHIESTO> 1000000 ) SET @RESULT =0 END
	ELSE BEGIN
					IF( @CODICE= 'CER') BEGIN  IF( @CONTRIBUTO_RICHIESTO> 0 ) SET @RESULT =0 END
					ELSE BEGIN IF( @CODICE = 'CSU') BEGIN  IF( @CONTRIBUTO_RICHIESTO> 500000 ) SET @RESULT =0 END 
											ELSE BEGIN  IF( @CODICE= 'LAB') BEGIN  IF( @CONTRIBUTO_RICHIESTO> 1000000 ) SET @RESULT =0 END  
																	 ELSE BEGIN IF( @CODICE= 'PRB') BEGIN  IF( @CONTRIBUTO_RICHIESTO> 3000000 ) SET @RESULT =0 END 
																				END
														END
								END
 END
SELECT @RESULT AS RESULT
END
