CREATE  PROCEDURE [dbo].[calcoloStep311_B_13]
@IdProgetto int , @FASE_ISTRUTTORIA INT =0
AS
BEGIN


-- 311 B  AZIONE D - 2013 -  sistemazioni di terreno <10% DEGLI INVESTIMENTI FISSI - COSTO SENZA SPESE TECNICHE

DECLARE @Result int , @COSTO_ESTERNO DECIMAL(18,2), @COSTO_FISSI DECIMAL(18,2)
SET @Result = 1 -- Impongo lo Step  verificato
 
SELECT @COSTO_FISSI= SUM(COSTO_INVESTIMENTO) FROM PIANO_INVESTIMENTI INV
	INNER JOIN DETTAGLIO_INVESTIMENTI DI ON DI.ID_CODIFICA_INVESTIMENTO = INV.ID_CODIFICA_INVESTIMENTO AND DI.ID_DETTAGLIO_INVESTIMENTO = INV.ID_DETTAGLIO_INVESTIMENTO
WHERE INV.ID_PROGETTO = @IdProgetto AND DI.COD_DETTAGLIO IN ('A','B') AND
		((@FASE_ISTRUTTORIA = 0 AND ID_INVESTIMENTO_ORIGINALE IS NULL AND ID_VARIANTE IS NULL)OR
		 (@FASE_ISTRUTTORIA = 1 AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL))
		
SELECT @COSTO_ESTERNO= SUM(COSTO_INVESTIMENTO) FROM VPIANO_INVESTIMENTI INV
WHERE INV.ID_PROGETTO = @IdProgetto AND INV.CODICE IN ('SI') AND
		((@FASE_ISTRUTTORIA = 0 AND ID_INVESTIMENTO_ORIGINALE IS NULL AND ID_VARIANTE IS NULL)OR
		 (@FASE_ISTRUTTORIA = 1 AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL))
 
IF(@COSTO_ESTERNO > @COSTO_FISSI*0.10)SET @Result =0
ELSE SET @Result =1

 select @Result 
END
