CREATE PROCEDURE [dbo].[calcoloStep112_121_A1]
@IdProgetto int
AS
/*
FATTO!!! 
DECLARE @IdProgetto INT
SET @IdProgetto =1862*/


DECLARE @ID_PROG_CORRENTE_121 INT, @ID_BANDO_121 INT 

SELECT DISTINCT @ID_PROG_CORRENTE_121 = p.ID_PROGETTO, @ID_BANDO_121=P.ID_BANDO FROM PROGETTO P
		INNER JOIN BANDO B ON B.ID_BANDO = P.ID_BANDO INNER JOIN ZPROGRAMMAZIONE ZP ON ZP.ID =B.ID_PROGRAMMAZIONE AND CODICE = '1.2.1.'
WHERE ID_PROG_INTEGRATO = @IdProgetto

DECLARE @RESULT INT
SET @RESULT=1

DECLARE @TOTALE_INVESTIMENTI DECIMAL(18,2)
SET @TOTALE_INVESTIMENTI=(SELECT ISNULL(SUM(COSTO_INVESTIMENTO),0) FROM PIANO_INVESTIMENTI 
		WHERE ID_PROGETTO=@ID_PROG_CORRENTE_121 AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL)
IF @TOTALE_INVESTIMENTI>0 BEGIN
---CONTROLLO STEP
	IF (SELECT COUNT(*) FROM ITER_PROGETTO WHERE ID_PROGETTO=@IdProgetto AND ID_STEP IN (162,166,167,168,170) AND COD_ESITO='NO')>0
		SET @RESULT=0
END 
SELECT @RESULT
