CREATE PROCEDURE [dbo].[calcoloPriorita911_3]
(
	@IdProgetto int,
	@fase_istruttoria bit,
	@IdVariante int =NULL
)
AS
BEGIN

--- punteggio calcolato in base alla domanda di riferimento

	DECLARE @TOT_SUP DECIMAL(18,2),  @MQ_CONVERSIONE DECIMAL(18,2), @MQ_IMPIANTO DECIMAL(18,2)
			,@ID_BANDO INT,@ID_IMPRESA INT, @Risultato INT
	  	
 	SELECT @MQ_CONVERSIONE=SUM(QUANTITA)
	FROM PIANO_INVESTIMENTI INV 
		INNER JOIN VPROGETTO AS p ON P.ID_PROGETTO=INV.ID_PROGETTO 
		INNER JOIN DETTAGLIO_INVESTIMENTI D ON D.ID_DETTAGLIO_INVESTIMENTO = INV.ID_DETTAGLIO_INVESTIMENTO AND D.ID_CODIFICA_INVESTIMENTO = INV.ID_CODIFICA_INVESTIMENTO AND COD_DETTAGLIO = 'BB'
	WHERE  P.ID_PROGETTO = @IdProgetto 
		  AND ((@FASE_ISTRUTTORIA=0 AND INV.ID_INVESTIMENTO_ORIGINALE IS NULL )
				OR(@FASE_ISTRUTTORIA=1 AND INV.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL AND @IdVariante IS NULL) 
				OR (@IdVariante IS NOT NULL AND ID_VARIANTE=@IdVariante))
		 		
	SELECT @MQ_IMPIANTO=SUM(QUANTITA)
	FROM PIANO_INVESTIMENTI INV 
		INNER JOIN VPROGETTO AS p ON P.ID_PROGETTO=INV.ID_PROGETTO 
		INNER JOIN DETTAGLIO_INVESTIMENTI D ON D.ID_DETTAGLIO_INVESTIMENTO = INV.ID_DETTAGLIO_INVESTIMENTO AND D.ID_CODIFICA_INVESTIMENTO = INV.ID_CODIFICA_INVESTIMENTO AND COD_DETTAGLIO = 'AA'
	WHERE  P.ID_PROGETTO = @IdProgetto 
		  AND ((@FASE_ISTRUTTORIA=0 AND INV.ID_INVESTIMENTO_ORIGINALE IS NULL )
				OR(@FASE_ISTRUTTORIA=1 AND INV.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL AND @IdVariante IS NULL) 
				OR (@IdVariante IS NOT NULL AND ID_VARIANTE=@IdVariante))
		 
	SET @TOT_SUP= ISNULL(@MQ_CONVERSIONE ,0)  + ISNULL(@MQ_IMPIANTO ,0)
    IF(@TOT_SUP > 50000) SET @Risultato=0
    ELSE IF @TOT_SUP >20000  SET @Risultato=5
		ELSE IF @TOT_SUP >=5000  SET @Risultato=15
			 ELSE SET @Risultato =0
 
	SELECT @Risultato AS PUNTEGGIO
END
