--
CREATE   PROCEDURE [dbo].[calcoloStep132_3]
(
@IdProgetto int,
@FASE_ISTRUTTORIA INT =0
)
AS
BEGIN

DECLARE @CUAA VARCHAR(16),@result int, @ID_BANDO INT
SET @RESULT =1 --PONGO LO STEP VERIFICATO
--annualita 864
DECLARE @COUNT_ANNO INT, @COUNT_INV INT

SET  @COUNT_INV = (SELECT ((SELECT count(*) as a  FROM PIANO_INVESTIMENTI PI 
							WHERE ID_PROGETTO = @IdProgetto AND(((PI.ID_INVESTIMENTO_ORIGINALE IS NULL AND @FASE_ISTRUTTORIA=0 )OR(PI.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND @FASE_ISTRUTTORIA=1))))
					 - 
				 (SELECT COUNT(*) FROM  PIANO_INVESTIMENTI AS PI INNER JOIN PRIORITA_X_INVESTIMENTI ON PI.ID_INVESTIMENTO = PRIORITA_X_INVESTIMENTI.ID_INVESTIMENTO 
				  WHERE(PI.ID_PROGETTO = @IdProgetto)AND(((PI.ID_INVESTIMENTO_ORIGINALE IS NULL AND @FASE_ISTRUTTORIA=0 )OR(PI.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND @FASE_ISTRUTTORIA=1)) AND ID_PRIORITA in(375,864,1081)))))

IF( @COUNT_INV = 0)BEGIN
	 SELECT @COUNT_ANNO = COUNT(*) FROM (SELECT  COUNT(*) AS ANNO 
	 FROM PIANO_INVESTIMENTI AS PI INNER JOIN VPRIORITA_X_INVESTIMENTI PXI ON PI.ID_INVESTIMENTO = PXI.ID_INVESTIMENTO
	 WHERE (PI.ID_PROGETTO = @IdProgetto ) AND (((PI.ID_INVESTIMENTO_ORIGINALE IS NULL AND @FASE_ISTRUTTORIA=0) 
			OR(PI.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND @FASE_ISTRUTTORIA=1))AND  ID_PRIORITA in(375,864,1081)) GROUP BY PXI.DESCRIZIONE) AS ANNO 
END ELSE SET @RESULT =0

SELECT @ID_BANDO =ID_BANDO FROM PROGETTO WHERE ID_PROGETTO=@IdProgetto 
IF(@ID_BANDO IN (297,265,345, 394))BEGIN IF( ISNULL(@COUNT_ANNO,0)<2) SET @RESULT =0 END---MICROFILIERA
ELSE IF( ISNULL(@COUNT_ANNO,0) <3 ) SET @RESULT =0
SELECT @RESULT AS RESULT
END
