CREATE PROCEDURE [dbo].[calcoloStep221_6]
(
@IdProgetto int,
@FASE_ISTRUTTORIA INT =0
)
AS
BEGIN

--declare @IdProgetto int = 8521,
--		@FASE_ISTRUTTORIA INT =0

DECLARE @ID_FASCICOLO INT, @CUAA VARCHAR(16),@DATA_VALIDITA DATETIME,
		@ID_IMPRESA INT, @RESULT INT, @COUNT_SUP_NON_SEMINABILE INT

SET @RESULT = 1-- PONGO LO STEP IN STATO VERIFICATO

SELECT @ID_FASCICOLO = ID_FASCICOLO, @CUAA=IMP.CUAA, @ID_IMPRESA= IMP.ID_IMPRESA , @DATA_VALIDITA= PS.DATA
FROM PROGETTO P 
	INNER JOIN vIMPRESA IMP ON IMP.ID_IMPRESA =P.ID_IMPRESA 
	 INNER JOIN PROGETTO_STORICO PS ON PS.ID_PROGETTO = P.ID_PROGETTO AND  PS.COD_STATO IN ('P')
WHERE P.ID_PROGETTO = @IdProgetto 
					
 IF(@ID_FASCICOLO IS NULL) SELECT @ID_FASCICOLO = MAX(ID_FASCICOLO) FROM FASCICOLO_AZIENDALE FA WHERE ID_IMPRESA=@ID_IMPRESA  --STATO PROVVISORIO DEL PROGETTO

 IF(@ID_FASCICOLO IS NULL) SET @RESULT= 0--NON ESISTE FASCICOLO
 ELSE BEGIN 
	SELECT @COUNT_SUP_NON_SEMINABILE= 
	      COUNT(*) FROM TERRITORIO T LEFT JOIN 
				   (SELECT DISTINCT ID_TERRITORIO, SUPERFICIE_UTILIZZATA, COD_MACROUSO FROM UTILIZZO_TERRA WHERE COD_MACROUSO IN ('020','040','060') ) UT ON T.ID_TERRITORIO = UT.ID_TERRITORIO INNER JOIN 
					PIANO_COLTURALE_DETTAGLIO PC ON PC.ID_CATASTO = T.ID_CATASTO INNER JOIN 
					(SELECT MAX (id_rif) ID_RIF, ID_IMPRESA FROM PIANO_COLTURALE_STORICO WHERE ID_IMPRESA=@ID_IMPRESA GROUP BY ID_IMPRESA ) AS PIANO_STO ON PIANO_STO.ID_RIF= PC.ID_RIF  
	WHERE T.ID_FASCICOLO = @ID_FASCICOLO AND UT.COD_MACROUSO IS NULL AND PC.SUPERFICIE_COLTURA >0 AND (PC.DATA_FINE_VALIDITA IS NULL  OR PC.DATA_FINE_VALIDITA >@DATA_VALIDITA) 
 
 
 END
IF(@COUNT_SUP_NON_SEMINABILE >0) SET @RESULT= 0	
SELECT @RESULT
END
