CREATE  PROCEDURE [dbo].[calcoloStepPagamento_A_112_2]
@IdProgetto int,
@IdDomandaPagamento int =NULL
 AS
BEGIN

-- Antimafia BANDO 112
 
--DECLARE @IdProgetto int = 400,
--@IdDomandaPagamento int =386

DECLARE	@RESULT INT, @ID_IMPRESA INT, @DATA_FINE_ISTRUTTORIA DATETIME 

 -- IMPONGO LO STEP NON VERIFICATO	
SET @RESULT = 0 
SELECT @DATA_FINE_ISTRUTTORIA = ISNULL(DATA_APPROVAZIONE,GETDATE())  FROM DOMANDA_DI_PAGAMENTO WHERE ID_DOMANDA_PAGAMENTO = @IdDomandaPagamento  
SELECT @ID_IMPRESA = ID_IMPRESA FROM PROGETTO P   WHERE ID_PROGETTO = @IdProgetto

EXEC @RESULT = SpControlloAntimafia @ID_IMPRESA, @DATA_FINE_ISTRUTTORIA
 
SELECT @RESULT
END
