CREATE PROCEDURE [dbo].[calcoloStep123_14]
@IdProgetto int
AS
BEGIN
-- Materia prima di provenienza da contratti di Filiera >= 50% totale materia prima trasformata
-- QUANTITA_DA_BACINO_BIETICOLO utilizzato per memorizzare la quantita da Filiera

DECLARE @Result int, @DATA datetime ,@QUANTITA_TOT decimal(15,2) , 
					@QUANTITA_FILIERA decimal(10,2)

SET @Result = 1 -- Impongo lo Step  verificato

 SELECT @DATA =DATA
 FROM PROGETTO P  INNER JOIN PROGETTO_STORICO S ON  P.ID_PROGETTO = S.ID_PROGETTO 
 where P.ID_PROGETTO = @IdProgetto AND COD_STATO IN ('P','L')
 ORDER BY S.ID DESC 
 
DECLARE MATERIA_PRIMA CURSOR  FOR 
(SELECT   SUM( isnull(QUANTITA_PROPRIA,0) + isnull(QUANTITA_EXTRA,0)) , isnull( SUM ( QUANTITA_DA_BACINO_BIETICOLO) ,0) 
 FROM PRODOTTI_VENDITE WHERE MATERIA_PRIMA=1 AND ID_PROGETTO =@IdProgetto AND
			  ANNO >= YEAR(@DATA ) GROUP BY ANNO )

OPEN MATERIA_PRIMA
FETCH NEXT FROM MATERIA_PRIMA 
INTO @QUANTITA_TOT , @QUANTITA_FILIERA 
WHILE @@FETCH_STATUS = 0
BEGIN
	IF( @QUANTITA_FILIERA < ((@QUANTITA_TOT )*0.5) )	
	BEGIN SET @Result =0 END
FETCH NEXT FROM MATERIA_PRIMA 
INTO @QUANTITA_TOT , @QUANTITA_FILIERA 
END

CLOSE MATERIA_PRIMA
DEALLOCATE MATERIA_PRIMA 

SELECT @Result AS RESULT
END
