CREATE PROCEDURE [dbo].[calcoloStep221_3]
(
@IdProgetto int,
@FASE_ISTRUTTORIA INT =0
)
AS
BEGIN
	
DECLARE @RESULT int,
		@RESULTA1 decimal,
		@RESULTA2 decimal,
		@RESULTA3 decimal

SET @RESULT = 0 -- PONGO LO STEP IN STATO NON VERIFICATO
--a1 bando id 203 id dettaglio 4494 - bando id 233 id dettaglio 4935 
--a2 bando id 203 id dettaglio 4495 - bando id 233 id dettaglio 4936 
--a3 bando id 203 id dettaglio 4496 - bando id 233 id dettaglio 4937 

--- Costo di impianto <= costo massimo/Ha per tipologia a di impianto
--- TIPOLOGIA a1)

set @RESULTA1 = (SELECT ((SELECT ISNULL(SUM(COSTO_INVESTIMENTO),0) FROM PROGETTO P
INNER JOIN VPIANO_INVESTIMENTI I ON (P.ID_PROGETTO=I.ID_PROGETTO) WHERE
I.COD_TIPO_INVESTIMENTO = 1 AND
((I.ID_INVESTIMENTO_ORIGINALE IS NULL AND @FASE_ISTRUTTORIA=0 AND ID_VARIANTE IS NULL)OR(I.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND @FASE_ISTRUTTORIA =1 AND ID_VARIANTE IS NULL)) AND
(P.ID_PROGETTO=@IdProgetto OR P.ID_PROG_INTEGRATO=@IdProgetto)  AND
I.CODICE = 'a' and I.ID_DETTAGLIO_INVESTIMENTO in 

-- inizio modifica per riaperture future  --- a1 ('4494','4935') 
(SELECT ID_DETTAGLIO_INVESTIMENTO FROM CODIFICA_INVESTIMENTO CI INNER JOIN DETTAGLIO_INVESTIMENTI DI ON 
(CI.ID_CODIFICA_INVESTIMENTO = DI.ID_CODIFICA_INVESTIMENTO) WHERE CI.ID_BANDO = 
(SELECT ID_BANDO FROM PROGETTO WHERE ID_PROGETTO = @IdProgetto) AND DI.COD_DETTAGLIO = 'a1')
-- fine modifica per riaperture future  

and I.ID_PROGETTO = @IdProgetto) 
/
((SELECT ISNULL(SUM (VALORE), 1) AS Totale_Ha FROM PRIORITA_X_INVESTIMENTI PXI 
inner join VPIANO_INVESTIMENTI I on I.ID_INVESTIMENTO = PXI.ID_INVESTIMENTO WHERE 
((I.ID_INVESTIMENTO_ORIGINALE IS NULL AND @FASE_ISTRUTTORIA=0 AND ID_VARIANTE IS NULL)OR(I.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND @FASE_ISTRUTTORIA =1 AND ID_VARIANTE IS NULL)) AND ------*------*
PXI.ID_PRIORITA = 605 AND  -- ottengo m2 e sotto gli ettari
I.ID_PROGETTO = @IdProgetto)/10000)))


--- TIPOLOGIA a2)

set @RESULTA2 = (SELECT ((SELECT ISNULL(SUM(COSTO_INVESTIMENTO),0) FROM PROGETTO P
INNER JOIN VPIANO_INVESTIMENTI I ON (P.ID_PROGETTO=I.ID_PROGETTO) WHERE
((I.ID_INVESTIMENTO_ORIGINALE IS NULL AND @FASE_ISTRUTTORIA=0 AND ID_VARIANTE IS NULL)OR(I.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND @FASE_ISTRUTTORIA =1 AND ID_VARIANTE IS NULL)) AND
I.COD_TIPO_INVESTIMENTO = 1 AND
(P.ID_PROGETTO=@IdProgetto OR P.ID_PROG_INTEGRATO=@IdProgetto)  AND
I.CODICE = 'a' and I.ID_DETTAGLIO_INVESTIMENTO in
-- inizio modifica per riaperture future  --- a2   ('4495','4936') 
(SELECT ID_DETTAGLIO_INVESTIMENTO FROM CODIFICA_INVESTIMENTO CI INNER JOIN DETTAGLIO_INVESTIMENTI DI ON 
(CI.ID_CODIFICA_INVESTIMENTO = DI.ID_CODIFICA_INVESTIMENTO) WHERE CI.ID_BANDO = 
(SELECT ID_BANDO FROM PROGETTO WHERE ID_PROGETTO = @IdProgetto) AND DI.COD_DETTAGLIO = 'a2')
-- fine modifica per riaperture future  
 and I.ID_PROGETTO = @IdProgetto)
/
((SELECT ISNULL(SUM (VALORE) , 1) AS Totale_Ha FROM PRIORITA_X_INVESTIMENTI PXI 
inner join VPIANO_INVESTIMENTI I on I.ID_INVESTIMENTO = PXI.ID_INVESTIMENTO WHERE  
((I.ID_INVESTIMENTO_ORIGINALE IS NULL AND @FASE_ISTRUTTORIA=0 AND ID_VARIANTE IS NULL)OR(I.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND @FASE_ISTRUTTORIA =1 AND ID_VARIANTE IS NULL)) AND ------*------*
PXI.ID_PRIORITA = 605 AND  -- ottengo m2 e sotto gli ettari
I.ID_PROGETTO = @IdProgetto)/10000)))


--- TIPOLOGIA a3)

set @RESULTA3 = (SELECT ((SELECT ISNULL(SUM(COSTO_INVESTIMENTO),0) FROM PROGETTO P
INNER JOIN VPIANO_INVESTIMENTI I ON (P.ID_PROGETTO=I.ID_PROGETTO) WHERE
((I.ID_INVESTIMENTO_ORIGINALE IS NULL AND @FASE_ISTRUTTORIA=0 AND ID_VARIANTE IS NULL)OR(I.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND @FASE_ISTRUTTORIA =1 AND ID_VARIANTE IS NULL)) AND
I.COD_TIPO_INVESTIMENTO = 1 AND
(P.ID_PROGETTO=@IdProgetto OR P.ID_PROG_INTEGRATO=@IdProgetto) AND
I.CODICE = 'a' and I.ID_DETTAGLIO_INVESTIMENTO in 
-- inizio modifica per riaperture future  --- a3   ('4496','4937') 
(SELECT ID_DETTAGLIO_INVESTIMENTO FROM CODIFICA_INVESTIMENTO CI INNER JOIN DETTAGLIO_INVESTIMENTI DI ON 
(CI.ID_CODIFICA_INVESTIMENTO = DI.ID_CODIFICA_INVESTIMENTO) WHERE CI.ID_BANDO = 
(SELECT ID_BANDO FROM PROGETTO WHERE ID_PROGETTO = @IdProgetto) AND DI.COD_DETTAGLIO = 'a3')
-- fine modifica per riaperture future  
and I.ID_PROGETTO = @IdProgetto) 
/
((SELECT ISNULL(SUM (VALORE) , 1) AS Totale_Ha FROM PRIORITA_X_INVESTIMENTI PXI 
inner join VPIANO_INVESTIMENTI I on I.ID_INVESTIMENTO = PXI.ID_INVESTIMENTO WHERE
((I.ID_INVESTIMENTO_ORIGINALE IS NULL AND @FASE_ISTRUTTORIA=0 AND ID_VARIANTE IS NULL)OR(I.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND @FASE_ISTRUTTORIA =1 AND ID_VARIANTE IS NULL)) AND ------*------*
PXI.ID_PRIORITA = 605 AND  -- ottengo m2 e sotto gli ettari
I.ID_PROGETTO = @IdProgetto)/10000)))

IF(@RESULTA1 <= 8500 AND @RESULTA2 <= 8500 AND @RESULTA3 <= 7800)
    SET @RESULT = 1
ELSE 
	SET @RESULT = 0
SELECT @RESULT

END
