CREATE  PROCEDURE [dbo].[calcoloRequisitoPagamento133_5]
@ID_DOMANDA_PAGAMENTO int
AS
 BEGIN
 --Spesa prodotto fornita dagli associati <=5% del totale annuale rendicontato 
--  Requisiti pagamento esito positivo =1 
-- anno =228

--DECLARE @ID_DOMANDA_PAGAMENTO int  
--SET @ID_DOMANDA_PAGAMENTO=1224

DECLARE @ID_VARIANTE INT, @ID_PROGETTO INT
DECLARE @RESULT INT,@COUNT_SPESE INT
DECLARE @DATA_MODIFICA_PAGAMENTO DATETIME,@ID_INVESTIMENTO INT,
		@IMPORTO_RENDICONTATO_ATTUALE DECIMAL(18,2),
		@CONTRIBUTO_RENDICONTATO_ATTUALE DECIMAL(18,2)

--TROVO PROGETTO E ULTIMA VARIANTE RELATIVA A QUESTA DOMANDA DI PAGAMENTO
SELECT @DATA_MODIFICA_PAGAMENTO=DATA_MODIFICA,@ID_PROGETTO=D.ID_PROGETTO 
FROM DOMANDA_DI_PAGAMENTO D INNER JOIN 
	 PROGETTO P ON D.ID_PROGETTO=P.ID_PROGETTO WHERE ID_DOMANDA_PAGAMENTO=@ID_DOMANDA_PAGAMENTO
SELECT @ID_VARIANTE=MAX(ID_VARIANTE) 
FROM VARIANTI WHERE ID_PROGETTO=@ID_PROGETTO AND APPROVATA=1 AND ANNULLATA=0 AND DATA_MODIFICA<@DATA_MODIFICA_PAGAMENTO
	 

--CREO PIANO INVESTIMENTI VIRTUALE
DECLARE @INVESTIMENTI_VIRTUALE TABLE ([ID_INVESTIMENTO] [int] NOT NULL,
	[ID_PROGETTO] [int] NULL,
	[ID_CODIFICA_INVESTIMENTO] [int] NULL,
	[ID_DETTAGLIO_INVESTIMENTO] [int] NULL,
	IMPORTO_TOTALE_RENDICONTATO DECIMAL(18,2),
	CONTRIBUTO_TOTALE_RENDICONTATO DECIMAL(18,2))	

INSERT INTO @INVESTIMENTI_VIRTUALE
SELECT I.ID_INVESTIMENTO, I.ID_PROGETTO, I.ID_CODIFICA_INVESTIMENTO,I.ID_DETTAGLIO_INVESTIMENTO,Dbo.calcoloTotaleImportoRendicontatoInvestimento (I.ID_INVESTIMENTO,@ID_DOMANDA_PAGAMENTO) AS IMPORTO_TOTALE_RENDICONTATO,
	dbo.calcoloTotaleContributoRendicontatoInvestimento(I.ID_INVESTIMENTO,@ID_DOMANDA_PAGAMENTO) AS CONTRIBUTO_TOTALE_RENDICONTATO 
FROM PROGETTO P INNER JOIN PIANO_INVESTIMENTI I ON P.ID_PROGETTO=I.ID_PROGETTO
WHERE ISNULL(P.ID_PROG_INTEGRATO,P.ID_PROGETTO)=@ID_PROGETTO AND
	((@ID_VARIANTE IS NULL AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND AMMESSO=1 AND ID_VARIANTE IS NULL) OR
	(ID_VARIANTE=@ID_VARIANTE AND ISNULL(COD_VARIAZIONE,'X')!='A')) ORDER BY COD_TIPO_INVESTIMENTO

SET @RESULT = 0 -- IMPONGO LO STEP NON VERIFICATO
-- CONTROLLO PER OGNI ANNO RENDICONTATO
SELECT @COUNT_SPESE= COUNT(*) FROM(
SELECT DESCRIZIONE FROM(SELECT PXI.DESCRIZIONE, 
							'SPESE_TOTALI' = CASE WHEN CO.CODICE IN ('1','2','3') THEN  SUM(IMPORTO_TOTALE_RENDICONTATO)  END, 
							'SPESE_PRODOTTO' = CASE WHEN PI.ID_DETTAGLIO_INVESTIMENTO IN (3445,5192,7198,8663) THEN SUM(IMPORTO_TOTALE_RENDICONTATO)END 
						FROM @INVESTIMENTI_VIRTUALE AS PI INNER JOIN  
							VPRIORITA_X_INVESTIMENTI PXI ON PI.ID_INVESTIMENTO = PXI.ID_INVESTIMENTO AND ID_PRIORITA IN( 228,1130,1237) INNER JOIN 
							CODIFICA_INVESTIMENTO CO ON CO.ID_CODIFICA_INVESTIMENTO = PI.ID_CODIFICA_INVESTIMENTO
						WHERE ID_PROGETTO =@ID_PROGETTO
						GROUP BY  PXI.DESCRIZIONE, CODICE, ID_DETTAGLIO_INVESTIMENTO)as t
					GROUP BY DESCRIZIONE	
					HAVING((SUM(ISNULL( SPESE_PRODOTTO,0)) *100 )/SUM(ISNULL(SPESE_TOTALI,1))) >5)as Ca 
					
IF(@COUNT_SPESE=0) SET @RESULT=1
ELSE SET @RESULT=0
SELECT @RESULT
END
