-- SALDO
--=== Richiesta di saldo  entro il 31 AGOSTO 2015   ===--

CREATE PROCEDURE [dbo].[calcoloRequisitoPagamento_B455_2]
@ID_DOMANDA_PAGAMENTO int
AS
BEGIN

	
DECLARE @RESULT INT, @DATA_ULTI_INTERVENTI DATETIME,@DATA_RICHIESTA_SALDO DATETIME
SET @RESULT = 0 -- IMPONGO LO STEP NON VERIFICATO		

--declare @ID_DOMANDA_PAGAMENTO int = 

SELECT @DATA_ULTI_INTERVENTI = VAL_DATA FROM DOMANDA_PAGAMENTO_REQUISITI WHERE ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO  AND ID_REQUISITO = 524


IF @DATA_ULTI_INTERVENTI <= '2015-08-31' SET @RESULT = 1 	
 ELSE SET @RESULT = 0 	

IF(@RESULT =1 )BEGIN
	SELECT @DATA_RICHIESTA_SALDO = DATA_MODIFICA FROM DOMANDA_DI_PAGAMENTO WHERE ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO
	SET @RESULT=(SELECT 'DIFF'= CASE WHEN DATEDIFF(DAY, DATEADD(DD, 0,'2015-08-31'), @DATA_RICHIESTA_SALDO)<=0 THEN 1 ELSE 0 END)
END

END
SELECT @RESULT
