CREATE PROCEDURE [dbo].[RptBusinessPlan_ValutazionePianoSviluppo] 
@ID_Impresa int,
@ID_Domanda int
AS
BEGIN
	SET NOCOUNT ON;
    		
    DECLARE @Count int
		
	IF (@ID_Domanda IS NOT NULL) SET @Count = (SELECT COUNT(ID_PIANO) FROM PIANO_DI_SVILUPPO WHERE ID_PROGETTO = @ID_Domanda)     					
	ELSE SET @Count = (SELECT COUNT(ID_PIANO) FROM PIANO_DI_SVILUPPO WHERE ID_IMPRESA = @ID_Impresa AND ID_PROGETTO IS NULL)
	
	IF (@Count > 0)

		IF (@ID_Domanda IS NOT NULL) -- Piano di sviluppo a livello di domanda
		
				   SELECT ANNO,
				   ISNULL(COSTO_INVESTIMENTO,0.00) AS COSTO_INVESTIMENTO,
				   ISNULL(MEZZI_PROPRI,0.00) AS MEZZI_PROPRI,
				   ISNULL(RISORSE_TERZI,0.00) AS RISORSE_TERZI,
				   ISNULL(CONTRIBUTI_PUBBLICI,0.00) AS CONTRIBUTI_PUBBLICI,
				   ISNULL(SPESE_GESTIONE,0.00) AS SPESE_GESTIONE,
				   ISNULL(RIMBORSO_DEBITO,0.00) AS RIMBORSO_DEBITO,
				   ISNULL(ENTRATA_GESTIONE,0.00) AS ENTRATA_GESTIONE,
				   ISNULL(ALTRE_COPERTURE,0.00) AS ALTRE_COPERTURE,               
				   (COSTO_INVESTIMENTO + SPESE_GESTIONE + RIMBORSO_DEBITO) AS TOTALE_FABBISOGNO,
				   (MEZZI_PROPRI + RISORSE_TERZI + CONTRIBUTI_PUBBLICI + ENTRATA_GESTIONE + ALTRE_COPERTURE) AS TOTALE_COPERTURA,			   
				   (MEZZI_PROPRI + RISORSE_TERZI + CONTRIBUTI_PUBBLICI + ENTRATA_GESTIONE + ALTRE_COPERTURE) -
				   (COSTO_INVESTIMENTO + SPESE_GESTIONE + RIMBORSO_DEBITO) AS SALDO_NETTO

			FROM PIANO_DI_SVILUPPO
									  
			WHERE ID_PROGETTO = @ID_Domanda
			
			ORDER BY ANNO ASC		
			
		ELSE -- Piano di sviluppo a livello di impresa
				   SELECT ANNO,
				   ISNULL(COSTO_INVESTIMENTO,0.00) AS COSTO_INVESTIMENTO,
				   ISNULL(MEZZI_PROPRI,0.00) AS MEZZI_PROPRI,
				   ISNULL(RISORSE_TERZI,0.00) AS RISORSE_TERZI,
				   ISNULL(CONTRIBUTI_PUBBLICI,0.00) AS CONTRIBUTI_PUBBLICI,
				   ISNULL(SPESE_GESTIONE,0.00) AS SPESE_GESTIONE,
				   ISNULL(RIMBORSO_DEBITO,0.00) AS RIMBORSO_DEBITO,
				   ISNULL(ENTRATA_GESTIONE,0.00) AS ENTRATA_GESTIONE,
				   ISNULL(ALTRE_COPERTURE,0.00) AS ALTRE_COPERTURE,               
				   (COSTO_INVESTIMENTO + SPESE_GESTIONE + RIMBORSO_DEBITO) AS TOTALE_FABBISOGNO,
				   (MEZZI_PROPRI + RISORSE_TERZI + CONTRIBUTI_PUBBLICI + ENTRATA_GESTIONE + ALTRE_COPERTURE) AS TOTALE_COPERTURA,			   
				   (MEZZI_PROPRI + RISORSE_TERZI + CONTRIBUTI_PUBBLICI + ENTRATA_GESTIONE + ALTRE_COPERTURE) -
				   (COSTO_INVESTIMENTO + SPESE_GESTIONE + RIMBORSO_DEBITO) AS SALDO_NETTO

			FROM PIANO_DI_SVILUPPO
									  
			WHERE ID_IMPRESA = @ID_Impresa AND ID_PROGETTO IS NULL
			
			ORDER BY ANNO ASC
		
	ELSE SELECT
				NULL AS ANNO,
				0.00 AS COSTO_INVESTIMENTO,
				0.00 AS MEZZI_PROPRI,
				0.00 AS RISORSE_TERZI,
				0.00 AS CONTRIBUTI_PUBBLICI,
				0.00 AS SPESE_GESTIONE,
				0.00 AS RIMBORSO_DEBITO,
				0.00 AS ENTRATA_GESTIONE,
				0.00 AS ALTRE_COPERTURE,
				0.00 AS TOTALE_FABBISOGNO,
				0.00 AS TOTALE_COPERTURA,
				0.00 AS SALDO_NETTO				

END
