CREATE PROCEDURE [dbo].[RptBusinessPlan_ProdottiMateriePrime]
@ID_Domanda int,
@TipoProdotto bit
AS
BEGIN
	SET NOCOUNT ON;
    	
    DECLARE @Count int
		
	IF (@ID_Domanda IS NOT NULL)
	 BEGIN			  
	

	SET @Count = (SELECT COUNT(ID_PRODOTTI_VENDITE) FROM PRODOTTI_VENDITE WHERE ID_PROGETTO = @ID_Domanda)
END

	IF (@Count > 0)

	BEGIN -- Materia prima
		IF (@TipoProdotto = 1)
		BEGIN
		SELECT 
			PMP.ID_PRODOTTI_MATERIE_PRIME,
			ANNO,
			ISNULL(QUANTITA_PROPRIA, 0) AS QUANTITA_PROPRIA,
			ISNULL(QUANTITA_EXTRA, 0) AS QUANTITA_EXTRA,
			ISNULL(VALORE_PROPRIO, 0) AS VALORE_PROPRIO,
			ISNULL(VALORE_EXTRA, 0) AS VALORE_EXTRA,
			ISNULL(QUANTITA_DA_BACINO_BIETICOLO, 0) AS QUANTITA_DA_BACINO_BIETICOLO,
			ISNULL(QUANTITA_DA_EXBIETICOLTORI, 0) AS QUANTITA_DA_EXBIETICOLTORI,
			ISNULL(VALORE_DA_ACCORDI, 0) AS VALORE_DA_ACCORDI,
			ISNULL(QUANTITA_DA_CONTRATTI, 0) AS QUANTITA_DA_CONTRATTI,
			ISNULL(DESCRIZIONE, 0) AS DESCRIZIONE,
			CUAA_TRASFORMATORE

		FROM PRODOTTI_VENDITE PV INNER JOIN PRODOTTI_MATERIE_PRIME PMP 
				ON PMP.ID_PRODOTTI_MATERIE_PRIME = PV.ID_PRODOTTI_MATERIE_PRIME
		WHERE ID_PROGETTO = @ID_Domanda AND MATERIA_PRIMA = 1 AND ANNO IS NOT NULL

		END


	
		ELSE IF (@TipoProdotto = 0)-- Prodotti Trasformati
		BEGIN 
		SELECT 
			PMP.ID_PRODOTTI_MATERIE_PRIME,
			ANNO,
			ISNULL(QUANTITA_PROPRIA, 0) AS QUANTITA_PROPRIA,
			ISNULL(VALORE_PROPRIO, 0) AS VALORE_PROPRIO,
			ISNULL(VALORE_DA_ACCORDI, 0) AS VALORE_DA_ACCORDI,
			ISNULL(DESCRIZIONE, 0) AS DESCRIZIONE,
			CUAA_TRASFORMATORE

		FROM PRODOTTI_VENDITE PV INNER JOIN PRODOTTI_MATERIE_PRIME PMP 
				ON PMP.ID_PRODOTTI_MATERIE_PRIME = PV.ID_PRODOTTI_MATERIE_PRIME
		WHERE ID_PROGETTO = @ID_Domanda AND MATERIA_PRIMA = 0 AND ANNO IS NOT NULL

		END
	END	

		ELSE SELECT NULL AS ANNO,
			NULL AS ID_PRODOTTI_MATERIE_PRIME,
			NULL AS QUANTITA_PROPRIA,
			NULL AS QUANTITA_EXTRA,
			NULL AS VALORE_PROPRIO,
			NULL AS VALORE_EXTRA,
			NULL AS QUANTITA_DA_BACINO_BIETICOLO,
			NULL AS QUANTITA_DA_EXBIETICOLTORI,
			NULL AS VALORE_DA_ACCORDI,
			NULL AS QUANTITA_DA_CONTRATTI,
			NULL AS DESCRIZIONE,
			NULL AS CUAA_TRASFORMATORE    		

	END
