CREATE PROCEDURE [dbo].[RptBandoPagamentoProvvisorie] 
(
@IdProgrammazione int
)
AS
BEGIN
SET NOCOUNT ON;

--DECLARE @IdPsr int,
--@CodAsse int, 
--@CodMisura int

--SET @IdPsr = 1 
--SET @CodAsse = 1 
--SET @CodMisura = 7

if(	SELECT COUNT(*)
FROM         vDOMANDA_DI_PAGAMENTO AS DP INNER JOIN
                      vPROGETTO AS P ON DP.ID_PROGETTO = ISNULL(P.ID_PROG_INTEGRATO, P.ID_PROGETTO) INNER JOIN
                      BANDO B ON P.ID_BANDO = B.ID_BANDO
WHERE     (DP.ANNULLATA = 0) AND DP.SEGNATURA IS NULL
AND B.ID_BANDO IN (SELECT ID_BANDO FROM vBANDO_PROGRAMMAZIONE WHERE ID_BANDO IN (SELECT ID_BANDO FROM vBANDO_PROGRAMMAZIONE WHERE ID_PROGRAMMAZIONE  IN (SELECT ID FROM zPROGRAMMAZIONE WHERE ID_PADRE = @IdProgrammazione)  
									AND MISURA_PREVALENTE = 1))
AND p.COD_STATO NOT IN ( 'R', 'E')) > 0 
	
	
	SELECT     ISNULL(P.ID_PROG_INTEGRATO, P.ID_PROGETTO) AS ID_PROGETTO, DP.DESCRIZIONE AS TIPO_PAGAMENTO, I.CUAA, 
                      BP.COD_PSR AS PSR_DESCRIZIONE, BP.CODICE AS MISURA, 
                     ISNULL(A.CONTRIBUTOR_ANTICIPO, 0)  + ISNULL(PAG.CONTR_R_PAGAMENTO, 0) 
                      AS CONTR_RICHIESTO,  I.RAGIONE_SOCIALE, 
                      IND.COMUNE AS COMUNE_SEDE_LEGALE, CASE WHEN DP.SEGNATURA IS NULL 
                      THEN 'PROVVISORIO' ELSE DP.SEGNATURA END AS STATO_DOMANDA, 
                     (CASE WHEN DISPOSIZIONI_ATTUATIVE = 1 THEN PROG_PRINC.STATO ELSE P.STATO END) AS STATO_ATTUALE, 
	P.PROVINCIA_DI_PRESENTAZIONE,
	(CASE WHEN DISPOSIZIONI_ATTUATIVE = 1 THEN PROG_PRINC.BANDO ELSE B.DESCRIZIONE END) AS BANDO,
	ISNULL(convert(VARCHAR(16), DATA_SCADENZA , 103), '') AS DATA_SCADENZA,
		P.ID_BANDO AS ID_BANDO, DP.OPERATORE AS OPERATORE_PRESENTAZIONE, EN.DESCRIZIONE AS ENTE_OPERATORE_PRESENTAZIONE
FROM  vDOMANDA_DI_PAGAMENTO AS DP 
	INNER JOIN vPROGETTO AS P ON DP.ID_PROGETTO = ISNULL(P.ID_PROG_INTEGRATO, P.ID_PROGETTO) 
      LEFT JOIN (SELECT ID_PROGETTO, SPR.ID_BANDO, ID_PROG_INTEGRATO, SPR.STATO, SPR.SEGNATURA, BA.DESCRIZIONE AS BANDO, SPR.COD_STATO 
					FROM vPROGETTO SPR
					INNER JOIN VBANDO BA ON SPR.ID_BANDO = BA.ID_BANDO WHERE ID_PROGETTO = ID_PROG_INTEGRATO) 
		AS PROG_PRINC ON P.ID_PROG_INTEGRATO = PROG_PRINC.ID_PROGETTO --PER VEDERE LO STATO E IL BANDO DEL PROGETTO PRINCIPALE IN CASO DI BANDO MULTIMISURA
       INNER JOIN vBANDO AS B ON B.ID_BANDO = P.ID_BANDO
       INNER JOIN vBANDO_PROGRAMMAZIONE BP ON B.ID_PROGRAMMAZIONE = BP.ID
       LEFT OUTER JOIN
                          (SELECT     PR.ID_DOMANDA_PAGAMENTO, P.ID_PROGETTO, SUM(ISNULL(PR.CONTRIBUTO_RICHIESTO, 0)) AS CONTR_R_PAGAMENTO
                            FROM          PAGAMENTI_RICHIESTI AS PR INNER JOIN
                                                   PIANO_INVESTIMENTI AS P ON P.ID_INVESTIMENTO = PR.ID_INVESTIMENTO
                            GROUP BY PR.ID_DOMANDA_PAGAMENTO, P.ID_PROGETTO) AS PAG ON PAG.ID_DOMANDA_PAGAMENTO = DP.ID_DOMANDA_PAGAMENTO AND 
                      PAG.ID_PROGETTO = P.ID_PROGETTO LEFT OUTER JOIN
                          (SELECT     SUM(ISNULL(CONTRIBUTO_RICHIESTO, 0)) AS CONTRIBUTOR_ANTICIPO, ID_BANDO,  ID_DOMANDA_PAGAMENTO
                            FROM          ANTICIPI_RICHIESTI
                            GROUP BY ID_DOMANDA_PAGAMENTO, ID_BANDO) AS A ON DP.ID_DOMANDA_PAGAMENTO = A.ID_DOMANDA_PAGAMENTO AND 
                      P.ID_BANDO = A.ID_BANDO  INNER JOIN
                      vIMPRESA AS I ON I.ID_IMPRESA = P.ID_IMPRESA INNER JOIN
                      vINDIRIZZARIO AS IND ON IND.ID_INDIRIZZARIO = I.ID_SEDELEGALE_ULTIMO 
       LEFT JOIN ENTE EN ON DP.COD_ENTE = EN.COD_ENTE 
WHERE     (DP.ANNULLATA = 0) AND DP.SEGNATURA IS NULL
AND ISNULL(PROG_PRINC.COD_STATO, P.COD_STATO) NOT IN ( 'R', 'E')
AND B.ID_BANDO IN (SELECT ID_BANDO FROM vBANDO_PROGRAMMAZIONE WHERE ID_BANDO IN (SELECT ID_BANDO FROM vBANDO_PROGRAMMAZIONE WHERE ID_PROGRAMMAZIONE  IN (SELECT ID FROM zPROGRAMMAZIONE WHERE ID_PADRE = @IdProgrammazione)  
									AND MISURA_PREVALENTE = 1))
ORDER BY DP.ID_DOMANDA_PAGAMENTO, P.ID_PROGETTO

ELSE SELECT NULL AS ID_PROGETTO,  
						NULL AS TIPO_PAGAMENTO, NULL AS CUAA, 
						NULL AS PSR_DESCRIZIONE, NULL AS  MISURA, 
                        NULL AS CONTR_RICHIESTO, NULL AS  RAGIONE_SOCIALE, 
                        NULL AS COMUNE_SEDE_LEGALE, NULL AS STATO_DOMANDA, 
                        NULL AS STATO_ATTUALE, NULL AS PROVINCIA_DI_PRESENTAZIONE,	
                        NULL AS BANDO, NULL AS DATA_SCADENZA,NULL AS ID_BANDO

END
