create PROCEDURE [dbo].[RptBusinessPlan_BilancioIndustrialePrevisionale] 
@ID_Impresa int,
@ID_Domanda int
AS
BEGIN
	SET NOCOUNT ON;

	-- Bilanci impresa industriali dei 3 anni successivi

	DECLARE @Count int
	SET @Count = (SELECT COUNT(ID_PROGETTO) FROM BILANCIO_INDUSTRIALE WHERE ID_PROGETTO = @ID_Domanda)

	IF (@Count > 0)
	BEGIN

		SELECT TOP(3) ANNO,
			   DATA_BILANCIO,
               ISNULL(PLV_RICAVI_VENDITA,0) AS PLV_RICAVI_VENDITA,
		       ISNULL(PLV_ALTRI_RICAVI,0) AS PLV_ALTRI_RICAVI,
               ISNULL(CP_MATERIE_PRIME,0) AS CP_MATERIE_PRIME,
			   ISNULL(CP_SERVIZI,0) AS CP_SERVIZI,
			   ISNULL(CP_BENI_TERZI,0) AS CP_BENI_TERZI,
			   ISNULL(CP_PERSONALE,0) AS CP_PERSONALE,
			   ISNULL(CP_AMM_SVALUTAZIONI,0) AS CP_AMM_SVALUTAZIONI,
			   ISNULL(CP_VAR_RIMANENZE,0) AS CP_VAR_RIMANENZE,
			   ISNULL(CP_ONERI,0) AS CP_ONERI,
			   ISNULL(POF_ALTRI_PROVENTI,0) AS POF_ALTRI_PROVENTI,
			   ISNULL(POF_INTERESSI_ONERI,0) AS POF_INTERESSI_ONERI,
			   ISNULL(RETT_VAL_ATT_FINANZIARIE,0) AS RETT_VAL_ATT_FINANZIARIE,
			   ISNULL(POS_PROVENTI_STRAORD,0) AS POS_PROVENTI_STRAORD,
			   ISNULL(POS_ONERI_STRAORD,0) AS POS_ONERI_STRAORD,
			   ISNULL(TOT_PRIMA_IMPOSTE,0) AS TOT_PRIMA_IMPOSTE,
			   ISNULL(IMPOSTE_REDDITO,0) AS IMPOSTE_REDDITO,
			   ISNULL(TA_CREDITI_SOCI,0) AS TA_CREDITI_SOCI,
			   ISNULL(TA_IMM_IMMATERIALI,0) AS TA_IMM_IMMATERIALI,
			   ISNULL(TA_IMMOB_MATERIALI,0) AS TA_IMMOB_MATERIALI,
			   ISNULL(TA_IMM_PARTECIPAZIONI,0) AS TA_IMM_PARTECIPAZIONI,
			   ISNULL(TA_IMM_CREDITI,0) AS TA_IMM_CREDITI,
			   ISNULL(TA_AC_RIMANENZE,0) AS TA_AC_RIMANENZE,
			   ISNULL(TA_AC_CREDITI_CLIENTI,0) AS TA_AC_CREDITI_CLIENTI,
			   ISNULL(TA_AC_CREDITI_ALTRI,0) AS TA_AC_CREDITI_ALTRI,
			   ISNULL(TA_AC_DEP_POSTALI,0) AS TA_AC_DEP_POSTALI,
			   ISNULL(TA_AC_DISPO_LIQUIDE,0) AS TA_AC_DISPO_LIQUIDE,
			   ISNULL(TA_RATEI_RISCONTI,0) AS TA_RATEI_RISCONTI,
			   ISNULL(TP_PN_CAPITALE,0) AS TP_PN_CAPITALE,
			   ISNULL(TP_PN_SOVRAP_AZIONI,0) AS TP_PN_SOVRAP_AZIONI,
			   ISNULL(TP_PN_RIS_RIVALUTAZIONE,0) AS TP_PN_RIS_RIVALUTAZIONE,
			   ISNULL(TP_PN_RIS_LEGALE,0) AS TP_PN_RIS_LEGALE,
			   ISNULL(TP_PN_AZIONI_PROPRIE,0) AS TP_PN_AZIONI_PROPRIE,
			   ISNULL(TP_PN_RISERVA_904,0) AS TP_PN_RISERVA_904,
			   ISNULL(TP_PN_RISERVE_STATUTARIE,0) AS TP_PN_RISERVE_STATUTARIE,
			   ISNULL(TP_PN_ALTRE_RISERVE,0) AS TP_PN_ALTRE_RISERVE,
			   ISNULL(TP_PN_UTILI_PRECEDENTI,0) AS TP_PN_UTILI_PRECEDENTI,
			   ISNULL(TP_PN_UTILI_ESERCIZIO,0) AS TP_PN_UTILI_ESERCIZIO,
			   ISNULL(TP_FONDI_RISCHI_ONERI,0) AS TP_FONDI_RISCHI_ONERI,
			   ISNULL(TP_FINE_RAPPORTO,0) AS TP_FINE_RAPPORTO,
			   ISNULL(TP_DEBITI_BANCHE,0) AS TP_DEBITI_BANCHE,
			   ISNULL(TP_DEBITI_FINANZIATORI,0) AS TP_DEBITI_FINANZIATORI,
			   ISNULL(TP_DEBITI_FORNITORI,0) AS TP_DEBITI_FORNITORI,
			   ISNULL(TP_DEBITI_IST_PREVID,0) AS TP_DEBITI_IST_PREVID,
			   ISNULL(TP_ALTRI_DEBITI,0) AS TP_ALTRI_DEBITI,
			   ISNULL(TP_RATEI_RISCONTI,0) AS TP_RATEI_RISCONTI


		FROM BILANCIO_INDUSTRIALE
		
		WHERE PREVISIONALE = 1 AND ID_PROGETTO = @ID_Domanda ORDER BY ANNO 
	END	    		
	ELSE SELECT NULL AS ANNO,
				NULL AS DATA_BILANCIO,
				NULL AS PLV_RICAVI_VENDITA,
				NULL AS PLV_ALTRI_RICAVI,
				NULL AS CP_MATERIE_PRIME,
				NULL AS CP_SERVIZI,
				NULL AS CP_BENI_TERZI,
				NULL AS CP_PERSONALE,
				NULL AS CP_AMM_SVALUTAZIONI,
				NULL AS CP_VAR_RIMANENZE,
				NULL AS CP_ONERI,
				NULL AS POF_ALTRI_PROVENTI,
				NULL AS POF_INTERESSI_ONERI,
				NULL AS RETT_VAL_ATT_FINANZIARIE,
				NULL AS POS_PROVENTI_STRAORD,
				NULL AS POS_ONERI_STRAORD,
				NULL AS TOT_PRIMA_IMPOSTE,
				NULL AS IMPOSTE_REDDITO,
				NULL AS TA_CREDITI_SOCI,
				NULL AS TA_IMM_IMMATERIALI,
				NULL AS TA_IMMOB_MATERIALI,
				NULL AS TA_IMM_PARTECIPAZIONI,
				NULL AS TA_IMM_CREDITI,
				NULL AS TA_AC_RIMANENZE,
				NULL AS TA_AC_CREDITI_CLIENTI,
				NULL AS TA_AC_CREDITI_ALTRI,
				NULL AS TA_AC_DEP_POSTALI,
				NULL AS TA_AC_DISPO_LIQUIDE,
				NULL AS TA_RATEI_RISCONTI,
				NULL AS TP_PN_CAPITALE,
				NULL AS TP_PN_SOVRAP_AZIONI,
				NULL AS TP_PN_RIS_RIVALUTAZIONE,
				NULL AS TP_PN_RIS_LEGALE,
				NULL AS TP_PN_AZIONI_PROPRIE,
				NULL AS TP_PN_RISERVA_904,
				NULL AS TP_PN_RISERVE_STATUTARIE,
				NULL AS TP_PN_ALTRE_RISERVE,
				NULL AS TP_PN_UTILI_PRECEDENTI,
				NULL AS TP_PN_UTILI_ESERCIZIO,
				NULL AS TP_FONDI_RISCHI_ONERI,
				NULL AS TP_FINE_RAPPORTO,
				NULL AS TP_DEBITI_BANCHE,
				NULL AS TP_DEBITI_FINANZIATORI,
				NULL AS TP_DEBITI_FORNITORI,
				NULL AS TP_DEBITI_IST_PREVID,
				NULL AS TP_ALTRI_DEBITI,
				NULL AS TP_RATEI_RISCONTI

END