CREATE PROCEDURE [dbo].[RptBandoVariante] 
(
@IdProgrammazione int
)
AS
BEGIN
SET NOCOUNT ON;

--DECLARE @IdPsr int,
--@CodAsse int, 
--@CodMisura int

--SET @IdPsr = 1 
--SET @CodAsse = 1 
--SET @CodMisura = 5

		SELECT ISNULL(P.ID_PROG_INTEGRATO, P.ID_PROGETTO) AS ID_PROGETTO, 
		RAGIONE_SOCIALE, 
		PR.DESCRIZIONE AS PSR, 
		PR.CODICE AS CODICE_MISURA, 
		VBA.DATA_SCADENZA, 
		P.PROVINCIA_DI_PRESENTAZIONE, 
		V.SEGNATURA AS SEGNATURA_PRESENTAZIONE, V.ID_VARIANTE, 
		0 AS COSTO_PREC,
		0 AS CONTRIBUTO_PREC,
		dbo.calcoloCostoTotaleProgetto(P.ID_PROGETTO, 1, V.ID_VARIANTE) AS COSTO,
		DBO.calcoloContributoTotaleProgetto(P.ID_PROGETTO, 1, V.ID_VARIANTE) AS CONTRIBUTO,
		dbo.calcoloPremioContoCapitale(P.ID_PROGETTO, 1, V.ID_VARIANTE) AS PREMIO, 
		V.TIPO_VARIANTE, V.APPROVATA, V.DATA_MODIFICA, 
		V.COD_TIPO,  V.ANNULLATA, V.DATA_ANNULLAMENTO, V.SEGNATURA_ANNULLAMENTO, V.SEGNATURA_APPROVAZIONE, 
		A.NUMERO AS NUMERO_ATTO, A.DATA AS DATA_ATTO, A.DESCRIZIONE, VXP.FLAG_DEFINITIVO,
		 VXP.PUNT AS PUNTEGGIO,
		V.DATA_APPROVAZIONE,
		VS.SEGNATURA AS SEGNATURA_COMUNICAZIONE

		FROM vVARIANTI AS V 
		INNER JOIN PROGETTO AS P ON V.ID_PROGETTO = P.ID_PROGETTO 
		INNER JOIN vBANDO AS VBA ON VBA.ID_BANDO = P.ID_BANDO 
		INNER JOIN vzPROGRAMMAZIONE PR ON VBA.ID_PROGRAMMAZIONE = PR.ID
		LEFT JOIN ATTI AS A ON A.ID_ATTO = V.ID_ATTO_APPROVAZIONE 
		LEFT OUTER JOIN (SELECT SUM(PUNTEGGIO) AS PUNT, ID_VARIANTE, FLAG_DEFINITIVO
						 FROM VARIANTI_X_PRIORITA
						 GROUP BY ID_VARIANTE, FLAG_DEFINITIVO) 
						 AS VXP ON VXP.ID_VARIANTE = V.ID_VARIANTE 
		LEFT OUTER JOIN VARIANTI_SEGNATURE AS VS ON VS.ID_VARIANTE = V.ID_VARIANTE AND VS.COD_TIPO = 'CEI'
		INNER JOIN VIMPRESA I ON I.ID_IMPRESA = P.ID_IMPRESA
		WHERE (V.SEGNATURA IS NOT NULL) 
		AND VBA.ID_PROGRAMMAZIONE = @IdProgrammazione

END
