CREATE PROCEDURE [dbo].[RptBusinessPlan_PianoColturale] 
@ID_Impresa int,
@ID_Domanda int
AS
BEGIN
	SET NOCOUNT ON;
				
	DECLARE @CUAA varchar(16)
    DECLARE @Count int
    DECLARE @FASE CHAR(1)
		
	IF (@ID_Domanda IS NOT NULL)
	 BEGIN
	  SET @ID_Impresa = (SELECT ID_IMPRESA FROM PROGETTO WHERE ID_PROGETTO = @ID_Domanda)
	 END
	 
	SET @Count = (SELECT COUNT(ID_IMPRESA) FROM PIANO_COLTURALE_STORICO WHERE ID_IMPRESA = @ID_Impresa)
	
	IF(ISNULL(@FASE, 1) < 2 )
	BEGIN	 
		IF (@Count > 0)		
		BEGIN	
			SELECT dbo.MqAEttari(PC.SUPERFICIE_COLTURA) AS SUPERFICIE_COLTURA, dbo.MqAEttari(PC.SUPERFICIE_FILIERA) AS SUPERFICIE_FILIERA, PC.VARIETA, 
						  PC.PRODOTTO, PC.FOGLIO_CATASTALE, PC.PARTICELLA, PC.SEZIONE, PC.SUBALTERNO, dbo.MqAEttari(PC.SUPERFICIE_CATASTALE) 
						  AS SUPERFICIE_CATASTALE, PC.SVANTAGGIO, PC.COMUNE, PC.SIGLA, PC.CAP, PS.DATA_FINE, PS.ID_RIF
			FROM vPIANO_COLTURALE_IMPRESA AS PC INNER JOIN
				 (SELECT MAX(ID_RIF) AS ID_RIF, MAX(DATA_FINE) AS DATA_FINE
				 FROM PIANO_COLTURALE_STORICO
				 WHERE (ID_IMPRESA = @ID_Impresa) AND (DATA_FINE IS NOT NULL)) AS PS ON PS.ID_RIF = PC.ID_RIF
			WHERE (PC.DATA_FINE_VALIDITA IS NULL)	
		END
		ELSE SELECT NULL AS SUPERFICIE_COLTURA, 
			NULL AS SUPERFICIE_FILIERA, 
			NULL AS VARIETA, 
            NULL AS PRODOTTO, 
            NULL AS FOGLIO_CATASTALE, 
            NULL AS PARTICELLA, 
            NULL AS SEZIONE, 
            NULL AS SUBALTERNO, 
            NULL AS SUPERFICIE_CATASTALE, 
            NULL AS SVANTAGGIO, 
            NULL AS COMUNE, 
            NULL AS SIGLA, 
            NULL AS CAP,
			NULL AS DATA_FINE			
	END
	ELSE
		BEGIN		 
			SELECT dbo.MqAEttari(PC.SUPERFICIE_COLTURA) AS SUPERFICIE_COLTURA, dbo.MqAEttari(PC.SUPERFICIE_FILIERA) AS SUPERFICIE_FILIERA, PC.VARIETA, 
						  PC.PRODOTTO, PC.FOGLIO_CATASTALE, PC.PARTICELLA, PC.SEZIONE, PC.SUBALTERNO, dbo.MqAEttari(PC.SUPERFICIE_CATASTALE) 
						  AS SUPERFICIE_CATASTALE, PC.SVANTAGGIO, PC.COMUNE, PC.SIGLA, PC.CAP, PS.DATA_FINE
			FROM vPIANO_COLTURALE_IMPRESA AS PC INNER JOIN
				 (SELECT MAX(ID_RIF) AS ID_RIF, MAX(DATA_FINE) AS DATA_FINE
				 FROM PIANO_COLTURALE_STORICO
				 WHERE (ID_IMPRESA = @ID_Impresa) 
				 AND (DATA_FINE < (SELECT TOP 1 DATA FROM PROGETTO_STORICO WHERE ID_PROGETTO =  @ID_Domanda AND COD_STATO IN ('A', 'B') ORDER BY ID DESC)))
				  AS PS ON PS.ID_RIF = PC.ID_RIF
			WHERE (PC.DATA_FINE_VALIDITA IS NULL)	
		END
		
	END
