CREATE PROCEDURE [dbo].[RptBusinessPlan_PlvAnnoCorrente] 
@ID_Impresa int,
@ID_Domanda int,
@TipoPLV int
AS
BEGIN
	SET NOCOUNT ON;
    	
DECLARE @Count int
DECLARE @CountPac int
DECLARE @Anno int
		
	IF (@ID_Domanda IS NOT NULL) SELECT @Count = COUNT(ID_PLV), @Anno = MIN(ANNO) FROM vPLV_AZIENDALE WHERE ID_PROGETTO = @ID_Domanda AND PREVISIONALE = 0   					
	ELSE SELECT @Count = COUNT(ID_PLV) FROM PLV_IMPRESA WHERE ID_IMPRESA = @ID_Impresa AND PREVISIONALE = 0 AND ID_PROGETTO IS NULL

	IF (@Count > 0)
	 BEGIN
	
		IF (@TipoPLV = 0) -- Plv Piano Colturale					 
			   
		   IF (@ID_Domanda IS NOT NULL) -- a livello di domanda
				BEGIN
			     SELECT PLVA.PRODOTTO,PLVA.VARIETA, 
                      dbo.MqAEttari(PLVA.SAU) AS SAU,
                      ISNULL(PLVA.RESA_COLTURA,0) AS RESA_COLTURA,
                      ISNULL(PLVA.PRODUZIONE_UNITARIA,0) AS PRODUZIONE_UNITARIA,
			          ISNULL(PLVA.QUANTITA_REIMPIEGO,0) AS QUANTITA_REIMPIEGO, 
                      ISNULL(PLVA.PREZZO_COLTURA,0) AS PREZZO_COLTURA,
                      ISNULL(PLVA.PREZZO_UNITARIO_ALLEVAMENTI,0) AS PREZZO_UNITARIO_ALLEVAMENTI,
                      ISNULL(PLVA.PREZZO_ATTIVITA_CONNESSE,0) AS PREZZO_ATTIVITA_CONNESSE, 
                      ISNULL(PLVA.PREZZO_UNITARIO,0) AS PREZZO_UNITARIO,
					  UM.DESCRIZIONE AS UNITA_MISURA,
					  ISNULL(PLVA.PLV,0) AS PLV,
                      ISNULL(PLVA.ORE_UNITARIE,0) AS ORE_UNITARIE,
                      ISNULL(PLVA.ORE_COLTURA,0) AS ORE_COLTURA,
			          PLVA.ATTIVITA_CONNESSA,                       
			          PLVA.PAC,
					  PLVA.FLAG_BIOLOGICO,
					  PLVA.FLAG_ZONASVANTAGGIATA,
					  PLVA.FLAG_COMMERCIALIZZAZIONE,
					  PLVA.FLAG_TRASFORMAZIONE,
					  PLVA.CLASSE_ALLEVAMENTO,
					  PLVA.PRODUZIONE_UNITARIA_ALLEVAMENTI,
                      ISNULL(PLVA.ORE_ALLEVAMENTI,0) AS ORE_ALLEVAMENTI,
					  dbo.MqAEttari((SELECT SUM(SAU) 
									FROM vPLV_AZIENDALE PLVA LEFT JOIN UNITA_DI_MISURA UM ON (PLVA.ID_UNITA_MISURA = UM.ID_UNITA_MISURA) 
									WHERE ID_PROGETTO = @ID_Domanda AND COD_PRODOTTO IS NOT NULL AND PREVISIONALE = 0 AND ANNO = @Anno
									AND PREVISIONALE = 0)) AS TOT_SAU

			   FROM vPLV_AZIENDALE PLVA LEFT JOIN UNITA_DI_MISURA UM ON (PLVA.ID_UNITA_MISURA = UM.ID_UNITA_MISURA)

			   WHERE ID_PROGETTO = @ID_Domanda AND COD_PRODOTTO IS NOT NULL AND PREVISIONALE = 0 AND ANNO = @Anno
				END
		   ELSE -- a livello di impresa
				BEGIN
			    SELECT PLVA.PRODOTTO,PLVA.VARIETA, 
                      dbo.MqAEttari(PLVA.SAU) AS SAU,
                      ISNULL(PLVA.RESA_COLTURA,0) AS RESA_COLTURA,
                      ISNULL(PLVA.PRODUZIONE_UNITARIA,0) AS PRODUZIONE_UNITARIA,
			          ISNULL(PLVA.QUANTITA_REIMPIEGO,0) AS QUANTITA_REIMPIEGO, 
                      ISNULL(PLVA.PREZZO_COLTURA,0) AS PREZZO_COLTURA,
                      ISNULL(PLVA.PREZZO_UNITARIO_ALLEVAMENTI,0) AS PREZZO_UNITARIO_ALLEVAMENTI,
                      ISNULL(PLVA.PREZZO_ATTIVITA_CONNESSE,0) AS PREZZO_ATTIVITA_CONNESSE, 
                      ISNULL(PLVA.PREZZO_UNITARIO,0) AS PREZZO_UNITARIO,
					  UM.DESCRIZIONE AS UNITA_MISURA,
					  ISNULL(PLVA.PLV,0) AS PLV,
                      ISNULL(PLVA.ORE_UNITARIE,0) AS ORE_UNITARIE,
                      ISNULL(PLVA.ORE_COLTURA,0) AS ORE_COLTURA,
			          PLVA.ATTIVITA_CONNESSA,                       
			          PLVA.PAC,
					  PLVA.FLAG_BIOLOGICO,
					  PLVA.FLAG_ZONASVANTAGGIATA,
					  PLVA.FLAG_COMMERCIALIZZAZIONE,
					  PLVA.FLAG_TRASFORMAZIONE,
					  PLVA.CLASSE_ALLEVAMENTO,
					  PLVA.PRODUZIONE_UNITARIA_ALLEVAMENTI,
                      ISNULL(PLVA.ORE_ALLEVAMENTI,0) AS ORE_ALLEVAMENTI,
					  dbo.MqAEttari((SELECT SUM(SAU) 
									FROM vPLV_AZIENDALE PLVA LEFT JOIN UNITA_DI_MISURA UM ON (PLVA.ID_UNITA_MISURA = UM.ID_UNITA_MISURA) 
									WHERE ID_IMPRESA = @ID_Impresa AND PREVISIONALE = 0 AND COD_PRODOTTO IS NOT NULL AND ID_PROGETTO IS NULL 
									AND PREVISIONALE = 0)) AS TOT_SAU

			   FROM vPLV_AZIENDALE PLVA LEFT JOIN UNITA_DI_MISURA UM ON (PLVA.ID_UNITA_MISURA = UM.ID_UNITA_MISURA)

			   WHERE ID_IMPRESA = @ID_Impresa AND PREVISIONALE = 0 AND COD_PRODOTTO IS NOT NULL AND ID_PROGETTO IS NULL 
			END
		ELSE IF (@TipoPLV = 1) -- Plv Zootecnica		
			
		   IF (@ID_Domanda IS NOT NULL) -- a livello di domanda
			BEGIN
				   SELECT PLVA.PRODOTTO,PLVA.VARIETA, 
                      ISNULL(PLVA.SAU, 0) AS SAU,
                      ISNULL(PLVA.RESA_COLTURA,0) AS RESA_COLTURA,
                      ISNULL(PLVA.PRODUZIONE_UNITARIA,0) AS PRODUZIONE_UNITARIA,
			          ISNULL(PLVA.QUANTITA_REIMPIEGO,0) AS QUANTITA_REIMPIEGO, 
                      ISNULL(PLVA.PREZZO_COLTURA,0) AS PREZZO_COLTURA,
                      ISNULL(PLVA.PREZZO_UNITARIO_ALLEVAMENTI,0) AS PREZZO_UNITARIO_ALLEVAMENTI,
                      ISNULL(PLVA.PREZZO_ATTIVITA_CONNESSE,0) AS PREZZO_ATTIVITA_CONNESSE, 
                      ISNULL(PLVA.PREZZO_UNITARIO,0) AS PREZZO_UNITARIO,
					  UM.DESCRIZIONE AS UNITA_MISURA,
					  ISNULL(PLVA.PLV,0) AS PLV,
                      ISNULL(PLVA.ORE_UNITARIE,0) AS ORE_UNITARIE,
                      ISNULL(PLVA.ORE_COLTURA,0) AS ORE_COLTURA,
			          PLVA.ATTIVITA_CONNESSA,                       
			          PLVA.PAC,
					  PLVA.FLAG_BIOLOGICO,
					  PLVA.FLAG_ZONASVANTAGGIATA,
					  PLVA.FLAG_COMMERCIALIZZAZIONE,
					  PLVA.FLAG_TRASFORMAZIONE,
					  PLVA.CLASSE_ALLEVAMENTO,
					  PLVA.PRODUZIONE_UNITARIA_ALLEVAMENTI,
                      ISNULL(PLVA.ORE_ALLEVAMENTI,0) AS ORE_ALLEVAMENTI,
					  dbo.MqAEttari((SELECT SUM(SAU) 
									FROM vPLV_AZIENDALE PLVA LEFT JOIN UNITA_DI_MISURA UM ON (PLVA.ID_UNITA_MISURA = UM.ID_UNITA_MISURA) 
									WHERE ID_PROGETTO = @ID_Domanda AND ID_CLASSE_ALLEVAMENTO IS NOT NULL AND PREVISIONALE = 0 AND ANNO = @Anno
									AND PREVISIONALE = 0)) AS TOT_SAU

			   FROM vPLV_AZIENDALE PLVA LEFT JOIN UNITA_DI_MISURA UM ON (PLVA.ID_UNITA_MISURA = UM.ID_UNITA_MISURA)

			   WHERE ID_PROGETTO = @ID_Domanda AND ID_CLASSE_ALLEVAMENTO IS NOT NULL AND PREVISIONALE = 0 AND ANNO = @Anno
			END
		   ELSE -- a livello di impresa
			BEGIN
				   SELECT PLVA.PRODOTTO,PLVA.VARIETA, 
                      ISNULL(PLVA.SAU, 0) AS SAU,
                      ISNULL(PLVA.RESA_COLTURA,0) AS RESA_COLTURA,
                      ISNULL(PLVA.PRODUZIONE_UNITARIA,0) AS PRODUZIONE_UNITARIA,
			          ISNULL(PLVA.QUANTITA_REIMPIEGO,0) AS QUANTITA_REIMPIEGO, 
                      ISNULL(PLVA.PREZZO_COLTURA,0) AS PREZZO_COLTURA,
                      ISNULL(PLVA.PREZZO_UNITARIO_ALLEVAMENTI,0) AS PREZZO_UNITARIO_ALLEVAMENTI,
                      ISNULL(PLVA.PREZZO_ATTIVITA_CONNESSE,0) AS PREZZO_ATTIVITA_CONNESSE, 
                      ISNULL(PLVA.PREZZO_UNITARIO,0) AS PREZZO_UNITARIO,
					  UM.DESCRIZIONE AS UNITA_MISURA,
					  ISNULL(PLVA.PLV,0) AS PLV,
                      ISNULL(PLVA.ORE_UNITARIE,0) AS ORE_UNITARIE,
                      ISNULL(PLVA.ORE_COLTURA,0) AS ORE_COLTURA,
			          PLVA.ATTIVITA_CONNESSA,                       
			          PLVA.PAC,
					  PLVA.FLAG_BIOLOGICO,
					  PLVA.FLAG_ZONASVANTAGGIATA,
					  PLVA.FLAG_COMMERCIALIZZAZIONE,
					  PLVA.FLAG_TRASFORMAZIONE,
					  PLVA.CLASSE_ALLEVAMENTO,
					  PLVA.PRODUZIONE_UNITARIA_ALLEVAMENTI,
                      ISNULL(PLVA.ORE_ALLEVAMENTI,0) AS ORE_ALLEVAMENTI,
					  dbo.MqAEttari((SELECT SUM(SAU) 
									FROM vPLV_AZIENDALE PLVA LEFT JOIN UNITA_DI_MISURA UM ON (PLVA.ID_UNITA_MISURA = UM.ID_UNITA_MISURA) 
									WHERE ID_CLASSE_ALLEVAMENTO IS NOT NULL AND PREVISIONALE = 0 AND ID_PROGETTO IS NULL AND ID_IMPRESA = @ID_Impresa
									AND PREVISIONALE = 0)) AS TOT_SAU

			   FROM vPLV_AZIENDALE PLVA LEFT JOIN UNITA_DI_MISURA UM ON (PLVA.ID_UNITA_MISURA = UM.ID_UNITA_MISURA)
			   WHERE ID_CLASSE_ALLEVAMENTO IS NOT NULL AND PREVISIONALE = 0 AND ID_PROGETTO IS NULL AND ID_IMPRESA = @ID_Impresa
			END
		   ELSE IF (@TipoPLV = 2)  -- Plv Attività connesse	

		   IF (@ID_Domanda IS NOT NULL) -- a livello di domanda
			   
			    SELECT PLVA.PRODOTTO,PLVA.VARIETA, 
                      dbo.MqAEttari(PLVA.SAU) AS SAU,
                      ISNULL(PLVA.RESA_COLTURA,0) AS RESA_COLTURA,
                      ISNULL(PLVA.PRODUZIONE_UNITARIA,0) AS PRODUZIONE_UNITARIA,
			          ISNULL(PLVA.QUANTITA_REIMPIEGO,0) AS QUANTITA_REIMPIEGO, 
                      ISNULL(PLVA.PREZZO_COLTURA,0) AS PREZZO_COLTURA,
                      ISNULL(PLVA.PREZZO_UNITARIO_ALLEVAMENTI,0) AS PREZZO_UNITARIO_ALLEVAMENTI,
                      ISNULL(PLVA.PREZZO_ATTIVITA_CONNESSE,0) AS PREZZO_ATTIVITA_CONNESSE, 
                      ISNULL(PLVA.PREZZO_UNITARIO,0) AS PREZZO_UNITARIO,
					  UM.DESCRIZIONE AS UNITA_MISURA,
					  ISNULL(PLVA.PLV,0) AS PLV,
                      ISNULL(PLVA.ORE_UNITARIE,0) AS ORE_UNITARIE,
                      ISNULL(PLVA.ORE_COLTURA,0) AS ORE_COLTURA,
			          PLVA.ATTIVITA_CONNESSA,                       
			          PLVA.PAC,
					  PLVA.FLAG_BIOLOGICO,
					  PLVA.FLAG_ZONASVANTAGGIATA,
					  PLVA.FLAG_COMMERCIALIZZAZIONE,
					  PLVA.FLAG_TRASFORMAZIONE,
					  PLVA.CLASSE_ALLEVAMENTO,
					  PLVA.PRODUZIONE_UNITARIA_ALLEVAMENTI,
                      ISNULL(PLVA.ORE_ALLEVAMENTI,0) AS ORE_ALLEVAMENTI,
					  dbo.MqAEttari((SELECT SUM(SAU) 
									FROM vPLV_AZIENDALE PLVA LEFT JOIN UNITA_DI_MISURA UM ON (PLVA.ID_UNITA_MISURA = UM.ID_UNITA_MISURA) 
									WHERE ID_PROGETTO = @ID_Domanda AND ID_ATTIVITA_CONNESSA IS NOT NULL AND PREVISIONALE = 0 AND ANNO = @Anno
									AND PREVISIONALE = 0)) AS TOT_SAU

			   FROM vPLV_AZIENDALE PLVA LEFT JOIN UNITA_DI_MISURA UM ON (PLVA.ID_UNITA_MISURA = UM.ID_UNITA_MISURA)

			   WHERE ID_PROGETTO = @ID_Domanda AND ID_ATTIVITA_CONNESSA IS NOT NULL AND PREVISIONALE = 0 AND ANNO = @Anno
			
		   ELSE -- a livello di impresa

			   SELECT PLVA.PRODOTTO,PLVA.VARIETA, 
                      dbo.MqAEttari(PLVA.SAU) AS SAU,
                      ISNULL(PLVA.RESA_COLTURA,0) AS RESA_COLTURA,
                      ISNULL(PLVA.PRODUZIONE_UNITARIA,0) AS PRODUZIONE_UNITARIA,
			          ISNULL(PLVA.QUANTITA_REIMPIEGO,0) AS QUANTITA_REIMPIEGO, 
                      ISNULL(PLVA.PREZZO_COLTURA,0) AS PREZZO_COLTURA,
                      ISNULL(PLVA.PREZZO_UNITARIO_ALLEVAMENTI,0) AS PREZZO_UNITARIO_ALLEVAMENTI,
                      ISNULL(PLVA.PREZZO_ATTIVITA_CONNESSE,0) AS PREZZO_ATTIVITA_CONNESSE, 
                      ISNULL(PLVA.PREZZO_UNITARIO,0) AS PREZZO_UNITARIO,
					  UM.DESCRIZIONE AS UNITA_MISURA,
					  ISNULL(PLVA.PLV,0) AS PLV,
                      ISNULL(PLVA.ORE_UNITARIE,0) AS ORE_UNITARIE,
                      ISNULL(PLVA.ORE_COLTURA,0) AS ORE_COLTURA,
			          PLVA.ATTIVITA_CONNESSA,                       
			          PLVA.PAC,
					  PLVA.FLAG_BIOLOGICO,
					  PLVA.FLAG_ZONASVANTAGGIATA,
					  PLVA.FLAG_COMMERCIALIZZAZIONE,
					  PLVA.FLAG_TRASFORMAZIONE,
					  PLVA.CLASSE_ALLEVAMENTO,
					  PLVA.PRODUZIONE_UNITARIA_ALLEVAMENTI,
                      ISNULL(PLVA.ORE_ALLEVAMENTI,0) AS ORE_ALLEVAMENTI,
					  dbo.MqAEttari((SELECT SUM(SAU) 
									FROM vPLV_AZIENDALE PLVA LEFT JOIN UNITA_DI_MISURA UM ON (PLVA.ID_UNITA_MISURA = UM.ID_UNITA_MISURA) 
									WHERE ID_IMPRESA = @ID_Impresa AND PREVISIONALE = 0 AND ID_ATTIVITA_CONNESSA IS NOT NULL AND ID_PROGETTO IS NULL)) AS TOT_SAU

			   FROM vPLV_AZIENDALE PLVA LEFT JOIN UNITA_DI_MISURA UM ON (PLVA.ID_UNITA_MISURA = UM.ID_UNITA_MISURA)

			   WHERE ID_IMPRESA = @ID_Impresa AND PREVISIONALE = 0 AND ID_ATTIVITA_CONNESSA IS NOT NULL AND ID_PROGETTO IS NULL

  		   ELSE IF (@TipoPLV = 3)  -- Contributi P.A.C.	

		   IF (@ID_Domanda IS NOT NULL) -- a livello di domanda
			BEGIN
			 SET @CountPac = (SELECT COUNT(ID_PLV) FROM vPLV_AZIENDALE WHERE ID_PROGETTO = @ID_Domanda AND PREVISIONALE = 0 AND  CODICE_PAC IS NOT NULL)						

			IF (@CountPac > 0)
	 		
			    SELECT PLVA.PRODOTTO,PLVA.VARIETA, 
                      dbo.MqAEttari(PLVA.SAU) AS SAU,
                      ISNULL(PLVA.RESA_COLTURA,0) AS RESA_COLTURA,
                      ISNULL(PLVA.PRODUZIONE_UNITARIA,0) AS PRODUZIONE_UNITARIA,
			          ISNULL(PLVA.QUANTITA_REIMPIEGO,0) AS QUANTITA_REIMPIEGO, 
                      ISNULL(PLVA.PREZZO_COLTURA,0) AS PREZZO_COLTURA,
                      ISNULL(PLVA.PREZZO_UNITARIO_ALLEVAMENTI,0) AS PREZZO_UNITARIO_ALLEVAMENTI,
                      ISNULL(PLVA.PREZZO_ATTIVITA_CONNESSE,0) AS PREZZO_ATTIVITA_CONNESSE, 
                      ISNULL(PLVA.PREZZO_UNITARIO,0) AS PREZZO_UNITARIO,
					  UM.DESCRIZIONE AS UNITA_MISURA,
					  ISNULL(PLVA.PLV,0) AS PLV,
                      ISNULL(PLVA.ORE_UNITARIE,0) AS ORE_UNITARIE,
                      ISNULL(PLVA.ORE_COLTURA,0) AS ORE_COLTURA,
			          PLVA.ATTIVITA_CONNESSA,                       
			          PLVA.PAC,
					  PLVA.FLAG_BIOLOGICO,
					  PLVA.FLAG_ZONASVANTAGGIATA,
					  PLVA.FLAG_COMMERCIALIZZAZIONE,
					  PLVA.FLAG_TRASFORMAZIONE,
					  PLVA.CLASSE_ALLEVAMENTO,
					  PLVA.PRODUZIONE_UNITARIA_ALLEVAMENTI,
                      ISNULL(PLVA.ORE_ALLEVAMENTI,0) AS ORE_ALLEVAMENTI,
					  dbo.MqAEttari((SELECT SUM(SAU) 
									FROM vPLV_AZIENDALE PLVA LEFT JOIN UNITA_DI_MISURA UM ON (PLVA.ID_UNITA_MISURA = UM.ID_UNITA_MISURA) 
									WHERE ID_PROGETTO = @ID_Domanda AND PLVA.CODICE_PAC IS NOT NULL  AND PREVISIONALE = 0 AND ANNO = @Anno)) AS TOT_SAU

			   FROM vPLV_AZIENDALE PLVA LEFT JOIN UNITA_DI_MISURA UM ON (PLVA.ID_UNITA_MISURA = UM.ID_UNITA_MISURA)
			
			   WHERE ID_PROGETTO = @ID_Domanda AND PLVA.CODICE_PAC IS NOT NULL  AND PREVISIONALE = 0 AND ANNO = @Anno
			ELSE
				    SELECT     CODICI_PAC.CODICE_PAC, 
                            CODICI_PAC.DESCRIZIONE AS PAC, 
							NULL AS PRODOTTO,
                            NULL AS VARIETA,
                            NULL AS SAU,
							NULL AS RESA_COLTURA,
                            NULL AS PRODUZIONE_UNITARIA,
							NULL AS QUANTITA_REIMPIEGO, 
                            NULL AS PREZZO_COLTURA,
							NULL AS PREZZO_UNITARIO_ALLEVAMENTI,
                            NULL AS PREZZO_ATTIVITA_CONNESSE, 
							NULL AS PREZZO_UNITARIO,
							NULL AS UNITA_MISURA,                            
							0 AS PLV, 
                            NULL AS ORE_UNITARIE ,
                            NULL AS CLASSE_ALLEVAMENTO,  							
							NULL AS ATTIVITA_CONNESSA

					FROM  CODICI_PAC 
			END

		   ELSE -- a livello di impresa
           BEGIN
			 SET @CountPac = (SELECT COUNT(ID_PLV) FROM vPLV_AZIENDALE WHERE Id_Impresa =@ID_Impresa AND PREVISIONALE = 0 
			 AND  CODICE_PAC IS NOT NULL  and Id_PROGETTO is null)   						

			IF (@CountPac > 0)
				    SELECT PLVA.PRODOTTO,PLVA.VARIETA, 
                      dbo.MqAEttari(PLVA.SAU) AS SAU,
                      ISNULL(PLVA.RESA_COLTURA,0) AS RESA_COLTURA,
                      ISNULL(PLVA.PRODUZIONE_UNITARIA,0) AS PRODUZIONE_UNITARIA,
			          ISNULL(PLVA.QUANTITA_REIMPIEGO,0) AS QUANTITA_REIMPIEGO, 
                      ISNULL(PLVA.PREZZO_COLTURA,0) AS PREZZO_COLTURA,
                      ISNULL(PLVA.PREZZO_UNITARIO_ALLEVAMENTI,0) AS PREZZO_UNITARIO_ALLEVAMENTI,
                      ISNULL(PLVA.PREZZO_ATTIVITA_CONNESSE,0) AS PREZZO_ATTIVITA_CONNESSE, 
                      ISNULL(PLVA.PREZZO_UNITARIO,0) AS PREZZO_UNITARIO,
					  UM.DESCRIZIONE AS UNITA_MISURA,
					  ISNULL(PLVA.PLV,0) AS PLV,
                      ISNULL(PLVA.ORE_UNITARIE,0) AS ORE_UNITARIE,
                      ISNULL(PLVA.ORE_COLTURA,0) AS ORE_COLTURA,
			          PLVA.ATTIVITA_CONNESSA,                       
			          PLVA.PAC,
					  PLVA.FLAG_BIOLOGICO,
					  PLVA.FLAG_ZONASVANTAGGIATA,
					  PLVA.FLAG_COMMERCIALIZZAZIONE,
					  PLVA.FLAG_TRASFORMAZIONE,
					  PLVA.CLASSE_ALLEVAMENTO,
					  PLVA.PRODUZIONE_UNITARIA_ALLEVAMENTI,
                      ISNULL(PLVA.ORE_ALLEVAMENTI,0) AS ORE_ALLEVAMENTI,
					  dbo.MqAEttari((SELECT SUM(SAU) 
									FROM vPLV_AZIENDALE PLVA LEFT JOIN UNITA_DI_MISURA UM ON (PLVA.ID_UNITA_MISURA = UM.ID_UNITA_MISURA) 
									WHERE ID_IMPRESA = @ID_Impresa AND PREVISIONALE = 0 AND PLVA.CODICE_PAC IS NOT NULL AND ID_PROGETTO IS NULL 
									AND PREVISIONALE = 0)) AS TOT_SAU

			   FROM vPLV_AZIENDALE PLVA 
				LEFT JOIN UNITA_DI_MISURA UM ON (PLVA.ID_UNITA_MISURA = UM.ID_UNITA_MISURA)

			   WHERE ID_IMPRESA = @ID_Impresa AND PREVISIONALE = 0 AND PLVA.CODICE_PAC IS NOT NULL AND ID_PROGETTO IS NULL 

		   ELSE
			     SELECT     CODICI_PAC.CODICE_PAC, 
                            CODICI_PAC.DESCRIZIONE AS PAC, 
							NULL AS PRODOTTO,
                            NULL AS VARIETA,
                            NULL AS SAU,
							NULL AS RESA_COLTURA,
                            NULL AS PRODUZIONE_UNITARIA,
							NULL AS QUANTITA_REIMPIEGO, 
                            NULL AS PREZZO_COLTURA,
							NULL AS PREZZO_UNITARIO_ALLEVAMENTI,
                            NULL AS PREZZO_ATTIVITA_CONNESSE, 
							NULL AS PREZZO_UNITARIO,
							NULL AS UNITA_MISURA,                            
							0 AS PLV, 
                            NULL AS ORE_UNITARIE ,
                            NULL AS CLASSE_ALLEVAMENTO,  							
							NULL AS ATTIVITA_CONNESSA

					FROM  CODICI_PAC 
		   END

	   ELSE  
	   SELECT NULL AS PRODOTTO,
					  NULL AS VARIETA, 
                      NULL AS SAU,
                      NULL AS RESA_COLTURA,
                      NULL AS PRODUZIONE_UNITARIA,
			          NULL AS QUANTITA_REIMPIEGO, 
                      NULL AS PREZZO_COLTURA,
                      NULL AS PREZZO_UNITARIO_ALLEVAMENTI,
                      NULL AS PREZZO_ATTIVITA_CONNESSE, 
                      NULL AS PREZZO_UNITARIO,
					  NULL AS UNITA_MISURA,
					  NULL AS PLV,
                      NULL AS ORE_UNITARIE,
                      NULL AS ORE_COLTURA,
			          NULL AS ATTIVITA_CONNESSA,                       
			          NULL AS PAC,
					  NULL AS FLAG_BIOLOGICO,
					  NULL AS FLAG_ZONASVANTAGGIATA,
					  NULL AS FLAG_COMMERCIALIZZAZIONE,
					  NULL AS FLAG_TRASFORMAZIONE,
					  NULL AS CLASSE_ALLEVAMENTO,
					  NULL AS PRODUZIONE_UNITARIA_ALLEVAMENTI,
                      NULL AS ORE_ALLEVAMENTI
	 END	
	 ELSE 	

	   SELECT NULL AS PRODOTTO,
					  NULL AS VARIETA, 
                      NULL AS SAU,
                      NULL AS RESA_COLTURA,
                      NULL AS PRODUZIONE_UNITARIA,
			          NULL AS QUANTITA_REIMPIEGO, 
                      NULL AS PREZZO_COLTURA,
                      NULL AS PREZZO_UNITARIO_ALLEVAMENTI,
                      NULL AS PREZZO_ATTIVITA_CONNESSE, 
                      NULL AS PREZZO_UNITARIO,
					  NULL AS UNITA_MISURA,
					  NULL AS PLV,
                      NULL AS ORE_UNITARIE,
                      NULL AS ORE_COLTURA,
			          NULL AS ATTIVITA_CONNESSA,                       
			          NULL AS PAC,
					  NULL AS FLAG_BIOLOGICO,
					  NULL AS FLAG_ZONASVANTAGGIATA,
					  NULL AS FLAG_COMMERCIALIZZAZIONE,
					  NULL AS FLAG_TRASFORMAZIONE,
					  NULL AS CLASSE_ALLEVAMENTO,
					  NULL AS PRODUZIONE_UNITARIA_ALLEVAMENTI,
                      NULL AS ORE_ALLEVAMENTI



END
