CREATE PROCEDURE [dbo].[RptDP_PianoInvestimenti]
(
	@ID_DOMANDA_PAGAMENTO INT, 
	@COD_TIPO_INVESTIMENTO INT 
)
AS

DECLARE @ID_PROGETTO INT
SET              @ID_PROGETTO =
                          (SELECT     ID_PROGETTO
                            FROM          DOMANDA_DI_PAGAMENTO
                            WHERE      ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO) 

DECLARE @ID_VARIANTE INT, @DATA_MODIFICA_PAGAMENTO DATETIME,  @COD_TIPO CHAR(3)
                          SELECT     @DATA_MODIFICA_PAGAMENTO = DATA_MODIFICA, @COD_TIPO = COD_TIPO
                           FROM         DOMANDA_DI_PAGAMENTO
                           WHERE     ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO
                                                      SELECT     @ID_VARIANTE = MAX(ID_VARIANTE)
                                                       FROM         VARIANTI
                                                       WHERE     ID_PROGETTO = @ID_PROGETTO AND ((APPROVATA = 1 AND COD_TIPO <> 'VI') or COD_TIPO='VI') 
SELECT     I.ID_INVESTIMENTO, I.ID_PROGETTO, I.ID_PROGRAMMAZIONE, I.DESCRIZIONE, I.DATA_VARIAZIONE, I.OPERATORE_VARIAZIONE, I.COD_STP, 
                      I.ID_UNITA_MISURA, I.QUANTITA, I.COSTO_INVESTIMENTO, I.SPESE_GENERALI, I.CONTRIBUTO_RICHIESTO,  I.QUOTA_CONTRIBUTO_RICHIESTO, 
                      I.ID_SETTORE_PRODUTTIVO, I.ID_PRIORITA_SETTORIALE, I.ID_OBIETTIVO_MISURA, I.AMMESSO, I.ISTRUTTORE, I.ID_INVESTIMENTO_ORIGINALE, 
                      I.DATA_VALUTAZIONE, I.ID_CODIFICA_INVESTIMENTO, I.ID_DETTAGLIO_INVESTIMENTO, I.ID_SPECIFICA_INVESTIMENTO, I.COD_TP, 
                      I.CODIFICA_INVESTIMENTO, I.AIUTO_MINIMO, I.CODICE, I.COD_SPECIFICA, I.SPECIFICA_INVESTIMENTI, I.DETTAGLIO_INVESTIMENTI, I.MOBILE, 
                      I.QUOTA_SPESE_GENERALI, I.SETTORE_PRODUTTIVO, I.COD_TIPO_INVESTIMENTO,
                      I.MISURA, I.RICHIEDI_PARTICELLA, I.VALUTAZIONE_INVESTIMENTO, I.ID_VARIANTE, 
                      I.COD_VARIAZIONE, I.TASSO_ABBUONO, PAGAMENTI_RICHIESTI.IMPORTO_COMPUTO_METRICO, 
                      PAGAMENTI_RICHIESTI.IMPORTO_RICHIESTO, PAGAMENTI_RICHIESTI.CONTRIBUTO_RICHIESTO AS CONTR_RICHIESTO, 
                      PAGAMENTI_RICHIESTI.IMPORTO_AMMESSO, PAGAMENTI_RICHIESTI.CONTRIBUTO_AMMESSO, PAGAMENTI_RICHIESTI.id_DOMANDA_PAGAMENTO,
                      dbo.calcoloContributoTotaleProgetto(@ID_PROGETTO, 1, @ID_VARIANTE) + dbo.calcoloPremioContoCapitale(@ID_PROGETTO, 1, @ID_VARIANTE) 
                      AS CONTRIBUTO_TOTALE, dbo.calcoloContributoInvestimentiProgetto(@ID_PROGETTO, 1, @ID_VARIANTE) as CONTRIBUTO_CALCOLATO, 
(SELECT     VALORI_PRIORITA.CODICE
	FROM         PRIORITA_X_INVESTIMENTI INNER JOIN VALORI_PRIORITA ON PRIORITA_X_INVESTIMENTI.ID_VALORE = VALORI_PRIORITA.ID_VALORE INNER JOIN	  PIANO_INVESTIMENTI ON PRIORITA_X_INVESTIMENTI.ID_INVESTIMENTO = PIANO_INVESTIMENTI.ID_INVESTIMENTO INNER JOIN  PROGETTO ON PIANO_INVESTIMENTI.ID_PROGETTO = PROGETTO.ID_PROGETTO
	WHERE     (PRIORITA_X_INVESTIMENTI.ID_PRIORITA IN (37,88, 92, 93, 94, 102, 103,116) ) AND PRIORITA_X_INVESTIMENTI.ID_INVESTIMENTO = I.ID_INVESTIMENTO) AS RENDIMENTO_GLOBALE
FROM         PROGETTO AS P INNER JOIN
                      vPIANO_INVESTIMENTI AS I ON P.ID_PROGETTO = I.ID_PROGETTO LEFT OUTER JOIN
                      PAGAMENTI_RICHIESTI ON I.ID_INVESTIMENTO = PAGAMENTI_RICHIESTI.ID_INVESTIMENTO 
                      AND PAGAMENTI_RICHIESTI.ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO
WHERE     (P.ID_PROGETTO=@ID_PROGETTO OR P.ID_PROG_INTEGRATO=@ID_PROGETTO) AND
		((@ID_VARIANTE IS NULL AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL) OR
		 (ID_VARIANTE=@ID_VARIANTE AND ISNULL(COD_VARIAZIONE,'X')!='A')) AND
		COD_TIPO_INVESTIMENTO = @COD_TIPO_INVESTIMENTO  
ORDER BY I.COD_TIPO_INVESTIMENTO, I.ID_INVESTIMENTO
