
CREATE PROCEDURE [dbo].[RptDA_Comunicazione_DatiBando]
(
	@ID_PROGETTO INT, 
	@COD_STATO CHAR(1)=null
)
AS
--DECLARE @ID_DOMANDA_PAGAMENTO INT;SET @ID_DOMANDA_PAGAMENTO =3346

SELECT  TOP (1) BANDO.DESCRIZIONE, PROVINCE.SIGLA, PROVINCE.DENOMINAZIONE, PR.SEGNATURA_ALLEGATI, P.SEGNATURA, 
               VUTENTI.NOMINATIVO, BANDO.ID_BANDO, BANDO.PAROLE_CHIAVE, BANDO.COD_ENTE, E.DESCRIZIONE AS ENTE, 
               ATTO_BANDO.NUMERO AS NUMERO_ATTO_BANDO, ATTO_BANDO.DATA AS DATA_ATTO_BANDO, ATTO_BANDO.REGISTRO AS REGISTRO_ATTO_BANDO, 
               ATTO_BANDO.DEFINIZIONE_ATTO AS DEFINIZIONE_ATTO_BANDO, 
               ATTO_GRADUATORIA.NUMERO AS NUMERO_ATTO_GRADUATORIA, ATTO_GRADUATORIA.DATA AS DATA_ATTO_GRADUATORIA, 
               ATTO_GRADUATORIA.REGISTRO AS REGISTRO_ATTO_GRADUATORIA, P.DATA AS DATA_PRESENTAZIONE
FROM PROGETTO PR INNER JOIN PROGETTO_STORICO P  ON PR.ID_PROGETTO = P.ID_PROGETTO AND P.COD_STATO = 'L'
INNER JOIN BANDO ON PR.ID_BANDO = BANDO.ID_BANDO 
INNER JOIN PROVINCE ON PR.PROVINCIA_DI_PRESENTAZIONE = PROVINCE.SIGLA 
LEFT JOIN BANDO_RESPONSABILI BR ON PR.ID_BANDO = BR.ID_BANDO AND 
                      PR.PROVINCIA_DI_PRESENTAZIONE = BR.PROVINCIA 
LEFT JOIN VUTENTI ON BR.ID_UTENTE = VUTENTI.ID_UTENTE 
INNER JOIN BANDO_STORICO BS ON BANDO.ID_BANDO = BS.ID_BANDO 
INNER JOIN vATTO AS ATTO_BANDO ON BS.ID_ATTO = ATTO_BANDO.ID_ATTO
LEFT JOIN ENTE E ON E.COD_ENTE = BANDO.COD_ENTE
LEFT JOIN BANDO_COMUNICAZIONI BC ON BANDO.ID_BANDO = BC.ID_BANDO 
					AND ((BC.COD_TIPO = 'CFI' AND @COD_STATO = 'F') OR (BC.COD_TIPO = 'CFN' AND @COD_STATO = 'N') OR (BC.COD_TIPO = 'NAD' AND @COD_STATO = 'B'))
LEFT JOIN (SELECT MAX(ID_ATTO) AS ID_MAX_ATTO, ID_PROGETTO 
						FROM PROGETTO_STORICO  WHERE COD_STATO  = @COD_STATO GROUP BY ID_PROGETTO) AS 	PS_GRADUATORIA 
				ON PR.ID_PROGETTO = PS_GRADUATORIA.ID_PROGETTO 
LEFT JOIN vATTO AS ATTO_GRADUATORIA ON ISNULL(PS_GRADUATORIA.ID_MAX_ATTO, BC.ID_ATTO) = ATTO_GRADUATORIA.ID_ATTO
WHERE P.ID_PROGETTO = @ID_PROGETTO AND BS.COD_STATO = 'L' 
ORDER BY BR.ID DESC
