CREATE PROCEDURE [dbo].[RptDP_BusinessPlan_Fatturato] 
@ID_Domanda int
AS
BEGIN
	SET NOCOUNT ON;
    	
	DECLARE @CUAA varchar(16)
    DECLARE @ID_Impresa int
    DECLARE @DATA_MODIFICA_DP DATETIME
		
	IF (@ID_Domanda IS NOT NULL)
	 BEGIN			  
		SET @ID_Impresa = (SELECT ID_IMPRESA FROM PROGETTO WHERE ID_PROGETTO = @ID_Domanda)
		SET @DATA_MODIFICA_DP = (SELECT DATA_MODIFICA FROM DOMANDA_DI_PAGAMENTO WHERE ID_PROGETTO = @ID_Domanda
										AND SEGNATURA IS NULL -- PRENDO LA DOMANDA DI PAGAMENTO IN STATO DI LAVORAZIONE 
										AND COD_TIPO = 'SLD')
	 END				
	SELECT ANNO, 			   
               ALIQUOTA AS ALIQUOTA,			   			   
			   IMPORTO AS IMPONIBILE,
			   ((IMPORTO*(ALIQUOTA/100)) + IMPORTO) AS TOTALE 

	FROM FATTURATO_AZIENDA 								  							  
	WHERE ID_IMPRESA = @ID_Impresa
	AND DATA_MODIFICA >= @DATA_MODIFICA_DP
	ORDER BY ANNO DESC				
END
