create PROCEDURE [dbo].[RptDP_BusinessPlan_ValutazionePianoSviluppo] 
@ID_DOMANDA_PAGAMENTO int
AS
BEGIN
	SET NOCOUNT ON;
			
   SELECT ANNO,
	   ISNULL(COSTO_INVESTIMENTO,0.00) AS COSTO_INVESTIMENTO,
	   ISNULL(MEZZI_PROPRI,0.00) AS MEZZI_PROPRI,
	   ISNULL(RISORSE_TERZI,0.00) AS RISORSE_TERZI,
	   ISNULL(CONTRIBUTI_PUBBLICI,0.00) AS CONTRIBUTI_PUBBLICI,
	   ISNULL(SPESE_GESTIONE,0.00) AS SPESE_GESTIONE,
	   ISNULL(RIMBORSO_DEBITO,0.00) AS RIMBORSO_DEBITO,
	   ISNULL(ENTRATA_GESTIONE,0.00) AS ENTRATA_GESTIONE,
	   ISNULL(ALTRE_COPERTURE,0.00) AS ALTRE_COPERTURE,               
	   (COSTO_INVESTIMENTO + SPESE_GESTIONE + RIMBORSO_DEBITO) AS TOTALE_FABBISOGNO,
	   (MEZZI_PROPRI + RISORSE_TERZI + CONTRIBUTI_PUBBLICI + ENTRATA_GESTIONE + ALTRE_COPERTURE) AS TOTALE_COPERTURA,			   
	   (MEZZI_PROPRI + RISORSE_TERZI + CONTRIBUTI_PUBBLICI + ENTRATA_GESTIONE + ALTRE_COPERTURE) -
	   (COSTO_INVESTIMENTO + SPESE_GESTIONE + RIMBORSO_DEBITO) AS SALDO_NETTO

	FROM dbo.PIANO_DI_SVILUPPO_DOMANDA_PAGAMENTO
							  
	WHERE ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO
	
	ORDER BY ANNO ASC				

END
