CREATE PROCEDURE [dbo].[RptDP_Comunicazione]
(
	@ID_DOMANDA_PAGAMENTO INT
)
AS
--DECLARE @ID_DOMANDA_PAGAMENTO INT;SET @ID_DOMANDA_PAGAMENTO =3346

-- modifica 11/12/2012
DECLARE @ID_PROGETTO INT,@ID_VARIANTE INT,@DATA_MODIFICA_PAGAMENTO DATETIME,@COD_TIPO CHAR(3),
@AMMONTARE_PREMIO_CONTO_CAPITALE DECIMAL(18,2) 
,@PREMIO_AMMESSO_PAG DECIMAL (18,2), @PREMIO_RICHIESTO_PAG DECIMAL(18,2)
SELECT @ID_PROGETTO=ID_PROGETTO,@DATA_MODIFICA_PAGAMENTO=DATA_MODIFICA,@COD_TIPO=COD_TIPO,@ID_VARIANTE=ID_VARIAZIONE_ACCERTATA 
FROM DOMANDA_DI_PAGAMENTO WHERE ID_DOMANDA_PAGAMENTO=@ID_DOMANDA_PAGAMENTO
IF @ID_VARIANTE IS NULL
	SELECT @ID_VARIANTE=MAX(ID_VARIANTE) FROM VARIANTI WHERE ID_PROGETTO=@ID_PROGETTO AND APPROVATA=1 AND ANNULLATA=0 
	AND DATA_MODIFICA<@DATA_MODIFICA_PAGAMENTO	

SELECT @AMMONTARE_PREMIO_CONTO_CAPITALE=dbo.calcoloPremioContoCapitale(@ID_PROGETTO,1,@ID_VARIANTE)
SELECT @PREMIO_AMMESSO_PAG = ISNULL(dbo.calcoloPremioContoCapitaleSaldo(@ID_DOMANDA_PAGAMENTO,1),0) 
SELECT @PREMIO_RICHIESTO_PAG =  ISNULL(dbo.calcoloPremioContoCapitaleSaldo(@ID_DOMANDA_PAGAMENTO,0),0) 

SELECT DISTINCT P.ID_PROGETTO, '1.1.2 C.C.' AS MISURA,
	CONTRIBUTO_AMMISSIBILE = CASE WHEN @COD_TIPO='SLD' THEN @PREMIO_AMMESSO_PAG ELSE 0 END,
	E.IMPORTO_SANZIONE AS AMMONTARE_SANZIONE,
	E.IMPORTO_RECUPERO_ANTICIPO AS RECUPERO_ANTICIPO,
	CONTRIBUTO_AMMESSO = CASE WHEN @COD_TIPO = 'SLD' THEN @PREMIO_AMMESSO_PAG - E.IMPORTO_RECUPERO_ANTICIPO - E.IMPORTO_SANZIONE
														 WHEN  @COD_TIPO = 'ANT' THEN  @PREMIO_AMMESSO_PAG  ELSE 0 END,
	Q1.COSTO_TOTALE_PROGETTO AS COSTO_TOTALE_PROGETTO_CORRELATO,
	0 AS IMPORTO_RICHIESTO,
		CONTRIBUTO_TOTALE_PROGETTO_CORRELATO = @AMMONTARE_PREMIO_CONTO_CAPITALE,
	CONTRIBUTO_RICHIESTO = CASE WHEN @COD_TIPO='SLD' THEN @PREMIO_RICHIESTO_PAG ELSE 0 END
FROM DOMANDA_DI_PAGAMENTO_ESPORTAZIONE E
INNER JOIN PROGETTO P ON E.ID_PROGETTO=P.ID_PROGETTO
INNER JOIN (
	SELECT ID_PROGETTO,CONTRIBUTO_DI_MISURA,0 AS COSTO_TOTALE_PROGETTO,
	0 AS CONTRIBUTO_TOTALE_PROGETTO
	FROM GRADUATORIA_PROGETTI_FINANZIABILITA WHERE ID_PROG_INTEGRATO=@ID_PROGETTO
	)Q1 ON E.ID_PROGETTO=Q1.ID_PROGETTO
WHERE E.ID_DOMANDA_PAGAMENTO=@ID_DOMANDA_PAGAMENTO and p.ID_PROGETTO = p.ID_PROG_INTEGRATO

UNION ALL


SELECT DISTINCT P.ID_PROGETTO, '1.1.2 C.I.' AS MISURA, 
CONTRIBUTO_AMMISSIBILE = E.IMPORTO_AMMISSIBILE - CASE WHEN @COD_TIPO = 'SLD' THEN @PREMIO_AMMESSO_PAG ELSE 0 END,
0 AS IMPORTO_SANZIONE ,
RECUPERO_ANTICIPO = 0,
CONTRIBUTO_AMMESSO =  E.IMPORTO_AMMISSIBILE - @PREMIO_AMMESSO_PAG ,
Q1.COSTO_TOTALE_PROGETTO AS COSTO_TOTALE_PROGETTO_CORRELATO,
ISNULL(Q2.IMPORTO_RICHIESTO,0) AS IMPORTO_RICHIESTO,
CONTRIBUTO_TOTALE_PROGETTO_CORRELATO=CASE 
WHEN Q1.CONTRIBUTO_TOTALE_PROGETTO>Q1.CONTRIBUTO_DI_MISURA THEN Q1.CONTRIBUTO_DI_MISURA ELSE Q1.CONTRIBUTO_TOTALE_PROGETTO END
- @AMMONTARE_PREMIO_CONTO_CAPITALE,
CONTRIBUTO_RICHIESTO = ISNULL(Q2.CONTRIBUTO_RICHIESTO,0) 
FROM DOMANDA_DI_PAGAMENTO_ESPORTAZIONE E
INNER JOIN PROGETTO P ON E.ID_PROGETTO=P.ID_PROGETTO
LEFT JOIN (
	SELECT ID_PROGETTO,SUM(RIC.IMPORTO_RICHIESTO) AS IMPORTO_RICHIESTO,SUM(RIC.CONTRIBUTO_RICHIESTO) AS CONTRIBUTO_RICHIESTO 
	FROM PIANO_INVESTIMENTI I INNER JOIN PAGAMENTI_RICHIESTI RIC ON I.ID_INVESTIMENTO=RIC.ID_INVESTIMENTO 
	WHERE RIC.ID_DOMANDA_PAGAMENTO=@ID_DOMANDA_PAGAMENTO GROUP BY ID_PROGETTO) Q2 ON Q2.ID_PROGETTO=P.ID_PROGETTO
LEFT JOIN (
	SELECT ID_PROGETTO,CONTRIBUTO_DI_MISURA,dbo.calcoloCostoTotaleProgettoCorrelato(ID_PROGETTO,1,@ID_VARIANTE) AS COSTO_TOTALE_PROGETTO,
		ISNULL(dbo.calcoloContributoTotaleProgettoCorrelato(ID_PROGETTO,1,@ID_VARIANTE),0)+CASE WHEN ID_PROGETTO=ID_PROG_INTEGRATO 
		THEN ISNULL(dbo.calcoloPremioContoCapitale(@ID_PROGETTO,1,@ID_VARIANTE),0) ELSE 0 END AS CONTRIBUTO_TOTALE_PROGETTO
	FROM GRADUATORIA_PROGETTI_FINANZIABILITA WHERE ID_PROG_INTEGRATO=@ID_PROGETTO) Q1 ON P.ID_PROGETTO=Q1.ID_PROGETTO
WHERE E.ID_DOMANDA_PAGAMENTO=@ID_DOMANDA_PAGAMENTO  and p.ID_PROGETTO = p.ID_PROG_INTEGRATO

UNION ALL

SELECT DISTINCT P.ID_PROGETTO,P_PRINC.CODICE AS MISURA,
	E.IMPORTO_AMMISSIBILE AS CONTRIBUTO_AMMISSIBILE,E.IMPORTO_SANZIONE AS AMMONTARE_SANZIONE,E.IMPORTO_RECUPERO_ANTICIPO AS RECUPERO_ANTICIPO,
	E.IMPORTO_AMMESSO AS CONTRIBUTO_AMMESSO,
	ISNULL( dbo.calcoloCostoTotaleProgettoCorrelato(P.ID_PROGETTO,1,@ID_VARIANTE), 0) AS COSTO_TOTALE_PROGETTO_CORRELATO,
	ISNULL(Q2.IMPORTO_RICHIESTO,0) AS IMPORTO_RICHIESTO,
	CONTRIBUTO_TOTALE_PROGETTO_CORRELATO= CASE WHEN dbo.calcoloContributoTotaleProgettoCorrelato(P.ID_PROGETTO,1,@ID_VARIANTE) >ISNULL(GPF.CONTRIBUTO_DI_MISURA, 0) + ISNULL(GP.CONTRIBUTO_TOTALE, 0) 
	THEN ISNULL(GPF.CONTRIBUTO_DI_MISURA, 0)  + ISNULL(GP.CONTRIBUTO_TOTALE, 0) 
	ELSE dbo.calcoloContributoTotaleProgettoCorrelato(P.ID_PROGETTO,1,@ID_VARIANTE)  END,
	CONTRIBUTO_RICHIESTO=ISNULL(Q2.CONTRIBUTO_RICHIESTO,0)
FROM DOMANDA_DI_PAGAMENTO D
INNER JOIN PROGETTO P ON D.ID_PROGETTO=ISNULL(P.ID_PROG_INTEGRATO , P.ID_PROGETTO)
INNER JOIN BANDO B ON P.ID_BANDO = B.ID_BANDO
INNER JOIN zPROGRAMMAZIONE P_PRINC ON B.ID_PROGRAMMAZIONE = P_PRINC.ID
LEFT JOIN  GRADUATORIA_PROGETTI_FINANZIABILITA  GPF ON P.ID_PROGETTO=GPF.ID_PROGETTO
LEFT JOIN GRADUATORIA_PROGETTI GP ON P.ID_PROGETTO = GP.ID_PROGETTO
LEFT JOIN DOMANDA_DI_PAGAMENTO_ESPORTAZIONE E ON D.ID_DOMANDA_PAGAMENTO=E.ID_DOMANDA_PAGAMENTO AND P.ID_PROGETTO=E.ID_PROGETTO
LEFT JOIN (
	SELECT ID_PROGETTO,SUM(RIC.IMPORTO_RICHIESTO) AS IMPORTO_RICHIESTO,SUM(RIC.CONTRIBUTO_RICHIESTO) AS CONTRIBUTO_RICHIESTO 
	FROM PIANO_INVESTIMENTI I INNER JOIN PAGAMENTI_RICHIESTI RIC ON I.ID_INVESTIMENTO=RIC.ID_INVESTIMENTO 
	WHERE RIC.ID_DOMANDA_PAGAMENTO=@ID_DOMANDA_PAGAMENTO GROUP BY ID_PROGETTO) Q2 ON Q2.ID_PROGETTO=P.ID_PROGETTO
WHERE D.ID_DOMANDA_PAGAMENTO=@ID_DOMANDA_PAGAMENTO AND (P.ID_PROG_INTEGRATO <> P.ID_PROGETTO OR P.ID_PROG_INTEGRATO IS NULL)






-- modifica di novembre 2012
/*
DECLARE @ID_PROGETTO INT,@ID_VARIANTE INT,@DATA_MODIFICA_PAGAMENTO DATETIME,@COD_TIPO CHAR(3),@AMMONTARE_PREMIO_CONTO_CAPITALE DECIMAL(18,2), @AMMONTARE_PREMIO_SALDO DECIMAL (18,2)
SELECT @ID_PROGETTO=ID_PROGETTO,@DATA_MODIFICA_PAGAMENTO=DATA_MODIFICA,@COD_TIPO=COD_TIPO,@ID_VARIANTE=ID_VARIAZIONE_ACCERTATA 
FROM DOMANDA_DI_PAGAMENTO WHERE ID_DOMANDA_PAGAMENTO=@ID_DOMANDA_PAGAMENTO
IF @ID_VARIANTE IS NULL
	SELECT @ID_VARIANTE=MAX(ID_VARIANTE) FROM VARIANTI WHERE ID_PROGETTO=@ID_PROGETTO AND APPROVATA=1 AND ANNULLATA=0 
	AND DATA_MODIFICA<@DATA_MODIFICA_PAGAMENTO	

DECLARE @TMP TABLE
(
	ID_PROGETTO INT, ID_BANDO INT ,MISURA VARCHAR(7),	MISURA_PREVALENTE BIT, 
	CONTRIBUTO_AMMISSIBILE DECIMAL(18,2), AMMONTARE_SANZIONE DECIMAL(18,2),
	RECUPERO_ANTICIPO  DECIMAL(18,2),CONTRIBUTO_AMMESSO  DECIMAL(18,2),
	COSTO_TOTALE_PROGETTO_CORRELATO  DECIMAL(18,2), IMPORTO_RICHIESTO  DECIMAL(18,2),
	CONTRIBUTO_TOTALE_PROGETTO_CORRELATO  DECIMAL(18,2),CONTRIBUTO_RICHIESTO  DECIMAL(18,2)
)
 INSERT INTO @TMP 
exec SpRiepilogoImportiDomandaPagamentoXMisura @ID_DOMANDA_PAGAMENTO


SELECT ID_PROGETTO, 
	MISURA,	
	CONTRIBUTO_AMMISSIBILE , 
	AMMONTARE_SANZIONE ,
	RECUPERO_ANTICIPO,CONTRIBUTO_AMMESSO,
	COSTO_TOTALE_PROGETTO_CORRELATO,
	CONTRIBUTO_TOTALE_PROGETTO_CORRELATO,
	IMPORTO_RICHIESTO,CONTRIBUTO_RICHIESTO
FROM @TMP

UNION ALL
SELECT DPE.ID_PROGETTO, 
PR.CODICE AS MISURA, 
DPE.IMPORTO_AMMISSIBILE AS CONTRIBUTO_AMMISSIBILE,
DPE.IMPORTO_SANZIONE AS AMMONTARE_SANZIONE, 
DPE.IMPORTO_RECUPERO_ANTICIPO AS RECUPERO_ANTICIPO, 
DPE.IMPORTO_AMMESSO AS CONTRIBUTO_AMMESSO,
Q1.COSTO_TOTALE_PROGETTO AS COSTO_TOTALE_PROGETTO_CORRELATO,
CONTRIBUTO_TOTALE_PROGETTO_CORRELATO=CASE 
WHEN Q1.CONTRIBUTO_TOTALE_PROGETTO>Q1.CONTRIBUTO_TOTALE THEN Q1.CONTRIBUTO_TOTALE ELSE Q1.CONTRIBUTO_TOTALE_PROGETTO END,
ISNULL(Q2.IMPORTO_RICHIESTO,0) AS IMPORTO_RICHIESTO,
CONTRIBUTO_RICHIESTO = ISNULL(Q2.CONTRIBUTO_RICHIESTO,0) 
FROM DOMANDA_DI_PAGAMENTO_ESPORTAZIONE DPE
INNER JOIN PROGETTO P ON DPE.ID_PROGETTO=P.ID_PROGETTO
INNER JOIN (SELECT CODICE, ID_BANDO 
			FROM VPROGRAMMAZIONE_BANDO PB 
			INNER JOIN MISURA M ON PB.COD_OBIETTIVO=M.COD_OBIETTIVO AND PB.ID_PSR=M.ID_PSR AND PB.COD_ASSE=M.COD_ASSE 
			AND PB.COD_MISURA=M.COD_MISURA
			WHERE PB.MISURA_PREVALENTE=1 GROUP BY CODICE, ID_BANDO
			) PR ON P.ID_BANDO=PR.ID_BANDO
INNER JOIN (
	SELECT ID_PROGETTO,dbo.calcoloCostoTotaleProgetto(@ID_PROGETTO,1,@ID_VARIANTE) AS COSTO_TOTALE_PROGETTO,
	ISNULL(dbo.calcoloContributoTotaleProgetto(@ID_PROGETTO,1,@ID_VARIANTE),0) AS CONTRIBUTO_TOTALE_PROGETTO,
	CONTRIBUTO_TOTALE
	FROM GRADUATORIA_PROGETTI WHERE ID_PROGETTO=@ID_PROGETTO
	)Q1 ON DPE.ID_PROGETTO=Q1.ID_PROGETTO
LEFT JOIN (
	SELECT ID_PROGETTO,SUM(RIC.IMPORTO_RICHIESTO) AS IMPORTO_RICHIESTO,SUM(RIC.CONTRIBUTO_RICHIESTO) AS CONTRIBUTO_RICHIESTO 
	FROM PIANO_INVESTIMENTI I INNER JOIN PAGAMENTI_RICHIESTI RIC ON I.ID_INVESTIMENTO=RIC.ID_INVESTIMENTO 
	WHERE RIC.ID_DOMANDA_PAGAMENTO=@ID_DOMANDA_PAGAMENTO GROUP BY ID_PROGETTO) Q2 ON Q2.ID_PROGETTO=P.ID_PROGETTO
WHERE DPE.ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO
AND P.ID_PROG_INTEGRATO IS NULL

*/





--DECLARE @ID_PROGETTO INT,@ID_VARIANTE INT,@DATA_MODIFICA_PAGAMENTO DATETIME,@COD_TIPO CHAR(3),@AMMONTARE_PREMIO_CONTO_CAPITALE DECIMAL(18,2), @AMMONTARE_PREMIO_SALDO DECIMAL (18,2)
--SELECT @ID_PROGETTO=ID_PROGETTO,@DATA_MODIFICA_PAGAMENTO=DATA_MODIFICA,@COD_TIPO=COD_TIPO,@ID_VARIANTE=ID_VARIAZIONE_ACCERTATA 
--FROM DOMANDA_DI_PAGAMENTO WHERE ID_DOMANDA_PAGAMENTO=@ID_DOMANDA_PAGAMENTO
--IF @ID_VARIANTE IS NULL
--	SELECT @ID_VARIANTE=MAX(ID_VARIANTE) FROM VARIANTI WHERE ID_PROGETTO=@ID_PROGETTO AND APPROVATA=1 AND ANNULLATA=0 
--	AND DATA_MODIFICA<@DATA_MODIFICA_PAGAMENTO	

--SELECT @AMMONTARE_PREMIO_CONTO_CAPITALE=dbo.calcoloPremioContoCapitale(@ID_PROGETTO,1,@ID_VARIANTE)
--SELECT @AMMONTARE_PREMIO_SALDO = ISNULL(dbo.calcoloPremioContoCapitaleSaldo(@ID_DOMANDA_PAGAMENTO,0),0) 


--SELECT DISTINCT P.ID_PROGETTO, '1.1.2 C.C.' AS MISURA,
--	CONTRIBUTO_AMMISSIBILE = CASE WHEN E.MISURA_PREVALENTE=1 AND @COD_TIPO='SLD' THEN 
--	@AMMONTARE_PREMIO_SALDO ELSE 0 END
--	,
--	E.IMPORTO_SANZIONE AS AMMONTARE_SANZIONE,
--E.IMPORTO_RECUPERO_ANTICIPO AS RECUPERO_ANTICIPO,
--CONTRIBUTO_AMMESSO = CASE WHEN @COD_TIPO = 'SLD' THEN e.IMPORTO_AMMESSO ELSE 0 END ,
--Q1.COSTO_TOTALE_PROGETTO AS COSTO_TOTALE_PROGETTO_CORRELATO,CONTRIBUTO_TOTALE_PROGETTO_CORRELATO = @AMMONTARE_PREMIO_CONTO_CAPITALE,
--ISNULL(Q2.IMPORTO_RICHIESTO,0) AS IMPORTO_RICHIESTO,
--CONTRIBUTO_RICHIESTO = CASE WHEN @COD_TIPO='SLD' THEN @AMMONTARE_PREMIO_CONTO_CAPITALE ELSE 0 END
--FROM DOMANDA_DI_PAGAMENTO_ESPORTAZIONE E
--INNER JOIN PROGETTO P ON E.ID_PROGETTO=P.ID_PROGETTO
--INNER JOIN PROGRAMMAZIONE_BANDO PB ON P.ID_BANDO=PB.ID_BANDO AND PB.MISURA_PREVALENTE=1
--INNER JOIN PROGRAMMAZIONE PR ON PB.ID_PROGRAMMAZIONE=PR.ID_PROGRAMMAZIONE 
--INNER JOIN MISURA M ON PR.COD_OBIETTIVO=M.COD_OBIETTIVO AND PR.ID_PSR=M.ID_PSR AND PR.COD_ASSE=M.COD_ASSE AND PR.COD_MISURA=M.COD_MISURA
--INNER JOIN (
--	SELECT ID_PROGETTO,CONTRIBUTO_DI_MISURA,0 AS COSTO_TOTALE_PROGETTO,
--	0 AS CONTRIBUTO_TOTALE_PROGETTO
--	FROM GRADUATORIA_PROGETTI_FINANZIABILITA WHERE ID_PROG_INTEGRATO=@ID_PROGETTO
--	)Q1 ON E.ID_PROGETTO=Q1.ID_PROGETTO
--LEFT JOIN (
--	SELECT ID_PROGETTO,0 AS IMPORTO_RICHIESTO,0 AS CONTRIBUTO_RICHIESTO 
--	FROM PIANO_INVESTIMENTI I INNER JOIN PAGAMENTI_RICHIESTI RIC ON I.ID_INVESTIMENTO=RIC.ID_INVESTIMENTO 
--	WHERE RIC.ID_DOMANDA_PAGAMENTO=@ID_DOMANDA_PAGAMENTO GROUP BY ID_PROGETTO) Q2 ON Q2.ID_PROGETTO=P.ID_PROGETTO
--WHERE E.ID_DOMANDA_PAGAMENTO=@ID_DOMANDA_PAGAMENTO and p.ID_PROGETTO = p.ID_PROG_INTEGRATO

--UNION ALL


--SELECT DISTINCT P.ID_PROGETTO,
--CODICE  + CASE WHEN E.MISURA_PREVALENTE=1 THEN ' C.I.' ELSE '' END
--AS MISURA, 
--CONTRIBUTO_AMMISSIBILE = CASE WHEN E.MISURA_PREVALENTE=1 THEN 0 ELSE E.IMPORTO_AMMISSIBILE end,

--AMMONTARE_SANZIONE = CASE WHEN E.MISURA_PREVALENTE=1 THEN 0 ELSE E.IMPORTO_SANZIONE END,
--RECUPERO_ANTICIPO = CASE WHEN E.MISURA_PREVALENTE=1 THEN 0 ELSE E.IMPORTO_RECUPERO_ANTICIPO END
--,CONTRIBUTO_AMMESSO = CASE WHEN E.MISURA_PREVALENTE=1 THEN 0 ELSE e.IMPORTO_AMMESSO END ,
--Q1.COSTO_TOTALE_PROGETTO AS COSTO_TOTALE_PROGETTO_CORRELATO,CONTRIBUTO_TOTALE_PROGETTO_CORRELATO=CASE 
--WHEN Q1.CONTRIBUTO_TOTALE_PROGETTO>Q1.CONTRIBUTO_DI_MISURA THEN Q1.CONTRIBUTO_DI_MISURA ELSE Q1.CONTRIBUTO_TOTALE_PROGETTO END,
--ISNULL(Q2.IMPORTO_RICHIESTO,0) AS IMPORTO_RICHIESTO,
--CONTRIBUTO_RICHIESTO = ISNULL(Q2.CONTRIBUTO_RICHIESTO,0) 
--FROM DOMANDA_DI_PAGAMENTO_ESPORTAZIONE E
--INNER JOIN PROGETTO P ON E.ID_PROGETTO=P.ID_PROGETTO
--INNER JOIN PROGRAMMAZIONE_BANDO PB ON P.ID_BANDO=PB.ID_BANDO AND PB.MISURA_PREVALENTE=1
--INNER JOIN PROGRAMMAZIONE PR ON PB.ID_PROGRAMMAZIONE=PR.ID_PROGRAMMAZIONE 
--INNER JOIN MISURA M ON PR.COD_OBIETTIVO=M.COD_OBIETTIVO AND PR.ID_PSR=M.ID_PSR AND PR.COD_ASSE=M.COD_ASSE AND PR.COD_MISURA=M.COD_MISURA
--INNER JOIN (
--	SELECT ID_PROGETTO,CONTRIBUTO_DI_MISURA,dbo.calcoloCostoTotaleProgettoCorrelato(ID_PROGETTO,1,@ID_VARIANTE) AS COSTO_TOTALE_PROGETTO,
--	ISNULL(dbo.calcoloContributoTotaleProgettoCorrelato(ID_PROGETTO,1,@ID_VARIANTE),0) AS CONTRIBUTO_TOTALE_PROGETTO
--	FROM GRADUATORIA_PROGETTI_FINANZIABILITA WHERE ID_PROG_INTEGRATO=@ID_PROGETTO
--	)Q1 ON E.ID_PROGETTO=Q1.ID_PROGETTO
--LEFT JOIN (
--	SELECT ID_PROGETTO,SUM(RIC.IMPORTO_RICHIESTO) AS IMPORTO_RICHIESTO,SUM(RIC.CONTRIBUTO_RICHIESTO) AS CONTRIBUTO_RICHIESTO 
--	FROM PIANO_INVESTIMENTI I INNER JOIN PAGAMENTI_RICHIESTI RIC ON I.ID_INVESTIMENTO=RIC.ID_INVESTIMENTO 
--	WHERE RIC.ID_DOMANDA_PAGAMENTO=@ID_DOMANDA_PAGAMENTO GROUP BY ID_PROGETTO) Q2 ON Q2.ID_PROGETTO=P.ID_PROGETTO
--WHERE E.ID_DOMANDA_PAGAMENTO=@ID_DOMANDA_PAGAMENTO

--UNION ALL

--SELECT DPE.ID_PROGETTO, PR.CODICE AS MISURA, DPE.IMPORTO_AMMISSIBILE AS CONTRIBUTO_AMMISSIBILE,
--DPE.IMPORTO_SANZIONE AS AMMONTARE_SANZIONE, DPE.IMPORTO_RECUPERO_ANTICIPO AS RECUPERO_ANTICIPO, 
--DPE.IMPORTO_AMMESSO AS CONTRIBUTO_AMMESSO,
--Q1.COSTO_TOTALE_PROGETTO AS COSTO_TOTALE_PROGETTO_CORRELATO,CONTRIBUTO_TOTALE_PROGETTO_CORRELATO=CASE 
--WHEN Q1.CONTRIBUTO_TOTALE_PROGETTO>Q1.CONTRIBUTO_TOTALE THEN Q1.CONTRIBUTO_TOTALE ELSE Q1.CONTRIBUTO_TOTALE_PROGETTO END,
--ISNULL(Q2.IMPORTO_RICHIESTO,0) AS IMPORTO_RICHIESTO,
--CONTRIBUTO_RICHIESTO = ISNULL(Q2.CONTRIBUTO_RICHIESTO,0) 
--FROM DOMANDA_DI_PAGAMENTO_ESPORTAZIONE DPE
--INNER JOIN PROGETTO P ON DPE.ID_PROGETTO=P.ID_PROGETTO
--INNER JOIN (SELECT CODICE, ID_BANDO 
--			FROM VPROGRAMMAZIONE_BANDO PB 
--			INNER JOIN MISURA M ON PB.COD_OBIETTIVO=M.COD_OBIETTIVO AND PB.ID_PSR=M.ID_PSR AND PB.COD_ASSE=M.COD_ASSE 
--			AND PB.COD_MISURA=M.COD_MISURA
--			WHERE PB.MISURA_PREVALENTE=1 GROUP BY CODICE, ID_BANDO
--			) PR ON P.ID_BANDO=PR.ID_BANDO
--INNER JOIN (
--	SELECT ID_PROGETTO,dbo.calcoloCostoTotaleProgetto(@ID_PROGETTO,1,@ID_VARIANTE) AS COSTO_TOTALE_PROGETTO,
--	ISNULL(dbo.calcoloContributoTotaleProgetto(@ID_PROGETTO,1,@ID_VARIANTE),0) AS CONTRIBUTO_TOTALE_PROGETTO,
--	CONTRIBUTO_TOTALE
--	FROM GRADUATORIA_PROGETTI WHERE ID_PROGETTO=@ID_PROGETTO
--	)Q1 ON DPE.ID_PROGETTO=Q1.ID_PROGETTO
--LEFT JOIN (
--	SELECT ID_PROGETTO,SUM(RIC.IMPORTO_RICHIESTO) AS IMPORTO_RICHIESTO,SUM(RIC.CONTRIBUTO_RICHIESTO) AS CONTRIBUTO_RICHIESTO 
--	FROM PIANO_INVESTIMENTI I INNER JOIN PAGAMENTI_RICHIESTI RIC ON I.ID_INVESTIMENTO=RIC.ID_INVESTIMENTO 
--	WHERE RIC.ID_DOMANDA_PAGAMENTO=@ID_DOMANDA_PAGAMENTO GROUP BY ID_PROGETTO) Q2 ON Q2.ID_PROGETTO=P.ID_PROGETTO
--WHERE DPE.ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO
--AND P.ID_PROG_INTEGRATO IS NULL
