CREATE PROCEDURE [dbo].[rptElencoDomandeAsra] 
	--@OPERATORE CHAR(16) = NULL, 
	@NUM_PROGRESSIVO INT = NULL
AS
BEGIN
	SET NOCOUNT ON;
	--DECLARE @CAA VARCHAR(8)  = 'CON'
SELECT * FROM (
SELECT   *, DENSE_RANK() OVER (ORDER BY ente, PROVINCIA, CUAA ASC) AS NUM_PROGRESSIVO
FROM      (SELECT   u.CF_UTENTE, u.NOMINATIVO, u.PROVINCIA, u.COD_ENTE, u.ENTE, ISL.CUAA, ISL.RAGIONE_SOCIALE, ISL.VIA, ISL.COMUNE, ISL.SIGLA, ISL.CAP, 
                 CAST(AEC.ID_ASSEGNAZIONE AS VARCHAR(15)) AS NUMERO_DOMANDA, 'UMA' AS MISURA, YEAR(AEC.DATA_ESTRAZIONE) AS ANNO, A.STATO, FA_ASS.BARCODE, 
                 FA_ASS.DATA_SCHEDA_VALIDAZIONE, FA_ASS.DATA_VALIDAZIONE_FASCICOLO, NULL AS ENTE_DELEGATO
FROM      SIAR_UMA.dbo.ASSEGNAZIONI_ESTRAZIONE_CONTROLLO AS AEC INNER JOIN
             SIAR_UMA.dbo.vASSEGNAZIONI AS A ON AEC.ID_ASSEGNAZIONE = A.ID LEFT OUTER JOIN
             FASCICOLO_AZIENDALE AS FA_ASS ON A.ID_FASCICOLO = FA_ASS.ID_FASCICOLO INNER JOIN
             SIAR_UMA.dbo.vIMPRESA_SEDELEGALE AS ISL ON ISL.ID_IMPRESA = A.ID_IMPRESA INNER JOIN
             vUTENTI AS u ON AEC.ID_UTENTE = u.ID_UTENTE
WHERE   (AEC.ESTRATTA = 1) /*AND (AEC.ID_ASSEGNAZIONE = @IdAssegnazione)*/ 
--AND u.COD_ENTE = @CAA AND U.PROVINCIA = @PROVINCIA
GROUP BY u.CF_UTENTE, u.NOMINATIVO, u.PROVINCIA, u.ENTE, ISL.CUAA, ISL.RAGIONE_SOCIALE, ISL.VIA, ISL.COMUNE, ISL.SIGLA, ISL.CAP, AEC.ID_ASSEGNAZIONE, 
             AEC.DATA_ESTRAZIONE, A.STATO, FA_ASS.BARCODE, FA_ASS.DATA_SCHEDA_VALIDAZIONE, FA_ASS.DATA_VALIDAZIONE_FASCICOLO, u.COD_ENTE
UNION ALL
SELECT   u.CF_UTENTE, u.NOMINATIVO, u.PROVINCIA, u.COD_ENTE, u.ENTE, ISL.CUAA, ISL.RAGIONE_SOCIALE, ISL.VIA, ISL.COMUNE, ISL.SIGLA, ISL.CAP, 
             CAST(P.ID_PROGETTO AS VARCHAR(15)) + ' -  BARCODE: ' + ISNULL(P.COD_AGEA, 0) AS NUMERO_DOMANDA, PR.DESCRIZIONE + ' - ' + PR.CODICE AS MISURA, 
             YEAR(SP.DATA) AS ANNO, P.STATO, FA_PROG.BARCODE, FA_PROG.DATA_SCHEDA_VALIDAZIONE, FA_PROG.DATA_VALIDAZIONE_FASCICOLO, NULL 
             AS ENTE_DELEGATO
FROM      SIAR_UMA.dbo.ASSEGNAZIONI_ESTRAZIONE_CONTROLLO AS AEC INNER JOIN
             SIAR_UMA.dbo.vASSEGNAZIONI AS A ON AEC.ID_ASSEGNAZIONE = A.ID INNER JOIN
             FASCICOLO_AZIENDALE AS FA_ASS ON A.ID_FASCICOLO = FA_ASS.ID_FASCICOLO INNER JOIN
             SIAR_UMA.dbo.vIMPRESA_SEDELEGALE AS ISL ON ISL.ID_IMPRESA = A.ID_IMPRESA INNER JOIN
             VPROGETTO AS P ON ISL.ID_IMPRESA = P.ID_IMPRESA
            INNER JOIN PROGETTO_STORICO AS SP ON P.ID_PROGETTO = SP.ID_PROGETTO AND SP.COD_STATO = 'L'
             INNER JOIN FASCICOLO_AZIENDALE AS FA_PROG ON P.ID_FASCICOLO = FA_PROG.ID_FASCICOLO INNER JOIN
                 (SELECT   M.ID_PSR, PSR.DESCRIZIONE, M.COD_ASSE, M.COD_MISURA, M.COD_OBIETTIVO, PB.ID_BANDO, M.CODICE
                  FROM      vPROGRAMMAZIONE_BANDO AS PB INNER JOIN
                                  MISURA AS M ON PB.ID_PSR = M.ID_PSR AND PB.COD_ASSE = M.COD_ASSE AND PB.COD_MISURA = M.COD_MISURA INNER JOIN
                                  PSR ON M.ID_PSR = PSR.ID_PSR
                  WHERE   (PB.MISURA_PREVALENTE = 1) AND PB.ID_PSR <> 3 AND CODICE NOT IN ('7.1.1', '8.1.1')
                  GROUP BY M.ID_PSR, M.COD_ASSE, M.COD_MISURA, M.COD_OBIETTIVO, PB.ID_BANDO, M.CODICE, PSR.DESCRIZIONE) AS PR ON 
             P.ID_BANDO = PR.ID_BANDO INNER JOIN
             vUTENTI AS u ON AEC.ID_UTENTE = u.ID_UTENTE
WHERE   (AEC.ESTRATTA = 1) /*AND (AEC.ID_ASSEGNAZIONE = @IdAssegnazione)*/ 
--AND u.COD_ENTE = @CAA  AND U.PROVINCIA = @PROVINCIA
GROUP BY u.CF_UTENTE, u.NOMINATIVO, u.PROVINCIA, u.ENTE, ISL.CUAA, ISL.RAGIONE_SOCIALE, ISL.VIA, ISL.COMUNE, ISL.SIGLA, ISL.CAP, P.ID_PROGETTO, P.COD_AGEA, 
             PR.DESCRIZIONE, PR.CODICE, SP.DATA, P.STATO, FA_PROG.BARCODE, FA_PROG.DATA_SCHEDA_VALIDAZIONE, 
             FA_PROG.DATA_VALIDAZIONE_FASCICOLO, u.COD_ENTE
UNION
SELECT   u.CF_UTENTE, u.NOMINATIVO, u.PROVINCIA, u.COD_ENTE, u.ENTE, ISL.CUAA, ISL.RAGIONE_SOCIALE, ISL.VIA, ISL.COMUNE, ISL.SIGLA, ISL.CAP, 
             E_1.Ndomanda AS NUMERO_DOMANDA, E_1.Misura AS MISURA, E_1.ANNO, E_1.Stato_avanzamento AS STATO, NULL AS BARCODE, NULL 
             AS DATA_SCHEDA_VALIDAZIONE, NULL AS DATA_VALIDAZIONE_FASCICOLO, E_1.Ente_delegato
FROM      SIAR_UMA.dbo.ASSEGNAZIONI_ESTRAZIONE_CONTROLLO AS AEC INNER JOIN
             SIAR_UMA.dbo.vASSEGNAZIONI AS A ON AEC.ID_ASSEGNAZIONE = A.ID INNER JOIN
             FASCICOLO_AZIENDALE AS FA_ASS ON A.ID_FASCICOLO = FA_ASS.ID_FASCICOLO INNER JOIN
             SIAR_UMA.dbo.vIMPRESA_SEDELEGALE AS ISL ON ISL.ID_IMPRESA = A.ID_IMPRESA INNER JOIN
                 (SELECT   ANNO, Gruppo_misura, Misura, Ndomanda, CUAA, Denominazione, CAA, Ente_delegato, Stato_avanzamento, Esito_ricevibilità, Esito_ammissibilità, 
                                  Istrmanuale, Anno_impegno, [% scost# sup#], [% scoct# zoot#], [Istr# negativa], [Imp# richiesto], [Imp# pagato], [Camp#/non camp#]
                  FROM      ELENCO_DOMANDE_ASRA AS ELENCO_DOMANDE_ASRA_1
                  WHERE   ANNO <> 2007) AS E_1 ON E_1.CUAA = ISL.CUAA OR E_1.CUAA = ISL.CODICE_FISCALE INNER JOIN
             vUTENTI AS u ON AEC.ID_UTENTE = u.ID_UTENTE
WHERE   (AEC.ESTRATTA = 1) /*AND (AEC.ID_ASSEGNAZIONE = @IdAssegnazione)*/ 
--AND u.COD_ENTE = @CAA  AND U.PROVINCIA = @PROVINCIA
GROUP BY u.CF_UTENTE, u.NOMINATIVO, u.PROVINCIA, u.ENTE, ISL.CUAA, ISL.RAGIONE_SOCIALE, ISL.VIA, ISL.COMUNE, ISL.SIGLA, ISL.CAP, E_1.Stato_avanzamento, 
             E_1.Ndomanda, E_1.ANNO, E_1.Stato_avanzamento, E_1.Misura, E_1.Ente_delegato, u.COD_ENTE) AS A
            ) AS B
  WHERE  NUM_PROGRESSIVO = @NUM_PROGRESSIVO

END
