CREATE PROCEDURE [dbo].[RptFascicolo]
@IdFascicolo int	
AS
BEGIN	
	
	--DECLARE @IdFascicolo INT
	--SET @IdFascicolo = 75

	SELECT F.*, SC.DENOMINAZIONE AS SPORTELLO_CAA 
	FROM FASCICOLO_AZIENDALE F 
	LEFT JOIN vCAA_SPORTELLO SC ON F.COD_DETENTORE = SC.CODICE
	WHERE ID_FASCICOLO = @IdFascicolo
	
END
