CREATE PROCEDURE [dbo].[RptFontiFinanziarie]
@IdElencoPagamento int	, 
@IdFonte int
AS
BEGIN	
	
SET NOCOUNT ON;

SELECT ISNULL(F.PERCENTUALE, F1.PERCENTUALE) as PERCENTUALE
FROM ELENCO_DI_PAGAMENTO E 
INNER JOIN BANDO B ON E.ID_BANDO_PRINCIPALE = B.ID_BANDO
INNER JOIN vzPROGRAMMAZIONE P ON B.ID_PROGRAMMAZIONE = P.ID
LEFT JOIN ZPROGRAMMAZIONE_FONTI F ON P.ID_PADRE = F.ID_PROGRAMMAZIONE AND (F.ID_FONTE = @IdFonte) 
LEFT JOIN ZPROGRAMMAZIONE_FONTI F1 ON P.ID = F1.ID_PROGRAMMAZIONE AND (F1.ID_FONTE = @IdFonte) 
WHERE E.ID_ELENCO_PAGAMENTO = @IdElencoPagamento 
END
