create PROCEDURE [dbo].[RptFAUbicazioneCentroInteresse]
@IdFascicolo int	
AS
BEGIN	
		--USATA ANCHE IN EROA DOMANDA
	--DECLARE @IdFascicolo INT
	--SET @IdFascicolo = 75
	
	SELECT dbo.MqAEttari(SUM(SUPERFICIE_CATASTALE)) SUPERFICIE_CATASTALE,C.DENOMINAZIONE AS COMUNE,SIGLA,CAP, TIPO_AREA
    FROM CATASTO_TERRENI CT 
    INNER JOIN (SELECT DISTINCT ID_CATASTO 
				FROM TERRITORIO WHERE Id_fascicolo = @IdFascicolo)TER ON TER.ID_CATASTO=CT.ID_CATASTO 
	INNER JOIN COMUNI C ON C.ID_COMUNE=CT.ID_COMUNE
    GROUP BY CT.ID_COMUNE, C.DENOMINAZIONE ,SIGLA,CAP, TIPO_AREA ORDER BY TIPO_AREA, C.DENOMINAZIONE
	
END
