CREATE PROCEDURE [dbo].[RptIstruttoriaVariantePremio]

	@IdVariante int

AS
BEGIN

	DECLARE @ID_PROGETTO INT 

	SET @ID_PROGETTO = (SELECT ID_PROGETTO FROM VARIANTI WHERE ID_VARIANTE = @IdVariante)

	IF((SELECT COUNT(*) FROM BANDO_TIPO_INVESTIMENTI WHERE COD_TIPO_INVESTIMENTO=3 AND ID_BANDO = (SELECT ID_BANDO FROM PROGETTO WHERE ID_PROGETTO = @ID_PROGETTO)) > 0)
	
	BEGIN
		SELECT DBO.calcoloPremioContoCapitale(@ID_PROGETTO, 1, @IdVariante) AS PREMIO
	END 
END
