
CREATE PROCEDURE [dbo].[RptInvestimento]
(
@IdInvestimento int
)
AS
BEGIN	

SET NOCOUNT ON;

--	DECLARE @ID_Domanda int
--	DECLARE @COD_Tipo_Investimento int
--	SET @ID_Domanda = 117
--	SET @COD_Tipo_Investimento = 1


		SELECT vPIANO_INVESTIMENTI.MISURA, vPIANO_INVESTIMENTI.DESCRIZIONE, vPIANO_INVESTIMENTI.QUANTITA, vPIANO_INVESTIMENTI.COSTO_INVESTIMENTO, 
                      vPIANO_INVESTIMENTI.SPESE_GENERALI, vPIANO_INVESTIMENTI.CONTRIBUTO_RICHIESTO, 
                      vPIANO_INVESTIMENTI.QUOTA_CONTRIBUTO_RICHIESTO, vPIANO_INVESTIMENTI.ID_OBIETTIVO_MISURA, vPIANO_INVESTIMENTI.AMMESSO, 
                      vPIANO_INVESTIMENTI.COD_TP, vPIANO_INVESTIMENTI.CODIFICA_INVESTIMENTO, vPIANO_INVESTIMENTI.AIUTO_MINIMO, 
                      vPIANO_INVESTIMENTI.CODICE, vPIANO_INVESTIMENTI.SPECIFICA_INVESTIMENTI, vPIANO_INVESTIMENTI.DETTAGLIO_INVESTIMENTI, 
                      vPIANO_INVESTIMENTI.MOBILE, vPIANO_INVESTIMENTI.QUOTA_SPESE_GENERALI, vPIANO_INVESTIMENTI.SETTORE_PRODUTTIVO, 
                      zOB_MISURA.CODICE AS COD_OB_MISURA, 
                      zOB_MISURA.DESCRIZIONE AS DESCRIZIONE_OBIETTIVI_MISURA, zPROGRAMMAZIONE.CODICE AS COD_INTERVENTO, 
                      zPROGRAMMAZIONE.DESCRIZIONE AS DESCRIZIONE_INTERVENTO, UNITA_DI_MISURA.DESCRIZIONE AS DESCRIZIONE_UNITA_MISURA, 
                      zSTP.DESCRIZIONE AS DESCRIZIONE_STP, 
                      vPIANO_INVESTIMENTI.ID_INVESTIMENTO, 
                      vPIANO_INVESTIMENTI.ID_INVESTIMENTO_ORIGINALE, vPIANO_INVESTIMENTI.VALUTAZIONE_INVESTIMENTO,
					DENSE_RANK() over (ORDER BY  COD_TIPO_INVESTIMENTO, VPIANO_INVESTIMENTI.ID_INVESTIMENTO) AS ROWS, 
					vPIANO_INVESTIMENTI.COD_TIPO_INVESTIMENTO, TASSO_ABBUONO, vPIANO_INVESTIMENTI.ID_VARIANTE, PS.DESCRIZIONE AS DESCRIZIONE_PRIORITA_SETTORIALE
		FROM         vPIANO_INVESTIMENTI INNER JOIN
                      vPROGETTO AS P ON vPIANO_INVESTIMENTI.ID_PROGETTO = P.ID_PROGETTO 
                     LEFT JOIN BANDO B ON P.ID_BANDO = B.ID_BANDO 
                      LEFT JOIN
                      zOB_MISURA ON vPIANO_INVESTIMENTI.ID_OBIETTIVO_MISURA = zOB_MISURA.ID LEFT JOIN
                      zPROGRAMMAZIONE ON vPIANO_INVESTIMENTI.ID_PROGRAMMAZIONE = zPROGRAMMAZIONE.ID LEFT JOIN
                      UNITA_DI_MISURA ON vPIANO_INVESTIMENTI.ID_UNITA_MISURA = UNITA_DI_MISURA.ID_UNITA_MISURA LEFT  JOIN
                      zSTP ON B.ID_PROGRAMMAZIONE = zSTP.ID_PROGRAMMAZIONE AND ZSTP.CODICE = vPIANO_INVESTIMENTI.COD_STP
                     LEFT JOIN PRIORITA_SETTORIALI  PS ON vPIANO_INVESTIMENTI.ID_PRIORITA_SETTORIALE = PS.ID_PRIORITA_SETTORIALE 
				WHERE vPIANO_INVESTIMENTI.ID_INVESTIMENTO = @IdInvestimento
				
END