CREATE PROCEDURE [dbo].[RptManifestazioneSistemaQualita]
	@IdManifestazione INT 
AS
BEGIN

--- SISTEMA DI QUALITà tutti escluso QM 
--- AGRITEST = (56,57,58)
--- SIAR = (232, 233, 234)
--- SIARTEST = (236,234,235)


SELECT   PRIORITA_X_MANIFESTAZIONE.*
FROM         PRIORITA_X_MANIFESTAZIONE INNER JOIN
                      PRIORITA ON PRIORITA_X_MANIFESTAZIONE.ID_PRIORITA = PRIORITA.ID_PRIORITA 
WHERE     (PRIORITA_X_MANIFESTAZIONE.ID_MANIFESTAZIONE = @IdManifestazione) 
	AND (PRIORITA_X_MANIFESTAZIONE.ID_PRIORITA IN (232, 233, 234))
END
