CREATE PROCEDURE [dbo].[RptPolizza]
@IdDomandaPagamento int	
AS
BEGIN	
	
SET NOCOUNT ON;
	
--DECLARE @IdDomandaPagamento INT
--SET @IdDomandaPagamento=276

SELECT A.*, 
CASE WHEN B.MULTIMISURA=1 THEN DBO.calcoloPremioContoCapitale(A.ID_PROGETTO, 1, ID_V) ELSE
DBO.calcoloContributoTotaleProgettoCorrelato (A.ID_PROGETTO, 1, ID_V) END AS CONTR
FROM DBO.calcoloImportoGarantitoFidejussioneMultimisura(@IdDomandaPagamento) a
INNER JOIN PROGETTO P ON A.ID_PROGETTO = P.ID_PROGETTO
INNER JOIN BANDO B ON P.ID_BANDO = B.ID_BANDO
LEFT JOIN (SELECT MAX(ID_VARIANTE) ID_V, ID_PROGETTO FROM VARIANTI 
			WHERE APPROVATA = 1 AND ANNULLATA = 0 
			GROUP BY ID_PROGETTO) V ON A.ID_PROGETTO = V.ID_PROGETTO


--DECLARE @ID_PROGETTO INT, @MISURA VARCHAR(8), @COD_TIPO_DOMANDA_PAGAMENTO CHAR(3),@CONTRIBUTO_RICHIESTO DECIMAL(18,5),
--		@AMMONTARE_ANTICIPO DECIMAL(18,5),
--		@ANTICIPO_RECUPERATO DECIMAL(18,5),@ANTICIPO_DA_RECUPERARE DECIMAL(18,5),@IMPORTO_MAX DECIMAL(18,5),
--		@QUOTA_MAX DECIMAL(18,5),@IMPORTO_PARZIALE DECIMAL(18,5), @ID_BANDO INT 
	
--	SELECT @ID_PROGETTO=D.ID_PROGETTO,@COD_TIPO_DOMANDA_PAGAMENTO=COD_TIPO, @ID_BANDO = P.ID_BANDO
--		FROM DOMANDA_DI_PAGAMENTO D INNER JOIN PROGETTO P ON P.ID_PROGETTO = D.ID_PROGETTO 
--		WHERE ID_DOMANDA_PAGAMENTO=@IdDomandaPagamento	
--	IF @COD_TIPO_DOMANDA_PAGAMENTO='ANT' 
--	BEGIN 
--		SELECT @CONTRIBUTO_RICHIESTO=SUM(CONTRIBUTO_RICHIESTO) FROM ANTICIPI_RICHIESTI WHERE ID_DOMANDA_PAGAMENTO=@IdDomandaPagamento
--		EXEC SpCalcoloAmmontareAnticipo @ID_BANDO, @IdDomandaPagamento
--	END 
--	ELSE BEGIN
	
--		DECLARE @TABELLA_RIEPILOGO TABLE (ID_PROGETTO INT, MISURA VARCHAR(8), CONTRIBUTO_DI_MISURA DECIMAL(18,5),ANTICIPO_PERCEPITO DECIMAL(18,5),
--			ANTICIPO_RECUPERATO DECIMAL(18,5),ANTICIPO_DA_RECUPERARE DECIMAL(18,5),AMMONTARE_RICHIESTO DECIMAL(18,5),
--			COD_TIPO_INVESTIMENTO INT,IMPORTO_MAX_RECUPERO_ANTICIPO DECIMAL(18,5),QUOTA_MAX_RECUPERO_ANTICIPO DECIMAL(18,5))
		
--		-- A SAL NON RICHIEDONO IL CONTO CAPITALE MIS 112 QUINDI NON LO CALCOLO
--		INSERT INTO @TABELLA_RIEPILOGO
--		SELECT P.ID_PROGETTO,MISURA,SUM(R.CONTRIBUTO_RICHIESTO),NULL,NULL,NULL,NULL,BT.COD_TIPO_INVESTIMENTO,IMPORTO_MAX,QUOTA_MAX FROM PROGETTO P		
--		LEFT JOIN PIANO_INVESTIMENTI I ON P.ID_PROGETTO=I.ID_PROGETTO
--		LEFT JOIN PAGAMENTI_RICHIESTI R ON I.ID_INVESTIMENTO=R.ID_INVESTIMENTO AND ID_DOMANDA_PAGAMENTO=@IdDomandaPagamento
--		LEFT JOIN BANDO_TIPO_INVESTIMENTI BT ON P.ID_BANDO=BT.ID_BANDO AND BT.COD_TIPO_INVESTIMENTO=8
--		INNER JOIN
--		(SELECT ID_BANDO, CODICE AS MISURA
--				FROM PROGRAMMAZIONE_BANDO PB INNER JOIN PROGRAMMAZIONE P ON PB.ID_PROGRAMMAZIONE=P.ID_PROGRAMMAZIONE
--				INNER JOIN MISURA M ON P.COD_OBIETTIVO=M.COD_OBIETTIVO AND P.ID_PSR=M.ID_PSR AND P.COD_ASSE=M.COD_ASSE 
--				AND P.COD_MISURA=M.COD_MISURA AND MISURA_PREVALENTE = 1
--				GROUP BY ID_BANDO, CODICE) AS Q1 ON P.ID_BANDO = Q1.ID_BANDO
--		WHERE ISNULL(P.ID_PROG_INTEGRATO,P.ID_PROGETTO)=@ID_PROGETTO
--		GROUP BY P.ID_PROGETTO,BT.COD_TIPO_INVESTIMENTO,IMPORTO_MAX,QUOTA_MAX, MISURA
				
--		--CALCOLO L'ANTICIPO PERCEPITO E AGGIORNO LA QUOTA MAX DA % A €
--		UPDATE T SET ANTICIPO_PERCEPITO=Q1.SOMMA,ANTICIPO_DA_RECUPERARE=Q1.SOMMA,QUOTA_MAX_RECUPERO_ANTICIPO=CASE
--			WHEN COD_TIPO_INVESTIMENTO=8 THEN Q1.SOMMA*QUOTA_MAX_RECUPERO_ANTICIPO/100 ELSE NULL END
--		 FROM @TABELLA_RIEPILOGO T
--		INNER JOIN (
--			SELECT E.ID_PROGETTO,SUM(IMPORTO_AMMISSIBILE) AS SOMMA FROM DOMANDA_DI_PAGAMENTO_ESPORTAZIONE E
--			INNER JOIN DOMANDA_DI_PAGAMENTO D ON E.ID_DOMANDA_PAGAMENTO=D.ID_DOMANDA_PAGAMENTO
--			WHERE D.ID_PROGETTO=@ID_PROGETTO AND D.ID_DOMANDA_PAGAMENTO<@IdDomandaPagamento AND D.ANNULLATA=0 AND D.APPROVATA=1
--			AND D.COD_TIPO='ANT' GROUP BY E.ID_PROGETTO) AS Q1 ON T.ID_PROGETTO=Q1.ID_PROGETTO		
		
--		-- SE E' STATO RICHIESTO UN ANTICIPO
--		IF @@ROWCOUNT>0 BEGIN
--			--CALCOLO L'ANTICIPO RECUPERATO IN DOMADE DI PAGAMENTO PRECEDENTI
--			UPDATE T SET ANTICIPO_RECUPERATO=Q1.SOMMA,ANTICIPO_DA_RECUPERARE=ISNULL(ANTICIPO_PERCEPITO,0)-ISNULL(Q1.SOMMA,0)
--			FROM @TABELLA_RIEPILOGO T 
--			INNER JOIN (
--				SELECT E.ID_PROGETTO,SUM(IMPORTO_RECUPERO_ANTICIPO) AS SOMMA FROM DOMANDA_DI_PAGAMENTO_ESPORTAZIONE E
--				INNER JOIN DOMANDA_DI_PAGAMENTO D ON E.ID_DOMANDA_PAGAMENTO=D.ID_DOMANDA_PAGAMENTO
--				WHERE D.ID_PROGETTO=@ID_PROGETTO AND D.ID_DOMANDA_PAGAMENTO<@IdDomandaPagamento AND D.ANNULLATA=0 AND D.APPROVATA=1
--				AND D.COD_TIPO!='ANT' GROUP BY E.ID_PROGETTO) AS Q1 ON T.ID_PROGETTO=Q1.ID_PROGETTO
				
--			UPDATE @TABELLA_RIEPILOGO SET AMMONTARE_RICHIESTO=CASE
--				-- RECUPERO PARZIALE SOLO A SAL
--				WHEN (@COD_TIPO_DOMANDA_PAGAMENTO='SAL' AND COD_TIPO_INVESTIMENTO=8) THEN CONTRIBUTO_DI_MISURA-
--					dbo.SIAR_MIN(ISNULL(ANTICIPO_DA_RECUPERARE,0),
--					dbo.SIAR_MIN(ISNULL(IMPORTO_MAX_RECUPERO_ANTICIPO,QUOTA_MAX_RECUPERO_ANTICIPO),
--						ISNULL(QUOTA_MAX_RECUPERO_ANTICIPO,IMPORTO_MAX_RECUPERO_ANTICIPO)))
--				-- RECUPERO TOTALE
--				ELSE CONTRIBUTO_DI_MISURA-ISNULL(ANTICIPO_DA_RECUPERARE,0) END
--			WHERE CONTRIBUTO_DI_MISURA IS NOT NULL
			
--			SELECT @CONTRIBUTO_RICHIESTO=SUM(CASE WHEN AMMONTARE_RICHIESTO<0 THEN 0 ELSE AMMONTARE_RICHIESTO END) FROM @TABELLA_RIEPILOGO
--		END
--		SELECT * FROM @TABELLA_RIEPILOGO
--	END


END
