CREATE PROCEDURE [dbo].[RptPistaControlloFinanziario] 
@IdProgetto int
AS
BEGIN
--declare @IdProgetto int = 11507

SELECT 
	-- DOMANDA_PAGAMENTO
	DP.ID_PROGETTO,
	P.COD_STATO,
	DP.ID_DOMANDA_PAGAMENTO,
	DP.SEGNATURA AS SEGNATURA_DOMANDA_PAGAMENTO,
	--CONTROLLI I LIVELLO DOCUMENTALE
	RDP.SEGNATURA_REVISIONE,
	RDP.DATA_MODIFICA AS DATA_CHECKLIST_REVISIONE,
	(SELECT SUM(IMPORTO_AMMESSO)
		FROM PAGAMENTI_RICHIESTI PR
		WHERE PR.ID_DOMANDA_PAGAMENTO = DP.ID_DOMANDA_PAGAMENTO) AS SPESA_AMMISSIBILE_REVISIONE,
	--(SUM(PR.IMPORTO_AMMESSO) OVER(PARTITION BY PR.ID_PAGAMENTO_RICHIESTO)) AS SPESA_AMMISSIBILE_REVISIONE,
	--EROGAZIONE CONTRIBUTO
	ATTI.NUMERO AS NUMERO_DECRETO,
	ATTI.DATA AS DATA_DECRETO,
	--DICHIARAZIONE DI SPESA ADG
	CSPT.Segnatura AS SEGNATURA_DICHIARAZIONE_ADG,
	CSPT.DataSegnatura AS DATA_DICHIARAZIONE_ADG,
	CSPD.SpesaAmmessa AS SPESA_DICHIARAZIONE_ADG,
	convert(varchar(10), CSPT.DataInizio, 103) + ' - 30/06/' +CONVERT(varchar,YEAR(CSPT.DataInizio)+1)  AS PERIODO_CONTABILE_DICHIARAZIONE_ADG,
	--CERTIFICAZIONE ADG
	CSPT.IdCertSp AS ID_CERT_SPESA,
	CSPT.DataInizio AS DATA_INIZIO_CERT_SPESA,
	CSPT.DataFine AS DATA_FINE_CERT_SPESA,
	CSPT.DataModifica AS DATA_CERT_SPESA,
	CSPT.Definitivo AS FLAG_DEFINITIVO_CERT_SPESA,
	CSPD.SpesaAmmessa AS IMPORTO_SPESA_CERT_SPESA,
	CSPD.ImportoContributoPubblico AS CONTRIBUTO_RENDICONTATO_CONCESSO,
	--CONTROLLI ADA
	--NULL AS DATA_CONTROLLO_ADA,
	--NULL AS IMPORTO_SPESA_AMMISSIBILE_ADA,
	--NULL AS IMPORTO_SPESA_IRREGOLARE_ADA,
	pirr3.DATA_COSTATAZIONE_AMMINISTRATIVA AS DATA_CONTROLLO_ADA,
	(pirr3.CONTRIBUTO_AMMESSO - pirr3.IMPORTO_IRREGOLARE_CONCESSO) AS IMPORTO_SPESA_AMMISSIBILE_ADA,
	pirr3.IMPORTO_IRREGOLARE_CONCESSO AS IMPORTO_SPESA_IRREGOLARE_ADA,
	--CONTROLLI ORGANISMI ESTERNI
	NULL AS ORGANISMO_OE,
	NULL AS DATA_CONTROLLO_OE,
	NULL AS IMPORTO_SPESA_AMMISSIBILE_OE,
	NULL AS IMPORTO_SPESA_IRREGOLARE_OE,
	--DECERTIFICAZIONI
	--NULL AS DATA_DECERTIFICAZIONE,
	--NULL AS TIPO_DECERTIFICAZIONE,
	--NULL AS IMPORTO_SPESA_DECERTIFICAZIONE,
	--NULL AS PERIODO_CONTABILE_DECERTIFICAZIONE
	pirr2.DATA_DECERTIFICAZIONE AS DATA_DECERTIFICAZIONE,
	pirr2.TIPO_DECERTIFICAZIONE AS TIPO_DECERTIFICAZIONE,
	pirr2.IMPORTO_SPESA_DECERTIFICAZIONE AS IMPORTO_SPESA_DECERTIFICAZIONE,
	pirr2.PERIODO_CONTABILE_DECERTIFICAZIONE AS PERIODO_CONTABILE_DECERTIFICAZIONE
FROM vPROGETTO P 
	INNER JOIN DOMANDA_DI_PAGAMENTO DP ON P.ID_PROGETTO = DP.ID_PROGETTO
	--LEFT OUTER JOIN PAGAMENTI_RICHIESTI PR ON DP.ID_DOMANDA_PAGAMENTO = PR.ID_DOMANDA_PAGAMENTO
	LEFT OUTER JOIN CTE_TESTATA_VALIDAZIONE RDP ON DP.ID_DOMANDA_PAGAMENTO = RDP.ID_DOMANDA_PAGAMENTO
	LEFT OUTER JOIN DOMANDA_DI_PAGAMENTO_ESPORTAZIONE DPE ON DP.ID_DOMANDA_PAGAMENTO = DPE.ID_DOMANDA_PAGAMENTO
	LEFT OUTER JOIN DECRETI_X_DOM_PAG_ESPORTAZIONE DDPE ON DPE.ID_DOMANDA_PAGAMENTO = DDPE.ID_DOMANDA_PAGAMENTO
	LEFT OUTER JOIN ATTI ON DDPE.ID_DECRETO = ATTI.ID_ATTO
	LEFT OUTER JOIN CertSp_Dettaglio CSPD ON DP.ID_DOMANDA_PAGAMENTO = CSPD.Id_Domanda_Pagamento
	LEFT OUTER JOIN CertSp_Testa CSPT ON CSPD.IdCertSp = CSPT.IdCertSp
	LEFT OUTER JOIN
	(
		--select 
		--null as DATA_DECERTIFICAZIONE,
		--i.AZIONE_CERTIFICAZIONE as TIPO_DECERTIFICAZIONE,
		--pirr1.IMPORTO_SPESA_DECERTIFICAZIONE,
		--'01/07/2018 - 30/06/2019' as PERIODO_CONTABILE_DECERTIFICAZIONE,
		--i.ID_PROGETTO,
		--pirr1.ID_DOMANDA_PAGAMENTO
		--from
		--VIRREGOLARITA i
		--inner join  
		--(
		--	select 
		--	pirr.ID_IRREGOLARITA,
		--	pirr.ID_DOMANDA ID_DOMANDA_PAGAMENTO,
		--	pirr.ID_PROGETTO,
		--	SUM(pirr.IMPORTO_IRREGOLARE_CONCESSO) AS IMPORTO_SPESA_DECERTIFICAZIONE
		--	from
		--	PAGAMENTI_IRREGOLARITA pirr 
		--	group by 
		--	pirr.ID_IRREGOLARITA,
		--	pirr.ID_DOMANDA,
		--	pirr.ID_PROGETTO
		--)
		--pirr1 on
		--i.ID_IRREGOLARITA = pirr1.ID_IRREGOLARITA
		select 
		null as DATA_DECERTIFICAZIONE,
		i.AZIONE_CERTIFICAZIONE as TIPO_DECERTIFICAZIONE,
		i.CONTRIBUTO_PUBBLICO_CERTIFICATO as IMPORTO_SPESA_DECERTIFICAZIONE,
		'01/07/2018 - 30/06/2019' as PERIODO_CONTABILE_DECERTIFICAZIONE,
		i.ID_PROGETTO,
		idp.ID_DOMANDA_PAGAMENTO
		from
		IRREGOLARITA_DOMANDA_PAGAMENTO idp  
		inner join
		VIRREGOLARITA i on
		idp.ID_IRREGOLARITA = i.ID_IRREGOLARITA
			) pirr2 ON
		DP.ID_DOMANDA_PAGAMENTO = pirr2.ID_DOMANDA_PAGAMENTO
	LEFT OUTER JOIN 
	(
		select 
		i.DATA_COSTATAZIONE_AMMINISTRATIVA,
		pirr1.CONTRIBUTO_AMMESSO,
		pirr1.IMPORTO_IRREGOLARE_CONCESSO,
		i.ID_PROGETTO,
		pirr1.ID_DOMANDA_PAGAMENTO
		from
		VIRREGOLARITA i
		inner join  
		(
			select 
			pirr.ID_IRREGOLARITA,
			pirr.ID_DOMANDA ID_DOMANDA_PAGAMENTO,
			--pirr.ID_PROGETTO,
			SUM(pb.CONTRIBUTO_AMMESSO) AS CONTRIBUTO_AMMESSO,
			SUM(pirr.IMPORTO_IRREGOLARE_CONCESSO) AS IMPORTO_IRREGOLARE_CONCESSO
			from
			PAGAMENTI_IRREGOLARITA pirr 
			inner join 
			PAGAMENTI_BENEFICIARIO pb on
			pirr.ID_PAGAMENTO_BENEFICIARIO = pb.ID_PAGAMENTO_BENEFICIARIO
			group by 
			pirr.ID_IRREGOLARITA,
			pirr.ID_DOMANDA,
			pirr.ID_PROGETTO
		)
		pirr1 on
		i.ID_IRREGOLARITA = pirr1.ID_IRREGOLARITA
		where 
		i.ID_CONTROLLO_ORIGINE = 10002
	) pirr3 ON
	DP.ID_DOMANDA_PAGAMENTO = pirr3.ID_DOMANDA_PAGAMENTO
WHERE 1 = 1
	AND DP.SEGNATURA IS NOT NULL
	AND ((@IdProgetto IS NULL) OR (DP.ID_PROGETTO = @IdProgetto))
ORDER BY 
	DP.ID_PROGETTO,
	DP.ID_DOMANDA_PAGAMENTO
END

--select * from ERRORE where ID_PROGETTO = 15029--10639
--SELECT * FROM vIRREGOLARITA WHERE ID_PROGETTO = 15029--10639
--select * from PAGAMENTI_IRREGOLARITA where ID_PROGETTO = 15029--10639

--select id_progetto from IRREGOLARITA
--union
--select id_progetto from ERRORE


--select * from IRREGOLARITA irr 
--inner join ERRORE err on err.ID_PROGETTO = irr.ID_PROGETTO


--select * from REVISIONE_DOMANDA_PAGAMENTO where ID_DOMANDA_PAGAMENTO in (12822
--,13784)

--select * from DOMANDA_DI_PAGAMENTO where ID_DOMANDA_PAGAMENTO in (12822
--,13784)
GO


