CREATE PROCEDURE [dbo].[RptQuadroESelect] 	
	@ID_Domanda int
AS
BEGIN
	
	SET NOCOUNT ON;
	DECLARE @IDFascicolo int
	SET @IDFascicolo = (select isNull (ID_FASCICOLO,( SELECT    MAX(F.ID_FASCICOLO) AS Expr1  
								FROM  IMPRESA INNER JOIN PROGETTO ON IMPRESA.ID_IMPRESA = PROGETTO.ID_IMPRESA 
								INNER JOIN FASCICOLO_AZIENDALE AS F ON IMPRESA.ID_IMPRESA = F.ID_IMPRESA
								WHERE     (PROGETTO.ID_PROGETTO = @ID_Domanda) ) ) 
								FROM PROGETTO WHERE ID_PROGETTO = @ID_Domanda)

	DECLARE @Count int
	SET @Count = (SELECT COUNT(ID_FASCICOLO) FROM ALLEVAMENTI_CLASSIFICATI WHERE ID_FASCICOLO = @IDFascicolo)

	IF (@Count > 0)
		
		SELECT CA.DESCRIZIONE AS SPECIE, AC.NUMEROSITA AS NUMERO_CAPI, CA.UBA AS COEFFICENTE_UBA, (AC.NUMEROSITA * CA.UBA) AS UBA
        FROM ALLEVAMENTI_CLASSIFICATI AC INNER JOIN CLASSIFICAZIONE_ALLEVAMENTI CA ON (AC.ID_CLASSE_ALLEVAMENTO = CA.ID_CLASSE)
		WHERE AC.ID_FASCICOLO = @IDFascicolo
		ORDER BY CA.DESCRIZIONE 

	ELSE SELECT NULL AS SPECIE,
				NULL AS NUMERO_CAPI,
				NULL AS COEFFICENTE_UBA,
				NULL AS UBA				
END
