CREATE PROCEDURE [dbo].[RptQuadroASelect_DomicilioAzienda]
@ID_Domanda int	
AS
BEGIN	

DECLARE @ID_IMPRESA int
SET @ID_IMPRESA = (SELECT ID_IMPRESA FROM dbo.PROGETTO WHERE ID_PROGETTO = @ID_Domanda)

IF (@ID_IMPRESA IS NOT NULL)
BEGIN
	
	SELECT TOP 1 IND.VIA,
       IND.LOCALITA,
       IND.TELEFONO,
       IND.FAX,
       IND.EMAIL,
       IND.COMUNE, 
       IND.CAP,
       IND.ISTAT AS ISTAT_COMUNE,
       IND.COD_PROVINCIA AS ISTAT_PROVINCIA,
       IND.SIGLA AS PROVINCIA             

	FROM  IMPRESA I 
			   INNER JOIN vINDIRIZZARIO IND ON (I.ID_IMPRESA = IND.ID_IMPRESA)
			  
    WHERE IND.COD_TIPO_SEDE = 'D' AND I.ID_IMPRESA = @ID_IMPRESA
	order by IND.ID_INDIRIZZARIO DESC
END
ELSE 
	BEGIN

		 SELECT NULL AS VIA,
				NULL AS LOCALITA,
				NULL AS TELEFONO,
				NULL AS FAX,
				NULL AS EMAIL,
				NULL AS COMUNE,
				NULL AS CAP,
				NULL AS ISTAT_COMUNE,
				NULL AS ISTAT_PROVINCIA,
				NULL AS PROVINCIA   
	END
END
