CREATE PROCEDURE [dbo].[RptQuadroSSelect]
@ID_Domanda int	
AS
BEGIN	
	--declare @ID_Domanda int	= 12056 
SET NOCOUNT ON;

DECLARE @Count int, @fase_istruttoria BIT
SET @Count = (SELECT COUNT(*) 
				FROM dbo.PRIORITA_X_PROGETTO PP INNER JOIN PROGETTO P ON PP.ID_PROGETTO = P.ID_PROGETTO 
				WHERE P.ID_PROGETTO = @ID_Domanda OR P.ID_PROG_INTEGRATO = @ID_Domanda)

IF (@Count > 0)
BEGIN

SET @fase_istruttoria= (SELECT COUNT(*) FROM vPROGETTO WHERE ORDINE_FASE>=2  AND ID_PROGETTO = @ID_Domanda)

DECLARE @TMP AS TABLE (COD_MISURA VARCHAR(500), REQUISITO_SOGGETTIVO VARCHAR(500), DESCRIZIONE_VALORE VARCHAR(500), DESCRIZIONE_MISURA VARCHAR(500), 
PROGRAMMAZIONE VARCHAR(500), ID_PRIORITA INT, TESTO VARCHAR(1000), VAL_TESTO VARCHAR(500), FATTO BIT, ORDINE INT)

INSERT INTO @TMP
select PRO.CODICE COD_MISURA, 
			P.DESCRIZIONE AS REQUISITO_SOGGETTIVO, 
			NULL AS DESCRIZIONE_VALORE, 
			PRO.DESCRIZIONE AS DESCRIZIONE_MISURA, 
			pro.TIPO AS PROGRAMMAZIONE, PP.ID_PRIORITA, Q.TESTO, VAL_TESTO, 0, SV.ORDINE
from PRIORITA P INNER JOIN PRIORITA_X_PROGETTO PP ON (P.ID_PRIORITA = PP.ID_PRIORITA)
                    LEFT JOIN VALORI_PRIORITA VP ON (PP.ID_VALORE = VP.ID_VALORE)
					INNER JOIN PROGETTO PR ON (PR.ID_PROGETTO = PP.ID_PROGETTO)
					INNER JOIN BANDO PB ON (PR.ID_BANDO = PB.ID_BANDO)
					INNER JOIN vzPROGRAMMAZIONE PRO ON PB.ID_PROGRAMMAZIONE = PRO.ID
					INNER JOIN SCHEDA_X_PRIORITA SV ON PB.ID_SCHEDA_VALUTAZIONE = SV.ID_SCHEDA_VALUTAZIONE AND SV.SELEZIONABILE = 1 
																					AND SV.ID_PRIORITA = PP.ID_PRIORITA	
					INNER JOIN dbo.zQUERY_SQL Q ON P.QUERY_PLURIVALORE = Q.NOME
WHERE P.COD_LIVELLO = 'D' AND (PP.ID_PROGETTO = @ID_Domanda OR ID_PROG_INTEGRATO = @ID_Domanda) AND P.PLURI_VALORE_SQL = 1
 
WHILE (SELECT COUNT(*) FROM @TMP WHERE FATTO = 0) > 0
BEGIN 

DECLARE @TESTO nVARCHAR(1000), @ID_PRIORITA INT, @DESCRIZIONE VARCHAR(500), @COD VARCHAR(500)
SELECT TOP 1 @TESTO = TESTO, @ID_PRIORITA = ID_PRIORITA, @COD = VAL_TESTO FROM @TMP WHERE FATTO = 0 


IF(@TESTO IS NOT NULL) 
BEGIN
	DECLARE @RISULT AS TABLE (DESCRIZIONE VARCHAR(500), CODICE VARCHAR(500))
	INSERT INTO @RISULT 
		EXECute sp_executesql @TESTO,N'@CODICE VARCHAR(500), @IdProgetto INT, @fase_istruttoria BIT',@COD, @ID_Domanda, @fase_istruttoria
	SELECT @DESCRIZIONE = case when DESCRIZIONE != @cod then descrizione else CODICE end FROM @RISULT	

END
UPDATE @TMP
SET DESCRIZIONE_VALORE = @DESCRIZIONE, FATTO = 1 
WHERE ID_PRIORITA = @ID_PRIORITA

END

	SELECT COD_MISURA, REQUISITO_SOGGETTIVO, DESCRIZIONE_VALORE, DESCRIZIONE_MISURA, PROGRAMMAZIONE, ORDINE
	FROM @TMP
	
	UNION 

	SELECT  PRO.CODICE COD_MISURA, 
			P.DESCRIZIONE AS REQUISITO_SOGGETTIVO, 
			ISNULL(VP.DESCRIZIONE, '') + '' + ISNULL(CAST(PP.VALORE AS VARCHAR), '') 
			+ ISNULL(CONVERT(VARCHAR(15), PP.VAL_DATA, 103), '')  
			+  ISNULL(PP.VAL_TESTO, '')  AS DESCRIZIONE_VALORE, 
			PRO.DESCRIZIONE AS DESCRIZIONE_MISURA, 
			pro.TIPO AS PROGRAMMAZIONE, ORDINE
			
	FROM PRIORITA P INNER JOIN PRIORITA_X_PROGETTO PP ON (P.ID_PRIORITA = PP.ID_PRIORITA)
                    LEFT JOIN VALORI_PRIORITA VP ON (PP.ID_VALORE = VP.ID_VALORE)
					INNER JOIN PROGETTO PR ON (PR.ID_PROGETTO = PP.ID_PROGETTO)
					INNER JOIN BANDO PB ON (PR.ID_BANDO = PB.ID_BANDO)
					INNER JOIN vzPROGRAMMAZIONE PRO ON PB.ID_PROGRAMMAZIONE = PRO.ID
					INNER JOIN SCHEDA_X_PRIORITA SV ON PB.ID_SCHEDA_VALUTAZIONE = SV.ID_SCHEDA_VALUTAZIONE AND SV.SELEZIONABILE = 1 
																					AND SV.ID_PRIORITA = PP.ID_PRIORITA
	WHERE P.COD_LIVELLO = 'D' AND (PP.ID_PROGETTO = @ID_Domanda OR ID_PROG_INTEGRATO = @ID_Domanda) AND P.PLURI_VALORE_SQL = 0 
	GROUP BY P.ID_PRIORITA, PRO.CODICE, P.DESCRIZIONE, VP.DESCRIZIONE, PP.VALORE, 
	PRO.DESCRIZIONE, PP.VAL_DATA, PP.VAL_TESTO, PRO.TIPO, PP.ID_PROGETTO, ORDINE
	ORDER BY 	ORDINE	
END

ELSE SELECT PRO.CODICE COD_MISURA, 'Nessun requisito soggettivo selezionato' AS REQUISITO_SOGGETTIVO,
            NULL AS DESCRIZIONE_VALORE, 
			PRO.DESCRIZIONE AS DESCRIZIONE_MISURA, 
			PRO.TIPO AS PROGRAMMAZIONE
			FROM PROGETTO PR 
					INNER JOIN BANDO PB ON (PR.ID_BANDO = PB.ID_BANDO)
					INNER JOIN vzPROGRAMMAZIONE PRO ON PB.ID_PROGRAMMAZIONE = PRO.ID
			WHERE (PR.ID_PROGETTO = @ID_Domanda OR PR.ID_PROG_INTEGRATO = @ID_Domanda)

END
