CREATE PROCEDURE [dbo].[RptQuadroTSelect]
@ID_Domanda int,
@COD_Tipo_Investimento int	
AS
BEGIN	

SET NOCOUNT ON;

	--DECLARE @ID_Domanda int
	--DECLARE @COD_Tipo_Investimento int
	--SET @ID_Domanda = 435
	--SET @COD_Tipo_Investimento = 1

DECLARE @Count INT
DECLARE @ID_VARIANTE int 
DECLARE @FASE BIT
DECLARE @USO_FEM BIT --aggiunto 23/03/2018 

SET @ID_VARIANTE =(SELECT MAX(ID_VARIANTE) FROM VARIANTI WHERE ID_PROGETTO=@ID_Domanda AND APPROVATA = 1)
SET @FASE = (SELECT CASE WHEN ORDINE_FASE>2 THEN 1 ELSE 0 END  FROM vPROGETTO  WHERE ID_PROGETTO = @ID_Domanda)

--Aggiunto 23/03/2018 per gestione visibilità colonne quota FEM
SET @USO_FEM = (SELECT TOP(1)
				--P.ID_BANDO,
				ISNULL(CONVERT(BIT, BC.VALORE),0) AS VALORE
				FROM vPROGETTO P 
				INNER JOIN BANDO B ON P.ID_BANDO = B.ID_BANDO
				LEFT OUTER JOIN BANDO_CONFIG BC ON
				B.ID_BANDO = BC.ID_BANDO
				AND
				BC.COD_TIPO = 'UTSTRUMFIN' 
				WHERE P.ID_PROGETTO = @ID_Domanda)
--fine aggiunta


SET @Count = (SELECT COUNT(I.ID_INVESTIMENTO) 
				FROM vPROGETTO AS P INNER JOIN VPIANO_INVESTIMENTI AS I ON P.ID_PROGETTO=I.ID_PROGETTO
				WHERE (P.ID_PROGETTO=@ID_Domanda OR P.ID_PROG_INTEGRATO=@ID_Domanda) AND
					((ORDINE_FASE IS NULL AND ID_INVESTIMENTO_ORIGINALE IS NULL AND ID_VARIANTE IS NULL) OR 
					(ORDINE_FASE<4 AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL) OR
					(ORDINE_FASE>=4  AND ((@ID_VARIANTE IS NULL AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL) OR
					 ID_VARIANTE=@ID_VARIANTE))) AND I.COD_TIPO_INVESTIMENTO = @COD_Tipo_Investimento)

IF (@Count > 0)
BEGIN
IF(@COD_Tipo_Investimento = 1) -- investimenti
BEGIN

	DECLARE @TMP AS TABLE (ID_PRIORITA INT, ID_INVESTIMENTO INT, TESTO VARCHAR(MAX), VAL_TESTO VARCHAR(1000), DESCRIZIONE VARCHAR(1000), FATTO BIT)

INSERT INTO @TMP
select PP.ID_PRIORITA, PIN.ID_INVESTIMENTO, Q.TESTO, VAL_TESTO, NULL, 0
from vPIANO_INVESTIMENTI PIN
INNER JOIN vPROGETTO AS P ON PIN.ID_PROGETTO = P.ID_PROGETTO
INNER JOIN vPRIORITA_X_INVESTIMENTI PP ON PIN.ID_INVESTIMENTO = PP.ID_INVESTIMENTO
inner join PRIORITA PRIO ON PP.ID_PRIORITA = PRIO.ID_PRIORITA
INNER JOIN dbo.zQUERY_SQL Q ON PRIO.QUERY_PLURIVALORE = Q.NOME
INNER JOIN BANDO PB ON (P.ID_BANDO = PB.ID_BANDO)
INNER JOIN vzPROGRAMMAZIONE PRO ON PB.ID_PROGRAMMAZIONE = PRO.ID
WHERE (P.ID_PROGETTO=@ID_Domanda OR P.ID_PROG_INTEGRATO=@ID_Domanda) AND
	((ORDINE_FASE IS NULL AND ID_INVESTIMENTO_ORIGINALE IS NULL AND ID_VARIANTE IS NULL) OR 
	(ORDINE_FASE<4 AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL) OR
	(ORDINE_FASE>=4  AND ((@ID_VARIANTE IS NULL AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL) OR
	 ID_VARIANTE=@ID_VARIANTE))) AND PIN.COD_TIPO_INVESTIMENTO = 1 AND ISNULL(COD_VARIAZIONE,'x')!='A'
WHILE (
SELECT COUNT(*) FROM @TMP WHERE FATTO = 0) > 0
BEGIN 

DECLARE @TESTO nVARCHAR(MAX), @ID_PRIORITA INT, @DESCRIZIONE VARCHAR(1000), @COD VARCHAR(1000), 
@ID_INV INT 
SELECT TOP 1 @TESTO = TESTO, @ID_PRIORITA = ID_PRIORITA, @COD = VAL_TESTO, @ID_INV = ID_INVESTIMENTO
FROM @TMP WHERE FATTO = 0 


IF(@TESTO IS NOT NULL) 
BEGIN
	DECLARE @RISULT AS TABLE (CODICE VARCHAR(1000), DESCRIZIONE VARCHAR(1000))
	INSERT INTO @RISULT 
		EXECute sp_executesql @TESTO,N'@CODICE VARCHAR(1000), @IdProgetto INT, @fase_istruttoria BIT',@COD, @ID_Domanda, @FASE
	SELECT @DESCRIZIONE = case when DESCRIZIONE != @cod then descrizione else CODICE end FROM @RISULT	
END
UPDATE @TMP
SET DESCRIZIONE = @DESCRIZIONE, FATTO = 1 
WHERE ID_INVESTIMENTO = @ID_INV AND ID_PRIORITA = @ID_PRIORITA

END
		SELECT vPIANO_INVESTIMENTI.MISURA, vPIANO_INVESTIMENTI.DESCRIZIONE, vPIANO_INVESTIMENTI.QUANTITA, vPIANO_INVESTIMENTI.COSTO_INVESTIMENTO, 
                      vPIANO_INVESTIMENTI.SPESE_GENERALI, vPIANO_INVESTIMENTI.CONTRIBUTO_RICHIESTO, 
                      vPIANO_INVESTIMENTI.QUOTA_CONTRIBUTO_RICHIESTO, vPIANO_INVESTIMENTI.ID_OBIETTIVO_MISURA, vPIANO_INVESTIMENTI.AMMESSO, 
                      vPIANO_INVESTIMENTI.COD_TP, vPIANO_INVESTIMENTI.CODIFICA_INVESTIMENTO, vPIANO_INVESTIMENTI.AIUTO_MINIMO, 
                      vPIANO_INVESTIMENTI.CODICE, vPIANO_INVESTIMENTI.SPECIFICA_INVESTIMENTI, vPIANO_INVESTIMENTI.DETTAGLIO_INVESTIMENTI, 
                      vPIANO_INVESTIMENTI.MOBILE, vPIANO_INVESTIMENTI.QUOTA_SPESE_GENERALI, vPIANO_INVESTIMENTI.SETTORE_PRODUTTIVO, 
                     CAST(vPIANO_INVESTIMENTI.VALUTAZIONE_INVESTIMENTO AS VARCHAR(MAX)) AS VALUTAZIONE_INVESTIMENTO, zOB_MISURA.CODICE AS COD_OB_MISURA, 
                      zOB_MISURA.DESCRIZIONE AS DESCRIZIONE_OBIETTIVI_MISURA, zPROGRAMMAZIONE.CODICE AS COD_INTERVENTO, 
                      zPROGRAMMAZIONE.DESCRIZIONE AS DESCRIZIONE_INTERVENTO, UNITA_DI_MISURA.DESCRIZIONE AS DESCRIZIONE_UNITA_MISURA, 
                      zSTP.DESCRIZIONE AS DESCRIZIONE_STP, PRIORITA_SETTORIALI.DESCRIZIONE AS DESCRIZIONE_PRIORITA_SETTORIALE, 
                      PRIORITA.DESCRIZIONE AS DESCRIZIONE_PRIORITA, 
                      VPRIORITA_X_INVESTIMENTI.SCELTO AS PRIORITA_SELEZIONATA, 
					 ISNULL(VPRIORITA_X_INVESTIMENTI.DESCRIZIONE, '') + ISNULL(CONVERT(VARCHAR(15), vPRIORITA_X_INVESTIMENTI.VAL_DATA, 103), '') 
					 +  ISNULL(TMP.DESCRIZIONE, ISNULL(vPRIORITA_X_INVESTIMENTI.VAL_TESTO, '')) AS DESCRIZIONE_SELEZIONATA, 
					  VPRIORITA_X_INVESTIMENTI.VALORE AS INPUT_SELEZIONATO,
                      vPIANO_INVESTIMENTI.ID_INVESTIMENTO, 
                      vPIANO_INVESTIMENTI.ID_INVESTIMENTO_ORIGINALE, 
                      PRIORITA_SETTORIALI.ID_PRIORITA_SETTORIALE,
					DENSE_RANK() over (ORDER BY  COD_TIPO_INVESTIMENTO, VPIANO_INVESTIMENTI.ID_INVESTIMENTO) AS ROWS,
					SV.ORDINE,
					vPIANO_INVESTIMENTI.QUOTA_CONTRIBUTO_ALTRE_FONTI, --aggiunto 23/03/2018 
					vPIANO_INVESTIMENTI.CONTRIBUTO_ALTRE_FONTI, --aggiunto 23/03/2018 
					@USO_FEM AS USO_FEM --aggiunto 23/03/2018 
		FROM         vPIANO_INVESTIMENTI INNER JOIN
                      vPROGETTO AS P ON vPIANO_INVESTIMENTI.ID_PROGETTO = P.ID_PROGETTO
                     INNER JOIN BANDO B ON P.ID_BANDO = B.ID_BANDO 
                      INNER JOIN
                      zOB_MISURA ON vPIANO_INVESTIMENTI.ID_OBIETTIVO_MISURA = zOB_MISURA.ID INNER JOIN
                      zPROGRAMMAZIONE ON vPIANO_INVESTIMENTI.ID_PROGRAMMAZIONE = zPROGRAMMAZIONE.ID LEFT OUTER JOIN
                      UNITA_DI_MISURA ON vPIANO_INVESTIMENTI.ID_UNITA_MISURA = UNITA_DI_MISURA.ID_UNITA_MISURA LEFT OUTER JOIN
                      zSTP ON B.ID_PROGRAMMAZIONE = zSTP.ID_PROGRAMMAZIONE AND ZSTP.CODICE = vPIANO_INVESTIMENTI.COD_STP
                      LEFT OUTER JOIN vPRIORITA_X_INVESTIMENTI ON vPIANO_INVESTIMENTI.ID_INVESTIMENTO = vPRIORITA_X_INVESTIMENTI.ID_INVESTIMENTO LEFT OUTER JOIN
                      PRIORITA ON vPRIORITA_X_INVESTIMENTI.ID_PRIORITA = PRIORITA.ID_PRIORITA LEFT OUTER JOIN
                      PRIORITA_SETTORIALI ON vPIANO_INVESTIMENTI.ID_PRIORITA_SETTORIALE = PRIORITA_SETTORIALI.ID_PRIORITA_SETTORIALE 
                      LEFT JOIN SCHEDA_X_PRIORITA SV ON B.ID_SCHEDA_VALUTAZIONE = SV.ID_SCHEDA_VALUTAZIONE AND SV.ID_PRIORITA = vPRIORITA_X_INVESTIMENTI.ID_PRIORITA	
                     LEFT JOIN @TMP TMP ON  PRIORITA.ID_PRIORITA  = TMP.ID_PRIORITA AND vPRIORITA_X_INVESTIMENTI.ID_INVESTIMENTO = TMP.ID_INVESTIMENTO
				WHERE (P.ID_PROGETTO=@ID_Domanda OR P.ID_PROG_INTEGRATO=@ID_Domanda) AND
					((ORDINE_FASE IS NULL AND ID_INVESTIMENTO_ORIGINALE IS NULL AND ID_VARIANTE IS NULL) OR 
					(ORDINE_FASE<4 AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL) OR
					(ORDINE_FASE>=4  AND ((@ID_VARIANTE IS NULL AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL) OR
					 ID_VARIANTE=@ID_VARIANTE))) AND vPIANO_INVESTIMENTI.COD_TIPO_INVESTIMENTO = 1 AND ISNULL(COD_VARIAZIONE,'x')!='A'
			  GROUP BY vPIANO_INVESTIMENTI.MISURA, vPIANO_INVESTIMENTI.DESCRIZIONE, vPIANO_INVESTIMENTI.QUANTITA, vPIANO_INVESTIMENTI.COSTO_INVESTIMENTO, 
                      vPIANO_INVESTIMENTI.SPESE_GENERALI, vPIANO_INVESTIMENTI.CONTRIBUTO_RICHIESTO, 
                      vPIANO_INVESTIMENTI.QUOTA_CONTRIBUTO_RICHIESTO, vPIANO_INVESTIMENTI.ID_OBIETTIVO_MISURA, vPIANO_INVESTIMENTI.AMMESSO, 
                      vPIANO_INVESTIMENTI.COD_TP, vPIANO_INVESTIMENTI.CODIFICA_INVESTIMENTO, vPIANO_INVESTIMENTI.AIUTO_MINIMO, 
                      vPIANO_INVESTIMENTI.CODICE, vPIANO_INVESTIMENTI.SPECIFICA_INVESTIMENTI, vPIANO_INVESTIMENTI.DETTAGLIO_INVESTIMENTI, 
                      vPIANO_INVESTIMENTI.MOBILE, vPIANO_INVESTIMENTI.QUOTA_SPESE_GENERALI, vPIANO_INVESTIMENTI.SETTORE_PRODUTTIVO, 
                      zOB_MISURA.CODICE, 
                      zOB_MISURA.DESCRIZIONE, zPROGRAMMAZIONE.CODICE, zPROGRAMMAZIONE.DESCRIZIONE, UNITA_DI_MISURA.DESCRIZIONE, 
                      zSTP.DESCRIZIONE, PRIORITA_SETTORIALI.DESCRIZIONE, PRIORITA.DESCRIZIONE, 
                      VPRIORITA_X_INVESTIMENTI.SCELTO, VPRIORITA_X_INVESTIMENTI.DESCRIZIONE, vPRIORITA_X_INVESTIMENTI.VAL_DATA, vPRIORITA_X_INVESTIMENTI.VAL_TESTO,
					  VPRIORITA_X_INVESTIMENTI.VALORE,
                      vPIANO_INVESTIMENTI.ID_INVESTIMENTO, 
                      vPIANO_INVESTIMENTI.ID_INVESTIMENTO_ORIGINALE, 
                      PRIORITA_SETTORIALI.ID_PRIORITA_SETTORIALE,COD_TIPO_INVESTIMENTO, VPIANO_INVESTIMENTI.ID_INVESTIMENTO, 
                     CAST(vPIANO_INVESTIMENTI.VALUTAZIONE_INVESTIMENTO AS VARCHAR(MAX)), TMP.DESCRIZIONE, SV.ORDINE,
                     vPIANO_INVESTIMENTI.QUOTA_CONTRIBUTO_ALTRE_FONTI, --aggiunto 23/03/2018 
					 vPIANO_INVESTIMENTI.CONTRIBUTO_ALTRE_FONTI --aggiunto 23/03/2018 

END  
ELSE IF(@COD_Tipo_Investimento = 2)  -- mutuo
BEGIN
		SELECT     vPIANO_INVESTIMENTI.ID_INVESTIMENTO, vPIANO_INVESTIMENTI.DESCRIZIONE, vPIANO_INVESTIMENTI.QUANTITA, vPIANO_INVESTIMENTI.COSTO_INVESTIMENTO, 
                      vPIANO_INVESTIMENTI.SPESE_GENERALI, vPIANO_INVESTIMENTI.CONTRIBUTO_RICHIESTO, 
                      vPIANO_INVESTIMENTI.QUOTA_CONTRIBUTO_RICHIESTO, vPIANO_INVESTIMENTI.CODIFICA_INVESTIMENTO, 
                      vPIANO_INVESTIMENTI.AIUTO_MINIMO, zOB_MISURA.CODICE as COD_OB_MISURA, 
                      zOB_MISURA.DESCRIZIONE AS DESCRIZIONE_OBIETTIVI_MISURA, zPROGRAMMAZIONE.CODICE AS COD_INTERVENTO, 
                      zPROGRAMMAZIONE.DESCRIZIONE AS DESCRIZIONE_INTERVENTO, vPIANO_INVESTIMENTI.VALUTAZIONE_INVESTIMENTO
		FROM         vPIANO_INVESTIMENTI LEFT OUTER JOIN
                      vPROGETTO AS P ON vPIANO_INVESTIMENTI.ID_PROGETTO = P.ID_PROGETTO INNER JOIN
                      zOB_MISURA ON vPIANO_INVESTIMENTI.ID_OBIETTIVO_MISURA = zOB_MISURA.ID INNER JOIN
                      zPROGRAMMAZIONE ON vPIANO_INVESTIMENTI.ID_PROGRAMMAZIONE = zPROGRAMMAZIONE.ID
		WHERE (P.ID_PROGETTO=@ID_Domanda OR P.ID_PROG_INTEGRATO=@ID_Domanda) AND
					((ORDINE_FASE IS NULL AND ID_INVESTIMENTO_ORIGINALE IS NULL AND ID_VARIANTE IS NULL) OR 
					(ORDINE_FASE<4 AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL) OR
					(ORDINE_FASE>=4  AND ((@ID_VARIANTE IS NULL AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL) OR
					 ID_VARIANTE=@ID_VARIANTE))) AND vPIANO_INVESTIMENTI.COD_TIPO_INVESTIMENTO = 2 AND ISNULL(COD_VARIAZIONE,'x')!='A'
END


ELSE IF(@COD_Tipo_Investimento = 5)  -- BREVETTI
BEGIN
		SELECT    vPIANO_INVESTIMENTI.ID_INVESTIMENTO,  vPIANO_INVESTIMENTI.DESCRIZIONE, QUANTITA, COSTO_INVESTIMENTO, CONTRIBUTO_RICHIESTO,
					QUOTA_CONTRIBUTO_RICHIESTO
		FROM         vPIANO_INVESTIMENTI INNER JOIN
							  vPROGETTO AS P ON vPIANO_INVESTIMENTI.ID_PROGETTO = P.ID_PROGETTO
		WHERE (P.ID_PROGETTO=@ID_Domanda OR P.ID_PROG_INTEGRATO=@ID_Domanda) AND
					((ORDINE_FASE IS NULL AND ID_INVESTIMENTO_ORIGINALE IS NULL AND ID_VARIANTE IS NULL) OR 
					(ORDINE_FASE<4 AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL) OR
					(ORDINE_FASE>=4  AND ((@ID_VARIANTE IS NULL AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL) OR
					 ID_VARIANTE=@ID_VARIANTE))) AND vPIANO_INVESTIMENTI.COD_TIPO_INVESTIMENTO = 5 AND ISNULL(COD_VARIAZIONE,'x')!='A'

END
ELSE SELECT NULL AS DESCRIZIONE, 
			NULL AS QUANTITA, 
			NULL AS COSTO_INVESTIMENTO, 
            NULL AS SPESE_GENERALI, 
			NULL AS CONTRIBUTO_RICHIESTO, 
            NULL AS QUOTA_CONTRIBUTO_RICHIESTO, 
			NULL AS ID_OBIETTIVO_MISURA, 
			NULL AS AMMESSO, 
            NULL AS COD_TP, 
			NULL AS CODIFICA_INVESTIMENTO, 
			NULL AS AIUTO_MINIMO, 
			NULL AS ORDINE
END
END
