CREATE PROCEDURE [dbo].[RptQuadroMSelect] 	
@ID_Domanda int
AS
BEGIN	

	SET NOCOUNT ON;
	DECLARE @IDFascicolo int
	SET @IDFascicolo = (select isNull (ID_FASCICOLO,( SELECT    MAX(F.ID_FASCICOLO) AS Expr1  
								FROM  IMPRESA INNER JOIN PROGETTO ON IMPRESA.ID_IMPRESA = PROGETTO.ID_IMPRESA
								INNER JOIN FASCICOLO_AZIENDALE AS F ON IMPRESA.ID_IMPRESA = F.ID_IMPRESA
								WHERE     (PROGETTO.ID_PROGETTO = @ID_Domanda) ) ) 
								FROM PROGETTO WHERE ID_PROGETTO = @ID_Domanda)

	DECLARE @Count int
	SET @Count = (SELECT COUNT(ID_FASCICOLO) FROM MACCHINARI WHERE ID_FASCICOLO = @IDFascicolo)

	IF (@Count > 0)
		SELECT TIPO_MACCHINARIO, 
               TIPO_POSSESSO, 
               MARCA, 
               MODELLO, 
               TIPO_TRAZIONE, 
               TIPO_CARBURANTE,
               TARGA, 
               ANNO_ISCRIZIONE, 
               DATA_CARICO, 
               TIPO_USO, 
			   KW
		FROM MACCHINARI
		WHERE ID_FASCICOLO = @IDFascicolo
	ELSE SELECT NULL AS TIPO_MACCHINARIO,
				NULL AS TIPO_POSSESSO,
				NULL AS MARCA,
				NULL AS MODELLO,
				NULL AS TIPO_TRAZIONE,
				NULL AS TIPO_CARBURANTE,
				NULL AS TARGA,
				NULL AS ANNO_ISCRIZIONE,
				NULL AS DATA_CARICO,
				NULL AS TIPO_USO,
				NULL AS KW
			
END
