CREATE PROCEDURE [dbo].[RptQuadroASelect_SedeLegaleAzienda]
@ID_Domanda int	
AS
BEGIN	

DECLARE @ID_IMPRESA int
SET @ID_IMPRESA = (SELECT ID_IMPRESA FROM dbo.PROGETTO WHERE ID_PROGETTO = @ID_Domanda)

IF (@ID_IMPRESA IS NOT NULL)
BEGIN
	
	SELECT IND.VIA,
       IND.LOCALITA,
       IND.TELEFONO,
       IND.FAX,
       IND.EMAIL,
       IND.COMUNE AS COMUNE, 
       IND.CAP,
       IND.ISTAT AS ISTAT_COMUNE,
       IND.COD_PROVINCIA AS ISTAT_PROVINCIA,
       IND.SIGLA AS PROVINCIA,
       IND.PEC        

	FROM IMPRESA I 
					   INNER JOIN VINDIRIZZARIO IND ON (I.ID_SEDELEGALE_ULTIMO = IND.ID_INDIRIZZARIO)
  	WHERE I.ID_IMPRESA = @ID_IMPRESA

END
ELSE 
	BEGIN

		 SELECT NULL AS VIA,
				NULL AS LOCALITA,
				NULL AS TELEFONO,
				NULL AS FAX,
				NULL AS EMAIL,
				NULL AS COMUNE,
				NULL AS CAP,
				NULL AS ISTAT_COMUNE,
				NULL AS ISTAT_PROVINCIA,
				NULL AS PROVINCIA   
	END
END
