CREATE PROCEDURE [dbo].[RptQuadroKPremio]

	@IdProgetto int

AS
BEGIN

--DECLARE  @IdProgetto int = 1571
DECLARE @FASE BIT
DECLARE @ID_VARIANTE INT
DECLARE @PREMIO DECIMAL(16,2) 
DECLARE @PRES AS VARCHAR(2) = 'SI'
IF((SELECT COUNT(*) FROM BANDO_TIPO_INVESTIMENTI WHERE COD_TIPO_INVESTIMENTO=3 AND ID_BANDO = (SELECT ID_BANDO FROM PROGETTO WHERE ID_PROGETTO = @IdProgetto)) > 0)
BEGIN
	SET @ID_VARIANTE = (SELECT MAX(ID_VARIANTE) FROM VARIANTI WHERE ID_PROGETTO=@IdProgetto  AND APPROVATA = 1)
	SET @FASE = (SELECT CASE WHEN ORDINE_FASE>2 THEN 1 ELSE 0 END  FROM vPROGETTO  WHERE ID_PROGETTO = @IdProgetto)
	IF (@FASE IS NULL) SET @FASE=0
	SELECT @PREMIO = DBO.calcoloPremioContoCapitale(@IdProgetto, @FASE, @ID_VARIANTE) 
END 
ELSE SET	@PRES = 'NO'
	SELECT @PREMIO AS PREMIO , @PRES AS PRESENTE
END
