CREATE PROCEDURE [dbo].[RptQuadroISelect] 
@ID_Domanda int
AS
BEGIN
	SET NOCOUNT ON;
	
	IF(SELECT COUNT(*)
    FROM vPROGETTO_RELAZIONE_TECNICA
	WHERE ID_PROGETTO = @ID_Domanda ) > 0 
	
	SELECT r.TITOLO, R.TESTO
    FROM vPROGETTO_RELAZIONE_TECNICA R 
	WHERE R.ID_PROGETTO = @ID_Domanda 
	ORDER BY R.ORDINE
	
	ELSE 
	SELECT NULL AS TITOLO, NULL AS TESTO

END
