CREATE PROCEDURE [dbo].[RptRAEDettaglio]
@Misura char(6) -- esempio 1.1.1.
AS

SELECT  ISNULL(PR.ID_PROG_INTEGRATO, PR.ID_PROGETTO) AS ID_PROGETTO, STATO, PR.ID_BANDO,
P.CODICE_MISURA, COD_OB_MISURA, O.DESCRIZIONE AS OBIETTIVO_MISURA, COD_INTERVENTO, PBB.INTERVENTO,
STP.DESCRIZIONE AS STP, 
CODIFICA_INVESTIMENTO, DETTAGLIO_INVESTIMENTI, SPECIFICA_INVESTIMENTI, P.DESCRIZIONE AS DESCRIZIONE_INVESTIMENTO,
P.SETTORE_PRODUTTIVO, PRIORITA_SETTORIALE, SCELTO, QUANTITA, UDM.DESCRIZIONE AS UNITA_MISURA,
ISNULL(CASE COD_TIPO_INVESTIMENTO WHEN 2 THEN ISNULL(COSTO_INVESTIMENTO,0) 
		ELSE ISNULL(COSTO_INVESTIMENTO,0)+ISNULL(SPESE_GENERALI,0) END,0) AS COSTO_AMMESSO, 
P.CONTRIBUTO_RICHIESTO AS CONTRIBUTO_AMMESSO,
(
SELECT ISNULL(CASE COD_TIPO_INVESTIMENTO WHEN 2 THEN ISNULL(COSTO_INVESTIMENTO,0) 
		ELSE ISNULL(COSTO_INVESTIMENTO,0)+ISNULL(SPESE_GENERALI,0) END,0) AS COSTO 
FROM VPIANO_INVESTIMENTI WHERE VPIANO_INVESTIMENTI.ID_INVESTIMENTO = P.ID_INVESTIMENTO_ORIGINALE) AS COSTO_RICHIESTO,
(SELECT CONTRIBUTO_RICHIESTO FROM VPIANO_INVESTIMENTI WHERE VPIANO_INVESTIMENTI.ID_INVESTIMENTO = P.ID_INVESTIMENTO_ORIGINALE) AS CONTRIBUTO_RICHIESTO,
/*dbo.calcoloPremioContoCapitale(PR.ID_PROG_INTEGRATO, 0, NULL)*/ 0 AS PREMIO_RICHIESTO,
/*dbo.calcoloPremioContoCapitale(PR.ID_PROG_INTEGRATO, 1, NULL)*/ 0 AS PREMIO_AMMESSO,

(SELECT dbo.OTE_PLV (ISNULL(PR.ID_PROG_INTEGRATO, PR.ID_PROGETTO), NULL)) AS OTE,
PXP.VALORE_DESC AS FILIERA, B.DESCRIZIONE AS BANDO, B.DATA_SCADENZA,
PXP_RO.VALORE_DESC AS RUOLO_OPERATIVO
, ISNULL(PXP_LR23.ID_PRIORITA, 0)  AS [LR 23/2003]
, ISNULL(PXP_R834.ID_PRIORITA, 0) AS [REG CE 834/07]
, ISNULL(PXP_R510.ID_PRIORITA, 0) AS [REG CE 510/2006]
, ISNULL(PXP_R509.ID_PRIORITA, 0) AS [REG CE 509/2006]
, ISNULL(PXP_TIT1463.ID_PRIORITA, 0) AS [Titolo VI del Regolamento del Consiglio  n. 1493/99]
, ISNULL(PXP_R1974.ID_PRIORITA, 0) AS [REG CE 1974/06]
, V.ID_V, P.COD_VARIAZIONE, P.ID_INVESTIMENTO,ISNULL(PRI.IMPORTO_AMMESSO_PAGAMENTO, 0) as IMPORTO_AMMESSO_PAGAMENTO, ISNULL(PRI.CONTRIBUTO_AMMESSO_PAGAMENTO, 0) AS CONTRIBUTO_AMMESSO_PAGAMENTO
FROM  vPROGETTO PR INNER JOIN 
(SELECT ID_BANDO, ISNULL(ID_DISPOSIZIONI_ATTUATIVE, ID_BANDO) AS DISP
FROM PROGRAMMAZIONE_BANDO GROUP BY ID_BANDO, ID_DISPOSIZIONI_ATTUATIVE) AS PB ON PB.DISP = PR.ID_BANDO
INNER JOIN VPIANO_INVESTIMENTI P ON PR.ID_PROGETTO = P.ID_PROGETTO  
LEFT JOIN OBIETTIVI_DI_MISURA O ON P.ID_OBIETTIVO_MISURA = O.ID_OBIETTIVO_MISURA
LEFT JOIN UNITA_DI_MISURA UDM ON UDM.ID_UNITA_MISURA = P.ID_UNITA_MISURA
LEFT JOIN dbo.vSTP AS STP ON STP.ID_PSR = P.ID_PSR AND STP.COD_OBIETTIVO = P.COD_OBIETTIVO AND 
		STP.COD_ASSE = P.COD_ASSE AND STP.COD_MISURA = P.COD_MISURA AND STP.COD_STP = P.COD_STP
LEFT JOIN VBANDO_X_SETTORE_PRODUTTIVO BSP ON BSP.ID_BANDO = P.ID_BANDO AND BSP.ID_SETTORE_PRODUTTIVO = P.ID_SETTORE_PRODUTTIVO 
		AND BSP.ID_PRIORITA_SETTORIALE = P.ID_PRIORITA_SETTORIALE
LEFT JOIN PRIORITA_X_INVESTIMENTI PXI ON PXI.ID_INVESTIMENTO = P.ID_INVESTIMENTO AND PXI.ID_PRIORITA IN (25,60,179,192,240)-- per la misura 226 bisogna togliere 166,167 altrimenti duplica i record
LEFT JOIN VPROGRAMMAZIONE_BANDO PBB ON PBB.ID_PROGRAMMAZIONE = P.ID_PROGRAMMAZIONE AND P.ID_BANDO = PBB.ID_BANDO
LEFT OUTER JOIN  vPRIORITA_X_PROGETTO AS PXP ON PXP.ID_PROGETTO = PR.ID_PROGETTO AND PXP.ID_PRIORITA IN (374, 406,798, 1191) -- FILIERA
INNER JOIN vBANDOATTUALE B ON PR.ID_BANDO = B.ID_BANDO
LEFT JOIN vPRIORITA_X_PROGETTO AS PXP_RO ON PR.ID_PROGETTO = PXP_RO.ID_PROGETTO AND PXP_RO.ID_PRIORITA IN (391) -- RUOLO OPERATIVO 
LEFT JOIN vPRIORITA_X_PROGETTO AS PXP_LR23 ON P.ID_PROGETTO = PXP_LR23.ID_PROGETTO AND PXP_LR23.ID_PRIORITA IN (265) -- LR 23/2003
LEFT JOIN vPRIORITA_X_PROGETTO AS PXP_R834 ON P.ID_PROGETTO = PXP_R834.ID_PROGETTO AND PXP_R834.ID_PRIORITA IN (232, 262) --REG CE 834/07
LEFT JOIN vPRIORITA_X_PROGETTO AS PXP_R510 ON P.ID_PROGETTO = PXP_R510.ID_PROGETTO AND PXP_R510.ID_PRIORITA IN (233, 263) --REG CE 510/2006
LEFT JOIN vPRIORITA_X_PROGETTO AS PXP_R509 ON P.ID_PROGETTO = PXP_R509.ID_PROGETTO AND PXP_R509.ID_PRIORITA IN (234, 264) --REG CE 509/2006
LEFT JOIN vPRIORITA_X_PROGETTO AS PXP_TIT1463 ON P.ID_PROGETTO = PXP_TIT1463.ID_PROGETTO AND PXP_TIT1463.ID_PRIORITA IN (277) --Titolo VI del Regolamento del Consiglio  n. 1493/99 â€“ produzioni DOC e DOCG
LEFT JOIN vPRIORITA_X_PROGETTO AS PXP_R1974 ON P.ID_PROGETTO = PXP_R1974.ID_PROGETTO AND PXP_R1974.ID_PRIORITA IN (284) -- REG CE 1974/06 art. 22 - Produzioni con marchio collettivo di qualitÃ  
LEFT JOIN (SELECT MAX(ID_VARIANTE) ID_V, ID_PROGETTO FROM VARIANTI WHERE APPROVATA = 1 GROUP BY ID_PROGETTO) V ON ISNULL(PR.ID_PROG_INTEGRATO, PR.ID_PROGETTO) = V.ID_PROGETTO 
LEFT JOIN (SELECT SUM(ISNULL(IMPORTO_AMMESSO, 0)) as IMPORTO_AMMESSO_PAGAMENTO, SUM(ISNULL(CONTRIBUTO_AMMESSO, 0)) AS CONTRIBUTO_AMMESSO_PAGAMENTO, ID_INVESTIMENTO FROM PAGAMENTI_RICHIESTI PR
inner jOIN DOMANDA_DI_PAGAMENTO DP ON PR.ID_DOMANDA_PAGAMENTO = DP.ID_DOMANDA_PAGAMENTO WHERE APPROVATA = 1 
					GROUP BY ID_INVESTIMENTO)
 PRI ON P.ID_INVESTIMENTO = PRI.ID_INVESTIMENTO
WHERE PB.ID_BANDO IN(SELECT  ID_BANDO
				FROM          vPROGRAMMAZIONE_BANDO INNER JOIN
					   MISURA ON vPROGRAMMAZIONE_BANDO.ID_PSR = MISURA.ID_PSR AND 
					   vPROGRAMMAZIONE_BANDO.COD_OBIETTIVO = MISURA.COD_OBIETTIVO AND 
					   vPROGRAMMAZIONE_BANDO.COD_ASSE = MISURA.COD_ASSE AND 
					   vPROGRAMMAZIONE_BANDO.COD_MISURA = MISURA.COD_MISURA
				WHERE   (vPROGRAMMAZIONE_BANDO.MISURA_PREVALENTE = 1)
				AND CODICE = @Misura
				AND MISURA.ID_PSR = 1 
				GROUP BY ID_BANDO, CODICE) 
		AND ((V.ID_V IS NULL AND  ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL) OR (V.ID_V IS NOT NULL AND ID_VARIANTE = V.ID_V ))
--AND PR.ID_PROGETTO = 328 
AND ISNULL(COD_VARIAZIONE, 'X') != 'A' 
ORDER BY ISNULL(PR.ID_PROG_INTEGRATO, PR.ID_PROGETTO)
