--UTILIZZATA SULLA NOTIFICA BIO (SEZIONE DATI GENERALI) 
CREATE PROCEDURE [dbo].[RptSezioneIndirizzario]
(
@IdImpresa int,
@CodSede char(1)
)
AS
		BEGIN 
			SELECT  TOP(1)    INDIRIZZO.VIA, 
						INDIRIZZO.LOCALITA, 
						INDIRIZZARIO.TELEFONO, 
						INDIRIZZARIO.FAX, 
						INDIRIZZARIO.EMAIL, 
						C.DENOMINAZIONE AS COMUNE, 
						C.CAP, 
						C.ISTAT AS ISTAT_COMUNE, 
						C.COD_PROVINCIA AS ISTAT_PROVINCIA, 
						P.SIGLA AS PROVINCIA,
						INDIRIZZARIO.PEC
			FROM        IMPRESA AS I INNER JOIN
								  INDIRIZZARIO AS INDIRIZZARIO ON I.ID_IMPRESA = INDIRIZZARIO.ID_IMPRESA INNER JOIN
								  INDIRIZZO AS INDIRIZZO ON INDIRIZZARIO.ID_INDIRIZZO = INDIRIZZO.ID_INDIRIZZO INNER JOIN
								  COMUNI AS C ON INDIRIZZO.ID_COMUNE = C.ID_COMUNE INNER JOIN
								  PROVINCE AS P ON C.COD_PROVINCIA = P.CODICE
			WHERE     (INDIRIZZARIO.COD_TIPO_SEDE = @CodSede) AND (I.ID_IMPRESA = @IdImpresa) 
			ORDER BY INDIRIZZARIO.ID_INDIRIZZARIO DESC
		END
