--UTILIZZATA SULLA NOTIFICA BIO (SEZIONE DATI GENERALI) 
CREATE PROCEDURE [dbo].[RptSezioneRappresentanteLegale]
(
@IdImpresa int	
)
AS
BEGIN
			SELECT   TOP(1)   PF.NOME, 
						PF.COGNOME, 
						PF.CODICE_FISCALE, 
						PF.SESSO, 
						PF.DATA_NASCITA,
						PXI.COD_RUOLO,
						C1.DENOMINAZIONE AS COMUNE_NASCITA, 
						P1.SIGLA AS PROVINCIA_NASCITA, 
						INDIRIZZARIO.TELEFONO, 
						INDIRIZZARIO.FAX, 
						INDIRIZZARIO.EMAIL, 
						INDIRIZZO.VIA AS VIA_RESIDENZA, 
						INDIRIZZO.LOCALITA AS LOCALITA_RESIDENZA, 
						C2.DENOMINAZIONE AS COMUNE_RESIDENZA, 
						C2.CAP AS CAP_RESIDENZA, 
						C2.ISTAT AS ISTAT_COMUNE_RESIDENZA, 
						C2.COD_PROVINCIA AS ISTAT_PROVINCIA_RESIDENZA, 
						P2.SIGLA AS PROVINCIA_RESIDENZA
			FROM         IMPRESA AS I INNER JOIN
								  PERSONE_X_IMPRESE AS PXI ON I.ID_RAPPRLEGALE_ULTIMO = PXI.ID_PERSONE_X_IMPRESE INNER JOIN
								  PERSONA_FISICA AS PF ON PXI.ID_PERSONA = PF.ID_PERSONA INNER JOIN
								  COMUNI AS C1 ON PF.ID_COMUNE_NASCITA = C1.ID_COMUNE INNER JOIN
								  PROVINCE AS P1 ON C1.COD_PROVINCIA = P1.CODICE INNER JOIN
								  INDIRIZZARIO AS INDIRIZZARIO ON INDIRIZZARIO.ID_PERSONA = PF.ID_PERSONA INNER JOIN
								  INDIRIZZO AS INDIRIZZO ON INDIRIZZO.ID_INDIRIZZO = INDIRIZZARIO.ID_INDIRIZZO INNER JOIN
								  COMUNI AS C2 ON INDIRIZZO.ID_COMUNE = C2.ID_COMUNE INNER JOIN
								  PROVINCE AS P2 ON C2.COD_PROVINCIA = P2.CODICE 
			WHERE   (I.ID_IMPRESA = @IdImpresa) --AND (PXI.DATA_FINE IS NULL) AND (INDIRIZZARIO.DATA_FINE_VALIDITA IS NULL)
			ORDER BY PXI.ID_PERSONE_X_IMPRESE DESC, INDIRIZZARIO.ID_INDIRIZZARIO DESC
END
