CREATE PROCEDURE [dbo].[RptSezioneF]
	@IdImpresa INT 
AS
BEGIN

-- DECLARE @IdImpresa INT 
-- SET @IdImpresa = 2723

SELECT  NUM_UNITA_PRODUTTIVA,  NUMERO_APPEZZAMENTO, DENOMINAZIONE, SIGLA, PARTICELLA, dbo.MqAEttari(SUM(ISNULL(SUPERFICIE_BIOLOGICA, 0))) 
                      AS SUPERFICIE_BIOLOGICA, dbo.MqAEttari(SUM(ISNULL(SUPERFICIE_CONVERSIONE, 0))) AS SUPERFICIE_CONVERSIONE, 
				SUM(ISNULL(SUPERFICIE_BIOLOGICA, 0)) AS S_BIOLOGICA, 
						SUM(ISNULL(SUPERFICIE_CONVERSIONE, 0)) AS S_CONVER, SUM(ISNULL(SUPERFICIE_CONVENZIONALE, 0)) AS S_CONV, 
                      dbo.MqAEttari(SUM(ISNULL(SUPERFICIE_CONVENZIONALE, 0))) AS SUPERFICIE_CONVENZIONALE, dbo.MqAEttari
                          ((SELECT     SUM(ISNULL(SUPERFICIE_CONVERSIONE, 0)) + SUM(ISNULL(SUPERFICIE_CONVENZIONALE, 0)) 
                                                    + SUM(ISNULL(SUPERFICIE_BIOLOGICA, 0)) AS Expr1
                              FROM         vAPPEZZAMENTI
                              WHERE    (DATA_FINE_VALIDITA IS NULL) and (NUMERO_APPEZZAMENTO = A.NUMERO_APPEZZAMENTO) AND (ID_IMPRESA = @IdImpresa) AND FOGLIO_CATASTALE = A.FOGLIO_CATASTALE AND ISTAT_LUNGO = A.ISTAT_LUNGO)) AS TOTALE_SUPERFICIE, 
                      SUBSTRING(ISTAT_LUNGO, 1, 3) AS ISTAT_PROVINCIA, SUBSTRING(ISTAT_LUNGO, 3, 6) AS ISTAT_COMUNE, SEZIONE, FOGLIO_CATASTALE, 
                      SUBALTERNO, DATA_CESSAZIONE, ISNULL(ORIENTAMENTO_PRODUTTIVO, '') as ORIENTAMENTO_PRODUTTIVO, TIPO_COLTURA_ERBACEA, TIPO_COLTURA_ARBOREA, 
                      TIPO_COLTURA_PROMISCUA
FROM         vAPPEZZAMENTI AS A
WHERE     (ID_IMPRESA = @IdImpresa) AND (DATA_FINE_VALIDITA IS NULL)
GROUP BY NUM_UNITA_PRODUTTIVA, ID_APPEZZAMENTO, ID_IMPRESA, NUMERO_APPEZZAMENTO, DENOMINAZIONE, SIGLA, PARTICELLA, ISTAT_LUNGO, SEZIONE, 
                      FOGLIO_CATASTALE, SUBALTERNO, DATA_CESSAZIONE, ORIENTAMENTO_PRODUTTIVO, TIPO_COLTURA_ERBACEA, TIPO_COLTURA_ARBOREA, 
                      TIPO_COLTURA_PROMISCUA 
ORDER BY ID_APPEZZAMENTO

END
