CREATE PROCEDURE [dbo].[RptTotaleContributo]
(
	@IdProgetto INT, 
	@FASE BIT
)
AS 
BEGIN
-- UTILIZZATA SIA IN PRESENTAZIONE DOMANDA CHE IN AMMISSIBILITà (NEI REPORT) PER FAR VISUALIZZARE O MENO IL TRONCAMENTO DI CONTRIBUTO 

--DECLARE @IdProgetto INT 
--SET @IdProgetto = 64
DECLARE @CONTRIBUTO_FUNZIONE DECIMAL(18, 2)
DECLARE @CONTRIBUTO_TOTALE DECIMAL(18, 2)
DECLARE @ID_VARIANTE int 


SET @ID_VARIANTE =(SELECT MAX(ID_VARIANTE) FROM VARIANTI WHERE ID_PROGETTO=@IdProgetto)

SET @CONTRIBUTO_TOTALE = (SELECT SUM(ISNULL(CONTRIBUTO_RICHIESTO, 0)) 
							FROM PIANO_INVESTIMENTI INNER JOIN vPROGETTO P ON PIANO_INVESTIMENTI.ID_PROGETTO = P.ID_PROGETTO
							WHERE ((P.ID_PROG_INTEGRATO IS NULL AND P.ID_PROGETTO= @IdProgetto) OR P.ID_PROG_INTEGRATO=@IdProgetto)
							AND COD_TIPO_INVESTIMENTO = 1 AND
							((ORDINE_FASE IS NULL AND ID_INVESTIMENTO_ORIGINALE IS NULL AND ID_VARIANTE IS NULL) OR 
							(ORDINE_FASE<4 AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL) OR
							(ORDINE_FASE>=4  AND ((@ID_VARIANTE IS NULL AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL) OR
							 ID_VARIANTE=@ID_VARIANTE))))

SET @CONTRIBUTO_FUNZIONE = (SELECT DBO.calcoloContributoTotaleProgetto(@IdProgetto, @FASE, @ID_VARIANTE))
IF(@CONTRIBUTO_TOTALE > @CONTRIBUTO_FUNZIONE)

RETURN @CONTRIBUTO_FUNZIONE --as TOT_CONTRIBUTO_TRONCATO

ELSE 
RETURN @CONTRIBUTO_TOTALE --as TOTALE_CONTRIBUTO

END
