CREATE PROCEDURE [dbo].[RptVariantePremioPrecedente]

	@IdVariante int

AS
BEGIN

DECLARE @ID_DOMANDA INT
DECLARE @ID_VARIANTE INT 

SET @ID_DOMANDA =(SELECT ID_PROGETTO FROM VARIANTI WHERE ID_VARIANTE =@IdVariante)

IF((SELECT COUNT(*) FROM BANDO_TIPO_INVESTIMENTI WHERE COD_TIPO_INVESTIMENTO=3 AND ID_BANDO = (SELECT ID_BANDO FROM PROGETTO WHERE ID_PROGETTO = @ID_DOMANDA)) > 0)
BEGIN
	SET @ID_VARIANTE =(SELECT MAX(ID_VARIANTE) FROM VARIANTI WHERE ID_PROGETTO=@ID_DOMANDA AND APPROVATA=1 AND ID_VARIANTE<@IdVariante)
	SELECT DBO.calcoloPremioContoCapitale(@ID_DOMANDA, 1, @ID_VARIANTE) AS PREMIO
END 
END
