CREATE	PROCEDURE [dbo].[RptVariantePianoInvestimentiPrecedente]
(
@IdVariante int,
@COD_Tipo_Investimento int	
)
AS
BEGIN	

SET NOCOUNT ON;

--DECLARE @IdVariante int 
--DECLARE @COD_Tipo_Investimento int
--SET @IdVariante = 34
--SET @COD_Tipo_Investimento = 5


DECLARE @Count int

SET @Count = (SELECT COUNT(ID_INVESTIMENTO) 
				FROM vPIANO_INVESTIMENTI
				WHERE ID_INVESTIMENTO IN (SELECT ID_INVESTIMENTO_ORIGINALE 
										FROM  vPIANO_INVESTIMENTI 
										WHERE (ID_VARIANTE = @IdVariante)) AND COD_TIPO_INVESTIMENTO = @COD_Tipo_Investimento)

IF (@Count > 0)
BEGIN

	SELECT I.ID_INVESTIMENTO, I.ID_INVESTIMENTO_ORIGINALE,  I.DESCRIZIONE,
				   I.MISURA,
				   I.SETTORE_PRODUTTIVO,
				   I.COSTO_INVESTIMENTO,
				   I.SPESE_GENERALI,
				   I.CONTRIBUTO_RICHIESTO AS CONTRIBUTO_AMMISSIBILE,
				   I.QUOTA_CONTRIBUTO_RICHIESTO AS QUOTA_CONTRIBUTO_AMMISSIBILE,
				   I.ID_PRIORITA_SETTORIALE,
				   RATA_REINTEGRAZIONE = CASE MOBILE
											WHEN 1 THEN ((I.COSTO_INVESTIMENTO + I.SPESE_GENERALI)/10)
											WHEN 0 THEN ((I.COSTO_INVESTIMENTO + I.SPESE_GENERALI)/30)
											ELSE 0
											END, 
					(SELECT     VALORI_PRIORITA.CODICE
					FROM         PRIORITA_X_INVESTIMENTI INNER JOIN
										  VALORI_PRIORITA ON PRIORITA_X_INVESTIMENTI.ID_VALORE = VALORI_PRIORITA.ID_VALORE INNER JOIN
										  PIANO_INVESTIMENTI ON PRIORITA_X_INVESTIMENTI.ID_INVESTIMENTO = PIANO_INVESTIMENTI.ID_INVESTIMENTO INNER JOIN
										  PROGETTO ON PIANO_INVESTIMENTI.ID_PROGETTO = PROGETTO.ID_PROGETTO
					WHERE     (PRIORITA_X_INVESTIMENTI.ID_PRIORITA IN (37,88, 92, 93, 94, 102, 103,116) ) AND PRIORITA_X_INVESTIMENTI.ID_INVESTIMENTO = I.ID_INVESTIMENTO
					) AS RENDIMENTO_GLOBALE, 
					COD_VARIAZIONE, I.TASSO_ABBUONO
	FROM VPIANO_INVESTIMENTI AS I 
	WHERE ID_INVESTIMENTO IN (SELECT ID_INVESTIMENTO_ORIGINALE 
										FROM  vPIANO_INVESTIMENTI 
										WHERE (ID_VARIANTE = @IdVariante)) 
		AND COD_TIPO_INVESTIMENTO = @COD_Tipo_Investimento AND ISNULL(COD_VARIAZIONE,'x')!='A' -- non faccio più visualizzare quelli annullati
	ORDER BY  COD_TIPO_INVESTIMENTO,ID_INVESTIMENTO
END

ELSE SELECT NULL AS DESCRIZIONE,
            NULL AS CODICE_MISURA,
		    NULL AS SETTORE_PRODUTTIVO,
		    NULL AS COSTO_INVESTIMENTO,
		    NULL AS SPESE_GENERALI,
		    NULL AS CONTRIBUTO_AMMISSIBILE, 
			NULL AS QUOTA_CONTRIBUTO_AMMISSIBILE,
			NULL AS ID_PRIORITA_SETTORIALE,
		    NULL AS RATA_REINTEGRAZIONE,
			NULL AS TOTALE_CONTRIBUTO,
			NULL AS TOTALE_CONTRIBUTO_TRONCATO, 
			NULL AS RENDIMENTO_GLOBALE,
			NULL AS COD_VARIAZIONE, 
			NULL AS TASSO_ABBUONO	    
END
