CREATE PROCEDURE [dbo].[SpCalcoloSanzioneRitardoComunicazioniDomanda]
(
	@ID_SANZIONE INT,
	@DURATA DECIMAL(18,2) =NULL,
	@GRAVITA DECIMAL(18,2) =NULL,
	@ENTITA DECIMAL(18,2)=NULL,
	@MOTIVAZIONE NTEXT =NULL
)
AS

/*
DECLARE @ID_SANZIONE INT,@DURATA DECIMAL(18,2),@GRAVITA DECIMAL(18,2),@ENTITA DECIMAL(18,2)
SET @ID_SANZIONE=93
SET @DURATA =6
SET @ENTITA=50000
SET @GRAVITA=4*/

IF(@DURATA IS NULL OR @ENTITA IS NULL OR @GRAVITA IS NULL) RAISERROR('INPUT_ERROR',13,1)
ELSE BEGIN
	DECLARE @ID_DOMANDA_PAGAMENTO INT,@CONTRIBUTO_AMMESSO DECIMAL(18,2),@AMMONTARE_SANZIONE DECIMAL(18,5)
	SELECT @CONTRIBUTO_AMMESSO=SUM(CONTRIBUTO_AMMESSO) FROM PAGAMENTI_RICHIESTI P
	INNER JOIN PIANO_INVESTIMENTI I ON P.ID_INVESTIMENTO=I.ID_INVESTIMENTO
	INNER JOIN SANZIONI S ON P.ID_DOMANDA_PAGAMENTO=S.ID_DOMANDA_PAGAMENTO
	WHERE ID_SANZIONE=@ID_SANZIONE AND S.ID_INVESTIMENTO IS NULL  AND I.ID_PROGETTO=S.ID_PROGETTO
	IF(@CONTRIBUTO_AMMESSO IS NULL) RAISERROR('PAGAMENTO_NON_ISTRUITO_ERROR',13,1)  
	ELSE BEGIN
		IF(@CONTRIBUTO_AMMESSO=0) SET @AMMONTARE_SANZIONE=0
		ELSE BEGIN
			DECLARE @CLASSE_VIOLAZIONE_DURATA INT,@CLASSE_VIOLAZIONE_GRAVITA INT,@CLASSE_VIOLAZIONE_ENTITA INT,@QUOTA_RIDUZIONE INT,
				@SOMMA_VIOLAZIONI DECIMAL(10,5)
			--TUTTI I PARAMETRI SONO SELEZIONATI DALL'ISTRUTTORE
			SELECT @CLASSE_VIOLAZIONE_DURATA=CLASSE_VIOLAZIONE FROM TIPO_SANZIONI_PARAMETRI WHERE CODICE=@DURATA
			SELECT @CLASSE_VIOLAZIONE_GRAVITA=CLASSE_VIOLAZIONE FROM TIPO_SANZIONI_PARAMETRI WHERE CODICE=@GRAVITA
			SELECT @CLASSE_VIOLAZIONE_ENTITA=CLASSE_VIOLAZIONE FROM TIPO_SANZIONI_PARAMETRI WHERE CODICE=@ENTITA
			SET @SOMMA_VIOLAZIONI=(@CLASSE_VIOLAZIONE_DURATA+@CLASSE_VIOLAZIONE_GRAVITA+@CLASSE_VIOLAZIONE_ENTITA)/3
			IF(@SOMMA_VIOLAZIONI<3) SET @QUOTA_RIDUZIONE=3
			ELSE IF(@SOMMA_VIOLAZIONI<4) SET @QUOTA_RIDUZIONE=5
			ELSE SET @QUOTA_RIDUZIONE=7
			SET @AMMONTARE_SANZIONE=ROUND(@QUOTA_RIDUZIONE*@CONTRIBUTO_AMMESSO/100,2)
		END
		UPDATE SANZIONI SET DATA_APPLICAZIONE=GETDATE(),AMMONTARE=@AMMONTARE_SANZIONE,DURATA=@DURATA,GRAVITA=@GRAVITA,
			ENTITA=@ENTITA,MOTIVAZIONE=@MOTIVAZIONE WHERE ID_SANZIONE=@ID_SANZIONE
		SELECT * FROM VSANZIONI WHERE ID_SANZIONE=@ID_SANZIONE
	END
END
