

CREATE procedure  [dbo].[SpcalcoloImportoGarantitoFidejussione] 
(
	@ID_DOMANDA_PAGAMENTO INT
)
 as
BEGIN
	--DECLARE @ID_DOMANDA_PAGAMENTO INT; SET @ID_DOMANDA_PAGAMENTO=402

	DECLARE @AMMONTARE_POLIZZA DECIMAL(18,5),@AMMONTARE_RICHIESTO DECIMAL(18,5)
	SELECT @AMMONTARE_RICHIESTO=SUM(CASE WHEN CONTRIBUTO_NETTO>0 THEN CONTRIBUTO_NETTO ELSE 0 END),@AMMONTARE_POLIZZA =SUM(AMMONTARE_FIDEJUSSIONE)
		FROM DBO.calcoloImportoGarantitoFidejussioneMultimisura(@ID_DOMANDA_PAGAMENTO)
	
	SELECT ROUND(ISNULL(@AMMONTARE_POLIZZA,0),2) AMMONTARE_POLIZZA, ROUND(ISNULL(@AMMONTARE_RICHIESTO,0),2) AMMONTARE_RICHIESTO
END

