CREATE PROCEDURE [dbo].[SpCalcoloSanzioneVANonComunicata]
(
	@ID_SANZIONE INT,
	@DURATA DECIMAL(18,2)=NULL,
	@GRAVITA DECIMAL(18,2)=NULL,
	@ENTITA DECIMAL(18,2)=NULL
)
AS
	--DECLARE @ID_SANZIONE INT;SET @ID_SANZIONE=93

	DECLARE @PAGAMENTO_AMMESSO DECIMAL(18,2)	
	SELECT @PAGAMENTO_AMMESSO=CONTRIBUTO_AMMESSO FROM PAGAMENTI_RICHIESTI PR 
	INNER JOIN SANZIONI S ON PR.ID_DOMANDA_PAGAMENTO=S.ID_DOMANDA_PAGAMENTO AND PR.ID_INVESTIMENTO=S.ID_INVESTIMENTO
	WHERE S.ID_SANZIONE=@ID_SANZIONE	
	IF(@PAGAMENTO_AMMESSO IS NULL) RAISERROR('PAGAMENTO_NON_ISTRUITO_ERROR',13,1)
	ELSE BEGIN
		DECLARE @AMMONTARE DECIMAL(10,2)
		IF(@PAGAMENTO_AMMESSO>0) SET @AMMONTARE=ROUND(30*@PAGAMENTO_AMMESSO/100,2)
		ELSE SET @AMMONTARE=0		
		UPDATE SANZIONI SET DATA_APPLICAZIONE=GETDATE(),AMMONTARE=@AMMONTARE WHERE ID_SANZIONE=@ID_SANZIONE
		SELECT * FROM vSANZIONI WHERE ID_SANZIONE=@ID_SANZIONE
	END
