CREATE PROCEDURE [dbo].[SpCalcoloTotaliProgettoXDomandaPagamento]
(
	@ID_PROGETTO INT,
	@ID_DOMANDA_PAGAMENTO INT
)
AS
--CALCOLO I TOTALI DEL PROGETTO ALLA DATA DI INSERIMENTO DELLA DOMANDA DI PAGAMENTO
/*
DECLARE @ID_PROGETTO INT,@ID_DOMANDA_PAGAMENTO INT
SET @ID_PROGETTO =260 SET @ID_DOMANDA_PAGAMENTO =156*/

DECLARE @ID_VARIANTE INT,@DATA_MODIFICA DATETIME
SELECT @DATA_MODIFICA=DATA_MODIFICA FROM DOMANDA_DI_PAGAMENTO WHERE ID_DOMANDA_PAGAMENTO=@ID_DOMANDA_PAGAMENTO
SELECT @ID_VARIANTE=MAX(ID_VARIANTE) FROM VARIANTI WHERE ID_PROGETTO=@ID_PROGETTO AND APPROVATA=1 AND ANNULLATA=0
	AND DATA_MODIFICA<@DATA_MODIFICA

--CONTRIBUTO EROGATO
DECLARE @CONTRIBUTO_EROGATO DECIMAL(18,2)
SELECT @CONTRIBUTO_EROGATO=SUM(IMPORTO_AMMESSO) FROM DOMANDA_DI_PAGAMENTO_ESPORTAZIONE E
INNER JOIN DOMANDA_DI_PAGAMENTO D ON E.ID_DOMANDA_PAGAMENTO=D.ID_DOMANDA_PAGAMENTO
WHERE D.ID_DOMANDA_PAGAMENTO<@ID_DOMANDA_PAGAMENTO AND D.ID_PROGETTO=@ID_PROGETTO AND D.ANNULLATA=0 AND D.APPROVATA=1

--CALCOLO L'EVENTUALE SANZIONE
DECLARE @CONTRIBUTO_AMMISSIBILE DECIMAL(18,2),@IMPORTO_SANZIONE DECIMAL(18,2),@ANTICIPO_RECUPERATO DECIMAL(18,2),
	@CONTRIBUTO_AMMESSO DECIMAL(18,2)
SELECT @CONTRIBUTO_AMMISSIBILE=SUM(IMPORTO_AMMISSIBILE),@IMPORTO_SANZIONE=SUM(IMPORTO_SANZIONE),
	@ANTICIPO_RECUPERATO=SUM(IMPORTO_RECUPERO_ANTICIPO),@CONTRIBUTO_AMMESSO=SUM(IMPORTO_AMMESSO)
FROM DOMANDA_DI_PAGAMENTO_ESPORTAZIONE WHERE ID_DOMANDA_PAGAMENTO=@ID_DOMANDA_PAGAMENTO

SELECT DBO.calcoloCostoTotaleProgetto(@ID_PROGETTO,1,@ID_VARIANTE) AS COSTO_TOTALE,
	DBO.calcoloContributoTotaleProgetto(@ID_PROGETTO,1,@ID_VARIANTE)+ISNULL(DBO.calcoloPremioContoCapitale(@ID_PROGETTO,1,@ID_VARIANTE),0) 
	AS CONTRIBUTO_TOTALE,ISNULL(@CONTRIBUTO_EROGATO,0) AS CONTRIBUTO_EROGATO,ISNULL(@CONTRIBUTO_AMMISSIBILE,0) AS CONTRIBUTO_AMMISSIBILE,
	ISNULL(@IMPORTO_SANZIONE,0) AS IMPORTO_SANZIONE,ISNULL(@ANTICIPO_RECUPERATO,0) AS RECUPERO_ANTICIPO,
	ISNULL(@CONTRIBUTO_AMMESSO,0) AS CONTRIBUTO_AMMESSO
