CREATE  PROCEDURE [dbo].[SpCheckListFase]
(
	@COD_FASE varchar(1),
	@FLAG_TEMPLATE BIT
)
AS
	SELECT C.* FROM CHECK_LIST C
	INNER JOIN (SELECT MAX(ID_STEP )ID_STEP_max,FASE_PROCEDURALE  ,ID_CHECK_LIST FROM vCHECKLIST where COD_FASE =@COD_FASE 
		GROUP by ID_CHECK_LIST, FASE_PROCEDURALE  ) s on s.ID_CHECK_LIST=c.ID_CHECK_LIST
	ORDER BY C.DESCRIZIONE
