CREATE PROCEDURE [dbo].[SpControlloCambioBeneficiarioVariante]
(
	@ID_VARIANTE INT,
	@FASE_ISTRUTTORIA BIT =0
)
AS
/*
DECLARE @ID_VARIANTE INT, @FASE_ISTRUTTORIA BIT
SET @ID_VARIANTE=94
SET @FASE_ISTRUTTORIA =0*/

DECLARE @RETVAL INT,@CUAA_ENTRANTE VARCHAR(16),@ID_FASCICOLO_ENTRANTE INT,@MAX_ID_FASCICOLO INT
SET @RETVAL=0 /*VALORI DI RITORNO: 0=OK, 1=FASCICOLO NON APPARTENENTE AL CUAA, 2=VERSIONE NON AGGIORNATA,
				3=LOCALIZZAZIONE NON VALIDE O RIFERITE A FASCICOLI DIVERSI, 4=CONTRIBUTI NON RICALCOLATI(ISTRUTTORE)*/
-- TUTTO COMMENTATO IL SIGEF NON HA IL FASCICOLO
--SELECT @CUAA_ENTRANTE=CUAA_ENTRANTE,@ID_FASCICOLO_ENTRANTE=ID_FASCICOLO_ENTRANTE FROM VARIANTI WHERE ID_VARIANTE=@ID_VARIANTE

--IF(SELECT COUNT(ID_FASCICOLO) FROM FASCICOLO_AZIENDALE FA INNER JOIN IMPRESA I ON FA.ID_IMPRESA=I.ID_IMPRESA
--WHERE I.CUAA=@CUAA_ENTRANTE AND ID_FASCICOLO=@ID_FASCICOLO_ENTRANTE)=0 SET @RETVAL=1 --FASCICOLO NON APPARTENENTE AL CUAA
--ELSE BEGIN 
--	SELECT @MAX_ID_FASCICOLO=MAX(ID_FASCICOLO) FROM FASCICOLO_AZIENDALE FA INNER JOIN IMPRESA I ON FA.ID_IMPRESA=I.ID_IMPRESA
--	WHERE I.CUAA=@CUAA_ENTRANTE
--	--CONTROLLO CHE SIA LA VERSIONE AGGIORNATA DEL FASCICOLO, CIO' NON VALE IN ISTRUTTORIA VARIANTE
--	IF(@FASE_ISTRUTTORIA=0 AND @MAX_ID_FASCICOLO>@ID_FASCICOLO_ENTRANTE) SET @RETVAL=2
--	ELSE BEGIN
--		--CONTROLLO LOCALIZZAZIONE DEGLI INVESTIMENTI CON PARTICELLE
--		IF(@FASE_ISTRUTTORIA=0) BEGIN
--			IF(SELECT COUNT(*) FROM PIANO_INVESTIMENTI I INNER JOIN LOCALIZZAZIONE_INVESTIMENTO L ON I.ID_INVESTIMENTO=L.ID_INVESTIMENTO 
--			LEFT JOIN TERRITORIO T ON L.ID_CATASTO=T.ID_CATASTO AND T.ID_FASCICOLO=@ID_FASCICOLO_ENTRANTE
--			WHERE I.ID_VARIANTE=@ID_VARIANTE GROUP BY T.ID_FASCICOLO HAVING T.ID_FASCICOLO IS NULL)>0 SET @RETVAL=3
--		END
--		-- CONTROLLO CHE L'ISTRUTTORE ABBIA RICALCOLATO TUTTI I CONTRIBUTI
--		ELSE IF(SELECT COUNT(*) FROM PIANO_INVESTIMENTI WHERE ID_VARIANTE=@ID_VARIANTE AND AMMESSO IS NULL AND ISNULL(COD_VARIAZIONE,'X')!='A')>0 
--			SET @RETVAL=4	
--	END
--END
SELECT @RETVAL
