CREATE PROCEDURE [dbo].[SpControlloAntimafia]
(
	@ID_IMPRESA INT,
	@DATA DATETIME
)
AS
	--DECLARE @ID_IMPRESA INT,@DATA DATETIME
	--set @ID_IMPRESA = 494
	--set @DATA = GETDATE()
	DECLARE @RETURN_VALUE INT,@ID_ANTIMAFIA INT,@ESENZIONE_CERTIFICAZIONE BIT,@ESITO_CERTIFICATO_PREFETTIZIO BIT,
		@DATA_PROTOCOLLO_RICHIESTA DATETIME, @DATA_ACQUISIZIONE_ANTIMAFIA DATETIME
	SET @RETURN_VALUE=0

	SELECT TOP(1) @ID_ANTIMAFIA=ID,@ESENZIONE_CERTIFICAZIONE=ESENZIONE_CERTIFICAZIONE,
		@ESITO_CERTIFICATO_PREFETTIZIO=ESITO_CERTIFICATO_PREFETTIZIO,
		@DATA_PROTOCOLLO_RICHIESTA=DATA_PROTOCOLLO_RICHIESTA, 
		@DATA_ACQUISIZIONE_ANTIMAFIA = DATA_ACQUISIZIONE_ANTIMAFIA 
	FROM IMPRESA_CERTIFICAZIONE_ANTIMAFIA 
	WHERE ID_IMPRESA=@ID_IMPRESA AND DATA_INIZIO_VALIDITA<=@DATA AND DATA_FINE_VALIDITA>=@DATA 
	ORDER BY ID DESC
	-- ESENZIONE (DURATA 12 MESI)
	-- CERTIFICATO ANTIMAFIA (DURATA 6 MESI)
	
	/** controllo tolto in data 19/07/2012 **/
	-- COMUNICAZIONE AL BENEFICARIO MANCATO CERTIFICATO ANTIMAFIA (DURATA 3 MESI)
	/** DATA 17/10/2013 BISOGNA TENERE CONTO ANCHE DELLA DATA DI ACQUISIZIONE ANTIMAFIA QUANDO C'è L'ESITO DEL CERTIFICATO PREFETTIZIO**/
--SELECT @ID_ANTIMAFIA, @ESENZIONE_CERTIFICAZIONE, @ESITO_CERTIFICATO_PREFETTIZIO, @DATA
	IF @ID_ANTIMAFIA IS NOT NULL 
	BEGIN 
		IF (@ESENZIONE_CERTIFICAZIONE=1) SET @RETURN_VALUE=1
		ELSE IF (@ESITO_CERTIFICATO_PREFETTIZIO=1 AND @DATA_ACQUISIZIONE_ANTIMAFIA IS NOT NULL) SET @RETURN_VALUE = 1 
		ELSE BEGIN
			--AGGIORNATO IN DATA 08/10/2014 - SI RITORNA AI 45 GIORNI
			--AGGIORNATO IN DATA 04/11/2014 - FINO AL 31/12 SARà PER 15 GIORNI
			--AGGIORNATA IN DATA 26/11/2014 - FINO AL 31/12 SARà DI 0 GIORNI - DAL 01/01/2015 SARà DI 30 GIORNI
			--AGGIORNATA IN DATA 22/12/2015 - FINO AL 31/12 SARà DI 0 GIORNI - DAL 01/01/2016 SARà DI 30 GIORNI
			IF(GETDATE()>= '2015-12-22' AND GETDATE()<= '2015-12-31') BEGIN 
				IF (@DATA_PROTOCOLLO_RICHIESTA IS NOT NULL AND DATEADD(DAY, 0, @DATA_PROTOCOLLO_RICHIESTA) <= GETDATE()) SET @RETURN_VALUE=1
			END
			ELSE IF (@DATA_PROTOCOLLO_RICHIESTA IS NOT NULL AND DATEADD(DAY, 30, @DATA_PROTOCOLLO_RICHIESTA) <= GETDATE()) SET @RETURN_VALUE=1
		END
	END
	SELECT @RETURN_VALUE
RETURN @RETURN_VALUE
