
CREATE PROCEDURE [dbo].[SpEstraiCampioneDomandeXControlliLocoRischioSub]
(
	@ID_LOTTO INT,
	@SOGLIA_ESTRAZIONE DECIMAL(18,2),
	@CLASSE CHAR(1) -- CLASSE DI RISCHIO
)
AS

	WHILE @SOGLIA_ESTRAZIONE>0 BEGIN
		DECLARE @NR_DOMANDE INT,@INDICE_CASUALE INT,@ID_DOMANDA INT,@CONTRIBUTO_DOMANDA DECIMAL(18,2),@COUNTER INT=1
		SELECT @NR_DOMANDE=COUNT(*) FROM CONTROLLI_DOMANDE_PAGAMENTO_ESTRAZIONE_TEMP WHERE ID_LOTTO=@ID_LOTTO
			AND CLASSE_DI_RISCHIO=@CLASSE AND ESTRATTA=0	
		SELECT @INDICE_CASUALE=FLOOR(RAND()*(@NR_DOMANDE+1))
		
		DECLARE DOMANDE CURSOR FOR 
			SELECT ID_DOMANDA_PAGAMENTO,CONTRIBUTO_RICHIESTO FROM CONTROLLI_DOMANDE_PAGAMENTO_ESTRAZIONE_TEMP
			WHERE ID_LOTTO=@ID_LOTTO AND CLASSE_DI_RISCHIO=@CLASSE AND ESTRATTA=0
		OPEN DOMANDE
		FETCH NEXT FROM DOMANDE INTO @ID_DOMANDA,@CONTRIBUTO_DOMANDA
		WHILE @@FETCH_STATUS=0 BEGIN
			IF @COUNTER=@INDICE_CASUALE BEGIN
				UPDATE CONTROLLI_DOMANDE_PAGAMENTO_ESTRAZIONE_TEMP SET ESTRATTA=1,TIPO_ESTRAZIONE='R'
				WHERE ID_LOTTO=@ID_LOTTO AND ID_DOMANDA_PAGAMENTO=@ID_DOMANDA
				SET @SOGLIA_ESTRAZIONE=@SOGLIA_ESTRAZIONE-@CONTRIBUTO_DOMANDA
				BREAK
			END
			SET @COUNTER=@COUNTER+1
			FETCH NEXT FROM DOMANDE INTO @ID_DOMANDA,@CONTRIBUTO_DOMANDA
		END
		CLOSE DOMANDE
		DEALLOCATE DOMANDE
	END