

CREATE PROCEDURE [dbo].[SpEstraiCampioneDomandeXRevisione]
(
	@ID_BANDO INT,
	@REVISORE INT,
	@PROVINCIA CHAR(2)
)
AS
/*
DECLARE @ID_BANDO INT,@REVISORE VARCHAR(16),@PROVINCIA CHAR(2)
SET @ID_BANDO=136
SET @REVISORE='STRNDR56B07L182G'
SET @PROVINCIA='AN'*/

DECLARE @REVISIONE_T TABLE (ID_PROGETTO INT,OPERATORE INT,COD_STATO CHAR(1),ORDINE_FASE INT,COSTO_TOTALE_PROGETTO DECIMAL(18,2),
	ISTRUTTORE INT,SELEZIONATA_X_REVISIONE BIT)
INSERT INTO @REVISIONE_T
SELECT P.ID_PROGETTO,P.OPERATORE,COD_STATO,ORDINE_FASE,NULL,C.ID_UTENTE,0 FROM VPROGETTO P 
LEFT JOIN COLLABORATORI_X_BANDO C ON P.ID_PROGETTO=C.ID_PROGETTO AND C.ATTIVO=1
WHERE P.ID_BANDO=@ID_BANDO AND PROVINCIA_DI_PRESENTAZIONE=@PROVINCIA AND COD_STATO NOT IN ('P','Q','R')

-- CONTROLLO CHE SIANO TUTTE ASSEGNATE AD UN ISTRUTTORE
IF (SELECT COUNT(*) FROM @REVISIONE_T WHERE ISTRUTTORE IS NULL)>0 SELECT -2
-- CONTROLLO CHE SIANO TUTTE NELLA FASE DI AMMISSIBILITA
ELSE IF (SELECT COUNT(*) FROM @REVISIONE_T WHERE ORDINE_FASE<>3)>0 SELECT -1
ELSE BEGIN
	-- BANDO MACROFILIERA: MODIFICA DEL 04/11/2011
	-- BANDO FILIERA LOCALE : MODIFICA DEL 05/06/2012
	-- LA REVISIONE VIENE UTILIZZATA PER L'ISTRUTTORIA COLLEGIALE CHE SARA' FATTA SU TUTTE LE DOMANDE DI AIUTO
	IF @ID_BANDO IN (124,126,127,128,129,131,150,153,166 /*144 (PIF PER ORA NON LO INCLUDO)*/) BEGIN
	 
		UPDATE P SET SELEZIONATA_X_REVISIONE=1 FROM PROGETTO P
		INNER JOIN @REVISIONE_T T ON P.ID_PROGETTO=T.ID_PROGETTO-- WHERE OPERATORE!=@REVISORE
		SELECT @@ROWCOUNT
	END
	ELSE BEGIN
		--BANDO LEGGE 56 PRIMA SCADENZA 
		-- LA REVISIONE VIENE UTILIZZATA PER AGGIORNARE IL REQUISITO SOGGETTIVO DELLA BANCA
		IF @ID_BANDO IN (186, 200)  BEGIN
		UPDATE P SET SELEZIONATA_X_REVISIONE=1 FROM PROGETTO P
		INNER JOIN @REVISIONE_T T ON P.ID_PROGETTO=T.ID_PROGETTO-- WHERE OPERATORE!=@REVISORE
		WHERE P.ID_PROGETTO IN (8200,8339,8308,8269,8159,8224,8157,8302,8109,8204,8219,8294,8146,8268,8283,
								8323,8161,8182,8163,8172,8154,8221,8175,8241,8120,8132,8167,8207,8220,8152,
								8114,8179,8142,8144,8196,8168,8124,8139,8186,8153,8145,8210,8306,8195,8237,
								8183,8273,8127,8271,8280,8297)
		SELECT @@ROWCOUNT
	 
	    END
		ELSE BEGIN
		
		-- AGGIORNO LA TABELLA TEMPORANEA CON IL COSTO DEL PROGETTO
		UPDATE @REVISIONE_T SET COSTO_TOTALE_PROGETTO=dbo.calcoloCostoTotaleProgetto(ID_PROGETTO,1,NULL) WHERE OPERATORE!=@REVISORE
 
		DECLARE @NUMERO_DOMANDE DECIMAL (10,5),@CAMPIONE DECIMAL (10,5)
		SELECT @NUMERO_DOMANDE=COUNT(ID_PROGETTO) FROM @REVISIONE_T WHERE COSTO_TOTALE_PROGETTO<700000
		SET @CAMPIONE=@NUMERO_DOMANDE*5/100
		IF @CAMPIONE>CAST(@CAMPIONE AS INT) SET @CAMPIONE=CAST(@CAMPIONE+1 AS INT)

		IF @NUMERO_DOMANDE>0 BEGIN
			DECLARE @COUNTER INT,@RAND_ID INT,@ID_PROGETTO_ESTRATTTO INT
			IF @CAMPIONE<2 SET @CAMPIONE=2			
			SET @COUNTER=1
			WHILE @COUNTER<@CAMPIONE+1 BEGIN
				SET @RAND_ID=RAND()*@NUMERO_DOMANDE+1				
				SELECT @ID_PROGETTO_ESTRATTTO=MAX(ID_PROGETTO) FROM @REVISIONE_T WHERE ID_PROGETTO IN 
					(SELECT TOP(@RAND_ID) ID_PROGETTO FROM @REVISIONE_T WHERE SELEZIONATA_X_REVISIONE=0)
				UPDATE @REVISIONE_T SET SELEZIONATA_X_REVISIONE=1 WHERE ID_PROGETTO=@ID_PROGETTO_ESTRATTTO
				SET @COUNTER=@COUNTER+1
			END
						
			UPDATE P SET SELEZIONATA_X_REVISIONE=1 FROM PROGETTO P
			INNER JOIN @REVISIONE_T T ON P.ID_PROGETTO=T.ID_PROGETTO WHERE T.SELEZIONATA_X_REVISIONE=1
			SELECT @@ROWCOUNT
		END
		ELSE SELECT 0
		END
	END
END
