CREATE PROCEDURE [dbo].[SpExecQuerySqlInvestimento]
(
	@NOME NVARCHAR(3000),
	@ID_PROGETTO INT,
	@ID_DOMANDA_PAGAMENTO INT=NULL,
	@FASE_ISTRUTTORIA bit,
	@ID_INVESTIMENTO INT
)
AS
	DECLARE @TESTO_QUERY NVARCHAR(MAX)
	IF LEN(@NOME)<101
		SELECT @TESTO_QUERY=TESTO FROM zQUERY_SQL WHERE NOME=@NOME
	IF @TESTO_QUERY IS NOT NULL 
		EXEC sp_executesql @TESTO_QUERY,N'@IdProgetto INT,@IdDomandaPagamento INT,@fase_istruttoria bit,@IdInvestimento INT',@ID_PROGETTO,@ID_DOMANDA_PAGAMENTO,@FASE_ISTRUTTORIA, @ID_INVESTIMENTO
	ELSE 
		EXEC sp_executesql @NOME,N'@IdProgetto INT,@IdDomandaPagamento INT,@fase_istruttoria bit,@IdInvestimento INT',@ID_PROGETTO,@ID_DOMANDA_PAGAMENTO,@FASE_ISTRUTTORIA , @ID_INVESTIMENTO
