CREATE PROCEDURE [dbo].[SpGetTipoPagamentoByIdBando] 
	@IDBANDO INT
AS
	SELECT T.*,B.ID_BANDO,QUOTA_MAX,QUOTA_MAX,QUOTA_MIN,IMPORTO_MAX,IMPORTO_MIN,FASE,ORDINE,NUMERO,COD_TIPO_POLIZZA,TIPO_POLIZZA FROM TIPO_DOMANDA_PAGAMENTO T 
        LEFT JOIN VBANDO_TIPO_PAGAMENTO B ON T.COD_TIPO=B.COD_TIPO AND B.ID_BANDO=@IDBANDO
