CREATE PROCEDURE [dbo].[SpGetCollabBandoDatiProgettoImpresa]
(
	@ID_BANDO INT=NULL,
	@ID_PROGETTO INT=NULL,
	@ID_UTENTE INT=NULL,
	@PROVINCIA CHAR(2)=NULL,
	@COD_STATO CHAR(1)=NULL
)
AS

	SELECT C.*,I.ID_IMPRESA,I.CUAA,I.CODICE_FISCALE,I.RAGIONE_SOCIALE,N.COMUNE,N.SIGLA,N.CAP,P.COD_STATO,P.STATO,
		P.REVISIONE,P.SEGNATURA_RI,P.ID_PROG_INTEGRATO,P.PROVINCIA_DI_PRESENTAZIONE,S.DATA AS DATA_RILASCIO
	FROM vCOLLABORATORI_X_BANDO C INNER JOIN vPROGETTO P ON C.ID_PROGETTO=P.ID_PROGETTO
	LEFT JOIN PROGETTO_STORICO S ON P.ID_PROGETTO=S.ID_PROGETTO AND S.COD_STATO='L'
	INNER JOIN vIMPRESA I ON P.ID_IMPRESA=I.ID_IMPRESA INNER JOIN vINDIRIZZARIO N ON I.ID_SEDELEGALE_ULTIMO=N.ID_INDIRIZZARIO
	WHERE C.ATTIVO=1 AND (@ID_BANDO IS NULL OR C.ID_BANDO=@ID_BANDO) AND (@ID_PROGETTO IS NULL OR C.ID_PROGETTO=@ID_PROGETTO)
		AND (@ID_UTENTE IS NULL OR C.ID_UTENTE=@ID_UTENTE) AND (@PROVINCIA IS NULL OR C.PROVINCIA=@PROVINCIA)
		AND (@COD_STATO IS NULL OR P.COD_STATO=@COD_STATO)
	ORDER BY C.ID_PROGETTO
