-- =============================================

CREATE PROCEDURE [dbo].[SpGetStoricoInvestimento] 
(
	@ID_INVESTIMENTO_ORIGINALE INT
)
AS
/*
DECLARE @ID_INVESTIMENTO_ORIGINALE INT
SET @ID_INVESTIMENTO_ORIGINALE=1280*/

DECLARE @TABELLA TABLE (
	[ID_INVESTIMENTO] [int] NOT NULL,
	[ID_PROGETTO] [int] NULL,
	[ID_PROGRAMMAZIONE] [int] NULL,
	[DESCRIZIONE] [varchar](2000) NULL,
	[DATA_VARIAZIONE] [datetime] NULL,
	[OPERATORE_VARIAZIONE] [varchar](16) NULL,
	[COD_TIPO_INVESTIMENTO] [int] NULL,
	[COD_STP] [varchar](10) NULL,
	[ID_UNITA_MISURA] [int] NULL,
	[QUANTITA] [decimal](10, 2) NULL,
	[COSTO_INVESTIMENTO] [decimal](15, 2) NULL,
	[SPESE_GENERALI] [decimal](15, 2) NULL,
	[CONTRIBUTO_RICHIESTO] [decimal](15, 2) NULL,
	[QUOTA_CONTRIBUTO_RICHIESTO] [decimal](10, 2) NULL,
	[TASSO_ABBUONO] [decimal](10, 2) NULL,
	[ID_SETTORE_PRODUTTIVO] [int] NULL,
	[ID_PRIORITA_SETTORIALE] [int] NULL,
	[ID_OBIETTIVO_MISURA] [int] NULL,
	[ID_CODIFICA_INVESTIMENTO] [int] NULL,
	[ID_DETTAGLIO_INVESTIMENTO] [int] NULL,
	[ID_SPECIFICA_INVESTIMENTO] [int] NULL,
	[AMMESSO] [bit] NULL,
	[ISTRUTTORE] [varchar](16) NULL,
	[ID_INVESTIMENTO_ORIGINALE] [int] NULL,
	[DATA_VALUTAZIONE] [datetime] NULL,
	[VALUTAZIONE_INVESTIMENTO] [ntext] NULL,
	[ID_VARIANTE] [int] NULL,
	[COD_VARIAZIONE] [char](1) NULL)

WHILE(@ID_INVESTIMENTO_ORIGINALE IS NOT NULL) BEGIN
	INSERT INTO @TABELLA
	SELECT ID_INVESTIMENTO,ID_PROGETTO,ID_PROGRAMMAZIONE,DESCRIZIONE,DATA_VARIAZIONE,OPERATORE_VARIAZIONE,COD_TIPO_INVESTIMENTO,COD_STP,
	ID_UNITA_MISURA,QUANTITA,COSTO_INVESTIMENTO,SPESE_GENERALI,CONTRIBUTO_RICHIESTO,QUOTA_CONTRIBUTO_RICHIESTO,TASSO_ABBUONO,ID_SETTORE_PRODUTTIVO,
	ID_PRIORITA_SETTORIALE,ID_OBIETTIVO_MISURA,ID_CODIFICA_INVESTIMENTO,ID_DETTAGLIO_INVESTIMENTO,ID_SPECIFICA_INVESTIMENTO,AMMESSO,ISTRUTTORE,
	ID_INVESTIMENTO_ORIGINALE,DATA_VALUTAZIONE,VALUTAZIONE_INVESTIMENTO,ID_VARIANTE,COD_VARIAZIONE 
	FROM PIANO_INVESTIMENTI WHERE ID_INVESTIMENTO=@ID_INVESTIMENTO_ORIGINALE
	SELECT @ID_INVESTIMENTO_ORIGINALE=ID_INVESTIMENTO_ORIGINALE FROM PIANO_INVESTIMENTI WHERE ID_INVESTIMENTO=@ID_INVESTIMENTO_ORIGINALE
END
SELECT * FROM @TABELLA
