CREATE PROCEDURE [dbo].[SpGetDocumentiPubblici]
(
	@DESCRIZIONE VARCHAR(50)=NULL
)
AS
	SELECT * FROM DOCUMENTI WHERE DATA_FINE_VALIDITA>=GETDATE()	AND 
		(@DESCRIZIONE IS NULL OR (TITOLO LIKE '%'+@DESCRIZIONE+'%' OR DESCRIZIONE LIKE '%'+@DESCRIZIONE+'%'))
		ORDER BY DATA_MODIFICA DESC