CREATE PROCEDURE [dbo].[SpGetIstruttoriaDomandePagamento]
(
	@ID_BANDO INT,
	@ID_ISTRUTTORE INT=NULL,
	@ID_PROGETTO INT=NULL,
	@COD_STATO CHAR(1)='F',
	@PROVINCIA CHAR(2)=NULL,
	@CUAA VARCHAR(16)=NULL,
	@RAGIONE_SOCIALE VARCHAR(50)=NULL,
	@CERCA_PAGAMENTI BIT,
	@CERCA_VARIANTI BIT,
	@CERCA_ADEGTECNICI BIT,
	@ISTRUTTORIA_CONCLUSA BIT,
	@ISTRUTTORIA_IN_CORSO BIT,
	@ANNULLATI BIT
)
AS
	SELECT DISTINCT P.* FROM vISTRUTTORIA_DOMANDE P
	LEFT JOIN DOMANDA_DI_PAGAMENTO D ON P.ID_PROGETTO=D.ID_PROGETTO
	LEFT JOIN VARIANTI V ON P.ID_PROGETTO=V.ID_PROGETTO
	WHERE ID_BANDO=@ID_BANDO AND FILTRO_STATO_ISTRUTTORIA=@COD_STATO 
	AND (@ID_PROGETTO IS NULL OR P.ID_PROGETTO=@ID_PROGETTO) AND (@ID_ISTRUTTORE IS NULL OR ID_ISTRUTTORE=@ID_ISTRUTTORE) 
	AND (@PROVINCIA IS NULL OR PROVINCIA_ASSEGNAZIONE=@PROVINCIA)
	AND (@CUAA IS NULL OR (CUAA=@CUAA OR PARTITA_IVA=@CUAA)) AND (@RAGIONE_SOCIALE IS NULL OR RAGIONE_SOCIALE LIKE '%'+@RAGIONE_SOCIALE+'%')
	AND (@CERCA_PAGAMENTI=0 OR (@CERCA_PAGAMENTI=1 AND D.ID_DOMANDA_PAGAMENTO IS NOT NULL AND D.SEGNATURA IS NOT NULL
		AND (@ANNULLATI=0 OR (@ANNULLATI=1 AND D.ANNULLATA=1)) AND (@ISTRUTTORIA_CONCLUSA=0 OR (@ISTRUTTORIA_CONCLUSA=1 AND D.APPROVATA IS NOT NULL))
		AND (@ISTRUTTORIA_IN_CORSO=0 OR (@ISTRUTTORIA_IN_CORSO=1 AND D.APPROVATA IS NULL AND D.ANNULLATA=0))))
	AND ((@CERCA_VARIANTI=0 AND @CERCA_ADEGTECNICI=0) OR (V.ID_VARIANTE IS NOT NULL AND V.SEGNATURA IS NOT NULL
		AND ((@CERCA_VARIANTI=1 AND V.COD_TIPO='VA') OR (@CERCA_ADEGTECNICI=1 AND V.COD_TIPO='AT'))
		AND (@ANNULLATI=0 OR (@ANNULLATI=1 AND V.ANNULLATA=1)) AND (@ISTRUTTORIA_CONCLUSA=0 OR (@ISTRUTTORIA_CONCLUSA=1 AND V.APPROVATA IS NOT NULL))
		AND (@ISTRUTTORIA_IN_CORSO=0 OR (@ISTRUTTORIA_IN_CORSO=1 AND V.APPROVATA IS NULL AND V.ANNULLATA=0))))
	ORDER BY ID_PROGETTO
