
CREATE PROCEDURE [dbo].[SpGetPecSuap]
(
	@ID_COMUNE INT
)
AS
	SELECT SPORTELLO, PEC
	FROM SUAP S INNER JOIN COMUNI C ON S.COD_BELFIORE = C.COD_BELFIORE
	WHERE C.ID_COMUNE = @ID_COMUNE AND S.ATTIVO = 1 AND C.ATTIVO = 1 
