CREATE PROCEDURE [dbo].[SpGetDomandeInRiesame]
(
	@ID_BANDO INT
)
AS
	SELECT C.*,PS.DATA AS DATA_DOCUMENTO,PS.SEGNATURA AS SEGNATURA_DOCUMENTO,PS.NOMINATIVO AS OPERATORE_DOCUMENTO,
		S.COD_STATO AS COD_STATO_RIESAMINATO,S.STATO AS STATO_RIESAMINATO 
	FROM vPROGETTO_SEGNATURE PS INNER JOIN vCOLLABORATORI_X_BANDO C ON PS.ID_PROGETTO=C.ID_PROGETTO AND C.ATTIVO=1
    LEFT OUTER JOIN vPROGETTO_STORICO S ON PS.ID_PROGETTO=S.ID_PROGETTO AND S.COD_STATO IN ('A','B') AND S.RIESAME=1
    WHERE PS.COD_TIPO='RID' AND ID_BANDO=@ID_BANDO
