CREATE PROCEDURE [dbo].[SpGetDecretiVarianti]
(
	@ID_BANDO INT,
	@ID_PROGETTO INT=NULL,
	@APPROVATA BIT=NULL,
	@NASCONDI_DECRETI_REGISTRATI BIT=0
)
AS
	--DECLARE @ID_BANDO INT=131,@ID_PROGETTO INT,@APPROVATA BIT,@NASCONDI_DECRETI_REGISTRATI BIT=0

	SELECT V.ID_VARIANTE,v.COD_TIPO,V.ID_PROGETTO,V.DESCRIZIONE,APPROVATA,V.SEGNATURA,V.SEGNATURA_APPROVAZIONE,V.ID_ATTO_APPROVAZIONE,
		A.COD_DEFINIZIONE,A.NUMERO AS NUMERO_DECRETO,A.DATA AS DATA_DECRETO,A.AW_DOCNUMBER,A.AW_DOCNUMBER_NUOVO
	FROM VARIANTI V INNER JOIN PROGETTO P ON V.ID_PROGETTO=P.ID_PROGETTO
	LEFT JOIN ATTI A ON V.ID_ATTO_APPROVAZIONE=A.ID_ATTO
	WHERE V.COD_TIPO='VA' AND P.ID_BANDO=@ID_BANDO AND SEGNATURA_APPROVAZIONE IS NOT NULL AND ANNULLATA=0
		AND (@ID_PROGETTO IS NULL OR P.ID_PROGETTO=@ID_PROGETTO) AND (@APPROVATA IS NULL OR APPROVATA=@APPROVATA)
		AND (@NASCONDI_DECRETI_REGISTRATI=0 OR (@NASCONDI_DECRETI_REGISTRATI=1 AND V.ID_ATTO_APPROVAZIONE IS NULL))    
	ORDER BY ID_PROGETTO
