

CREATE PROCEDURE [dbo].[SpGetSociImpresa]
(
	@ID_IMPRESA INT,
	@CUAA VARCHAR(16) = NULL,
	@CODICE_FISCALE VARCHAR(16) = NULL,
	@RAGIONE_SOCIALE NVARCHAR(max) = NULL,
	@COD_TIPO_SOCIO CHAR(1) = null
)
AS

BEGIN
	SELECT S.* ,F1.BARCODE AS BARCODE1, F1.DATA_SCHEDA_VALIDAZIONE AS DATA_SCHEDA_VALIDAZIONE1, 
				F1.DATA_DOWNLOAD AS DATA_DOWNLOAD1, F1.DATA_STORICIZZAZIONE AS DATA_STORICIZZAZIONE1,
			    F2.BARCODE AS BARCODE2, F2.DATA_SCHEDA_VALIDAZIONE AS DATA_SCHEDA_VALIDAZIONE2, 
			    F2.DATA_DOWNLOAD AS DATA_DOWNLOAD2, F2.DATA_STORICIZZAZIONE AS DATA_STORICIZZAZIONE2
	FROM vIMPRESA_SOCI S 
	LEFT JOIN (
	    SELECT ID_IMPRESA,MAX(ID_FASCICOLO) AS MAX_ID1 FROM FASCICOLO_AZIENDALE GROUP BY ID_IMPRESA
	) Q1 ON S.ID_SOCIO=Q1.ID_IMPRESA
	LEFT JOIN FASCICOLO_AZIENDALE F1 ON Q1.MAX_ID1=F1.ID_FASCICOLO
	LEFT JOIN (
	    SELECT ID_IMPRESA,MAX(ID_FASCICOLO) AS MAX_ID2 FROM FASCICOLO_AZIENDALE WHERE DATA_STORICIZZAZIONE IS NOT NULL GROUP BY ID_IMPRESA
	) Q2 ON S.ID_SOCIO=Q2.ID_IMPRESA
	LEFT JOIN FASCICOLO_AZIENDALE F2 ON Q2.MAX_ID2=F2.ID_FASCICOLO
	WHERE S.ID_IMPRESA=@ID_IMPRESA AND ((@COD_TIPO_SOCIO IS NULL) OR(@COD_TIPO_SOCIO IS NOT NULL AND S.COD_TIPO_SOCIO = @COD_TIPO_SOCIO ))
	AND (@CUAA IS NULL OR S.CUAA=@CUAA) 
	AND (@CODICE_FISCALE IS NULL OR S.CODICE_FISCALE=@CODICE_FISCALE)
	AND (@RAGIONE_SOCIALE IS NULL OR S.RAGIONE_SOCIALE LIKE '%'+@RAGIONE_SOCIALE+'%') 
	
	ORDER BY ATTIVO DESC, S.RAGIONE_SOCIALE

END

