
CREATE PROCEDURE [dbo].[SpGetGraduatoriaProgettiDettaglioByPriorita]
(
	@ID_PROGETTO INT
)
AS
	SELECT R.ID_PRIORITA,P.ID_PROGETTO,PUNTEGGIO,DATA_VALUTAZIONE,OPERATORE,MODIFICA_MANUALE,R.DESCRIZIONE,R.COD_LIVELLO,
		R.PLURI_VALORE,R.EVAL,R.FLAG_MANUALE,R.INPUT_NUMERICO,R.MISURA
	FROM PROGETTO P INNER JOIN BANDO B ON P.ID_BANDO=B.ID_BANDO
	INNER JOIN SCHEDA_VALUTAZIONE V ON B.ID_SCHEDA_VALUTAZIONE = V.ID_SCHEDA_VALUTAZIONE
	INNER JOIN SCHEDA_X_PRIORITA SP ON V.ID_SCHEDA_VALUTAZIONE = SP.ID_SCHEDA_VALUTAZIONE AND ISNULL(SP.PESO,0)> 0 AND SP.SELEZIONABILE = 0
	INNER JOIN PRIORITA R ON SP.ID_PRIORITA=R.ID_PRIORITA
	LEFT OUTER JOIN GRADUATORIA_PROGETTI_DETTAGLIO G ON SP.ID_PRIORITA = G.ID_PRIORITA AND P.ID_PROGETTO=G.ID_PROGETTO
	WHERE P.ID_PROGETTO=@ID_PROGETTO

