CREATE PROCEDURE [dbo].[SpGetImpresaAbilitataById]
(
	@ID_IMPRESA INT,
	@COD_ENTE VARCHAR(10)=NULL,
	@CF_UTENTE VARCHAR(16)=NULL
)
AS
	DECLARE @DATA DATETIME
	SET @DATA=GETDATE()
	-- REGIONALI, AMMINISTRAZIONE	
	IF @COD_ENTE IN ('%','RM','RM_DEC','AdC') 
		SELECT * FROM vIMPRESA WHERE ID_IMPRESA=@ID_IMPRESA
	-- CAA
	ELSE IF @COD_ENTE IS NOT NULL BEGIN
		SELECT I.* FROM vIMPRESA I INNER JOIN CF_ABILITATI_X_UTENTE A ON I.CUAA=A.CF_ABILITATO OR I.CODICE_FISCALE=A.CF_ABILITATO
		WHERE I.ID_IMPRESA=@ID_IMPRESA AND A.COD_ENTE=@COD_ENTE AND A.DATA_INIZIO_VALIDITA<=@DATA AND A.DATA_FINE_VALIDITA>@DATA		
	END
	-- AGRONOMI, RAPPRESENTANTI LEGALI IMPRESA
	ELSE BEGIN
		SELECT I.* FROM vIMPRESA I INNER JOIN CF_ABILITATI_X_UTENTE A ON I.CUAA=A.CF_ABILITATO OR I.CODICE_FISCALE=A.CF_ABILITATO
		WHERE I.ID_IMPRESA=@ID_IMPRESA AND A.CF_UTENTE=@CF_UTENTE AND A.DATA_INIZIO_VALIDITA<=@DATA AND A.DATA_FINE_VALIDITA>@DATA
		UNION ALL
		SELECT I.* FROM vIMPRESA I INNER JOIN vPERSONE_X_IMPRESE P ON I.ID_RAPPRLEGALE_ULTIMO=P.ID_PERSONE_X_IMPRESE
		WHERE I.ID_IMPRESA=@ID_IMPRESA AND P.CODICE_FISCALE=@CF_UTENTE		
    END
