CREATE PROCEDURE [dbo].[SpGetImpresaSenzaStoricoByCuaa]
(
	@CUAA VARCHAR(16)
)
AS
	--DECLARE @ID_IMPRESA INT,@CUAA VARCHAR(16),@RAGIONE_SOCIALE VARCHAR(100),@COD_ENTE VARCHAR(10),@CF_UTENTE VARCHAR(16)
	--SET @CUAA='00351040423'

SELECT 
	I.*,
	S.ID_STORICO_IMPRESA,
	S.DATA_INIZIO_VALIDITA,
	S.DATA_FINE_VALIDITA,
	S.RAGIONE_SOCIALE,
	S.CODICE_INPS,
	S.COD_FORMA_GIURIDICA,
	S.ID_DIMENSIONE,
	S.REGISTRO_IMPRESE_NUMERO,
	S.REA_NUMERO,
	S.REA_ANNO,
	S.ATTIVA,
	S.DATA_CESSAZIONE,
	S.SEGNATURA_CESSAZIONE,
	S.COD_TIPO_CESSAZIONE,
	NULL AS DIMENSIONE_IMPRESA,
	NULL AS FORMA_GIURIDICA,
	NULL AS FOGLIA,
	NULL AS COD_CLASSIFICAZIONE_UMA,
	S.COD_ATECO2007
FROM IMPRESA I 
LEFT JOIN 
IMPRESA_STORICO S ON 
I.ID_IMPRESA=S.ID_IMPRESA 
AND 
S.DATA_FINE_VALIDITA IS NULL		
WHERE 
CUAA=@CUAA 
OR 
CODICE_FISCALE=@CUAA 
ORDER BY DATA_INIZIO_VALIDITA DESC
