CREATE PROCEDURE [dbo].SpGetImpresaAggregazioneInvestimento
(
	@ID_INVESTIMENTO INT
)
AS

--declare @@ID_INVESTIMENTO INT = 7841
DECLARE @CODICE_FISCALE VARCHAR(100) = null ,	 @DENOMINAZIONE VARCHAR(1000)  = null


SELECT @CODICE_FISCALE = imp.CODICE_FISCALE, 
@DENOMINAZIONE = imp_stor.RAGIONE_SOCIALE


from PRIORITA_X_INVESTIMENTI pxi 
inner join IMPRESA imp on imp.CODICE_FISCALE = pxi.VAL_TESTO
INNER JOIN IMPRESA_STORICO imp_stor on imp.ID_STORICO_ULTIMO = imp_stor.ID_STORICO_IMPRESA
where pxi.ID_INVESTIMENTO = @ID_INVESTIMENTO and pxi.ID_PRIORITA = 334

SELECT @CODICE_FISCALE as CODICE_FISCALE, @DENOMINAZIONE  as DENOMINAZIONE


