CREATE PROCEDURE [dbo].[SpGetSpeseSostenuteDomandaPagamento]
(
	@ID_DOMANDA_PAGAMENTO INT,
	@NUMERO_GIUSTIFICATIVO VARCHAR(20)=NULL,
	@DATA_GIUSTIFICATIVO DATETIME=NULL
)
AS
	SELECT V.*,ISNULL(Q1.IMPORTO_RICHIESTO,0) AS IMPORTO_RICHIESTO,ISNULL(Q1.IMPORTO_AMMESSO,0) AS IMPORTO_AMMESSO FROM vSPESE_SOSTENUTE V
	LEFT JOIN (	
		SELECT ID_GIUSTIFICATIVO,SUM(ISNULL(B.IMPORTO_RICHIESTO,0)) AS IMPORTO_RICHIESTO,SUM(ISNULL(B.IMPORTO_AMMESSO,0)) AS IMPORTO_AMMESSO 
		FROM PAGAMENTI_RICHIESTI R INNER JOIN PAGAMENTI_BENEFICIARIO B ON R.ID_PAGAMENTO_RICHIESTO=B.ID_PAGAMENTO_RICHIESTO
		WHERE R.ID_DOMANDA_PAGAMENTO=@ID_DOMANDA_PAGAMENTO GROUP BY B.ID_GIUSTIFICATIVO) Q1 ON V.ID_GIUSTIFICATIVO=Q1.ID_GIUSTIFICATIVO
	 WHERE ID_DOMANDA_PAGAMENTO=@ID_DOMANDA_PAGAMENTO
