/*************************************************************************************************************************************/
	 
	CREATE PROCEDURE [dbo].[SpGraduatoriaProgetti_sigef_mis31]
	(
	@ID_BANDO INT,
	@OPERATORE VARCHAR(16)
	)
AS

DECLARE @ABILITA_FINANZIABILITA_PARZIALE BIT=1

--IMPORTO MASSIMO DEL BANDO TRASVERSALE RISPETTO LE ALTRE MISURE ATTIVATE
DECLARE  @IMPORTO_TOTALE_BANDO DECIMAL(18,2)
SELECT @IMPORTO_TOTALE_BANDO=IMPORTO-IMPORTO*ISNULL(QUOTA_RISERVA,0)/100 FROM VBANDO WHERE ID_BANDO=@ID_BANDO

--SELEZIONO LA LISTA DELLE DOMANDE CON I RELATIVI PUNTEGGI
DECLARE @GRADUATORIA_PROGETTI_T TABLE (ID_PROGETTO INT,PUNTEGGIO DECIMAL(10,6),COSTO_TOTALE DECIMAL(18,2),UTILIZZA_FONDI_RISERVA BIT,
AMMONTARE_FONDI_RISERVA_UTILIZZATO DECIMAL(18,2),ORDINE INT,CONTRIBUTO_TOTALE DECIMAL(18,2),CONTRIBUTO_RIMANENTE DECIMAL(18,2),
FINANZIABILITA CHAR(1),DATA_VALUTAZIONE DATETIME,OPERATORE VARCHAR(16))
INSERT INTO @GRADUATORIA_PROGETTI_T
SELECT ID_PROGETTO,PUNTEGGIO,dbo.calcoloCostoTotaleProgetto(ID_PROGETTO,1,NULL),UTILIZZA_FONDI_RISERVA,AMMONTARE_FONDI_RISERVA_UTILIZZATO,
NULL,NULL,NULL,NULL,NULL,NULL FROM GRADUATORIA_PROGETTI WHERE ID_BANDO=@ID_BANDO

--SELEZIONO LA LISTA DELLE DOMANDE CON I RELATIVI PUNTEGGI
DECLARE @GRADUATORIA_PROGETTI_AMBITI_T TABLE (ID_PROGETTO INT)

-- IMPOSTO DI DEFAULT LA FINANZIABILITA TOTALE DELLA DOMANDA
DECLARE @FINANZIABILITA CHAR(1)
SET @FINANZIABILITA='S'

DECLARE @PROGETTO1 INT, @AMBITO1 INT, @CONTRIBUTO_PROGETTO1 DECIMAL(18,2)
DECLARE @PROGETTO2 INT, @AMBITO2 INT, @CONTRIBUTO_PROGETTO2 DECIMAL(18,2)
DECLARE @PROGETTO3 INT, @AMBITO3 INT, @CONTRIBUTO_PROGETTO3 DECIMAL(18,2)
DECLARE @PROGETTO4 INT, @AMBITO4 INT, @CONTRIBUTO_PROGETTO4 DECIMAL(18,2)
DECLARE @PROGETTO5 INT, @AMBITO5 INT, @CONTRIBUTO_PROGETTO5 DECIMAL(18,2)

SET @AMBITO1 = 5
SET @AMBITO2 = 6
SET @AMBITO3 = 7
SET @AMBITO4 = 8
SET @AMBITO5 = 9

SET @PROGETTO1 = (SELECT TOP 1 GP.ID_PROGETTO FROM @GRADUATORIA_PROGETTI_T GP 
	INNER JOIN vPIANO_INVESTIMENTI I ON GP.ID_PROGETTO = I.ID_PROGETTO
	WHERE I.ID_SETTORE_PRODUTTIVO = @AMBITO1
	GROUP BY GP.ID_PROGETTO, GP.PUNTEGGIO
	ORDER BY GP.PUNTEGGIO DESC)

	SET @CONTRIBUTO_PROGETTO1 = dbo.calcoloContributoTotaleProgetto(@PROGETTO1,1,NULL)

	IF @IMPORTO_TOTALE_BANDO<@CONTRIBUTO_PROGETTO1 BEGIN		
		IF @ABILITA_FINANZIABILITA_PARZIALE=1 AND @IMPORTO_TOTALE_BANDO>0 BEGIN										
			SET @CONTRIBUTO_PROGETTO1=@IMPORTO_TOTALE_BANDO
			SET @IMPORTO_TOTALE_BANDO=0
			SET @FINANZIABILITA='P' --FINANZIABILITA PARZIALE
		END
		ELSE BEGIN
			SET @IMPORTO_TOTALE_BANDO=0
			SET @FINANZIABILITA='N' --NON FINANZIABILITA TOTALE
		END
	END
	ELSE SET @IMPORTO_TOTALE_BANDO=@IMPORTO_TOTALE_BANDO-@CONTRIBUTO_PROGETTO1

UPDATE @GRADUATORIA_PROGETTI_T SET DATA_VALUTAZIONE=GETDATE(),OPERATORE=@OPERATORE,ORDINE=1,
		CONTRIBUTO_TOTALE=@CONTRIBUTO_PROGETTO1,CONTRIBUTO_RIMANENTE=@IMPORTO_TOTALE_BANDO,FINANZIABILITA=@FINANZIABILITA
	WHERE ID_PROGETTO=@PROGETTO1

SET @PROGETTO2 = (SELECT TOP 1 GP.ID_PROGETTO FROM @GRADUATORIA_PROGETTI_T GP 
	INNER JOIN vPIANO_INVESTIMENTI I ON GP.ID_PROGETTO = I.ID_PROGETTO
	WHERE I.ID_SETTORE_PRODUTTIVO = @AMBITO2
	GROUP BY GP.ID_PROGETTO , GP.PUNTEGGIO
	ORDER BY GP.PUNTEGGIO DESC)

	SET @CONTRIBUTO_PROGETTO2 = dbo.calcoloContributoTotaleProgetto(@PROGETTO2,1,NULL)

	IF @IMPORTO_TOTALE_BANDO<@CONTRIBUTO_PROGETTO1 BEGIN		
		IF @ABILITA_FINANZIABILITA_PARZIALE=1 AND @IMPORTO_TOTALE_BANDO>0 BEGIN										
			SET @CONTRIBUTO_PROGETTO2=@IMPORTO_TOTALE_BANDO
			SET @IMPORTO_TOTALE_BANDO=0
			SET @FINANZIABILITA='P' --FINANZIABILITA PARZIALE
		END
		ELSE BEGIN
			SET @IMPORTO_TOTALE_BANDO=0
			SET @FINANZIABILITA='N' --NON FINANZIABILITA TOTALE
		END
	END
	ELSE SET @IMPORTO_TOTALE_BANDO=@IMPORTO_TOTALE_BANDO-@CONTRIBUTO_PROGETTO2

UPDATE @GRADUATORIA_PROGETTI_T SET DATA_VALUTAZIONE=GETDATE(),OPERATORE=@OPERATORE,ORDINE=2,
		CONTRIBUTO_TOTALE=@CONTRIBUTO_PROGETTO2,CONTRIBUTO_RIMANENTE=@IMPORTO_TOTALE_BANDO,FINANZIABILITA=@FINANZIABILITA
	WHERE ID_PROGETTO=@PROGETTO2

SET @PROGETTO3 = (SELECT TOP 1 GP.ID_PROGETTO FROM @GRADUATORIA_PROGETTI_T GP 
	INNER JOIN vPIANO_INVESTIMENTI I ON GP.ID_PROGETTO = I.ID_PROGETTO
	WHERE I.ID_SETTORE_PRODUTTIVO = @AMBITO3
	GROUP BY GP.ID_PROGETTO , GP.PUNTEGGIO
	ORDER BY GP.PUNTEGGIO DESC)
	
	SET @CONTRIBUTO_PROGETTO3 = dbo.calcoloContributoTotaleProgetto(@PROGETTO3,1,NULL)

	IF @IMPORTO_TOTALE_BANDO<@CONTRIBUTO_PROGETTO1 BEGIN		
		IF @ABILITA_FINANZIABILITA_PARZIALE=1 AND @IMPORTO_TOTALE_BANDO>0 BEGIN										
			SET @CONTRIBUTO_PROGETTO3=@IMPORTO_TOTALE_BANDO
			SET @IMPORTO_TOTALE_BANDO=0
			SET @FINANZIABILITA='P' --FINANZIABILITA PARZIALE
		END
		ELSE BEGIN
			SET @IMPORTO_TOTALE_BANDO=0
			SET @FINANZIABILITA='N' --NON FINANZIABILITA TOTALE
		END
	END
	ELSE SET @IMPORTO_TOTALE_BANDO=@IMPORTO_TOTALE_BANDO-@CONTRIBUTO_PROGETTO3

UPDATE @GRADUATORIA_PROGETTI_T SET DATA_VALUTAZIONE=GETDATE(),OPERATORE=@OPERATORE,ORDINE=3,
		CONTRIBUTO_TOTALE=@CONTRIBUTO_PROGETTO3,CONTRIBUTO_RIMANENTE=@IMPORTO_TOTALE_BANDO,FINANZIABILITA=@FINANZIABILITA
	WHERE ID_PROGETTO=@PROGETTO3

SET @PROGETTO4 = (SELECT TOP 1 GP.ID_PROGETTO FROM @GRADUATORIA_PROGETTI_T GP 
	INNER JOIN vPIANO_INVESTIMENTI I ON GP.ID_PROGETTO = I.ID_PROGETTO
	WHERE I.ID_SETTORE_PRODUTTIVO = @AMBITO4
	GROUP BY GP.ID_PROGETTO , GP.PUNTEGGIO
	ORDER BY GP.PUNTEGGIO DESC)

	SET @CONTRIBUTO_PROGETTO4 = dbo.calcoloContributoTotaleProgetto(@PROGETTO4,1,NULL)

	IF @IMPORTO_TOTALE_BANDO<@CONTRIBUTO_PROGETTO1 BEGIN		
		IF @ABILITA_FINANZIABILITA_PARZIALE=1 AND @IMPORTO_TOTALE_BANDO>0 BEGIN										
			SET @CONTRIBUTO_PROGETTO4=@IMPORTO_TOTALE_BANDO
			SET @IMPORTO_TOTALE_BANDO=0
			SET @FINANZIABILITA='P' --FINANZIABILITA PARZIALE
		END
		ELSE BEGIN
			SET @IMPORTO_TOTALE_BANDO=0
			SET @FINANZIABILITA='N' --NON FINANZIABILITA TOTALE
		END
	END
	ELSE SET @IMPORTO_TOTALE_BANDO=@IMPORTO_TOTALE_BANDO-@CONTRIBUTO_PROGETTO4

UPDATE @GRADUATORIA_PROGETTI_T SET DATA_VALUTAZIONE=GETDATE(),OPERATORE=@OPERATORE,ORDINE=4,
		CONTRIBUTO_TOTALE=@CONTRIBUTO_PROGETTO4,CONTRIBUTO_RIMANENTE=@IMPORTO_TOTALE_BANDO,FINANZIABILITA=@FINANZIABILITA
	WHERE ID_PROGETTO=@PROGETTO4

SET @PROGETTO5 = (SELECT TOP 1 GP.ID_PROGETTO FROM @GRADUATORIA_PROGETTI_T GP 
	INNER JOIN vPIANO_INVESTIMENTI I ON GP.ID_PROGETTO = I.ID_PROGETTO
	WHERE I.ID_SETTORE_PRODUTTIVO = @AMBITO5
	GROUP BY GP.ID_PROGETTO , GP.PUNTEGGIO
	ORDER BY GP.PUNTEGGIO DESC)

	SET @CONTRIBUTO_PROGETTO5 = dbo.calcoloContributoTotaleProgetto(@PROGETTO5,1,NULL)

	IF @IMPORTO_TOTALE_BANDO<@CONTRIBUTO_PROGETTO1 BEGIN		
		IF @ABILITA_FINANZIABILITA_PARZIALE=1 AND @IMPORTO_TOTALE_BANDO>0 BEGIN										
			SET @CONTRIBUTO_PROGETTO5=@IMPORTO_TOTALE_BANDO
			SET @IMPORTO_TOTALE_BANDO=0
			SET @FINANZIABILITA='P' --FINANZIABILITA PARZIALE
		END
		ELSE BEGIN
			SET @IMPORTO_TOTALE_BANDO=0
			SET @FINANZIABILITA='N' --NON FINANZIABILITA TOTALE
		END
	END
	ELSE SET @IMPORTO_TOTALE_BANDO=@IMPORTO_TOTALE_BANDO-@CONTRIBUTO_PROGETTO5

UPDATE @GRADUATORIA_PROGETTI_T SET DATA_VALUTAZIONE=GETDATE(),OPERATORE=@OPERATORE,ORDINE=5,
		CONTRIBUTO_TOTALE=@CONTRIBUTO_PROGETTO5,CONTRIBUTO_RIMANENTE=@IMPORTO_TOTALE_BANDO,FINANZIABILITA=@FINANZIABILITA
	WHERE ID_PROGETTO=@PROGETTO5

INSERT INTO @GRADUATORIA_PROGETTI_AMBITI_T SELECT @PROGETTO1
INSERT INTO @GRADUATORIA_PROGETTI_AMBITI_T SELECT @PROGETTO2
INSERT INTO @GRADUATORIA_PROGETTI_AMBITI_T SELECT @PROGETTO3
INSERT INTO @GRADUATORIA_PROGETTI_AMBITI_T SELECT @PROGETTO4
INSERT INTO @GRADUATORIA_PROGETTI_AMBITI_T SELECT @PROGETTO5

--SELECT @CONTRIBUTO_PROGETTO1
--SELECT @CONTRIBUTO_PROGETTO2
--SELECT @CONTRIBUTO_PROGETTO3
--SELECT @CONTRIBUTO_PROGETTO4
--SELECT @CONTRIBUTO_PROGETTO5


DECLARE @ID_PROGETTO INT,@ORDINE INT,@CONTRIBUTO_PROGETTO DECIMAL(18,2)
SET @ORDINE=6

DECLARE PROGETTI CURSOR FOR SELECT ID_PROGETTO FROM @GRADUATORIA_PROGETTI_T 
WHERE ID_PROGETTO NOT IN (
	SELECT ID_PROGETTO FROM @GRADUATORIA_PROGETTI_AMBITI_T
)
ORDER BY PUNTEGGIO DESC
OPEN PROGETTI
FETCH NEXT FROM PROGETTI INTO @ID_PROGETTO
WHILE @@FETCH_STATUS=0 BEGIN
	SET @CONTRIBUTO_PROGETTO=dbo.calcoloContributoTotaleProgetto(@ID_PROGETTO,1,NULL)
		
	IF @IMPORTO_TOTALE_BANDO<@CONTRIBUTO_PROGETTO BEGIN		
		IF @ABILITA_FINANZIABILITA_PARZIALE=1 AND @IMPORTO_TOTALE_BANDO>0 BEGIN										
			SET @CONTRIBUTO_PROGETTO=@IMPORTO_TOTALE_BANDO
			SET @IMPORTO_TOTALE_BANDO=0
			SET @FINANZIABILITA='P' --FINANZIABILITA PARZIALE
		END
		ELSE BEGIN
			SET @IMPORTO_TOTALE_BANDO=0
			SET @FINANZIABILITA='N' --NON FINANZIABILITA TOTALE
		END
	END
	ELSE SET @IMPORTO_TOTALE_BANDO=@IMPORTO_TOTALE_BANDO-@CONTRIBUTO_PROGETTO
		
	UPDATE @GRADUATORIA_PROGETTI_T SET DATA_VALUTAZIONE=GETDATE(),OPERATORE=@OPERATORE,ORDINE=@ORDINE,
		CONTRIBUTO_TOTALE=@CONTRIBUTO_PROGETTO,CONTRIBUTO_RIMANENTE=@IMPORTO_TOTALE_BANDO,FINANZIABILITA=@FINANZIABILITA
	WHERE ID_PROGETTO=@ID_PROGETTO
	SET @ORDINE=@ORDINE+1
	FETCH NEXT FROM PROGETTI INTO @ID_PROGETTO
END	
CLOSE PROGETTI
DEALLOCATE PROGETTI
	
SELECT G.*,ID_BANDO,SEGNATURA_ALLEGATI,ID_PROG_INTEGRATO,FLAG_PREADESIONE,FLAG_DEFINITIVO,ID_FASCICOLO,ID_IMPRESA,
	PROVINCIA_DI_PRESENTAZIONE,SELEZIONATA_X_REVISIONE 
FROM @GRADUATORIA_PROGETTI_T G INNER JOIN PROGETTO P ON G.ID_PROGETTO=P.ID_PROGETTO
ORDER BY ORDINE