CREATE PROCEDURE [dbo].[SpGraduatoriaProgetti_sigef_SportM3]
(
	@ID_BANDO INT,
	@OPERATORE VARCHAR(16)
)
AS

--DECLARE @ID_BANDO INT, @OPERATORE VARCHAR(16)
--SET @ID_BANDO =327--135
--SET @OPERATORE =''
-- FATTO!!!  


DECLARE @ABILITA_FINANZIABILITA_PARZIALE BIT=0
	--IF @ID_BANDO IN (327, 416,428,482) SET @ABILITA_FINANZIABILITA_PARZIALE=1
	IF @ID_BANDO IN (1,2,41,42,43) SET @ABILITA_FINANZIABILITA_PARZIALE=1

	--IMPORTO MASSIMO DEL BANDO TRASVERSALE RISPETTO LE ALTRE MISURE ATTIVATE
	DECLARE  @IMPORTO_TOTALE_BANDO DECIMAL(18,2)
	SELECT @IMPORTO_TOTALE_BANDO=IMPORTO-IMPORTO*ISNULL(QUOTA_RISERVA,0)/100 FROM VBANDO WHERE ID_BANDO=@ID_BANDO

	--SELEZIONO LA LISTA DELLE DOMANDE CON I RELATIVI PUNTEGGI
	DECLARE @GRADUATORIA_PROGETTI_T TABLE (ID_PROGETTO INT,PUNTEGGIO DECIMAL(10,6),COSTO_TOTALE DECIMAL(18,2),UTILIZZA_FONDI_RISERVA BIT,
	AMMONTARE_FONDI_RISERVA_UTILIZZATO DECIMAL(18,2),ORDINE INT,CONTRIBUTO_TOTALE DECIMAL(18,2),CONTRIBUTO_RIMANENTE DECIMAL(18,2),
	FINANZIABILITA CHAR(1),DATA_VALUTAZIONE DATETIME,OPERATORE VARCHAR(16))
	INSERT INTO @GRADUATORIA_PROGETTI_T
	SELECT GRADUATORIA_PROGETTI.ID_PROGETTO,PUNTEGGIO,dbo.calcoloCostoTotaleProgetto(GRADUATORIA_PROGETTI.ID_PROGETTO,1,NULL),UTILIZZA_FONDI_RISERVA,AMMONTARE_FONDI_RISERVA_UTILIZZATO,
	NULL,NULL,NULL,NULL,NULL,NULL FROM GRADUATORIA_PROGETTI INNER JOIN PROGETTO_STORICO ON PROGETTO_STORICO.ID_PROGETTO = GRADUATORIA_PROGETTI.ID_PROGETTO
	WHERE ID_BANDO=@ID_BANDO AND COD_STATO ='L'  ORDER BY PROGETTO_STORICO.DATA ASC

	DECLARE @ID_PROGETTO INT,@ORDINE INT,@CONTRIBUTO_PROGETTO DECIMAL(18,2),@FINANZIABILITA CHAR(1)
	SET @ORDINE=1
	-- IMPOSTO DI DEFAULT LA FINANZIABILITA TOTALE DELLA DOMANDA
	SET @FINANZIABILITA='S'
	DECLARE PROGETTI CURSOR FOR SELECT ID_PROGETTO FROM @GRADUATORIA_PROGETTI_T ORDER BY PUNTEGGIO DESC
	OPEN PROGETTI
	FETCH NEXT FROM PROGETTI INTO @ID_PROGETTO
	WHILE @@FETCH_STATUS=0 BEGIN
		SET @CONTRIBUTO_PROGETTO=dbo.calcoloContributoTotaleProgetto(@ID_PROGETTO,1,NULL)
		
		IF @IMPORTO_TOTALE_BANDO<@CONTRIBUTO_PROGETTO BEGIN		
			IF @ABILITA_FINANZIABILITA_PARZIALE=1 AND @IMPORTO_TOTALE_BANDO>0 BEGIN										
				SET @CONTRIBUTO_PROGETTO=@IMPORTO_TOTALE_BANDO
				SET @IMPORTO_TOTALE_BANDO=0
				SET @FINANZIABILITA='P' --FINANZIABILITA PARZIALE
			END
			ELSE BEGIN
				SET @IMPORTO_TOTALE_BANDO=0
				SET @FINANZIABILITA='N' --NON FINANZIABILITA TOTALE
			END
		END
		ELSE SET @IMPORTO_TOTALE_BANDO=@IMPORTO_TOTALE_BANDO-@CONTRIBUTO_PROGETTO
		
		UPDATE @GRADUATORIA_PROGETTI_T SET DATA_VALUTAZIONE=GETDATE(),OPERATORE=@OPERATORE,ORDINE=@ORDINE,
			CONTRIBUTO_TOTALE=@CONTRIBUTO_PROGETTO,CONTRIBUTO_RIMANENTE=@IMPORTO_TOTALE_BANDO,FINANZIABILITA=@FINANZIABILITA
		WHERE ID_PROGETTO=@ID_PROGETTO
		SET @ORDINE=@ORDINE+1
		FETCH NEXT FROM PROGETTI INTO @ID_PROGETTO
	END	
	CLOSE PROGETTI
	DEALLOCATE PROGETTI
	
	SELECT G.*,ID_BANDO,SEGNATURA_ALLEGATI,ID_PROG_INTEGRATO,FLAG_PREADESIONE,FLAG_DEFINITIVO,ID_FASCICOLO,ID_IMPRESA,
		PROVINCIA_DI_PRESENTAZIONE,SELEZIONATA_X_REVISIONE 
	FROM @GRADUATORIA_PROGETTI_T G INNER JOIN PROGETTO P ON G.ID_PROGETTO=P.ID_PROGETTO
	ORDER BY ORDINE