

CREATE PROCEDURE [dbo].[SpProgettoComunicazioniFileXProtocollazione]
(
	@ID_PROGETTO INT,
	@ID_COMUNICAZIONE INT
)
AS
	--DECLARE @ID_DOMANDA_PAGAMENTO INT=409

	SELECT A.ID_FILE,NOME_FILE=REPLACE(REPLACE(SUBSTRING(ISNULL(' '+A.DESCRIZIONE,''),0,100),'/',' '),'"',''),
		NOME_FILE AS NOME_FILE_EFFETTIVO, RIGHT(NOME_FILE,CHARINDEX('.',REVERSE(NOME_FILE))-1) AS TIPO
	FROM PROGETTO_COMUNICAZIONE_ALLEGATO A INNER JOIN ARCHIVIO_FILE F ON A.ID_FILE=F.ID
	WHERE A.ID_COMUNICAZIONE = @ID_COMUNICAZIONE AND A.ID_PROGETTO=@ID_PROGETTO	
