CREATE PROCEDURE [dbo].[SpPsrGetDocumentiBando]
(
	 @ID_BANDO INT
)
AS
	--DECLARE @ID_BANDO INT=16
	SELECT ID,ID_BANDO,COD_STATO,B.DATA,B.OPERATORE,SEGNATURA,B.ID_ATTO,A.DESCRIZIONE AS STATO,NULL AS ORDINE_STATO,PROFILO,
		NOMINATIVO,A.NUMERO AS NUMERO_ATTO,A.DATA AS DATA_ATTO
	FROM BANDO_STORICO B INNER JOIN VUTENTI U ON B.OPERATORE=U.ID_UTENTE
	INNER JOIN ATTI A ON B.ID_ATTO=A.ID_ATTO WHERE ID_BANDO=@ID_BANDO
	UNION ALL
	SELECT ID,ID_BANDO,'I' AS COD_STATO,I.DATA,I.OPERATORE,NULL AS SEGNATURA,I.ID_ATTO,A.DESCRIZIONE AS STATO,NULL AS ORDINE_STATO,PROFILO,
		NOMINATIVO,A.NUMERO AS NUMERO_ATTO,A.DATA AS DATA_ATTO
	FROM BANDO_INTEGRAZIONI I INNER JOIN VUTENTI U ON I.OPERATORE=U.ID_UTENTE 
	INNER JOIN ATTI A ON I.ID_ATTO=A.ID_ATTO WHERE ID_BANDO=@ID_BANDO
	ORDER BY DATA DESC,ID DESC
