CREATE PROCEDURE [dbo].[SpPsrGetDispAttuativeBando]
(
	@ID_BANDO INT,
	@ID_PROGETTO INT=NULL
)
AS
	SELECT R.TIPO+' '+R.CODICE AS CODICE,R.DESCRIZIONE,Q1.MISURA_PREVALENTE,Q1.IDB AS ID_DISPOSIZIONI_ATTUATIVE,P.ID_PROGETTO
	FROM BANDO B INNER JOIN (	
		SELECT DISTINCT MISURA_PREVALENTE,ISNULL(ID_DISPOSIZIONI_ATTUATIVE,ID_BANDO) AS IDB FROM BANDO_PROGRAMMAZIONE WHERE ID_BANDO=@ID_BANDO
		) Q1 ON B.ID_BANDO=Q1.IDB
	INNER JOIN vzPROGRAMMAZIONE R ON B.ID_PROGRAMMAZIONE=R.ID
	LEFT JOIN PROGETTO P ON B.ID_BANDO=P.ID_BANDO AND ISNULL(ID_PROG_INTEGRATO,ID_PROGETTO)=@ID_PROGETTO
	ORDER BY MISURA_PREVALENTE DESC,R.TIPO+' '+R.CODICE
