CREATE PROCEDURE [dbo].[SpPsrGetProgrammazioneBando]
(
	@ID_BANDO INT,
	@DISP_ATTUATIVE BIT=0
)
AS
	IF @DISP_ATTUATIVE=0 BEGIN
		DECLARE @ID_MISURA_BANDO INT	
		SELECT @ID_MISURA_BANDO=ID_PROGRAMMAZIONE FROM BANDO WHERE ID_BANDO=@ID_BANDO

		DECLARE @BPROG TABLE (ID INT,COD_TIPO VARCHAR(30),CODICE VARCHAR(20),DESCRIZIONE VARCHAR(2000),ID_PADRE INT,COD_PSR VARCHAR(20),
			TIPO VARCHAR(50),LIVELLO INT,ATTIVAZIONE_BANDI BIT,ATTIVAZIONE_FA BIT,ATTIVAZIONE_OB_MISURA BIT,ATTIVAZIONE_INVESTIMENTI BIT,
			ATTIVAZIONE_FF BIT,IMPORTO_DOTAZIONE DECIMAL(18,2),PATH_LABEL VARCHAR(20))
		INSERT INTO @BPROG
		exec SpPsrGetProgrammazione NULL,@ID_MISURA_BANDO,0,0,0,1,0
		
		SELECT B.ID,B.ID_BANDO,B.MISURA_PREVALENTE,B.ID_DISPOSIZIONI_ATTUATIVE,BP.ID AS ID_PROGRAMMAZIONE,BP.COD_TIPO,BP.CODICE,
			BP.DESCRIZIONE,BP.ID_PADRE,BP.COD_PSR,BP.TIPO,BP.LIVELLO,P.TIPO+' '+P.CODICE+' - '+P.DESCRIZIONE AS PADRE
		FROM @BPROG BP LEFT JOIN vzPROGRAMMAZIONE P ON BP.ID_PADRE=P.ID AND P.ATTIVAZIONE_BANDI=0
		LEFT JOIN BANDO_PROGRAMMAZIONE B ON BP.ID=B.ID_PROGRAMMAZIONE AND B.ID_BANDO=@ID_BANDO
		ORDER BY BP.CODICE
	END
	ELSE 
		SELECT DISTINCT NULL AS ID,B.ID_BANDO,MISURA_PREVALENTE,ID_DISPOSIZIONI_ATTUATIVE,P.ID AS ID_PROGRAMMAZIONE,P.COD_TIPO,P.CODICE,
			P.DESCRIZIONE,P.ID_PADRE,P.COD_PSR,P.TIPO,P.LIVELLO,B.DESCRIZIONE AS PADRE		
		FROM BANDO_PROGRAMMAZIONE BP INNER JOIN BANDO B ON BP.ID_DISPOSIZIONI_ATTUATIVE=B.ID_BANDO
		INNER JOIN vzPROGRAMMAZIONE P ON B.ID_PROGRAMMAZIONE=P.ID
		WHERE BP.ID_BANDO=@ID_BANDO AND MISURA_PREVALENTE=0
