

CREATE PROCEDURE [dbo].[SpPsrDomandaPagamentoFileXProtocollazione]
(
	@ID_DOMANDA_PAGAMENTO INT
)
AS
	--DECLARE @ID_DOMANDA_PAGAMENTO INT=409

	SELECT A.ID_FILE,NOME_FILE=REPLACE(REPLACE(SUBSTRING(T.DESCRIZIONE+ISNULL(' '+A.DESCRIZIONE,''),0,100),'/',' '),'"',''),
		CONTENUTO, NOME_FILE AS NOME_FILE_EFFETTIVO, RIGHT(NOME_FILE,CHARINDEX('.',REVERSE(NOME_FILE))-1) AS TIPO,0 AS ORDINE	
	FROM DOMANDA_PAGAMENTO_ALLEGATI A INNER JOIN ARCHIVIO_FILE F ON A.ID_FILE=F.ID
	INNER JOIN TIPO_DOCUMENTO T ON A.COD_TIPO_DOCUMENTO=T.CODICE
	WHERE ID_DOMANDA_PAGAMENTO=@ID_DOMANDA_PAGAMENTO
	UNION ALL
	SELECT DISTINCT G.ID_FILE,REPLACE(REPLACE(SUBSTRING(T.DESCRIZIONE+ISNULL(' nr '+G.NUMERO+' del '+CONVERT(CHAR(10),G.DATA,104)
		+' Fornitore '+G.CF_FORNITORE,''),0,100),'/',' '),'"',''),CONTENUTO, NOME_FILE AS NOME_FILE_EFFETTIVO, RIGHT(NOME_FILE,CHARINDEX('.',REVERSE(NOME_FILE))-1),1 AS ORDINE
	FROM SPESE_SOSTENUTE S INNER JOIN GIUSTIFICATIVI G ON S.ID_GIUSTIFICATIVO=G.ID_GIUSTIFICATIVO
	INNER JOIN TIPO_GIUSTIFICATIVO T ON G.COD_TIPO=T.COD_TIPO
	INNER JOIN ARCHIVIO_FILE F ON G.ID_FILE=F.ID
	WHERE ID_DOMANDA_PAGAMENTO=@ID_DOMANDA_PAGAMENTO
	UNION ALL
	SELECT S.ID_FILE,REPLACE(REPLACE(SUBSTRING(T.DESCRIZIONE+ISNULL(' '+ESTREMI,''),0,100),'/',' '),'"',''),CONTENUTO, NOME_FILE AS NOME_FILE_EFFETTIVO,
		RIGHT(NOME_FILE,CHARINDEX('.',REVERSE(NOME_FILE))-1),2 AS ORDINE		
	FROM SPESE_SOSTENUTE S INNER JOIN ARCHIVIO_FILE F ON S.ID_FILE=F.ID
	INNER JOIN TIPO_GIUSTIFICATIVO T ON S.COD_TIPO=T.COD_TIPO
	WHERE ID_DOMANDA_PAGAMENTO=@ID_DOMANDA_PAGAMENTO
	ORDER BY ORDINE
