CREATE PROCEDURE [dbo].[SpPsrCalcoloImportiFondoRiservaBando]
(
	@ID_BANDO INT,
	@ID_PROGETTO INT
)
AS
	/*
	DECLARE @ID_BANDO INT,@ID_PROGETTO INT
	SET @ID_BANDO=90
	SET @ID_PROGETTO=3731*/

	DECLARE @IMPORTO_RISERVA_BANDO DECIMAL(18,2),@IMPORTO_RISERVA_BANDO_UTILIZZATO DECIMAL(18,2),@CONTRIBUTO_PROGETTO DECIMAL(18,2)
	SELECT @IMPORTO_RISERVA_BANDO=ROUND(IMPORTO*ISNULL(QUOTA_RISERVA,0)/100,2) FROM VBANDO WHERE ID_BANDO=@ID_BANDO
	SELECT @IMPORTO_RISERVA_BANDO_UTILIZZATO=SUM(AMMONTARE_FONDI_RISERVA_UTILIZZATO) FROM GRADUATORIA_PROGETTI 
	WHERE ID_BANDO=@ID_BANDO AND UTILIZZA_FONDI_RISERVA=1
	SELECT @CONTRIBUTO_PROGETTO=dbo.calcoloContributoTotaleProgetto(@ID_PROGETTO,1,NULL)+
		ISNULL(dbo.calcoloPremioContoCapitale(@ID_PROGETTO,1,NULL),0)
	SELECT ISNULL(@IMPORTO_RISERVA_BANDO,0) AS IMPORTO_RISERVA_BANDO,@CONTRIBUTO_PROGETTO AS CONTRIBUTO_PROGETTO,
		ISNULL(@IMPORTO_RISERVA_BANDO_UTILIZZATO,0) AS IMPORTO_RISERVA_UTILIZZATO
