CREATE PROCEDURE [dbo].[SpPsrGetFascicolo]
(
	@ID_BANDO INT
)

AS
	SELECT F.ID,F.FASCICOLO
	FROM BANDO B INNER JOIN vzPROGRAMMAZIONE P ON B.ID_PROGRAMMAZIONE=P.ID
	INNER JOIN FASCICOLO_PALEO F ON F.COD_TIPO=P.COD_TIPO+' '+P.CODICE+' '+CAST(B.ID_BANDO AS VARCHAR(10)) AND F.ATTIVO=1 
		AND B.COD_ENTE=F.COD_ENTE 
	WHERE B.ID_BANDO=@ID_BANDO
	ORDER BY F.DATA_INIZIO_VALIDITA DESC,F.COD_TIPO DESC
