CREATE PROCEDURE [dbo].[SpPsrGetBusinessPlanBando]
(
	@ID_BANDO INT	
)
AS	
	SELECT BP.ID_BANDO,Q.ID_QUADRO,BP.ORDINE,Q.DESCRIZIONE AS QUADRO,Q.URL,Q.TITOLO,Q.ORDINE AS ORDINE_QUADRI,Q.DOMANDA
	FROM QUADRI_BUSINESS_PLAN Q LEFT JOIN BUSINESS_PLAN BP ON Q.ID_QUADRO=BP.ID_QUADRO AND BP.ID_BANDO=@ID_BANDO
	ORDER BY ORDINE_QUADRI
