
CREATE PROCEDURE [dbo].[SpPsrGetBandoConfig]
(
	@ID_BANDO INT
)
AS
	--DECLARE @ID_BANDO INT=9

	SELECT T.CODICE AS COD_TIPO,COD_MACROTIPO,FORMATO,T.DESCRIZIONE,T.ATTIVO AS TIPO_ATTIVO,T.ORDINE,C.ID,ID_BANDO,VALORE,C.ATTIVO,
		DATA_INIZIO,OPERATORE_INIZIO,DATA_FINE,OPERATORE_FINE,P.DESCRIZIONE AS VALORE_DESCRIZIONE
	FROM BANDO_CONFIG_TIPO T LEFT JOIN BANDO_CONFIG C ON T.CODICE=C.COD_TIPO AND C.ID_BANDO=@ID_BANDO AND C.ATTIVO=1
	LEFT JOIN BANDO_CONFIG_TIPO_PARAMETRI P ON T.CODICE=P.COD_TIPO AND C.VALORE=P.CODICE
	ORDER BY ORDINE,DATA_INIZIO DESC