CREATE PROCEDURE [dbo].[SpPsrGetProgrammazioneSanzioni]
(
	@ID_PROGRAMMAZIONE INT,
	@LIVELLO CHAR(1)=NULL
)
AS
	SELECT TITOLO,COD_TIPO,LIVELLO FROM zPROGRAMMAZIONE_SANZIONI S 
	INNER JOIN TIPO_SANZIONI T ON S.COD_SANZIONE=T.COD_TIPO
	WHERE S.ID_PROGRAMMAZIONE=@ID_PROGRAMMAZIONE AND S.ATTIVA=1 AND AUTOMATICO=0
		AND (@LIVELLO IS NULL OR T.LIVELLO=@LIVELLO)
	UNION
	SELECT TITOLO,T.COD_TIPO,LIVELLO FROM zPROGRAMMAZIONE P 
	INNER JOIN zPROGRAMMAZIONE_SANZIONI S ON P.ID_PADRE=S.ID_PROGRAMMAZIONE
	INNER JOIN TIPO_SANZIONI T ON S.COD_SANZIONE=T.COD_TIPO
	WHERE P.ID=@ID_PROGRAMMAZIONE AND S.ATTIVA=1 AND AUTOMATICO=0
		AND (@LIVELLO IS NULL OR T.LIVELLO=@LIVELLO)
