CREATE PROCEDURE [dbo].[SpPsrRilevaSanzioniXDomandaPagamento]
(
	@ID_DOMANDA_PAGAMENTO INT
)
AS
	SELECT COD_TIPO,TITOLO,SUM(AMMONTARE) AS AMMONTARE,COUNT(ID_INVESTIMENTO) AS NUM_INVESTIMENTI,LIVELLO,AUTOMATICO 
	FROM VSANZIONI WHERE ID_DOMANDA_PAGAMENTO=@ID_DOMANDA_PAGAMENTO GROUP BY COD_TIPO,TITOLO,LIVELLO,AUTOMATICO
