CREATE PROCEDURE [dbo].[SpPsrGetStatisticheProgetti]
(
	@ID_BANDO INT
)
AS
	SELECT F.COD_FASE,F.DESCRIZIONE AS FASE,S.COD_STATO,S.DESCRIZIONE AS STATO,COUNT(Q2.ID_PROGETTO) AS NR_DOMANDE
	FROM STATO_PROGETTO S INNER JOIN FASI_PROCEDURALI F ON ISNULL(S.COD_FASE,'P')=F.COD_FASE
	LEFT JOIN (
		SELECT PS.ID_PROGETTO,PS.COD_STATO,Q1.COD_FASE
		FROM PROGETTO_STORICO PS
		INNER JOIN PROGETTO P ON PS.ID_PROGETTO=P.ID_PROGETTO
		INNER JOIN (
			SELECT ID_PROGETTO,ISNULL(COD_FASE,'P') AS COD_FASE,MAX(PS.ID) AS MAX_ID FROM PROGETTO_STORICO PS
			INNER JOIN STATO_PROGETTO S ON PS.COD_STATO=S.COD_STATO GROUP BY ID_PROGETTO,ISNULL(COD_FASE,'P')
			) Q1 ON PS.ID=Q1.MAX_ID
		WHERE ISNULL(P.ID_PROG_INTEGRATO,P.ID_PROGETTO)=P.ID_PROGETTO AND P.ID_BANDO=@ID_BANDO
		) Q2 ON S.COD_STATO=Q2.COD_STATO
	GROUP BY F.COD_FASE,F.DESCRIZIONE,S.COD_STATO,S.DESCRIZIONE,F.ORDINE,S.ORDINE
	ORDER BY F.ORDINE,S.ORDINE,S.DESCRIZIONE
