CREATE PROCEDURE [dbo].[SpPsrRiepilogoImportiDPXProgrammazione]
(
	@ID_DOMANDA_PAGAMENTO INT
)
AS
--DECLARE @ID_DOMANDA_PAGAMENTO INT;SET @ID_DOMANDA_PAGAMENTO =290

DECLARE @ID_PROGETTO INT,@ID_VARIANTE INT,@DATA_MODIFICA_PAGAMENTO DATETIME,@COD_TIPO CHAR(3)
SELECT @ID_PROGETTO=ID_PROGETTO,@DATA_MODIFICA_PAGAMENTO=DATA_MODIFICA,@COD_TIPO=COD_TIPO,@ID_VARIANTE=ID_VARIAZIONE_ACCERTATA 
FROM DOMANDA_DI_PAGAMENTO WHERE ID_DOMANDA_PAGAMENTO=@ID_DOMANDA_PAGAMENTO
IF @ID_VARIANTE IS NULL
	SELECT @ID_VARIANTE=MAX(ID_VARIANTE) FROM VARIANTI WHERE ID_PROGETTO=@ID_PROGETTO AND APPROVATA=1 AND ANNULLATA=0 
	AND DATA_MODIFICA<@DATA_MODIFICA_PAGAMENTO

SELECT DISTINCT P.ID_PROGETTO,P.ID_BANDO,TIPO+' '+CODICE AS MISURA,MISURA_PREVALENTE=CASE WHEN P.ID_PROGETTO=P.ID_PROG_INTEGRATO THEN 1 ELSE 0 END,
	E.IMPORTO_AMMISSIBILE AS CONTRIBUTO_AMMISSIBILE,E.IMPORTO_SANZIONE AS AMMONTARE_SANZIONE,E.IMPORTO_RECUPERO_ANTICIPO AS RECUPERO_ANTICIPO,
	E.IMPORTO_AMMESSO AS CONTRIBUTO_AMMESSO,Q1.COSTO_TOTALE_PROGETTO AS COSTO_TOTALE_PROGETTO_CORRELATO,
	ISNULL(Q2.IMPORTO_RICHIESTO,0) AS IMPORTO_RICHIESTO,CONTRIBUTO_TOTALE_PROGETTO_CORRELATO=CASE 
	WHEN Q1.CONTRIBUTO_TOTALE_PROGETTO>Q1.CONTRIBUTO_DI_MISURA THEN Q1.CONTRIBUTO_DI_MISURA ELSE Q1.CONTRIBUTO_TOTALE_PROGETTO END,
	CONTRIBUTO_RICHIESTO=ISNULL(Q2.CONTRIBUTO_RICHIESTO,0)+CASE WHEN P.ID_PROGETTO=P.ID_PROG_INTEGRATO AND @COD_TIPO='SLD' THEN 
	ISNULL(dbo.calcoloPremioContoCapitaleSaldo(@ID_DOMANDA_PAGAMENTO,0),0) ELSE 0 END
FROM DOMANDA_DI_PAGAMENTO D INNER JOIN PROGETTO P ON D.ID_PROGETTO=P.ID_PROG_INTEGRATO
INNER JOIN BANDO B ON P.ID_BANDO=B.ID_BANDO INNER JOIN vzPROGRAMMAZIONE PR ON B.ID_PROGRAMMAZIONE=PR.ID
LEFT JOIN (
	SELECT ID_PROGETTO,CONTRIBUTO_DI_MISURA,dbo.calcoloCostoTotaleProgettoCorrelato(ID_PROGETTO,1,@ID_VARIANTE) AS COSTO_TOTALE_PROGETTO,
		ISNULL(dbo.calcoloContributoTotaleProgettoCorrelato(ID_PROGETTO,1,@ID_VARIANTE),0)+CASE WHEN ID_PROGETTO=ID_PROG_INTEGRATO 
		THEN ISNULL(dbo.calcoloPremioContoCapitale(@ID_PROGETTO,1,@ID_VARIANTE),0) ELSE 0 END AS CONTRIBUTO_TOTALE_PROGETTO
	FROM GRADUATORIA_PROGETTI_FINANZIABILITA WHERE ID_PROG_INTEGRATO=@ID_PROGETTO) Q1 ON P.ID_PROGETTO=Q1.ID_PROGETTO
LEFT JOIN DOMANDA_DI_PAGAMENTO_ESPORTAZIONE E ON D.ID_DOMANDA_PAGAMENTO=E.ID_DOMANDA_PAGAMENTO AND P.ID_PROGETTO=E.ID_PROGETTO
LEFT JOIN (
	SELECT ID_PROGETTO,SUM(RIC.IMPORTO_RICHIESTO) AS IMPORTO_RICHIESTO,SUM(RIC.CONTRIBUTO_RICHIESTO) AS CONTRIBUTO_RICHIESTO 
	FROM PIANO_INVESTIMENTI I INNER JOIN PAGAMENTI_RICHIESTI RIC ON I.ID_INVESTIMENTO=RIC.ID_INVESTIMENTO 
	WHERE RIC.ID_DOMANDA_PAGAMENTO=@ID_DOMANDA_PAGAMENTO GROUP BY ID_PROGETTO) Q2 ON Q2.ID_PROGETTO=P.ID_PROGETTO
WHERE D.ID_DOMANDA_PAGAMENTO=@ID_DOMANDA_PAGAMENTO
