CREATE PROCEDURE [dbo].[SpPsrCreaElencoDomandeXControlliLoco] 
(
	@ID_LOTTO INT
)
AS
	--DECLARE @ID_PROGRAMMAZIONE INT

	--SELECT @ID_PROGRAMMAZIONE=ID_PROGRAMMAZIONE FROM CONTROLLI_LOCO_LOTTO WHERE ID_LOTTO=@ID_LOTTO

	----INSERT INTO CONTROLLI_DOMANDE_PAGAMENTO
	--SELECT @ID_LOTTO,ID_DOMANDA_PAGAMENTO,NULL,0,NULL,NULL,NULL,NULL,
	--ISNULL( CASE WHEN D.COD_TIPO='ANT' THEN -- MODIFICATA IL 23/10/2013, AGGIUNTA DEGLI ANTICPI AI LOTTI
	--	(SELECT SUM(CONTRIBUTO_RICHIESTO) FROM ANTICIPI_RICHIESTI WHERE ID_DOMANDA_PAGAMENTO=D.ID_DOMANDA_PAGAMENTO)
	--	ELSE (SELECT SUM(CONTRIBUTO_RICHIESTO) FROM PAGAMENTI_RICHIESTI WHERE ID_DOMANDA_PAGAMENTO=D.ID_DOMANDA_PAGAMENTO) END,0),NULL,NULL,0 
	--FROM DOMANDA_DI_PAGAMENTO D INNER JOIN vPROGETTO P ON D.ID_PROGETTO=P.ID_PROGETTO
	--INNER JOIN BANDO B ON P.ID_BANDO=B.ID_BANDO
	--INNER JOIN zPROGRAMMAZIONE R ON B.ID_PROGRAMMAZIONE=R.ID
	--WHERE R.ID=@ID_PROGRAMMAZIONE AND D.SEGNATURA IS NOT NULL AND SEGNATURA_APPROVAZIONE IS NULL 
	--	AND (PREDISPOSTA_A_CONTROLLO=1 OR D.COD_TIPO='ANT') AND D.ANNULLATA=0
	--	AND ORDINE_FASE<9 AND ORDINE_STATO=1 -- CONTROLLO SU STATO PROGETTO
	--	AND ID_DOMANDA_PAGAMENTO NOT IN (SELECT ID_DOMANDA_PAGAMENTO FROM CONTROLLI_DOMANDE_PAGAMENTO)

	
	
	INSERT INTO CONTROLLI_DOMANDE_PAGAMENTO
	SELECT DISTINCT @ID_LOTTO,D.ID_DOMANDA_PAGAMENTO,NULL,0,NULL,NULL,NULL,NULL,
		ISNULL( CASE WHEN D.COD_TIPO='ANT' THEN (SELECT SUM(CONTRIBUTO_RICHIESTO) FROM ANTICIPI_RICHIESTI WHERE ID_DOMANDA_PAGAMENTO=D.ID_DOMANDA_PAGAMENTO)
		ELSE (SELECT SUM(CONTRIBUTO_RICHIESTO) FROM PAGAMENTI_RICHIESTI WHERE ID_DOMANDA_PAGAMENTO=D.ID_DOMANDA_PAGAMENTO) END,0),NULL,NULL,0,1
	--P.ID_PROGETTO,CD.* 
	FROM CONTROLLI_LOCO_LOTTO C	
	INNER JOIN zPROGRAMMAZIONE R ON C.ID_PROGRAMMAZIONE=R.ID_PADRE
	INNER JOIN BANDO B ON C.ID_PROGRAMMAZIONE=B.ID_PROGRAMMAZIONE OR R.ID=B.ID_PROGRAMMAZIONE
	INNER JOIN vPROGETTO P ON B.ID_BANDO=P.ID_BANDO AND P.ORDINE_FASE<9 AND P.ORDINE_STATO=1
	INNER JOIN DOMANDA_DI_PAGAMENTO D ON P.ID_PROGETTO=D.ID_PROGETTO AND D.SEGNATURA IS NOT NULL AND D.SEGNATURA_APPROVAZIONE IS NOT NULL
		AND /*(PREDISPOSTA_A_CONTROLLO=1 OR*/ D.COD_TIPO!='ANT'/*)*/ AND D.ANNULLATA=0
	LEFT JOIN CONTROLLI_DOMANDE_PAGAMENTO CD ON D.ID_DOMANDA_PAGAMENTO=CD.ID_DOMANDA_PAGAMENTO	
	WHERE C.ID_LOTTO=@ID_LOTTO AND CD.ID_LOTTO IS NULL
	
	SELECT * FROM vCONTROLLI_DOMANDE_PAGAMENTO WHERE ID_LOTTO=@ID_LOTTO ORDER BY COD_TIPO DESC, DATA_PRESENTAZIONE_DOMANDA_PAGAMENTO
