CREATE PROCEDURE [dbo].[SpRiepilogoCollaboratoriXManifestazione]
(
	@ID_BANDO INT
)
AS

--DECLARE @ID_BANDO INT 
--SET @ID_BANDO=128



SELECT	ID_UTENTE,
		U.CF_UTENTE,
		ID_PROFILO,
		NOMINATIVO,
		COD_ENTE, 
		NULL AS PROVINCIA, 
		COUNT(C.ID_MANIFESTAZIONE) AS PROGETTI_ASSEGNATI,
		(
			SELECT COUNT(ID_MANIFESTAZIONE)
			FROM MANIFESTAZIONE_ISTRUTTORIA 
			WHERE RICEVIBILITA_OPERATORE = U.CF_UTENTE AND RICEVIBILITA = 'I'
		) AS PROGETTI_RICEVIBILI,
		(
			SELECT COUNT(ID_MANIFESTAZIONE)
			FROM MANIFESTAZIONE_ISTRUTTORIA 
			WHERE RICEVIBILITA_OPERATORE = U.CF_UTENTE AND RICEVIBILITA = 'Q'
		) AS PROGETTI_NON_RICEVIBILI,
		(
			SELECT COUNT(ID_MANIFESTAZIONE)
			FROM MANIFESTAZIONE_ISTRUTTORIA 
			WHERE AMMISSIBILITA_OPERATORE = U.CF_UTENTE AND AMMISSIBILITA = 'A'
		) AS PROGETTI_AMMISSIBILI,
		(
			SELECT COUNT(ID_MANIFESTAZIONE)
			FROM MANIFESTAZIONE_ISTRUTTORIA 
			WHERE AMMISSIBILITA_OPERATORE = U.CF_UTENTE AND AMMISSIBILITA = 'B'
		) AS PROGETTI_NON_AMMISSIBILI,
		0 AS PROGETTI_ISTRUITI_DA_ALTRI
FROM MANIFESTAZIONE_DI_INTERESSE M LEFT JOIN COLLABORATORI_X_MANIFESTAZIONE C ON M.ID_MANIFESTAZIONE = C.ID_MANIFESTAZIONE
INNER JOIN vUTENTI U ON C.CF_UTENTE = U.CF_UTENTE
WHERE M.ID_BANDO = @ID_BANDO AND SEGNATURA IS NOT NULL
GROUP BY ID_UTENTE,U.CF_UTENTE,ID_PROFILO,NOMINATIVO,COD_ENTE
