CREATE PROCEDURE [dbo].[SpRiepilogoBandi]
(
	@ID_BANDO INT,
	@COD_QUERY VARCHAR(40)
)
AS
/*
DECLARE @ID_BANDO INT
SET @ID_BANDO=27
DECLARE @COD_QUERY VARCHAR(30)
SET @COD_QUERY='DOMANDE_NON_ASSEGNATE'
*/

IF @COD_QUERY='DOMANDE_PRESENTATE' BEGIN
	SELECT COUNT(P.ID_PROGETTO) FROM PROGETTO AS P INNER JOIN PROGETTO_STORICO  AS S 
	ON P.ID_PROGETTO = S.ID_PROGETTO WHERE P.ID_BANDO = @ID_BANDO AND S.COD_STATO = 'L'	
END
ELSE IF @COD_QUERY='DOMANDE_NON_ASSEGNATE' BEGIN
	SELECT COUNT(P.ID_PROGETTO) FROM PROGETTO AS P INNER JOIN PROGETTO_STORICO  AS S 
	ON P.ID_PROGETTO = S.ID_PROGETTO WHERE P.ID_BANDO = @ID_BANDO AND S.COD_STATO = 'L'	
	AND P.ID_PROGETTO NOT IN (SELECT ID_PROGETTO FROM COLLABORATORI_X_BANDO WHERE ID_BANDO=@ID_BANDO AND ATTIVO = 1)
END
ELSE IF @COD_QUERY='MANIFESTAZIONI_PRESENTATE' BEGIN
	SELECT COUNT(ID_MANIFESTAZIONE) 
	FROM MANIFESTAZIONE_DI_INTERESSE 
	WHERE SEGNATURA IS NOT NULL AND ID_BANDO = @ID_BANDO
END
