CREATE  PROCEDURE [dbo].[SpRiepilogoFatturatoFiliera]
(
	@ID_UTENTE  INT = NULL, 
	@ID_PROGETTO INT, 
	@CUAA VARCHAR(16)    = NULL,
 	@RAGIONE_SOCIALE VARCHAR(255)  = NULL   
)
AS
 --@ID_PROGETTO  -> è IL PROGETTO  PIF   DEL PROMOTORE
--declare	@ID_UTENTE  INT ,
--	@ID_PROGETTO INT, 
--	@CUAA VARCHAR(16)    ,
-- 	@RAGIONE_SOCIALE VARCHAR(255)  
--set  @ID_PROGETTO= 5198

 
DECLARE @ID_MANIFESTAZIONE INT, @COD_FILIERA VARCHAR(10), @ID_BANDO_PROMOTORE INT

-- RECUPERO LA  MACROFILIERA
  SET @ID_MANIFESTAZIONE = ( SELECT ID_VALORE FROM PRIORITA_X_PROGETTO WHERE ID_PROGETTO = @ID_PROGETTO AND ID_PRIORITA in ( 374,406,798, 1191)  ) 
  SET  @COD_FILIERA = (SELECT  VP.CODICE  FROM  PRIORITA_X_PROGETTO pp inner join  VALORI_PRIORITA VP ON VP.ID_VALORE = PP.ID_VALORE   WHERE ID_PROGETTO = @ID_PROGETTO AND PP.ID_PRIORITA in ( 374,406,798, 1191) )
  SET @ID_BANDO_PROMOTORE = (SELECT ID_BANDO FROM PROGETTO WHERE ID_PROGETTO = @ID_PROGETTO)
 
-- prendere la plv di quale bando? Il primo progetto approvato dal promotore

SELECT     CUAA, RAGIONE_SOCIALE, 
SUM(ISNULL( PRODUZIONE_TOTALE,0)) as PRODUZIONE_TOTALE, 
SUM(ISNULL( PRODUZIONE_IN_FILIERA,0)) AS PRODUZIONE_IN_FILIERA, 
SUM(ISNULL( PLV_TOTALE,0)) AS PLV_TOTALE, SUM(ISNULL( PLV_FILIERA,0)) AS PLV_FILIERA
FROM         (SELECT      I.CUAA, RAGIONE_SOCIALE  , 
										'PRODUZIONE_TOTALE'  =  
									CASE 
											WHEN COD_PRODOTTO IS NOT NULL THEN  ISNULL(	SUM(isnull(PRODUZIONE_UNITARIA,0) * SAU/10000),0)
											WHEN  ID_CLASSE_ALLEVAMENTO IS NOT NULL  THEN  ISNULL(SUM(isnull(PRODUZIONE_UNITARIA,0) * SAU),0) 
											WHEN  ID_ATTIVITA_CONNESSA IS NOT NULL  THEN ISNULL( SAU,0)
									END ,  
									SUM( ISNULL(PRODUZIONE_IN_FILIERA,0)) AS PRODUZIONE_IN_FILIERA,
									 PLV AS PLV_TOTALE, 
									 isnull(PLV_FILIERA,0)   AS PLV_FILIERA
				FROM          VPROGETTO  AS P INNER JOIN
									 VIMPRESA AS I ON P.ID_IMPRESA = I.ID_IMPRESA INNER JOIN 
									  PRIORITA_X_PROGETTO AS PP ON PP.ID_PROGETTO = P.ID_PROGETTO AND ID_PRIORITA in (374,406, 798, 1191) AND ID_VALORE =@ID_MANIFESTAZIONE  LEFT OUTER JOIN
									  (SELECT MAX(PARTECIPANTI_X_FILIERA.ID_PROGETTO_VALIDATO) AS ID_PROGETTO_VALIDATO, AMMESSO 
										FROM PARTECIPANTI_X_FILIERA 
											INNER JOIN VPROGETTO PR ON PARTECIPANTI_X_FILIERA.ID_PROGETTO_VALIDATO = PR.ID_PROGETTO
											INNER JOIN PLV_IMPRESA ON PARTECIPANTI_X_FILIERA.ID_PROGETTO_VALIDATO = PLV_IMPRESA.ID_PROGETTO  
											INNER JOIN VIMPRESA AS I ON Pr.ID_IMPRESA = I.ID_IMPRESA
										WHERE (PARTECIPANTI_X_FILIERA.COD_FILIERA = @COD_FILIERA) AND PLV_IMPRESA.PRODUZIONE_IN_FILIERA > 0 AND AMMESSO = 1 AND PR.COD_STATO!='P'
										GROUP BY I.CUAA,AMMESSO) AS PxF ON P.ID_PROGETTO = PxF.ID_PROGETTO_VALIDATO INNER JOIN
									(  SELECT PREVISIONALE,  ID_PROGETTO, COD_VARIETA, COD_PRODOTTO, ID_CLASSE_ALLEVAMENTO, ID_MATERIA_PRIMA, 
														 ID_UNITA_MISURA, ID_ATTIVITA_CONNESSA, 
															CASE
																		WHEN 	 ID_UNITA_MISURA = 6 THEN PRODUZIONE_UNITARIA/1000
																		WHEN    ID_UNITA_MISURA = 7 THEN PRODUZIONE_UNITARIA/10
																	    WHEN     ID_UNITA_MISURA = 26 THEN PRODUZIONE_UNITARIA/1000000
																		WHEN     ID_UNITA_MISURA = 18 THEN PRODUZIONE_UNITARIA*1.03/1000
																		ELSE  PRODUZIONE_UNITARIA
															END AS  PRODUZIONE_UNITARIA, 
															CASE
																		WHEN 	 ID_UNITA_MISURA = 6 THEN PRODUZIONE_IN_FILIERA/1000
																		WHEN    ID_UNITA_MISURA = 7 THEN PRODUZIONE_IN_FILIERA/10
																	    WHEN     ID_UNITA_MISURA = 26 THEN PRODUZIONE_IN_FILIERA/1000000
																		WHEN     ID_UNITA_MISURA = 18 THEN PRODUZIONE_IN_FILIERA*1.03/1000
																		ELSE  PRODUZIONE_IN_FILIERA
															END AS PRODUZIONE_IN_FILIERA, 
															  PREZZO_UNITARIO, PLV, PLV_FILIERA,  SAU , CUAA_TRASFORMATORE  
										FROM         PLV_IMPRESA  )AS  PLV  ON P.ID_PROGETTO = PLV.ID_PROGETTO
				 WHERE     PxF.AMMESSO = 1 AND  ((@CUAA IS NULL) OR I.CUAA = @CUAA)  AND
									 ((@RAGIONE_SOCIALE IS NULL) OR RAGIONE_SOCIALE LIKE '%' + @RAGIONE_SOCIALE + '%' )   
									  AND P.ID_PROGETTO != @ID_PROGETTO  AND PREVISIONALE=1
									  AND P.ORDINE_STATO = 1 AND P.COD_STATO NOT IN ('P')
									  AND ((@ID_BANDO_PROMOTORE = 302 AND P.ID_BANDO IN (295,296,297,298,299,300,301)) 
											OR (@ID_BANDO_PROMOTORE = 276 AND P.ID_BANDO IN (262,264,265,266,270,271,275))
											OR (@ID_BANDO_PROMOTORE = 340 AND P.ID_BANDO IN (347,346,345,344,342,341,343))
											OR @ID_BANDO_PROMOTORE NOT IN (302, 276, 340))
				GROUP BY  P.ID_PROGETTO,   I.CUAA, RAGIONE_SOCIALE , COD_PRODOTTO ,COD_VARIETA ,ID_CLASSE_ALLEVAMENTO,ID_ATTIVITA_CONNESSA, SAU, PRODUZIONE_IN_FILIERA, PLV,PLV_FILIERA) AS B
GROUP BY CUAA, RAGIONE_SOCIALE
ORDER BY RAGIONE_SOCIALE
