
CREATE PROCEDURE SpRiepilogoSingolaDomandaPagamento
(
	@ID_PROGETTO INT,
	@ID_DOMANDA INT
)
AS
/*
DECLARE @ID_PROGETTO INT
DECLARE @ID_DOMANDA INT
SET @ID_PROGETTO = 49
SET @ID_DOMANDA = 30
*/

	SELECT V.COD_TIPO, V.DESCRIZIONE,V.NUMERO,QUOTA_MAX,QUOTA_MIN,IMPORTO_MAX,IMPORTO_MIN, V.COD_FASE, FASE, V.ORDINE,
		D.ID_DOMANDA_PAGAMENTO, D.ID_PROGETTO,D.DATA_INSERIMENTO,D.APPROVATA,D.SEGNATURA_APPROVAZIONE,D.SEGNATURA_SECONDA_APPROVAZIONE,
		D.CF_OPERATORE,F.COGNOME+' '+F.NOME AS OPERATORE,D.DATA_MODIFICA,D.COD_ENTE, D.SEGNATURA,SUM(IMPORTO_RICHIESTO) AS IMPORTO_RICHIESTO,
		R.SELEZIONATA_X_REVISIONE,R.APPROVATA AS APPROVATA_REVISIONE,SEGNATURA_REVISIONE,SEGNATURA_SECONDA_REVISIONE,D.ANNULLATA,
		D.SEGNATURA_ANNULLAMENTO,SUM(IMPORTO_AMMESSO) AS IMPORTO_AMMESSO,CONTRIBUTO_RICHIESTO=CASE 
		WHEN V.COD_TIPO='ANT' THEN (SELECT SUM(CONTRIBUTO_RICHIESTO) FROM ANTICIPI_RICHIESTI WHERE ID_DOMANDA_PAGAMENTO=D.ID_DOMANDA_PAGAMENTO)  
		WHEN V.COD_TIPO='SLD' THEN SUM(CONTRIBUTO_RICHIESTO)+ISNULL(dbo.calcoloPremioContoCapitaleDomandaPagamento(D.ID_DOMANDA_PAGAMENTO,0),0)
		ELSE SUM(CONTRIBUTO_RICHIESTO) END,
		(SELECT SUM(IMPORTO_AMMESSO) FROM DOMANDA_DI_PAGAMENTO_ESPORTAZIONE WHERE ID_DOMANDA_PAGAMENTO=D.ID_DOMANDA_PAGAMENTO) AS CONTRIBUTO_AMMESSO,
		L.NUMERO_ESTRAZIONI, L.REVISIONE_CONCLUSA
	FROM vBANDO_TIPO_PAGAMENTO V 
		JOIN PROGETTO ON V.ID_BANDO=PROGETTO.ID_BANDO AND PROGETTO.ID_PROGETTO = @ID_PROGETTO
		LEFT JOIN DOMANDA_DI_PAGAMENTO D ON V.COD_TIPO = D.COD_TIPO AND D.ID_PROGETTO = @ID_PROGETTO
		LEFT JOIN PERSONA_FISICA F ON D.CF_OPERATORE=F.CODICE_FISCALE
		LEFT JOIN PAGAMENTI_RICHIESTI P ON D.ID_DOMANDA_PAGAMENTO = P.ID_DOMANDA_PAGAMENTO
		--LEFT JOIN REVISIONE_DOMANDA_PAGAMENTO R ON D.ID_DOMANDA_PAGAMENTO = R.ID_DOMANDA_PAGAMENTO
		LEFT JOIN CTE_TESTATA_VALIDAZIONE R ON D.ID_DOMANDA_PAGAMENTO = R.ID_DOMANDA_PAGAMENTO
		LEFT JOIN LOTTO_DI_REVISIONE L ON R.ID_LOTTO=L.ID_LOTTO
	WHERE NUMERO > 0 
	AND D.ID_DOMANDA_PAGAMENTO = @ID_DOMANDA
	GROUP BY V.COD_TIPO, V.DESCRIZIONE,V.NUMERO,QUOTA_MAX,QUOTA_MIN,IMPORTO_MAX,IMPORTO_MIN,COD_FASE, FASE, V.ORDINE, D.ID_DOMANDA_PAGAMENTO, 
		D.ID_PROGETTO, D.DATA_INSERIMENTO,D.APPROVATA,D.SEGNATURA_APPROVAZIONE,D.SEGNATURA_SECONDA_APPROVAZIONE, D.CF_OPERATORE,F.COGNOME+' '+F.NOME,
		D.DATA_MODIFICA,D.COD_ENTE, D.SEGNATURA,R.SELEZIONATA_X_REVISIONE,R.APPROVATA,SEGNATURA_REVISIONE,SEGNATURA_SECONDA_REVISIONE,
		D.ANNULLATA,D.SEGNATURA_ANNULLAMENTO,L.NUMERO_ESTRAZIONI, L.REVISIONE_CONCLUSA
	ORDER BY ORDINE
GO


