
CREATE PROCEDURE [dbo].[SpRiepilogoAttivitaImpresa]
(
	@ID_IMPRESA INT
)
AS
	--DECLARE @ID_IMPRESA INT=270

	DECLARE @PROGETTI TABLE (ID_PROGETTO INT,COD_STATO CHAR(1),DATA DATETIME,SEGNATURA VARCHAR(100),STATO VARCHAR(50),
		ORDINE_STATO INT,ORDINE_FASE INT)
	INSERT INTO @PROGETTI
	SELECT ID_PROGETTO,COD_STATO,DATA,SEGNATURA,STATO,ORDINE_STATO,ORDINE_FASE
	FROM vPROGETTO WHERE ID_IMPRESA=@ID_IMPRESA AND ISNULL(ID_PROG_INTEGRATO,ID_PROGETTO)=ID_PROGETTO

	DECLARE @NR_PR_PRESENTATI INT,@NR_PR_ATTIVI INT,@ID_PR_ULTIMO INT,@STATO_PR_ULTIMO VARCHAR(50)
	SELECT @NR_PR_PRESENTATI=COUNT(*) FROM @PROGETTI WHERE SEGNATURA IS NOT NULL
	SELECT @NR_PR_ATTIVI=COUNT(*) FROM @PROGETTI WHERE SEGNATURA IS NOT NULL AND ORDINE_STATO=1 AND ORDINE_FASE<9
	SELECT TOP 1 @ID_PR_ULTIMO=ID_PROGETTO,@STATO_PR_ULTIMO=STATO FROM @PROGETTI ORDER BY DATA DESC
	
	DECLARE @ASSEGNAZIONI TABLE (ID INT,ANNO INT,TIPO VARCHAR(50),COD_STATO CHAR(1),DATA DATETIME,STATO VARCHAR(50),
		ORDINE_STATO INT,ORDINE_FASE INT)
	--INSERT INTO @ASSEGNAZIONI
	--SELECT ID,ANNO,TIPO_ASSEGNAZIONE,COD_STATO,DATA,STATO,ORDINE_STATO,ORDINE_FASE FROM SIAR_UMA.dbo.vASSEGNAZIONI
	--WHERE ID_IMPRESA=@ID_IMPRESA
	
	DECLARE @UMA_PRIMO_ANNO INT,@UMA_ULTIMO_ID INT,@UMA_ULTIMO_TIPO VARCHAR(50),@UMA_ULTIMO_STATO VARCHAR(50),@UMA_ULTIMO_ANNO INT
	--SELECT TOP 1 @UMA_PRIMO_ANNO=ANNO FROM @ASSEGNAZIONI ORDER BY ANNO,ID
	--SELECT TOP 1 @UMA_ULTIMO_ID=ID,@UMA_ULTIMO_TIPO=TIPO,@UMA_ULTIMO_STATO=STATO,@UMA_ULTIMO_ANNO=ANNO
	--FROM @ASSEGNAZIONI ORDER BY ANNO DESC,ID DESC
	
	DECLARE @BIO_ANNO INT,@BIO_ODC VARCHAR(100),@BIO_ATTIVITA VARCHAR(10)
	--SELECT TOP 1 @BIO_ANNO=ANNO,@BIO_ODC=ODC,@BIO_ATTIVITA=COD_ATTIVITA FROM vBIO_NOTIFICA
	--WHERE ID_IMPRESA=@ID_IMPRESA /*AND COD_TIPO_NOTIFICA IN ('PN','VN')*/ AND COD_STATO!='P' ORDER BY DATA DESC
	
	DECLARE @EROA_ANNO INT,@EROA_NUMERO VARCHAR(20),@EROA_STATO VARCHAR(30),@EROA_ATT_MINIMA BIT
	/*SELECT TOP 1 @EROA_PRIMO_ANNO=ANNO FROM VEROA_DOMANDE WHERE ID_IMPRESA=@ID_IMPRESA AND ORDINE_FASE>10 ORDER BY ANNO,ID
	SELECT TOP 1 @EROA_ULTIMO_ID=ID,@EROA_ULTIMO_ANNO=ANNO,@EROA_ULTIMO_TIPO=TIPO_DOMANDA,@EROA_ULTIMO_STATO=STATO_DOMANDA
	FROM VEROA_DOMANDE WHERE ID_IMPRESA=@ID_IMPRESA ORDER BY ANNO DESC,ID DESC*/
	
	--SELECT @EROA_ANNO=ANNO,@EROA_NUMERO=CODICE,@EROA_STATO=STATO,@EROA_ATT_MINIMA=ATTIVITA_MINIMA
	--FROM VEROA_ELENCO WHERE ID_IMPRESA=@ID_IMPRESA

	SELECT /*PSR*/ISNULL(@NR_PR_PRESENTATI,0) AS PR_PRESENTATI,ISNULL(@NR_PR_ATTIVI,0) AS PR_ATTIVI,@ID_PR_ULTIMO AS PR_ULTIMO,
		@STATO_PR_ULTIMO AS PR_STATO_ULTIMO,/*UMA*/@UMA_PRIMO_ANNO AS UMA_PRIMO_ANNO,@UMA_ULTIMO_ID AS UMA_ULTIMO_ID,
		@UMA_ULTIMO_TIPO AS UMA_ULTIMO_TIPO,@UMA_ULTIMO_STATO AS UMA_ULTIMO_STATO,@UMA_ULTIMO_ANNO AS UMA_ULTIMO_ANNO,
		/*BIO*/@BIO_ANNO AS BIO_ANNO,@BIO_ODC AS BIO_ODC,@BIO_ATTIVITA AS BIO_ATTIVITA,
		/*EROA*/@EROA_ANNO AS EROA_ANNO,@EROA_NUMERO AS EROA_NUMERO,@EROA_STATO AS EROA_STATO,ISNULL(@EROA_ATT_MINIMA,0) AS EROA_ATT_MINIMA

