CREATE PROCEDURE [dbo].[SpVerificaCondizioniGeneraliPresentazioneDomandaAiuto]
(
	@ID_PROGETTO INT   -- PROGETTO INTEGRATO
)
AS
	--DECLARE @ID_PROGETTO INT;SET @ID_PROGETTO=69

	DECLARE @RETVAL INT,@ERRORE VARCHAR(255)
	SET @RETVAL=0 -- VALORI POSSIBILI: 0 OK, 1 WARNING, 2 ERRORE

	-- RECUPERO L'IMPRESA
	DECLARE @ID_IMPRESA INT,@ID_BANDO INT,@OPERATORE_PRESENTAZIONE CHAR(16),@ID_RLEGALE INT,@IMPRESA_ATTIVA BIT,@ID_SEDE_LEGALE INT,
		@ID_CC INT, @COD_FORMA_GIURIDICA VARCHAR(10), @ID_DIMENSIONE INT, @COD_ATECO VARCHAR(9)
	SELECT @ID_IMPRESA=P.ID_IMPRESA,@ID_BANDO=ID_BANDO,@OPERATORE_PRESENTAZIONE=UT.CF_UTENTE,@ID_RLEGALE=I.ID_RAPPRLEGALE_ULTIMO,
		@IMPRESA_ATTIVA=I.ATTIVA,@ID_SEDE_LEGALE=I.ID_SEDELEGALE_ULTIMO,@ID_CC=I.ID_CONTO_CORRENTE_ULTIMO,
		@COD_FORMA_GIURIDICA =COD_FORMA_GIURIDICA, @ID_DIMENSIONE = ID_DIMENSIONE , @COD_ATECO = I.COD_ATECO2007
	FROM vPROGETTO P INNER JOIN vIMPRESA I ON P.ID_IMPRESA=I.ID_IMPRESA  
	INNER JOIN vUTENTI UT ON P.OPERATORE=UT.ID_UTENTE
	WHERE ID_PROGETTO=@ID_PROGETTO AND ATTIVA=1
	
	--DECLARE @ENTE_PUBBLICO BIT 
	--EXEC  @ENTE_PUBBLICO = SpVerificaBeneficiarioEntePubblico @ID_IMPRESA 	
	
	--------- ERRORI
	IF @ID_IMPRESA IS NULL BEGIN 
		SET @ERRORE='I dati anagrafici dell`impresa selezionata sono incompleti. Impossibile continuare.'
		SET @RETVAL=2
	END
	-- FORMA GIURIDICA
	ELSE IF	@COD_FORMA_GIURIDICA IS NULL  BEGIN
		SET @ERRORE='I dati anagrafici dell`impresa selezionata sono incompleti. selezionare la Forma Giuridica. Impossibile continuare.'
		SET @RETVAL=2	
	END
	-- FORMA GIURIDICA
	ELSE IF	@COD_ATECO IS NULL  BEGIN
		SET @ERRORE='I dati anagrafici dell`impresa selezionata sono incompleti. selezionare il codice ATECO. Impossibile continuare.'
		SET @RETVAL=2	
	END
	-- ENTE PUBBLICO O PRIVATO
	ELSE IF	(@ID_DIMENSIONE IS NULL AND (SELECT count(*) from vIMPRESA i where i.ID_IMPRESA = @ID_IMPRESA  and I.COD_FORMA_GIURIDICA NOT IN ('1.6','2','2.1','2.2','2.3.','2.4','2.4.10','2.4.20','2.4.30','2.4.40','2.4.50','2.4.60','2.5','2.6.10','2.6.20','2.7','2.7.11','2.7.12','2.7.40','2.7.51','2.7.52','2.7.53','2.7.54','2.7.55','2.7.56','2.7.90') )>0 ) BEGIN
		SET @ERRORE='I dati anagrafici dell`impresa selezionata sono incompleti, selezionare la dimensione. Impossibile continuare.'
		SET @RETVAL=2	
	END
	ELSE IF @IMPRESA_ATTIVA=0 BEGIN
		SET @ERRORE='L`impresa selezionata non è più in attività. Impossibile continuare.'
		SET @RETVAL=2	
	END
	-- RAPPRESENTANTE LEGALE
	ELSE IF @ID_RLEGALE IS NULL BEGIN 
		SET @ERRORE='L`impresa non ha un rappresentante legale valido. Impossibile continuare.'
		SET @RETVAL=2
	END
	-- SEDE LEGALE
	ELSE IF @ID_SEDE_LEGALE IS NULL OR (SELECT COUNT(*) FROM vINDIRIZZARIO WHERE ID_INDIRIZZARIO=@ID_SEDE_LEGALE
			AND EMAIL IS NOT NULL AND TELEFONO IS NOT NULL)=0 BEGIN 
		SET @ERRORE='L`impresa non ha una sede legale valida. Impossibile continuare.'
		SET @RETVAL=2 
	END
	-- CONTO CORRENTE: SOLO PER BANDI CHE RICHIEDONO IL FASCICOLO
	ELSE IF (@ID_CC IS NULL OR (SELECT COUNT(*) FROM CONTO_CORRENTE WHERE ID_CONTO_CORRENTE=@ID_CC AND NUMERO IS NOT NULL)=0)
		AND (SELECT COUNT(*) FROM BANDO WHERE ID_BANDO=@ID_BANDO AND FASCICOLO_RICHIESTO=1)>0 BEGIN 
		SET @ERRORE='L`impresa non ha un conto corrente valido. Impossibile continuare.'
		SET @RETVAL=2
	END
	-- RELAZIONE TECNICA    (NON CONTROLLATO)
	--ELSE IF (SELECT COUNT(*) FROM PROGETTO_RELAZIONE_TECNICA WHERE ID_PROGETTO=@ID_PROGETTO)=0 BEGIN 
	--	SET @ERRORE='Per continuare è necessario compilare la relazione tecnica progettuale.'
	--	SET @RETVAL=2
	--END
	-- ALLEGATI
	ELSE IF (@ID_BANDO NOT IN (48, 49,50) AND (SELECT COUNT(*) FROM PROGETTO_ALLEGATI WHERE ID_PROGETTO=@ID_PROGETTO)=0 ) BEGIN
		SET @ERRORE='Non è stato selezionato nemmeno un allegato. Impossibile continuare.'
		SET @RETVAL=2
	END
	-- DICHIARAZIONI
	ELSE IF (SELECT COUNT(*) FROM DICHIARAZIONI_X_PROGETTO WHERE ID_PROGETTO=@ID_PROGETTO)=0 BEGIN
		SET @ERRORE='Non è stato selezionata nemmeno una dichiarazione. Impossibile continuare.'
		SET @RETVAL=2
	END
	-- SCADENZA BANDO
	ELSE IF (SELECT COUNT(*) FROM vBANDO WHERE ID_BANDO=@ID_BANDO AND DATA_SCADENZA<GETDATE())>0 BEGIN
		SET @ERRORE='Sono scaduti i termini per la presentazione della domande di adesione a questo bando di gara. Impossibile continuare.'
		SET @RETVAL=2
	END
	-- PIANO INVESTIMENTI
	ELSE IF (SELECT COUNT(*) FROM vPIANO_INVESTIMENTI WHERE ID_PROGETTO=@ID_PROGETTO AND ID_INVESTIMENTO_ORIGINALE IS NULL)= 0 BEGIN
		IF (SELECT COUNT (*) FROM BUSINESS_PLAN WHERE ID_BANDO=@ID_BANDO AND ID_QUADRO = 7 )= 0 BEGIN
			SET @ERRORE='Non è stata inserita nessuna voce sul piano investimenti. Continuare?'
			SET @RETVAL=1
		END
		ELSE
		BEGIN
			SET @ERRORE='Non è stata inserita nessuna voce sul piano degli investimenti. Impossibile continuare.'
			SET @RETVAL=2
		END
	END
	
	IF (@RETVAL IN (0,1))
	BEGIN
		-- CHECKLIST
		DECLARE @ESITO_VERIFICA BIT
		EXEC @ESITO_VERIFICA=SpVerificaCheckListDomandaDiAiuto @ID_PROGETTO,NULL,'P',@OPERATORE_PRESENTAZIONE
		IF @ESITO_VERIFICA=0 BEGIN
			SET @ERRORE='Per continuare occorre che siano positivamente soddisfatti tutti gli step obbligatori della checklist di presentazione.'
			SET @RETVAL=2
		END
		---------- WARNINGS
		ELSE BEGIN		
			-- REQUISITI SOGGETTIVI		
			IF (SELECT COUNT(*) FROM PROGETTO AS P INNER JOIN PRIORITA_X_PROGETTO AS PXP ON P.ID_PROGETTO=PXP.ID_PROGETTO 
					WHERE ISNULL(P.ID_PROG_INTEGRATO,P.ID_PROGETTO)=@ID_PROGETTO)=0 BEGIN
				SET @ERRORE='Non è stato selezionato nemmeno una requisito soggettivo di domanda. Continuare?'
				SET @RETVAL=1
			END
			-- PRIORITA X INVESTIMENTI
			--SELECT V.ID_INVESTIMENTO,ID_PRIORITA,ID_VALORE,SCELTO,VALORE FROM PIANO_INVESTIMENTI V 
			--LEFT JOIN PRIORITA_X_INVESTIMENTI PI ON V.ID_INVESTIMENTO=PI.ID_INVESTIMENTO INNER JOIN PROGETTO P ON V.ID_PROGETTO=P.ID_PROGETTO
			--WHERE V.COD_TIPO_INVESTIMENTO=1 AND (P.ID_PROGETTO=" + Progetto.IdProgetto + " OR P.ID_PROG_INTEGRATO=" + Progetto.IdProgetto + ")
		END
	END
	SELECT @RETVAL AS RETVAL,@ERRORE AS ERRORE
