
CREATE PROCEDURE [dbo].[SpZoomPrioritaPlurivaloreSql]
(
	@ID_PROGETTO INT,
	@FASE_ISTRUTTORIA bit,
	@ID_REQUISITO INT,
	@CODICE VARCHAR(50) = NULL
)
AS
	DECLARE @TESTO_QUERY NVARCHAR(4000)
	SELECT @TESTO_QUERY = QUERY_PLURIVALORE FROM PRIORITA WHERE ID_PRIORITA = @ID_REQUISITO
	
	SELECT @TESTO_QUERY=TESTO FROM zQUERY_SQL WHERE NOME=@TESTO_QUERY
	EXEC sp_executesql @TESTO_QUERY,N'@IdProgetto INT,@fase_istruttoria bit,@CODICE varchar(16)',@ID_PROGETTO,@FASE_ISTRUTTORIA,@CODICE
	
