CREATE PROCEDURE [dbo].[SpZoomUtentiFind]
(
	@NOMINATIVO VARCHAR(50)=NULL,
	@COD_ENTE VARCHAR(10)=NULL
)
AS
	SELECT TOP 8 ID_UTENTE,ID_PERSONA_FISICA,CF_UTENTE,NOMINATIVO,COD_ENTE,ID_PROFILO,PROVINCIA,COD_TIPO_ENTE,
		ENTE,PROFILO,NOMINATIVO+' - '+PROFILO+' - '+ISNULL(ENTE,'') AS DESCRIZIONE
	FROM vUTENTI WHERE (@NOMINATIVO IS NULL OR NOMINATIVO LIKE @NOMINATIVO) AND (@COD_ENTE IS NULL OR COD_ENTE=@COD_ENTE)
		AND ATTIVO=1
	ORDER BY NOMINATIVO
