CREATE PROCEDURE [dbo].[SubReportPistaControlloFinanziarioGiustificativiSpese] 
@IdDomandaPagamento int
AS
BEGIN
--declare @IdDomandaPagamento INT = 11009;

SELECT 
--PROGETTO
DP.ID_DOMANDA_PAGAMENTO,
DP.SEGNATURA,
--GIUSTIFICATIVI
G.ID_GIUSTIFICATIVO,
G.NUMERO AS NUMERO_GIUSTIFICATIVO,
G.DATA AS DATA_GIUSTIFICATIVO,
TG.DESCRIZIONE AS TIPO_GIUSTIFICATIVO,
CASE G.IVA_NON_RECUPERABILE
	WHEN 1 THEN G.IMPONIBILE + (G.IVA * G.IMPONIBILE / 100)
	ELSE G.IMPONIBILE 
END AS IMPORTO_GIUSTIFICATIVO,
CASE 
	WHEN G.DESCRIZIONE_FORNITORE IS NOT NULL 
		AND G.DESCRIZIONE_FORNITORE != ''
	THEN G.CF_FORNITORE + ' - ' + G.DESCRIZIONE_FORNITORE
	ELSE G.CF_FORNITORE 
END AS FORNITORE,
--SPESE
SS.ID_SPESA,
SS.DATA AS DATA_SPESA,
SS.ESTREMI AS ESTREMI_SPESA,
SS.IMPORTO AS IMPORTO_SPESA,
TS.DESCRIZIONE AS TIPO_SPESA,
SS.DATA AS DATA_QUIETANZA_SPESA,
PB.IMPORTO_AMMESSO AS IMPORTO_AMMESSO_RUP
FROM 
DOMANDA_DI_PAGAMENTO DP
INNER JOIN SPESE_SOSTENUTE SS ON SS.ID_DOMANDA_PAGAMENTO = dp.ID_DOMANDA_PAGAMENTO
INNER JOIN GIUSTIFICATIVI G ON SS.ID_GIUSTIFICATIVO = G.ID_GIUSTIFICATIVO
INNER JOIN TIPO_GIUSTIFICATIVO TG ON G.COD_TIPO = TG.COD_TIPO
INNER JOIN TIPO_GIUSTIFICATIVO TS ON SS.COD_TIPO = TS.COD_TIPO
INNER JOIN PAGAMENTI_BENEFICIARIO PB ON PB.ID_GIUSTIFICATIVO = G.ID_GIUSTIFICATIVO
WHERE 1 = 1
AND DP.SEGNATURA IS NOT NULL
AND ((@IdDomandaPagamento IS NULL) OR (DP.ID_DOMANDA_PAGAMENTO = @IdDomandaPagamento))
ORDER BY 
DP.ID_DOMANDA_PAGAMENTO,
G.ID_GIUSTIFICATIVO,
SS.ID_SPESA

END