SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SFC_NUTS](
	[ID_SFC_NUTS] [int] IDENTITY(1,1) NOT NULL,
	[AREA] [varchar](max) NULL,
	[COD_NUTS] [int] NULL,
	[VAL_NUTS] [varchar](max) NULL,
	[COD_PROVINCIA] [char](3) NULL,
 CONSTRAINT [PK_SFC_NUTS] PRIMARY KEY CLUSTERED 
(
	[ID_SFC_NUTS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[SFC_NUTS]  WITH CHECK ADD  CONSTRAINT [FK_SFC_NUTS_SFC_NUTS] FOREIGN KEY([COD_PROVINCIA])
REFERENCES [dbo].[PROVINCE] ([CODICE])
GO

ALTER TABLE [dbo].[SFC_NUTS] CHECK CONSTRAINT [FK_SFC_NUTS_SFC_NUTS]
GO
