CREATE TABLE [dbo].[CONTRATTI_FEM] (
    [ID_CONTRATTO_FEM]			 INT             IDENTITY (1, 1) NOT NULL,
    [ID_BANDO]					 INT             NOT NULL,
    [ID_PROGETTO]				 INT             NULL,
	[ID_IMPRESA]				 INT             NULL,
    [DATA_STIPULA_CONTRATTO]	 DATETIME        NULL,
    [SEGNATURA]					 VARCHAR (100)   NULL,
    [DATA_SEGNATURA]			 DATETIME        NULL,
    [IMPORTO]					 DECIMAL (15, 2) NULL,
    [DATA_CREAZIONE]			 DATETIME        NULL,
    [DATA_AGGIORNAMENTO]		 DATETIME        NULL,
    [OPERATORE_CREAZIONE]		 INT             NULL,
	[OPERATORE_AGGIORNAMENTO]    INT             NULL,
	[ID_DOMANDA_PAGAMENTO]		 INT			 NULL,
	[NUMERO]					 VARCHAR(MAX)	 NULL,
	[ID_PROGETTO_RIF]			 INT			 NULL,
    CONSTRAINT [PK_CONTRATTI_FEM] PRIMARY KEY CLUSTERED ([ID_CONTRATTO_FEM] ASC),
	CONSTRAINT [FK_CONTRATTI_FEM_IMPRESA] FOREIGN KEY ([ID_IMPRESA]) REFERENCES [dbo].[IMPRESA] ([ID_IMPRESA]),
	CONSTRAINT [FK_CONTRATTI_FEM_DOMANDA_DI_PAGAMENTO] FOREIGN KEY ([ID_DOMANDA_PAGAMENTO]) REFERENCES [dbo].[DOMANDA_DI_PAGAMENTO] ([ID_DOMANDA_PAGAMENTO])
);

