CREATE VIEW vIstruttoria_Domande_Aiuto
AS
SELECT 
	B.ID_BANDO, 
	B.DESCRIZIONE, 
	B.DATA_SCADENZA, 
	P.ID_PROGETTO, 
	P.DATA, 
	P.STATO, 
	P.ID_IMPRESA, 
	I.CODICE_FISCALE, 
	I.RAGIONE_SOCIALE, 
	CB.ID_UTENTE, 
	P.COD_STATO
FROM vCOLLABORATORI_X_BANDO CB 
	JOIN vBANDO B on CB.ID_BANDO = B.ID_BANDO 
	JOIN vPROGETTO P ON P.ID_PROGETTO = CB.ID_PROGETTO 
	JOIN vIMPRESA I ON I.ID_IMPRESA=P.ID_IMPRESA
WHERE 1 = 1
	AND CB.ATTIVO = 1
GO