CREATE VIEW [dbo].[VCONTRATTI_FEM_PAGAMENTI]
AS
SELECT 
	CON.ID_BANDO,
	CON.ID_PROGETTO AS ID_PROGETTO_CONTRATTO,
	CON.DATA_STIPULA_CONTRATTO,
	CON.SEGNATURA AS SEGNATURA_CONTRATTO,
	CON.IMPORTO AS IMPORTO_CONTRATTO,
	CON.ID_IMPRESA AS ID_IMPRESA_CONTRATTO,
	PAG.*,
	IMP.RAGIONE_SOCIALE AS IMPRESA_PAGAMENTO,
	IMP.CODICE_FISCALE AS CODICE_FISCALE_IMPRESA_PAGAMENTO,
	IMP.CUAA AS CUAA_IMPRESA_PAGAMENTO,
	TIP.DESCRIZIONE AS TIPO_PAGAMENTO
FROM CONTRATTI_FEM_PAGAMENTI PAG
	JOIN TIPO_GIUSTIFICATIVO TIP ON PAG.COD_TIPO = TIP.COD_TIPO
	JOIN CONTRATTI_FEM CON ON PAG.ID_CONTRATTO_FEM = CON.ID_CONTRATTO_FEM
	LEFT JOIN VIMPRESA IMP ON PAG.ID_IMPRESA = IMP.ID_IMPRESA;

GO