-- DROP VIEW VPAGAMENTI_RICHIESTI_FEM;
CREATE VIEW VPAGAMENTI_RICHIESTI_FEM
AS
SELECT 
	PG.*, 
	PROG.ID_BANDO,
	PROG.ID_PROGETTO,
	CON.ID_IMPRESA AS ID_IMPRESA_CONTRATTO,
	IMP.RAGIONE_SOCIALE AS IMPRESA_CONTRATTO,
	CON.IMPORTO AS IMPORTO_CONTRATTO,
	CON.SEGNATURA AS SEGNATURA_CONTRATTO,
	CON.DATA_STIPULA_CONTRATTO AS DATA_CONTRATTO, 
	GIU.NUMERO AS NUMERO_GIUSTIFICATIVO,
	GIU.COD_TIPO AS COD_TIPO_GIUSTIFICATIVO,
	TI.DESCRIZIONE AS TIPO_GIUSTIFICATIVO,
	GIU.DATA AS DATA_GIUSTIFICATIVO,
	GIU.IMPONIBILE AS IMPONIBILE_GIUSTIFICATIVO,
	GIU.IVA AS IVA_GIUSTIFICATIVO,
	GIU.DESCRIZIONE AS DESCRIZIONE_GIUSTIFICATIVO,
	GIU.CF_FORNITORE AS CF_FORNITORE_GIUSTIFICATIVO,
	GIU.DESCRIZIONE_FORNITORE AS DESCRIZIONE_FORNITORE_GIUSTIFICATIVO,
	GIU.IVA_NON_RECUPERABILE AS IVA_NON_RECUPERABILE_GIUSTIFICATIVO,
	GIU.ID_FILE AS ID_FILE_GIUSTIFICATIVO,
	GIU.IN_INTEGRAZIONE AS IN_INTEGRAZIONE_GIUSTIFICATIVO,
	GIU.ID_FILE_MODIFICATO_INTEGRAZIONE AS ID_FILE_MODIFICATO_INTEGRAZIONE_GIUSTIFICATIVO
FROM PAGAMENTI_RICHIESTI_FEM PG	
	JOIN PIANO_INVESTIMENTI P ON P.ID_INVESTIMENTO = PG.ID_INVESTIMENTO
	JOIN PROGETTO PROG ON PROG.ID_PROGETTO = P.ID_PROGETTO
	LEFT JOIN CONTRATTI_FEM CON ON CON.ID_CONTRATTO_FEM = PG.ID_CONTRATTO
	LEFT JOIN vIMPRESA IMP ON IMP.ID_IMPRESA = CON.ID_IMPRESA
	LEFT JOIN GIUSTIFICATIVI GIU ON GIU.ID_GIUSTIFICATIVO = PG.ID_GIUSTIFICATIVO 
	LEFT JOIN TIPO_GIUSTIFICATIVO TI ON TI.COD_TIPO = GIU.COD_TIPO

GO


