CREATE PROCEDURE SpGetRevisioniProgettoValideFem
(
	@ID_PROGETTO INT 
)
AS
	
	SELECT TOP 1 R.*, 
		B.DESCRIZIONE 
	FROM CTE_TESTATA_VALIDAZIONE R
		JOIN BANDO B ON B.ID_BANDO = R.ID_BANDO
	WHERE 1 = 1
		AND (@ID_PROGETTO IS NULL OR R.ID_PROGETTO = @ID_PROGETTO) 
		AND R.ID_BANDO IN (SELECT DISTINCT ID_BANDO 
							FROM vBando_Config BG 
							WHERE BG.Cod_Tipo = 'TPAPPALTO' 
							AND BG.VALORE_DESCRIZIONE = 'Strumenti finanziari')
		AND ID_LOTTO IS NOT NULL
		AND R.APPROVATA IS NOT NULL
		AND (R.AUTOVALUTAZIONE IS NULL OR R.AUTOVALUTAZIONE = 0)
	ORDER BY DATA_APPROVAZIONE DESC
GO