CREATE PROCEDURE SpPsrGetDomandePerRevisioneByRupAndBando
(
    @ID_UTENTE INT,
	@ID_BANDO INT = NULL
)
AS

 -- QUI SELEZIONO LE DOMANDE DI PAGAMENTO DI ENTI PUBBLICI
SELECT 
	DPAG.ID_DOMANDA_PAGAMENTO,
	DPAG.COD_TIPO,
	DPAG.ID_PROGETTO,
	DPAG.DATA_INSERIMENTO,
	DPAG.DATA_MODIFICA,
	DPAG.COD_ENTE,
	DPAG.SEGNATURA,
	DPAG.DESCRIZIONE,
	DPAG.COD_FASE,
	DPAG.FASE,
	DPAG.ORDINE,
	DPAG.ID_FIDEJUSSIONE,
	DPAG.OPERATORE,
	DPAG.CF_OPERATORE,
	DPAG.SEGNATURA_ALLEGATI,
	DPAG.DATA_CERTIFICAZIONE_ANTIMAFIA,
	DPAG.APPROVATA,
	DPAG.SEGNATURA_APPROVAZIONE,
	DPAG.CF_ISTRUTTORE,
	DPAG.DATA_APPROVAZIONE,
	DPAG.SEGNATURA_SECONDA_APPROVAZIONE,
	DPAG.ANNULLATA,
	DPAG.SEGNATURA_ANNULLAMENTO,
	DPAG.CF_OPERATORE_ANNULLAMENTO,
	DPAG.DATA_ANNULLAMENTO,
	DPAG.VALIDITA_VERSIONE_ADC,
	DPAG.ID_VARIAZIONE_ACCERTATA,
	DPAG.PREDISPOSTA_A_CONTROLLO,
	DPAG.VISITA_INSITU_ESITO,
	CONVERT(VARCHAR(MAX), DPAG.VISITA_INSITU_NOTE) AS VISITA_INSITU_NOTE,
	DPAG.CONTROLLO_INLOCO_ESITO,
	CONVERT(VARCHAR(MAX), DPAG.CONTROLLO_INLOCO_NOTE) AS CONTROLLO_INLOCO_NOTE,
	CONVERT(VARCHAR(MAX), DPAG.VALUTAZIONE_ISTRUTTORE) AS VALUTAZIONE_ISTRUTTORE,
	DPAG.VERIFICA_PAGAMENTI_ESITO,
	DPAG.VERIFICA_PAGAMENTI_MESSAGGIO,
	DPAG.VERIFICA_PAGAMENTI_DATA,
	DPAG.DATA_PREDISPOSIZIONE_A_CONTROLLO,
	DPAG.NOMINATIVO_OPERATORE_ANNULLAMENTO,
	DPAG.ISTRUTTORE,
	DPAG.FIRMA_PREDISPOSTA,
	DPAG.IN_INTEGRAZIONE,
	DPAG.FIRMA_PREDISPOSTA_RUP,
	DPAG.ID_BANDO,
	DPAG.DESCRIZIONE_BANDO
FROM
(
	SELECT 
		D.*,
		P.ID_BANDO,
		P.ID_IMPRESA,
		B.DESCRIZIONE AS DESCRIZIONE_BANDO
	FROM vDOMANDA_DI_PAGAMENTO D 
		JOIN PROGETTO P ON D.ID_PROGETTO = P.ID_PROGETTO
		JOIN DATI_MONITORAGGIO_FESR DMF ON DMF.ID_PROGETTO = P.ID_PROGETTO 
		JOIN BANDO B ON P.ID_BANDO = B.ID_BANDO
		LEFT JOIN CTE_TESTATA_VALIDAZIONE R ON D.ID_DOMANDA_PAGAMENTO = R.ID_DOMANDA_PAGAMENTO 
	WHERE 1 = 1
		AND ((@ID_BANDO IS NULL 
				AND P.ID_BANDO IN (SELECT DISTINCT ID_BANDO 
									FROM BANDO_RESPONSABILI 
									WHERE ID_UTENTE = @ID_UTENTE 
										AND ATTIVO = 1 
										AND PROVINCIA IS NULL) ) 
			OR P.ID_BANDO = @ID_BANDO) 
		AND B.ID_BANDO NOT IN (SELECT DISTINCT ID_BANDO 
								FROM vBando_Config BG 
								WHERE BG.Cod_Tipo = 'TPAPPALTO' 
								AND BG.VALORE_DESCRIZIONE = 'Strumenti finanziari')
		AND D.ANNULLATA               = 0 
		AND D.APPROVATA               = 1
		AND D.SEGNATURA_APPROVAZIONE  IS NOT NULL 
		AND R.ID_DOMANDA_PAGAMENTO    IS NULL
		AND DMF.CUP_NATURA NOT IN ('06', '07')
) DPAG
	JOIN vIMPRESA I ON DPAG.ID_IMPRESA = I.ID_IMPRESA 
--AND I.COD_FORMA_GIURIDICA  IN	(--'1.6',
--                                        '2',
--                                        '2.1',
--                                        '2.2',
--                                        '2.3.',
--                                        '2.4',
--                                        '2.4.10',
--                                        '2.4.20',
--                                        '2.4.30',
--                                        '2.4.40',
--                                        '2.4.50',
--                                        '2.4.60',
--                                        '2.5',
--                                        '2.6.10',
--                                        '2.6.20',
--                                        '2.7',
--                                        '2.7.11',
--                                        '2.7.12',
--                                        '2.7.40',
--                                        '2.7.51',
--                                        '2.7.52',
--                                        '2.7.53',
--                                        '2.7.54',
--                                        '2.7.55',
--                                        '2.7.56',
--                                        '2.7.90'
--                                        )

 -- QUI FACCIO LA UNION CON DOMANDE DI PAGAMENTO PER ENTI NON PUBBLICI 
UNION

SELECT 
	D.ID_DOMANDA_PAGAMENTO,
	D.COD_TIPO,
	D.ID_PROGETTO,
	D.DATA_INSERIMENTO,
	D.DATA_MODIFICA,
	D.COD_ENTE,
	D.SEGNATURA,
	D.DESCRIZIONE,
	D.COD_FASE,
	D.FASE,
	D.ORDINE,
	D.ID_FIDEJUSSIONE,
	D.OPERATORE,
	D.CF_OPERATORE,
	D.SEGNATURA_ALLEGATI,
	D.DATA_CERTIFICAZIONE_ANTIMAFIA,
	D.APPROVATA,
	D.SEGNATURA_APPROVAZIONE,
	D.CF_ISTRUTTORE,
	D.DATA_APPROVAZIONE,
	D.SEGNATURA_SECONDA_APPROVAZIONE,
	D.ANNULLATA,
	D.SEGNATURA_ANNULLAMENTO,
	D.CF_OPERATORE_ANNULLAMENTO,
	D.DATA_ANNULLAMENTO,
	D.VALIDITA_VERSIONE_ADC,
	D.ID_VARIAZIONE_ACCERTATA,
	D.PREDISPOSTA_A_CONTROLLO,
	D.VISITA_INSITU_ESITO,
	CONVERT(VARCHAR(MAX), D.VISITA_INSITU_NOTE) AS VISITA_INSITU_NOTE,
	D.CONTROLLO_INLOCO_ESITO,
	CONVERT(VARCHAR(MAX), D.CONTROLLO_INLOCO_NOTE) AS CONTROLLO_INLOCO_NOTE,
	CONVERT(VARCHAR(MAX), D.VALUTAZIONE_ISTRUTTORE) AS VALUTAZIONE_ISTRUTTORE,
	D.VERIFICA_PAGAMENTI_ESITO,
	D.VERIFICA_PAGAMENTI_MESSAGGIO,
	D.VERIFICA_PAGAMENTI_DATA,
	D.DATA_PREDISPOSIZIONE_A_CONTROLLO,
	D.NOMINATIVO_OPERATORE_ANNULLAMENTO,
	D.ISTRUTTORE,
	D.FIRMA_PREDISPOSTA,
	D.IN_INTEGRAZIONE,
	D.FIRMA_PREDISPOSTA_RUP,
	P.ID_BANDO,
	B.DESCRIZIONE AS DESCRIZIONE_BANDO
FROM PROGETTO P 
	JOIN vIMPRESA I ON  P.ID_IMPRESA = I.ID_IMPRESA 
--AND I.COD_FORMA_GIURIDICA NOT IN	(--'1.6',
--                        '2',
--                        '2.1',
--                        '2.2',
--                        '2.3.',
--                        '2.4',
--                        '2.4.10',
--                        '2.4.20',
--                        '2.4.30',
--                        '2.4.40',
--                        '2.4.50',
--                        '2.4.60',
--                        '2.5',
--                        '2.6.10',
--                        '2.6.20',
--                        '2.7',
--                        '2.7.11',
--                        '2.7.12',
--                        '2.7.40',
--                        '2.7.51',
--                        '2.7.52',
--                        '2.7.53',
--                        '2.7.54',
--                        '2.7.55',
--                        '2.7.56',
--                        '2.7.90'
--                        )
	JOIN BANDO B ON P.ID_BANDO = B.ID_BANDO
	JOIN vDOMANDA_DI_PAGAMENTO D ON D.ID_PROGETTO = P.ID_PROGETTO
    LEFT JOIN  (SELECT  Q.ID_DOMANDA_PAGAMENTO, 
					SUM(ISNULL(Q.MANDATO_IMPORTO, 0))   AS IMPORTO_LIQUIDATO,
					SUM(ISNULL(Q.QUIETANZA_IMPORTO, 0)) AS IMPORTO_QUIETANZA
				FROM DOMANDA_PAGAMENTO_LIQUIDAZIONE Q
					-- AND PROG.ID_BANDO = @ID_BANDO
				GROUP BY Q.ID_DOMANDA_PAGAMENTO ) MANDATI ON MANDATI.ID_DOMANDA_PAGAMENTO = D.ID_DOMANDA_PAGAMENTO 
	LEFT JOIN (SELECT  F.ID_DOMANDA_PAGAMENTO, 
					SUM(ISNULL(F.IMPORTO, 0))   AS IMPORTO_DECRETO
				FROM DECRETI_X_DOM_PAG_ESPORTAZIONE F
				-- AND F.ID_BANDO = @ID_BANDO
				GROUP BY F.ID_DOMANDA_PAGAMENTO ) DECRETI on DECRETI.ID_DOMANDA_PAGAMENTO = D.ID_DOMANDA_PAGAMENTO
	JOIN DOMANDA_DI_PAGAMENTO_ESPORTAZIONE ESP ON ESP.ID_DOMANDA_PAGAMENTO = D.ID_DOMANDA_PAGAMENTO
	JOIN DATI_MONITORAGGIO_FESR DMF ON P.ID_PROGETTO = DMF.ID_PROGETTO
	LEFT JOIN CTE_TESTATA_VALIDAZIONE R ON D.ID_DOMANDA_PAGAMENTO = R.ID_DOMANDA_PAGAMENTO
	WHERE 1 = 1
		AND ((@ID_BANDO IS NULL
				 AND P.ID_BANDO IN (SELECT DISTINCT ID_BANDO 
									FROM BANDO_RESPONSABILI 
									WHERE ID_UTENTE = @ID_UTENTE 
										AND ATTIVO = 1 
										AND PROVINCIA IS NULL) ) 
			OR P.ID_BANDO = @ID_BANDO) 
		AND B.ID_BANDO NOT IN (SELECT DISTINCT ID_BANDO 
							FROM vBando_Config BG 
							WHERE BG.Cod_Tipo = 'TPAPPALTO' 
								AND BG.VALORE_DESCRIZIONE = 'Strumenti finanziari')
		AND( (MANDATI.IMPORTO_LIQUIDATO > 0 
				AND MANDATI.IMPORTO_QUIETANZA > 0 
				AND DECRETI.IMPORTO_DECRETO   > 0
				AND ESP.IMPORTO_AMMESSO       IS NOT NULL 
				AND ESP.IMPORTO_AMMESSO       > 0
				AND MANDATI.IMPORTO_LIQUIDATO = MANDATI.IMPORTO_QUIETANZA 
				AND MANDATI.IMPORTO_LIQUIDATO = DECRETI.IMPORTO_DECRETO
				AND ESP.IMPORTO_AMMESSO = MANDATI.IMPORTO_LIQUIDATO )
			OR (ESP.IMPORTO_AMMESSO			= 0
				AND MANDATI.IMPORTO_QUIETANZA IS NULL
				AND DECRETI.IMPORTO_DECRETO   IS NULL) )
		AND D.ANNULLATA = 0 
		AND D.APPROVATA = 1
		AND D.SEGNATURA_APPROVAZIONE  IS NOT NULL 
		AND R.ID_DOMANDA_PAGAMENTO    IS NULL
		AND DMF.CUP_NATURA IN ('06', '07')
GO