
CREATE PROCEDURE SpPsrRevisioneRiepilogo
(
	@ID_BANDO INT
)
AS
	--DECLARE @ID_BANDO INT=755
	
	DECLARE @NR_PAG INT,@NR_PAG_ISTRUITE INT,@NR_PAG_NEI_LOTTI INT,@NR_PAG_VALIDATE INT
	SELECT @NR_PAG=COUNT(*),@NR_PAG_ISTRUITE=SUM(CASE WHEN D.SEGNATURA_APPROVAZIONE IS NOT NULL THEN 1 ELSE 0 END),
	@NR_PAG_NEI_LOTTI=SUM(CASE WHEN R.ID_LOTTO IS NOT NULL THEN 1 ELSE 0 END),
	@NR_PAG_VALIDATE=SUM(CASE WHEN (L.REVISIONE_CONCLUSA=1 OR (L.NUMERO_ESTRAZIONI>0 AND R.SELEZIONATA_X_REVISIONE=0)
		OR R.SEGNATURA_SECONDA_REVISIONE IS NOT NULL OR (R.SEGNATURA_REVISIONE IS NOT NULL AND R.APPROVATA=1)) THEN 1 ELSE 0 END)

	FROM DOMANDA_DI_PAGAMENTO D INNER JOIN PROGETTO P ON D.ID_PROGETTO=P.ID_PROGETTO
	LEFT JOIN CTE_TESTATA_VALIDAZIONE R ON D.ID_DOMANDA_PAGAMENTO=R.ID_DOMANDA_PAGAMENTO
	LEFT JOIN LOTTO_DI_REVISIONE L ON R.ID_LOTTO=L.ID_LOTTO
	WHERE P.ID_BANDO=@ID_BANDO --AND D.SEGNATURA IS NOT NULL

	DECLARE @NR_LOTTI INT,@NR_LOTTI_CAMPIONATI INT,@NR_LOTTI_CONCLUSI INT
	SELECT @NR_LOTTI=COUNT(*),@NR_LOTTI_CAMPIONATI=SUM(NUMERO_ESTRAZIONI),
		@NR_LOTTI_CONCLUSI=SUM(CASE WHEN REVISIONE_CONCLUSA=1 THEN 1 ELSE 0 END)
	FROM LOTTO_DI_REVISIONE WHERE ID_BANDO=@ID_BANDO

	SELECT @NR_PAG AS NR_PAG_PERVENUTE,ISNULL(@NR_PAG_ISTRUITE,0) AS NR_PAG_ISTRUITE,ISNULL(@NR_PAG_NEI_LOTTI,0) AS NR_PAG_NEI_LOTTI,
		ISNULL(@NR_PAG_VALIDATE,0) AS NR_PAG_VALIDATE,@NR_LOTTI AS NR_LOTTI,ISNULL(@NR_LOTTI_CAMPIONATI,0) AS NR_LOTTI_CAMPIONATI,
		ISNULL(@NR_LOTTI_CONCLUSI,0) AS NR_LOTTI_CONCLUSI

GO
