-- DROP PROCEDURE SpGetTestataValidazioneDomandeRup
/* BACKUP
CREATE PROCEDURE SpGetTestataValidazioneDomandeRup
(
	@ID_UTENTE INT,
	@ID_BANDO INT = NULL,
	@ID_PROGETTO INT = NULL,
	@ID_DOMANDA_PAGAMENTO INT = NULL
)
AS
	DECLARE @CF_VALIDATORE VARCHAR(16)

	SELECT @CF_VALIDATORE = CF_UTENTE 
	FROM vUTENTI 
	WHERE ID_UTENTE = @ID_UTENTE
	
	SELECT R.*, 
		B.DESCRIZIONE 
	FROM VTESTATA_VALIDAZIONE R
		JOIN BANDO B ON B.ID_BANDO = R.ID_BANDO
	WHERE 1 = 1
		AND ((@ID_BANDO IS NULL 
				AND R.ID_BANDO IN (SELECT DISTINCT ID_BANDO 
									FROM BANDO_RESPONSABILI 
									WHERE ID_UTENTE = @ID_UTENTE 
									AND ATTIVO = 1)) 
			OR R.ID_BANDO = @ID_BANDO) 
		AND (@ID_PROGETTO IS NULL OR R.ID_PROGETTO = @ID_PROGETTO) 
		AND (@ID_DOMANDA_PAGAMENTO IS NULL OR R.ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO) 
		AND R.ID_BANDO NOT IN (SELECT DISTINCT ID_BANDO 
								FROM vBando_Config BG 
								WHERE BG.Cod_Tipo = 'TPAPPALTO' 
								AND BG.VALORE_DESCRIZIONE = 'Strumenti finanziari') 
		AND ID_LOTTO IS NOT NULL

	UNION

	SELECT R.*, 
		B.DESCRIZIONE 
	FROM VTESTATA_VALIDAZIONE R
		JOIN BANDO B ON B.ID_BANDO = R.ID_BANDO
	WHERE 1 = 1
		AND (@ID_BANDO IS NULL OR R.ID_BANDO = @ID_BANDO) 
		AND (@ID_PROGETTO IS NULL OR R.ID_PROGETTO = @ID_PROGETTO) 
		AND (@ID_DOMANDA_PAGAMENTO IS NULL OR R.ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO)
		AND R.ID_BANDO NOT IN (SELECT DISTINCT ID_BANDO 
								FROM vBando_Config BG 
								WHERE BG.Cod_Tipo = 'TPAPPALTO' 
								AND BG.VALORE_DESCRIZIONE = 'Strumenti finanziari') 
		AND ID_LOTTO IS NOT NULL 
		AND CF_VALIDATORE = @CF_VALIDATORE
GO
*/

CREATE PROCEDURE SpGetTestataValidazioneDomandeRup
(
	@ID_UTENTE INT,
	@ID_BANDO INT = NULL,
	@ID_PROGETTO INT = NULL,
	@ID_DOMANDA_PAGAMENTO INT = NULL
)
AS
	DECLARE @CF_VALIDATORE VARCHAR(16)

	SELECT @CF_VALIDATORE = CF_UTENTE 
	FROM vUTENTI 
	WHERE ID_UTENTE = @ID_UTENTE;

	WITH CTE AS
		(
		SELECT R.*, 
			B.DESCRIZIONE,
			ROW_NUMBER() OVER (PARTITION BY R.ID_DOMANDA_PAGAMENTO ORDER BY R.DATA_INSERIMENTO DESC) AS RN
		FROM VTESTATA_VALIDAZIONE R
			JOIN BANDO B ON B.ID_BANDO = R.ID_BANDO
		WHERE 1 = 1
			AND ((@ID_BANDO IS NULL 
					AND R.ID_BANDO IN (SELECT DISTINCT ID_BANDO 
										FROM BANDO_RESPONSABILI 
										WHERE ID_UTENTE = @ID_UTENTE 
										AND ATTIVO = 1)) 
				OR R.ID_BANDO = @ID_BANDO) 
			AND (@ID_PROGETTO IS NULL OR R.ID_PROGETTO = @ID_PROGETTO) 
			AND (@ID_DOMANDA_PAGAMENTO IS NULL OR R.ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO) 
			AND R.ID_BANDO NOT IN (SELECT DISTINCT ID_BANDO 
									FROM vBando_Config BG 
									WHERE BG.Cod_Tipo = 'TPAPPALTO' 
									AND BG.VALORE_DESCRIZIONE = 'Strumenti finanziari') 
			AND R.SEGNATURA_APPROVAZIONE_DOMANDA IS NOT NULL
			AND ID_LOTTO IS NOT NULL
		),
		CTE2 AS
		(
			SELECT R.*, 
				B.DESCRIZIONE,
				ROW_NUMBER() OVER (PARTITION BY R.ID_DOMANDA_PAGAMENTO ORDER BY R.DATA_INSERIMENTO DESC) AS RN 
			FROM VTESTATA_VALIDAZIONE R
				JOIN BANDO B ON B.ID_BANDO = R.ID_BANDO
			WHERE 1 = 1
				AND (@ID_BANDO IS NULL OR R.ID_BANDO = @ID_BANDO) 
				AND (@ID_PROGETTO IS NULL OR R.ID_PROGETTO = @ID_PROGETTO) 
				AND (@ID_DOMANDA_PAGAMENTO IS NULL OR R.ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO)
				AND R.ID_BANDO NOT IN (SELECT DISTINCT ID_BANDO 
										FROM vBando_Config BG 
										WHERE BG.Cod_Tipo = 'TPAPPALTO' 
										AND BG.VALORE_DESCRIZIONE = 'Strumenti finanziari') 
				AND R.SEGNATURA_APPROVAZIONE_DOMANDA IS NOT NULL
				AND ID_LOTTO IS NOT NULL 
				AND CF_VALIDATORE = @CF_VALIDATORE
		)

	SELECT *
	FROM CTE
	WHERE RN = 1

	UNION

	SELECT *
	FROM CTE2
	WHERE RN = 1

GO