CREATE PROCEDURE [dbo].[ZProgettoComunicazioniFindFindcomunicazioneriferimento]
(
	@IdComunicazioneRiferimentoequalthis INT
)
AS
	declare @sql nvarchar(4000);
	declare @lensql int;
	set @lensql=0;
	SET @sql = 'SELECT ID, ID_PROGETTO, ID_DOMANDA_PAGAMENTO, ID_VARIANTE, COD_TIPO, DATA, SEGNATURA, OPERATORE, ID_NOTE, ISTRUTTORE, ESITO, ID_DECRETO, ID_COMUNICAZIONE_RIFERIMENTO, DIREZIONE, TIPO_SEGNATURA, GIORNI_PREVISTI, FLAG_DOMANDA_AIUTO, FLAG_DOMANDA_PAGAMENTO, FLAG_VARIANTE, NOMINATIVO_OPERATORE, CF_OPERATORE, CF_ISTRUTTORE, NOMINATIVO_ISTRUTTORE, NUM_ATTO, DATA_ATTO, DESCRIZIONE_ATTO, ID_BANDO, CUAA, CODICE_FISCALE, RAGIONE_SOCIALE, PREDISPOSTA_ALLA_FIRMA, DATA_ISTRUTTORIA, SEGNATURA_ISTRUTTORIA, ID_NOTE_ISTRUTTORIA, COD_ENTE_EMETTITORE, ID_COMUNE, ENTE, COD_TIPO_ENTE FROM vPROGETTO_COMUNICAZIONI WHERE 1=1';
	IF (@IdComunicazioneRiferimentoequalthis IS NOT NULL) BEGIN SET @sql = @sql + ' AND (ID_COMUNICAZIONE_RIFERIMENTO = @IdComunicazioneRiferimentoequalthis)'; set @lensql=@lensql+len(@IdComunicazioneRiferimentoequalthis);end;
	set @lensql=@lensql+len(@sql);
	if (@lensql<3000)
	exec sp_executesql @sql,N'@IdComunicazioneRiferimentoequalthis INT',@IdComunicazioneRiferimentoequalthis ;
	else
		SELECT ID, ID_PROGETTO, ID_DOMANDA_PAGAMENTO, ID_VARIANTE, COD_TIPO, DATA, SEGNATURA, OPERATORE, ID_NOTE, ISTRUTTORE, ESITO, ID_DECRETO, ID_COMUNICAZIONE_RIFERIMENTO, DIREZIONE, TIPO_SEGNATURA, GIORNI_PREVISTI, FLAG_DOMANDA_AIUTO, FLAG_DOMANDA_PAGAMENTO, FLAG_VARIANTE, NOMINATIVO_OPERATORE, CF_OPERATORE, CF_ISTRUTTORE, NOMINATIVO_ISTRUTTORE, NUM_ATTO, DATA_ATTO, DESCRIZIONE_ATTO, ID_BANDO, CUAA, CODICE_FISCALE, RAGIONE_SOCIALE, PREDISPOSTA_ALLA_FIRMA, DATA_ISTRUTTORIA, SEGNATURA_ISTRUTTORIA, ID_NOTE_ISTRUTTORIA, COD_ENTE_EMETTITORE, ID_COMUNE, ENTE, COD_TIPO_ENTE
		FROM vPROGETTO_COMUNICAZIONI
		WHERE 
			((@IdComunicazioneRiferimentoequalthis IS NULL) OR ID_COMUNICAZIONE_RIFERIMENTO = @IdComunicazioneRiferimentoequalthis)
		


GO
EXECUTE sp_addextendedproperty @name = N'backup', @value = 'CREATE PROCEDURE [dbo].[ZProgettoComunicazioniFindFindcomunicazioneriferimento]
(
	@IdComunicazioneRiferimentoequalthis INT
)
AS
	declare @sql nvarchar(4000);
	declare @lensql int;
	set @lensql=0;
	SET @sql = ''SELECT ID, ID_PROGETTO, ID_DOMANDA_PAGAMENTO, ID_VARIANTE, COD_TIPO, DATA, SEGNATURA, OPERATORE, ID_NOTE, ISTRUTTORE, ESITO, ID_DECRETO, ID_COMUNICAZIONE_RIFERIMENTO, DIREZIONE, TIPO_SEGNATURA, GIORNI_PREVISTI, FLAG_DOMANDA_AIUTO, FLAG_DOMANDA_PAGAMENTO, FLAG_VARIANTE, NOMINATIVO_OPERATORE, CF_OPERATORE, CF_ISTRUTTORE, NOMINATIVO_ISTRUTTORE, NUM_ATTO, DATA_ATTO, DESCRIZIONE_ATTO, ID_BANDO, CUAA, CODICE_FISCALE, RAGIONE_SOCIALE, PREDISPOSTA_ALLA_FIRMA, DATA_ISTRUTTORIA, SEGNATURA_ISTRUTTORIA, ID_NOTE_ISTRUTTORIA, COD_ENTE_EMETTITORE, ID_COMUNE, ENTE, COD_TIPO_ENTE FROM vPROGETTO_COMUNICAZIONI WHERE 1=1'';
	IF (@IdComunicazioneRiferimentoequalthis IS NOT NULL) BEGIN SET @sql = @sql + '' AND (ID_COMUNICAZIONE_RIFERIMENTO = @IdComunicazioneRiferimentoequalthis)''; set @lensql=@lensql+len(@IdComunicazioneRiferimentoequalthis);end;
	set @lensql=@lensql+len(@sql);
	if (@lensql<3000)
	exec sp_executesql @sql,N''@IdComunicazioneRiferimentoequalthis INT'',@IdComunicazioneRiferimentoequalthis ;
	else
		SELECT ID, ID_PROGETTO, ID_DOMANDA_PAGAMENTO, ID_VARIANTE, COD_TIPO, DATA, SEGNATURA, OPERATORE, ID_NOTE, ISTRUTTORE, ESITO, ID_DECRETO, ID_COMUNICAZIONE_RIFERIMENTO, DIREZIONE, TIPO_SEGNATURA, GIORNI_PREVISTI, FLAG_DOMANDA_AIUTO, FLAG_DOMANDA_PAGAMENTO, FLAG_VARIANTE, NOMINATIVO_OPERATORE, CF_OPERATORE, CF_ISTRUTTORE, NOMINATIVO_ISTRUTTORE, NUM_ATTO, DATA_ATTO, DESCRIZIONE_ATTO, ID_BANDO, CUAA, CODICE_FISCALE, RAGIONE_SOCIALE, PREDISPOSTA_ALLA_FIRMA, DATA_ISTRUTTORIA, SEGNATURA_ISTRUTTORIA, ID_NOTE_ISTRUTTORIA, COD_ENTE_EMETTITORE, ID_COMUNE, ENTE, COD_TIPO_ENTE
		FROM vPROGETTO_COMUNICAZIONI
		WHERE 
			((@IdComunicazioneRiferimentoequalthis IS NULL) OR ID_COMUNICAZIONE_RIFERIMENTO = @IdComunicazioneRiferimentoequalthis)
		

', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'PROCEDURE', @level1name = N'ZProgettoComunicazioniFindFindcomunicazioneriferimento';

