CREATE PROCEDURE [dbo].[ZRegistroRecuperoFindGetcollectionreport]
(
	@IdProgrammazioneequalthis INT, 
	@IdProgettoequalthis INT, 
	@DataAvvioeqgreaterthanthis DATETIME, 
	@DataAvvioeqlessthanthis DATETIME, 
	@IdTipoRecuperoequalthis INT, 
	@Recuperabileequalthis BIT, 
	@Storicoequalthis BIT
)
AS
	declare @sql nvarchar(4000);
	declare @lensql int;
	set @lensql=0;
	SET @sql = 'SELECT ID_REGISTRO_RECUPERO, DATA_INSERIMENTO, CF_INSERIMENTO, DATA_MODIFICA, CF_MODIFICA, ID_REGISTRO_IRREGOLARITA, DATA_AVVIO, DATA_PROBABILE_CONCLUSIONE, IMPORTO_DA_RECUPERARE_UE, IMPORTO_DA_RECUPERARE_NAZIONALE, IMPORTO_DA_RECUPERARE_PUBBLICO, IMPORTO_DETRATTO_UE, IMPORTO_DETRATTO_NAZIONALE, IMPORTO_DETRATTO_PUBBLICO, IMPORTO_RECUPERATO_UE, IMPORTO_RECUPERATO_PUBBLICO, IMPORTO_RECUPERATO_NAZIONALE, SALDO_DA_RECUPERARE_UE, SALDO_DA_RECUPERARE_NAZIONALE, SALDO_DA_RECUPERARE_PUBBLICO, IMPORTO_VERSATO_UE, IMPORTO_RITENUTO_STATO, DATA_CONCLUSIONE, ID_PROCEDURE_AVVIATE, ID_TIPO_PROCEDURE_AVVIATE, DATA_AVVIO_PROCEDURE, DATA_PROBABILE_CONCLUSIONE_PROCEDURE, ID_TIPO_RECUPERO, ID_ORIGINE_RECUPERO, ID_STORICO_RECUPERO_PRECEDENTE, ID_PROGETTO, ID_BANDO, ID_IMPRESA, COD_AGEA, SEGNATURA_ALLEGATI, ID_PROG_INTEGRATO, FLAG_PREADESIONE, FLAG_DEFINITIVO, ID_FASCICOLO, PROVINCIA_DI_PRESENTAZIONE, SELEZIONATA_X_REVISIONE, ID_STORICO_ULTIMO, DATA_CREAZIONE, OPERATORE_CREAZIONE, FIRMA_PREDISPOSTA, STORICO, IMPORTO_INTERESSI_LEGALI, IMPORTO_INTERESSI_MORA, IMPORTO_GESTIONE_PRATICA, DATA_REGISTRAZIONE_RITIRO, DATA_CERTIFICAZIONE_RECUPERO, DATA_CERTIFICAZIONE_RITIRO, GESTIONE_RATE, NUMERO_RATE, DATA_INIZIO_RATE, IMPORTO_RATA, INTERVALLO_RATE_MESI, ID_PROGRAMMAZIONE, PROGRAMMAZIONE, IMPORTO_DA_RECUPERARE_PRIVATO, IMPORTO_DA_RECUPERARE_TOTALE, IMPORTO_DETRATTO_PRIVATO, IMPORTO_RECUPERATO_PRIVATO, IMPORTO_RECUPERATO_TOTALE, SALDO_DA_RECUPERARE_PRIVATO, SALDO_DA_RECUPERARE_TOTALE, SOGGETTO_REVOCA_FINANZIAMENTO, ID_ATTO_RECUPERO, ID_ATTO_RITIRO, ID_ATTO_NON_RECUPERABILITA, RECUPERABILE, IMPORTO_DETRATTO_TOTALE, DATA_CERTIFICAZIONE_NON_RECUPERABILITA, DATA_REGISTRAZIONE_NON_RECUPERABILITA, COD_ASSE, DESC_AZIONE, DATA_SEGNATURA, SEGNATURA FROM VREGISTRO_RECUPERO WHERE 1=1';
	IF (@IdProgrammazioneequalthis IS NOT NULL) BEGIN SET @sql = @sql + ' AND (ID_PROGRAMMAZIONE = @IdProgrammazioneequalthis)'; set @lensql=@lensql+len(@IdProgrammazioneequalthis);end;
	IF (@IdProgettoequalthis IS NOT NULL) BEGIN SET @sql = @sql + ' AND (ID_PROGETTO = @IdProgettoequalthis)'; set @lensql=@lensql+len(@IdProgettoequalthis);end;
	IF (@DataAvvioeqgreaterthanthis IS NOT NULL) BEGIN SET @sql = @sql + ' AND (DATA_AVVIO >= @DataAvvioeqgreaterthanthis)'; set @lensql=@lensql+len(@DataAvvioeqgreaterthanthis);end;
	IF (@DataAvvioeqlessthanthis IS NOT NULL) BEGIN SET @sql = @sql + ' AND (DATA_AVVIO <= @DataAvvioeqlessthanthis)'; set @lensql=@lensql+len(@DataAvvioeqlessthanthis);end;
	IF (@IdTipoRecuperoequalthis IS NOT NULL) BEGIN SET @sql = @sql + ' AND (ID_TIPO_RECUPERO = @IdTipoRecuperoequalthis)'; set @lensql=@lensql+len(@IdTipoRecuperoequalthis);end;
	IF (@Recuperabileequalthis IS NOT NULL) BEGIN SET @sql = @sql + ' AND (RECUPERABILE = @Recuperabileequalthis)'; set @lensql=@lensql+len(@Recuperabileequalthis);end;
	IF (@Storicoequalthis IS NOT NULL) BEGIN SET @sql = @sql + ' AND (STORICO = @Storicoequalthis)'; set @lensql=@lensql+len(@Storicoequalthis);end;
	set @lensql=@lensql+len(@sql);
	if (@lensql<3000)
	exec sp_executesql @sql,N'@IdProgrammazioneequalthis INT, @IdProgettoequalthis INT, @DataAvvioeqgreaterthanthis DATETIME, @DataAvvioeqlessthanthis DATETIME, @IdTipoRecuperoequalthis INT, @Recuperabileequalthis BIT, @Storicoequalthis BIT',@IdProgrammazioneequalthis , @IdProgettoequalthis , @DataAvvioeqgreaterthanthis , @DataAvvioeqlessthanthis , @IdTipoRecuperoequalthis , @Recuperabileequalthis , @Storicoequalthis ;
	else
		SELECT ID_REGISTRO_RECUPERO, DATA_INSERIMENTO, CF_INSERIMENTO, DATA_MODIFICA, CF_MODIFICA, ID_REGISTRO_IRREGOLARITA, DATA_AVVIO, DATA_PROBABILE_CONCLUSIONE, IMPORTO_DA_RECUPERARE_UE, IMPORTO_DA_RECUPERARE_NAZIONALE, IMPORTO_DA_RECUPERARE_PUBBLICO, IMPORTO_DETRATTO_UE, IMPORTO_DETRATTO_NAZIONALE, IMPORTO_DETRATTO_PUBBLICO, IMPORTO_RECUPERATO_UE, IMPORTO_RECUPERATO_PUBBLICO, IMPORTO_RECUPERATO_NAZIONALE, SALDO_DA_RECUPERARE_UE, SALDO_DA_RECUPERARE_NAZIONALE, SALDO_DA_RECUPERARE_PUBBLICO, IMPORTO_VERSATO_UE, IMPORTO_RITENUTO_STATO, DATA_CONCLUSIONE, ID_PROCEDURE_AVVIATE, ID_TIPO_PROCEDURE_AVVIATE, DATA_AVVIO_PROCEDURE, DATA_PROBABILE_CONCLUSIONE_PROCEDURE, ID_TIPO_RECUPERO, ID_ORIGINE_RECUPERO, ID_STORICO_RECUPERO_PRECEDENTE, ID_PROGETTO, ID_BANDO, ID_IMPRESA, COD_AGEA, SEGNATURA_ALLEGATI, ID_PROG_INTEGRATO, FLAG_PREADESIONE, FLAG_DEFINITIVO, ID_FASCICOLO, PROVINCIA_DI_PRESENTAZIONE, SELEZIONATA_X_REVISIONE, ID_STORICO_ULTIMO, DATA_CREAZIONE, OPERATORE_CREAZIONE, FIRMA_PREDISPOSTA, STORICO, IMPORTO_INTERESSI_LEGALI, IMPORTO_INTERESSI_MORA, IMPORTO_GESTIONE_PRATICA, DATA_REGISTRAZIONE_RITIRO, DATA_CERTIFICAZIONE_RECUPERO, DATA_CERTIFICAZIONE_RITIRO, GESTIONE_RATE, NUMERO_RATE, DATA_INIZIO_RATE, IMPORTO_RATA, INTERVALLO_RATE_MESI, ID_PROGRAMMAZIONE, PROGRAMMAZIONE, IMPORTO_DA_RECUPERARE_PRIVATO, IMPORTO_DA_RECUPERARE_TOTALE, IMPORTO_DETRATTO_PRIVATO, IMPORTO_RECUPERATO_PRIVATO, IMPORTO_RECUPERATO_TOTALE, SALDO_DA_RECUPERARE_PRIVATO, SALDO_DA_RECUPERARE_TOTALE, SOGGETTO_REVOCA_FINANZIAMENTO, ID_ATTO_RECUPERO, ID_ATTO_RITIRO, ID_ATTO_NON_RECUPERABILITA, RECUPERABILE, IMPORTO_DETRATTO_TOTALE, DATA_CERTIFICAZIONE_NON_RECUPERABILITA, DATA_REGISTRAZIONE_NON_RECUPERABILITA, COD_ASSE, DESC_AZIONE, DATA_SEGNATURA, SEGNATURA
		FROM VREGISTRO_RECUPERO
		WHERE 
			((@IdProgrammazioneequalthis IS NULL) OR ID_PROGRAMMAZIONE = @IdProgrammazioneequalthis) AND 
			((@IdProgettoequalthis IS NULL) OR ID_PROGETTO = @IdProgettoequalthis) AND 
			((@DataAvvioeqgreaterthanthis IS NULL) OR DATA_AVVIO >= @DataAvvioeqgreaterthanthis) AND 
			((@DataAvvioeqlessthanthis IS NULL) OR DATA_AVVIO <= @DataAvvioeqlessthanthis) AND 
			((@IdTipoRecuperoequalthis IS NULL) OR ID_TIPO_RECUPERO = @IdTipoRecuperoequalthis) AND 
			((@Recuperabileequalthis IS NULL) OR RECUPERABILE = @Recuperabileequalthis) AND 
			((@Storicoequalthis IS NULL) OR STORICO = @Storicoequalthis)
		


GO
EXECUTE sp_addextendedproperty @name = N'backup', @value = 'CREATE PROCEDURE [dbo].[ZRegistroRecuperoFindGetcollectionreport]
(
	@IdProgrammazioneequalthis INT, 
	@IdProgettoequalthis INT, 
	@DataAvvioeqgreaterthanthis DATETIME, 
	@DataAvvioeqlessthanthis DATETIME, 
	@IdTipoRecuperoequalthis INT, 
	@Recuperabileequalthis BIT, 
	@Storicoequalthis BIT
)
AS
	declare @sql nvarchar(4000);
	declare @lensql int;
	set @lensql=0;
	SET @sql = ''SELECT ID_REGISTRO_RECUPERO, DATA_INSERIMENTO, CF_INSERIMENTO, DATA_MODIFICA, CF_MODIFICA, ID_REGISTRO_IRREGOLARITA, DATA_AVVIO, DATA_PROBABILE_CONCLUSIONE, IMPORTO_DA_RECUPERARE_UE, IMPORTO_DA_RECUPERARE_NAZIONALE, IMPORTO_DA_RECUPERARE_PUBBLICO, IMPORTO_DETRATTO_UE, IMPORTO_DETRATTO_NAZIONALE, IMPORTO_DETRATTO_PUBBLICO, IMPORTO_RECUPERATO_UE, IMPORTO_RECUPERATO_PUBBLICO, IMPORTO_RECUPERATO_NAZIONALE, SALDO_DA_RECUPERARE_UE, SALDO_DA_RECUPERARE_NAZIONALE, SALDO_DA_RECUPERARE_PUBBLICO, IMPORTO_VERSATO_UE, IMPORTO_RITENUTO_STATO, DATA_CONCLUSIONE, ID_PROCEDURE_AVVIATE, ID_TIPO_PROCEDURE_AVVIATE, DATA_AVVIO_PROCEDURE, DATA_PROBABILE_CONCLUSIONE_PROCEDURE, ID_TIPO_RECUPERO, ID_ORIGINE_RECUPERO, ID_STORICO_RECUPERO_PRECEDENTE, ID_PROGETTO, ID_BANDO, ID_IMPRESA, COD_AGEA, SEGNATURA_ALLEGATI, ID_PROG_INTEGRATO, FLAG_PREADESIONE, FLAG_DEFINITIVO, ID_FASCICOLO, PROVINCIA_DI_PRESENTAZIONE, SELEZIONATA_X_REVISIONE, ID_STORICO_ULTIMO, DATA_CREAZIONE, OPERATORE_CREAZIONE, FIRMA_PREDISPOSTA, STORICO, IMPORTO_INTERESSI_LEGALI, IMPORTO_INTERESSI_MORA, IMPORTO_GESTIONE_PRATICA, DATA_REGISTRAZIONE_RITIRO, DATA_CERTIFICAZIONE_RECUPERO, DATA_CERTIFICAZIONE_RITIRO, GESTIONE_RATE, NUMERO_RATE, DATA_INIZIO_RATE, IMPORTO_RATA, INTERVALLO_RATE_MESI, ID_PROGRAMMAZIONE, PROGRAMMAZIONE, IMPORTO_DA_RECUPERARE_PRIVATO, IMPORTO_DA_RECUPERARE_TOTALE, IMPORTO_DETRATTO_PRIVATO, IMPORTO_RECUPERATO_PRIVATO, IMPORTO_RECUPERATO_TOTALE, SALDO_DA_RECUPERARE_PRIVATO, SALDO_DA_RECUPERARE_TOTALE, SOGGETTO_REVOCA_FINANZIAMENTO, ID_ATTO_RECUPERO, ID_ATTO_RITIRO, ID_ATTO_NON_RECUPERABILITA, RECUPERABILE, IMPORTO_DETRATTO_TOTALE, DATA_CERTIFICAZIONE_NON_RECUPERABILITA, DATA_REGISTRAZIONE_NON_RECUPERABILITA, COD_ASSE, DESC_AZIONE FROM VREGISTRO_RECUPERO WHERE 1=1'';
	IF (@IdProgrammazioneequalthis IS NOT NULL) BEGIN SET @sql = @sql + '' AND (ID_PROGRAMMAZIONE = @IdProgrammazioneequalthis)''; set @lensql=@lensql+len(@IdProgrammazioneequalthis);end;
	IF (@IdProgettoequalthis IS NOT NULL) BEGIN SET @sql = @sql + '' AND (ID_PROGETTO = @IdProgettoequalthis)''; set @lensql=@lensql+len(@IdProgettoequalthis);end;
	IF (@DataAvvioeqgreaterthanthis IS NOT NULL) BEGIN SET @sql = @sql + '' AND (DATA_AVVIO >= @DataAvvioeqgreaterthanthis)''; set @lensql=@lensql+len(@DataAvvioeqgreaterthanthis);end;
	IF (@DataAvvioeqlessthanthis IS NOT NULL) BEGIN SET @sql = @sql + '' AND (DATA_AVVIO <= @DataAvvioeqlessthanthis)''; set @lensql=@lensql+len(@DataAvvioeqlessthanthis);end;
	IF (@IdTipoRecuperoequalthis IS NOT NULL) BEGIN SET @sql = @sql + '' AND (ID_TIPO_RECUPERO = @IdTipoRecuperoequalthis)''; set @lensql=@lensql+len(@IdTipoRecuperoequalthis);end;
	IF (@Recuperabileequalthis IS NOT NULL) BEGIN SET @sql = @sql + '' AND (RECUPERABILE = @Recuperabileequalthis)''; set @lensql=@lensql+len(@Recuperabileequalthis);end;
	IF (@Storicoequalthis IS NOT NULL) BEGIN SET @sql = @sql + '' AND (STORICO = @Storicoequalthis)''; set @lensql=@lensql+len(@Storicoequalthis);end;
	set @lensql=@lensql+len(@sql);
	if (@lensql<3000)
	exec sp_executesql @sql,N''@IdProgrammazioneequalthis INT, @IdProgettoequalthis INT, @DataAvvioeqgreaterthanthis DATETIME, @DataAvvioeqlessthanthis DATETIME, @IdTipoRecuperoequalthis INT, @Recuperabileequalthis BIT, @Storicoequalthis BIT'',@IdProgrammazioneequalthis , @IdProgettoequalthis , @DataAvvioeqgreaterthanthis , @DataAvvioeqlessthanthis , @IdTipoRecuperoequalthis , @Recuperabileequalthis , @Storicoequalthis ;
	else
		SELECT ID_REGISTRO_RECUPERO, DATA_INSERIMENTO, CF_INSERIMENTO, DATA_MODIFICA, CF_MODIFICA, ID_REGISTRO_IRREGOLARITA, DATA_AVVIO, DATA_PROBABILE_CONCLUSIONE, IMPORTO_DA_RECUPERARE_UE, IMPO', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'PROCEDURE', @level1name = N'ZRegistroRecuperoFindGetcollectionreport';

