CREATE TABLE [dbo].[ISTANZA_CHECKLIST_GENERICA] (
    [ID_ISTANZA_GENERICA]   INT       IDENTITY (1, 1) NOT NULL,
    [ID_CHECKLIST_GENERICA] INT       NOT NULL,
    [DATA_INSERIMENTO]      DATETIME  CONSTRAINT [DF_ISTANZA_CHECKLIST_GENERICA_DATA_INSERIMENTO] DEFAULT (getdate()) NULL,
    [CF_INSERIMENTO]        CHAR (16) NULL,
    [DATA_MODIFICA]         DATETIME  CONSTRAINT [DF_ISTANZA_CHECKLIST_GENERICA_DATA_MODIFICA] DEFAULT (getdate()) NULL,
    [CF_MODIFICA]           CHAR (16) NULL,
    [COD_FASE]              CHAR (1)  NOT NULL,
    ID_CHECKLIST_PADRE      INT       NULL,
    D_SCHEDA_X_CHECKLIST    INT       NULL,
    CONSTRAINT [PK_ISTANZA_CHECKLIST_GENERICA] PRIMARY KEY CLUSTERED ([ID_ISTANZA_GENERICA] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_ISTANZA_CHECKLIST_CHECKLIST_GENERICA] FOREIGN KEY ([ID_CHECKLIST_GENERICA]) REFERENCES [dbo].[CHECKLIST_GENERICA] ([ID_CHECKLIST_GENERICA])
);

