CREATE TABLE SCHEDA_X_CHECKLIST (
	ID_SCHEDA_X_CHECKLIST INT IDENTITY (1, 1) NOT NULL PRIMARY KEY,
	CF_INSERIMENTO VARCHAR(16) NOT NULL,
	DATA_INSERIMENTO DATETIME NOT NULL,
	CF_MODIFICA VARCHAR(16) NOT NULL,
	DATA_MODIFICA DATETIME NOT NULL DEFAULT GETDATE(),

	ID_CHECKLIST INT NOT NULL,
	ID_SCHEDA INT NOT NULL,
	ORDINE INT NOT NULL,
	OBBLIGATORIO BIT NOT NULL DEFAULT 0,
	PESO DECIMAL(10,2) NULL
);

ALTER TABLE SCHEDA_X_CHECKLIST  WITH CHECK ADD CONSTRAINT [FK_SCHEDA_X_CHECKLIST_CHECKLIST_GENERICA_CHECKLIST] FOREIGN KEY(ID_CHECKLIST)
REFERENCES CHECKLIST_GENERICA (ID_CHECKLIST_GENERICA)
GO

ALTER TABLE SCHEDA_X_CHECKLIST  WITH CHECK ADD CONSTRAINT [FK_SCHEDA_X_CHECKLIST_CHECKLIST_GENERICA_SCHEDA] FOREIGN KEY(ID_SCHEDA)
REFERENCES CHECKLIST_GENERICA (ID_CHECKLIST_GENERICA)
GO