CREATE TABLE [dbo].[VOCE_GENERICA] (
    [ID_VOCE_GENERICA]   INT            IDENTITY (1, 1) NOT NULL,
    [DESCRIZIONE]        VARCHAR (8000) NOT NULL,
    [AUTOMATICO]         BIT            NULL,
    [QUERY_SQL]          VARCHAR (8000) NULL,
    [QUERY_SQL_POST]     VARCHAR (300)  NULL,
    [CODE_METHOD]        VARCHAR (30)   NULL,
    [URL]                VARCHAR (100)  NULL,
    [VAL_MINIMO]         VARCHAR (20)   NULL,
    [VAL_MASSIMO]        VARCHAR (20)   NULL,
    [DATA_INSERIMENTO]   DATETIME       CONSTRAINT [DF_VOCE_GENERICA_DATA_INSERIMENTO] DEFAULT (getdate()) NULL,
    [CF_INSERIMENTO]     CHAR (16)      NULL,
    [DATA_MODIFICA]      DATETIME       CONSTRAINT [DF_VOCE_GENERICA_DATA_MODIFICA] DEFAULT (getdate()) NULL,
    [CF_MODIFICA]        CHAR (16)      NULL,
    [VAL_ESITO_NEGATIVO] BIT            CONSTRAINT [DF_VOCE_GENERICA_VAL_ESITO_NEGATIVO] DEFAULT ((0)) NULL,
    ID_FILTRO            VARCHAR(200)   NULL,
    TITOLO               BIT            CONSTRAINT [DF_VOCE_GENERICA_TITOLO] DEFAULT ((0)) NULL,
    COMMENTO             VARCHAR(MAX)   NULL,
    CONSTRAINT [PK_VOCE_GENERICA_] PRIMARY KEY CLUSTERED ([ID_VOCE_GENERICA] ASC) WITH (FILLFACTOR = 80)
);

ALTER TABLE VOCE_GENERICA  WITH CHECK ADD CONSTRAINT [FK_VOCE_GENERICA_FILTRO] FOREIGN KEY(ID_FILTRO)
REFERENCES FILTRO_CHECKLIST_VOCE (ID_FILTRO)
GO
