CREATE TABLE [dbo].[VOCE_X_CHECKLIST_GENERICA] (
    [ID_VOCE_X_CHECKLIST_GENERICA] INT             IDENTITY (1, 1) NOT NULL,
    [ID_CHECKLIST_GENERICA]        INT             NOT NULL,
    [ID_VOCE_GENERICA]             INT             NOT NULL,
    [ORDINE]                       INT             NULL,
    [OBBLIGATORIO]                 BIT             CONSTRAINT [DF_VOCE_X_CHECKLIST_GENERICA_OBBLIGATORIO] DEFAULT ((0)) NOT NULL,
    [PESO]                         DECIMAL (10, 2) NULL,
    [DATA_INSERIMENTO]             DATETIME        CONSTRAINT [DF_VOCE_X_CHECKLIST_GENERICA_DATA_INSERIMENTO] DEFAULT (getdate()) NULL,
    [CF_INSERIMENTO]               CHAR (16)       NULL,
    [DATA_MODIFICA]                DATETIME        CONSTRAINT [DF_VOCE_X_CHECKLIST_GENERICA_DATA_MODIFICA] DEFAULT (getdate()) NULL,
    [CF_MODIFICA]                  CHAR (16)       NULL,
    [MISURA]                       VARCHAR (20)    NULL,
    CONSTRAINT [PK_VOCE_X_CHECKLIST_GENERICA] PRIMARY KEY CLUSTERED ([ID_VOCE_X_CHECKLIST_GENERICA] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_VOCE_X_CHECKLIST_GENERICA_CHECKLIST_GENERICA] FOREIGN KEY ([ID_CHECKLIST_GENERICA]) REFERENCES [dbo].[CHECKLIST_GENERICA] ([ID_CHECKLIST_GENERICA]),
    CONSTRAINT [FK_VOCE_X_CHECKLIST_GENERICA_VOCE_GENERICA] FOREIGN KEY ([ID_VOCE_GENERICA]) REFERENCES [dbo].[VOCE_GENERICA] ([ID_VOCE_GENERICA])
);

