CREATE PROCEDURE [dbo].[ZIrregolaritaUpdate]
(
	@IdIrregolarita INT, 
	@CfInserimento VARCHAR(255), 
	@DataInserimento DATETIME, 
	@CfModifica VARCHAR(255), 
	@DataModifica DATETIME, 
	@IdProgetto INT, 
	@IdTipoIrregolarita INT, 
	@IdControlloOrigine INT, 
	@SospettoFrode BIT, 
	@DataCostatazioneAmministrativa DATETIME, 
	@ImportoIrregolareDaRecuperare BIT, 
	@SegnalazioneOlaf BIT, 
	@DataSegnalazioneOlaf DATETIME, 
	@DataSegnalazioneOlafDa DATETIME, 
	@DataSegnalazioneOlafA DATETIME, 
	@TrimestreSegnalazioneOlaf VARCHAR(max), 
	@DataPrimaInformazione DATETIME, 
	@FontePrimaInformazione VARCHAR(max), 
	@IdImpresaCommessaDa INT, 
	@NoteCommessaDa VARCHAR(max), 
	@IdCategoria INT, 
	@IdTipo INT, 
	@IdClassificazione INT, 
	@PraticheUtilizzate VARCHAR(max), 
	@NoteGiustificativi VARCHAR(max), 
	@ImportoSpesa DECIMAL(15,2), 
	@ContributoAmmesso DECIMAL(15,2), 
	@ContributoPubblico DECIMAL(15,2), 
	@ContributoAmmessoCertificato DECIMAL(15,2), 
	@ContributoPubblicoCertificato DECIMAL(15,2), 
	@ContributoPubblicoDaRecuperare DECIMAL(15,2), 
	@CommentiImpattiFinanziario VARCHAR(max), 
	@ProcedimentoAmministrativo BIT, 
	@AzioneGiudiziaria BIT, 
	@AzionePenale BIT, 
	@IdStatoFinanziario INT, 
	@StabilitaOperazioni BIT
)
AS
	SET @DataModifica=getdate()
	UPDATE IRREGOLARITA
	SET
		CF_INSERIMENTO = @CfInserimento, 
		DATA_INSERIMENTO = @DataInserimento, 
		CF_MODIFICA = @CfModifica, 
		DATA_MODIFICA = @DataModifica, 
		ID_PROGETTO = @IdProgetto, 
		ID_TIPO_IRREGOLARITA = @IdTipoIrregolarita, 
		ID_CONTROLLO_ORIGINE = @IdControlloOrigine, 
		SOSPETTO_FRODE = @SospettoFrode, 
		DATA_COSTATAZIONE_AMMINISTRATIVA = @DataCostatazioneAmministrativa, 
		IMPORTO_IRREGOLARE_DA_RECUPERARE = @ImportoIrregolareDaRecuperare, 
		SEGNALAZIONE_OLAF = @SegnalazioneOlaf, 
		DATA_SEGNALAZIONE_OLAF = @DataSegnalazioneOlaf, 
		DATA_SEGNALAZIONE_OLAF_DA = @DataSegnalazioneOlafDa, 
		DATA_SEGNALAZIONE_OLAF_A = @DataSegnalazioneOlafA, 
		TRIMESTRE_SEGNALAZIONE_OLAF = @TrimestreSegnalazioneOlaf, 
		DATA_PRIMA_INFORMAZIONE = @DataPrimaInformazione, 
		FONTE_PRIMA_INFORMAZIONE = @FontePrimaInformazione, 
		ID_IMPRESA_COMMESSA_DA = @IdImpresaCommessaDa, 
		NOTE_COMMESSA_DA = @NoteCommessaDa, 
		ID_CATEGORIA = @IdCategoria, 
		ID_TIPO = @IdTipo, 
		ID_CLASSIFICAZIONE = @IdClassificazione, 
		PRATICHE_UTILIZZATE = @PraticheUtilizzate, 
		NOTE_GIUSTIFICATIVI = @NoteGiustificativi, 
		IMPORTO_SPESA = @ImportoSpesa, 
		CONTRIBUTO_AMMESSO = @ContributoAmmesso, 
		CONTRIBUTO_PUBBLICO = @ContributoPubblico, 
		CONTRIBUTO_AMMESSO_CERTIFICATO = @ContributoAmmessoCertificato, 
		CONTRIBUTO_PUBBLICO_CERTIFICATO = @ContributoPubblicoCertificato, 
		CONTRIBUTO_PUBBLICO_DA_RECUPERARE = @ContributoPubblicoDaRecuperare, 
		COMMENTI_IMPATTI_FINANZIARIO = @CommentiImpattiFinanziario, 
		PROCEDIMENTO_AMMINISTRATIVO = @ProcedimentoAmministrativo, 
		AZIONE_GIUDIZIARIA = @AzioneGiudiziaria, 
		AZIONE_PENALE = @AzionePenale, 
		ID_STATO_FINANZIARIO = @IdStatoFinanziario, 
		STABILITA_OPERAZIONI = @StabilitaOperazioni
	WHERE 
		(ID_IRREGOLARITA = @IdIrregolarita)
	SELECT @DataModifica;

GO