CREATE PROCEDURE [dbo].[ZIrregolaritaFindFind]
(
	@IdIrregolaritaequalthis INT, 
	@IdBandoequalthis INT, 
	@IdProgettoequalthis INT, 
	@IdTipoIrregolaritaequalthis INT, 
	@SegnalazioneOlafequalthis BIT
)
AS
	declare @sql nvarchar(4000);
	declare @lensql int;
	set @lensql=0;
	SET @sql = 'SELECT ID_IRREGOLARITA, CF_INSERIMENTO, DATA_INSERIMENTO, CF_MODIFICA, DATA_MODIFICA, ID_PROGETTO, ID_TIPO_IRREGOLARITA, ID_CONTROLLO_ORIGINE, SOSPETTO_FRODE, DATA_COSTATAZIONE_AMMINISTRATIVA, IMPORTO_IRREGOLARE_DA_RECUPERARE, SEGNALAZIONE_OLAF, DATA_SEGNALAZIONE_OLAF, DATA_SEGNALAZIONE_OLAF_DA, DATA_SEGNALAZIONE_OLAF_A, TRIMESTRE_SEGNALAZIONE_OLAF, DATA_PRIMA_INFORMAZIONE, FONTE_PRIMA_INFORMAZIONE, ID_IMPRESA_COMMESSA_DA, NOTE_COMMESSA_DA, ID_CATEGORIA, ID_TIPO, ID_CLASSIFICAZIONE, PRATICHE_UTILIZZATE, NOTE_GIUSTIFICATIVI, IMPORTO_SPESA, CONTRIBUTO_AMMESSO, CONTRIBUTO_PUBBLICO, CONTRIBUTO_AMMESSO_CERTIFICATO, CONTRIBUTO_PUBBLICO_CERTIFICATO, CONTRIBUTO_PUBBLICO_DA_RECUPERARE, COMMENTI_IMPATTI_FINANZIARIO, PROCEDIMENTO_AMMINISTRATIVO, AZIONE_GIUDIZIARIA, AZIONE_PENALE, ID_STATO_FINANZIARIO, STABILITA_OPERAZIONI, TIPO_IRREGOLARITA, ATTIVO_TIPO_IRREGOLARITA, ID_BANDO, COD_STATO_PROGETTO, STATO_PROGETTO, COD_FASE_PROGETTO, FASE_PROGETTO, ID_IMPRESA_PROGETTO, CUAA_IMPRESA_IRREGOLARITA, CODICE_FISCALE_IMPRESA_IRREGOLARITA, RAGIONE_SOCIALE_IMPRESA_IRREGOLARITA, DESCRIZIONE_CATEGORIA, DESCRIZIONE_CONTROLLO_ORIGINE, DESCRIZIONE_TIPO, DESCRIZIONE_CLASSIFICAZIONE, DESCRIZIONE_STATO_FINANZIARIO FROM VIRREGOLARITA WHERE 1=1';
	IF (@IdIrregolaritaequalthis IS NOT NULL) BEGIN SET @sql = @sql + ' AND (ID_IRREGOLARITA = @IdIrregolaritaequalthis)'; set @lensql=@lensql+len(@IdIrregolaritaequalthis);end;
	IF (@IdBandoequalthis IS NOT NULL) BEGIN SET @sql = @sql + ' AND (ID_BANDO = @IdBandoequalthis)'; set @lensql=@lensql+len(@IdBandoequalthis);end;
	IF (@IdProgettoequalthis IS NOT NULL) BEGIN SET @sql = @sql + ' AND (ID_PROGETTO = @IdProgettoequalthis)'; set @lensql=@lensql+len(@IdProgettoequalthis);end;
	IF (@IdTipoIrregolaritaequalthis IS NOT NULL) BEGIN SET @sql = @sql + ' AND (ID_TIPO_IRREGOLARITA = @IdTipoIrregolaritaequalthis)'; set @lensql=@lensql+len(@IdTipoIrregolaritaequalthis);end;
	IF (@SegnalazioneOlafequalthis IS NOT NULL) BEGIN SET @sql = @sql + ' AND (SEGNALAZIONE_OLAF = @SegnalazioneOlafequalthis)'; set @lensql=@lensql+len(@SegnalazioneOlafequalthis);end;
	set @lensql=@lensql+len(@sql);
	if (@lensql<3000)
	exec sp_executesql @sql,N'@IdIrregolaritaequalthis INT, @IdBandoequalthis INT, @IdProgettoequalthis INT, @IdTipoIrregolaritaequalthis INT, @SegnalazioneOlafequalthis BIT',@IdIrregolaritaequalthis , @IdBandoequalthis , @IdProgettoequalthis , @IdTipoIrregolaritaequalthis , @SegnalazioneOlafequalthis ;
	else
		SELECT ID_IRREGOLARITA, CF_INSERIMENTO, DATA_INSERIMENTO, CF_MODIFICA, DATA_MODIFICA, ID_PROGETTO, ID_TIPO_IRREGOLARITA, ID_CONTROLLO_ORIGINE, SOSPETTO_FRODE, DATA_COSTATAZIONE_AMMINISTRATIVA, IMPORTO_IRREGOLARE_DA_RECUPERARE, SEGNALAZIONE_OLAF, DATA_SEGNALAZIONE_OLAF, DATA_SEGNALAZIONE_OLAF_DA, DATA_SEGNALAZIONE_OLAF_A, TRIMESTRE_SEGNALAZIONE_OLAF, DATA_PRIMA_INFORMAZIONE, FONTE_PRIMA_INFORMAZIONE, ID_IMPRESA_COMMESSA_DA, NOTE_COMMESSA_DA, ID_CATEGORIA, ID_TIPO, ID_CLASSIFICAZIONE, PRATICHE_UTILIZZATE, NOTE_GIUSTIFICATIVI, IMPORTO_SPESA, CONTRIBUTO_AMMESSO, CONTRIBUTO_PUBBLICO, CONTRIBUTO_AMMESSO_CERTIFICATO, CONTRIBUTO_PUBBLICO_CERTIFICATO, CONTRIBUTO_PUBBLICO_DA_RECUPERARE, COMMENTI_IMPATTI_FINANZIARIO, PROCEDIMENTO_AMMINISTRATIVO, AZIONE_GIUDIZIARIA, AZIONE_PENALE, ID_STATO_FINANZIARIO, STABILITA_OPERAZIONI, TIPO_IRREGOLARITA, ATTIVO_TIPO_IRREGOLARITA, ID_BANDO, COD_STATO_PROGETTO, STATO_PROGETTO, COD_FASE_PROGETTO, FASE_PROGETTO, ID_IMPRESA_PROGETTO, CUAA_IMPRESA_IRREGOLARITA, CODICE_FISCALE_IMPRESA_IRREGOLARITA, RAGIONE_SOCIALE_IMPRESA_IRREGOLARITA, DESCRIZIONE_CATEGORIA, DESCRIZIONE_CONTROLLO_ORIGINE, DESCRIZIONE_TIPO, DESCRIZIONE_CLASSIFICAZIONE, DESCRIZIONE_STATO_FINANZIARIO
		FROM VIRREGOLARITA
		WHERE 
			((@IdIrregolaritaequalthis IS NULL) OR ID_IRREGOLARITA = @IdIrregolaritaequalthis) AND 
			((@IdBandoequalthis IS NULL) OR ID_BANDO = @IdBandoequalthis) AND 
			((@IdProgettoequalthis IS NULL) OR ID_PROGETTO = @IdProgettoequalthis) AND 
			((@IdTipoIrregolaritaequalthis IS NULL) OR ID_TIPO_IRREGOLARITA = @IdTipoIrregolaritaequalthis) AND 
			((@SegnalazioneOlafequalthis IS NULL) OR SEGNALAZIONE_OLAF = @SegnalazioneOlafequalthis)
		

GO