CREATE PROCEDURE [dbo].[ZVricercaSpeseIrregolariFindFindspeseprogetto]
(
	@IdProgettoequalthis INT, 
	@IdDomandaPagamentoequalthis INT, 
	@IdGiustificativoequalthis INT, 
	@IdSpesaequalthis INT
)
AS
	declare @sql nvarchar(4000);
	declare @lensql int;
	set @lensql=0;
	SET @sql = 'SELECT ID_SPESA, ID_GIUSTIFICATIVO, COD_TIPO_SPESA, ESTREMI_SPESA, DATA_SPESA, IMPORTO_SPESA, NETTO_SPESA, TIPO_SPESA, ID_DOMANDA_PAGAMENTO, COD_TIPO_DOMANDA, TIPO_DOMANDA, ID_PROGETTO, NUMERO_GIUSTIFICATIVO, COD_TIPO_GIUSTIFICATIVO, DATA_GIUSTIFICATIVO, NUMERO_DOCTRASPORTO_GIUSTIFICATIVO, IMPONIBILE_GIUSTIFICATIVO, IVA_GIUSTIFICATIVO, IVA_NON_RECUPERABILE_GIUSTIFICATIVO, DESCRIZIONE_GIUSTIFICATIVO, CF_FORNITORE_GIUSTIFICATIVO, DESCRIZIONE_FORNITORE_GIUSTIFICATIVO, TIPO_GIUSTIFICATIVO, ID_LOTTO_CERTIFICAZIONE, COD_PSR_CERTIFICAZIONE, DATA_INIZIO_LOTTO_CERTIFICAZIONE, DATA_FINE_LOTTO_CERTIFICAZIONE FROM VRICERCA_SPESE_IRREGOLARI WHERE 1=1';
	IF (@IdProgettoequalthis IS NOT NULL) BEGIN SET @sql = @sql + ' AND (ID_PROGETTO = @IdProgettoequalthis)'; set @lensql=@lensql+len(@IdProgettoequalthis);end;
	IF (@IdDomandaPagamentoequalthis IS NOT NULL) BEGIN SET @sql = @sql + ' AND (ID_DOMANDA_PAGAMENTO = @IdDomandaPagamentoequalthis)'; set @lensql=@lensql+len(@IdDomandaPagamentoequalthis);end;
	IF (@IdGiustificativoequalthis IS NOT NULL) BEGIN SET @sql = @sql + ' AND (ID_GIUSTIFICATIVO = @IdGiustificativoequalthis)'; set @lensql=@lensql+len(@IdGiustificativoequalthis);end;
	IF (@IdSpesaequalthis IS NOT NULL) BEGIN SET @sql = @sql + ' AND (ID_SPESA = @IdSpesaequalthis)'; set @lensql=@lensql+len(@IdSpesaequalthis);end;
	set @sql = @sql + 'ORDER BY ID_DOMANDA_PAGAMENTO ASC, ID_GIUSTIFICATIVO ASC, ID_SPESA ASC';
	set @lensql=@lensql+len(@sql);
	if (@lensql<3000)
	exec sp_executesql @sql,N'@IdProgettoequalthis INT, @IdDomandaPagamentoequalthis INT, @IdGiustificativoequalthis INT, @IdSpesaequalthis INT',@IdProgettoequalthis , @IdDomandaPagamentoequalthis , @IdGiustificativoequalthis , @IdSpesaequalthis ;
	else
		SELECT ID_SPESA, ID_GIUSTIFICATIVO, COD_TIPO_SPESA, ESTREMI_SPESA, DATA_SPESA, IMPORTO_SPESA, NETTO_SPESA, TIPO_SPESA, ID_DOMANDA_PAGAMENTO, COD_TIPO_DOMANDA, TIPO_DOMANDA, ID_PROGETTO, NUMERO_GIUSTIFICATIVO, COD_TIPO_GIUSTIFICATIVO, DATA_GIUSTIFICATIVO, NUMERO_DOCTRASPORTO_GIUSTIFICATIVO, IMPONIBILE_GIUSTIFICATIVO, IVA_GIUSTIFICATIVO, IVA_NON_RECUPERABILE_GIUSTIFICATIVO, DESCRIZIONE_GIUSTIFICATIVO, CF_FORNITORE_GIUSTIFICATIVO, DESCRIZIONE_FORNITORE_GIUSTIFICATIVO, TIPO_GIUSTIFICATIVO, ID_LOTTO_CERTIFICAZIONE, COD_PSR_CERTIFICAZIONE, DATA_INIZIO_LOTTO_CERTIFICAZIONE, DATA_FINE_LOTTO_CERTIFICAZIONE
		FROM VRICERCA_SPESE_IRREGOLARI
		WHERE 
			((@IdProgettoequalthis IS NULL) OR ID_PROGETTO = @IdProgettoequalthis) AND 
			((@IdDomandaPagamentoequalthis IS NULL) OR ID_DOMANDA_PAGAMENTO = @IdDomandaPagamentoequalthis) AND 
			((@IdGiustificativoequalthis IS NULL) OR ID_GIUSTIFICATIVO = @IdGiustificativoequalthis) AND 
			((@IdSpesaequalthis IS NULL) OR ID_SPESA = @IdSpesaequalthis)
		ORDER BY ID_DOMANDA_PAGAMENTO ASC, ID_GIUSTIFICATIVO ASC, ID_SPESA ASC

GO