//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace web.Private.PPagamento {
    
    
    public partial class PagamentoInvestimentoFem {
        
        /// <summary>
        /// btnAggiungiPagamentoContratto control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SiarLibrary.Web.Button btnAggiungiPagamentoContratto;
        
        /// <summary>
        /// btnAggiungiPagamentoGiustificativo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SiarLibrary.Web.Button btnAggiungiPagamentoGiustificativo;
        
        /// <summary>
        /// btnEliminaPagamento control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SiarLibrary.Web.Button btnEliminaPagamento;
        
        /// <summary>
        /// hdnIdPagamentoFem control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hdnIdPagamentoFem;
        
        /// <summary>
        /// hdnIdPagamentoFemEliminare control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hdnIdPagamentoFemEliminare;
        
        /// <summary>
        /// ucWorkflowPagamento control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::web.CONTROLS.WorkflowPagamento ucWorkflowPagamento;
        
        /// <summary>
        /// imgDettaglioInvestimento control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlImage imgDettaglioInvestimento;
        
        /// <summary>
        /// tbInvestimento control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTable tbInvestimento;
        
        /// <summary>
        /// txtCostoInvestimento control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SiarLibrary.Web.CurrencyBox txtCostoInvestimento;
        
        /// <summary>
        /// lblSpeseTecniche control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SiarLibrary.Web.Label lblSpeseTecniche;
        
        /// <summary>
        /// txtSpeseTecniche control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SiarLibrary.Web.CurrencyBox txtSpeseTecniche;
        
        /// <summary>
        /// txtContributoAmmesso control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SiarLibrary.Web.CurrencyBox txtContributoAmmesso;
        
        /// <summary>
        /// txtQuotaAiuto control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SiarLibrary.Web.CurrencyBox txtQuotaAiuto;
        
        /// <summary>
        /// txtStoricoImportoRichiesto control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SiarLibrary.Web.CurrencyBox txtStoricoImportoRichiesto;
        
        /// <summary>
        /// txtStoricoContributoRichiesto control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SiarLibrary.Web.CurrencyBox txtStoricoContributoRichiesto;
        
        /// <summary>
        /// txtStoricoRichiestoQuota control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SiarLibrary.Web.QuotaBox txtStoricoRichiestoQuota;
        
        /// <summary>
        /// lblFormulaCompletamento control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblFormulaCompletamento;
        
        /// <summary>
        /// txtCompletamentoInvestimento control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SiarLibrary.Web.CurrencyBox txtCompletamentoInvestimento;
        
        /// <summary>
        /// txtImportoInvestimento control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SiarLibrary.Web.CurrencyBox txtImportoInvestimento;
        
        /// <summary>
        /// txtImportoComputoMetrico control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SiarLibrary.Web.CurrencyBox txtImportoComputoMetrico;
        
        /// <summary>
        /// txtImportoSpeseTecniche control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SiarLibrary.Web.CurrencyBox txtImportoSpeseTecniche;
        
        /// <summary>
        /// txtImportoTotaleRichiesto control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SiarLibrary.Web.CurrencyBox txtImportoTotaleRichiesto;
        
        /// <summary>
        /// txtContributoTotaleRichiesto control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SiarLibrary.Web.CurrencyBox txtContributoTotaleRichiesto;
        
        /// <summary>
        /// tdRichiestoAltreFonti control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell tdRichiestoAltreFonti;
        
        /// <summary>
        /// txtContributoRichiestoAltreFonti control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SiarLibrary.Web.CurrencyBox txtContributoRichiestoAltreFonti;
        
        /// <summary>
        /// txtImportoRichiestoLavoriInEconomia control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SiarLibrary.Web.CurrencyBox txtImportoRichiestoLavoriInEconomia;
        
        /// <summary>
        /// txtQuotaRichiestoLavoriInEconomia control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SiarLibrary.Web.CurrencyBox txtQuotaRichiestoLavoriInEconomia;
        
        /// <summary>
        /// txtImportoInvestimentoAmmesso control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SiarLibrary.Web.CurrencyBox txtImportoInvestimentoAmmesso;
        
        /// <summary>
        /// txtImportoComputoMetricoAmmesso control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SiarLibrary.Web.CurrencyBox txtImportoComputoMetricoAmmesso;
        
        /// <summary>
        /// txtImportoSpeseTecnicheAmmesse control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SiarLibrary.Web.CurrencyBox txtImportoSpeseTecnicheAmmesse;
        
        /// <summary>
        /// txtImportoTotaleAmmesso control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SiarLibrary.Web.CurrencyBox txtImportoTotaleAmmesso;
        
        /// <summary>
        /// txtContributoTotaleAmmesso control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SiarLibrary.Web.CurrencyBox txtContributoTotaleAmmesso;
        
        /// <summary>
        /// tdAmmessoAltreFonti control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell tdAmmessoAltreFonti;
        
        /// <summary>
        /// txtContributoAmmessoAltreFonti control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SiarLibrary.Web.CurrencyBox txtContributoAmmessoAltreFonti;
        
        /// <summary>
        /// txtImportoAmmessoLavoriInEconomia control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SiarLibrary.Web.CurrencyBox txtImportoAmmessoLavoriInEconomia;
        
        /// <summary>
        /// txtQuotaAmmessoLavoriInEconomia control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SiarLibrary.Web.CurrencyBox txtQuotaAmmessoLavoriInEconomia;
        
        /// <summary>
        /// tableValutazione control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTable tableValutazione;
        
        /// <summary>
        /// txtValutazioneLunga control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SiarLibrary.Web.TextArea txtValutazioneLunga;
        
        /// <summary>
        /// btnSalva control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SiarLibrary.Web.Button btnSalva;
        
        /// <summary>
        /// lblNumeroContratti control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblNumeroContratti;
        
        /// <summary>
        /// lnkNuovoContratto control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor lnkNuovoContratto;
        
        /// <summary>
        /// lnkNuovoGiustificativo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor lnkNuovoGiustificativo;
        
        /// <summary>
        /// dgPagamenti control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SiarLibrary.Web.DataGrid dgPagamenti;
        
        /// <summary>
        /// modalePagamento control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::web.CONTROLS.ucPagamentoInvestimento modalePagamento;
        
        /// <summary>
        /// ucZoomLoaderContrattiPagati control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::web.CONTROLS.ZoomLoader ucZoomLoaderContrattiPagati;
        
        /// <summary>
        /// ucZoomLoaderGiustificativiPagati control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::web.CONTROLS.ZoomLoader ucZoomLoaderGiustificativiPagati;
    }
}
