CREATE VIEW [dbo].[vALLEGATI_X_DOMANDA]
AS
SELECT     dbo.ALLEGATI_X_DOMANDA.ID_ALLEGATO, dbo.ALLEGATI_X_DOMANDA.ID_DOMANDA, dbo.ALLEGATI_X_DOMANDA.ORDINE, dbo.ALLEGATI.DESCRIZIONE, 
                      dbo.ALLEGATI.MISURA, dbo.ALLEGATI.COD_TIPO, dbo.TIPO_ALLEGATO.DESCRIZIONE AS TIPO_ALLEGATO
FROM         dbo.ALLEGATI_X_DOMANDA INNER JOIN
                      dbo.ALLEGATI ON dbo.ALLEGATI_X_DOMANDA.ID_ALLEGATO = dbo.ALLEGATI.ID_ALLEGATO INNER JOIN
                      dbo.TIPO_ALLEGATO ON dbo.ALLEGATI.COD_TIPO = dbo.TIPO_ALLEGATO.CODICE
