CREATE VIEW [dbo].[vBANDO_RESPONSABILI]
AS
SELECT     dbo.BANDO_RESPONSABILI.ID, dbo.BANDO_RESPONSABILI.ID_BANDO, dbo.BANDO_RESPONSABILI.ID_UTENTE, dbo.BANDO_RESPONSABILI.PROVINCIA, 
                      dbo.BANDO_RESPONSABILI.ATTIVO, dbo.BANDO_RESPONSABILI.DATA, dbo.BANDO_RESPONSABILI.OPERATORE, 
                      dbo.PROVINCE.DENOMINAZIONE AS DENOMINAZIONE_PROVINCIA, dbo.vUTENTI.NOMINATIVO, dbo.vUTENTI.COD_ENTE, dbo.vUTENTI.ENTE, 
                      dbo.vUTENTI.PROFILO
FROM         dbo.BANDO_RESPONSABILI LEFT OUTER JOIN
                      dbo.PROVINCE ON dbo.BANDO_RESPONSABILI.PROVINCIA = dbo.PROVINCE.SIGLA INNER JOIN
                      dbo.vUTENTI ON dbo.BANDO_RESPONSABILI.ID_UTENTE = dbo.vUTENTI.ID_UTENTE
