

CREATE VIEW [dbo].[vBANDO]
AS
SELECT dbo.BANDO.ID_BANDO, dbo.BANDO.COD_ENTE, dbo.BANDO.DESCRIZIONE, dbo.BANDO.PAROLE_CHIAVE, dbo.BANDO.DATA_INSERIMENTO, 
               dbo.BANDO.DISPOSIZIONI_ATTUATIVE, dbo.BANDO.ID_SCHEDA_VALUTAZIONE, dbo.BANDO.MULTIPROGETTO, dbo.BANDO.MULTIMISURA, 
               dbo.BANDO.INTERESSE_FILIERA, dbo.BANDO.FASCICOLO_RICHIESTO, dbo.BANDO.ID_STORICO_ULTIMO, dbo.BANDO.DATA_APERTURA, 
               dbo.BANDO.ID_MODELLO_DOMANDA, dbo.BANDO.ID_PROGRAMMAZIONE, dbo.BANDO.ID_INTEGRAZIONE_ULTIMA, 
               dbo.BANDO_INTEGRAZIONI.DATA_SCADENZA, dbo.BANDO_INTEGRAZIONI.IMPORTO, dbo.BANDO_INTEGRAZIONI.IMPORTO_DI_MISURA, 
               dbo.BANDO_INTEGRAZIONI.QUOTA_RISERVA, dbo.BANDO_INTEGRAZIONI.ID_ATTO AS ID_ATTO_INTEGRAZIONE, dbo.vBANDO_STORICO.COD_STATO, 
               dbo.vBANDO_STORICO.DATA, dbo.vBANDO_STORICO.OPERATORE, dbo.vBANDO_STORICO.SEGNATURA, dbo.vBANDO_STORICO.ID_ATTO, 
               dbo.vBANDO_STORICO.ORDINE_STATO, dbo.vBANDO_STORICO.STATO, dbo.vBANDO_STORICO.PROFILO, dbo.vBANDO_STORICO.NOMINATIVO, 
               dbo.ENTE.COD_TIPO_ENTE, dbo.ENTE.DESCRIZIONE AS ENTE, dbo.BANDO.FIRMA_RICHIESTA, dbo.BANDO.ABILITA_VALUTAZIONE
FROM  dbo.BANDO INNER JOIN
               dbo.vBANDO_STORICO ON dbo.BANDO.ID_STORICO_ULTIMO = dbo.vBANDO_STORICO.ID INNER JOIN
               dbo.BANDO_INTEGRAZIONI ON dbo.BANDO.ID_INTEGRAZIONE_ULTIMA = dbo.BANDO_INTEGRAZIONI.ID INNER JOIN
               dbo.ENTE ON dbo.BANDO.COD_ENTE = dbo.ENTE.COD_ENTE


