CREATE VIEW [dbo].[vCERTIFICAZIONE_CONTI]
AS
SELECT     
ID_CERTIFICAZIONE_CONTI,
ANNO_CONTABILE_DA, 
ANNO_CONTABILE_A, 
DATA_PRESENTAZIONE_CONTI, 
ISTANZA_CERTIFICAZIONE_CONTI, 
CF_OPERATORE, 
FLAG_DEFINITIVO, 
DATA_INSERIMENTO, 
DATA_MODIFICA
FROM         
CERTIFICAZIONE_CONTI
