CREATE VIEW [dbo].[vCONTROLLI_PARAMETRI_X_DOMANDA]
AS
SELECT     dbo.CONTROLLI_PARAMETRI_X_DOMANDA.ID_DOMANDA_PAGAMENTO, dbo.CONTROLLI_PARAMETRI_X_DOMANDA.PUNTEGGIO, 
                      dbo.CONTROLLI_PARAMETRI_X_DOMANDA.DATA_VALUTAZIONE, dbo.CONTROLLI_PARAMETRI_X_DOMANDA.OPERATORE, 
                      dbo.CONTROLLI_PARAMETRI_X_DOMANDA.ID_PARAMETRO, dbo.CONTROLLI_PARAMETRI_X_DOMANDA.ID_LOTTO, 
                      dbo.CONTROLLI_PARAMETRI_DI_RISCHIO.DESCRIZIONE, dbo.CONTROLLI_PARAMETRI_DI_RISCHIO.QUERY_SQL, 
                      dbo.CONTROLLI_PARAMETRI_DI_RISCHIO.MANUALE
FROM         dbo.CONTROLLI_PARAMETRI_X_DOMANDA INNER JOIN
                      dbo.CONTROLLI_PARAMETRI_X_LOTTO ON dbo.CONTROLLI_PARAMETRI_X_DOMANDA.ID_LOTTO = dbo.CONTROLLI_PARAMETRI_X_LOTTO.ID_LOTTO AND 
                      dbo.CONTROLLI_PARAMETRI_X_DOMANDA.ID_PARAMETRO = dbo.CONTROLLI_PARAMETRI_X_LOTTO.ID_PARAMETRO INNER JOIN
                      dbo.CONTROLLI_PARAMETRI_DI_RISCHIO ON dbo.CONTROLLI_PARAMETRI_X_LOTTO.ID_PARAMETRO = dbo.CONTROLLI_PARAMETRI_DI_RISCHIO.ID_PARAMETRO
