CREATE VIEW [dbo].[vCONTO_CORRENTE]
AS
SELECT     dbo.CONTO_CORRENTE.ID_CONTO_CORRENTE, dbo.CONTO_CORRENTE.ID_IMPRESA, dbo.CONTO_CORRENTE.ID_PERSONA, dbo.CONTO_CORRENTE.COD_PAESE, 
                      dbo.CONTO_CORRENTE.CIN_EURO, dbo.CONTO_CORRENTE.CIN, dbo.CONTO_CORRENTE.ABI, dbo.CONTO_CORRENTE.CAB, dbo.CONTO_CORRENTE.NUMERO, 
                      dbo.CONTO_CORRENTE.NOTE, dbo.CONTO_CORRENTE.DATA_INIZIO_VALIDITA, dbo.CONTO_CORRENTE.DATA_FINE_VALIDITA, dbo.CONTO_CORRENTE.ISTITUTO, 
                      dbo.CONTO_CORRENTE.AGENZIA, dbo.CONTO_CORRENTE.ID_COMUNE, dbo.COMUNI.COD_BELFIORE, dbo.COMUNI.DENOMINAZIONE AS COMUNE, 
                      dbo.COMUNI.SIGLA, dbo.COMUNI.CAP
FROM         dbo.CONTO_CORRENTE INNER JOIN
                      dbo.COMUNI ON dbo.CONTO_CORRENTE.ID_COMUNE = dbo.COMUNI.ID_COMUNE
