CREATE VIEW [dbo].[vCONTROLLI_PARAMETRI_X_LOTTO]
AS
SELECT     dbo.CONTROLLI_PARAMETRI_X_LOTTO.ID_LOTTO, dbo.CONTROLLI_PARAMETRI_X_LOTTO.ID_PARAMETRO, dbo.CONTROLLI_PARAMETRI_X_LOTTO.PESO_REALE, 
                      dbo.CONTROLLI_PARAMETRI_DI_RISCHIO.DESCRIZIONE, dbo.CONTROLLI_PARAMETRI_DI_RISCHIO.QUERY_SQL, dbo.CONTROLLI_PARAMETRI_DI_RISCHIO.PESO, 
                      dbo.CONTROLLI_PARAMETRI_DI_RISCHIO.MANUALE
FROM         dbo.CONTROLLI_PARAMETRI_X_LOTTO INNER JOIN
                      dbo.CONTROLLI_PARAMETRI_DI_RISCHIO ON dbo.CONTROLLI_PARAMETRI_X_LOTTO.ID_PARAMETRO = dbo.CONTROLLI_PARAMETRI_DI_RISCHIO.ID_PARAMETRO
