CREATE VIEW [dbo].[vCORRETTIVA_RENDICONTAZIONE]
AS
SELECT     dbo.CORRETTIVA_RENDICONTAZIONE.ID, dbo.CORRETTIVA_RENDICONTAZIONE.ID_DOMANDA_PAGAMENTO, dbo.CORRETTIVA_RENDICONTAZIONE.CONCLUSA, 
                      dbo.CORRETTIVA_RENDICONTAZIONE.ANNULLATA, dbo.CORRETTIVA_RENDICONTAZIONE.ID_UTENTE, dbo.CORRETTIVA_RENDICONTAZIONE.DATA, 
                      dbo.CORRETTIVA_RENDICONTAZIONE.ID_NOTE, dbo.NOTE.TESTO AS NOTE, dbo.vUTENTI.NOMINATIVO, dbo.vUTENTI.COD_ENTE
FROM         dbo.CORRETTIVA_RENDICONTAZIONE INNER JOIN
                      dbo.NOTE ON dbo.CORRETTIVA_RENDICONTAZIONE.ID_NOTE = dbo.NOTE.ID INNER JOIN
                      dbo.vUTENTI ON dbo.CORRETTIVA_RENDICONTAZIONE.ID_UTENTE = dbo.vUTENTI.ID_UTENTE
