CREATE VIEW vDATE_PROGETTI
AS  

WITH PSORD AS
(
	SELECT
	A.ID_PROGETTO,
	MAX(A.DATA) AS DATA,
	A.COD_STATO,
	ROW_NUMBER() OVER(PARTITION BY A.ID_PROGETTO ORDER BY MAX(A.DATA) ASC) AS NR_STATO 
	FROM 
	(
		SELECT 
		PS1.ID_PROGETTO,
		MAX(PS1.DATA) AS DATA,
		--DATEADD(DAY,1,MAX(PS1.DATA)) DATA,
		CASE WHEN PS1.COD_STATO IN ('V','S','T','E','R','Y','C','O','X') THEN 'V' ELSE PS1.COD_STATO END COD_STATO 
		FROM PROGETTO_STORICO PS1
		--WHERE 
		--PS1.COD_STATO IN ('P','L','F','V','S','O','T','C') 
		GROUP BY 
		PS1.ID_PROGETTO,
		PS1.COD_STATO
		UNION 
		SELECT 
		ID_PROGETTO,
		DATEADD(DAY,1,MAX(DATA)) DATA,
		'F1' AS COD_STATO
		FROM
		PROGETTO_STORICO
		WHERE 
		COD_STATO='F'
		AND NOT EXISTS
		(
		 SELECT NULL FROM PROGETTO_STORICO PS2
		 --WHERE PS2.COD_STATO IN ('V') AND 
		 WHERE PS2.COD_STATO IN ('V','S','T','E','R','Y','C','O','X') AND 
		 PS2.ID_PROGETTO = PROGETTO_STORICO.ID_PROGETTO
		)
		GROUP BY 
		ID_PROGETTO,
		COD_STATO
	) AS A
	WHERE A.COD_STATO IS NOT NULL
	--and A.ID_PROGETTO = 11592
	GROUP BY 
	A.ID_PROGETTO,
	A.COD_STATO
),

PSG AS 
(
	SELECT 
	B.ID_PROGETTO,
	B.COD_STATO,
	MAX(B.DATA) DATA
	FROM 
	(	
		SELECT 
		ID_PROGETTO,
		--COD_STATO,
		CASE WHEN COD_STATO IN ('V','S','T','E','R','Y','C','O','X') THEN 'V' ELSE COD_STATO END COD_STATO ,
		MAX(DATA) DATA
		FROM
		PROGETTO_STORICO 
		--WHERE 
		--COD_STATO IN ('P','L','F','V','S','O','T','C') 
		GROUP BY 
		ID_PROGETTO,
		COD_STATO
		UNION 
		SELECT 
		ID_PROGETTO,
		'F1' AS COD_STATO,
		--MAX(DATA) DATA
		DATEADD(DAY,1,MAX(DATA)) DATA
		FROM
		PROGETTO_STORICO
		WHERE 
		COD_STATO='F'
		AND NOT EXISTS
		(
		 SELECT NULL FROM PROGETTO_STORICO PS2
		 --WHERE PS2.COD_STATO IN ('V') AND 
		 WHERE PS2.COD_STATO IN ('V','S','T','E','R','Y','C','O','X') AND 
		 PS2.ID_PROGETTO = PROGETTO_STORICO.ID_PROGETTO
		)
		GROUP BY 
		ID_PROGETTO,
		COD_STATO
	) AS B
	GROUP BY 
	B.ID_PROGETTO,
	B.COD_STATO
),

REQ_DATE AS (
SELECT 
PP.ID_PROGETTO,
PP.ID_PRIORITA,
CASE PP.ID_PRIORITA
WHEN 122 THEN 'D_INIZIO_PREV'
WHEN 123 THEN 'D_FINE_PREV'
WHEN 368 THEN 'D_INIZIO_PREV'
WHEN 369 THEN 'D_FINE_PREV'
WHEN 400 THEN 'D_INIZIO_PREV'
WHEN 401 THEN 'D_FINE_PREV' END AS TIPO_DATA_FASE,
PP.VAL_DATA 
FROM PRIORITA_X_PROGETTO PP
WHERE ID_PRIORITA 
IN 
(122,123,368,369,400,401) 

UNION ALL

SELECT 
P.ID_PROGETTO,
RP.ID_REQUISITO,
--DP.COD_TIPO,
CASE RP.ID_REQUISITO
WHEN 5 THEN 'D_AVVIO_EFF_LAVORI'
WHEN 6 THEN 'D_FINE_PREV_LAVORI'
WHEN 51 THEN 'D_FINE_PREV_LAVORI'
WHEN 7 THEN 'D_FINE_EFF_LAVORI'
END AS TIPO_DATA_FASE,
CASE RP.ID_REQUISITO 
WHEN 5 THEN MIN(RP.VAL_DATA) 
WHEN 6 THEN MIN(RP.VAL_DATA)
WHEN 51 THEN MIN(RP.VAL_DATA)
WHEN 7 THEN MAX(RP.VAL_DATA)
END AS VAL_DATA
FROM 
DOMANDA_PAGAMENTO_REQUISITI RP
INNER JOIN 
DOMANDA_DI_PAGAMENTO DP ON
RP.ID_DOMANDA_PAGAMENTO = DP.ID_DOMANDA_PAGAMENTO
AND 
DP.APPROVATA = 1
INNER JOIN 
vPROGETTO P ON 
DP.ID_PROGETTO = P.ID_PROGETTO
WHERE 
ID_REQUISITO 
IN 
(5,6,7,51)
--AND P.ID_PROGETTO = 12885 --12237--12236--10037
GROUP BY 
P.ID_PROGETTO,
RP.ID_REQUISITO
),

DATE_IMP AS (
	SELECT 
	P.ID_PROGETTO,
	ATTIG.DATA AS DATA_IMPEGNO
	FROM vPROGETTO P 
	INNER JOIN vBANDO B ON
	P.ID_BANDO = B.ID_BANDO
	INNER JOIN zPROGRAMMAZIONE PRG ON
	B.ID_PROGRAMMAZIONE = PRG.ID
	INNER JOIN zPSR_ALBERO PA ON
	PRG.COD_TIPO = PA.CODICE
	INNER JOIN zPSR PSR ON
	PA.COD_PSR = PSR.CODICE
	LEFT OUTER JOIN GRADUATORIA_PROGETTI GPR ON
	P.ID_PROGETTO = GPR.ID_PROGETTO
	LEFT OUTER JOIN BANDO_CONFIG BCA ON
	B.ID_BANDO = BCA.ID_BANDO 
	AND 
	BCA.COD_TIPO = 'TPAPPALTO'
	AND 
	BCA.ATTIVO = 1 
	AND 
	BCA.VALORE = '04'
	LEFT OUTER JOIN (
		SELECT 
		GPA.ID_PROGETTO,
		MIN(ATTI.DATA) AS [DATA]
		FROM
		GRADUATORIA_PROGETTI_ATTI GPA
		INNER JOIN 
		ATTI ON
		GPA.ID_ATTO = ATTI.ID_ATTO
		WHERE GPA.IMPORTO > 0
		GROUP BY GPA.ID_PROGETTO
	) AS ATTIG ON
	P.ID_PROGETTO = ATTIG.ID_PROGETTO
	WHERE 
	P.COD_STATO IN ('F','V','S','O','T','X','C','Y','E','R') 
	AND 
	PSR.CODICE = 'POR20142020'
	AND PRG.ID NOT IN (17,18,19)
	AND
	P.COD_AGEA IS NOT NULL
)

select * from (
SELECT 
P.ID_PROGETTO AS COD_LOCALE_PROGETTO,
--PS.COD_STATO,
CASE
WHEN DMF.CUP_NATURA ='01' AND PS.COD_STATO IN ('F') THEN '0101'
WHEN DMF.CUP_NATURA ='01' AND PS.COD_STATO IN ('F1','V','S','T') THEN '0102'
WHEN DMF.CUP_NATURA ='02' AND PS.COD_STATO IN ('F') THEN '0201'
WHEN DMF.CUP_NATURA ='02' AND PS.COD_STATO IN ('F1','V','S','T') THEN '0202'
WHEN DMF.CUP_NATURA ='03' AND PS.COD_STATO IN ('P','L') THEN '0301'
WHEN DMF.CUP_NATURA ='03' AND PS.COD_STATO IN ('F') THEN '0305'
WHEN DMF.CUP_NATURA ='03' AND PS.COD_STATO IN ('F1','V','S','T') THEN '0306'
WHEN DMF.CUP_NATURA ='03' AND PS.COD_STATO IN ('C') THEN '0307'
WHEN DMF.CUP_NATURA ='06' AND PS.COD_STATO IN ('F') THEN '0601'
WHEN DMF.CUP_NATURA ='06' AND PS.COD_STATO IN ('F1','V','S','T') THEN '0602'
WHEN DMF.CUP_NATURA ='07' AND PS.COD_STATO IN ('F') THEN '0701'
WHEN DMF.CUP_NATURA ='07' AND PS.COD_STATO IN ('F1','V','S','T') THEN '0702'
WHEN DMF.CUP_NATURA ='08' AND PS.COD_STATO IN ('F') THEN '0801'
WHEN DMF.CUP_NATURA ='08' AND PS.COD_STATO IN ('F1','V','S','T') THEN '0802'
END AS COD_FASE,
--PS.COD_STATO,
--PSORD1.COD_STATO COD_STATO_1,
--dbo.DateToString_Igrue(PS.DATA) DATA_INIZIO_PREVISTA,
CASE 
--WHEN PS.COD_STATO IN ('F') THEN DATE_INI_PREV.VAL_DATA END AS DATA_INIZIO_PREVISTA_2,
WHEN DMF.CUP_NATURA ='01' AND PS.COD_STATO IN ('F') THEN dbo.DateToString_Igrue(DATE_IMP.DATA_IMPEGNO)
WHEN DMF.CUP_NATURA ='01' AND PS.COD_STATO IN ('F1','V','S','T') THEN dbo.DateToString_Igrue(ISNULL(DATE_INI_PREV.VAL_DATA,DATE_IMP.DATA_IMPEGNO))
WHEN DMF.CUP_NATURA ='02' AND PS.COD_STATO IN ('F') THEN dbo.DateToString_Igrue(DATE_IMP.DATA_IMPEGNO)
WHEN DMF.CUP_NATURA ='02' AND PS.COD_STATO IN ('F1','V','S','T') THEN dbo.DateToString_Igrue(ISNULL(DATE_INI_PREV.VAL_DATA,DATE_IMP.DATA_IMPEGNO))
WHEN DMF.CUP_NATURA ='03' AND PS.COD_STATO IN ('P','L') THEN dbo.DateToString_Igrue(PS.DATA) --gestire
WHEN DMF.CUP_NATURA ='03' AND PS.COD_STATO IN ('F') THEN dbo.DateToString_Igrue(ISNULL(DATE_INI_PREV.VAL_DATA,DATE_IMP.DATA_IMPEGNO))
WHEN DMF.CUP_NATURA ='03' AND PS.COD_STATO IN ('F1','V','S','T') THEN dbo.DateToString_Igrue(ISNULL(DATE_INI_PREV.VAL_DATA,DATE_IMP.DATA_IMPEGNO))
WHEN DMF.CUP_NATURA ='03' AND PS.COD_STATO IN ('C') THEN dbo.DateToString_Igrue(DATE_IMP.DATA_IMPEGNO) --gestire
WHEN DMF.CUP_NATURA ='06' AND PS.COD_STATO IN ('F') THEN dbo.DateToString_Igrue(DATE_IMP.DATA_IMPEGNO)
WHEN DMF.CUP_NATURA ='06' AND PS.COD_STATO IN ('F1','V','S','T') THEN dbo.DateToString_Igrue(ISNULL(DATE_INI_PREV.VAL_DATA,DATE_IMP.DATA_IMPEGNO))
WHEN DMF.CUP_NATURA ='07' AND PS.COD_STATO IN ('F') THEN dbo.DateToString_Igrue(DATE_IMP.DATA_IMPEGNO)
WHEN DMF.CUP_NATURA ='07' AND PS.COD_STATO IN ('F1','V','S','T') THEN dbo.DateToString_Igrue(ISNULL(DATE_INI_PREV.VAL_DATA,DATE_IMP.DATA_IMPEGNO))
WHEN DMF.CUP_NATURA ='08' AND PS.COD_STATO IN ('F') THEN dbo.DateToString_Igrue(DATE_IMP.DATA_IMPEGNO)
WHEN DMF.CUP_NATURA ='08' AND PS.COD_STATO IN ('F1','V','S','T') THEN dbo.DateToString_Igrue(ISNULL(DATE_INI_PREV.VAL_DATA,DATE_IMP.DATA_IMPEGNO))
END AS DATA_INIZIO_PREVISTA,
--PS.DATA AS DATA_INIZIO_EFFETTIVA,
--NULL AS DATA_INIZIO_EFFETTIVA,

CASE 
--WHEN PS.COD_STATO IN ('F') THEN DATE_INI_PREV.VAL_DATA END AS DATA_INIZIO_PREVISTA_2,
WHEN DMF.CUP_NATURA ='01' AND PS.COD_STATO IN ('F') THEN dbo.DateToString_Igrue(DATE_IMP.DATA_IMPEGNO)
--WHEN DMF.CUP_NATURA ='01' AND PS.COD_STATO IN ('F1','V','S','T') THEN dbo.DateToString_Igrue(DATE_INI_EFF.VAL_DATA)
WHEN DMF.CUP_NATURA ='01' AND PS.COD_STATO IN ('F1','V','S','T') THEN dbo.DateToString_Igrue(ISNULL(DATE_INI_EFF.VAL_DATA,DATE_IMP.DATA_IMPEGNO))
WHEN DMF.CUP_NATURA ='02' AND PS.COD_STATO IN ('F') THEN dbo.DateToString_Igrue(DATE_IMP.DATA_IMPEGNO)
--WHEN DMF.CUP_NATURA ='02' AND PS.COD_STATO IN ('F1','V','S','T') THEN dbo.DateToString_Igrue(DATE_INI_EFF.VAL_DATA)
WHEN DMF.CUP_NATURA ='02' AND PS.COD_STATO IN ('F1','V','S','T') THEN dbo.DateToString_Igrue(ISNULL(DATE_INI_EFF.VAL_DATA,DATE_IMP.DATA_IMPEGNO))
WHEN DMF.CUP_NATURA ='03' AND PS.COD_STATO IN ('P','L') THEN dbo.DateToString_Igrue(PS.DATA) --gestire
--WHEN DMF.CUP_NATURA ='03' AND PS.COD_STATO IN ('F') THEN dbo.DateToString_Igrue(DATE_INI_EFF.VAL_DATA)
WHEN DMF.CUP_NATURA ='03' AND PS.COD_STATO IN ('F') THEN dbo.DateToString_Igrue(ISNULL(DATE_INI_EFF.VAL_DATA,DATE_IMP.DATA_IMPEGNO))
--WHEN DMF.CUP_NATURA ='03' AND PS.COD_STATO IN ('F1','V','S','T') THEN dbo.DateToString_Igrue(DATE_INI_EFF.VAL_DATA)
WHEN DMF.CUP_NATURA ='03' AND PS.COD_STATO IN ('F1','V','S','T') THEN dbo.DateToString_Igrue(ISNULL(DATE_INI_EFF.VAL_DATA,DATE_IMP.DATA_IMPEGNO))
WHEN DMF.CUP_NATURA ='03' AND PS.COD_STATO IN ('C') THEN dbo.DateToString_Igrue(DATE_IMP.DATA_IMPEGNO) --gestire
WHEN DMF.CUP_NATURA ='06' AND PS.COD_STATO IN ('F') THEN dbo.DateToString_Igrue(DATE_IMP.DATA_IMPEGNO)
WHEN DMF.CUP_NATURA ='06' AND PS.COD_STATO IN ('F1','V','S','T') THEN dbo.DateToString_Igrue(ISNULL(DATE_INI_EFF.VAL_DATA,DATE_IMP.DATA_IMPEGNO))
WHEN DMF.CUP_NATURA ='07' AND PS.COD_STATO IN ('F') THEN dbo.DateToString_Igrue(DATE_IMP.DATA_IMPEGNO)
--WHEN DMF.CUP_NATURA ='07' AND PS.COD_STATO IN ('F1','V','S','T') THEN dbo.DateToString_Igrue(DATE_INI_EFF.VAL_DATA)
WHEN DMF.CUP_NATURA ='07' AND PS.COD_STATO IN ('F1','V','S','T') THEN dbo.DateToString_Igrue(ISNULL(DATE_INI_EFF.VAL_DATA,DATE_IMP.DATA_IMPEGNO))
WHEN DMF.CUP_NATURA ='08' AND PS.COD_STATO IN ('F') THEN dbo.DateToString_Igrue(DATE_IMP.DATA_IMPEGNO)
--WHEN DMF.CUP_NATURA ='08' AND PS.COD_STATO IN ('F1','V','S','T') THEN dbo.DateToString_Igrue(DATE_INI_EFF.VAL_DATA)
WHEN DMF.CUP_NATURA ='08' AND PS.COD_STATO IN ('F1','V','S','T') THEN dbo.DateToString_Igrue(ISNULL(DATE_INI_EFF.VAL_DATA,DATE_IMP.DATA_IMPEGNO))
END AS DATA_INIZIO_EFFETTIVA,
CASE 
WHEN DMF.CUP_NATURA ='01' AND PS.COD_STATO IN ('F') THEN dbo.DateToString_Igrue(DATE_IMP.DATA_IMPEGNO)
WHEN DMF.CUP_NATURA ='01' AND PS.COD_STATO IN ('F1','V','S','T') THEN dbo.DateToString_Igrue(ISNULL(DATE_FINE_PREV_LAV.VAL_DATA,DATEADD(MONTH,18,DATE_IMP.DATA_IMPEGNO)))
WHEN DMF.CUP_NATURA ='02' AND PS.COD_STATO IN ('F') THEN dbo.DateToString_Igrue(DATE_IMP.DATA_IMPEGNO)
WHEN DMF.CUP_NATURA ='02' AND PS.COD_STATO IN ('F1','V','S','T') THEN dbo.DateToString_Igrue(ISNULL(DATE_FINE_PREV_LAV.VAL_DATA,DATEADD(MONTH,18,DATE_IMP.DATA_IMPEGNO)))
WHEN DMF.CUP_NATURA ='03' AND PS.COD_STATO IN ('P','L') THEN dbo.DateToString_Igrue(PS.DATA) --gestire
WHEN DMF.CUP_NATURA ='03' AND PS.COD_STATO IN ('F') THEN dbo.DateToString_Igrue(ISNULL(DATE_FINE_PREV.VAL_DATA,DATE_IMP.DATA_IMPEGNO))
WHEN DMF.CUP_NATURA ='03' AND PS.COD_STATO IN ('F1','V','S','T') THEN dbo.DateToString_Igrue(ISNULL(DATE_FINE_PREV_LAV.VAL_DATA,DATEADD(MONTH,18,DATE_IMP.DATA_IMPEGNO)))
WHEN DMF.CUP_NATURA ='03' AND PS.COD_STATO IN ('C') THEN dbo.DateToString_Igrue(DATE_IMP.DATA_IMPEGNO) --gestire
WHEN DMF.CUP_NATURA ='06' AND PS.COD_STATO IN ('F') THEN dbo.DateToString_Igrue(DATE_IMP.DATA_IMPEGNO)
WHEN DMF.CUP_NATURA ='06' AND PS.COD_STATO IN ('F1','V','S','T') THEN dbo.DateToString_Igrue(ISNULL(DATE_FINE_PREV_LAV.VAL_DATA,DATEADD(MONTH,18,DATE_IMP.DATA_IMPEGNO)))
WHEN DMF.CUP_NATURA ='07' AND PS.COD_STATO IN ('F') THEN dbo.DateToString_Igrue(DATE_IMP.DATA_IMPEGNO)
WHEN DMF.CUP_NATURA ='07' AND PS.COD_STATO IN ('F1','V','S','T') THEN dbo.DateToString_Igrue(ISNULL(DATE_FINE_PREV_LAV.VAL_DATA,DATEADD(MONTH,18,DATE_IMP.DATA_IMPEGNO)))
WHEN DMF.CUP_NATURA ='08' AND PS.COD_STATO IN ('F') THEN dbo.DateToString_Igrue(DATE_IMP.DATA_IMPEGNO)
WHEN DMF.CUP_NATURA ='08' AND PS.COD_STATO IN ('F1','V','S','T') THEN dbo.DateToString_Igrue(ISNULL(DATE_FINE_PREV_LAV.VAL_DATA,DATEADD(MONTH,18,DATE_IMP.DATA_IMPEGNO)))
END AS DATA_FINE_PREVISTA,
--PSORD1.DATA DATA_FINE_EFFETTIVA,
--NULL AS DATA_FINE_EFFETTIVA,
CASE 
WHEN DMF.CUP_NATURA ='01' AND PS.COD_STATO IN ('F') THEN dbo.DateToString_Igrue(DATE_IMP.DATA_IMPEGNO)
WHEN DMF.CUP_NATURA ='01' AND PS.COD_STATO IN ('F1','V','S','T') THEN dbo.DateToString_Igrue(DATE_FINE_EFF.VAL_DATA)
WHEN DMF.CUP_NATURA ='02' AND PS.COD_STATO IN ('F') THEN dbo.DateToString_Igrue(DATE_IMP.DATA_IMPEGNO)
WHEN DMF.CUP_NATURA ='02' AND PS.COD_STATO IN ('F1','V','S','T') THEN dbo.DateToString_Igrue(DATE_FINE_EFF.VAL_DATA)
WHEN DMF.CUP_NATURA ='03' AND PS.COD_STATO IN ('P','L') THEN dbo.DateToString_Igrue(PS.DATA) --gestire
--WHEN DMF.CUP_NATURA ='03' AND PS.COD_STATO IN ('F') THEN dbo.DateToString_Igrue(DATE_FINE_EFF.VAL_DATA)
--WHEN DMF.CUP_NATURA ='03' AND PS.COD_STATO IN ('F') THEN dbo.DateToString_Igrue(DATE_IMP.DATA_IMPEGNO)
WHEN DMF.CUP_NATURA ='03' AND PS.COD_STATO IN ('F') THEN dbo.DateToString_Igrue(ISNULL(DATE_INI_EFF.VAL_DATA,DATE_IMP.DATA_IMPEGNO))
WHEN DMF.CUP_NATURA ='03' AND PS.COD_STATO IN ('F1','V','S','T') THEN dbo.DateToString_Igrue(DATE_FINE_EFF.VAL_DATA)
--WHEN DMF.CUP_NATURA ='03' AND PS.COD_STATO IN ('C') THEN dbo.DateToString_Igrue(DATE_IMP.DATA_IMPEGNO) --gestire
WHEN DMF.CUP_NATURA ='03' AND PS.COD_STATO IN ('C') THEN dbo.DateToString_Igrue(DATE_FINE_EFF.VAL_DATA) --gestire
WHEN DMF.CUP_NATURA ='06' AND PS.COD_STATO IN ('F') THEN dbo.DateToString_Igrue(DATE_IMP.DATA_IMPEGNO)
WHEN DMF.CUP_NATURA ='06' AND PS.COD_STATO IN ('F1','V','S','T') THEN dbo.DateToString_Igrue(DATE_FINE_EFF.VAL_DATA)
WHEN DMF.CUP_NATURA ='07' AND PS.COD_STATO IN ('F') THEN dbo.DateToString_Igrue(DATE_IMP.DATA_IMPEGNO)
WHEN DMF.CUP_NATURA ='07' AND PS.COD_STATO IN ('F1','V','S','T') THEN dbo.DateToString_Igrue(DATE_FINE_EFF.VAL_DATA)
WHEN DMF.CUP_NATURA ='08' AND PS.COD_STATO IN ('F') THEN dbo.DateToString_Igrue(DATE_IMP.DATA_IMPEGNO)
WHEN DMF.CUP_NATURA ='08' AND PS.COD_STATO IN ('F1','V','S','T') THEN dbo.DateToString_Igrue(DATE_FINE_EFF.VAL_DATA)
END AS DATA_FINE_EFFETTIVA,
NULL AS FLG_CANCELLAZIONE,
--PSORD.COD_STATO,
--PSORD.NR_STATO,
--PSORD1.COD_STATO COD_STATO_SUCC,
--PSORD1.NR_STATO AS NR_STATO_SUCC,
--@IdInvio AS ID_INVIO,
--ISNULL(@rNumber,0) + ROW_NUMBER() OVER(ORDER BY P.ID_PROGETTO ASC) AS NR_RIGA_INVIO,
'FESR20142020' AS CODICE_FONDO 
FROM vPROGETTO P
INNER JOIN vBANDO B ON
P.ID_BANDO = B.ID_BANDO
--INNER JOIN PROGETTO_STORICO PS ON
--P.ID_PROGETTO = PS.ID_PROGETTO
INNER JOIN PSG PS ON
P.ID_PROGETTO = PS.ID_PROGETTO
INNER JOIN BANDO_PROGRAMMAZIONE BP ON
B.ID_BANDO = BP.ID_BANDO
INNER JOIN zPROGRAMMAZIONE PRG ON
BP.ID_PROGRAMMAZIONE = PRG.ID
INNER JOIN zPSR_ALBERO PA ON
PRG.COD_TIPO = PA.CODICE
INNER JOIN zPSR PSR ON
PA.COD_PSR = PSR.CODICE
--INNER JOIN BANDO_RESPONSABILI BR ON
--B.ID_BANDO = BR.ID_BANDO
INNER JOIN DATI_MONITORAGGIO_FESR DMF ON
P.ID_PROGETTO = DMF.ID_PROGETTO
INNER JOIN PSORD ON
PS.ID_PROGETTO = PSORD.ID_PROGETTO
AND
PS.COD_STATO = PSORD.COD_STATO
LEFT OUTER JOIN PSORD PSORD1 ON
PSORD1.ID_PROGETTO = PSORD.ID_PROGETTO
AND
PSORD1.NR_STATO = PSORD.NR_STATO + 1
LEFT OUTER JOIN REQ_DATE DATE_INI_PREV ON 
P.ID_PROGETTO = DATE_INI_PREV.ID_PROGETTO
AND 
DATE_INI_PREV.TIPO_DATA_FASE = 'D_INIZIO_PREV'
LEFT OUTER JOIN REQ_DATE DATE_FINE_PREV ON 
P.ID_PROGETTO = DATE_FINE_PREV.ID_PROGETTO
AND 
DATE_FINE_PREV.TIPO_DATA_FASE = 'D_FINE_PREV'
LEFT OUTER JOIN REQ_DATE DATE_INI_EFF ON 
P.ID_PROGETTO = DATE_INI_EFF.ID_PROGETTO
AND 
DATE_INI_EFF.TIPO_DATA_FASE = 'D_AVVIO_EFF_LAVORI'
LEFT OUTER JOIN REQ_DATE DATE_FINE_EFF ON 
P.ID_PROGETTO = DATE_FINE_EFF.ID_PROGETTO
AND 
DATE_FINE_EFF.TIPO_DATA_FASE = 'D_FINE_EFF_LAVORI'
LEFT OUTER JOIN REQ_DATE DATE_FINE_PREV_LAV ON 
P.ID_PROGETTO = DATE_FINE_PREV_LAV.ID_PROGETTO
AND 
DATE_FINE_PREV_LAV.TIPO_DATA_FASE = 'D_FINE_PREV_LAVORI'
LEFT OUTER JOIN DATE_IMP ON 
P.ID_PROGETTO = DATE_IMP.ID_PROGETTO
WHERE 
PS.COD_STATO IN ('F','F1','V','S','O','T','X','C','Y','E','R') 
AND 
PSR.CODICE = 'POR20142020'
AND 
PRG.ID NOT IN (17,18,19)
AND
BP.ID_PROGRAMMAZIONE NOT IN (17,18,19)
AND
P.COD_AGEA IS NOT NULL
--26/01/2018
--CLAUSOLA TEMPORANEA PER ESCLUDERE PROGETTO STRUMENTI FINANZIARI ARTIGIANCASSA
AND P.ID_PROGETTO <> 13301
) t WHERE
t.COD_FASE IN ('0102','0202','0306','0602','0702','0802')