
CREATE VIEW [dbo].[vIGRUE_VOCI_SPESA]
AS
SELECT     
TC37.VOCE_SPESA, 
TC37.DESCRIZIONE_VOCE_SPESA,
TC37.CODICE_NATURA_CUP,
TC37.DESCRIZIONE_NATURA_CUP
FROM         
[IGRUE_MONIT].dbo.IGRUE_T_TC37 TC37

