


CREATE VIEW [dbo].[vIMPRESA_SOCI]
AS
SELECT     dbo.IMPRESA_SOCI.ID, dbo.IMPRESA_SOCI.ID_IMPRESA, dbo.IMPRESA_SOCI.ID_SOCIO, dbo.IMPRESA_SOCI.ATTIVO, dbo.IMPRESA_SOCI.DATA_INIZIO_VALIDITA, 
                      dbo.IMPRESA_SOCI.DATA_FINE_VALIDITA, dbo.IMPRESA_SOCI.ID_OPERATORE_INIZIO, dbo.IMPRESA_SOCI.ID_OPERATORE_FINE, dbo.vIMPRESA.CUAA, 
                      dbo.vIMPRESA.CODICE_FISCALE, dbo.vIMPRESA.RAGIONE_SOCIALE, dbo.vIMPRESA.FORMA_GIURIDICA, dbo.IMPRESA_SOCI.COD_TIPO_SOCIO, 
                      S.DESCRIZIONE AS TIPO_SOCIO
FROM         dbo.IMPRESA_SOCI INNER JOIN
                      dbo.vIMPRESA ON dbo.vIMPRESA.ID_IMPRESA = dbo.IMPRESA_SOCI.ID_SOCIO INNER JOIN
                      dbo.TIPO_SOCIO AS S ON S.CODICE = dbo.IMPRESA_SOCI.COD_TIPO_SOCIO



