CREATE VIEW vLOTTO_DI_REVISIONE
AS
SELECT LOTTO_DI_REVISIONE.ID_LOTTO, LOTTO_DI_REVISIONE.ID_BANDO, LOTTO_DI_REVISIONE.PROVINCIA, LOTTO_DI_REVISIONE.DATA_CREAZIONE, 
	LOTTO_DI_REVISIONE.CF_OPERATORE, LOTTO_DI_REVISIONE.DATA_MODIFICA, LOTTO_DI_REVISIONE.NUMERO_ESTRAZIONI, 
	LOTTO_DI_REVISIONE.REVISIONE_CONCLUSA,
		(SELECT     COUNT(*) AS Expr1
        FROM        CTE_TESTATA_VALIDAZIONE -- REVISIONE_DOMANDA_PAGAMENTO
        WHERE      (ID_LOTTO = LOTTO_DI_REVISIONE.ID_LOTTO)) AS NUMERO_DOMANDE_ASSEGNATE,
        (SELECT     COUNT(*) AS Expr1
        FROM        CTE_TESTATA_VALIDAZIONE AS REVISIONE_DOMANDA_PAGAMENTO_1 -- REVISIONE_DOMANDA_PAGAMENTO AS REVISIONE_DOMANDA_PAGAMENTO_1
        WHERE      (ID_LOTTO = LOTTO_DI_REVISIONE.ID_LOTTO) AND (SELEZIONATA_X_REVISIONE = 1)) AS NUMERO_DOMANDE_ESTRATTE,  
	PERSONA_FISICA.COGNOME + ' ' + PERSONA_FISICA.NOME AS OPERATORE
FROM LOTTO_DI_REVISIONE 
	JOIN PERSONA_FISICA ON LOTTO_DI_REVISIONE.CF_OPERATORE = PERSONA_FISICA.CODICE_FISCALE
GO
