CREATE VIEW [dbo].[vMANDATI_IMPRESA]
AS
SELECT     dbo.MANDATI_IMPRESA.ID, dbo.MANDATI_IMPRESA.ID_IMPRESA, dbo.MANDATI_IMPRESA.ID_UTENTE_ABILITATO, dbo.MANDATI_IMPRESA.COD_ENTE, 
                      dbo.MANDATI_IMPRESA.CODICE_SPORTELLO_CAA, dbo.MANDATI_IMPRESA.TIPO_MANDATO, dbo.MANDATI_IMPRESA.ATTIVO, 
                      dbo.MANDATI_IMPRESA.DATA_INIZIO_VALIDITA, dbo.MANDATI_IMPRESA.DATA_FINE_VALIDITA, dbo.MANDATI_IMPRESA.ID_OPERATORE_INIZIO, 
                      dbo.MANDATI_IMPRESA.ID_OPERATORE_FINE, dbo.MANDATI_IMPRESA.SEGNATURA_MANDATO, dbo.MANDATI_IMPRESA.SEGNATURA_REVOCA, 
                      dbo.IMPRESA.CUAA, dbo.IMPRESA.CODICE_FISCALE, dbo.IMPRESA.ANNO_COSTITUZIONE, dbo.IMPRESA.ID_STORICO_ULTIMO, 
                      dbo.IMPRESA.ID_CONTO_CORRENTE_ULTIMO, dbo.IMPRESA.ID_RAPPRLEGALE_ULTIMO, dbo.IMPRESA.ID_SEDELEGALE_ULTIMO, 
                      dbo.IMPRESA_STORICO.RAGIONE_SOCIALE, dbo.IMPRESA_STORICO.COD_FORMA_GIURIDICA, dbo.IMPRESA_STORICO.ID_DIMENSIONE, 
                      dbo.ENTE.COD_TIPO_ENTE, dbo.ENTE.DESCRIZIONE AS ENTE
FROM         dbo.MANDATI_IMPRESA INNER JOIN
                      dbo.IMPRESA ON dbo.MANDATI_IMPRESA.ID_IMPRESA = dbo.IMPRESA.ID_IMPRESA LEFT OUTER JOIN
                      dbo.ENTE ON dbo.MANDATI_IMPRESA.COD_ENTE = dbo.ENTE.COD_ENTE LEFT OUTER JOIN
                      dbo.IMPRESA_STORICO ON dbo.IMPRESA.ID_STORICO_ULTIMO = dbo.IMPRESA_STORICO.ID_STORICO_IMPRESA
