

CREATE VIEW [dbo].[vPROGETTO_COMUNICAZIONI]
AS
SELECT     dbo.PROGETTO_COMUNICAZIONI.ID, dbo.PROGETTO_COMUNICAZIONI.ID_PROGETTO, dbo.PROGETTO_COMUNICAZIONI.ID_DOMANDA_PAGAMENTO, 
                      dbo.PROGETTO_COMUNICAZIONI.ID_VARIANTE, dbo.PROGETTO_COMUNICAZIONI.COD_TIPO, dbo.PROGETTO_COMUNICAZIONI.DATA, 
                      dbo.PROGETTO_COMUNICAZIONI.SEGNATURA, dbo.PROGETTO_COMUNICAZIONI.OPERATORE, dbo.PROGETTO_COMUNICAZIONI.ID_NOTE, 
                      dbo.PROGETTO_COMUNICAZIONI.ISTRUTTORE, dbo.PROGETTO_COMUNICAZIONI.ESITO, dbo.PROGETTO_COMUNICAZIONI.ID_DECRETO, 
                      dbo.PROGETTO_COMUNICAZIONI.ID_COMUNICAZIONE_RIFERIMENTO, dbo.PROGETTO_COMUNICAZIONI.DIREZIONE, 
                      dbo.TIPO_SEGNATURA.DESCRIZIONE AS TIPO_SEGNATURA, dbo.TIPO_SEGNATURA.GIORNI_PREVISTI, dbo.TIPO_SEGNATURA.FLAG_DOMANDA_AIUTO, 
                      dbo.TIPO_SEGNATURA.FLAG_DOMANDA_PAGAMENTO, dbo.TIPO_SEGNATURA.FLAG_VARIANTE, dbo.vUTENTI.NOMINATIVO AS NOMINATIVO_OPERATORE, 
                      dbo.vUTENTI.CF_UTENTE AS CF_OPERATORE, ISTRUTTORE.CF_UTENTE AS CF_ISTRUTTORE, ISTRUTTORE.NOMINATIVO AS NOMINATIVO_ISTRUTTORE, 
                      dbo.ATTI.NUMERO AS NUM_ATTO, dbo.ATTI.DATA AS DATA_ATTO, dbo.ATTI.DESCRIZIONE AS DESCRIZIONE_ATTO, dbo.PROGETTO.ID_BANDO, dbo.vIMPRESA.CUAA, 
                      dbo.vIMPRESA.CODICE_FISCALE, dbo.vIMPRESA.RAGIONE_SOCIALE, dbo.PROGETTO_COMUNICAZIONI.PREDISPOSTA_ALLA_FIRMA, 
                      dbo.PROGETTO_COMUNICAZIONI.DATA_ISTRUTTORIA, dbo.PROGETTO_COMUNICAZIONI.SEGNATURA_ISTRUTTORIA, 
                      dbo.PROGETTO_COMUNICAZIONI.ID_NOTE_ISTRUTTORIA, dbo.PROGETTO_COMUNICAZIONI.COD_ENTE_EMETTITORE, 
                      dbo.PROGETTO_COMUNICAZIONI.ID_COMUNE, CASE WHEN dbo.PROGETTO_COMUNICAZIONI.ID_COMUNE IS NULL 
                      THEN dbo.ENTE.DESCRIZIONE ELSE 'COMUNE DI ' + dbo.COMUNI.DENOMINAZIONE + ' (' + dbo.COMUNI.SIGLA + ')' END AS ENTE, dbo.ENTE.COD_TIPO_ENTE
FROM         dbo.vIMPRESA INNER JOIN
                      dbo.PROGETTO ON dbo.vIMPRESA.ID_IMPRESA = dbo.PROGETTO.ID_IMPRESA RIGHT OUTER JOIN
                      dbo.PROGETTO_COMUNICAZIONI INNER JOIN
                      dbo.TIPO_SEGNATURA ON dbo.PROGETTO_COMUNICAZIONI.COD_TIPO = dbo.TIPO_SEGNATURA.COD_TIPO LEFT OUTER JOIN
                      dbo.ATTI ON dbo.PROGETTO_COMUNICAZIONI.ID_DECRETO = dbo.ATTI.ID_ATTO ON 
                      dbo.PROGETTO.ID_PROGETTO = dbo.PROGETTO_COMUNICAZIONI.ID_PROGETTO LEFT OUTER JOIN
                      dbo.vUTENTI AS ISTRUTTORE ON dbo.PROGETTO_COMUNICAZIONI.ISTRUTTORE = ISTRUTTORE.ID_UTENTE LEFT OUTER JOIN
                      dbo.vUTENTI ON dbo.PROGETTO_COMUNICAZIONI.OPERATORE = dbo.vUTENTI.ID_UTENTE LEFT OUTER JOIN
                      dbo.ENTE ON dbo.PROGETTO_COMUNICAZIONI.COD_ENTE_EMETTITORE = dbo.ENTE.COD_ENTE LEFT OUTER JOIN
                      dbo.COMUNI ON dbo.PROGETTO_COMUNICAZIONI.ID_COMUNE = dbo.COMUNI.ID_COMUNE


