CREATE VIEW VRECUPERO_PAGAMENTI_BENEFICIARIO AS (
SELECT 
	ID_ACCORPAMENTO_INVESTIMENTI,
	ref.value('ID_PAGAMENTO_BENEFICIARIO[1]', 'INT') AS ID_PAGAMENTO_BENEFICIARIO,
	ref.value('ID_PAGAMENTO_RICHIESTO[1]', 'INT') AS ID_PAGAMENTO_RICHIESTO,
	ref.value('ID_GIUSTIFICATIVO[1]', 'INT') AS ID_GIUSTIFICATIVO,
	CASE 
		WHEN ref.value('IMPORTO_RICHIESTO[1]', 'VARCHAR(MAX)') = ''
		THEN null
		ELSE ref.value('IMPORTO_RICHIESTO[1]', 'DECIMAL(18,2)')
	END AS IMPORTO_RICHIESTO,
	CASE 
		WHEN ref.value('IMPORTO_AMMESSO[1]', 'VARCHAR(MAX)') = ''
		THEN null
		ELSE ref.value('IMPORTO_AMMESSO[1]', 'DECIMAL(18,2)')
	END AS IMPORTO_AMMESSO,
	CASE 
		WHEN ref.value('CONTRIBUTO_AMMESSO[1]', 'VARCHAR(MAX)') = ''
		THEN null
		ELSE ref.value('CONTRIBUTO_AMMESSO[1]', 'DECIMAL(18,2)')
	END AS CONTRIBUTO_AMMESSO,
	CASE 
		WHEN ref.value('QUOTA_CONTRIBUTO_AMMESSO[1]', 'VARCHAR(MAX)') = ''
		THEN null
		ELSE ref.value('QUOTA_CONTRIBUTO_AMMESSO[1]', 'DECIMAL(10,2)')
	END AS QUOTA_CONTRIBUTO_AMMESSO,
	CASE 
		WHEN ref.value('COD_RIDUZIONE[1]', 'VARCHAR(MAX)') = ''
		THEN null
		ELSE ref.value('COD_RIDUZIONE[1]', 'VARCHAR(MAX)')
	END AS COD_RIDUZIONE,
	CASE 
		WHEN ref.value('MOTIVAZIONE_RIDUZIONE[1]', 'VARCHAR(MAX)') = ''
		THEN null
		ELSE ref.value('MOTIVAZIONE_RIDUZIONE[1]', 'INT')
	END AS MOTIVAZIONE_RIDUZIONE,
	CASE 
		WHEN ref.value('IMPORTO_NONAMM_NONRESP[1]', 'VARCHAR(MAX)') = ''
		THEN null
		ELSE ref.value('IMPORTO_NONAMM_NONRESP[1]', 'DECIMAL(18,2)')
	END AS IMPORTO_NONAMM_NONRESP,
	CASE 
		WHEN ref.value('IMPORTO_AMMESSO_CONTR[1]', 'VARCHAR(MAX)') = ''
		THEN null
		ELSE ref.value('IMPORTO_AMMESSO_CONTR[1]', 'DECIMAL(18,2)')
	END AS IMPORTO_AMMESSO_CONTR,
	CASE 
		WHEN ref.value('IMPORTO_NONAMM_CONTR_NONRESP[1]', 'VARCHAR(MAX)') = ''
		THEN null
		ELSE ref.value('IMPORTO_NONAMM_CONTR_NONRESP[1]', 'DECIMAL(18,2)')
	END AS IMPORTO_NONAMM_CONTR_NONRESP,
	CASE 
		WHEN ref.value('SPESA_TECNICA_RICHIESTA[1]', 'VARCHAR(MAX)') = ''
		THEN null
		ELSE ref.value('SPESA_TECNICA_RICHIESTA[1]', 'BIT')
	END AS SPESA_TECNICA_RICHIESTA,
	CASE 
		WHEN ref.value('SPESA_TECNICA_AMMESSA[1]', 'VARCHAR(MAX)') = ''
		THEN null
		ELSE ref.value('SPESA_TECNICA_AMMESSA[1]', 'BIT')
	END AS SPESA_TECNICA_AMMESSA,
	CASE 
		WHEN ref.value('SPESA_TECNICA_AMMESSA_CONTR[1]', 'VARCHAR(MAX)') = ''
		THEN null
		ELSE ref.value('SPESA_TECNICA_AMMESSA_CONTR[1]', 'BIT')
	END AS SPESA_TECNICA_AMMESSA_CONTR,
	CASE 
		WHEN ref.value('COSTITUISCE_VARIANTE[1]', 'VARCHAR(MAX)') = ''
		THEN null
		ELSE ref.value('COSTITUISCE_VARIANTE[1]', 'BIT')
	END AS COSTITUISCE_VARIANTE,
	CASE 
		WHEN ref.value('COD_RIDUZIONE_CONTR[1]', 'VARCHAR(MAX)') = ''
		THEN null
		ELSE ref.value('COD_RIDUZIONE_CONTR[1]', 'VARCHAR(MAX)')
	END AS COD_RIDUZIONE_CONTR,
	CASE 
		WHEN ref.value('MOTIVAZIONE_RIDUZIONE_CONTR[1]', 'VARCHAR(MAX)') = ''
		THEN null
		ELSE ref.value('MOTIVAZIONE_RIDUZIONE_CONTR[1]', 'INT')
	END AS MOTIVAZIONE_RIDUZIONE_CONTR
FROM ACCORPAMENTO_INVESTIMENTI I
	CROSS APPLY
	I.ISTANZA_PIANO_INVESTIMENTI.nodes('//IstanzaPianoInvestimenti/PAGAMENTI_BENEFICIARIO/PAGAMENTO_BENEFICIARIO') AS AUT_MODIFICA_PERC_AIUTO1(ref)
WHERE 1 = 1);
go