CREATE VIEW VRECUPERO_PRIORITA_X_INVESTIMENTI AS (
SELECT 
	ID_ACCORPAMENTO_INVESTIMENTI,
	ref.value('ID_PRIORITA[1]', 'INT') AS ID_PRIORITA,
	ref.value('ID_INVESTIMENTO[1]', 'INT') AS ID_INVESTIMENTO,
	CASE 
		WHEN ref.value('ID_VALORE[1]', 'VARCHAR(MAX)') = ''
		THEN null
		ELSE ref.value('ID_VALORE[1]', 'INT')
	END AS ID_VALORE,
	ref.value('SCELTO[1]', 'BIT') AS SCELTO,
	CASE 
		WHEN ref.value('VALORE[1]', 'VARCHAR(MAX)') = ''
		THEN null
		ELSE ref.value('VALORE[1]', 'DECIMAL(18,2)')
	END AS VALORE,
	CASE 
		WHEN ref.value('VAL_DATA[1]', 'VARCHAR(MAX)') = ''
		THEN null
		ELSE ref.value('VAL_DATA[1]', 'DATETIME')
	END AS VAL_DATA,
	CASE 
		WHEN ref.value('VAL_TESTO[1]', 'VARCHAR(MAX)') = ''
		THEN null
		ELSE ref.value('VAL_TESTO[1]', 'VARCHAR(MAX)')
	END AS VAL_TESTO
FROM ACCORPAMENTO_INVESTIMENTI I
	CROSS APPLY
	I.ISTANZA_PIANO_INVESTIMENTI.nodes('//IstanzaPianoInvestimenti/PRIORITA_X_INVESTIMENTI/PRIORITA_X_INVESTIMENTI') AS PRIORITA_X_INVESTIMENTI1(ref)
WHERE 1 = 1);
go