CREATE VIEW VRECUPERO_PAGAMENTI_RICHIESTI AS (
SELECT 
	ID_ACCORPAMENTO_INVESTIMENTI,
	ref.value('ID_PAGAMENTO_RICHIESTO[1]', 'INT') AS ID_PAGAMENTO_RICHIESTO,
	ref.value('ID_DOMANDA_PAGAMENTO[1]', 'INT') AS ID_DOMANDA_PAGAMENTO,
	ref.value('ID_INVESTIMENTO[1]', 'INT') AS ID_INVESTIMENTO,
	CASE 
		WHEN ref.value('DATA_RICHIESTA_PAGAMENTO[1]', 'VARCHAR(MAX)') = ''
		THEN null
		ELSE ref.value('DATA_RICHIESTA_PAGAMENTO[1]', 'DATETIME')
	END AS DATA_RICHIESTA_PAGAMENTO,
	CASE 
		WHEN ref.value('IMPORTO_COMPUTO_METRICO[1]', 'VARCHAR(MAX)') = ''
		THEN null
		ELSE ref.value('IMPORTO_COMPUTO_METRICO[1]', 'DECIMAL(18,2)')
	END AS IMPORTO_COMPUTO_METRICO,
	CASE 
		WHEN ref.value('IMPORTO_RICHIESTO[1]', 'VARCHAR(MAX)') = ''
		THEN null
		ELSE ref.value('IMPORTO_RICHIESTO[1]', 'DECIMAL(18,2)')
	END AS IMPORTO_RICHIESTO,
	CASE 
		WHEN ref.value('CONTRIBUTO_RICHIESTO[1]', 'VARCHAR(MAX)') = ''
		THEN null
		ELSE ref.value('CONTRIBUTO_RICHIESTO[1]', 'DECIMAL(18,2)')
	END AS CONTRIBUTO_RICHIESTO,
	CASE 
		WHEN ref.value('CONTRIBUTO_RICHIESTO_ALTRE_FONTI[1]', 'VARCHAR(MAX)') = ''
		THEN null
		ELSE ref.value('CONTRIBUTO_RICHIESTO_ALTRE_FONTI[1]', 'DECIMAL(18,2)')
	END AS CONTRIBUTO_RICHIESTO_ALTRE_FONTI,
	CASE 
		WHEN ref.value('IMPORTO_DISAVANZO_COSTI_AMMESSI[1]', 'VARCHAR(MAX)') = ''
		THEN null
		ELSE ref.value('IMPORTO_DISAVANZO_COSTI_AMMESSI[1]', 'DECIMAL(18,2)')
	END AS IMPORTO_DISAVANZO_COSTI_AMMESSI,
	CASE 
		WHEN ref.value('CONTRIBUTO_DISAVANZO_COSTI_AMMESSI[1]', 'VARCHAR(MAX)') = ''
		THEN null
		ELSE ref.value('CONTRIBUTO_DISAVANZO_COSTI_AMMESSI[1]', 'DECIMAL(18,2)')
	END AS CONTRIBUTO_DISAVANZO_COSTI_AMMESSI,
	CASE 
		WHEN ref.value('CONTRIBUTO_RICHIESTO_RECUPERO_ANTICIPO[1]', 'VARCHAR(MAX)') = ''
		THEN null
		ELSE ref.value('CONTRIBUTO_RICHIESTO_RECUPERO_ANTICIPO[1]', 'DECIMAL(18,2)')
	END AS CONTRIBUTO_RICHIESTO_RECUPERO_ANTICIPO,
	CASE 
		WHEN ref.value('IMPORTO_COMPUTO_METRICO_AMMESSO[1]', 'VARCHAR(MAX)') = ''
		THEN null
		ELSE ref.value('IMPORTO_COMPUTO_METRICO_AMMESSO[1]', 'DECIMAL(18,2)')
	END AS IMPORTO_COMPUTO_METRICO_AMMESSO,
	CASE 
		WHEN ref.value('IMPORTO_AMMESSO[1]', 'VARCHAR(MAX)') = ''
		THEN null
		ELSE ref.value('IMPORTO_AMMESSO[1]', 'DECIMAL(18,2)')
	END AS IMPORTO_AMMESSO,
	CASE 
		WHEN ref.value('CONTRIBUTO_AMMESSO[1]', 'VARCHAR(MAX)') = ''
		THEN null
		ELSE ref.value('CONTRIBUTO_AMMESSO[1]', 'DECIMAL(18,2)')
	END AS CONTRIBUTO_AMMESSO,
	CASE 
		WHEN ref.value('CONTRIBUTO_AMMESSO_ALTRE_FONTI[1]', 'VARCHAR(MAX)') = ''
		THEN null
		ELSE ref.value('CONTRIBUTO_AMMESSO_ALTRE_FONTI[1]', 'DECIMAL(18,2)')
	END AS CONTRIBUTO_AMMESSO_ALTRE_FONTI,
	CASE 
		WHEN ref.value('CONTRIBUTO_AMMESSO_RECUPERO_ANTICIPO[1]', 'VARCHAR(MAX)') = ''
		THEN null
		ELSE ref.value('CONTRIBUTO_AMMESSO_RECUPERO_ANTICIPO[1]', 'DECIMAL(18,2)')
	END AS CONTRIBUTO_AMMESSO_RECUPERO_ANTICIPO,
	CASE 
		WHEN ref.value('AMMESSO[1]', 'VARCHAR(MAX)') = ''
		THEN null
		ELSE ref.value('AMMESSO[1]', 'BIT')
	END AS AMMESSO,
	CASE 
		WHEN ref.value('ISTRUTTORE[1]', 'VARCHAR(MAX)') = ''
		THEN null
		ELSE ref.value('ISTRUTTORE[1]', 'VARCHAR(MAX)')
	END AS ISTRUTTORE,
	CASE 
		WHEN ref.value('DATA_VALUTAZIONE[1]', 'VARCHAR(MAX)') = ''
		THEN null
		ELSE ref.value('DATA_VALUTAZIONE[1]', 'DATETIME')
	END AS DATA_VALUTAZIONE,
	CASE 
		WHEN ref.value('NOTE_ISTRUTTORE[1]', 'VARCHAR(MAX)') = ''
		THEN null
		ELSE ref.value('NOTE_ISTRUTTORE[1]', 'VARCHAR(MAX)')
	END AS NOTE_ISTRUTTORE,
	CASE 
		WHEN ref.value('COD_SANZIONE_VARIAZIONE_INVESTIMENTI[1]', 'VARCHAR(MAX)') = ''
		THEN null
		ELSE ref.value('COD_SANZIONE_VARIAZIONE_INVESTIMENTI[1]', 'VARCHAR(3)')
	END AS COD_SANZIONE_VARIAZIONE_INVESTIMENTI
FROM ACCORPAMENTO_INVESTIMENTI I
	CROSS APPLY
	I.ISTANZA_PIANO_INVESTIMENTI.nodes('//IstanzaPianoInvestimenti/PAGAMENTI_RICHIESTI/PAGAMENTO_RICHIESTO') AS AUT_MODIFICA_PERC_AIUTO1(ref)
WHERE 1 = 1);
go