CREATE VIEW VRECUPERO_AUT_MODIFICA_PERC_AIUTO AS (
SELECT 
	ID_ACCORPAMENTO_INVESTIMENTI,
	ref.value('ID_AUTORIZZAZIONE[1]', 'INT') AS ID_AUTORIZZAZIONE,
	ref.value('DATA_INSERIMENTO[1]', 'DATETIME') AS DATA_INSERIMENTO,
	ref.value('CF_INSERIMENTO[1]', 'VARCHAR(MAX)') AS CF_INSERIMENTO,
	ref.value('DATA_MODIFICA[1]', 'DATETIME') AS DATA_MODIFICA,
	ref.value('CF_MODIFICA[1]', 'VARCHAR(MAX)') AS CF_MODIFICA,
	ref.value('ID_INVESTIMENTO[1]', 'INT') AS ID_INVESTIMENTO,
	ref.value('COSTO_INVESTIMENTO_PRECEDENTE[1]', 'DECIMAL(18,2)') AS COSTO_INVESTIMENTO_PRECEDENTE,
	ref.value('COSTO_INVESTIMENTO_AUTORIZZATO[1]', 'DECIMAL(18,2)') AS COSTO_INVESTIMENTO_AUTORIZZATO,
	ref.value('QUANTITA_PRECEDENTE[1]', 'DECIMAL(10,2)') AS QUANTITA_PRECEDENTE,
	ref.value('QUANTITA_AUTORIZZATA[1]', 'DECIMAL(10,2)') AS QUANTITA_AUTORIZZATA,
	ref.value('PERC_PRECEDENTE[1]', 'DECIMAL(10,2)') AS PERC_PRECEDENTE,
	ref.value('PERC_AUTORIZZATA[1]', 'DECIMAL(10,2)') AS PERC_AUTORIZZATA
FROM ACCORPAMENTO_INVESTIMENTI I
	CROSS APPLY
	I.ISTANZA_PIANO_INVESTIMENTI.nodes('//IstanzaPianoInvestimenti/AUT_MODIFICA_PERC_AIUTO/AUT_MODIFICA_PERC_AIUTO') AS AUT_MODIFICA_PERC_AIUTO1(ref)
WHERE 1 = 1);
go
