CREATE VIEW vRITIRI_RECUPERI
AS 
WITH INTERVENTI AS                   
(
SELECT  ASSE.ID ID_ASSE,
        ASSE.CODICE COD_ASSE,
        ASSE.DESCRIZIONE DESC_ASSE,
        AZIONE.ID ID_AZIONE,
        AZIONE.CODICE COD_AZIONE,
        AZIONE.DESCRIZIONE DESC_AZIONE,
        IP.ID ID_INTERVENTO,
        IP.CODICE COD_INTERVENTO,
        IP.DESCRIZIONE DESC_INTERVENTO
FROM    zPROGRAMMAZIONE IP
        INNER JOIN 
        zPROGRAMMAZIONE AZIONE ON AZIONE.ID = IP.ID_PADRE
        INNER JOIN 
        zPROGRAMMAZIONE ASSE ON ASSE.ID = AZIONE.ID_PADRE
WHERE IP.COD_TIPO = 'POR20142020L3')

SELECT 
	IRR.ID_PROGETTO,
	PROG.COD_AZIONE,
	PROG.DESC_AZIONE,
	ID_IRREGOLARITA AS ID_RITIRO,
	'Irregolarità' AS TIPO_RITIRO,
	'RITIRO' AS TIPO,
	IRR.RAGIONE_SOCIALE_IMPRESA_IRREGOLARITA AS BENEFICIARIO,
	DESCRIZIONE_CONTROLLO_ORIGINE as SOGGETTO_ORIGINE,
	NUMERO_PROTOCOLLO,
	DATA_COSTATAZIONE_AMMINISTRATIVA,
	CONTRIBUTO_PUBBLICO * 0.70 AS FESR,
	CONTRIBUTO_PUBBLICO * 0.35 AS STATO,
	CONTRIBUTO_PUBBLICO * 0.15 AS REGIONE,
	CONTRIBUTO_PUBBLICO AS TOTALE_PUBBLICO,
	0 AS PRIVATI,
	PROG.ID_AZIONE
FROM 
	vIRREGOLARITA IRR
	INNER JOIN vPROGETTO P 
	ON P.ID_PROGETTO = IRR.ID_PROGETTO
	INNER JOIN vBANDO_PROGRAMMAZIONE VBP 
	ON VBP.ID_BANDO = P.ID_BANDO and vbp.COD_PSR = 'POR20142020' AND vbp.DESCRIZIONE NOT LIKE '%DA ELIMINARE%'
	INNER JOIN INTERVENTI PROG
	ON PROG.ID_INTERVENTO = VBP.ID_PROGRAMMAZIONE
WHERE 
	AZIONE_CERTIFICAZIONE LIKE 'RITIRO'
	
UNION

SELECT 
	ERR.ID_PROGETTO,
	PROG.COD_AZIONE,
	PROG.DESC_AZIONE,
	ERR.ID_ERRORE AS ID_RITIRO,
	'Errore' AS TIPO_RITIRO,
	'RITIRO' AS TIPO,
	IMP.RAGIONE_SOCIALE  AS BENEFICIARIO,
	SOGGETTO_RILEVAZIONE as SOGGETTO_ORIGINE,
	ERR_ALL.SEGNATURA_ALLEGATO as NUMERO_PROTOCOLLO,
	DATA_RILEVAZIONE as DATA_COSTATAZIONE_AMMINISTRATIVA,
	CONTRIBUTO_PUBBLICO_ERRORE * 0.70 AS FESR,
	CONTRIBUTO_PUBBLICO_ERRORE * 0.35 AS STATO,
	CONTRIBUTO_PUBBLICO_ERRORE * 0.15 AS REGIONE,
	CONTRIBUTO_PUBBLICO_ERRORE AS TOTALE_PUBBLICO,
	0 AS PRIVATI,
	PROG.ID_AZIONE
FROM 
	ERRORE ERR
	INNER JOIN vPROGETTO P 
	ON P.ID_PROGETTO = ERR.ID_PROGETTO
	INNER JOIN vBANDO_PROGRAMMAZIONE VBP 
	ON VBP.ID_BANDO = P.ID_BANDO and vbp.COD_PSR = 'POR20142020' AND vbp.DESCRIZIONE NOT LIKE '%DA ELIMINARE%'
	INNER JOIN INTERVENTI PROG
	ON PROG.ID_INTERVENTO = VBP.ID_PROGRAMMAZIONE
	LEFT JOIN vIMPRESA IMP 
	ON IMP.CODICE_FISCALE = IMPRESE_BENEFICIARI
	LEFT JOIN ERRORE_ALLEGATI ERR_ALL
	ON ERR_ALL.ID_ERRORE = ERR.ID_ERRORE
GO