CREATE VIEW vRNA_COVID_ESITO_CONCESSIONE
AS
SELECT 
	P.ID_BANDO,
	P.ID_PROGETTO,
	P.COD_STATO,
	I.ID_IMPRESA,
	I.CODICE_FISCALE,
	I.RAGIONE_SOCIALE,
	CASE
		WHEN LOG_CONC.ID_RNA_LOG_CONCESSIONE IS NULL THEN 'daInviare'
		WHEN NOT LOG_CONC.CODICE_ESITO = 0 THEN 'erroreRichiesta'
		WHEN LOG_CONC.CODICE_ESITO = 0 AND LOG_CONC.CODICE_ESITO_STATO_RICHIESTA IS NULL THEN 'daVerificareEsito'
		WHEN LOG_CONC.CODICE_ESITO = 0 AND LOG_CONC.CODICE_ESITO_STATO_RICHIESTA <> 0 THEN 'erroreRichiesta'
		WHEN PROG_COR.ANNULLATO = 1 THEN 'daInviare'
		WHEN PROG_COR.CONFERMATO = 1 THEN 'completata'
		WHEN PROG_COR.CONFERMATO = 0 THEN 'daConfermareCOR'
		ELSE 'ALTRO'--QUI NON CI DEVE ARRIVARE!
		END AS STATO_CONCESSIONE,
	LOG_CONC.ID_RICHIESTA,
	LOG_CONC.COR,
	PROG_COR.DATA_ASSEGNAZIONE_COR,
	G.PUNTEGGIO,
	ISNULL(G.ORDINE,999999) AS ORDINE,
	G.FINANZIABILITA,
	COV.DEFINITIVA,
	LOG_CONC.PRODUZIONE
FROM
	vPROGETTO P INNER JOIN 
	COVID_AUTODICHIARAZIONE COV ON P.ID_PROGETTO = COV.ID_PROGETTO INNER JOIN
(SELECT ID_IMPRESA, ID_PROGETTO FROM PROGETTO
UNION
SELECT IA.ID_IMPRESA, ID_PROGETTO FROM
IMPRESA_AGGREGAZIONE IA INNER JOIN
PROGETTO_NATURA_SOGGETTO PNS 
ON PNS.ID_AGGREGAZIONE = IA.ID_AGGREGAZIONE AND IA.ATTIVO = 1) IMP
ON IMP.ID_PROGETTO = P.ID_PROGETTO INNER JOIN
vIMPRESA I ON I.ID_IMPRESA = IMP.ID_IMPRESA LEFT JOIN
(SELECT *
	FROM RNA_LOG_CONCESSIONI t1
	WHERE
	( SELECT COUNT(*)
		FROM RNA_LOG_CONCESSIONI AS t2
		WHERE t1.ID_PROGETTO = t2.ID_PROGETTO AND t1.ID_IMPRESA = t2.ID_IMPRESA
		AND t2.DATA_INSERIMENTO > t1.DATA_INSERIMENTO AND t2.PRODUZIONE=1
		) = 0 AND t1.PRODUZIONE=1 ) LOG_CONC 
ON LOG_CONC.ID_PROGETTO = P.ID_PROGETTO AND LOG_CONC.ID_IMPRESA = IMP.ID_IMPRESA  lEFT JOIN
RNA_PROGETTO_COR PROG_COR 
ON PROG_COR.ID_RICHIESTA = LOG_CONC.ID_RICHIESTA LEFT JOIN
GRADUATORIA_PROGETTI G 
ON P.ID_PROGETTO = G.ID_PROGETTO
WHERE COV.DEFINITIVA = 1 