CREATE VIEW vRNA_COMPONENTI_X_CODIFICA
AS
	SELECT
		COMP.ID_COMPONENTI_X_CODIFICA,
		PR.ID_PROCEDIMENTI_REGOLAMENTI,
		O.ID_OBIETTIVO,
		COMP.ID_CODIFICA_INVESTIMENTO,
		PR.CODICE_REGOLAMENTO, 
		PR.DESCRIZIONE,
		PR.SETTORE,
		O.OBIETTIVO	
	FROM
		RNA_COMPONENTI_X_CODIFICA COMP INNER JOIN
		RNA_OBIETTIVI O ON O.ID_OBIETTIVO = COMP.ID_RNA_OBIETTIVO INNER JOIN
		RNA_PROCEDIMENTI_E_REGOLAMENTI PR ON PR.ID_PROCEDIMENTI_REGOLAMENTI = COMP.ID_RNA_PROCEDIMENTI_E_REGOLAMENTI