


CREATE VIEW [dbo].[vVARIANTI_ALLEGATI]
AS
SELECT     dbo.VARIANTI_ALLEGATI.ID_ALLEGATO, dbo.VARIANTI_ALLEGATI.ID_VARIANTE, dbo.VARIANTI_ALLEGATI.COD_TIPO_DOCUMENTO, dbo.VARIANTI_ALLEGATI.ID_FILE, 
                      dbo.VARIANTI_ALLEGATI.DESCRIZIONE, dbo.VARIANTI_ALLEGATI.COD_ENTE_EMETTITORE, dbo.VARIANTI_ALLEGATI.ID_COMUNE, 
                      dbo.VARIANTI_ALLEGATI.NUMERO, dbo.VARIANTI_ALLEGATI.DATA, dbo.VARIANTI_ALLEGATI.COD_ESITO, dbo.VARIANTI_ALLEGATI.NOTE_ISTRUTTORE, 
                      dbo.ESITI_STEP.DESCRIZIONE AS ESITO, dbo.ESITI_STEP.ESITO_POSITIVO, ISNULL(dbo.TIPO_DOCUMENTO.FORMATO, 'C') AS FORMATO, 
                      ISNULL(dbo.TIPO_ALLEGATO.DESCRIZIONE, 'Supporto Cartaceo') AS TIPO_ALLEGATO, dbo.TIPO_DOCUMENTO.DESCRIZIONE AS TIPOLOGIA_DOCUMENTO, 
                      CASE WHEN varianti_allegati.ID_COMUNE IS NULL 
                      THEN ENTE.DESCRIZIONE ELSE 'COMUNE DI ' + COMUNI.DENOMINAZIONE + ' (' + COMUNI.SIGLA + ')' END AS ENTE, 
                      dbo.ARCHIVIO_FILE.DIMENSIONE / 1024 AS DIMENSIONE_FILE
FROM         dbo.VARIANTI_ALLEGATI LEFT OUTER JOIN
                      dbo.ARCHIVIO_FILE ON dbo.VARIANTI_ALLEGATI.ID_FILE = dbo.ARCHIVIO_FILE.ID LEFT OUTER JOIN
                      dbo.ENTE ON dbo.VARIANTI_ALLEGATI.COD_ENTE_EMETTITORE = dbo.ENTE.COD_ENTE LEFT OUTER JOIN
                      dbo.COMUNI ON dbo.VARIANTI_ALLEGATI.ID_COMUNE = dbo.COMUNI.ID_COMUNE LEFT OUTER JOIN
                      dbo.TIPO_DOCUMENTO ON dbo.VARIANTI_ALLEGATI.COD_TIPO_DOCUMENTO = dbo.TIPO_DOCUMENTO.CODICE LEFT OUTER JOIN
                      dbo.ESITI_STEP ON dbo.VARIANTI_ALLEGATI.COD_ESITO = dbo.ESITI_STEP.COD_ESITO LEFT OUTER JOIN
                      dbo.TIPO_ALLEGATO ON dbo.TIPO_DOCUMENTO.FORMATO = dbo.TIPO_ALLEGATO.CODICE



