
CREATE VIEW [dbo].[vzDIMENSIONI_ESTRAZIONI_IO]
AS
SELECT        dbo.zDIMENSIONI_ESTRAZIONI_IO.COD_PSR, dbo.zDIMENSIONI_ESTRAZIONI_IO.ID_DIM_PRIORITA, zDIMENSIONI_1.CODICE AS CodPriorita, 
                         zDIMENSIONI_1.DESCRIZIONE AS DesPriorita, zDIMENSIONI_1.ORDINE AS OrdPriorita, dbo.zDIMENSIONI_ESTRAZIONI_IO.ID_DIM_INDICATORE, 
                         dbo.zDIMENSIONI.CODICE AS CodIndicatore, dbo.zDIMENSIONI.DESCRIZIONE AS DesIndicatore, dbo.zDIMENSIONI.ORDINE AS OrdIndicatore, 
                         dbo.zDIMENSIONI_ESTRAZIONI_IO.VALORE_RTOT, dbo.zDIMENSIONI_ESTRAZIONI_IO.VALORE_PF, dbo.zDIMENSIONI_ESTRAZIONI_IO.DATA_PF, 
                         dbo.zDIMENSIONI_ESTRAZIONI_IO.VALORE_F, dbo.zDIMENSIONI_ESTRAZIONI_IO.DATA_F, dbo.zDIMENSIONI_ESTRAZIONI_IO.ID_ESTRAZIONE, 
                         dbo.zDIMENSIONI_ESTRAZIONI_IO.DATA_ESTRAZIONE, dbo.zDIMENSIONI.UM, dbo.zDIMENSIONI_ESTRAZIONI_IO.ID_ESTRAZIONE_IO, 
                         dbo.zDIMENSIONI_ESTRAZIONI_T.BLOCCATO, YEAR(dbo.zDIMENSIONI_ESTRAZIONI_T.DATA_INIZIO) AS ANNO
FROM            dbo.zDIMENSIONI_ESTRAZIONI_IO INNER JOIN
                         dbo.zDIMENSIONI AS zDIMENSIONI_1 ON dbo.zDIMENSIONI_ESTRAZIONI_IO.ID_DIM_PRIORITA = zDIMENSIONI_1.ID INNER JOIN
                         dbo.zDIMENSIONI ON dbo.zDIMENSIONI_ESTRAZIONI_IO.ID_DIM_INDICATORE = dbo.zDIMENSIONI.ID INNER JOIN
                         dbo.zDIMENSIONI_ESTRAZIONI_T ON dbo.zDIMENSIONI_ESTRAZIONI_IO.ID_ESTRAZIONE = dbo.zDIMENSIONI_ESTRAZIONI_T.ID_ESTRAZIONE

