

CREATE VIEW [dbo].[vzPROGRAMMAZIONE_FONTI]
AS
SELECT        P.ID, P.ID_PROGRAMMAZIONE, P.ID_FONTE, P.PERCENTUALE, P.DATA_INIZIO, P.OPERATORE_INIZIO, P.DATA_FINE, P.OPERATORE_FINE, P.ATTIVA, 
                         F.PERCENTUALE AS PERCENTUALE_FONTE, F.DESCRIZIONE, U1.NOMINATIVO AS NOMINATIVO_INIZIO, U2.NOMINATIVO AS NOMINATIVO_FINE
FROM            dbo.zPROGRAMMAZIONE_FONTI AS P INNER JOIN
                         dbo.FONTI_FINANZIARIE AS F ON P.ID_FONTE = F.ID_FONTE LEFT OUTER JOIN
                         dbo.vUTENTI AS U1 ON P.OPERATORE_INIZIO = U1.ID_UTENTE LEFT OUTER JOIN
                         dbo.vUTENTI AS U2 ON P.OPERATORE_FINE = U2.ID_UTENTE


