CREATE VIEW [dbo].[vzPROG_FA]
AS
SELECT     dbo.zPROG_FA.ID, dbo.zPROG_FA.ID_PROGRAMMAZIONE, dbo.zPROG_FA.COD_FA, dbo.zPROG_FA.TIPO_CONTRIBUTO, dbo.zPROG_FA.DOT_FINANZIARIA, 
                      dbo.zFOCUS_AREA.COD_PSR, dbo.zFOCUS_AREA.DESCRIZIONE AS FA_DESCRIZIONE, dbo.zFOCUS_AREA.DOT_FINANZIARIA AS FA_DOT_FINANZIARIA, 
                      dbo.zFOCUS_AREA.TRASVERSALE, dbo.vzPROGRAMMAZIONE.COD_TIPO AS PROG_COD_TIPO, dbo.vzPROGRAMMAZIONE.CODICE AS PROG_CODICE, 
                      dbo.vzPROGRAMMAZIONE.DESCRIZIONE AS PROG_DESCRIZIONE, dbo.vzPROGRAMMAZIONE.ID_PADRE, dbo.vzPROGRAMMAZIONE.TIPO AS PROG_TIPO, 
                      dbo.vzPROGRAMMAZIONE.LIVELLO, dbo.vzPROGRAMMAZIONE.ATTIVAZIONE_BANDI, dbo.vzPROGRAMMAZIONE.ATTIVAZIONE_FA, 
                      dbo.vzPROGRAMMAZIONE.ATTIVAZIONE_OB_MISURA, dbo.zPROG_FA.ATTIVO, dbo.zPROG_FA.DATA, dbo.zPROG_FA.OPERATORE, dbo.vUTENTI.CF_UTENTE, 
                      dbo.vUTENTI.NOMINATIVO, dbo.vUTENTI.COD_ENTE, dbo.vzPROGRAMMAZIONE.ATTIVAZIONE_INVESTIMENTI, dbo.vzPROGRAMMAZIONE.ATTIVAZIONE_FF
FROM         dbo.zPROG_FA INNER JOIN
                      dbo.zFOCUS_AREA ON dbo.zPROG_FA.COD_FA = dbo.zFOCUS_AREA.CODICE INNER JOIN
                      dbo.vzPROGRAMMAZIONE ON dbo.zPROG_FA.ID_PROGRAMMAZIONE = dbo.vzPROGRAMMAZIONE.ID INNER JOIN
                      dbo.vUTENTI ON dbo.zPROG_FA.OPERATORE = dbo.vUTENTI.ID_UTENTE
