CREATE VIEW [dbo].[vzTP]
AS
SELECT     dbo.zTP.ID, dbo.zTP.ID_PROGRAMMAZIONE, dbo.zTP.CODICE, dbo.zTP.DESCRIZIONE, 
			--dbo.vzPROGRAMMAZIONE.CODICE AS CODICE_PROGRAMMAZIONE, 
            --dbo.vzPROGRAMMAZIONE.DESCRIZIONE AS PROGRAMMAZIONE
			SUBSTRING(dbo.vzPROGRAMMAZIONE.TIPO+' '+dbo.vzPROGRAMMAZIONE.CODICE+' - '+
					  dbo.vzPROGRAMMAZIONE.DESCRIZIONE,0,140) AS PROGRAMMAZIONE,
			dbo.zPSR.DESCRIZIONE+' '+CAST(ANNO_DA AS CHAR(4))+' - '+CAST(ANNO_A AS CHAR(4)) AS PSR,
			zPSR.ANNO_DA, zPSR.ANNO_A
			
FROM        dbo.zTP 
			INNER JOIN dbo.vzPROGRAMMAZIONE 
				ON dbo.zTP.ID_PROGRAMMAZIONE = dbo.vzPROGRAMMAZIONE.ID
			INNER JOIN zPSR 
				ON dbo.vzPROGRAMMAZIONE.COD_PSR=dbo.zPSR.CODICE 
			
--ORDER BY ANNO_DA+ANNO_A DESC,COD_PSR+CAST(LIVELLO AS VARCHAR(5))+dbo.vzPROGRAMMAZIONE.CODICE
