CREATE TABLE [dbo].[ACCORPAMENTO_INVESTIMENTI] (
	[ID_ACCORPAMENTO_INVESTIMENTI]		[INT]			IDENTITY(1,1) NOT NULL,
	[DATA_CREAZIONE]				[DATETIME]		CONSTRAINT [DF_ACCORPAMENTO_INVESTIMENTI_DATA_CREAZIONE] DEFAULT (getdate()) NULL,
	[CF_CREAZIONE]					[VARCHAR](50)	NULL,
	[DATA_MODIFICA]					[DATETIME]		CONSTRAINT [DF_ACCORPAMENTO_INVESTIMENTI_DATA_MODIFICA] DEFAULT (getdate()) NULL,
	[CF_MODIFICA]					[VARCHAR](50)	NULL,
	[ID_DOMANDA_PAGAMENTO]			[INT]			NULL,
	[ID_INVESTIMENTO_X]				[INT]			NOT NULL,
	[ID_INVESTIMENTO_Y]				[INT]			NOT NULL,
	[ISTANZA_PIANO_INVESTIMENTI]	[XML]			NOT NULL,
	CONSTRAINT [PK_ACCORPAMENTO_INVESTIMENTI] PRIMARY KEY CLUSTERED ([ID_ACCORPAMENTO_INVESTIMENTI] ASC),
	CONSTRAINT [FK_ACCORPAMENTO_INVESTIMENTI_DOMANDA_DI_PAGAMENTO] FOREIGN KEY ([ID_DOMANDA_PAGAMENTO]) REFERENCES [dbo].[DOMANDA_DI_PAGAMENTO] ([ID_DOMANDA_PAGAMENTO])
);