CREATE TABLE [dbo].[AGGREGAZIONE] (
    [ID]                    INT            IDENTITY (1, 1) NOT NULL,
    [DENOMINAZIONE]         VARCHAR (2000) NOT NULL,
    [COD_TIPO_AGGREGAZIONE] VARCHAR (10)   NOT NULL,
    [DATA_INIZIO]           DATETIME       NOT NULL,
    [OPERATORE_INIZIO]      INT            NOT NULL,
    [ATTIVO]                BIT            NOT NULL,
    [DATA_FINE]             DATETIME       NULL,
    [OPERATORE_FINE]        INT            NULL,
    CONSTRAINT [PK_AGGREGAZIONE] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_AGGREGAZIONE_TIPO_AGGREGAZIONE] FOREIGN KEY ([COD_TIPO_AGGREGAZIONE]) REFERENCES [dbo].[TIPO_AGGREGAZIONE] ([CODICE])
);

