CREATE TABLE [dbo].[ARCHIVIO_FILE] (
    [ID]            INT             IDENTITY (1, 1) NOT NULL,
    [TIPO]          VARCHAR (100)   NOT NULL,
    [NOME_FILE]     VARCHAR (255)   NOT NULL,
    [NOME_COMPLETO] VARCHAR (510)   NOT NULL,
    [CONTENUTO]     VARBINARY (MAX) NOT NULL,
    [DIMENSIONE]    INT             NOT NULL,
    [HASH_CODE]     VARCHAR (100)   NULL,
    CONSTRAINT [PK_ARCHIVIO_FILE] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 80)
);

