CREATE TABLE [dbo].[BANDO_CODICI_ATTIVAZIONE] (
    [ID_BANDO]                  INT          NOT NULL,
    [COD_PROCEDURA_ATTIVAZIONE] VARCHAR (50) NULL,
    [DATA_INSERIMENTO]          DATETIME     NULL,
    [DATA_AGGIORNAMENTO]        DATETIME     NULL,
    [DATA_ASSEGNAZIONE]         DATETIME     NULL
);

