CREATE TABLE [dbo].[BANDO_COMUNI_LOCALIZZAZIONI] (
    [ID_BANDO]              INT      NOT NULL,
    [ID_COMUNE]             INT      NOT NULL,
    [EFFETTO_SU_CONTRIBUTO] SMALLINT CONSTRAINT [DF_BANDO_COMUNI_LOCALIZZAZIONI_MaggiorazioneContributo] DEFAULT ((0)) NOT NULL,
    [IS_ATTIVO]             BIT      CONSTRAINT [DF_BANDO_COMUNI_LOCALIZZAZIONI_ATTIVO] DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PK_BANDO_COMUNI_LOCALIZZAZIONI] PRIMARY KEY CLUSTERED ([ID_BANDO] ASC, [ID_COMUNE] ASC) WITH (FILLFACTOR = 80)
);

