CREATE TABLE [dbo].[BANDO_X_SETTORE_PRODUTTIVO] (
    [ID_BANDO_X_SETTORE_PRODUTTIVO] INT IDENTITY (1, 1) NOT NULL,
    [ID_BANDO]                      INT NOT NULL,
    [ID_SETTORE_PRODUTTIVO]         INT NULL,
    [ID_PRIORITA_SETTORIALE]        INT NULL,
    CONSTRAINT [PK_BANDO_X_SETTORE_PRODUTTIVO] PRIMARY KEY CLUSTERED ([ID_BANDO_X_SETTORE_PRODUTTIVO] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_BANDO_X_SETTORE_PRODUTTIVO_BANDO] FOREIGN KEY ([ID_BANDO]) REFERENCES [dbo].[BANDO] ([ID_BANDO]),
    CONSTRAINT [FK_BANDO_X_SETTORE_PRODUTTIVO_PRIORITA_SETTORIALI] FOREIGN KEY ([ID_PRIORITA_SETTORIALE]) REFERENCES [dbo].[PRIORITA_SETTORIALI] ([ID_PRIORITA_SETTORIALE]),
    CONSTRAINT [FK_BANDO_X_SETTORE_PRODUTTIVO_SETTORI_PRODUTTIVI] FOREIGN KEY ([ID_SETTORE_PRODUTTIVO]) REFERENCES [dbo].[SETTORI_PRODUTTIVI] ([ID_SETTORE_PRODUTTIVO])
);

