CREATE TABLE [dbo].[BANDO_ATECO2007] (
    [ID_BANDO]     INT      NOT NULL,
    [ID_ATECO2007] CHAR (9) NOT NULL,
    CONSTRAINT [PK_BANDO_ATECO2007] PRIMARY KEY CLUSTERED ([ID_BANDO] ASC, [ID_ATECO2007] ASC),
    CONSTRAINT [FK_BANDO_ATECO2007_TIPO_ATECO2007] FOREIGN KEY ([ID_ATECO2007]) REFERENCES [dbo].[TIPO_ATECO2007] ([COD_TIPO_ATECO2007]) ON UPDATE CASCADE
);

