CREATE TABLE [dbo].[BANDO_TIPO_VARIANTI] (
    [ID_BANDO]       INT      NOT NULL,
    [COD_TIPO]       CHAR (2) NOT NULL,
    [NUMERO_MASSIMO] INT      NULL,
    CONSTRAINT [PK_BANDO_TIPO_VARIANTI] PRIMARY KEY CLUSTERED ([ID_BANDO] ASC, [COD_TIPO] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_BANDO_TIPO_VARIANTI_BANDO] FOREIGN KEY ([ID_BANDO]) REFERENCES [dbo].[BANDO] ([ID_BANDO]),
    CONSTRAINT [FK_BANDO_TIPO_VARIANTI_TIPO_VARIANTE] FOREIGN KEY ([COD_TIPO]) REFERENCES [dbo].[TIPO_VARIANTE] ([COD_TIPO])
);

