CREATE TABLE [dbo].[BANDO_INTEGRAZIONI] (
    [ID]                INT             IDENTITY (1, 1) NOT NULL,
    [ID_BANDO]          INT             NOT NULL,
    [DATA]              DATETIME        NOT NULL,
    [OPERATORE]         INT             NOT NULL,
    [DATA_SCADENZA]     DATETIME        NOT NULL,
    [IMPORTO]           DECIMAL (18, 2) NOT NULL,
    [IMPORTO_DI_MISURA] DECIMAL (18, 2) CONSTRAINT [DF_BANDO_INTEGRAZIONI_IMPORTO_DI_MISURA] DEFAULT ((0)) NOT NULL,
    [QUOTA_RISERVA]     DECIMAL (10, 2) CONSTRAINT [DF_BANDO_INTEGRAZIONI_QUOTA_RISERVA] DEFAULT ((0)) NOT NULL,
    [ID_ATTO]           INT             NULL,
    CONSTRAINT [PK_BANDO_INTEGRAZIONI] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_BANDO_INTEGRAZIONI_BANDO] FOREIGN KEY ([ID_BANDO]) REFERENCES [dbo].[BANDO] ([ID_BANDO])
);

