CREATE TABLE [dbo].[BANDO_STORICO] (
    [ID]        INT           IDENTITY (1, 1) NOT NULL,
    [ID_BANDO]  INT           NOT NULL,
    [COD_STATO] CHAR (1)      NOT NULL,
    [DATA]      DATETIME      NOT NULL,
    [OPERATORE] INT           NOT NULL,
    [SEGNATURA] VARCHAR (100) NULL,
    [ID_ATTO]   INT           NULL,
    CONSTRAINT [PK_BANDO_STORICO] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_BANDO_STORICO_BANDO] FOREIGN KEY ([ID_BANDO]) REFERENCES [dbo].[BANDO] ([ID_BANDO]),
    CONSTRAINT [FK_BANDO_STORICO_BANDO_TIPO_STATO] FOREIGN KEY ([COD_STATO]) REFERENCES [dbo].[BANDO_TIPO_STATO] ([CODICE])
);

