CREATE TABLE [dbo].[BANDO_CONFIG_TIPO_PARAMETRI] (
    [ID]          INT           IDENTITY (1, 1) NOT NULL,
    [COD_TIPO]    VARCHAR (30)  NOT NULL,
    [CODICE]      VARCHAR (30)  NOT NULL,
    [DESCRIZIONE] VARCHAR (255) NOT NULL,
    [ORDINE]      INT           NOT NULL,
    CONSTRAINT [PK_BANDO_CONFIG_TIPO_PARAMETRI] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_BANDO_CONFIG_TIPO_PARAMETRI_BANDO_CONFIG_TIPO] FOREIGN KEY ([COD_TIPO]) REFERENCES [dbo].[BANDO_CONFIG_TIPO] ([CODICE])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_BANDO_CONFIG_TIPO_PARAMETRI]
    ON [dbo].[BANDO_CONFIG_TIPO_PARAMETRI]([COD_TIPO] ASC, [CODICE] ASC);

