CREATE TABLE [dbo].[CAA_STORICO_SPORTELLO] (
    [ID]                  INT           IDENTITY (1, 1) NOT NULL,
    [CODICE_SPORTELLO]    CHAR (9)      NOT NULL,
    [DENOMINAZIONE]       VARCHAR (60)  NOT NULL,
    [UFFICIO_PROVINCIALE] BIT           CONSTRAINT [DF_CAA_STORICO_SPORTELLO_UFFICIO_PROVINCIALE] DEFAULT ((0)) NOT NULL,
    [UFFICIO_REGIONALE]   BIT           CONSTRAINT [DF_CAA_STORICO_SPORTELLO_UFFICIO_REGIONALE] DEFAULT ((0)) NOT NULL,
    [INDIRIZZO]           VARCHAR (150) NOT NULL,
    [ID_COMUNE]           INT           NULL,
    [TELEFONO]            VARCHAR (15)  NULL,
    [FAX]                 VARCHAR (15)  NULL,
    [EMAIL]               VARCHAR (50)  NULL,
    [COD_STATO]           CHAR (1)      NOT NULL,
    [DATA]                DATETIME      NOT NULL,
    [OPERATORE]           INT           NOT NULL,
    CONSTRAINT [PK_CAA_STORICO_SPORTELLO] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_CAA_STORICO_SPORTELLO_CAA_SPORTELLO] FOREIGN KEY ([CODICE_SPORTELLO]) REFERENCES [dbo].[CAA_SPORTELLO] ([CODICE])
);

