CREATE TABLE [dbo].[CAA_SPORTELLO] (
    [CODICE]            CHAR (9)     NOT NULL,
    [CODICE_CAA]        CHAR (3)     NOT NULL,
    [CODICE_PROVINCIA]  CHAR (3)     NOT NULL,
    [CODICE_UFFICIO]    CHAR (3)     NOT NULL,
    [COD_ENTE]          VARCHAR (10) NULL,
    [ID_STORICO_ULTIMO] INT          NULL,
    CONSTRAINT [PK_CAA_SPORTELLO] PRIMARY KEY CLUSTERED ([CODICE] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_CAA_SPORTELLO_ENTE] FOREIGN KEY ([COD_ENTE]) REFERENCES [dbo].[ENTE] ([COD_ENTE])
);

