CREATE TABLE [dbo].[CATALOGO_DICHIARAZIONI] (
    [ID_DICHIARAZIONE] INT            IDENTITY (1, 1) NOT NULL,
    [DESCRIZIONE]      VARCHAR (1000) NULL,
    [MISURA]           VARCHAR (10)   NULL,
    CONSTRAINT [PK_CATALOGO_DICHIARAZIONI] PRIMARY KEY CLUSTERED ([ID_DICHIARAZIONE] ASC) WITH (FILLFACTOR = 80)
);

