CREATE TABLE [dbo].[CHECK_LIST] (
    [ID_CHECK_LIST] INT                 IDENTITY (1, 1) NOT NULL,
    [DESCRIZIONE]   [dbo].[DESCRIZIONE] NOT NULL,
    [FLAG_TEMPLATE] BIT                 NOT NULL,
    [DATA_MODIFICA] DATETIME            NULL,
    [OPERATORE]     CHAR (16)           NULL,
    CONSTRAINT [PK_CHECK_LIST] PRIMARY KEY CLUSTERED ([ID_CHECK_LIST] ASC) WITH (FILLFACTOR = 80)
);

