CREATE TABLE [dbo].[CODICI_VARIAZIONE] (
    [COD_VARIAZIONE] CHAR (1)     NOT NULL,
    [DESCRIZIONE]    VARCHAR (50) NULL,
    CONSTRAINT [PK_CODICI_VARIAZIONE] PRIMARY KEY CLUSTERED ([COD_VARIAZIONE] ASC) WITH (FILLFACTOR = 100)
);

