CREATE TABLE [dbo].[COMUNI] (
    [ID_COMUNE]            INT           IDENTITY (1, 1) NOT NULL,
    [COD_BELFIORE]         CHAR (4)      NOT NULL,
    [DENOMINAZIONE]        VARCHAR (255) NOT NULL,
    [COD_PROVINCIA]        CHAR (3)      NOT NULL,
    [SIGLA]                CHAR (2)      NOT NULL,
    [CAP]                  VARCHAR (5)   NULL,
    [ISTAT]                CHAR (3)      NULL,
    [TIPO_AREA]            VARCHAR (2)   NULL,
    [COD_RUBRICA_PALEO]    VARCHAR (10)  NULL,
    [ATTIVO]               BIT           CONSTRAINT [DF_COMUNI_ATTIVO] DEFAULT ((1)) NOT NULL,
    [DATA_INIZIO_VALIDITA] DATETIME      CONSTRAINT [DF_COMUNI_DATA_INIZIO_VALIDITA] DEFAULT (getdate()) NOT NULL,
    [DATA_FINE_VALIDITA]   DATETIME      NULL,
    [ID_OPERATORE_INIZIO]  INT           CONSTRAINT [DF_COMUNI_ID_OPERATORE_INIZIO] DEFAULT ((1)) NULL,
    [ID_OPERATORE_FINE]    INT           NULL,
    CONSTRAINT [PK_COMUNI] PRIMARY KEY CLUSTERED ([ID_COMUNE] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_COMUNI_PROVINCE] FOREIGN KEY ([COD_PROVINCIA]) REFERENCES [dbo].[PROVINCE] ([CODICE])
);


GO
CREATE NONCLUSTERED INDEX [IX_COMUNI]
    ON [dbo].[COMUNI]([COD_PROVINCIA] ASC, [ISTAT] ASC) WITH (FILLFACTOR = 80);

