CREATE TABLE [dbo].[CONTROLLI_PARAMETRI_X_LOTTO] (
    [ID_LOTTO]     INT NOT NULL,
    [ID_PARAMETRO] INT NOT NULL,
    [PESO_REALE]   INT NULL,
    CONSTRAINT [PK_CONTROLLI_PARAMETRI_X_LOTTO] PRIMARY KEY CLUSTERED ([ID_LOTTO] ASC, [ID_PARAMETRO] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_CONTROLLI_PARAMETRI_X_LOTTO_CONTROLLI_LOCO_LOTTO] FOREIGN KEY ([ID_LOTTO]) REFERENCES [dbo].[CONTROLLI_LOCO_LOTTO] ([ID_LOTTO]),
    CONSTRAINT [FK_CONTROLLI_PARAMETRI_X_LOTTO_CONTROLLI_PARAMETRI_DI_RISCHIO] FOREIGN KEY ([ID_PARAMETRO]) REFERENCES [dbo].[CONTROLLI_PARAMETRI_DI_RISCHIO] ([ID_PARAMETRO])
);

