CREATE TABLE [dbo].[CONTROLLI_PARAMETRI_DI_RISCHIO] (
    [ID_PARAMETRO] INT            IDENTITY (1, 1) NOT NULL,
    [DESCRIZIONE]  VARCHAR (500)  NOT NULL,
    [MANUALE]      BIT            CONSTRAINT [DF_CONTROLLI_PARAMETRI_DI_RISCHIO_MANUALE] DEFAULT ((0)) NOT NULL,
    [QUERY_SQL]    VARCHAR (3000) NULL,
    [PESO]         INT            NULL,
    CONSTRAINT [PK_CONTROLLI_PARAMETRI_DI_RISCHIO] PRIMARY KEY CLUSTERED ([ID_PARAMETRO] ASC) WITH (FILLFACTOR = 80)
);

