CREATE TABLE [dbo].[CORRETTIVA_RENDICONTAZIONE_SPOSTAMENTI] (
    [ID]                 INT             IDENTITY (1, 1) NOT NULL,
    [ID_CORRETTIVA]      INT             NOT NULL,
    [ID_INVESTIMENTO_DA] INT             NOT NULL,
    [ID_INVESTIMENTO_A]  INT             NOT NULL,
    [IMPORTO_SPOSTATO]   DECIMAL (18, 2) CONSTRAINT [DF_CORRETTIVA_RENDICONTAZIONE_SPOSTAMENTI_IMPORTO_SPOSTATO] DEFAULT ((0)) NOT NULL,
    [CONCLUSO]           BIT             CONSTRAINT [DF_CORRETTIVA_RENDICONTAZIONE_SPOSTAMENTI_CONCLUSO] DEFAULT ((0)) NOT NULL,
    [ANNULLATO]          BIT             CONSTRAINT [DF_CORRETTIVA_RENDICONTAZIONE_SPOSTAMENTI_ANNULLATO] DEFAULT ((0)) NOT NULL,
    [ID_UTENTE]          INT             NOT NULL,
    [DATA]               DATETIME        NOT NULL,
    [DESCRIZIONE]        VARCHAR (255)   NOT NULL,
    [ID_JSON_LOG]        INT             NULL,
    CONSTRAINT [PK_CORRETTIVA_RENDICONTAZIONE_SPOSTAMENTI] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_CORRETTIVA_RENDICONTAZIONE_SPOSTAMENTI_CORRETTIVA_RENDICONTAZIONE] FOREIGN KEY ([ID_CORRETTIVA]) REFERENCES [dbo].[CORRETTIVA_RENDICONTAZIONE] ([ID]),
    CONSTRAINT [FK_CORRETTIVA_RENDICONTAZIONE_SPOSTAMENTI_NOTE] FOREIGN KEY ([ID_JSON_LOG]) REFERENCES [dbo].[NOTE] ([ID]),
    CONSTRAINT [FK_CORRETTIVA_RENDICONTAZIONE_SPOSTAMENTI_PIANO_INVESTIMENTI] FOREIGN KEY ([ID_INVESTIMENTO_DA]) REFERENCES [dbo].[PIANO_INVESTIMENTI] ([ID_INVESTIMENTO]),
    CONSTRAINT [FK_CORRETTIVA_RENDICONTAZIONE_SPOSTAMENTI_PIANO_INVESTIMENTI1] FOREIGN KEY ([ID_INVESTIMENTO_A]) REFERENCES [dbo].[PIANO_INVESTIMENTI] ([ID_INVESTIMENTO])
);

