CREATE TABLE [dbo].[CORRETTIVA_RENDICONTAZIONE] (
    [ID]                   INT      IDENTITY (1, 1) NOT NULL,
    [ID_DOMANDA_PAGAMENTO] INT      NOT NULL,
    [CONCLUSA]             BIT      CONSTRAINT [DF_CORRETTIVA_RENDICONTAZIONE_CONCLUSA] DEFAULT ((0)) NOT NULL,
    [ANNULLATA]            BIT      CONSTRAINT [DF_CORRETTIVA_RENDICONTAZIONE_ANNULLATA] DEFAULT ((0)) NOT NULL,
    [ID_UTENTE]            INT      NOT NULL,
    [DATA]                 DATETIME NOT NULL,
    [ID_NOTE]              INT      NOT NULL,
    CONSTRAINT [PK_CORRETTIVA_RENDICONTAZIONE] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_CORRETTIVA_RENDICONTAZIONE_DOMANDA_DI_PAGAMENTO] FOREIGN KEY ([ID_DOMANDA_PAGAMENTO]) REFERENCES [dbo].[DOMANDA_DI_PAGAMENTO] ([ID_DOMANDA_PAGAMENTO]),
    CONSTRAINT [FK_CORRETTIVA_RENDICONTAZIONE_NOTE] FOREIGN KEY ([ID_NOTE]) REFERENCES [dbo].[NOTE] ([ID])
);

