CREATE TABLE [dbo].[DATI_MONITORAGGIO_FESR] (
    [ID_DATI_MONIT]          INT      IDENTITY (1, 1) NOT NULL,
    [ID_PROGETTO]            INT      NOT NULL,
    [CUP_CATEGORIA]          CHAR (7) NOT NULL,
    [CUP_CATEGORIA_SOGGETTO] CHAR (6) NOT NULL,
    [TEMA_PRIORITARIO]       CHAR (2) NOT NULL,
    [ID_ATECO]               CHAR (9) NOT NULL,
    [ATTIVITA_ECON]          CHAR (2) NOT NULL,
    [CPT_SETTORE]            CHAR (2) NOT NULL,
    [CUP_DIMENSIONE_TERR]    CHAR (2) NOT NULL,
    [CUP_NATURA]             CHAR (2) NULL,
    [CUP_CATEGORIA_TIPOOPER] CHAR (4) NOT NULL,
    CONSTRAINT [PK_DATI_MONITORAGGIO_FESR] PRIMARY KEY NONCLUSTERED ([ID_DATI_MONIT] ASC),
    CONSTRAINT [FK_DATI_MONITORAGGIO_FESR_TIPO_ATECO2007] FOREIGN KEY ([ID_ATECO]) REFERENCES [dbo].[TIPO_ATECO2007] ([COD_TIPO_ATECO2007]) ON UPDATE CASCADE,
    CONSTRAINT [FK_DATI_MONITORAGGIO_FESR_TIPO_ATTIVITA_ECON] FOREIGN KEY ([ATTIVITA_ECON]) REFERENCES [dbo].[TIPO_ATTIVITA_ECON] ([COD_ATTIVITA_ECON]) ON UPDATE CASCADE,
    CONSTRAINT [FK_DATI_MONITORAGGIO_FESR_TIPO_CPT_SETTORE] FOREIGN KEY ([CPT_SETTORE]) REFERENCES [dbo].[TIPO_CPT_SETTORE] ([COD_CPT_SETTORE]) ON UPDATE CASCADE,
    CONSTRAINT [FK_DATI_MONITORAGGIO_FESR_TIPO_CUP_CATEGORIE] FOREIGN KEY ([CUP_CATEGORIA]) REFERENCES [dbo].[TIPO_CUP_CATEGORIE] ([COD_CUP_CATEGORIE]) ON UPDATE CASCADE,
    CONSTRAINT [FK_DATI_MONITORAGGIO_FESR_TIPO_CUP_CATEGORIE_SOGGETTI] FOREIGN KEY ([CUP_CATEGORIA_SOGGETTO]) REFERENCES [dbo].[TIPO_CUP_CATEGORIE_SOGGETTI] ([COD_CUP_CATEGORIE_SOGGETTI]) ON UPDATE CASCADE,
    CONSTRAINT [FK_DATI_MONITORAGGIO_FESR_TIPO_CUP_CATEGORIE_TIPIOPERAZIONI] FOREIGN KEY ([CUP_CATEGORIA_TIPOOPER]) REFERENCES [dbo].[TIPO_CUP_CATEGORIE_TIPIOPERAZIONI] ([COD_CUP_CATEGORIE_TIPIOPERAZIONI]) ON UPDATE CASCADE,
    CONSTRAINT [FK_DATI_MONITORAGGIO_FESR_TIPO_CUP_DIMENSIONE_TERR] FOREIGN KEY ([CUP_DIMENSIONE_TERR]) REFERENCES [dbo].[TIPO_CUP_DIMENSIONE_TERR] ([COD_CUP_DIMENSIONE_TERR]) ON UPDATE CASCADE,
    CONSTRAINT [FK_DATI_MONITORAGGIO_FESR_TIPO_TEMA_PRIORITARIO] FOREIGN KEY ([TEMA_PRIORITARIO]) REFERENCES [dbo].[TIPO_TEMA_PRIORITARIO] ([COD_TEMA_PRIORITARIO]) ON UPDATE CASCADE
);


GO
CREATE UNIQUE CLUSTERED INDEX [IX_DATI_MONITORAGGIO_FESR_PRJ]
    ON [dbo].[DATI_MONITORAGGIO_FESR]([ID_PROGETTO] ASC);

