CREATE TABLE [dbo].[DETTAGLIO_INVESTIMENTI] (
    [ID_DETTAGLIO_INVESTIMENTO] INT             IDENTITY (1, 1) NOT NULL,
    [ID_CODIFICA_INVESTIMENTO]  INT             NOT NULL,
    [COD_DETTAGLIO]             CHAR (2)        NOT NULL,
    [DESCRIZIONE]               VARCHAR (255)   NULL,
    [MOBILE]                    BIT             CONSTRAINT [DF_DETTAGLIO_INVESTIMENTI_MOBILE] DEFAULT ((0)) NOT NULL,
    [QUOTA_SPESE_GENERALI]      DECIMAL (10, 2) NULL,
    [RICHIEDI_PARTICELLA]       BIT             NULL,
    [ID_UDM]                    INT             NULL,
    CONSTRAINT [PK_DETTAGLIO_INVESTIMENTI] PRIMARY KEY CLUSTERED ([ID_DETTAGLIO_INVESTIMENTO] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_DETTAGLIO_INVESTIMENTI_CODIFICA_INVESTIMENTO] FOREIGN KEY ([ID_CODIFICA_INVESTIMENTO]) REFERENCES [dbo].[CODIFICA_INVESTIMENTO] ([ID_CODIFICA_INVESTIMENTO]),
    CONSTRAINT [FK_DETTAGLIO_INVESTIMENTI_UNITA_DI_MISURA] FOREIGN KEY ([ID_UDM]) REFERENCES [dbo].[UNITA_DI_MISURA] ([ID_UNITA_MISURA])
);

