CREATE TABLE [dbo].[DICHIARAZIONI_X_DOMANDA] (
    [ID_DICHIARAZIONE] INT NOT NULL,
    [ID_DOMANDA]       INT NOT NULL,
    [ORDINE]           INT NULL,
    [OBBLIGATORIO]     BIT NULL,
    CONSTRAINT [PK_DICHIARAZIONI_X_DOMANDA] PRIMARY KEY CLUSTERED ([ID_DICHIARAZIONE] ASC, [ID_DOMANDA] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_DICHIARAZIONI_X_DOMANDA_CATALOGO_DICHIARAZIONI] FOREIGN KEY ([ID_DICHIARAZIONE]) REFERENCES [dbo].[CATALOGO_DICHIARAZIONI] ([ID_DICHIARAZIONE]),
    CONSTRAINT [FK_DICHIARAZIONI_X_DOMANDA_MODELLO_DOMANDA] FOREIGN KEY ([ID_DOMANDA]) REFERENCES [dbo].[MODELLO_DOMANDA] ([ID_DOMANDA])
);

