CREATE TABLE [dbo].[DIMENSIONE_IMPRESA] (
    [ID_DIMENSIONE] INT          IDENTITY (1, 1) NOT NULL,
    [DESCRIZIONE]   VARCHAR (50) NULL,
    CONSTRAINT [PK_DIMENSIONE_IMPRESA] PRIMARY KEY CLUSTERED ([ID_DIMENSIONE] ASC) WITH (FILLFACTOR = 100)
);

