CREATE TABLE [dbo].[DOMANDA_PAGAMENTO_ALLEGATI] (
    [ID_ALLEGATO]          INT           IDENTITY (1, 1) NOT NULL,
    [ID_DOMANDA_PAGAMENTO] INT           NOT NULL,
    [DESCRIZIONE]          VARCHAR (255) NULL,
    [COD_TIPO_DOCUMENTO]   VARCHAR (10)  NOT NULL,
    [ID_FILE]              INT           NULL,
    [COD_ENTE_EMETTITORE]  VARCHAR (10)  NULL,
    [ID_COMUNE]            INT           NULL,
    [NUMERO]               VARCHAR (20)  NULL,
    [DATA]                 DATETIME      NULL,
    [COD_ESITO]            CHAR (2)      NULL,
    [NOTE_ISTRUTTORE]      NTEXT         NULL,
    [IN_INTEGRAZIONE]      BIT           CONSTRAINT [DF_DOMANDA_PAGAMENTO_ALLEGATI_IN_INTEGRAZIONE] DEFAULT ((0)) NULL,
	[DATA_INSERIMENTO]		DATETIME	NULL,
	[CF_INSERIMENTO]		VARCHAR(50) NULL,
	[DATA_MODIFICA]			DATETIME	CONSTRAINT [DF_DOMANDA_PAGAMENTO_ALLEGATI_DATA_MODIFICA] DEFAULT ((GETDATE())) NULL,
	[CF_MODIFICA]			VARCHAR(50) NULL,
    CONSTRAINT [PK_DOMANDA_PAGAMENTO_ALLEGATI] PRIMARY KEY CLUSTERED ([ID_ALLEGATO] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_DOMANDA_PAGAMENTO_ALLEGATI_DOMANDA_DI_PAGAMENTO] FOREIGN KEY ([ID_DOMANDA_PAGAMENTO]) REFERENCES [dbo].[DOMANDA_DI_PAGAMENTO] ([ID_DOMANDA_PAGAMENTO]),
    CONSTRAINT [FK_DOMANDA_PAGAMENTO_ALLEGATI_ESITI_STEP] FOREIGN KEY ([COD_ESITO]) REFERENCES [dbo].[ESITI_STEP] ([COD_ESITO])
);

