CREATE TABLE [dbo].[FASCICOLO_AZIENDALE] (
    [ID_FASCICOLO]               INT             IDENTITY (1, 1) NOT NULL,
    [ID_IMPRESA]                 INT             NOT NULL,
    [DATA_DOWNLOAD]              DATETIME        NOT NULL,
    [DATA_CREAZIONE]             DATETIME        NOT NULL,
    [OPERATORE_CREAZIONE]        CHAR (16)       NULL,
    [DATA_STORICIZZAZIONE]       DATETIME        NULL,
    [DATA_APERTURA_FASCICOLO]    DATETIME        NOT NULL,
    [DATA_CHIUSURA_FASCICOLO]    DATETIME        NULL,
    [DATA_ELABORAZIONE]          DATETIME        NOT NULL,
    [DATA_VALIDAZIONE_FASCICOLO] DATETIME        NOT NULL,
    [ORGANISMO_PAGATORE]         VARCHAR (4)     NULL,
    [OTE]                        CHAR (4)        NULL,
    [UDE]                        INT             NULL,
    [RLS]                        DECIMAL (18, 2) NULL,
    [UBA]                        DECIMAL (18, 2) NULL,
    [DATA_SCHEDA_VALIDAZIONE]    DATETIME        NULL,
    [BARCODE]                    CHAR (11)       NULL,
    [COD_TIPO_DETENTORE]         CHAR (3)        NULL,
    [COD_DETENTORE]              VARCHAR (20)    NULL,
    [STATO_TERRITORIO]           CHAR (2)        NULL,
    [STATO_VETERINARIA]          CHAR (2)        NULL,
    [STATO_FABBRICATI]           CHAR (2)        NULL,
    [STATO_MANODOPERA]           CHAR (2)        NULL,
    [STATO_MACCHINARI]           CHAR (2)        NULL,
    CONSTRAINT [PK_FASCICOLO_AZIENDALE] PRIMARY KEY CLUSTERED ([ID_FASCICOLO] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_FASCICOLO_AZIENDALE_IMPRESA] FOREIGN KEY ([ID_IMPRESA]) REFERENCES [dbo].[IMPRESA] ([ID_IMPRESA]),
    CONSTRAINT [FK_FASCICOLO_AZIENDALE_ORGANISMO_PAGATORE] FOREIGN KEY ([ORGANISMO_PAGATORE]) REFERENCES [dbo].[ORGANISMO_PAGATORE] ([CODICE_ESTERNO])
);


GO
CREATE NONCLUSTERED INDEX [IX_FASCICOLO_AZIENDALE]
    ON [dbo].[FASCICOLO_AZIENDALE]([ID_IMPRESA] ASC) WITH (FILLFACTOR = 80);

