CREATE TABLE [dbo].[FASI_PROCEDURALI] (
    [COD_FASE]    CHAR (1)      NOT NULL,
    [DESCRIZIONE] VARCHAR (100) NOT NULL,
    [ORDINE]      INT           NULL,
    CONSTRAINT [PK_FASI_PROCEDURALI] PRIMARY KEY CLUSTERED ([COD_FASE] ASC) WITH (FILLFACTOR = 100)
);

