CREATE TABLE [dbo].[FILE_DOCUMENTO] (
    [ID_FILE]          INT           IDENTITY (1, 1) NOT NULL,
    [ID_DOCUMENTO]     INT           NOT NULL,
    [NOME]             VARCHAR (80)  NULL,
    [TIPO]             VARCHAR (10)  NULL,
    [SIZE_FILE]        INT           NOT NULL,
    [DESCRIZIONE]      VARCHAR (100) NOT NULL,
    [ID_ARCHIVIO_FILE] INT           NULL,
    CONSTRAINT [PK_FILE_DOCUMENTO] PRIMARY KEY CLUSTERED ([ID_FILE] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_FILE_DOCUMENTO_DOCUMENTI] FOREIGN KEY ([ID_DOCUMENTO]) REFERENCES [dbo].[DOCUMENTI] ([ID_DOCUMENTO])
);

