CREATE TABLE [dbo].[FONTI_FINANZIARIE] (
    [ID_FONTE]    INT             IDENTITY (1, 1) NOT NULL,
    [PERCENTUALE] DECIMAL (10, 3) NOT NULL,
    [DESCRIZIONE] VARCHAR (255)   NOT NULL,
    CONSTRAINT [FONTI_FSE_PK] PRIMARY KEY CLUSTERED ([ID_FONTE] ASC) WITH (FILLFACTOR = 100)
);

