CREATE TABLE [dbo].[FORMA_GIURIDICA] (
    [COD_ISTAT]   VARCHAR (10)        NOT NULL,
    [DESCRIZIONE] [dbo].[DESCRIZIONE] NULL,
    [FOGLIA]      BIT                 NULL,
    CONSTRAINT [PK_CODICI_ISTAT_IMPRESE] PRIMARY KEY CLUSTERED ([COD_ISTAT] ASC) WITH (FILLFACTOR = 100)
);

