CREATE TABLE [dbo].[GANTT_UO_PROGRAMMAZIONE] (
    [ID_GANTT_UO_PROGRAMMAZIONE] INT             IDENTITY (1, 1) NOT NULL,
    [ID_UO]                      INT             NULL,
    [ID_PROGRAMMAZIONE]          INT             NULL,
    [IMPORTO_DOTAZIONE]          DECIMAL (18, 2) NULL,
    [NOTE]                       VARCHAR (MAX)   NULL,
    [IMPORTO_TARGET]             DECIMAL (18, 2) NULL,
    CONSTRAINT [PK_GANTT_UO_PROGRAMMAZIONE] PRIMARY KEY CLUSTERED ([ID_GANTT_UO_PROGRAMMAZIONE] ASC)
);

