CREATE TABLE [dbo].[GIUSTIFICATIVI] (
    [ID_GIUSTIFICATIVO]               INT             IDENTITY (1, 1) NOT NULL,
    [ID_PROGETTO]                     INT             NOT NULL,
    [NUMERO]                          VARCHAR (30)    NULL,
    [COD_TIPO]                        CHAR (3)        NOT NULL,
    [DATA]                            DATETIME        NOT NULL,
    [NUMERO_DOCTRASPORTO]             VARCHAR (30)    NULL,
    [DATA_DOCTRASPORTO]               DATETIME        NULL,
    [IMPONIBILE]                      DECIMAL (18, 2) NOT NULL,
    [IVA]                             DECIMAL (18, 2) CONSTRAINT [DF_GIUSTIFICATIVI_IVA] DEFAULT ((0)) NULL,
    [ALTRI_ONERI]                     DECIMAL (18, 2) NULL,
    [DESCRIZIONE]                     VARCHAR (255)   NULL,
    [CF_FORNITORE]                    VARCHAR (16)    NOT NULL,
    [DESCRIZIONE_FORNITORE]           VARCHAR (255)   NULL,
    [IVA_NON_RECUPERABILE]            BIT             CONSTRAINT [DF_GIUSTIFICATIVI_IVA_NON_RECUPERABILE] DEFAULT ((0)) NOT NULL,
    [ID_FILE]                         INT             NULL,
    [IN_INTEGRAZIONE]                 BIT             CONSTRAINT [DF_GIUSTIFICATIVI_IN_INTEGRAZIONE] DEFAULT ((0)) NULL,
    [ID_FILE_MODIFICATO_INTEGRAZIONE] BIT             NULL,
    CONSTRAINT [PK_GIUSTIFICATIVI] PRIMARY KEY CLUSTERED ([ID_GIUSTIFICATIVO] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_GIUSTIFICATIVI_PROGETTO] FOREIGN KEY ([ID_PROGETTO]) REFERENCES [dbo].[PROGETTO] ([ID_PROGETTO]),
    CONSTRAINT [FK_GIUSTIFICATIVI_TIPO_GIUSTIFICATIVO] FOREIGN KEY ([COD_TIPO]) REFERENCES [dbo].[TIPO_GIUSTIFICATIVO] ([COD_TIPO])
);


GO
CREATE NONCLUSTERED INDEX [IX_GIUSTIFICATIVI]
    ON [dbo].[GIUSTIFICATIVI]([ID_PROGETTO] ASC) WITH (FILLFACTOR = 80);

