CREATE TABLE [dbo].[GRADUATORIA_PROGETTI] (
    [ID_BANDO]                           INT             NOT NULL,
    [ID_PROGETTO]                        INT             NOT NULL,
    [PUNTEGGIO]                          DECIMAL (10, 6) CONSTRAINT [DF_GRADUATORIA_PROGETTI_PUNTEGGIO] DEFAULT ((0)) NOT NULL,
    [DATA_VALUTAZIONE]                   DATETIME        NOT NULL,
    [OPERATORE]                          VARCHAR (16)    NOT NULL,
    [ORDINE]                             INT             NULL,
    [COSTO_TOTALE]                       DECIMAL (18, 2) NULL,
    [CONTRIBUTO_TOTALE]                  DECIMAL (18, 2) NULL,
    [CONTRIBUTO_RIMANENTE]               DECIMAL (18, 2) NULL,
    [FINANZIABILITA]                     CHAR (1)        NULL,
    [UTILIZZA_FONDI_RISERVA]             BIT             CONSTRAINT [DF_GRADUATORIA_PROGETTI_UTILIZZA_FONDI_RISERVA] DEFAULT ((0)) NOT NULL,
    [AMMONTARE_FONDI_RISERVA_UTILIZZATO] DECIMAL (18, 2) NULL,
    CONSTRAINT [PK_GRADUATORIA_PROGETTI_1] PRIMARY KEY CLUSTERED ([ID_BANDO] ASC, [ID_PROGETTO] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_GRADUATORIA_PROGETTI_BANDO] FOREIGN KEY ([ID_BANDO]) REFERENCES [dbo].[BANDO] ([ID_BANDO]),
    CONSTRAINT [FK_GRADUATORIA_PROGETTI_PROGETTO] FOREIGN KEY ([ID_PROGETTO]) REFERENCES [dbo].[PROGETTO] ([ID_PROGETTO])
);

