CREATE TABLE [dbo].[GRADUATORIA_PROGETTI_FINANZIABILITA] (
    [ID_BANDO]             INT             NOT NULL,
    [ID_PROGETTO]          INT             NOT NULL,
    [ID_PROG_INTEGRATO]    INT             NOT NULL,
    [COSTO_TOTALE]         DECIMAL (18, 2) NULL,
    [CONTRIBUTO_DI_MISURA] DECIMAL (18, 2) NULL,
    [CONTRIBUTO_RIMANENTE] DECIMAL (18, 2) NULL,
    [MISURA]               VARCHAR (10)    NULL,
    [MISURA_PREVALENTE]    BIT             NULL,
    CONSTRAINT [PK_GRADUATORIA_PROGETTI_FINANZIABILITA] PRIMARY KEY CLUSTERED ([ID_BANDO] ASC, [ID_PROGETTO] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_GRADUATORIA_PROGETTI_FINANZIABILITA_PROGETTO] FOREIGN KEY ([ID_PROGETTO]) REFERENCES [dbo].[PROGETTO] ([ID_PROGETTO])
);

