CREATE TABLE [dbo].[IMPRESA] (
    [ID_IMPRESA]                  INT          IDENTITY (1, 1) NOT NULL,
    [CUAA]                        VARCHAR (16) NOT NULL,
    [CODICE_FISCALE]              VARCHAR (16) NOT NULL,
    [ANNO_COSTITUZIONE]           INT          NULL,
    [COD_ENTE]                    VARCHAR (10) NULL,
    [ISCRIZIONE_REGISTRO_IMPRESE] VARCHAR (16) NULL,
    [PRESENTAZIONE]               NTEXT        NULL,
    [DESCRIZIONE]                 NTEXT        NULL,
    [DATA_INIZIO_ATTIVITA]        DATETIME     NULL,
    [ID_STORICO_ULTIMO]           INT          NULL,
    [ID_SEDELEGALE_ULTIMO]        INT          NULL,
    [ID_RAPPRLEGALE_ULTIMO]       INT          NULL,
    [ID_CONTO_CORRENTE_ULTIMO]    INT          NULL,
    CONSTRAINT [PK_IMPRESA] PRIMARY KEY CLUSTERED ([ID_IMPRESA] ASC) WITH (FILLFACTOR = 80)
);


GO
CREATE NONCLUSTERED INDEX [IX_IMPRESA]
    ON [dbo].[IMPRESA]([CUAA] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IX_IMPRESA_1]
    ON [dbo].[IMPRESA]([CODICE_FISCALE] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IX_IMPRESA_2]
    ON [dbo].[IMPRESA]([ID_STORICO_ULTIMO] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IX_IMPRESA_3]
    ON [dbo].[IMPRESA]([ID_RAPPRLEGALE_ULTIMO] ASC)
    INCLUDE([ID_IMPRESA], [CUAA], [CODICE_FISCALE], [ID_STORICO_ULTIMO], [ID_SEDELEGALE_ULTIMO]) WITH (FILLFACTOR = 80);

