CREATE TABLE [dbo].[IMPRESA_CERTIFICAZIONE_ANTIMAFIA] (
    [ID]                                       INT          IDENTITY (1, 1) NOT NULL,
    [ID_IMPRESA]                               INT          NOT NULL,
    [ESENZIONE_CERTIFICAZIONE]                 BIT          CONSTRAINT [DF_IMPRESA_CERTIFICAZIONE_ANTIMAFIA_ESENZIONE_CERTIFICAZIONE] DEFAULT ((0)) NOT NULL,
    [DATA_INIZIO_VALIDITA]                     DATETIME     NULL,
    [DATA_FINE_VALIDITA]                       DATETIME     NULL,
    [NUMERO_PROTOCOLLO_RICHIESTA]              VARCHAR (30) NULL,
    [DATA_PROTOCOLLO_RICHIESTA]                DATETIME     NULL,
    [NUMERO_PROTOCOLLO_CAMERALE]               VARCHAR (30) NULL,
    [DATA_CERTIFICATO_CAMERALE]                DATETIME     NULL,
    [ESITO_CERTIFICATO_CAMERALE]               BIT          NULL,
    [NUMERO_PROTOCOLLO_PREFETTIZIO]            VARCHAR (30) NULL,
    [DATA_CERTIFICATO_PREFETTIZIO]             DATETIME     NULL,
    [ESITO_CERTIFICATO_PREFETTIZIO]            BIT          NULL,
    [NUMERO_PROTOCOLLO_COMUNICAZIONE]          VARCHAR (30) NULL,
    [DATA_PROTOCOLLO_COMUNICAZIONE]            DATETIME     NULL,
    [DATA_ACQUISIZIONE_ANTIMAFIA]              DATETIME     NULL,
    [NUMERO_PROTOCOLLO_ACQUISIZIONE_ANTIMAFIA] VARCHAR (30) NULL,
    CONSTRAINT [PK_IMPRESA_CERTIFICAZIONE_ANTIMAFIA] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_IMPRESA_CERTIFICAZIONE_ANTIMAFIA_IMPRESA] FOREIGN KEY ([ID_IMPRESA]) REFERENCES [dbo].[IMPRESA] ([ID_IMPRESA])
);

