CREATE TABLE [dbo].[INDIRIZZO] (
    [ID_INDIRIZZO]  INT                 IDENTITY (1, 1) NOT NULL,
    [VIA]           VARCHAR (500)       NOT NULL,
    [LOCALITA]      VARCHAR (500)       NULL,
    [ID_COMUNE]     INT                 NULL,
    [DENOMINAZIONE] [dbo].[DESCRIZIONE] NULL,
    CONSTRAINT [PK_INDIRIZZO] PRIMARY KEY CLUSTERED ([ID_INDIRIZZO] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_INDIRIZZO_COMUNI] FOREIGN KEY ([ID_COMUNE]) REFERENCES [dbo].[COMUNI] ([ID_COMUNE])
);


GO
CREATE NONCLUSTERED INDEX [IX_INDIRIZZO]
    ON [dbo].[INDIRIZZO]([ID_COMUNE] ASC) WITH (FILLFACTOR = 80);

