CREATE TABLE [dbo].[INDIRIZZARIO] (
    [ID_INDIRIZZARIO]      INT           IDENTITY (1, 1) NOT NULL,
    [ID_INDIRIZZO]         INT           NOT NULL,
    [ID_PERSONA]           INT           NULL,
    [ID_IMPRESA]           INT           NULL,
    [COD_TIPO_SEDE]        CHAR (1)      NOT NULL,
    [DATA_INIZIO_VALIDITA] DATETIME      CONSTRAINT [DF_INDIRIZZARIO_DATA_INIZIO_VALIDITA] DEFAULT (getdate()) NOT NULL,
    [DATA_FINE_VALIDITA]   DATETIME      NULL,
    [FLAG_ATTIVO]          BIT           CONSTRAINT [DF_INDIRIZZARIO_FLAG_ATTIVO] DEFAULT ((0)) NOT NULL,
    [TELEFONO]             VARCHAR (80)  NULL,
    [FAX]                  VARCHAR (80)  NULL,
    [EMAIL]                VARCHAR (80)  NULL,
    [PEC]                  VARCHAR (200) NULL,
    CONSTRAINT [PK_INDIRIZZARIO] PRIMARY KEY CLUSTERED ([ID_INDIRIZZARIO] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_INDIRIZZARIO_IMPRESA] FOREIGN KEY ([ID_IMPRESA]) REFERENCES [dbo].[IMPRESA] ([ID_IMPRESA]),
    CONSTRAINT [FK_INDIRIZZARIO_INDIRIZZO] FOREIGN KEY ([ID_INDIRIZZO]) REFERENCES [dbo].[INDIRIZZO] ([ID_INDIRIZZO]),
    CONSTRAINT [FK_INDIRIZZARIO_PERSONA_FISICA] FOREIGN KEY ([ID_PERSONA]) REFERENCES [dbo].[PERSONA_FISICA] ([ID_PERSONA]),
    CONSTRAINT [FK_INDIRIZZARIO_TIPO_SEDE] FOREIGN KEY ([COD_TIPO_SEDE]) REFERENCES [dbo].[TIPO_SEDE] ([COD_TIPO_SEDE])
);


GO
CREATE NONCLUSTERED INDEX [IX_INDIRIZZARIO]
    ON [dbo].[INDIRIZZARIO]([ID_IMPRESA] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IX_INDIRIZZARIO_1]
    ON [dbo].[INDIRIZZARIO]([ID_PERSONA] ASC, [COD_TIPO_SEDE] ASC) WITH (FILLFACTOR = 80);

