CREATE TABLE [dbo].[INTEGRAZIONE_SINGOLA_DI_DOMANDA] (
    [ID_SINGOLA_INTEGRAZIONE]                      INT           IDENTITY (1, 1) NOT NULL,
    [ID_INTEGRAZIONE_DOMANDA]                      INT           NOT NULL,
    [COD_TIPO_INTEGRAZIONE]                        CHAR (3)      NOT NULL,
    [DATA_INSERIMENTO]                             DATETIME      CONSTRAINT [DF_INTEGRAZIONE_DI_DOMANDA_DATA_CREAZIONE] DEFAULT (getdate()) NULL,
    [DATA_MODIFICA]                                DATETIME      CONSTRAINT [DF_INTEGRAZIONE_DI_DOMANDA_DATA_MODIFICA] DEFAULT (getdate()) NULL,
    [CF_ISTRUTTORE_SINGOLA_INTEGRAZIONE]           VARCHAR (16)  NULL,
    [NOTE_INTEGRAZIONE_ISTRUTTORE]                 VARCHAR (MAX) NULL,
    [DATA_RICHIESTA_INTEGRAZIONE_ISTRUTTORE]       DATETIME      NULL,
    [DATA_CONCLUSIONE_ISTRUTTORE]                  DATETIME      NULL,
    [SINGOLA_INTEGRAZIONE_COMPLETATA_ISTRUTTORE]   BIT           CONSTRAINT [DF_INTEGRAZIONE_DI_DOMANDA_COMPLETATA] DEFAULT ((0)) NULL,
    [CF_BENEFICIARIO_SINGOLA_INTEGRAZIONE]         VARCHAR (16)  NULL,
    [NOTE_INTEGRAZIONE_BENEFICIARIO]               VARCHAR (MAX) NULL,
    [DATA_RILASCIO_INTEGRAZIONE_BENEFICIARIO]      DATETIME      NULL,
    [DATA_CONCLUSIONE_BENEFICIARIO]                DATETIME      NULL,
    [SINGOLA_INTEGRAZIONE_COMPLETATA_BENEFICIARIO] BIT           NULL,
    [ID_SPESA]                                     INT           NULL,
    [ID_GIUSTIFICATIVO]                            INT           NULL,
    CONSTRAINT [PK_INTEGRAZIONE_DI_DOMANDA] PRIMARY KEY CLUSTERED ([ID_SINGOLA_INTEGRAZIONE] ASC),
    CONSTRAINT [FK_INTEGRAZIONE_DI_DOMANDA_INTEGRAZIONI_PER_DOMANDA_DI_PAGAMENTO] FOREIGN KEY ([ID_INTEGRAZIONE_DOMANDA]) REFERENCES [dbo].[INTEGRAZIONI_PER_DOMANDA_DI_PAGAMENTO] ([ID_INTEGRAZIONE_DOMANDA_DI_PAGAMENTO]),
    CONSTRAINT [FK_INTEGRAZIONE_SINGOLA_DI_DOMANDA_TIPO_INTEGRAZIONE_DOMANDA] FOREIGN KEY ([COD_TIPO_INTEGRAZIONE]) REFERENCES [dbo].[TIPO_INTEGRAZIONE_DOMANDA] ([COD_TIPO])
);

