CREATE TABLE [dbo].[ITER_PROGETTO] (
    [ID_PROGETTO]              INT          NOT NULL,
    [ID_STEP]                  INT          NOT NULL,
    [COD_ESITO]                CHAR (2)     NULL,
    [DATA]                     DATETIME     NOT NULL,
    [CF_OPERATORE]             VARCHAR (16) NULL,
    [NOTE]                     NTEXT        NULL,
    [COD_ESITO_REVISORE]       CHAR (2)     NULL,
    [DATA_REVISORE]            DATETIME     NULL,
    [REVISORE]                 VARCHAR (16) NULL,
    [NOTE_REVISORE]            NTEXT        NULL,
    [ESCLUDI_DA_COMUNICAZIONE] BIT          CONSTRAINT [DF_ITER_PROGETTO_ESCLUDI_DA_COMUNICAZIONE] DEFAULT ((0)) NULL,
    CONSTRAINT [PK_ITER_PROGETTO_1] PRIMARY KEY CLUSTERED ([ID_PROGETTO] ASC, [ID_STEP] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_ITER_PROGETTO_ESITI_STEP] FOREIGN KEY ([COD_ESITO]) REFERENCES [dbo].[ESITI_STEP] ([COD_ESITO]),
    CONSTRAINT [FK_ITER_PROGETTO_PROGETTO] FOREIGN KEY ([ID_PROGETTO]) REFERENCES [dbo].[PROGETTO] ([ID_PROGETTO]),
    CONSTRAINT [FK_ITER_PROGETTO_STEP] FOREIGN KEY ([ID_STEP]) REFERENCES [dbo].[STEP] ([ID_STEP])
);

