CREATE TABLE [dbo].[LOCALIZZAZIONE_PROGETTO] (
    [ID_LOCALIZZAZIONE]  INT            IDENTITY (1, 1) NOT NULL,
    [ID_PROGETTO]        INT            NOT NULL,
    [ID_IMPRESA]         INT            NOT NULL,
    [ID_COMUNE]          INT            NOT NULL,
    [CAP]                CHAR (5)       NOT NULL,
    [DUG]                SMALLINT       NOT NULL,
    [VIA]                VARCHAR (200)  NOT NULL,
    [NUM]                VARCHAR (16)   NOT NULL,
    [CATASTO_ID]         INT            NULL,
    [CATASTO_FOGLIO]     VARCHAR (6)    NULL,
    [CATASTO_PARTICELLA] VARCHAR (6)    NULL,
    [CATASTO_SEZIONE]    CHAR (1)       NULL,
    [CATASTO_SUBALTERNO] VARCHAR (3)    NULL,
    [CATASTO_SUPERFICIE] INT            NULL,
    [QUOTA]              DECIMAL (5, 2) CONSTRAINT [DF_LOCALIZZAZIONE_PROGETTO_QUOTA] DEFAULT ((100.00)) NULL,
    CONSTRAINT [PK_LOCALIZZAZIONE_PROGETTO] PRIMARY KEY CLUSTERED ([ID_LOCALIZZAZIONE] ASC) WITH (FILLFACTOR = 80)
);

