CREATE TABLE [dbo].[MODELLO_DOMANDA] (
    [ID_DOMANDA]    INT            IDENTITY (1, 1) NOT NULL,
    [ID_BANDO]      INT            NOT NULL,
    [DEFINITIVO]    BIT            NULL,
    [OPERATORE]     VARCHAR (16)   NULL,
    [DENOMINAZIONE] VARCHAR (50)   NOT NULL,
    [DESCRIZIONE]   VARCHAR (1000) NULL,
    CONSTRAINT [PK_MODELLO_DOMANDA] PRIMARY KEY CLUSTERED ([ID_DOMANDA] ASC) WITH (FILLFACTOR = 80)
);

