CREATE TABLE [dbo].[PAGAMENTI_RICHIESTI] (
    [ID_PAGAMENTO_RICHIESTO]                 INT             IDENTITY (1, 1) NOT NULL,
    [ID_DOMANDA_PAGAMENTO]                   INT             NOT NULL,
    [ID_INVESTIMENTO]                        INT             NOT NULL,
    [DATA_RICHIESTA_PAGAMENTO]               DATETIME        NOT NULL,
    [IMPORTO_COMPUTO_METRICO]                DECIMAL (18, 2) NULL,
    [IMPORTO_RICHIESTO]                      DECIMAL (18, 2) NOT NULL,
    [CONTRIBUTO_RICHIESTO]                   DECIMAL (18, 2) NOT NULL,
    [CONTRIBUTO_RICHIESTO_ALTRE_FONTI]       DECIMAL (18, 2) NULL,
    [IMPORTO_DISAVANZO_COSTI_AMMESSI]        DECIMAL (18, 2) NULL,
    [CONTRIBUTO_DISAVANZO_COSTI_AMMESSI]     DECIMAL (18, 2) NULL,
    [CONTRIBUTO_RICHIESTO_RECUPERO_ANTICIPO] DECIMAL (18, 2) NULL,
    [IMPORTO_COMPUTO_METRICO_AMMESSO]        DECIMAL (18, 2) NULL,
    [IMPORTO_AMMESSO]                        DECIMAL (18, 2) NULL,
    [CONTRIBUTO_AMMESSO]                     DECIMAL (18, 2) NULL,
    [CONTRIBUTO_AMMESSO_ALTRE_FONTI]         DECIMAL (18, 2) NULL,
    [CONTRIBUTO_AMMESSO_RECUPERO_ANTICIPO]   DECIMAL (18, 2) NULL,
    [AMMESSO]                                BIT             CONSTRAINT [DF_PAGAMENTI_RICHIESTI_AMMESSO] DEFAULT ((0)) NOT NULL,
    [ISTRUTTORE]                             VARCHAR (16)    NULL,
    [DATA_VALUTAZIONE]                       DATETIME        NULL,
    [NOTE_ISTRUTTORE]                        NTEXT           NULL,
    [COD_SANZIONE_VARIAZIONE_INVESTIMENTI]   CHAR (3)        NULL,
    CONSTRAINT [PK_PAGAMENTI_RICHIESTI] PRIMARY KEY NONCLUSTERED ([ID_PAGAMENTO_RICHIESTO] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_PAGAMENTI_RICHIESTI_DOMANDA_DI_PAGAMENTO] FOREIGN KEY ([ID_DOMANDA_PAGAMENTO]) REFERENCES [dbo].[DOMANDA_DI_PAGAMENTO] ([ID_DOMANDA_PAGAMENTO]),
    CONSTRAINT [FK_PAGAMENTI_RICHIESTI_PIANO_INVESTIMENTI] FOREIGN KEY ([ID_INVESTIMENTO]) REFERENCES [dbo].[PIANO_INVESTIMENTI] ([ID_INVESTIMENTO])
);


GO
CREATE CLUSTERED INDEX [IX_PAGAMENTI_RICHIESTI]
    ON [dbo].[PAGAMENTI_RICHIESTI]([ID_INVESTIMENTO] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IX_PAGAMENTI_RICHIESTI_1]
    ON [dbo].[PAGAMENTI_RICHIESTI]([ID_DOMANDA_PAGAMENTO] ASC) WITH (FILLFACTOR = 80);

