CREATE TABLE [dbo].[PAGAMENTI_BENEFICIARIO] (
    [ID_PAGAMENTO_BENEFICIARIO]    INT             IDENTITY (1, 1) NOT NULL,
    [ID_PAGAMENTO_RICHIESTO]       INT             NOT NULL,
    [ID_GIUSTIFICATIVO]            INT             NOT NULL,
    [IMPORTO_RICHIESTO]            DECIMAL (18, 2) NOT NULL,
    [IMPORTO_AMMESSO]              DECIMAL (18, 2) NULL,
    [CONTRIBUTO_AMMESSO]           DECIMAL (18, 2) NULL,
    [QUOTA_CONTRIBUTO_AMMESSO]     DECIMAL (10, 2) NULL,
    [IMPORTO_NONAMM_NONRESP]       DECIMAL (18, 2) NULL,
    [IMPORTO_AMMESSO_CONTR]        DECIMAL (18, 2) NULL,
    [IMPORTO_NONAMM_CONTR_NONRESP] DECIMAL (18, 2) NULL,
    [SPESA_TECNICA_RICHIESTA]      BIT             CONSTRAINT [DF_PAGAMENTI_BENEFICIARIO_SPESA_TECNICA_RICHIESTA] DEFAULT ((0)) NOT NULL,
    [SPESA_TECNICA_AMMESSA]        BIT             CONSTRAINT [DF_PAGAMENTI_BENEFICIARIO_SPESA_TECNICA_AMMESSA] DEFAULT ((0)) NULL,
    [SPESA_TECNICA_AMMESSA_CONTR]  BIT             CONSTRAINT [DF_PAGAMENTI_BENEFICIARIO_SPESA_TECNICA_AMMESSA_CONTR] DEFAULT ((0)) NULL,
    [COSTITUISCE_VARIANTE]         BIT             CONSTRAINT [DF_PAGAMENTI_BENEFICIARIO_COSTITUISCE_VARIANTE] DEFAULT ((0)) NOT NULL,
    [COD_RIDUZIONE]                VARCHAR (50)    NULL,
    [MOTIVAZIONE_RIDUZIONE]        INT             NULL,
    [COD_RIDUZIONE_CONTR]          VARCHAR (50)    NULL,
    [MOTIVAZIONE_RIDUZIONE_CONTR]  INT             NULL,
    CONSTRAINT [PK_PAGAMENTI_BENEFICIARIO] PRIMARY KEY NONCLUSTERED ([ID_PAGAMENTO_BENEFICIARIO] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_PAGAMENTI_BENEFICIARIO_GIUSTIFICATIVI] FOREIGN KEY ([ID_GIUSTIFICATIVO]) REFERENCES [dbo].[GIUSTIFICATIVI] ([ID_GIUSTIFICATIVO]),
    CONSTRAINT [FK_PAGAMENTI_BENEFICIARIO_PAGAMENTI_RICHIESTI] FOREIGN KEY ([ID_PAGAMENTO_RICHIESTO]) REFERENCES [dbo].[PAGAMENTI_RICHIESTI] ([ID_PAGAMENTO_RICHIESTO])
);


GO
CREATE CLUSTERED INDEX [IX_PAGAMENTO_BENEFICIARIO]
    ON [dbo].[PAGAMENTI_BENEFICIARIO]([ID_PAGAMENTO_RICHIESTO] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IX_PAGAMENTI_BENEFICIARIO]
    ON [dbo].[PAGAMENTI_BENEFICIARIO]([ID_GIUSTIFICATIVO] ASC) WITH (FILLFACTOR = 80);

