CREATE TABLE [dbo].[PAGE_HELP] (
    [ID]        INT           IDENTITY (1, 1) NOT NULL,
    [PAGE]      VARCHAR (255) NOT NULL,
    [PARAMETRI] VARCHAR (255) NULL,
    [ID_DOC]    INT           NOT NULL,
    [ID_PDF]    INT           NOT NULL,
    [OPERATORE] INT           NOT NULL,
    [DATA]      DATETIME      NOT NULL,
    [ATTIVO]    BIT           CONSTRAINT [DF_PAGE_HELP_ATTIVO] DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PK_PAGE_HELP] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 80)
);

