CREATE TABLE [dbo].[PERSONE_X_IMPRESE] (
    [ID_PERSONE_X_IMPRESE] INT      IDENTITY (1, 1) NOT NULL,
    [ID_IMPRESA]           INT      NULL,
    [ID_PERSONA]           INT      NULL,
    [COD_RUOLO]            CHAR (1) NOT NULL,
    [ATTIVO]               BIT      CONSTRAINT [DF_PERSONE_X_IMPRESE_ATTIVO] DEFAULT ((1)) NOT NULL,
    [DATA_INIZIO]          DATETIME CONSTRAINT [DF_PERSONE_X_IMPRESE_DATA_INIZIO] DEFAULT (getdate()) NOT NULL,
    [DATA_FINE]            DATETIME NULL,
    [AMMESSO]              BIT      CONSTRAINT [DF_PERSONE_X_IMPRESE_AMMESSO] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_PERSONE_X_IMPRESE] PRIMARY KEY CLUSTERED ([ID_PERSONE_X_IMPRESE] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_PERSONE_X_IMPRESE_IMPRESA] FOREIGN KEY ([ID_IMPRESA]) REFERENCES [dbo].[IMPRESA] ([ID_IMPRESA]),
    CONSTRAINT [FK_PERSONE_X_IMPRESE_PERSONA_FISICA] FOREIGN KEY ([ID_PERSONA]) REFERENCES [dbo].[PERSONA_FISICA] ([ID_PERSONA]),
    CONSTRAINT [FK_PERSONE_X_IMPRESE_RUOLO] FOREIGN KEY ([COD_RUOLO]) REFERENCES [dbo].[RUOLO] ([COD_RUOLO])
);


GO
CREATE NONCLUSTERED INDEX [IX_PERSONE_X_IMPRESE]
    ON [dbo].[PERSONE_X_IMPRESE]([ID_IMPRESA] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IX_PERSONE_X_IMPRESE_1]
    ON [dbo].[PERSONE_X_IMPRESE]([ID_PERSONA] ASC)
    INCLUDE([ID_PERSONE_X_IMPRESE]) WITH (FILLFACTOR = 80);

