CREATE TABLE [dbo].[PIANO_DI_SVILUPPO_DOMANDA_PAGAMENTO] (
    [ID_PIANO]             INT             IDENTITY (1, 1) NOT NULL,
    [ANNO]                 INT             NULL,
    [ID_DOMANDA_PAGAMENTO] INT             NOT NULL,
    [ID_IMPRESA]           INT             NULL,
    [ID_PROGETTO]          INT             NULL,
    [COSTO_INVESTIMENTO]   DECIMAL (10, 2) NULL,
    [MEZZI_PROPRI]         DECIMAL (10, 2) NULL,
    [RISORSE_TERZI]        DECIMAL (10, 2) NULL,
    [CONTRIBUTI_PUBBLICI]  DECIMAL (10, 2) NULL,
    [SPESE_GESTIONE]       DECIMAL (10, 2) NULL,
    [RIMBORSO_DEBITO]      DECIMAL (10, 2) NULL,
    [ENTRATA_GESTIONE]     DECIMAL (10, 2) NULL,
    [ALTRE_COPERTURE]      DECIMAL (10, 2) NULL,
    CONSTRAINT [PK_PIANO_DI_SVILUPPO_DOMANDA_PAGAMENTO] PRIMARY KEY CLUSTERED ([ID_PIANO] ASC) WITH (FILLFACTOR = 80)
);

