CREATE TABLE [dbo].[PRIORITA_X_INVESTIMENTI] (
    [ID_PRIORITA]     INT             NOT NULL,
    [ID_INVESTIMENTO] INT             NOT NULL,
    [ID_VALORE]       INT             NULL,
    [SCELTO]          BIT             NULL,
    [VALORE]          DECIMAL (18, 2) NULL,
    [VAL_DATA]        DATETIME        NULL,
    [VAL_TESTO]       VARCHAR (500)   NULL,
    CONSTRAINT [PK_PRIORITA_X_INVESTIMENTI] PRIMARY KEY CLUSTERED ([ID_PRIORITA] ASC, [ID_INVESTIMENTO] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_PRIORITA_X_INVESTIMENTI_PIANO_INVESTIMENTI] FOREIGN KEY ([ID_INVESTIMENTO]) REFERENCES [dbo].[PIANO_INVESTIMENTI] ([ID_INVESTIMENTO]),
    CONSTRAINT [FK_PRIORITA_X_INVESTIMENTI_PRIORITA] FOREIGN KEY ([ID_PRIORITA]) REFERENCES [dbo].[PRIORITA] ([ID_PRIORITA])
);


GO
CREATE NONCLUSTERED INDEX [IX_PRIORITA_X_INVESTIMENTI]
    ON [dbo].[PRIORITA_X_INVESTIMENTI]([ID_INVESTIMENTO] ASC) WITH (FILLFACTOR = 80);

