CREATE TABLE [dbo].[PRIORITA_X_PROGETTO] (
    [ID_PROGETTO]           INT             NOT NULL,
    [ID_PRIORITA]           INT             NOT NULL,
    [ID_VALORE]             INT             NULL,
    [VALORE]                DECIMAL (18, 2) NULL,
    [DATA_VALUTAZIONE]      DATETIME        NULL,
    [OPERATORE_VALUTAZIONE] VARCHAR (16)    NULL,
    [MODIFICA_MANUALE]      BIT             NULL,
    [PUNTEGGIO]             DECIMAL (18, 6) NULL,
    [VAL_DATA]              DATETIME        NULL,
    [VAL_TESTO]             VARCHAR (500)   NULL,
    CONSTRAINT [PK_INDICATORI_X_PROGETTO] PRIMARY KEY CLUSTERED ([ID_PROGETTO] ASC, [ID_PRIORITA] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_INDICATORI_X_PROGETTO_PRIORITA] FOREIGN KEY ([ID_PRIORITA]) REFERENCES [dbo].[PRIORITA] ([ID_PRIORITA]),
    CONSTRAINT [FK_INDICATORI_X_PROGETTO_PROGETTO] FOREIGN KEY ([ID_PROGETTO]) REFERENCES [dbo].[PROGETTO] ([ID_PROGETTO])
);

