CREATE TABLE [dbo].[PROGETTO_RELAZIONE_TECNICA] (
    [ID_PARAGRAFO] INT   NOT NULL,
    [ID_PROGETTO]  INT   NOT NULL,
    [TESTO]        NTEXT NULL,
    CONSTRAINT [PK_PROGETTO_RELAZIONE_TECNICA] PRIMARY KEY CLUSTERED ([ID_PARAGRAFO] ASC, [ID_PROGETTO] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_PROGETTO_RELAZIONE_TECNICA_BANDO_RELAZIONE_TECNICA] FOREIGN KEY ([ID_PARAGRAFO]) REFERENCES [dbo].[BANDO_RELAZIONE_TECNICA] ([ID_PARAGRAFO]),
    CONSTRAINT [FK_PROGETTO_RELAZIONE_TECNICA_PROGETTO] FOREIGN KEY ([ID_PROGETTO]) REFERENCES [dbo].[PROGETTO] ([ID_PROGETTO])
);

