CREATE TABLE [dbo].[PROGETTO_INDICATORI] (
    [ID_PROGETTO_INDICATORI]       INT             IDENTITY (1, 1) NOT NULL,
    [ID_DIM_X_PROGRAMMAZIONE]      INT             NOT NULL,
    [ID_PROGETTO]                  INT             NOT NULL,
    [ID_DOMANDA_PAGAMENTO]         INT             NULL,
    [ID_VARIANTE]                  INT             NULL,
    [COD_TIPO]                     VARCHAR (10)    NOT NULL,
    [VALORE_PROGRAMMATO_RICHIESTO] DECIMAL (18, 2) NOT NULL,
    [VALORE_REALIZZATO_RICHIESTO]  DECIMAL (18, 2) NOT NULL,
    [DATA_REGISTRAZIONE]           DATETIME        NOT NULL,
    [OPERATORE]                    INT             NOT NULL,
    [VALORE_PROGRAMMATO_AMMESSO]   DECIMAL (18, 2) NULL,
    [VALORE_REALIZZATO_AMMESSO]    DECIMAL (18, 2) NULL,
    [DATA_ISTRUTTORIA]             DATETIME        NULL,
    [ISTRUTTORE]                   INT             NULL,
    CONSTRAINT [PROGETTO_INDICATORI_PK] PRIMARY KEY CLUSTERED ([ID_PROGETTO_INDICATORI] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_PROGETTO_INDICATORI_PROGETTO] FOREIGN KEY ([ID_PROGETTO]) REFERENCES [dbo].[PROGETTO] ([ID_PROGETTO]),
    CONSTRAINT [FK_PROGETTO_INDICATORI_zDIMENSIONI_X_PROGRAMMAZIONE] FOREIGN KEY ([ID_DIM_X_PROGRAMMAZIONE]) REFERENCES [dbo].[zDIMENSIONI_X_PROGRAMMAZIONE] ([ID_DIM_X_PROGRAMMAZIONE])
);

