CREATE TABLE [dbo].[PROGETTO_ALLEGATI] (
    [ID]                    INT            IDENTITY (1, 1) NOT NULL,
    [ID_PROGETTO]           INT            NOT NULL,
    [ID_ALLEGATO]           INT            NULL,
    [ID_FILE]               INT            NULL,
    [DESCRIZIONE_BREVE]     VARCHAR (255)  NULL,
    [COD_ENTE_EMETTITORE]   VARCHAR (10)   NULL,
    [ID_COMUNE]             INT            NULL,
    [NUMERO]                VARCHAR (20)   NULL,
    [DATA]                  DATETIME       NULL,
    [GIA_PRESENTATO]        BIT            CONSTRAINT [DF_PROGETTO_ALLEGATI_GIA_PRESENTATO] DEFAULT ((0)) NOT NULL,
    [COD_ESITO_ISTRUTTORIA] CHAR (2)       NULL,
    [NOTE_ISTRUTTORIA]      VARCHAR (1000) NULL,
    CONSTRAINT [PK_PROGETTO_ALLEGATI] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_PROGETTO_ALLEGATI_ALLEGATI] FOREIGN KEY ([ID_ALLEGATO]) REFERENCES [dbo].[ALLEGATI] ([ID_ALLEGATO]),
    CONSTRAINT [FK_PROGETTO_ALLEGATI_ARCHIVIO_FILE] FOREIGN KEY ([ID_FILE]) REFERENCES [dbo].[ARCHIVIO_FILE] ([ID]),
    CONSTRAINT [FK_PROGETTO_ALLEGATI_PROGETTO] FOREIGN KEY ([ID_PROGETTO]) REFERENCES [dbo].[PROGETTO] ([ID_PROGETTO])
);


GO
CREATE NONCLUSTERED INDEX [IX_PROGETTO_ALLEGATI]
    ON [dbo].[PROGETTO_ALLEGATI]([ID_PROGETTO] ASC) WITH (FILLFACTOR = 80);

