CREATE TABLE [dbo].[PROGETTO_COMUNICAZIONI_DOCUMENTI] (
    [ID]                            INT           IDENTITY (1, 1) NOT NULL,
    [ID_COMUNICAZIONE]              INT           NOT NULL,
    [ID_DOMANDA_PAGAMENTO_ALLEGATI] INT           NULL,
    [ID_VARIANTE_ALLEGATI]          INT           NULL,
    [COD_TIPO_DOCUMENTO]            VARCHAR (10)  NULL,
    [ID_FILE]                       INT           NULL,
    [COD_ENTE_EMETTITORE]           VARCHAR (10)  NULL,
    [ID_COMUNE]                     INT           NULL,
    [NUMERO]                        VARCHAR (20)  NULL,
    [DATA]                          DATETIME      NULL,
    [DESCRIZIONE]                   VARCHAR (255) NULL,
    [ID_NOTE_COMUNICAZIONE]         INT           NULL,
    CONSTRAINT [PK_PROGETTO_COMUNICAZIONI_DOCUMENTI] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PROGETTO_COMUNICAZIONI_DOCUMENTI_DOMANDA_PAGAMENTO_ALLEGATI] FOREIGN KEY ([ID_DOMANDA_PAGAMENTO_ALLEGATI]) REFERENCES [dbo].[DOMANDA_PAGAMENTO_ALLEGATI] ([ID_ALLEGATO]),
    CONSTRAINT [FK_PROGETTO_COMUNICAZIONI_DOCUMENTI_PROGETTO_COMUNICAZIONI] FOREIGN KEY ([ID_COMUNICAZIONE]) REFERENCES [dbo].[PROGETTO_COMUNICAZIONI] ([ID]),
    CONSTRAINT [FK_PROGETTO_COMUNICAZIONI_DOCUMENTI_TIPO_DOCUMENTO] FOREIGN KEY ([COD_TIPO_DOCUMENTO]) REFERENCES [dbo].[TIPO_DOCUMENTO] ([CODICE]),
    CONSTRAINT [FK_PROGETTO_COMUNICAZIONI_DOCUMENTI_VARIANTI_ALLEGATI] FOREIGN KEY ([ID_VARIANTE_ALLEGATI]) REFERENCES [dbo].[VARIANTI_ALLEGATI] ([ID_ALLEGATO])
);

