CREATE TABLE [dbo].[PROGETTO_COMUNICAZIONI_ALLEGATI] (
    [ID]                   INT IDENTITY (1, 1) NOT NULL,
    [ID_COMUNICAZIONE]     INT NOT NULL,
    [ID_PROGETTO_ALLEGATI] INT NULL,
    [ID_ALLEGATO]          INT NULL,
    [ID_NOTE]              INT NULL,
    CONSTRAINT [PK_PROGETTO_COMUNICAZIONI_ALLEGATI] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_PROGETTO_COMUNICAZIONI_ALLEGATI_PROGETTO_ALLEGATI] FOREIGN KEY ([ID_PROGETTO_ALLEGATI]) REFERENCES [dbo].[PROGETTO_ALLEGATI] ([ID]),
    CONSTRAINT [FK_PROGETTO_COMUNICAZIONI_ALLEGATI_PROGETTO_COMUNICAZIONI] FOREIGN KEY ([ID_COMUNICAZIONE]) REFERENCES [dbo].[PROGETTO_COMUNICAZIONI] ([ID])
);

