CREATE TABLE [dbo].[PROGETTO_SEGNATURE] (
    [ID_PROGETTO]    INT           NOT NULL,
    [COD_TIPO]       CHAR (3)      NOT NULL,
    [DATA]           DATETIME      NULL,
    [OPERATORE]      VARCHAR (16)  NULL,
    [SEGNATURA]      VARCHAR (100) NULL,
    [RIAPRI_DOMANDA] BIT           CONSTRAINT [DF_PROGETTO_SEGNATURE_RIAPRI_DOMANDA] DEFAULT ((0)) NULL,
    [MOTIVAZIONE]    NTEXT         NULL,
    CONSTRAINT [PK_PROGETTO_SEGNATURE] PRIMARY KEY CLUSTERED ([ID_PROGETTO] ASC, [COD_TIPO] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_PROGETTO_SEGNATURE_PROGETTO] FOREIGN KEY ([ID_PROGETTO]) REFERENCES [dbo].[PROGETTO] ([ID_PROGETTO]),
    CONSTRAINT [FK_PROGETTO_SEGNATURE_TIPO_SEGNATURA] FOREIGN KEY ([COD_TIPO]) REFERENCES [dbo].[TIPO_SEGNATURA] ([COD_TIPO])
);

