CREATE TABLE [dbo].[PROGETTO_VALUTATORI] (
    [ID]                      INT IDENTITY (1, 1) NOT NULL,
    [ID_PROGETTO_VALUTAZIONE] INT NOT NULL,
    [ID_VALUTATORE]           INT NOT NULL,
    [PRESENTE]                BIT CONSTRAINT [DF_PROGETTO_VALUTATORI_PRESENTE] DEFAULT ((1)) NOT NULL,
    [ORDINE]                  INT NOT NULL,
    CONSTRAINT [PK_PROGETTO_VALUTATORI] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PROGETTO_VALUTATORI_BANDO_VALUTATORI] FOREIGN KEY ([ID_VALUTATORE]) REFERENCES [dbo].[BANDO_VALUTATORI] ([ID_VALUTATORE]),
    CONSTRAINT [FK_PROGETTO_VALUTATORI_PROGETTO_VALUTAZIONE] FOREIGN KEY ([ID_PROGETTO_VALUTAZIONE]) REFERENCES [dbo].[PROGETTO_VALUTAZIONE] ([ID])
);

