CREATE TABLE [dbo].[PROGETTO_STORICO] (
    [ID]                     INT           IDENTITY (1, 1) NOT NULL,
    [ID_PROGETTO]            INT           NOT NULL,
    [COD_STATO]              CHAR (1)      NOT NULL,
    [DATA]                   DATETIME      NOT NULL,
    [OPERATORE]              INT           NOT NULL,
    [SEGNATURA]              VARCHAR (100) NULL,
    [REVISIONE]              BIT           CONSTRAINT [DF_PROGETTO_STORICO_REVISIONE] DEFAULT ((0)) NOT NULL,
    [RIESAME]                BIT           CONSTRAINT [DF_PROGETTO_STORICO_RIESAME] DEFAULT ((0)) NOT NULL,
    [RICORSO]                BIT           CONSTRAINT [DF_PROGETTO_STORICO_RICORSO] DEFAULT ((0)) NOT NULL,
    [DATA_RI]                DATETIME      NULL,
    [OPERATORE_RI]           INT           NULL,
    [SEGNATURA_RI]           VARCHAR (100) NULL,
    [RIAPERTURA_PROVINCIALE] BIT           CONSTRAINT [DF_PROGETTO_STORICO_RIAPERTURA_PROVINCIALE] DEFAULT ((0)) NOT NULL,
    [ID_ATTO]                INT           NULL,
    CONSTRAINT [PK_PROGETTO_STORICO] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_PROGETTO_STORICO_PROGETTO] FOREIGN KEY ([ID_PROGETTO]) REFERENCES [dbo].[PROGETTO] ([ID_PROGETTO]),
    CONSTRAINT [FK_PROGETTO_STORICO_STATO_PROGETTO] FOREIGN KEY ([COD_STATO]) REFERENCES [dbo].[STATO_PROGETTO] ([COD_STATO])
);


GO
CREATE NONCLUSTERED INDEX [IX_PROGETTO_STORICO]
    ON [dbo].[PROGETTO_STORICO]([ID_PROGETTO] ASC)
    INCLUDE([COD_STATO], [DATA]) WITH (FILLFACTOR = 80);

