CREATE TABLE [dbo].[PROGETTO_SEGNATURE_ANNULLATE] (
    [ID]                INT           IDENTITY (1, 1) NOT NULL,
    [ID_PROGETTO]       INT           NOT NULL,
    [COD_TIPO]          CHAR (3)      NOT NULL,
    [DATA]              DATETIME      NULL,
    [OPERATORE]         VARCHAR (16)  NULL,
    [SEGNATURA]         VARCHAR (100) NULL,
    [RIAPRI_DOMANDA]    BIT           NULL,
    [MOTIVAZIONE]       NTEXT         NULL,
    [DATA_ANNULLAMENTO] DATETIME      CONSTRAINT [DF_PROGETTO_SEGNATURE_ANNULLATE_DATA_ANNULLAMENTO] DEFAULT (getdate()) NULL,
    CONSTRAINT [PK_PROGETTO_SEGNATURE_ANNULLATE] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 80)
);

