CREATE TABLE [dbo].[QUADRO_DOMANDA] (
    [ID_QUADRO]     INT           IDENTITY (1, 1) NOT NULL,
    [DENOMINAZIONE] VARCHAR (70)  NOT NULL,
    [DESCRIZIONE]   VARCHAR (500) NULL,
    [METODO_REPORT] VARCHAR (50)  NULL,
    CONSTRAINT [PK_QUADRO_DOMANDA] PRIMARY KEY CLUSTERED ([ID_QUADRO] ASC) WITH (FILLFACTOR = 100)
);

