CREATE TABLE [dbo].[QUADRI_BUSINESS_PLAN] (
    [ID_QUADRO]   INT            IDENTITY (1, 1) NOT NULL,
    [DESCRIZIONE] VARCHAR (1000) NULL,
    [URL]         VARCHAR (80)   NULL,
    [TITOLO]      VARCHAR (255)  NULL,
    [ORDINE]      INT            NULL,
    [DOMANDA]     BIT            NULL,
    CONSTRAINT [PK_QUADRI_BUSINESS_PLAN] PRIMARY KEY CLUSTERED ([ID_QUADRO] ASC) WITH (FILLFACTOR = 80)
);

