CREATE TABLE [dbo].[REVOCA](
	[ID_REVOCA] [int] IDENTITY(1,1) NOT NULL,
	[ID_PROGETTO] [int] NULL,
	[ID_IMPRESA] [int] NULL,
	[ORIGINE] [varchar](255) NULL,
	[NOTE] [varchar](max) NULL,
	[IMPORTO_REVOCA] [decimal](15, 2) NULL,
	[NUMERO_ATTO] [varchar](255) NULL,
	[DATA_ATTO] [datetime] NULL,
	[RECUPERO_BENEFICIARIO] [bit] NULL,
	[REVOCA_CONTRIBUTO] [bit] NULL,
	[IMPORTO_DA_RECUPERARE] [decimal](15, 2) NULL,
	[INTERESSI_LEGALI] [decimal](15, 2) NULL,
	[SPESE_NOTIFICA] [decimal](15, 2) NULL,
	[SANZIONI] [decimal](15, 2) NULL,
	[TOTALE] [decimal](15, 2) NULL,
	[IMPORTO_RECUPERATO] [decimal](15, 2) NULL,
	[IRRECUPERABILE] [bit] NULL,
	[DATA_IRRECUPERABILE] [datetime] NULL,
	[IMPORTO_IRRECUPERABILE] [decimal](15, 2) NULL,
	[DATA_MODIFICA] [datetime] NULL,
	[RECUPERATO] [bit] NULL,
	[STABILITA] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_REVOCA] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[REVOCA] ADD  DEFAULT (getdate()) FOR [DATA_MODIFICA]
GO