CREATE TABLE RNA_FORMA_GIURIDICA_MATCH(
COD_FORMA_GIURIDICA_RNA VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES RNA_FORMA_GIURIDICA(COD_FORMA_GIURIDICA),
COD_ISTAT VARCHAR (10) NOT NULL FOREIGN KEY REFERENCES FORMA_GIURIDICA(COD_ISTAT),
PRIMARY KEY (COD_FORMA_GIURIDICA_RNA,COD_ISTAT)
)