CREATE TABLE RNA_OBIETTIVI (
ID_OBIETTIVO INT IDENTITY(1,1) NOT NULL,
CODICE_REGOLAMENTO VARCHAR(30) NULL,
REGOLAMENTO VARCHAR(MAX) NULL,
COD_OBIETTIVO VARCHAR(20) NULL,
MACRO_OBIETTIVO VARCHAR(500) NULL,
OBIETTIVO VARCHAR(500) NULL,
 CONSTRAINT OBIETTIVO_PK PRIMARY KEY CLUSTERED 
(
	ID_OBIETTIVO ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY];