CREATE TABLE [dbo].[RNA_PROGETTO_COR](
	[ID_RNA_PROGETTO_COR] [int] IDENTITY(1,1) NOT NULL,
	[ID_PROGETTO] [int] NULL,
	[ID_PROGETTO_RNA] [varchar](255) NULL,
	[ID_RICHIESTA] [varchar](50) NULL,
	[ID_IMPRESA] [int] NULL,
	[ID_FISCALE_IMPRESA] [varchar](16) NULL,
	[ID_OPERATORE_ASSEGNAZIONE_COR] [int] NULL,
	[COR] [varchar](50) NULL,
	[STATO_CONCESSIONE] [varchar](50) NULL,
	[DATA_ASSEGNAZIONE_COR] [datetime] NULL,
	[CONFERMATO] [bit] NULL,
	[ID_OPERATORE_CONFERMA_CONCESSIONE] [int] NULL,
	[DATA_CONFERMA_CONCESSIONE] [datetime] NULL,
	[ANNULLATO] [bit] NULL,
	[ID_OPERATORE_ANNULLAMENTO] [int] NULL,
	[DATA_ANNULLAMENTO] [datetime] NULL,
	[DATA_INSERIMENTO] [datetime] NULL,
	[DATA_AGGIORNAMENTO] [datetime] NULL,
 CONSTRAINT [PK_RNA_PROGETTO_COR] PRIMARY KEY CLUSTERED 
(
	[ID_RNA_PROGETTO_COR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[RNA_PROGETTO_COR] ADD  CONSTRAINT [DF_RNA_PROGETTO_COR_CONFERMATO]  DEFAULT ((0)) FOR [CONFERMATO]
GO

ALTER TABLE [dbo].[RNA_PROGETTO_COR] ADD  CONSTRAINT [DF_RNA_PROGETTO_COR_ANNULLATO]  DEFAULT ((0)) FOR [ANNULLATO]
GO

ALTER TABLE [dbo].[RNA_PROGETTO_COR] ADD  CONSTRAINT [DF_RNA_PROGETTO_COR_DATA_INSERIMENTO]  DEFAULT (getdate()) FOR [DATA_INSERIMENTO]
GO

ALTER TABLE [dbo].[RNA_PROGETTO_COR] ADD  CONSTRAINT [DF_RNA_PROGETTO_COR_DATA_AGGIORNAMENTO]  DEFAULT (getdate()) FOR [DATA_AGGIORNAMENTO]
GO

