CREATE TABLE [dbo].[RNA_LOG_VISURE](
	[ID_RNA_LOG_VISURA] [int] IDENTITY(1,1) NOT NULL,
	[ID_PROGETTO] [int] NULL,
	[ID_IMPRESA] [int] NULL,
	[ID_FISCALE_IMPRESA] [varchar](16) NULL,
	[ID_RICHIESTA] [varchar](50) NULL,
	[TIPO_VISURA] [varchar](50) NULL,
	[CODICE_ESITO] [int] NULL,
	[DESCRIZIONE_ESITO] [nvarchar](max) NULL,
	[DATA_RICHIESTA] [datetime] NULL,
	[CODICE_STATO_RICHIESTA] [int] NULL,
	[DESCRIZIONE_STATO_RICHIESTA] [nvarchar](max) NULL,
	[DATA_STATO_RICHIESTA] [datetime] NULL,
	[ID_OPERATORE] [int] NULL,
	[DATA_INSERIMENTO] [datetime] NULL,
	[DATA_AGGIORNAMENTO] [datetime] NULL,
	[PAYLOAD] [VARBINARY](MAX) NULL,
 CONSTRAINT [PK_RNA_LOG_VISURE] PRIMARY KEY CLUSTERED 
(
	[ID_RNA_LOG_VISURA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[RNA_LOG_VISURE] ADD  CONSTRAINT [DF_RNA_LOG_VISURE_DATA_INSERIMENTO]  DEFAULT (getdate()) FOR [DATA_INSERIMENTO]
GO

ALTER TABLE [dbo].[RNA_LOG_VISURE] ADD  CONSTRAINT [DF_RNA_LOG_VISURE_DATA_AGGIORNAMENTO]  DEFAULT (getdate()) FOR [DATA_AGGIORNAMENTO]
GO


