CREATE TABLE RNA_STRUMENTI_X_COMPONENTI(
ID_STRUMENTI_X_COMPONENTI INT IDENTITY(1,1) NOT NULL,
ID_COMPONENTI_X_CODIFICA INT NOT NULL FOREIGN KEY REFERENCES RNA_COMPONENTI_X_CODIFICA(ID_COMPONENTI_X_CODIFICA),
COD_TIPO_STRUMENTO_AIUTO INT NULL FOREIGN KEY REFERENCES RNA_STRUMENTI_DI_AIUTO(COD_TIPO_STRUMENTO_AIUTO),
INTENSITA_STRUMENTO DECIMAL(15,12) NULL,
CONSTRAINT ID_RNA_CODIFICA_INV_PK PRIMARY KEY CLUSTERED 
(
	ID_STRUMENTI_X_COMPONENTI ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]