CREATE TABLE RNA_FORMA_GIURIDICA (
COD_FORMA_GIURIDICA VARCHAR(10) NOT NULL,
DESCRIZIONE VARCHAR (300) NULL
CONSTRAINT FORMA_GIURIDICA_PK PRIMARY KEY CLUSTERED 
(
	COD_FORMA_GIURIDICA ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]