CREATE TABLE [dbo].[RNA_ENTI](
	[ID_RNA_ENTE] [int] IDENTITY(1,1) NOT NULL,
	[COD_ENTE] [varchar](10) NULL,
	[USERNAME] [nvarchar](250) NULL,
	[PASSWORD_CRYPTED] [nvarchar](max) NULL,
	[ABILITATO] [bit] NULL,
	[CREDENZIALI_PRODUZIONE] [bit] NULL,
	[COD_ENTE_ACCOUNT] [varchar](10) NULL,
	[DESCRIZIONE_ACCOUNT] [varchar](255) NULL,
	[DATA_PASSWORD] [datetime] NULL,
 CONSTRAINT [ID_RNA_ENTE_PK] PRIMARY KEY CLUSTERED 
(
	[ID_RNA_ENTE] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[RNA_ENTI] ADD  DEFAULT ((0)) FOR [ABILITATO]
GO

ALTER TABLE [dbo].[RNA_ENTI] ADD  DEFAULT ((0)) FOR [CREDENZIALI_PRODUZIONE]