CREATE TABLE RNA_TIPO_COSTO_AMMISSIBILE (
COD_TIPO_SPESA INT NOT NULL,
MACRO_SPESA VARCHAR(500) NULL,
SPESA VARCHAR (500) NULL
CONSTRAINT TIPO_COSTO_AMMISSIBILE_PK PRIMARY KEY CLUSTERED 
(
	COD_TIPO_SPESA ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]