CREATE TABLE [dbo].[RUOLO] (
    [COD_RUOLO]       CHAR (1)      NOT NULL,
    [DESCRIZIONE]     VARCHAR (255) NOT NULL,
    [POTERE_DI_FIRMA] BIT           CONSTRAINT [DF_RUOLO_POTERE_DI_FIRMA] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_RUOLO] PRIMARY KEY CLUSTERED ([COD_RUOLO] ASC) WITH (FILLFACTOR = 100)
);

