CREATE TABLE [dbo].[SCHEDA_X_PRIORITA] (
    [ID_SCHEDA_VALUTAZIONE] INT             NOT NULL,
    [ID_PRIORITA]           INT             NOT NULL,
    [ORDINE]                INT             CONSTRAINT [DF_SCHEDA_X_INDICATORI_ORDINE_PRIORITA] DEFAULT ((0)) NULL,
    [PESO]                  DECIMAL (10, 2) NULL,
    [AIUTO_ADDIZIONALE]     DECIMAL (10, 2) NULL,
    [SELEZIONABILE]         BIT             NULL,
    [IS_MAX]                BIT             NULL,
    CONSTRAINT [PK_SCHEDA_X_INDICATORI_1] PRIMARY KEY CLUSTERED ([ID_SCHEDA_VALUTAZIONE] ASC, [ID_PRIORITA] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_SCHEDA_X_PRIORITA_PRIORITA] FOREIGN KEY ([ID_PRIORITA]) REFERENCES [dbo].[PRIORITA] ([ID_PRIORITA]),
    CONSTRAINT [FK_SCHEDA_X_PRIORITA_SCHEDA_VALUTAZIONE] FOREIGN KEY ([ID_SCHEDA_VALUTAZIONE]) REFERENCES [dbo].[SCHEDA_VALUTAZIONE] ([ID_SCHEDA_VALUTAZIONE])
);

