CREATE TABLE [dbo].[STATO_PROGETTO] (
    [COD_STATO]   CHAR (1)                  NOT NULL,
    [DESCRIZIONE] [dbo].[DESCRIZIONE_BREVE] NOT NULL,
    [COD_FASE]    CHAR (1)                  NULL,
    [ORDINE]      INT                       NULL,
    CONSTRAINT [PK_TIPO_STATO] PRIMARY KEY CLUSTERED ([COD_STATO] ASC) WITH (FILLFACTOR = 100),
    CONSTRAINT [FK_STATO_PROGETTO_FASI_PROCEDURALI] FOREIGN KEY ([COD_FASE]) REFERENCES [dbo].[FASI_PROCEDURALI] ([COD_FASE])
);

