CREATE TABLE [dbo].[STEP_X_BANDO] (
    [ID_BANDO]      INT      NOT NULL,
    [ID_CHECK_LIST] INT      NOT NULL,
    [COD_FASE]      CHAR (1) NOT NULL,
    CONSTRAINT [PK_STEP_X_BANDO_1] PRIMARY KEY CLUSTERED ([ID_BANDO] ASC, [ID_CHECK_LIST] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_STEP_X_BANDO_BANDO] FOREIGN KEY ([ID_BANDO]) REFERENCES [dbo].[BANDO] ([ID_BANDO]),
    CONSTRAINT [FK_STEP_X_BANDO_CHECK_LIST] FOREIGN KEY ([ID_CHECK_LIST]) REFERENCES [dbo].[CHECK_LIST] ([ID_CHECK_LIST]),
    CONSTRAINT [FK_STEP_X_BANDO_FASI_PROCEDURALI] FOREIGN KEY ([COD_FASE]) REFERENCES [dbo].[FASI_PROCEDURALI] ([COD_FASE])
);

