CREATE TABLE [dbo].[SUAP] (
    [ID]                   INT           IDENTITY (1, 1) NOT NULL,
    [SPORTELLO]            VARCHAR (255) NOT NULL,
    [COD_BELFIORE]         CHAR (4)      NOT NULL,
    [PEC]                  VARCHAR (255) NOT NULL,
    [COGNOME_RESPONSABILE] VARCHAR (255) NOT NULL,
    [NOME_RESPONSABILE]    VARCHAR (255) NOT NULL,
    [ATTIVO]               BIT           CONSTRAINT [DF_SUAP_ATTIVO] DEFAULT ((1)) NOT NULL,
    [DATA_INIZIO_VALIDITA] DATETIME      NOT NULL,
    [ID_OPERATORE_INIZIO]  INT           NOT NULL,
    [DATA_FINE_VALIDITA]   DATETIME      NULL,
    [ID_OPERATORE_FINE]    INT           NULL,
    CONSTRAINT [PK_SUAP] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 100)
);

