CREATE TABLE [dbo].[TIPO_ALLEGATO] (
    [CODICE]      CHAR (1)      NOT NULL,
    [DESCRIZIONE] VARCHAR (255) NOT NULL,
    [ATTIVO]      BIT           CONSTRAINT [DF_TIPO_ALLEGATO_ATTIVO] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_TIPO_ALLEGATO] PRIMARY KEY CLUSTERED ([CODICE] ASC) WITH (FILLFACTOR = 100)
);

