CREATE TABLE [dbo].[TIPO_CONTRATTI_CONDUZIONE] (
    [COD_TIPO_CONTRATTO] INT           NOT NULL,
    [DESCRIZIONE]        VARCHAR (500) NULL,
    CONSTRAINT [PK_TIPO_CONTRATTI_CONDUZIONE] PRIMARY KEY CLUSTERED ([COD_TIPO_CONTRATTO] ASC) WITH (FILLFACTOR = 100)
);

