CREATE TABLE [dbo].[TIPO_TEMA_PRIORITARIO] (
    [COD_TEMA_PRIORITARIO] CHAR (2)      NOT NULL,
    [Descrizione]          VARCHAR (250) NOT NULL,
    CONSTRAINT [PK_TEMA_PRIORITARIO] PRIMARY KEY CLUSTERED ([COD_TEMA_PRIORITARIO] ASC)
);

