CREATE TABLE [dbo].[TIPO_POLIZZA] (
    [COD_TIPO_POLIZZA] CHAR (3)      NOT NULL,
    [DESCRIZIONE]      VARCHAR (255) NOT NULL,
    CONSTRAINT [PK_TIPO_POLIZZA] PRIMARY KEY CLUSTERED ([COD_TIPO_POLIZZA] ASC) WITH (FILLFACTOR = 100)
);

