CREATE TABLE [dbo].[TIPO_RIDUZIONE_SPESE] (
    [CODICE]             CHAR (3)     NOT NULL,
    [DESCRIZIONE]        VARCHAR (50) NOT NULL,
    [ATTIVO]             BIT          CONSTRAINT [DF_TIPO_RIDUZIONE_SPESE_ATTIVO] DEFAULT ((0)) NOT NULL,
    [LAVORO_IN_ECONOMIA] BIT          CONSTRAINT [DF_TIPO_RIDUZIONE_SPESE_LAVORO_IN_ECONOMIA] DEFAULT ((0)) NOT NULL,
    [ORDINE]             INT          NULL,
    CONSTRAINT [PK_TIPO_RIDUZIONE_SPESE] PRIMARY KEY CLUSTERED ([CODICE] ASC) WITH (FILLFACTOR = 100)
);

