CREATE TABLE [dbo].[TIPO_SANZIONI_PARAMETRI] (
    [CODICE]                INT           IDENTITY (1, 1) NOT NULL,
    [COD_TIPO_SANZIONE]     VARCHAR (10)  NOT NULL,
    [DESCRIZIONE]           VARCHAR (500) NOT NULL,
    [NON_COMPORTA_SANZIONE] BIT           CONSTRAINT [DF_TIPO_SANZIONI_PARAMETRI_NON_CONPORTA_SANZIONE] DEFAULT ((0)) NOT NULL,
    [DURATA]                BIT           CONSTRAINT [DF_TIPO_SANZIONI_PARAMETRI_DURATA] DEFAULT ((0)) NOT NULL,
    [GRAVITA]               BIT           CONSTRAINT [DF_TIPO_SANZIONI_PARAMETRI_GRAVITA] DEFAULT ((0)) NOT NULL,
    [ENTITA]                BIT           CONSTRAINT [DF_TIPO_SANZIONI_PARAMETRI_ENTITA] DEFAULT ((0)) NOT NULL,
    [CLASSE_VIOLAZIONE]     INT           NOT NULL,
    [TOOLTIP]               VARCHAR (255) NULL,
    CONSTRAINT [PK_TIPO_SANZIONI_PARAMETRI_1] PRIMARY KEY CLUSTERED ([CODICE] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_TIPO_SANZIONI_PARAMETRI_TIPO_SANZIONI] FOREIGN KEY ([COD_TIPO_SANZIONE]) REFERENCES [dbo].[TIPO_SANZIONI] ([COD_TIPO])
);

