CREATE TABLE [dbo].[TIPO_SEGNATURA] (
    [COD_TIPO]               CHAR (3)      NOT NULL,
    [DESCRIZIONE]            VARCHAR (500) NULL,
    [GIORNI_PREVISTI]        INT           CONSTRAINT [DF_TIPO_SEGNATURA_GIORNI_PREVISTI] DEFAULT ((0)) NOT NULL,
    [FLAG_DOMANDA_AIUTO]     BIT           CONSTRAINT [DF_TIPO_SEGNATURA_FLAG_DOMANDA_AIUTO] DEFAULT ((0)) NOT NULL,
    [FLAG_DOMANDA_PAGAMENTO] BIT           CONSTRAINT [DF_TIPO_SEGNATURA_FLAG_DOMANDA_PAGAMENTO] DEFAULT ((0)) NOT NULL,
    [FLAG_VARIANTE]          BIT           CONSTRAINT [DF_TIPO_SEGNATURA_FLAG_VARIANTE] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_TIPO_SEGNATURA] PRIMARY KEY CLUSTERED ([COD_TIPO] ASC) WITH (FILLFACTOR = 100)
);

