CREATE TABLE [dbo].[TIPO_COLLABORAZIONE] (
    [COD_TIPO_COLLABORAZIONE] INT           NOT NULL,
    [DESCRIZIONE]             VARCHAR (200) NULL,
    CONSTRAINT [PK_TIPO_COLLABORAZIONE] PRIMARY KEY CLUSTERED ([COD_TIPO_COLLABORAZIONE] ASC) WITH (FILLFACTOR = 80)
);

