CREATE TABLE [dbo].[TIPO_SEDE] (
    [COD_TIPO_SEDE] CHAR (1)            NOT NULL,
    [DESCRIZIONE]   [dbo].[DESCRIZIONE] NULL,
    CONSTRAINT [PK_TIPO_SEDE] PRIMARY KEY CLUSTERED ([COD_TIPO_SEDE] ASC) WITH (FILLFACTOR = 100)
);

