CREATE TABLE [dbo].[TIPO_MANDATI_IMPRESA] (
    [CODICE]      CHAR (3)     NOT NULL,
    [DESCRIZIONE] VARCHAR (50) NOT NULL,
    [ATTIVO]      BIT          NOT NULL,
    CONSTRAINT [PK_TIPO_MADATI_IMPRESA] PRIMARY KEY CLUSTERED ([CODICE] ASC) WITH (FILLFACTOR = 100)
);

