CREATE TABLE [dbo].[TIPO_GIUSTIFICATIVO] (
    [COD_TIPO]           CHAR (3)      NOT NULL,
    [DESCRIZIONE]        VARCHAR (100) NOT NULL,
    [DI_SPESA]           BIT           NOT NULL,
    [DI_PAGAMENTO]       BIT           NOT NULL,
    [LAVORI_IN_ECONOMIA] BIT           CONSTRAINT [DF_TIPO_GIUSTIFICATIVO_LAVORI_IN_ECONOMIA] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_TIPO_GIUSTIFICATIVO] PRIMARY KEY CLUSTERED ([COD_TIPO] ASC) WITH (FILLFACTOR = 100)
);

