CREATE TABLE [dbo].[UFFICI_DECENTRATI] (
    [CODICE]             CHAR (6)      NOT NULL,
    [DENOMINAZIONE]      VARCHAR (255) NOT NULL,
    [PROVINCIA]          CHAR (2)      NOT NULL,
    [PEC]                VARCHAR (255) NOT NULL,
    [ATTIVO]             BIT           CONSTRAINT [DF_UFFICI_DECENTRATI_ATTIVO] DEFAULT ((1)) NOT NULL,
    [DATA_FINE_VALIDITA] DATETIME      NULL,
    CONSTRAINT [PK_UFFICI_DECENTRATI] PRIMARY KEY CLUSTERED ([CODICE] ASC) WITH (FILLFACTOR = 100)
);

