CREATE TABLE [dbo].[VALORI_PRIORITA] (
    [ID_VALORE]   INT             IDENTITY (1, 1) NOT NULL,
    [ID_PRIORITA] INT             NULL,
    [DESCRIZIONE] VARCHAR (500)   NULL,
    [CODICE]      VARCHAR (10)    NULL,
    [PUNTEGGIO]   DECIMAL (10, 2) NULL,
    CONSTRAINT [PK_VALORI_PRIORITA] PRIMARY KEY CLUSTERED ([ID_VALORE] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_VALORI_PRIORITA_PRIORITA] FOREIGN KEY ([ID_PRIORITA]) REFERENCES [dbo].[PRIORITA] ([ID_PRIORITA])
);

