CREATE TABLE [dbo].[VARIANTI_ALLEGATI] (
    [ID_ALLEGATO]         INT           IDENTITY (1, 1) NOT NULL,
    [ID_VARIANTE]         INT           NOT NULL,
    [DESCRIZIONE]         VARCHAR (255) NULL,
    [COD_TIPO_DOCUMENTO]  VARCHAR (10)  NOT NULL,
    [ID_FILE]             INT           NULL,
    [COD_ENTE_EMETTITORE] VARCHAR (10)  NULL,
    [ID_COMUNE]           INT           NULL,
    [NUMERO]              VARCHAR (20)  NULL,
    [DATA]                DATETIME      NULL,
    [COD_ESITO]           CHAR (2)      NULL,
    [NOTE_ISTRUTTORE]     NTEXT         NULL,
    CONSTRAINT [PK_VARIANTI_ALLEGATI] PRIMARY KEY CLUSTERED ([ID_ALLEGATO] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_VARIANTI_ALLEGATI_ESITI_STEP] FOREIGN KEY ([COD_ESITO]) REFERENCES [dbo].[ESITI_STEP] ([COD_ESITO]),
    CONSTRAINT [FK_VARIANTI_ALLEGATI_VARIANTI] FOREIGN KEY ([ID_VARIANTE]) REFERENCES [dbo].[VARIANTI] ([ID_VARIANTE])
);

