CREATE TABLE [dbo].[VARIANTI_X_PRIORITA] (
    [ID_VARIANTE]      INT             NOT NULL,
    [ID_PRIORITA]      INT             NOT NULL,
    [ID_PROGETTO]      INT             NULL,
    [PUNTEGGIO]        DECIMAL (10, 6) NULL,
    [DATA_VALUTAZIONE] DATETIME        NULL,
    [OPERATORE]        VARCHAR (16)    NULL,
    [FLAG_DEFINITIVO]  BIT             CONSTRAINT [DF_VARIANTI_X_PRIORITA_FLAG_DEFINITIVO] DEFAULT ((0)) NULL,
    CONSTRAINT [PK_VARIANTI_X_PRIORITA] PRIMARY KEY CLUSTERED ([ID_VARIANTE] ASC, [ID_PRIORITA] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_VARIANTI_X_PRIORITA_VARIANTI] FOREIGN KEY ([ID_VARIANTE]) REFERENCES [dbo].[VARIANTI] ([ID_VARIANTE])
);

