CREATE TABLE [dbo].[VARIANTI_ESITI_REQUISITI] (
    [ID_VARIANTE]              INT          NOT NULL,
    [ID_REQUISITO]             INT          NOT NULL,
    [COD_ESITO]                CHAR (2)     NULL,
    [DATA]                     DATETIME     NULL,
    [CF_OPERATORE]             VARCHAR (16) NULL,
    [COD_ESITO_ISTRUTTORE]     CHAR (2)     NULL,
    [DATA_VALUTAZIONE]         DATETIME     NULL,
    [ISTRUTTORE]               VARCHAR (16) NULL,
    [NOTE]                     NTEXT        NULL,
    [ESCLUDI_DA_COMUNICAZIONE] BIT          CONSTRAINT [DF_VARIANTI_ESITI_STEP_ESCLUDI_DA_COMUNICAZIONE] DEFAULT ((0)) NULL,
    CONSTRAINT [PK_VARIANTI_ESITI_STEP] PRIMARY KEY CLUSTERED ([ID_VARIANTE] ASC, [ID_REQUISITO] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_VARIANTI_ESITI_STEP_REQUISITI_VARIANTE] FOREIGN KEY ([ID_REQUISITO]) REFERENCES [dbo].[REQUISITI_VARIANTE] ([ID_REQUISITO]),
    CONSTRAINT [FK_VARIANTI_ESITI_STEP_VARIANTI] FOREIGN KEY ([ID_VARIANTE]) REFERENCES [dbo].[VARIANTI] ([ID_VARIANTE])
);

