CREATE TABLE [dbo].[VARIANTI_SEGNATURE_ANNULLATE] (
    [ID_ANNULLAMENTO]   INT           IDENTITY (1, 1) NOT NULL,
    [ID_VARIANTE]       INT           NOT NULL,
    [COD_TIPO]          CHAR (3)      NOT NULL,
    [SEGNATURA]         VARCHAR (100) NOT NULL,
    [DATA]              DATETIME      NOT NULL,
    [OPERATORE]         VARCHAR (16)  NOT NULL,
    [MOTIVAZIONE]       NTEXT         NULL,
    [DATA_ANNULLAMENTO] DATETIME      CONSTRAINT [DF_VARIANTI_SEGNATURE_ANNULLATE_DATA_ANNULLAMENTO] DEFAULT (getdate()) NULL,
    CONSTRAINT [PK_VARIANTI_SEGNATURE_ANNULLATE] PRIMARY KEY CLUSTERED ([ID_ANNULLAMENTO] ASC) WITH (FILLFACTOR = 80)
);

