CREATE TABLE [dbo].[VARIANTI_SEGNATURE] (
    [ID_VARIANTE]     INT           NOT NULL,
    [COD_TIPO]        CHAR (3)      NOT NULL,
    [SEGNATURA]       VARCHAR (100) NOT NULL,
    [DATA]            DATETIME      NOT NULL,
    [OPERATORE]       VARCHAR (16)  NOT NULL,
    [MOTIVAZIONE]     NTEXT         NULL,
    [RIAPRI_VARIANTE] BIT           CONSTRAINT [DF_VARIANTI_SEGNATURE_RIAPRI_VARIANTE] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_VARIANTI_SEGNATURE] PRIMARY KEY CLUSTERED ([ID_VARIANTE] ASC, [COD_TIPO] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_VARIANTI_SEGNATURE_VARIANTI] FOREIGN KEY ([ID_VARIANTE]) REFERENCES [dbo].[VARIANTI] ([ID_VARIANTE])
);

