CREATE TABLE [dbo].[VERBALE_VALUTAZIONE_DOMANDA] (
    [COD_ENTE]            VARCHAR (50)  NOT NULL,
    [DECRETO_1]           VARCHAR (50)  NULL,
    [DECRETO_2]           VARCHAR (50)  NULL,
    [TESTO_X_GRADUATORIA] VARCHAR (150) NOT NULL
);

