CREATE TABLE [dbo].[VISITE_AZIENDALI] (
    [ID_VISITA]            INT           IDENTITY (1, 1) NOT NULL,
    [ID_DOMANDA_PAGAMENTO] INT           NULL,
    [ID_DOMANDA_EROA]      INT           NULL,
    [ID_IMPRESA]           INT           NOT NULL,
    [COD_TIPO]             CHAR (3)      NOT NULL,
    [DATA_APERTURA]        DATETIME      NOT NULL,
    [OPERATORE_APERTURA]   VARCHAR (16)  NOT NULL,
    [CONTROLLO_CONCLUSO]   BIT           CONSTRAINT [DF_VISITE_AZIENDALI_CONTROLLO_CONCLUSO] DEFAULT ((0)) NOT NULL,
    [DATA_CHIUSURA]        DATETIME      NULL,
    [OPERATORE_CHIUSURA]   VARCHAR (16)  NULL,
    [SEGNATURA_VERBALE]    VARCHAR (100) NULL,
    CONSTRAINT [PK_VISITE_AZIENDALI] PRIMARY KEY CLUSTERED ([ID_VISITA] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_VISITE_AZIENDALI_DOMANDA_DI_PAGAMENTO] FOREIGN KEY ([ID_DOMANDA_PAGAMENTO]) REFERENCES [dbo].[DOMANDA_DI_PAGAMENTO] ([ID_DOMANDA_PAGAMENTO]),
    CONSTRAINT [FK_VISITE_AZIENDALI_TIPO_VISITA_AZIENDALE] FOREIGN KEY ([COD_TIPO]) REFERENCES [dbo].[TIPO_VISITA_AZIENDALE] ([COD_TIPO])
);

