CREATE TABLE [dbo].[VLD_CHECK_LIST_STEP] (
    [ID_VLD_CHECK_LIST]   INT NOT NULL,
    [ID_VLD_STEP]         INT NOT NULL,
    [ORDINE]              INT NULL,
    [OBBLIGATORIO]        BIT CONSTRAINT [DF_VLD_CHECK_LIST_STEP_OBBLIGATORIO] DEFAULT ((0)) NOT NULL,
    [INCLUDI_VERBALE_VIS] BIT CONSTRAINT [DF_VLD_CHECK_LIST_STEP_INCLUDI_VERBALE_VIS] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_VLD_CHECK_LIST_STEP] PRIMARY KEY CLUSTERED ([ID_VLD_CHECK_LIST] ASC, [ID_VLD_STEP] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_VLD_CHECK_LIST_STEP_VLD_CHECK_LIST] FOREIGN KEY ([ID_VLD_CHECK_LIST]) REFERENCES [dbo].[VLD_CHECK_LIST] ([ID]),
    CONSTRAINT [FK_VLD_CHECK_LIST_STEP_VLD_STEP] FOREIGN KEY ([ID_VLD_STEP]) REFERENCES [dbo].[VLD_STEP] ([ID])
);

