CREATE TABLE [dbo].[VLD_CHECK_LIST] (
    [ID]                  INT           IDENTITY (1, 1) NOT NULL,
    [DESCRIZIONE]         VARCHAR (255) NOT NULL,
    [COD_TIPO_DPAGAMENTO] CHAR (3)      NOT NULL,
    [TPAPPALTO]           VARCHAR (5)   NOT NULL,
    [DATA_MODIFICA]       DATETIME      NOT NULL,
    [OPERATORE]           INT           NOT NULL,
    CONSTRAINT [PK_VLD_CHECK_LIST] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_VLD_CHECK_LIST_TIPO_DOMANDA_PAGAMENTO] FOREIGN KEY ([COD_TIPO_DPAGAMENTO]) REFERENCES [dbo].[TIPO_DOMANDA_PAGAMENTO] ([COD_TIPO])
);

