CREATE TABLE [dbo].[WORKFLOW_PAGAMENTO] (
    [COD_TIPO]     CHAR (3) NOT NULL,
    [COD_WORKFLOW] CHAR (5) NOT NULL,
    [ORDINE]       INT      NOT NULL,
    [OBBLIGATORIO] BIT      CONSTRAINT [DF_BANDO_WORKFLOW_PAGAMENTO_OBBLIGATORIO] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_BANDO_WORKFLOW_PAGAMENTO_1] PRIMARY KEY CLUSTERED ([COD_TIPO] ASC, [COD_WORKFLOW] ASC) WITH (FILLFACTOR = 100),
    CONSTRAINT [FK_BANDO_WORKFLOW_PAGAMENTO_WORK_FLOW] FOREIGN KEY ([COD_WORKFLOW]) REFERENCES [dbo].[WORKFLOW] ([COD_WORKFLOW]),
    CONSTRAINT [FK_WORKFLOW_PAGAMENTO_TIPO_DOMANDA_PAGAMENTO] FOREIGN KEY ([COD_TIPO]) REFERENCES [dbo].[TIPO_DOMANDA_PAGAMENTO] ([COD_TIPO])
);

