CREATE TABLE [dbo].[WORKFLOW_PROCEDURE] (
    [COD_TIPO_PROCEDURA] CHAR (3) NOT NULL,
    [COD_WORKFLOW]       CHAR (5) NOT NULL,
    [ORDINE]             INT      NOT NULL,
    [OBBLIGATORIO]       BIT      CONSTRAINT [DF_WORKFLOW_PROCEDURE_OBBLIGATORIO] DEFAULT ((0)) NOT NULL,
    [NOTE]               NTEXT    NULL,
    CONSTRAINT [PK_WORKFLOW_PROCEDURE] PRIMARY KEY CLUSTERED ([COD_TIPO_PROCEDURA] ASC, [COD_WORKFLOW] ASC) WITH (FILLFACTOR = 100)
);

