CREATE TABLE [dbo].[zDIMENSIONI_ESTRAZIONI_IR] (
    [ID_ESTRAZIONE_IR]  INT             IDENTITY (1, 1) NOT NULL,
    [CODICE_PSR]        VARCHAR (20)    NOT NULL,
    [ID_DIMENSIONE]     INT             NOT NULL,
    [DATA_INIZIO]       DATETIME        NOT NULL,
    [DATA_FINE]         DATETIME        NOT NULL,
    [VALORE_BASE]       DECIMAL (18, 2) NULL,
    [VALORE_OBBIETTIVO] DECIMAL (18, 2) NULL,
    [VALORE_REALIZZATO] DECIMAL (18, 2) NULL,
    [UM]                VARCHAR (50)    NULL,
    [CODICE_OBMISURA]   VARCHAR (10)    NULL,
    CONSTRAINT [PK_zDIMENSIONI_ESTRAZIONI_IR] PRIMARY KEY CLUSTERED ([ID_ESTRAZIONE_IR] ASC),
    CONSTRAINT [FK_zDIMENSIONI_ESTRAZIONI_IR_zDIMENSIONI] FOREIGN KEY ([ID_DIMENSIONE]) REFERENCES [dbo].[zDIMENSIONI] ([ID]),
    CONSTRAINT [FK_zDIMENSIONI_ESTRAZIONI_IR_zDIMENSIONI_ESTRAZIONI_IR] FOREIGN KEY ([CODICE_PSR]) REFERENCES [dbo].[zPSR] ([CODICE])
);

