CREATE TABLE [dbo].[zOBBP_MISURA] (
    [ID]                INT           IDENTITY (1, 1) NOT NULL,
    [ID_PROGRAMMAZIONE] INT           NOT NULL,
    [DESCRIZIONE]       VARCHAR (255) NOT NULL,
    [CODICE]            VARCHAR (10)  NOT NULL,
    CONSTRAINT [PK_zOBBP_MISURA] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_zOBBP_MISURA_zPROGRAMMAZIONE] FOREIGN KEY ([ID_PROGRAMMAZIONE]) REFERENCES [dbo].[zPROGRAMMAZIONE] ([ID])
);

