CREATE TABLE [dbo].[zQUERY_SQL] (
    [ID]    INT            IDENTITY (1, 1) NOT NULL,
    [NOME]  NVARCHAR (100) NOT NULL,
    [TESTO] NVARCHAR (MAX) NOT NULL,
    CONSTRAINT [PK_zQUERY_SQL] PRIMARY KEY NONCLUSTERED ([ID] ASC)
);


GO
CREATE UNIQUE CLUSTERED INDEX [IX_zQUERY_SQL]
    ON [dbo].[zQUERY_SQL]([NOME] ASC);

