CREATE TABLE [dbo].[zTIPO_DIMENSIONE] (
    [COD_DIM]     VARCHAR (50)  NOT NULL,
    [DESCRIZIONE] VARCHAR (255) NOT NULL,
    [ORDINE]      INT           NULL,
    CONSTRAINT [PK_zTIPO_DIMENSIONE] PRIMARY KEY CLUSTERED ([COD_DIM] ASC)
);

