CREATE TABLE [dbo].[zTP] (
    [ID]                INT           IDENTITY (1, 1) NOT NULL,
    [ID_PROGRAMMAZIONE] INT           NOT NULL,
    [CODICE]            CHAR (2)      NOT NULL,
    [DESCRIZIONE]       VARCHAR (255) NOT NULL,
    CONSTRAINT [PK_zTP] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_zTP_zPROGRAMMAZIONE] FOREIGN KEY ([ID_PROGRAMMAZIONE]) REFERENCES [dbo].[zPROGRAMMAZIONE] ([ID])
);

