CREATE VIEW VMODIFICA_DATI_GENERALE
AS
SELECT 
	MO.*,
	CASE
		WHEN MO.ID_DOMANDA IS NOT NULL
			THEN 'Domanda di pagamento'
		WHEN MO.ID_VARIANTE IS NOT NULL
			THEN 'Variante'
		ELSE 'Domanda di aiuto'
	END AS TARGET,
	TIPO.DESCRIZIONE AS TIPO_MODIFICA,
	TIPO.ATTIVO AS TIPO_MODIFICA_ATTIVO,
	UT.NOMINATIVO AS UTENTE_MODIFICA,
	UT.CF_UTENTE AS CF_UTENTE_MODIFICA
FROM MODIFICA_DATI_GENERALE MO
	JOIN TIPO_MODIFICA_GENERALE TIPO ON MO.COD_TIPO_MODIFICA = TIPO.ID_TIPO_MODIFICA
	JOIN vUTENTI UT ON MO.ID_UTENTE_MODIFICA = UT.ID_UTENTE
GO