SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

--DROP VIEW VRICERCA_PROG_MODIFICABILI;
CREATE VIEW VRICERCA_PROG_MODIFICABILI
AS
SELECT 
	BAN.ID_BANDO,
	BAN.DESCRIZIONE AS DESCRIZIONE_BANDO, 
	BAN.COD_ENTE AS COD_ENTE_BANDO, 
	BAN.ENTE AS ENTE_BANDO,
	UT.ID_UTENTE AS ID_RUP,
	UT.NOMINATIVO AS RUP,
	UT.CF_UTENTE AS CF_RUP,
	BAN.DATA_APERTURA AS DATA_APERTURA_BANDO,
	BAN.DATA_SCADENZA AS DATA_SCADENZA_BANDO,
	BAN.COD_STATO AS COD_STATO_BANDO,
	BAN.STATO AS STATO_BANDO, 
	BAN.SEGNATURA AS SEGNATURA_BANDO,
	PROG.ID_PROGETTO,
	PROG.COD_STATO AS COD_STATO_PROGETTO, 
	PROG.STATO AS STATO_PROGETTO,
	PROG.SEGNATURA AS SEGNATURA_PROGETTO,
	PROG.ID_IMPRESA AS ID_IMPRESA,
	IMP.RAGIONE_SOCIALE AS IMPRESA,
	IMP.CODICE_FISCALE AS CF_IMPRESA,
	IMP.CUAA AS CUAA_IMPRESA,
	COLL.ID_UTENTE AS ID_ISTRUTTORE_PROGETTO,
	ISNULL(COLL.NOMINATIVO, 'Istruttore non assegnato') AS ISTRUTTORE_PROGETTO
FROM vBANDO BAN
	JOIN vBANDO_RESPONSABILI RESP ON BAN.ID_BANDO = RESP.ID_BANDO
	JOIN vUTENTI UT ON RESP.ID_UTENTE = UT.ID_UTENTE
	JOIN vPROGETTO PROG ON BAN.ID_BANDO = PROG.ID_BANDO
	JOIN vIMPRESA IMP ON PROG.ID_IMPRESA = IMP.ID_IMPRESA
	LEFT JOIN vCOLLABORATORI_X_BANDO COLL ON PROG.ID_PROGETTO = COLL.ID_PROGETTO 
WHERE 1 = 1
	AND PROG.COD_STATO IN ('C', 'F', 'S', 'D', 'T', 'V')
	AND RESP.ATTIVO = 1
	AND RESP.PROVINCIA IS NULL
	AND (COLL.ATTIVO IS NULL 
		OR COLL.ATTIVO = 1)
GO