-- =============================================

CREATE FUNCTION [dbo].[calcoloContributoRimanenteFinanziabileProgetto] 
(
	@ID_PROGETTO INT, --ID DEL PROGETTO CORRELATO
	@ID_VARIANTE INT, 
	@ID_INVESTIMENTO INT=NULL
)
RETURNS DECIMAL(18,2)
AS BEGIN
	
	/*DECLARE @ID_PROGETTO INT, @ID_VARIANTE INT,@ID_INVESTIMENTO INT
	SET @ID_PROGETTO= 118
	SET @ID_VARIANTE=23
	SET @ID_INVESTIMENTO=615*/

	--------CONTRIBUTO PROGETTO CORRELATO VERSIONE PRECEDENTE
	DECLARE @ID_VARIANTE_PRECEDENTE INT,@CONTRIBUTO_PRECEDENTE DECIMAL(18,2),@CONTRIBUTO_ATTUALE DECIMAL(18,2)
	SELECT @ID_VARIANTE_PRECEDENTE=MAX(ID_VARIANTE) FROM VARIANTI V 
	INNER JOIN PROGETTO P ON V.ID_PROGETTO=ISNULL(P.ID_PROG_INTEGRATO,P.ID_PROGETTO) 
	WHERE V.APPROVATA=1 AND V.ANNULLATA=0 AND V.COD_TIPO IN ('VA','AR','VI') AND P.ID_PROGETTO=@ID_PROGETTO AND ID_VARIANTE<@ID_VARIANTE
	SELECT @CONTRIBUTO_PRECEDENTE=SUM(CONTRIBUTO_RICHIESTO) FROM PIANO_INVESTIMENTI WHERE ID_PROGETTO=@ID_PROGETTO
		AND ((@ID_VARIANTE_PRECEDENTE IS NULL AND ID_VARIANTE IS NULL AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL) OR
		(ID_VARIANTE=@ID_VARIANTE_PRECEDENTE AND ISNULL(COD_VARIAZIONE,'x')!='A'))
	
	SELECT @CONTRIBUTO_ATTUALE=SUM(CONTRIBUTO_RICHIESTO) FROM PIANO_INVESTIMENTI
	WHERE ID_PROGETTO=@ID_PROGETTO AND ID_VARIANTE=@ID_VARIANTE AND ISNULL(COD_VARIAZIONE,'OK')!='A'
		AND (@ID_INVESTIMENTO IS NULL OR ID_INVESTIMENTO!=@ID_INVESTIMENTO) -- NON SOMMO L'INVESTIMENTO CORRENTE 

	RETURN ISNULL(@CONTRIBUTO_PRECEDENTE,0)-ISNULL(@CONTRIBUTO_ATTUALE,0)
END
