-- =============================================

CREATE FUNCTION [dbo].[calcoloCostoTotaleProgettoCorrelato] 
(
	@ID_PROGETTO INT, --ID DEL PROGETTO CORRELATO
	@FASE_ISTRUTTORIA BIT =0, --SE FASE ISTRUTTORIA TRUE, ALTRIMENTI DEVO CALCOLARE PER GLI INVESTIMENTI ORIGINALI
	@ID_VARIANTE INT =NULL
)
RETURNS DECIMAL(18,2)
AS
BEGIN

/*
DECLARE @ID_PROGETTO INT
DECLARE	@FASE_ISTRUTTORIA BIT 
SET @ID_PROGETTO= 118
SET	@FASE_ISTRUTTORIA =0
*/
RETURN  (SELECT ISNULL(SUM(CASE COD_TIPO_INVESTIMENTO WHEN 2 /*PER IL MUTUO SOMMO SOLO L'AMMONTARE*/ THEN ISNULL(COSTO_INVESTIMENTO,0) 
		ELSE ISNULL(COSTO_INVESTIMENTO,0)+ISNULL(SPESE_GENERALI,0) END),0) 
		FROM PIANO_INVESTIMENTI PI WHERE ID_PROGETTO=@ID_PROGETTO AND
			((@FASE_ISTRUTTORIA=0 AND ID_INVESTIMENTO_ORIGINALE IS NULL AND ID_VARIANTE IS NULL) OR 
			(@FASE_ISTRUTTORIA=1 AND ((@ID_VARIANTE IS NULL AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL) 
			OR (ID_VARIANTE=@ID_VARIANTE AND ISNULL(COD_VARIAZIONE,'x')!='A')))))
END
