-- =============================================

CREATE FUNCTION [dbo].[calcoloInteressiTotaleProgettoCorrelato] 
(
	@ID_PROGETTO INT, --ID DEL PROGETTO CORRELATO
	@FASE_ISTRUTTORIA BIT =0,
	@ID_VARIANTE INT =NULL
)
RETURNS DECIMAL(18,2)
AS
BEGIN
/*
DECLARE @ID_PROGETTO INT,@FASE_ISTRUTTORIA BIT,@ID_VARIANTE INT 
SET @ID_PROGETTO= 118
SET 	@FASE_ISTRUTTORIA  =1
SET @ID_VARIANTE=13
*/
RETURN (SELECT ISNULL(CASE WHEN (B.IMPORTO_MAX IS NOT NULL AND B.IMPORTO_MAX < CONTRIBUTO) THEN B.IMPORTO_MAX ELSE CONTRIBUTO END,0)
		FROM (SELECT I.ID_PROGETTO,ID_BANDO,SUM(ISNULL(CONTRIBUTO_RICHIESTO,0)) AS CONTRIBUTO
		FROM PIANO_INVESTIMENTI I INNER JOIN PROGETTO P ON I.ID_PROGETTO=P.ID_PROGETTO		
		WHERE P.ID_PROGETTO=@ID_PROGETTO AND ((@FASE_ISTRUTTORIA=0 AND ID_INVESTIMENTO_ORIGINALE IS NULL AND ID_VARIANTE IS NULL) OR 
		(@FASE_ISTRUTTORIA=1 AND ((@ID_VARIANTE IS NULL AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL) 
		OR (ID_VARIANTE=@ID_VARIANTE AND ISNULL(COD_VARIAZIONE,'x')!='A')))) AND  I.COD_TIPO_INVESTIMENTO = 2 -- SOLO PER GLI INTERESSI
		GROUP BY I.ID_PROGETTO,ID_BANDO) AS Q1
		LEFT JOIN BANDO_TIPO_INVESTIMENTI B ON Q1.ID_BANDO=B.ID_BANDO AND B.COD_TIPO_INVESTIMENTO=7)
END
