-- =============================================

CREATE FUNCTION [dbo].[calcoloAmmontareDisponibileGiustificativo] 
(
	@ID_GIUSTIFICATIVO INT, 
	@IMPORTO DECIMAL(18,2),
	@FASE_ISTRUTTORIA BIT
)
RETURNS DECIMAL(18,2)
AS
BEGIN/*
	DECLARE @ID_GIUSTIFICATIVO INT, @IMPORTO DECIMAL(18,2)
SET @ID_GIUSTIFICATIVO=86
SET @IMPORTO=1750000*/
RETURN (SELECT @IMPORTO-ISNULL(SUM(ISNULL(CASE WHEN @FASE_ISTRUTTORIA=1 THEN V.IMPORTO_AMMESSO ELSE V.IMPORTO_RICHIESTO END,0)),0) 
FROM vPAGAMENTI_BENEFICIARIO V INNER JOIN PAGAMENTI_RICHIESTI P ON V.ID_PAGAMENTO_RICHIESTO=P.ID_PAGAMENTO_RICHIESTO
INNER JOIN DOMANDA_DI_PAGAMENTO D ON P.ID_DOMANDA_PAGAMENTO=D.ID_DOMANDA_PAGAMENTO
WHERE ID_GIUSTIFICATIVO=@ID_GIUSTIFICATIVO AND D.ANNULLATA=0)
END
