-- =============================================

CREATE FUNCTION [dbo].[calcoloContributoPagamentiRichiestiInvestimento] 
(
	@ID_INVESTIMENTO INT, 
	@DATA DATETIME
)
RETURNS DECIMAL(18,2)
AS
BEGIN
	DECLARE @CONTRIBUTO DECIMAL(18,2),@ID_INVESTIMENTO_ORIGINALE INT
	SELECT @CONTRIBUTO=Q1.CONTRIBUTO_RICHIESTO,@ID_INVESTIMENTO_ORIGINALE=ID_INVESTIMENTO_ORIGINALE FROM PIANO_INVESTIMENTI I
	LEFT JOIN 
		(SELECT ID_INVESTIMENTO,SUM(P.CONTRIBUTO_RICHIESTO) AS CONTRIBUTO_RICHIESTO FROM PAGAMENTI_RICHIESTI P
		INNER JOIN DOMANDA_DI_PAGAMENTO D ON P.ID_DOMANDA_PAGAMENTO=D.ID_DOMANDA_PAGAMENTO
		WHERE P.ID_INVESTIMENTO=@ID_INVESTIMENTO AND D.DATA_APPROVAZIONE<=@DATA AND D.APPROVATA=1 AND D.ANNULLATA=0 
		GROUP BY ID_INVESTIMENTO) Q1 ON I.ID_INVESTIMENTO=Q1.ID_INVESTIMENTO
	WHERE I.ID_INVESTIMENTO=@ID_INVESTIMENTO
	IF @ID_INVESTIMENTO_ORIGINALE IS NOT NULL
		SET @CONTRIBUTO=ISNULL(@CONTRIBUTO,0) + dbo.calcoloContributoPagamentiRichiestiInvestimento(@ID_INVESTIMENTO_ORIGINALE,@DATA)
	RETURN ISNULL(@CONTRIBUTO,0)
END
