-- =============================================

CREATE FUNCTION [dbo].[calcoloAmmontareErogatoInvestimento] 
(
	@ID_INVESTIMENTO INT, 
	@ID_DOMANDA_PAGAMENTO INT
)
RETURNS DECIMAL(18,2)
AS
BEGIN
	DECLARE @CONTRIBUTO DECIMAL(18,2),@ID_INVESTIMENTO_ORIGINALE INT
	SELECT @ID_INVESTIMENTO_ORIGINALE=ID_INVESTIMENTO_ORIGINALE FROM PIANO_INVESTIMENTI WHERE ID_INVESTIMENTO=@ID_INVESTIMENTO
	SELECT @CONTRIBUTO=SUM(CONTRIBUTO_AMMESSO) FROM PAGAMENTI_RICHIESTI P
	INNER JOIN DOMANDA_DI_PAGAMENTO D ON P.ID_DOMANDA_PAGAMENTO=D.ID_DOMANDA_PAGAMENTO AND D.APPROVATA=1 AND D.ANNULLATA=0					
	WHERE ID_INVESTIMENTO=@ID_INVESTIMENTO AND D.ID_DOMANDA_PAGAMENTO<@ID_DOMANDA_PAGAMENTO
	IF (@ID_INVESTIMENTO_ORIGINALE IS NOT NULL) 
		SET @CONTRIBUTO=ISNULL(@CONTRIBUTO,0)+dbo.calcoloAmmontareErogatoInvestimento(@ID_INVESTIMENTO_ORIGINALE,@ID_DOMANDA_PAGAMENTO)
	RETURN ISNULL(@CONTRIBUTO,0)
END
