-- =============================================

CREATE FUNCTION [dbo].[calcoloPremioContoCapitaleDomandaPagamento] 
(
	@ID_DOMANDA_PAGAMENTO INT,
	@AMMESSO BIT -- SE TRUE CALCOLO ANCHE PER LE VARIAZIONI IN FASE DI ISTRUTTORIA
)
RETURNS DECIMAL(18,2)
AS
BEGIN
DECLARE @ID_VARIANTE INT,@ID_PROGETTO INT,@DATA_MODIFICA_PAGAMENTO DATETIME,@COD_TIPO CHAR(3)
SELECT @DATA_MODIFICA_PAGAMENTO=DATA_MODIFICA,@ID_PROGETTO=ID_PROGETTO,@ID_VARIANTE=CASE WHEN @AMMESSO=1 THEN ID_VARIAZIONE_ACCERTATA ELSE NULL END 
FROM DOMANDA_DI_PAGAMENTO WHERE ID_DOMANDA_PAGAMENTO=@ID_DOMANDA_PAGAMENTO
IF @ID_VARIANTE IS NULL
	SELECT @ID_VARIANTE=MAX(ID_VARIANTE) FROM VARIANTI WHERE ID_PROGETTO=@ID_PROGETTO AND APPROVATA=1 AND ANNULLATA=0 
	AND DATA_MODIFICA<@DATA_MODIFICA_PAGAMENTO
RETURN dbo.calcoloPremioContoCapitale(@ID_PROGETTO,1,@ID_VARIANTE)
END
