CREATE FUNCTION [dbo].[ConvertNumberToDigit_Terzina]
(
	@TERZINA VARCHAR(3),
	@ORDINE INT
)
RETURNS VARCHAR(100)
AS
BEGIN
/*DECLARE @TERZINA VARCHAR(3),@ORDINE INT
SET @TERZINA='958'
SET @ORDINE=1*/

	DECLARE @RESULT VARCHAR(100),@VALORE_TERZINA INT	
	SET @RESULT=''
	SET @VALORE_TERZINA=CAST(@TERZINA AS INT)	
	IF @VALORE_TERZINA>0 BEGIN
		IF @VALORE_TERZINA<20 SET @RESULT=dbo.ConvertNumberToDigit_Unita(@VALORE_TERZINA)
		ELSE BEGIN
			IF LEN(@TERZINA)=2 SET @TERZINA='0'+@TERZINA
			ELSE IF LEN(@TERZINA)=1 SET @TERZINA='00'+@TERZINA
		
			IF @VALORE_TERZINA>99 BEGIN
				DECLARE @PRIMA_CIFRA INT
				SET @PRIMA_CIFRA=CAST(SUBSTRING(@TERZINA,1,1)AS INT)
				IF @PRIMA_CIFRA>1 SET @RESULT=dbo.ConvertNumberToDigit_Unita(@PRIMA_CIFRA)							
				SET @RESULT=@RESULT+'cento'			
			END
			
			
			---- old terzina
			--DECLARE @DECINE INT,@UNITA INT
			--SET @DECINE=CAST(SUBSTRING(@TERZINA,2,1) AS INT)
			--SET @RESULT=@RESULT+dbo.ConvertNumberToDigit_Decine(@DECINE)
			
			--SET @UNITA=CAST(SUBSTRING(@TERZINA,3,1) AS INT)
			--IF @UNITA IN (1,8) SET @RESULT=SUBSTRING(@RESULT,0,LEN(@RESULT))
			--SET @RESULT=@RESULT+dbo.ConvertNumberToDigit_Unita(@UNITA)
			
			
			DECLARE @DECINE INT,@UNITA INT
			SET @DECINE=CAST(SUBSTRING(@TERZINA,2,1) AS INT)
			IF(@DECINE >1)	
			BEGIN
			SET @RESULT=@RESULT+dbo.ConvertNumberToDigit_Decine(@DECINE)
			SET @UNITA=CAST(SUBSTRING(@TERZINA, 3,1) AS INT)
			END
			ELSE SET @UNITA=CAST(SUBSTRING(@TERZINA,2,2) AS INT)
			IF @UNITA IN (1,8) SET @RESULT=SUBSTRING(@RESULT,0,LEN(@RESULT))
			SET @RESULT=@RESULT+dbo.ConvertNumberToDigit_Unita(@UNITA)

		END
		
		IF @ORDINE=2 BEGIN
			SET @RESULT=@RESULT+'mila'
			IF @VALORE_TERZINA=1 SET @RESULT='mille'
		END
		ELSE IF @ORDINE=3 BEGIN
			SET @RESULT=@RESULT+'milioni'
			IF @VALORE_TERZINA=1 SET @RESULT='unmilione'
		END
		ELSE IF @ORDINE=4 BEGIN
			SET @RESULT=@RESULT+'miliardi'
			IF @VALORE_TERZINA=1 SET @RESULT='unmiliardo'
		END
		ELSE IF @ORDINE=5 BEGIN
			SET @RESULT=@RESULT+'milamiliardi'
			IF @VALORE_TERZINA=1 SET @RESULT='millemiliardi'
		END
	END
	RETURN ISNULL(@RESULT,'')
END
