CREATE FUNCTION [dbo].[fnGetPunteggioMinimoGraduatoria]
(
	@ID_BANDO INT
)
RETURNS DECIMAL(10,6)
AS
BEGIN
	DECLARE @PUNTEGGIO_MINIMO DECIMAL(10,6)
	SELECT TOP 1 @PUNTEGGIO_MINIMO=PUNTEGGIO FROM GRADUATORIA_PROGETTI WHERE ID_BANDO=@ID_BANDO AND FINANZIABILITA='N' ORDER BY ORDINE
	IF @PUNTEGGIO_MINIMO IS NULL RETURN 0
	ELSE IF (SELECT COUNT(*) FROM GRADUATORIA_PROGETTI WHERE ID_BANDO=@ID_BANDO AND FINANZIABILITA!='N' AND PUNTEGGIO=@PUNTEGGIO_MINIMO)>0
		RETURN -1
	RETURN @PUNTEGGIO_MINIMO
END
