CREATE FUNCTION [dbo].[fnProgettoTitolo]
(
	@Id_Progetto   INT
)
RETURNS VARCHAR(500)
AS
BEGIN
    DECLARE @ret VARCHAR(500);

    WITH BRT AS 
    (
        SELECT  dbo.PROGETTO.ID_PROGETTO, 
                dbo.PROGETTO.ID_BANDO, 
                dbo.BANDO_RELAZIONE_TECNICA.ORDINE, 
                ROW_NUMBER() OVER(PARTITION BY PROGETTO.ID_PROGETTO, dbo.BANDO_RELAZIONE_TECNICA.ORDINE ORDER BY PROGETTO.ID_PROGETTO, dbo.BANDO_RELAZIONE_TECNICA.ORDINE ASC) AS ORDER_ROW,
                dbo.PROGETTO_RELAZIONE_TECNICA.TESTO
        FROM    dbo.BANDO_RELAZIONE_TECNICA 
                INNER JOIN
                dbo.PROGETTO_RELAZIONE_TECNICA ON dbo.BANDO_RELAZIONE_TECNICA.ID_PARAGRAFO = dbo.PROGETTO_RELAZIONE_TECNICA.ID_PARAGRAFO 
                INNER JOIN
                dbo.PROGETTO ON dbo.PROGETTO_RELAZIONE_TECNICA.ID_PROGETTO = dbo.PROGETTO.ID_PROGETTO
        WHERE dbo.BANDO_RELAZIONE_TECNICA.ORDINE IN (1,2) 
    )

    SELECT  -- P.ID_PROGETTO AS COD_LOCALE_PROGETTO,
            @ret = ISNULL(REPLACE(REPLACE(REPLACE(REPLACE(SUBSTRING(BRT1.TESTO, 1, 500),CHAR(10), ' '), CHAR(13), ' '), '#', ' '), '|', ' '), I.RAGIONE_SOCIALE) -- AS TITOLO_PROGETTO,
            --ISNULL(REPLACE(REPLACE(REPLACE(REPLACE(SUBSTRING(BRT2.TESTO,1,1300),CHAR(10),' '),CHAR(13),' '),'#',' '),'|',' '),I.RAGIONE_SOCIALE) AS SINTESI_PRG,
            --CUP_TO.Natura + '.' + CUP_TO.Tipologia AS TIPO_OPERAZIONE, -- TC5 
            --P.COD_AGEA AS CUP, 
            --'FESR20142020' AS CODICE_FONDO
    FROM    vPROGETTO P
            INNER JOIN 
            DATI_MONITORAGGIO_FESR DMF ON P.ID_PROGETTO = DMF.ID_PROGETTO
            INNER JOIN 
            TIPO_CUP_CATEGORIE_TIPIOPERAZIONI CUP_TO ON DMF.CUP_CATEGORIA_TIPOOPER = CUP_TO.COD_CUP_CATEGORIE_TIPIOPERAZIONI
            INNER JOIN 
            vBANDO B ON P.ID_BANDO = B.ID_BANDO
            INNER JOIN 
            zPROGRAMMAZIONE PRG ON B.ID_PROGRAMMAZIONE = PRG.ID
            INNER JOIN 
            zPSR_ALBERO PA ON PRG.COD_TIPO = PA.CODICE
            INNER JOIN 
            zPSR PSR ON PA.COD_PSR = PSR.CODICE
            LEFT OUTER JOIN 
            (
                SELECT  BRT.ID_PROGETTO, 
                        BRT.TESTO 
                FROM BRT
                WHERE ORDINE = 2 
                  AND ORDER_ROW = 1
            ) AS BRT2 ON P.ID_PROGETTO = BRT2.ID_PROGETTO
            LEFT OUTER JOIN 
            (
                SELECT  BRT.ID_PROGETTO, 
                        BRT.TESTO 
                FROM BRT
                WHERE ORDINE = 1 
                  AND ORDER_ROW = 1
            ) AS BRT1 ON P.ID_PROGETTO = BRT1.ID_PROGETTO
            INNER JOIN 
            vIMPRESA I ON P.ID_IMPRESA = I.ID_IMPRESA
    WHERE P.COD_STATO IN ('F','V','S','O','T','X','C','Y','E','R')  --INSERIRE STATI VALIDI
      AND PSR.CODICE = 'POR20142020'
      AND P.COD_AGEA IS NOT NULL
      AND P.Id_Progetto = @Id_Progetto

    RETURN(@ret)
END