CREATE FUNCTION [dbo].[StringDifference]
(
	@STR1 VARCHAR(255),
	@STR2 VARCHAR(255)
)
RETURNS INT
AS BEGIN
	IF @STR1 IS NULL OR @STR2 IS NULL RETURN 9999
	IF @STR1=@STR2 RETURN 0
	DECLARE @RETVAL INT,@COMPARE_STR VARCHAR(255),@PATTERN VARCHAR(255)
	IF LEN(@STR1)<=LEN(@STR2) BEGIN
		SET @PATTERN=@STR1
		SET @COMPARE_STR=@STR2
	END
	ELSE BEGIN
		SET @COMPARE_STR=@STR1
		SET @PATTERN=@STR2	
	END
	
	SET @RETVAL=LEN(@COMPARE_STR)-LEN(@PATTERN)
	
	DECLARE @COUNTER INT=1,@L INT=LEN(@COMPARE_STR)
	WHILE @COUNTER<=@L BEGIN
		IF SUBSTRING(@PATTERN,@COUNTER,1)!=SUBSTRING(@COMPARE_STR,@COUNTER,1) BEGIN
			SET @RETVAL=@RETVAL+1
			SET @PATTERN=LEFT(@PATTERN,@COUNTER-1)+'_'+RIGHT(@PATTERN,@L-@COUNTER)
		END	
		IF @COMPARE_STR LIKE '%'+@PATTERN+'%' BREAK
		SET @COUNTER=@COUNTER+1
	END	
	RETURN @RETVAL
END
