CREATE FUNCTION [dbo].[VerificaDisponibilitaFondiRiservaBando]
(
	@ID_BANDO INT,
	@ID_PROGETTO INT
)
RETURNS BIT
AS
BEGIN
	DECLARE @RETVAL BIT
	SET @RETVAL=0
	/*
	DECLARE @ID_BANDO INT,@ID_PROGETTO INT
	SET @ID_BANDO=90
	SET @ID_PROGETTO=3731*/

	DECLARE @IMPORTO_RISERVA_BANDO DECIMAL(18,5),@IMPORTO_RISERVA_BANDO_UTILIZZATO DECIMAL(18,5),@CONTRIBUTO_PROGETTO DECIMAL(18,2)
	SELECT @IMPORTO_RISERVA_BANDO=IMPORTO*ISNULL(QUOTA_RISERVA,0)/100 FROM VBANDO WHERE ID_BANDO=@ID_BANDO
	SELECT @IMPORTO_RISERVA_BANDO_UTILIZZATO=SUM(CONTRIBUTO_TOTALE) FROM GRADUATORIA_PROGETTI WHERE ID_BANDO=@ID_BANDO 
		AND UTILIZZA_FONDI_RISERVA=1
	SET @IMPORTO_RISERVA_BANDO=ISNULL(@IMPORTO_RISERVA_BANDO,0)-ISNULL(@IMPORTO_RISERVA_BANDO_UTILIZZATO,0)
	IF(@IMPORTO_RISERVA_BANDO>0) BEGIN
		SELECT @CONTRIBUTO_PROGETTO=dbo.calcoloContributoTotaleProgetto(@ID_PROGETTO,1,NULL)+
			ISNULL(dbo.calcoloPremioContoCapitale(@ID_PROGETTO,1,NULL),0)
		-- PER ORA OMETTO IL CONTROLLO SUI MASSIMALI PER BENEFICIARIO PER L'INTERA PROGRAMMAZIONE
		IF(@IMPORTO_RISERVA_BANDO>@CONTRIBUTO_PROGETTO) SET @RETVAL=1
	END
	RETURN @RETVAL
END
