
CREATE VIEW VCHECKLIST_GENERICA
AS
SELECT CG.*,
	TC.DESCRIZIONE AS DESCRIZIONE_TIPO,
	TC.CONTIENE_VOCI AS CONTIENE_VOCI_TIPO,
	TC.SCHEDA AS SCHEDA_TIPO,
	FC.DESCRIZIONE AS DESCRIZIONE_FILTRO,
	FC.ORDINE AS ORDINE_FILTRO
FROM CHECKLIST_GENERICA CG
	LEFT JOIN TIPO_CHECKLIST TC ON CG.ID_TIPO = TC.ID_TIPO
	LEFT JOIN FILTRO_CHECKLIST_VOCE FC ON CG.ID_FILTRO = FC.ID_FILTRO