
CREATE VIEW VISTANZA_CHECKLIST_GENERICA
AS
SELECT ICG.ID_ISTANZA_GENERICA, 
	ICG.ID_CHECKLIST_GENERICA, 
	ICG.DATA_INSERIMENTO, 
	ICG.CF_INSERIMENTO, 
	ICG.DATA_MODIFICA, 
	ICG.CF_MODIFICA, 
	CG.DESCRIZIONE, 
	CG.FLAG_TEMPLATE, 
	ICG.COD_FASE,
	ICG.ID_CHECKLIST_PADRE,
	ICG.ID_SCHEDA_X_CHECKLIST
FROM ISTANZA_CHECKLIST_GENERICA ICG
	JOIN CHECKLIST_GENERICA CG ON ICG.ID_CHECKLIST_GENERICA = CG.ID_CHECKLIST_GENERICA