-- DROP VIEW VSCHEDA_X_CHECKLIST
CREATE VIEW VSCHEDA_X_CHECKLIST
AS
	SELECT SXC.*,
		CGC.DESCRIZIONE AS DESCRIZIONE_CHECKLIST,
		CGC.FLAG_TEMPLATE AS FLAG_TEMPLATE_CHECKLIST,

		TCC.ID_TIPO AS ID_TIPO_CHECKLIST,
		TCC.DESCRIZIONE AS DESCRIZIONE_TIPO_CHECKLIST,
		TCC.CONTIENE_VOCI AS CONTIENE_VOCI_CHECKLIST,
		TCC.SCHEDA AS SCHEDA_CHECKLIST,
		FCC.ID_FILTRO AS ID_FILTRO_CHECKLIST,
		FCC.DESCRIZIONE AS DESCRIZIONE_FILTRO_CHECKLIST,
		FCC.ORDINE AS ORDINE_FILTRO_CHECKLIST,

		TCS.ID_TIPO AS ID_TIPO_SCHEDA,
		TCS.DESCRIZIONE AS DESCRIZIONE_TIPO_SCHEDA,
		TCS.CONTIENE_VOCI AS CONTIENE_VOCI_SCHEDA,
		TCS.SCHEDA AS SCHEDA_SCHEDA,
		FCS.ID_FILTRO AS ID_FILTRO_SCHEDA,
		FCS.DESCRIZIONE AS DESCRIZIONE_FILTRO_SCHEDA,
		FCS.ORDINE AS ORDINE_FILTRO_SCHEDA
	FROM SCHEDA_X_CHECKLIST SXC
		JOIN CHECKLIST_GENERICA CGC ON SXC.ID_CHECKLIST = CGC.ID_CHECKLIST_GENERICA 
		LEFT JOIN TIPO_CHECKLIST TCC ON CGC.ID_TIPO = TCC.ID_TIPO
		LEFT JOIN FILTRO_CHECKLIST_VOCE FCC ON CGC.ID_FILTRO = FCC.ID_FILTRO
		JOIN CHECKLIST_GENERICA CGS ON SXC.ID_SCHEDA = CGS.ID_CHECKLIST_GENERICA
		LEFT JOIN TIPO_CHECKLIST TCS ON CGC.ID_TIPO = TCS.ID_TIPO
		LEFT JOIN FILTRO_CHECKLIST_VOCE FCS ON CGC.ID_FILTRO = FCS.ID_FILTRO;
GO