
CREATE VIEW VVOCE_X_CHECKLIST_GENERICA
AS 
SELECT VXC.*,

	VG.DESCRIZIONE AS DESCRIZIONE_VOCE,
	VG.AUTOMATICO AS AUTOMATICO_VOCE,
	VG.QUERY_SQL AS QUERY_SQL_VOCE,
	VG.QUERY_SQL_POST AS QUERY_SQL_POST_VOCE,
	VG.CODE_METHOD AS CODE_METHOD_VOCE,
	VG.URL AS URL_VOCE,
	VG.VAL_MINIMO AS VAL_MINIMO_VOCE,
	VG.VAL_MASSIMO AS VAL_MASSIMO_VOCE,
	VG.VAL_ESITO_NEGATIVO AS VAL_ESITO_NEGATIVO_VOCE,
	VG.ID_FILTRO AS ID_FILTRO_VOCE,
	VG.TITOLO AS TITOLO_VOCE,
	VG.COMMENTO AS COMMENTO_VOCE,
	FCV.DESCRIZIONE AS DESCRIZIONE_FILTRO_VOCE,
	FCV.ORDINE AS ORDINE_FILTRO_VOCE,

	CG.DESCRIZIONE AS DESCRIZIONE_CHECKLIST,
	CG.FLAG_TEMPLATE AS FLAG_TEMPLATE_CHECKLIST,
	CG.ID_TIPO AS ID_TIPO_CHECKLIST,
	TC.DESCRIZIONE AS DESCRIZIONE_TIPO_CHECKLIST,
	TC.CONTIENE_VOCI AS CONTIENE_VOCI_TIPO_CHECKLIST,
	TC.SCHEDA AS SCHEDA_TIPO_CHECKLIST,
	CG.ID_FILTRO AS ID_FILTRO_CHECKLIST,
	FCC.DESCRIZIONE AS DESCRIZIONE_FILTRO_CHECKLIST,
	FCC.ORDINE AS ORDINE_FILTRO_CHEKLIST
FROM VOCE_X_CHECKLIST_GENERICA VXC

	JOIN VOCE_GENERICA VG ON VXC.ID_VOCE_GENERICA = VG.ID_VOCE_GENERICA
	LEFT JOIN FILTRO_CHECKLIST_VOCE FCV ON VG.ID_FILTRO = FCV.ID_FILTRO

	JOIN CHECKLIST_GENERICA CG ON VXC.ID_CHECKLIST_GENERICA = CG.ID_CHECKLIST_GENERICA
	LEFT JOIN TIPO_CHECKLIST TC ON CG.ID_TIPO = TC.ID_TIPO
	LEFT JOIN FILTRO_CHECKLIST_VOCE FCC ON CG.ID_FILTRO = FCC.ID_FILTRO