
CREATE VIEW VVOCE_GENERICA
AS
SELECT VG.*,
	FC.DESCRIZIONE AS DESCRIZIONE_FILTRO,
	FC.ORDINE AS ORDINE_FILTRO
FROM VOCE_GENERICA VG
	LEFT JOIN FILTRO_CHECKLIST_VOCE FC ON VG.ID_FILTRO = FC.ID_FILTRO