-- DROP VIEW VSPESA_IRREGOLARE
CREATE VIEW VSPESA_IRREGOLARE
AS
	SELECT
		SPI.*, 
		SP.ID_GIUSTIFICATIVO, 
		SP.COD_TIPO AS COD_TIPO_SPESA, 
		SP.ESTREMI AS ESTREMI_SPESA, 
		SP.DATA AS DATA_SPESA, 
		SP.IMPORTO AS IMPORTO_SPESA, 
		SP.NETTO AS NETTO_SPESA, 
		TIPS.DESCRIZIONE AS TIPO_SPESA,
		DOM.ID_DOMANDA_PAGAMENTO,
		DOM.COD_TIPO AS COD_TIPO_DOMANDA,
		DOM.DESCRIZIONE AS TIPO_DOMANDA,
		GIU.ID_PROGETTO,
		GIU.NUMERO AS NUMERO_GIUSTIFICATIVO, 
		GIU.COD_TIPO AS COD_TIPO_GIUSTIFICATIVO, 
		GIU.DATA AS DATA_GIUSTIFICATIVO, 
		GIU.NUMERO_DOCTRASPORTO AS NUMERO_DOCTRASPORTO_GIUSTIFICATIVO, 
		GIU.IMPONIBILE AS IMPONIBILE_GIUSTIFICATIVO,
		GIU.IVA AS IVA_GIUSTIFICATIVO, 
		GIU.IVA_NON_RECUPERABILE AS IVA_NON_RECUPERABILE_GIUSTIFICATIVO,
		GIU.DESCRIZIONE AS DESCRIZIONE_GIUSTIFICATIVO,
		GIU.CF_FORNITORE AS CF_FORNITORE_GIUSTIFICATIVO,
		GIU.DESCRIZIONE_FORNITORE AS DESCRIZIONE_FORNITORE_GIUSTIFICATIVO,
		TIPG.DESCRIZIONE AS TIPO_GIUSTIFICATIVO,
		CERT_T.IdCertSp AS ID_LOTTO_CERTIFICAZIONE,
		CERT_T.CodPsr AS COD_PSR_CERTIFICAZIONE,
		CERT_T.DataInizio AS DATA_INIZIO_LOTTO_CERTIFICAZIONE,
		CERT_T.DataFine AS DATA_FINE_LOTTO_CERTIFICAZIONE
	FROM SPESA_IRREGOLARE SPI 
		JOIN SPESE_SOSTENUTE SP ON SPI.ID_SPESA = SP.ID_SPESA 
		JOIN TIPO_GIUSTIFICATIVO TIPS ON SP.COD_TIPO = TIPS.COD_TIPO
		JOIN VDOMANDA_DI_PAGAMENTO DOM ON SP.ID_DOMANDA_PAGAMENTO = DOM.ID_DOMANDA_PAGAMENTO
		JOIN GIUSTIFICATIVI GIU ON SP.ID_GIUSTIFICATIVO = GIU.ID_GIUSTIFICATIVO 
		JOIN TIPO_GIUSTIFICATIVO TIPG ON GIU.COD_TIPO = TIPG.COD_TIPO
		LEFT JOIN vCertSp_Dettaglio CERT_D ON SP.ID_DOMANDA_PAGAMENTO = CERT_D.Id_Domanda_Pagamento
		LEFT JOIN CertSp_Testa CERT_T ON CERT_D.IdCertSp = CERT_T.IdCertSp
	WHERE 1 = 1
		AND (CERT_D.Definitivo IS NULL OR CERT_D.Definitivo = 1)
		AND (CERT_D.Selezionata IS NULL OR CERT_D.Selezionata = 1)
GO