CREATE TABLE [dbo].[_GraduatoriaSigfrido170] (
    [POS]                                     INT             NULL,
    [ID_DOMANDA]                              INT             NULL,
    [DENOMINAZIONE_IMPRESA]                   NVARCHAR (255)  NULL,
    [PIVA_CF]                                 NVARCHAR (255)  NULL,
    [INDIRIZZO]                               NVARCHAR (255)  NULL,
    [PV]                                      NVARCHAR (255)  NULL,
    [CAP]                                     FLOAT (53)      NULL,
    [COMUNE]                                  NVARCHAR (255)  NULL,
    [TITOLO_PROGETTO]                         NVARCHAR (255)  NULL,
    [PUNTEGGIO]                               FLOAT (53)      NULL,
    [Priorità a)_N# dipen#  _Sesso femminile] FLOAT (53)      NULL,
    [Priorità b)_N# dipen#  _<= 35 anni ]     FLOAT (53)      NULL,
    [CUP]                                     NVARCHAR (255)  NULL,
    [F14]                                     NVARCHAR (255)  NULL,
    [ESITO]                                   NVARCHAR (255)  NULL,
    [INVESTIMENTO_AMMESSO]                    DECIMAL (20, 2) NULL,
    [INVESTIMENTO_TOTALE_AMMESSO]             DECIMAL (20, 2) NULL,
    [CONTRIBUTO_CONCEDIBILE]                  DECIMAL (20, 2) NULL,
    [CONTRIBUTO_CONCESSO]                     DECIMAL (20, 2) NULL,
    [INVIO COMUNIC# ESITI]                    NVARCHAR (255)  NULL,
    [ACCETTAZIONE ESITI]                      NVARCHAR (255)  NULL,
    [AVVIO REVOCA]                            NVARCHAR (255)  NULL,
    [CONTRODEDUZIONI]                         NVARCHAR (255)  NULL,
    [FLAG_CAPOFILA]                           BIT             NULL,
    [ID_PROGETTO_SIGEF]                       INT             NULL,
    [DATA_ATTO_CONCESSIONE]                   DATETIME        NULL,
    [DATA_RICEVIBILITA]                       DATETIME        NULL,
    [DATA_AMMISSIBILITA]                      DATETIME        NULL,
    [BK_DATA_UTENTE_STORICO]                  DATETIME        NULL
);

