CREATE TABLE [dbo].[_GraduatoriaSigfrido95Filiere_1] (
    [POS]                                         INT             NULL,
    [ID_DOMANDA_SIGFRIDO]                         INT             NULL,
    [ID_PROGETTO_SIGFRIDO]                        INT             NULL,
    [DENOMINAZIONE_IMPRESA]                       NVARCHAR (255)  NULL,
    [LP_o_PP]                                     NVARCHAR (255)  NULL,
    [P#IVA]                                       NVARCHAR (255)  NULL,
    [Codice_Fiscale]                              NVARCHAR (255)  NULL,
    [Indirizzo_Localizzazione_Sede_investimento]  NVARCHAR (255)  NULL,
    [Numero_Civico_Localizzazione]                NVARCHAR (255)  NULL,
    [Cap_Localizzazione]                          NVARCHAR (255)  NULL,
    [COMUNE_SEDE_INVESTIMENTO]                    NVARCHAR (255)  NULL,
    [Provincia_Localizzazione]                    NVARCHAR (255)  NULL,
    [Email_Sede]                                  NVARCHAR (255)  NULL,
    [Email_PEC]                                   NVARCHAR (255)  NULL,
    [TITOLO_PROGETTO]                             NVARCHAR (255)  NULL,
    [Ambito_tecnologico]                          NVARCHAR (MAX)  NULL,
    [Dimensione_Impresa]                          NVARCHAR (255)  NULL,
    [Percen#]                                     FLOAT (53)      NULL,
    [PUNTEGGIO]                                   DECIMAL (10, 6) NULL,
    [Cognome_Resp]                                NVARCHAR (255)  NULL,
    [Nome_Resp]                                   NVARCHAR (255)  NULL,
    [Tel_Resp]                                    NVARCHAR (255)  NULL,
    [Email_Resp]                                  NVARCHAR (255)  NULL,
    [Cognome_Team]                                NVARCHAR (255)  NULL,
    [Nome_Team]                                   NVARCHAR (255)  NULL,
    [Tel_Team]                                    NVARCHAR (255)  NULL,
    [Email_Team]                                  NVARCHAR (255)  NULL,
    [CUP]                                         NVARCHAR (255)  NULL,
    [Investimento_proposto]                       DECIMAL (20, 2) NULL,
    [Contributo_richiesto]                        DECIMAL (20, 2) NULL,
    [Investimento_ammesso_progetto]               DECIMAL (20, 2) NULL,
    [Investimento_ammesso]                        DECIMAL (20, 2) NULL,
    [Contributo_concesso_progetto]                DECIMAL (20, 2) NULL,
    [Contributo_concesso]                         DECIMAL (20, 2) NULL,
    [personale_piano_investimenti]                DECIMAL (20, 2) NULL,
    [personale_rendicontato]                      DECIMAL (20, 2) NULL,
    [personale_ammissibile]                       DECIMAL (20, 2) NULL,
    [strumenti_e_attrezzature_piano_investimenti] DECIMAL (20, 2) NULL,
    [strumenti_e_attrezzature_rendicontato]       DECIMAL (20, 2) NULL,
    [strumenti_e_attrezzature_ammissibile]        DECIMAL (20, 2) NULL,
    [consulenze_piano_investimenti]               DECIMAL (20, 2) NULL,
    [consulenze_rendicontato]                     DECIMAL (20, 2) NULL,
    [consulenze_ammissibile]                      DECIMAL (20, 2) NULL,
    [materiali__piano_investimenti]               DECIMAL (20, 2) NULL,
    [materiali_rendicontato]                      DECIMAL (20, 2) NULL,
    [materiali_ammissibile]                       DECIMAL (20, 2) NULL,
    [Totale__piano_investimenti]                  DECIMAL (20, 2) NULL,
    [Totale_rendicontato_progetto]                DECIMAL (20, 2) NULL,
    [Totale_rendicontato]                         DECIMAL (20, 2) NULL,
    [Totale_ammissibile]                          DECIMAL (20, 2) NULL,
    [COMUNICAZIONE_ESITI_INVIATA_IL]              DATETIME        NULL,
    [ACCETTAZIONE_ESITI_INVIATA_IL]               DATETIME        NULL,
    [DATA_INIZIO_PROGETTO]                        DATETIME        NULL,
    [DATA_INVIO_PEC_1_SAL_(365_GG_DA_RICEZIONE)]  DATETIME        NULL,
    [TERMINE_PROGETTO]                            DATETIME        NULL,
    [A)_ANTICIPAZIONE_LIQUIDATA_]                 DECIMAL (20, 2) NULL,
    [Decreto_anticipo_num]                        NVARCHAR (255)  NULL,
    [Anticipo_segnatura]                          NVARCHAR (255)  NULL,
    [SPESA_RENDICONTATA_1_SAL_]                   DECIMAL (20, 2) NULL,
    [Spesa_non_ammissibile]                       DECIMAL (20, 2) NULL,
    [B)_CONTRIBUTO_1_SAL_SPETTANTE_]              DECIMAL (20, 2) NULL,
    [_c)_=_(BA)_CONTRIBUTO_1_SAL_DA_LIQUIDARE_]   DECIMAL (20, 2) NULL,
    [Decreto_di_liquidazione_num]                 NVARCHAR (255)  NULL,
    [Decreto_di_liquidazione_data]                NVARCHAR (255)  NULL,
    [Liquidazione_segnatura]                      NVARCHAR (255)  NULL,
    [F67]                                         NVARCHAR (255)  NULL,
    [ESITO]                                       NVARCHAR (255)  NULL,
    [BK_DATA_UTENTE_STORICO]                      DATETIME        NULL,
    [FLAG_CAPOFILA]                               BIT             NULL,
    [CODICE_PROGETTO]                             VARCHAR (50)    NULL,
    [ID_PROGETTO_SIGEF]                           INT             NULL,
    [DATA_RILASCIO]                               DATETIME        NULL,
    [DATA_RICEVIBILITA]                           DATETIME        NULL,
    [DATA_AMMISSIBILITA]                          DATETIME        NULL,
    [DATA_CONCESSIONE]                            DATETIME        NULL,
    [Decreto_anticipo_data]                       DATETIME        NULL
);

