CREATE TABLE [dbo].[_old_IMPRESA_SOCI] (
    [ID]                   INT      IDENTITY (1, 1) NOT NULL,
    [ID_IMPRESA]           INT      NOT NULL,
    [ID_SOCIO]             INT      NOT NULL,
    [ATTIVO]               BIT      CONSTRAINT [DF_IMPRESA_SOCI_ATTIVO] DEFAULT ((0)) NOT NULL,
    [DATA_INIZIO_VALIDITA] DATETIME NOT NULL,
    [DATA_FINE_VALIDITA]   DATETIME NULL,
    [ID_OPERATORE_INIZIO]  INT      NOT NULL,
    [ID_OPERATORE_FINE]    INT      NULL,
    [COD_TIPO_SOCIO]       CHAR (1) NOT NULL,
    CONSTRAINT [PK_IMPRESA_SOCI] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 80)
);


GO
CREATE NONCLUSTERED INDEX [IX_IMPRESA_SOCI]
    ON [dbo].[_old_IMPRESA_SOCI]([ID_IMPRESA] ASC);

