CREATE TABLE [dbo].[ANTICIPI_RICHIESTI] (
    [ID_ANTICIPO]          INT             IDENTITY (1, 1) NOT NULL,
    [ID_DOMANDA_PAGAMENTO] INT             NOT NULL,
    [ID_BANDO]             INT             NOT NULL,
    [DATA_RICHIESTA]       DATETIME        NOT NULL,
    [CONTRIBUTO_RICHIESTO] DECIMAL (18, 2) NOT NULL,
    [CONTRIBUTO_AMMESSO]   DECIMAL (18, 2) NULL,
    [AMMESSO]              BIT             NULL,
    [ISTRUTTORE]           VARCHAR (16)    NULL,
    [DATA_VALUTAZIONE]     DATETIME        NULL,
    CONSTRAINT [PK_ANTICIPI_RICHIESTI] PRIMARY KEY CLUSTERED ([ID_ANTICIPO] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_ANTICIPI_RICHIESTI_BANDO] FOREIGN KEY ([ID_BANDO]) REFERENCES [dbo].[BANDO] ([ID_BANDO]),
    CONSTRAINT [FK_ANTICIPI_RICHIESTI_DOMANDA_DI_PAGAMENTO] FOREIGN KEY ([ID_DOMANDA_PAGAMENTO]) REFERENCES [dbo].[DOMANDA_DI_PAGAMENTO] ([ID_DOMANDA_PAGAMENTO])
);

