CREATE TABLE [dbo].[ATTI_REGISTRI] (
    [CODICE]              VARCHAR (10)  NOT NULL,
    [DESCRIZIONE]         VARCHAR (100) NOT NULL,
    [ATTIVO]              BIT           CONSTRAINT [DF_ATTI_REGISTRI_ATTIVO] DEFAULT ((0)) NOT NULL,
    [ORDINE]              INT           NOT NULL,
    [OPEN_ACT]            BIT           CONSTRAINT [DF_ATTI_REGISTRI_OPEN_ACT] DEFAULT ((0)) NOT NULL,
    [DATA_AVVIO_OPEN_ACT] DATETIME      NULL,
    CONSTRAINT [PK_ATTI_REGISTRI] PRIMARY KEY CLUSTERED ([CODICE] ASC) WITH (FILLFACTOR = 100)
);

