CREATE TABLE [dbo].[BANDO_REQUISITI_PAGAMENTO] (
    [ID_BANDO]                 INT      NOT NULL,
    [COD_TIPO]                 CHAR (3) NOT NULL,
    [ID_REQUISITO]             INT      NOT NULL,
    [OBBLIGATORIO]             BIT      CONSTRAINT [DF_BANDO_REQUISITI_PAGAMENTO_OBBLIGATORIO] DEFAULT ((0)) NOT NULL,
    [REQUISITO_DI_INSERIMENTO] BIT      CONSTRAINT [DF_BANDO_REQUISITI_PAGAMENTO_REQUISITO_DI_INSERIMENTO] DEFAULT ((0)) NOT NULL,
    [REQUISITO_DI_CONTROLLO]   BIT      CONSTRAINT [DF_BANDO_REQUISITI_PAGAMENTO_PRESENTAZIONE] DEFAULT ((0)) NOT NULL,
    [ORDINE]                   INT      NULL,
    CONSTRAINT [PK_BANDO_REQUISITI_PAGAMENTO] PRIMARY KEY CLUSTERED ([ID_BANDO] ASC, [COD_TIPO] ASC, [ID_REQUISITO] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_BANDO_REQUISITI_PAGAMENTO_BANDO_TIPO_PAGAMENTO] FOREIGN KEY ([ID_BANDO], [COD_TIPO]) REFERENCES [dbo].[BANDO_TIPO_PAGAMENTO] ([ID_BANDO], [COD_TIPO]),
    CONSTRAINT [FK_BANDO_REQUISITI_PAGAMENTO_REQUISITI_PAGAMENTO] FOREIGN KEY ([ID_REQUISITO]) REFERENCES [dbo].[REQUISITI_PAGAMENTO] ([ID_REQUISITO])
);

