CREATE TABLE [dbo].[BANDO_VALIDATORI] (
    [ID]               INT      IDENTITY (1, 1) NOT NULL,
    [ID_BANDO]         INT      NOT NULL,
    [ID_UTENTE]        INT      NOT NULL,
    [RESPONSABILE]     BIT      CONSTRAINT [DF_BANDO_VALIDATORI_RESPONSABILE] DEFAULT ((0)) NOT NULL,
    [ATTIVO]           BIT      CONSTRAINT [DF_BANDO_VALIDATORI_ATTIVO] DEFAULT ((1)) NOT NULL,
    [DATA_INIZIO]      DATETIME NOT NULL,
    [OPERATORE_INIZIO] INT      NOT NULL,
    [DATA_FINE]        DATETIME NULL,
    [OPERATORE_FINE]   INT      NULL,
    CONSTRAINT [PK_BANDO_VALIDATORI] PRIMARY KEY CLUSTERED ([ID] ASC)
);

