CREATE TABLE [dbo].[BANDO_MASSIMALI] (
    [ID]                INT             IDENTITY (1, 1) NOT NULL,
    [ID_BANDO]          INT             NOT NULL,
    [ID_PROGRAMMAZIONE] INT             NOT NULL,
    [QUOTA]             DECIMAL (10, 2) CONSTRAINT [DF_BANDO_MASSIMALI_QUOTA] DEFAULT ((0)) NOT NULL,
    [IMPORTO]           DECIMAL (18, 2) CONSTRAINT [DF_BANDO_MASSIMALI_IMPORTO] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_BANDO_MASSIMALI] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_BANDO_MASSIMALI_BANDO] FOREIGN KEY ([ID_BANDO]) REFERENCES [dbo].[BANDO] ([ID_BANDO]),
    CONSTRAINT [FK_BANDO_MASSIMALI_zPROGRAMMAZIONE] FOREIGN KEY ([ID_PROGRAMMAZIONE]) REFERENCES [dbo].[zPROGRAMMAZIONE] ([ID])
);

