CREATE TABLE [dbo].[BANDO_COMUNICAZIONI] (
    [COD_TIPO]              CHAR (3) NOT NULL,
    [ID_BANDO]              INT      NOT NULL,
    [TESTO]                 NTEXT    NULL,
    [MODALITA_ANTICIPO]     NTEXT    NULL,
    [OBBLIGHI_BENEFICIARIO] NTEXT    NULL,
    [ID_ATTO]               INT      NULL,
    [DATA]                  DATETIME NULL,
    CONSTRAINT [PK_BANDO_COMUNICAZIONI] PRIMARY KEY CLUSTERED ([COD_TIPO] ASC, [ID_BANDO] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_BANDO_COMUNICAZIONI_ATTI] FOREIGN KEY ([ID_ATTO]) REFERENCES [dbo].[ATTI] ([ID_ATTO]),
    CONSTRAINT [FK_BANDO_COMUNICAZIONI_BANDO] FOREIGN KEY ([ID_BANDO]) REFERENCES [dbo].[BANDO] ([ID_BANDO]),
    CONSTRAINT [FK_BANDO_COMUNICAZIONI_TIPO_SEGNATURA] FOREIGN KEY ([COD_TIPO]) REFERENCES [dbo].[TIPO_SEGNATURA] ([COD_TIPO])
);

