CREATE TABLE [dbo].[BANDO_PROGRAMMAZIONE] (
    [ID]                        INT IDENTITY (1, 1) NOT NULL,
    [ID_BANDO]                  INT NOT NULL,
    [ID_PROGRAMMAZIONE]         INT NOT NULL,
    [MISURA_PREVALENTE]         BIT CONSTRAINT [DF_BANDO_PROGRAMMAZIONE_MISURA_PREVALENTE] DEFAULT ((1)) NOT NULL,
    [ID_DISPOSIZIONI_ATTUATIVE] INT NULL,
    CONSTRAINT [PK_BANDO_PROGRAMMAZIONE] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_BANDO_PROGRAMMAZIONE_BANDO] FOREIGN KEY ([ID_BANDO]) REFERENCES [dbo].[BANDO] ([ID_BANDO]),
    CONSTRAINT [FK_BANDO_PROGRAMMAZIONE_zPROGRAMMAZIONE] FOREIGN KEY ([ID_PROGRAMMAZIONE]) REFERENCES [dbo].[zPROGRAMMAZIONE] ([ID])
);

