CREATE TABLE [dbo].[BANDO_RESPONSABILI] (
    [ID]        INT      IDENTITY (1, 1) NOT NULL,
    [ID_BANDO]  INT      NOT NULL,
    [ID_UTENTE] INT      NOT NULL,
    [PROVINCIA] CHAR (2) NULL,
    [ATTIVO]    BIT      CONSTRAINT [DF_BANDO_RESPONSABILI_ATTIVO] DEFAULT ((0)) NOT NULL,
    [DATA]      DATETIME NOT NULL,
    [OPERATORE] INT      NOT NULL,
    CONSTRAINT [PK_BANDO_RESPONSABILI] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_BANDO_RESPONSABILI_BANDO] FOREIGN KEY ([ID_BANDO]) REFERENCES [dbo].[BANDO] ([ID_BANDO])
);

