CREATE TABLE [dbo].[BANDO_TIPO_PAGAMENTO] (
    [ID_BANDO]         INT             NOT NULL,
    [COD_TIPO]         CHAR (3)        NOT NULL,
    [QUOTA_MAX]        DECIMAL (10, 2) NULL,
    [QUOTA_MIN]        DECIMAL (10, 2) NULL,
    [IMPORTO_MAX]      DECIMAL (18, 2) NULL,
    [IMPORTO_MIN]      DECIMAL (18, 2) NULL,
    [NUMERO]           INT             NOT NULL,
    [COD_TIPO_POLIZZA] CHAR (3)        NOT NULL,
    CONSTRAINT [PK_BANDO_TIPO_PAGAMENTO] PRIMARY KEY CLUSTERED ([ID_BANDO] ASC, [COD_TIPO] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_BANDO_TIPO_PAGAMENTO_BANDO] FOREIGN KEY ([ID_BANDO]) REFERENCES [dbo].[BANDO] ([ID_BANDO]),
    CONSTRAINT [FK_BANDO_TIPO_PAGAMENTO_TIPO_DOMANDA_PAGAMENTO] FOREIGN KEY ([COD_TIPO]) REFERENCES [dbo].[TIPO_DOMANDA_PAGAMENTO] ([COD_TIPO]),
    CONSTRAINT [FK_BANDO_TIPO_PAGAMENTO_TIPO_POLIZZA] FOREIGN KEY ([COD_TIPO_POLIZZA]) REFERENCES [dbo].[TIPO_POLIZZA] ([COD_TIPO_POLIZZA])
);

