CREATE TABLE [dbo].[BANDO_RELAZIONE_TECNICA] (
    [ID_PARAGRAFO] INT            IDENTITY (1, 1) NOT NULL,
    [ID_BANDO]     INT            NOT NULL,
    [DESCRIZIONE]  VARCHAR (2000) NULL,
    [TITOLO]       VARCHAR (100)  NOT NULL,
    [ORDINE]       INT            CONSTRAINT [DF_BANDO_RELAZIONE_TECNICA_ORDINE] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_BANDO_RELAZIONE_TECNICA] PRIMARY KEY CLUSTERED ([ID_PARAGRAFO] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_BANDO_RELAZIONE_TECNICA_BANDO] FOREIGN KEY ([ID_BANDO]) REFERENCES [dbo].[BANDO] ([ID_BANDO])
);

