CREATE TABLE [dbo].[CAA_OPERATORI] (
    [ID]                INT      IDENTITY (1, 1) NOT NULL,
    [CODICE_SPORTELLO]  CHAR (9) NOT NULL,
    [ID_UTENTE]         INT      NOT NULL,
    [ID_STORICO_ULTIMO] INT      NULL,
    CONSTRAINT [PK_CAA_OPERATORI] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_CAA_OPERATORI_CAA_SPORTELLO] FOREIGN KEY ([CODICE_SPORTELLO]) REFERENCES [dbo].[CAA_SPORTELLO] ([CODICE]),
    CONSTRAINT [FK_CAA_OPERATORI_UTENTI] FOREIGN KEY ([ID_UTENTE]) REFERENCES [dbo].[UTENTI] ([ID_UTENTE])
);

