CREATE TABLE [dbo].[CERTSP_CONTI] (
    [ID_CONTO]                  INT             IDENTITY (1, 1) NOT NULL,
    [ID_PROGETTO]               INT             NOT NULL,
    [ID_ATTO]                   INT             NOT NULL,
    [DATA_PRES_CONTAB]          DATETIME        NULL,
    [DATA_PRES_CONTI]           DATETIME        NULL,
    [TOT_REGISTRATE]            DECIMAL (18, 2) NULL,
    [TOT_SPESAPUB_REGISTRATE]   DECIMAL (18, 2) NULL,
    [TOT_PAGAMENTI_REGISTRATE]  DECIMAL (18, 2) NULL,
    [TOT_RITIRATA]              DECIMAL (18, 2) NULL,
    [TOT_SPESAPUB_RITIRATA]     DECIMAL (18, 2) NULL,
    [TOT_RECUPERATA]            DECIMAL (18, 2) NULL,
    [TOT_SPESAPUB_RECUPERATA]   DECIMAL (18, 2) NULL,
    [TOT_DARECUPERARE]          DECIMAL (18, 2) NULL,
    [TOT_SPESAPUB_DARECUPERARE] DECIMAL (18, 2) NULL,
    [TOT_NONRECUPERAB]          DECIMAL (18, 2) NULL,
    [TOT_SPESAPUB_NONRECUPERAB] DECIMAL (18, 2) NULL,
    [RECUPERATO_ART71]          DECIMAL (18, 2) NULL,
    [RECUPERATO_ART71_PUBBLICA] DECIMAL (18, 2) NULL,
    CONSTRAINT [PK_CERTSP_CONTI] PRIMARY KEY CLUSTERED ([ID_CONTO] ASC)
);

