CREATE TABLE [dbo].[CERTIFICAZIONE_CONTI](
	[ID_CERTIFICAZIONE_CONTI] [int] IDENTITY(1,1) NOT NULL,
	[ANNO_CONTABILE_DA] [datetime] NULL,
	[ANNO_CONTABILE_A] [datetime] NULL,
	[DATA_PRESENTAZIONE_CONTI] [datetime] NULL,
	[ISTANZA_CERTIFICAZIONE_CONTI] [xml] NULL,
	[CF_OPERATORE] [varchar](16) NULL,
	[FLAG_DEFINITIVO] [bit] NULL,
	[DATA_INSERIMENTO] [datetime] NULL,
	[DATA_MODIFICA] [datetime] NULL,
 CONSTRAINT [PK_CERTIFICAZIONE_CONTI] PRIMARY KEY CLUSTERED 
(
	[ID_CERTIFICAZIONE_CONTI] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[CERTIFICAZIONE_CONTI] ADD  CONSTRAINT [DF_CERTIFICAZIONE_CONTI_DATA_INSERIMENTO]  DEFAULT (getdate()) FOR [DATA_INSERIMENTO]
GO