CREATE TABLE [dbo].[CHECK_LIST_X_STEP] (
    [ID_CHECK_LIST]       INT             NOT NULL,
    [ID_STEP]             INT             NOT NULL,
    [ORDINE]              INT             NULL,
    [OBBLIGATORIO]        BIT             CONSTRAINT [DF_CHECK_LIST_X_STEP_OBBLIGATORIO] DEFAULT ((0)) NOT NULL,
    [PESO]                DECIMAL (10, 2) NULL,
    [INCLUDI_VERBALE_VIS] BIT             CONSTRAINT [DF_CHECK_LIST_X_STEP_INCLUDI_VERBALE_VIS] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_CHECK_LIST_X_STEP] PRIMARY KEY CLUSTERED ([ID_CHECK_LIST] ASC, [ID_STEP] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_CHECK_LIST_X_STEP_CHECK_LIST] FOREIGN KEY ([ID_CHECK_LIST]) REFERENCES [dbo].[CHECK_LIST] ([ID_CHECK_LIST]),
    CONSTRAINT [FK_CHECK_LIST_X_STEP_STEP] FOREIGN KEY ([ID_STEP]) REFERENCES [dbo].[STEP] ([ID_STEP])
);

