CREATE TABLE [dbo].[CITTADINANZA] (
    [ID_CITTADINANZA] INT          IDENTITY (1, 1) NOT NULL,
    [DESCRIZIONE]     VARCHAR (80) NOT NULL,
    CONSTRAINT [PK_CITTADINANZA] PRIMARY KEY CLUSTERED ([ID_CITTADINANZA] ASC) WITH (FILLFACTOR = 100)
);

