CREATE TABLE [dbo].[CntrLoco_Dettaglio] (
    [IdLoco_Dettaglio]                       INT             IDENTITY (1, 1) NOT NULL,
    [IdLoco]                                 INT             NOT NULL,
    [Id_Domanda_Pagamento]                   INT             NOT NULL,
    [Id_Progetto]                            INT             NOT NULL,
    [Asse]                                   VARCHAR (20)    NOT NULL,
    [Selezionata]                            BIT             NOT NULL,
    [Esito]                                  CHAR (1)        NULL,
    [DataEsito]                              DATETIME        NULL,
    [CostoTotale]                            DECIMAL (18, 2) NULL,
    [ImportoAmmesso]                         DECIMAL (18, 2) NULL,
    [ImportoConcesso]                        DECIMAL (18, 2) NULL,
    [NrOperazioniB]                          INT             NULL,
    [Beneficiario]                           VARCHAR (155)   NULL,
    [SpesaAmmessa]                           DECIMAL (18, 2) NULL,
    [ImportoContributoPubblico]              DECIMAL (18, 2) NULL,
    [SpesaAmmessa_Incrementale]              DECIMAL (18, 2) NULL,
    [ImportoContributoPubblico_Incrementale] DECIMAL (18, 2) NULL,
    [Esclusione]                             VARCHAR (50)    NULL,
    [RischioIR]                              DECIMAL (6, 2)  NULL,
    [RischioCR]                              DECIMAL (6, 2)  NULL,
    [RischioComp]                            VARCHAR (10)    NULL,
    [Operatore]                              VARCHAR (16)    NULL,
    [DataInserimento]                        DATETIME        NOT NULL,
    [DataModifica]                           DATETIME        NOT NULL,
    [Azione]                                 VARCHAR (20)    NULL,
    [Intervento]                             VARCHAR (20)    NULL,
    CONSTRAINT [PK_CntrLoco_Dettaglio] PRIMARY KEY CLUSTERED ([IdLoco_Dettaglio] ASC),
    CONSTRAINT [FK_CntrLoco_Dettaglio_CntrLoco_Testa] FOREIGN KEY ([IdLoco]) REFERENCES [dbo].[CntrLoco_Testa] ([IdLoco]),
    CONSTRAINT [FK_CntrLoco_Dettaglio_DOMANDA_DI_PAGAMENTO] FOREIGN KEY ([Id_Domanda_Pagamento]) REFERENCES [dbo].[DOMANDA_DI_PAGAMENTO] ([ID_DOMANDA_PAGAMENTO])
);

