CREATE TABLE [dbo].[CODIFICA_INVESTIMENTO] (
    [ID_CODIFICA_INVESTIMENTO] INT             IDENTITY (1, 1) NOT NULL,
    [ID_BANDO]                 INT             NOT NULL,
    [COD_TP]                   CHAR (2)        NULL,
    [DESCRIZIONE]              VARCHAR (255)   NULL,
    [AIUTO_MINIMO]             DECIMAL (10, 2) NULL,
    [CODICE]                   CHAR (2)        NULL,
    [IS_MAX]                   BIT             NULL,
    [QUERY_SQL]                VARCHAR (3000)  NULL,
    [AIUTO_MINIMO_ALTREFONTI]  DECIMAL (10, 2) NULL,
    [QUERY_SQL_ALTREFONTI]     VARCHAR (3000)  NULL,
    CONSTRAINT [PK_CODIFICA_INVESTIMENTO] PRIMARY KEY CLUSTERED ([ID_CODIFICA_INVESTIMENTO] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_CODIFICA_INVESTIMENTO_BANDO] FOREIGN KEY ([ID_BANDO]) REFERENCES [dbo].[BANDO] ([ID_BANDO])
);

