CREATE TABLE [dbo].[CODICI_IPA] (
    [CODICE_AMM]      VARCHAR (30)  NULL,
    [DESC_AMM]        VARCHAR (500) NULL,
    [COMUNE]          VARCHAR (255) NULL,
    [CAP]             VARCHAR (10)  NULL,
    [SIGLA_PROVINCIA] VARCHAR (4)   NULL,
    [REGIONE]         VARCHAR (30)  NULL,
    [INDIRIZZO]       VARCHAR (255) NULL,
    [TIPOLOGIA_ISTAT] VARCHAR (100) NULL,
    [TIPOLOGIA_AMM]   VARCHAR (100) NULL,
    [ACRONIMO]        VARCHAR (60)  NULL,
    [CF_VALIDATO]     VARCHAR (2)   NULL,
    [CODICE_FISCALE]  VARCHAR (30)  NULL
);

