CREATE TABLE [dbo].[COLLABORATORI_X_BANDO] (
    [ID_COLLABORATORE]        INT      IDENTITY (1, 1) NOT NULL,
    [ID_BANDO]                INT      NOT NULL,
    [ID_PROGETTO]             INT      NOT NULL,
    [ID_UTENTE]               INT      NOT NULL,
    [PROVINCIA]               CHAR (2) NOT NULL,
    [OPERATORE_INSERIMENTO]   INT      NOT NULL,
    [DATA_INSERIMENTO]        DATETIME NOT NULL,
    [OPERATORE_FINE_VALIDITA] INT      NULL,
    [DATA_FINE_VALIDITA]      DATETIME NULL,
    [ATTIVO]                  BIT      CONSTRAINT [DF_COLLABORATORI_X_BANDO_ATTIVO] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_COLLABORATORI_X_BANDO] PRIMARY KEY NONCLUSTERED ([ID_COLLABORATORE] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_COLLABORATORI_X_BANDO_BANDO] FOREIGN KEY ([ID_BANDO]) REFERENCES [dbo].[BANDO] ([ID_BANDO]),
    CONSTRAINT [FK_COLLABORATORI_X_BANDO_PROGETTO] FOREIGN KEY ([ID_PROGETTO]) REFERENCES [dbo].[PROGETTO] ([ID_PROGETTO])
);


GO
CREATE CLUSTERED INDEX [IX_COLLABORATORI_X_BANDO_1]
    ON [dbo].[COLLABORATORI_X_BANDO]([ID_PROGETTO] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IX_COLLABORATORI_X_BANDO]
    ON [dbo].[COLLABORATORI_X_BANDO]([ID_BANDO] ASC) WITH (FILLFACTOR = 80);

