CREATE TABLE [dbo].[CONTROLLI_LOCO_LOTTO] (
    [ID_LOTTO]           INT           IDENTITY (1, 1) NOT NULL,
    [DATA_CREAZIONE]     DATETIME      NOT NULL,
    [DATA_MODIFICA]      DATETIME      NOT NULL,
    [OPERATORE]          VARCHAR (16)  NOT NULL,
    [DATA_ESTRAZIONE]    DATETIME      NULL,
    [NUMERO_ESTRAZIONI]  INT           CONSTRAINT [DF_CONTROLLI_LOCO_LOTTO_NUMERO_ESTRAZIONI] DEFAULT ((0)) NOT NULL,
    [CONTROLLO_CONCLUSO] BIT           CONSTRAINT [DF_CONTROLLI_LOCO_LOTTO_CONTROLLO_CONCLUSO] DEFAULT ((0)) NOT NULL,
    [SEGNATURA]          VARCHAR (100) NULL,
    [ID_PROGRAMMAZIONE]  INT           NOT NULL,
    [NOTE]               NTEXT         NULL,
    CONSTRAINT [PK_CONTROLLI_LOCO_LOTTO] PRIMARY KEY CLUSTERED ([ID_LOTTO] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_CONTROLLI_LOCO_LOTTO_zPROGRAMMAZIONE] FOREIGN KEY ([ID_PROGRAMMAZIONE]) REFERENCES [dbo].[zPROGRAMMAZIONE] ([ID])
);

