CREATE TABLE [dbo].[CONTROLLI_PARAMETRI_X_DOMANDA] (
    [ID_DOMANDA_PAGAMENTO] INT          NOT NULL,
    [ID_PARAMETRO]         INT          NOT NULL,
    [ID_LOTTO]             INT          NOT NULL,
    [PUNTEGGIO]            INT          NULL,
    [DATA_VALUTAZIONE]     DATETIME     NULL,
    [OPERATORE]            VARCHAR (16) NULL,
    CONSTRAINT [PK_CONTROLLI_PARAMETRI_X_DOMANDA] PRIMARY KEY CLUSTERED ([ID_DOMANDA_PAGAMENTO] ASC, [ID_PARAMETRO] ASC, [ID_LOTTO] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_CONTROLLI_PARAMETRI_X_DOMANDA_CONTROLLI_DOMANDE_PAGAMENTO] FOREIGN KEY ([ID_LOTTO], [ID_DOMANDA_PAGAMENTO]) REFERENCES [dbo].[CONTROLLI_DOMANDE_PAGAMENTO] ([ID_LOTTO], [ID_DOMANDA_PAGAMENTO]),
    CONSTRAINT [FK_CONTROLLI_PARAMETRI_X_DOMANDA_CONTROLLI_PARAMETRI_X_LOTTO] FOREIGN KEY ([ID_LOTTO], [ID_PARAMETRO]) REFERENCES [dbo].[CONTROLLI_PARAMETRI_X_LOTTO] ([ID_LOTTO], [ID_PARAMETRO])
);

