CREATE TABLE [dbo].[CONTROLLI_DOMANDE_PAGAMENTO] (
    [ID_LOTTO]                 INT             NOT NULL,
    [ID_DOMANDA_PAGAMENTO]     INT             NOT NULL,
    [OPERATORE_ASSEGNATO]      VARCHAR (16)    NULL,
    [SELEZIONATA_X_CONTROLLO]  BIT             CONSTRAINT [DF_CONTROLLI_DOMANDE_PAGAMENTO_SELEZIONATA_X_CONTROLLO] DEFAULT ((0)) NOT NULL,
    [TIPO_ESTRAZIONE]          CHAR (1)        NULL,
    [VALORE_DI_RISCHIO]        DECIMAL (10, 4) NULL,
    [CLASSE_DI_RISCHIO]        CHAR (1)        NULL,
    [ORDINE_CLASSE_DI_RISCHIO] INT             NULL,
    [CONTRIBUTO_RICHIESTO]     DECIMAL (18, 2) NULL,
    [DATA_MODIFICA]            DATETIME        NULL,
    [OPERATORE]                VARCHAR (16)    NULL,
    [CONTROLLO_CONCLUSO]       BIT             CONSTRAINT [DF_CONTROLLI_DOMANDE_PAGAMENTO_CONTROLLO_CONCLUSO] DEFAULT ((0)) NOT NULL,
    [OGGETTO_DI_CONTROLLO]     BIT             CONSTRAINT [DF_CONTROLLI_DOMANDE_PAGAMENTO_OGGETTO_DI_CONTROLLO] DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PK_CONTROLLI_DOMANDE_PAGAMENTO] PRIMARY KEY CLUSTERED ([ID_LOTTO] ASC, [ID_DOMANDA_PAGAMENTO] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_CONTROLLI_DOMANDE_PAGAMENTO_CONTROLLI_LOCO_LOTTO] FOREIGN KEY ([ID_LOTTO]) REFERENCES [dbo].[CONTROLLI_LOCO_LOTTO] ([ID_LOTTO]),
    CONSTRAINT [FK_CONTROLLI_DOMANDE_PAGAMENTO_DOMANDA_DI_PAGAMENTO] FOREIGN KEY ([ID_DOMANDA_PAGAMENTO]) REFERENCES [dbo].[DOMANDA_DI_PAGAMENTO] ([ID_DOMANDA_PAGAMENTO])
);

