CREATE TABLE [dbo].[DECRETI_X_DOM_PAG_ESPORTAZIONE] (
    [ID_DECRETI_X_DOM_PAG_ESPORTAZIONE] INT             IDENTITY (1, 1) NOT NULL,
    [ID_DOMANDA_PAGAMENTO]              INT             NOT NULL,
    [ID_PROGETTO]                       INT             NOT NULL,
    [ID_DECRETO]                        INT             NOT NULL,
    [IMPORTO]                           DECIMAL (18, 2) NULL,
    [DATA_INSERIMENTO]                  DATETIME        CONSTRAINT [DF_DECRETI_X_DOM_PAG_ESPORTAZIONE_DATA_INSERIMENTO] DEFAULT (getdate()) NOT NULL,
    [DATA_MODIFICA]                     DATETIME        CONSTRAINT [DF_DECRETI_X_DOM_PAG_ESPORTAZIONE_DATA_MODIFICA] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_DECRETI_X_DOM_PAG_ESPORTAZIONE] PRIMARY KEY CLUSTERED ([ID_DECRETI_X_DOM_PAG_ESPORTAZIONE] ASC),
    CONSTRAINT [FK_DECRETI_X_DOM_PAG_ESPORTAZIONE_ATTI] FOREIGN KEY ([ID_DECRETO]) REFERENCES [dbo].[ATTI] ([ID_ATTO]),
    CONSTRAINT [FK_DECRETI_X_DOM_PAG_ESPORTAZIONE_DOMANDA_DI_PAGAMENTO_ESPORTAZIONE] FOREIGN KEY ([ID_DOMANDA_PAGAMENTO], [ID_PROGETTO]) REFERENCES [dbo].[DOMANDA_DI_PAGAMENTO_ESPORTAZIONE] ([ID_DOMANDA_PAGAMENTO], [ID_PROGETTO]),
    CONSTRAINT [IX_DECRETI_X_DOM_PAG_ESPORTAZIONE] UNIQUE NONCLUSTERED ([ID_DOMANDA_PAGAMENTO] ASC, [ID_PROGETTO] ASC, [ID_DECRETO] ASC)
);

