CREATE TABLE [dbo].[DOCUMENTI] (
    [ID_DOCUMENTO]       INT            IDENTITY (1, 1) NOT NULL,
    [TITOLO]             VARCHAR (500)  NULL,
    [DESCRIZIONE]        VARCHAR (1000) NULL,
    [DATA_MODIFICA]      DATETIME       NULL,
    [OPERATORE]          VARCHAR (16)   NULL,
    [DATA_FINE_VALIDITA] DATETIME       NULL,
    CONSTRAINT [PK_DOCUMENTI] PRIMARY KEY CLUSTERED ([ID_DOCUMENTO] ASC) WITH (FILLFACTOR = 80)
);

