CREATE TABLE [dbo].[DOMANDA_PAGAMENTO_REQUISITI] (
    [ID_DOMANDA_PAGAMENTO] INT             NOT NULL,
    [ID_REQUISITO]         INT             NOT NULL,
    [ID_VALORE]            INT             NULL,
    [VAL_NUMERICO]         DECIMAL (18, 2) NULL,
    [VAL_DATA]             DATETIME        NULL,
    [VAL_TESTO]            VARCHAR (500)   NULL,
    [ESITO]                CHAR (2)        NULL,
    [DATA_ESITO]           DATETIME        NULL,
    [SELEZIONATO]          BIT             CONSTRAINT [DF_DOMANDA_PAGAMENTO_REQUISITI_SELEZIONATO] DEFAULT ((0)) NULL,
    CONSTRAINT [PK_DOMANDA_PAGAMENTO_REQUISITI] PRIMARY KEY CLUSTERED ([ID_DOMANDA_PAGAMENTO] ASC, [ID_REQUISITO] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_DOMANDA_PAGAMENTO_REQUISITI_DOMANDA_DI_PAGAMENTO] FOREIGN KEY ([ID_DOMANDA_PAGAMENTO]) REFERENCES [dbo].[DOMANDA_DI_PAGAMENTO] ([ID_DOMANDA_PAGAMENTO]),
    CONSTRAINT [FK_DOMANDA_PAGAMENTO_REQUISITI_REQUISITI_PAGAMENTO] FOREIGN KEY ([ID_REQUISITO]) REFERENCES [dbo].[REQUISITI_PAGAMENTO] ([ID_REQUISITO]),
    CONSTRAINT [FK_DOMANDA_PAGAMENTO_REQUISITI_REQUISITI_PAGAMENTO_PLURIVALORE] FOREIGN KEY ([ID_VALORE]) REFERENCES [dbo].[REQUISITI_PAGAMENTO_PLURIVALORE] ([ID_VALORE])
);

