CREATE TABLE [dbo].[DOMANDA_DI_PAGAMENTO] (
    [ID_DOMANDA_PAGAMENTO]             INT            IDENTITY (1, 1) NOT NULL,
    [COD_TIPO]                         CHAR (3)       NOT NULL,
    [ID_PROGETTO]                      INT            NOT NULL,
    [DATA_INSERIMENTO]                 DATETIME       NOT NULL,
    [CF_OPERATORE]                     VARCHAR (16)   NOT NULL,
    [DATA_MODIFICA]                    DATETIME       NOT NULL,
    [COD_ENTE]                         VARCHAR (10)   NULL,
    [SEGNATURA]                        VARCHAR (100)  NULL,
    [SEGNATURA_ALLEGATI]               VARCHAR (100)  NULL,
    [ID_FIDEJUSSIONE]                  INT            NULL,
    [DATA_CERTIFICAZIONE_ANTIMAFIA]    DATETIME       NULL,
    [APPROVATA]                        BIT            NULL,
    [SEGNATURA_APPROVAZIONE]           VARCHAR (100)  NULL,
    [SEGNATURA_SECONDA_APPROVAZIONE]   VARCHAR (100)  NULL,
    [CF_ISTRUTTORE]                    VARCHAR (16)   NULL,
    [DATA_APPROVAZIONE]                DATETIME       NULL,
    [VALUTAZIONE_ISTRUTTORE]           NTEXT          NULL,
    [ANNULLATA]                        BIT            CONSTRAINT [DF_DOMANDA_DI_PAGAMENTO_ANNULLATA] DEFAULT ((0)) NOT NULL,
    [SEGNATURA_ANNULLAMENTO]           VARCHAR (100)  NULL,
    [CF_OPERATORE_ANNULLAMENTO]        VARCHAR (16)   NULL,
    [DATA_ANNULLAMENTO]                DATETIME       NULL,
    [VALIDITA_VERSIONE_ADC]            BIT            CONSTRAINT [DF_DOMANDA_DI_PAGAMENTO_VALIDITA_VERSIONE_ADC] DEFAULT ((0)) NOT NULL,
    [ID_VARIAZIONE_ACCERTATA]          INT            NULL,
    [PREDISPOSTA_A_CONTROLLO]          BIT            CONSTRAINT [DF_DOMANDA_DI_PAGAMENTO_PREDISPOSTA_A_CONTROLLO] DEFAULT ((0)) NOT NULL,
    [DATA_PREDISPOSIZIONE_A_CONTROLLO] DATETIME       NULL,
    [VISITA_INSITU_ESITO]              CHAR (2)       NULL,
    [VISITA_INSITU_NOTE]               NTEXT          NULL,
    [CONTROLLO_INLOCO_ESITO]           CHAR (2)       NULL,
    [CONTROLLO_INLOCO_NOTE]            NTEXT          NULL,
    [VERIFICA_PAGAMENTI_ESITO]         CHAR (1)       NULL,
    [VERIFICA_PAGAMENTI_MESSAGGIO]     VARCHAR (3000) NULL,
    [VERIFICA_PAGAMENTI_DATA]          DATETIME       NULL,
    [FIRMA_PREDISPOSTA]                BIT            CONSTRAINT [DF_DOMANDA_DI_PAGAMENTO_FIRMA_PREDISPOSTA] DEFAULT ((0)) NULL,
    [FIRMA_PREDISPOSTA_RUP]            BIT            CONSTRAINT [DF_DOMANDA_DI_PAGAMENTO_FIRMA_PREDISPOSTA1] DEFAULT ((0)) NULL,
    [IN_INTEGRAZIONE]                  BIT            CONSTRAINT [DF_DOMANDA_DI_PAGAMENTO_IN_INTEGRAZIONE] DEFAULT ((0)) NULL,
    CONSTRAINT [PK_DOMANDA_DI_PAGAMENTO] PRIMARY KEY CLUSTERED ([ID_DOMANDA_PAGAMENTO] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_DOMANDA_DI_PAGAMENTO_FIDEJUSSIONI] FOREIGN KEY ([ID_FIDEJUSSIONE]) REFERENCES [dbo].[FIDEJUSSIONI] ([ID_FIDEJUSSIONE]),
    CONSTRAINT [FK_DOMANDA_DI_PAGAMENTO_PROGETTO] FOREIGN KEY ([ID_PROGETTO]) REFERENCES [dbo].[PROGETTO] ([ID_PROGETTO]),
    CONSTRAINT [FK_DOMANDA_DI_PAGAMENTO_TIPO_DOMANDA_PAGAMENTO] FOREIGN KEY ([COD_TIPO]) REFERENCES [dbo].[TIPO_DOMANDA_PAGAMENTO] ([COD_TIPO])
);


GO
CREATE NONCLUSTERED INDEX [IX_DOMANDA_DI_PAGAMENTO]
    ON [dbo].[DOMANDA_DI_PAGAMENTO]([ID_PROGETTO] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IX_DOMANDA_DI_PAGAMENTO_1]
    ON [dbo].[DOMANDA_DI_PAGAMENTO]([COD_TIPO] ASC) WITH (FILLFACTOR = 80);

