CREATE TABLE [dbo].[DOMANDA_DI_PAGAMENTO_SEGNATURE] (
    [ID_DOMANDA_PAGAMENTO] INT           NOT NULL,
    [COD_TIPO]             CHAR (3)      NOT NULL,
    [DATA]                 DATETIME      NOT NULL,
    [OPERATORE]            CHAR (16)     NOT NULL,
    [SEGNATURA]            VARCHAR (100) NOT NULL,
    [MOTIVAZIONE]          NTEXT         NULL,
    [RIAPRI_DOMANDA]       BIT           CONSTRAINT [DF_DOMANDA_DI_PAGAMENTO_SEGNATURE_RIAPRI_DOMANDA] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_DOMANDA_DI_PAGAMENTO_SEGNATURE] PRIMARY KEY CLUSTERED ([ID_DOMANDA_PAGAMENTO] ASC, [COD_TIPO] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_DOMANDA_DI_PAGAMENTO_SEGNATURE_DOMANDA_DI_PAGAMENTO] FOREIGN KEY ([ID_DOMANDA_PAGAMENTO]) REFERENCES [dbo].[DOMANDA_DI_PAGAMENTO] ([ID_DOMANDA_PAGAMENTO]),
    CONSTRAINT [FK_DOMANDA_DI_PAGAMENTO_SEGNATURE_TIPO_SEGNATURA] FOREIGN KEY ([COD_TIPO]) REFERENCES [dbo].[TIPO_SEGNATURA] ([COD_TIPO])
);

