CREATE TABLE [dbo].[ESITI_STEP] (
    [COD_ESITO]      CHAR (2)     NOT NULL,
    [DESCRIZIONE]    VARCHAR (50) NOT NULL,
    [ESITO_POSITIVO] BIT          NULL,
    CONSTRAINT [PK_ESITI_STEP] PRIMARY KEY CLUSTERED ([COD_ESITO] ASC) WITH (FILLFACTOR = 100)
);

