CREATE TABLE [dbo].[GANTT_PASSI_TIPIOPERAZIONI] (
    [ID_TIPOOP] INT NOT NULL,
    [ID_PASSO]  INT NOT NULL,
    [ORDINE]    INT NULL,
    CONSTRAINT [PK_GANTT_PASSI_TIPIOPERAZIONI] PRIMARY KEY CLUSTERED ([ID_TIPOOP] ASC, [ID_PASSO] ASC),
    CONSTRAINT [FK_GANTT_PASSI_TIPIOPERAZIONI_TIPO_GANTT_PASSI] FOREIGN KEY ([ID_PASSO]) REFERENCES [dbo].[TIPO_GANTT_PASSI] ([ID_PASSO]) ON UPDATE CASCADE,
    CONSTRAINT [FK_GANTT_PASSI_TIPIOPERAZIONI_TIPO_GANTT_TIPIOPERAZIONE] FOREIGN KEY ([ID_TIPOOP]) REFERENCES [dbo].[TIPO_GANTT_TIPIOPERAZIONE] ([ID_TIPOOP]) ON UPDATE CASCADE
);

