CREATE TABLE [dbo].[GRADUATORIA_PROGETTI_DETTAGLIO] (
    [ID_PRIORITA]      INT             NOT NULL,
    [ID_PROGETTO]      INT             NOT NULL,
    [PUNTEGGIO]        DECIMAL (10, 6) NULL,
    [DATA_VALUTAZIONE] DATETIME        NULL,
    [OPERATORE]        VARCHAR (16)    NULL,
    [MODIFICA_MANUALE] BIT             NULL,
    CONSTRAINT [PK_GRADUATORIA_PROGETTI_DETTAGLIO] PRIMARY KEY CLUSTERED ([ID_PRIORITA] ASC, [ID_PROGETTO] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_GRADUATORIA_PROGETTI_DETTAGLIO_PRIORITA] FOREIGN KEY ([ID_PRIORITA]) REFERENCES [dbo].[PRIORITA] ([ID_PRIORITA]),
    CONSTRAINT [FK_GRADUATORIA_PROGETTI_DETTAGLIO_PROGETTO] FOREIGN KEY ([ID_PROGETTO]) REFERENCES [dbo].[PROGETTO] ([ID_PROGETTO])
);

