CREATE TABLE [dbo].[IMPRESA_STORICO] (
    [ID_STORICO_IMPRESA]      INT                 IDENTITY (1, 1) NOT NULL,
    [ID_IMPRESA]              INT                 NOT NULL,
    [DATA_INIZIO_VALIDITA]    DATETIME            CONSTRAINT [DF_IMPRESA_STORICO_DATA_INIZIO_VALIDITA] DEFAULT (getdate()) NOT NULL,
    [DATA_FINE_VALIDITA]      DATETIME            NULL,
    [RAGIONE_SOCIALE]         [dbo].[DESCRIZIONE] NOT NULL,
    [CODICE_INPS]             VARCHAR (15)        NULL,
    [COD_FORMA_GIURIDICA]     VARCHAR (10)        NULL,
    [ID_DIMENSIONE]           INT                 NULL,
    [REGISTRO_IMPRESE_NUMERO] VARCHAR (16)        NULL,
    [REA_NUMERO]              VARCHAR (20)        NULL,
    [REA_ANNO]                INT                 NULL,
    [COD_CLASSIFICAZIONE_UMA] VARCHAR (3)         NULL,
    [ATTIVA]                  BIT                 CONSTRAINT [DF_IMPRESA_STORICO_ATTIVA] DEFAULT ((1)) NOT NULL,
    [DATA_CESSAZIONE]         DATETIME            NULL,
    [SEGNATURA_CESSAZIONE]    VARCHAR (100)       NULL,
    [COD_TIPO_CESSAZIONE]     CHAR (1)            NULL,
    [COD_ATECO2007]           CHAR (9)            NULL,
    CONSTRAINT [PK_IMPRESA_STORICO] PRIMARY KEY CLUSTERED ([ID_STORICO_IMPRESA] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_IMPRESA_STORICO_DIMENSIONE_IMPRESA] FOREIGN KEY ([ID_DIMENSIONE]) REFERENCES [dbo].[DIMENSIONE_IMPRESA] ([ID_DIMENSIONE]),
    CONSTRAINT [FK_IMPRESA_STORICO_FORMA_GIURIDICA] FOREIGN KEY ([COD_FORMA_GIURIDICA]) REFERENCES [dbo].[FORMA_GIURIDICA] ([COD_ISTAT]),
    CONSTRAINT [FK_IMPRESA_STORICO_IMPRESA] FOREIGN KEY ([ID_IMPRESA]) REFERENCES [dbo].[IMPRESA] ([ID_IMPRESA])
);


GO
CREATE NONCLUSTERED INDEX [IX_IMPRESA_STORICO]
    ON [dbo].[IMPRESA_STORICO]([ID_IMPRESA] ASC) WITH (FILLFACTOR = 80);

