CREATE TABLE [dbo].[INTEGRAZIONI_PER_DOMANDA_DI_PAGAMENTO] (
    [ID_INTEGRAZIONE_DOMANDA_DI_PAGAMENTO] INT           IDENTITY (1, 1) NOT NULL,
    [ID_DOMANDA_PAGAMENTO]                 INT           NOT NULL,
    [DATA_INSERIMENTO]                     DATETIME      CONSTRAINT [DF_INTEGRAZIONE_DOMANDA_DI_PAGAMENTO_DATA_CREAZIONE] DEFAULT (getdate()) NOT NULL,
    [DATA_MODIFICA]                        DATETIME      CONSTRAINT [DF_INTEGRAZIONI_PER_DOMANDA_DI_PAGAMENTO_DATA_MODIFICA] DEFAULT (getdate()) NULL,
    [ISTANZA_DOMANDA_PAGAMENTO]            XML           NULL,
    [INTEGRAZIONE_COMPLETA]                BIT           CONSTRAINT [DF_INTEGRAZIONE_DOMANDA_DI_PAGAMENTO_COMPLETA] DEFAULT ((0)) NULL,
    [NOTE_INTEGRAZIONE_DOMANDA]            VARCHAR (MAX) NULL,
    [CF_ISTRUTTORE]                        VARCHAR (16)  NULL,
    [DATA_RICHIESTA_INTEGRAZIONE_DOMANDA]  DATETIME      NULL,
    [SEGNATURA_ISTRUTTORE]                 VARCHAR (100) NULL,
    [CF_BENFICIARIO]                       VARCHAR (16)  NULL,
    [SEGNATURA_BENEFICIARIO]               VARCHAR (100) NULL,
    [DATA_CONCLUSIONE_INTEGRAZIONE]        DATETIME      NULL,
    CONSTRAINT [PK_INTEGRAZIONE_DOMANDA_DI_PAGAMENTO] PRIMARY KEY CLUSTERED ([ID_INTEGRAZIONE_DOMANDA_DI_PAGAMENTO] ASC),
    CONSTRAINT [FK_INTEGRAZIONI_PER_DOMANDA_DI_PAGAMENTO_DOMANDA_DI_PAGAMENTO] FOREIGN KEY ([ID_DOMANDA_PAGAMENTO]) REFERENCES [dbo].[DOMANDA_DI_PAGAMENTO] ([ID_DOMANDA_PAGAMENTO])
);

