CREATE TABLE [dbo].[LOTTO_DI_REVISIONE] (
    [ID_LOTTO]           INT          IDENTITY (1, 1) NOT NULL,
    [ID_BANDO]           INT          NOT NULL,
    [PROVINCIA]          CHAR (2)     NOT NULL,
    [DATA_CREAZIONE]     DATETIME     NOT NULL,
    [CF_OPERATORE]       VARCHAR (16) NOT NULL,
    [DATA_MODIFICA]      DATETIME     NOT NULL,
    [NUMERO_ESTRAZIONI]  INT          CONSTRAINT [DF_LOTTO_DI_REVISIONE_NUMERO_ESTRAZIONI] DEFAULT ((0)) NOT NULL,
    [REVISIONE_CONCLUSA] BIT          CONSTRAINT [DF_LOTTO_DI_REVISIONE_REVISIONE_CONCLUSA] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_LOTTO_DI_REVISIONE] PRIMARY KEY CLUSTERED ([ID_LOTTO] ASC) WITH (FILLFACTOR = 80)
);

