CREATE TABLE [dbo].[MANDATI_IMPRESA] (
    [ID]                   INT           IDENTITY (1, 1) NOT NULL,
    [ID_IMPRESA]           INT           NOT NULL,
    [ID_UTENTE_ABILITATO]  INT           NULL,
    [COD_ENTE]             VARCHAR (10)  NULL,
    [CODICE_SPORTELLO_CAA] CHAR (9)      NULL,
    [TIPO_MANDATO]         CHAR (3)      CONSTRAINT [DF_MANDATI_IMPRESA_MANDATO_PSR] DEFAULT ((0)) NOT NULL,
    [ATTIVO]               BIT           CONSTRAINT [DF_MANDATI_IMPRESA_ATTIVO] DEFAULT ((0)) NOT NULL,
    [DATA_INIZIO_VALIDITA] DATETIME      NOT NULL,
    [DATA_FINE_VALIDITA]   DATETIME      NULL,
    [ID_OPERATORE_INIZIO]  INT           NOT NULL,
    [ID_OPERATORE_FINE]    INT           NULL,
    [SEGNATURA_MANDATO]    VARCHAR (100) NULL,
    [SEGNATURA_REVOCA]     VARCHAR (100) NULL,
    CONSTRAINT [PK_MANDATI_IMPRESA] PRIMARY KEY NONCLUSTERED ([ID] ASC) WITH (FILLFACTOR = 80)
);


GO
CREATE CLUSTERED INDEX [IX_MANDATI_IMPRESA]
    ON [dbo].[MANDATI_IMPRESA]([ID_IMPRESA] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IX_MANDATI_IMPRESA_1]
    ON [dbo].[MANDATI_IMPRESA]([ID_UTENTE_ABILITATO] ASC, [ATTIVO] ASC)
    INCLUDE([ID_IMPRESA], [TIPO_MANDATO]) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IX_MANDATI_IMPRESA_2]
    ON [dbo].[MANDATI_IMPRESA]([COD_ENTE] ASC, [ATTIVO] ASC)
    INCLUDE([ID_IMPRESA], [TIPO_MANDATO]) WITH (FILLFACTOR = 80);

