CREATE TABLE [dbo].[NOTE] (
    [ID]    INT            IDENTITY (1, 1) NOT NULL,
    [TESTO] NVARCHAR (MAX) NOT NULL,
    CONSTRAINT [PK_NOTE] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 80)
);

