CREATE TABLE [dbo].[PERSONA_FISICA] (
    [ID_PERSONA]        INT                 IDENTITY (1, 1) NOT NULL,
    [NOME]              [dbo].[DESCRIZIONE] NULL,
    [COGNOME]           [dbo].[DESCRIZIONE] NULL,
    [CODICE_FISCALE]    VARCHAR (16)        NOT NULL,
    [SESSO]             CHAR (1)            NULL,
    [DATA_NASCITA]      DATETIME            NULL,
    [ID_COMUNE_NASCITA] INT                 NULL,
    [ID_CITTADINANZA]   INT                 NULL,
    CONSTRAINT [PK_PERSONA_FISICA] PRIMARY KEY CLUSTERED ([ID_PERSONA] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_PERSONA_FISICA_CITTADINANZA] FOREIGN KEY ([ID_CITTADINANZA]) REFERENCES [dbo].[CITTADINANZA] ([ID_CITTADINANZA])
);


GO
CREATE NONCLUSTERED INDEX [IX_PERSONA_FISICA]
    ON [dbo].[PERSONA_FISICA]([CODICE_FISCALE] ASC) WITH (FILLFACTOR = 80);

