CREATE TABLE [dbo].[PIANO_INVESTIMENTI] (
    [ID_INVESTIMENTO]              INT             IDENTITY (1, 1) NOT NULL,
    [ID_PROGETTO]                  INT             NOT NULL,
    [ID_PROGRAMMAZIONE]            INT             NOT NULL,
    [DESCRIZIONE]                  VARCHAR (2000)  NOT NULL,
    [DATA_VARIAZIONE]              DATETIME        NULL,
    [OPERATORE_VARIAZIONE]         VARCHAR (16)    NULL,
    [COD_TIPO_INVESTIMENTO]        INT             NOT NULL,
    [COD_STP]                      VARCHAR (10)    NULL,
    [ID_UNITA_MISURA]              INT             NULL,
    [QUANTITA]                     DECIMAL (10, 2) NULL,
    [COSTO_INVESTIMENTO]           DECIMAL (15, 2) NOT NULL,
    [SPESE_GENERALI]               DECIMAL (15, 2) NULL,
    [CONTRIBUTO_RICHIESTO]         DECIMAL (15, 2) NULL,
    [QUOTA_CONTRIBUTO_RICHIESTO]   DECIMAL (10, 2) NOT NULL,
    [CONTRIBUTO_ALTRE_FONTI]       DECIMAL (15, 2) NULL,
    [QUOTA_CONTRIBUTO_ALTRE_FONTI] DECIMAL (15, 2) NULL,
    [TASSO_ABBUONO]                DECIMAL (10, 2) NULL,
    [ID_SETTORE_PRODUTTIVO]        INT             NULL,
    [ID_PRIORITA_SETTORIALE]       INT             NULL,
    [ID_OBIETTIVO_MISURA]          INT             NULL,
    [ID_CODIFICA_INVESTIMENTO]     INT             NULL,
    [ID_DETTAGLIO_INVESTIMENTO]    INT             NULL,
    [ID_SPECIFICA_INVESTIMENTO]    INT             NULL,
    [AMMESSO]                      BIT             NULL,
    [ISTRUTTORE]                   VARCHAR (16)    NULL,
    [ID_INVESTIMENTO_ORIGINALE]    INT             NULL,
    [DATA_VALUTAZIONE]             DATETIME        NULL,
    [VALUTAZIONE_INVESTIMENTO]     NTEXT           NULL,
    [ID_VARIANTE]                  INT             NULL,
    [COD_VARIAZIONE]               CHAR (1)        NULL,
    [NON_COFINANZIATO]             BIT             CONSTRAINT [DF_PIANO_INVESTIMENTI_NON_COFINANZIATO] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_PIANO_INVESTIMENTI] PRIMARY KEY CLUSTERED ([ID_INVESTIMENTO] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_PIANO_INVESTIMENTI_CODICI_VARIAZIONE] FOREIGN KEY ([COD_VARIAZIONE]) REFERENCES [dbo].[CODICI_VARIAZIONE] ([COD_VARIAZIONE]),
    CONSTRAINT [FK_PIANO_INVESTIMENTI_CODIFICA_INVESTIMENTO] FOREIGN KEY ([ID_CODIFICA_INVESTIMENTO]) REFERENCES [dbo].[CODIFICA_INVESTIMENTO] ([ID_CODIFICA_INVESTIMENTO]),
    CONSTRAINT [FK_PIANO_INVESTIMENTI_DETTAGLIO_INVESTIMENTI] FOREIGN KEY ([ID_DETTAGLIO_INVESTIMENTO]) REFERENCES [dbo].[DETTAGLIO_INVESTIMENTI] ([ID_DETTAGLIO_INVESTIMENTO]),
    CONSTRAINT [FK_PIANO_INVESTIMENTI_PRIORITA_SETTORIALI] FOREIGN KEY ([ID_PRIORITA_SETTORIALE]) REFERENCES [dbo].[PRIORITA_SETTORIALI] ([ID_PRIORITA_SETTORIALE]),
    CONSTRAINT [FK_PIANO_INVESTIMENTI_PROGETTO] FOREIGN KEY ([ID_PROGETTO]) REFERENCES [dbo].[PROGETTO] ([ID_PROGETTO]),
    CONSTRAINT [FK_PIANO_INVESTIMENTI_SETTORI_PRODUTTIVI] FOREIGN KEY ([ID_SETTORE_PRODUTTIVO]) REFERENCES [dbo].[SETTORI_PRODUTTIVI] ([ID_SETTORE_PRODUTTIVO]),
    CONSTRAINT [FK_PIANO_INVESTIMENTI_TIPO_INVESTIMENTO] FOREIGN KEY ([COD_TIPO_INVESTIMENTO]) REFERENCES [dbo].[TIPO_INVESTIMENTO] ([COD_TIPO_INVESTIMENTO]),
    CONSTRAINT [FK_PIANO_INVESTIMENTI_UNITA_DI_MISURA] FOREIGN KEY ([ID_UNITA_MISURA]) REFERENCES [dbo].[UNITA_DI_MISURA] ([ID_UNITA_MISURA]),
    CONSTRAINT [FK_PIANO_INVESTIMENTI_VARIANTI] FOREIGN KEY ([ID_VARIANTE]) REFERENCES [dbo].[VARIANTI] ([ID_VARIANTE]),
    CONSTRAINT [FK_PIANO_INVESTIMENTI_zOB_MISURA] FOREIGN KEY ([ID_OBIETTIVO_MISURA]) REFERENCES [dbo].[zOB_MISURA] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [IX_PIANO_INVESTIMENTI]
    ON [dbo].[PIANO_INVESTIMENTI]([ID_PROGETTO] ASC)
    INCLUDE([ID_INVESTIMENTO], [COSTO_INVESTIMENTO], [CONTRIBUTO_RICHIESTO], [QUOTA_CONTRIBUTO_RICHIESTO], [ID_INVESTIMENTO_ORIGINALE], [ID_VARIANTE], [COD_VARIAZIONE]) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IX_PIANO_INVESTIMENTI_1]
    ON [dbo].[PIANO_INVESTIMENTI]([ID_VARIANTE] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IX_PIANO_INVESTIMENTI_2]
    ON [dbo].[PIANO_INVESTIMENTI]([ID_INVESTIMENTO_ORIGINALE] ASC)
    INCLUDE([ID_PROGETTO]);

