CREATE TABLE [dbo].[PRIORITA] (
    [ID_PRIORITA]       INT            IDENTITY (1, 1) NOT NULL,
    [DESCRIZIONE]       VARCHAR (1000) NULL,
    [COD_LIVELLO]       CHAR (1)       NULL,
    [PLURI_VALORE]      BIT            NULL,
    [EVAL]              VARCHAR (3000) NULL,
    [FLAG_MANUALE]      BIT            NULL,
    [INPUT_NUMERICO]    BIT            NULL,
    [MISURA]            VARCHAR (20)   NULL,
    [DATETIME]          BIT            CONSTRAINT [DF_PRIORITA_DATETIME] DEFAULT ((0)) NULL,
    [TESTO_SEMPLICE]    BIT            CONSTRAINT [DF_PRIORITA_TESTO_SEMPLICE] DEFAULT ((0)) NULL,
    [TESTO_AREA]        BIT            CONSTRAINT [DF_PRIORITA_TESTO_AREA] DEFAULT ((0)) NULL,
    [PLURI_VALORE_SQL]  BIT            CONSTRAINT [DF_PRIORITA_PLURI_VALORE_SQL] DEFAULT ((0)) NULL,
    [QUERY_PLURIVALORE] VARCHAR (100)  NULL,
    CONSTRAINT [PK_PRIORITA] PRIMARY KEY CLUSTERED ([ID_PRIORITA] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_PRIORITA_LIVELLO_PRIORITA] FOREIGN KEY ([COD_LIVELLO]) REFERENCES [dbo].[LIVELLO_PRIORITA] ([COD_LIVELLO])
);

