CREATE TABLE [dbo].[PRIORITA_SETTORIALI] (
    [ID_PRIORITA_SETTORIALE] INT            IDENTITY (1, 1) NOT NULL,
    [DESCRIZIONE]            VARCHAR (1000) NULL,
    CONSTRAINT [PK_PRIORITA_SETTORIALI] PRIMARY KEY CLUSTERED ([ID_PRIORITA_SETTORIALE] ASC) WITH (FILLFACTOR = 80)
);

