CREATE TABLE [dbo].[PRIORITA_SPECIALE] (
    [ID_SCHEDA_VALUTAZIONE]   INT NOT NULL,
    [ID_PRIORITA]             INT NOT NULL,
    [ID_PRIORITA_SELEZIONATA] INT NOT NULL,
    [IS_MAX]                  BIT NULL,
    CONSTRAINT [PK_PRIORITA_SPECIALE] PRIMARY KEY CLUSTERED ([ID_SCHEDA_VALUTAZIONE] ASC, [ID_PRIORITA] ASC, [ID_PRIORITA_SELEZIONATA] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_PRIORITA_SPECIALE_SCHEDA_X_PRIORITA] FOREIGN KEY ([ID_SCHEDA_VALUTAZIONE], [ID_PRIORITA]) REFERENCES [dbo].[SCHEDA_X_PRIORITA] ([ID_SCHEDA_VALUTAZIONE], [ID_PRIORITA])
);

