CREATE TABLE [dbo].[PROFILO_X_FUNZIONI] (
    [ID_PROFILO]   INT NOT NULL,
    [COD_FUNZIONE] INT NOT NULL,
    [MODIFICA]     BIT NULL,
    CONSTRAINT [PK_PROFILO_X_FUNZIONI] PRIMARY KEY CLUSTERED ([ID_PROFILO] ASC, [COD_FUNZIONE] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_PROFILO_X_FUNZIONI_FUNZIONALITA] FOREIGN KEY ([COD_FUNZIONE]) REFERENCES [dbo].[FUNZIONALITA] ([COD_FUNZIONE]),
    CONSTRAINT [FK_PROFILO_X_FUNZIONI_PROFILI] FOREIGN KEY ([ID_PROFILO]) REFERENCES [dbo].[PROFILI] ([ID_PROFILO])
);

