CREATE TABLE [dbo].[PROGETTO_COMUNICAZIONE_ALLEGATO] (
    [ID]               INT           IDENTITY (1, 1) NOT NULL,
    [ID_COMUNICAZIONE] INT           NOT NULL,
    [ID_PROGETTO]      INT           NOT NULL,
    [ID_FILE]          INT           NOT NULL,
    [DESCRIZIONE]      VARCHAR (MAX) NULL,
    CONSTRAINT [PK_PROGETTO_COMUNICAZIONE_ALLEGATO] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PROGETTO_COMUNICAZIONE_ALLEGATO_PROGETTO_COMUNICAZIONE] FOREIGN KEY ([ID_COMUNICAZIONE]) REFERENCES [dbo].[PROGETTO_COMUNICAZIONE] ([ID_COMUNICAZIONE])
);

