CREATE TABLE [dbo].[PROGETTO_COMUNICAZIONE] (
    [ID_COMUNICAZIONE]     INT           IDENTITY (1, 1) NOT NULL,
    [ID_PROGETTO]          INT           NOT NULL,
    [ID_COMUNICAZIONE_REF] INT           NULL,
    [OGGETTO]              VARCHAR (250) NOT NULL,
    [TESTO]                VARCHAR (MAX) NOT NULL,
    [COD_TIPO]             CHAR (3)      NOT NULL,
    [DATA_INSERIMENTO]     DATETIME      CONSTRAINT [DF_PROGETTO_COMUNICAZIONE_DATA_INSERIMENTO] DEFAULT (getdate()) NULL,
    [DATA_MODIFICA]        DATETIME      CONSTRAINT [DF_PROGETTO_COMUNICAZIONE_DATA_MODIFICA] DEFAULT (getdate()) NULL,
    [OPERATORE]            INT           NOT NULL,
    [SEGNATURA]            VARCHAR (100) NULL,
    [SEGNATURA_ESTERNA]    BIT           NULL,
    [IN_ENTRATA]           BIT           NULL,
    [ID_NOTE]              INT           NULL,
    CONSTRAINT [PK_PROGETTO_COMUNICAZIONE] PRIMARY KEY CLUSTERED ([ID_COMUNICAZIONE] ASC),
    CONSTRAINT [FK_PROGETTO_COMUNICAZIONE_PROGETTO] FOREIGN KEY ([ID_PROGETTO]) REFERENCES [dbo].[PROGETTO] ([ID_PROGETTO]),
    CONSTRAINT [FK_PROGETTO_COMUNICAZIONE_PROGETTO_COMUNICAZIONE] FOREIGN KEY ([ID_COMUNICAZIONE_REF]) REFERENCES [dbo].[PROGETTO_COMUNICAZIONE] ([ID_COMUNICAZIONE]),
    CONSTRAINT [FK_PROGETTO_COMUNICAZIONE_TIPO_COMUNICAZIONE] FOREIGN KEY ([COD_TIPO]) REFERENCES [dbo].[TIPO_COMUNICAZIONE] ([COD_TIPO])
);

