CREATE TABLE [dbo].[PROVINCE] (
    [CODICE]                  CHAR (3)     NOT NULL,
    [SIGLA]                   CHAR (2)     NOT NULL,
    [COD_CITTA_METROPOLITANA] CHAR (3)     NULL,
    [DENOMINAZIONE]           VARCHAR (50) NOT NULL,
    [COD_REGIONE]             CHAR (2)     NOT NULL,
    CONSTRAINT [PK_PROVINCE] PRIMARY KEY CLUSTERED ([CODICE] ASC) WITH (FILLFACTOR = 100),
    CONSTRAINT [FK_PROVINCE_REGIONI] FOREIGN KEY ([COD_REGIONE]) REFERENCES [dbo].[REGIONI] ([CODICE])
);

