CREATE TABLE [dbo].[QUADRI_X_DOMANDA] (
    [ID_QUADRO]  INT NOT NULL,
    [ID_DOMANDA] INT NOT NULL,
    [ORDINE]     INT NULL,
    CONSTRAINT [PK_QUADRI_X_DOMANDA] PRIMARY KEY CLUSTERED ([ID_QUADRO] ASC, [ID_DOMANDA] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_QUADRI_X_DOMANDA_MODELLO_DOMANDA] FOREIGN KEY ([ID_DOMANDA]) REFERENCES [dbo].[MODELLO_DOMANDA] ([ID_DOMANDA]),
    CONSTRAINT [FK_QUADRI_X_DOMANDA_QUADRO_DOMANDA] FOREIGN KEY ([ID_QUADRO]) REFERENCES [dbo].[QUADRO_DOMANDA] ([ID_QUADRO])
);

