CREATE TABLE [dbo].[RATA] (
    [ID_RATA]              INT             IDENTITY (1, 1) NOT NULL,
    [DATA_INSERIMENTO]     DATETIME        CONSTRAINT [DF_RATA_DATA_INSERIMENTO] DEFAULT (getdate()) NULL,
    [CF_INSERIMENTO]       VARCHAR (16)    NULL,
    [DATA_MODIFICA]        DATETIME        CONSTRAINT [DF_RATA_DATA_MODIFICA] DEFAULT (getdate()) NULL,
    [CF_MODIFICA]          VARCHAR (16)    NULL,
    [ID_TIPO_RATA]         INT             NOT NULL,
    [DATA_RATA]            DATETIME        NULL,
    [DATA_SCADENZA]        DATETIME        NULL,
    [DATA_PAGAMENTO]       DATETIME        NULL,
    [IMPORTO_RATA]         DECIMAL (15, 2) NULL,
    [PAGATA]               BIT             CONSTRAINT [DF_RATA_PAGATA] DEFAULT ((0)) NULL,
    [ID_REGISTRO_RECUPERO] INT             NULL,
    CONSTRAINT [PK_RATA] PRIMARY KEY CLUSTERED ([ID_RATA] ASC),
    CONSTRAINT [FK_RATA_REGISTRO_RECUPERO] FOREIGN KEY ([ID_REGISTRO_RECUPERO]) REFERENCES [dbo].[REGISTRO_RECUPERO] ([ID_REGISTRO_RECUPERO]),
    CONSTRAINT [FK_RATA_TIPO_RATA] FOREIGN KEY ([ID_TIPO_RATA]) REFERENCES [dbo].[TIPO_RATA] ([ID_TIPO_RATA])
);

