CREATE TABLE [dbo].[REPORTISTICA_BANDO] (
    [ID_BANDO]               INT             NOT NULL,
    [DESCRIZIONE]            NTEXT           NOT NULL,
    [DATA_SCADENZA]          DATETIME        NULL,
    [DISPOSIZIONI_ATTUATIVE] BIT             NOT NULL,
    [COD_STATO]              CHAR (1)        NOT NULL,
    [NUM_DOMANDE]            INT             NOT NULL,
    [TOTALE_INVESTIMENTI]    DECIMAL (18, 2) NULL,
    [TOTALE_CONTRIBUTO]      DECIMAL (18, 2) NULL,
    [TOT_INTERESSI]          DECIMAL (18, 2) NULL,
    [DATA_AGGIORNAMENTO]     DATETIME        NULL,
    CONSTRAINT [PK_REPORTISTICA_BANDO] PRIMARY KEY CLUSTERED ([ID_BANDO] ASC, [COD_STATO] ASC) WITH (FILLFACTOR = 80)
);

