CREATE TABLE [dbo].[REQUISITI_VARIANTE] (
    [ID_REQUISITO] INT             IDENTITY (1, 1) NOT NULL,
    [AUTOMATICO]   BIT             NOT NULL,
    [DESCRIZIONE]  VARCHAR (500)   NOT NULL,
    [QUERY_EVAL]   VARCHAR (3000)  NULL,
    [QUERY_INSERT] VARCHAR (3000)  NULL,
    [VAL_MINIMO]   DECIMAL (18, 2) NULL,
    [VAL_MASSIMO]  DECIMAL (18, 2) NULL,
    [MISURA]       VARCHAR (10)    NULL,
    CONSTRAINT [PK_REQUISITI_VARIANTE] PRIMARY KEY CLUSTERED ([ID_REQUISITO] ASC) WITH (FILLFACTOR = 80)
);

