CREATE TABLE [dbo].[REQUISITI_PAGAMENTO_PLURIVALORE] (
    [ID_VALORE]    INT           IDENTITY (1, 1) NOT NULL,
    [ID_REQUISITO] INT           NULL,
    [CODICE]       VARCHAR (10)  NULL,
    [DESCRIZIONE]  VARCHAR (500) NULL,
    CONSTRAINT [PK_REQUISITI_PAGAMENTO_PLURIVALORE] PRIMARY KEY CLUSTERED ([ID_VALORE] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_REQUISITI_PAGAMENTO_PLURIVALORE_REQUISITI_PAGAMENTO] FOREIGN KEY ([ID_REQUISITO]) REFERENCES [dbo].[REQUISITI_PAGAMENTO] ([ID_REQUISITO])
);

