CREATE TABLE [dbo].[REVISIONE_DOMANDA_PAGAMENTO] (
    [ID_LOTTO]                    INT           NOT NULL,
    [ID_DOMANDA_PAGAMENTO]        INT           NOT NULL,
    [DATA_INSERIMENTO]            DATETIME      NOT NULL,
    [DATA_MODIFICA]               DATETIME      NOT NULL,
    [CF_OPERATORE]                VARCHAR (16)  NOT NULL,
    [SELEZIONATA_X_REVISIONE]     BIT           CONSTRAINT [DF_REVISIONE_DOMANDA_PAGAMENTO_SELEZIONATA_X_REVISIONE] DEFAULT ((0)) NOT NULL,
    [APPROVATA]                   BIT           NULL,
    [NUMERO_ESTRAZIONE]           INT           CONSTRAINT [DF_REVISIONE_DOMANDA_PAGAMENTO_NUMERO_ESTRAZIONE] DEFAULT ((0)) NOT NULL,
    [ORDINE]                      INT           NOT NULL,
    [SEGNATURA_REVISIONE]         VARCHAR (100) NULL,
    [SEGNATURA_SECONDA_REVISIONE] VARCHAR (100) NULL,
    [DATA_VALIDAZIONE]            DATETIME      NULL,
    CONSTRAINT [PK_REVISIONE_DOMANDA_PAGAMENTO_1] PRIMARY KEY CLUSTERED ([ID_LOTTO] ASC, [ID_DOMANDA_PAGAMENTO] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_REVISIONE_DOMANDA_PAGAMENTO_DOMANDA_DI_PAGAMENTO] FOREIGN KEY ([ID_DOMANDA_PAGAMENTO]) REFERENCES [dbo].[DOMANDA_DI_PAGAMENTO] ([ID_DOMANDA_PAGAMENTO]),
    CONSTRAINT [FK_REVISIONE_DOMANDA_PAGAMENTO_LOTTO_DI_REVISIONE] FOREIGN KEY ([ID_LOTTO]) REFERENCES [dbo].[LOTTO_DI_REVISIONE] ([ID_LOTTO])
);

