CREATE TABLE [dbo].[REVOCA_ORDINATIVO_INCASSO](
	[ID_ORDINATIVO_INCASSO] [int] IDENTITY(1,1) NOT NULL,
	[ID_REVOCA] [int] NOT NULL,
	[ORDINATIVO_INCASSO] [varchar](255) NULL,
	[DATA_ORDINATIVO] [datetime] NULL,
	[IMPORTO_ORDINATIVO] [decimal](15, 2) NULL,
	[DATA_INSERIMENTO] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_ORDINATIVO_INCASSO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[REVOCA_ORDINATIVO_INCASSO]  WITH CHECK ADD FOREIGN KEY([ID_REVOCA])
REFERENCES [dbo].[REVOCA] ([ID_REVOCA])
GO

ALTER TABLE [dbo].[REVOCA_ORDINATIVO_INCASSO] ADD  DEFAULT (getdate()) FOR [DATA_INSERIMENTO]
GO