CREATE TABLE RNA_PROCEDIMENTI_E_REGOLAMENTI (
ID_PROCEDIMENTI_REGOLAMENTI INT IDENTITY(1,1) NOT NULL,
COD_TIPO_PROCEDIMENTO INT NULL,
DESCRIZIONE_PROCEDURA VARCHAR(50) NULL,
CODICE_REGOLAMENTO VARCHAR(30) NULL,
DESCRIZIONE VARCHAR(MAX) NULL,
CODICE_SETTORE VARCHAR(10) NULL,
SETTORE VARCHAR(20) NULL
 CONSTRAINT PROCEDIMENTI_REGOLAMENTI_PK PRIMARY KEY CLUSTERED 
(
	ID_PROCEDIMENTI_REGOLAMENTI ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]