CREATE TABLE RNA_COMPONENTI_X_CODIFICA(
ID_COMPONENTI_X_CODIFICA INT IDENTITY(1,1) NOT NULL,
ID_CODIFICA_INVESTIMENTO INT NOT NULL FOREIGN KEY REFERENCES CODIFICA_INVESTIMENTO(ID_CODIFICA_INVESTIMENTO),
ID_RNA_PROCEDIMENTI_E_REGOLAMENTI INT NULL FOREIGN KEY REFERENCES RNA_PROCEDIMENTI_E_REGOLAMENTI(ID_PROCEDIMENTI_REGOLAMENTI),
ID_RNA_OBIETTIVO INT NULL FOREIGN KEY REFERENCES RNA_OBIETTIVI(ID_OBIETTIVO),
CONSTRAINT ID_RNA_CODIFICA_INV_PK PRIMARY KEY CLUSTERED 
(
	ID_COMPONENTI_X_CODIFICA ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]