CREATE TABLE RNA_TIPO_SOGGETTO_BENEFICIARIO (
COD_TIPO_SOGGETTO INT NOT NULL,
DESCRIZIONE VARCHAR(300) NULL,
NOTE VARCHAR(300) NULL
 CONSTRAINT TIPO_SOGGETTO_BENEFICIARIO_PK PRIMARY KEY CLUSTERED 
(
	COD_TIPO_SOGGETTO ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY];