CREATE TABLE RNA_STRUMENTI_DI_AIUTO (
COD_TIPO_STRUMENTO_AIUTO INT NOT NULL,
MACRO_STRUMENTO VARCHAR(100) NULL,
STRUMENTO VARCHAR(300) NULL
CONSTRAINT TIPO_STRUMENTO_AIUTO_PK PRIMARY KEY CLUSTERED 
(
	COD_TIPO_STRUMENTO_AIUTO ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]