SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[RNA_BANDO_CONFIG](
	[ID_RNA_BANDO_CONFIG] [int] IDENTITY(1,1) NOT NULL,
	[ID_BANDO] [int] NOT NULL,
	[COD_BANDO_RNA] [int] NOT NULL,
	[DATA_PREVISTA_CONCESSIONE] [datetime] NULL,
	[CUMULABILITA] [char](1) NULL,
	[COD_BANDO_RNA_COLLAUDO] [int] NULL,
	[ID_RNA_ENTE] [int] NULL,
 CONSTRAINT [ID_RNA_BANDO_CONFIG_PK] PRIMARY KEY CLUSTERED 
(
	[ID_RNA_BANDO_CONFIG] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[RNA_BANDO_CONFIG]  WITH CHECK ADD FOREIGN KEY([ID_BANDO])
REFERENCES [dbo].[BANDO] ([ID_BANDO])