CREATE TABLE [dbo].[SANZIONI_RECUPERO] (
    [ID_SANZIONE_RECUPERO]  INT             IDENTITY (1, 1) NOT NULL,
    [DATA_INSERIMENTO]      DATETIME        NULL,
    [CF_INSERIMENTO]        VARCHAR (16)    NULL,
    [DATA_MODIFICA]         DATETIME        NULL,
    [CF_MODIFICA]           VARCHAR (16)    NULL,
    [ID_REGISTRO_RECUPERO]  INT             NULL,
    [ID_CATEGORIA_SANZIONE] INT             NULL,
    [ID_TIPO_SANZIONE]      INT             NULL,
    [IMPORTO_SANZIONE]      DECIMAL (15, 2) NULL,
    [DATA_CONCLUSIONE]      DATETIME        NULL,
    [ID_STATO_SANZIONE]     INT             NULL,
    CONSTRAINT [PK_SANZIONI_RECUPERO] PRIMARY KEY CLUSTERED ([ID_SANZIONE_RECUPERO] ASC),
    CONSTRAINT [FK_SANZIONI_RECUPERO_CODIFICA_GENERICA_CATEGORIA_SANZIONE] FOREIGN KEY ([ID_CATEGORIA_SANZIONE]) REFERENCES [dbo].[CODIFICA_GENERICA] ([ID]),
    CONSTRAINT [FK_SANZIONI_RECUPERO_CODIFICA_GENERICA_STATO_SANZIONE] FOREIGN KEY ([ID_STATO_SANZIONE]) REFERENCES [dbo].[CODIFICA_GENERICA] ([ID]),
    CONSTRAINT [FK_SANZIONI_RECUPERO_CODIFICA_GENERICA_TIPO_SANZIONE] FOREIGN KEY ([ID_TIPO_SANZIONE]) REFERENCES [dbo].[CODIFICA_GENERICA] ([ID]),
    CONSTRAINT [FK_SANZIONI_RECUPERO_REGISTRO_RECUPERO] FOREIGN KEY ([ID_REGISTRO_RECUPERO]) REFERENCES [dbo].[REGISTRO_RECUPERO] ([ID_REGISTRO_RECUPERO])
);

