CREATE TABLE [dbo].[SANZIONI] (
    [ID_SANZIONE]          INT             IDENTITY (1, 1) NOT NULL,
    [COD_TIPO]             VARCHAR (10)    NOT NULL,
    [ID_DOMANDA_PAGAMENTO] INT             NOT NULL,
    [ID_PROGETTO]          INT             NOT NULL,
    [DATA_APPLICAZIONE]    DATETIME        NOT NULL,
    [OPERATORE]            VARCHAR (16)    NOT NULL,
    [AMMONTARE]            DECIMAL (18, 2) NULL,
    [ID_INVESTIMENTO]      INT             NULL,
    [DURATA]               INT             NULL,
    [VALORE_DURATA]        DECIMAL (18, 2) NULL,
    [GRAVITA]              INT             NULL,
    [VALORE_GRAVITA]       DECIMAL (18, 2) NULL,
    [ENTITA]               INT             NULL,
    [VALORE_ENTITA]        DECIMAL (18, 2) NULL,
    [MOTIVAZIONE]          NTEXT           NULL,
    CONSTRAINT [PK_SANZIONI] PRIMARY KEY CLUSTERED ([ID_SANZIONE] ASC) WITH (FILLFACTOR = 100),
    CONSTRAINT [FK_SANZIONI_DOMANDA_DI_PAGAMENTO_ESPORTAZIONE] FOREIGN KEY ([ID_DOMANDA_PAGAMENTO], [ID_PROGETTO]) REFERENCES [dbo].[DOMANDA_DI_PAGAMENTO_ESPORTAZIONE] ([ID_DOMANDA_PAGAMENTO], [ID_PROGETTO]),
    CONSTRAINT [FK_SANZIONI_TIPO_SANZIONI] FOREIGN KEY ([COD_TIPO]) REFERENCES [dbo].[TIPO_SANZIONI] ([COD_TIPO])
);

