CREATE TABLE [dbo].[SCHEDA_VALUTAZIONE] (
    [ID_SCHEDA_VALUTAZIONE] INT                 IDENTITY (1, 1) NOT NULL,
    [DESCRIZIONE]           [dbo].[DESCRIZIONE] NOT NULL,
    [FLAG_TEMPLATE]         BIT                 NOT NULL,
    [VALORE_MAX]            DECIMAL (10, 2)     NULL,
    [VALORE_MIN]            DECIMAL (10, 2)     NULL,
    [PAROLE_CHIAVE]         VARCHAR (50)        NULL,
    [DATA_MODIFICA]         DATETIME            CONSTRAINT [DF_SCHEDA_VALUTAZIONE_DATA_MODIFICA] DEFAULT (getdate()) NULL,
    CONSTRAINT [SCHEDA_VALUTAZIONE_PK] PRIMARY KEY CLUSTERED ([ID_SCHEDA_VALUTAZIONE] ASC) WITH (FILLFACTOR = 80)
);

