CREATE TABLE [dbo].[SEGNATURE_ANNULLATE] (
    [ID]                  INT            IDENTITY (1, 1) NOT NULL,
    [DATA_ANNULLAMENTO]   DATETIME       CONSTRAINT [DF_SEGNATURE_ANNULLATE_DATA_ANNULLAMENTO] DEFAULT (getdate()) NOT NULL,
    [SEGNATURA]           VARCHAR (100)  NOT NULL,
    [OPERATORE_SEGNATURA] CHAR (16)      NOT NULL,
    [DESCRIZIONE]         VARCHAR (1000) NOT NULL,
    CONSTRAINT [PK_SEGNATURE_ANNULLATE] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 80)
);

