CREATE TABLE [dbo].[SETTORI_PRODUTTIVI] (
    [ID_SETTORE_PRODUTTIVO] INT                 IDENTITY (1, 1) NOT NULL,
    [DESCRIZIONE]           [dbo].[DESCRIZIONE] NULL,
    CONSTRAINT [PK_SETTORI_PRODUTTIVI] PRIMARY KEY CLUSTERED ([ID_SETTORE_PRODUTTIVO] ASC) WITH (FILLFACTOR = 100)
);

