CREATE TABLE [dbo].[TIPO_CPT_SETTORE] (
    [COD_CPT_SETTORE] CHAR (2)      NOT NULL,
    [Descrizione]     VARCHAR (100) NOT NULL,
    CONSTRAINT [PK_TIPO_CPT_SETTORE] PRIMARY KEY CLUSTERED ([COD_CPT_SETTORE] ASC)
);

