CREATE TABLE [dbo].[TIPO_VARIANTE] (
    [COD_TIPO]    CHAR (2)     NOT NULL,
    [DESCRIZIONE] VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_TIPO_VARIANTE] PRIMARY KEY CLUSTERED ([COD_TIPO] ASC) WITH (FILLFACTOR = 100)
);

