CREATE TABLE [dbo].[TIPO_CONDUZIONE] (
    [COD_TIPO_CONDUZIONE] INT          NOT NULL,
    [DESCRIZIONE]         VARCHAR (25) NULL,
    [COD_SIAN]            VARCHAR (25) NULL,
    CONSTRAINT [PK_TIPO_CONDUZIONE] PRIMARY KEY CLUSTERED ([COD_TIPO_CONDUZIONE] ASC) WITH (FILLFACTOR = 100)
);

