CREATE TABLE [dbo].[TIPO_CUP_DIMENSIONE_TERR] (
    [COD_CUP_DIMENSIONE_TERR] CHAR (2)      NOT NULL,
    [Descrizione]             VARCHAR (100) NOT NULL,
    CONSTRAINT [PK_TIPO_CUP_DIMENSIONE_TERR] PRIMARY KEY CLUSTERED ([COD_CUP_DIMENSIONE_TERR] ASC)
);

