CREATE TABLE [dbo].[TIPO_INTEGRAZIONE_DOMANDA] (
    [COD_TIPO]    CHAR (3)      NOT NULL,
    [DESCRIZIONE] VARCHAR (200) NOT NULL,
    CONSTRAINT [PK_TIPO_INTEGRAZIONE_DOMANDA] PRIMARY KEY CLUSTERED ([COD_TIPO] ASC)
);

