CREATE TABLE [dbo].[TIPO_AGGREGAZIONE] (
    [CODICE]      VARCHAR (10)  NOT NULL,
    [DESCRIZIONE] VARCHAR (255) NOT NULL,
    CONSTRAINT [PK_TIPO_AGGREGAZIONE] PRIMARY KEY CLUSTERED ([CODICE] ASC)
);

