CREATE TABLE [dbo].[TIPO_RATA] (
    [ID_TIPO_RATA] INT          IDENTITY (1, 1) NOT NULL,
    [DESCRIZIONE]  VARCHAR (80) NULL,
    CONSTRAINT [PK_TIPO_RATA] PRIMARY KEY CLUSTERED ([ID_TIPO_RATA] ASC)
);

