CREATE TABLE [dbo].[TIPO_SOCIO] (
    [CODICE]      CHAR (1)     NOT NULL,
    [DESCRIZIONE] VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_TIPO_SOCIO] PRIMARY KEY CLUSTERED ([CODICE] ASC) WITH (FILLFACTOR = 100)
);

