CREATE TABLE [dbo].[TIPO_CAUSE_VARIAZIONI] (
    [ID_CAUSA]    INT          IDENTITY (1, 1) NOT NULL,
    [CODICE]      CHAR (5)     NULL,
    [DESCRIZIONE] VARCHAR (50) NOT NULL,
    [COD_SIAN]    VARCHAR (50) NULL,
    CONSTRAINT [PK_TIPO_CAUSE_VARIAZIONI] PRIMARY KEY CLUSTERED ([ID_CAUSA] ASC) WITH (FILLFACTOR = 100)
);

