CREATE TABLE [dbo].[TIPO_GANTT_VALORI] (
    [ID_TIPO_VALORE] TINYINT       NOT NULL,
    [NOME]           VARCHAR (100) NULL,
    [FORMATO]        VARCHAR (20)  NULL,
    [PATTERN]        VARCHAR (100) NULL,
    CONSTRAINT [PK_TIPO_GANT_VALORI] PRIMARY KEY CLUSTERED ([ID_TIPO_VALORE] ASC)
);

