CREATE TABLE [dbo].[TIPO_INVESTIMENTO] (
    [COD_TIPO_INVESTIMENTO] INT           IDENTITY (1, 1) NOT NULL,
    [DESCRIZIONE]           VARCHAR (100) NOT NULL,
    [URL]                   VARCHAR (100) NULL,
    [TEXT]                  VARCHAR (50)  NOT NULL,
    CONSTRAINT [PK_TIPO_INVESTIMENTO] PRIMARY KEY CLUSTERED ([COD_TIPO_INVESTIMENTO] ASC) WITH (FILLFACTOR = 100)
);

