CREATE TABLE [dbo].[TIPO_ENTE] (
    [COD_TIPO_ENTE] VARCHAR (10)  NOT NULL,
    [DESCRIZIONE]   VARCHAR (255) NOT NULL,
    CONSTRAINT [PK_TIPO_ENTE] PRIMARY KEY CLUSTERED ([COD_TIPO_ENTE] ASC) WITH (FILLFACTOR = 100)
);

