CREATE TABLE [dbo].[TIPO_DEFINIZIONE_ATTO] (
    [CODICE]      CHAR (1)      NOT NULL,
    [DESCRIZIONE] VARCHAR (100) NOT NULL,
    [ATTIVO]      BIT           CONSTRAINT [DF_TIPO_DEFINIZIONE_ATTO_ATTIVO] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_TIPO_DEFINIZIONE_ATTO] PRIMARY KEY CLUSTERED ([CODICE] ASC) WITH (FILLFACTOR = 100)
);

