CREATE TABLE [dbo].[TIPO_GANTT_TIPIOPERAZIONE] (
    [ID_TIPOOP]   INT           NOT NULL,
    [NOME_TIPOOP] VARCHAR (200) NOT NULL,
    CONSTRAINT [PK_TIPO_GANTT_TIPIOPERAZIONE] PRIMARY KEY CLUSTERED ([ID_TIPOOP] ASC)
);

