CREATE TABLE [dbo].[TIPO_CESSAZIONE_ATTIVITA] (
    [CODICE]      CHAR (1)      NOT NULL,
    [DESCRIZIONE] VARCHAR (100) NOT NULL,
    CONSTRAINT [PK_TIPO_CESSAZIONE_ATTIVITA] PRIMARY KEY CLUSTERED ([CODICE] ASC) WITH (FILLFACTOR = 100)
);

