CREATE TABLE [dbo].[TIPO_DOMANDA_PAGAMENTO] (
    [COD_TIPO]    CHAR (3)      NOT NULL,
    [DESCRIZIONE] VARCHAR (100) NULL,
    [COD_FASE]    CHAR (1)      NULL,
    CONSTRAINT [PK_TIPO_DOMANDA_PAGAMENTO] PRIMARY KEY CLUSTERED ([COD_TIPO] ASC) WITH (FILLFACTOR = 100),
    CONSTRAINT [FK_TIPO_DOMANDA_PAGAMENTO_FASI_PROCEDURALI] FOREIGN KEY ([COD_FASE]) REFERENCES [dbo].[FASI_PROCEDURALI] ([COD_FASE])
);

