CREATE TABLE [dbo].[TIPO_COMMERCIALIZZAZIONE] (
    [COD_TIPO]    INT          IDENTITY (1, 1) NOT NULL,
    [DESCRIZIONE] VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_TIPO_COMMERCIALIZZAZIONE] PRIMARY KEY CLUSTERED ([COD_TIPO] ASC) WITH (FILLFACTOR = 100)
);

