CREATE TABLE [dbo].[UNITA_DI_MISURA] (
    [ID_UNITA_MISURA] INT           IDENTITY (1, 1) NOT NULL,
    [DESCRIZIONE]     VARCHAR (255) NULL,
    CONSTRAINT [PK_UNITA_DI_MISURA] PRIMARY KEY CLUSTERED ([ID_UNITA_MISURA] ASC) WITH (FILLFACTOR = 100)
);

