CREATE TABLE [dbo].[UTENTI_STORICO] (
    [ID]         INT           IDENTITY (1, 1) NOT NULL,
    [ID_UTENTE]  INT           NOT NULL,
    [ID_PROFILO] INT           NOT NULL,
    [COD_ENTE]   VARCHAR (10)  NULL,
    [PROVINCIA]  CHAR (2)      NULL,
    [EMAIL]      VARCHAR (100) NULL,
    [ATTIVO]     BIT           CONSTRAINT [DF_UTENTI_STORICO_ATTIVO] DEFAULT ((1)) NOT NULL,
    [DATA]       DATETIME      NOT NULL,
    [OPERATORE]  INT           NOT NULL,
    CONSTRAINT [PK_UTENTI_STORICO] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_UTENTI_STORICO_ENTE] FOREIGN KEY ([COD_ENTE]) REFERENCES [dbo].[ENTE] ([COD_ENTE]),
    CONSTRAINT [FK_UTENTI_STORICO_PROFILI] FOREIGN KEY ([ID_PROFILO]) REFERENCES [dbo].[PROFILI] ([ID_PROFILO]),
    CONSTRAINT [FK_UTENTI_STORICO_UTENTI] FOREIGN KEY ([ID_UTENTE]) REFERENCES [dbo].[UTENTI] ([ID_UTENTE])
);

