CREATE TABLE [dbo].[WORKFLOW] (
    [COD_WORKFLOW] CHAR (5)      NOT NULL,
    [DESCRIZIONE]  VARCHAR (500) NOT NULL,
    [URL]          VARCHAR (100) NOT NULL,
    CONSTRAINT [PK_WORK_FLOW] PRIMARY KEY CLUSTERED ([COD_WORKFLOW] ASC) WITH (FILLFACTOR = 100)
);

