CREATE TABLE [dbo].[zDIMENSIONI_X_PROGRAMMAZIONE] (
    [ID_PROGRAMMAZIONE]       INT NOT NULL,
    [ID_DIMENSIONE]           INT NOT NULL,
    [ID_DIM_X_PROGRAMMAZIONE] INT IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_zDIMENSIONI_X_PROGRAMMAZIONE_1] PRIMARY KEY CLUSTERED ([ID_DIM_X_PROGRAMMAZIONE] ASC),
    CONSTRAINT [FK_zDIMENSIONI_X_PROGRAMMAZIONE_zDIMENSIONI1] FOREIGN KEY ([ID_DIMENSIONE]) REFERENCES [dbo].[zDIMENSIONI] ([ID]),
    CONSTRAINT [FK_zDIMENSIONI_X_PROGRAMMAZIONE_zPROGRAMMAZIONE] FOREIGN KEY ([ID_PROGRAMMAZIONE]) REFERENCES [dbo].[zPROGRAMMAZIONE] ([ID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_zDIMENSIONI_X_PROGRAMMAZIONE]
    ON [dbo].[zDIMENSIONI_X_PROGRAMMAZIONE]([ID_PROGRAMMAZIONE] ASC, [ID_DIMENSIONE] ASC);

