CREATE TABLE [dbo].[zDIMENSIONI_VALPROGRAMMATI] (
    [ID_DIM_VALPROG]    INT             IDENTITY (1, 1) NOT NULL,
    [ID_DIM_PRIORITA]   INT             NULL,
    [ID_DIM_INDICATORE] INT             NULL,
    [DATA_RIF]          DATE            NULL,
    [VALORE]            DECIMAL (18, 2) NULL,
    [TIPO]              CHAR (1)        NULL,
    CONSTRAINT [PK_zDIMENSIONI_VALPROGRAMMATI ] PRIMARY KEY CLUSTERED ([ID_DIM_VALPROG] ASC),
    CONSTRAINT [FK_zDIMENSIONI_VALPROGRAMMATI _zDIMENSIONI1] FOREIGN KEY ([ID_DIM_PRIORITA]) REFERENCES [dbo].[zDIMENSIONI] ([ID]),
    CONSTRAINT [FK_zDIMENSIONI_VALPROGRAMMATI _zDIMENSIONI2] FOREIGN KEY ([ID_DIM_INDICATORE]) REFERENCES [dbo].[zDIMENSIONI] ([ID])
);

