CREATE TABLE [dbo].[zFOCUS_AREA] (
    [CODICE]          VARCHAR (10)    NOT NULL,
    [COD_PSR]         VARCHAR (20)    NOT NULL,
    [DESCRIZIONE]     VARCHAR (255)   NOT NULL,
    [DOT_FINANZIARIA] DECIMAL (18, 2) CONSTRAINT [DF_zFOCUS_AREA_DOT_FINANZIARIA] DEFAULT ((0)) NOT NULL,
    [TRASVERSALE]     BIT             CONSTRAINT [DF_zFOCUS_AREA_TRASVERSALE] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_zFOCUS_AREA] PRIMARY KEY CLUSTERED ([CODICE] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_zFOCUS_AREA_zPSR] FOREIGN KEY ([COD_PSR]) REFERENCES [dbo].[zPSR] ([CODICE])
);

