CREATE TABLE [dbo].[zOB_PSN] (
    [CODICE]      VARCHAR (10)  NOT NULL,
    [COD_PSN]     VARCHAR (20)  NOT NULL,
    [DESCRIZIONE] VARCHAR (255) NOT NULL,
    CONSTRAINT [PK_zOB_PSN] PRIMARY KEY CLUSTERED ([CODICE] ASC) WITH (FILLFACTOR = 100)
);

