CREATE TABLE [dbo].[zOB_PSR] (
    [CODICE]      VARCHAR (10)  NOT NULL,
    [COD_OB_PSN]  VARCHAR (10)  NOT NULL,
    [DESCRIZIONE] VARCHAR (255) NOT NULL,
    CONSTRAINT [PK_zOB_PSR] PRIMARY KEY CLUSTERED ([CODICE] ASC),
    CONSTRAINT [FK_zOB_PSR_zOB_PSN] FOREIGN KEY ([COD_OB_PSN]) REFERENCES [dbo].[zOB_PSN] ([CODICE])
);

