CREATE TABLE [dbo].[zOB_MISURA] (
    [ID]                INT           IDENTITY (1, 1) NOT NULL,
    [ID_PROGRAMMAZIONE] INT           NOT NULL,
    [CODICE]            VARCHAR (10)  NOT NULL,
    [DESCRIZIONE]       VARCHAR (500) NOT NULL,
    CONSTRAINT [PK_zOB_MISURA] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 100),
    CONSTRAINT [FK_zOB_MISURA_zPROGRAMMAZIONE] FOREIGN KEY ([ID_PROGRAMMAZIONE]) REFERENCES [dbo].[zPROGRAMMAZIONE] ([ID])
);

