CREATE TABLE [dbo].[zPROGRAMMAZIONE] (
    [ID]                INT             IDENTITY (1, 1) NOT NULL,
    [COD_TIPO]          VARCHAR (30)    NOT NULL,
    [CODICE]            VARCHAR (20)    NOT NULL,
    [DESCRIZIONE]       VARCHAR (2000)  NOT NULL,
    [ID_PADRE]          INT             NOT NULL,
    [IMPORTO_DOTAZIONE] DECIMAL (18, 2) NULL,
    CONSTRAINT [PK_zPROGRAMMAZIONE] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_zPROGRAMMAZIONE_zPSR_ALBERO] FOREIGN KEY ([COD_TIPO]) REFERENCES [dbo].[zPSR_ALBERO] ([CODICE])
);

