CREATE TABLE [dbo].[zPROGRAMMAZIONE_SANZIONI] (
    [ID]                INT          IDENTITY (1, 1) NOT NULL,
    [ID_PROGRAMMAZIONE] INT          NOT NULL,
    [COD_SANZIONE]      VARCHAR (10) NOT NULL,
    [ATTIVA]            BIT          CONSTRAINT [DF_zPROGRAMMAZIONE_SANZIONI_ATTIVA] DEFAULT ((0)) NOT NULL,
    [DATA_INIZIO]       DATETIME     NOT NULL,
    [OPERATORE_INIZIO]  INT          NOT NULL,
    [DATA_FINE]         DATETIME     NULL,
    [OPERATORE_FINE]    INT          NULL,
    [ORDINE]            INT          NOT NULL,
    CONSTRAINT [PK_zPROGRAMMAZIONE_SANZIONI] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_zPROGRAMMAZIONE_SANZIONI_TIPO_SANZIONI] FOREIGN KEY ([COD_SANZIONE]) REFERENCES [dbo].[TIPO_SANZIONI] ([COD_TIPO]),
    CONSTRAINT [FK_zPROGRAMMAZIONE_SANZIONI_zPROGRAMMAZIONE] FOREIGN KEY ([ID_PROGRAMMAZIONE]) REFERENCES [dbo].[zPROGRAMMAZIONE] ([ID])
);

