CREATE TABLE [dbo].[zPROGRAMMAZIONE_FONTI] (
    [ID]                INT             IDENTITY (1, 1) NOT NULL,
    [ID_PROGRAMMAZIONE] INT             NOT NULL,
    [ID_FONTE]          INT             NOT NULL,
    [PERCENTUALE]       DECIMAL (10, 2) NOT NULL,
    [ATTIVA]            BIT             CONSTRAINT [DF_zPROGRAMMAZIONE_FONTI_ATTIVA] DEFAULT ((0)) NOT NULL,
    [DATA_INIZIO]       DATETIME        NOT NULL,
    [OPERATORE_INIZIO]  INT             NOT NULL,
    [DATA_FINE]         DATETIME        NULL,
    [OPERATORE_FINE]    INT             NULL,
    CONSTRAINT [PK_zPROGRAMMAZIONE_FONTI] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_zPROGRAMMAZIONE_FONTI_FONTI_FINANZIARIE] FOREIGN KEY ([ID_FONTE]) REFERENCES [dbo].[FONTI_FINANZIARIE] ([ID_FONTE]),
    CONSTRAINT [FK_zPROGRAMMAZIONE_FONTI_zPROGRAMMAZIONE] FOREIGN KEY ([ID_PROGRAMMAZIONE]) REFERENCES [dbo].[zPROGRAMMAZIONE] ([ID])
);

