CREATE TABLE [dbo].[zPSR_ALBERO] (
    [CODICE]                   VARCHAR (30) NOT NULL,
    [COD_PSR]                  VARCHAR (20) NOT NULL,
    [DESCRIZIONE]              VARCHAR (50) NOT NULL,
    [LIVELLO]                  INT          NOT NULL,
    [ATTIVAZIONE_BANDI]        BIT          CONSTRAINT [DF_zPSR_ALBERO_ATTIVAZIONE_BANDI] DEFAULT ((0)) NOT NULL,
    [ATTIVAZIONE_FA]           BIT          CONSTRAINT [DF_zPSR_ALBERO_ATTIVAZIONE_FA] DEFAULT ((0)) NOT NULL,
    [ATTIVAZIONE_OB_MISURA]    BIT          CONSTRAINT [DF_zPSR_ALBERO_ATTIVAZIONE_OB_MISURA] DEFAULT ((0)) NOT NULL,
    [ATTIVAZIONE_INVESTIMENTI] BIT          CONSTRAINT [DF_zPSR_ALBERO_ATTIVAZIONE_INVESTIMENTI] DEFAULT ((0)) NOT NULL,
    [ATTIVAZIONE_FF]           BIT          CONSTRAINT [DF_zPSR_ALBERO_ATTIVAZIONE_FF] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_zPSR_ALBERO] PRIMARY KEY CLUSTERED ([CODICE] ASC),
    CONSTRAINT [FK_zPSR_ALBERO_zPSR] FOREIGN KEY ([COD_PSR]) REFERENCES [dbo].[zPSR] ([CODICE])
);

