CREATE VIEW CTE_TESTATA_VALIDAZIONE
AS
	WITH CTE AS 
	(
		SELECT R.*, 
			ROW_NUMBER() OVER (PARTITION BY R.ID_DOMANDA_PAGAMENTO ORDER BY R.DATA_INSERIMENTO DESC) AS RN
		FROM VTESTATA_VALIDAZIONE R
		WHERE 1 = 1
			AND ID_LOTTO IS NOT NULL
	)

	SELECT *
	FROM CTE 
	WHERE 1 = 1
		AND RN = 1