-- DROP VIEW VTESTATA_VALIDAZIONE_X_ISTANZA
CREATE VIEW VTESTATA_VALIDAZIONE_X_ISTANZA
AS
	SELECT TVI.*,
		TV.AUTOVALUTAZIONE,
		TV.APPROVATA,
		TV.DATA_VALIDAZIONE,
		TV.CF_VALIDATORE,
		UT.NOMINATIVO AS NOMINATIVO_VALIDATORE,
		ICG.ID_CHECKLIST_GENERICA,
		ICG.COD_FASE AS COD_FASE_ISTANZA,
		CG.DESCRIZIONE AS DESCRIZIONE_CHECKLIST,
		CG.FLAG_TEMPLATE AS FLAG_TEMPLATE_CHECKLIST,
		CG.ID_FILTRO AS ID_FILTRO_CHECKLIST,
		CG.ID_TIPO AS ID_TIPO_CHECKLIST
	FROM TESTATA_VALIDAZIONE_X_ISTANZA TVI
		JOIN TESTATA_VALIDAZIONE TV ON TVI.ID_TESTATA_VALIDAZIONE = TV.ID_TESTATA
		LEFT JOIN vUTENTI UT ON TV.CF_VALIDATORE = UT.CF_UTENTE
		LEFT JOIN ISTANZA_CHECKLIST_GENERICA ICG ON TVI.ID_ISTANZA_CHECKLIST_GENERICA = ICG.ID_ISTANZA_GENERICA
		LEFT JOIN CHECKLIST_GENERICA CG ON ICG.ID_CHECKLIST_GENERICA = CG.ID_CHECKLIST_GENERICA