CREATE VIEW [dbo].[VCONTRATTI_FEM]
AS
SELECT 
	CON.*,
	IMP.DESCRIZIONE AS IMPRESA,
	IMP.CODICE_FISCALE AS CODICE_FISCALE_IMPRESA,
	IMP.CUAA AS CUAA_IMPRESA
FROM CONTRATTI_FEM CON
	LEFT JOIN IMPRESA IMP ON CON.ID_IMPRESA = IMP.ID_IMPRESA;
GO