----
CREATE PROCEDURE [dbo].[calcoloStepVariante122_1]
@ID_VARIANTE int
AS
BEGIN
 
--- Rispetto massimale investimento per Miglioramento viabilità forestale
-- declare @ID_VARIANTE int
--set @ID_VARIANTE = 1520
 
DECLARE @RESULT int, @IdProgetto INT,
		@INV_VIABILITA decimal(18,2) ,
		@INV_SELVICOLTURA decimal(18,2)


SET @RESULT = 0  -- Impongo lo Step NON verificato

SET @IdProgetto =  (SELECT ID_PROGETTO FROM VARIANTI WHERE ID_VARIANTE=@ID_VARIANTE )

SET @INV_VIABILITA = (SELECT ISNULL(SUM(COSTO_INVESTIMENTO),0) + ISNULL( SUM (SPESE_GENERALI),0)  FROM PROGETTO P  INNER JOIN
					 VPIANO_INVESTIMENTI I ON (P.ID_PROGETTO=I.ID_PROGETTO) 
					 WHERE
						I.ID_PROGETTO = @IdProgetto AND ID_VARIANTE = @ID_VARIANTE AND isnull(COD_VARIAZIONE,'x')!='A' AND
						I.ID_DETTAGLIO_INVESTIMENTO IN
							(SELECT ID_DETTAGLIO_INVESTIMENTO  FROM CODIFICA_INVESTIMENTO CI INNER JOIN
								DETTAGLIO_INVESTIMENTI DI ON (CI.ID_CODIFICA_INVESTIMENTO = DI.ID_CODIFICA_INVESTIMENTO) WHERE
								CI.ID_BANDO = (SELECT ID_BANDO FROM PROGETTO WHERE ID_PROGETTO = @IdProgetto) AND DI.COD_DETTAGLIO = 'a7'))

SET @INV_SELVICOLTURA = (SELECT ISNULL(SUM(COSTO_INVESTIMENTO),0) + ISNULL( SUM (SPESE_GENERALI),0)  FROM PROGETTO P  INNER JOIN
					VPIANO_INVESTIMENTI I ON (P.ID_PROGETTO=I.ID_PROGETTO) WHERE 
						I.ID_PROGETTO = @IdProgetto AND ID_VARIANTE = @ID_VARIANTE AND isnull(COD_VARIAZIONE,'x')!='A' AND
						I.ID_DETTAGLIO_INVESTIMENTO IN
					(SELECT ID_DETTAGLIO_INVESTIMENTO  FROM CODIFICA_INVESTIMENTO CI  INNER JOIN
								DETTAGLIO_INVESTIMENTI DI ON (CI.ID_CODIFICA_INVESTIMENTO = DI.ID_CODIFICA_INVESTIMENTO) WHERE
								CI.ID_BANDO = (SELECT ID_BANDO FROM PROGETTO WHERE ID_PROGETTO = @IdProgetto) AND DI.COD_DETTAGLIO in ('a1','a2','a3','a4','a5','a6')))
  								   
IF(ISNULL(@INV_VIABILITA,0) > 0)
BEGIN
	IF(ISNULL(@INV_SELVICOLTURA,0) > 0)
		BEGIN
			IF ((@INV_VIABILITA * 100) / @INV_SELVICOLTURA) > 25
			SET @Result=0
		END
	ELSE 
		SET @Result=0
END  
  ELSE 
	SET @Result=1

SELECT @RESULT
END
