--
CREATE PROCEDURE [dbo].[calcoloPriorita413_3]
(
@IdProgetto int,
@fase_istruttoria bit,
@IdVariante INT 
)
AS
BEGIN
-- - Investimenti ZONA 2000
--declare @IdProgetto int, 
--@FASE_ISTRUTTORIA INT 
--set @IdProgetto  = 834 
--set @FASE_ISTRUTTORIA   =0
DECLARE @PUNTEGGIO decimal(10,2), 
		@COSTO DECIMAL(18,2),
		@ZONA_2000 decimal(18,2) 
 
SELECT TOP(1)@COSTO=SUM(COSTO_INVESTIMENTO),@ZONA_2000=ISNULL(pxi.id_priorita,0)  
FROM PIANO_INVESTIMENTI AS I LEFT JOIN
			PRIORITA_X_INVESTIMENTI PXI ON I.ID_INVESTIMENTO = PXI.ID_INVESTIMENTO AND (PXI.ID_PRIORITA = 420)
WHERE (I.ID_PROGETTO = @IdProgetto) AND ((@fase_istruttoria=0 AND I.ID_INVESTIMENTO_ORIGINALE IS NULL AND ID_VARIANTE IS NULL)
	 OR (@fase_istruttoria=1 AND (I.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL AND @IdVariante IS NULL) OR 
	 (ID_VARIANTE = @IdVariante AND @IdVariante IS NOT NULL AND ISNULL(COD_VARIAZIONE,'X')!='A')))
GROUP BY PXI.ID_PRIORITA
ORDER BY SUM(COSTO_INVESTIMENTO) desc

IF (@ZONA_2000>0) SELECT 1
ELSE SELECT 0 
END
