--- Calcolo spese tecniche dal 10% o al 3%
--- GAL FLAMINIA CESANO

CREATE PROCEDURE [dbo].[calcoloStepVariante4135_B254_1]
@ID_VARIANTE int
AS
BEGIN

DECLARE @IdProgetto int

SET @IdProgetto = ( SELECT ID_PROGETTO FROM VARIANTI WHERE ID_VARIANTE= @ID_VARIANTE )


DECLARE @result int, @A int, @B int, @COSTO int, @CONTA_ATTREZZATURE int, @CONTA_ALTRO int, @COSTO_SPESE_TECNICHE int
SET @result = 0

--- costo spese per codifica B
SELECT @COSTO = (SELECT (ISNULL(SUM(COSTO_INVESTIMENTO),0) + ISNULL(SUM(SPESE_GENERALI),0)) AS Totale_Investimenti FROM PROGETTO P INNER JOIN
			vPIANO_INVESTIMENTI VPI ON P.ID_PROGETTO=VPI.ID_PROGETTO WHERE
			VPI.ID_VARIANTE = @ID_VARIANTE AND isnull(COD_VARIAZIONE,'x')!='A' AND VPI.COD_TIPO_INVESTIMENTO = 1 AND 
			VPI.CODICE = 'B')

--- costo spese tecniche per dettaglio attrezzature (cod_dettaglio = 5) o al 10% o al 3%
SELECT @COSTO_SPESE_TECNICHE = (SELECT ISNULL(SUM(SPESE_GENERALI),0) AS Totale_Spese_tecniche FROM PROGETTO P  INNER JOIN VPIANO_INVESTIMENTI I ON (P.ID_PROGETTO=I.ID_PROGETTO) WHERE
			I.ID_VARIANTE = @ID_VARIANTE AND isnull(COD_VARIAZIONE,'x')!='A' AND I.COD_TIPO_INVESTIMENTO = 1 AND 
			I.ID_DETTAGLIO_INVESTIMENTO = 
			(SELECT DI.ID_DETTAGLIO_INVESTIMENTO FROM CODIFICA_INVESTIMENTO CI  INNER JOIN
			 DETTAGLIO_INVESTIMENTI DI ON CI.ID_CODIFICA_INVESTIMENTO = DI.ID_CODIFICA_INVESTIMENTO  WHERE
			 DI.COD_DETTAGLIO = '5' AND CI.CODICE = 'B' AND  CI.ID_BANDO = (SELECT ID_BANDO FROM PROGETTO WHERE ID_PROGETTO = @IdProgetto))) 

--- conto investimenti su codifica B per attrezzature (cod_dettaglio = 5)
SELECT @CONTA_ATTREZZATURE = (SELECT COUNT(I.ID_INVESTIMENTO) FROM PROGETTO P  INNER JOIN VPIANO_INVESTIMENTI I ON (P.ID_PROGETTO=I.ID_PROGETTO) WHERE
			I.ID_VARIANTE = @ID_VARIANTE AND isnull(COD_VARIAZIONE,'x')!='A' AND I.COD_TIPO_INVESTIMENTO = 1 AND 
			I.ID_DETTAGLIO_INVESTIMENTO = 
			(SELECT DI.ID_DETTAGLIO_INVESTIMENTO FROM CODIFICA_INVESTIMENTO CI  INNER JOIN
			 DETTAGLIO_INVESTIMENTI DI ON CI.ID_CODIFICA_INVESTIMENTO = DI.ID_CODIFICA_INVESTIMENTO  WHERE
			 DI.COD_DETTAGLIO = '5' AND CI.CODICE = 'B' AND  CI.ID_BANDO = (SELECT ID_BANDO FROM PROGETTO WHERE ID_PROGETTO = @IdProgetto))) 

--- conto investimenti su codifica B diverse da specifica per attrezzature 
SELECT @CONTA_ALTRO = (SELECT COUNT(I.ID_INVESTIMENTO) FROM PROGETTO P  INNER JOIN VPIANO_INVESTIMENTI I ON (P.ID_PROGETTO=I.ID_PROGETTO) WHERE
			I.ID_VARIANTE = @ID_VARIANTE AND isnull(COD_VARIAZIONE,'x')!='A' AND I.COD_TIPO_INVESTIMENTO = 1 AND 
			I.ID_DETTAGLIO_INVESTIMENTO in 
			(SELECT DI.ID_DETTAGLIO_INVESTIMENTO FROM CODIFICA_INVESTIMENTO CI  INNER JOIN
			 DETTAGLIO_INVESTIMENTI DI ON CI.ID_CODIFICA_INVESTIMENTO = DI.ID_CODIFICA_INVESTIMENTO  WHERE
			 DI.COD_DETTAGLIO != '5' AND CI.CODICE = 'B' AND  CI.ID_BANDO = (SELECT ID_BANDO FROM PROGETTO WHERE ID_PROGETTO = @IdProgetto))) 

IF ( 
(((ISNULL(@CONTA_ALTRO,0) >= 1) and (ISNULL(@CONTA_ATTREZZATURE,0) >= 1)) and  (((ISNULL(@COSTO_SPESE_TECNICHE,0) * 100) / @COSTO) <= 10)) OR
(((ISNULL(@CONTA_ALTRO,0) = 0) and (ISNULL(@CONTA_ATTREZZATURE,0) >= 1)) and  (((ISNULL(@COSTO_SPESE_TECNICHE,0) * 100) / @COSTO) <= 3)) OR
(((ISNULL(@CONTA_ALTRO,0) >= 1) and (ISNULL(@CONTA_ATTREZZATURE,0) = 0)))
)
SET @result = 1

SELECT @result AS RESULT
END
