CREATE  PROCEDURE [dbo].[calcoloRequisitoPagamento_GAL_GARE]
@ID_DOMANDA_PAGAMENTO int
AS
BEGIN

-- SALDO

--DECLARE @ID_DOMANDA_PAGAMENTO int
--SET @ID_DOMANDA_PAGAMENTO = 1
DECLARE @ID_PROGETTO INT, @RESULT INT,
		@REQ1 INT,@REQ2 INT,@REQ3 INT, 
		@REQ_TEXT_AREA INT, @REQ_PUBB_AGG INT,
		@SOGGETTO_PUBBLICO INT
					
SET @RESULT = 0 -- IMPONGO LO STEP NON VERIFICATO

-- PER IL CHECK DEVI VEDERE IL SELEZIONATO = 1 
-- PER IL TESTO INVECE VEDI CHE VAL_TESTO E VAL_DATA SIA != NULL 


SELECT @SOGGETTO_PUBBLICO = ISNULL(COUNT(COD_FORMA_GIURIDICA),0) FROM DOMANDA_DI_PAGAMENTO DP INNER JOIN
								PROGETTO PR ON DP.ID_PROGETTO = PR.ID_PROGETTO INNER JOIN 
								vIMPRESA VI ON PR.ID_IMPRESA = VI.ID_IMPRESA
								WHERE COD_FORMA_GIURIDICA LIKE '2%' AND DP.ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO


--472	Data del CONTRATTO pubblico con il contraente
--473	Data del COLLAUDO/certificato di regolare esecuzione/conformità // non è un campo di tipo data è stato voluto così dalla Barocci 
--474	Modalità di pubblicità del bando di gara
--475	Modalità di pubblicità dell`aggiudicazione

IF (@SOGGETTO_PUBBLICO = 1) 
BEGIN
	SELECT @REQ1 = CASE WHEN COUNT(*)>= 1 THEN 1 ELSE 0 END FROM DOMANDA_PAGAMENTO_REQUISITI WHERE ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO AND ID_REQUISITO IN ('466','467') AND (SELEZIONATO = 1 OR VAL_TESTO IS NOT NULL)
	SELECT @REQ2 = CASE WHEN COUNT(*)>= 1 THEN 1 ELSE 0 END FROM DOMANDA_PAGAMENTO_REQUISITI WHERE ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO AND ID_REQUISITO IN ('468','469') AND (SELEZIONATO = 1 OR VAL_TESTO IS NOT NULL)
	SELECT @REQ3 = CASE WHEN COUNT(*)>= 1 THEN 1 ELSE 0 END FROM DOMANDA_PAGAMENTO_REQUISITI WHERE ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO AND ID_REQUISITO IN ('470','471') AND (SELEZIONATO = 1 OR VAL_TESTO IS NOT NULL)


	SELECT @REQ_TEXT_AREA = CASE WHEN COUNT(*)= 3 THEN 1 ELSE 0 END FROM DOMANDA_PAGAMENTO_REQUISITI WHERE ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO AND ID_REQUISITO IN ('473','474','475') AND VAL_TESTO IS NOT NULL
	SELECT @REQ_PUBB_AGG = CASE WHEN COUNT(*)= 1 THEN 1 ELSE 0 END FROM DOMANDA_PAGAMENTO_REQUISITI WHERE ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO AND ID_REQUISITO = '472' AND VAL_DATA IS NOT NULL

	IF (@REQ1+@REQ2+@REQ3+@REQ_TEXT_AREA+@REQ_PUBB_AGG >= 5) SET @RESULT=1
END
ELSE SET @RESULT=1

SELECT @RESULT
END
