CREATE  PROCEDURE [dbo].[calcoloStepVariante112_311_7]
 @ID_VARIANTE INT
AS
 
-- 112-311 Rispetto della soglia del 10% per gli adeguamenti tenici (tenuto conto degli eventuali precedenti adeguamenti tecnici autorizzati)

DECLARE @IdProgetto INT
DECLARE @SPESA_AMMESSA_GRADUATORIA DECIMAL(18,2), @SPESA_AMMESSA_ADEGUAMENTO DECIMAL(18,2) ,
		@DIFF DECIMAL(18,2),@RESULT INT 
		
SET @IdProgetto = (SELECT ID_PROGETTO FROM VARIANTI WHERE ID_VARIANTE = @ID_VARIANTE)

-- TROVO IL PROGETTO CORRELATO
DECLARE @ID_PROG_CORRENTE_311 INT, @ID_BANDO_311 INT 

SELECT DISTINCT @ID_PROG_CORRENTE_311 = p.ID_PROGETTO, @ID_BANDO_311=P.ID_BANDO FROM PROGETTO P
	INNER JOIN BANDO B ON B.ID_BANDO = P.ID_BANDO INNER JOIN ZPROGRAMMAZIONE ZP ON ZP.ID =B.ID_PROGRAMMAZIONE AND CODICE = '3.1.1.A'
WHERE ID_PROG_INTEGRATO = @IdProgetto

SET @RESULT=1 -- LO IMPONGO VERIFICATO
SET @SPESA_AMMESSA_GRADUATORIA = (SELECT SUM(ISNULL(COSTO_INVESTIMENTO,0)) + SUM(ISNULL(SPESE_GENERALI,0)) 
						          FROM PIANO_INVESTIMENTI 
						          WHERE ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL AND ID_PROGETTO = @ID_PROG_CORRENTE_311)
 

SET @DIFF = (SELECT SUM( ABS( (PI_PREC.COSTO_INVESTIMENTO+ISNULL(PI_PREC.SPESE_GENERALI,0))-(PI.COSTO_INVESTIMENTO+ISNULL(PI.SPESE_GENERALI,0))) )
  					 	    FROM VARIANTI AS V 
								INNER JOIN (select  SUM(COSTO_INVESTIMENTO) AS COSTO_INVESTIMENTO, SUM( SPESE_GENERALI) AS SPESE_GENERALI , ID_PROGETTO,
												ID_INVESTIMENTO_ORIGINALE, ID_VARIANTE FROM PIANO_INVESTIMENTI GROUP BY ID_INVESTIMENTO_ORIGINALE, ID_VARIANTE, ID_PROGETTO )AS PI ON V.ID_VARIANTE = PI.ID_VARIANTE INNER JOIN
											  PIANO_INVESTIMENTI AS PI_PREC ON PI.ID_INVESTIMENTO_ORIGINALE = PI_PREC.ID_INVESTIMENTO
						    WHERE (V.COD_TIPO = 'AT') AND (V.APPROVATA = 1) AND (V.ANNULLATA = 0) AND (PI.ID_PROGETTO = @ID_PROG_CORRENTE_311) AND (V.DATA_MODIFICA <
												  (SELECT DATA_MODIFICA FROM VARIANTI
													WHERE (ID_VARIANTE = @ID_VARIANTE)))  OR  (V.COD_TIPO = 'AT') AND (PI.ID_PROGETTO = @ID_PROG_CORRENTE_311)  AND (V.ID_VARIANTE = @ID_VARIANTE)
						)

IF(ISNULL(@DIFF,0) > (@SPESA_AMMESSA_GRADUATORIA * 0.10)) SET @RESULT=0

SELECT @RESULT AS RESULT
