--ATS - Spese per coordinamento inferiore/uguale al 5% di A+B+C+D
CREATE  PROCEDURE [dbo].[calcoloStepVarianteATS_2]
@ID_VARIANTE INT
AS
BEGIN

DECLARE @result int 
DECLARE @TOTALE_INVESTIMENTO decimal(10,2)
DECLARE @TOTALE_9 decimal(10,2)
 
SET @result =1 -- PONGO LO STEP VERIFICATO 
SET @TOTALE_INVESTIMENTO = (SELECT SUM(PI.COSTO_INVESTIMENTO) AS COSTO_INVESTIMENTO
							FROM PIANO_INVESTIMENTI AS PI 
							WHERE (PI.ID_DETTAGLIO_INVESTIMENTO NOT IN (722, 727, 732, 737, 742)) AND 
							      (PI.ID_VARIANTE = @ID_VARIANTE) AND isnull(PI.COD_VARIAZIONE,'x')!='A' )
																
SET @TOTALE_9 =(SELECT ISNULL(SUM(PI.COSTO_INVESTIMENTO),0)
				FROM PIANO_INVESTIMENTI PI 
				WHERE PI.COD_TIPO_INVESTIMENTO = 1AND ID_VARIANTE=@ID_VARIANTE AND
					 PI.ID_SPECIFICA_INVESTIMENTO IN (348,409,418,427,436 ) AND isnull(PI.COD_VARIAZIONE,'x')!='A' )

IF(@TOTALE_9 > @TOTALE_INVESTIMENTO*0.05 )SET @result =0 
SELECT @result AS RESULT
END
