CREATE  PROCEDURE [dbo].[calcoloStepPagamento133_5]
@IdProgetto int,
@IdDomandaPagamento int =NULL
AS
 BEGIN
 
 --Spesa prodotto fornita dagli associati <=5% del totale annuale rendicontato 
-- anno =228

--DECLARE 
--@IdProgetto int,
--@IdDomandaPagamento int  
--SET @IdProgetto  =4543
--SET @IdDomandaPagamento=1224

DECLARE  @ANNO VARCHAR(4), @DATA_MODIFICA DATETIME,@ID_VARIANTE INT
DECLARE @RESULT INT, @ID_BANDO INT

DECLARE @DATA_MODIFICA_PAGAMENTO DATETIME,@ID_INVESTIMENTO INT,
		@IMPORTO_RENDICONTATO_ATTUALE DECIMAL(18,2),
		@CONTRIBUTO_RENDICONTATO_ATTUALE DECIMAL(18,2),@ID_FASCICOLO INT

--TROVO PROGETTO E ULTIMA VARIANTE RELATIVA A QUESTA DOMANDA DI PAGAMENTO
SELECT @DATA_MODIFICA_PAGAMENTO=DATA_MODIFICA,@IdProgetto=D.ID_PROGETTO,@ID_FASCICOLO=ID_FASCICOLO FROM DOMANDA_DI_PAGAMENTO D
	INNER JOIN PROGETTO P ON D.ID_PROGETTO=P.ID_PROGETTO WHERE ID_DOMANDA_PAGAMENTO=@IdDomandaPagamento
SELECT @ID_VARIANTE=MAX(ID_VARIANTE) FROM VARIANTI WHERE ID_PROGETTO=@IdProgetto AND APPROVATA=1 AND ANNULLATA=0 AND
	 DATA_MODIFICA<@DATA_MODIFICA_PAGAMENTO

--- TROVO IL BANDO
SELECT @ID_BANDO = ID_BANDO FROM PROGETTO WHERE ID_PROGETTO = @IdProgetto 

--CREO PIANO INVESTIMENTI VIRTUALE
DECLARE @INVESTIMENTI_VIRTUALE TABLE ([ID_INVESTIMENTO] [int] NOT NULL,
	[ID_PROGETTO] [int] NULL,
	[ID_CODIFICA_INVESTIMENTO] [int] NULL,
	[ID_DETTAGLIO_INVESTIMENTO] [int] NULL,
	IMPORTO_TOTALE_RENDICONTATO DECIMAL(18,2),
	CONTRIBUTO_TOTALE_RENDICONTATO DECIMAL(18,2))	

INSERT INTO @INVESTIMENTI_VIRTUALE
SELECT I.ID_INVESTIMENTO, I.ID_PROGETTO, I.ID_CODIFICA_INVESTIMENTO,I.ID_DETTAGLIO_INVESTIMENTO,
	Dbo.calcoloTotaleImportoRendicontatoAmmessoInvestimento (I.ID_INVESTIMENTO,@IdDomandaPagamento) AS IMPORTO_TOTALE_RENDICONTATO,
	dbo.calcoloTotaleContributoRendicontatoInvestimento(I.ID_INVESTIMENTO,@IdDomandaPagamento) AS CONTRIBUTO_TOTALE_RENDICONTATO 
FROM PROGETTO P INNER JOIN PIANO_INVESTIMENTI I ON P.ID_PROGETTO=I.ID_PROGETTO
WHERE ISNULL(P.ID_PROG_INTEGRATO,P.ID_PROGETTO)=@IdProgetto AND
	((@ID_VARIANTE IS NULL AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND AMMESSO=1 AND ID_VARIANTE IS NULL) OR
	(ID_VARIANTE=@ID_VARIANTE AND ISNULL(COD_VARIAZIONE,'X')!='A')) ORDER BY COD_TIPO_INVESTIMENTO

SET @RESULT = 1 -- IMPONGO LO STEP NON  VERIFICATO
-- CONTROLLO PER OGNI ANNO RENDICONTATO
IF(@ID_BANDO IN (267 ))BEGIN 
		SELECT @RESULT = COUNT(*) FROM(
					SELECT VALORE FROM(SELECT PXI.VALORE, 
								'SPESE_TOTALI' = CASE WHEN CO.CODICE NOT IN ('4','8','12','16') THEN  SUM(IMPORTO_TOTALE_RENDICONTATO)  END, 
								'SPESE_PRODOTTO' = CASE WHEN d.COD_DETTAGLIO='27' THEN SUM(IMPORTO_TOTALE_RENDICONTATO)END 
							FROM @INVESTIMENTI_VIRTUALE AS PI INNER JOIN  
								VPRIORITA_X_INVESTIMENTI PXI ON PI.ID_INVESTIMENTO = PXI.ID_INVESTIMENTO AND ID_PRIORITA = 399   
								INNER JOIN CODIFICA_INVESTIMENTO CO ON CO.ID_CODIFICA_INVESTIMENTO = PI.ID_CODIFICA_INVESTIMENTO
								inner join DETTAGLIO_INVESTIMENTI d on d.ID_CODIFICA_INVESTIMENTO = pi.ID_CODIFICA_INVESTIMENTO and d.ID_DETTAGLIO_INVESTIMENTO = pi.ID_DETTAGLIO_INVESTIMENTO
							WHERE ID_PROGETTO =@IdProgetto
							GROUP BY  PXI.VALORE, CODICE, COD_DETTAGLIO)as t
						group by VALORE	
						HAVING   ((SUM(ISNULL( SPESE_PRODOTTO,0)) *100 )/isnull(nullif(SUM(ISNULL(SPESE_TOTALI,1)),0),1)) >5 )as Ca 

END
ELSE BEGIN
	SELECT @RESULT = COUNT(*) FROM(
					SELECT VALORE FROM(SELECT PXI.VALORE, 
								'SPESE_TOTALI' = CASE WHEN CO.CODICE IN ('1','2','3') THEN  SUM(IMPORTO_TOTALE_RENDICONTATO)  END, 
								'SPESE_PRODOTTO' = CASE WHEN d.COD_DETTAGLIO='27' THEN SUM(IMPORTO_TOTALE_RENDICONTATO)END 
							FROM @INVESTIMENTI_VIRTUALE AS PI INNER JOIN  
								VPRIORITA_X_INVESTIMENTI PXI ON PI.ID_INVESTIMENTO = PXI.ID_INVESTIMENTO AND ID_PRIORITA = 399   
								INNER JOIN CODIFICA_INVESTIMENTO CO ON CO.ID_CODIFICA_INVESTIMENTO = PI.ID_CODIFICA_INVESTIMENTO
								inner join DETTAGLIO_INVESTIMENTI d on d.ID_CODIFICA_INVESTIMENTO = pi.ID_CODIFICA_INVESTIMENTO and d.ID_DETTAGLIO_INVESTIMENTO = pi.ID_DETTAGLIO_INVESTIMENTO
							WHERE ID_PROGETTO =@IdProgetto
							GROUP BY  PXI.VALORE, CODICE, COD_DETTAGLIO)as t
						group by VALORE	
						HAVING((SUM(ISNULL( SPESE_PRODOTTO,0)) *100 )/  isnull(nullif(SUM(ISNULL(SPESE_TOTALI,1)),0),1)) >5)as Ca 
END				
SELECT @RESULT
END
