CREATE PROCEDURE [dbo].[calcoloRequisitoPagamento_B404]
@ID_DOMANDA_PAGAMENTO int
AS
BEGIN

-- SALDO
-- VERIFICA SE L'INTERVENTO E LA SUBMISURA SONO CORRETTI
---

--DECLARE @ID_DOMANDA_PAGAMENTO int
--SET @ID_DOMANDA_PAGAMENTO = 1

DECLARE @ID_PROGETTO INT, 
					@RESULT INT,
					@CONTA INT

-- INIZIALIZZO A FALSE
SET @RESULT = 0

SET @ID_PROGETTO = (SELECT ID_PROGETTO FROM DOMANDA_DI_PAGAMENTO WHERE ID_DOMANDA_PAGAMENTO=@ID_DOMANDA_PAGAMENTO)

SET @CONTA = (SELECT COUNT(ID_INVESTIMENTO) FROM  VPIANO_INVESTIMENTI INV
INNER JOIN vzPROGRAMMAZIONE PP ON PP.ID = INV.ID_PROGRAMMAZIONE
LEFT JOIN (SELECT MAX(ID_VARIANTE)ID_VAR , ID_PROGETTO FROM VARIANTI WHERE ID_PROGETTO = @ID_PROGETTO AND APPROVATA = 1 GROUP BY ID_PROGETTO) AS V ON INV.ID_PROGETTO = V.ID_PROGETTO 
WHERE ((V.ID_VAR IS NULL AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL) OR(V.ID_VAR IS NOT NULL AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE = ID_VAR ))  AND   
PP.CODICE LIKE '%4.1.35.H%' AND INV.ID_PROGETTO = @ID_PROGETTO)

IF(@CONTA >= 1)SET @RESULT=0 
ELSE BEGIN
  SET @RESULT=1 
 END
SELECT @RESULT
END

--FATTO!!!
