CREATE PROCEDURE [dbo].[calcoloStep124pabs]
(
@IdProgetto int,
@FASE_ISTRUTTORIA INT =0
)
AS
BEGIN

DECLARE @RESULT int,
		@SPESEQUOTA int,
		@SPESE int,
		@SPESENOQUOTA int

--- Inserito valore quota per divulgazione ASSAM dove previsto 124PABS
SET @RESULT = 0 -- PONGO LO STEP IN STATO NON VERIFICATO

SET @SPESEQUOTA = (SELECT count(VALORE) FROM PRIORITA_X_INVESTIMENTI PI inner join    
vPIANO_INVESTIMENTI VPI on VPI.ID_INVESTIMENTO = PI.ID_INVESTIMENTO WHERE
((VPI.ID_INVESTIMENTO_ORIGINALE IS NULL AND @FASE_ISTRUTTORIA=0 AND ID_VARIANTE IS NULL)OR(VPI.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND @FASE_ISTRUTTORIA =1 AND ID_VARIANTE IS NULL)) AND
PI.ID_PRIORITA = 733 AND 
VPI.CODICE in ('1A','1B','1C','1D','1E','1F','1G','1H','1I','1L','1M','1N','1O') AND
VPI.ID_PROGETTO = @IdProgetto AND
VALORE IS NOT NULL)


SET @SPESE = (SELECT count(ID_INVESTIMENTO) FROM VPIANO_INVESTIMENTI WHERE
((ID_INVESTIMENTO_ORIGINALE IS NULL AND @FASE_ISTRUTTORIA=0 AND ID_VARIANTE IS NULL)OR(ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND @FASE_ISTRUTTORIA =1 AND ID_VARIANTE IS NULL)) AND
CODICE in ('1A','1B','1C','1D','1E','1F','1G','1H','1I','1L','1M','1N','1O') AND
ID_PROGETTO = @IdProgetto)


SET @SPESENOQUOTA = (SELECT count(VALORE) FROM PRIORITA_X_INVESTIMENTI PI inner join    
vPIANO_INVESTIMENTI VPI on VPI.ID_INVESTIMENTO = PI.ID_INVESTIMENTO INNER JOIN
DETTAGLIO_INVESTIMENTI DI ON (DI.ID_DETTAGLIO_INVESTIMENTO=VPI.ID_DETTAGLIO_INVESTIMENTO) WHERE
((VPI.ID_INVESTIMENTO_ORIGINALE IS NULL AND @FASE_ISTRUTTORIA=0 AND ID_VARIANTE IS NULL)OR(VPI.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND @FASE_ISTRUTTORIA =1 AND ID_VARIANTE IS NULL)) AND
PI.ID_PRIORITA = 733 AND
VPI.CODICE in ('A','B','C','D','E','F','G','H','I','L','M','N','O','P') AND 
VPI.ID_PROGETTO = @IdProgetto AND
 VALORE IS NOT NULL AND VALORE != 0)


IF((@SPESEQUOTA  = @SPESE) and (@SPESENOQUOTA =0))
    SET @RESULT =1
ELSE  SET @RESULT=0
SELECT @RESULT
END
