---CONTROLLO REQUISITI DI FILIERA
 
CREATE  PROCEDURE [dbo].[calcoloStepMicro_1]
@IdProgetto int
AS
BEGIN
 
--232,233,234,277,284   microfiliera
-- 798 id priorita microfileira  
-- obbligatorio il quadro sitra --- aggiunto valore "Non previsto"
--DECLARE @IdProgetto int
--SET @IdProgetto = 7661


DECLARE  @RESULT INT , @ID_BANDO INT, @C INT
SET @ID_BANDO = (SELECT ID_BANDO FROM PROGETTO WHERE ID_PROGETTO =@IdProgetto )
SET @RESULT =0 --PONGO LO STEP NN VERIFICATO
 
IF((SELECT COUNT(*)  FROM PRIORITA_X_PROGETTO PP  WHERE ID_PRIORITA IN (798,1191) AND  ID_PROGETTO =@IdProgetto ) =1)
BEGIN
-- microfiliere -- CONTROLLO SIATEMA DI QUALITA
IF((SELECT COUNT(*)  FROM PRIORITA_X_PROGETTO PP  WHERE ID_PRIORITA IN (232,233,234,277,284,866) AND ID_PROGETTO =@IdProgetto ) >= 1)
  BEGIN 
 --- CONTROLLO RUOLO SITRA;  CONTROLLO RUOLO OPERATIVO; CONTROLLO SELEZIONE FILIeRA micro
  IF((SELECT COUNT(*)  FROM PRIORITA_X_PROGETTO PP  WHERE ID_PRIORITA IN (390,391, 798,1191 ) AND  ID_PROGETTO =@IdProgetto ) =3)
		BEGIN  SET @RESULT =1  END
 END
END
SELECT   @RESULT  
END
