CREATE  PROCEDURE [dbo].[calcoloRequisitoPagamento_A_431_1]
 @ID_DOMANDA_PAGAMENTO int
AS
BEGIN 
--- massimale di intervento A
DECLARE @RESULT int,		 
		@CONTRIBUTO_RICHIESTO_PROGETTO_A DECIMAL (10,2),	 
	 	@CONTRIBUTO_ANTICIPO DECIMAL(10,2), @IdProgetto INT
	
SET @RESULT = 0  -- Impongo lo Step NON verificato
SET @IdProgetto = (SELECT ID_PROGETTO FROM DOMANDA_DI_PAGAMENTO WHERE ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO)


--------------------------------------------------------------------------------------------------------------
SET @CONTRIBUTO_RICHIESTO_PROGETTO_A = (SELECT SUM(PI.CONTRIBUTO_RICHIESTO) AS CONTRIBUTO
										FROM PIANO_INVESTIMENTI PI INNER JOIN
											 vPROGETTO P ON PI.ID_PROGETTO = P.ID_PROGETTO
										WHERE (PI.ID_PROGETTO = @IdProgetto) AND PI.ID_PROGRAMMAZIONE = 325 AND
									       ((PI.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND P.COD_STATO !='P' AND ID_VARIANTE IS NULL)))

 
SET @CONTRIBUTO_ANTICIPO = (SELECT  ISNULL(CONTRIBUTO_RICHIESTO,0) 
							FROM ANTICIPI_RICHIESTI 
							WHERE ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO)
							
IF (@CONTRIBUTO_ANTICIPO <= (ISNULL(@CONTRIBUTO_RICHIESTO_PROGETTO_A ,0 ) * 0.2 ) )
	 SET @RESULT = 1
 
 SELECT @RESULT
 END
