CREATE PROCEDURE [dbo].[calcoloStep413_FERM_3]
@IdProgetto int, 
@FASE_ISTRUTTORIA INT =0
AS
BEGIN

--declare @IdProgetto int =10291

-- Comuni GAL Fermano  
-- CONTROLLO SPESE TECNICHE

DECLARE @result int, @SPESE_TECNICHE_10 DECIMAL(18,2),@SPESE_TECNICHE_3 DECIMAL(18,2),
@COSTO_PROGETTO_10 DECIMAL(18,2),@COSTO_PROGETTO_3 DECIMAL(18,2), @COUNT_INVESTIMENTI_STECNICHE INT
SET @result = 0 -- NON VERIFICATO
 
SELECT @COSTO_PROGETTO_10=SUM(COSTO_INVESTIMENTO )
FROM PIANO_INVESTIMENTI inv 
	INNER JOIN CODIFICA_INVESTIMENTO C ON C.ID_CODIFICA_INVESTIMENTO= INV.ID_CODIFICA_INVESTIMENTO
where ID_PROGETTO = @IdProgetto and ID_INVESTIMENTO_ORIGINALE is not null AND ID_VARIANTE IS NULL AND CODICE in( 'a','b','f')

SELECT @SPESE_TECNICHE_10 = SUM(COSTO_INVESTIMENTO ) 
FROM PIANO_INVESTIMENTI inv 
	INNER JOIN CODIFICA_INVESTIMENTO C ON C.ID_CODIFICA_INVESTIMENTO= INV.ID_CODIFICA_INVESTIMENTO
where ID_PROGETTO = @IdProgetto and ID_INVESTIMENTO_ORIGINALE is not null AND ID_VARIANTE IS NULL AND CODICE in( 'X')
 
--- CONTROLLO 10%
IF(ISNULL(@SPESE_TECNICHE_10, 0) <=(ISNULL(@COSTO_PROGETTO_10,0) * 0.10)) SET @result =1 

SELECT @COSTO_PROGETTO_3=SUM(COSTO_INVESTIMENTO )
FROM PIANO_INVESTIMENTI inv 
	INNER JOIN CODIFICA_INVESTIMENTO C ON C.ID_CODIFICA_INVESTIMENTO= INV.ID_CODIFICA_INVESTIMENTO
where ID_PROGETTO = @IdProgetto and ID_INVESTIMENTO_ORIGINALE is not null AND ID_VARIANTE IS NULL AND CODICE in( 'c','d','e')

SELECT @SPESE_TECNICHE_3 = SUM(COSTO_INVESTIMENTO ) 
FROM PIANO_INVESTIMENTI inv 
	INNER JOIN CODIFICA_INVESTIMENTO C ON C.ID_CODIFICA_INVESTIMENTO= INV.ID_CODIFICA_INVESTIMENTO
where ID_PROGETTO = @IdProgetto and ID_INVESTIMENTO_ORIGINALE is not null AND ID_VARIANTE IS NULL AND CODICE in( 'Z')
 
 
--- CONTROLLO 3
IF(ISNULL(@SPESE_TECNICHE_3,0) <=(ISNULL(@COSTO_PROGETTO_3,0) * 0.03)) SET @result =1 
else SET @result = 0


 -- NON SI CONTENTE IL RILASCIO CON LE SPESE TECNICHE IMPUTATE IN DUE PUNTI
SELECT @COUNT_INVESTIMENTI_STECNICHE = COUNT(*)
FROM PIANO_INVESTIMENTI inv 
	INNER JOIN CODIFICA_INVESTIMENTO C ON C.ID_CODIFICA_INVESTIMENTO= INV.ID_CODIFICA_INVESTIMENTO
where ID_PROGETTO = @IdProgetto and ID_INVESTIMENTO_ORIGINALE is not null AND ID_VARIANTE IS NULL AND CODICE not in( 'X','Z') AND SPESE_GENERALI >0

IF(ISNULL(@COUNT_INVESTIMENTI_STECNICHE,0) >0 AND  isnull(@SPESE_TECNICHE_10,0) + isnull(@SPESE_TECNICHE_3,0) > 0 ) SET @result =0

SELECT @result AS RESULT

END
