CREATE PROCEDURE [dbo].[calcoloPriorita413_7]
(@IdProgetto int,
@FASE_ISTRUTTORIA bit = 0,
@IdVariante INT = 0
)

AS
BEGIN

DECLARE @CI int
DECLARE @CT int
DECLARE @CTOT int

-- Controllo se tutti gli investimenti ricadono in NATURA 2000
SET @CI =(SELECT COUNT(*) FROM PIANO_INVESTIMENTI PI INNER JOIN PRIORITA_X_INVESTIMENTI PXI ON PI.ID_INVESTIMENTO = PXI.ID_INVESTIMENTO 
WHERE PXI.ID_PRIORITA = 524 AND PI.ID_PROGETTO = @IdProgetto 
		  AND ((@fase_istruttoria=0 AND PI.ID_INVESTIMENTO_ORIGINALE IS NULL AND ID_VARIANTE IS NULL)
		  OR (@fase_istruttoria=1 AND (PI.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL AND @IdVariante IS NULL) 
		  OR (ID_VARIANTE  = @IdVariante AND @IdVariante IS NOT NULL AND ISNULL(COD_VARIAZIONE, 'X' ) != 'A'))))

SET @CT =(SELECT COUNT(*) FROM PIANO_INVESTIMENTI WHERE ID_PROGETTO = @IdProgetto
		  AND ((@fase_istruttoria=0 AND ID_INVESTIMENTO_ORIGINALE IS NULL AND ID_VARIANTE IS NULL)
		  OR (@fase_istruttoria=1 AND (ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL AND @IdVariante IS NULL) 
		  OR (ID_VARIANTE  = @IdVariante AND @IdVariante IS NOT NULL AND ISNULL(COD_VARIAZIONE, 'X' ) != 'A'))))

IF ((@CT - @CI) =0) SELECT 1
	ELSE SELECT 0 
END
