CREATE PROCEDURE [dbo].[calcoloStepVariante112_9]
@ID_VARIANTE int
AS
BEGIN

  
-- Verifica del raggiungimento del punteggio minimo  IN PRESENTAZIONE
-- E 112 - 121 - VERIFICA STEP DI MISURA 121  112 - 311 - VERIFICA STEP DI MISURA 311 PER L'ISTRUTTORIA
--DECLARE  @ID_VARIANTE int
--SET @ID_VARIANTE = 1339

DECLARE @RILASCIATA INT, @C_ISTR INT, @C_121 INT, @C_311 INT
			
SET @C_ISTR= 0
SELECT @RILASCIATA= COUNT(*) FROM VARIANTI WHERE ID_VARIANTE = @ID_VARIANTE AND SEGNATURA IS NOT NULL

IF(@RILASCIATA=0)
BEGIN 
	SET @C_121 = (SELECT COUNT(*) FROM VARIANTI_ESITI_REQUISITI  WHERE ID_VARIANTE =  @ID_VARIANTE AND ID_REQUISITO IN (16,22,18,17 )AND ISNULL(COD_ESITO_istruttore, COD_ESITO)='NO')
	SET @C_311 = (SELECT COUNT(*) FROM VARIANTI_ESITI_REQUISITI  WHERE ID_VARIANTE =  @ID_VARIANTE AND ID_REQUISITO IN (19,20) AND ISNULL(COD_ESITO_istruttore, COD_ESITO)='NO')
   IF(@C_121>0 AND @C_311>0  ) SET @C_ISTR=0 ELSE SET @C_ISTR=1
END
ELSE BEGIN 
	SELECT @C_ISTR= COUNT(*) FROM VARIANTI_ESITI_REQUISITI WHERE ID_VARIANTE=@ID_VARIANTE AND ID_REQUISITO IN (101,103)  AND ISNULL(COD_ESITO_istruttore, COD_ESITO)='SI'
END
IF(@C_ISTR>0) SELECT 1 ELSE SELECT 0
END
