CREATE PROCEDURE [dbo].[calcoloPolizzaFidejussoria]
(
	@ID_PROGETTO INT, --ID DEL PROGETTO SPECIFICO PER LA MISURA
	@FASE_ISTRUTTORIA BIT =0 --SE FASE ISTRUTTORIA TRUE, ALTRIMENTI DEVO CALCOLARE PER GLI INVESTIMENTI ORIGINALI
)
AS
/*
DECLARE @ID_PROGETTO INT
DECLARE	@FASE_ISTRUTTORIA BIT 
SET @ID_PROGETTO= 118
SET	@FASE_ISTRUTTORIA =1*/

-- RECUPERO I DATI DELLA POLIZZA FIDEJUSSORIA
DECLARE @MAX_AIUTO DECIMAL(15,2)
DECLARE @MIN_AIUTO DECIMAL(15,2)
DECLARE @MAX_QUOTA DECIMAL(15,2)
DECLARE @COD_AIUTO INT

DECLARE TAIUTO CURSOR FOR (
SELECT COD_TIPO_INVESTIMENTO,ISNULL(IMPORTO_MIN,0),ISNULL(IMPORTO_MAX,1000000000),ISNULL(QUOTA_MAX,100) FROM PROGETTO AS P 
INNER JOIN BANDO_TIPO_INVESTIMENTI AS B ON P.ID_BANDO=B.ID_BANDO AND COD_TIPO_INVESTIMENTO=4
WHERE P.ID_PROGETTO=@ID_PROGETTO)

OPEN TAIUTO
FETCH NEXT FROM TAIUTO 
INTO @COD_AIUTO,@MIN_AIUTO,@MAX_AIUTO,@MAX_QUOTA
CLOSE TAIUTO
DEALLOCATE TAIUTO
----------------------------------------------

IF @COD_AIUTO IS NULL RAISERROR('TIPOLOGIA DI INVESTIMENTO "POLIZZA FIDEJUSSORIA" NON ASSOCIATA AL BANDO',13,1)
ELSE
BEGIN
	--COSTO TOTALE DEGLI INVESTIMENTI
	DECLARE @COSTO_TOTALE DECIMAL(18,2), @SPESE_TOTALI DECIMAL(18,2)
	SELECT @COSTO_TOTALE=SUM(COSTO_INVESTIMENTO),
		@SPESE_TOTALI=	CAST(SUM((CONTRIBUTO_RICHIESTO/QUOTA_CONTRIBUTO_RICHIESTO*100)- COSTO_INVESTIMENTO) AS DECIMAL(18,2))
		FROM PIANO_INVESTIMENTI WHERE ID_PROGETTO=@ID_PROGETTO AND COD_TIPO_INVESTIMENTO =1	AND 
		((@FASE_ISTRUTTORIA=0 AND ID_INVESTIMENTO_ORIGINALE IS NULL) OR 
		(@FASE_ISTRUTTORIA=1 AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL))
	---------------------------------------------

	--COSTO TOTALE DEI BREVETTI
	DECLARE @COSTO_BREVETTI DECIMAL(18,2)
	SELECT @COSTO_BREVETTI=SUM(COSTO_INVESTIMENTO) FROM PIANO_INVESTIMENTI 
		WHERE ID_PROGETTO=@ID_PROGETTO AND COD_TIPO_INVESTIMENTO =5	and
		((@FASE_ISTRUTTORIA=0 AND ID_INVESTIMENTO_ORIGINALE IS NULL) OR 
		(@FASE_ISTRUTTORIA=1 AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL))
	---------------------------------------------

	--PERCENTUALE MAX SPESE GENERALI 
	DECLARE @MAX_SPESE_GENERALI DECIMAL(18,2)
	SELECT @MAX_SPESE_GENERALI=ISNULL(QUOTA_MAX,100) FROM PROGETTO AS P INNER JOIN BANDO_TIPO_INVESTIMENTI AS B 
	ON P.ID_BANDO=B.ID_BANDO AND COD_TIPO_INVESTIMENTO=6 WHERE P.ID_PROGETTO=@ID_PROGETTO
	---------------------------------------------	
	
	--AMMONTARE DELLA POLIZZA
	DECLARE @POLIZZA DECIMAL(18,2)
	DECLARE @RESTO DECIMAL(18,2)
	SET @POLIZZA=@COSTO_TOTALE/100*@MAX_QUOTA --% SU COSTO TOTALE INVESTIMENTI
	
	IF(@MAX_SPESE_GENERALI IS NOT NULL)BEGIN
		--RIMANENTE DEI SOLDI CHE POSSONO ESSERE ATTRIBUITI ALLE SPESE DI POLIZZA
		SET @RESTO=@COSTO_TOTALE/100*@MAX_SPESE_GENERALI-@SPESE_TOTALI-ISNULL(@COSTO_BREVETTI,0)
		IF(@RESTO>0)BEGIN
			SET @RESTO=@RESTO-@POLIZZA --SE LA POLIZZA NON RIENTRA TUTTA NEL RESTO 
			IF(@RESTO<0)SET @POLIZZA=@POLIZZA+@RESTO --	LA SOTTRAGGO A QUELLO CHE ECCEDE COSI TROVO LA PARTE CHE PUO' ESSERE FINANZIATA
		END			
		ELSE BEGIN
			SET @POLIZZA=0
		END
	END	

	--------SE LA POLIZZA E' GIA' PRESENTE SUL DB RITORNO L'ID PER AGGIORNARLO
	DECLARE @ID_INVESTIMENTO INT,@ID_INVESTIMENTO_ORIGINALE INT
	SELECT @ID_INVESTIMENTO=ID_INVESTIMENTO,@ID_INVESTIMENTO_ORIGINALE=ID_INVESTIMENTO_ORIGINALE FROM PIANO_INVESTIMENTI WHERE ID_PROGETTO=@ID_PROGETTO AND COD_TIPO_INVESTIMENTO=4 AND
	((@FASE_ISTRUTTORIA=0 AND ID_INVESTIMENTO_ORIGINALE IS NULL) OR 
	(@FASE_ISTRUTTORIA=1 AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL))
	----------------------------------------------
	
	IF(@POLIZZA>0)BEGIN
		
		--IMPOSTO COME MASSIMALI I VALORI DELL'ORIGINALE
		DECLARE @AMMONTARE_ORIGINALE DECIMAL (18,2),@CONTRIBUTO_ORIGINALE DECIMAL (18,2)
		IF(@FASE_ISTRUTTORIA=1 AND @ID_INVESTIMENTO_ORIGINALE IS NOT NULL) BEGIN
			SELECT @AMMONTARE_ORIGINALE =COSTO_INVESTIMENTO, @CONTRIBUTO_ORIGINALE=CONTRIBUTO_RICHIESTO FROM PIANO_INVESTIMENTI 
			WHERE ID_INVESTIMENTO=@ID_INVESTIMENTO_ORIGINALE
			IF(@AMMONTARE_ORIGINALE IS NOT NULL AND @AMMONTARE_ORIGINALE<@POLIZZA) SET @POLIZZA=@AMMONTARE_ORIGINALE			
		END
		--CALCOLO GLI INVESTIMENTI SU CUI SPALMARE IL COSTO DELLA POLIZZA
		DECLARE @CONTRIBUTO_POLIZZA DECIMAL(18,2)
		SET @CONTRIBUTO_POLIZZA =0
		DECLARE @COSTO_INVESTIMENTO DECIMAL(18,2)
		DECLARE @CONTRIBUTO DECIMAL(18,2)
		DECLARE TOTALE CURSOR FOR
		(SELECT COSTO_INVESTIMENTO,QUOTA_CONTRIBUTO_RICHIESTO FROM PIANO_INVESTIMENTI 
			WHERE ID_PROGETTO=@ID_PROGETTO AND COD_TIPO_INVESTIMENTO =1 AND
		((@FASE_ISTRUTTORIA=0 AND ID_INVESTIMENTO_ORIGINALE IS NULL) OR 
		(@FASE_ISTRUTTORIA=1 AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL)))
		OPEN TOTALE
		FETCH NEXT FROM TOTALE 
		INTO @COSTO_INVESTIMENTO,@CONTRIBUTO
		WHILE @@FETCH_STATUS = 0
		BEGIN
			DECLARE @PARTE_POLIZZA DECIMAL(18,2)
			SET @PARTE_POLIZZA= @POLIZZA*@COSTO_INVESTIMENTO/@COSTO_TOTALE
			SET @CONTRIBUTO_POLIZZA=@CONTRIBUTO_POLIZZA+@CONTRIBUTO*@PARTE_POLIZZA/100	
			FETCH NEXT FROM TOTALE 
			INTO @COSTO_INVESTIMENTO,@CONTRIBUTO
		END
		CLOSE TOTALE
		DEALLOCATE TOTALE
		-------------------------------------------------------

		-- IL CONTRIBUTO NON PUO' SUPERARE QUELLO RICHIESTO
		IF(@FASE_ISTRUTTORIA=1 AND @ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND @CONTRIBUTO_ORIGINALE IS NOT NULL 
			AND @CONTRIBUTO_ORIGINALE<@CONTRIBUTO_POLIZZA) SET @CONTRIBUTO_POLIZZA=@CONTRIBUTO_ORIGINALE
	END

	------------------------------------------
	
	SELECT @POLIZZA AS AMMONTARE_POLIZZA,@CONTRIBUTO_POLIZZA AS CONTRIBUTO_POLIZZA,CAST(@CONTRIBUTO_POLIZZA/@POLIZZA*100 AS DECIMAL(18,2)) 
	AS QUOTA_CONTRIBUTO_POLIZZA,@ID_INVESTIMENTO AS ID_INVESTIMENTO

END
