CREATE  PROCEDURE [dbo].[calcoloStepPagamento123_2]
@IdProgetto int,
@IdDomandaPagamento int =NULL
AS
BEGIN

	-- verificato che la richiesta di SAL è inferiore del 70% del contributo concesso 

	DECLARE  @ID_VARIANTE INT, @RESULT INT
    DECLARE @CONTRIBUTO_PROGETTO decimal(10,2), @CONTRIBUTO_RICHIESTO_PAG DECIMAL(10,2)

SET @RESULT = 1 -- IMPONGO LO STEP VERIFICATO		 
SET @ID_VARIANTE =  (SELECT MAX(ID_VARIANTE) FROM VARIANTI WHERE ID_PROGETTO = @IdProgetto AND APPROVATA =1 AND ANNULLATA =0)
SET @CONTRIBUTO_PROGETTO = ISNULL((SELECT dbo.[calcoloContributoTotaleProgettoCorrelato] (@IdProgetto, 1, @ID_VARIANTE)), 0)

SET @CONTRIBUTO_RICHIESTO_PAG = (SELECT SUM(ISNULL(CONTRIBUTO_AMMESSO,0)) + SUM(ISNULL(CONTRIBUTO_AMMESSO_RECUPERO_ANTICIPO,0)) 
									FROM PAGAMENTI_RICHIESTI WHERE ID_DOMANDA_PAGAMENTO =@IdDomandaPagamento)

IF(@CONTRIBUTO_RICHIESTO_PAG > (@CONTRIBUTO_PROGETTO * 0.70 ))
	SET @RESULT = 0
 
SELECT @RESULT
END
