CREATE PROCEDURE [dbo].[calcoloStep123_1]
@IdProgetto int
AS
BEGIN

-- 123 a) certificazione difficoltà impresa con Bilanci chiusi

DECLARE @Result int,@DATA datetime , 
		@ID_Impresa int, @CAPITALE_1 decimal(10,2),  @CAPITALE_2 decimal(10,2), @CAPITALE_3 decimal(10,2)

SET @Result = 0 -- Impongo lo Step non verificato


 SELECT @ID_Impresa = Id_Impresa, @DATA=DATA
 FROM PROGETTO P  INNER JOIN PROGETTO_STORICO S ON  P.ID_PROGETTO = S.ID_PROGETTO 
 where P.ID_PROGETTO = @IdProgetto AND COD_STATO IN ('P','L')
 ORDER BY S.ID DESC 

DECLARE @ANNO INT, @CAPITALE decimal (10,2)

DECLARE @d decimal(10,2), @e decimal (10,2)
DECLARE BILANCIO_INDUSTRIALE CURSOR  FOR 
SELECT TOP(3) ISNULL(TP_PN_CAPITALE,0) AS TP_PN_CAPITALE, ANNO  FROM BILANCIO_INDUSTRIALE 
WHERE PREVISIONALE = 0  and ID_IMPRESA = @ID_Impresa AND DATEDIFF(day, BILANCIO_INDUSTRIALE.data_Modifica, @DATA ) >=0  group by TP_PN_CAPITALE, ANNO order by anno DESC

DECLARE @count int
SET @count=0

OPEN BILANCIO_INDUSTRIALE
FETCH NEXT FROM BILANCIO_INDUSTRIALE 
INTO @CAPITALE , @ANNO
WHILE @@FETCH_STATUS = 0
BEGIN 
	IF @COUNT =0 BEGIN SET	@CAPITALE_1 = @CAPITALE	END
	ELSE IF @COUNT = 1 BEGIN SET @CAPITALE_2 = @CAPITALE	END
	ELSE IF @COUNT = 2 BEGIN SET @CAPITALE_3= @CAPITALE	END
	SET @count = @count + 1
 FETCH NEXT FROM BILANCIO_INDUSTRIALE 
 INTO  @CAPITALE , @ANNO
END

CLOSE BILANCIO_INDUSTRIALE
DEALLOCATE BILANCIO_INDUSTRIALE

set @d = (ISNULL(@CAPITALE_1,0) - ISNULL(@CAPITALE_3,0 ))/ISNULL(@CAPITALE_3,1)
IF @d >=0 set @Result = 1
ELSE
	BEGIN 
		IF abs(@d)<= 0.50 SET  @Result = 1
		ELSE BEGIN
			SET @e = (ISNULL(@CAPITALE_2,0) - ISNULL(@CAPITALE_3,0))/ISNULL(@CAPITALE_3,1)
			IF abs(@d - @e )<=0.25  	
			SET  @Result = 1
		END
	END
SELECT @Result AS RESULT
END
