CREATE PROCEDURE [dbo].[calcoloStep111_12]
	@IdProgetto int,
	@FASE_ISTRUTTORIA INT =0 
AS
BEGIN
DECLARE @ID_IMPRESA INT , @RESULT INT, @PROGETTI_121  INT, @CF_RAPP_LEGALE VARCHAR(16)

SET @RESULT = 1 --> VERIFICATO

-- 111 CUAA PRESENTE in un elenco di pagamento provinciale  Bando PSR Misura 121
SELECT @ID_IMPRESA = P.ID_IMPRESA ,@CF_RAPP_LEGALE = PP.CODICE_FISCALE 
FROM PROGETTO P INNER JOIN  VIMPRESA IMP ON IMP.ID_IMPRESA = P.ID_IMPRESA
INNER JOIN VPERSONE_X_IMPRESE PP ON PP.ID_PERSONE_X_IMPRESE = IMP.ID_RAPPRLEGALE_ULTIMO
WHERE ID_PROGETTO=@IdProgetto

SELECT @PROGETTI_121=COUNT(*)
FROM PROGETTO P INNER JOIN (SELECT MAX(ID_PROGRAMMAZIONE)ID_PROGRAMMAZIONE, ID_BANDO 
							FROM VBANDO_PROGRAMMAZIONE WHERE CODICE LIKE '1.2.1%' AND COD_PSR LIKE 'PSR%' GROUP BY ID_BANDO )PB ON P.ID_BANDO = PB.ID_BANDO 
	INNER JOIN DOMANDA_DI_PAGAMENTO_ESPORTAZIONE DPE ON DPE.ID_PROGETTO = P.ID_PROGETTO 
	INNER JOIN DOMANDA_DI_PAGAMENTO DP ON DP.ID_DOMANDA_PAGAMENTO= DPE.ID_DOMANDA_PAGAMENTO AND DP.COD_TIPO = 'SLD'
	INNER JOIN VPERSONE_X_IMPRESE PP ON PP.ID_IMPRESA = P.ID_IMPRESA AND DATA_INIZIO < DP.DATA_MODIFICA AND ISNULL(DATA_FINE, GETDATE()) > DP.DATA_MODIFICA AND COD_RUOLO = 'R' AND PP.CODICE_FISCALE = @CF_RAPP_LEGALE
WHERE P.ID_IMPRESA = @ID_IMPRESA AND DPE.ID_ELENCO_PAGAMENTO IS NOT NULL

IF(ISNULL(@PROGETTI_121,0)>0)SET @RESULT = 0
ELSE BEGIN 
	SELECT @PROGETTI_121=COUNT(*) FROM VPROGETTO P 
	INNER JOIN (SELECT MAX(ID_PROGRAMMAZIONE)ID_PROGRAMMAZIONE, ID_BANDO 
				FROM VBANDO_PROGRAMMAZIONE WHERE CODICE LIKE '1.2.1%' AND COD_PSR LIKE 'PSR%' GROUP BY ID_BANDO )PB ON P.ID_BANDO = PB.ID_BANDO 
	WHERE P.ID_IMPRESA=@ID_IMPRESA AND P.ORDINE_FASE >=3 AND P.COD_STATO NOT IN ('N','R','E','B')

	IF(ISNULL(@PROGETTI_121,0)=0) SET @RESULT = 0
END
SELECT @RESULT AS RESULT

END
