CREATE   PROCEDURE [dbo].[calcoloStep124_MF_1]
@IdProgetto int,   
@FASE_ISTRUTTORIA INT =0
AS
BEGIN
 
--    MASSIMALI PER CODIFICA
 
DECLARE @Result int
SET @Result = 1 -- Impongo lo Step verificato
--------------------------------------------------------------------------------------------------------------
DECLARE @QUANTITA DECIMAL(18,2),
					@COSTO_INVESTIMENTO DECIMAL(18,2), @COUNT_UDM INT

--controllo corretta selezione della misura   ID_UNITA_MISURA = 17 -- numero
SET @COUNT_UDM =( SELECT COUNT(*) FROM PIANO_INVESTIMENTI  PI  
					INNER JOIN  DETTAGLIO_INVESTIMENTI D ON PI.ID_DETTAGLIO_INVESTIMENTO = D.ID_DETTAGLIO_INVESTIMENTO
WHERE ID_PROGETTO = @IdProgetto  AND  D.COD_DETTAGLIO IN ('5','6','7','8')  AND  ID_UNITA_MISURA != 17 AND  
	 ((ID_INVESTIMENTO_ORIGINALE  IS NULL  AND  @FASE_ISTRUTTORIA = 0 ) OR  ( ID_INVESTIMENTO_ORIGINALE  IS NOT NULL  AND  @FASE_ISTRUTTORIA = 1 )))

IF( @COUNT_UDM > 0 ) SET  @Result=0
ELSE 
	BEGIN
-------------- MASSIMALE PER INCONTRI ------------------------------
		SELECT  @QUANTITA = SUM(QUANTITA) , @COSTO_INVESTIMENTO=SUM(COSTO_INVESTIMENTO)    
		FROM PIANO_INVESTIMENTI  PI  INNER JOIN  DETTAGLIO_INVESTIMENTI D ON PI.ID_DETTAGLIO_INVESTIMENTO = D.ID_DETTAGLIO_INVESTIMENTO
		WHERE ID_PROGETTO = @IdProgetto  AND  D.COD_DETTAGLIO= '5'  AND   ( ( ID_INVESTIMENTO_ORIGINALE  IS NULL  AND  @FASE_ISTRUTTORIA = 0 ) OR  ( ID_INVESTIMENTO_ORIGINALE  IS NOT NULL  AND  @FASE_ISTRUTTORIA = 1 )  )

		IF( (ISNULL(@QUANTITA,0) *  200 )< ISNULL(@COSTO_INVESTIMENTO,0)   ) SET @Result =0  
		ELSE 
			BEGIN
						----------------Seminari informativi -------------------
			   SELECT  @QUANTITA = SUM(QUANTITA) , @COSTO_INVESTIMENTO=SUM(COSTO_INVESTIMENTO)   FROM PIANO_INVESTIMENTI  PI  INNER JOIN  DETTAGLIO_INVESTIMENTI D ON PI.ID_DETTAGLIO_INVESTIMENTO = D.ID_DETTAGLIO_INVESTIMENTO
				WHERE ID_PROGETTO = @IdProgetto  AND  D.COD_DETTAGLIO = '6'  AND   ( ( ID_INVESTIMENTO_ORIGINALE  IS NULL  AND  @FASE_ISTRUTTORIA = 0 ) OR  ( ID_INVESTIMENTO_ORIGINALE  IS NOT NULL  AND  @FASE_ISTRUTTORIA = 1 )  )

				 IF( (ISNULL(@QUANTITA,0) *  800 )< ISNULL(@COSTO_INVESTIMENTO,0)    ) SET @Result =0  
				ELSE
						BEGIN
							---------------------------- Visite guidate, campi dimostrativi, Open day
							   SELECT  @QUANTITA = SUM(QUANTITA) , @COSTO_INVESTIMENTO=SUM(COSTO_INVESTIMENTO)     FROM PIANO_INVESTIMENTI  PI  INNER JOIN  DETTAGLIO_INVESTIMENTI D ON PI.ID_DETTAGLIO_INVESTIMENTO = D.ID_DETTAGLIO_INVESTIMENTO
								WHERE ID_PROGETTO = @IdProgetto  AND  D.COD_DETTAGLIO = '7'  AND   ( ( ID_INVESTIMENTO_ORIGINALE  IS NULL  AND  @FASE_ISTRUTTORIA = 0 ) OR  ( ID_INVESTIMENTO_ORIGINALE  IS NOT NULL  AND  @FASE_ISTRUTTORIA = 1 )  )

								IF( (ISNULL(@QUANTITA,0) *  1500 )< ISNULL(@COSTO_INVESTIMENTO,0)   ) SET @Result =0  
								ELSE 
									BEGIN
									-------------Pubblicazioni divulgative (bollettini, newsletter, ecc..)
									   SELECT  @QUANTITA = SUM(QUANTITA) , @COSTO_INVESTIMENTO=SUM(COSTO_INVESTIMENTO)   FROM PIANO_INVESTIMENTI  PI 
														 INNER JOIN  DETTAGLIO_INVESTIMENTI D ON PI.ID_DETTAGLIO_INVESTIMENTO = D.ID_DETTAGLIO_INVESTIMENTO
														WHERE ID_PROGETTO = @IdProgetto  AND  D.COD_DETTAGLIO = '8'  AND   ( ( ID_INVESTIMENTO_ORIGINALE  IS NULL  AND  @FASE_ISTRUTTORIA = 0 ) OR  ( ID_INVESTIMENTO_ORIGINALE  IS NOT NULL  AND  @FASE_ISTRUTTORIA = 1 )  )

										IF( (ISNULL(@QUANTITA,0) *  1500 )< ISNULL(@COSTO_INVESTIMENTO,0)   ) SET @Result =0  

									END
						END
		END 
END
SELECT @Result AS RESULT
END
