create  PROCEDURE [dbo].[calcoloPrioritaNumSog]
(
@IdProgetto int
)

AS
BEGIN

DECLARE @N_PRIVATI INT
DECLARE @N_ENTI_LOCALI INT
DECLARE @RESULTP decimal(10,2)
DECLARE @RESULTE decimal(10,2)
DECLARE @RESULT decimal(10,2)

SET @RESULT = 0
SET @N_PRIVATI = (SELECT VALORE FROM PRIORITA_X_PROGETTO WHERE ID_PRIORITA = 502 AND ID_PROGETTO = @IdProgetto)
SET @N_ENTI_LOCALI = (SELECT VALORE FROM PRIORITA_X_PROGETTO WHERE ID_PRIORITA = 503 AND ID_PROGETTO = @IdProgetto)

--Numero Partecipanti Privati
IF (@N_PRIVATI > 9 ) BEGIN
    IF (@N_PRIVATI > 15 ) SET @RESULTP = 0.50
		ELSE
			IF (@N_PRIVATI >= 11 AND @N_PRIVATI <= 15 ) SET @RESULTP = 0.25
				ELSE
					IF (@N_PRIVATI <= 10) SET @RESULTP = 0
END


--Numero Partecipanti Enti Locali
IF (@N_ENTI_LOCALI > 4 ) BEGIN
	IF (@N_ENTI_LOCALI > 10 ) SET @RESULTE = 0.50
		ELSE
			IF (@N_ENTI_LOCALI >= 6 AND @N_ENTI_LOCALI <= 10 ) SET @RESULTE = 0.25
				ELSE
					IF (@N_ENTI_LOCALI < 6 ) SET @RESULTE = 0
END      

--Risultato
SET @RESULT = isnull(@RESULTE,0) + isnull(@RESULTP,0)
SELECT @RESULT

END
