CREATE PROCEDURE [dbo].[calcoloStepVariante112_111_1]
@ID_VARIANTE int

-- 111 - Verifica massimali da intervento su corsi di formazione   

AS
DECLARE @IdProgetto INT
DECLARE @COUNT_CODIFICA int,@COSTO_INVESTIMENTO int 
SET @IdProgetto = (SELECT ID_PROGETTO FROM  VARIANTI WHERE ID_VARIANTE = @ID_VARIANTE )

-- TROVO IL PROGETTO INTEGRATO 
DECLARE @ID_PROG_INTEG_111 INT 
SELECT DISTINCT @ID_PROG_INTEG_111 = p.ID_PROGETTO FROM PROGETTO P
		INNER JOIN BANDO B ON B.ID_BANDO = P.ID_BANDO INNER JOIN ZPROGRAMMAZIONE ZP ON ZP.ID =B.ID_PROGRAMMAZIONE AND CODICE = '1.1.1.A'
WHERE ID_PROG_INTEGRATO = @IdProgetto

SET @COUNT_CODIFICA = (SELECT SUM(QUANTITA) FROM VPIANO_INVESTIMENTI
					WHERE (ID_CODIFICA_INVESTIMENTO = 151 or ID_CODIFICA_INVESTIMENTO=226  or  ID_CODIFICA_INVESTIMENTO=311 OR ID_CODIFICA_INVESTIMENTO= 783   ) AND 
							ID_PROGETTO = @ID_PROG_INTEG_111 AND ID_VARIANTE = @ID_VARIANTE AND  isnull(COD_VARIAZIONE,'x')!='A' 
					GROUP BY QUANTITA)

SET @COSTO_INVESTIMENTO = (SELECT SUM(CONTRIBUTO_RICHIESTO) FROM VPIANO_INVESTIMENTI
								WHERE (ID_CODIFICA_INVESTIMENTO = 151 or ID_CODIFICA_INVESTIMENTO=226 or  ID_CODIFICA_INVESTIMENTO=311 OR ID_CODIFICA_INVESTIMENTO= 783 ) 
								AND ID_PROGETTO = @ID_PROG_INTEG_111  AND ID_VARIANTE = @ID_VARIANTE AND isnull(COD_VARIAZIONE,'x')!='A' )

DECLARE @RISULTATO int

IF(@COUNT_CODIFICA*1500<@COSTO_INVESTIMENTO)SET @RISULTATO = 0
ELSE SET @RISULTATO = 1
 
SELECT @RISULTATO AS RISULTATO
