CREATE PROCEDURE [dbo].[calcoloStep123_15]
(
	@IdProgetto int,
	@FASE_ISTRUTTORIA INT =0
)
AS
BEGIN
 
--DECLARE @IdProgetto int, @FASE_ISTRUTTORIA INT =0 
-- rispetto massimale di contributo per Impresa/periodo di programmazione su domande ammissibili
DECLARE  @result int, @CONTRIBUTO_RICHIESTO DECIMAL(18,2),@ID_IMPRESA INT

SET @RESULT =1 --PONGO LO STEP VERIFICATO

-- CONTRIBUTO RICHIESTO AMMISSIBILE PER LE DOMANDE AMMISSIBILI DELL'IMPRESA (il contriburo va calcolato solo per le domande del PSR e non per i bandi PABS )
SELECT @ID_IMPRESA = ID_IMPRESA FROM PROGETTO WHERE ID_PROGETTO = @IdProgetto 

SELECT @CONTRIBUTO_RICHIESTO = SUM(DBO.calcoloContributoTotaleProgetto (P.ID_PROGETTO, FLAG_DEFINITIVO, VA.ID_VARIANTE ) ) 
FROM vPROGETTO P 
	INNER JOIN BANDO PB_MAX ON PB_MAX.ID_BANDO = P.ID_BANDO 
	INNER JOIN vzPROGRAMMAZIONE PR ON PR.ID= PB_MAX.ID_PROGRAMMAZIONE 
	LEFT JOIN (SELECT MAX(ID_VARIANTE)ID_VARIANTE , ID_PROGETTO FROM VARIANTI WHERE COD_TIPO IN ('VA', 'AR') GROUP BY ID_PROGETTO ) AS V ON V.ID_PROGETTO = P.ID_PROGETTO
	LEFT JOIN VARIANTI VA ON VA.ID_PROGETTO = P.ID_PROGETTO AND VA.ID_VARIANTE = V.ID_VARIANTE 
WHERE P.ID_IMPRESA =@ID_IMPRESA AND  (P.COD_STATO NOT  IN ('P','Q','B','R','E','N') OR (P.ID_PROGETTO = @IdProgetto )) AND pr.COD_PSR like 'PSR%' 
 
 IF(@CONTRIBUTO_RICHIESTO > 3000000) SET @result =0
SELECT @result AS RESULT
END
