CREATE    PROCEDURE [dbo].[calcoloStepVariante112_114_2]
@ID_VARIANTE int
AS
 
-- MAX NUMERO VARIANTE PER MODIFICHE APPORTATE 

 DECLARE @RESULT INT
SET @RESULT =0

DECLARE @ID_PROGETTO INT,  @COUNT_A INT,@COUNT_B INT, @COUNT_V INT,
		@ID_VARIANTE_PASS INT ,@ID_PROGETTO_114_PASS INT, @ID_PROGETTO_PASS INT,
		@COUNT_VARIANTI INT

SET @ID_PROGETTO  = (SELECT ID_PROGETTO FROM VARIANTI WHERE ID_VARIANTE = @ID_VARIANTE)
SET @COUNT_V = ( SELECT COUNT (*) FROM VARIANTI WHERE ID_PROGETTO =@ID_PROGETTO AND APPROVATA = 1 AND ANNULLATA =0  AND COD_TIPO='VA' )
SET @COUNT_VARIANTI= 0
-- CONTROLLO SE HA FATTO UNA VARIANTE PER LA 114 - questa non conta nel conteggio
IF (@COUNT_V >= 2)
		BEGIN
			
		DECLARE @ID_PROG_CORRENTE_114 INT 

		SELECT DISTINCT @ID_PROG_CORRENTE_114 = p.ID_PROGETTO FROM PROGETTO P
		INNER JOIN BANDO B ON B.ID_BANDO = P.ID_BANDO INNER JOIN ZPROGRAMMAZIONE ZP ON ZP.ID =B.ID_PROGRAMMAZIONE AND CODICE = '1.1.4.'
		WHERE ID_PROG_INTEGRATO = @ID_PROGETTO
			
			DECLARE VARIANTI CURSOR  FOR 
			( SELECT ID_VARIANTE, ID_PROGETTO 
				FROM VARIANTI WHERE ID_VARIANTE = @ID_VARIANTE OR  (ID_PROGETTO =@ID_PROGETTO AND APPROVATA = 1 AND ANNULLATA =0)  AND COD_TIPO='VA' )

				OPEN VARIANTI
				FETCH NEXT FROM VARIANTI 
				INTO  @ID_VARIANTE_PASS, @ID_PROGETTO_PASS
				WHILE @@FETCH_STATUS = 0
				BEGIN
					--VEDO SE VARIANTE PASSATA ERA STATA FATTA PER LA 114
					 SET @COUNT_A = ( SELECT COUNT (*) FROM PIANO_INVESTIMENTI PI WHERE COD_VARIAZIONE IS NOT NULL AND ID_VARIANTE = @ID_VARIANTE_PASS )
                     SET @COUNT_B= (SELECT COUNT (*) FROM PIANO_INVESTIMENTI PI WHERE COD_VARIAZIONE IS NOT NULL AND ID_VARIANTE = @ID_VARIANTE_PASS AND ID_PROGETTO = @ID_PROG_CORRENTE_114 )
						IF (ISNULL(@COUNT_A,0) ! = ISNULL(@COUNT_B,0)) SET  @COUNT_VARIANTI= @COUNT_VARIANTI+ 1

				FETCH NEXT FROM VARIANTI
				INTO  @ID_VARIANTE_PASS, @ID_PROGETTO_PASS
				END

CLOSE VARIANTI
DEALLOCATE VARIANTI 
				
END

 

IF (@COUNT_VARIANTI>  2) SET @RESULT =0
 ELSE   SET @RESULT =1

SELECT @RESULT AS RESULT
