CREATE  PROCEDURE [dbo].[calcoloStep112_111_3]
@IdProgetto int

-- 111 - Verifica massimali da intervento su corsi di formazione  
 
AS
-- TROVO IL PROGETTO INTEGRATO
-- FATTO!!! 
DECLARE @ID_PROG_INTEG_111 int, @Result INT  

SELECT DISTINCT @ID_PROG_INTEG_111 = p.ID_PROGETTO FROM PROGETTO P
INNER JOIN BANDO B ON B.ID_BANDO = P.ID_BANDO INNER JOIN ZPROGRAMMAZIONE ZP ON ZP.ID =B.ID_PROGRAMMAZIONE AND CODICE = '1.1.1.A'
WHERE ID_PROG_INTEGRATO = @IdProgetto 

SET @Result = 0-- NON VERIFICATO 


SET @Result = (SELECT  COUNT(*) AS C FROM  PIANO_INVESTIMENTi I
					INNER JOIN VPRIORITA_X_INVESTIMENTI PXI ON I.ID_INVESTIMENTO = PXI.ID_INVESTIMENTO AND PXI.ID_PRIORITA in (384 ,1179)
				WHERE ID_PROGETTO = @ID_PROG_INTEG_111 
				GROUP BY PXI.DESCRIZIONE 
				HAVING SUM(CONTRIBUTO_RICHIESTO) > 1500)

 SELECT isnull(@Result,0) AS RESULT
