--SALDO 123b 
CREATE  PROCEDURE [dbo].[calcoloStepPagamento123_8]
@IdProgetto int,
@IdDomandaPagamento int =NULL
AS
BEGIN
 
DECLARE @RESULT INT = 1

	SELECT @RESULT=COUNT(*) 
	FROM PAGAMENTI_RICHIESTI pr 
		INNER JOIN PIANO_INVESTIMENTI inv on inv.ID_INVESTIMENTO= pr.ID_INVESTIMENTO 
		INNER JOIN vzPROGRAMMAZIONE PP ON PP.ID = INV.ID_PROGRAMMAZIONE 
	WHERE ID_DOMANDA_PAGAMENTO =@IdDomandaPagamento AND PP.CODICE LIKE '%1.2.3.a.b%'
	 
	SELECT @RESULT
END
