CREATE  PROCEDURE [dbo].[calcoloStepVariante123_9]
@ID_VARIANTE int
AS
BEGIN

--  123 - Totale inivestimenti per interventi legati alla    commercializzazione > = 10.000,00 €
--  aggiunto requitio a livello investimento

--DECLARE @ID_VARIANTE INT = 3082
DECLARE @ID_BANDO INT 
DECLARE @Count int, @COSTO_TRASFORMAZIONE DECIMAL (20,2), @COSTO_COMM DECIMAL (20,2),@RESULT INT, @COSTO DECIMAL (20,2)
SET @RESULT =0  --- NON VERIFICATO


SELECT @ID_BANDO = ID_BANDO FROM PROGETTO P WHERE ID_PROGETTO = (SELECT ID_PROGETTO FROM VARIANTI WHERE ID_VARIANTE =@ID_VARIANTE )
-- 
 IF (@ID_BANDO IN (300,270))BEGIN 
 
		DECLARE @C_PRIO INT
		SELECT @C_PRIO= COUNT(*) FROM PIANO_INVESTIMENTI INV LEFT JOIN PRIORITA_X_INVESTIMENTI PXI ON INV.ID_INVESTIMENTO = PXI.ID_INVESTIMENTO AND ID_PRIORITA = 1230
		WHERE INV.ID_VARIANTE = @ID_VARIANTE AND  isnull(COD_VARIAZIONE,'x')!='A' AND INV.COD_TIPO_INVESTIMENTO = 1 AND PXI.ID_INVESTIMENTO IS NULL
  
		IF (ISNULL(@C_PRIO,0) > 0) SET @RESULT =0
		ELSE BEGIN 
			-- CONTROLLO CHE IL PROGETTO SIA SOLO COMMERCIALIZZAZIONE
			SELECT @COSTO_TRASFORMAZIONE= SUM(COSTO_INVESTIMENTO) FROM PIANO_INVESTIMENTI INV 
				INNER JOIN PRIORITA_X_INVESTIMENTI PXI ON INV.ID_INVESTIMENTO = PXI.ID_INVESTIMENTO AND ID_PRIORITA = 1230
				INNER JOIN VALORI_PRIORITA VP ON VP.ID_PRIORITA = PXI.ID_PRIORITA AND VP.ID_VALORE = PXI.ID_VALORE 
			WHERE INV.ID_VARIANTE = @ID_VARIANTE AND  isnull(COD_VARIAZIONE,'x')!='A' AND INV.COD_TIPO_INVESTIMENTO = 1  AND VP.CODICE IN ('T','X') 
		 
			SELECT @COSTO_COMM= SUM(COSTO_INVESTIMENTO) FROM PIANO_INVESTIMENTI INV 
				INNER JOIN PRIORITA_X_INVESTIMENTI PXI ON INV.ID_INVESTIMENTO = PXI.ID_INVESTIMENTO AND ID_PRIORITA = 1230
				INNER JOIN VALORI_PRIORITA VP ON VP.ID_PRIORITA = PXI.ID_PRIORITA AND VP.ID_VALORE = PXI.ID_VALORE 
			WHERE INV.ID_VARIANTE = @ID_VARIANTE AND  isnull(COD_VARIAZIONE,'x')!='A' AND INV.COD_TIPO_INVESTIMENTO = 1  AND VP.CODICE IN ('C') 
			
			IF(ISNULL(@COSTO_TRASFORMAZIONE,0)>0)	SET @RESULT=1
			ELSE BEGIN  IF(  @COSTO_COMM > 10000)SET @RESULT=1
						ELSE SET @RESULT=0
				END
				  
		END
		 

END
ELSE BEGIN 
	SET @Count = (SELECT COUNT(ID_INVESTIMENTO)
				  FROM PROGETTO P INNER JOIN VPIANO_INVESTIMENTI I ON (P.ID_PROGETTO=I.ID_PROGETTO) 
				  WHERE ID_VARIANTE= @ID_VARIANTE AND ISNULL(COD_VARIAZIONE,'x')!='A'  AND (CODICE   IN ('64','65')))

	--SELECT @Count 
	IF (ISNULL(@Count,0) > 0) 
	BEGIN 
		SET @COSTO=(SELECT ISNULL( SUM (COSTO_INVESTIMENTO + SPESE_GENERALI) , 0) AS Totale_Investimenti  
					FROM PROGETTO P INNER JOIN  vPIANO_INVESTIMENTI I ON (P.ID_PROGETTO=I.ID_PROGETTO)
					WHERE ID_VARIANTE= @ID_VARIANTE AND ISNULL(COD_VARIAZIONE,'x')!='A' AND CODICE IN ('64','65','66','67'))
		
		IF(@COSTO > 10000)SET @RESULT=1
	END
	 ELSE SET @RESULT =1
END
SELECT @RESULT AS RESULT
END
