CREATE  PROCEDURE [dbo].[calcoloStepPagamento133_2]
@IdProgetto int,
@IdDomandaPagamento int =NULL
AS
 BEGIN
--	E` possibile presentare domanda di SAL (spesa rendicontata >= 50% di quella autorizzata per il progetto annuale)
--  Requisiti pagamento esito positivo =1 
-- anno =228

--DECLARE 
--@IdProgetto int,
--@IdDomandaPagamento int  
--SET @IdProgetto  =4543
--SET @IdDomandaPagamento=1224

DECLARE  @ANNO VARCHAR(4), @DATA_MODIFICA DATETIME,@ID_VARIANTE INT
DECLARE @RESULT INT

DECLARE @DATA_MODIFICA_PAGAMENTO DATETIME,@ID_INVESTIMENTO INT,
		@IMPORTO_RENDICONTATO_ATTUALE DECIMAL(18,2),
		@CONTRIBUTO_RENDICONTATO_ATTUALE DECIMAL(18,2),@ID_FASCICOLO INT

--TROVO PROGETTO E ULTIMA VARIANTE RELATIVA A QUESTA DOMANDA DI PAGAMENTO
SELECT @DATA_MODIFICA_PAGAMENTO=DATA_MODIFICA,@IdProgetto=D.ID_PROGETTO,@ID_FASCICOLO=ID_FASCICOLO,@ID_VARIANTE=ID_VARIAZIONE_ACCERTATA  FROM DOMANDA_DI_PAGAMENTO D
	INNER JOIN PROGETTO P ON D.ID_PROGETTO=P.ID_PROGETTO WHERE ID_DOMANDA_PAGAMENTO=@IdDomandaPagamento
IF(@ID_VARIANTE IS NULL)
SELECT @ID_VARIANTE=MAX(ID_VARIANTE) FROM VARIANTI WHERE ID_PROGETTO=@IdProgetto AND APPROVATA=1 AND ANNULLATA=0 
	AND DATA_MODIFICA<@DATA_MODIFICA_PAGAMENTO

--CREO PIANO INVESTIMENTI VIRTUALE
DECLARE @INVESTIMENTI_VIRTUALE TABLE ([ID_INVESTIMENTO] [int] NOT NULL,
	[ID_PROGETTO] [int] NULL,
	[ID_CODIFICA_INVESTIMENTO] [int] NULL,
	[ID_DETTAGLIO_INVESTIMENTO] [int] NULL,
	IMPORTO_TOTALE_RENDICONTATO DECIMAL(18,2),
	CONTRIBUTO_TOTALE_RENDICONTATO DECIMAL(18,2))	

INSERT INTO @INVESTIMENTI_VIRTUALE
SELECT I.ID_INVESTIMENTO, I.ID_PROGETTO, I.ID_CODIFICA_INVESTIMENTO,I.ID_DETTAGLIO_INVESTIMENTO,Dbo.calcoloTotaleImportoRendicontatoAmmessoInvestimento (I.ID_INVESTIMENTO,@IdDomandaPagamento) AS IMPORTO_TOTALE_RENDICONTATO,
	dbo.calcoloTotaleContributoRendicontatoInvestimento(I.ID_INVESTIMENTO,@IdDomandaPagamento) AS CONTRIBUTO_TOTALE_RENDICONTATO 
FROM PROGETTO P INNER JOIN PIANO_INVESTIMENTI I ON P.ID_PROGETTO=I.ID_PROGETTO
WHERE ISNULL(P.ID_PROG_INTEGRATO,P.ID_PROGETTO)=@IdProgetto AND
	((@ID_VARIANTE IS NULL AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL) OR
	(ID_VARIANTE=@ID_VARIANTE AND ISNULL(COD_VARIAZIONE,'X')!='A')) ORDER BY COD_TIPO_INVESTIMENTO

SET @RESULT = 1 -- IMPONGO LO STEP  VERIFICATO
-- CONTROLLO PER OGNI ANNO RENDICONTATO
 SELECT @RESULT= COUNT(*) 
 FROM (SELECT ((SUM(ISNULL(SPESE_GENERALI,0)) *100 )/SUM(ISNULL( SPESE_TOTALI,1)))AS C 
		FROM (SELECT PXI.DESCRIZIONE, 
				  'SPESE_TOTALI' = CASE WHEN CO.CODICE IN ('1','2','3') THEN  SUM(IMPORTO_TOTALE_RENDICONTATO)  END, 
				  'SPESE_GENERALI' = CASE WHEN CO.CODICE IN ('4') THEN SUM(IMPORTO_TOTALE_RENDICONTATO)END  
				FROM @INVESTIMENTI_VIRTUALE AS PI INNER JOIN 
					VPRIORITA_X_INVESTIMENTI PXI ON PI.ID_INVESTIMENTO = PXI.ID_INVESTIMENTO AND ID_PRIORITA  in ( 228,1130,1237) inner join 
					CODIFICA_INVESTIMENTO CO ON CO.ID_CODIFICA_INVESTIMENTO= PI.ID_CODIFICA_INVESTIMENTO
				WHERE  ID_PROGETTO= @IdProgetto GROUP BY PXI.DESCRIZIONE, CODICE ) AS T  
GROUP BY DESCRIZIONE  
HAVING  ( (SUM(ISNULL( SPESE_GENERALI,0)) *100 ) / SUM(ISNULL( SPESE_TOTALI,1))) >15 ) AS C

SELECT @RESULT
END
