CREATE  PROCEDURE [dbo].[calcoloStepPagamento112_5_XXX]
@IdProgetto int,
@IdDomandaPagamento int =NULL
AS
BEGIN

--DECLARE @IdProgetto int, @ID_DOMANDA_PAGAMENTO int
--SET @ID_DOMANDA_PAGAMENTO =2128
--set @IdProgetto =511

DECLARE @RESULT INT ,@IMPORTOAMMESSO DECIMAL(18,2), 
		@IMPORTO_TOTALE DECIMAL(18,2), @IMPORTOAMMESSO_SALDO DECIMAL(18,2)
SET @RESULT= 1

SELECT @IMPORTOAMMESSO_SALDO= SUM(IMPORTO) 
FROM (
	SELECT  ISNULL( IMPORTO_COMPUTO_METRICO_AMMESSO , SUM(spesa_tecnica)+  sum( importoAmmesso )) as IMPORTO
	FROM (
			SELECT pr.ID_INVESTIMENTO , pr.IMPORTO_COMPUTO_METRICO_AMMESSO, 
					CASE WHEN pb.SPESA_TECNICA_AMMESSA =1 then sum( pb.IMPORTO_AMMESSO) end as spesa_tecnica,
					case WHEN pb.SPESA_TECNICA_AMMESSA =0 then sum(pb.IMPORTO_AMMESSO ) end as importoAmmesso
			FROM PAGAMENTI_RICHIESTI PR
				 inner join PAGAMENTI_BENEFICIARIO pb on pb .ID_PAGAMENTO_RICHIESTO= pr.ID_PAGAMENTO_RICHIESTO  
			WHERE AMMESSO = 1 AND ID_DOMANDA_PAGAMENTO in (select ID_DOMANDA_PAGAMENTO from DOMANDA_DI_PAGAMENTO where ID_PROGETTO =@IdProgetto and isnull(APPROVATA,2) != 0  and COD_TIPO ='SLD') 
			GROUP BY pr.ID_PAGAMENTO_RICHIESTO , IMPORTO_COMPUTO_METRICO_AMMESSO, pb.SPESA_TECNICA_AMMESSA, pr.ID_INVESTIMENTO
	) as totale
group by IMPORTO_COMPUTO_METRICO_AMMESSO 
)as import_ammesso

SELECT @IMPORTOAMMESSO =  SUM(IMPORTO_AMMESSO) FROM PAGAMENTI_RICHIESTI 
WHERE AMMESSO = 1 AND ID_DOMANDA_PAGAMENTO in (select ID_DOMANDA_PAGAMENTO from DOMANDA_DI_PAGAMENTO where ID_PROGETTO =@IdProgetto and isnull(APPROVATA,2) != 0  and COD_TIPO ='SAL') 

SELECT  @IMPORTO_TOTALE = dbo.calcoloCostoTotaleProgetto( @IdProgetto, 1 , NULL)
IF(	(ISNULL(@IMPORTOAMMESSO,0) + ISNULL(@IMPORTOAMMESSO_SALDO,0) )< (ISNULL(@IMPORTO_TOTALE,0) * 0.50 ))SET @RESULT= 0
SELECT @RESULT			 
 
END
