CREATE  PROCEDURE [dbo].[calcoloStep123_7]
@IdProgetto int, 
@FASE_ISTRUTTORIA INT = 0
AS
BEGIN

--  123 - Totale inivestimenti per interventi legati alla trasformazione e commercializzazione > = 100.000,00 €
-- IMPORTO MODIFICATO DICEMBRE 2010


DECLARE @Count int, 
					@COSTO DECIMAL (20,2),
					@RESULT INT
SET @RESULT =0  --- NON VERIFICATO

SET @Count = (SELECT COUNT(ID_INVESTIMENTO)
		      FROM PROGETTO P INNER JOIN VPIANO_INVESTIMENTI I ON (P.ID_PROGETTO=I.ID_PROGETTO) 
		      WHERE ( (I.ID_INVESTIMENTO_ORIGINALE IS NULL  AND @FASE_ISTRUTTORIA =0  AND ID_VARIANTE IS NULL  ) 
							OR (@FASE_ISTRUTTORIA =  1 AND   I.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL  )  ) 
						AND I.COD_TIPO_INVESTIMENTO = 1 
			  AND (P.ID_PROGETTO=@IdProgetto ) AND  (CODICE IN ( '66','67') )   )
 
--SELECT @Count 
IF (ISNULL(@Count,0) > 0) 
BEGIN 
	SET @COSTO  = ( SELECT ISNULL( SUM (COSTO_INVESTIMENTO + SPESE_GENERALI) , 0) AS Totale_Investimenti  
										FROM PROGETTO P INNER JOIN  vPIANO_INVESTIMENTI I ON (P.ID_PROGETTO=I.ID_PROGETTO)
										WHERE   ( (I.ID_INVESTIMENTO_ORIGINALE IS NULL  AND @FASE_ISTRUTTORIA =0  AND ID_VARIANTE IS NULL  ) 
										OR (@FASE_ISTRUTTORIA =  1 AND  I.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL  )  )  
										AND I.COD_TIPO_INVESTIMENTO = 1 AND (P.ID_PROGETTO=@IdProgetto ) 
										AND  CODICE IN ('64','65','66','67')   )
			IF( @COSTO > 100000 )  SET @RESULT=1
END
 ELSE SET @RESULT =1

SELECT @RESULT AS RESULT



	
END
