CREATE PROCEDURE [dbo].[calcoloPrioritaRequisitoPagamento121_3]
@ID_DOMANDA_PAGAMENTO INT , 
@ID_PROG_CORRENTE INT -- @ID_PROG_CORRENTE PER LA 121 è L'ID PROGETTO PER IL MULTIMISURA è L'ID PROGETTO INTEGRATO
AS
BEGIN

-- 121 - Investimenti relativi a tipologie indicate come prioritarie dal PSR per i settori produttivi di cui al cap.5
 -- ID_PRIORITA= 22

DECLARE @Investimenti decimal(10,2)
DECLARE @TotaleInvestimenti decimal(10,2)


SET @Investimenti =  (SELECT SUM ( ISNULL(PB.IMPORTO_AMMESSO,PB.IMPORTO_RICHIESTO) )  FROM 
					  PAGAMENTI_BENEFICIARIO PB 
					  INNER JOIN PAGAMENTI_RICHIESTI PR ON PB.ID_PAGAMENTO_RICHIESTO= PR.ID_PAGAMENTO_RICHIESTO
					  INNER JOIN PIANO_INVESTIMENTI PI ON PI.ID_INVESTIMENTO = PR.ID_INVESTIMENTO
					WHERE  PI.ID_PRIORITA_SETTORIALE IS NOT NULL   AND COD_TIPO_INVESTIMENTO =1 
						AND ( ID_DOMANDA_PAGAMENTO IN 
							( SELECT ID_DOMANDA_PAGAMENTO FROM DOMANDA_DI_PAGAMENTO 
							 WHERE (APPROVATA =1 AND ID_PROGETTO= @ID_PROG_CORRENTE  AND ANNULLATA = 0
						)OR ID_DOMANDA_PAGAMENTO =@ID_DOMANDA_PAGAMENTO)) ) 

SET @TotaleInvestimenti =  (SELECT SUM ( ISNULL(PB.IMPORTO_AMMESSO,PB.IMPORTO_RICHIESTO) )  FROM 
							PAGAMENTI_BENEFICIARIO PB 
							INNER JOIN PAGAMENTI_RICHIESTI PR ON PB.ID_PAGAMENTO_RICHIESTO= PR.ID_PAGAMENTO_RICHIESTO
							WHERE ( ID_DOMANDA_PAGAMENTO IN 
								( SELECT ID_DOMANDA_PAGAMENTO FROM DOMANDA_DI_PAGAMENTO 
								 WHERE (APPROVATA =1 AND ID_PROGETTO= @ID_PROG_CORRENTE  AND ANNULLATA = 0
							)OR ID_DOMANDA_PAGAMENTO =@ID_DOMANDA_PAGAMENTO)) )


DECLARE @Punteggio decimal(10,2)

IF(@TotaleInvestimenti = 0 )SET @Punteggio = 0
ELSE IF (@Investimenti >= (@TotaleInvestimenti * 0.7)) SET @Punteggio = 1 

ELSE IF (@Investimenti >= (@TotaleInvestimenti * 0.4) AND
         @Investimenti < (@TotaleInvestimenti * 0.7)) SET @Punteggio = 0.8

ELSE IF (@Investimenti >= (@TotaleInvestimenti * 0.2) AND
         @Investimenti < (@TotaleInvestimenti * 0.4)) SET @Punteggio = 0.4

ELSE SET @Punteggio = 0

SELECT @Punteggio AS PUNTEGGIO	
RETURN (@Punteggio * 100)

END
