CREATE PROCEDURE [dbo].[calcoloStep121_18]
@IdProgetto int
AS
BEGIN

-- 121 - bloccare bilancio
--declare @IdProgetto int = 11127 
 

DECLARE @Result int, @TOT_IMPIEGHI decimal(10,2),@TOT_FONTI_FINANZIAMENTO decimal(10,2),  
	    @REDDITO_OPERATIVO decimal(10,2), @REDDITO_NETTO_PAC decimal(10,2),
		@anno char(4), @ID_IMPRESA INT, @ID_BANDO INT

SET @Result = 1 -- Impongo lo Step VERIFICATO
select @ID_BANDO = ID_BANDO from PROGETTO where ID_PROGETTO =@idProgetto 

IF(SELECT COUNT (*) FROM PRIORITA_X_PROGETTO WHERE ID_PROGETTO=@IdProgetto AND ID_PRIORITA = 151 ) =0
BEGIN
	SELECT  @ID_IMPRESA = ID_IMPRESA FROM  PROGETTO WHERE PROGETTO.ID_PROGETTO =@IdProgetto  

IF (@ID_BANDO in( 370, 385)) SET @anno = 2012 -- BANDO LIGHT DELLA 121 
ELSE BEGIN
	SELECT @anno = YEAR(DATA), @ID_BANDO = ID_BANDO FROM PROGETTO P INNER JOIN  PROGETTO_STORICO S ON  P.ID_PROGETTO = S.ID_PROGETTO 
	WHERE P.ID_PROGETTO = @IdProgetto AND COD_STATO IN ('P','L') ORDER BY S.ID DESC 
	SET @anno = @anno-1 
END


IF((SELECT COUNT(*) from BILANCIO_AGRICOLO WHERE ID_IMPRESA = @ID_IMPRESA AND PREVISIONALE=0 AND  ANNO =@anno ) >0)
 begin 
 SET @Result = 1
 end
	ELSE SET @Result = 0
END
SELECT @Result AS RESULT
END
