CREATE   PROCEDURE [dbo].[calcoloStep133_4]
(
@IdProgetto int,
@FASE_ISTRUTTORIA INT =0
)
AS
BEGIN
--  CORRETTA % DELLE SPESE GENERALI

--declare @IdProgetto int,
-- @FASE_ISTRUTTORIA INT  
--
--set @IdProgetto=7343
--set @FASE_ISTRUTTORIA=0

DECLARE @COSTO_INIZIATIVA DECIMAL(18,2),  
		@NUM_INIZIATIVA INT, @SPESE_GENERALI DECIMAL(18,2), 
		@SOGGETTO INT,@RESULT INT 
SET @RESULT =1 --PONGO LO STEP  VERIFICATO

DECLARE COST_INIZ CURSOR FOR
(SELECT SUM(ISNULL(SPESE_TOTALI,1)) AS COSTO_TOTALE,SUM(ISNULL( SP_GENERALI,0)) AS SP_GENERALI,VALORE
 FROM (SELECT PXI.VALORE, 
			  'SPESE_TOTALI'=CASE WHEN I.CODICE NOT IN ('4','8','12','16','20') THEN SUM(COSTO_INVESTIMENTO) END,
			  'SP_GENERALI' =CASE WHEN I.CODICE IN ('4','8','12','16','20') THEN SUM(COSTO_INVESTIMENTO) END   
		FROM VPIANO_INVESTIMENTI AS I 
			 INNER JOIN  PRIORITA_X_INVESTIMENTI PXI ON I.ID_INVESTIMENTO = PXI.ID_INVESTIMENTO AND ID_PRIORITA IN( 399,858)     
		WHERE ID_PROGETTO =@IdProgetto AND ((@FASE_ISTRUTTORIA =0 and ID_INVESTIMENTO_ORIGINALE  is null and id_variante is null )
			  OR(@FASE_ISTRUTTORIA =1 and ID_INVESTIMENTO_ORIGINALE  is not null and id_variante is null))   
		GROUP BY  PXI.VALORE, CODICE) AS T
 GROUP BY VALORE )

OPEN COST_INIZ
FETCH NEXT FROM COST_INIZ 
INTO @COSTO_INIZIATIVA , @SPESE_GENERALI, @NUM_INIZIATIVA
WHILE @@FETCH_STATUS = 0
BEGIN
 SET @SOGGETTO=(SELECT TOP(1) ID_VALORE 
				FROM (SELECT PXI.ID_INVESTIMENTO 
					  FROM PIANO_INVESTIMENTI AS I 
					       INNER JOIN PRIORITA_X_INVESTIMENTI AS PXI ON I.ID_INVESTIMENTO = PXI.ID_INVESTIMENTO AND PXI.ID_PRIORITA IN( 399,858) AND VALORE = @NUM_INIZIATIVA
					  WHERE ID_PROGETTO =@IdProgetto AND ((@FASE_ISTRUTTORIA =0 and ID_INVESTIMENTO_ORIGINALE  is null and id_variante is null ) or (@FASE_ISTRUTTORIA =1 and ID_INVESTIMENTO_ORIGINALE  is not null and id_variante is null ))) AS INIZ  
				INNER JOIN PRIORITA_X_INVESTIMENTI AS PXI_SOGG ON INIZ.ID_INVESTIMENTO = PXI_SOGG.ID_INVESTIMENTO AND PXI_SOGG.ID_PRIORITA = 398 )

IF (@COSTO_INIZIATIVA > 0)
IF(@SOGGETTO= 571 )	BEGIN  -- SOGGETTO ESTERNO
	IF(((ISNULL(@SPESE_GENERALI,0) *100)/ISNULL(@COSTO_INIZIATIVA,0))>1)SET @RESULT =0 END
ELSE BEGIN
	IF(@SOGGETTO= 572 ) -- SOGGETTO IN PROPRIO
		 IF(((ISNULL(@SPESE_GENERALI ,0) *100)/ ISNULL(@COSTO_INIZIATIVA,0))> 3) SET @RESULT =0 
	END
FETCH NEXT FROM COST_INIZ
INTO @COSTO_INIZIATIVA,@SPESE_GENERALI,  @NUM_INIZIATIVA
END

CLOSE COST_INIZ
DEALLOCATE COST_INIZ 
SELECT @RESULT AS RESULT
END
