CREATE PROCEDURE [dbo].[calcoloStepPagamento311_B_8]
@IdProgetto int,
@IdDomandaPagamento int
AS
BEGIN

-- verifica sostenibilità investimento:
-- rata annua reintegrazione < 40%  @RICAVO_LORDO
-- IL RICAVO LORDO LO PRENDO DALLA DOMANDA DI PAGAMENTO ID REQUISITO = 509

DECLARE @result int,
		@RICAVO_LORDO decimal(18,2), @ID_VARIANTE INT,@IMPORTO_LORDO DECIMAL(18,2),
		@ID_BANDO INT ,@DATA_MODIFICA_PAGAMENTO DATETIME

select @ID_BANDO = ID_BANDO FROM PROGETTO WHERE ID_PROGETTO = @IdProgetto 

--TROVO PROGETTO E ULTIMA VARIANTE RELATIVA A QUESTA DOMANDA DI PAGAMENTO
SELECT @DATA_MODIFICA_PAGAMENTO=DATA_MODIFICA  FROM DOMANDA_DI_PAGAMENTO D
	INNER JOIN PROGETTO P ON D.ID_PROGETTO=P.ID_PROGETTO WHERE ID_DOMANDA_PAGAMENTO=@IdDomandaPagamento
SELECT @ID_VARIANTE=MAX(ID_VARIANTE) FROM VARIANTI WHERE ID_PROGETTO=@IdProgetto AND APPROVATA=1 AND ANNULLATA=0 
	AND DATA_MODIFICA<@DATA_MODIFICA_PAGAMENTO

--CREO PIANO INVESTIMENTI VIRTUALE
DECLARE @INVESTIMENTI_TEMP TABLE ([ID_INVESTIMENTO] [int] NOT NULL,
	[ID_PROGETTO] [int] NULL,
	[ID_PROGRAMMAZIONE] [int] NULL,
	[DESCRIZIONE] [varchar](2000) NULL,
	[DATA_VARIAZIONE] [datetime] NULL,
	[OPERATORE_VARIAZIONE] [varchar](16) NULL,
	[COD_TIPO_INVESTIMENTO] [int] NULL,
	[COD_STP] [char](2) NULL,
	[ID_UNITA_MISURA] [int] NULL,
	[QUANTITA] [decimal](10, 2) NULL,
	[COSTO_INVESTIMENTO] [decimal](15, 2) NULL,
	[SPESE_GENERALI] [decimal](15, 2) NULL,
	[CONTRIBUTO_RICHIESTO] [decimal](15, 2) NULL,
	[QUOTA_CONTRIBUTO_RICHIESTO] [decimal](10, 2) NULL,
	[TASSO_ABBUONO] [decimal](10, 2) NULL,
	[ID_SETTORE_PRODUTTIVO] [int] NULL,
	[ID_PRIORITA_SETTORIALE] [int] NULL,
	[ID_OBIETTIVO_MISURA] [int] NULL,
	[ID_CODIFICA_INVESTIMENTO] [int] NULL,
	[ID_DETTAGLIO_INVESTIMENTO] [int] NULL,
	[ID_SPECIFICA_INVESTIMENTO] [int] NULL,
	[AMMESSO] [bit] NULL,
	[ISTRUTTORE] [varchar](16) NULL,
	[ID_INVESTIMENTO_ORIGINALE] [int] NULL,
	[DATA_VALUTAZIONE] [datetime] NULL,
	[VALUTAZIONE_INVESTIMENTO] [ntext] NULL,
	[ID_VARIANTE] [int] NULL,
	[COD_VARIAZIONE] [char](1),
	[NON_COFINANZIATO] [bit] NULL,
	IMPORTO_TOTALE_RENDICONTATO DECIMAL(18,2),
	CONTRIBUTO_TOTALE_RENDICONTATO DECIMAL(18,2))	
	
INSERT INTO @INVESTIMENTI_TEMP
SELECT I.*,	dbo.calcoloTotaleImportoRendicontatoInvestimento(I.ID_INVESTIMENTO,@IdDomandaPagamento) AS IMPORTO_TOTALE_RENDICONTATO,
	dbo.calcoloTotaleContributoRendicontatoInvestimento(I.ID_INVESTIMENTO,@IdDomandaPagamento) AS CONTRIBUTO_TOTALE_RENDICONTATO 
FROM PROGETTO P INNER JOIN PIANO_INVESTIMENTI I ON P.ID_PROGETTO=I.ID_PROGETTO
WHERE ISNULL(P.ID_PROG_INTEGRATO,P.ID_PROGETTO)=@IdProgetto  AND
	((@ID_VARIANTE IS NULL AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND AMMESSO=1 AND ID_VARIANTE IS NULL) OR
	(ID_VARIANTE=@ID_VARIANTE AND ISNULL(COD_VARIAZIONE,'X')!='A')) ORDER BY COD_TIPO_INVESTIMENTO

 
/**********************************************************************************************************/
--INIZIO CONTROLLO STEP

-- Verifica sostenibilità investimento: rata annua reintegrazione < 40% DEL REQUISITO DI PAGAMENTO

DECLARE @RATA_INTEGRAZIONE DECIMAL(10,2),@PLV DECIMAL(10,2)
SELECT @RATA_INTEGRAZIONE=SUM(CASE D.MOBILE WHEN 1 THEN IMPORTO_TOTALE_RENDICONTATO/10 ELSE IMPORTO_TOTALE_RENDICONTATO/30 END)
	FROM @INVESTIMENTI_TEMP I LEFT JOIN DETTAGLIO_INVESTIMENTI D ON I.ID_DETTAGLIO_INVESTIMENTO=D.ID_DETTAGLIO_INVESTIMENTO
	WHERE COD_TIPO_INVESTIMENTO=1
 

SELECT @IMPORTO_LORDO = R.VAL_NUMERICO FROM DOMANDA_PAGAMENTO_REQUISITI R WHERE ID_REQUISITO = 509 AND ID_DOMANDA_PAGAMENTO = @IdDomandaPagamento
SELECT @RICAVO_LORDO = ISNULL( VALORE,0) FROM  PRIORITA_X_PROGETTO WHERE ID_PROGETTO = @IdProgetto AND ID_PRIORITA  = 197 

IF(@ID_BANDO in ( 382,115,430 , 128) ) BEGIN 
	IF (@RATA_INTEGRAZIONE <= (@IMPORTO_LORDO * 0.4)) SET @result = 1
	ELSE SET @result = 0
END 
ELSE BEGIN 
	IF (@RATA_INTEGRAZIONE <= (@RICAVO_LORDO * 0.4)) SET @result = 1
	ELSE SET @result = 0
END
SELECT @result AS RESULT

END
