CREATE  PROCEDURE [dbo].[calcoloStepPagamento311_2]
@IdProgetto int,
@IdDomandaPagamento int =NULL
AS
BEGIN
 -- DATA INIZIO LAVORI 
 
DECLARE  @COUNT INT,	
					@RESULT INT,
					@ID_BANDO INT,
					@DATE_FIN AS DATETIME

SET @DATE_FIN =  (SELECT  VAL_DATA FROM  DOMANDA_PAGAMENTO_REQUISITI WHERE ID_DOMANDA_PAGAMENTO = @IdDomandaPagamento  AND ID_REQUISITO =2)
SET @ID_BANDO = (SELECT ID_BANDO FROM PROGETTO WHERE ID_PROGETTO = @IdProgetto )
SET @RESULT =(SELECT 'DIFF'= CASE 
								WHEN   DATEDIFF(DAY, DATEADD(MM,6,@DATE_FIN ) , 
																	(SELECT  VAL_DATA FROM DOMANDA_PAGAMENTO_REQUISITI WHERE ID_DOMANDA_PAGAMENTO = @IdDomandaPagamento  AND ID_REQUISITO =1) ) <=0 THEN 1 	
								ELSE  0 END)

 SELECT @RESULT
END
