CREATE PROCEDURE [dbo].[calcoloStep125_2]
@IdProgetto int,
@FASE_ISTRUTTORIA INT
AS
BEGIN
 
-- Rispetto percentuale massima di Spese Tecniche ammessa da bando nel caso di progettazione interna
-- 1164	Progettazione interna
-- 1165	Direzione lavori interna
 
DECLARE @RESULT int, @COSTO_INVESTIMENTO DECIMAL (10,2)

SET @RESULT = 1 -- Impongo lo Step verificato
--------------------------------------------------------------------------------------------------------------
DECLARE @COSTO_PROG DECIMAL(18,2)=0,@COSTO_DIREZIONE DECIMAL (18,2)=0
		,@C_P INT =0, @C_D INT=0

SELECT @COSTO_INVESTIMENTO = SUM(COSTO_INVESTIMENTO) FROM vPIANO_INVESTIMENTI 
WHERE ID_PROGETTO = @IdProgetto AND CODICE IN ('2','3') AND 
		((@FASE_ISTRUTTORIA=0 AND ID_INVESTIMENTO_ORIGINALE IS NULL )OR(@FASE_ISTRUTTORIA=1 AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL))	
		

IF((SELECT  COUNT(*) FROM PRIORITA_X_PROGETTO WHERE ID_PRIORITA = 1164 AND ID_PROGETTO = @IdProgetto )>0)
BEGIN
	SET @C_P =1
 	SELECT @COSTO_PROG = SUM(COSTO_INVESTIMENTO) 
 	FROM vPIANO_INVESTIMENTI INV
 		INNER JOIN DETTAGLIO_INVESTIMENTI D ON D.ID_CODIFICA_INVESTIMENTO=INV.ID_CODIFICA_INVESTIMENTO AND D.ID_DETTAGLIO_INVESTIMENTO =INV.ID_DETTAGLIO_INVESTIMENTO 
	WHERE ID_PROGETTO = @IdProgetto AND CODICE ='4' AND D.COD_DETTAGLIO ='C1' AND
		((@FASE_ISTRUTTORIA=0 AND ID_INVESTIMENTO_ORIGINALE IS NULL )OR(@FASE_ISTRUTTORIA=1 AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL))	
	IF(@COSTO_PROG > (@COSTO_INVESTIMENTO *2)/100) SET @RESULT =0
END

IF((SELECT  COUNT(*) FROM PRIORITA_X_PROGETTO WHERE ID_PRIORITA = 1165 AND ID_PROGETTO = @IdProgetto )>0)
BEGIN	
	SET @C_D=1
 	SELECT @COSTO_DIREZIONE = SUM(COSTO_INVESTIMENTO) 
 	FROM vPIANO_INVESTIMENTI INV
 		INNER JOIN DETTAGLIO_INVESTIMENTI D ON D.ID_CODIFICA_INVESTIMENTO=INV.ID_CODIFICA_INVESTIMENTO AND D.ID_DETTAGLIO_INVESTIMENTO =INV.ID_DETTAGLIO_INVESTIMENTO 
	WHERE ID_PROGETTO = @IdProgetto AND CODICE ='4' AND D.COD_DETTAGLIO ='C2' AND
		((@FASE_ISTRUTTORIA=0 AND ID_INVESTIMENTO_ORIGINALE IS NULL )OR(@FASE_ISTRUTTORIA=1 AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL))	
	IF(@COSTO_DIREZIONE > (@COSTO_INVESTIMENTO *2)/100) SET @RESULT =0
END

IF(@C_P=1 AND @C_D =1 AND @RESULT =1)
BEGIN 
	IF((@COSTO_PROG +@COSTO_DIREZIONE) > (@COSTO_INVESTIMENTO *2)/100) SET @RESULT =0
END

SELECT @RESULT

END
