CREATE PROCEDURE [dbo].[calcoloStep112_121_4]
@IdProgetto int
AS
/*DECLARE @IdProgetto INT
SET @IdProgetto=336*/
-- 121 - verifica totale investimenti in domanda >= 25.000,00 € 
DECLARE @RESULT INT
SELECT @RESULT=1

DECLARE @ID_PROG_CORRENTE INT
SELECT @ID_PROG_CORRENTE= P.ID_PROGETTO FROM PROGETTO P 
		INNER JOIN BANDO B ON B.ID_BANDO = P.ID_BANDO INNER JOIN ZPROGRAMMAZIONE ZP ON ZP.ID =B.ID_PROGRAMMAZIONE AND CODICE = '1.2.1.'
WHERE ID_PROG_INTEGRATO = @IdProgetto  

DECLARE @TOTALE INT

SET @TOTALE = (SELECT SUM(COSTO_INVESTIMENTO) 
			   FROM PIANO_INVESTIMENTI
					INNER JOIN PROGETTO ON PIANO_INVESTIMENTI.ID_PROGETTO=PROGETTO.ID_PROGETTO
		        WHERE ((FLAG_DEFINITIVO =0  AND ID_INVESTIMENTO_ORIGINALE IS NULL)OR(FLAG_DEFINITIVO =1 AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL ))
					AND COD_TIPO_INVESTIMENTO = 1 AND PIANO_INVESTIMENTI.ID_PROGETTO=@ID_PROG_CORRENTE)

IF (@TOTALE IS NULL OR @TOTALE < 25000) SET @RESULT=0

select @RESULT
