CREATE PROCEDURE [dbo].[calcoloStepVariante133_10]
(
@ID_VARIANTE int
)
AS
BEGIN
--Verificato il rispetto del massimale di contributo previsto dal bando (1.100.000,00 euro/anno)
-- BUDGET PER IL 2013--> 825000 I 9/12 DI 1100000

DECLARE @RESULT INT, @ANNO INT,
		@COSTO_ANNUALITA DECIMAL(18,2),@CONTRIBUTO_ANNUALE DECIMAL(18,2)
	--	,@FASE_ISTRUTTORIA INT =0,@IdProgetto int
		
--SET @IdProgetto = 9023
SET @RESULT =1 --PONGO LO STEP VERIFICATO

-- CONTROLLO L'ANNUALITA --> 1130
-- VALORI 2013 E 2014
SELECT @CONTRIBUTO_ANNUALE= SUM(CONTRIBUTO_RICHIESTO) FROM PIANO_INVESTIMENTI INV 
		INNER JOIN PRIORITA_X_INVESTIMENTI PXI ON PXI.ID_INVESTIMENTO = INV.ID_INVESTIMENTO AND PXI.ID_VALORE =  1110 -- ANNO 2013
WHERE ID_VARIANTE =@ID_VARIANTE and isnull(COD_VARIAZIONE, 'X') != 'A' AND COD_TIPO_INVESTIMENTO =1  
 
IF(@CONTRIBUTO_ANNUALE>825000)SET @RESULT=0
ELSE BEGIN 
		SELECT @CONTRIBUTO_ANNUALE= SUM(CONTRIBUTO_RICHIESTO) FROM PIANO_INVESTIMENTI INV 
				INNER JOIN PRIORITA_X_INVESTIMENTI PXI ON PXI.ID_INVESTIMENTO = INV.ID_INVESTIMENTO AND PXI.ID_VALORE =  1111 -- ANNO 2014
		WHERE ID_VARIANTE =@ID_VARIANTE and isnull(COD_VARIAZIONE, 'X') != 'A' AND COD_TIPO_INVESTIMENTO =1  
		
		IF(@CONTRIBUTO_ANNUALE>1100000)SET @RESULT=0
	END
 
 
SELECT @RESULT  
 
END
