CREATE   PROCEDURE [dbo].[calcoloStepVariante112_111_3]
@ID_VARIANTE  int
-- 111 - Verifica massimali da intervento su corsi di formazione   come da catalogo -- BANDO Iv SCADENZA 
 
AS
-- TROVO IL PROGETTO INTEGRATO
DECLARE @ID_PROG_INTEG_111 INT,@Result INT , @IdProgetto INT, 
		@CODICE CHAR(2), @COSTO DECIMAL(18,2), @COD_TIPO CHAR(2)

SET @Result = 1
SELECT @IdProgetto=  ID_PROGETTO, @COD_TIPO = COD_TIPO  FROM VARIANTI WHERE ID_VARIANTE =  @ID_VARIANTE

SELECT DISTINCT @ID_PROG_INTEG_111 = p.ID_PROGETTO FROM PROGETTO P
		INNER JOIN BANDO B ON B.ID_BANDO = P.ID_BANDO INNER JOIN ZPROGRAMMAZIONE ZP ON ZP.ID =B.ID_PROGRAMMAZIONE AND CODICE = '1.1.1.A'
WHERE ID_PROG_INTEGRATO = @IdProgetto
 
-- controllo la completa indicazione DEL DETTAGLIO DEL CORSO
IF( @Result != 0 )
BEGIN
  DECLARE CORSO_FORMAZIONE CURSOR FOR
  ( 
		SELECT SUM(COSTO_INVESTIMENTO) AS COSTO , D.COD_DETTAGLIO
		FROM PIANO_INVESTIMENTI I INNER JOIN DETTAGLIO_INVESTIMENTI D ON D.ID_DETTAGLIO_INVESTIMENTO= I.ID_DETTAGLIO_INVESTIMENTO
		WHERE ID_PROGETTO =@ID_PROG_INTEG_111 AND ID_VARIANTE = @ID_VARIANTE AND ISNULL(COD_VARIAZIONE, 'X') != 'A' 
		GROUP BY I.ID_DETTAGLIO_INVESTIMENTO, COD_DETTAGLIO
   ) 

OPEN CORSO_FORMAZIONE
FETCH NEXT FROM CORSO_FORMAZIONE 
INTO   @COSTO , @CODICE
WHILE @@FETCH_STATUS = 0
BEGIN

IF( @COSTO>0 )
	IF (@CODICE IN ('1')) -- MIN 934.63;  MAX 1.752,63
		BEGIN IF(@COSTO<934.63 OR @COSTO >1752.63) BEGIN SELECT @COSTO  SET @Result =0 END
		END
		ELSE 
		BEGIN IF (@CODICE IN ('2', '4', '5','6','8','9', '10','13', '36')) BEGIN IF(@COSTO<1000.00 OR @COSTO >1875.00) SET @Result =0 END
			ELSE 
			BEGIN IF (@CODICE IN ('3')) BEGIN  IF(@COSTO<993.33 OR @COSTO >1862.50) SET @Result =0 END
				ELSE
				BEGIN IF (@CODICE IN ('7')) BEGIN IF(@COSTO<800 OR @COSTO >1500) SET @Result =0 END
					ELSE
					BEGIN IF (@CODICE IN ('11')) BEGIN IF(@COSTO<904.25 OR @COSTO >1695.46) SET @Result =0 	END
						ELSE
						BEGIN IF (@CODICE IN ('12')) BEGIN IF(@COSTO<854.25  OR @COSTO >1601.71) SET @Result =0 	END
							ELSE
							BEGIN IF (@CODICE IN ('14','15','16', '17','18','19','20','22','23','24','25','27','28','29','30','31','32', '37','41','42','43','44','45')) --400,00 750,00
										BEGIN IF(@COSTO<400  OR @COSTO >750) SET @Result =0	END
								ELSE--324,00 607,50
								BEGIN IF (@CODICE IN ('21')) BEGIN IF(@COSTO<324  OR @COSTO >607.50) SET @Result =0	END
									ELSE--387,50 726,56
									BEGIN IF (@CODICE IN ('26'))BEGIN IF(@COSTO<387.50  OR @COSTO >726.56) SET @Result =0 END
										ELSE--160,00 300,00 
										BEGIN IF (@CODICE IN ('33'))  BEGIN IF(@COSTO<160  OR @COSTO >300) SET @Result =0 END
											ELSE--389.47 730.25
											BEGIN IF (@CODICE IN ('34','35')) BEGIN IF(@COSTO<389.47  OR @COSTO >730.25) SET @Result =0 END
												ELSE --1.000,00 1.875,00
												BEGIN IF (@CODICE IN ('36')) BEGIN IF(@COSTO<1000  OR @COSTO >1875 ) SET @Result =0 END
													ELSE --200 375
													BEGIN IF (@CODICE IN ('38')) BEGIN IF(@COSTO<200  OR @COSTO >375 ) SET @Result =0 END
														ELSE  
														BEGIN IF (@CODICE IN ('39')) BEGIN IF(@COSTO<233.3  OR @COSTO >437.5 ) SET @Result =0 END
															ELSE  
															BEGIN IF (@CODICE IN ('40')) BEGIN IF(@COSTO<333.3  OR @COSTO >625.5 ) SET @Result =0 END
																ELSE  
																BEGIN IF (@CODICE IN ('46')) BEGIN IF(@COSTO<180  OR @COSTO >340 ) SET @Result =0 END
																	ELSE  
																	BEGIN IF (@CODICE IN ('47')) BEGIN IF(@COSTO<370  OR @COSTO >688 ) SET @Result =0 END
																	END
																END
															END
														END
													END
												END
											  END	
											END	
										END		
									END		
								END		
							END		
						END				
					END											
				END	
		END 			

FETCH NEXT FROM CORSO_FORMAZIONE
INTO @COSTO   ,  @CODICE 
END

CLOSE CORSO_FORMAZIONE
DEALLOCATE CORSO_FORMAZIONE
 END
 
SELECT @Result AS RESULT
