--SALDO 123 macro
CREATE  PROCEDURE [dbo].[calcoloStepPagamento123_6]
@IdProgetto int,
@IdDomandaPagamento int =NULL
AS
BEGIN
	--	Verifica totale investimenti in domanda >=  100000
	--  Requisiti pagamento esito positivo =1 
	
	DECLARE @ID_PROGETTO INT , @IMPORTO_AMMESSO DECIMAL (18,2), @IMPORTO_DOMANDA_ATTUALE DECIMAL (18,2)
	DECLARE @RESULT INT

SET @RESULT = 0 -- IMPONGO LO STEP NON VERIFICATO		 

SET @ID_PROGETTO = ( SELECT ID_PROGETTO FROM DOMANDA_DI_PAGAMENTO WHERE ID_DOMANDA_PAGAMENTO=@IdDomandaPagamento  )	

-- (CODICE IN ( '66','67') ) 
DECLARE @C_TRAF INT
 SET @C_TRAF =( SELECT COUNT(*)
				FROM  PAGAMENTI_RICHIESTI PR  
					INNER JOIN VPIANO_INVESTIMENTI INV ON INV.ID_INVESTIMENTO = PR.ID_INVESTIMENTO 
				WHERE ID_DOMANDA_PAGAMENTO IN (SELECT ID_DOMANDA_PAGAMENTO FROM DOMANDA_DI_PAGAMENTO WHERE ID_PROGETTO = @ID_PROGETTO  AND ANNULLATA=0) 
					AND (CODICE IN ( '66','67') ) AND PR.IMPORTO_RICHIESTO >0
 )


IF(ISNULL(@C_TRAF,0) >0)
BEGIN 
		--COSTO INVESTIMENTO AMMESSO NELLE DOMANDE PRECEDENTI
	SET @IMPORTO_AMMESSO = (SELECT ISNULL( SUM(ISNULL( PB.IMPORTO_AMMESSO,0 ) +  ISNULL( PB.SPESA_TECNICA_AMMESSA,0 )) ,0)
							FROM PAGAMENTI_BENEFICIARIO PB INNER JOIN
										PAGAMENTI_RICHIESTI PR ON PB.ID_PAGAMENTO_RICHIESTO = PR.ID_PAGAMENTO_RICHIESTO
							WHERE ID_DOMANDA_PAGAMENTO  IN (SELECT ID_DOMANDA_PAGAMENTO FROM DOMANDA_DI_PAGAMENTO WHERE ID_PROGETTO = @ID_PROGETTO AND APPROVATA = 1  AND ANNULLATA=0) 
							)	

	SET @IMPORTO_DOMANDA_ATTUALE = (SELECT ISNULL( SUM(ISNULL( PB.IMPORTO_AMMESSO,0 ) +  ISNULL( PB.SPESA_TECNICA_AMMESSA,0 ) ) ,0)
									FROM PAGAMENTI_BENEFICIARIO PB INNER JOIN
										PAGAMENTI_RICHIESTI PR ON PB.ID_PAGAMENTO_RICHIESTO = PR.ID_PAGAMENTO_RICHIESTO
									WHERE ID_DOMANDA_PAGAMENTO = @IdDomandaPagamento )

	IF((@IMPORTO_DOMANDA_ATTUALE + isnull(@IMPORTO_AMMESSO,0))>=100000 )SET @RESULT = 1
END 
ELSE SET @RESULT =1

SELECT @RESULT
END
