--SAL  111 a assam   
-- CONTROLLO 100% ANNO N-1 NON OBBLIGATORIO

CREATE   PROCEDURE [dbo].[calcoloRequisitoPagamento111_2 ]
@ID_DOMANDA_PAGAMENTO int
AS
BEGIN
 
	DECLARE @ID_PROGETTO INT , @IMPORTO_RICHIESTO DECIMAL (18,2) , @ANNO INT, @COSTO_INVESTIMENTO  DECIMAL (18,2), @DATA_ULTIMA_MODIFICA DATETIME
	DECLARE @RESULT INT

SET @RESULT =1  -- IMPONGO LO STEP   VERIFICATO		 
SELECT @ID_PROGETTO =ID_PROGETTO, @DATA_ULTIMA_MODIFICA=DATA_MODIFICA FROM DOMANDA_DI_PAGAMENTO WHERE ID_DOMANDA_PAGAMENTO=@ID_DOMANDA_PAGAMENTO
SET @ANNO =DATEPART(YEAR,@DATA_ULTIMA_MODIFICA)-1
SELECT  @IMPORTO_RICHIESTO = SUM(ISNULL(IMPORTO_RICHIESTO,0) ),  
		@COSTO_INVESTIMENTO =(SUM(ISNULL(COSTO_INVESTIMENTO,0 ))+ SUM(ISNULL(SPESE_GENERALI,0)))
FROM PIANO_INVESTIMENTI PI LEFT JOIN  
	 PAGAMENTI_RICHIESTI PR ON PI.ID_INVESTIMENTO = PR.ID_INVESTIMENTO AND ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO
WHERE id_progetto = @ID_PROGETTO AND ID_INVESTIMENTO_ORIGINALE is not null AND  
	  DESCRIZIONE LIKE '%'+CAST(@ANNO  AS CHAR(4))+ '%'   
	  
IF(@COSTO_INVESTIMENTO !=@IMPORTO_RICHIESTO ) SET @RESULT=0
SELECT @RESULT
END
