CREATE  PROCEDURE [dbo].[calcoloRequisitoPagamento133_1]
@ID_DOMANDA_PAGAMENTO int
AS
BEGIN
--	E` possibile presentare domanda di SAL (spesa rendicontata >= 50% di quella autorizzata per il progetto annuale)
--  Requisiti pagamento esito positivo =1 
-- anno =228
--	
--DECLARE @ID_DOMANDA_PAGAMENTO int
--SET @ID_DOMANDA_PAGAMENTO  =1224
DECLARE @ID_PROGETTO INT, @IMPORTO_RICHIESTO DECIMAL (18,2),@ANNO VARCHAR(4), @DATA_MODIFICA DATETIME,
						@IMPORTO_DOMANDA_ATTUALE DECIMAL (18,2), @ID_INVESTIMENTO INT, @ID_VARIANTE INT, @COSTO_INVESTIMENTO DECIMAL(18,2), @COSTO_TOTALE DECIMAL (18,2)
DECLARE @RESULT INT

SET @RESULT = 1 -- IMPONGO LO STEP  VERIFICATO
SET @IMPORTO_RICHIESTO= 0 	 
SELECT @ID_PROGETTO =  ID_PROGETTO, @DATA_MODIFICA =DATA_MODIFICA FROM DOMANDA_DI_PAGAMENTO WHERE ID_DOMANDA_PAGAMENTO=@ID_DOMANDA_PAGAMENTO 	
SELECT @ID_VARIANTE= MAX(ID_VARIANTE) FROM VARIANTI WHERE ID_PROGETTO =@ID_PROGETTO AND APPROVATA = 1 AND ANNULLATA =0 
 -- CONTROLLO PER OGNI ANNO RENDICONTATO
DECLARE ANNI CURSOR FOR
(
SELECT PXI.DESCRIZIONE FROM PAGAMENTI_RICHIESTI PR INNER JOIN 
				PIANO_INVESTIMENTI INV ON PR.ID_INVESTIMENTO= INV.ID_INVESTIMENTO AND PR.ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO INNER JOIN 
				vPRIORITA_X_INVESTIMENTI PXI ON INV.ID_INVESTIMENTO = PXI.ID_INVESTIMENTO AND PXI.ID_PRIORITA in ( 228,1130)
WHERE PXI.DESCRIZIONE <= CAST( DATEPART(YYYY,@DATA_MODIFICA) AS VARCHAR(4)) GROUP BY PXI.DESCRIZIONE
)
OPEN ANNI
FETCH NEXT FROM ANNI 
INTO  @ANNO
WHILE @@FETCH_STATUS = 0
BEGIN
SET @COSTO_TOTALE =0
		DECLARE INVESTIMENTO CURSOR FOR
		(   SELECT INV.ID_INVESTIMENTO, COSTO_INVESTIMENTO 
			FROM PIANO_INVESTIMENTI INV INNER JOIN 
						vPRIORITA_X_INVESTIMENTI PXI ON INV.ID_INVESTIMENTO = PXI.ID_INVESTIMENTO AND PXI.ID_PRIORITA in ( 228,1130)
			WHERE ((@ID_VARIANTE IS NULL AND ID_VARIANTE IS NULL AND ID_PROGETTO =@ID_PROGETTO AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL)OR
							(@ID_VARIANTE IS NOT NULL AND ID_VARIANTE=@ID_VARIANTE AND ISNULL(COD_VARIAZIONE,'X') != 'A')) AND	PXI.DESCRIZIONE = @ANNO)
		
		OPEN INVESTIMENTO
		FETCH NEXT FROM INVESTIMENTO 
		INTO @ID_INVESTIMENTO ,@COSTO_INVESTIMENTO
		WHILE @@FETCH_STATUS = 0
		BEGIN
			--COSTO INVESTIMENTO AMMESSO NELLE DOMANDE PRECEDENTI mETTENDO L'INVESIMENTO ATTUALE MI CALCOLA DIRETTAMENTE ANCHE LA SPESA PER LA DOMANDA ATTUALE
 			SELECT @IMPORTO_RICHIESTO =@IMPORTO_RICHIESTO+ DBO.calcoloStoricoImportoRichiestoInvestimento(@ID_INVESTIMENTO, @ID_DOMANDA_PAGAMENTO)
  			SET @COSTO_TOTALE =@COSTO_TOTALE + ISNULL(@COSTO_INVESTIMENTO,0)
 			FETCH NEXT FROM INVESTIMENTO
			INTO @ID_INVESTIMENTO ,@COSTO_INVESTIMENTO
		END
		CLOSE INVESTIMENTO
		DEALLOCATE INVESTIMENTO 
 IF(ISNULL(@IMPORTO_RICHIESTO,0) < @COSTO_TOTALE/2)    SET @RESULT = 0    

FETCH NEXT FROM ANNI
INTO @ID_INVESTIMENTO 
END

CLOSE ANNI
DEALLOCATE ANNI 

SELECT @RESULT
END
