-- SALDO
--=== Data richiesta di saldo (entro il 30 giugno 2013 più eventuali proroghe) ===--

--ID_REQUISITO	DESCRIZIONE	PLURIVALORE	NUMERICO	DATETIME
--204	Data di ricezione della comunicazione di finanziabilità	0	0	1
--205	Data inizio inteventi programmati	0	0	1
--211	Proroga di 6 mesi per la fine dei lavori	0	0	0
--260	Data fine interventi programmati	0	0	1
--261	Data richiesta di saldo (entro il 30 giugno 2013 più eventuali proroghe)	0	0	0

CREATE PROCEDURE [dbo].[calcoloRequisitoPagamento_B143_1]
@ID_DOMANDA_PAGAMENTO int
AS
BEGIN

DECLARE @ID_PROGETTO INT, @RESULT INT, @DATA_IMPOSTA DATETIME, @PROROGA_6 INT,@DIFFERENZA INT
SET @RESULT = 0 -- IMPONGO LO STEP NON VERIFICATO		

--declare @ID_DOMANDA_PAGAMENTO int = 
SELECT @DATA_IMPOSTA = '2013-06-30 00:00:00.000' -- DATA ENTRO LA QUALE DEVONO PRESENTARE IL SALDO SE NON RICHIEDONO PROROGA DI 6 MESI
SELECT @PROROGA_6 = CASE WHEN COUNT(*)>0 THEN 6 ELSE 0 END  FROM DOMANDA_PAGAMENTO_REQUISITI WHERE ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO AND ID_REQUISITO = 211
  
SELECT @DIFFERENZA = DATEDIFF(DAY, DATEADD(MM,@PROROGA_6 ,(@DATA_IMPOSTA)) , (select DATA_MODIFICA from DOMANDA_DI_PAGAMENTO where ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO))
	
IF (@DIFFERENZA <= 0) 
SET @RESULT = 1 	
	 ELSE SET @RESULT = 0 	
END
SELECT @RESULT
