CREATE PROCEDURE [dbo].[calcoloPriorita4135_FL_A]
(
@IdProgetto int,
@fase_istruttoria bit,
@IdVariante INT 
)
AS
BEGIN
-- AZIONE A
-- tutti gli invetimenti devono essere in area D o C3 per ottenere il punteggio

DECLARE @COSTO_EXTRA DECIMAL(18,2),@PUNTEGGIO DECIMAL(10,2)
	 


 SELECT @COSTO_EXTRA= SUM(ISNULL(COSTO_INVESTIMENTO,0)) --,TIPO_AREA
     FROM VPIANO_INVESTIMENTI AS I
         INNER JOIN(SELECT MAX(LOC.ID_LOCALIZZAZIONE) AS ID_LOCALIZZAZIONE, LOC.ID_INVESTIMENTO FROM LOCALIZZAZIONE_INVESTIMENTO AS LOC
                         INNER JOIN PIANO_INVESTIMENTI AS PI ON LOC.ID_INVESTIMENTO = PI.ID_INVESTIMENTO
                    WHERE (PI.ID_PROGETTO = @IdProgetto) AND
                         ((@fase_istruttoria=0 AND PI.ID_INVESTIMENTO_ORIGINALE IS NULL AND ID_VARIANTE IS NULL )OR
                         (@fase_istruttoria=1 AND (PI.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL AND @IdVariante IS NULL) OR
                                                 (ID_VARIANTE = @IdVariante AND @IdVariante IS NOT NULL AND ISNULL(COD_VARIAZIONE, 'X' ) != 'A')))
                     GROUP BY LOC.ID_INVESTIMENTO) AS LOC_INV ON LOC_INV.ID_INVESTIMENTO = I.ID_INVESTIMENTO
         INNER JOIN vLOCALIZZAZIONE_INVESTIMENTO AS L ON L.ID_LOCALIZZAZIONE = LOC_INV.ID_LOCALIZZAZIONE
         INNER JOIN vCOMUNI ON L.ID_COMUNE = vCOMUNI.ID_COMUNE
     WHERE I.CODICE='A' AND I.ID_PROGETTO=@IdProgetto AND TIPO_AREA NOT IN ('D','C3')

IF(@COSTO_EXTRA >0)SET @PUNTEGGIO = 0 
	ELSE SET @PUNTEGGIO=0.2
SELECT @Punteggio AS PUNTEGGIO
END
