CREATE PROCEDURE [dbo].[calcoloStep111_11]
	@IdProgetto int,
	@FASE_ISTRUTTORIA INT =0 
AS
BEGIN

-- 111b) - Spesa relativa alle Azioni informative sulla sicurezza almeno il 20% del costo totale progetto
-- 1155 id priorita sicurezza

DECLARE @Result int, @COSTO_SICUREZZA DECIMAL(18,2), @COSTO_PROGETTO DECIMAL(18,2)
SET @Result = 1 -- Impongo lo Step verificato
--------------------------------------------------------------------------------------------------------------
SELECT @COSTO_SICUREZZA = SUM(COSTO_INVESTIMENTO) 
FROM PIANO_INVESTIMENTI INV 
	INNER JOIN PRIORITA_X_INVESTIMENTI PXI ON PXI.ID_INVESTIMENTO = INV.ID_INVESTIMENTO AND PXI.ID_PRIORITA = 1155
	INNER JOIN CODIFICA_INVESTIMENTO C ON C.ID_CODIFICA_INVESTIMENTO = INV.ID_CODIFICA_INVESTIMENTO
WHERE C.CODICE IN ('1','2','3','4','9','10') AND INV.ID_PROGETTO =@IdProgetto AND 
	((@FASE_ISTRUTTORIA=0 AND INV.ID_INVESTIMENTO_ORIGINALE IS NULL AND ID_VARIANTE IS NULL )
		OR(@FASE_ISTRUTTORIA=1 AND INV.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NOT NULL ))		

SELECT @COSTO_PROGETTO = DBO.calcoloCostoTotaleProgetto(@IdProgetto,@FASE_ISTRUTTORIA,NULL)
IF(@COSTO_SICUREZZA < @COSTO_PROGETTO * 0.2) SET @Result = 0
ELSE SET @Result = 1
SELECT @Result AS RESULT

END
