CREATE PROCEDURE [dbo].[calcoloStepVariante431_2]
@ID_VARIANTE int
AS
BEGIN
 
----- massimale di aiuto per l'intervento B
--  declare @ID_VARIANTE int
--set @ID_VARIANTE = 1520
DECLARE @RESULT int, @IdProgetto INT,@CONTRIBUTO_RICHIESTO_PROGETTO_B DECIMAL (10,2),
	    @CONTRIBUTO_RICHIESTO_PASSATO_B DECIMAL (10,2),@QUOTA_CONTRIBUTO_TOTALE_B DECIMAL(10,2), @CUAA CHAR(16),@ID_IMPRESA INT,
	    @CONTRIBUTO_RICHIESTO_PROGETTO_A DECIMAL (10,2),@CONTRIBUTO_RICHIESTO_PASSATO_A DECIMAL (10,2), @QUOTA_CONTRIBUTO_TOTALE_A DECIMAL(10,2)
SET @RESULT = 0  -- Impongo lo Step NON verificato
--modifica 15/02/2013 -->b PUò ESSERE IL DOPPIO MA RIMANE CONFERMATO IL MASSIMALE A+B

--------------------------------------------------------------------------------------------------------------
SET @IdProgetto =  (SELECT ID_PROGETTO FROM VARIANTI WHERE ID_VARIANTE=@ID_VARIANTE )
SELECT @ID_IMPRESA = P.ID_IMPRESA , @CUAA = imp.CUAA 
FROM PROGETTO P INNER JOIN IMPRESA IMP ON IMP.ID_IMPRESA = P.ID_IMPRESA  WHERE ID_PROGETTO = @IdProgetto 


SET @CONTRIBUTO_RICHIESTO_PROGETTO_B = (SELECT SUM(PI.CONTRIBUTO_RICHIESTO) AS CONTRIBUTO
										FROM PIANO_INVESTIMENTI PI INNER JOIN
											 PROGETTO ON PI.ID_PROGETTO = PROGETTO.ID_PROGETTO
										WHERE PI.ID_PROGRAMMAZIONE = 326 AND ID_VARIANTE = @ID_VARIANTE AND ISNULL(COD_VARIAZIONE,'x')!='A' )
--ID_BANDO = 106
SET @CONTRIBUTO_RICHIESTO_PASSATO_B =(SELECT SUM(CONTRIBUTO_RICHIESTO) AS CONTRIBUTO
									  FROM PIANO_INVESTIMENTI 
									  WHERE ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL  AND ID_PROGRAMMAZIONE = 326 AND ID_PROGETTO IN 
								 		(SELECT ID_PROGETTO FROM VPROGETTO WHERE ID_IMPRESA=@ID_IMPRESA AND ORDINE_FASE >= 4 AND COD_STATO!= 'n' AND ORDINE_FASE != 99 
								 				AND FLAG_DEFINITIVO =1 AND  ID_PROGETTO <> @IdProgetto  AND ID_BANDO = 106 ) )   
								 				   
SET @QUOTA_CONTRIBUTO_TOTALE_B = (ISNULL(@CONTRIBUTO_RICHIESTO_PROGETTO_B,0) + ISNULL(@CONTRIBUTO_RICHIESTO_PASSATO_B,0)   )

SET @CONTRIBUTO_RICHIESTO_PROGETTO_A = (SELECT     SUM(PI.CONTRIBUTO_RICHIESTO) AS CONTRIBUTO
									  FROM PIANO_INVESTIMENTI PI INNER JOIN
										PROGETTO ON PI.ID_PROGETTO = PROGETTO.ID_PROGETTO
									  WHERE     (PI.ID_PROGETTO = @IdProgetto) AND PI.ID_PROGRAMMAZIONE = 325 AND
									 ID_VARIANTE = @ID_VARIANTE AND isnull(COD_VARIAZIONE,'x')!='A' )
--ID_BANDO = 106
SET @CONTRIBUTO_RICHIESTO_PASSATO_A = (SELECT SUM(CONTRIBUTO_RICHIESTO) AS CONTRIBUTO
									   FROM PIANO_INVESTIMENTI 
									   WHERE ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL  
											AND ID_PROGRAMMAZIONE = 325  AND
											ID_PROGETTO IN (SELECT ID_PROGETTO FROM vPROGETTO 
															WHERE ID_IMPRESA =@ID_IMPRESA AND ORDINE_FASE >= 4 AND COD_STATO!= 'n' AND ORDINE_FASE != 99 AND FLAG_DEFINITIVO =1 AND  ID_PROGETTO <> @IdProgetto  AND ID_BANDO = 106 ) )      
 
SET @QUOTA_CONTRIBUTO_TOTALE_A = (ISNULL(@CONTRIBUTO_RICHIESTO_PROGETTO_A,0) + ISNULL(@CONTRIBUTO_RICHIESTO_PASSATO_A,0)   )
 
-- A Colli Esini San Vicino    TOTALE  € 852.045,08 	 
IF (@CUAA = '01119560439' AND @QUOTA_CONTRIBUTO_TOTALE_B <=  593227.31  )
	BEGIN IF((ISNULL(@QUOTA_CONTRIBUTO_TOTALE_B,0) + ISNULL(@QUOTA_CONTRIBUTO_TOTALE_A,0)) <= 1186455.30) SET @RESULT = 1 END 
 -- B	Montefeltro Sviluppo 	 TOTALE  € 836.048,86 
ELSE IF ((@CUAA = '01377860414' )    AND  @QUOTA_CONTRIBUTO_TOTALE_B   <=  642073.52 )
	BEGIN IF((ISNULL(@QUOTA_CONTRIBUTO_TOTALE_B,0) + ISNULL(@QUOTA_CONTRIBUTO_TOTALE_A,0)) <= 1284147.03  ) SET @RESULT = 1 END 
-- C	Sibilla 	   € 920.633,20 
ELSE IF (@CUAA = '01451540437'  AND @QUOTA_CONTRIBUTO_TOTALE_B <=  605332.76 )
	BEGIN IF((ISNULL(@QUOTA_CONTRIBUTO_TOTALE_B,0) + ISNULL(@QUOTA_CONTRIBUTO_TOTALE_A,0)) <= 1040803.80 ) SET @RESULT = 1 END 
--D1	Flaminia Cesano 	 € 655.201,44 
ELSE IF (@CUAA = '01377760416'   AND  @QUOTA_CONTRIBUTO_TOTALE_B  <=    406308.46   ) 
		BEGIN IF((ISNULL(@QUOTA_CONTRIBUTO_TOTALE_B,0) + ISNULL(@QUOTA_CONTRIBUTO_TOTALE_A,0)) <=  788950.73) SET @RESULT = 1 END 
--D2	Piceno     € 660.202,29 
ELSE IF (@CUAA = '01502360447' AND  @QUOTA_CONTRIBUTO_TOTALE_B  <= 466794.77  )  
		BEGIN IF((ISNULL(@QUOTA_CONTRIBUTO_TOTALE_B,0) + ISNULL(@QUOTA_CONTRIBUTO_TOTALE_A,0)) <= 799596.72) SET @RESULT = 1 END 
-- E	Fermano Leader  € 674.050,97 
ELSE IF (@CUAA = '01944950441'   AND  @QUOTA_CONTRIBUTO_TOTALE_B  <= 445734.38  )  
		BEGIN IF((ISNULL(@QUOTA_CONTRIBUTO_TOTALE_B,0) + ISNULL(@QUOTA_CONTRIBUTO_TOTALE_A,0)) <= 869899.13 ) SET @RESULT = 1 END 
--SELECT @CUAA, @QUOTA_CONTRIBUTO_TOTALE_B
SELECT @RESULT
END
