-- Controllo massimale di spesa su Spese generali (Dettaglio = 06 max 5% totale domanda)
-- UNICO BENEFICIARIO ASSAM CUAA= 01491360424

CREATE PROCEDURE [dbo].[calcoloStep214_3]
@IdProgetto int
AS
BEGIN

DECLARE @RESULT INT, @COSTO_SPESE_GENERALI DECIMAL(18,2),
		@COSTO_TOTALE DECIMAL (18,2), @CUAA VARCHAR(16)



SET @RESULT =1 --PONGO LO STEP NN VERIFICATO
 SELECT @CUAA= IMP.CUAA FROM PROGETTO P INNER JOIN IMPRESA IMP ON P.ID_IMPRESA =IMP.ID_IMPRESA  WHERE ID_PROGETTO = @IdProgetto

IF (@CUAA  = '01491360424')
	BEGIN

	SET @COSTO_TOTALE = (SELECT SUM (ISNULL(COSTO_INVESTIMENTO,0)) FROM PIANO_INVESTIMENTI PI
									INNER JOIN VPROGETTO P ON P.ID_PROGETTO = PI.ID_PROGETTO 
									WHERE   PI.ID_PROGETTO = @IdProgetto  AND 
									((P.COD_STATO ='P' and ID_INVESTIMENTO_ORIGINALE IS NULL AND ID_VARIANTE is null  ) OR 
	 						          (P.COD_STATO !='P'  AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE is null ) ) )

	SET @COSTO_SPESE_GENERALI = (SELECT SUM (ISNULL(COSTO_INVESTIMENTO,0)) FROM PIANO_INVESTIMENTI PI
									INNER JOIN VPROGETTO P ON P.ID_PROGETTO = PI.ID_PROGETTO 
									INNER JOIN CODIFICA_INVESTIMENTO C ON C.ID_CODIFICA_INVESTIMENTO = PI.ID_CODIFICA_INVESTIMENTO 
									INNER JOIN DETTAGLIO_INVESTIMENTI D ON C.ID_CODIFICA_INVESTIMENTO = D.ID_CODIFICA_INVESTIMENTO and d.ID_DETTAGLIO_INVESTIMENTO =pi.ID_DETTAGLIO_INVESTIMENTO  AND D.COD_DETTAGLIO ='06' 
									WHERE PI.ID_PROGETTO = @IdProgetto  AND 
								((P.COD_STATO ='P' and ID_INVESTIMENTO_ORIGINALE IS NULL AND ID_VARIANTE is null  ) OR 
	 						          (P.COD_STATO !='P' AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE is null ) ) )
 
    IF(isnull(@COSTO_SPESE_GENERALI,0) > (isnull(@COSTO_TOTALE,0) * 0.05) )SET @RESULT = 0 
		 
	END
 ELSE SET @RESULT = 0 

 SELECT   @RESULT AS RESULT
	
END
