CREATE PROCEDURE [dbo].[calcoloStep222_3]
(
@IdProgetto int,
@FASE_ISTRUTTORIA INT =0
)
AS
BEGIN

--declare @IdProgetto int = ....,
--		@FASE_ISTRUTTORIA INT =0

DECLARE @RESULT INT, 
		@CONTA_NO_QUANTITA DECIMAL,
		@CONTA_NO_HA DECIMAL,
		@CONTA_NO_TIPOLOGIA DECIMAL,
		@NUMERO_IMPIANTO INT

SET @RESULT = 0 -- pongo lo step in STATO NON VERIFICATO

-- STEP ---- E' stato inserita la quantità di piante, gli Ha e la tipologia dell'impianto

-- id priorità 1181	Quota LAVORI IN ECONOMIA (€) -- numeroco livello inv
-- id priorità: 1185 - Ettari da piano colturale (m2) -- numeroco livello inv

--  Tipologia specie  - id priorità: 1180 -->  (livello investimento - plurivalore)
	-- id_valore priorita: 1151 - Arboree - codice: 1
	-- id_valore priorita: 1152	- Arbustive- codice: 2

-- id priorità: 1203 - numero dell'impianto -- numerico liv inv


-- CONTROLLO UNO -- NUMERO PIANTE
SELECT @CONTA_NO_QUANTITA = (SELECT((SELECT COUNT(ID_INVESTIMENTO) FROM VPIANO_INVESTIMENTI I 
							inner join DETTAGLIO_INVESTIMENTI D on D.ID_DETTAGLIO_INVESTIMENTO = I.ID_DETTAGLIO_INVESTIMENTO
							WHERE 
							COD_TIPO_INVESTIMENTO = 1 AND
								((ID_INVESTIMENTO_ORIGINALE IS NULL AND @FASE_ISTRUTTORIA=0 AND ID_VARIANTE IS NULL) OR
								(ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND @FASE_ISTRUTTORIA =1 AND ID_VARIANTE IS NULL)) AND
							I.ID_PROGETTO = @IdProgetto AND
							D.COD_DETTAGLIO = 'a')
-
(SELECT COUNT(QUANTITA) FROM VPIANO_INVESTIMENTI I 
							inner join DETTAGLIO_INVESTIMENTI D on D.ID_DETTAGLIO_INVESTIMENTO = I.ID_DETTAGLIO_INVESTIMENTO
							WHERE 
							COD_TIPO_INVESTIMENTO = 1 AND
								((ID_INVESTIMENTO_ORIGINALE IS NULL AND @FASE_ISTRUTTORIA=0 AND ID_VARIANTE IS NULL) OR
								(ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND @FASE_ISTRUTTORIA =1 AND ID_VARIANTE IS NULL)) AND
							I.ID_PROGETTO = @IdProgetto AND
							D.COD_DETTAGLIO = 'a' AND
							I.QUANTITA IS NOT NULL)))
							
							
-- CONTROLLO DUE -- Presenza Ettari
SELECT @CONTA_NO_HA = (SELECT((SELECT COUNT(ID_INVESTIMENTO) FROM VPIANO_INVESTIMENTI I 
							inner join DETTAGLIO_INVESTIMENTI D on D.ID_DETTAGLIO_INVESTIMENTO = I.ID_DETTAGLIO_INVESTIMENTO
							WHERE 
							COD_TIPO_INVESTIMENTO = 1 AND
								((ID_INVESTIMENTO_ORIGINALE IS NULL AND @FASE_ISTRUTTORIA=0 AND ID_VARIANTE IS NULL) OR
								(ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND @FASE_ISTRUTTORIA =1 AND ID_VARIANTE IS NULL)) AND
							I.ID_PROGETTO = @IdProgetto AND
							D.COD_DETTAGLIO = 'a')
-
(SELECT COUNT(I.ID_INVESTIMENTO) FROM VPIANO_INVESTIMENTI I 
							inner join DETTAGLIO_INVESTIMENTI D on D.ID_DETTAGLIO_INVESTIMENTO = I.ID_DETTAGLIO_INVESTIMENTO
							inner join PRIORITA_X_INVESTIMENTI PXI on I.ID_INVESTIMENTO = PXI.ID_INVESTIMENTO
							WHERE 
							COD_TIPO_INVESTIMENTO = 1 AND
								((ID_INVESTIMENTO_ORIGINALE IS NULL AND @FASE_ISTRUTTORIA=0 AND ID_VARIANTE IS NULL) OR
								(ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND @FASE_ISTRUTTORIA =1 AND ID_VARIANTE IS NULL)) AND
							I.ID_PROGETTO = @IdProgetto AND
							D.COD_DETTAGLIO = 'a' AND
							PXI.ID_PRIORITA = 1185)))


-- CONTROLLO TRE -- Tipologia su tutti
SELECT @CONTA_NO_TIPOLOGIA = (SELECT((SELECT COUNT(ID_INVESTIMENTO) FROM VPIANO_INVESTIMENTI 
							WHERE 
							COD_TIPO_INVESTIMENTO = 1 AND
								((ID_INVESTIMENTO_ORIGINALE IS NULL AND @FASE_ISTRUTTORIA=0 AND ID_VARIANTE IS NULL) OR
								(ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND @FASE_ISTRUTTORIA =1 AND ID_VARIANTE IS NULL)) AND
							ID_PROGETTO = @IdProgetto)
-
(SELECT COUNT(I.ID_INVESTIMENTO) FROM VPIANO_INVESTIMENTI I 
							inner join DETTAGLIO_INVESTIMENTI D on D.ID_DETTAGLIO_INVESTIMENTO = I.ID_DETTAGLIO_INVESTIMENTO
							inner join PRIORITA_X_INVESTIMENTI PXI on I.ID_INVESTIMENTO = PXI.ID_INVESTIMENTO
							WHERE 
							COD_TIPO_INVESTIMENTO = 1 AND
								((ID_INVESTIMENTO_ORIGINALE IS NULL AND @FASE_ISTRUTTORIA=0 AND ID_VARIANTE IS NULL) OR
								(ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND @FASE_ISTRUTTORIA =1 AND ID_VARIANTE IS NULL)) AND
							I.ID_PROGETTO = @IdProgetto AND
							PXI.ID_PRIORITA = 1180)))
							
							
							
-- CONTROLLO QUATTRO -- NUMERO IMPIANTO
SELECT @NUMERO_IMPIANTO = (SELECT((SELECT COUNT(ID_INVESTIMENTO) FROM VPIANO_INVESTIMENTI I 
							inner join DETTAGLIO_INVESTIMENTI D on D.ID_DETTAGLIO_INVESTIMENTO = I.ID_DETTAGLIO_INVESTIMENTO
							WHERE 
							COD_TIPO_INVESTIMENTO = 1 AND
								((ID_INVESTIMENTO_ORIGINALE IS NULL AND @FASE_ISTRUTTORIA=0 AND ID_VARIANTE IS NULL) OR
								(ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND @FASE_ISTRUTTORIA =1 AND ID_VARIANTE IS NULL)) AND
							I.ID_PROGETTO = @IdProgetto AND
							D.COD_DETTAGLIO = 'a')
-
(SELECT COUNT(I.ID_INVESTIMENTO) FROM VPIANO_INVESTIMENTI I 
							inner join DETTAGLIO_INVESTIMENTI D on D.ID_DETTAGLIO_INVESTIMENTO = I.ID_DETTAGLIO_INVESTIMENTO
							inner join PRIORITA_X_INVESTIMENTI PXI on I.ID_INVESTIMENTO = PXI.ID_INVESTIMENTO
							WHERE 
							COD_TIPO_INVESTIMENTO = 1 AND
								((ID_INVESTIMENTO_ORIGINALE IS NULL AND @FASE_ISTRUTTORIA=0 AND ID_VARIANTE IS NULL) OR
								(ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND @FASE_ISTRUTTORIA =1 AND ID_VARIANTE IS NULL)) AND
							I.ID_PROGETTO = @IdProgetto AND
							D.COD_DETTAGLIO = 'a' AND
							PXI.ID_PRIORITA = 1203)))

IF((@CONTA_NO_QUANTITA = 0) AND (@CONTA_NO_HA = 0) AND (@CONTA_NO_TIPOLOGIA = 0) AND (@NUMERO_IMPIANTO = 0) )
	SET @RESULT = 1	
SELECT @RESULT
END
