-- controlli manifestazione

CREATE  PROCEDURE [dbo].[calcoloStepPIF_121_1]
	@IdProgetto int
AS
BEGIN
DECLARE  @RESULT INT 
SET @RESULT =0 --PONGO LO STEP NN VERIFICATO

 IF((SELECT COUNT(*)  FROM PRIORITA_X_PROGETTO WHERE ID_PRIORITA in (390, 391, 374) AND ID_PROGETTO =@IdProgetto ) = 3  )
		 BEGIN
              IF((SELECT COUNT(*)  FROM PRIORITA_X_PROGETTO WHERE ID_PRIORITA in (262,263,264,265) AND ID_PROGETTO =@IdProgetto ) > 1  )
					SET @RESULT =1
			 END
SELECT  @RESULT AS RESULT
 	END
