CREATE PROCEDURE [dbo].[calcoloStep112_111_1]
@IdProgetto int

-- 111 - Verifica massimali da intervento su corsi di formazione  
-- id=311 - altra formazione per disposizione III scadenza
 
AS

DECLARE @ID_PROG_INTEG_111 INT

SELECT DISTINCT @ID_PROG_INTEG_111 = p.ID_PROGETTO FROM PROGETTO P
INNER JOIN BANDO B ON B.ID_BANDO = P.ID_BANDO INNER JOIN ZPROGRAMMAZIONE ZP ON ZP.ID =B.ID_PROGRAMMAZIONE AND CODICE = '1.1.1.A'
WHERE ID_PROG_INTEGRATO = @IdProgetto


DECLARE @COUNT_CODIFICA int
SET @COUNT_CODIFICA = (SELECT SUM(QUANTITA) FROM PIANO_INVESTIMENTI
						WHERE (ID_CODIFICA_INVESTIMENTO in (151,226,311)) AND ID_PROGETTO = @ID_PROG_INTEG_111 AND ID_INVESTIMENTO_ORIGINALE IS NULL
						GROUP BY QUANTITA)

DECLARE @COSTO_INVESTIMENTO int 
SET @COSTO_INVESTIMENTO = (SELECT SUM(CONTRIBUTO_RICHIESTO) 
							FROM PIANO_INVESTIMENTI
							WHERE (ID_CODIFICA_INVESTIMENTO in (151,226,311) ) AND ID_PROGETTO = @ID_PROG_INTEG_111 AND ID_INVESTIMENTO_ORIGINALE IS NULL)

DECLARE @RISULTATO int

IF(@COUNT_CODIFICA*1500<@COSTO_INVESTIMENTO)SET @RISULTATO = 0
ELSE SET @RISULTATO = 1
 
SELECT @RISULTATO AS RISULTATO
