CREATE PROCEDURE [dbo].[calcoloStep111_13]
@IdProgetto int
AS
BEGIN

-- 111 a - rispetto massimale di aiuto 111 a per impresa (6000 € / periodo 2007-13)

DECLARE @Result int,@ID_IMPRESA INT, @CONTRIBUTO_IMPRESA_PERIODO DECIMAL(18,2) , @CONTR_ATTUALE DECIMAL(18,2)

SET @Result = 1 -- Impongo lo Step verificato

-- ELENCO PROGETTI FINANZIATI NELLA MISURA  111 
-- CONTROLLO I PROGETTO AMMISSIBILI 

SELECT @ID_IMPRESA =  ID_IMPRESA FROM PROGETTO WHERE ID_PROGETTO = @IdProgetto
 
SELECT @CONTR_ATTUALE= dbo.calcoloContributoTotaleProgettoCorrelato(@IdProgetto	, 1, null) 
 
SELECT @CONTRIBUTO_IMPRESA_PERIODO = SUM(CONTRIBUTO) FROM (
	SELECT DISTINCT PB.ID_BANDO, P.ID_PROGETTO , dbo.calcoloContributoTotaleProgettoCorrelato(p.id_progetto	, 1,id_var)CONTRIBUTO
	FROM vBANDO_PROGRAMMAZIONE AS PB 
		 INNER JOIN vPROGETTO AS P ON PB.ID_BANDO = P.ID_BANDO AND (P.ORDINE_FASE >= 3 AND P.COD_STATO NOT IN ('N', 'R', 'B', 'E'))
         LEFT JOIN (SELECT MAX(ID_VARIANTE)ID_VAR, ID_PROGETTO FROM VARIANTI WHERE COD_TIPO IN ('VA', 'AR') GROUP BY ID_PROGETTO ) V ON V.ID_PROGETTO = ISNULL(P.ID_PROG_INTEGRATO, P.ID_PROGETTO)
	WHERE (PB.MISURA_PREVALENTE = 1) AND pb.CODICE like '1.1.1.a%' AND (PB.ID_DISPOSIZIONI_ATTUATIVE IS NULL) AND ID_IMPRESA = @ID_IMPRESA ) AS CONTR

IF((ISNULL(@CONTRIBUTO_IMPRESA_PERIODO,0)+ ISNULL(@CONTR_ATTUALE,0) )> 6000) SET @Result =0
ELSE SET @Result =1

SELECT @Result AS RESULT
END
