CREATE PROCEDURE [dbo].[calcoloStepVariante123_13]
@ID_VARIANTE INT

AS
BEGIN

--  123 - Totale inivestimenti per interventi legati alla trasformazione e commercializzazione > = 50.000,00 € - MICROFILIERE

DECLARE @Count int, @COSTO_TRASFORMAZIONE DECIMAL (20,2),@RESULT INT
SET @RESULT =0  --- NON VERIFICATO

-- ID_PRIORITA =1230 LIVELLO INVESTIMENTO

DECLARE @C_PRIO INT
SELECT @C_PRIO= COUNT(*) FROM PIANO_INVESTIMENTI INV LEFT JOIN PRIORITA_X_INVESTIMENTI PXI ON INV.ID_INVESTIMENTO = PXI.ID_INVESTIMENTO AND ID_PRIORITA = 1230
WHERE INV.ID_VARIANTE = @ID_VARIANTE AND  isnull(COD_VARIAZIONE,'x')!='A' AND INV.COD_TIPO_INVESTIMENTO = 1 AND PXI.ID_INVESTIMENTO IS NULL

	IF (ISNULL(@C_PRIO,0) >0) SET @RESULT=0
	ELSE BEGIN 
		SELECT @COSTO_TRASFORMAZIONE= SUM(COSTO_INVESTIMENTO) FROM PIANO_INVESTIMENTI INV 
				INNER JOIN PRIORITA_X_INVESTIMENTI PXI ON INV.ID_INVESTIMENTO = PXI.ID_INVESTIMENTO AND ID_PRIORITA = 1230
				INNER JOIN VALORI_PRIORITA VP ON VP.ID_PRIORITA = PXI.ID_PRIORITA AND VP.ID_VALORE = PXI.ID_VALORE 
		WHERE INV.ID_VARIANTE = @ID_VARIANTE AND  isnull(COD_VARIAZIONE,'x')!='A' AND INV.COD_TIPO_INVESTIMENTO = 1  AND VP.CODICE IN ('T','X')
		
		IF(@COSTO_TRASFORMAZIONE  > 50000 )  SET @RESULT=1
	END
SELECT @RESULT AS RESULT

END

--- MODIFICATO IL 12/03/2014 -- AGGIUNTA PRIORITA PER INVESTIMENTO
 
----SET @Count = (SELECT COUNT(ID_INVESTIMENTO)
----		      FROM PROGETTO P INNER JOIN VPIANO_INVESTIMENTI I ON (P.ID_PROGETTO=I.ID_PROGETTO) 
----		      WHERE I.ID_VARIANTE = @ID_VARIANTE AND  isnull(COD_VARIAZIONE,'x')!='A'  AND I.COD_TIPO_INVESTIMENTO = 1 AND (CODICE IN ( '66','67') ) )
 
------SELECT @Count 
----IF (ISNULL(@Count,0) > 0) 
----BEGIN 
----	SET @COSTO  = ( SELECT ISNULL( SUM (COSTO_INVESTIMENTO + SPESE_GENERALI) , 0) AS Totale_Investimenti  
----										FROM PROGETTO P INNER JOIN  vPIANO_INVESTIMENTI I ON (P.ID_PROGETTO=I.ID_PROGETTO)
----										WHERE  I.ID_VARIANTE = @ID_VARIANTE AND  isnull(COD_VARIAZIONE,'x')!='A' 
----										AND I.COD_TIPO_INVESTIMENTO = 1 AND CODICE IN ('64','65','66','67')   )
----	IF( @COSTO > 50000 )  SET @RESULT=1
----END
----ELSE SET @RESULT =1
