CREATE PROCEDURE [dbo].[calcoloStepVariante431_1]
@ID_VARIANTE int
AS
BEGIN
 
----- massimale di intervento A
-- declare @ID_VARIANTE int
--set @ID_VARIANTE = 2976
 
DECLARE @RESULT int, @IdProgetto INT,
		@CONTRIBUTO_RICHIESTO_PROGETTO_A DECIMAL (10,2),	 
		@CONTRIBUTO_RICHIESTO_PASSATO_A DECIMAL (10,2), 
	 	@QUOTA_CONTRIBUTO_TOTALE_A DECIMAL(10,2), 
		@CUAA CHAR(16),@ID_IMPRESA INT

SET @RESULT = 0  -- Impongo lo Step NON verificato
--------------------------------------------------------------------------------------------------------------
SET @IdProgetto =  (SELECT ID_PROGETTO FROM VARIANTI WHERE ID_VARIANTE=@ID_VARIANTE )

SELECT @ID_IMPRESA = P.ID_IMPRESA , @CUAA = imp.CUAA 
FROM PROGETTO P INNER JOIN IMPRESA IMP ON IMP.ID_IMPRESA = P.ID_IMPRESA  WHERE ID_PROGETTO = @IdProgetto  

SET @CONTRIBUTO_RICHIESTO_PROGETTO_A = (SELECT SUM(PI.CONTRIBUTO_RICHIESTO) AS CONTRIBUTO
									    FROM PIANO_INVESTIMENTI PI INNER JOIN
											PROGETTO ON PI.ID_PROGETTO = PROGETTO.ID_PROGETTO
									     WHERE (PI.ID_PROGETTO = @IdProgetto) AND PI.ID_PROGRAMMAZIONE = 325 AND
												ID_VARIANTE = @ID_VARIANTE AND isnull(COD_VARIAZIONE,'x')!='A' )


--ID_BANDO = 106

SET @CONTRIBUTO_RICHIESTO_PASSATO_A = (SELECT SUM(CONTRIBUTO_RICHIESTO) AS CONTRIBUTO
									   FROM PIANO_INVESTIMENTI 
									   WHERE ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL  AND  
											ID_PROGRAMMAZIONE = 325  AND 
											ID_PROGETTO IN  ( SELECT ID_PROGETTO FROM vPROGETTO 
															  WHERE ID_IMPRESA=@ID_IMPRESA AND ORDINE_FASE >= 4 AND COD_STATO!= 'n' AND
																	ORDINE_FASE != 99 AND FLAG_DEFINITIVO =1 AND 
																	ID_PROGETTO <> @IdProgetto  AND ID_BANDO = 106 ) )      
 
SET @QUOTA_CONTRIBUTO_TOTALE_A = (ISNULL(@CONTRIBUTO_RICHIESTO_PROGETTO_A,0) + ISNULL(@CONTRIBUTO_RICHIESTO_PASSATO_A,0)   )
 
 -- select @CONTRIBUTO_RICHIESTO_PASSATO_A,@QUOTA_CONTRIBUTO_TOTALE_A,@cuaa

-- A	COLLI ESINI    TOTALE  € 889.840,96	 
IF (@CUAA =  '01119560439'  AND   @QUOTA_CONTRIBUTO_TOTALE_A  <= 889840.96 )
	 SET @RESULT = 1
-- B	Montefeltro Sviluppo 	 TOTALE  € 836.048,86 

ELSE IF ((@CUAA = '01377860414' ) AND   @QUOTA_CONTRIBUTO_TOTALE_A   <= 963110.27 )  
  SET @RESULT = 1

-- C	Sibilla  
ELSE IF (@CUAA = '01451540437' AND   @QUOTA_CONTRIBUTO_TOTALE_A   <=  907999.13  )  
	  SET @RESULT = 1

--D1	Flaminia Cesano 	 € 655.201,44 
ELSE IF (@CUAA = '01377760416' AND  @QUOTA_CONTRIBUTO_TOTALE_A  <= 609462.70 ) 
	  SET @RESULT = 1

--D2	Piceno     € 660.202,29 

ELSE IF (@CUAA = '01502360447' AND  @QUOTA_CONTRIBUTO_TOTALE_A  <=   700192.16   )  
	  SET @RESULT = 1

-- E	Fermano Leader  € 674.050,97 
ELSE IF (@CUAA = '01944950441' AND  @QUOTA_CONTRIBUTO_TOTALE_A  <=  668601.57   )  
	  SET @RESULT = 1

--SELECT @CUAA, @QUOTA_CONTRIBUTO_TOTALE_A
 SELECT @RESULT
 END
