CREATE PROCEDURE [dbo].[calcoloStepVarianteATS_1]
 @ID_VARIANTE int
AS
BEGIN

--ATS - Spese generali  capitolo 6 par E inferiori/uguale al 12% delle spese A+B+C+D

DECLARE @result int, @TOTALE_INVESTIMENTO DECIMAL(10,2), @TOTALE_E DECIMAL(10,2) 
SET @result =1 -- PONGO LO STEP VERIFICATO 

SET @TOTALE_INVESTIMENTO =(SELECT SUM(PI.COSTO_INVESTIMENTO) AS COSTO_INVESTIMENTO
						   FROM PIANO_INVESTIMENTI AS PI 
						   WHERE (PI.COD_TIPO_INVESTIMENTO = 1) AND
								PI.ID_DETTAGLIO_INVESTIMENTO NOT IN (722, 727, 732, 737, 742 ) AND 
								(PI.ID_VARIANTE =@ID_VARIANTE )  AND isnull(PI.COD_VARIAZIONE,'x')!='A' )

SET @TOTALE_E=(SELECT SUM(PI.COSTO_INVESTIMENTO) AS COSTO_INVESTIMENTO
			   FROM PIANO_INVESTIMENTI PI
			   WHERE ID_VARIANTE =@ID_VARIANTE AND PI.COD_TIPO_INVESTIMENTO = 1 AND 
					 ID_DETTAGLIO_INVESTIMENTO  IN (722,727,732,737,742)  AND isnull(PI.COD_VARIAZIONE,'x')!='A' )

IF(@TOTALE_E > @TOTALE_INVESTIMENTO*0.12 )SET @result =0 
SELECT @result AS RESULT
END
