CREATE  PROCEDURE [dbo].[calcoloStepPagamento112_6]
@IdProgetto int,
@IdDomandaPagamento int 
AS
BEGIN

DECLARE @CODICE INT,@RESULT INT,
		@DATA_FINE_INTERVENTI DATETIME,@DATA_GRADUATORIA DATETIME, @PROROGA_6 INT, @PROROGA_12 INT
SET @RESULT = 0 -- IMPONGO LO STEP NON VERIFICATO		
--La richiesta di saldo è stata effettuata entro e non oltre il quarantesimo mese dalla data di adozione della decisione 
--individuale di concedere il sostegno (graduatoria) 
--o entro la data che inseriscono nel requisito Data di approvazione della graduatoria di riferimento (inserire la data del Decreto Dirigenziale) + 46 mesi se hanno selezionato il requisito Richiesta proroga di sei mesi per la fine lavori
-- proroga di 6 mesi id_requisito = 156
 
--declare @ID_DOMANDA_PAGAMENTO int = 1220

SELECT @DATA_GRADUATORIA= VAL_DATA FROM DOMANDA_PAGAMENTO_REQUISITI WHERE ID_DOMANDA_PAGAMENTO = @IdDomandaPagamento AND ID_REQUISITO =144
SELECT @DATA_FINE_INTERVENTI=VAL_DATA FROM DOMANDA_PAGAMENTO_REQUISITI WHERE ID_DOMANDA_PAGAMENTO = @IdDomandaPagamento  AND ID_REQUISITO =135
SELECT @PROROGA_6=CASE WHEN COUNT(*)>0 THEN 6 ELSE 0 END FROM DOMANDA_PAGAMENTO_REQUISITI WHERE ID_DOMANDA_PAGAMENTO = @IdDomandaPagamento  AND ID_REQUISITO =156 AND SELEZIONATO =1
SELECT @PROROGA_12=CASE WHEN COUNT(*)>0 THEN 12 ELSE 0 END  FROM DOMANDA_PAGAMENTO_REQUISITI WHERE ID_DOMANDA_PAGAMENTO = @IdDomandaPagamento AND ID_REQUISITO =168 AND SELEZIONATO = 1
IF(@PROROGA_6 >0 AND @PROROGA_12>0)SET @PROROGA_6=0 
IF((@DATA_FINE_INTERVENTI)<=(SELECT DATA_MODIFICA FROM DOMANDA_DI_PAGAMENTO WHERE ID_DOMANDA_PAGAMENTO = @IdDomandaPagamento ))
 BEGIN 
  SET @RESULT=(SELECT 'DIFF'= CASE WHEN DATEDIFF(DAY, DATEADD(MM,40,(@DATA_GRADUATORIA)),(SELECT DATA_MODIFICA FROM DOMANDA_DI_PAGAMENTO WHERE ID_DOMANDA_PAGAMENTO = @IdDomandaPagamento ))<=0 THEN 1 ELSE 0 END)
  IF(@RESULT =0 ) BEGIN 
		IF(@PROROGA_6>0) SET @RESULT=(SELECT 'DIFF'= CASE WHEN DATEDIFF(DAY, DATEADD(MM,46,(@DATA_GRADUATORIA)),(SELECT DATA_MODIFICA FROM DOMANDA_DI_PAGAMENTO WHERE ID_DOMANDA_PAGAMENTO = @IdDomandaPagamento ))<=0 THEN 1 ELSE 0 END)
		ELSE IF(@PROROGA_12>0) SET @RESULT=(SELECT 'DIFF'= CASE WHEN DATEDIFF(DAY, DATEADD(MM,49,(@DATA_GRADUATORIA)),(SELECT DATA_MODIFICA FROM DOMANDA_DI_PAGAMENTO WHERE ID_DOMANDA_PAGAMENTO = @IdDomandaPagamento ))<=0 THEN 1 ELSE 0 END)
     END
	END 
SELECT @RESULT
END
