CREATE  PROCEDURE [dbo].[calcoloStep311_B_6]
@IdProgetto int, 
@FASE_ISTRUTTORIA  int = 0
AS
BEGIN

-- bando 114 e 165  ---  311 b energia
-- VAN >0 
--declare
--@IdProgetto int = 11520 , 
--@FASE_ISTRUTTORIA  int = 0

DECLARE @COSTO_INVESTIMENTO decimal (10,2)  ,
					@RW decimal (10,4), @C decimal(10,2)
DECLARE @TESTO NCHAR (255),
					 @TESTO_SUB NCHAR (255),
					@COUNTER INT,
					@INDICE DECIMAL (18,4 ),
					@SOMMA DECIMAL (18,4 ),
					@SOMMATORIA DECIMAL(18,4),
					@VAN  DECIMAL (18,4),
					@RESULT AS INT =0, @s VARCHAR(15)
 
 SET @RESULT = 0 -- NON VERIFICATO
  SELECT  @s=  CAST (TESTO  AS NCHAR (10) )  FROM  progetto_relazione_tecnica WHERE ID_PROGETTO = @IdProgetto AND ID_PARAGRAFO in (160,394,1650) 
 
 IF(@s NOT LIKE'%;%' AND @s not like '%a%' and  @s not like '%e%' and  @s not like '%i%'   )BEGIN
 
	SET @RW = ( SELECT CAST( CAST (TESTO  AS NCHAR (10) )AS DECIMAL (10,4) )  FROM  progetto_relazione_tecnica WHERE ID_PROGETTO = @IdProgetto AND ID_PARAGRAFO in (160,394,1650)    )
    SET @TESTO = ( SELECT  TESTO FROM  progetto_relazione_tecnica WHERE ID_PROGETTO = @IdProgetto AND ID_PARAGRAFO in ( 176,395,1651)) 
	 SET @COSTO_INVESTIMENTO = (SELECT SUM(COSTO_INVESTIMENTO+ SPESE_GENERALI) - SUM(ISNULL(CONTRIBUTO_RICHIESTO,0)) FROM PIANO_INVESTIMENTI PI  
																	WHERE ID_PROGETTO = @IdProgetto AND  ((@FASE_ISTRUTTORIA=0 AND pi.ID_INVESTIMENTO_ORIGINALE IS NULL)OR
																	(@FASE_ISTRUTTORIA=1 AND PI.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL))  AND  COD_TIPO_INVESTIMENTO =1)
	
	IF(@TESTO not like '%a%' and  @s not like '%e%'and  @s not like '%i%')BEGIN
 		SET @COUNTER =1
		DECLARE @POS_VIRGOLA INT 
		SET @POS_VIRGOLA =( SELECT CHARINDEX( ',',@TESTO )) -- CHI HA UTILIZZATO LA VIRGOLA AL POSTO DEL PUNTO PER IL DECIMALE
		IF(@POS_VIRGOLA > 0 )BEGIN 
			SET @TESTO= REPLACE (@TESTO, '.','')
			SET @TESTO= REPLACE (@TESTO, ',','.')
		END
		DECLARE @POSIZIONE INT
		SET @POSIZIONE =1
		SET @SOMMA =0
		SET @SOMMATORIA =0
		 WHILE  @POSIZIONE  > 0
		   BEGIN 
			SET @POSIZIONE  = ( SELECT CHARINDEX( ';',@TESTO ) )
			IF (@POSIZIONE >0 ) BEGIN SET @TESTO_SUB = SUBSTRING ( @TESTO, 0, @POSIZIONE ) END
			ELSE SET @TESTO_SUB= @TESTO
			IF(LEN(@TESTO_SUB )>0) BEGIN  
				SET @C = CAST(@TESTO_SUB AS DECIMAL(10,2))
 				SET @INDICE = ( POWER( ( 1+@RW  ), @COUNTER ))
				SET @SOMMA = (@C/ @INDICE )
  				SET @SOMMATORIA =@SOMMATORIA +  @SOMMA
				SET @TESTO = SUBSTRING ( @TESTO,  @POSIZIONE + 1, LEN(@TESTO)   ) 
				SET @COUNTER = @COUNTER + 1
			END
		END -- FINE WHILE
		SET @VAN  =  @SOMMATORIA - @COSTO_INVESTIMENTO 
		IF (@VAN>0) SET @RESULT = 1 
		ELSE SET @RESULT = 0
	END	 
 END
 
 SELECT @RESULT 
END
