-- massimale per corso formativo

CREATE   PROCEDURE [dbo].[calcoloStep111_MF_2]
@IdProgetto int
AS
BEGIN

DECLARE  @RESULT INT, @ID_CODIFICA_INVESTIMENTO INT , @COSTO DECIMAL (18,2)
SET @RESULT = 1 -- Impongo lo Step verificato

 DECLARE CORSO CURSOR FOR
  ( 
		SELECT SUM(COSTO_INVESTIMENTO) AS COSTO , ID_CODIFICA_INVESTIMENTO
		FROM PIANO_INVESTIMENTI PI WHERE ID_PROGETTO =@IdProgetto AND ID_INVESTIMENTO_ORIGINALE IS NULL
		GROUP BY ID_CODIFICA_INVESTIMENTO
   ) 
 
 
OPEN CORSO
FETCH NEXT FROM CORSO 
INTO   @COSTO   ,  @ID_CODIFICA_INVESTIMENTO 
WHILE @@FETCH_STATUS = 0
	BEGIN
	IF (@ID_CODIFICA_INVESTIMENTO IN (436 )) -- MIN 400;  MAX  750
		BEGIN 
			IF(@COSTO<400 OR @COSTO >750) SET @Result =0
		END
	 ELSE 
		BEGIN
						IF (@ID_CODIFICA_INVESTIMENTO IN (437, 438))
							BEGIN
								IF(@COSTO<366.67 OR @COSTO >687.50) SET @Result =0
							END
		END 			

	FETCH NEXT FROM CORSO
INTO @COSTO   ,  @ID_CODIFICA_INVESTIMENTO 
END

CLOSE CORSO
DEALLOCATE CORSO 
 
 SELECT   @RESULT  
	
END
