--SAL  111 a assam   
CREATE  PROCEDURE [dbo].[calcoloRequisitoPagamento111_1]
@ID_DOMANDA_PAGAMENTO int
AS
BEGIN
 	DECLARE @ID_PROGETTO INT , @IMPORTO_EXTRA DECIMAL (18,2) , @ANNO INT,@DATA_ULTIMA_MODIFICA DATETIME
	DECLARE @RESULT INT

SET @RESULT =1  -- IMPONGO LO STEP   VERIFICATO		 
SELECT @ID_PROGETTO =ID_PROGETTO, @DATA_ULTIMA_MODIFICA=DATA_MODIFICA FROM DOMANDA_DI_PAGAMENTO WHERE ID_DOMANDA_PAGAMENTO=@ID_DOMANDA_PAGAMENTO
SET @ANNO =DATEPART(YEAR,@DATA_ULTIMA_MODIFICA)-1
	
SET @IMPORTO_EXTRA =(SELECT SUM(ISNULL(IMPORTO_RICHIESTO,0) ) 
					 FROM PIANO_INVESTIMENTI PI LEFT JOIN  
						  PAGAMENTI_RICHIESTI PR ON PI.ID_INVESTIMENTO = PR.ID_INVESTIMENTO AND ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO 
					 WHERE id_progetto = @ID_PROGETTO  AND ID_INVESTIMENTO_ORIGINALE is not null AND 
						   DESCRIZIONE NOT  LIKE  '%'+CAST (@ANNO  AS  CHAR(4))+ '%'  )
IF(@IMPORTO_EXTRA >0)SET @RESULT=0
SELECT @RESULT
END
