CREATE PROCEDURE [dbo].[calcoloStep123_16]
	@IdProgetto int, 
	@FASE_ISTRUTTORIA INT = 0
AS
BEGIN
--  123 - Totale inivestimenti per interventi legati al fotovoltaico

DECLARE @Count int, @COSTO_FOTOVOLTAICO DECIMAL (20,2)
		,@RESULT INT, @COSTO DECIMAL(18,2)

SET @RESULT =0  --- NON VERIFICATO
SET @COSTO_FOTOVOLTAICO = (SELECT ISNULL( SUM (COSTO_INVESTIMENTO + SPESE_GENERALI) , 0) AS Totale_Investimenti  
				FROM PROGETTO P INNER JOIN  vPIANO_INVESTIMENTI I ON (P.ID_PROGETTO=I.ID_PROGETTO)
				WHERE ((I.ID_INVESTIMENTO_ORIGINALE IS NULL  AND @FASE_ISTRUTTORIA =0  AND ID_VARIANTE IS NULL  ) 
								OR (@FASE_ISTRUTTORIA =  1 AND  I.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL  )  )  
								AND I.COD_TIPO_INVESTIMENTO = 1 AND (P.ID_PROGETTO=@IdProgetto) 
								AND COD_SPECIFICA IN ('80'))
				
SELECT @COSTO = dbo.calcoloCostoTotaleProgetto (@IdProgetto, @FASE_ISTRUTTORIA, NULL)							

IF(@COSTO_FOTOVOLTAICO > @COSTO * 0.30) SET @RESULT =0
ELSE SET @RESULT =1 

SELECT @RESULT AS RESULT
END
