CREATE  PROCEDURE [dbo].[calcoloStep321_FM]
@IdProgetto int, 
@FASE_ISTRUTTORIA INT =0
AS
BEGIN

DECLARE @result int, 
		@ZONA INT,
		@COSTO_TOT_PROGETTO INT

--- ID PRIORITA' () 986 PLURIVALORE CHE IDENTIFICA LA ZONA 
--- ZONA D ---> ID_VALORE 1006
--- ZONA C3 --> ID_VALORE 1007

SET @result = 0 -- NON VERIFICATO

SET @ZONA = (select ID_VALORE from priorita_x_progetto WHERE ID_PROGETTO = @IdProgetto and ID_PRIORITA = 986)

SET @COSTO_TOT_PROGETTO = (SELECT ISNULL(SUM(COSTO_INVESTIMENTO),0) + ISNULL( SUM (SPESE_GENERALI),0)  AS Totale_Investimenti FROM PROGETTO P 
							INNER JOIN VPIANO_INVESTIMENTI I ON P.ID_PROGETTO=I.ID_PROGETTO
							WHERE
							I.COD_TIPO_INVESTIMENTO = 1 AND 
							(P.ID_PROGETTO = @IdProgetto) AND
							((I.ID_INVESTIMENTO_ORIGINALE IS NULL AND @FASE_ISTRUTTORIA = 0 AND ID_VARIANTE IS NULL) OR (I.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND @FASE_ISTRUTTORIA = 1 AND ID_VARIANTE IS NULL))) 

IF ((@ZONA = '1006' AND @COSTO_TOT_PROGETTO <= 120000) OR (@ZONA = '1007' AND @COSTO_TOT_PROGETTO <= 80000))
	  SET @result = 1
ELSE
	SET @result = 0			

SELECT @result AS RESULT
END
