--SALDO ATS  PABS
--ATS - spesa progetto > 25.000,00 e < = 65.000,00 Euro

CREATE  PROCEDURE [dbo].[calcoloRequisitoPagamentoATS_1]
@ID_DOMANDA_PAGAMENTO int
AS
BEGIN
 	--  Requisiti pagamento esito positivo =1 
	
	DECLARE @ID_PROGETTO INT , @IMPORTO_AMMESSO DECIMAL (18,2), @IMPORTO_DOMANDA_ATTUALE DECIMAL (18,2)
	DECLARE @RESULT INT

SET @RESULT = 0 -- IMPONGO LO STEP NON VERIFICATO		 
SET @ID_PROGETTO = ( SELECT ID_PROGETTO FROM DOMANDA_DI_PAGAMENTO WHERE ID_DOMANDA_PAGAMENTO=@ID_DOMANDA_PAGAMENTO  )	

--COSTO INVESTIMENTO AMMESSO NELLE DOMANDE PRECEDENTI
SET @IMPORTO_AMMESSO = ( SELECT   ISNULL( SUM(ISNULL( PB.IMPORTO_AMMESSO,0 ) +  ISNULL( PB.SPESA_TECNICA_AMMESSA,0 )) ,0)
															FROM PAGAMENTI_BENEFICIARIO PB INNER JOIN
																		PAGAMENTI_RICHIESTI PR ON PB.ID_PAGAMENTO_RICHIESTO = PR.ID_PAGAMENTO_RICHIESTO
															WHERE ID_DOMANDA_PAGAMENTO  IN (SELECT ID_DOMANDA_PAGAMENTO FROM DOMANDA_DI_PAGAMENTO WHERE ID_PROGETTO = @ID_PROGETTO AND APPROVATA = 1  AND ANNULLATA=0) 
					   )	

SET @IMPORTO_DOMANDA_ATTUALE = 
( SELECT ISNULL( SUM(ISNULL( PB.IMPORTO_RICHIESTO,0 ) +  ISNULL( PB.SPESA_TECNICA_RICHIESTA,0 ) ) ,0)
								  FROM    PAGAMENTI_BENEFICIARIO PB INNER JOIN
										  PAGAMENTI_RICHIESTI PR ON PB.ID_PAGAMENTO_RICHIESTO = PR.ID_PAGAMENTO_RICHIESTO
								  WHERE ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO )

IF((@IMPORTO_DOMANDA_ATTUALE + isnull(@IMPORTO_AMMESSO,0))>=25000 )
	 IF(  (@IMPORTO_DOMANDA_ATTUALE + isnull(@IMPORTO_AMMESSO,0))<=65000)SET @RESULT = 1

SELECT @RESULT
END
