CREATE PROCEDURE [dbo].[calcoloStep911_1]
(
	@IdProgetto int,
	@FASE_ISTRUTTORIA int 
)
AS
BEGIN
/*
1219	Diritti in portafoglio NON in corso di esercizio (mq)
1220	Diritti in portafoglio in corso di esercizio (mq)

*/
	DECLARE @ID_FASCICOLO int, @SUP_PORT_NON_USATA DECIMAL(18,4), @SUP_PORT_USATA DECIMAL(18,2),@Risultato INT =0,@GIOVANE INT,
			@TOT_SUP DECIMAL(18,2), @TotSupVitata decimal (10,2), @MQ_CONVERSIONE DECIMAL(18,2), @MQ_IMPIANTO DECIMAL(18,2)
			
	SET @ID_FASCICOLO =(SELECT ISNULL (ID_FASCICOLO,  (SELECT MAX(F.ID_FASCICOLO) AS Expr1  FROM IMPRESA 
								  INNER JOIN PROGETTO ON IMPRESA.ID_IMPRESA  = PROGETTO.ID_IMPRESA   				
								  INNER JOIN FASCICOLO_AZIENDALE AS F ON IMPRESA.ID_IMPRESA = F.ID_IMPRESA
								WHERE(PROGETTO.ID_PROGETTO = @IdProgetto))) 
						FROM PROGETTO WHERE ID_PROGETTO = @IdProgetto)

	IF (@ID_FASCICOLO IS NOT NULL)
	BEGIN
		SELECT @GIOVANE = COUNT(*) FROM PRIORITA_X_PROGETTO WHERE ID_PROGETTO =@IdProgetto AND ID_PRIORITA = 242		
			
		SELECT @TotSupVitata = ISNULL(SUM(SUPERFICIE_UTILIZZATA), 0) 
		FROM TERRITORIO T
			INNER JOIN UTILIZZO_TERRA UT ON UT.ID_TERRITORIO = T.ID_TERRITORIO 
		WHERE ID_FASCICOLO = @ID_FASCICOLO AND COD_MACROUSO  IN ('200','210') --NO UNA DA MENSA
		
		SELECT @SUP_PORT_NON_USATA = VALORE FROM PRIORITA_X_PROGETTO WHERE ID_PROGETTO =@IdProgetto AND ID_PRIORITA = 1219
		SELECT @SUP_PORT_USATA = VALORE FROM PRIORITA_X_PROGETTO WHERE ID_PROGETTO =@IdProgetto AND ID_PRIORITA = 1220 
	
		IF(@SUP_PORT_NON_USATA IS NULL OR @SUP_PORT_USATA IS NULL)SET @Risultato =0	
		ELSE BEGIN 
	 
			SET @TOT_SUP = @TotSupVitata + @SUP_PORT_NON_USATA + @SUP_PORT_USATA		
			IF(@TOT_SUP>=40000 OR (@TOT_SUP >=20000 AND @GIOVANE > 0) ) SET @Risultato =1
			ELSE BEGIN 
				-- sommo gli mq scritti in quantità dell'investimento 					
				SELECT @MQ_IMPIANTO=SUM(QUANTITA)
				FROM PIANO_INVESTIMENTI INV 
					INNER JOIN DETTAGLIO_INVESTIMENTI D ON D.ID_DETTAGLIO_INVESTIMENTO = INV.ID_DETTAGLIO_INVESTIMENTO AND D.ID_CODIFICA_INVESTIMENTO = INV.ID_CODIFICA_INVESTIMENTO AND COD_DETTAGLIO = 'AA'
				WHERE ID_PROGETTO = @IdProgetto AND   ((@FASE_ISTRUTTORIA=0 AND INV.ID_INVESTIMENTO_ORIGINALE IS NULL)OR(@FASE_ISTRUTTORIA=1 AND INV.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL)) 

		   		IF ((@TOT_SUP + ISNULL(@MQ_IMPIANTO ,0) )>=40000) SET @Risultato=1
		   		ELSE IF ((@TOT_SUP + ISNULL(@MQ_IMPIANTO ,0) )>=20000 AND @GIOVANE >0) SET @Risultato=1
		   			 ELSE SET @Risultato=0
			END
		END
	END
	ELSE SET @Risultato=0
	SELECT @Risultato AS PUNTEGGIO
	--return   @Risultato
END
