CREATE PROCEDURE [dbo].[calcoloStepVariante112_121_4]
@ID_VARIANTE int
AS

DECLARE @IdProgetto INT
/*SET @IdProgetto=336*/
-- 121 - verifica totale investimenti in domanda >= 25.000,00 € 

DECLARE @RESULT INT
SET @RESULT=1

SET @IdProgetto = (SELECT ID_PROGETTO FROM VARIANTI WHERE ID_VARIANTE = @ID_VARIANTE)


DECLARE @ID_PROG_CORRENTE_121 INT, @ID_BANDO_121 INT 

SELECT DISTINCT @ID_PROG_CORRENTE_121 = p.ID_PROGETTO, @ID_BANDO_121=P.ID_BANDO FROM PROGETTO P
		INNER JOIN BANDO B ON B.ID_BANDO = P.ID_BANDO INNER JOIN ZPROGRAMMAZIONE ZP ON ZP.ID =B.ID_PROGRAMMAZIONE AND CODICE = '1.2.1.'
WHERE ID_PROG_INTEGRATO = @IdProgetto
 
DECLARE @TOTALE int

SET @TOTALE  = (SELECT SUM(COSTO_INVESTIMENTO) FROM PIANO_INVESTIMENTI P
			     WHERE  P.ID_VARIANTE = @ID_VARIANTE   AND    isnull(COD_VARIAZIONE,'x')!='A' 
				AND COD_TIPO_INVESTIMENTO = 1 AND P.ID_PROGETTO=@ID_PROG_CORRENTE_121)

IF (@TOTALE IS NULL OR @TOTALE < 25000) SET @RESULT=0

select @RESULT
