CREATE  PROCEDURE [dbo].[calcoloStepPagamento_A_121_1]
@IdProgetto int,
@IdDomandaPagamento int =NULL
AS
BEGIN

--ANTICIPO
--Certificato Antimafia BANDO 121  
-- Verifica presenza Certificato CCIAA valido con dicitura Antimafia - Antimafia Prefettura (per progetti > 154.937,07)
--DECLARE @IdProgetto int,@IdDomandaPagamento int
--SET @IdProgetto =1434
--SET @IdDomandaPagamento=1815
 


DECLARE	@RESULT INT, @ID_IMPRESA INT, @DATA_FINE_ISTRUTTORIA DATETIME, @CONTRIBUTO_PROGETTO DECIMAL(16,2), @ID_VARIANTE INT
			--@ID_VARIANTE int, 
			--@CONTRIBUTO_PROGETTO decimal(10,2),
			--@DATA_CERTIFICAZIONE_ANTIMAFIA DATETIME, @CONTRIBUTO_PROGETTO_FINANZIATO decimal(10,2) 

 
 -- IMPONGO LO STEP NON VERIFICATO	
SET @RESULT = 0

--SELECT @DATA_CERTIFICAZIONE_ANTIMAFIA = DATA_CERTIFICAZIONE_ANTIMAFIA, @DATA_FINE_ISTRUTTORIA = ISNULL(DATA_APPROVAZIONE,GETDATE())  FROM DOMANDA_DI_PAGAMENTO WHERE ID_DOMANDA_PAGAMENTO = @IdDomandaPagamento  
--SELECT @CONTRIBUTO_PROGETTO_FINANZIATO= CONTRIBUTO_TOTALE FROM GRADUATORIA_PROGETTI GP WHERE ID_PROGETTO= @IdProgetto
--IF( @DATA_CERTIFICAZIONE_ANTIMAFIA IS NULL )
--	BEGIN 
--			SET @ID_VARIANTE =  (SELECT MAX(ID_VARIANTE) FROM VARIANTI WHERE ID_PROGETTO = @IdProgetto AND APPROVATA =1 AND ANNULLATA =0)
--			SET @CONTRIBUTO_PROGETTO = ISNULL((SELECT dbo.[calcoloContributoTotaleProgetto] (@IdProgetto, 1, @ID_VARIANTE)), 0)
--			IF(@CONTRIBUTO_PROGETTO_FINANZIATO <@CONTRIBUTO_PROGETTO) SET @CONTRIBUTO_PROGETTO=@CONTRIBUTO_PROGETTO_FINANZIATO
--			IF (@CONTRIBUTO_PROGETTO <= 154937.07 )
--					SET @RESULT =1
--	END
--ELSE 
--BEGIN
--	IF( DATEDIFF( day,  DATEADD (month, 6 , @DATA_CERTIFICAZIONE_ANTIMAFIA ), @DATA_FINE_ISTRUTTORIA ) <= 0 )	
-- 	 SET @RESULT=1
--	END

 -- modifica del 04-04-2013: controllo antimafia sotto i 150000 €  
SELECT @DATA_FINE_ISTRUTTORIA = ISNULL(DATA_APPROVAZIONE,GETDATE())  FROM DOMANDA_DI_PAGAMENTO WHERE ID_DOMANDA_PAGAMENTO = @IdDomandaPagamento  
SELECT @ID_IMPRESA = ID_IMPRESA FROM PROGETTO P   WHERE ID_PROGETTO = @IdProgetto
SELECT @ID_VARIANTE=MAX(ID_VARIANTE) FROM VARIANTI WHERE ID_PROGETTO=@IdProgetto AND APPROVATA=1 AND ANNULLATA=0 AND DATA_MODIFICA<=@DATA_FINE_ISTRUTTORIA
SET @CONTRIBUTO_PROGETTO =  (SELECT  ISNULL( dbo.[calcoloContributoTotaleProgetto] (@IdProgetto, 1, @ID_VARIANTE),0) +  ISNULL(dbo.[calcoloPremioContoCapitale] (@IdProgetto, 1, @ID_VARIANTE ) ,0))
IF( @CONTRIBUTO_PROGETTO > (SELECT SUM(CONTRIBUTO_DI_MISURA) AS CONTRIBUTO_DI_MISURA FROM GRADUATORIA_PROGETTI_FINANZIABILITA GPF WHERE ID_PROG_INTEGRATO = @IdProgetto))
	SET @CONTRIBUTO_PROGETTO = (SELECT SUM(CONTRIBUTO_DI_MISURA) AS CONTRIBUTO_DI_MISURA FROM GRADUATORIA_PROGETTI_FINANZIABILITA GPF WHERE ID_PROG_INTEGRATO = @IdProgetto)
--SELECT @CONTRIBUTO_PROGETTO
--SELECT  ISNULL( dbo.[calcoloContributoTotaleProgetto] (@IdProgetto, 1, @ID_VARIANTE),0) +  ISNULL(dbo.[calcoloPremioContoCapitale] (@IdProgetto, 1, @ID_VARIANTE ) ,0)
IF (@CONTRIBUTO_PROGETTO <=  150000 )
	SET @RESULT =1
	ELSE EXEC @RESULT = SpControlloAntimafia @ID_IMPRESA, @DATA_FINE_ISTRUTTORIA
SELECT @RESULT
  
END
