CREATE    PROCEDURE [dbo].[calcoloStep111_7 ]
@IdProgetto int,
@FASE_ISTRUTTORIA INT  = 0
AS
BEGIN

-- OBIETTIVO Offerta formativa (azione B - Altra Formazione) --- ID_PRIORITA= 286

DECLARE @Result int, 
					@CODICE CHAR(2) , 
					@COSTO DECIMAL (18,2)

SET @Result = 1 -- Impongo lo Step verificato
--------------------------------------------------------------------------------------------------------------
    
DECLARE @COUNT_C INT, @COUNT_ATT INT
SET @COUNT_C = (SELECT COUNT(*) FROM  (SELECT     PI.ID_CODIFICA_INVESTIMENTO--, VP.ID_VALORE, VP.ID_PRIORITA
										FROM         PIANO_INVESTIMENTI AS PI LEFT OUTER JOIN
															  PRIORITA_X_INVESTIMENTI AS PXI ON PI.ID_INVESTIMENTO = PXI.ID_INVESTIMENTO AND PXI.ID_PRIORITA = 286 
										   left  JOIN  VALORI_PRIORITA AS VP ON VP.ID_VALORE = PXI.ID_VALORE
										WHERE     (PI.ID_PROGETTO = @IdProgetto) AND(( ID_INVESTIMENTO_ORIGINALE IS NULL AND @FASE_ISTRUTTORIA =0  ) OR ( ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND @FASE_ISTRUTTORIA =1 )  )
										group by ID_CODIFICA_INVESTIMENTO)AS C
									 )
 
SET @COUNT_ATT  = ( SELECT COUNT(*) FROM  (SELECT    VP.ID_VALORE--, VP.ID_PRIORITA
											FROM         PIANO_INVESTIMENTI AS PI LEFT OUTER JOIN
																PRIORITA_X_INVESTIMENTI AS PXI ON PI.ID_INVESTIMENTO = PXI.ID_INVESTIMENTO AND  PXI.ID_PRIORITA = 286  LEFT  JOIN 
																VALORI_PRIORITA AS VP ON VP.ID_VALORE = PXI.ID_VALORE
											WHERE     (PI.ID_PROGETTO = @IdProgetto) AND (( ID_INVESTIMENTO_ORIGINALE IS NULL AND @FASE_ISTRUTTORIA =0  ) OR ( ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND @FASE_ISTRUTTORIA =1 )  )
																 AND  VP.ID_VALORE IS NULL
											GROUP  BY  VP.ID_VALORE)AS C )
 

IF(@COUNT_ATT>0   OR   @COUNT_C >1 ) SET @Result =0
 
SELECT @Result AS RESULT


END
