CREATE  PROCEDURE [dbo].[calcoloStep313c_PR_PU]
@IdProgetto int, 
@FASE_ISTRUTTORIA INT =0
AS
BEGIN

DECLARE @result int,@COUNT int, @SCARTO int

--- Costo singolo guida <= 3.000€
--- ID PRIORITA 1077 A LIVELLO DI INVESTIMENTO CHE PERMETTERE L'INSERIMENTO DEL NUMERO UNIVOCO CHE IDENTIFICA LA GUIDA
--- 

SET @result = 0 -- LO PONGO NON VERIFICATO 

SET @SCARTO  = (SELECT((SELECT COUNT(*) AS A FROM PIANO_INVESTIMENTI PI
					WHERE PI.ID_PROGETTO = @IdProgetto AND PI.COD_TIPO_INVESTIMENTO = 1 AND
					((@FASE_ISTRUTTORIA=0 AND PI.ID_INVESTIMENTO_ORIGINALE IS NULL AND ID_VARIANTE IS NULL) OR (@FASE_ISTRUTTORIA=1 AND PI.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL)))
					-
					(SELECT COUNT(*)  FROM  PIANO_INVESTIMENTI AS PI INNER JOIN PRIORITA_X_INVESTIMENTI PXI ON PI.ID_INVESTIMENTO = PXI.ID_INVESTIMENTO 
					 WHERE PI.ID_PROGETTO = @IdProgetto AND PI.COD_TIPO_INVESTIMENTO = 1 AND PXI.ID_PRIORITA = 1077 AND 
					((@FASE_ISTRUTTORIA=0 AND PI.ID_INVESTIMENTO_ORIGINALE IS NULL AND ID_VARIANTE IS NULL) OR (@FASE_ISTRUTTORIA=1 AND PI.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL))
					)))

SELECT @COUNT = COUNT(*) FROM PROGETTO P INNER JOIN VPIANO_INVESTIMENTI I ON P.ID_PROGETTO=I.ID_PROGETTO 
						INNER JOIN PRIORITA_X_INVESTIMENTI PXI ON PXI.ID_INVESTIMENTO = I.ID_INVESTIMENTO
					WHERE 
					((@FASE_ISTRUTTORIA=0 AND I.ID_INVESTIMENTO_ORIGINALE IS NULL AND ID_VARIANTE IS NULL) OR (@FASE_ISTRUTTORIA=1 AND I.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL)) AND
					I.COD_TIPO_INVESTIMENTO = 1 AND P.ID_PROGETTO=@IdProgetto AND PXI.ID_PRIORITA = 1077
					GROUP BY PXI.VALORE
					HAVING ISNULL(SUM(CONTRIBUTO_RICHIESTO),0) > 3000

IF ((ISNULL(@COUNT,0) = 0 ) AND (ISNULL(@SCARTO,0) = 0)) SET @result = 1
SELECT @result AS RESULT
END
