-- SALDO  221 
-- Spese di sistemazione terreno <= 10% delle spese di impianto per tipologia di impianto
-- controllo in PRESENTAZIONE SALDO

CREATE  PROCEDURE [dbo].[calcoloRequisitoPagamento221_1]
@ID_DOMANDA_PAGAMENTO int
AS
BEGIN

-- DECLARE  @ID_DOMANDA_PAGAMENTO int
--SET  @ID_DOMANDA_PAGAMENTO = 626
DECLARE @ID_PROGETTO INT , @IMPORTO_A1 DECIMAL (18,2) ,@IMPORTO_A2 DECIMAL (18,2) ,@IMPORTO_A3 DECIMAL (18,2) , @ANNO INT, @IMPORTO_TOTALE  DECIMAL (18,2),@DATA_ULTIMA_MODIFICA DATETIME
DECLARE @RESULT INT

SET @IMPORTO_A1 = 0 -- INIZIALIZZO LA VARIABILE		
SET @IMPORTO_A2 = 0 -- INIZIALIZZO LA VARIABILE		
SET @IMPORTO_A3 = 0 -- INIZIALIZZO LA VARIABILE

SET @RESULT = 0  -- IMPONGO LO STEP NON  VERIFICATO		 
SELECT @ID_PROGETTO =ID_PROGETTO, @DATA_ULTIMA_MODIFICA=DATA_MODIFICA FROM DOMANDA_DI_PAGAMENTO WHERE ID_DOMANDA_PAGAMENTO=@ID_DOMANDA_PAGAMENTO
SET @ANNO =DATEPART(YEAR,@DATA_ULTIMA_MODIFICA)-1

SET @IMPORTO_A1= (((SELECT SUM( ISNULL(IMPORTO_AMMESSO, PR.IMPORTO_RICHIESTO) )
						 FROM vPIANO_INVESTIMENTI  PI inner join PAGAMENTI_RICHIESTI  PR  ON PI.ID_INVESTIMENTO = PR.ID_INVESTIMENTO 
						 WHERE ID_PROGETTO = @ID_PROGETTO AND ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO
							AND PI.COD_TIPO_INVESTIMENTO = 1  AND 
							PI.COD_SPECIFICA in ('4') 
							AND PI.ID_DETTAGLIO_INVESTIMENTO IN (SELECT ID_DETTAGLIO_INVESTIMENTO FROM CODIFICA_INVESTIMENTO CI INNER JOIN DETTAGLIO_INVESTIMENTI DI ON 
																(CI.ID_CODIFICA_INVESTIMENTO = DI.ID_CODIFICA_INVESTIMENTO) WHERE CI.ID_BANDO = 
																(SELECT ID_BANDO FROM PROGETTO WHERE ID_PROGETTO = @ID_PROGETTO) AND DI.COD_DETTAGLIO = 'a1'))* 100)
						/ --- divido
						(SELECT SUM( ISNULL(IMPORTO_AMMESSO, PR.IMPORTO_RICHIESTO) )
						 FROM vPIANO_INVESTIMENTI  PI inner join PAGAMENTI_RICHIESTI  PR  ON PI.ID_INVESTIMENTO = PR.ID_INVESTIMENTO 
						 WHERE ID_PROGETTO = @ID_PROGETTO AND ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO
							AND PI.COD_TIPO_INVESTIMENTO = 1  AND 
							PI.COD_SPECIFICA in ('1','2','3') 
							AND PI.ID_DETTAGLIO_INVESTIMENTO IN (SELECT ID_DETTAGLIO_INVESTIMENTO FROM CODIFICA_INVESTIMENTO CI INNER JOIN DETTAGLIO_INVESTIMENTI DI ON 
																(CI.ID_CODIFICA_INVESTIMENTO = DI.ID_CODIFICA_INVESTIMENTO) WHERE CI.ID_BANDO = 
																(SELECT ID_BANDO FROM PROGETTO WHERE ID_PROGETTO = @ID_PROGETTO) AND DI.COD_DETTAGLIO = 'a1')))

SET @IMPORTO_A2= (((SELECT SUM( ISNULL(IMPORTO_AMMESSO, PR.IMPORTO_RICHIESTO) )
						 FROM vPIANO_INVESTIMENTI  PI inner join PAGAMENTI_RICHIESTI  PR  ON PI.ID_INVESTIMENTO = PR.ID_INVESTIMENTO 
						 WHERE ID_PROGETTO = @ID_PROGETTO AND ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO
							AND PI.COD_TIPO_INVESTIMENTO = 1  AND 
							PI.COD_SPECIFICA in ('4') 
							AND PI.ID_DETTAGLIO_INVESTIMENTO IN (SELECT ID_DETTAGLIO_INVESTIMENTO FROM CODIFICA_INVESTIMENTO CI INNER JOIN DETTAGLIO_INVESTIMENTI DI ON 
																(CI.ID_CODIFICA_INVESTIMENTO = DI.ID_CODIFICA_INVESTIMENTO) WHERE CI.ID_BANDO = 
																(SELECT ID_BANDO FROM PROGETTO WHERE ID_PROGETTO = @ID_PROGETTO) AND DI.COD_DETTAGLIO = 'a2'))* 100)
						/ --- divido
						(SELECT SUM( ISNULL(IMPORTO_AMMESSO, PR.IMPORTO_RICHIESTO) )
						 FROM vPIANO_INVESTIMENTI  PI inner join PAGAMENTI_RICHIESTI  PR  ON PI.ID_INVESTIMENTO = PR.ID_INVESTIMENTO 
						 WHERE ID_PROGETTO = @ID_PROGETTO AND ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO
							AND PI.COD_TIPO_INVESTIMENTO = 1  AND 
							PI.COD_SPECIFICA in ('1','2','3') 
							AND PI.ID_DETTAGLIO_INVESTIMENTO IN (SELECT ID_DETTAGLIO_INVESTIMENTO FROM CODIFICA_INVESTIMENTO CI INNER JOIN DETTAGLIO_INVESTIMENTI DI ON 
																(CI.ID_CODIFICA_INVESTIMENTO = DI.ID_CODIFICA_INVESTIMENTO) WHERE CI.ID_BANDO = 
																(SELECT ID_BANDO FROM PROGETTO WHERE ID_PROGETTO = @ID_PROGETTO) AND DI.COD_DETTAGLIO = 'a2')))	
SET @IMPORTO_A3= (((SELECT SUM( ISNULL(IMPORTO_AMMESSO, PR.IMPORTO_RICHIESTO) )
						 FROM vPIANO_INVESTIMENTI  PI inner join PAGAMENTI_RICHIESTI  PR  ON PI.ID_INVESTIMENTO = PR.ID_INVESTIMENTO 
						 WHERE ID_PROGETTO = @ID_PROGETTO AND ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO
							AND PI.COD_TIPO_INVESTIMENTO = 1  AND 
							PI.COD_SPECIFICA in ('4') 
							AND PI.ID_DETTAGLIO_INVESTIMENTO IN (SELECT ID_DETTAGLIO_INVESTIMENTO FROM CODIFICA_INVESTIMENTO CI INNER JOIN DETTAGLIO_INVESTIMENTI DI ON 
																(CI.ID_CODIFICA_INVESTIMENTO = DI.ID_CODIFICA_INVESTIMENTO) WHERE CI.ID_BANDO = 
																(SELECT ID_BANDO FROM PROGETTO WHERE ID_PROGETTO = @ID_PROGETTO) AND DI.COD_DETTAGLIO = 'a3'))* 100)
						/ --- divido
						(SELECT SUM( ISNULL(IMPORTO_AMMESSO, PR.IMPORTO_RICHIESTO) )
						 FROM vPIANO_INVESTIMENTI  PI inner join PAGAMENTI_RICHIESTI  PR  ON PI.ID_INVESTIMENTO = PR.ID_INVESTIMENTO 
						 WHERE ID_PROGETTO = @ID_PROGETTO AND ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO
							AND PI.COD_TIPO_INVESTIMENTO = 1  AND 
							PI.COD_SPECIFICA in ('1','2','3') 
							AND PI.ID_DETTAGLIO_INVESTIMENTO IN (SELECT ID_DETTAGLIO_INVESTIMENTO FROM CODIFICA_INVESTIMENTO CI INNER JOIN DETTAGLIO_INVESTIMENTI DI ON 
																(CI.ID_CODIFICA_INVESTIMENTO = DI.ID_CODIFICA_INVESTIMENTO) WHERE CI.ID_BANDO = 
																(SELECT ID_BANDO FROM PROGETTO WHERE ID_PROGETTO = @ID_PROGETTO) AND DI.COD_DETTAGLIO = 'a3')))																									

IF(ISNULL(@IMPORTO_A1,0) <= 10 AND ISNULL(@IMPORTO_A2,0) <=10 AND ISNULL(@IMPORTO_A3,0) <=10) SET @RESULT=1
SELECT @RESULT
END
