CREATE  PROCEDURE [dbo].[calcoloRequisitoPagamento221_4]
@ID_DOMANDA_PAGAMENTO int
AS
BEGIN

-- DECLARE @ID_DOMANDA_PAGAMENTO int
-- SET @ID_DOMANDA_PAGAMENTO = 174
DECLARE @ID_PROGETTO INT, 
					@RESULT INT,
					@DIFFERENZA INT
					
SELECT @DIFFERENZA = DATEDIFF(DAY, DATEADD(DD,120,(select VAL_DATA from DOMANDA_PAGAMENTO_REQUISITI where 
														ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO  and ID_REQUISITO = 171)
												 ) , (select VAL_DATA from DOMANDA_PAGAMENTO_REQUISITI where
												        ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO  and ID_REQUISITO = 170))

IF (@DIFFERENZA <= 0) SET @RESULT = 1 	
	 ELSE SET @RESULT = 0 	

SELECT @RESULT
END
