--- Si impegna alla realizzazione di studi e ricerche originali in presenza di interventi di tipo A)
--- GAL FLAMINIA CESANO

CREATE PROCEDURE [dbo].[calcoloStepVariante4135_B254]
@ID_VARIANTE int
AS
BEGIN

DECLARE @result int, @A int, @B int, @COSTOA int
SET @result = 0

SELECT @A = (SELECT COUNT(I.ID_INVESTIMENTO) FROM PROGETTO P  INNER JOIN VPIANO_INVESTIMENTI I ON (P.ID_PROGETTO=I.ID_PROGETTO) WHERE
			  I.ID_VARIANTE = @ID_VARIANTE AND isnull(COD_VARIAZIONE,'x') != 'A' AND
		     I.CODICE = 'A') 
			
SELECT @B = (SELECT COUNT(I.ID_INVESTIMENTO) FROM PROGETTO P  INNER JOIN VPIANO_INVESTIMENTI I ON (P.ID_PROGETTO=I.ID_PROGETTO) WHERE
			 I.ID_VARIANTE = @ID_VARIANTE AND isnull(COD_VARIAZIONE,'x') != 'A' AND
			 I.CODICE = 'B') 			 

SELECT @COSTOA = (SELECT ISNULL(SUM(ISNULL(COSTO_INVESTIMENTO,0)) , 0) + ISNULL(SUM(SPESE_GENERALI),0) AS Totale_Investimenti FROM PROGETTO P   INNER JOIN vPIANO_INVESTIMENTI I ON (P.ID_PROGETTO=I.ID_PROGETTO) WHERE  
				  I.ID_VARIANTE = @ID_VARIANTE AND isnull(COD_VARIAZIONE,'x') != 'A' AND 
				  I.CODICE = 'A')

IF (((ISNULL(@A,0) >= 1 AND @B >= 1) OR ((@A IS NULL OR @A = 0) AND @B >= 1)) AND (@COSTOA <= 5000)) SET @result = 1
	ELSE SET @result = 0

SELECT @result AS RESULT
END
