CREATE PROCEDURE [dbo].[calcoloStepVariante123_3]
@ID_VARIANTE int  
AS
BEGIN

-- 123 a) verifica sostenibilità economica investimento: (tot. FISSI/30 + tot. MOBILI/10) < 15% Fatturato ex-post

DECLARE @result int, @COUNT_BILANCI INT, @ID_PROGETTO INT,
  @Rata  decimal(15,2),  @PLV_RICAVI_VENDITA decimal(15,2)


SET @Rata = (SELECT ISNULL(SUM((CASE I.MOBILE
								 WHEN 1 THEN   (I.COSTO_INVESTIMENTO + I.SPESE_GENERALI)  / 10 
								 WHEN 0 THEN (I.COSTO_INVESTIMENTO + I.SPESE_GENERALI)  / 30
								 ELSE (I.COSTO_INVESTIMENTO + I.SPESE_GENERALI)  / 30
								 END)) , 0)
							FROM PROGETTO P INNER JOIN VPIANO_INVESTIMENTI I ON (P.ID_PROGETTO=I.ID_PROGETTO)
							WHERE  ID_VARIANTE = @ID_VARIANTE AND I.COD_TIPO_INVESTIMENTO = 1  
                        )	

SET @ID_PROGETTO = (SELECT ID_PROGETTO FROM VARIANTI WHERE ID_VARIANTE = @ID_VARIANTE)

SET @PLV_RICAVI_VENDITA= (SELECT   ISNULL(SUM(PLV_RICAVI_VENDITA),0)/COUNT(*) AS RICAVI FROM BILANCIO_INDUSTRIALE WHERE PREVISIONALE = 1 AND ID_PROGETTO = @ID_PROGETTO )

IF (@Rata < (@PLV_RICAVI_VENDITA * 0.15)) SET @result = 1
ELSE SET @result = 0

SELECT @result AS RESULT

END
