CREATE PROCEDURE [dbo].[calcoloPrioritaVariante311_B_3]
(
 @ID_VARIANTE int
)
AS
BEGIN

-- 148 -  MATERIA PRIMA PROVENIENTE DA BACINO BIETICOLO

DECLARE @CONTRIBUTO decimal(10,2)
DECLARE @Investimenti decimal(10,2)
DECLARE @ID_SPECIFICA_INVESTIMENTO int 
DECLARE @ID_CODIFICA_INVESTIMENTO INT
DECLARE @IdProgetto int 
SET @IdProgetto= (select id_progetto from varianti where id_variante= @ID_VARIANTE)

DECLARE CONTRIBUTO CURSOR FOR
	SELECT       SUM(PIANO_INVESTIMENTI.CONTRIBUTO_RICHIESTO )  , PIANO_INVESTIMENTI.ID_CODIFICA_INVESTIMENTO
	FROM         PIANO_INVESTIMENTI  
	WHERE     (PIANO_INVESTIMENTI.ID_PROGETTO = @IdProgetto  AND ID_CODIFICA_INVESTIMENTO IS NOT NULL 
				AND  PIANO_INVESTIMENTI.ID_VARIANTE = @ID_VARIANTE   AND isnull(COD_VARIAZIONE,'x')!='A' )
	group by  PIANO_INVESTIMENTI.ID_CODIFICA_INVESTIMENTO 
	ORDER BY    SUM(PIANO_INVESTIMENTI.CONTRIBUTO_RICHIESTO ) desc

OPEN CONTRIBUTO
FETCH NEXT FROM CONTRIBUTO INTO @CONTRIBUTO, @ID_CODIFICA_INVESTIMENTO
CLOSE CONTRIBUTO
DEALLOCATE CONTRIBUTO

DECLARE @Punteggio decimal (10,2)
SET @Punteggio= (SELECT  top (1)   VALORI_PRIORITA.PUNTEGGIO FROM PRIORITA_X_INVESTIMENTI INNER JOIN
                      VALORI_PRIORITA ON PRIORITA_X_INVESTIMENTI.ID_VALORE = VALORI_PRIORITA.ID_VALORE INNER JOIN
                      PIANO_INVESTIMENTI ON PRIORITA_X_INVESTIMENTI.ID_INVESTIMENTO = PIANO_INVESTIMENTI.ID_INVESTIMENTO
						WHERE PIANO_INVESTIMENTI.ID_PROGETTO = @IdProgetto AND
					 PIANO_INVESTIMENTI.ID_CODIFICA_INVESTIMENTO =@ID_CODIFICA_INVESTIMENTO AND PRIORITA_X_INVESTIMENTI.ID_PRIORITA = 148  and
 PIANO_INVESTIMENTI.ID_VARIANTE = @ID_VARIANTE   AND isnull(COD_VARIAZIONE,'x')!='A'  )

 SELECT @Punteggio AS PUNTEGGIO
 RETURN (@Punteggio * 100)
END
