--Investimenti completi di indicazione dell`annualità di PROGETTO e di REALIZZAZIONE

CREATE   PROCEDURE [dbo].[calcoloStepVariante133_7]
@ID_VARIANTE int
AS
 
BEGIN
 

--declare @IdProgetto int,
-- @FASE_ISTRUTTORIA INT  
--
--set @IdProgetto=7343
--set @FASE_ISTRUTTORIA=0

DECLARE @NUM_INVESTIMENTI INT,@NUM_ANNO INT,@NUM_REALIZZAZIONE INT ,@RESULT INT =1, @COUNT_ANNO_R INT

SELECT @NUM_INVESTIMENTI = COUNT(*) FROM PIANO_INVESTIMENTI PI  
WHERE ID_VARIANTE = @ID_VARIANTE AND COD_TIPO_INVESTIMENTO = 1 AND isnull(COD_VARIAZIONE,'x')!='A'

SELECT @NUM_REALIZZAZIONE= COUNT(*) FROM  PIANO_INVESTIMENTI AS PI 
	INNER JOIN PRIORITA_X_INVESTIMENTI ON PI.ID_INVESTIMENTO = PRIORITA_X_INVESTIMENTI.ID_INVESTIMENTO 
WHERE  ID_PRIORITA = 768 AND ID_VARIANTE = @ID_VARIANTE AND COD_TIPO_INVESTIMENTO = 1 AND isnull(COD_VARIAZIONE,'x')!='A'

SELECT @COUNT_ANNO_R=COUNT(*) FROM (
			SELECT COUNT(*) AS TIPO_NUM FROM PIANO_INVESTIMENTI AS PI 
				INNER JOIN PRIORITA_X_INVESTIMENTI ON PI.ID_INVESTIMENTO = PRIORITA_X_INVESTIMENTI.ID_INVESTIMENTO 
			WHERE  ID_PRIORITA = 768 AND ID_VARIANTE = @ID_VARIANTE AND COD_TIPO_INVESTIMENTO = 1 AND isnull(COD_VARIAZIONE,'x')!='A'				 
			GROUP BY ID_VALORE )AS T

IF(@NUM_INVESTIMENTI!=@NUM_REALIZZAZIONE OR @COUNT_ANNO_R > 1) SET @RESULT =0
ELSE BEGIN
		SELECT @NUM_ANNO = COUNT(*) FROM  PIANO_INVESTIMENTI AS PI 
				INNER JOIN PRIORITA_X_INVESTIMENTI ON PI.ID_INVESTIMENTO = PRIORITA_X_INVESTIMENTI.ID_INVESTIMENTO 
		WHERE  ID_PRIORITA = 404 AND ID_VARIANTE = @ID_VARIANTE AND COD_TIPO_INVESTIMENTO = 1 AND isnull(COD_VARIAZIONE,'x')!='A'
				 
		IF(@NUM_INVESTIMENTI!=@NUM_ANNO) SET @RESULT =0
	 END 
 SELECT @RESULT
END
