CREATE PROCEDURE [dbo].[calcoloStep112_311_1]
@IdProgetto int
AS
-- CONTROLLO SU DICHIARAZIONI FACOLTATIVE MISURA 311

/*

DECLARE @IdProgetto INT
SET @IdProgetto=375
*/
DECLARE @RESULT INT

DECLARE  @ID_BANDO_311 INT,   @ID_PROG_INTEG_311 INT 
	
 
SELECT DISTINCT @ID_PROG_INTEG_311 = p.ID_PROGETTO , @ID_BANDO_311= P.ID_BANDO FROM PROGETTO P
	INNER JOIN BANDO B ON B.ID_BANDO = P.ID_BANDO INNER JOIN ZPROGRAMMAZIONE ZP ON ZP.ID =B.ID_PROGRAMMAZIONE AND CODICE = '3.1.1.A'
WHERE ID_PROG_INTEGRATO = @IdProgetto
 

IF @ID_PROG_INTEG_311 IS NULL SET @RESULT=4
ELSE BEGIN
	DECLARE @NUMERO_INVESTIMENTI INT
	SET @NUMERO_INVESTIMENTI =(SELECT COUNT(*) FROM PIANO_INVESTIMENTI 
								WHERE ID_PROGETTO=@ID_PROG_INTEG_311 AND ID_INVESTIMENTO_ORIGINALE IS NULL AND COSTO_INVESTIMENTO >0)
	IF @NUMERO_INVESTIMENTI =0 SET @RESULT=4
	ELSE BEGIN
		SET @RESULT=(SELECT COUNT(*) FROM DICHIARAZIONI_X_PROGETTO WHERE ID_PROGETTO=@IdProgetto AND ID_DICHIARAZIONE IN (16,20,21,91))
	END
END
SELECT @RESULT
