CREATE PROCEDURE [dbo].[calcoloSpeseBrevetti]
(
	@ID_PROGETTO INT, --ID DEL PROGETTO O DEL PROGETTO INTEGRATO
	@FASE_ISTRUTTORIA BIT =0 --SE FASE ISTRUTTORIA TRUE, ALTRIMENTI DEVO CALCOLARE PER GLI INVESTIMENTI ORIGINALI
)
AS
/*
declare @ID_PROGETTO INT
declare	@FASE_ISTRUTTORIA BIT 
set @id_progetto=118
set @fase_istruttoria=1*/

-- RECUPERO I DATI DEI BREVETTI/LICENZE
DECLARE @MAX_AIUTO DECIMAL(15,2)
DECLARE @MIN_AIUTO DECIMAL(15,2)
DECLARE @MAX_QUOTA DECIMAL(15,2)
DECLARE @COD_AIUTO INT

DECLARE TAIUTO CURSOR FOR (
SELECT COD_TIPO_INVESTIMENTO,ISNULL(IMPORTO_MIN,0),ISNULL(IMPORTO_MAX,1000000000),ISNULL(QUOTA_MAX,100) FROM PROGETTO AS P 
INNER JOIN BANDO_TIPO_INVESTIMENTI AS B ON P.ID_BANDO=B.ID_BANDO AND COD_TIPO_INVESTIMENTO=5
WHERE P.ID_PROGETTO=@ID_PROGETTO)

OPEN TAIUTO
FETCH NEXT FROM TAIUTO 
INTO @COD_AIUTO,@MIN_AIUTO,@MAX_AIUTO,@MAX_QUOTA
CLOSE TAIUTO
DEALLOCATE TAIUTO
----------------------------------------------

IF @COD_AIUTO IS NULL RAISERROR('TIPOLOGIA DI INVESTIMENTO "BREVETTI LICENZE" NON ASSOCIATA AL BANDO',13,1)
ELSE
BEGIN
	--COSTO TOTALE DEGLI INVESTIMENTI
	DECLARE @COSTO_TOTALE DECIMAL(18,2)
	DECLARE @SPESE_TOTALI DECIMAL(18,2)
	DECLARE TOTALE CURSOR FOR
	(SELECT SUM(COSTO_INVESTIMENTO) AS COSTO_TOTALE,
			CAST(SUM((CONTRIBUTO_RICHIESTO/QUOTA_CONTRIBUTO_RICHIESTO*100)- COSTO_INVESTIMENTO) AS DECIMAL(18,2)) AS SPESE_TECNICHE
		FROM PIANO_INVESTIMENTI 
		WHERE ID_PROGETTO=@ID_PROGETTO AND COD_TIPO_INVESTIMENTO =1	
		AND ((@FASE_ISTRUTTORIA=0 AND ID_INVESTIMENTO_ORIGINALE IS NULL) OR (@FASE_ISTRUTTORIA=1 AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL)))
	OPEN TOTALE
	FETCH NEXT FROM TOTALE 
	INTO @COSTO_TOTALE,@SPESE_TOTALI
	CLOSE TOTALE
	DEALLOCATE TOTALE
	---------------------------------------------

   	--COSTO TOTALE DEI BREVETTI
	DECLARE @COSTO_BREVETTI DECIMAL(18,2)
	DECLARE TOTALE CURSOR FOR
	(SELECT SUM(COSTO_INVESTIMENTO) AS COSTO_BREVETTI
		FROM PIANO_INVESTIMENTI 
		WHERE ID_PROGETTO=@ID_PROGETTO AND COD_TIPO_INVESTIMENTO =5	
		AND ((@FASE_ISTRUTTORIA=0 AND ID_INVESTIMENTO_ORIGINALE IS NULL) OR (@FASE_ISTRUTTORIA=1 AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL)))
	OPEN TOTALE
	FETCH NEXT FROM TOTALE 
	INTO @COSTO_BREVETTI
	CLOSE TOTALE
	DEALLOCATE TOTALE
	---------------------------------------------
	--COSTO TOTALE polizza
	DECLARE @COSTO_POLIZZA DECIMAL(18,2)
	DECLARE TOTALE CURSOR FOR
	(SELECT SUM(COSTO_INVESTIMENTO) AS COSTO_POLIZZA
		FROM PIANO_INVESTIMENTI 
		WHERE ID_PROGETTO=@ID_PROGETTO AND COD_TIPO_INVESTIMENTO =4	
		AND ((@FASE_ISTRUTTORIA=0 AND ID_INVESTIMENTO_ORIGINALE IS NULL) OR (@FASE_ISTRUTTORIA=1 AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL)))
	OPEN TOTALE
	FETCH NEXT FROM TOTALE 
	INTO @COSTO_POLIZZA
	CLOSE TOTALE
	DEALLOCATE TOTALE
	---------------------------------------------

	--PERCENTUALE MAX SPESE GENERALI 
	DECLARE @MAX_SPESE_GENERALI DECIMAL(18,2)
	DECLARE TAIUTO CURSOR FOR (
	SELECT ISNULL(QUOTA_MAX,100) FROM PROGETTO AS P INNER JOIN BANDO_TIPO_INVESTIMENTI AS B 
	ON P.ID_BANDO=B.ID_BANDO AND COD_TIPO_INVESTIMENTO=6 WHERE P.ID_PROGETTO=@ID_PROGETTO)
	OPEN TAIUTO
	FETCH NEXT FROM TAIUTO 
	INTO @MAX_SPESE_GENERALI
	CLOSE TAIUTO
	DEALLOCATE TAIUTO
	---------------------------------------------	
	
	DECLARE @AMMONTARE_BREVETTI DECIMAL(18,2)
	DECLARE @RESTO DECIMAL(18,2)
	SET @AMMONTARE_BREVETTI=@COSTO_TOTALE/100*@MAX_QUOTA-ISNULL(@COSTO_BREVETTI,0) --% SU COSTO TOTALE INVESTIMENTI

	IF(@MAX_SPESE_GENERALI IS NOT NULL)BEGIN
		--RIMANENTE DEI SOLDI CHE POSSONO ESSERE ATTRIBUITI ALLE SPESE DEL BREVETTO
		SET @RESTO=@COSTO_TOTALE/100*@MAX_SPESE_GENERALI-@SPESE_TOTALI-ISNULL(@COSTO_POLIZZA,0)
		IF(@RESTO>0)BEGIN

			SET @RESTO=@RESTO-@AMMONTARE_BREVETTI --SE L'AMMONTARE BREVETTI NON RIENTRA TUTTA NEL RESTO 
			IF(@RESTO<0)SET @AMMONTARE_BREVETTI=@AMMONTARE_BREVETTI+@RESTO --LA SOTTRAGGO A QUELLO CHE ECCEDE COSI TROVO 
																			--LA PARTE CHE PUO' ESSERE FINANZIATA
		END			
		ELSE BEGIN
			SET @AMMONTARE_BREVETTI=0
		END
	END

	DECLARE @AMMONTARE_NULLO BIT		
	SET @AMMONTARE_NULLO=0
	
	IF(@AMMONTARE_BREVETTI>=0)BEGIN
	
		-- SE L'AMMONTARE E' NULLO FALSA TUTTI I CALCOLI QUINDI BARBATRUCCO!
		
		IF @AMMONTARE_BREVETTI=0 BEGIN
			SET @AMMONTARE_NULLO=1
			SET @AMMONTARE_BREVETTI=1
		END
		IF @COSTO_TOTALE>0 BEGIN

			--CALCOLO GLI INVESTIMENTI SU CUI SPALMARE IL COSTO DEI BREVETTI
			DECLARE @CONTRIBUTO_BREVETTO DECIMAL(18,2)
			SET @CONTRIBUTO_BREVETTO =0
			DECLARE @COSTO_INVESTIMENTO DECIMAL(18,2)
			DECLARE @CONTRIBUTO DECIMAL(18,2)
			DECLARE TOTALE CURSOR FOR
			(SELECT COSTO_INVESTIMENTO,QUOTA_CONTRIBUTO_RICHIESTO FROM PIANO_INVESTIMENTI 
				WHERE ID_PROGETTO=@ID_PROGETTO AND COD_TIPO_INVESTIMENTO =1
				AND ((@FASE_ISTRUTTORIA=0 AND ID_INVESTIMENTO_ORIGINALE IS NULL) OR (@FASE_ISTRUTTORIA=1 AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL)))
			OPEN TOTALE
			FETCH NEXT FROM TOTALE 
			INTO @COSTO_INVESTIMENTO,@CONTRIBUTO
			WHILE @@FETCH_STATUS = 0
			BEGIN
				DECLARE @PARTE_BREVETTO DECIMAL(18,2)
				SET @PARTE_BREVETTO= @AMMONTARE_BREVETTI*@COSTO_INVESTIMENTO/@COSTO_TOTALE
				SET @CONTRIBUTO_BREVETTO=@CONTRIBUTO_BREVETTO+@CONTRIBUTO*@PARTE_BREVETTO/100							
				FETCH NEXT FROM TOTALE 
				INTO @COSTO_INVESTIMENTO,@CONTRIBUTO
			END
			CLOSE TOTALE
			DEALLOCATE TOTALE
		END
		-------------------------------------------------------
	END
	
	SELECT CASE WHEN @AMMONTARE_NULLO=1 THEN 0 ELSE @AMMONTARE_BREVETTI END AS AMMONTARE_BREVETTI,
           CAST(@CONTRIBUTO_BREVETTO/@AMMONTARE_BREVETTI*100 AS DECIMAL(18,2)) AS QUOTA_CONTRIBUTO_BREVETTI           
END
