CREATE PROCEDURE [dbo].[calcoloStepATS_1]
@IdProgetto int
AS
BEGIN

DECLARE @result int
DECLARE @TOTALE_INVESTIMENTO decimal(10,2)
DECLARE @TOTALE_E decimal(10,2)
 
 
SET @result =1 -- PONGO LO STEP VERIFICATO 

SET @TOTALE_INVESTIMENTO = ( SELECT     SUM(PIANO_INVESTIMENTI.COSTO_INVESTIMENTO) AS COSTO_INVESTIMENTO
							FROM  PROGETTO INNER JOIN PIANO_INVESTIMENTI ON PROGETTO.ID_PROGETTO = PIANO_INVESTIMENTI.ID_PROGETTO 
							WHERE  PROGETTO.ID_PROGETTO= @IdProgetto  
							AND ((PIANO_INVESTIMENTI.ID_INVESTIMENTO_ORIGINALE IS NULL AND PROGETTO.FLAG_DEFINITIVO = 0 ) 
							OR (PIANO_INVESTIMENTI.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND PROGETTO.FLAG_DEFINITIVO = 1 AND ID_VARIANTE IS NULL) )
							AND PIANO_INVESTIMENTI.COD_TIPO_INVESTIMENTO = 1 AND   
							ID_DETTAGLIO_INVESTIMENTO NOT IN (722,727,732,737,742)  )

select @TOTALE_INVESTIMENTO as tot

SET @TOTALE_E = ( SELECT     SUM(PIANO_INVESTIMENTI.COSTO_INVESTIMENTO) AS COSTO_INVESTIMENTO
					FROM         PROGETTO INNER JOIN PIANO_INVESTIMENTI ON PROGETTO.ID_PROGETTO = PIANO_INVESTIMENTI.ID_PROGETTO 
					WHERE   PROGETTO.ID_PROGETTO= @IdProgetto AND 
							  ((PIANO_INVESTIMENTI.ID_INVESTIMENTO_ORIGINALE IS NULL AND PROGETTO.FLAG_DEFINITIVO = 0 ) 
								OR (PIANO_INVESTIMENTI.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND PROGETTO.FLAG_DEFINITIVO = 1 AND ID_VARIANTE IS NULL) )
					AND PIANO_INVESTIMENTI.COD_TIPO_INVESTIMENTO = 1 AND ID_DETTAGLIO_INVESTIMENTO  IN (722,727,732,737,742)   )

select @TOTALE_E as e
IF(@TOTALE_E > @TOTALE_INVESTIMENTO*0.12 )SET @result =0 

SELECT @result AS RESULT

END
