-- beneficiario della filiera
--   BENEFICIARI della filiera - TUTTI

CREATE PROCEDURE [dbo].[calcoloStep111_MF_1]
@IdProgetto int
AS
BEGIN

DECLARE  @RESULT INT, @ID_FILIERA INT , @COUNT_CUAA INT

SET @RESULT =0 --PONGO LO STEP NN VERIFICATO

 IF((SELECT COUNT(*)  FROM PRIORITA_X_PROGETTO WHERE ID_PRIORITA = 267 AND ID_PROGETTO =@IdProgetto ) > 0  )
		 BEGIN
		SET @ID_FILIERA= (SELECT CODICE FROM PRIORITA_X_PROGETTO PP INNER JOIN VALORI_PRIORITA VP ON PP.ID_VALORE = VP.ID_VALORE WHERE PP.ID_PRIORITA = 267 AND ID_PROGETTO =@IdProgetto)
			SET @COUNT_CUAA = ( SELECT COUNT (*)  FROM IMPRESA_X_FILIERA WHERE ID_FILIERA = @ID_FILIERA  
															AND CUAA IN (SELECT CUAA FROM PROGETTO WHERE ID_PROGETTO = @IdProgetto) )
IF (@COUNT_CUAA>0 ) SET @RESULT = 1
		 END

 SELECT   @RESULT  
	
END
