CREATE  PROCEDURE [dbo].[calcoloRequisitoPagamento112_2]
@ID_DOMANDA_PAGAMENTO int
AS
BEGIN


--DECLARE @ID_DOMANDA_PAGAMENTO int
--SET @ID_DOMANDA_PAGAMENTO =28
DECLARE @ID_PROGETTO INT, 
					@COUNT INT,	
					@RESULT INT,
					@ID_BANDO INT,
					@DATE_FIN AS DATETIME

SET @ID_PROGETTO = ( SELECT ID_PROGETTO FROM DOMANDA_DI_PAGAMENTO WHERE ID_DOMANDA_PAGAMENTO=@ID_DOMANDA_PAGAMENTO  )	
SET @DATE_FIN =  (SELECT  VAL_DATA FROM  DOMANDA_PAGAMENTO_REQUISITI where ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO  AND ID_REQUISITO =2)

SELECT @ID_BANDO = ID_BANDO FROM PROGETTO WHERE ID_PROGETTO = @ID_PROGETTO 

IF(@ID_BANDO IN (376))
BEGIN 
		SET @RESULT =(SELECT 'DIFF'=
						CASE WHEN DATEDIFF(DAY, DATEADD(MM,3,@DATE_FIN ),(SELECT  VAL_DATA FROM DOMANDA_PAGAMENTO_REQUISITI WHERE ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO  AND ID_REQUISITO =1) ) <=0 THEN 1 	
							 ELSE 0 
						END)
END
ELSE BEGIN 

		IF(@ID_BANDO IN (27,76,107,135))-- SE BANDO GIOVANI
		BEGIN
 				SET @COUNT = (SELECT COUNT(*) FROM  DOMANDA_PAGAMENTO_REQUISITI  DPR WHERE  DPR.ID_REQUISITO =  105 AND ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO )
				IF(@COUNT >0 ) SET @DATE_FIN = DATEADD(MM,3,  @DATE_FIN) 
	 			IF (@ID_BANDO IN (27,107,135)) SET @DATE_FIN = DATEADD(DD ,45,  @DATE_FIN) 
		 
		END
		SET @RESULT =(SELECT 'DIFF'=
						CASE WHEN DATEDIFF(DAY, DATEADD(MM,6,@DATE_FIN ),(SELECT  VAL_DATA FROM DOMANDA_PAGAMENTO_REQUISITI WHERE ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO  AND ID_REQUISITO =1) ) <=0 THEN 1 	
							 ELSE 0 
						END)
END		
SELECT @RESULT
END
