CREATE PROCEDURE [dbo].[calcoloPriorita126_1]
(
@IdProgetto int,
@fase_istruttoria bit,
@IdVariante int =NULL
)
AS
BEGIN
-- D.	Ubicazione degli investimenti nelle aree D, C3 e C2
--declare @IdProgetto int, @fase_istruttoria bit, @IdVariante int 
--set @IdProgetto =2305
--set @fase_istruttoria= 0
--set @IdVariante= 0

DECLARE @Risultato decimal (8,2)
DECLARE @AREA varchar(2)
SET @Risultato =0

SELECT TOP(1)@AREA=TIPO_AREA  
FROM PIANO_INVESTIMENTI INV
	INNER JOIN (SELECT MAX(ID_LOCALIZZAZIONE)ID_LOCALIZZAZIONE,ID_INVESTIMENTO FROM LOCALIZZAZIONE_INVESTIMENTO GROUP BY ID_INVESTIMENTO )LOC ON  LOC.ID_INVESTIMENTO = INV.ID_INVESTIMENTO 
	INNER JOIN LOCALIZZAZIONE_INVESTIMENTO  L ON L.ID_LOCALIZZAZIONE=LOC.ID_LOCALIZZAZIONE
	INNER JOIN CATASTO_TERRENI CT ON CT.ID_CATASTO = L.ID_CATASTO 
	INNER JOIN COMUNI C ON C.ID_COMUNE =CT.ID_COMUNE 
WHERE INV.ID_PROGETTO =@IdProgetto AND 
	((@fase_istruttoria=0 AND ID_INVESTIMENTO_ORIGINALE IS NULL AND ID_VARIANTE IS NULL)OR
	(@fase_istruttoria=1 AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL AND @IdVariante IS NULL)
	 OR(@fase_istruttoria=1 AND    @IdVariante IS NOT NULL AND ID_VARIANTE =@IdVariante AND ISNULL(COD_VARIAZIONE, 'X' ) != 'A'))
GROUP BY TIPO_AREA
ORDER BY SUM(COSTO_INVESTIMENTO) DESC

IF(@AREA IN('D','C3'))SET @Risultato = 1
ELSE IF(@AREA IN('C2'))SET @Risultato = 0.5

SELECT @Risultato 
END
