CREATE PROCEDURE [dbo].[calcoloPrioritaVariante311_2]
(
	@ID_VARIANTE  int
)
AS
BEGIN

--  priorità 63 (311 - investimenti destinati a creare occupazione) 
-- 311 - VERIFICA AUMENTO OCCUPAZIONE
-- - AUMENTO ORE >= 800 e < 1600 -> 0,50 
-- - AUMENTO ORE >= 1600 -> 1
 
DECLARE @ORE_ATTIVITA_ANTE decimal(10,2),
		@ORE_ATTIVITA_POST decimal(10,2),
		@PUNTEGGIO decimal(10,2), 
		@OREINCREMENTO decimal(10,2), 
		@IdProgetto int, @DATA_PRESENTAZIONE DATETIME 
-- cambio calcolo obbligatoria la plv ante -- 
DECLARE @ANNO INT , @ANNO_POST INT 

-- Calcolo delle ore totali per le attività connesse
SELECT @IdProgetto =  ID_PROGETTO, @DATA_PRESENTAZIONE= DATA_MODIFICA FROM VARIANTI WHERE ID_VARIANTE = @ID_VARIANTE 
SELECT @ANNO = MIN(ANNO) FROM PLV_IMPRESA 
WHERE ID_PROGETTO = @IdProgetto AND PREVISIONALE = 0 AND ID_ATTIVITA_CONNESSA IS NOT NULL

IF(@DATA_PRESENTAZIONE > '2015-07-14')BEGIN 
		SELECT @ANNO_POST = MAX(ANNO) FROM PLV_IMPRESA WHERE ID_PROGETTO = @IdProgetto AND PREVISIONALE = 0 AND ID_ATTIVITA_CONNESSA IS NOT NULL
		SET @ORE_ATTIVITA_POST = (SELECT ISNULL(SUM(ISNULL(SAU,0) * ISNULL(ORE_UNITARIE,0)),0) 
									FROM PLV_IMPRESA WHERE ID_PROGETTO = @IdProgetto AND PREVISIONALE = 0 AND ID_ATTIVITA_CONNESSA IS NOT NULL AND ANNO =@ANNO_POST)

END
ELSE BEGIN 
	SET @ORE_ATTIVITA_POST = (SELECT ISNULL(SUM(ISNULL(SAU,0) * ISNULL(ORE_UNITARIE,0)),0) 
							  FROM PLV_IMPRESA WHERE ID_PROGETTO = @IdProgetto AND PREVISIONALE = 1 AND ID_ATTIVITA_CONNESSA IS NOT NULL)
END

SET @ORE_ATTIVITA_ANTE = (SELECT ISNULL(SUM(ISNULL(SAU,0) * ISNULL(ORE_UNITARIE,0)),0) 
                           FROM PLV_IMPRESA WHERE ID_PROGETTO = @IdProgetto AND PREVISIONALE = 0 AND ID_ATTIVITA_CONNESSA IS NOT NULL AND ANNO = @ANNO)



SET @OREINCREMENTO = ISNULL(@ORE_ATTIVITA_POST,0 ) - ISNULL(@ORE_ATTIVITA_ANTE,0)
  
   IF (@OREINCREMENTO >= 1600)  
		SET @PUNTEGGIO = 1
    ELSE 
		IF (@OREINCREMENTO >= 800 AND @OREINCREMENTO < 1600)  
			SET @PUNTEGGIO = 0.5	
		ELSE  
			SET @PUNTEGGIO = 0

SELECT @Punteggio AS PUNTEGGIO
RETURN (@PUNTEGGIO*100)
END
