CREATE  PROCEDURE [dbo].[calcoloStepPagamentoGAL_MAX2]
@IdProgetto int,
@IdDomandaPagamento int =NULL
AS
BEGIN
	-- Costo ammissibile all`aiuto per la realizzazione di guide su supporto cartaceo e multimediale < € 50.000,00 (PER LA CODIFICA 01)
	-- verifica totale investimenti in domanda < 50.000,00 € PER LA CODIFICA 01
DECLARE @RESULT INT, @SPESA_AMMESSA decimal(10,2)

 SET @RESULT = 0 -- IMPONGO LO STEP NON VERIFICATO		 
 
 SET @SPESA_AMMESSA = (SELECT ISNULL(SUM(ISNULL(IMPORTO_AMMESSO,0)) , 0)    
						FROM PAGAMENTI_RICHIESTI P
							INNER JOIN VPIANO_INVESTIMENTI I ON (P.ID_INVESTIMENTO=I.ID_INVESTIMENTO)      
							INNER JOIN DOMANDA_DI_PAGAMENTO DP ON DP.ID_DOMANDA_PAGAMENTO = P.ID_DOMANDA_PAGAMENTO  
						WHERE I.CODICE ='01' AND ((DP.ID_DOMANDA_PAGAMENTO < @IdDomandaPagamento  AND DP.APPROVATA=1 AND DP.ID_PROGETTO=@IdProgetto)
							    OR DP.ID_DOMANDA_PAGAMENTO=@IdDomandaPagamento) AND I.COD_TIPO_INVESTIMENTO = 1)

--SELECT @SPESA_AMMESSA
IF ( @SPESA_AMMESSA <=50000) SET @RESULT = 1	 
SELECT @RESULT
END
