CREATE PROCEDURE [dbo].[calcoloStep911_7]
(
	@IdProgetto int,
	@FASE_ISTRUTTORIA int 
)
AS
BEGIN
/*
DIRITTI RICHIESTI MAX 2HA E MIN 1HA

*/
	DECLARE @Risultato INT =0,@ID_BANDO INT,@ID_IMPRESA INT,
		@TOT_SUP DECIMAL(18,2), @TotSupVitata decimal (10,2), @MQ_CONVERSIONE DECIMAL(18,2), @MQ_IMPIANTO DECIMAL(18,2),
		@MQ_MAX INT 
	-- sommo gli HA scritti in quantità dell'investimento
	SELECT  @ID_BANDO =  ID_BANDO, @ID_IMPRESA=ID_IMPRESA   FROM PROGETTO WHERE ID_PROGETTO=@IdProgetto 	
	IF(@ID_BANDO = 491)SET @MQ_MAX = 100000
	ELSE SET @MQ_MAX = 50000
	
	SELECT @MQ_CONVERSIONE=SUM(QUANTITA)
	FROM  PIANO_INVESTIMENTI INV 
		INNER JOIN VPROGETTO AS p ON P.ID_PROGETTO=INV.ID_PROGETTO 
		INNER JOIN DETTAGLIO_INVESTIMENTI D ON D.ID_DETTAGLIO_INVESTIMENTO = INV.ID_DETTAGLIO_INVESTIMENTO AND D.ID_CODIFICA_INVESTIMENTO = INV.ID_CODIFICA_INVESTIMENTO AND COD_DETTAGLIO = 'BB'
	WHERE P.ID_BANDO =@ID_BANDO AND P.ID_IMPRESA =@ID_IMPRESA 
		AND ( (INV.ID_PROGETTO = @IdProgetto AND ((@FASE_ISTRUTTORIA=0 AND INV.ID_INVESTIMENTO_ORIGINALE IS NULL)OR(@FASE_ISTRUTTORIA=1 AND INV.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL)))
				OR (INV.ID_PROGETTO!= @IdProgetto  AND INV.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL )) -- DOMANDA PRESENTATA DELLA STESSA IMPRESA
		 		
	SELECT @MQ_IMPIANTO=SUM(QUANTITA)
	FROM PIANO_INVESTIMENTI INV 
		INNER JOIN VPROGETTO AS p ON P.ID_PROGETTO=INV.ID_PROGETTO 
		INNER JOIN DETTAGLIO_INVESTIMENTI D ON D.ID_DETTAGLIO_INVESTIMENTO = INV.ID_DETTAGLIO_INVESTIMENTO AND D.ID_CODIFICA_INVESTIMENTO = INV.ID_CODIFICA_INVESTIMENTO AND COD_DETTAGLIO = 'AA'
	WHERE P.ID_BANDO =@ID_BANDO AND P.ID_IMPRESA =@ID_IMPRESA 
		  AND ( (INV.ID_PROGETTO = @IdProgetto AND ((@FASE_ISTRUTTORIA=0 AND INV.ID_INVESTIMENTO_ORIGINALE IS NULL)OR(@FASE_ISTRUTTORIA=1 AND INV.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL)))
				OR (INV.ID_PROGETTO!= @IdProgetto  AND INV.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL )) -- DOMANDA PRESENTATA DELLA STESSA IMPRESA
		 
	SET @TOT_SUP= ISNULL(@MQ_CONVERSIONE ,0)  + ISNULL(@MQ_IMPIANTO ,0)
		
	IF (@TOT_SUP >=5000 AND @TOT_SUP <=@MQ_MAX) SET @Risultato=1
	ELSE SET @Risultato=0
	SELECT @Risultato AS PUNTEGGIO
END
