CREATE PROCEDURE [dbo].[calcoloStepVariante112_114_3]
@ID_VARIANTE int
AS
 
  -- 112-114 - E' stato selezionato il consulente prescelto a sistema (requisiti soggettivi mis 114)?

 DECLARE @RESULT INT
 SET @RESULT =1

DECLARE @ID_PROGETTO INT,@COUNT_INV INT 
DECLARE @ID_PROGETTO_114 INT 
SET @ID_PROGETTO  = (SELECT ID_PROGETTO FROM VARIANTI WHERE ID_VARIANTE = @ID_VARIANTE)

SELECT DISTINCT @ID_PROGETTO_114 = p.ID_PROGETTO  FROM PROGETTO P
	INNER JOIN BANDO B ON B.ID_BANDO = P.ID_BANDO INNER JOIN ZPROGRAMMAZIONE ZP ON ZP.ID =B.ID_PROGRAMMAZIONE AND CODICE = '1.1.4.'
WHERE ID_PROG_INTEGRATO = @ID_PROGETTO

--SOLO SE LA VARIANTE è PER LA 114
SET @COUNT_INV = ( SELECT COUNT (*) FROM PIANO_INVESTIMENTI I WHERE ID_VARIANTE = @ID_VARIANTE AND ID_PROGETTO = @ID_PROGETTO_114 AND ISNULL(COD_VARIAZIONE , 'X' )!='A'  AND  COD_VARIAZIONE is not null AND COSTO_INVESTIMENTO >0 )

IF(  @COUNT_INV  >0 )
BEGIN
	SET @RESULT = ( SELECT COUNT(*) FROM PRIORITA_X_PROGETTO WHERE ID_PRIORITA= 245 AND ID_PROGETTO  = @ID_PROGETTO_114   )  
 END
SELECT @RESULT AS RESULT
