CREATE PROCEDURE [dbo].[calcoloStep911_10]
(
	@IdProgetto int,
	@FASE_ISTRUTTORIA int 
)
AS
BEGIN
/* GIOVANE  */
	DECLARE @Risultato INT =1 , 
			@ID_BANDO INT , @ETA INT
	
	SELECT  @ID_BANDO =  ID_BANDO  FROM PROGETTO WHERE ID_PROGETTO=@IdProgetto 	
		
	IF(@ID_BANDO = 491) BEGIN 
		SELECT  @ETA= DATEDIFF(MM, PP.DATA_NASCITA ,PS.DATA)/12
		FROM PROGETTO P
			INNER JOIN PROGETTO_STORICO PS ON PS.ID_PROGETTO= P.ID_PROGETTO AND COD_STATO='L'
			INNER JOIN VIMPRESA IMP ON P.ID_IMPRESA = IMP.ID_IMPRESA 
			INNER JOIN VPERSONE_X_IMPRESE PP ON PP.ID_PERSONE_X_IMPRESE= IMP.	ID_RAPPRLEGALE_ULTIMO
		WHERE P.ID_PROGETTO = @IdProgetto
			 
		IF @ETA <40 SET @Risultato =1
		ELSE SET @Risultato =0 
	END
	ELSE BEGIN 
		
		SELECT @ETA=ISNULL(DATEDIFF(YEAR,CONVERT(datetime,convert(varchar, note),103),P.DATA ),-1) 
		FROM ITER_PROGETTO I 
				INNER JOIN PROGETTO_STORICO P ON I.ID_PROGETTO=P.ID_PROGETTO AND COD_STATO='L' where i.id_progetto=@IdProgetto AND ID_STEP=5885
	
		IF(@ETA > 40) SET @Risultato = 0
		ELSE SET @Risultato=1
	END	 
	 
	SELECT @Risultato 
END
