CREATE PROCEDURE [dbo].[calcoloStep133_13]
(
	@IdProgetto int,
	@FASE_ISTRUTTORIA INT =0
)
AS
BEGIN
-- TOTALE PROGETTO PER ANNUALITà CORRISPONDENTE CON IL PROGETTO PLURIENNALE - MICROFILEIRA
DECLARE @RESULT INT, @ID_PROGETTO_PLURI INT,
		@ID_ANNUALITA INT, @ANNO_MIN INT,@ANNO_MAX INT,@VALORE_ANNUALITA VARCHAR(50),
		@COSTO_ANNUALITA DECIMAL(18,2), @COSTO_ANNO_PLURIENNALE DECIMAL(18,2), @ECONOMIA_ANNUALE DECIMAL(18,2)
	--	,@FASE_ISTRUTTORIA INT =0,@IdProgetto int
		
--SET @IdProgetto = 9023
SET @RESULT =1 --PONGO LO STEP VERIFICATO

SELECT @ID_PROGETTO_PLURI = VALORE FROM PRIORITA_X_PROGETTO PP WHERE ID_PRIORITA=757 AND ID_PROGETTO = @IdProgetto
-- ID_PRIORITA =1079 VIENE UTILIZZATA PER MEMORIZZARE L'ECONOMIA DELLA DOMADNA ANNUALE RISPETTO L'ANNUALITA DEFINITA NEL PROGETO-PLURIENNALE
SELECT @ECONOMIA_ANNUALE= VALORE FROM PRIORITA_X_PROGETTO PP WHERE PP.ID_PROGETTO = @IdProgetto AND ID_PRIORITA = 1079
IF(@ECONOMIA_ANNUALE IS NULL ) SET @RESULT =0

-- CONTROLLO L'ANNUALITA -->ID PRIORITA 768 (PRIMO/SECONDO/TERZO ANNO)
SELECT @ID_ANNUALITA = PXI.ID_VALORE, @VALORE_ANNUALITA =VP.DESCRIZIONE FROM PIANO_INVESTIMENTI INV 
		INNER JOIN PRIORITA_X_INVESTIMENTI PXI ON PXI.ID_INVESTIMENTO= INV.ID_INVESTIMENTO 
		INNER JOIN VALORI_PRIORITA VP ON VP.ID_VALORE =PXI.ID_VALORE AND VP.ID_PRIORITA =768 
WHERE ID_PROGETTO = @IdProgetto AND ((@FASE_ISTRUTTORIA=0 AND ID_INVESTIMENTO_ORIGINALE IS NULL AND ID_VARIANTE IS NULL) OR(@FASE_ISTRUTTORIA=1 AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL))

--TROVO L'ANNUALITà PIù PICCOLA e LA PIù GRANDE DEFINITA NEL PROGETTO PLURIENNALE (PRENDO ID_VALORE) (2011/2012/2013/2014)
SELECT @ANNO_MIN = PXI.ID_VALORE FROM PIANO_INVESTIMENTI INV 
		INNER JOIN PRIORITA_X_INVESTIMENTI PXI ON PXI.ID_INVESTIMENTO= INV.ID_INVESTIMENTO 
		INNER JOIN VALORI_PRIORITA VP ON VP.ID_VALORE = PXI.ID_VALORE AND VP.ID_PRIORITA in (859,1080) 
WHERE ID_PROGETTO = @IdProgetto AND ((@FASE_ISTRUTTORIA=0 AND ID_INVESTIMENTO_ORIGINALE IS NULL AND ID_VARIANTE IS NULL) OR(@FASE_ISTRUTTORIA=1 AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL)) ORDER BY CODICE DESC

SELECT @ANNO_MAX = PXI.ID_VALORE FROM PIANO_INVESTIMENTI INV 
		INNER JOIN PRIORITA_X_INVESTIMENTI PXI ON PXI.ID_INVESTIMENTO= INV.ID_INVESTIMENTO 
		INNER JOIN VALORI_PRIORITA VP ON VP.ID_VALORE = PXI.ID_VALORE AND VP.ID_PRIORITA in (859,1080)
WHERE ID_PROGETTO = @IdProgetto AND ((@FASE_ISTRUTTORIA=0 AND ID_INVESTIMENTO_ORIGINALE IS NULL AND ID_VARIANTE IS NULL) OR(@FASE_ISTRUTTORIA=1 AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL)) ORDER BY CODICE ASC

--SELECT @ID_ANNUALITA,@ANNO_MIN,@ID_PROGETTO_PLURI, @IdProgetto
--SELECT *FROM VALORI_PRIORITA WHERE ID_VALORE =@ANNO_MIN 

SELECT @COSTO_ANNUALITA = SUM(COSTO_INVESTIMENTO) FROM PIANO_INVESTIMENTI INV 
WHERE ID_PROGETTO = @IdProgetto AND COD_TIPO_INVESTIMENTO =1 AND 
 ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL


--COSTO DEL PROGETTO PLURIENNALE CON STESSO VALORE "ANNUALITA DI REALIZZAZIONE"
	SELECT @COSTO_ANNO_PLURIENNALE= SUM(COSTO_INVESTIMENTO)
	FROM PIANO_INVESTIMENTI INV 
			INNER JOIN PRIORITA_X_INVESTIMENTI PXI ON PXI.ID_INVESTIMENTO = INV.ID_INVESTIMENTO AND PXI.ID_PRIORITA=768 AND PXI.ID_VALORE= @ID_ANNUALITA 
	WHERE ID_PROGETTO = @ID_PROGETTO_PLURI AND COD_TIPO_INVESTIMENTO =1 AND ((@FASE_ISTRUTTORIA=0 AND ID_INVESTIMENTO_ORIGINALE IS NULL AND ID_VARIANTE IS NULL) OR(@FASE_ISTRUTTORIA=1 AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL))

IF (ISNULL(@COSTO_ANNUALITA,0) + ISNULL(@ECONOMIA_ANNUALE,0)) > ISNULL(@COSTO_ANNO_PLURIENNALE,0) SET @RESULT =0
SELECT ISNULL(@RESULT,0)
END
