CREATE  PROCEDURE [dbo].[calcoloRequisitoPagamento121_10]
@ID_DOMANDA_PAGAMENTO int
AS
BEGIN

DECLARE @ID_PROGETTO INT, @RESULT INT,@DATA_COMUN_FINA DATETIME

SET @RESULT = 0 -- IMPONGO LO STEP NON VERIFICATO		
--La richiesta di saldo è stata effettuata entro e non oltre il 24  mese dalla data di adozione della decisione 

 
--declare @ID_DOMANDA_PAGAMENTO int = 1220

 SELECT @DATA_COMUN_FINA=VAL_DATA FROM DOMANDA_PAGAMENTO_REQUISITI WHERE ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO  AND ID_REQUISITO =2
 
 IF((@DATA_COMUN_FINA)<=(SELECT DATA_MODIFICA FROM DOMANDA_DI_PAGAMENTO WHERE ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO ))
 BEGIN 
  SET @RESULT=(SELECT 'DIFF'= CASE WHEN DATEDIFF(DAY, DATEADD(MM,24,(@DATA_COMUN_FINA)),(SELECT DATA_MODIFICA FROM DOMANDA_DI_PAGAMENTO WHERE ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO ))<=0 THEN 1 ELSE 0 END) END 
SELECT @RESULT
END
