CREATE   PROCEDURE [dbo].[calcoloStep133_8]
(
	@IdProgetto int,
	@FASE_ISTRUTTORIA INT =0
)
AS
BEGIN
/* Investimenti completi di indicazione dell`annualità di realizzazione E ANNUALITA DI PROGETTO: 
859:PRIMA E SECONDA SCADENZA - 1080:TERZA SCADENZA
ANNUALITÀ DI PROGETTO ID 768: TUTTI I BANDI 
ANNUALITÀ DI PROGETTO ID 1198: QUARTA SCADENZA 
*/
DECLARE @CUAA VARCHAR(16), @RESULT int
--@IdProgetto int
--set @IdProgetto =  7343 
SET @RESULT =1 --PONGO LO STEP VERIFICATO
 
 SELECT @RESULT =((SELECT COUNT(*) AS A  FROM  PIANO_INVESTIMENTI PI  
					WHERE  ID_PROGETTO = @IdProgetto AND COD_TIPO_INVESTIMENTO = 1 AND ((ID_INVESTIMENTO_ORIGINALE  IS NULL AND @FASE_ISTRUTTORIA=0 AND ID_VARIANTE IS NULL )
															OR(ID_INVESTIMENTO_ORIGINALE  IS NOT NULL AND @FASE_ISTRUTTORIA=1 AND ID_VARIANTE IS NULL)) ) 
					- 
				 (SELECT COUNT(*) FROM PIANO_INVESTIMENTI AS PI INNER JOIN PRIORITA_X_INVESTIMENTI ON PI.ID_INVESTIMENTO = PRIORITA_X_INVESTIMENTI.ID_INVESTIMENTO 
				  WHERE (PI.ID_PROGETTO = @IdProgetto )AND COD_TIPO_INVESTIMENTO = 1  AND ((ID_INVESTIMENTO_ORIGINALE IS NULL AND @FASE_ISTRUTTORIA=0 AND ID_VARIANTE IS NULL )
						OR(ID_INVESTIMENTO_ORIGINALE  IS NOT NULL AND @FASE_ISTRUTTORIA=1 AND ID_VARIANTE IS NULL)) AND ID_PRIORITA in (859,1080)))
 IF(@RESULT=1)BEGIN
	SELECT @RESULT =((SELECT   COUNT(*) AS A  FROM  PIANO_INVESTIMENTI PI  
					WHERE  ID_PROGETTO = @IdProgetto AND ((ID_INVESTIMENTO_ORIGINALE  IS NULL AND @FASE_ISTRUTTORIA=0 AND ID_VARIANTE IS NULL )OR
							(ID_INVESTIMENTO_ORIGINALE  IS NOT NULL AND @FASE_ISTRUTTORIA=1 AND ID_VARIANTE IS NULL)) AND COD_TIPO_INVESTIMENTO = 1) 
					- 
					(SELECT COUNT(*) FROM PIANO_INVESTIMENTI AS PI INNER JOIN PRIORITA_X_INVESTIMENTI ON PI.ID_INVESTIMENTO = PRIORITA_X_INVESTIMENTI.ID_INVESTIMENTO 
					 WHERE (PI.ID_PROGETTO = @IdProgetto )AND cod_tipo_investimento = 1  AND ((ID_INVESTIMENTO_ORIGINALE  IS NULL AND @FASE_ISTRUTTORIA=0 AND ID_VARIANTE IS NULL )
							OR(ID_INVESTIMENTO_ORIGINALE  IS NOT NULL AND @FASE_ISTRUTTORIA=1 AND ID_VARIANTE IS NULL)) AND ID_PRIORITA in (768,1198) ))
	
 END

 IF(@RESULT!=1) SET @RESULT =0
 SELECT ISNULL(@RESULT,0)
END
