CREATE PROCEDURE [dbo].[calcoloPriorita313_AN]
(
@IdProgetto int,
@fase_istruttoria bit,
@IdVariante INT = 0
)
AS
BEGIN
-- Investimenti relativi all`utilizzo delle Tecnologie di Informazione e Comunicazione >= 15% del totale investimenti (INCLUSE le spese tecniche)

DECLARE @COSTO_INVESTIMENTO DECIMAL(18,2), 
		@SPESE_TIC DECIMAL (18,2),
		@Punteggio decimal(10,2)
SET @Punteggio = 0

SELECT @COSTO_INVESTIMENTO=ISNULL(SUM(COSTO_INVESTIMENTO),0) + ISNULL( SUM (SPESE_GENERALI),0) FROM PIANO_INVESTIMENTI I 
WHERE I.ID_PROGETTO = @IdProgetto AND I.COD_TIPO_INVESTIMENTO = 1 AND
((@fase_istruttoria=0 AND I.ID_INVESTIMENTO_ORIGINALE IS NULL AND ID_VARIANTE IS NULL ) OR 
 (@fase_istruttoria=1 AND (I.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE  IS NULL AND @IdVariante IS  NULL ) OR (ID_VARIANTE  = @IdVariante AND @IdVariante IS NOT NULL AND ISNULL(COD_VARIAZIONE, 'X' ) != 'A')))
  
SELECT @SPESE_TIC= ISNULL(SUM(COSTO_INVESTIMENTO),0) + ISNULL(SUM(SPESE_GENERALI),0) FROM PROGETTO P INNER JOIN VPIANO_INVESTIMENTI I ON (P.ID_PROGETTO=I.ID_PROGETTO) WHERE
P.ID_PROGETTO=@IdProgetto AND
((@fase_istruttoria=0 AND I.ID_INVESTIMENTO_ORIGINALE IS NULL AND ID_VARIANTE IS NULL ) OR 
 (@fase_istruttoria=1 AND (I.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE  IS NULL AND @IdVariante IS  NULL ) OR (ID_VARIANTE  = @IdVariante AND @IdVariante IS NOT NULL AND ISNULL(COD_VARIAZIONE, 'X' ) != 'A'))) AND
I.COD_TIPO_INVESTIMENTO = 1 AND
I.ID_DETTAGLIO_INVESTIMENTO = (SELECT DI.ID_DETTAGLIO_INVESTIMENTO FROM CODIFICA_INVESTIMENTO CI INNER JOIN
								DETTAGLIO_INVESTIMENTI DI ON CI.ID_CODIFICA_INVESTIMENTO = DI.ID_CODIFICA_INVESTIMENTO  WHERE
								DI.COD_DETTAGLIO = '2' AND CI.CODICE = 'A' AND CI.ID_BANDO =
								(SELECT ID_BANDO FROM PROGETTO WHERE ID_PROGETTO = @IdProgetto))
 
 
IF(ISNULL(@SPESE_TIC,0) >= ((@COSTO_INVESTIMENTO*15)/100)) SET @Punteggio = 1
	ELSE SET  @Punteggio= 0
SELECT @Punteggio AS PUNTEGGIO
END
