CREATE  PROCEDURE [dbo].[calcoloRequisitoPagamento121_11]
@ID_DOMANDA_PAGAMENTO int
AS
BEGIN


--DECLARE @ID_DOMANDA_PAGAMENTO int
--SET @ID_DOMANDA_PAGAMENTO =28
DECLARE @ID_PROGETTO INT, 
					@COUNT INT,	
					@RESULT INT,
					@ID_BANDO INT,
					@DATE_FIN AS DATETIME

SET @ID_PROGETTO = ( SELECT ID_PROGETTO FROM DOMANDA_DI_PAGAMENTO WHERE ID_DOMANDA_PAGAMENTO=@ID_DOMANDA_PAGAMENTO  )	
SET @DATE_FIN =  (SELECT  VAL_DATA FROM  DOMANDA_PAGAMENTO_REQUISITI where ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO  AND ID_REQUISITO =2)

SET @RESULT =(SELECT 'DIFF'=
						CASE WHEN DATEDIFF(DAY, DATEADD(MM,6,@DATE_FIN ),
									(SELECT  VAL_DATA FROM DOMANDA_PAGAMENTO_REQUISITI 
									 WHERE ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO  AND ID_REQUISITO =480) ) <=0 THEN 1 	
							 ELSE 0 
						END)
 
SELECT @RESULT
END
