CREATE   PROCEDURE [dbo].[calcoloStep123_MF_1]
@IdProgetto int
AS
BEGIN
 

--  CONTROLLO SETTORE UNICO PER IL PROGETTO E OBBLIGATORIO PER GLI INVESTIMENTI
--
DECLARE @COUNT_TOTALE INT , @COUNT_S INT, @COUNT_NULL INT, @Result INT
SET @Result = 1 -- Impongo lo Step   verificato

SET  @COUNT_TOTALE = (SELECT COUNT(*) FROM PIANO_INVESTIMENTI P LEFT JOIN PRIORITA_X_INVESTIMENTI PI  ON PI.ID_INVESTIMENTO= P.ID_INVESTIMENTO  AND ID_PRIORITA = 201 
													WHERE COD_TIPO_INVESTIMENTO = 1 AND ID_PRIORITA IS NULL AND ID_INVESTIMENTO_ORIGINALE IS NULL AND  ID_PROGETTO =@IdProgetto )
IF (@COUNT_TOTALE =0 )
BEGIN 
		SET @COUNT_S =  (  SELECT COUNT(*)  FROM  ( SELECT  COUNT(*) AS C , ID_SETTORE_PRODUTTIVO FROM PIANO_INVESTIMENTI P  
															WHERE COD_TIPO_INVESTIMENTO = 1 AND  ID_INVESTIMENTO_ORIGINALE IS NULL  AND ID_PROGETTO =@IdProgetto AND ID_SETTORE_PRODUTTIVO IS NULL
															GROUP BY ID_SETTORE_PRODUTTIVO
															) AS T 
												 )
		IF ( @COUNT_S  = 1  )
				BEGIN		
						SET @COUNT_NULL =   (  SELECT  COUNT(*) AS C   FROM PIANO_INVESTIMENTI P  
																		 WHERE COD_TIPO_INVESTIMENTO = 1 AND  ID_INVESTIMENTO_ORIGINALE IS NULL  AND ID_PROGETTO =@IdProgetto AND ID_SETTORE_PRODUTTIVO IS NULL  )
						IF(@COUNT_NULL > 0) 	SET @Result = 0
				END
		ELSE  
				SET @Result = 0
END
ELSE 
IF ( @COUNT_TOTALE >  0) SET @Result = 0
 
	SELECT @Result AS RESULT
	END
