CREATE  PROCEDURE [dbo].[calcoloRequisitoPagamento112_1]
@ID_DOMANDA_PAGAMENTO int
AS
BEGIN

	 
	DECLARE @ID_PROGETTO INT, @CODICE INT,
						@RESULT INT


SET @RESULT = 1 -- IMPONGO LO STEP NON VERIFICATO		 

SET @ID_PROGETTO = ( SELECT ID_PROGETTO FROM DOMANDA_DI_PAGAMENTO WHERE ID_DOMANDA_PAGAMENTO=@ID_DOMANDA_PAGAMENTO  )	
SET @CODICE = (SELECT  CAST(CODICE AS INT)  
				FROM DOMANDA_PAGAMENTO_REQUISITI DPR
					INNER JOIN REQUISITI_PAGAMENTO_PLURIVALORE RPP ON DPR.ID_VALORE= RPP.ID_VALORE
				WHERE  DPR.ID_REQUISITO = 49 AND ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO )
IF (@CODICE =1)--HA RICHIESTO IL MUTUO
BEGIN 
		 SET @CODICE = (SELECT  CAST(CODICE AS INT)  FROM  DOMANDA_PAGAMENTO_REQUISITI  DPR
						 INNER JOIN REQUISITI_PAGAMENTO_PLURIVALORE RPP ON DPR.ID_VALORE= RPP.ID_VALORE
						WHERE  DPR.ID_REQUISITO = 50 AND ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO )
		IF(@CODICE in(2,3)) SET @RESULT = 0
END
SELECT @RESULT
END
