create PROCEDURE [dbo].[calcoloStepVariante221_12]
@ID_VARIANTE int,
@IdProgetto int 
AS
BEGIN
-- deminimis

DECLARE @RESULT int,
		@RESULTA int,
		@RESULTB int

SET @IdProgetto = ( SELECT ID_PROGETTO FROM VARIANTI WHERE ID_VARIANTE= @ID_VARIANTE )
SET @RESULT = 0 -- PONGO LO STEP IN STATO NON VERIFICATO
SET @RESULTA = 0 -- PONGO LO STEP IN STATO NON VERIFICATO
SET @RESULTB = 0 -- PONGO LO STEP IN STATO NON VERIFICATO


SET @RESULTA = (SELECT ISNULL (VALORE,0) from PRIORITA_X_PROGETTO WHERE ID_PRIORITA = 600 AND ID_PROGETTO = @IdProgetto)  
SET @RESULTB = (SELECT ISNULL(SUM(CONTRIBUTO_RICHIESTO),0) 
				FROM PROGETTO P  
					 INNER JOIN PIANO_INVESTIMENTI I ON (P.ID_PROGETTO=I.ID_PROGETTO) WHERE
					 P.ID_PROGETTO=@IdProgetto)

IF ((ISNULL (@RESULTA,0) + @RESULTB) <= 200000)SET @RESULT=1
SELECT @RESULT AS RESULT

END
