CREATE PROCEDURE [dbo].[calcoloStep123_3]
@IdProgetto int
AS
BEGIN

-- 123 a) verifica sostenibilità economica investimento: (tot. FISSI/30 + tot. MOBILI/10) < 15% Fatturato ex-post

DECLARE @result int, @COUNT_BILANCI INT
DECLARE @Rata  decimal(15,2)
DECLARE @PLV_RICAVI_VENDITA decimal(15,2)

SELECT @COUNT_BILANCI=COUNT(*) FROM BILANCIO_INDUSTRIALE WHERE PREVISIONALE = 1 AND ID_PROGETTO = @IdProgetto 

IF(ISNULL(@COUNT_BILANCI,0) =0 ) BEGIN SET @result =0 END
ELSE BEGIN 	
	SET @Rata = (SELECT ISNULL(SUM((CASE I.MOBILE
									 WHEN 1 THEN (I.COSTO_INVESTIMENTO + I.SPESE_GENERALI)/ 10 
									 WHEN 0 THEN (I.COSTO_INVESTIMENTO + I.SPESE_GENERALI)/ 30
									 ELSE (I.COSTO_INVESTIMENTO + I.SPESE_GENERALI)/ 30
									 END)) , 0)
				FROM PROGETTO P INNER JOIN VPIANO_INVESTIMENTI I ON (P.ID_PROGETTO=I.ID_PROGETTO)
				WHERE  ((FLAG_DEFINITIVO =0  AND ID_INVESTIMENTO_ORIGINALE IS NULL)OR
						(FLAG_DEFINITIVO =1 AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL)) AND I.COD_TIPO_INVESTIMENTO = 1 AND
									  (P.ID_PROGETTO=@IdProgetto))	
	
	SET @PLV_RICAVI_VENDITA= (SELECT ISNULL(SUM(PLV_RICAVI_VENDITA),0)/COUNT(*) AS RICAVI FROM BILANCIO_INDUSTRIALE WHERE PREVISIONALE = 1 AND ID_PROGETTO = @IdProgetto )

	IF (@Rata < (@PLV_RICAVI_VENDITA * 0.15)) SET @result = 1
	ELSE SET @result = 0
END

SELECT @result AS RESULT
END
