CREATE  PROCEDURE [dbo].[calcoloStep123_FIL_3]
@IdProgetto int
AS
BEGIN
 

--  CONTROLLO SETTORI BIOLOGICI
--
DECLARE @COUNT_TOTALE INT , @COUNT_S INT, @Result INT
SET @Result = 0 -- Impongo lo Step non verificato

SET  @COUNT_TOTALE = (SELECT COUNT(*) FROM PIANO_INVESTIMENTI P LEFT JOIN PRIORITA_X_INVESTIMENTI PI  ON PI.ID_INVESTIMENTO= P.ID_INVESTIMENTO  AND ID_PRIORITA = 201 
													WHERE COD_TIPO_INVESTIMENTO = 1 AND ID_PRIORITA IS NULL AND ID_INVESTIMENTO_ORIGINALE IS NULL and id_progetto =@IdProgetto )

IF ( @COUNT_TOTALE = 0) SET @Result = 1 
 
	SELECT @Result AS RESULT
	END
