CREATE PROCEDURE [dbo].[calcoloRequisitoPagamento112_Bilancio]
@ID_DOMANDA_PAGAMENTO int
AS
BEGIN

-- 112 - bloccare bilancio
--declare @ID_DOMANDA_PAGAMENTO int = 2223
DECLARE @Result int,@IdProgetto int,@IdImpresa INT,@ID_BILANCIO INT,@DATA_PRESENTAZIONE DATETIME,@ANNO_PRESENTAZIONE INT,
	    @TOT_IMPIEGHI decimal(10,2),
		@TOT_FONTI_FINANZIAMENTO decimal(10,2),  
	    @REDDITO_OPERATIVO decimal(10,2),
        @REDDITO_NETTO_PAC decimal(10,1) 
	 
	 
SET @Result = 1 -- Impongo lo Step VERIFICATO
SET @IdProgetto= (SELECT ID_PROGETTO FROM DOMANDA_DI_PAGAMENTO WHERE ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO)
SET @IdImpresa = (SELECT TOP(1) ID_IMPRESA FROM PROGETTO WHERE ID_PROGETTO =@IdProgetto  )

IF( (SELECT COUNT (*) FROM BILANCIO_AGRICOLO WHERE ID_IMPRESA = @IdImpresa AND PREVISIONALE=0) >0)
BEGIN 
SELECT TOP(1) @ID_BILANCIO = ID_BILANCIO_AGRICOLO, @DATA_PRESENTAZIONE =DATA_MODIFICA FROM BILANCIO_AGRICOLO WHERE ID_IMPRESA =@IdImpresa AND PREVISIONALE=0  ORDER BY ANNO desc
IF(@DATA_PRESENTAZIONE >= (SELECT  DATA_INSERIMENTO FROM DOMANDA_DI_PAGAMENTO WHERE ID_DOMANDA_PAGAMENTO =@ID_DOMANDA_PAGAMENTO))
 	SET @Result = 1 
ELSE
BEGIN 
	SET @ANNO_PRESENTAZIONE = YEAR(@DATA_PRESENTAZIONE)
	IF(@ANNO_PRESENTAZIONE = (SELECT YEAR(DATA_BILANCIO)+ 1 FROM BILANCIO_AGRICOLO WHERE ID_BILANCIO_AGRICOLO = @ID_BILANCIO))
		SET @Result = 1
	ELSE SET @Result = 0
END


SET @TOT_IMPIEGHI = (SELECT sum ( ISNULL(CF_CF_TERRENI,0) + ISNULL(CF_CF_IMPIANTI,0)+ ISNULL(CF_CF_PIANTAGIONI,0) + ISNULL(CF_CF_MIGLIORAMENTI,0) + 
											ISNULL(CF_CA_MACCHINE,0) + ISNULL(CF_CA_BESTIAME,0) + ISNULL(CF_IF_PARTECIPAZIONI,0) +   
											ISNULL( CC_DF_RIMANENZE,0) + ISNULL( CC_DF_ANTICIPAZIONI,0)+ ISNULL( CC_LD_CREDITI,0) + ISNULL( CC_LI_BANCA,0) +ISNULL(CC_LI_CASSA,0) ) 
											FROM BILANCIO_AGRICOLO WHERE ID_BILANCIO_AGRICOLO=@ID_BILANCIO )
SET @TOT_FONTI_FINANZIAMENTO = (SELECT sum (ISNULL( FF_PC_DEBITI_BREVE_TERMINE,0) + ISNULL( FF_PC_FORNITORI,0) + ISNULL( FF_PC_DEBITI,0) 
																		+ ISNULL( FF_PC_MUTUI,0)  + ISNULL( FF_MP_CAPITALE,0) +ISNULL( FF_MP_RISERVE,0) + ISNULL( FF_MP_UTILE,0) )  
																		FROM BILANCIO_AGRICOLO WHERE ID_BILANCIO_AGRICOLO=@ID_BILANCIO )


IF( @TOT_IMPIEGHI < 0 OR  @TOT_IMPIEGHI <> @TOT_FONTI_FINANZIAMENTO )
		SET @Result = 0
		ELSE 
			BEGIN
				
			 	SET @REDDITO_OPERATIVO = ( SELECT SUM( ISNULL( PLV_RICAVI_NETTI,0) + ISNULL( PLV_RICAVI_ATTIVITA,0) + ISNULL( PLV_RIMANENZE_FINALI,0) - ISNULL( PLV_RIMANENZE_INIZIALI,0) - ISNULL( VA_COSTI_MAT_PRIME,0) -
																				ISNULL( VA_COSTI_ATT_CONNESSE,0) - ISNULL( VA_NOLEGGI,0) - ISNULL( VA_MANUTENZIONI,0) - ISNULL( VA_SPESE_GENERALI,0) - ISNULL( VA_AFFITTI,0) - ISNULL( VA_ALTRI_COSTI , 0) - ISNULL( PN_AMM_MACCHINE,0) - 
																				ISNULL( PN_AMM_FABBRICATI,0)  - ISNULL( PN_AMM_PIANTAGIONI,0) - ISNULL( RO_SALARI,0) - ISNULL( RO_ONERI,0) ) 
																			FROM BILANCIO_AGRICOLO WHERE ID_BILANCIO_AGRICOLO=@ID_BILANCIO )
 			         IF(@REDDITO_OPERATIVO)<>0
							BEGIN 
						      SET @REDDITO_NETTO_PAC = @REDDITO_OPERATIVO + (SELECT  SUM ( ISNULL(RN_PAC_RICAVI,0) - ISNULL(RN_PAC_COSTI,0) + 
																							ISNULL(RN_PAC_PROVENTI,0) - ISNULL(RN_PAC_PERDITE,0) + ISNULL(RN_PAC_INTERESSI_ATTIVI,0) -
																							ISNULL(RN_PAC_INTERESSI_PASSIVI,0) - ISNULL(RN_PAC_IMPOSTE,0) + ISNULL(RN_PAC_CONTRIBUTI_PAC,0) )    
																							FROM BILANCIO_AGRICOLO WHERE ID_BILANCIO_AGRICOLO=@ID_BILANCIO )
								IF(@REDDITO_NETTO_PAC<0 ) SET @Result = 0
								ELSE BEGIN IF(@REDDITO_NETTO_PAC <> (SELECT CONVERT(DECIMAL(10,1), ISNULL(FF_MP_UTILE,0)) FROM BILANCIO_AGRICOLO WHERE ID_BILANCIO_AGRICOLO=@ID_BILANCIO))SET @Result = 0 END			
								--SELECT @REDDITO_NETTO_PAC	
								--SELECT CONVERT(DECIMAL(10,1), ISNULL(FF_MP_UTILE,0)) FROM BILANCIO_AGRICOLO WHERE ID_BILANCIO_AGRICOLO=@ID_BILANCIO							
							END
			 ELSE 						
				 SET @Result = 0
	 END	
END
ELSE SET @Result = 0
SELECT @Result AS RESULT
END
