



CREATE PROCEDURE [dbo].[calcoloStepVariante71_1]
(
	@ID_VARIANTE INT 
	
)
AS   
	DECLARE @RESULT INT=1,@ID_PROGETTO INT,@COSTO_CONCESSO DECIMAL(18,2)
	SELECT @ID_PROGETTO=ID_PROGETTO FROM VARIANTI WHERE ID_VARIANTE=@ID_VARIANTE	
	SELECT @COSTO_CONCESSO=COSTO_TOTALE FROM GRADUATORIA_PROGETTI WHERE ID_PROGETTO=@ID_PROGETTO

	IF ABS(@COSTO_CONCESSO-dbo.calcoloCostoTotaleProgetto(@ID_PROGETTO,1,@ID_VARIANTE))>
		(30*@COSTO_CONCESSO/100) SET @RESULT=0

	SELECT @RESULT AS RESULT
	
