
CREATE PROCEDURE dbo.calcolomartaprovasp
(
	@PARAMETRO1 INT,
	@PARAMETRO2 VARCHAR(10),
	@PARAMETRO3 DATETIME
)
AS
	DECLARE @OUTPUT1 INT, @OUTPUT2 DATETIME
	
	SELECT @OUTPUT1=COUNT(*) FROM PIANO_INVESTIMENTI WHERE ID_PROGETTO=@PARAMETRO1
	
	SELECT @OUTPUT2=MAX(DATA_MODIFICA) FROM DOMANDA_DI_PAGAMENTO WHERE ID_PROGETTO=@PARAMETRO1 AND COD_TIPO=@PARAMETRO2

	IF @OUTPUT2>@PARAMETRO3 SELECT 0
	ELSE SELECT 1
