CREATE PROCEDURE [dbo].[calcoloStepVariante_B366]
  @ID_VARIANTE int
AS
BEGIN

DECLARE @Result int, @IdProgetto int, @FASE_ISTRUTTORIA INT =1
SET @Result = 1 -- Impongo lo Step verificato
--------------------------------------------------------------------------------------------------------------

SELECT @IdProgetto  = ID_PROGETTO FROM VARIANTI WHERE ID_VARIANTE=@ID_VARIANTE
 
/*
1149	SUPERFICIE TOTALE NETTA in area D e C oggetto del Piano di gestione (Ha) 
1153	Numero siti in Natura 2000
*/ 

 -- ettari
 DECLARE @HA DECIMAL(18,2), @N2000 INT, @COSTO_MAX DECIMAL(18,2),@COSTO_PROGETTO DECIMAL(18,2)
 SELECT @HA=ISNULL(VALORE,0) FROM PRIORITA_X_PROGETTO WHERE ID_PROGETTO =@IdProgetto AND ID_PRIORITA= 1149
 SELECT @N2000=ISNULL(VALORE,0) FROM PRIORITA_X_PROGETTO WHERE ID_PROGETTO =@IdProgetto AND ID_PRIORITA= 1153
 --
 SET @RESULT=0
 
 SET @COSTO_MAX = 8000
 IF(@HA>0 AND @N2000>0)BEGIN 
	 IF(@HA>=40)
		BEGIN 
			SET @COSTO_MAX =@COSTO_MAX + 8000
			IF (@HA > 5000)SET @COSTO_MAX =@COSTO_MAX + 10000
			ELSE IF (@HA > 2000)SET @COSTO_MAX =@COSTO_MAX + 7500
			ELSE IF (@HA > 500)SET @COSTO_MAX =@COSTO_MAX + 5000
		END
	 IF(@N2000>0)BEGIN SET @COSTO_MAX= @COSTO_MAX + (@N2000 * 2000) END
	 
	 SELECT @COSTO_PROGETTO= DBO.calcoloContributoTotaleProgetto(@IdProgetto, @FASE_ISTRUTTORIA, @ID_VARIANTE)
 
	IF(@COSTO_PROGETTO>@COSTO_MAX) SET @RESULT=0
	ELSE SET @RESULT=1
  END
SELECT @RESULT
END
