CREATE PROCEDURE [dbo].[calcoloRequisitoPagamento133_6]
@ID_DOMANDA_PAGAMENTO int
AS
 BEGIN
-- CORRETTA % DELLE SPESE GENERALI IN BASE AL SOGGETTO
-- 399	Numero Iniziativa
-- DECLARE @ID_DOMANDA_PAGAMENTO int; SET @ID_DOMANDA_PAGAMENTO=1224

DECLARE @ID_VARIANTE INT, @ID_PROGETTO INT,@RESULT INT,@COUNT_SPESE INT,@DATA_MODIFICA_PAGAMENTO DATETIME,@ID_INVESTIMENTO INT,
   		@IMPORTO_RENDICONTATO_ATTUALE DECIMAL(18,2),@CONTRIBUTO_RENDICONTATO_ATTUALE DECIMAL(18,2)  ,
		@COSTO_INIZIATIVA DECIMAL(18,2), @NUM_INIZIATIVA INT, @SOGGETTO INT, @SPESE_GENERALI DECIMAL(18,2)

SET @RESULT=1 --> IMPORTO IL CONTROLLO VERIFICATO

--TROVO PROGETTO E ULTIMA VARIANTE RELATIVA A QUESTA DOMANDA DI PAGAMENTO
SELECT @DATA_MODIFICA_PAGAMENTO=DATA_MODIFICA,@ID_PROGETTO=D.ID_PROGETTO 
FROM DOMANDA_DI_PAGAMENTO D INNER JOIN 
	PROGETTO P ON D.ID_PROGETTO=P.ID_PROGETTO 
WHERE ID_DOMANDA_PAGAMENTO=@ID_DOMANDA_PAGAMENTO
SELECT @ID_VARIANTE=MAX(ID_VARIANTE) FROM VARIANTI WHERE ID_PROGETTO=@ID_PROGETTO AND APPROVATA=1 AND ANNULLATA=0 AND DATA_MODIFICA<@DATA_MODIFICA_PAGAMENTO

--CREO PIANO INVESTIMENTI VIRTUALE
DECLARE @INVESTIMENTI_VIRTUALE TABLE ([ID_INVESTIMENTO] [int] NOT NULL,
	[ID_PROGETTO] [int] NULL,
	[ID_CODIFICA_INVESTIMENTO] [int] NULL,
	[ID_DETTAGLIO_INVESTIMENTO] [int] NULL,
	IMPORTO_TOTALE_RENDICONTATO DECIMAL(18,2),
	CONTRIBUTO_TOTALE_RENDICONTATO DECIMAL(18,2))	

INSERT INTO @INVESTIMENTI_VIRTUALE
SELECT I.ID_INVESTIMENTO, I.ID_PROGETTO, I.ID_CODIFICA_INVESTIMENTO,I.ID_DETTAGLIO_INVESTIMENTO,
		Dbo.calcoloTotaleImportoRendicontatoInvestimento (I.ID_INVESTIMENTO,@ID_DOMANDA_PAGAMENTO) AS IMPORTO_TOTALE_RENDICONTATO,
		dbo.calcoloTotaleContributoRendicontatoInvestimento(I.ID_INVESTIMENTO,@ID_DOMANDA_PAGAMENTO) AS CONTRIBUTO_TOTALE_RENDICONTATO 
FROM PROGETTO P INNER JOIN PIANO_INVESTIMENTI I ON P.ID_PROGETTO=I.ID_PROGETTO
WHERE ISNULL(P.ID_PROG_INTEGRATO,P.ID_PROGETTO)=@ID_PROGETTO AND
	((@ID_VARIANTE IS NULL AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND AMMESSO=1 AND ID_VARIANTE IS NULL) OR
	(ID_VARIANTE=@ID_VARIANTE AND ISNULL(COD_VARIAZIONE,'X')!='A')) ORDER BY COD_TIPO_INVESTIMENTO

DECLARE COST_INIZ CURSOR FOR
(SELECT SUM(ISNULL(SPESE_TOTALI,1)) AS COSTO_TOTALE,SUM(ISNULL( SP_GENERALI,0)) AS SP_GENERALI,VALORE
 FROM ( SELECT PXI.VALORE, 
			  'SPESE_TOTALI'=CASE WHEN CO.CODICE NOT IN ('4','8','12','16','20') THEN SUM(IMPORTO_TOTALE_RENDICONTATO) END,
			  'SP_GENERALI' =CASE WHEN CO.CODICE IN ('4','8','12','16','20') THEN SUM(IMPORTO_TOTALE_RENDICONTATO) END   
	    FROM @INVESTIMENTI_VIRTUALE AS PI 
			 INNER JOIN VPRIORITA_X_INVESTIMENTI PXI ON PI.ID_INVESTIMENTO = PXI.ID_INVESTIMENTO AND ID_PRIORITA IN (399,858)
			 INNER JOIN CODIFICA_INVESTIMENTO CO ON CO.ID_CODIFICA_INVESTIMENTO= PI.ID_CODIFICA_INVESTIMENTO
		WHERE ID_PROGETTO = @ID_PROGETTO 
	    GROUP BY  PXI.VALORE, CODICE) AS T
 GROUP BY VALORE )

OPEN COST_INIZ
FETCH NEXT FROM COST_INIZ 
INTO @COSTO_INIZIATIVA , @SPESE_GENERALI, @NUM_INIZIATIVA
WHILE @@FETCH_STATUS = 0
BEGIN
	SET @SOGGETTO=(SELECT TOP(1) ID_VALORE FROM (
						SELECT PXI.ID_INVESTIMENTO FROM @INVESTIMENTI_VIRTUALE AS I 
							   INNER JOIN PRIORITA_X_INVESTIMENTI AS PXI ON I.ID_INVESTIMENTO = PXI.ID_INVESTIMENTO AND PXI.ID_PRIORITA IN( 399,858) AND VALORE = @NUM_INIZIATIVA
						WHERE ID_PROGETTO =@ID_PROGETTO ) AS INIZ  
					INNER JOIN PRIORITA_X_INVESTIMENTI AS PXI_SOGG ON INIZ.ID_INVESTIMENTO = PXI_SOGG.ID_INVESTIMENTO AND PXI_SOGG.ID_PRIORITA = 398 )

	IF (@COSTO_INIZIATIVA > 0)
		IF(@SOGGETTO= 571 )	BEGIN  -- SOGGETTO ESTERNO
			IF(((ISNULL(@SPESE_GENERALI,0) *100)/ISNULL(@COSTO_INIZIATIVA,0))>1)SET @RESULT =0 END
	ELSE BEGIN
		IF(@SOGGETTO= 572 ) -- SOGGETTO IN PROPRIO
			IF(((ISNULL(@SPESE_GENERALI ,0) *100)/ ISNULL(@COSTO_INIZIATIVA,0))> 3) SET @RESULT =0 
	END
FETCH NEXT FROM COST_INIZ
INTO @COSTO_INIZIATIVA,@SPESE_GENERALI,  @NUM_INIZIATIVA
END

CLOSE COST_INIZ
DEALLOCATE COST_INIZ 


SELECT @RESULT
END
