CREATE PROCEDURE [dbo].[calcoloStepVariante112_121_7]
 @ID_VARIANTE INT
AS
 
-- 112-121 Rispetto della soglia del 10% per gli adeguamenti tenici (tenuto conto degli eventuali precedenti adeguamenti tecnici autorizzati)

DECLARE @IdProgetto INT
 
SET @IdProgetto = (SELECT ID_PROGETTO FROM VARIANTI WHERE ID_VARIANTE = @ID_VARIANTE)

-- TROVO IL PROGETTO CORRELATO

DECLARE @ID_PROG_CORRENTE_121 INT, @ID_BANDO_311 INT 

SELECT DISTINCT @ID_PROG_CORRENTE_121 = p.ID_PROGETTO, @ID_BANDO_311=P.ID_BANDO FROM PROGETTO P
		INNER JOIN BANDO B ON B.ID_BANDO = P.ID_BANDO INNER JOIN ZPROGRAMMAZIONE ZP ON ZP.ID =B.ID_PROGRAMMAZIONE AND CODICE = '1.2.1.'
WHERE ID_PROG_INTEGRATO = @IdProgetto

DECLARE @SPESA_AMMESSA_GRADUATORIA DECIMAL(18,2),@SPESA_AMMESSA_ADEGUAMENTO DECIMAL(18,2) ,
		@DIFF DECIMAL(18,2),@RESULT INT

 
SET @RESULT=1 -- LO IMPONGO VERIFICATO
SET @SPESA_AMMESSA_GRADUATORIA = (SELECT SUM(ISNULL(COSTO_INVESTIMENTO,0)) + SUM(ISNULL(SPESE_GENERALI,0)) 
						FROM PIANO_INVESTIMENTI WHERE ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL AND ID_PROGETTO = @ID_PROG_CORRENTE_121)
 

SET @DIFF = ( (SELECT  SUM( CASE WHEN PI.COD_VARIAZIONE = 'M' THEN ((PI.COSTO_INVESTIMENTO) + (PI.SPESE_GENERALI)  )-(  (PI_PREC.COSTO_INVESTIMENTO) + (PI_PREC.SPESE_GENERALI))
								 WHEN PI.COD_VARIAZIONE = 'E' THEN (  (PI_PREC.COSTO_INVESTIMENTO) + (PI_PREC.SPESE_GENERALI))- ((PI.COSTO_INVESTIMENTO) + (PI.SPESE_GENERALI)  )
								 ELSE ( (PI_PREC.COSTO_INVESTIMENTO) + (PI_PREC.SPESE_GENERALI))- ((PI.COSTO_INVESTIMENTO) + (PI.SPESE_GENERALI)  )
													END )
							FROM VARIANTI  V
							INNER JOIN PIANO_INVESTIMENTI PI ON V.ID_VARIANTE= PI.ID_VARIANTE
							INNER JOIN PIANO_INVESTIMENTI PI_PREC ON PI.ID_INVESTIMENTO_ORIGINALE = PI_PREC.ID_INVESTIMENTO
							WHERE  V.COD_TIPO ='AT' AND ((V.APPROVATA  =1 AND ANNULLATA=0 AND PI.ID_PROGETTO= @ID_PROG_CORRENTE_121 
												AND V.DATA_MODIFICA < (SELECT DATA_MODIFICA FROM VARIANTI WHERE ID_VARIANTE = @ID_VARIANTE  ))
							OR (V.ID_VARIANTE = @ID_VARIANTE AND PI.ID_PROGETTO= @ID_PROG_CORRENTE_121) )  AND PI.COD_VARIAZIONE IS NOT NULL  )
						)

IF(ISNULL(@DIFF,0) > (@SPESA_AMMESSA_GRADUATORIA * 0.10))
		SET @RESULT=0

SELECT @RESULT AS RESULT
