CREATE  PROCEDURE [dbo].[calcoloStepVariante112_7]
 @ID_VARIANTE INT
AS

 DECLARE @ID_PROG_CORRENTE INT,
		@COUNT_V INT, @COUNT_M INT,
		@RESULT INT

SET @ID_PROG_CORRENTE = (SELECT ID_PROGETTO FROM VARIANTI WHERE ID_VARIANTE = @ID_VARIANTE)

SET @COUNT_V =(SELECT COUNT(*) FROM PIANO_INVESTIMENTI 
				WHERE ID_VARIANTE= @ID_VARIANTE AND (COD_VARIAZIONE = 'A' OR COD_VARIAZIONE ='N'))

SET @COUNT_M= (SELECT   COUNT(*)
  				FROM VARIANTI  V INNER JOIN 
					PIANO_INVESTIMENTI PI ON V.ID_VARIANTE= PI.ID_VARIANTE INNER JOIN
					PIANO_INVESTIMENTI PI_PREC ON PI.ID_INVESTIMENTO_ORIGINALE = PI_PREC.ID_INVESTIMENTO
				WHERE  V.COD_TIPO ='AT' AND ((V.APPROVATA  =1 AND ANNULLATA=0 AND PI.ID_PROGETTO= @ID_PROG_CORRENTE 
						AND V.DATA_MODIFICA < (SELECT DATA_MODIFICA FROM VARIANTI WHERE ID_VARIANTE = @ID_VARIANTE ))
						OR (V.ID_VARIANTE = @ID_VARIANTE AND PI.ID_PROGETTO= @ID_PROG_CORRENTE)) AND PI.COD_VARIAZIONE IS NOT NULL 
						AND (PI.CONTRIBUTO_RICHIESTO)>(PI_PREC.CONTRIBUTO_RICHIESTO) 
			 )

IF (@COUNT_V >0 OR  @COUNT_M >0) SET @RESULT =0
ELSE SET @RESULT = 1
SELECT @RESULT AS R
