CREATE PROCEDURE [dbo].[calcoloStep222_2]
(
@IdProgetto int,
@FASE_ISTRUTTORIA INT =0
)
AS
BEGIN

--declare @IdProgetto int = ....,
--		@FASE_ISTRUTTORIA INT =0

DECLARE @RESULT INT, 
		@COSTO_TOT_PROGETTO DECIMAL(18,2), 
		@CONTRIBUTO_TOT_PROGETTO DECIMAL(18,2), 
		@COSTO_ECONOMIE DECIMAL(18,2),
		@ECONOMIE_NON_PERMESSE INT,
		@COUNT INT

SET @RESULT = 1 -- PONGO LO STEP IN STATO VERIFICATO

--- //// Rispetto quota lavori in economia //// ---

-- id priorità 1181	Quota LAVORI IN ECONOMIA (€) -- numeroco livello inv


SELECT @ECONOMIE_NON_PERMESSE = (SELECT COUNT(VALORE) from PRIORITA_X_INVESTIMENTI PI INNER JOIN
									vPIANO_INVESTIMENTI VPI on VPI.ID_INVESTIMENTO = PI.ID_INVESTIMENTO INNER JOIN
									DETTAGLIO_INVESTIMENTI DI ON VPI.ID_DETTAGLIO_INVESTIMENTO = DI.ID_DETTAGLIO_INVESTIMENTO
					WHERE  
					VPI.COD_TIPO_INVESTIMENTO = 1 AND
							((VPI.ID_INVESTIMENTO_ORIGINALE IS NULL AND @FASE_ISTRUTTORIA=0 AND ID_VARIANTE IS NULL) OR
							 (VPI.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND @FASE_ISTRUTTORIA =1 AND ID_VARIANTE IS NULL)) AND
					PI.ID_PRIORITA = 1181 and  DI.COD_DETTAGLIO <> 'b' AND
					VPI.ID_PROGETTO = @IdProgetto AND VALORE > 0)

-- costo spese in economia senza spese tecniche
SELECT @COSTO_ECONOMIE = (SELECT ISNULL(SUM(COSTO_INVESTIMENTO),0) from PRIORITA_X_INVESTIMENTI PI INNER JOIN
									vPIANO_INVESTIMENTI VPI on VPI.ID_INVESTIMENTO = PI.ID_INVESTIMENTO INNER JOIN
									DETTAGLIO_INVESTIMENTI DI ON VPI.ID_DETTAGLIO_INVESTIMENTO = DI.ID_DETTAGLIO_INVESTIMENTO
					WHERE 
					VPI.COD_TIPO_INVESTIMENTO = 1 AND
							((VPI.ID_INVESTIMENTO_ORIGINALE IS NULL AND @FASE_ISTRUTTORIA=0 AND ID_VARIANTE IS NULL) OR
							 (VPI.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND @FASE_ISTRUTTORIA =1 AND ID_VARIANTE IS NULL)) AND
					PI.ID_PRIORITA = 1181 and  DI.COD_DETTAGLIO = 'b' AND
					VPI.ID_PROGETTO = @IdProgetto)


SELECT @COSTO_TOT_PROGETTO =(SELECT ISNULL(SUM(COSTO_INVESTIMENTO),0) + ISNULL(SUM (SPESE_GENERALI),0)  FROM  PIANO_INVESTIMENTI
					WHERE  
					COD_TIPO_INVESTIMENTO = 1 AND
							((ID_INVESTIMENTO_ORIGINALE IS NULL AND @FASE_ISTRUTTORIA=0 AND ID_VARIANTE IS NULL) OR
							(ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND @FASE_ISTRUTTORIA =1 AND ID_VARIANTE IS NULL)) AND
					ID_PROGETTO = @IdProgetto)


SELECT @CONTRIBUTO_TOT_PROGETTO =(SELECT ISNULL(SUM(CONTRIBUTO_RICHIESTO),0) FROM  PIANO_INVESTIMENTI
					WHERE  
					COD_TIPO_INVESTIMENTO = 1 AND
							((ID_INVESTIMENTO_ORIGINALE IS NULL AND @FASE_ISTRUTTORIA=0 AND ID_VARIANTE IS NULL) OR
							(ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND @FASE_ISTRUTTORIA =1 AND ID_VARIANTE IS NULL)) AND
					ID_PROGETTO = @IdProgetto)



IF((ISNULL(@ECONOMIE_NON_PERMESSE,0) > 0) OR ((@COSTO_TOT_PROGETTO - ISNULL(@COSTO_ECONOMIE,0)) < @CONTRIBUTO_TOT_PROGETTO))
	SET @RESULT = 0	
SELECT @RESULT
END
