CREATE PROCEDURE [dbo].[calcoloStep421_1]
@IdProgetto int,
@FASE_ISTRUTTORIA INT =0 
AS
BEGIN

 --Coerenza tra soggetto attuatore ed investimenti 
 -- IL CAPOFILA solo PUò AVERE :Ai sensi del PSR 2007-2013 - Interventi di coordinamento

/*
DECLARE 
@IdProgetto int = 9566,
@FASE_ISTRUTTORIA INT =0 

9549
9551
9566

*/

DECLARE @Result int
SET @Result = 1 -- Impongo lo Step verificato

IF((SELECT COUNT(*) as PRIVATO FROM PRIORITA_X_PROGETTO WHERE ID_VALORE = 908 AND ID_PROGETTO = @IdProgetto) =0 )
BEGIN 
	DECLARE @COUNT_COOR INT
	
	SELECT @COUNT_COOR=COUNT(*) FROM PIANO_INVESTIMENTI INV
	INNER JOIN DETTAGLIO_INVESTIMENTI D ON D.ID_DETTAGLIO_INVESTIMENTO = INV.ID_DETTAGLIO_INVESTIMENTO AND D.ID_CODIFICA_INVESTIMENTO = INV.ID_CODIFICA_INVESTIMENTO
	WHERE D.COD_DETTAGLIO ='1' AND ID_PROGETTO=@IdProgetto AND((@FASE_ISTRUTTORIA =0 AND ID_INVESTIMENTO_ORIGINALE IS NULL AND  ID_VARIANTE IS NULL)OR(@FASE_ISTRUTTORIA = 1 AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND  ID_VARIANTE IS NULL ))
	--SELECT @COUNT_COOR AS COR
	IF(@COUNT_COOR >0)SET @Result= 0
END

SELECT @Result 
END
