--
CREATE PROCEDURE [dbo].[calcoloStepVariante132_3]
(
 @ID_VARIANTE int
)
AS
BEGIN

DECLARE @CUAA VARCHAR(16),@result int, @ID_BANDO INT
SET @RESULT =1 --PONGO LO STEP VERIFICATO
--annualita 864
DECLARE @COUNT_ANNO INT, @COUNT_INV INT,@IdProgetto INT
SELECT @IdProgetto = ID_PROGETTO FROM VARIANTI WHERE ID_VARIANTE =@ID_VARIANTE 

SET  @COUNT_INV = (SELECT ((SELECT COUNT(*) as a  FROM PIANO_INVESTIMENTI PI WHERE ID_VARIANTE = @ID_VARIANTE AND ISNULL(COD_VARIAZIONE,'X') != 'A' )
					 - 
				 (SELECT COUNT(*) FROM PIANO_INVESTIMENTI AS PI 
						INNER JOIN PRIORITA_X_INVESTIMENTI ON PI.ID_INVESTIMENTO = PRIORITA_X_INVESTIMENTI.ID_INVESTIMENTO 
				  WHERE ID_VARIANTE = @ID_VARIANTE AND ISNULL(COD_VARIAZIONE,'X') != 'A' AND ID_PRIORITA IN (375,864,1081))))

IF( @COUNT_INV = 0)BEGIN
	 SELECT @COUNT_ANNO = COUNT(*) FROM (SELECT  COUNT(*) AS ANNO 
	 FROM PIANO_INVESTIMENTI AS PI INNER JOIN VPRIORITA_X_INVESTIMENTI PXI ON PI.ID_INVESTIMENTO = PXI.ID_INVESTIMENTO
	 WHERE ID_VARIANTE = @ID_VARIANTE AND ISNULL(COD_VARIAZIONE,'X') != 'A' AND  ID_PRIORITA in (375,864,1081) GROUP BY PXI.DESCRIZIONE) AS ANNO 
END 
ELSE SET @RESULT =0

SELECT @ID_BANDO =ID_BANDO FROM PROGETTO WHERE ID_PROGETTO=@IdProgetto 

IF(@ID_BANDO IN (297,265,345, 394))BEGIN IF( ISNULL(@COUNT_ANNO,0)<2) SET @RESULT =0 END---MICROFILIERA
ELSE IF( ISNULL(@COUNT_ANNO,0) <3 ) SET @RESULT =0
SELECT @RESULT AS RESULT
END
