CREATE  PROCEDURE [dbo].[calcoloStep4137_MONF_1]
@IdProgetto int, 
@FASE_ISTRUTTORIA INT = 0
AS
BEGIN

DECLARE @result int,@DICHIARAZIONE_PRIVATO int, @ALTRE_DICHIARAZIONI int, @PRIORITA int

-- Corretta selezione delle dichiarazioni facoltative

SET @result = 0 -- LO PONGO NON VERIFICATO 

SET @ALTRE_DICHIARAZIONI = (SELECT COUNT(*) FROM DICHIARAZIONI_X_PROGETTO WHERE ID_PROGETTO=@IdProgetto AND ID_DICHIARAZIONE IN (650,652))
SET @DICHIARAZIONE_PRIVATO = (SELECT COUNT(*) FROM DICHIARAZIONI_X_PROGETTO WHERE ID_PROGETTO = @IdProgetto  AND ID_DICHIARAZIONE = 658)
SELECT @PRIORITA = (SELECT COUNT(*) FROM PRIORITA_X_PROGETTO WHERE ID_PROGETTO = @IdProgetto  AND ID_PRIORITA = 1089)

IF ((((ISNULL(@DICHIARAZIONE_PRIVATO,0) = 0 ) AND (ISNULL(@PRIORITA,0) = 1)) or ((ISNULL(@DICHIARAZIONE_PRIVATO,0) = 1 ) AND (ISNULL(@PRIORITA,0) = 0))) AND (ISNULL(@ALTRE_DICHIARAZIONI,0) = 1 )) SET @result = 1
	SELECT @result AS RESULT
END
