CREATE PROCEDURE [dbo].[calcoloStep111_16]
@IdProgetto int
AS
BEGIN

-- 111 a -  Domande presentate da beneficiari della misura 221

DECLARE @Result int,@ID_IMPRESA INT, @C_221 INT 

SET @Result = 0 -- Impongo lo Step NON  verificato

 

SELECT @ID_IMPRESA =  ID_IMPRESA FROM PROGETTO WHERE ID_PROGETTO = @IdProgetto

SELECT @C_221 =COUNT(*) FROM (
	SELECT DISTINCT PB.ID_BANDO, P.ID_PROGETTO 
	FROM vBANDO_PROGRAMMAZIONE  AS PB 
		 INNER JOIN vPROGETTO AS P ON PB.ID_BANDO = P.ID_BANDO AND (P.ORDINE_FASE >= 3 AND P.COD_STATO NOT IN ('N','B'))
 	WHERE (PB.MISURA_PREVALENTE = 1) AND PB.CODICE LIKE '2.2.1.%' AND PB.COD_PSR LIKE 'PSR%'
 			AND (PB.ID_DISPOSIZIONI_ATTUATIVE IS NULL) AND ID_IMPRESA = @ID_IMPRESA ) AS B121

IF(ISNULL(@C_221 ,0) >0 ) SET @Result =1
SELECT @Result AS RESULT
END
