CREATE   PROCEDURE [dbo].[calcoloStepVariante114_1]
@ID_VARIANTE int
AS
BEGIN
  
--- 114  Contributo massimo richiesto in rapporto al periodo di consulenza
 
DECLARE @RESULT int,	@CODICE CHAR(1)	 , @CONTRIBUTO_RICHIESTO_PROGETTO DECIMAL(18,2),@IdProgetto int
set @IdProgetto = (SELECT ID_PROGETTO FROM VARIANTI WHERE ID_VARIANTE=@ID_VARIANTE)
 
SET @RESULT = 0  -- Impongo lo Step NON verificato

--------------------------------------------------------------------------------------------------------------
 SET @CODICE = (SELECT CODICE FROM VALORI_PRIORITA VP INNER JOIN PRIORITA_X_PROGETTO PP ON PP.ID_VALORE = VP.ID_VALORE WHERE PP.ID_PRIORITA = 241 AND PP.ID_PROGETTO = @IdProgetto )
 
SET  @CONTRIBUTO_RICHIESTO_PROGETTO = (SELECT     SUM(PIANO_INVESTIMENTI.CONTRIBUTO_RICHIESTO) AS CONTRIBUTO
									FROM PIANO_INVESTIMENTI INNER JOIN  PROGETTO ON PIANO_INVESTIMENTI.ID_PROGETTO = PROGETTO.ID_PROGETTO
									WHERE  ID_VARIANTE=@ID_VARIANTE AND ISNULL(COD_VARIAZIONE,'X' )!= 'A')

-- A	 € 600
IF (@CODICE = '1'  AND   @CONTRIBUTO_RICHIESTO_PROGETTO  <= 600    )
	 SET @RESULT = 1
-- B	900

ELSE IF (@CODICE = '2'  AND   @CONTRIBUTO_RICHIESTO_PROGETTO   <= 900 )  
	  SET @RESULT = 1
-- C	1200

ELSE IF (@CODICE = '3' AND   @CONTRIBUTO_RICHIESTO_PROGETTO   <= 1200 )  
	  SET @RESULT = 1
--D1	1500

ELSE IF (@CODICE = '4' AND  @CONTRIBUTO_RICHIESTO_PROGETTO  <= 1500 ) 
	  SET @RESULT = 1
 
SELECT @RESULT
 END
