CREATE PROCEDURE [dbo].[calcoloStep112_3]
@IdProgetto int
AS
-- 112 - ETA' DEL BENEFICIARIO <40 O PREDOMANDA DEFINITIVA
/*
DECLARE @IdProgetto INT
SET @IdProgetto=375
*/
DECLARE @RESULT INT, @ID_IMPRESA INT
SET @RESULT =0

-- TROVO IL CUAA DELL'IMPRESA
 SET @ID_IMPRESA =(SELECT @ID_IMPRESA FROM PROGETTO WHERE ID_PROGETTO=@IdProgetto)

DECLARE @PREDOMANDA INT
SET @PREDOMANDA=(SELECT COUNT(*) FROM PROGETTO WHERE ID_IMPRESA =@ID_IMPRESA AND FLAG_PREADESIONE=1 AND FLAG_DEFINITIVO=1 AND ID_BANDO=55)
IF @PREDOMANDA >0 SET @RESULT =1
ELSE
BEGIN
 
	IF @ID_IMPRESA IS NOT NULL 
	BEGIN 
		DECLARE @ID_PERSONA INT
		SET @ID_PERSONA=(SELECT TOP 1 ID_PERSONA 
						 FROM PERSONE_X_IMPRESE WHERE ID_IMPRESA=@ID_IMPRESA AND COD_RUOLO='R' 
						 ORDER by ID_PERSONA DESC)
 
          IF @ID_PERSONA IS NOT NULL 
			BEGIN
				IF((SELECT DATEDIFF(day, dateadd(year,40, DATA_NASCITA), GETDATE()) FROM PERSONA_FISICA WHERE ID_PERSONA=@ID_PERSONA)>0 ) 
					SET @RESULT=0
				ELSE  SET @RESULT=1
			END
	END	
END
SELECT @RESULT
