CREATE PROCEDURE [dbo].[calcoloStep126_3]
@IdProgetto int
AS
-- CONTROLLO SU DICHIARAZIONI FACOLTATIVE MISURA 126

/*
 
DECLARE @IdProgetto INT
SET @IdProgetto=375
*/
DECLARE @C INT=0,
		@RESULT INT = 0 -- NON VERIFICATO
SET @C=(SELECT COUNT(*) FROM DICHIARAZIONI_X_PROGETTO WHERE ID_PROGETTO=@IdProgetto AND ID_DICHIARAZIONE IN (730,731))
IF(@C =1)BEGIN 
	SET @C=0
	SET @C=(SELECT COUNT(*) FROM DICHIARAZIONI_X_PROGETTO WHERE ID_PROGETTO=@IdProgetto AND ID_DICHIARAZIONE IN (727,728))
	IF(@C =1)SET @RESULT =1 END

SELECT @RESULT
