CREATE PROCEDURE [dbo].[calcoloPriorita4131_FC]
@IdProgetto int,
@FASE_ISTRUTTORIA INT =0,
@IdVariante INT 
AS
BEGIN

--declare @IdProgetto int =8459,
-- @FASE_ISTRUTTORIA INT =1,
-- @IdVariante INT = 0
 
DECLARE @ID_COMUNE VARCHAR(4),
				  @Punteggio decimal (10,2),
				  @PunteggioGA decimal (10,2),
				  @PunteggioGB decimal (10,2),
				  @PunteggioGC decimal (10,2)
declare @CountGA int, @CountGB int, @CountGC int, @CountAltri INT, @COUNTINV INT

SET @CountGA=0
SET @CountGB=0
SET @CountGC=0
SET @CountAltri=0

 
--SET @COUNTINV = (SELECT COUNT(*) FROM PIANO_INVESTIMENTI I
--					                 WHERE  ID_PROGETTO = @IdProgetto 
--										AND ((@fase_istruttoria=0 AND I.ID_INVESTIMENTO_ORIGINALE IS NULL AND ID_VARIANTE IS NULL)
--										OR (@fase_istruttoria=1 AND (I.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL AND @IdVariante =0) 
--										OR (ID_VARIANTE  = @IdVariante AND @IdVariante >0 AND ISNULL(COD_VARIAZIONE, 'X' ) != 'A')))) 

SET @COUNTINV=0	 --CONTO I COMUNI DELLA DOMANDA						
DECLARE COMUNI_GAL_FLAMINIO_CESANO CURSOR FOR
(SELECT ID_COMUNE  FROM vLOCALIZZAZIONE_INVESTIMENTO AS LI 
	INNER JOIN PIANO_INVESTIMENTI I ON LI.ID_INVESTIMENTO = I.ID_INVESTIMENTO
 WHERE ID_PROGETTO = @IdProgetto 
		AND ((@fase_istruttoria=0 AND I.ID_INVESTIMENTO_ORIGINALE IS NULL AND ID_VARIANTE IS NULL)
		OR (@fase_istruttoria=1 AND (I.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL AND @IdVariante IS NULL) 
		OR (ID_VARIANTE  = @IdVariante AND @IdVariante IS NOT NULL AND ISNULL(COD_VARIAZIONE, 'X' ) != 'A'))) 
 GROUP BY ID_COMUNE)

OPEN COMUNI_GAL_FLAMINIO_CESANO
FETCH NEXT FROM COMUNI_GAL_FLAMINIO_CESANO
INTO @ID_COMUNE
WHILE @@FETCH_STATUS = 0
BEGIN	/** GRUPPO A **/
	SET @COUNTINV= @COUNTINV+1
	IF(@ID_COMUNE IN (6444,3785,3802,8640,7947,639,6080))SET @CountGA = @CountGA+1
	ELSE  /** GRUPPO B **/
	IF(@ID_COMUNE IN (3743,6528,4344,8656,7875,7710,5546,8330,5489,5339))SET @CountGB= @CountGB+  1
	ELSE   /** GRUPPO C **/
	IF(@ID_COMUNE IN (3001,5585,2068,5466,5302,5581,7798))SET @CountGC = @CountGC + 1
	ELSE  SET @CountAltri = @CountAltri+1

	FETCH NEXT FROM COMUNI_GAL_FLAMINIO_CESANO
	INTO @ID_COMUNE
END 
CLOSE COMUNI_GAL_FLAMINIO_CESANO
DEALLOCATE COMUNI_GAL_FLAMINIO_CESANO
 
IF(@COUNTINV=@CountAltri)SET @Punteggio=0
ELSE IF(@COUNTINV = @CountGC)SET @Punteggio= 0.2
ELSE  IF (@COUNTINV = @CountGB)SET @Punteggio= 0.6
ELSE IF(@COUNTINV = @CountGA) SET  @Punteggio= 1

--  IF (@CountAltri >0 ) SET @Punteggio=0
--  ELSE IF(@CountGC >0 ) SET @Punteggio= 0.2
--	ELSE IF(@CountGB >0 ) SET @Punteggio= 0.6
--	ELSE IF(@CountGA>0) SET  @Punteggio= 1

SELECT isnull(@Punteggio,0) as PUNTEGGIO
END
