CREATE PROCEDURE [dbo].[calcoloStep911_6]
(
	@IdProgetto int,
	@FASE_ISTRUTTORIA int 
)
AS
BEGIN
/* SUP A CONVERSIONE <= DEGLI HA A SUP.VITATA DA FASCICOLO */
	DECLARE @ID_FASCICOLO int, @Risultato INT =0 ,@ID_BANDO INT,@ID_IMPRESA INT,
			@TotSupVitata decimal (10,2), @MQ_CONVERSIONE DECIMAL(18,2) 
	SELECT  @ID_BANDO = ID_BANDO, @ID_IMPRESA=ID_IMPRESA FROM PROGETTO WHERE ID_PROGETTO=@IdProgetto 	
	
	SET @ID_FASCICOLO =(SELECT ISNULL (ID_FASCICOLO,  (SELECT MAX(F.ID_FASCICOLO) AS Expr1  FROM PROGETTO   				
															INNER JOIN FASCICOLO_AZIENDALE AS F ON PROGETTO.ID_IMPRESA = F.ID_IMPRESA
														WHERE(PROGETTO.ID_PROGETTO = @IdProgetto))) 
						FROM PROGETTO WHERE ID_PROGETTO = @IdProgetto)

	IF (@ID_FASCICOLO IS NOT NULL)
	BEGIN	 		
		SELECT @TotSupVitata = ISNULL(SUM(SUPERFICIE_UTILIZZATA), 0) 
		FROM TERRITORIO T
			INNER JOIN UTILIZZO_TERRA UT ON UT.ID_TERRITORIO = T.ID_TERRITORIO 
		WHERE ID_FASCICOLO = @ID_FASCICOLO AND COD_MACROUSO  IN ('200','210') --NO UNA DA MENSA
		 -- sommo gli HA scritti in quantità dell'investimento
			 
		SELECT @MQ_CONVERSIONE=SUM(QUANTITA)
		FROM PIANO_INVESTIMENTI INV 
			INNER JOIN VPROGETTO AS p ON P.ID_PROGETTO=INV.ID_PROGETTO 
			INNER JOIN DETTAGLIO_INVESTIMENTI D ON D.ID_DETTAGLIO_INVESTIMENTO = INV.ID_DETTAGLIO_INVESTIMENTO AND D.ID_CODIFICA_INVESTIMENTO = INV.ID_CODIFICA_INVESTIMENTO AND D.COD_DETTAGLIO = 'BB'
		WHERE P.ID_BANDO =@ID_BANDO AND P.ID_IMPRESA  =@ID_IMPRESA  AND (
				(INV.ID_PROGETTO = @IdProgetto AND ((@FASE_ISTRUTTORIA=0 AND INV.ID_INVESTIMENTO_ORIGINALE IS NULL)
				OR(@FASE_ISTRUTTORIA=1 AND INV.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL)))
			OR (INV.ID_PROGETTO!= @IdProgetto AND INV.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL )) -- DOMANDA PRESENTATA DELLA STESSA IMPRESA
		
	 		IF ( ISNULL(@MQ_CONVERSIONE,0) >  @TotSupVitata ) SET @Risultato=0
		   	ELSE SET @Risultato=1
	END
	ELSE SET @Risultato=0
	SELECT @Risultato AS PUNTEGGIO
END
