CREATE PROCEDURE [dbo].[calcoloStep112_121_3]
@IdProgetto int
AS
	-- 112 - 121 - verifica massimale investimento fotovoltaico:
	-- a) La somma degli investimenti aventi come specifica "fotovoltaico" non può superare i 400000€
    -- b) Il contributo ammissibile sul fotovoltatico non può superare il 30% del contributo ammissibile totale

DECLARE @RESULT INT
--SET @RESULT =1
/*
DECLARE @IdProgetto INT
SET @IdProgetto=356*/

-- TROVO IL PROGETTO INTEGRATO
DECLARE @ID_PROG_CORRENTE INT
SELECT @ID_PROG_CORRENTE= P.ID_PROGETTO FROM PROGETTO P 
	   INNER JOIN BANDO B ON B.ID_BANDO = P.ID_BANDO INNER JOIN ZPROGRAMMAZIONE ZP ON ZP.ID =B.ID_PROGRAMMAZIONE AND CODICE = '1.2.1.'
WHERE ID_PROG_INTEGRATO = @IdProgetto  

DECLARE @COSTO_INVESTIMENTI_FOTOVOLTAICI DECIMAL(18,2), @ID_SPECIFICA INT,
		@COSTO_INVESTIMENTI_TOTALE DECIMAL(18,2), @COSTO_INVESTIMENTO DECIMAL(18,2) 

DECLARE INVESTIMENTO CURSOR FOR
(SELECT COSTO_INVESTIMENTO,/*CONTRIBUTO_RICHIESTO,*/ID_SPECIFICA_INVESTIMENTO 
 FROM PIANO_INVESTIMENTI I
	  INNER JOIN PROGETTO P ON I.ID_PROGETTO=P.ID_PROGETTO 
 WHERE I.ID_PROGETTO=@ID_PROG_CORRENTE AND COD_TIPO_INVESTIMENTO = 1 AND 
	  ((FLAG_DEFINITIVO =0 AND ID_INVESTIMENTO_ORIGINALE IS NULL)OR(FLAG_DEFINITIVO = 1 AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL )))

OPEN INVESTIMENTO
FETCH NEXT FROM INVESTIMENTO
INTO @COSTO_INVESTIMENTO,/*@CONTRIBUTO,*/@ID_SPECIFICA
WHILE @@FETCH_STATUS = 0
BEGIN
	SET @COSTO_INVESTIMENTI_TOTALE=@COSTO_INVESTIMENTI_TOTALE+@COSTO_INVESTIMENTO 
	IF(@ID_SPECIFICA=238 or @ID_SPECIFICA=326 OR @ID_SPECIFICA=1014 OR @ID_SPECIFICA= 1395 OR @ID_SPECIFICA= 2729)
	BEGIN
		SET @COSTO_INVESTIMENTI_FOTOVOLTAICI=@COSTO_INVESTIMENTI_FOTOVOLTAICI+@COSTO_INVESTIMENTO 
	END
	FETCH NEXT FROM INVESTIMENTO
	INTO @COSTO_INVESTIMENTI_TOTALE,/*@CONTRIBUTO_TOTALE,*/@ID_SPECIFICA
END
CLOSE INVESTIMENTO
DEALLOCATE INVESTIMENTO

SET @RESULT=CASE WHEN @COSTO_INVESTIMENTI_FOTOVOLTAICI>400000 OR @COSTO_INVESTIMENTI_FOTOVOLTAICI > (@COSTO_INVESTIMENTI_TOTALE*0.3)THEN 0
				 ELSE 1 END
SELECT @RESULT
