---CONTROLLO REQUISITI DI FILIERA
 
CREATE  PROCEDURE [dbo].[calcoloStepMF_2]
@IdProgetto int
AS
BEGIN
--262,263,264,265 macro filiera
--232,233,234,277,284 FILIERA LOCALE
-- FILIERA LOCALE CONTROLLO COMPILAZIONE QUADRO PRODOTTO TRASFORMATI

--DECLARE @IdProgetto int
--SET @IdProgetto = 10359


DECLARE  @RESULT INT , @ID_BANDO INT, @C INT
SET @ID_BANDO = (SELECT ID_BANDO FROM PROGETTO WHERE ID_PROGETTO =@IdProgetto )
SET @RESULT =0 --PONGO LO STEP NN VERIFICATO
 IF((SELECT COUNT(*)  FROM PRIORITA_X_PROGETTO PP  WHERE ID_PRIORITA IN (374) AND  ID_PROGETTO =@IdProgetto ) =1)
BEGIN
-- MACROFILIERE

IF((SELECT COUNT(*)  FROM PRIORITA_X_PROGETTO PP  WHERE ID_PRIORITA IN ( 262,263,264,265) AND ID_PROGETTO =@IdProgetto ) >= 1)
  BEGIN 
 --- CONTROLLO RUOLO SITRA;  CONTROLLO RUOLO OPERATIVO; CONTROLLO SELEZIONE FILEIRA LOCALE
    IF((SELECT COUNT(*)  FROM PRIORITA_X_PROGETTO PP  WHERE ID_PRIORITA IN (390,391, 374) AND  ID_PROGETTO =@IdProgetto ) =3   )
		BEGIN  SET @RESULT =1  END
    ELSE  
		BEGIN
			 IF((SELECT COUNT(*)  FROM PRIORITA_X_PROGETTO PP  WHERE ID_PRIORITA IN (391,374) AND  ID_PROGETTO =@IdProgetto ) =2 
					AND (SELECT  COUNT(*) FROM PRIORITA_X_PROGETTO WHERE ID_PRIORITA IN ( 262)  AND  ID_PROGETTO =@IdProgetto ) >0)
 			   	SET @RESULT =1  
		END
END
END
 

 IF((SELECT COUNT(*)  FROM PRIORITA_X_PROGETTO PP  WHERE ID_PRIORITA IN (406) AND  ID_PROGETTO =@IdProgetto ) =1)
BEGIN
-- FILIERE LOCALI-- CONTROLLO SIATEMA DI QUALITA
IF((SELECT COUNT(*)  FROM PRIORITA_X_PROGETTO PP  WHERE ID_PRIORITA IN (  232,233,234,277,284) AND ID_PROGETTO =@IdProgetto ) >= 1)
  BEGIN 
 --- CONTROLLO RUOLO SITRA;  CONTROLLO RUOLO OPERATIVO; CONTROLLO SELEZIONE FILEIRA LOCALE
    IF((SELECT COUNT(*)  FROM PRIORITA_X_PROGETTO PP  WHERE ID_PRIORITA IN (390,391, 406) AND  ID_PROGETTO =@IdProgetto ) =3   )
		BEGIN  SET @RESULT =1  END
    ELSE  
		BEGIN
			 IF((SELECT COUNT(*)  FROM PRIORITA_X_PROGETTO PP  WHERE ID_PRIORITA IN (391,406) AND  ID_PROGETTO =@IdProgetto ) =2 
					AND (SELECT  COUNT(*) FROM PRIORITA_X_PROGETTO WHERE ID_PRIORITA IN ( 284)  AND  ID_PROGETTO =@IdProgetto ) =0)
 			   	SET @RESULT =1  
		END
END

--PRIORITA: 428-superficie di filiera
SET @C  = (SELECT COUNT(*) FROM PROGETTO P INNER JOIN PRIORITA_X_PROGETTO PP ON PP.ID_PROGETTO = P.ID_PROGETTO AND ID_PRIORITA = 428
			WHERE ID_IMPRESA = (SELECT ID_IMPRESA FROM PROGETTO P WHERE ID_PROGETTO =@IdProgetto ) )
IF(ISNULL(@C,0) =0)SET @RESULT =0 
END

 SELECT   @RESULT  AS RESULT
END
