CREATE PROCEDURE [dbo].[calcoloStep413_FERM_1]
@IdProgetto int, 
@FASE_ISTRUTTORIA INT =0
AS
BEGIN

-- Comuni GAL Fermano in zona montana aiuto addizionale pari al 10%
-- Amandola, Montefalcone Appennino, Montefortino, Santa Vittoria in Matenano, Smerillo

DECLARE @result int, @CONTATOREA INT, @CONTATOREB INT
SET @result = 1



-- VERIFICO SE SELEZIONA L'AIUTO ADDIZIONALE QUANDO DOVUTO
SELECT @CONTATOREA = COUNT(*)
FROM         vLOCALIZZAZIONE_INVESTIMENTO AS LI
LEFT JOIN PRIORITA_X_INVESTIMENTI AS PI ON LI.ID_INVESTIMENTO = PI.ID_INVESTIMENTO AND ID_PRIORITA = 547
INNER JOIN PIANO_INVESTIMENTI I ON LI.ID_INVESTIMENTO = I.ID_INVESTIMENTO
WHERE 	  ID_PROGETTO = @IdProgetto AND ( (I.ID_INVESTIMENTO_ORIGINALE IS NULL AND @FASE_ISTRUTTORIA=0 AND ID_VARIANTE IS NULL)OR
( I.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND @FASE_ISTRUTTORIA =1 AND ID_VARIANTE IS NULL))  
AND ID_COMUNE IN (252,10596,5485,10608,5501,10609,8760,10633,8301,10630) AND PI.ID_PRIORITA IS NULL

IF (@CONTATOREA > 0) SET @result = 0
ELSE
BEGIN 
-- VERIFICO SE SELEZIONA L'AIUTO ADDIZIONALE QUANDO NON DOVUTO
SELECT @CONTATOREB = COUNT(*)
FROM         vLOCALIZZAZIONE_INVESTIMENTO AS LI
INNER JOIN PRIORITA_X_INVESTIMENTI AS PI ON LI.ID_INVESTIMENTO = PI.ID_INVESTIMENTO AND ID_PRIORITA = 547
INNER JOIN PIANO_INVESTIMENTI I ON LI.ID_INVESTIMENTO = I.ID_INVESTIMENTO
WHERE 	  ID_PROGETTO = @IdProgetto AND ( (I.ID_INVESTIMENTO_ORIGINALE IS NULL AND @FASE_ISTRUTTORIA=0 AND ID_VARIANTE IS NULL)OR
( I.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND @FASE_ISTRUTTORIA =1 AND ID_VARIANTE IS NULL))
AND ID_COMUNE NOT IN (252,10596,5485,10608,5501,10609,8760,10633,8301,10630)  

IF (@CONTATOREB > 0) SET @result = 0
END

SELECT @result AS RESULT

END
