CREATE  PROCEDURE [dbo].[calcoloStepPagamento311_3]
@IdProgetto int,
@IdDomandaPagamento int =NULL
AS
BEGIN

	-- 311 a PSR - Nel caso in cui al beneficiario fosse già stato liquidato l'anticipo l'importo del SAL deve corrispondere ad una spesa compresa tra il 51% e il 70% dell'investimento ammesso

	DECLARE @ID_VARIANTE INT, @RESULT INT
    DECLARE @CONTRIBUTO_PROGETTO DECIMAL(10,2),
						@CONTRIBUTO_RICHIESTO_PAG DECIMAL(10,2), @COUNT_ANT INT

SET @RESULT = 1 -- IMPONGO LO STEP VERIFICATO		 
SET @COUNT_ANT = (SELECT COUNT(*) FROM DOMANDA_DI_PAGAMENTO DP WHERE COD_TIPO = 'ANT' AND ID_PROGETTO = @IdProgetto AND APPROVATA= 1 AND  ANNULLATA =0 )

IF(@COUNT_ANT> 0)
BEGIN 
	SET @ID_VARIANTE =  (SELECT MAX(ID_VARIANTE) FROM VARIANTI WHERE ID_PROGETTO = @IdProgetto AND APPROVATA =1 AND ANNULLATA =0)
	SET @CONTRIBUTO_PROGETTO = ISNULL((SELECT dbo.[calcoloContributoTotaleProgettoCorrelato] (@IdProgetto, 1, @ID_VARIANTE)), 0)
	SET @CONTRIBUTO_RICHIESTO_PAG = (SELECT SUM(ISNULL(CONTRIBUTO_AMMESSO,0)) + SUM(ISNULL(CONTRIBUTO_AMMESSO_RECUPERO_ANTICIPO,0)) 
																					FROM PAGAMENTI_RICHIESTI WHERE ID_DOMANDA_PAGAMENTO =@IdDomandaPagamento)
	IF(@CONTRIBUTO_RICHIESTO_PAG < (@CONTRIBUTO_PROGETTO * 0.51 )) SET @RESULT = 0
	IF(@CONTRIBUTO_RICHIESTO_PAG > (@CONTRIBUTO_PROGETTO * 0.70 )) SET @RESULT = 0
END

SELECT @RESULT
END
