CREATE PROCEDURE [dbo].[RAEUltimaDomandaPagamentoConStorico]
AS
SELECT ISNULL(p.ID_PROG_INTEGRATO,p.ID_PROGETTO) AS NUMERO_DOMANDA, P.STATO ,
P.ID_BANDO, 
INV.MISURA AS CODICE_MISURA ,
PR.DESCRIZIONE AS DESCRIZIONE_MISURA , 
zOB_MISURA.CODICE COD_OB_MISURA , zOB_MISURA.DESCRIZIONE AS OBIETTIVO_MISURA

, PR_INTERV.CODICE AS COD_INTERVENTO,   PR_INTERV.DESCRIZIONE,
INV.COD_STP, STP.DESCRIZIONE AS STP, 
INV.CODIFICA_INVESTIMENTO, INV.DETTAGLIO_INVESTIMENTI, INV.SPECIFICA_INVESTIMENTI,
INV.DESCRIZIONE AS DESC_INVESTIMENTO, 
INV.SETTORE_PRODUTTIVO 
, PRS.DESCRIZIONE AS PRIORITA_SETTORIALE,CASE WHEN pxi.ID_PRIORITA  IS NOT NULL THEN  'SI' ELSE 'NO' END AS NATURA_2000 ,pxi.ID_PRIORITA ,
INV.QUANTITA, U.DESCRIZIONE AS UNITA_MISURA,
INV.COSTO_INVESTIMENTO + ISNULL(INV.SPESE_GENERALI,0) as costo_ammesso_nellUltimoPiano, INV.CONTRIBUTO_RICHIESTO as Contributo_ammesso_da_istruttoria
,dbo.calcoloStoricoImportoRichiestoInvestimento(inv.ID_INVESTIMENTO, DP_MAX.ID_DOMANDA_MAX )Costo_richiesto_pagamento
,dbo. calcoloStoricoContributoRichiestoInvestimento(inv.ID_INVESTIMENTO, DP_MAX.ID_DOMANDA_MAX )Contributo_richiesto_pagamento

,dbo.calcoloTotaleImportoRendicontatoAmmessoInvestimento (inv.ID_INVESTIMENTO, DP_MAX.ID_DOMANDA_MAX )Costo_Ammesso_pagamento
, dbo.calcoloAmmontareErogatoInvestimento(inv.ID_INVESTIMENTO, DP_MAX.ID_DOMANDA_MAX+1 )Contributo_ammesso_pagamento, 
DP_MAX .ID_DOMANDA_MAX,inv.ID_INVESTIMENTO

FROM  vPROGETTO  P 
	LEFT JOIN (SELECT MAX(ID_VARIANTE)ID_VARIANTE_MAX, ID_PROGETTO FROM VARIANTI WHERE APPROVATA = 1 AND ANNULLATA =0 /* AND COD_TIPO IN ('AR','VA')*/ GROUP BY ID_PROGETTO)VA_MAX ON VA_MAX.ID_PROGETTO =  ISNULL(P.ID_PROG_INTEGRATO,  P.ID_PROGETTO)
	LEFT JOIN VARIANTI V ON V.ID_VARIANTE = VA_MAX.ID_VARIANTE_MAX 
	INNER JOIN VPIANO_INVESTIMENTI INV ON INV.ID_PROGETTO = P.ID_PROGETTO AND ((V.ID_VARIANTE IS NULL AND INV.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND INV.ID_VARIANTE IS NULL)  OR (V.ID_VARIANTE IS NOT NULL AND INV.ID_VARIANTE = V.ID_VARIANTE))
INNER JOIN BANDO B ON P.ID_BANDO = B.ID_BANDO	
INNER JOIN vzPROGRAMMAZIONE PR ON B.ID_PROGRAMMAZIONE = PR.ID
	LEFT JOIN vzSTP STP ON INV.COD_STP = STP.CODICE AND B.ID_PROGRAMMAZIONE = STP.ID_PROGRAMMAZIONE
	                      LEFT JOIN
                      zOB_MISURA ON inv.ID_OBIETTIVO_MISURA = zOB_MISURA.ID
                     INNER JOIN vzPROGRAMMAZIONE PR_INTERV ON INV.ID_PROGRAMMAZIONE = PR_INTERV.ID
 
	LEFT JOIN PRIORITA_SETTORIALI PRS ON PRS.ID_PRIORITA_SETTORIALE = INV.ID_PRIORITA_SETTORIALE
	LEFT JOIN UNITA_DI_MISURA U ON U.ID_UNITA_MISURA= INV.ID_UNITA_MISURA
	LEFT JOIN (select MAX(ID_DOMANDA_PAGAMENTO) ID_DOMANDA_MAX,ID_PROGETTO FROM DOMANDA_DI_PAGAMENTO  WHERE COD_TIPO !='ANT' AND APPROVATA =1 AND ANNULLATA =0 GROUP BY ID_PROGETTO ) DP_MAX ON DP_MAX.ID_PROGETTO= ISNULL(P.ID_PROG_INTEGRATO,  P.ID_PROGETTO)
	left join PRIORITA_X_INVESTIMENTI pxi on pxi.ID_INVESTIMENTO = inv.ID_INVESTIMENTO and ID_PRIORITA in (25,166,167,179,192,420,436,524,540,552,626,634,644,727) 
--WHERE P.ID_PROG_INTEGRATO = 400
WHERE P.ID_BANDO = 493
ORDER BY P.ID_PROGETTO
