CREATE PROCEDURE [dbo].[RptAnagrafica]
@CUAA VARCHAR(16) = NULL, 
@ID_IMPRESA INT = NULL
AS
BEGIN	
	
	-- utilizzato in tutti i report in cui compare l'anagrafica, meno i report di presentazione della domanda di aiuto

	---- Dati generali
	--DECLARE @Count int
	--SET @Count = (SELECT COUNT(ID_IMPRESA) FROM dbo.IMPRESA WHERE 
	--				(@CUAA IS NULL AND ID_IMPRESA = @ID_IMPRESA) OR (@CUAA IS NOT NULL AND CUAA = @CUAA))

	SELECT I.CUAA, I.CODICE_FISCALE, RAGIONE_SOCIALE, IND.VIA, IND.COMUNE, IND.CAP, IND.SIGLA, 
	PXP.CODICE_FISCALE as CF_RAPPR_LEGALE, PXP.NOME, PXP.COGNOME, PXP.DATA_NASCITA, 
	PXP.SIGLA AS PROV_NASCITA, PXP.COMUNE AS COMUNE_NASCITA, RUOLO, 
	REGISTRO_IMPRESE_NUMERO, REA_NUMERO, REA_ANNO, COD_PROVINCIA AS ISTAT_PROVINCIA, ISTAT AS ISTAT_COMUNE,
	TELEFONO, EMAIL, DIMENSIONE_IMPRESA, FORMA_GIURIDICA, 
	IND.COD_REGIONE, IND.SIGLA AS PROVINCIA, IND.PEC, IND.LOCALITA, IND.FAX, I.COD_FORMA_GIURIDICA
	FROM vIMPRESA I 
	LEFT JOIN VINDIRIZZARIO IND ON I.ID_SEDELEGALE_ULTIMO = IND.ID_INDIRIZZARIO
	LEFT JOIN vPERSONE_X_IMPRESE PXP ON I.ID_RAPPRLEGALE_ULTIMO = PXP.ID_PERSONE_X_IMPRESE
	WHERE (@CUAA IS NULL AND I.ID_IMPRESA = @ID_IMPRESA) OR (@CUAA IS NOT NULL AND CUAA = @CUAA)
		    
END
