CREATE PROCEDURE [dbo].[RptBandoPagamentoAll] 
AS
	--ID progetto	Barcode SIAN - AIUTO	CUAA	Misura	Scadenza bando	Stato attuale domanda	
	--Data finanziabilità	Spesa ammessa - finanziabilità	Contributo ammesso - finanziabilità	Data Anticipo	
	--Barcode SIAN – Pagamento Anticipo	Contributo ammesso - Anticipo	Data SAL	Barcode SIAN – Pagamento SAL	
	--Spesa ammessa - SAL	Contributo ammesso - SAL	Data SALDO	Barcode SIAN – Pagamento SALDO	Spesa ammessa - SALDO	
	--Contributo ammesso - SALDO
	SELECT ISNULL(P.ID_PROG_INTEGRATO, P.ID_PROGETTO) AS NUM_DOMANDA,
	CASE WHEN DISPOSIZIONI_ATTUATIVE = 1 
		 THEN (SELECT COD_AGEA FROM PROGETTO WHERE ID_PROGETTO = P.ID_PROG_INTEGRATO)
		 ELSE p.cod_agea END AS BARCODE_DOMANDA_AIUTO,
	BP.CODICE AS MISURA, 
	P.ID_BANDO AS ID_BANDO,
	I.CUAA, 
	I.RAGIONE_SOCIALE, 
	C1.NOMINATIVO AS ISTRUTTORE_ATTUALE, 
	(CASE WHEN P.COD_STATO = 'F' AND (GF.FINANZIABILITA = 'P' OR G.FINANZIABILITA = 'P') THEN 'Parzialmente Finanziabile' 
				WHEN DISPOSIZIONI_ATTUATIVE = 1 THEN PROG_PRINC.STATO ELSE P.STATO END) AS STATO_ATTUALE, 
	P.PROVINCIA_DI_PRESENTAZIONE,
	(CASE WHEN DISPOSIZIONI_ATTUATIVE = 1 THEN PROG_PRINC.BANDO ELSE B.DESCRIZIONE END) AS BANDO,
	B.IMPORTO_DI_MISURA AS BUDGET,
	ISNULL(convert(VARCHAR(16), DATA_SCADENZA, 103), '') AS DATA_SCADENZA,
	dbo.calcoloCostoTotaleProgettoCorrelato(P.ID_PROGETTO, 0, NULL) AS COSTO_RICHIESTO,
	ISNULL(dbo.calcoloContributoTotaleProgettoCorrelato(P.ID_PROGETTO, 0, NULL), 0)
	+ ISNULL(DBO.calcoloPremioContoCapitale(P.ID_PROGETTO, 0, NULL), 0) AS CONTRIBUTO_RICHIESTO,
	CASE WHEN P.COD_STATO IN ('B', 'Q') THEN 0 ELSE dbo.calcoloCostoTotaleProgettoCorrelato(P.ID_PROGETTO, 1, NULL) END AS COSTO_AMMESSO,
	CASE WHEN P.COD_STATO IN ('B', 'Q') THEN 0 ELSE ISNULL(dbo.calcoloContributoTotaleProgettoCorrelato(P.ID_PROGETTO, 1, NULL), 0)
	+ ISNULL(DBO.calcoloPremioContoCapitale(P.ID_PROGETTO, 1, NULL), 0) END AS CONTRIBUTO_AMMESSO,
	ISNULL(convert(VARCHAR(16), (SELECT TOP 1 DATA -- PERMETTE DI PRENDERE LA PRIMA DATA DI GRADUATORIA
			FROM PROGETTO_STORICO M 
			INNER JOIN ( 
			SELECT MIN(ID) ID_MIN, ID_PROGETTO, COD_STATO
			FROM PROGETTO_STORICO 
			WHERE ID_PROGETTO = P.ID_PROGETTO AND COD_STATO IN ('F', 'N')
			GROUP BY ID_PROGETTO, COD_STATO) AS MO ON M.ID = MO.ID_MIN
			ORDER BY ID DESC), 103), '') AS DATA_FINANZIABILITA, 
	CASE WHEN P.COD_STATO = 'N' THEN 0 ELSE ISNULL(gf.COSTO,g.COSTO) END  SPESA_GRADUATORIA,
	CASE WHEN P.COD_STATO = 'N' THEN 0 ELSE ISNULL(GF.CONTR,G.CONTR) END AS CONTRIBUTO_GRADUATORIA, 
	A.DATA DATA_ATTO_DECADENZA, A.REGISTRO REGISTRO_DECADENZA, A.NUMERO NUMERO_ATTO_DECADENZA,
	PS.SEGNATURA AS SEGNATURA_RINUNCIA,
	E.DESCRIZIONE AS ENTE_BANDO,
	PP.VALORE_DESC AS FILIERA,
	
	ISNULL(DP_ANT.BARCODE, '') as BARCODE_DOMANDA_ANTICIPO,
	ISNULL(convert(VARCHAR(16), DP_ANT.DATA_MODIFICA, 103), '') as DATA_PRESENTAZIONE_ANTICIPO, 
	ISNULL(DP_ANT.SEGNATURA, '') AS SEGNATURA_PRESENTAZIONE_ANTICIPO, 
	ISNULL(DP_ANT.SEGNATURA_APPROVAZIONE, '') AS SEGNATURA_APPROVAZIONE_ANTICIPO, 
	ISNULL(DP_ANT.SEGNATURA_SECONDA_APPROVAZIONE, '') SEGNATURA_SECONDA_APPROVAZIONE_ANTICIPO, 
	CASE WHEN DP_ANT.APPROVATA = 1 THEN 'SI' WHEN DP_ANT.APPROVATA = 0 THEN 'NO' ELSE '' END AS APPROVATA_ANTICIPO, 
	DP_ANT.ID_ELENCO_REGIONALE AS ID_ELENCO_REGIONALE_ANTICIPO, 
	DP_ANT.ID_ELENCO_PAGAMENTO AS ID_ELENCO_PROVINCIALE_ANTICIPO,
	ISNULL(DP_ANT.CONTRIBUTO_RICHIESTO, 0) AS CONTRIBUTO_RICHIESTO_ANTICIPO,
	ISNULL(DP_ANT.IMPORTO_AMMESSO, 0) AS CONTRIBUTO_AMMESSO_ANTICIPO,
	DP_ANT.NUM_FIDEJUSSIONE AS NUM_FIDEJUSSIONE_ANT, DP_ANT.BAR_FIDEJUSSIONE BAR_FIDEJUSSIONE_ANT,  DP_ANT.RAG_FIDEJUSSIONE RAG_FIDEJUSSIONE_ANT, 
	DP_ANT.DATA_FIDEJUSSIONE AS DATA_FIDEJUSSIONE_ANT, DP_ANT.IMPORTO_FIDEJUSSIONE AS IMPORTO_FIDEJUSSIONE_ANT,
	DP_ANT.NUM_DECRETO AS NUM_DECRETO_ANT, DP_ANT.DATA_DECRETO AS DATA_DECRETO_ANT, DP_ANT.IMPORTO_LIQUIDATO AS IMPORTO_LIQUIDATO_ANT,
	DP_ANT.ISTRUTTORE AS ISTRUTTORE_ANT, 
	DP_ANT.OPERATORE OPERATORE_PRESENTAZIONE_ANT, 
	DP_ANT.ENTE AS ENTE_OPERATORE_PRESENTAZIONE_ANT,

	ISNULL(DP_SAL.BARCODE, '') AS BARCODE_DOMANDA_SAL,
	ISNULL(convert(VARCHAR(16), DP_SAL.DATA_MODIFICA, 103), '')  AS DATA_PRESENTAZIONE_SAL, 
	ISNULL(DP_SAL.SEGNATURA, '') AS SEGNATURA_PRESENTAZIONE_SAL, 
	ISNULL(DP_SAL.SEGNATURA_APPROVAZIONE, '') AS SEGNATURA_APPROVAZIONE_SAL, 
	ISNULL(DP_SAL.SEGNATURA_SECONDA_APPROVAZIONE, '') AS SEGNATURA_SECONDA_APPROVAZIONE_SAL, 
	CASE WHEN DP_SAL.APPROVATA =  1 THEN 'SI' WHEN DP_SAL.APPROVATA =  0 THEN 'NO' ELSE '' END  AS APPROVATA_SAL, 
	DP_SAL.ID_ELENCO_REGIONALE AS ID_ELENCO_REGIONALE_SAL, 
	DP_SAL.ID_ELENCO_PAGAMENTO AS ID_ELENCO_PROVINCIALE_SAL,
	ISNULL(DP_SAL.IMPORTO_RICHIESTO, 0) SPESA_RICHIESTA_SAL,
	ISNULL(DP_SAL.CONTRIBUTO_RICHIESTO, 0) as CONTRIBUTO_RICHIESTO_SAL,
	ISNULL(DP_SAL.SPESA_AMMESSA, 0) AS SPESA_AMMESSA_SAL,
	ISNULL(DP_SAL.IMPORTO_AMMESSO, 0) AS IMPORTO_AMMESSO_SAL,
	CASE WHEN DP_SAL.PREDISPOSTA_A_CONTROLLO =  1 THEN  'SI' ELSE 'NO' END PREDISPOSTA_A_CONTROLLO_SAL, 
	DP_SAL.CONTROLLO_INLOCO_ESITO CONTROLLO_INLOCO_ESITO_SAL,
	DP_SAL.NUM_FIDEJUSSIONE AS NUM_FIDEJUSSIONE_SAL, DP_SAL.BAR_FIDEJUSSIONE BAR_FIDEJUSSIONE_SAL,  DP_SAL.RAG_FIDEJUSSIONE RAG_FIDEJUSSIONE_SAL, 
	DP_SAL.DATA_FIDEJUSSIONE AS DATA_FIDEJUSSIONE_SAL, DP_SAL.IMPORTO_FIDEJUSSIONE AS IMPORTO_FIDEJUSSIONE_SAL,
	DP_SAL.NUM_DECRETO AS NUM_DECRETO_SAL, DP_SAL.DATA_DECRETO AS DATA_DECRETO_SAL, DP_SAL.IMPORTO_LIQUIDATO AS IMPORTO_LIQUIDATO_SAL,
	DP_SAL.ISTRUTTORE AS ISTRUTTORE_SAL,
	DP_SAL.OPERATORE OPERATORE_PRESENTAZIONE_SAL, 
	DP_SAL.ENTE AS ENTE_OPERATORE_PRESENTAZIONE_SAL,


	ISNULL(DP_SLD.BARCODE, '') AS BARCODE_DOMANDA_SALDO,
	ISNULL(convert(VARCHAR(16), DP_SLD.DATA_MODIFICA, 103), '') AS DATA_PRESENTAZIONE_SALDO, 
	ISNULL(DP_SLD.SEGNATURA, '') AS SEGNATURA_PRESENTAZIONE_SALDO, 
	ISNULL(DP_SLD.SEGNATURA_APPROVAZIONE, '') AS SEGNATURA_APPROVAZIONE_SALDO, 
	ISNULL(DP_SLD.SEGNATURA_SECONDA_APPROVAZIONE, '') AS SEGNATURA_SECONDA_APPROVAZIONE_SALDO, 
	CASE WHEN DP_SLD.APPROVATA =  1 THEN 'SI' WHEN DP_SLD.APPROVATA =  0 THEN 'NO' ELSE '' END AS APPROVATA_SALDO, 
	DP_SLD.ID_ELENCO_REGIONALE AS ID_ELENCO_REGIONALE_SALDO, 
	DP_SLD.ID_ELENCO_PAGAMENTO AS ID_ELENCO_PROVINCIALE_SALDO,
	ISNULL(DP_SLD.IMPORTO_RICHIESTO, 0) AS SPESA_RICHIESTA_SALDO, 
	CONTRIBUTO_RICHIESTO_SALDO = ISNULL(DP_SLD.CONTRIBUTO_RICHIESTO, 0)
	+CASE WHEN P.ID_PROGETTO=P.ID_PROG_INTEGRATO 
		THEN ISNULL(dbo.calcoloPremioContoCapitaleSaldo(DP_SLD.ID_DOMANDA_PAGAMENTO,0),0) 
		ELSE 0 END,
	ISNULL(DP_SLD.SPESA_AMMESSA, 0) AS SPESA_AMMESSA_SALDO,
	ISNULL(DP_SLD.IMPORTO_AMMESSO, 0) AS CONTRIBUTO_AMMESSO_SALDO,
	CASE WHEN DP_SLD.PREDISPOSTA_A_CONTROLLO =  1 THEN  'SI' ELSE 'NO' END PREDISPOSTA_A_CONTROLLO_SALDO, 
	DP_SLD.CONTROLLO_INLOCO_ESITO CONTROLLO_INLOCO_ESITO_SALDO,
	DP_SLD.NUM_DECRETO AS NUM_DECRETO_SLD, DP_SLD.DATA_DECRETO AS DATA_DECRETO_SLD, DP_SLD.IMPORTO_LIQUIDATO AS IMPORTO_LIQUIDATO_SLD,
	DP_SLD.ISTRUTTORE AS ISTRUTTORE_SLD,
	DP_SLD.OPERATORE OPERATORE_PRESENTAZIONE_SLD, 
	DP_SLD.ENTE AS ENTE_OPERATORE_PRESENTAZIONE_SLD

	FROM vBANDO AS B INNER JOIN vzPROGRAMMAZIONE BP ON B.ID_PROGRAMMAZIONE = BP.ID AND BP.COD_PSR='PSR20072013' AND BP.ATTIVAZIONE_BANDI=1
	INNER JOIN VPROGETTO AS P ON P.ID_BANDO = B.ID_BANDO
	LEFT JOIN (SELECT SP.ID_PROGETTO, SP.ID_BANDO, SP.ID_PROG_INTEGRATO, SP.STATO, SP.SEGNATURA, BA.DESCRIZIONE AS BANDO 
						FROM VPROGETTO SP
						INNER JOIN vBANDO BA ON SP.ID_BANDO = BA.ID_BANDO
						WHERE SP.ID_PROGETTO = SP.ID_PROG_INTEGRATO) 
								AS PROG_PRINC ON P.ID_PROG_INTEGRATO = PROG_PRINC.ID_PROGETTO --PER VEDERE LO STATO E IL BANDO DEL PROGETTO PRINCIPALE IN CASO DI BANDO MULTIMISURA
	LEFT JOIN PROGETTO_SEGNATURE PS ON ISNULL(P.ID_PROG_INTEGRATO, P.ID_PROGETTO) = PS.ID_PROGETTO AND PS.COD_TIPO = 'RIN'
	LEFT JOIN (SELECT ISNULL(G.COSTO_TOTALE, 0) AS COSTO, ISNULL(CONTRIBUTO_DI_MISURA, 0) AS CONTR, G.ID_PROGETTO, G.ID_BANDO, g.ID_PROG_INTEGRATO, GR.FINANZIABILITA
				FROM GRADUATORIA_PROGETTI_FINANZIABILITA G 
				INNER JOIN GRADUATORIA_PROGETTI GR ON ISNULL(G.ID_PROG_INTEGRATO, G.ID_PROGETTO) = GR.ID_PROGETTO) GF ON  P.ID_PROGETTO = GF.ID_PROGETTO
	LEFT JOIN (SELECT  ISNULL(COSTO_TOTALE, 0) AS COSTO, ISNULL(CONTRIBUTO_TOTALE, 0) AS CONTR, ID_PROGETTO, FINANZIABILITA
			   FROM GRADUATORIA_PROGETTI) G ON P.ID_PROGETTO = G.ID_PROGETTO
	INNER JOIN vIMPRESA AS I ON P.ID_IMPRESA = I.ID_IMPRESA
	LEFT JOIN ATTI A ON ISNULL(PROG_PRINC.SEGNATURA, P.SEGNATURA) = CONVERT(VARCHAR(10), A.ID_ATTO) 
			   
	LEFT JOIN (SELECT DP.ID_DOMANDA_PAGAMENTO, dpe.ID_PROGETTO, AR.ID_BANDO, dpe.BARCODE,  
				AR.CONTRIBUTO_RICHIESTO, DPE.IMPORTO_AMMESSO, E.ID_ELENCO_PAGAMENTO, E.ID_ELENCO_REGIONALE, 
				DP.DATA_MODIFICA, DP.APPROVATA, DP.SEGNATURA, DP.SEGNATURA_APPROVAZIONE, DP.SEGNATURA_SECONDA_APPROVAZIONE
				, F.NUMERO AS NUM_FIDEJUSSIONE, F.BARCODE BAR_FIDEJUSSIONE,  RAGIONE_SOCIALE_GARANTE RAG_FIDEJUSSIONE
				, DATA_SOTTOSCRIZIONE AS DATA_FIDEJUSSIONE, IMPORTO AS IMPORTO_FIDEJUSSIONE
				, DPE.IMPORTO_LIQUIDATO, AD.NUMERO AS NUM_DECRETO, AD.DATA AS DATA_DECRETO, DP.ISTRUTTORE, DP.OPERATORE, EN.DESCRIZIONE AS ENTE
				FROM vDOMANDA_DI_PAGAMENTO AS DP
				LEFT JOIN FIDEJUSSIONI F ON DP.ID_FIDEJUSSIONE = F.ID_FIDEJUSSIONE
	 			LEFT JOIN ANTICIPI_RICHIESTI AR ON DP.ID_DOMANDA_PAGAMENTO = AR.ID_DOMANDA_PAGAMENTO 
				LEFT JOIN DOMANDA_DI_PAGAMENTO_ESPORTAZIONE AS DPE ON DP.ID_DOMANDA_PAGAMENTO = DPE.ID_DOMANDA_PAGAMENTO 
				LEFT JOIN ELENCO_DI_PAGAMENTO AS E ON E.ID_ELENCO_PAGAMENTO = DPE.ID_ELENCO_PAGAMENTO 
				AND AR.ID_BANDO = ISNULL(E.ID_DISPOSIZIONE_ATTUATIVA, E.ID_BANDO_PRINCIPALE)
				LEFT JOIN AGEA_DECRETI AD ON DPE.ID_DECRETO_AGEA = AD.ID
				LEFT JOIN ENTE EN ON DP.COD_ENTE = EN.COD_ENTE
				WHERE DP.COD_TIPO = 'ANT' AND DP.ANNULLATA = 0 --AND DP.APPROVATA <> 0
				AND ((DP.SEGNATURA_APPROVAZIONE IS NOT NULL AND DP.APPROVATA = 1) OR DP.SEGNATURA_APPROVAZIONE IS NULL)
	) DP_ANT ON DP_ANT.ID_PROGETTO =  P.ID_PROGETTO AND P.ID_BANDO = DP_ANT.ID_BANDO

	LEFT JOIN (SELECT DP.ID_DOMANDA_PAGAMENTO, dpE.ID_PROGETTO, dpe.BARCODE,  
				DPE.IMPORTO_AMMESSO, E.ID_ELENCO_PAGAMENTO, E.ID_ELENCO_REGIONALE, 
				DP.DATA_MODIFICA, DP.APPROVATA, DP.SEGNATURA, DP.SEGNATURA_APPROVAZIONE, DP.SEGNATURA_SECONDA_APPROVAZIONE, 
				PR.IMPORTO_RICHIESTO, PR.CONTRIBUTO_RICHIESTO, PR.IMPORTO_AMMESSO AS SPESA_AMMESSA, 
				DP.PREDISPOSTA_A_CONTROLLO, DP.CONTROLLO_INLOCO_ESITO
				, F.NUMERO AS NUM_FIDEJUSSIONE, F.BARCODE BAR_FIDEJUSSIONE,  RAGIONE_SOCIALE_GARANTE RAG_FIDEJUSSIONE
				, DATA_SOTTOSCRIZIONE AS DATA_FIDEJUSSIONE, IMPORTO AS IMPORTO_FIDEJUSSIONE
				, DPE.IMPORTO_LIQUIDATO, AD.NUMERO AS NUM_DECRETO, AD.DATA AS DATA_DECRETO, DP.ISTRUTTORE, DP.OPERATORE, EN.DESCRIZIONE AS ENTE
				FROM VDOMANDA_DI_PAGAMENTO AS DP	
				LEFT JOIN FIDEJUSSIONI F ON DP.ID_FIDEJUSSIONE = F.ID_FIDEJUSSIONE 
				LEFT JOIN DOMANDA_DI_PAGAMENTO_ESPORTAZIONE AS DPE ON DP.ID_DOMANDA_PAGAMENTO = DPE.ID_DOMANDA_PAGAMENTO 
				LEFT JOIN ELENCO_DI_PAGAMENTO AS E ON E.ID_ELENCO_PAGAMENTO = DPE.ID_ELENCO_PAGAMENTO
				LEFT JOIN (SELECT ID_DOMANDA_PAGAMENTO, SUM(ISNULL(P.IMPORTO_RICHIESTO, 0)) AS IMPORTO_RICHIESTO, SUM(ISNULL(P.CONTRIBUTO_RICHIESTO, 0)) AS CONTRIBUTO_RICHIESTO
							, SUM(ISNULL(P.IMPORTO_AMMESSO, 0)) AS IMPORTO_AMMESSO, PINV.ID_PROGETTO
							FROM PAGAMENTI_RICHIESTI P
							LEFT JOIN PIANO_INVESTIMENTI PINV ON P.ID_INVESTIMENTO = PINV.ID_INVESTIMENTO
							GROUP BY ID_DOMANDA_PAGAMENTO, PINV.ID_PROGETTO) AS PR ON PR.ID_DOMANDA_PAGAMENTO = DP.ID_DOMANDA_PAGAMENTO  
							AND DPE.ID_PROGETTO = PR.ID_PROGETTO
				LEFT JOIN AGEA_DECRETI AD ON DPE.ID_DECRETO_AGEA = AD.ID
				LEFT JOIN ENTE EN ON DP.COD_ENTE = EN.COD_ENTE
				WHERE DP.COD_TIPO = 'SAL' AND DP.ANNULLATA = 0 --AND DP.APPROVATA <> 0
				AND ((DP.SEGNATURA_APPROVAZIONE IS NOT NULL AND DP.APPROVATA = 1) OR DP.SEGNATURA_APPROVAZIONE IS NULL)
	) DP_SAL ON DP_SAL.ID_PROGETTO =  P.ID_PROGETTO

	LEFT JOIN (SELECT DP.ID_DOMANDA_PAGAMENTO, dpE.ID_PROGETTO, dpe.BARCODE,  
				DPE.IMPORTO_AMMESSO, E.ID_ELENCO_PAGAMENTO, E.ID_ELENCO_REGIONALE, 
				DP.DATA_MODIFICA, DP.APPROVATA, DP.SEGNATURA, DP.SEGNATURA_APPROVAZIONE, DP.SEGNATURA_SECONDA_APPROVAZIONE, 
				PR.IMPORTO_RICHIESTO, PR.CONTRIBUTO_RICHIESTO, PR.IMPORTO_AMMESSO AS SPESA_AMMESSA,
				PREDISPOSTA_A_CONTROLLO, CONTROLLO_INLOCO_ESITO			
				, DPE.IMPORTO_LIQUIDATO, AD.NUMERO AS NUM_DECRETO, AD.DATA AS DATA_DECRETO, DP.ISTRUTTORE, DP.OPERATORE, EN.DESCRIZIONE AS ENTE
				FROM VDOMANDA_DI_PAGAMENTO AS DP	
				INNER JOIN (SELECT MAX(ID_DOMANDA_PAGAMENTO) AS ID_DOMANDA_PAGAMENTO, ID_PROGETTO FROM DOMANDA_DI_PAGAMENTO
									WHERE COD_TIPO = 'SLD' AND ANNULLATA = 0 
									GROUP BY ID_PROGETTO) DP_ULTIMA ON DP.ID_DOMANDA_PAGAMENTO = DP_ULTIMA.ID_DOMANDA_PAGAMENTO
				LEFT JOIN DOMANDA_DI_PAGAMENTO_ESPORTAZIONE AS DPE ON DP.ID_DOMANDA_PAGAMENTO = DPE.ID_DOMANDA_PAGAMENTO 
				LEFT JOIN ELENCO_DI_PAGAMENTO AS E ON E.ID_ELENCO_PAGAMENTO = DPE.ID_ELENCO_PAGAMENTO
				LEFT JOIN (SELECT ID_DOMANDA_PAGAMENTO, PINV.ID_PROGETTO,  SUM(ISNULL(P.IMPORTO_RICHIESTO, 0)) AS IMPORTO_RICHIESTO, 
							CONTRIBUTO_RICHIESTO = SUM(ISNULL(P.CONTRIBUTO_RICHIESTO, 0))
							, SUM(ISNULL(P.IMPORTO_AMMESSO, 0)) AS IMPORTO_AMMESSO
							FROM VPAGAMENTI_RICHIESTI P
							LEFT JOIN PIANO_INVESTIMENTI PINV ON P.ID_INVESTIMENTO = PINV.ID_INVESTIMENTO
							GROUP BY ID_DOMANDA_PAGAMENTO, PINV.ID_PROGETTO) AS PR ON PR.ID_DOMANDA_PAGAMENTO = DP.ID_DOMANDA_PAGAMENTO 
							AND DPE.ID_PROGETTO = PR.ID_PROGETTO
				LEFT JOIN AGEA_DECRETI AD ON DPE.ID_DECRETO_AGEA = AD.ID 
				LEFT JOIN ENTE EN ON DP.COD_ENTE = EN.COD_ENTE
	) DP_SLD ON DP_SLD.ID_PROGETTO = P.ID_PROGETTO
	LEFT JOIN ENTE E ON B.COD_ENTE = E.COD_ENTE 
	LEFT JOIN VPRIORITA_X_PROGETTO AS PP ON PP.ID_PROGETTO = P.ID_PROGETTO AND ID_PRIORITA in (374,406,798,1191)
	LEFT JOIN (SELECT MAX(ID_COLLABORATORE) ID_MAX, ID_PROGETTO
						FROM COLLABORATORI_X_BANDO 	WHERE DATA_FINE_VALIDITA IS NULL GROUP BY ID_PROGETTO
	) C ON ISNULL(P.ID_PROG_INTEGRATO, P.ID_PROGETTO) = C.ID_PROGETTO
	LEFT JOIN vCOLLABORATORI_X_BANDO C1 ON C.ID_MAX = C1.ID_COLLABORATORE
	WHERE P.COD_STATO <> 'P'--AND P.ID_PROGetto = 4334
	ORDER BY ISNULL(P.ID_PROG_INTEGRATO, P.ID_PROGETTO)
