create PROCEDURE [dbo].[RptBusinessPlan_PlvPagamento] 
@ID_Impresa int,
@ID_Domanda int,
@TipoPLV int
AS
BEGIN
	SET NOCOUNT ON;
    	
	DECLARE @Count int
DECLARE @CountPac int

		
	SET @Count = (SELECT COUNT(ID_PLV) FROM vPLV_AZIENDALE WHERE ID_PROGETTO = @ID_Domanda AND PREVISIONALE = 0)     						

	IF (@Count > 0)
	 BEGIN
	
		IF (@TipoPLV = 0) -- Plv Piano Colturale					 			   
		   
			   SELECT ANNO, 
                      PLVA.PRODOTTO,
                      PLVA.VARIETA,  
					  dbo.MqAEttari(PLVA.SAU) AS SAU,
                      ISNULL(PLVA.RESA_COLTURA,0) AS RESA_COLTURA,
                      ISNULL(PLVA.PRODUZIONE_UNITARIA,0) AS PRODUZIONE_UNITARIA,
			          ISNULL(PLVA.QUANTITA_REIMPIEGO,0) AS QUANTITA_REIMPIEGO, 
                      ISNULL(PLVA.PREZZO_COLTURA,0) AS PREZZO_COLTURA,
                      ISNULL(PLVA.PREZZO_UNITARIO_ALLEVAMENTI,0) AS PREZZO_UNITARIO_ALLEVAMENTI,
                      ISNULL(PLVA.PREZZO_ATTIVITA_CONNESSE,0) AS PREZZO_ATTIVITA_CONNESSE, 
                      ISNULL(PLVA.PREZZO_UNITARIO,0) AS PREZZO_UNITARIO,
					  ISNULL(PLVA.PRODUZIONE_IN_FILIERA, 0) AS PRODUZIONE_IN_FILIERA,
					  ISNULL(PLV_FILIERA, 0) AS PLV_FILIERA,
					  UM.DESCRIZIONE AS UNITA_MISURA,
					  ISNULL(PLVA.PLV,0) AS PLV,
                      ISNULL(PLVA.ORE_UNITARIE,0) AS ORE_UNITARIE,
                      ISNULL(PLVA.ORE_COLTURA,0) AS ORE_COLTURA,
			          PLVA.ATTIVITA_CONNESSA,                       
			          PLVA.PAC,
					  PLVA.FLAG_BIOLOGICO,
					  PLVA.FLAG_ZONASVANTAGGIATA,
					  PLVA.FLAG_COMMERCIALIZZAZIONE,
					  PLVA.FLAG_TRASFORMAZIONE,
					  PLVA.CLASSE_ALLEVAMENTO,
					  PLVA.PRODUZIONE_UNITARIA_ALLEVAMENTI,
                      ISNULL(PLVA.ORE_ALLEVAMENTI,0) AS ORE_ALLEVAMENTI,
					  dbo.MqAEttari((SELECT SUM(SAU) 
									FROM vPLV_AZIENDALE PLVA LEFT JOIN UNITA_DI_MISURA UM ON (PLVA.ID_UNITA_MISURA = UM.ID_UNITA_MISURA)
									WHERE ID_PROGETTO = @ID_Domanda AND PREVISIONALE = 0 AND COD_PRODOTTO IS NOT NULL
										AND ANNO = (SELECT MAX(ANNO) FROM vPLV_AZIENDALE WHERE ID_PROGETTO = @ID_Domanda AND PREVISIONALE = 0))) AS TOT_SAU
						, CUAA_TRASFORMATORE,
						0 AS NUM_CAPI_FILIERA
			   FROM vPLV_AZIENDALE PLVA LEFT JOIN UNITA_DI_MISURA UM ON (PLVA.ID_UNITA_MISURA = UM.ID_UNITA_MISURA)

			   WHERE ID_PROGETTO = @ID_Domanda AND PREVISIONALE = 0 AND COD_PRODOTTO IS NOT NULL
					 AND ANNO = (SELECT MAX(ANNO) FROM vPLV_AZIENDALE WHERE ID_PROGETTO = @ID_Domanda AND PREVISIONALE = 0)
                     		 
		ELSE IF (@TipoPLV = 1) -- Plv Zootecnica		
			
		   
			 SELECT ANNO, 
                      PLVA.PRODOTTO,
                      PLVA.VARIETA,
                      ISNULL(PLVA.SAU, 0) AS SAU,
                      ISNULL(PLVA.RESA_COLTURA,0) AS RESA_COLTURA,
                      ISNULL(PLVA.PRODUZIONE_UNITARIA,0) AS PRODUZIONE_UNITARIA,
			          ISNULL(PLVA.QUANTITA_REIMPIEGO,0) AS QUANTITA_REIMPIEGO, 
                      ISNULL(PLVA.PREZZO_COLTURA,0) AS PREZZO_COLTURA,
                      ISNULL(PLVA.PREZZO_UNITARIO_ALLEVAMENTI,0) AS PREZZO_UNITARIO_ALLEVAMENTI,
                      ISNULL(PLVA.PREZZO_ATTIVITA_CONNESSE,0) AS PREZZO_ATTIVITA_CONNESSE, 
                      ISNULL(PLVA.PREZZO_UNITARIO,0) AS PREZZO_UNITARIO,
					  ISNULL(PLV_FILIERA, 0) AS PLV_FILIERA,
					  ISNULL(PLVA.PRODUZIONE_IN_FILIERA, 0) AS PRODUZIONE_IN_FILIERA,
					  UM.DESCRIZIONE AS UNITA_MISURA,
					  ISNULL(PLVA.PLV,0) AS PLV,
                      ISNULL(PLVA.ORE_UNITARIE,0) AS ORE_UNITARIE,
                      ISNULL(PLVA.ORE_COLTURA,0) AS ORE_COLTURA,
			          PLVA.ATTIVITA_CONNESSA,                       
			          PLVA.PAC,
					  PLVA.FLAG_BIOLOGICO,
					  PLVA.FLAG_ZONASVANTAGGIATA,
					  PLVA.FLAG_COMMERCIALIZZAZIONE,
					  PLVA.FLAG_TRASFORMAZIONE,
					  PLVA.CLASSE_ALLEVAMENTO,
					  PLVA.PRODUZIONE_UNITARIA_ALLEVAMENTI,
                      ISNULL(PLVA.ORE_ALLEVAMENTI,0) AS ORE_ALLEVAMENTI,
					  CUAA_TRASFORMATORE,
					  ISNULL(PLVA.PRODUZIONE_IN_FILIERA, 0) / (CASE PLVA.PRODUZIONE_UNITARIA WHEN 0 THEN 1 ELSE PLVA.PRODUZIONE_UNITARIA END) AS NUM_CAPI_FILIERA


			   FROM vPLV_AZIENDALE PLVA LEFT JOIN UNITA_DI_MISURA UM ON (PLVA.ID_UNITA_MISURA = UM.ID_UNITA_MISURA)

			   WHERE ID_PROGETTO = @ID_Domanda AND ID_CLASSE_ALLEVAMENTO IS NOT NULL AND PREVISIONALE = 0
					 AND ANNO = (SELECT MAX(ANNO) FROM vPLV_AZIENDALE WHERE ID_PROGETTO = @ID_Domanda AND PREVISIONALE = 0)
		
		ELSE IF (@TipoPLV = 2)  -- Plv Attività connesse	
		  	   
			    SELECT ANNO, 
                      PLVA.PRODOTTO,
                      PLVA.VARIETA,
                       dbo.MqAEttari(PLVA.SAU) AS SAU,
                      ISNULL(PLVA.RESA_COLTURA,0) AS RESA_COLTURA,
                      ISNULL(PLVA.PRODUZIONE_UNITARIA,0) AS PRODUZIONE_UNITARIA,
			          ISNULL(PLVA.QUANTITA_REIMPIEGO,0) AS QUANTITA_REIMPIEGO, 
                      ISNULL(PLVA.PREZZO_COLTURA,0) AS PREZZO_COLTURA,
                      ISNULL(PLVA.PREZZO_UNITARIO_ALLEVAMENTI,0) AS PREZZO_UNITARIO_ALLEVAMENTI,
                      ISNULL(PLVA.PREZZO_ATTIVITA_CONNESSE,0) AS PREZZO_ATTIVITA_CONNESSE, 
                      ISNULL(PLVA.PREZZO_UNITARIO,0) AS PREZZO_UNITARIO,
					  ISNULL(PLV_FILIERA, 0) AS PLV_FILIERA,
					  ISNULL(PLVA.PRODUZIONE_IN_FILIERA, 0) AS PRODUZIONE_IN_FILIERA,
					  UM.DESCRIZIONE AS UNITA_MISURA,
					  ISNULL(PLVA.PLV,0) AS PLV,
                      ISNULL(PLVA.ORE_UNITARIE,0) AS ORE_UNITARIE,
                      ISNULL(PLVA.ORE_COLTURA,0) AS ORE_COLTURA,
			          PLVA.ATTIVITA_CONNESSA,                       
			          PLVA.PAC,
					  PLVA.FLAG_BIOLOGICO,
					  PLVA.FLAG_ZONASVANTAGGIATA,
					  PLVA.FLAG_COMMERCIALIZZAZIONE,
					  PLVA.FLAG_TRASFORMAZIONE,
					  PLVA.CLASSE_ALLEVAMENTO,
					  PLVA.PRODUZIONE_UNITARIA_ALLEVAMENTI,
                      ISNULL(PLVA.ORE_ALLEVAMENTI,0) AS ORE_ALLEVAMENTI,
					  CUAA_TRASFORMATORE,
					  0 AS NUM_CAPI_FILIERA

			   FROM vPLV_AZIENDALE PLVA LEFT JOIN UNITA_DI_MISURA UM ON (PLVA.ID_UNITA_MISURA = UM.ID_UNITA_MISURA)

			   WHERE ID_PROGETTO = @ID_Domanda AND ID_ATTIVITA_CONNESSA IS NOT NULL	AND PREVISIONALE = 0
                     AND ANNO = (SELECT MAX(ANNO) FROM vPLV_AZIENDALE WHERE ID_PROGETTO = @ID_Domanda AND PREVISIONALE = 0)
		
		ELSE IF (@TipoPLV = 3)  -- Contributi P.A.C.	

		 
		   IF (@ID_Domanda IS NOT NULL) -- a livello di domanda
			begin
			 SET @CountPac = (SELECT COUNT(ID_PLV) FROM vPLV_AZIENDALE   WHERE ID_PROGETTO = @ID_Domanda AND CODICE_PAC IS NOT NULL AND PREVISIONALE = 0 AND ANNO = (SELECT MAX(ANNO) FROM vPLV_AZIENDALE WHERE ID_PROGETTO = @ID_Domanda AND PREVISIONALE = 0))     						

			IF (@CountPac > 0)

			    SELECT ANNO, 
                      PLVA.PRODOTTO,
                      PLVA.VARIETA,
                      ISNULL(PLVA.SAU,0) AS SAU,
                      ISNULL(PLVA.RESA_COLTURA,0) AS RESA_COLTURA,
                      ISNULL(PLVA.PRODUZIONE_UNITARIA,0) AS PRODUZIONE_UNITARIA,
			          ISNULL(PLVA.QUANTITA_REIMPIEGO,0) AS QUANTITA_REIMPIEGO, 
                      ISNULL(PLVA.PREZZO_COLTURA,0) AS PREZZO_COLTURA,
                      ISNULL(PLVA.PREZZO_UNITARIO_ALLEVAMENTI,0) AS PREZZO_UNITARIO_ALLEVAMENTI,
                      ISNULL(PLVA.PREZZO_ATTIVITA_CONNESSE,0) AS PREZZO_ATTIVITA_CONNESSE, 
                      ISNULL(PLVA.PREZZO_UNITARIO,0) AS PREZZO_UNITARIO,
					  ISNULL(PLV_FILIERA, 0) AS PLV_FILIERA,
					  ISNULL(PLVA.PRODUZIONE_IN_FILIERA, 0) AS PRODUZIONE_IN_FILIERA,
					  UM.DESCRIZIONE AS UNITA_MISURA,
					  ISNULL(PLVA.PLV,0) AS PLV,
                      ISNULL(PLVA.ORE_UNITARIE,0) AS ORE_UNITARIE,
                      ISNULL(PLVA.ORE_COLTURA,0) AS ORE_COLTURA,
			          PLVA.ATTIVITA_CONNESSA,                       
			          PLVA.PAC,
					  PLVA.FLAG_BIOLOGICO,
					  PLVA.FLAG_ZONASVANTAGGIATA,
					  PLVA.FLAG_COMMERCIALIZZAZIONE,
					  PLVA.FLAG_TRASFORMAZIONE,
					  PLVA.CLASSE_ALLEVAMENTO,
					  PLVA.PRODUZIONE_UNITARIA_ALLEVAMENTI,
                      ISNULL(PLVA.ORE_ALLEVAMENTI,0) AS ORE_ALLEVAMENTI,
					  CUAA_TRASFORMATORE,
					  0 AS NUM_CAPI_FILIERA

			   FROM vPLV_AZIENDALE PLVA LEFT JOIN UNITA_DI_MISURA UM ON (PLVA.ID_UNITA_MISURA = UM.ID_UNITA_MISURA)

			   WHERE ID_PROGETTO = @ID_Domanda AND CODICE_PAC IS NOT NULL AND PREVISIONALE = 0
                     AND ANNO = (SELECT MAX(ANNO) FROM vPLV_AZIENDALE WHERE ID_PROGETTO = @ID_Domanda AND PREVISIONALE = 0)

			ELSE
			 SELECT   CODICI_PAC.CODICE_PAC, CODICI_PAC.DESCRIZIONE as PAC  , 
					   NULL as PRODOTTO,
                       NULL as VARIETA,
                       NULL as SAU,
                       NULL as RESA_COLTURA,
					   NULL as PRODUZIONE_UNITARIA,
					   NULL as QUANTITA_REIMPIEGO, 
                       NULL as PREZZO_COLTURA,
					   NULL as PREZZO_UNITARIO_ALLEVAMENTI,
                       NULL as PREZZO_ATTIVITA_CONNESSE, 
					   NULL as PREZZO_UNITARIO,
					   NULL as UNITA_MISURA,
                       NULL as PREZZO_UNITARIO,
					   0 as PLV, NULL as   ORE_UNITARIE ,
					   NULL as CLASSE_ALLEVAMENTO,                         
					   NULL as ATTIVITA_CONNESSA,
					   0 AS PLV_FILIERA, 
					   0 AS PRODUZIONE_IN_FILIERA,
					   NULL AS CUAA_TRASFORMATORE, 
					   0 AS NUM_CAPI_FILIERA

					FROM  CODICI_PAC 
END
		   			
	   ELSE  	   SELECT NULL AS ANNO, NULL AS PRODOTTO,
					  NULL AS VARIETA, 
                      NULL AS SAU,
                      NULL AS RESA_COLTURA,
                      NULL AS PRODUZIONE_UNITARIA,
			          NULL AS QUANTITA_REIMPIEGO, 
                      NULL AS PREZZO_COLTURA,
                      NULL AS PREZZO_UNITARIO_ALLEVAMENTI,
                      NULL AS PREZZO_ATTIVITA_CONNESSE, 
                      NULL AS PREZZO_UNITARIO,
					  NULL AS UNITA_MISURA,
					  NULL AS PLV,
                      NULL AS ORE_UNITARIE,
                      NULL AS ORE_COLTURA,
			          NULL AS ATTIVITA_CONNESSA,                       
			          NULL AS PAC,
					  NULL AS FLAG_BIOLOGICO,
					  NULL AS FLAG_ZONASVANTAGGIATA,
					  NULL AS FLAG_COMMERCIALIZZAZIONE,
					  NULL AS FLAG_TRASFORMAZIONE,
					  NULL AS CLASSE_ALLEVAMENTO,
					  NULL AS PRODUZIONE_UNITARIA_ALLEVAMENTI,
                      NULL AS ORE_ALLEVAMENTI,
					  0 AS PLV_FILIERA, 
					  0 AS PRODUZIONE_IN_FILIERA,
					  NULL AS CUAA_TRASFORMATORE,
					  0 AS NUM_CAPI_FILIERA
		
	 END	
	ELSE 	

	   SELECT NULL AS ANNO, NULL AS PRODOTTO,
					  NULL AS VARIETA, 
                      NULL AS SAU,
                      NULL AS RESA_COLTURA,
                      NULL AS PRODUZIONE_UNITARIA,
			          NULL AS QUANTITA_REIMPIEGO, 
                      NULL AS PREZZO_COLTURA,
                      NULL AS PREZZO_UNITARIO_ALLEVAMENTI,
                      NULL AS PREZZO_ATTIVITA_CONNESSE, 
                      NULL AS PREZZO_UNITARIO,
					  NULL AS UNITA_MISURA,
					  NULL AS PLV,
                      NULL AS ORE_UNITARIE,
                      NULL AS ORE_COLTURA,
			          NULL AS ATTIVITA_CONNESSA,                       
			          NULL AS PAC,
					  NULL AS FLAG_BIOLOGICO,
					  NULL AS FLAG_ZONASVANTAGGIATA,
					  NULL AS FLAG_COMMERCIALIZZAZIONE,
					  NULL AS FLAG_TRASFORMAZIONE,
					  NULL AS CLASSE_ALLEVAMENTO,
					  NULL AS PRODUZIONE_UNITARIA_ALLEVAMENTI,
                      NULL AS ORE_ALLEVAMENTI,
					  0 AS PLV_FILIERA, 
					  0 AS PRODUZIONE_IN_FILIERA,
					  NULL AS CUAA_TRASFORMATORE,
					  0 AS NUM_CAPI_FILIERA

END
