CREATE PROCEDURE [dbo].[RptChecklist]
@ID_PROGETTO INT, 
@FASE CHAR(1)
AS
BEGIN	

--declare @ID_PROGETTO INT = 9013, 
--@FASE CHAR(1) = 'A'

	declare @tabletmp table 
		(ID_STEP INT,
		DESCRIZIONE VARCHAR(1000),
		OBBLIGATORIO BIT,AUTOMATICO BIT,URL VARCHAR(100),CODE_METHOD VARCHAR(30),COD_ESITO CHAR(2), ESITO_POSITIVO BIT,
		DATA DATETIME,CF_OPERATORE VARCHAR(16),NOTE NTEXT)
	INSERT INTO @tabletmp 
	EXEC   SpGetEsitiChecklistByIdProgetto @ID_PROGETTO, @FASE

	SELECT T.*--, I.DATA AS DATA_COMPLETAMENTO, E.DESCRIZIONE AS ESITO_VERIFICA, FP.DESCRIZIONE AS FASE
	FROM @tabletmp T 
	INNER JOIN vITER_PROGETTO I ON T.ID_STEP = I.ID_STEP 
	INNER JOIN ESITI_STEP E ON T.COD_ESITO = E.COD_ESITO
	INNER JOIN FASI_PROCEDURALI FP ON I.COD_FASE = FP.COD_FASE
	WHERE ID_PROGETTO = @ID_PROGETTO AND I.COD_FASE = @FASE
	ORDER BY I.ORDINE
END
