CREATE PROCEDURE [dbo].[RptDP_BusinessPlan_Bilancio] 
@ID_Domanda int
AS
BEGIN
	SET NOCOUNT ON;
 
    DECLARE @DATA_MODIFICA_DP datetime, @ID_Impresa int 
	SET @ID_Impresa = (SELECT ID_IMPRESA FROM PROGETTO WHERE ID_PROGETTO = @ID_Domanda)
	SET @DATA_MODIFICA_DP = (SELECT DATA_MODIFICA FROM DOMANDA_DI_PAGAMENTO WHERE ID_PROGETTO = @ID_Domanda
										AND SEGNATURA IS NULL -- PRENDO LA DOMANDA DI PAGAMENTO IN STATO DI LAVORAZIONE 
										AND COD_TIPO = 'SLD')

	SELECT TOP(1) ANNO,
			   DATA_BILANCIO,
               ISNULL(PLV_RICAVI_NETTI,0) AS PLV_RICAVI_NETTI,
		       ISNULL(PLV_RICAVI_ATTIVITA,0) AS PLV_RICAVI_ATTIVITA,
               ISNULL(PLV_RIMANENZE_FINALI,0) AS PLV_RIMANENZE_FINALI,
               ISNULL(PLV_RIMANENZE_INIZIALI,0) AS PLV_RIMANENZE_INIZIALI,
			   ISNULL(VA_COSTI_MAT_PRIME,0) AS VA_COSTI_MAT_PRIME,
			   ISNULL(VA_COSTI_ATT_CONNESSE,0) AS VA_COSTI_ATT_CONNESSE,
			   ISNULL(VA_NOLEGGI,0) AS VA_NOLEGGI,
			   ISNULL(VA_MANUTENZIONI,0) AS VA_MANUTENZIONI,
			   ISNULL(VA_SPESE_GENERALI,0)AS VA_SPESE_GENERALI,
			   ISNULL(VA_AFFITTI,0) AS VA_AFFITTI,
			   ISNULL(VA_ALTRI_COSTI,0) AS VA_ALTRI_COSTI,
			   ISNULL(PN_AMM_MACCHINE,0) AS PN_AMM_MACCHINE,
			   ISNULL(PN_AMM_FABBRICATI,0) AS PN_AMM_FABBRICATI,
			   ISNULL(PN_AMM_PIANTAGIONI,0) AS PN_AMM_PIANTAGIONI,
			   ISNULL(RO_SALARI,0) AS RO_SALARI,
			   ISNULL(RO_ONERI,0) AS RO_ONERI,
			   ISNULL(RN_PAC_RICAVI,0) AS RN_PAC_RICAVI,
			   ISNULL(RN_PAC_COSTI,0) AS RN_PAC_COSTI,
			   ISNULL(RN_PAC_PROVENTI,0) AS RN_PAC_PROVENTI,
			   ISNULL(RN_PAC_PERDITE,0) AS RN_PAC_PERDITE,
			   ISNULL(RN_PAC_INTERESSI_ATTIVI,0) AS RN_PAC_INTERESSI_ATTIVI,
			   ISNULL(RN_PAC_INTERESSI_PASSIVI,0) AS RN_PAC_INTERESSI_PASSIVI,
			   ISNULL(RN_PAC_IMPOSTE,0) AS RN_PAC_IMPOSTE,
			   ISNULL(RN_PAC_CONTRIBUTI_PAC,0) AS RN_PAC_CONTRIBUTI_PAC,
			   ISNULL(MNL_REDDITI_FAM,0) AS MNL_REDDITI_FAM,
			   ISNULL(MNL_RIMBORSO,0) AS MNL_RIMBORSO,
			   ISNULL(MNL_PRELIEVI,0) AS MNL_PRELIEVI,
			   ISNULL(CF_CF_TERRENI,0) AS CF_CF_TERRENI,
			   ISNULL(CF_CF_IMPIANTI,0) AS CF_CF_IMPIANTI,
			   ISNULL(CF_CF_PIANTAGIONI,0) AS CF_CF_PIANTAGIONI,
			   ISNULL(CF_CF_MIGLIORAMENTI,0) AS CF_CF_MIGLIORAMENTI,
			   ISNULL(CF_CA_MACCHINE,0) AS CF_CA_MACCHINE,
			   ISNULL(CF_CA_BESTIAME,0) AS CF_CA_BESTIAME,
			   ISNULL(CF_IF_PARTECIPAZIONI,0) AS CF_IF_PARTECIPAZIONI,
			   ISNULL(CC_DF_RIMANENZE,0) AS CC_DF_RIMANENZE,
			   ISNULL(CC_DF_ANTICIPAZIONI,0) AS CC_DF_ANTICIPAZIONI,
			   ISNULL(CC_LD_CREDITI,0) AS CC_LD_CREDITI,
			   ISNULL(CC_LI_BANCA,0) AS CC_LI_BANCA,
			   ISNULL(CC_LI_CASSA,0) AS CC_LI_CASSA,
			   ISNULL(FF_PC_DEBITI_BREVE_TERMINE,0) AS FF_PC_DEBITI_BREVE_TERMINE,
			   ISNULL(FF_PC_FORNITORI,0) AS FF_PC_FORNITORI,
			   ISNULL(FF_PC_DEBITI,0) AS FF_PC_DEBITI,
			   ISNULL(FF_PC_MUTUI,0) AS FF_PC_MUTUI,
			   ISNULL(FF_MP_CAPITALE,0) ASFF_MP_CAPITALE,
			   ISNULL(FF_MP_RISERVE,0) AS FF_MP_RISERVE,
			   ISNULL(FF_MP_UTILE,0) AS FF_MP_UTILE

		FROM BILANCIO_AGRICOLO
		
		WHERE PREVISIONALE = 0 AND ID_IMPRESA = @ID_Impresa AND DATA_MODIFICA >= @DATA_MODIFICA_DP  
		ORDER BY ANNO DESC
END
