
CREATE PROCEDURE [dbo].[RptDP_DatiPolizza]
(
	@IdDomandaPagamento int
)
AS
BEGIN


SELECT D.ID_DOMANDA_PAGAMENTO, D.COD_TIPO, D.ID_PROGETTO, 
                D.DATA_INSERIMENTO, D.OPERATORE, D.DATA_MODIFICA, 
                D.COD_ENTE, D.SEGNATURA, D.DESCRIZIONE, D.COD_FASE, 
                D.FASE, D.ORDINE, F.ID_FIDEJUSSIONE, F.NUMERO, F.BARCODE, 
                F.DATA_SOTTOSCRIZIONE, F.LUOGO_SOTTOSCRIZIONE, 
                CONVERT(DECIMAL(18,2), (F.AMMONTARE_RICHIESTO * ISNULL( B.VALORE, 110)) / 100) AS IMPORTO,
                 dbo.ConvertNumberToDigit(CONVERT(DECIMAL(18,2), (F.AMMONTARE_RICHIESTO * ISNULL(B.VALORE, 110)) / 100)) 
                AS IMPORTO_LETTERE, F.AMMONTARE_RICHIESTO, 
                dbo.ConvertNumberToDigit(F.AMMONTARE_RICHIESTO) AS AMMONTARE_RICHIESTO_LETTERE, 
                F.DATA_FINE_LAVORI, F.PROROGA_SCADENZA, F.PIVA_GARANTE, F.RAGIONE_SOCIALE_GARANTE, 
                F.LOCALITA_GARANTE, F.NUMERO_REGISTRO_IMPRESE, F.COGNOME_RAPPLEGALE, F.NOME_RAPPLEGALE, 
                F.CF_RAPPLEGALE, F.DATA_NASCITA_RAPPLEGALE, F.STAMPA_EFFETTUATA, F.DATA_RICHIESTA_VALIDITA, 
                F.DATA_RICEVIMENTO_VALIDITA, F.PROTOCOLLO_FAX_VALIDITA, F.DATA_DECORRENZA_GARANZIA, 
                F.CODICE_ABI_ENTE_GARANTE, F.CODICE_CAB_ENTE_GARANTE, F.BARCODE_CONFERMA_VALIDITA, 
				DATEADD(MONTH,ISNULL(CONVERT(INT, B_durata.VALORE), 6),F.DATA_FINE_LAVORI) AS DATA_SCADENZA, 
				F.DATA_SCADENZA as DATA_SCADENZA2,
                F.COD_TIPO AS TIPO_POLIZZA, ISNULL(B.VALORE, 110) AS QUOTA_IMPORTO_GARANTITO, 
               CASE WHEN GP.CONTRIBUTO_TOTALE IS NULL THEN DBO.calcoloContributoTotaleProgettoCorrelato (P.ID_PROGETTO, 1, ID_V)
               ELSE GP.CONTRIBUTO_TOTALE  END AS CONTRIBUTO_AMMESSO,  
               CASE WHEN GP.COSTO_TOTALE IS NULL THEN DBO.calcoloCostoTotaleProgettoCorrelato (P.ID_PROGETTO, 1, ID_V)
               ELSE GP.COSTO_TOTALE  END AS SPESA_AMMESSA,
               vbResp.NOMINATIVO                  
FROM vDOMANDA_DI_PAGAMENTO D 
			LEFT JOIN FIDEJUSSIONI F ON D.ID_FIDEJUSSIONE = F.ID_FIDEJUSSIONE
            INNER JOIN PROGETTO P ON  D.ID_PROGETTO = P.ID_PROGETTO 
            LEFT JOIN bando_config B ON P.ID_BANDO = B.ID_BANDO AND B.COD_TIPO = 'QUOTIMPGARFID' and B.ATTIVO = 1 
			LEFT JOIN bando_config B_durata ON P.ID_BANDO = B_durata.ID_BANDO AND B_durata.COD_TIPO = 'MESIDURGARFID' and B_durata.ATTIVO = 1 
            LEFT JOIN vBANDO VB ON
            P.ID_BANDO = VB.ID_BANDO
            LEFT JOIN vBANDO_RESPONSABILI vbResp on vbResp.ID_BANDO = P.ID_BANDO and vbResp.PROVINCIA is null AND vbResp.ATTIVO = 1
            LEFT JOIN (SELECT MAX(ID_VARIANTE) ID_V, ID_PROGETTO FROM VARIANTI 
			WHERE APPROVATA = 1 AND ANNULLATA = 0 
			GROUP BY ID_PROGETTO) V ON P.ID_PROGETTO = V.ID_PROGETTO
			LEFT JOIN GRADUATORIA_PROGETTI GP ON GP.ID_PROGETTO = P.ID_PROGETTO
WHERE ID_DOMANDA_PAGAMENTO = @IdDomandaPagamento

END







