CREATE PROCEDURE [dbo].[RptDomandaPagamentoImportiAnticipo]
@IdDomandaPagamento int	
AS	

DECLARE @ID_PROGETTO INT, @ID_BANDO INT  
SET @ID_PROGETTO = (SELECT ID_PROGETTO FROM DOMANDA_DI_PAGAMENTO WHERE ID_DOMANDA_PAGAMENTO = @IdDomandaPagamento)

DECLARE @TMP_ANTICIPO TABLE 
	(ID_BANDO INT,MISURA_PREVALENTE BIT, MISURA VARCHAR(20) ,  COD_TIPO VARCHAR(7),
	QUOTA_MAX DECIMAL(16,8),QUOTA_MIN DECIMAL(16,8),IMPORTO_MAX DECIMAL(16,8),IMPORTO_MIN DECIMAL(16,8),
	DESCRIZIONE VARCHAR(100),
	COD_FASE VARCHAR(1) ,FASE VARCHAR(100),
	ORDINE INT,
	ID_PROGETTO INT,
	COSTO_DI_MISURA DECIMAL(18,2),	
	CONTRIBUTO_DI_MISURA DECIMAL(18,2),
	AMMESSO BIT,
	AMMONTARE_RICHIESTO DECIMAL(18,2),
	AMMONTARE_AMMESSO DECIMAL(18,2))
DECLARE PROGETTI_INTEGRATI CURSOR 
	FOR (SELECT ID_BANDO FROM PROGETTO WHERE ISNULL(ID_PROG_INTEGRATO, ID_PROGETTO) =  @ID_PROGETTO)
 
OPEN PROGETTI_INTEGRATI 
FETCH NEXT FROM PROGETTI_INTEGRATI INTO @ID_BANDO
WHILE @@FETCH_STATUS  = 0 
BEGIN
	INSERT INTO @TMP_ANTICIPO 
	EXEC DBO.SpPsrCalcoloAmmontareAnticipo @ID_BANDO, @IdDomandaPagamento

FETCH NEXT FROM PROGETTI_INTEGRATI INTO @ID_BANDO
END
CLOSE PROGETTI_INTEGRATI 
DEALLOCATE PROGETTI_INTEGRATI

SELECT A.ID_PROGETTO, MISURA, COSTO_DI_MISURA, CONTRIBUTO_DI_MISURA, AMMONTARE_AMMESSO, AMMONTARE_RICHIESTO, D.BARCODE
FROM @TMP_ANTICIPO A 
LEFT JOIN DOMANDA_DI_PAGAMENTO_ESPORTAZIONE D ON A.ID_PROGETTO = D.ID_PROGETTO
AND D.ID_DOMANDA_PAGAMENTO = @IdDomandaPagamento
GROUP BY A.ID_PROGETTO, MISURA, COSTO_DI_MISURA, CONTRIBUTO_DI_MISURA, AMMONTARE_AMMESSO, AMMONTARE_RICHIESTO, D.BARCODE
