CREATE PROCEDURE [dbo].[RptDomandaPagamentoPremio]
(
	@IdDomandaPagamento int, 
	@Istruttoria bit
)
AS
BEGIN

--DECLARE @IdDomandaPagamento int 
--set @iddomandapagamento = 111
DECLARE @ID_DOMANDA INT
DECLARE @ID_VARIANTE INT
DECLARE @CONTRIBUTO_AMMESSO INT

SET @ID_DOMANDA =(SELECT ID_PROGETTO FROM DOMANDA_DI_PAGAMENTO WHERE ID_DOMANDA_PAGAMENTO =@IdDomandaPagamento)

SET @CONTRIBUTO_AMMESSO = (SELECT ISNULL(CONTRIBUTO_AMMESSO, 0) FROM ANTICIPI_RICHIESTI 
WHERE ID_BANDO = (SELECT ID_BANDO FROM PROGETTO WHERE ID_PROGETTO = @ID_DOMANDA) AND ID_DOMANDA_PAGAMENTO = (SELECT ID_DOMANDA_PAGAMENTO 
FROM DOMANDA_DI_PAGAMENTO 
WHERE ID_PROGETTO = @ID_DOMANDA AND COD_TIPO = 'ANT' and approvata = 1 and annullata = 0 and ID_DOMANDA_PAGAMENTO =@IdDomandaPagamento ))

SELECT     @ID_VARIANTE = MAX(ID_VARIANTE)
FROM         VARIANTI
WHERE     ID_PROGETTO = @ID_DOMANDA AND ((APPROVATA = 1 AND COD_TIPO <> 'VI') or COD_TIPO='VI') 

if((SELECT COUNT(*) FROM BANDO_TIPO_INVESTIMENTI WHERE COD_TIPO_INVESTIMENTO=3 AND ID_BANDO = (SELECT ID_BANDO FROM PROGETTO WHERE ID_PROGETTO = @ID_DOMANDA)) > 0)

SELECT DBO.calcoloPremioContoCapitaleSaldo(@IdDomandaPagamento, @Istruttoria) AS PREMIO, ISNULL(@CONTRIBUTO_AMMESSO, 0) AS CONTRIBUTO_AMMESSO

ELSE SELECT 0 AS PREMIO, 0 AS CONTRIBUTO_AMMESSO

END
