-- PERMETTE L'ESTRAZIONE DI TUTTI GLI ELENCHI DI PAGAMENTO CREATI SUL SIAR (FIRMATI E NON) VISUALIZZATO NELLA PAGINA DI REPORTISTICA DEI BANDI
-- NELLA TAB DELL'ELENCO DI PAGAMENTO 
CREATE PROCEDURE [dbo].[rptElencoPagamento]

AS

DECLARE @ID_BANDO INT, @ID_DISPOSIZIONE_ATTUATIVA INT, @ID_ELENCO_PAGAMENTO INT, @DATA_CREAZIONE DATETIME, @SEGNATURA VARCHAR(80), @ESPORTATO BIT, 
	@NOMINATIVO VARCHAR(255), @CODICE VARCHAR(10), @MISURA VARCHAR(80), @PSR VARCHAR(100), @DATA_SCADENZA DATETIME, 
	@CUAA VARCHAR(16), @PERCENTUALE_COMUNITARIA DECIMAL(10,2), @PERCENTUALE_NAZIONALE DECIMAL(10,2),
	@PERCENTUALE_REGIONALE DECIMAL(10,2), @CONTRIBUTO DECIMAL(18,2), @DATA_ESPORTAZIONE DATETIME,
	@ELABORATO_DA_SIAN BIT, @DATA_ELABORAZIONE_SIAN DATETIME, @NUM_ATTO_AUTORIZZAZIONE INT, @DATA_ATTO_AUTORIZZAZIONE DATETIME, @ENTE VARCHAR(100)

CREATE TABLE #ELENCO_PA (ID_BANDO INT, ID_DISPOSIZIONE_ATTUATIVA INT, ID_ELENCO_PAGAMENTO INT, DATA_CREAZIONE DATETIME, SEGNATURA VARCHAR(80), ESPORTATO BIT, 
	DATA_ESPORTAZIONE DATETIME, NOMINATIVO VARCHAR(255), CODICE VARCHAR(10), MISURA VARCHAR(80), PSR VARCHAR(100), DATA_SCADENZA DATETIME,
	CUAA VARCHAR(16), PERCENTUALE_COMUNITARIA INT, PERCENTUALE_NAZIONALE INT,
	PERCENTUALE_REGIONALE INT, CONTRIBUTO DECIMAL(18,2), ELABORATO_DA_SIAN BIT, DATA_ELABORAZIONE_SIAN DATETIME,  NUM_ATTO_AUTORIZZAZIONE INT, 
	DATA_ATTO_AUTORIZZAZIONE DATETIME, ENTE VARCHAR(100))

DECLARE BANDI CURSOR FOR 
(
	SELECT E.ID_BANDO_PRINCIPALE, E.ID_DISPOSIZIONE_ATTUATIVA, E.ID_ELENCO_PAGAMENTO, E.DATA_CREAZIONE,
						  E.ESPORTATO, E.DATA_ESPORTAZIONE, vUTENTI.NOMINATIVO,
						  ELABORATO_DA_SIAN, DATA_ELABORAZIONE_SIAN, CONTRIBUTO, A.NUMERO AS NUM_ATTO_AUTORIZZAZIONE, A.DATA AS DATA_ATTO_AUTORIZZAZIONE
	FROM ELENCO_DI_PAGAMENTO E INNER JOIN vUTENTI ON E.CF_OPERATORE = vUTENTI.CF_UTENTE
	INNER JOIN  (SELECT SUM(ISNULL(IMPORTO_AMMESSO, 0)) AS CONTRIBUTO, E.ID_ELENCO_REGIONALE
						FROM DOMANDA_DI_PAGAMENTO_ESPORTAZIONE DPE 
						INNER JOIN DOMANDA_DI_PAGAMENTO ON DPE.ID_DOMANDA_PAGAMENTO = DOMANDA_DI_PAGAMENTO.ID_DOMANDA_PAGAMENTO 
						INNER JOIN ELENCO_DI_PAGAMENTO AS E ON E.ID_ELENCO_PAGAMENTO = DPE.ID_ELENCO_PAGAMENTO
				        WHERE PROVINCIA IS NOT NULL AND DPE.IMPORTO_AMMISSIBILE > 0
                       GROUP BY E.ID_ELENCO_REGIONALE) AS DPE1 ON E.ID_ELENCO_PAGAMENTO = DPE1.ID_ELENCO_REGIONALE
     LEFT JOIN ATTI A ON E.ID_ATTO_AUTORIZZAZIONE = A.ID_ATTO
     WHERE (E.PROVINCIA IS NULL) 
)
OPEN BANDI
FETCH NEXT FROM BANDI INTO @ID_BANDO, @ID_DISPOSIZIONE_ATTUATIVA, @ID_ELENCO_PAGAMENTO, @DATA_CREAZIONE, 
			@ESPORTATO, @DATA_ESPORTAZIONE, @NOMINATIVO, @ELABORATO_DA_SIAN, @DATA_ELABORAZIONE_SIAN, @CONTRIBUTO, @NUM_ATTO_AUTORIZZAZIONE, @DATA_ATTO_AUTORIZZAZIONE
WHILE @@FETCH_STATUS = 0
BEGIN
	SET @CODICE = NULL
	SET @MISURA = NULL
	SET @PSR = NULL
	SET @CUAA = NULL 
	SET @DATA_SCADENZA = NULL
	SET @PERCENTUALE_COMUNITARIA = 0
	SET @PERCENTUALE_NAZIONALE = 0
	SET @PERCENTUALE_REGIONALE = 0 
	SET @SEGNATURA = NULL
	
	SELECT TOP 1 @SEGNATURA = SEGNATURA FROM ELENCO_DI_PAGAMENTO WHERE ID_ELENCO_PAGAMENTO IN (
								SELECT ID_ELENCO_REGIONALE
								FROM ELENCO_DI_PAGAMENTO WHERE ID_ELENCO_PAGAMENTO = @ID_ELENCO_PAGAMENTO)

	SELECT @DATA_SCADENZA = DATA_SCADENZA FROM vBANDO WHERE ID_BANDO = @ID_BANDO 

	SELECT @CODICE = P.CODICE, @MISURA = P.DESCRIZIONE, @PSR = P.COD_PSR, @ENTE = B.ENTE 
		FROM vzPROGRAMMAZIONE P 
		INNER JOIN VBANDO B ON P.ID = B.ID_PROGRAMMAZIONE
		WHERE    B.ID_BANDO = @ID_DISPOSIZIONE_ATTUATIVA
		GROUP BY P.CODICE, P.DESCRIZIONE, P.COD_PSR, B.ENTE

	SELECT @CUAA = COUNT(ID_DOMANDA_PAGAMENTO) 
		FROM DOMANDA_DI_PAGAMENTO_ESPORTAZIONE 
		WHERE (ID_ELENCO_PAGAMENTO IN ((SELECT ID_ELENCO_PAGAMENTO
                 FROM ELENCO_DI_PAGAMENTO AS ELENCO_DI_PAGAMENTO_1
                 WHERE (ID_ELENCO_REGIONALE = @ID_ELENCO_PAGAMENTO) AND PROVINCIA IS NOT NULL)))
		AND IMPORTO_AMMESSO IS NOT NULL

	SELECT @PERCENTUALE_COMUNITARIA = ISNULL(F.PERCENTUALE, F1.PERCENTUALE)
	FROM BANDO B
	INNER JOIN vzPROGRAMMAZIONE P ON B.ID_PROGRAMMAZIONE = P.ID
	LEFT JOIN ZPROGRAMMAZIONE_FONTI F ON P.ID_PADRE = F.ID_PROGRAMMAZIONE AND (F.ID_FONTE = 1) 
	LEFT JOIN ZPROGRAMMAZIONE_FONTI F1 ON P.ID = F1.ID_PROGRAMMAZIONE AND (F1.ID_FONTE = 1) 
		WHERE ID_BANDO = @ID_DISPOSIZIONE_ATTUATIVA
		GROUP BY F.PERCENTUALE, F1.PERCENTUALE
 

	SELECT @PERCENTUALE_NAZIONALE = ISNULL(F.PERCENTUALE, F1.PERCENTUALE)
	FROM BANDO B
	INNER JOIN vzPROGRAMMAZIONE P ON B.ID_PROGRAMMAZIONE = P.ID
	LEFT JOIN ZPROGRAMMAZIONE_FONTI F ON P.ID_PADRE = F.ID_PROGRAMMAZIONE AND (F.ID_FONTE = 2) 
	LEFT JOIN ZPROGRAMMAZIONE_FONTI F1 ON P.ID = F1.ID_PROGRAMMAZIONE AND (F1.ID_FONTE = 2) 
		WHERE ID_BANDO = @ID_DISPOSIZIONE_ATTUATIVA
		GROUP BY F.PERCENTUALE, F1.PERCENTUALE

	SELECT @PERCENTUALE_REGIONALE = ISNULL(F.PERCENTUALE, F1.PERCENTUALE)
	FROM BANDO B
	INNER JOIN vzPROGRAMMAZIONE P ON B.ID_PROGRAMMAZIONE = P.ID
	LEFT JOIN ZPROGRAMMAZIONE_FONTI F ON P.ID_PADRE = F.ID_PROGRAMMAZIONE AND (F.ID_FONTE = 21) 
	LEFT JOIN ZPROGRAMMAZIONE_FONTI F1 ON P.ID = F1.ID_PROGRAMMAZIONE AND (F1.ID_FONTE = 21) 
		WHERE ID_BANDO = @ID_DISPOSIZIONE_ATTUATIVA
		GROUP BY F.PERCENTUALE, F1.PERCENTUALE
	

	INSERT INTO #ELENCO_PA SELECT @ID_BANDO, @ID_DISPOSIZIONE_ATTUATIVA, @ID_ELENCO_PAGAMENTO, @DATA_CREAZIONE, @SEGNATURA, @ESPORTATO, @DATA_ESPORTAZIONE, @NOMINATIVO,
								@CODICE, @MISURA, @PSR,	@DATA_SCADENZA, @CUAA, @PERCENTUALE_COMUNITARIA, @PERCENTUALE_NAZIONALE,
								@PERCENTUALE_REGIONALE, @CONTRIBUTO, @ELABORATO_DA_SIAN, @DATA_ELABORAZIONE_SIAN, @NUM_ATTO_AUTORIZZAZIONE, @DATA_ATTO_AUTORIZZAZIONE, @ENTE
 
	FETCH NEXT FROM BANDI INTO @ID_BANDO, @ID_DISPOSIZIONE_ATTUATIVA, @ID_ELENCO_PAGAMENTO, @DATA_CREAZIONE, 
					@ESPORTATO, @DATA_ESPORTAZIONE, @NOMINATIVO, @ELABORATO_DA_SIAN, @DATA_ELABORAZIONE_SIAN, @CONTRIBUTO, @NUM_ATTO_AUTORIZZAZIONE, @DATA_ATTO_AUTORIZZAZIONE
END 
CLOSE BANDI 
DEALLOCATE BANDI 

SELECT *
FROM #ELENCO_PA 
--WHERE CONTRIBUTO > 0
ORDER BY #ELENCO_PA.ID_ELENCO_PAGAMENTO
DROP TABLE #ELENCO_PA
