CREATE PROCEDURE [dbo].[RptFAMacrousoTerritorio] 
	@ID_FASCICOLO int
AS
BEGIN
	SET NOCOUNT ON;
	DECLARE @TABLE_MACROUSO TABLE (MACROUSO varchar(255),SUP_UTILIZZATA_10 INT,SUP_UTILIZZATA_5 INT, SUP_UTILIZZATA_5_10 INT, 
																		SUP_UTILIZZATA_10_120 INT, SUP_UTILIZZATA_5_10_120 INT, SUP_UTILIZZATA_5_120 INT )	
		INSERT INTO @TABLE_MACROUSO 
		EXEC SpGetFAMacrousoTerritorio @ID_FASCICOLO
	
	SELECT MACROUSO, DBO.MqAEttari(SUP_UTILIZZATA_10) SUP_UTILIZZATA_10, DBO.MqAEttari(SUP_UTILIZZATA_5) SUP_UTILIZZATA_5, DBO.MqAEttari(SUP_UTILIZZATA_5_10) SUP_UTILIZZATA_5_10, 
	DBO.MqAEttari(SUP_UTILIZZATA_10_120) SUP_UTILIZZATA_10_120, DBO.MqAEttari(SUP_UTILIZZATA_5_10_120) SUP_UTILIZZATA_5_10_120, DBO.MqAEttari(SUP_UTILIZZATA_5_120) SUP_UTILIZZATA_5_120,
	DBO.MqAEttari((SELECT SUM(SUP_UTILIZZATA_10) FROM @TABLE_MACROUSO)) AS SUP_UTILIZZATA_10_MQ,
	DBO.MqAEttari((SELECT SUM(SUP_UTILIZZATA_5) FROM @TABLE_MACROUSO)) AS SUP_UTILIZZATA_5_MQ,
	DBO.MqAEttari((SELECT SUM(SUP_UTILIZZATA_5_10) FROM @TABLE_MACROUSO)) AS SUP_UTILIZZATA_5_10_MQ
	FROM @TABLE_MACROUSO
END
