create PROCEDURE [dbo].[RptFAMacrouso]
(
	@ID_FASCICOLO INT, 
	@DATA DATETIME, 
	@TIPO_UMA BIT
)
AS
BEGIN	
	DECLARE @TMP TABLE (MACROUSO varchar(500), SUP_UTILIZZATA_10 INT, SUP_UTILIZZATA_5 INT, SUP_UTILIZZATA_5_10 INT, SUP_UTILIZZATA_10_120 INT, SUP_UTILIZZATA_5_10_120 INT, SUP_UTILIZZATA_5_120 INT)
	IF(@TIPO_UMA=1)
	BEGIN
		INSERT INTO @TMP 
		EXEC DBO.SpRiepilogoFascicoloUma @ID_FASCICOLO, 'TIPO_MACROUSO_UMA', @DATA

		SELECT MACROUSO, 
		dbo.MqAEttari(ISNULL( SUP_UTILIZZATA_10,0)) SUP_UTILIZZATA_10, 
		dbo.MqAEttari(ISNULL( SUP_UTILIZZATA_5,0)) SUP_UTILIZZATA_5,
		dbo.MqAEttari(ISNULL( SUP_UTILIZZATA_5_10,0))  SUP_UTILIZZATA_5_10
		FROM @TMP	
	END 
	ELSE 
	BEGIN 
			
		INSERT INTO @TMP 
		EXEC SpGetFAMacrousoTerritorio @ID_FASCICOLO
		
		SELECT MACROUSO, DBO.MqAEttari(SUP_UTILIZZATA_10) SUP_UTILIZZATA_10, DBO.MqAEttari(SUP_UTILIZZATA_5) SUP_UTILIZZATA_5, DBO.MqAEttari(SUP_UTILIZZATA_5_10) SUP_UTILIZZATA_5_10, 
		DBO.MqAEttari(SUP_UTILIZZATA_10_120) SUP_UTILIZZATA_10_120, DBO.MqAEttari(SUP_UTILIZZATA_5_10_120) SUP_UTILIZZATA_5_10_120, DBO.MqAEttari(SUP_UTILIZZATA_5_120) SUP_UTILIZZATA_5_120,
		DBO.MqAEttari((SELECT SUM(SUP_UTILIZZATA_10) FROM @TMP)) AS SUP_UTILIZZATA_10_MQ,
		DBO.MqAEttari((SELECT SUM(SUP_UTILIZZATA_5) FROM @TMP)) AS SUP_UTILIZZATA_5_MQ,
		DBO.MqAEttari((SELECT SUM(SUP_UTILIZZATA_5_10) FROM @TMP)) AS SUP_UTILIZZATA_5_10_MQ
		FROM @TMP
	
	END
END
