USE [sigefproduzione]
GO
/****** Object:  StoredProcedure [dbo].[RptIstruttoriaDomande]    Script Date: 03/15/2019 13:26:18 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[RptIstruttoriaDomande] (
@IdBando int, 
@IdProgetto int = null,
@Operatore varchar(16) = null,
@Provincia varchar(2) = null, 
@stato varchar(1) = null,
@Cuaa varchar(16) = null,
@Ragsoc varchar(500) = null
)
as
begin 


SELECT I.CUAA, CONTRIBUTO, PREMIO_C,C,RICHIEDI_PARTICELLA,
                       ID.ID_PROGETTO, 
                      ID.CUAA, ID.COD_STATO, ID.STATO, ID.PARTITA_IVA,
                       ID.RAGIONE_SOCIALE, ID.COMUNE, ID.SIGLA, 
                      ID.CAP, ID.ISTRUTTORE, ID.PROVINCIA_ASSEGNAZIONE, 
                      ID.SELEZIONATA_X_REVISIONE, ID.PROVINCIA_DI_PRESENTAZIONE, 
                      ID.FILTRO_STATO_ISTRUTTORIA, U.CF_UTENTE AS CF_ISTRUTTORE, ID.VIA, 
                      PXI.NOME, PXI.COGNOME, PXI.CODICE_FISCALE, 
                      PXI.DATA_NASCITA, PXI.COMUNE AS COMUNE_NASCITA, 
                      PXI.SIGLA AS PROV_NASCITA, PXI.CAP AS CAP_NASCITA,
                      	(select TOP 1 TELEFONO  from INDIRIZZARIO where INDIRIZZARIO.ID_IMPRESA = ID.ID_IMPRESA and EMAIL is not null order by ID_INDIRIZZARIO DESC) as TELEFONO,
(select TOP 1 EMAIL  from INDIRIZZARIO where INDIRIZZARIO.ID_IMPRESA = ID.ID_IMPRESA and EMAIL is not null order by ID_INDIRIZZARIO DESC) as EMAIL,
(select TOP 1 pec  from INDIRIZZARIO where INDIRIZZARIO.ID_IMPRESA = ID.ID_IMPRESA and PEC is not null order by ID_INDIRIZZARIO DESC) as PEC,
(CASE WHEN RICHIEDI_PARTICELLA = 0 THEN C ELSE 0 END) AS COSTO_RICHIEDI_PARTICELLA, 
(CASE WHEN RICHIEDI_PARTICELLA = 1 THEN C ELSE 0 END) AS COSTO_NON_RICHIEDI_PARTICELLA,
(CASE WHEN RICHIEDI_PARTICELLA = 0 THEN CONTRIBUTO ELSE 0 END) AS CONTRIBUTO_RICHIEDI_PARTICELLA, 
(CASE WHEN RICHIEDI_PARTICELLA = 1 THEN CONTRIBUTO ELSE 0 END) AS CONTRIBUTO_NON_RICHIEDI_PARTICELLA, PXP.VALORE_DESC
, M.SEGNATURA AS SEGNATURA_STATO, 
dbo.calcoloContributoTotaleProgetto(ID.ID_PROGETTO, 1, NULL) AS CONTRIBUTO_X_MASSIMALI, 
DBO.calcoloCostoTotaleProgetto(ID.ID_PROGETTO, 1, NULL) AS COSTO_TOTALE_PROGETTO, 
pinv.CostoInvestimentoOriginario,
		ISNULL((select case
		when ( btp.IMPORTO_MAX IS NOT NULL AND pinv.ContributoRichiestoOriginario > btp.IMPORTO_MAX) THEN btp.IMPORTO_MAX
		ELSE  pinv.ContributoRichiestoOriginario
		END )  ,0 ) AS ContributoRichiestoOriginario,
PS.SEGNATURA AS COMUNICAZIONE_FINANZIABILITA                  
FROM  vISTRUTTORIA_DOMANDE ID 
inner join (select id_progetto,  SUM(costo_investimento) as CostoInvestimentoOriginario, SUM(contributo_richiesto) as ContributoRichiestoOriginario from PIANO_INVESTIMENTI where ID_INVESTIMENTO_ORIGINALE is null and ID_VARIANTE is null group by id_progetto ) pinv on  ID.ID_PROGETTO = pinv.ID_PROGETTO
left outer join BANDO_TIPO_INVESTIMENTI btp on btp.ID_BANDO = ID.ID_BANDO and btp.COD_TIPO_INVESTIMENTO = 7
INNER JOIN
                      IMPRESA I ON ID.ID_IMPRESA = I.ID_IMPRESA  
INNER JOIN vPERSONE_X_IMPRESE PXI ON PXI.ID_PERSONE_X_IMPRESE = I.ID_RAPPRLEGALE_ULTIMO 
INNER JOIN (SELECT ISNULL(SUM(CASE COD_TIPO_INVESTIMENTO WHEN 2 /*PER IL MUTUO SOMMO SOLO L'AMMONTARE*/ 
		THEN ISNULL(COSTO_INVESTIMENTO,0) 
		ELSE ISNULL(COSTO_INVESTIMENTO,0)+ISNULL(SPESE_GENERALI,0) END),0)  AS C, 
ISNULL(PR.ID_PROG_INTEGRATO, PR.ID_PROGETTO) AS ID_PROGETTO, 
ISNULL(RICHIEDI_PARTICELLA, 0) AS RICHIEDI_PARTICELLA, SUM(CONTRIBUTO_RICHIESTO) AS CONTRIBUTO,
(CASE WHEN ISNULL(RICHIEDI_PARTICELLA, 0) = 0 
THEN dbo.calcoloPremioContoCapitale(ISNULL(PR.ID_PROG_INTEGRATO, PR.ID_PROGETTO), 1, V.ID_VARIANTE) ELSE 0 END) AS PREMIO_C

		FROM VPROGETTO PR INNER JOIN PIANO_INVESTIMENTI P1 ON PR.ID_PROGETTO = P1.ID_PROGETTO
			LEFT JOIN DETTAGLIO_INVESTIMENTI DI_RICHIEDI_PARTICELLA ON DI_RICHIEDI_PARTICELLA.ID_DETTAGLIO_INVESTIMENTO = P1.ID_DETTAGLIO_INVESTIMENTO 
			LEFT JOIN (SELECT MAX(ID_VARIANTE) AS ID_VARIANTE, ID_PROGETTO FROM VARIANTI 
				   WHERE APPROVATA = 1 GROUP BY ID_PROGETTO) 
			V ON V.ID_PROGETTO = ISNULL(PR.ID_PROG_INTEGRATO, PR.ID_PROGETTO)
		WHERE ((V.ID_VARIANTE IS NOT NULL AND P1.ID_VARIANTE = V.ID_VARIANTE) OR 
				  (V.ID_VARIANTE IS NULL AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND P1.ID_VARIANTE IS NULL))
				  AND ISNULL(P1.COD_VARIAZIONE,'x')!='A'
				  GROUP BY ISNULL(PR.ID_PROG_INTEGRATO, PR.ID_PROGETTO), ISNULL(RICHIEDI_PARTICELLA, 0), 
				  V.ID_VARIANTE
) AS C_RICHIEDI_PARTICELLA ON C_RICHIEDI_PARTICELLA.ID_PROGETTO = ID.ID_PROGETTO
LEFT OUTER JOIN
                      vPRIORITA_X_PROGETTO AS PXP ON PXP.ID_PROGETTO = ID.ID_PROGETTO AND PXP.ID_PRIORITA IN (374, 406,798,1191)
LEFT JOIN  (SELECT MAX(ID) AS MAX_ID, ID_PROGETTO FROM VPROGETTO_STORICO WHERE COD_FASE = 'A'  GROUP BY ID_PROGETTO) AS Q1 ON Q1.ID_PROGETTO = ID.ID_PROGETTO
LEFT JOIN PROGETTO_STORICO M ON Q1.MAX_ID = M.ID
INNER JOIN vUTENTI U ON ID.ID_ISTRUTTORE = U.ID_UTENTE
LEFT JOIN PROGETTO_SEGNATURE PS ON ID.ID_PROGETTO = PS.ID_PROGETTO AND PS.COD_TIPO = 'CFI'
WHERE     (ID.ID_BANDO = @IdBando) 
 AND 
                      (PXI.DATA_FINE IS NULL) 
                      AND (U.CF_UTENTE = ISNULL(@Operatore, 
                      U.CF_UTENTE)) AND (ID.ID_PROGETTO = ISNULL(@IdProgetto, 
                      ID.ID_PROGETTO)) AND (ID.PROVINCIA_ASSEGNAZIONE = ISNULL(@Provincia, 
                      ID.PROVINCIA_ASSEGNAZIONE)) AND (ID.FILTRO_STATO_ISTRUTTORIA = ISNULL(@stato, 'I')) 
                     AND (ID.CUAA LIKE ISNULL(@Cuaa + '%', ID.CUAA)) 
                     AND (@Ragsoc IS NULL OR (@Ragsoc IS NOT NULL AND ID.RAGIONE_SOCIALE LIKE '%' + @Ragsoc + '%'))    
ORDER BY  ID.ID_PROGETTO
end
