create PROCEDURE [dbo].[RptIstruttoriaVariantePremioPrec]

	@ID_VARIANTE_ATTUALE int

AS
BEGIN

	DECLARE @ID_PROGETTO INT 
	DECLARE @ID_VARIANTE INT 

	SET @ID_PROGETTO = (SELECT ID_PROGETTO FROM VARIANTI WHERE ID_VARIANTE = @ID_VARIANTE_ATTUALE)

	SET @ID_VARIANTE =(SELECT MAX(ID_VARIANTE) FROM VARIANTI WHERE ID_PROGETTO=@ID_PROGETTO AND APPROVATA=1 AND ID_VARIANTE<@ID_VARIANTE_ATTUALE)


	IF((SELECT COUNT(*) FROM BANDO_TIPO_INVESTIMENTI WHERE COD_TIPO_INVESTIMENTO=3 AND ID_BANDO = (SELECT ID_BANDO FROM PROGETTO WHERE ID_PROGETTO = @ID_PROGETTO)) > 0)
	
	BEGIN
		SELECT DBO.calcoloPremioContoCapitale(@ID_PROGETTO, 1, @ID_VARIANTE) AS PREMIO
	END 
END
