CREATE PROCEDURE [dbo].[RptIstruttoriaVariantePianoInvestimenti]
(
@ID_VARIANTE int,
@COD_Tipo_Investimento int	
)
AS
BEGIN	

SET NOCOUNT ON;

--DECLARE @ID_Domanda int 
--DECLARE @COD_Tipo_Investimento int
--SET @ID_Domanda = 1596
--SET @COD_Tipo_Investimento = 1


DECLARE @Count int
DECLARE @ID_Domanda int 
DECLARE @CONTR_TOTALE DECIMAL(18, 2)
DECLARE @CONTR_FUNZIONE DECIMAL(18, 2)
DECLARE @TOTALE DECIMAL(18, 2)
DECLARE @FASE BIT

SET @ID_Domanda =(SELECT ID_PROGETTO FROM VARIANTI WHERE ID_VARIANTE=@ID_VARIANTE)
SET @FASE = (SELECT CASE WHEN ORDINE_FASE>2 THEN 1 ELSE 0 END  FROM vPROGETTO  WHERE ID_PROGETTO = @ID_Domanda)

SET @Count = (SELECT COUNT(I.ID_INVESTIMENTO) 
				FROM vPROGETTO AS P INNER JOIN VPIANO_INVESTIMENTI AS I ON P.ID_PROGETTO=I.ID_PROGETTO
				WHERE (P.ID_PROGETTO=@ID_Domanda OR P.ID_PROG_INTEGRATO=@ID_Domanda) AND
					((ORDINE_FASE IS NULL AND ID_INVESTIMENTO_ORIGINALE IS NULL AND ID_VARIANTE IS NULL) OR 
					(ORDINE_FASE<4 AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL) OR
					(ORDINE_FASE>=4  AND ((@ID_VARIANTE IS NULL AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL) OR
					 ID_VARIANTE=@ID_VARIANTE))) AND I.COD_TIPO_INVESTIMENTO = @COD_Tipo_Investimento)

IF (@Count > 0)
BEGIN
	SET @CONTR_TOTALE = 0
	SET @CONTR_FUNZIONE = 0
	SET @CONTR_TOTALE = (SELECT SUM(ISNULL(CONTRIBUTO_RICHIESTO, 0)) 
								FROM PIANO_INVESTIMENTI INNER JOIN vPROGETTO P ON PIANO_INVESTIMENTI.ID_PROGETTO = P.ID_PROGETTO
								WHERE ((P.ID_PROG_INTEGRATO IS NULL AND P.ID_PROGETTO= @ID_Domanda) OR P.ID_PROG_INTEGRATO=@ID_Domanda) AND
									((ORDINE_FASE IS NULL AND ID_INVESTIMENTO_ORIGINALE IS NULL AND ID_VARIANTE IS NULL) OR 
									(ORDINE_FASE<4 AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL) OR
									(ORDINE_FASE>=4  AND ((@ID_VARIANTE IS NULL AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL) OR
									 ID_VARIANTE=@ID_VARIANTE))) AND COD_TIPO_INVESTIMENTO = @COD_Tipo_Investimento AND ISNULL(COD_VARIAZIONE,'x')!='A')

	SET @CONTR_FUNZIONE = (SELECT dbo.calcoloContributoInvestimentiProgetto(@ID_Domanda, @FASE, @ID_VARIANTE))


	SELECT I.ID_INVESTIMENTO, I.ID_INVESTIMENTO_ORIGINALE,  I.DESCRIZIONE,
				   I.MISURA AS CODICE_MISURA,
				   I.SETTORE_PRODUTTIVO,
				   I.COSTO_INVESTIMENTO,
				   I.SPESE_GENERALI,
				   I.CONTRIBUTO_RICHIESTO AS CONTRIBUTO_AMMISSIBILE,
				   I.QUOTA_CONTRIBUTO_RICHIESTO AS QUOTA_CONTRIBUTO_AMMISSIBILE,
				   I.ID_PRIORITA_SETTORIALE,
				   DENSE_RANK() over (ORDER BY I.ID_INVESTIMENTO) AS ROWS,
				   RATA_REINTEGRAZIONE = CASE MOBILE
											WHEN 1 THEN ((I.COSTO_INVESTIMENTO + I.SPESE_GENERALI)/10)
											WHEN 0 THEN ((I.COSTO_INVESTIMENTO + I.SPESE_GENERALI)/30)
											ELSE 0
											END, 
					@CONTR_TOTALE AS TOTALE_CONTRIBUTO, 
					@CONTR_FUNZIONE AS TOTALE_CONTRIBUTO_TRONCATO,
					(SELECT     VALORI_PRIORITA.CODICE
					FROM         PRIORITA_X_INVESTIMENTI INNER JOIN
										  VALORI_PRIORITA ON PRIORITA_X_INVESTIMENTI.ID_VALORE = VALORI_PRIORITA.ID_VALORE INNER JOIN
										  PIANO_INVESTIMENTI ON PRIORITA_X_INVESTIMENTI.ID_INVESTIMENTO = PIANO_INVESTIMENTI.ID_INVESTIMENTO INNER JOIN
										  PROGETTO ON PIANO_INVESTIMENTI.ID_PROGETTO = PROGETTO.ID_PROGETTO
					WHERE     (PRIORITA_X_INVESTIMENTI.ID_PRIORITA IN (37,88, 92, 93, 94, 102, 103,116) ) AND PRIORITA_X_INVESTIMENTI.ID_INVESTIMENTO = I.ID_INVESTIMENTO
					) AS RENDIMENTO_GLOBALE, 
					COD_VARIAZIONE	
	FROM vPROGETTO AS P INNER JOIN VPIANO_INVESTIMENTI AS I ON P.ID_PROGETTO=I.ID_PROGETTO
	WHERE (P.ID_PROGETTO=@ID_Domanda OR P.ID_PROG_INTEGRATO=@ID_Domanda) AND
					((ORDINE_FASE IS NULL AND ID_INVESTIMENTO_ORIGINALE IS NULL AND ID_VARIANTE IS NULL) OR 
					(ORDINE_FASE<4 AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL) OR
					(ORDINE_FASE>=4  AND ((@ID_VARIANTE IS NULL AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL) OR
					 ID_VARIANTE=@ID_VARIANTE))) AND I.COD_TIPO_INVESTIMENTO = @COD_Tipo_Investimento --AND ISNULL(COD_VARIAZIONE,'x')!='A'
	ORDER BY COD_TIPO_INVESTIMENTO,ID_INVESTIMENTO

END

ELSE SELECT NULL AS DESCRIZIONE,
            NULL AS CODICE_MISURA,
		    NULL AS SETTORE_PRODUTTIVO,
		    NULL AS COSTO_INVESTIMENTO,
		    NULL AS SPESE_GENERALI,
		    NULL AS CONTRIBUTO_AMMISSIBILE, 
			NULL AS QUOTA_CONTRIBUTO_AMMISSIBILE,
			NULL AS ID_PRIORITA_SETTORIALE,
		    NULL AS RATA_REINTEGRAZIONE,
			NULL AS TOTALE_CONTRIBUTO,
			NULL AS TOTALE_CONTRIBUTO_TRONCATO, 
			NULL AS RENDIMENTO_GLOBALE	    
END
