CREATE PROCEDURE [dbo].[RptManifestazioneAccessoQM]
	@IdManifestazione INT 
AS
BEGIN

--- SISTEMA DI QUALITà QM - PRIORITA
--- AGRITEST = 60
--- SIAR = 236
--- SIARTEST = 240

--DECLARE @IdManifestazione INT
--SET @IdManifestazione = 31

SELECT     PRIORITA_X_MANIFESTAZIONE.ID_MANIFESTAZIONE, PRIORITA_X_MANIFESTAZIONE.ID_PRIORITA, PRIORITA_X_MANIFESTAZIONE.ID_VALORE, 
                      PRIORITA_X_MANIFESTAZIONE.VALORE, PRIORITA_X_MANIFESTAZIONE.DATA_VALUTAZIONE, 
                      PRIORITA_X_MANIFESTAZIONE.OPERATORE_VALUTAZIONE, PRIORITA_X_MANIFESTAZIONE.MODIFICA_MANUALE, 
                      PRIORITA_X_MANIFESTAZIONE.PUNTEGGIO
FROM         PRIORITA_X_MANIFESTAZIONE INNER JOIN
                      PRIORITA ON PRIORITA_X_MANIFESTAZIONE.ID_PRIORITA = PRIORITA.ID_PRIORITA 
WHERE     (PRIORITA_X_MANIFESTAZIONE.ID_MANIFESTAZIONE = @IdManifestazione) 
AND (PRIORITA_X_MANIFESTAZIONE.ID_PRIORITA = 236)
END
