--
CREATE PROCEDURE [dbo].[RptManifestazioneSistemaQM]
	@IdManifestazione INT 
AS
BEGIN

--- SISTEMA DI QUALITà QM 
--- AGRITEST = 59
--- SIAR = 235
--- SIARTEST = 237

--declare @IdManifestazione int 
--set @IdManifestazione = 20

SELECT   PRIORITA_X_MANIFESTAZIONE.*
FROM         PRIORITA_X_MANIFESTAZIONE INNER JOIN
                      PRIORITA ON PRIORITA_X_MANIFESTAZIONE.ID_PRIORITA = PRIORITA.ID_PRIORITA 
WHERE     (PRIORITA_X_MANIFESTAZIONE.ID_MANIFESTAZIONE = @IdManifestazione) 
	AND (PRIORITA_X_MANIFESTAZIONE.ID_PRIORITA = 236) --AND PRIORITA_X_MANIFESTAZIONE.ID_VALORE = 383
-- modificato per le filiere locali 
END
