--CREATE PROCEDURE [dbo].[RptPianoInvestimenti]
CREATE PROCEDURE [dbo].[RptPianoInvestimenti]
(
	@ID_PROGETTO INT,
	@COD_QUERY VARCHAR(30),
	@ID_VARIANTE_ATTUALE INT = NULL,
	@ID_DOMANDA_PAGAMENTO INT = NULL
)
AS

DECLARE @ID_VARIANTE INT,@DATA_MODIFICA_PAGAMENTO DATETIME,@COD_TIPO CHAR(3)

--DECLARE @SPESE_AMMESSE DECIMAL(18,2);
--DECLARE @COSTO_INVESTIMENTO DECIMAL(18,2);
--DECLARE @QUOTA_COMPLETAMENTO DECIMAL(18,2);
--DECLARE @QUOTA_COMPLETAMENTO_AMMESSO DECIMAL(18,2);
--DECLARE @DISAVANZO DECIMAL(18,2);
--DECLARE @DISAVANZO_CONTRIBUTO DECIMAL(18,2);
--DECLARE @SOMMA_DISAVANZO_CONTRIBUTO DECIMAL(18,2);

--SET @SPESE_AMMESSE = 0.00;
--SET @COSTO_INVESTIMENTO = 0.00;
--SET @QUOTA_COMPLETAMENTO = 0.00;
--SET @QUOTA_COMPLETAMENTO_AMMESSO = 0.00;
--SET @DISAVANZO = 0.00;
--SET @DISAVANZO_CONTRIBUTO = 0.00;
--SET @SOMMA_DISAVANZO_CONTRIBUTO = 0.00;


--QUERY UTILIZZATA IN PIANO_INVESTIMENTI.ASPX E IDENTICA PAGINA IN ISTRUTTORIA e IN PAGAMENTO
IF @COD_QUERY='PIANO_INVESTIMENTI' BEGIN
	SELECT @ID_VARIANTE=MAX(ID_VARIANTE) FROM VARIANTI WHERE ID_PROGETTO=@ID_PROGETTO AND APPROVATA=1 AND ANNULLATA=0
	
	SELECT XXX.*,
		DISAVANZO * QUOTA_CONTRIBUTO_RICHIESTO / 100 AS DISAVANZO_CONTRIBUTO,
		CASE
			WHEN SPESE_AMMESSE > COSTO_INVESTIMENTO_CALC
			THEN (DISAVANZO * QUOTA_CONTRIBUTO_RICHIESTO / 100) - ISNULL(PAG_CONTRIBUTO_DISAVANZO_COSTI_AMMESSI, 0.00)
			ELSE (DISAVANZO * QUOTA_CONTRIBUTO_RICHIESTO / 100) + ISNULL(PAG_CONTRIBUTO_DISAVANZO_COSTI_AMMESSI, 0.00)
		END AS SOMMA_DISAVANZO_CONTRIBUTO
	FROM ( 
		SELECT XX.*,
			CASE
				WHEN SPESE_AMMESSE > COSTO_INVESTIMENTO_CALC AND QUOTA_COMPLETAMENTO_AMMESSO <= 110
				THEN SPESE_AMMESSE - COSTO_INVESTIMENTO_CALC
				WHEN SPESE_AMMESSE > COSTO_INVESTIMENTO_CALC AND QUOTA_COMPLETAMENTO_AMMESSO > 110
				THEN COSTO_INVESTIMENTO * 10 / 100
				WHEN SPESE_AMMESSE < COSTO_INVESTIMENTO_CALC AND QUOTA_COMPLETAMENTO_AMMESSO >= 90
				THEN - (COSTO_INVESTIMENTO_CALC - SPESE_AMMESSE)
				WHEN SPESE_AMMESSE < COSTO_INVESTIMENTO_CALC AND QUOTA_COMPLETAMENTO_AMMESSO < 90
				THEN -COSTO_INVESTIMENTO_CALC * 10 / 100
			END AS DISAVANZO
		FROM (
			SELECT X.*,
				CASE
					WHEN (COSTO_INVESTIMENTO_CALC > 0 AND ID_PROGETTO IS NOT NULL)
					THEN 100 * PAG_IMPORTO_RICHIESTO / COSTO_INVESTIMENTO
					ELSE 0.00
				END AS QUOTA_COMPLETAMENTO,
				CASE
					WHEN (COSTO_INVESTIMENTO_CALC > 0 AND ID_PROGETTO IS NOT NULL)
					THEN 100 * ISNULL(PAG_IMPORTO_AMMESSO, 0.00) / COSTO_INVESTIMENTO
					ELSE 0.00
				END AS QUOTA_COMPLETAMENTO_AMMESSO,
				CASE
					WHEN (COSTO_INVESTIMENTO_CALC > 0 AND ID_PROGETTO IS NOT NULL)
					THEN ISNULL(PAG_IMPORTO_AMMESSO, 0.00) 
					ELSE 0.00
				END AS SPESE_AMMESSE
			FROM (
				SELECT I.ID_PROGETTO AS ID_PROGETTO,
					I.ID_INVESTIMENTO AS ID_INVESTIMENTO,
					I.COD_TIPO_INVESTIMENTO AS COD_TIPO_INVESTIMENTO,
					I.MISURA,
					I.SPESE_GENERALI,
					I.CODIFICA_INVESTIMENTO,
					I.DETTAGLIO_INVESTIMENTI,
					I.DESCRIZIONE AS DESCRIZIONE,
					I.SETTORE_PRODUTTIVO,
					I.COSTO_INVESTIMENTO,
					I.CONTRIBUTO_RICHIESTO,
					I.QUOTA_CONTRIBUTO_RICHIESTO,
					dbo.calcoloImportoPagamentiRichiestiInvestimento(I.ID_INVESTIMENTO, @DATA_MODIFICA_PAGAMENTO) AS IMPORTO_PAGAMENTO_RICHIESTO,
					PAG_CONTRIBUTO_RICHIESTO,
					PAG_IMPORTO_RICHIESTO, 
					PAG_IMPORTO_AMMESSO,
					PAG_CONTRIBUTO_AMMESSO,
					PAG_CONTRIBUTO_DISAVANZO_COSTI_AMMESSI,
					100 * PAG_IMPORTO_RICHIESTO / (I.COSTO_INVESTIMENTO + I.SPESE_GENERALI) AS PAG_PERC_RENDICONTAZIONE,
					IMP.RAGIONE_SOCIALE_INVESTIMENTO,
					IMP.DIMENSIONE_IMPRESA_INVESTIMENTO,
					IMP_SOGG_SPER.DESCRIZIONE AS IMP_SOGG_SPERIMENTATORE,
					ISNULL(I.COSTO_INVESTIMENTO, 0.00) + ISNULL(I.SPESE_GENERALI, 0.00) AS COSTO_INVESTIMENTO_CALC
				FROM vPROGETTO P 
					INNER JOIN VPIANO_INVESTIMENTI I ON P.ID_PROGETTO=I.ID_PROGETTO
					LEFT JOIN (SELECT ID_PROGETTO, 
									ID_INVESTIMENTO,
									PAG.CONTRIBUTO_RICHIESTO AS PAG_CONTRIBUTO_RICHIESTO,
									PAG.IMPORTO_RICHIESTO AS PAG_IMPORTO_RICHIESTO, 
									PAG.IMPORTO_AMMESSO AS PAG_IMPORTO_AMMESSO,
									PAG.CONTRIBUTO_AMMESSO AS PAG_CONTRIBUTO_AMMESSO,
									PAG.CONTRIBUTO_DISAVANZO_COSTI_AMMESSI AS PAG_CONTRIBUTO_DISAVANZO_COSTI_AMMESSI
								FROM VPAGAMENTI_RICHIESTI PAG
								WHERE 1 = 1
									AND @ID_PROGETTO = PAG.ID_PROGETTO
									AND (@ID_DOMANDA_PAGAMENTO IS NULL OR PAG.ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO)) PAG ON PAG.ID_INVESTIMENTO = I.ID_INVESTIMENTO 
					LEFT JOIN (SELECT PRI.ID_INVESTIMENTO, 
									IMP.RAGIONE_SOCIALE AS RAGIONE_SOCIALE_INVESTIMENTO,
									IMP.DIMENSIONE_IMPRESA AS DIMENSIONE_IMPRESA_INVESTIMENTO
								FROM PRIORITA_X_INVESTIMENTI PRI
									LEFT JOIN PRIORITA PRIO ON PRIO.ID_PRIORITA = PRI.ID_PRIORITA
									LEFT JOIN VIMPRESA IMP ON IMP.CODICE_FISCALE = PRI.VAL_TESTO
								WHERE 1 = 1
									AND PRIO.DESCRIZIONE LIKE '%Selezionare l`ente/l''impresa che ha in carico l`investimento%') IMP ON I.ID_INVESTIMENTO = IMP.ID_INVESTIMENTO
					LEFT JOIN (SELECT PRI_SP.ID_INVESTIMENTO, VAL.DESCRIZIONE 
								FROM PRIORITA_X_INVESTIMENTI PRI_SP 
									LEFT JOIN PRIORITA PRIO_SP ON PRIO_SP.ID_PRIORITA = PRI_SP.ID_PRIORITA
									LEFT JOIN VALORI_PRIORITA VAL ON VAL.ID_VALORE = PRI_SP.ID_VALORE
								WHERE 1 = 1
									AND PRIO_SP.DESCRIZIONE = 'Impresa / Soggetto sperimentatore') IMP_SOGG_SPER ON I.ID_INVESTIMENTO = IMP_SOGG_SPER.ID_INVESTIMENTO
				WHERE ISNULL(P.ID_PROG_INTEGRATO,P.ID_PROGETTO)=@ID_PROGETTO AND ISNULL(I.COD_VARIAZIONE,'')!='A' AND
					((ORDINE_FASE IS NULL AND I.ID_INVESTIMENTO_ORIGINALE IS NULL AND I.ID_VARIANTE IS NULL) OR 
					(ORDINE_FASE<4 AND I.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND I.ID_VARIANTE IS NULL) OR
					(ORDINE_FASE>=4  AND ((@ID_VARIANTE IS NULL AND I.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND I.ID_VARIANTE IS NULL) OR
					 I.ID_VARIANTE=@ID_VARIANTE))) ) X ) XX ) XXX
	ORDER BY COD_TIPO_INVESTIMENTO, ID_INVESTIMENTO;
	
END
IF @COD_QUERY='INVESTIMENTI_PROG_CORRELATO' BEGIN	
	SET @ID_VARIANTE =@ID_VARIANTE_ATTUALE
	
	SELECT XXX.*,
		DISAVANZO * QUOTA_CONTRIBUTO_RICHIESTO / 100 AS DISAVANZO_CONTRIBUTO,
		CASE
			WHEN SPESE_AMMESSE > COSTO_INVESTIMENTO_CALC
			THEN (DISAVANZO * QUOTA_CONTRIBUTO_RICHIESTO / 100) - ISNULL(PAG_CONTRIBUTO_DISAVANZO_COSTI_AMMESSI, 0.00)
			ELSE (DISAVANZO * QUOTA_CONTRIBUTO_RICHIESTO / 100) + ISNULL(PAG_CONTRIBUTO_DISAVANZO_COSTI_AMMESSI, 0.00)
		END AS SOMMA_DISAVANZO_CONTRIBUTO
	FROM ( 
		SELECT XX.*,
			CASE
				WHEN SPESE_AMMESSE > COSTO_INVESTIMENTO_CALC AND QUOTA_COMPLETAMENTO_AMMESSO <= 110
				THEN SPESE_AMMESSE - COSTO_INVESTIMENTO_CALC
				WHEN SPESE_AMMESSE > COSTO_INVESTIMENTO_CALC AND QUOTA_COMPLETAMENTO_AMMESSO > 110
				THEN COSTO_INVESTIMENTO * 10 / 100
				WHEN SPESE_AMMESSE < COSTO_INVESTIMENTO_CALC AND QUOTA_COMPLETAMENTO_AMMESSO >= 90
				THEN - (COSTO_INVESTIMENTO_CALC - SPESE_AMMESSE)
				WHEN SPESE_AMMESSE < COSTO_INVESTIMENTO_CALC AND QUOTA_COMPLETAMENTO_AMMESSO < 90
				THEN -COSTO_INVESTIMENTO_CALC * 10 / 100
			END AS DISAVANZO
		FROM (
			SELECT X.*,
				CASE
					WHEN (COSTO_INVESTIMENTO_CALC > 0 AND ID_PROGETTO IS NOT NULL)
					THEN 100 * PAG_IMPORTO_RICHIESTO / COSTO_INVESTIMENTO
					ELSE 0.00
				END AS QUOTA_COMPLETAMENTO,
				CASE
					WHEN (COSTO_INVESTIMENTO_CALC > 0 AND ID_PROGETTO IS NOT NULL)
					THEN 100 * ISNULL(PAG_IMPORTO_AMMESSO, 0.00) / COSTO_INVESTIMENTO
					ELSE 0.00
				END AS QUOTA_COMPLETAMENTO_AMMESSO,
				CASE
					WHEN (COSTO_INVESTIMENTO_CALC > 0 AND ID_PROGETTO IS NOT NULL)
					THEN ISNULL(PAG_IMPORTO_AMMESSO, 0.00) 
					ELSE 0.00
				END AS SPESE_AMMESSE
			FROM (
				SELECT I.ID_PROGETTO AS ID_PROGETTO,
					I.ID_INVESTIMENTO AS ID_INVESTIMENTO,
					I.COD_TIPO_INVESTIMENTO AS COD_TIPO_INVESTIMENTO,
					I.MISURA,
					I.SPESE_GENERALI,
					I.CODIFICA_INVESTIMENTO,
					I.DETTAGLIO_INVESTIMENTI,
					I.DESCRIZIONE AS DESCRIZIONE,
					I.SETTORE_PRODUTTIVO,
					I.COSTO_INVESTIMENTO,
					I.CONTRIBUTO_RICHIESTO,
					I.QUOTA_CONTRIBUTO_RICHIESTO,
					dbo.calcoloImportoPagamentiRichiestiInvestimento(I.ID_INVESTIMENTO, @DATA_MODIFICA_PAGAMENTO) AS IMPORTO_PAGAMENTO_RICHIESTO,
					PAG_CONTRIBUTO_RICHIESTO,
					PAG_IMPORTO_RICHIESTO, 
					PAG_IMPORTO_AMMESSO,
					PAG_CONTRIBUTO_AMMESSO,
					PAG_CONTRIBUTO_DISAVANZO_COSTI_AMMESSI,
					100 * PAG_IMPORTO_RICHIESTO / (I.COSTO_INVESTIMENTO + I.SPESE_GENERALI) AS PAG_PERC_RENDICONTAZIONE,
					IMP.RAGIONE_SOCIALE_INVESTIMENTO,
					IMP.DIMENSIONE_IMPRESA_INVESTIMENTO,
					IMP_SOGG_SPER.DESCRIZIONE AS IMP_SOGG_SPERIMENTATORE,
					ISNULL(I.COSTO_INVESTIMENTO, 0.00) + ISNULL(I.SPESE_GENERALI, 0.00) AS COSTO_INVESTIMENTO_CALC
				FROM vPROGETTO P 
					INNER JOIN VPIANO_INVESTIMENTI I ON P.ID_PROGETTO=I.ID_PROGETTO
					LEFT JOIN (SELECT ID_PROGETTO, 
									ID_INVESTIMENTO,
									PAG.CONTRIBUTO_RICHIESTO AS PAG_CONTRIBUTO_RICHIESTO,
									PAG.IMPORTO_RICHIESTO AS PAG_IMPORTO_RICHIESTO, 
									PAG.IMPORTO_AMMESSO AS PAG_IMPORTO_AMMESSO,
									PAG.CONTRIBUTO_AMMESSO AS PAG_CONTRIBUTO_AMMESSO,
									PAG.CONTRIBUTO_DISAVANZO_COSTI_AMMESSI AS PAG_CONTRIBUTO_DISAVANZO_COSTI_AMMESSI
								FROM VPAGAMENTI_RICHIESTI PAG
								WHERE 1 = 1
									AND @ID_PROGETTO = PAG.ID_PROGETTO
									AND (@ID_DOMANDA_PAGAMENTO IS NULL OR PAG.ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO)) PAG ON PAG.ID_INVESTIMENTO = I.ID_INVESTIMENTO 
					LEFT JOIN (SELECT PRI.ID_INVESTIMENTO, 
									IMP.RAGIONE_SOCIALE AS RAGIONE_SOCIALE_INVESTIMENTO,
									IMP.DIMENSIONE_IMPRESA AS DIMENSIONE_IMPRESA_INVESTIMENTO
								FROM PRIORITA_X_INVESTIMENTI PRI
									LEFT JOIN PRIORITA PRIO ON PRIO.ID_PRIORITA = PRI.ID_PRIORITA
									LEFT JOIN VIMPRESA IMP ON IMP.CODICE_FISCALE = PRI.VAL_TESTO
								WHERE 1 = 1
									AND PRIO.DESCRIZIONE LIKE '%Selezionare l`ente/l''impresa che ha in carico l`investimento%') IMP ON I.ID_INVESTIMENTO = IMP.ID_INVESTIMENTO
					LEFT JOIN (SELECT PRI_SP.ID_INVESTIMENTO, VAL.DESCRIZIONE 
								FROM PRIORITA_X_INVESTIMENTI PRI_SP 
									LEFT JOIN PRIORITA PRIO_SP ON PRIO_SP.ID_PRIORITA = PRI_SP.ID_PRIORITA
									LEFT JOIN VALORI_PRIORITA VAL ON VAL.ID_VALORE = PRI_SP.ID_VALORE
								WHERE 1 = 1
									AND PRIO_SP.DESCRIZIONE = 'Impresa / Soggetto sperimentatore') IMP_SOGG_SPER ON I.ID_INVESTIMENTO = IMP_SOGG_SPER.ID_INVESTIMENTO
				WHERE ISNULL(P.ID_PROG_INTEGRATO,P.ID_PROGETTO)=@ID_PROGETTO AND ISNULL(I.COD_VARIAZIONE,'')!='A' AND
					((ORDINE_FASE IS NULL AND I.ID_INVESTIMENTO_ORIGINALE IS NULL AND I.ID_VARIANTE IS NULL) OR 
					(ORDINE_FASE<4 AND I.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND I.ID_VARIANTE IS NULL) OR
					(ORDINE_FASE>=4  AND ((@ID_VARIANTE IS NULL AND I.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND I.ID_VARIANTE IS NULL) OR
					 I.ID_VARIANTE=@ID_VARIANTE))) ) X ) XX ) XXX
	ORDER BY COD_TIPO_INVESTIMENTO, ID_INVESTIMENTO;
	
END
ELSE IF @COD_QUERY='PIANO_INVESTIMENTI_ISTRUTTORIA' BEGIN
	SELECT XXX.*,
		DISAVANZO * QUOTA_CONTRIBUTO_RICHIESTO / 100 AS DISAVANZO_CONTRIBUTO,
		CASE
			WHEN SPESE_AMMESSE > COSTO_INVESTIMENTO_CALC
			THEN (DISAVANZO * QUOTA_CONTRIBUTO_RICHIESTO / 100) - ISNULL(PAG_CONTRIBUTO_DISAVANZO_COSTI_AMMESSI, 0.00)
			ELSE (DISAVANZO * QUOTA_CONTRIBUTO_RICHIESTO / 100) + ISNULL(PAG_CONTRIBUTO_DISAVANZO_COSTI_AMMESSI, 0.00)
		END AS SOMMA_DISAVANZO_CONTRIBUTO
	FROM ( 
		SELECT XX.*,
			CASE
				WHEN SPESE_AMMESSE > COSTO_INVESTIMENTO_CALC AND QUOTA_COMPLETAMENTO_AMMESSO <= 110
				THEN SPESE_AMMESSE - COSTO_INVESTIMENTO_CALC
				WHEN SPESE_AMMESSE > COSTO_INVESTIMENTO_CALC AND QUOTA_COMPLETAMENTO_AMMESSO > 110
				THEN COSTO_INVESTIMENTO * 10 / 100
				WHEN SPESE_AMMESSE < COSTO_INVESTIMENTO_CALC AND QUOTA_COMPLETAMENTO_AMMESSO >= 90
				THEN - (COSTO_INVESTIMENTO_CALC - SPESE_AMMESSE)
				WHEN SPESE_AMMESSE < COSTO_INVESTIMENTO_CALC AND QUOTA_COMPLETAMENTO_AMMESSO < 90
				THEN -COSTO_INVESTIMENTO_CALC * 10 / 100
			END AS DISAVANZO
		FROM (
			SELECT X.*,
				CASE
					WHEN (COSTO_INVESTIMENTO_CALC > 0 AND ID_PROGETTO IS NOT NULL)
					THEN 100 * PAG_IMPORTO_RICHIESTO / COSTO_INVESTIMENTO
					ELSE 0.00
				END AS QUOTA_COMPLETAMENTO,
				CASE
					WHEN (COSTO_INVESTIMENTO_CALC > 0 AND ID_PROGETTO IS NOT NULL)
					THEN 100 * ISNULL(PAG_IMPORTO_AMMESSO, 0.00) / COSTO_INVESTIMENTO
					ELSE 0.00
				END AS QUOTA_COMPLETAMENTO_AMMESSO,
				CASE
					WHEN (COSTO_INVESTIMENTO_CALC > 0 AND ID_PROGETTO IS NOT NULL)
					THEN ISNULL(PAG_IMPORTO_AMMESSO, 0.00) 
					ELSE 0.00
				END AS SPESE_AMMESSE
			FROM (
				SELECT I.ID_PROGETTO AS ID_PROGETTO,
					I.ID_INVESTIMENTO AS ID_INVESTIMENTO,
					I.COD_TIPO_INVESTIMENTO AS COD_TIPO_INVESTIMENTO,
					I.MISURA,
					I.SPESE_GENERALI,
					I.CODIFICA_INVESTIMENTO,
					I.DETTAGLIO_INVESTIMENTI,
					I.DESCRIZIONE AS DESCRIZIONE,
					I.SETTORE_PRODUTTIVO,
					I.COSTO_INVESTIMENTO,
					I.CONTRIBUTO_RICHIESTO,
					I.QUOTA_CONTRIBUTO_RICHIESTO,
					dbo.calcoloImportoPagamentiRichiestiInvestimento(I.ID_INVESTIMENTO, @DATA_MODIFICA_PAGAMENTO) AS IMPORTO_PAGAMENTO_RICHIESTO,
					PAG_CONTRIBUTO_RICHIESTO,
					PAG_IMPORTO_RICHIESTO, 
					PAG_IMPORTO_AMMESSO,
					PAG_CONTRIBUTO_AMMESSO,
					PAG_CONTRIBUTO_DISAVANZO_COSTI_AMMESSI,
					100 * PAG_IMPORTO_RICHIESTO / (I.COSTO_INVESTIMENTO + I.SPESE_GENERALI) AS PAG_PERC_RENDICONTAZIONE,
					IMP.RAGIONE_SOCIALE_INVESTIMENTO,
					IMP.DIMENSIONE_IMPRESA_INVESTIMENTO,
					IMP_SOGG_SPER.DESCRIZIONE AS IMP_SOGG_SPERIMENTATORE,
					ISNULL(I.COSTO_INVESTIMENTO, 0.00) + ISNULL(I.SPESE_GENERALI, 0.00) AS COSTO_INVESTIMENTO_CALC
				FROM vPROGETTO P 
					INNER JOIN VPIANO_INVESTIMENTI I ON P.ID_PROGETTO=I.ID_PROGETTO
					LEFT JOIN (SELECT ID_PROGETTO, 
									ID_INVESTIMENTO,
									PAG.CONTRIBUTO_RICHIESTO AS PAG_CONTRIBUTO_RICHIESTO,
									PAG.IMPORTO_RICHIESTO AS PAG_IMPORTO_RICHIESTO, 
									PAG.IMPORTO_AMMESSO AS PAG_IMPORTO_AMMESSO,
									PAG.CONTRIBUTO_AMMESSO AS PAG_CONTRIBUTO_AMMESSO,
									PAG.CONTRIBUTO_DISAVANZO_COSTI_AMMESSI AS PAG_CONTRIBUTO_DISAVANZO_COSTI_AMMESSI
								FROM VPAGAMENTI_RICHIESTI PAG
								WHERE 1 = 1
									AND @ID_PROGETTO = PAG.ID_PROGETTO
									AND (@ID_DOMANDA_PAGAMENTO IS NULL OR PAG.ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO)) PAG ON PAG.ID_INVESTIMENTO = I.ID_INVESTIMENTO 
					LEFT JOIN (SELECT PRI.ID_INVESTIMENTO, 
									IMP.RAGIONE_SOCIALE AS RAGIONE_SOCIALE_INVESTIMENTO,
									IMP.DIMENSIONE_IMPRESA AS DIMENSIONE_IMPRESA_INVESTIMENTO
								FROM PRIORITA_X_INVESTIMENTI PRI
									LEFT JOIN PRIORITA PRIO ON PRIO.ID_PRIORITA = PRI.ID_PRIORITA
									LEFT JOIN VIMPRESA IMP ON IMP.CODICE_FISCALE = PRI.VAL_TESTO
								WHERE 1 = 1
									AND PRIO.DESCRIZIONE LIKE '%Selezionare l`ente/l''impresa che ha in carico l`investimento%') IMP ON I.ID_INVESTIMENTO = IMP.ID_INVESTIMENTO
					LEFT JOIN (SELECT PRI_SP.ID_INVESTIMENTO, VAL.DESCRIZIONE 
								FROM PRIORITA_X_INVESTIMENTI PRI_SP 
									LEFT JOIN PRIORITA PRIO_SP ON PRIO_SP.ID_PRIORITA = PRI_SP.ID_PRIORITA
									LEFT JOIN VALORI_PRIORITA VAL ON VAL.ID_VALORE = PRI_SP.ID_VALORE
								WHERE 1 = 1
									AND PRIO_SP.DESCRIZIONE = 'Impresa / Soggetto sperimentatore') IMP_SOGG_SPER ON I.ID_INVESTIMENTO = IMP_SOGG_SPER.ID_INVESTIMENTO
				WHERE ISNULL(P.ID_PROG_INTEGRATO,P.ID_PROGETTO)=@ID_PROGETTO AND I.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND I.ID_VARIANTE IS NULL 
				) X ) XX ) XXX
	ORDER BY COD_TIPO_INVESTIMENTO, ID_INVESTIMENTO;
	
END
/*ELSE IF @COD_QUERY='SPESE_GENERALI' BEGIN -- NON USATA
	SET @ID_VARIANTE =(SELECT MAX(ID_VARIANTE) FROM VARIANTI WHERE ID_PROGETTO=@ID_PROGETTO AND APPROVATA=1 AND ANNULLATA=0)
	SELECT I.*,Q1.CODICE AS CODICE_MISURA FROM vPROGETTO AS P INNER JOIN PIANO_INVESTIMENTI AS I 
    ON P.ID_PROGETTO=I.ID_PROGETTO INNER JOIN(SELECT DISTINCT ID_BANDO ,CODICE FROM  PROGRAMMAZIONE_BANDO 
    AS PB INNER JOIN PROGRAMMAZIONE ON PB.ID_PROGRAMMAZIONE = PROGRAMMAZIONE.ID_PROGRAMMAZIONE INNER JOIN
    MISURA ON PROGRAMMAZIONE.ID_PSR = MISURA.ID_PSR AND PROGRAMMAZIONE.COD_OBIETTIVO = MISURA.COD_OBIETTIVO 
    AND PROGRAMMAZIONE.COD_ASSE = MISURA.COD_ASSE AND PROGRAMMAZIONE.COD_MISURA = MISURA.COD_MISURA
    WHERE PB.MISURA_PREVALENTE=1) AS Q1 ON P.ID_BANDO=Q1.ID_BANDO WHERE COD_TIPO_INVESTIMENTO IN (4,5) AND
		ISNULL(P.ID_PROG_INTEGRATO,P.ID_PROGETTO)=@ID_PROGETTO AND
		((ORDINE_FASE IS NULL AND ID_INVESTIMENTO_ORIGINALE IS NULL AND ID_VARIANTE IS NULL) OR 
		(ORDINE_FASE<4 AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL) OR
		(ORDINE_FASE>=4  AND ((@ID_VARIANTE IS NULL AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL) OR
		 ID_VARIANTE=@ID_VARIANTE))) ORDER BY COD_TIPO_INVESTIMENTO DESC,ID_INVESTIMENTO
END*/
ELSE IF @COD_QUERY='VARIANTE_ATTUALE' BEGIN
	SELECT XXX.*,
		DISAVANZO * QUOTA_CONTRIBUTO_RICHIESTO / 100 AS DISAVANZO_CONTRIBUTO,
		CASE
			WHEN SPESE_AMMESSE > COSTO_INVESTIMENTO_CALC
			THEN (DISAVANZO * QUOTA_CONTRIBUTO_RICHIESTO / 100) - ISNULL(PAG_CONTRIBUTO_DISAVANZO_COSTI_AMMESSI, 0.00)
			ELSE (DISAVANZO * QUOTA_CONTRIBUTO_RICHIESTO / 100) + ISNULL(PAG_CONTRIBUTO_DISAVANZO_COSTI_AMMESSI, 0.00)
		END AS SOMMA_DISAVANZO_CONTRIBUTO
	FROM ( 
		SELECT XX.*,
			CASE
				WHEN SPESE_AMMESSE > COSTO_INVESTIMENTO_CALC AND QUOTA_COMPLETAMENTO_AMMESSO <= 110
				THEN SPESE_AMMESSE - COSTO_INVESTIMENTO_CALC
				WHEN SPESE_AMMESSE > COSTO_INVESTIMENTO_CALC AND QUOTA_COMPLETAMENTO_AMMESSO > 110
				THEN COSTO_INVESTIMENTO * 10 / 100
				WHEN SPESE_AMMESSE < COSTO_INVESTIMENTO_CALC AND QUOTA_COMPLETAMENTO_AMMESSO >= 90
				THEN - (COSTO_INVESTIMENTO_CALC - SPESE_AMMESSE)
				WHEN SPESE_AMMESSE < COSTO_INVESTIMENTO_CALC AND QUOTA_COMPLETAMENTO_AMMESSO < 90
				THEN -COSTO_INVESTIMENTO_CALC * 10 / 100
			END AS DISAVANZO
		FROM (
			SELECT X.*,
				CASE
					WHEN (COSTO_INVESTIMENTO_CALC > 0 AND ID_PROGETTO IS NOT NULL)
					THEN 100 * PAG_IMPORTO_RICHIESTO / COSTO_INVESTIMENTO
					ELSE 0.00
				END AS QUOTA_COMPLETAMENTO,
				CASE
					WHEN (COSTO_INVESTIMENTO_CALC > 0 AND ID_PROGETTO IS NOT NULL)
					THEN 100 * ISNULL(PAG_IMPORTO_AMMESSO, 0.00) / COSTO_INVESTIMENTO
					ELSE 0.00
				END AS QUOTA_COMPLETAMENTO_AMMESSO,
				CASE
					WHEN (COSTO_INVESTIMENTO_CALC > 0 AND ID_PROGETTO IS NOT NULL)
					THEN ISNULL(PAG_IMPORTO_AMMESSO, 0.00) 
					ELSE 0.00
				END AS SPESE_AMMESSE
			FROM (
				SELECT I.ID_PROGETTO AS ID_PROGETTO,
					I.ID_INVESTIMENTO AS ID_INVESTIMENTO,
					I.COD_TIPO_INVESTIMENTO AS COD_TIPO_INVESTIMENTO,
					I.MISURA,
					I.SPESE_GENERALI,
					I.CODIFICA_INVESTIMENTO,
					I.DETTAGLIO_INVESTIMENTI,
					I.DESCRIZIONE AS DESCRIZIONE,
					I.SETTORE_PRODUTTIVO,
					I.COSTO_INVESTIMENTO,
					I.CONTRIBUTO_RICHIESTO,
					I.QUOTA_CONTRIBUTO_RICHIESTO,
					dbo.calcoloImportoPagamentiRichiestiInvestimento(I.ID_INVESTIMENTO, @DATA_MODIFICA_PAGAMENTO) AS IMPORTO_PAGAMENTO_RICHIESTO,
					PAG_CONTRIBUTO_RICHIESTO,
					PAG_IMPORTO_RICHIESTO, 
					PAG_IMPORTO_AMMESSO,
					PAG_CONTRIBUTO_AMMESSO,
					PAG_CONTRIBUTO_DISAVANZO_COSTI_AMMESSI,
					100 * PAG_IMPORTO_RICHIESTO / (I.COSTO_INVESTIMENTO + I.SPESE_GENERALI) AS PAG_PERC_RENDICONTAZIONE,
					IMP.RAGIONE_SOCIALE_INVESTIMENTO,
					IMP.DIMENSIONE_IMPRESA_INVESTIMENTO,
					IMP_SOGG_SPER.DESCRIZIONE AS IMP_SOGG_SPERIMENTATORE,
					ISNULL(I.COSTO_INVESTIMENTO, 0.00) + ISNULL(I.SPESE_GENERALI, 0.00) AS COSTO_INVESTIMENTO_CALC
				FROM vPROGETTO P 
					INNER JOIN VPIANO_INVESTIMENTI I ON P.ID_PROGETTO=I.ID_PROGETTO
					LEFT JOIN (SELECT ID_PROGETTO, 
									ID_INVESTIMENTO,
									PAG.CONTRIBUTO_RICHIESTO AS PAG_CONTRIBUTO_RICHIESTO,
									PAG.IMPORTO_RICHIESTO AS PAG_IMPORTO_RICHIESTO, 
									PAG.IMPORTO_AMMESSO AS PAG_IMPORTO_AMMESSO,
									PAG.CONTRIBUTO_AMMESSO AS PAG_CONTRIBUTO_AMMESSO,
									PAG.CONTRIBUTO_DISAVANZO_COSTI_AMMESSI AS PAG_CONTRIBUTO_DISAVANZO_COSTI_AMMESSI
								FROM VPAGAMENTI_RICHIESTI PAG
								WHERE 1 = 1
									AND @ID_PROGETTO = PAG.ID_PROGETTO
									AND (@ID_DOMANDA_PAGAMENTO IS NULL OR PAG.ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO)) PAG ON PAG.ID_INVESTIMENTO = I.ID_INVESTIMENTO 
					LEFT JOIN (SELECT PRI.ID_INVESTIMENTO, 
									IMP.RAGIONE_SOCIALE AS RAGIONE_SOCIALE_INVESTIMENTO,
									IMP.DIMENSIONE_IMPRESA AS DIMENSIONE_IMPRESA_INVESTIMENTO
								FROM PRIORITA_X_INVESTIMENTI PRI
									LEFT JOIN PRIORITA PRIO ON PRIO.ID_PRIORITA = PRI.ID_PRIORITA
									LEFT JOIN VIMPRESA IMP ON IMP.CODICE_FISCALE = PRI.VAL_TESTO
								WHERE 1 = 1
									AND PRIO.DESCRIZIONE LIKE '%Selezionare l`ente/l''impresa che ha in carico l`investimento%') IMP ON I.ID_INVESTIMENTO = IMP.ID_INVESTIMENTO
					LEFT JOIN (SELECT PRI_SP.ID_INVESTIMENTO, VAL.DESCRIZIONE 
								FROM PRIORITA_X_INVESTIMENTI PRI_SP 
									LEFT JOIN PRIORITA PRIO_SP ON PRIO_SP.ID_PRIORITA = PRI_SP.ID_PRIORITA
									LEFT JOIN VALORI_PRIORITA VAL ON VAL.ID_VALORE = PRI_SP.ID_VALORE
								WHERE 1 = 1
									AND PRIO_SP.DESCRIZIONE = 'Impresa / Soggetto sperimentatore') IMP_SOGG_SPER ON I.ID_INVESTIMENTO = IMP_SOGG_SPER.ID_INVESTIMENTO
				WHERE ISNULL(P.ID_PROG_INTEGRATO,P.ID_PROGETTO)=@ID_PROGETTO AND I.ID_VARIANTE=@ID_VARIANTE_ATTUALE
				 ) X ) XX ) XXX
	ORDER BY COD_TIPO_INVESTIMENTO, ID_INVESTIMENTO;
	
END
ELSE IF @COD_QUERY='VARIANTE_PRECEDENTE' BEGIN
	SET @ID_VARIANTE =(SELECT MAX(ID_VARIANTE) FROM VARIANTI WHERE ID_PROGETTO=@ID_PROGETTO AND APPROVATA=1 AND ANNULLATA=0 AND ID_VARIANTE<@ID_VARIANTE_ATTUALE)
	
	SELECT XXX.*,
		DISAVANZO * QUOTA_CONTRIBUTO_RICHIESTO / 100 AS DISAVANZO_CONTRIBUTO,
		CASE
			WHEN SPESE_AMMESSE > COSTO_INVESTIMENTO_CALC
			THEN (DISAVANZO * QUOTA_CONTRIBUTO_RICHIESTO / 100) - ISNULL(PAG_CONTRIBUTO_DISAVANZO_COSTI_AMMESSI, 0.00)
			ELSE (DISAVANZO * QUOTA_CONTRIBUTO_RICHIESTO / 100) + ISNULL(PAG_CONTRIBUTO_DISAVANZO_COSTI_AMMESSI, 0.00)
		END AS SOMMA_DISAVANZO_CONTRIBUTO
	FROM ( 
		SELECT XX.*,
			CASE
				WHEN SPESE_AMMESSE > COSTO_INVESTIMENTO_CALC AND QUOTA_COMPLETAMENTO_AMMESSO <= 110
				THEN SPESE_AMMESSE - COSTO_INVESTIMENTO_CALC
				WHEN SPESE_AMMESSE > COSTO_INVESTIMENTO_CALC AND QUOTA_COMPLETAMENTO_AMMESSO > 110
				THEN COSTO_INVESTIMENTO * 10 / 100
				WHEN SPESE_AMMESSE < COSTO_INVESTIMENTO_CALC AND QUOTA_COMPLETAMENTO_AMMESSO >= 90
				THEN - (COSTO_INVESTIMENTO_CALC - SPESE_AMMESSE)
				WHEN SPESE_AMMESSE < COSTO_INVESTIMENTO_CALC AND QUOTA_COMPLETAMENTO_AMMESSO < 90
				THEN -COSTO_INVESTIMENTO_CALC * 10 / 100
			END AS DISAVANZO
		FROM (
			SELECT X.*,
				CASE
					WHEN (COSTO_INVESTIMENTO_CALC > 0 AND ID_PROGETTO IS NOT NULL)
					THEN 100 * PAG_IMPORTO_RICHIESTO / COSTO_INVESTIMENTO
					ELSE 0.00
				END AS QUOTA_COMPLETAMENTO,
				CASE
					WHEN (COSTO_INVESTIMENTO_CALC > 0 AND ID_PROGETTO IS NOT NULL)
					THEN 100 * ISNULL(PAG_IMPORTO_AMMESSO, 0.00) / COSTO_INVESTIMENTO
					ELSE 0.00
				END AS QUOTA_COMPLETAMENTO_AMMESSO,
				CASE
					WHEN (COSTO_INVESTIMENTO_CALC > 0 AND ID_PROGETTO IS NOT NULL)
					THEN ISNULL(PAG_IMPORTO_AMMESSO, 0.00) 
					ELSE 0.00
				END AS SPESE_AMMESSE
			FROM (
				SELECT I.ID_PROGETTO AS ID_PROGETTO,
					I.ID_INVESTIMENTO AS ID_INVESTIMENTO,
					I.COD_TIPO_INVESTIMENTO AS COD_TIPO_INVESTIMENTO,
					I.MISURA,
					I.SPESE_GENERALI,
					I.CODIFICA_INVESTIMENTO,
					I.DETTAGLIO_INVESTIMENTI,
					I.DESCRIZIONE AS DESCRIZIONE,
					I.SETTORE_PRODUTTIVO,
					I.COSTO_INVESTIMENTO,
					I.CONTRIBUTO_RICHIESTO,
					I.QUOTA_CONTRIBUTO_RICHIESTO,
					dbo.calcoloImportoPagamentiRichiestiInvestimento(I.ID_INVESTIMENTO, @DATA_MODIFICA_PAGAMENTO) AS IMPORTO_PAGAMENTO_RICHIESTO,
					PAG_CONTRIBUTO_RICHIESTO,
					PAG_IMPORTO_RICHIESTO, 
					PAG_IMPORTO_AMMESSO,
					PAG_CONTRIBUTO_AMMESSO,
					PAG_CONTRIBUTO_DISAVANZO_COSTI_AMMESSI,
					100 * PAG_IMPORTO_RICHIESTO / (I.COSTO_INVESTIMENTO + I.SPESE_GENERALI) AS PAG_PERC_RENDICONTAZIONE,
					IMP.RAGIONE_SOCIALE_INVESTIMENTO,
					IMP.DIMENSIONE_IMPRESA_INVESTIMENTO,
					IMP_SOGG_SPER.DESCRIZIONE AS IMP_SOGG_SPERIMENTATORE,
					ISNULL(I.COSTO_INVESTIMENTO, 0.00) + ISNULL(I.SPESE_GENERALI, 0.00) AS COSTO_INVESTIMENTO_CALC
				FROM vPROGETTO P 
					INNER JOIN VPIANO_INVESTIMENTI I ON P.ID_PROGETTO=I.ID_PROGETTO
					LEFT JOIN (SELECT ID_PROGETTO, 
									ID_INVESTIMENTO,
									PAG.CONTRIBUTO_RICHIESTO AS PAG_CONTRIBUTO_RICHIESTO,
									PAG.IMPORTO_RICHIESTO AS PAG_IMPORTO_RICHIESTO, 
									PAG.IMPORTO_AMMESSO AS PAG_IMPORTO_AMMESSO,
									PAG.CONTRIBUTO_AMMESSO AS PAG_CONTRIBUTO_AMMESSO,
									PAG.CONTRIBUTO_DISAVANZO_COSTI_AMMESSI AS PAG_CONTRIBUTO_DISAVANZO_COSTI_AMMESSI
								FROM VPAGAMENTI_RICHIESTI PAG
								WHERE 1 = 1
									AND @ID_PROGETTO = PAG.ID_PROGETTO
									AND (@ID_DOMANDA_PAGAMENTO IS NULL OR PAG.ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO)) PAG ON PAG.ID_INVESTIMENTO = I.ID_INVESTIMENTO 
					LEFT JOIN (SELECT PRI.ID_INVESTIMENTO, 
									IMP.RAGIONE_SOCIALE AS RAGIONE_SOCIALE_INVESTIMENTO,
									IMP.DIMENSIONE_IMPRESA AS DIMENSIONE_IMPRESA_INVESTIMENTO
								FROM PRIORITA_X_INVESTIMENTI PRI
									LEFT JOIN PRIORITA PRIO ON PRIO.ID_PRIORITA = PRI.ID_PRIORITA
									LEFT JOIN VIMPRESA IMP ON IMP.CODICE_FISCALE = PRI.VAL_TESTO
								WHERE 1 = 1
									AND PRIO.DESCRIZIONE LIKE '%Selezionare l`ente/l''impresa che ha in carico l`investimento%') IMP ON I.ID_INVESTIMENTO = IMP.ID_INVESTIMENTO
					LEFT JOIN (SELECT PRI_SP.ID_INVESTIMENTO, VAL.DESCRIZIONE 
								FROM PRIORITA_X_INVESTIMENTI PRI_SP 
									LEFT JOIN PRIORITA PRIO_SP ON PRIO_SP.ID_PRIORITA = PRI_SP.ID_PRIORITA
									LEFT JOIN VALORI_PRIORITA VAL ON VAL.ID_VALORE = PRI_SP.ID_VALORE
								WHERE 1 = 1
									AND PRIO_SP.DESCRIZIONE = 'Impresa / Soggetto sperimentatore') IMP_SOGG_SPER ON I.ID_INVESTIMENTO = IMP_SOGG_SPER.ID_INVESTIMENTO
				WHERE ISNULL(P.ID_PROG_INTEGRATO,P.ID_PROGETTO)=@ID_PROGETTO AND
					((@ID_VARIANTE IS NULL AND I.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND I.ID_VARIANTE IS NULL) OR I.ID_VARIANTE=@ID_VARIANTE)
		 ) X ) XX ) XXX
	ORDER BY COD_TIPO_INVESTIMENTO, ID_INVESTIMENTO;
	
END
ELSE IF @COD_QUERY='INVESTIMENTI_DOMANDA_PAGAMENTO' BEGIN
	SELECT @DATA_MODIFICA_PAGAMENTO=DATA_MODIFICA,@COD_TIPO=COD_TIPO,@ID_VARIANTE=ID_VARIAZIONE_ACCERTATA 
	FROM DOMANDA_DI_PAGAMENTO 
	WHERE ID_DOMANDA_PAGAMENTO=@ID_DOMANDA_PAGAMENTO
	
	IF @ID_VARIANTE IS NULL
		SELECT @ID_VARIANTE=MAX(ID_VARIANTE) 
		FROM VARIANTI 
		WHERE ID_PROGETTO=@ID_PROGETTO AND APPROVATA=1 AND ANNULLATA=0 AND DATA_MODIFICA<@DATA_MODIFICA_PAGAMENTO
		
	SELECT XXX.*,
		DISAVANZO * QUOTA_CONTRIBUTO_RICHIESTO / 100 AS DISAVANZO_CONTRIBUTO,
		CASE
			WHEN SPESE_AMMESSE > COSTO_INVESTIMENTO_CALC
			THEN (DISAVANZO * QUOTA_CONTRIBUTO_RICHIESTO / 100) - ISNULL(PAG_CONTRIBUTO_DISAVANZO_COSTI_AMMESSI, 0.00)
			ELSE (DISAVANZO * QUOTA_CONTRIBUTO_RICHIESTO / 100) + ISNULL(PAG_CONTRIBUTO_DISAVANZO_COSTI_AMMESSI, 0.00)
		END AS SOMMA_DISAVANZO_CONTRIBUTO
	FROM ( 
		SELECT XX.*,
			CASE
				WHEN SPESE_AMMESSE > COSTO_INVESTIMENTO_CALC AND QUOTA_COMPLETAMENTO_AMMESSO <= 110
				THEN SPESE_AMMESSE - COSTO_INVESTIMENTO_CALC
				WHEN SPESE_AMMESSE > COSTO_INVESTIMENTO_CALC AND QUOTA_COMPLETAMENTO_AMMESSO > 110
				THEN COSTO_INVESTIMENTO * 10 / 100
				WHEN SPESE_AMMESSE < COSTO_INVESTIMENTO_CALC AND QUOTA_COMPLETAMENTO_AMMESSO >= 90
				THEN - (COSTO_INVESTIMENTO_CALC - SPESE_AMMESSE)
				WHEN SPESE_AMMESSE < COSTO_INVESTIMENTO_CALC AND QUOTA_COMPLETAMENTO_AMMESSO < 90
				THEN -COSTO_INVESTIMENTO_CALC * 10 / 100
			END AS DISAVANZO
		FROM (
			SELECT X.*,
				CASE
					WHEN (COSTO_INVESTIMENTO_CALC > 0 AND ID_PROGETTO IS NOT NULL)
					THEN 100 * PAG_IMPORTO_RICHIESTO / COSTO_INVESTIMENTO
					ELSE 0.00
				END AS QUOTA_COMPLETAMENTO,
				CASE
					WHEN (COSTO_INVESTIMENTO_CALC > 0 AND ID_PROGETTO IS NOT NULL)
					THEN 100 * ISNULL(PAG_IMPORTO_AMMESSO, 0.00) / COSTO_INVESTIMENTO
					ELSE 0.00
				END AS QUOTA_COMPLETAMENTO_AMMESSO,
				CASE
					WHEN (COSTO_INVESTIMENTO_CALC > 0 AND ID_PROGETTO IS NOT NULL)
					THEN ISNULL(PAG_IMPORTO_AMMESSO, 0.00) 
					ELSE 0.00
				END AS SPESE_AMMESSE
			FROM (
				SELECT I.ID_PROGETTO AS ID_PROGETTO,
					I.ID_INVESTIMENTO AS ID_INVESTIMENTO,
					I.COD_TIPO_INVESTIMENTO AS COD_TIPO_INVESTIMENTO,
					I.MISURA,
					I.SPESE_GENERALI,
					I.CODIFICA_INVESTIMENTO,
					I.DETTAGLIO_INVESTIMENTI,
					I.DESCRIZIONE AS DESCRIZIONE,
					I.SETTORE_PRODUTTIVO,
					I.COSTO_INVESTIMENTO,
					I.CONTRIBUTO_RICHIESTO,
					I.QUOTA_CONTRIBUTO_RICHIESTO,
					dbo.calcoloImportoPagamentiRichiestiInvestimento(I.ID_INVESTIMENTO, @DATA_MODIFICA_PAGAMENTO) AS IMPORTO_PAGAMENTO_RICHIESTO,
					PAG_CONTRIBUTO_RICHIESTO,
					PAG_IMPORTO_RICHIESTO, 
					PAG_IMPORTO_AMMESSO,
					PAG_CONTRIBUTO_AMMESSO,
					PAG_CONTRIBUTO_DISAVANZO_COSTI_AMMESSI,
					100 * PAG_IMPORTO_RICHIESTO / (I.COSTO_INVESTIMENTO + I.SPESE_GENERALI) AS PAG_PERC_RENDICONTAZIONE,
					IMP.RAGIONE_SOCIALE_INVESTIMENTO,
					IMP.DIMENSIONE_IMPRESA_INVESTIMENTO,
					IMP_SOGG_SPER.DESCRIZIONE AS IMP_SOGG_SPERIMENTATORE,
					ISNULL(I.COSTO_INVESTIMENTO, 0.00) + ISNULL(I.SPESE_GENERALI, 0.00) AS COSTO_INVESTIMENTO_CALC
				FROM vPROGETTO P 
					INNER JOIN VPIANO_INVESTIMENTI I ON P.ID_PROGETTO=I.ID_PROGETTO
					LEFT JOIN (SELECT ID_PROGETTO, 
									ID_INVESTIMENTO,
									PAG.CONTRIBUTO_RICHIESTO AS PAG_CONTRIBUTO_RICHIESTO,
									PAG.IMPORTO_RICHIESTO AS PAG_IMPORTO_RICHIESTO, 
									PAG.IMPORTO_AMMESSO AS PAG_IMPORTO_AMMESSO,
									PAG.CONTRIBUTO_AMMESSO AS PAG_CONTRIBUTO_AMMESSO,
									PAG.CONTRIBUTO_DISAVANZO_COSTI_AMMESSI AS PAG_CONTRIBUTO_DISAVANZO_COSTI_AMMESSI
								FROM VPAGAMENTI_RICHIESTI PAG
								WHERE 1 = 1
									AND @ID_PROGETTO = PAG.ID_PROGETTO
									AND (@ID_DOMANDA_PAGAMENTO IS NULL OR PAG.ID_DOMANDA_PAGAMENTO = @ID_DOMANDA_PAGAMENTO)) PAG ON PAG.ID_INVESTIMENTO = I.ID_INVESTIMENTO 
					LEFT JOIN (SELECT PRI.ID_INVESTIMENTO, 
									IMP.RAGIONE_SOCIALE AS RAGIONE_SOCIALE_INVESTIMENTO,
									IMP.DIMENSIONE_IMPRESA AS DIMENSIONE_IMPRESA_INVESTIMENTO
								FROM PRIORITA_X_INVESTIMENTI PRI
									LEFT JOIN PRIORITA PRIO ON PRIO.ID_PRIORITA = PRI.ID_PRIORITA
									LEFT JOIN VIMPRESA IMP ON IMP.CODICE_FISCALE = PRI.VAL_TESTO
								WHERE 1 = 1
									AND PRIO.DESCRIZIONE LIKE '%Selezionare l`ente/l''impresa che ha in carico l`investimento%') IMP ON I.ID_INVESTIMENTO = IMP.ID_INVESTIMENTO
					LEFT JOIN (SELECT PRI_SP.ID_INVESTIMENTO, VAL.DESCRIZIONE 
								FROM PRIORITA_X_INVESTIMENTI PRI_SP 
									LEFT JOIN PRIORITA PRIO_SP ON PRIO_SP.ID_PRIORITA = PRI_SP.ID_PRIORITA
									LEFT JOIN VALORI_PRIORITA VAL ON VAL.ID_VALORE = PRI_SP.ID_VALORE
								WHERE 1 = 1
									AND PRIO_SP.DESCRIZIONE = 'Impresa / Soggetto sperimentatore') IMP_SOGG_SPER ON I.ID_INVESTIMENTO = IMP_SOGG_SPER.ID_INVESTIMENTO
				WHERE ISNULL(P.ID_PROG_INTEGRATO,P.ID_PROGETTO)=@ID_PROGETTO AND ISNULL(I.COD_VARIAZIONE,'')!='A' AND
					((ORDINE_FASE IS NULL AND I.ID_INVESTIMENTO_ORIGINALE IS NULL AND I.ID_VARIANTE IS NULL) OR 
					(ORDINE_FASE<4 AND I.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND I.ID_VARIANTE IS NULL) OR
					(ORDINE_FASE>=4  AND ((@ID_VARIANTE IS NULL AND I.ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND I.ID_VARIANTE IS NULL) OR
					 I.ID_VARIANTE=@ID_VARIANTE))) ) X ) XX ) XXX
	ORDER BY COD_TIPO_INVESTIMENTO, ID_INVESTIMENTO;
	
END/*
ELSE IF @COD_QUERY='SPESE_DOMANDA_PAGAMENTO' BEGIN -- DA RIFARE
	SELECT @DATA_MODIFICA_PAGAMENTO=DATA_MODIFICA,@COD_TIPO=COD_TIPO,@ID_VARIANTE=ID_VARIAZIONE_ACCERTATA FROM DOMANDA_DI_PAGAMENTO 
	WHERE ID_DOMANDA_PAGAMENTO=@ID_DOMANDA_PAGAMENTO
	IF @ID_VARIANTE IS NULL
		SELECT @ID_VARIANTE=MAX(ID_VARIANTE) FROM VARIANTI WHERE ID_PROGETTO=@ID_PROGETTO AND APPROVATA=1 AND ANNULLATA=0 AND DATA_MODIFICA<@DATA_MODIFICA_PAGAMENTO
	SELECT I.*,Q1.CODICE AS CODICE_MISURA FROM PROGETTO AS P INNER JOIN PIANO_INVESTIMENTI AS I 
    ON P.ID_PROGETTO=I.ID_PROGETTO INNER JOIN(SELECT DISTINCT ID_BANDO ,CODICE FROM  PROGRAMMAZIONE_BANDO 
    AS PB INNER JOIN PROGRAMMAZIONE ON PB.ID_PROGRAMMAZIONE = PROGRAMMAZIONE.ID_PROGRAMMAZIONE INNER JOIN
    MISURA ON PROGRAMMAZIONE.ID_PSR = MISURA.ID_PSR AND PROGRAMMAZIONE.COD_OBIETTIVO = MISURA.COD_OBIETTIVO 
    AND PROGRAMMAZIONE.COD_ASSE = MISURA.COD_ASSE AND PROGRAMMAZIONE.COD_MISURA = MISURA.COD_MISURA
    WHERE PB.MISURA_PREVALENTE=1) AS Q1 ON P.ID_BANDO=Q1.ID_BANDO WHERE COD_TIPO_INVESTIMENTO IN (4,5) AND
		ISNULL(P.ID_PROG_INTEGRATO,P.ID_PROGETTO)=@ID_PROGETTO AND
		((@ID_VARIANTE IS NULL AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL) OR
		 (ID_VARIANTE=@ID_VARIANTE AND ISNULL(COD_VARIAZIONE,'X')!='A')) ORDER BY COD_TIPO_INVESTIMENTO DESC,ID_INVESTIMENTO
END*/
