
CREATE PROCEDURE [dbo].[RptPianoInvestimentiXId]
(
@IdInvestimento int
)
AS
BEGIN	

SET NOCOUNT ON;

--DECLARE @IdVariante int , @IdInvestimento int = 3312
--DECLARE @COD_Tipo_Investimento int
--SET @IdVariante = 248
--SET @COD_Tipo_Investimento = 1


DECLARE @Count int

SET @Count = (SELECT COUNT(ID_INVESTIMENTO) 
				FROM VPIANO_INVESTIMENTI 
				WHERE ID_INVESTIMENTO = @IdInvestimento)

IF (@Count > 0)
BEGIN

DECLARE @ID_Domanda INT 
SET @ID_Domanda = (SELECT ISNULL(ID_PROG_INTEGRATO, P.ID_PROGETTO) 
									FROM PROGETTO P INNER JOIN PIANO_INVESTIMENTI I ON P.ID_PROGETTO = I.ID_PROGETTO WHERE ID_INVESTIMENTO = @IdInvestimento)

	DECLARE @TMP AS TABLE (ID_PRIORITA INT, ID_INVESTIMENTO INT, TESTO VARCHAR(MAX), VAL_TESTO VARCHAR(1000), DESCRIZIONE VARCHAR(1000), FATTO BIT)

INSERT INTO @TMP
select PP.ID_PRIORITA, PIN.ID_INVESTIMENTO, Q.TESTO, VAL_TESTO, NULL, 0
from vPIANO_INVESTIMENTI PIN
INNER JOIN vPROGETTO AS P ON PIN.ID_PROGETTO = P.ID_PROGETTO
INNER JOIN vPRIORITA_X_INVESTIMENTI PP ON PIN.ID_INVESTIMENTO = PP.ID_INVESTIMENTO
inner join PRIORITA PRIO ON PP.ID_PRIORITA = PRIO.ID_PRIORITA
INNER JOIN dbo.zQUERY_SQL Q ON PRIO.QUERY_PLURIVALORE = Q.NOME
WHERE  PIN.ID_INVESTIMENTO = @IdInvestimento AND PIN.COD_TIPO_INVESTIMENTO = 1 AND ISNULL(COD_VARIAZIONE,'x')!='A'
WHILE (
SELECT COUNT(*) FROM @TMP WHERE FATTO = 0) > 0
BEGIN 

DECLARE @TESTO nVARCHAR(MAX), @ID_PRIORITA INT, @DESCRIZIONE VARCHAR(1000), @COD VARCHAR(1000)
SELECT TOP 1 @TESTO = TESTO, @ID_PRIORITA = ID_PRIORITA, @COD = VAL_TESTO
FROM @TMP WHERE FATTO = 0 

IF(@TESTO IS NOT NULL) 
BEGIN
	DECLARE @RISULT AS TABLE (CODICE VARCHAR(1000), DESCRIZIONE VARCHAR(1000))
	INSERT INTO @RISULT 
		EXECute sp_executesql @TESTO,N'@CODICE VARCHAR(1000), @IdProgetto INT, @fase_istruttoria BIT',@COD, @ID_Domanda, 1
	SELECT @DESCRIZIONE = case when DESCRIZIONE != @cod then descrizione else CODICE end FROM @RISULT	
END
UPDATE @TMP
SET DESCRIZIONE = @DESCRIZIONE, FATTO = 1 
WHERE ID_PRIORITA = @ID_PRIORITA

END

		SELECT     vPIANO_INVESTIMENTI.DESCRIZIONE, vPIANO_INVESTIMENTI.QUANTITA, vPIANO_INVESTIMENTI.COSTO_INVESTIMENTO, 
                      vPIANO_INVESTIMENTI.SPESE_GENERALI, vPIANO_INVESTIMENTI.CONTRIBUTO_RICHIESTO, 
                      vPIANO_INVESTIMENTI.QUOTA_CONTRIBUTO_RICHIESTO, vPIANO_INVESTIMENTI.ID_OBIETTIVO_MISURA, vPIANO_INVESTIMENTI.AMMESSO, 
                      vPIANO_INVESTIMENTI.COD_TP, vPIANO_INVESTIMENTI.CODIFICA_INVESTIMENTO, vPIANO_INVESTIMENTI.AIUTO_MINIMO, 
                      vPIANO_INVESTIMENTI.CODICE, vPIANO_INVESTIMENTI.SPECIFICA_INVESTIMENTI, vPIANO_INVESTIMENTI.DETTAGLIO_INVESTIMENTI, 
                      vPIANO_INVESTIMENTI.MOBILE, vPIANO_INVESTIMENTI.QUOTA_SPESE_GENERALI, vPIANO_INVESTIMENTI.SETTORE_PRODUTTIVO, 
                      vPIANO_INVESTIMENTI.MISURA, vPIANO_INVESTIMENTI.VALUTAZIONE_INVESTIMENTO, zOB_MISURA.CODICE as COD_OB_MISURA, 
                      zOB_MISURA.DESCRIZIONE AS DESCRIZIONE_OBIETTIVI_MISURA, 
                      vzPROGRAMMAZIONE.CODICE as COD_INTERVENTO, 
                      vzPROGRAMMAZIONE.DESCRIZIONE AS DESCRIZIONE_INTERVENTO, UNITA_DI_MISURA.DESCRIZIONE AS DESCRIZIONE_UNITA_MISURA, 
                      zSTP.DESCRIZIONE AS DESCRIZIONE_STP, PRIORITA_SETTORIALI.DESCRIZIONE AS DESCRIZIONE_PRIORITA_SETTORIALE, 
                      PRIORITA.DESCRIZIONE AS DESCRIZIONE_PRIORITA, VPRIORITA_X_INVESTIMENTI.SCELTO AS PRIORITA_SELEZIONATA, 
	           ISNULL(VPRIORITA_X_INVESTIMENTI.DESCRIZIONE, '')  + ISNULL(CONVERT(VARCHAR(15),  vPRIORITA_X_INVESTIMENTI.VAL_DATA, 103), '')   +  ISNULL(TMP.DESCRIZIONE, ISNULL(vPRIORITA_X_INVESTIMENTI.VAL_TESTO, '')) AS DESCRIZIONE_SELEZIONATA, VPRIORITA_X_INVESTIMENTI.VALORE AS INPUT_SELEZIONATO,
                     vPIANO_INVESTIMENTI.ID_INVESTIMENTO, 
						vPIANO_INVESTIMENTI.ID_INVESTIMENTO_ORIGINALE,PRIORITA_SETTORIALI.ID_PRIORITA_SETTORIALE, vPIANO_INVESTIMENTI.COD_TIPO_INVESTIMENTO
FROM         vPIANO_INVESTIMENTI INNER JOIN 
                      PROGETTO ON vPIANO_INVESTIMENTI.ID_PROGETTO = PROGETTO.ID_PROGETTO INNER JOIN
                      zOB_MISURA ON vPIANO_INVESTIMENTI.ID_OBIETTIVO_MISURA = zOB_MISURA.ID INNER JOIN
                      vzPROGRAMMAZIONE ON vPIANO_INVESTIMENTI.ID_PROGRAMMAZIONE = vzPROGRAMMAZIONE.ID 
                      LEFT JOIN UNITA_DI_MISURA ON vPIANO_INVESTIMENTI.ID_UNITA_MISURA = UNITA_DI_MISURA.ID_UNITA_MISURA 
               LEFT OUTER JOIN
                      zSTP ON vPIANO_INVESTIMENTI.ID_PROGRAMMAZIONE = zSTP.ID_PROGRAMMAZIONE AND ZSTP.CODICE = vPIANO_INVESTIMENTI.COD_STP LEFT JOIN
                     vPRIORITA_X_INVESTIMENTI ON vPIANO_INVESTIMENTI.ID_INVESTIMENTO = vPRIORITA_X_INVESTIMENTI.ID_INVESTIMENTO 
LEFT JOIN
                     PRIORITA ON vPRIORITA_X_INVESTIMENTI.ID_PRIORITA = PRIORITA.ID_PRIORITA 
LEFT JOIN
                      PRIORITA_SETTORIALI ON vPIANO_INVESTIMENTI.ID_PRIORITA_SETTORIALE = PRIORITA_SETTORIALI.ID_PRIORITA_SETTORIALE 
                     LEFT JOIN @TMP TMP ON  PRIORITA.ID_PRIORITA  = TMP.ID_PRIORITA  
WHERE     (vPIANO_INVESTIMENTI.ID_INVESTIMENTO = @IdInvestimento)
END

ELSE SELECT NULL AS DESCRIZIONE,
            NULL AS CODICE_MISURA,
		    NULL AS SETTORE_PRODUTTIVO,
		    NULL AS COSTO_INVESTIMENTO,
		    NULL AS SPESE_GENERALI,
		    NULL AS CONTRIBUTO_AMMISSIBILE, 
			NULL AS QUOTA_CONTRIBUTO_AMMISSIBILE,
			NULL AS ID_PRIORITA_SETTORIALE,
		    NULL AS RATA_REINTEGRAZIONE,
			NULL AS TOTALE_CONTRIBUTO,
			NULL AS DETTAGLIO_INVESTIMENTI,
			NULL AS CODIFICA_INVESTIMENTO,
			NULL AS TOTALE_CONTRIBUTO_TRONCATO, 
			NULL AS RENDIMENTO_GLOBALE,
			NULL AS COD_VARIAZIONE, 
			NULL AS TASSO_ABBUONO    
END






