CREATE PROCEDURE [dbo].[RptQuadroKSelect]
(
@ID_Domanda int,
@COD_Tipo_Investimento int	
)
AS
BEGIN	

SET NOCOUNT ON;

--DECLARE @ID_Domanda int 
--DECLARE @COD_Tipo_Investimento int
--SET @ID_Domanda = 255
--SET @COD_Tipo_Investimento = 1


DECLARE @Count int
DECLARE @ID_VARIANTE int 
DECLARE @CONTR_TOTALE DECIMAL(18, 2)
DECLARE @CONTR_FUNZIONE DECIMAL(18, 2)
DECLARE @TOTALE DECIMAL(18, 2)
DECLARE @FASE BIT
DECLARE @CONTR_TOTALE_ALTRE_FONTI DECIMAL(18,2)
DECLARE @USO_FEM BIT

SET @ID_VARIANTE =(SELECT MAX(ID_VARIANTE) FROM VARIANTI WHERE ID_PROGETTO=@ID_Domanda AND APPROVATA = 1)
SET @FASE = (SELECT CASE WHEN ORDINE_FASE>=2 THEN 1 ELSE 0 END  FROM vPROGETTO  WHERE ID_PROGETTO = @ID_Domanda)

--Aggiunto 23/03/2018 per gestione visibilità colonne quota FEM
SET @USO_FEM = (SELECT TOP(1)
				--P.ID_BANDO,
				ISNULL(CONVERT(BIT, BC.VALORE),0) AS VALORE
				FROM vPROGETTO P 
				INNER JOIN BANDO B ON P.ID_BANDO = B.ID_BANDO
				LEFT OUTER JOIN BANDO_CONFIG BC ON
				B.ID_BANDO = BC.ID_BANDO
				AND
				BC.COD_TIPO = 'UTSTRUMFIN' 
				WHERE P.ID_PROGETTO = @ID_Domanda)
--fine aggiunta


SET @Count = (SELECT COUNT(I.ID_INVESTIMENTO) 
				FROM VPROGETTO AS P INNER JOIN VPIANO_INVESTIMENTI AS I ON P.ID_PROGETTO=I.ID_PROGETTO
				WHERE (P.ID_PROGETTO=@ID_Domanda OR P.ID_PROG_INTEGRATO=@ID_Domanda) AND
					((ORDINE_FASE IS NULL AND ID_INVESTIMENTO_ORIGINALE IS NULL AND ID_VARIANTE IS NULL) OR 
					(ORDINE_FASE<4 AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL) OR
					(ORDINE_FASE>=4  AND ((@ID_VARIANTE IS NULL AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL) OR
					 ID_VARIANTE=@ID_VARIANTE))) AND I.COD_TIPO_INVESTIMENTO = @COD_Tipo_Investimento)

IF (@Count > 0)
BEGIN
	SET @CONTR_TOTALE = 0
	SET @CONTR_FUNZIONE = 0
	SET @CONTR_TOTALE = (SELECT SUM(ISNULL(CONTRIBUTO_RICHIESTO, 0)) 
								FROM PIANO_INVESTIMENTI INNER JOIN vPROGETTO P ON PIANO_INVESTIMENTI.ID_PROGETTO = P.ID_PROGETTO
								WHERE ((P.ID_PROG_INTEGRATO IS NULL AND P.ID_PROGETTO= @ID_Domanda) OR P.ID_PROG_INTEGRATO=@ID_Domanda) AND
									((ORDINE_FASE IS NULL AND ID_INVESTIMENTO_ORIGINALE IS NULL AND ID_VARIANTE IS NULL) OR 
									(ORDINE_FASE<4 AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL) OR
									(ORDINE_FASE>=4  AND ((@ID_VARIANTE IS NULL AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL) OR
									 ID_VARIANTE=@ID_VARIANTE))) AND COD_TIPO_INVESTIMENTO = @COD_Tipo_Investimento AND ISNULL(COD_VARIAZIONE,'x')!='A')
	
	--Aggiunto 23/03/2018
	SET @CONTR_TOTALE_ALTRE_FONTI = (SELECT SUM(ISNULL(CONTRIBUTO_ALTRE_FONTI, 0)) 
								FROM PIANO_INVESTIMENTI INNER JOIN vPROGETTO P ON PIANO_INVESTIMENTI.ID_PROGETTO = P.ID_PROGETTO
								WHERE ((P.ID_PROG_INTEGRATO IS NULL AND P.ID_PROGETTO= @ID_Domanda) OR P.ID_PROG_INTEGRATO=@ID_Domanda) AND
									((ORDINE_FASE IS NULL AND ID_INVESTIMENTO_ORIGINALE IS NULL AND ID_VARIANTE IS NULL) OR 
									(ORDINE_FASE<4 AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL) OR
									(ORDINE_FASE>=4  AND ((@ID_VARIANTE IS NULL AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL) OR
									 ID_VARIANTE=@ID_VARIANTE))) AND COD_TIPO_INVESTIMENTO = @COD_Tipo_Investimento AND ISNULL(COD_VARIAZIONE,'x')!='A')
	
	--fine aggiunta
	SET @CONTR_FUNZIONE = (SELECT dbo.calcoloContributoInvestimentiProgetto(@ID_Domanda, @FASE, @ID_VARIANTE))


	SELECT I.ID_INVESTIMENTO, I.ID_INVESTIMENTO_ORIGINALE,  I.DESCRIZIONE, I.SETTORE_PRODUTTIVO,
				   I.COSTO_INVESTIMENTO,
				   I.SPESE_GENERALI,
				   I.CONTRIBUTO_RICHIESTO AS CONTRIBUTO_AMMISSIBILE,
				   I.QUOTA_CONTRIBUTO_RICHIESTO AS QUOTA_CONTRIBUTO_AMMISSIBILE,
				   I.QUOTA_CONTRIBUTO_ALTRE_FONTI AS QUOTA_CONTRIBUTO_ALTRE_FONTI, --aggiunto 23/03/2018 
				   I.CONTRIBUTO_ALTRE_FONTI AS CONTRIBUTO_ALTRE_FONTI_AMMISSIBILE, --aggiunto 23/03/2018
				   I.ID_PRIORITA_SETTORIALE,
				   I.CODIFICA_INVESTIMENTO,
				   I.DETTAGLIO_INVESTIMENTI,
				   DENSE_RANK() over (ORDER BY I.ID_INVESTIMENTO) AS ROWS,
				   RATA_REINTEGRAZIONE = CASE MOBILE
											WHEN 1 THEN ((I.COSTO_INVESTIMENTO + I.SPESE_GENERALI)/10)
											WHEN 0 THEN ((I.COSTO_INVESTIMENTO + I.SPESE_GENERALI)/30)
											ELSE 0
											END, 
					@CONTR_TOTALE AS TOTALE_CONTRIBUTO, 
					@CONTR_TOTALE_ALTRE_FONTI AS TOTALE_CONTRIBUTO_ALTRE_FONTI, --aggiunto 23/03/2018
					@CONTR_FUNZIONE AS TOTALE_CONTRIBUTO_TRONCATO,
					(SELECT     VALORI_PRIORITA.CODICE
					FROM         PRIORITA_X_INVESTIMENTI INNER JOIN
										  VALORI_PRIORITA ON PRIORITA_X_INVESTIMENTI.ID_VALORE = VALORI_PRIORITA.ID_VALORE INNER JOIN
										  PIANO_INVESTIMENTI ON PRIORITA_X_INVESTIMENTI.ID_INVESTIMENTO = PIANO_INVESTIMENTI.ID_INVESTIMENTO INNER JOIN
										  PROGETTO ON PIANO_INVESTIMENTI.ID_PROGETTO = PROGETTO.ID_PROGETTO
					WHERE     (PRIORITA_X_INVESTIMENTI.ID_PRIORITA IN (37,88, 92, 93, 94, 102, 103,116) ) AND PRIORITA_X_INVESTIMENTI.ID_INVESTIMENTO = I.ID_INVESTIMENTO
					) AS RENDIMENTO_GLOBALE, 
					COD_VARIAZIONE, 
					I.QUANTITA, 
					U.DESCRIZIONE AS UNITA_MISURA,
					MISURA, 
					I.NON_COFINANZIATO,
					@USO_FEM AS USO_FEM --aggiunto 23/03/2018
	FROM vPROGETTO AS P 
		INNER JOIN VPIANO_INVESTIMENTI AS I ON P.ID_PROGETTO=I.ID_PROGETTO
		LEFT JOIN UNITA_DI_MISURA U ON I.ID_UNITA_MISURA = U.ID_UNITA_MISURA
	WHERE (P.ID_PROGETTO=@ID_Domanda OR P.ID_PROG_INTEGRATO=@ID_Domanda) AND
					((ORDINE_FASE IS NULL AND ID_INVESTIMENTO_ORIGINALE IS NULL AND ID_VARIANTE IS NULL) OR 
					(ORDINE_FASE<4 AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL) OR
					(ORDINE_FASE>=4  AND ((@ID_VARIANTE IS NULL AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND ID_VARIANTE IS NULL) OR
					 ID_VARIANTE=@ID_VARIANTE))) AND I.COD_TIPO_INVESTIMENTO = @COD_Tipo_Investimento AND ISNULL(COD_VARIAZIONE,'x')!='A'
	ORDER BY  COD_TIPO_INVESTIMENTO,ID_INVESTIMENTO
END

ELSE SELECT NULL AS DESCRIZIONE,
            NULL AS CODICE_MISURA,
		    NULL AS SETTORE_PRODUTTIVO,
		    NULL AS COSTO_INVESTIMENTO,
		    NULL AS SPESE_GENERALI,
		    NULL AS CONTRIBUTO_AMMISSIBILE, 
			NULL AS QUOTA_CONTRIBUTO_AMMISSIBILE,
			NULL AS QUOTA_CONTRIBUTO_ALTRE_FONTI, --aggiunto 23/03/2018 
			NULL AS	CONTRIBUTO_ALTRE_FONTI_AMMISSIBILE, --aggiunto 23/03/2018 
			NULL AS CODIFICA_INVESTIMENTO,
			NULL AS DETTAGLIO_INVESTIMENTI,
			NULL AS ID_PRIORITA_SETTORIALE,
		    NULL AS RATA_REINTEGRAZIONE,
			NULL AS TOTALE_CONTRIBUTO,
			NULL AS TOTALE_CONTRIBUTO_ALTRE_FONTI, --aggiunto 23/03/2018 
			NULL AS TOTALE_CONTRIBUTO_TRONCATO, 
			NULL AS RENDIMENTO_GLOBALE,
			NULL AS QUANTITA, 
			NULL AS UNITA_MISURA,
			NULL AS MISURA,
			NULL AS NON_COFINANZIATO,
			NULL AS USO_FEM
			    
END
