CREATE PROCEDURE [dbo].[RptQuadroInsediamentoPlurimo] 
@ID_Domanda int
AS
BEGIN
	SET NOCOUNT ON;
	
	IF(SELECT COUNT(*) 
	FROM PROGETTO P 
	INNER JOIN vPERSONE_X_IMPRESE PI ON P.ID_IMPRESA = PI.ID_IMPRESA
	WHERE P.ID_PROGETTO = @ID_Domanda AND PI.COD_RUOLO = 'C') > 0 
	
	SELECT NOME, COGNOME, CODICE_FISCALE, DATA_INIZIO, DATA_NASCITA 
	FROM PROGETTO P 
	INNER JOIN vPERSONE_X_IMPRESE PI ON P.ID_IMPRESA = PI.ID_IMPRESA
	WHERE P.ID_PROGETTO = @ID_Domanda AND PI.COD_RUOLO = 'C'
	
	ELSE 
	SELECT NULL AS NOME, NULL AS COGNOME, NULL AS CODICE_FISCALE, NULL AS DATA_INIZIO, NULL AS DATA_NASCITA

END
