

CREATE PROCEDURE [dbo].[RptQuadroASelect_RappresentanteLegale]
@ID_Domanda int	
AS
BEGIN	

DECLARE @ID_IMPRESA int
SET @ID_IMPRESA = (SELECT ID_IMPRESA FROM dbo.PROGETTO WHERE ID_PROGETTO = @ID_Domanda)

IF (@ID_IMPRESA IS NOT NULL)
BEGIN
	   SELECT PXI.NOME,
       PXI.COGNOME,
	   PXI.CODICE_FISCALE,
       PXI.SESSO,
       PXI.DATA_NASCITA,
       PXI.COMUNE AS COMUNE_NASCITA,
       PXI.SIGLA AS PROVINCIA_NASCITA,
       IND.TELEFONO,
       IND.FAX,
       IND.EMAIL,
       IND.VIA AS VIA_RESIDENZA,
       IND.LOCALITA AS LOCALITA_RESIDENZA,
       IND.COMUNE AS COMUNE_RESIDENZA, 
       IND.CAP AS CAP_RESIDENZA,
       IND.ISTAT AS ISTAT_COMUNE_RESIDENZA,
       IND.COD_PROVINCIA AS ISTAT_PROVINCIA_RESIDENZA,
       IND.SIGLA AS PROVINCIA_RESIDENZA,
       P.ID_BANDO          
       
	   FROM dbo.IMPRESA I INNER JOIN vPERSONE_X_IMPRESE PXI ON (I.ID_RAPPRLEGALE_ULTIMO = PXI.ID_PERSONE_X_IMPRESE)
						  INNER JOIN VINDIRIZZARIO IND ON (PXI.ID_PERSONA = IND.ID_PERSONA) AND IND.FLAG_ATTIVO = 1
						  INNER JOIN PROGETTO P ON P.ID_IMPRESA = I.ID_IMPRESA 
	   WHERE P.ID_PROGETTO = @ID_Domanda 
END
ELSE 
	BEGIN

		 SELECT NULL AS NOME,
				NULL AS COGNOME,
				NULL AS CODICE_FISCALE,
				NULL AS SESSO,
				NULL AS DATA_NASCITA,
				NULL AS COMUNE_NASCITA,
				NULL AS PROVINCIA_NASCITA,
				NULL AS TELEFONO,
				NULL AS FAX,
				NULL AS EMAIL,
				NULL AS VIA_RESIDENZA,
				NULL AS LOCALITA_RESIDENZA,
				NULL AS COMUNE_RESIDENZA,
				NULL AS CAP_RESIDENZA,
				NULL AS ISTAT_COMUNE_RESIDENZA,
				NULL AS ISTAT_PROVINCIA_RESIDENZA,
				NULL AS PROVINCIA_RESIDENZA,
				NULL AS ID_BANDO
	END
END

