CREATE PROCEDURE [dbo].RptQuadroSoci
@ID_Domanda int	
AS
BEGIN	
	--declare @ID_Domanda int	= 10517
SET NOCOUNT ON;

DECLARE @Count int

SET @Count = (SELECT COUNT(*) 
				FROM PRIORITA P INNER JOIN PRIORITA_X_PROGETTO PP ON (P.ID_PRIORITA = PP.ID_PRIORITA)
						LEFT JOIN VALORI_PRIORITA VP ON (PP.ID_VALORE = VP.ID_VALORE)
						INNER JOIN PROGETTO PR ON (PR.ID_PROGETTO = PP.ID_PROGETTO)
						INNER JOIN vIMPRESA_AGGREGAZIONE A ON PP.VAL_TESTO = A.ID_AGGREGAZIONE
				WHERE P.COD_LIVELLO = 'D' 
	AND (PR.ID_PROGETTO = @ID_Domanda OR ID_PROG_INTEGRATO = @ID_Domanda) 
	AND P.PLURI_VALORE_SQL = 1)

IF (@Count > 0)
BEGIN

	SELECT A.DENOMINAZIONE AS AGGREGAZIONE, A.CUAA, A.RAGIONE_SOCIALE, 
	A.ATTIVO, A.DATA_INIZIO, A.DATA_FINE
	FROM PRIORITA P INNER JOIN PRIORITA_X_PROGETTO PP ON (P.ID_PRIORITA = PP.ID_PRIORITA)
						LEFT JOIN VALORI_PRIORITA VP ON (PP.ID_VALORE = VP.ID_VALORE)
						INNER JOIN PROGETTO PR ON (PR.ID_PROGETTO = PP.ID_PROGETTO)
						INNER JOIN vIMPRESA_AGGREGAZIONE A ON PP.VAL_TESTO = A.ID_AGGREGAZIONE
	WHERE P.COD_LIVELLO = 'D' 
	AND (PR.ID_PROGETTO = @ID_Domanda OR ID_PROG_INTEGRATO = @ID_Domanda) 
	AND P.PLURI_VALORE_SQL = 1
	
END

ELSE SELECT NULL  AS AGGREGAZIONE, NULL AS CUAA, NULL AS RAGIONE_SOCIALE, 
	 NULL AS ATTIVO, NULL AS DATA_INIZIO, NULL AS DATA_FINE

END
