CREATE PROCEDURE [dbo].[RptQuadroProduzioneStandardConnesse]
(
	@ID_PROGETTO int, 
	@PREVISIONALE BIT
)
AS
BEGIN	

	DECLARE @AMMESSO BIT =0
	IF(SELECT COD_STATO FROM vPROGETTO WHERE ID_PROGETTO = @ID_PROGETTO) != 'P' 
	SET @AMMESSO = 1 

	DECLARE @ID_PS INT 
	SELECT @ID_PS = ID FROM PRODUZIONE_STANDARD 
	WHERE ID_PROGETTO =@ID_PROGETTO and PREVISIONALE = @PREVISIONALE AND AMMESSO = @AMMESSO
	
	SELECT QUANTITA_ATTCONN, p.PS_REALE, I.DESCRIZIONE AS ATTIVITA_CONNESSA, PREZZO, PREZZO_UNITARIO,  
	ULA_TOTALE, U.DESCRIZIONE AS UNITA_MISURA
	FROM PRODUZIONE_STANDARD_DETTAGLIO P
	INNER JOIN INEA_PRODUZIONE_STANDARD I ON P.ID_ATTIVITA_CONNESSA = I.ID
	LEFT JOIN UNITA_DI_MISURA U ON U.ID_UNITA_MISURA= I.ID_UNITA_MISURA 
	WHERE COD_TIPO = 'C' AND ID_PS = @ID_PS
END
