CREATE PROCEDURE [dbo].[RptQuadroLSelect] 
@ID_Domanda int
AS
BEGIN
	SET NOCOUNT ON;
	DECLARE @IDFascicolo int
	SET @IDFascicolo = (select isNull (ID_FASCICOLO,( SELECT    MAX(F.ID_FASCICOLO) AS Expr1  
								FROM  IMPRESA INNER JOIN PROGETTO ON IMPRESA.ID_IMPRESA = PROGETTO.ID_IMPRESA 
								INNER JOIN FASCICOLO_AZIENDALE AS F ON IMPRESA.ID_IMPRESA = F.ID_IMPRESA
								WHERE     (PROGETTO.ID_PROGETTO = @ID_Domanda) ) ) 
								FROM PROGETTO WHERE ID_PROGETTO = @ID_Domanda)

	DECLARE @Count int
	SET @Count = (SELECT COUNT(ID_FASCICOLO) FROM vFABBRICATI WHERE ID_FASCICOLO = @IDFascicolo)

	IF (@Count > 0)
		SELECT COMUNE,
				PROVINCIA,
				FOGLIO_CATASTALE,
				PARTICELLA,
				SEZIONE,
				SUBALTERNO,
				TIPO_FABBRICATO,
				DESTINAZIONE_FABBRICATO,
				TIPO_CONDUZIONE,
				DATA_INIZIO_CONDUZIONE,
				DATA_FINE_CONDUZIONE,
				NUMERO_POSTI,
				dbo.MqAEttari(SUPERFICIE_COPERTA) AS SUPERFICIE_COPERTA,
				dbo.MqAEttari(SUPERFICIE_SCOPERTA) AS SUPERFICIE_SCOPERTA,
				dbo.MqAEttari((SELECT SUM(SUPERFICIE_COPERTA) FROM VFABBRICATI WHERE ID_FASCICOLO = @IDFascicolo)) AS TOT_SUPERFICIE_COPERTA,
				dbo.MqAEttari((SELECT SUM(SUPERFICIE_SCOPERTA) FROM VFABBRICATI WHERE ID_FASCICOLO = @IDFascicolo)) AS TOT_SUPERFICIE_SCOPERTA
		FROM	vFABBRICATI
		WHERE ID_FASCICOLO = @IDFascicolo
	ELSE SELECT NULL AS COMUNE,
				NULL AS PROVINCIA,
				NULL AS FOGLIO_CATASTALE,
				NULL AS PARTICELLA,
				NULL AS SEZIONE,
				NULL AS SUBALTERNO,
				NULL AS TIPO_FABBRICATO,
				NULL AS DESTINAZIONE_FABBRICATO,
				NULL AS TIPO_CONDUZIONE,
				NULL AS DATA_INIZIO_CONDUZIONE,
				NULL AS DATA_FINE_CONDUZIONE,
				NULL AS NUMERO_POSTI,
				NULL AS SUPERFICIE_COPERTA,
				NULL AS SUPERFICIE_SCOPERTA,
   			    NULL AS TOT_SUPERFICIE_COPERTA,
				NULL AS TOT_SUPERFICIE_SCOPERTA

END
