-- =============================================
-- Author:		Informatica
-- Create date: 07/03/2008
-- Description:	Per report QuadroP
-- =============================================
CREATE PROCEDURE [dbo].[RptQuadroPSelect] 
@ID_Domanda int 
AS
BEGIN
	SET NOCOUNT ON;
    
	DECLARE @IDFascicolo int
	SET @IDFascicolo = (select isNull (ID_FASCICOLO,( SELECT    MAX(F.ID_FASCICOLO) AS Expr1  
								FROM  IMPRESA INNER JOIN PROGETTO ON IMPRESA.ID_IMPRESA = PROGETTO.ID_IMPRESA 
								INNER JOIN FASCICOLO_AZIENDALE AS F ON IMPRESA.ID_IMPRESA = F.ID_IMPRESA
								WHERE     (PROGETTO.ID_PROGETTO = @ID_Domanda) ) ) 
								FROM PROGETTO WHERE ID_PROGETTO = @ID_Domanda )

	DECLARE @Count int	
	SET @Count = (SELECT COUNT(ID_FASCICOLO) FROM vPIANO_COLTURALE WHERE ID_FASCICOLO = @IDFascicolo)

	IF (@Count > 0)
	
		SELECT COMUNE , 
				PROVINCIA,
				FOGLIO_CATASTALE,
				PARTICELLA,
				SEZIONE,
				SUBALTERNO,
				dbo.MqAEttari(SUPERFICIE_CATASTALE) AS SUPERFICIE_CATASTALE,
				COD_TIPO_CONDUZIONE,
				TIPO_CONDUZIONE,
				dbo.MqAEttari(SUPERFICIE_CONDOTTA) AS SUPERFICIE_CONDOTTA,
				VARIETA,
				PRODOTTO,
				SVANTAGGIO,
				dbo.MqAEttari(SUPERFICIE_UTILIZZATA) AS SUPERFICIE_UTILIZZATA,
				dbo.MqAEttari((Select sum(SUPERFICIE_UTILIZZATA)
				FROM vPIANO_COLTURALE
					WHERE ID_FASCICOLO = @IDFascicolo)) as TOTALE,
				DATA_FINE_CONDUZIONE 

		FROM	vPIANO_COLTURALE
		WHERE ID_FASCICOLO = @IDFascicolo
group by COMUNE,PROVINCIA,
				FOGLIO_CATASTALE,
				PARTICELLA,
				SEZIONE,
				SUBALTERNO,
				SUPERFICIE_CATASTALE,
				COD_TIPO_CONDUZIONE,
				TIPO_CONDUZIONE,
				 SUPERFICIE_CONDOTTA,
				VARIETA,
				PRODOTTO,
				SVANTAGGIO,
				SUPERFICIE_UTILIZZATA, 
				DATA_FINE_CONDUZIONE
	ELSE SELECT NULL AS COMUNE,
				NULL AS PROVINCIA,
				NULL AS FOGLIO_CATASTALE,
				NULL AS PARTICELLA,
				NULL AS SEZIONE,
				NULL AS SUBALTERNO,
				NULL AS SUPERFICIE_CATASTALE,
				NULL AS COD_TIPO_CONDUZIONE,
				NULL AS TIPO_CONDUZIONE,
				NULL AS SUPERFICIE_CONDOTTA,
				NULL AS VARIETA,
				NULL AS PRODOTTO,
				NULL AS SVANTAGGIO,
				NULL AS SUPERFICIE_UTILIZZATA,
				NULL AS TOTALE, 
				NULL AS DATA_FINE_CONDUZIONE
END
