

CREATE PROCEDURE [dbo].[RptQuadroASelect_DatiAzienda]
@ID_Domanda int	
AS
BEGIN	

DECLARE @ID_IMPRESA int
SET @ID_IMPRESA = (SELECT ID_IMPRESA FROM dbo.PROGETTO WHERE ID_PROGETTO = @ID_Domanda)

IF (@ID_IMPRESA IS NOT NULL)
	BEGIN
	
		SELECT I.CUAA, 
			   I.CODICE_FISCALE AS PIVA_CF,
			   I.REGISTRO_IMPRESE_NUMERO,
			   I.CODICE_INPS,
			   I.RAGIONE_SOCIALE,
			   I.COD_FORMA_GIURIDICA,
			   I.FORMA_GIURIDICA AS DESCRIZIONE, 
			   I.DIMENSIONE_IMPRESA AS DIMENSIONE_IMPRESA,
			   I.REA_NUMERO, 
			   I.REA_ANNO
		FROM VIMPRESA I 
		WHERE I.ID_IMPRESA = @ID_IMPRESA
		
	END
ELSE 
	BEGIN
		
		 SELECT NULL AS CUAA,
				NULL AS PIVA_CF,
				NULL AS REGISTRO_IMPRESE_NUMERO,
				NULL AS CODICE_INPS,
				NULL AS RAGIONE_SOCIALE,
				NULL AS COD_FORMA_GIURIDICA, 
				NULL AS DIMENSIONE_IMPRESA, 
				NULL AS REA_NUMERO, 
				NULL AS REA_ANNO
	END
END

