CREATE PROCEDURE [dbo].[RptResponsabileBandoRegionale]
	@IdProgetto INT
AS
BEGIN
	SELECT TOP 1 vUTENTI.NOMINATIVO
	FROM  PROGETTO 
	INNER JOIN BANDO_RESPONSABILI BR ON PROGETTO.ID_BANDO = BR.ID_BANDO
	INNER JOIN vUTENTI ON BR.ID_UTENTE = vUTENTI.ID_UTENTE
	WHERE ID_PROGETTO = @IdProgetto  AND BR.PROVINCIA IS NULL 
	ORDER BY BR.ID DESC 
END
