CREATE PROCEDURE [dbo].[RptRAERiepilogo]
@IdBando int	
AS

SELECT PB.ID_BANDO, ISNULL(PR.ID_PROG_INTEGRATO, PR.ID_PROGETTO) AS ID_PROGETTO,  STATO, COD_AGEA, VIMPRESA.CUAA, PS.DATA AS DATA_ULTIMA_MODIFICA,
vIMPRESA.CODICE_FISCALE, vIMPRESA.RAGIONE_SOCIALE, 
		(SELECT     TOP (1) MISURA.CODICE
		FROM          vPROGRAMMAZIONE_BANDO INNER JOIN
			   MISURA ON vPROGRAMMAZIONE_BANDO.ID_PSR = MISURA.ID_PSR AND 
			   vPROGRAMMAZIONE_BANDO.COD_OBIETTIVO = MISURA.COD_OBIETTIVO AND 
			   vPROGRAMMAZIONE_BANDO.COD_ASSE = MISURA.COD_ASSE AND 
			   vPROGRAMMAZIONE_BANDO.COD_MISURA = MISURA.COD_MISURA
		WHERE      (vPROGRAMMAZIONE_BANDO.ID_BANDO = PB.DISP) AND (vPROGRAMMAZIONE_BANDO.MISURA_PREVALENTE = 1)) 
                      AS CODICE_MISURA,
(SELECT dbo.calcoloCostoTotaleProgettoCorrelato (PR.ID_PROGETTO, 0, NULL)) AS COSTO_RICHIESTO, 
(SELECT dbo.calcoloContributoTotaleProgettoCorrelato ( PR.ID_PROGETTO, 0, NULL)) AS CONTRIBUTO_RICHIESTO, 
(SELECT dbo.calcoloPremioContoCapitale(PR.ID_PROGETTO, 0, NULL)) AS PREMIO_RICHIESTO,
(SELECT dbo.calcoloCostoTotaleProgettoCorrelato (PR.ID_PROGETTO, 1, NULL)) AS COSTO_ammesso, 
(SELECT dbo.calcoloContributoTotaleProgettoCorrelato ( PR.ID_PROGETTO, 1, NULL)) AS CONTRIBUTO_ammesso, 
(SELECT dbo.calcoloPremioContoCapitale(PR.ID_PROGETTO, 1, NULL)) AS PREMIO_ammesso,

vIMPRESA.DIMENSIONE_IMPRESA, vIMPRESA.FORMA_GIURIDICA,  vINDIRIZZARIO.TIPO_SEDE, vINDIRIZZARIO.VIA, 
vINDIRIZZARIO.COMUNE, vINDIRIZZARIO.CAP, vINDIRIZZARIO.SIGLA, vPERSONE_X_IMPRESE.NOME, vPERSONE_X_IMPRESE.COGNOME, 
vPERSONE_X_IMPRESE.CODICE_FISCALE AS CODICE_FISCALE_RL, vPERSONE_X_IMPRESE.SESSO, vPERSONE_X_IMPRESE.DATA_NASCITA, 
vPERSONE_X_IMPRESE.COMUNE AS COMUNE_NASCITA, vPERSONE_X_IMPRESE.SIGLA AS PROVINCIA_NASCITA, 
vPERSONE_X_IMPRESE.CAP AS CAP_NASCITA, 
(CASE WHEN PB.ID_BANDO = PB.DISP THEN dbo.calcoloPremioContoCapitale(PR.ID_PROG_INTEGRATO, 0, NULL) ELSE 0 END) AS PREMIO_RICHIESTO,
D.DESCRIZIONE, D.DATA_MODIFICA, 
IMPORTO_AMMISSIBILE, IMPORTO_AMMESSO, BARCODE, E.ID_ELENCO_REGIONALE, E.DATA_ESPORTAZIONE,
BA.DESCRIZIONE_BANDO, CONVERT(VARCHAR(15), DATA_SCADENZA, 103) AS DATA_SCADENZA,
(Select sum(superficie_catastale)
from (select Distinct(territorio.id_catasto) 
from TERRITORIO where  TERRITORIO.id_fascicolo=PR.ID_FASCICOLO) as terr 
inner join vcatasto on vcatasto.id_catasto = terr.id_catasto 
where vcatasto.id_catasto is not null and vcatasto.svantaggio is  null) as vantaggio,  
(Select sum(superficie_catastale)
from (select Distinct(territorio.id_catasto) 
from TERRITORIO where  TERRITORIO.id_fascicolo=PR.ID_FASCICOLO) as terr 
inner join vcatasto on vcatasto.id_catasto = terr.id_catasto 
where vcatasto.id_catasto is not null and vcatasto.svantaggio = 'MONTAGNA par. 3.3' ) as MONTAGNA,
(Select sum(superficie_catastale)
from (select Distinct(territorio.id_catasto) 
from TERRITORIO where  TERRITORIO.id_fascicolo=PR.ID_FASCICOLO) as terr 
inner join vcatasto on vcatasto.id_catasto = terr.id_catasto 
where vcatasto.id_catasto is not null and vcatasto.svantaggio = 'ORDINARIO par. 3.4' ) as ORDINARIO,
(SELECT dbo.OTE_PLV (ISNULL(PR.ID_PROG_INTEGRATO, PR.ID_PROGETTO), NULL)) AS OTE
FROM  vprogetto PR 
INNER JOIN PROGETTO_STORICO PS ON PR.ID_PROGETTO = PS.ID_PROGETTO AND PS.COD_STATO = 'L'
INNER JOIN (SELECT ID_BANDO, ISNULL(ID_DISPOSIZIONI_ATTUATIVE, ID_BANDO) AS DISP
	FROM PROGRAMMAZIONE_BANDO GROUP BY ID_BANDO, ID_DISPOSIZIONI_ATTUATIVE) AS PB ON PB.DISP = PR.ID_BANDO
LEFT JOIN VDOMANDA_DI_PAGAMENTO D ON ISNULL(PR.ID_PROG_INTEGRATO, PR.ID_PROGETTO)  = D.ID_PROGETTO AND APPROVATA = 1 
LEFT JOIN DOMANDA_DI_PAGAMENTO_ESPORTAZIONE DE ON D.ID_DOMANDA_PAGAMENTO = DE.ID_DOMANDA_PAGAMENTO
AND PR.ID_PROGETTO  = DE.ID_PROGETTO
INNER JOIN vIMPRESA ON PR.ID_IMPRESA = vIMPRESA.ID_IMPRESA 
INNER JOIN vINDIRIZZARIO ON vIMPRESA.ID_SEDELEGALE_ULTIMO = vINDIRIZZARIO.ID_INDIRIZZARIO 
INNER JOIN vPERSONE_X_IMPRESE ON vIMPRESA.ID_RAPPRLEGALE_ULTIMO = vPERSONE_X_IMPRESE.ID_PERSONE_X_IMPRESE 
LEFT JOIN ELENCO_DI_PAGAMENTO E ON E.ID_ELENCO_PAGAMENTO = DE.ID_ELENCO_PAGAMENTO 
INNER JOIN (SELECT B.ID_BANDO, B.DESCRIZIONE AS DESCRIZIONE_BANDO, 
CONVERT(VARCHAR(15), MAX(DATA_SCADENZA), 103) AS DATA_SCADENZA
FROM BANDO B INNER JOIN MON_STATO_BANDO M ON B.ID_BANDO = M.ID_BANDO
GROUP BY B.ID_BANDO, B.DESCRIZIONE) AS BA ON PR.ID_BANDO = BA.ID_BANDO
WHERE PB.ID_BANDO = @IdBando AND PR.ORDINE_FASE  >=2 

GROUP BY PR.ID_PROGETTO, PR.ID_PROG_INTEGRATO, STATO, COD_AGEA, VIMPRESA.CUAA, PS.DATA,
PB.ID_BANDO, PB.DISP, PR.ID_FASCICOLO, D.DATA_MODIFICA, D.DESCRIZIONE,
IMPORTO_AMMISSIBILE, IMPORTO_AMMESSO, BARCODE,
vIMPRESA.CODICE_FISCALE, vIMPRESA.RAGIONE_SOCIALE, 
vIMPRESA.DIMENSIONE_IMPRESA, vIMPRESA.FORMA_GIURIDICA, vINDIRIZZARIO.TIPO_SEDE, vINDIRIZZARIO.VIA, 
vINDIRIZZARIO.COMUNE, vINDIRIZZARIO.CAP, vINDIRIZZARIO.SIGLA, vPERSONE_X_IMPRESE.NOME, vPERSONE_X_IMPRESE.COGNOME, 
vPERSONE_X_IMPRESE.CODICE_FISCALE, vPERSONE_X_IMPRESE.SESSO, vPERSONE_X_IMPRESE.DATA_NASCITA, 
vPERSONE_X_IMPRESE.COMUNE, vPERSONE_X_IMPRESE.SIGLA, 
E.ID_ELENCO_REGIONALE, E.DATA_ESPORTAZIONE,
vPERSONE_X_IMPRESE.CAP, BA.ID_BANDO, BA.DESCRIZIONE_BANDO, DATA_SCADENZA

ORDER BY PR.ID_PROG_INTEGRATO, PR.ID_PROGETTO
