--UTILIZZATA SULLA NOTIFICA BIO (SEZIONE DATI GENERALI)
--E SULL'UMA
CREATE PROCEDURE [dbo].[RptSezioneDatiGenerali]
(
@IdImpresa int	
)
AS
BEGIN	
			SELECT I.CUAA, 
						I.CODICE_FISCALE AS PIVA_CF, 
						ISt.RAGIONE_SOCIALE,  
						FG.DESCRIZIONE, 
						DIMENSIONE_IMPRESA.DESCRIZIONE AS DIMENSIONE_IMPRESA,
						REA_NUMERO, REA_ANNO, CODICE_INPS, REGISTRO_IMPRESE_NUMERO, CA.DESCRIZIONE AS CLASSIFICAZIONE_UMA
			FROM IMPRESA AS I 
				INNER JOIN IMPRESA_STORICO AS ISt ON I.ID_STORICO_ULTIMO = ISt.ID_STORICO_IMPRESA 
				LEFT JOIN FORMA_GIURIDICA AS FG ON ISt.COD_FORMA_GIURIDICA = FG.COD_ISTAT 
				LEFT JOIN DIMENSIONE_IMPRESA ON ISt.ID_DIMENSIONE = DIMENSIONE_IMPRESA.ID_DIMENSIONE
				LEFT JOIN SIAR_UMA.DBO.Z_CLASSIFICAZIONE_ASSEGNAZIONE CA ON IST.COD_CLASSIFICAZIONE_UMA = CA.CODICE
			WHERE I.ID_IMPRESA = @IdImpresa 
			
END
