CREATE PROCEDURE [dbo].[RptSezioneContoCorrente]
(
@IdImpresa int	
)
AS
BEGIN
	SELECT C.COD_PAESE, 
		C.CIN_EURO, 
		C.CIN, C.ABI, 
		C.CAB, 
		C.NUMERO, 
		C.NOTE, 
		C.DATA_INIZIO_VALIDITA, 
		C.DATA_FINE_VALIDITA, 
		C.ISTITUTO, 
		C.AGENZIA, 
		C.COMUNE, 
		C.CAP, 
		C.SIGLA
	FROM IMPRESA AS I 
			INNER JOIN vCONTO_CORRENTE AS C ON I.ID_CONTO_CORRENTE_ULTIMO = C.ID_CONTO_CORRENTE 
	WHERE I.ID_IMPRESA = @IdImpresa
	ORDER BY C.ID_CONTO_CORRENTE DESC
END
