CREATE PROCEDURE [dbo].[RptVariantePianoInvestimentiTotaliPrecedenti]
(
@IdVariante int,
@COD_Tipo_Investimento int	
)
AS
BEGIN	

SET NOCOUNT ON;

--DECLARE @IdVariante int 
--DECLARE @COD_Tipo_Investimento int
--SET @IdVariante = 34
--SET @COD_Tipo_Investimento = 1


DECLARE @Count int
DECLARE @ID_VARIANTE int 
DECLARE @CONTR_TOTALE DECIMAL(18, 2)
DECLARE @CONTR_FUNZIONE DECIMAL(18, 2)
DECLARE @TOTALE DECIMAL(18, 2)
DECLARE @FASE BIT 
DECLARE @ID_DOMANDA INT 


SET @Count = (SELECT COUNT(ID_INVESTIMENTO) 
				FROM vPIANO_INVESTIMENTI
				WHERE ID_INVESTIMENTO IN (SELECT ID_INVESTIMENTO_ORIGINALE 
										FROM  vPIANO_INVESTIMENTI 
										WHERE (ID_VARIANTE = @IdVariante)) AND COD_TIPO_INVESTIMENTO = @COD_Tipo_Investimento)
IF (@Count > 0)
BEGIN
	SET @ID_DOMANDA =(SELECT ID_PROGETTO FROM VARIANTI WHERE ID_VARIANTE =@IdVariante)
	SET @FASE = (SELECT CASE WHEN ORDINE_FASE>2 THEN 1 ELSE 0 END  FROM vPROGETTO  WHERE ID_PROGETTO = @ID_DOMANDA)

	SET @CONTR_TOTALE = 0
	SET @CONTR_FUNZIONE = 0
	SET @CONTR_TOTALE = (SELECT SUM(ISNULL(CONTRIBUTO_RICHIESTO, 0)) 
								FROM PIANO_INVESTIMENTI
								WHERE ID_INVESTIMENTO IN (SELECT ID_INVESTIMENTO_ORIGINALE 
										FROM  vPIANO_INVESTIMENTI 
										WHERE (ID_VARIANTE = @IdVariante)) AND COD_TIPO_INVESTIMENTO = @COD_Tipo_Investimento AND ISNULL(COD_VARIAZIONE,'X')!='A')

	SET @ID_VARIANTE =(SELECT MAX(ID_VARIANTE) FROM VARIANTI WHERE ID_PROGETTO=@ID_DOMANDA AND APPROVATA=1 AND ID_VARIANTE<@IdVariante)
	SET @CONTR_FUNZIONE = (SELECT dbo.calcoloContributoInvestimentiProgetto(@ID_DOMANDA, @FASE, @ID_VARIANTE))

	SELECT  COSTO_INVESTIMENTO,
				   SPESE_GENERALI,
				   CONTRIBUTO_RICHIESTO AS CONTRIBUTO_AMMISSIBILE,
				   QUOTA_CONTRIBUTO_RICHIESTO AS QUOTA_CONTRIBUTO_AMMISSIBILE,
				   ID_PRIORITA_SETTORIALE,
				   RATA_REINTEGRAZIONE = CASE MOBILE
											WHEN 1 THEN ((COSTO_INVESTIMENTO + SPESE_GENERALI)/10)
											WHEN 0 THEN ((COSTO_INVESTIMENTO + SPESE_GENERALI)/30)
											ELSE 0
											END, 
					@CONTR_TOTALE AS TOTALE_CONTRIBUTO, 
					@CONTR_FUNZIONE AS TOTALE_CONTRIBUTO_TRONCATO, COD_VARIAZIONE
	FROM VPIANO_INVESTIMENTI 
	WHERE ID_INVESTIMENTO IN (SELECT ID_INVESTIMENTO_ORIGINALE 
										FROM  vPIANO_INVESTIMENTI 
										WHERE (ID_VARIANTE = @IdVariante)) 
		AND COD_TIPO_INVESTIMENTO = @COD_Tipo_Investimento AND ISNULL(COD_VARIAZIONE,'X')!='A'
END

ELSE SELECT 
		    NULL AS COSTO_INVESTIMENTO,
		    NULL AS SPESE_GENERALI,
		    NULL AS CONTRIBUTO_AMMISSIBILE, 
			NULL AS QUOTA_CONTRIBUTO_AMMISSIBILE,
		    NULL AS RATA_REINTEGRAZIONE,
			NULL AS TOTALE_CONTRIBUTO,
			NULL AS TOTALE_CONTRIBUTO_TRONCATO
END
