CREATE PROCEDURE [dbo].[RptVarianteDettaglioMutuo]
(
@IdVariante int, 
@Codice bit
)
AS
BEGIN	

SET NOCOUNT ON;

--DECLARE @IdVariante int 
--DECLARE @COD_Tipo_Investimento int
--SET @IdVariante = 23
--SET @COD_Tipo_Investimento = 1

DECLARE @ID_DOMANDA INT
DECLARE @ID_VARIANTE INT

IF(@Codice = 1)
		SELECT     vPIANO_INVESTIMENTI.ID_INVESTIMENTO, vPIANO_INVESTIMENTI.DESCRIZIONE, vPIANO_INVESTIMENTI.QUANTITA, 
							  vPIANO_INVESTIMENTI.COSTO_INVESTIMENTO, vPIANO_INVESTIMENTI.SPESE_GENERALI, vPIANO_INVESTIMENTI.CONTRIBUTO_RICHIESTO, 
							  vPIANO_INVESTIMENTI.QUOTA_CONTRIBUTO_RICHIESTO, vPIANO_INVESTIMENTI.CODIFICA_INVESTIMENTO, 
							  vPIANO_INVESTIMENTI.AIUTO_MINIMO, zOB_MISURA.CODICE COD_OB_MISURA, 
							  zOB_MISURA.DESCRIZIONE AS DESCRIZIONE_OBIETTIVI_MISURA, vzPROGRAMMAZIONE.COD_TIPO AS CODICE_INTERVENTO, 
							  vzPROGRAMMAZIONE.DESCRIZIONE AS DESCRIZIONE_INTERVENTO, vPIANO_INVESTIMENTI.VALUTAZIONE_INVESTIMENTO, 
							  vPIANO_INVESTIMENTI.COD_VARIAZIONE, vPIANO_INVESTIMENTI.ID_INVESTIMENTO_ORIGINALE, 
							  vPIANO_INVESTIMENTI.TASSO_ABBUONO
		FROM         vPIANO_INVESTIMENTI   INNER JOIN
                      zOB_MISURA ON vPIANO_INVESTIMENTI.ID_OBIETTIVO_MISURA = zOB_MISURA.ID  INNER JOIN
							  vzPROGRAMMAZIONE ON vPIANO_INVESTIMENTI.ID_PROGRAMMAZIONE = vzPROGRAMMAZIONE.ID
		WHERE     (vPIANO_INVESTIMENTI.ID_INVESTIMENTO IN
								  (SELECT     ID_INVESTIMENTO
									FROM          PIANO_INVESTIMENTI
									WHERE      (ID_VARIANTE = @IdVariante) AND (COD_TIPO_INVESTIMENTO = 2)))
		ORDER BY vPIANO_INVESTIMENTI.ID_INVESTIMENTO
ELSE 
BEGIN 
	SET @ID_DOMANDA =(SELECT ID_PROGETTO FROM VARIANTI WHERE ID_VARIANTE = @IdVariante)

	SET @ID_VARIANTE =(SELECT MAX(ID_VARIANTE) FROM VARIANTI WHERE ID_PROGETTO=@ID_DOMANDA AND APPROVATA=1 AND ID_VARIANTE< @IdVariante)

	IF(@ID_VARIANTE IS NULL) 
		SELECT     vPIANO_INVESTIMENTI.ID_INVESTIMENTO, vPIANO_INVESTIMENTI.DESCRIZIONE, vPIANO_INVESTIMENTI.QUANTITA, 
							  vPIANO_INVESTIMENTI.COSTO_INVESTIMENTO, vPIANO_INVESTIMENTI.SPESE_GENERALI, vPIANO_INVESTIMENTI.CONTRIBUTO_RICHIESTO, 
							  vPIANO_INVESTIMENTI.QUOTA_CONTRIBUTO_RICHIESTO, vPIANO_INVESTIMENTI.CODIFICA_INVESTIMENTO, 
							  vPIANO_INVESTIMENTI.AIUTO_MINIMO, zOB_MISURA.CODICE COD_OB_MISURA, 
							  zOB_MISURA.DESCRIZIONE AS DESCRIZIONE_OBIETTIVI_MISURA, vzPROGRAMMAZIONE.COD_TIPO AS CODICE_INTERVENTO, 
							  vzPROGRAMMAZIONE.DESCRIZIONE AS DESCRIZIONE_INTERVENTO, vPIANO_INVESTIMENTI.VALUTAZIONE_INVESTIMENTO, 
							  vPIANO_INVESTIMENTI.COD_VARIAZIONE, vPIANO_INVESTIMENTI.ID_INVESTIMENTO_ORIGINALE, 
							  vPIANO_INVESTIMENTI.TASSO_ABBUONO
		FROM         vPIANO_INVESTIMENTI INNER JOIN
							  zOB_MISURA ON vPIANO_INVESTIMENTI.ID_OBIETTIVO_MISURA = zOB_MISURA.ID INNER JOIN
							  vzPROGRAMMAZIONE ON vPIANO_INVESTIMENTI.ID_PROGRAMMAZIONE = vzPROGRAMMAZIONE.ID
		WHERE     (vPIANO_INVESTIMENTI.ID_INVESTIMENTO_ORIGINALE IS NOT NULL) AND (vPIANO_INVESTIMENTI.COD_TIPO_INVESTIMENTO = 2) AND 
							  (vPIANO_INVESTIMENTI.ID_VARIANTE IS NULL) AND (vPIANO_INVESTIMENTI.ID_PROGETTO IN
								  (SELECT     ID_PROGETTO
									FROM          PROGETTO
									WHERE      (ID_PROG_INTEGRATO IS NULL) AND (ID_PROGETTO =
															   (SELECT     ID_PROGETTO
																 FROM          VARIANTI AS VARIANTI_1
																 WHERE      (ID_VARIANTE = @IdVariante))) OR
														   (ID_PROG_INTEGRATO =
															   (SELECT     ID_PROGETTO
																 FROM          VARIANTI
																 WHERE      (ID_VARIANTE = @IdVariante)))))
		ORDER BY vPIANO_INVESTIMENTI.ID_INVESTIMENTO

	ELSE 
		SELECT     vPIANO_INVESTIMENTI.ID_INVESTIMENTO, vPIANO_INVESTIMENTI.DESCRIZIONE, vPIANO_INVESTIMENTI.QUANTITA, 
							  vPIANO_INVESTIMENTI.COSTO_INVESTIMENTO, vPIANO_INVESTIMENTI.SPESE_GENERALI, vPIANO_INVESTIMENTI.CONTRIBUTO_RICHIESTO, 
							  vPIANO_INVESTIMENTI.QUOTA_CONTRIBUTO_RICHIESTO, vPIANO_INVESTIMENTI.CODIFICA_INVESTIMENTO, 
							  vPIANO_INVESTIMENTI.AIUTO_MINIMO, zOB_MISURA.CODICE COD_OB_MISURA, 
							  zOB_MISURA.DESCRIZIONE AS DESCRIZIONE_OBIETTIVI_MISURA, vzPROGRAMMAZIONE.COD_TIPO AS CODICE_INTERVENTO, 
							  vzPROGRAMMAZIONE.DESCRIZIONE AS DESCRIZIONE_INTERVENTO, vPIANO_INVESTIMENTI.VALUTAZIONE_INVESTIMENTO, 
							  vPIANO_INVESTIMENTI.COD_VARIAZIONE, vPIANO_INVESTIMENTI.ID_INVESTIMENTO_ORIGINALE, 
							  vPIANO_INVESTIMENTI.TASSO_ABBUONO
		FROM         vPIANO_INVESTIMENTI INNER JOIN
							  zOB_MISURA ON vPIANO_INVESTIMENTI.ID_OBIETTIVO_MISURA = zOB_MISURA.ID INNER JOIN
							  vzPROGRAMMAZIONE ON vPIANO_INVESTIMENTI.ID_PROGRAMMAZIONE = vzPROGRAMMAZIONE.ID
		WHERE     (vPIANO_INVESTIMENTI.ID_INVESTIMENTO IN
								  (SELECT     ID_INVESTIMENTO
									FROM          PIANO_INVESTIMENTI
									WHERE      (ID_VARIANTE = @ID_VARIANTE) AND (COD_TIPO_INVESTIMENTO = 2)))
		ORDER BY vPIANO_INVESTIMENTI.ID_INVESTIMENTO
		
END

END
