CREATE PROCEDURE [dbo].[RptVariantePremio]

	@IdVariante int

AS
BEGIN

DECLARE @ID_DOMANDA INT

SET @ID_DOMANDA =(SELECT ID_PROGETTO FROM VARIANTI WHERE ID_VARIANTE =@IdVariante)

IF((SELECT COUNT(*) FROM BANDO_TIPO_INVESTIMENTI WHERE COD_TIPO_INVESTIMENTO=3 AND ID_BANDO = (SELECT ID_BANDO FROM PROGETTO WHERE ID_PROGETTO = @ID_DOMANDA)) > 0)
BEGIN
	SELECT DBO.calcoloPremioContoCapitale(@ID_DOMANDA, 1, @IdVariante) AS PREMIO
END 
END
