CREATE PROCEDURE [dbo].[SpCalcoloSanzioneDDS4322013]
(
	@ID_SANZIONE INT,
	@DURATA DECIMAL(18,2) =NULL,
	@GRAVITA DECIMAL(18,2) =NULL,
	@ENTITA DECIMAL(18,2)=NULL,
	@MOTIVAZIONE NTEXT =NULL
)
AS
	--DECLARE @ID_SANZIONE INT=287,@GRAVITA DECIMAL(18,2) =50

	-- LA SANZIONE VIENE CALCOLATA PER MISURA (ID_PROGETTO)
	DECLARE @AMMONTARE_SANZIONE DECIMAL(18,5)
	SELECT @AMMONTARE_SANZIONE=ISNULL(@ENTITA,0)*SUM(ISNULL(PR.CONTRIBUTO_AMMESSO,0))/100
	FROM PAGAMENTI_RICHIESTI PR INNER JOIN SANZIONI S ON PR.ID_DOMANDA_PAGAMENTO=S.ID_DOMANDA_PAGAMENTO
	WHERE ID_SANZIONE=@ID_SANZIONE
	
	UPDATE SANZIONI SET DATA_APPLICAZIONE=GETDATE(),AMMONTARE=ROUND(@AMMONTARE_SANZIONE,2),VALORE_ENTITA=@ENTITA,
		MOTIVAZIONE=@MOTIVAZIONE WHERE ID_SANZIONE=@ID_SANZIONE
	SELECT * FROM VSANZIONI WHERE ID_SANZIONE=@ID_SANZIONE
