CREATE PROCEDURE [dbo].[SpCalcoloSanzioneRiduzione]
(
	@ID_DOMANDA_PAGAMENTO INT,
	@ID_PROGETTO INT, --ID_PROGETTO CORRELATO
	@OPERATORE VARCHAR(16)
)
AS
DECLARE @RETVAL INT
SET @RETVAL=0
DECLARE @COD_TIPO VARCHAR(10)
SET @COD_TIPO='ART-31'

-- CALCOLA L'IMPORTO DELLA SANZIONE DA DETRARRE DAL CONTRIBUTO AMMESSO SE SUPERA IL 3%
-- E MEMORIZZA I RISULTATI NELLA TABELLA SANZIONI
-- VALORE DI RITORNO 0=OK, 1='ALMENO UNO DEGLI IMPORTI RICHIESTI NON RISULTA AMMESSO.'
/*
DECLARE	@ID_DOMANDA_PAGAMENTO INT,@ID_PROGETTO INT,@OPERATORE VARCHAR(16)
SET @ID_DOMANDA_PAGAMENTO=181
SET @OPERATORE =''
SET @ID_PROGETTO =326--,324,326*/



IF(SELECT COUNT(*) FROM PAGAMENTI_RICHIESTI  WHERE ID_DOMANDA_PAGAMENTO=@ID_DOMANDA_PAGAMENTO AND IMPORTO_AMMESSO IS NULL)>0 
	SET @RETVAL=1 --ALMENO UNO DEGLI IMPORTI RICHIESTI NON RISULTA AMMESSO
-- MODIFICA DEL 13/02/2015, VIENE ESEGUITA SOLO PER LE DOMANDE DI PAGAMENTO PRESENTATE PRIMA DEL 01/01/2015
ELSE IF (SELECT COUNT(*) FROM DOMANDA_DI_PAGAMENTO WHERE ID_DOMANDA_PAGAMENTO=@ID_DOMANDA_PAGAMENTO AND DATA_MODIFICA<'2015-01-01')>0 BEGIN
	
	DECLARE @PAGAMENTO_RICHIESTO DECIMAL(18,2),@PAGAMENTO_AMMESSO DECIMAL(18,2),@SANZIONE DECIMAL(18,2)	
	-- TROVO L'EVENTUALE SANZIONE APPLICATA PRECEDENTEMENTE
	DECLARE @ID_SANZIONE INT
	SET @ID_SANZIONE=(SELECT ID_SANZIONE FROM SANZIONI WHERE ID_DOMANDA_PAGAMENTO=@ID_DOMANDA_PAGAMENTO 
	AND ID_PROGETTO=@ID_PROGETTO AND COD_TIPO=@COD_TIPO AND ID_INVESTIMENTO IS NULL)
	/*
	SELECT @PAGAMENTO_RICHIESTO=SUM(PB.IMPORTO_RICHIESTO),@PAGAMENTO_AMMESSO=SUM(PB.IMPORTO_AMMESSO)
	FROM PAGAMENTI_BENEFICIARIO PB INNER JOIN PAGAMENTI_RICHIESTI PR ON PB.ID_PAGAMENTO_RICHIESTO=PR.ID_PAGAMENTO_RICHIESTO
	INNER JOIN PIANO_INVESTIMENTI I ON PR.ID_INVESTIMENTO=I.ID_INVESTIMENTO
	WHERE PR.ID_DOMANDA_PAGAMENTO=@ID_DOMANDA_PAGAMENTO AND I.ID_PROGETTO=@ID_PROGETTO*/
	
	SELECT @PAGAMENTO_RICHIESTO=SUM(PR.CONTRIBUTO_RICHIESTO),@PAGAMENTO_AMMESSO=SUM(PR.CONTRIBUTO_AMMESSO)
	FROM PAGAMENTI_RICHIESTI PR INNER JOIN PIANO_INVESTIMENTI I ON PR.ID_INVESTIMENTO=I.ID_INVESTIMENTO
	WHERE PR.ID_DOMANDA_PAGAMENTO=@ID_DOMANDA_PAGAMENTO AND I.ID_PROGETTO=@ID_PROGETTO
	
	IF(@PAGAMENTO_AMMESSO>0 AND 100*(@PAGAMENTO_RICHIESTO-@PAGAMENTO_AMMESSO)/@PAGAMENTO_AMMESSO>3) BEGIN	
		--SELECT @SANZIONE=SUM((PB.IMPORTO_RICHIESTO-PB.IMPORTO_AMMESSO-ISNULL(IMPORTO_NONAMM_NONRESP,0))*I.QUOTA_CONTRIBUTO_RICHIESTO/100)
		SELECT @SANZIONE=@PAGAMENTO_RICHIESTO-@PAGAMENTO_AMMESSO-ISNULL(SUM(ISNULL(IMPORTO_NONAMM_NONRESP,0)* 
		(CASE WHEN I.COD_TIPO_INVESTIMENTO=2 THEN 100*I.CONTRIBUTO_RICHIESTO/I.COSTO_INVESTIMENTO ELSE I.QUOTA_CONTRIBUTO_RICHIESTO END)
		/100),0)
		FROM PAGAMENTI_BENEFICIARIO PB INNER JOIN PAGAMENTI_RICHIESTI PR ON PB.ID_PAGAMENTO_RICHIESTO=PR.ID_PAGAMENTO_RICHIESTO
		INNER JOIN PIANO_INVESTIMENTI I ON PR.ID_INVESTIMENTO=I.ID_INVESTIMENTO
		WHERE PR.ID_DOMANDA_PAGAMENTO=@ID_DOMANDA_PAGAMENTO AND PB.IMPORTO_RICHIESTO>PB.IMPORTO_AMMESSO AND I.ID_PROGETTO=@ID_PROGETTO			
		--NORMALIZZO
		IF(@SANZIONE<0)SET @SANZIONE=0
		--IF(@SANZIONE>(@PAGAMENTO_RICHIESTO-@PAGAMENTO_AMMESSO)) SET @SANZIONE=@PAGAMENTO_RICHIESTO-@PAGAMENTO_AMMESSO
		-- INSERISCO/AGGIORNO LA SANZIONE PER LA MISURA RELATIVA
		IF(@ID_SANZIONE IS NULL) INSERT INTO SANZIONI(COD_TIPO,ID_DOMANDA_PAGAMENTO,ID_PROGETTO,DATA_APPLICAZIONE,OPERATORE,AMMONTARE)			
			VALUES(@COD_TIPO,@ID_DOMANDA_PAGAMENTO,@ID_PROGETTO,GETDATE(),@OPERATORE,@SANZIONE)
		ELSE UPDATE SANZIONI SET DATA_APPLICAZIONE=GETDATE(),OPERATORE=@OPERATORE,AMMONTARE=@SANZIONE WHERE ID_SANZIONE=@ID_SANZIONE
	END
	ELSE IF(@ID_SANZIONE IS NOT NULL) DELETE FROM SANZIONI WHERE ID_SANZIONE=@ID_SANZIONE
END
RETURN @RETVAL
