CREATE PROCEDURE [dbo].[SpCalcoloPolizzaFidejussoriaVariante]
(
	@ID_PROGETTO INT, --ID DEL PROGETTO SPECIFICO PER LA MISURA
	@ID_VARIANTE INT
)
AS
/*
DECLARE @ID_PROGETTO INT
DECLARE	@ID_VARIANTE INT
SET @ID_PROGETTO= 118
SET	@ID_VARIANTE =23*/

-- RECUPERO I DATI DELLA POLIZZA FIDEJUSSORIA
DECLARE @MAX_AIUTO DECIMAL(15,2)
DECLARE @MIN_AIUTO DECIMAL(15,2)
DECLARE @MAX_QUOTA DECIMAL(15,2)
DECLARE @COD_AIUTO INT

SELECT @COD_AIUTO=COD_TIPO_INVESTIMENTO,@MIN_AIUTO=ISNULL(IMPORTO_MIN,0),@MAX_AIUTO=ISNULL(IMPORTO_MAX,1000000000),@MAX_QUOTA=ISNULL(QUOTA_MAX,100)
FROM PROGETTO AS P INNER JOIN BANDO_TIPO_INVESTIMENTI AS B ON P.ID_BANDO=B.ID_BANDO AND COD_TIPO_INVESTIMENTO=4 WHERE P.ID_PROGETTO=@ID_PROGETTO

----------------------------------------------
IF @COD_AIUTO IS NULL RAISERROR('TIPOLOGIA DI INVESTIMENTO "POLIZZA FIDEJUSSORIA" NON ASSOCIATA AL BANDO',13,1)
ELSE
BEGIN
	--COSTO TOTALE DEGLI INVESTIMENTI
	DECLARE @COSTO_TOTALE DECIMAL(18,2)
	DECLARE @SPESE_TOTALI DECIMAL(18,2)
	SELECT @COSTO_TOTALE=SUM(COSTO_INVESTIMENTO), @SPESE_TOTALI=CAST(SUM((CONTRIBUTO_RICHIESTO/QUOTA_CONTRIBUTO_RICHIESTO*100)- COSTO_INVESTIMENTO) AS DECIMAL(18,2))
	FROM PIANO_INVESTIMENTI WHERE ID_PROGETTO=@ID_PROGETTO AND COD_TIPO_INVESTIMENTO =1	AND ID_VARIANTE=@ID_VARIANTE AND ISNULL(COD_VARIAZIONE,'x')!='A'
	
	---------------------------------------------
	--COSTO TOTALE DEI BREVETTI
	DECLARE @COSTO_BREVETTI DECIMAL(18,2)
	SELECT @COSTO_BREVETTI=SUM(COSTO_INVESTIMENTO) FROM PIANO_INVESTIMENTI 
	WHERE ID_PROGETTO=@ID_PROGETTO AND COD_TIPO_INVESTIMENTO =5	AND ID_VARIANTE=@ID_VARIANTE AND ISNULL(COD_VARIAZIONE,'x')!='A'

	---------------------------------------------
	--PERCENTUALE MAX SPESE GENERALI 
	DECLARE @MAX_SPESE_GENERALI DECIMAL(18,2)	
	SELECT @MAX_SPESE_GENERALI=ISNULL(QUOTA_MAX,100) FROM PROGETTO AS P INNER JOIN BANDO_TIPO_INVESTIMENTI AS B 
	ON P.ID_BANDO=B.ID_BANDO AND COD_TIPO_INVESTIMENTO=6 WHERE P.ID_PROGETTO=@ID_PROGETTO

	---------------------------------------------	
	
	DECLARE @POLIZZA DECIMAL(18,2),@RESTO DECIMAL(18,2)
	SET @POLIZZA=@COSTO_TOTALE/100*@MAX_QUOTA --% SU COSTO TOTALE INVESTIMENTI	
	IF(@MAX_SPESE_GENERALI IS NOT NULL)BEGIN
		--RIMANENTE DEI SOLDI CHE POSSONO ESSERE ATTRIBUITI ALLE SPESE DI POLIZZA
		SET @RESTO=@COSTO_TOTALE/100*@MAX_SPESE_GENERALI-@SPESE_TOTALI-ISNULL(@COSTO_BREVETTI,0)
		IF(@RESTO>0)BEGIN
			SET @RESTO=@RESTO-@POLIZZA --SE LA POLIZZA NON RIENTRA TUTTA NEL RESTO 
			IF(@RESTO<0)SET @POLIZZA=@POLIZZA+@RESTO --	LA SOTTRAGGO A QUELLO CHE ECCEDE COSI TROVO LA PARTE CHE PUO' ESSERE FINANZIATA
		END			
		ELSE BEGIN
			SET @POLIZZA=0
		END
	END	
	IF(@POLIZZA>0)BEGIN
		--CALCOLO GLI INVESTIMENTI SU CUI SPALMARE IL COSTO DELLA POLIZZA
		DECLARE @CONTRIBUTO_POLIZZA DECIMAL(18,2)
		SET @CONTRIBUTO_POLIZZA =0
		DECLARE @COSTO_INVESTIMENTO DECIMAL(18,2)
		DECLARE @CONTRIBUTO DECIMAL(18,2)
		DECLARE TOTALE CURSOR FOR
		(SELECT COSTO_INVESTIMENTO,QUOTA_CONTRIBUTO_RICHIESTO FROM PIANO_INVESTIMENTI 
			WHERE ID_PROGETTO=@ID_PROGETTO AND COD_TIPO_INVESTIMENTO =1 AND ID_VARIANTE=@ID_VARIANTE AND ISNULL(COD_VARIAZIONE,'x')!='A')
		OPEN TOTALE
		FETCH NEXT FROM TOTALE 
		INTO @COSTO_INVESTIMENTO,@CONTRIBUTO
		WHILE @@FETCH_STATUS = 0
		BEGIN
			DECLARE @PARTE_POLIZZA DECIMAL(18,2)
			SET @PARTE_POLIZZA= @POLIZZA*@COSTO_INVESTIMENTO/@COSTO_TOTALE
			SET @CONTRIBUTO_POLIZZA=@CONTRIBUTO_POLIZZA+@CONTRIBUTO*@PARTE_POLIZZA/100	
			FETCH NEXT FROM TOTALE 
			INTO @COSTO_INVESTIMENTO,@CONTRIBUTO
		END
		CLOSE TOTALE
		DEALLOCATE TOTALE
		-------------------------------------------------------
	END
	--------SE LA POLIZZA E' GIA' PRESENTE SUL DB RITORNO L'ID PER AGGIORNARLO
	DECLARE @ID_INVESTIMENTO INT,@ID_INVESTIMENTO_ORIGINALE INT
	SELECT @ID_INVESTIMENTO=ID_INVESTIMENTO,@ID_INVESTIMENTO_ORIGINALE=ID_INVESTIMENTO_ORIGINALE
	FROM PIANO_INVESTIMENTI WHERE ID_PROGETTO=@ID_PROGETTO AND COD_TIPO_INVESTIMENTO=4 AND ID_VARIANTE=@ID_VARIANTE

	-------SE ESISTE LA POLIZZA ORIGINALE RITORNO IL COSTO
	DECLARE @COSTO_POLIZZA_ORIGINALE DECIMAL(18,2)
	if(@ID_INVESTIMENTO_ORIGINALE IS NOT NULL)
		SELECT @COSTO_POLIZZA_ORIGINALE=COSTO_INVESTIMENTO FROM PIANO_INVESTIMENTI WHERE ID_INVESTIMENTO=@ID_INVESTIMENTO_ORIGINALE
	------------------------------------------	
	SELECT @POLIZZA AS AMMONTARE_POLIZZA,@CONTRIBUTO_POLIZZA AS CONTRIBUTO_POLIZZA,
	CAST(@CONTRIBUTO_POLIZZA/@POLIZZA*100 AS DECIMAL(18,2)) AS QUOTA_CONTRIBUTO_POLIZZA,@ID_INVESTIMENTO AS ID_INVESTIMENTO,
	@ID_INVESTIMENTO_ORIGINALE AS ID_INVESTIMENTO_ORIGINALE,@COSTO_POLIZZA_ORIGINALE AS COSTO_POLIZZA_ORIGINALE,
	DBO.calcoloContributoRimanenteFinanziabileProgetto(@ID_PROGETTO,@ID_VARIANTE,@ID_INVESTIMENTO) AS CONTRIBUTO_DISPONIBILE_MISURA
END
