CREATE PROCEDURE [dbo].[SpCalcoloSanzioneRiduzioneArt63]
(
	@ID_DOMANDA_PAGAMENTO INT,
	@ID_PROGETTO INT, --ID_PROGETTO CORRELATO
	@OPERATORE VARCHAR(16)
)
AS
	DECLARE @COD_TIPO VARCHAR(10)
	SET @COD_TIPO='ART-63'

	-- CALCOLA L'IMPORTO DELLA SANZIONE DA DETRARRE DAL CONTRIBUTO AMMESSO SE SUPERA IL 10%
	-- E MEMORIZZA I RISULTATI NELLA TABELLA SANZIONI, VALE LE DOMANDE DI PAGAMENTO PRESENTATE DOPO IL 01/01/2015 COMPRESI GLI ANTICIPI
	-- RITORNA 0=OK, 1='ALMENO UNO DEGLI IMPORTI RICHIESTI NON RISULTA AMMESSO.'
	/*
	DECLARE	@ID_DOMANDA_PAGAMENTO INT,@ID_PROGETTO INT,@OPERATORE VARCHAR(16)
	SET @ID_DOMANDA_PAGAMENTO=181
	SET @OPERATORE =''
	SET @ID_PROGETTO =326--,324,326*/

	DECLARE @COD_TIPO_DOMANDA CHAR(3)
	SELECT @COD_TIPO_DOMANDA=COD_TIPO FROM DOMANDA_DI_PAGAMENTO WHERE ID_DOMANDA_PAGAMENTO=@ID_DOMANDA_PAGAMENTO 
		AND SEGNATURA IS NOT NULL AND DATA_MODIFICA>'2015-01-01'
		
	IF @COD_TIPO_DOMANDA IS NOT NULL BEGIN -- SE NULLO LA DOMANDA E' ANTECEDENTE IL 01/01/2015
	
		DECLARE @PAGAMENTO_RICHIESTO DECIMAL(18,2),@PAGAMENTO_AMMESSO DECIMAL(18,2),@SANZIONE DECIMAL(18,2)
		IF @COD_TIPO_DOMANDA='ANT' BEGIN
			DECLARE @ID_BANDO INT
			SELECT @ID_BANDO=ID_BANDO FROM PROGETTO WHERE ID_PROGETTO=@ID_PROGETTO
			SELECT TOP 1 @PAGAMENTO_RICHIESTO=CONTRIBUTO_RICHIESTO,@PAGAMENTO_AMMESSO=CONTRIBUTO_AMMESSO FROM ANTICIPI_RICHIESTI
			WHERE ID_DOMANDA_PAGAMENTO=@ID_DOMANDA_PAGAMENTO AND ID_BANDO=@ID_BANDO
			IF @PAGAMENTO_AMMESSO IS NULL RETURN 1 --ALMENO UNO DEGLI IMPORTI RICHIESTI NON RISULTA AMMESSO
		END
		ELSE BEGIN
			IF(SELECT COUNT(*) FROM PAGAMENTI_RICHIESTI  WHERE ID_DOMANDA_PAGAMENTO=@ID_DOMANDA_PAGAMENTO AND IMPORTO_AMMESSO IS NULL)>0 
				RETURN 1 --ALMENO UNO DEGLI IMPORTI RICHIESTI NON RISULTA AMMESSO
			ELSE BEGIN
				/*COMMENTATA IL 07-10-2015, CAMBIO SISTEMA DI CALCOLO
				SELECT @PAGAMENTO_RICHIESTO=SUM(PR.CONTRIBUTO_RICHIESTO),@PAGAMENTO_AMMESSO=SUM(PR.CONTRIBUTO_AMMESSO)
				FROM PAGAMENTI_RICHIESTI PR INNER JOIN PIANO_INVESTIMENTI I ON PR.ID_INVESTIMENTO=I.ID_INVESTIMENTO
				WHERE PR.ID_DOMANDA_PAGAMENTO=@ID_DOMANDA_PAGAMENTO AND I.ID_PROGETTO=@ID_PROGETTO*/
				SELECT @PAGAMENTO_RICHIESTO=SUM(CR2),@PAGAMENTO_AMMESSO=SUM(CONTRIBUTO_AMMESSO)
				FROM (
					SELECT PR.ID_PAGAMENTO_RICHIESTO,PR.CONTRIBUTO_RICHIESTO,PR.CONTRIBUTO_AMMESSO,
						DBO.SIAR_MAX(PR.CONTRIBUTO_RICHIESTO-SUM(ISNULL(IMPORTO_NONAMM_NONRESP,0)* 
						(CASE WHEN I.COD_TIPO_INVESTIMENTO=2 THEN 100*I.CONTRIBUTO_RICHIESTO/I.COSTO_INVESTIMENTO ELSE 
						I.QUOTA_CONTRIBUTO_RICHIESTO END)/100),PR.CONTRIBUTO_AMMESSO) AS CR2						
					FROM PAGAMENTI_RICHIESTI PR INNER JOIN PIANO_INVESTIMENTI I ON PR.ID_INVESTIMENTO=I.ID_INVESTIMENTO
					INNER JOIN PAGAMENTI_BENEFICIARIO PB ON PR.ID_PAGAMENTO_RICHIESTO=PB.ID_PAGAMENTO_RICHIESTO
					WHERE PR.ID_DOMANDA_PAGAMENTO=@ID_DOMANDA_PAGAMENTO AND I.ID_PROGETTO=@ID_PROGETTO
					GROUP BY PR.ID_PAGAMENTO_RICHIESTO,PR.CONTRIBUTO_RICHIESTO,PR.CONTRIBUTO_AMMESSO) Q1
			END
		END
		
		-- TROVO L'EVENTUALE SANZIONE APPLICATA PRECEDENTEMENTE
		DECLARE @ID_SANZIONE INT
		SELECT @ID_SANZIONE=ID_SANZIONE FROM SANZIONI WHERE ID_DOMANDA_PAGAMENTO=@ID_DOMANDA_PAGAMENTO 
			AND ID_PROGETTO=@ID_PROGETTO AND COD_TIPO=@COD_TIPO AND ID_INVESTIMENTO IS NULL
		-- VERIFICA
		IF @PAGAMENTO_AMMESSO>0 AND 100*(@PAGAMENTO_RICHIESTO-@PAGAMENTO_AMMESSO)/@PAGAMENTO_AMMESSO>10 BEGIN
			/*COMMENTATA IL 07-10-2015, CAMBIO SISTEMA DI CALCOLO
			IF @COD_TIPO_DOMANDA='ANT'*/ SET @SANZIONE=@PAGAMENTO_RICHIESTO-@PAGAMENTO_AMMESSO
			/*ELSE BEGIN
				SELECT @SANZIONE=@PAGAMENTO_RICHIESTO-@PAGAMENTO_AMMESSO-ISNULL(SUM(ISNULL(IMPORTO_NONAMM_NONRESP,0)* 
					(CASE WHEN I.COD_TIPO_INVESTIMENTO=2 THEN 100*I.CONTRIBUTO_RICHIESTO/I.COSTO_INVESTIMENTO ELSE 
					I.QUOTA_CONTRIBUTO_RICHIESTO END)/100),0)
				FROM PAGAMENTI_BENEFICIARIO PB INNER JOIN PAGAMENTI_RICHIESTI PR ON PB.ID_PAGAMENTO_RICHIESTO=PR.ID_PAGAMENTO_RICHIESTO
				INNER JOIN PIANO_INVESTIMENTI I ON PR.ID_INVESTIMENTO=I.ID_INVESTIMENTO
				WHERE PR.ID_DOMANDA_PAGAMENTO=@ID_DOMANDA_PAGAMENTO AND PB.IMPORTO_RICHIESTO>PB.IMPORTO_AMMESSO AND I.ID_PROGETTO=@ID_PROGETTO			
			END*/	
			--NORMALIZZO
			IF @SANZIONE<0 SET @SANZIONE=0			
			-- INSERISCO/AGGIORNO LA SANZIONE PER LA MISURA RELATIVA
			IF @ID_SANZIONE IS NULL 
				INSERT INTO SANZIONI(COD_TIPO,ID_DOMANDA_PAGAMENTO,ID_PROGETTO,DATA_APPLICAZIONE,OPERATORE,AMMONTARE)			
				VALUES(@COD_TIPO,@ID_DOMANDA_PAGAMENTO,@ID_PROGETTO,GETDATE(),@OPERATORE,@SANZIONE)
			ELSE UPDATE SANZIONI SET DATA_APPLICAZIONE=GETDATE(),OPERATORE=@OPERATORE,AMMONTARE=@SANZIONE WHERE ID_SANZIONE=@ID_SANZIONE
		END
		ELSE IF @ID_SANZIONE IS NOT NULL DELETE FROM SANZIONI WHERE ID_SANZIONE=@ID_SANZIONE	
	END
	RETURN 0
