CREATE PROCEDURE [dbo].[SpCalcoloSanzioneRI08032011]
(
	@ID_SANZIONE INT,
	@DURATA DECIMAL(18,2) =NULL,
	@GRAVITA DECIMAL(18,2) =NULL,
	@ENTITA DECIMAL(18,2)=NULL
)
AS
/*DECLARE @ID_SANZIONE INT
SET @ID_SANZIONE=93*/

DECLARE @ID_INVESTIMENTO INT,@CONTRIBUTO_AMMESSO DECIMAL(18,2),@AMMONTARE_SANZIONE DECIMAL(18,5)
SELECT @CONTRIBUTO_AMMESSO=CONTRIBUTO_AMMESSO FROM PAGAMENTI_RICHIESTI P 
INNER JOIN SANZIONI S ON P.ID_INVESTIMENTO=S.ID_INVESTIMENTO WHERE ID_SANZIONE=@ID_SANZIONE
IF(@CONTRIBUTO_AMMESSO IS NULL) RAISERROR('PAGAMENTO_NON_ISTRUITO_ERROR',13,1)  
ELSE BEGIN
	SET @AMMONTARE_SANZIONE=ROUND(3*@CONTRIBUTO_AMMESSO/100,2)	
	UPDATE SANZIONI SET DATA_APPLICAZIONE=GETDATE(),AMMONTARE=@AMMONTARE_SANZIONE,DURATA=@DURATA,GRAVITA=@GRAVITA,
		ENTITA=@ENTITA WHERE ID_SANZIONE=@ID_SANZIONE
	SELECT * FROM VSANZIONI WHERE ID_SANZIONE=@ID_SANZIONE
END
