CREATE PROCEDURE [dbo].[SpCheckModificaChecklist]
(
	@ID_CHEKLIST INT
)
AS
	--DECLARE @ID_CHEKLIST INT;SET @ID_CHEKLIST=7
	SELECT COUNT(*) FROM STEP_X_BANDO S INNER JOIN vBANDO B ON S.ID_BANDO=B.ID_BANDO WHERE S.ID_CHECK_LIST=@ID_CHEKLIST AND B.ORDINE_STATO>1
