
CREATE PROCEDURE [dbo].[SpControlloStatoProgettoXDecadenza]
(
	@ID_PROGETTO INT
)
AS
	--DECLARE @ID_PROGETTO INT
	--SET @ID_PROGETTO=662
	
	-- CONTROLLI VARI SU POSSIBILITA DI FAR DECADERE IL PROGETTO
	-- MANDA IN ERRORE SE NON E' POSSIBILE

	-- CONTROLLO LO STATO DEL PROGETTO
	DECLARE @ORDINE_FASE INT,@ORDINE_STATO INT,@STATO VARCHAR(50),@COD_STATO CHAR(1), @SEGNATURA VARCHAR(80), @ID_ATTO INT 
	SELECT @ORDINE_FASE=ORDINE_FASE,@ORDINE_STATO=ORDINE_STATO,@STATO=STATO,@COD_STATO=COD_STATO,@SEGNATURA=SEGNATURA, @ID_ATTO = ID_ATTO
	FROM vPROGETTO WHERE ID_PROGETTO=@ID_PROGETTO
 
	IF @COD_STATO = 'E' AND (ISNUMERIC(@SEGNATURA) = 1 OR @ID_ATTO IS NOT NULL ) AND (SELECT COUNT(*) FROM ATTI WHERE ID_ATTO = ISNULL(@ID_ATTO, @SEGNATURA) ) > 0 BEGIN
		RAISERROR('Per la domanda di aiuto è già stato registrato un decreto di decadenza. Impossibile continuare.',13,1)
	END
	ELSE 
	IF @COD_STATO!='R'  AND @COD_STATO !='E' AND (@ORDINE_STATO<>1 OR @ORDINE_FASE>8 OR @ORDINE_FASE IS NULL) BEGIN
		DECLARE @MESSAGGIO VARCHAR(100)
		SET @MESSAGGIO='La domanda di aiuto selezionata è in stato '+@STATO+'. Impossibile continuare.'
		RAISERROR(@MESSAGGIO,13,1)
	END
	ELSE 
	-- INCLUSIONE IN LOTTI DI CONTROLLO
	IF (SELECT COUNT(D.ID_DOMANDA_PAGAMENTO) FROM DOMANDA_DI_PAGAMENTO D
		INNER JOIN CONTROLLI_DOMANDE_PAGAMENTO C ON D.ID_DOMANDA_PAGAMENTO=C.ID_DOMANDA_PAGAMENTO
		WHERE ID_PROGETTO=@ID_PROGETTO AND D.ANNULLATA=0 AND C.SELEZIONATA_X_CONTROLLO=1 AND C.CONTROLLO_CONCLUSO=0)>0
		RAISERROR('Esistono domande di pagamento estratte a campione per i controlli in loco per la domanda di aiuto selezionata. Impossibile continuare.',13,1)
	
	
	/*ELSE
	-- INCLUSIONE IN ELENCHI DI PAGAMENTO
	IF (SELECT COUNT(D.ID_DOMANDA_PAGAMENTO) FROM DOMANDA_DI_PAGAMENTO D
		INNER JOIN DOMANDA_DI_PAGAMENTO_ESPORTAZIONE E ON D.ID_DOMANDA_PAGAMENTO=E.ID_DOMANDA_PAGAMENTO
		WHERE D.ID_PROGETTO=@ID_PROGETTO AND D.ANNULLATA=0 AND E.ID_ELENCO_PAGAMENTO IS NOT NULL)>0
		RAISERROR('la domanda di aiuto selezionata è stata inclusa in un elenco di pagamento. Impossibile continuare.',13,1)*/