
CREATE PROCEDURE [dbo].[SpEstraiCampioneDomandeXControlliLoco] 
(
	@ID_LOTTO INT,
	@OPERATORE VARCHAR(16),
	@CAMPIONE_AGGIUNTIVO BIT=0,
	-- RITORNA IL NUMERO DI DOMANDE ESTRATTE A CAMPIONE, SE MINORE DI ZERO IL CODICE ERRORE
	@RETURN_VALUE INT OUTPUT
)
AS
/*
DECLARE @ID_LOTTO INT,@OPERATORE VARCHAR(16)
SET @ID_LOTTO=26
SET @OPERATORE =''*/

------------------------------------------------------------
-- RIEMPO LA TABELLA CON DATI DI PROVA
/*DECLARE @I INT,@COD_TIPO CHAR(3)
SET @I = 0
WHILE @I<150 BEGIN
      SET @I=@I+1
      IF @I<40 SET @COD_TIPO='SLD'
      ELSE IF @I<90 SET @COD_TIPO='SAL'
      ELSE SET @COD_TIPO='ANT'
      INSERT INTO @TABELLA_TEMP VALUES (@I,@COD_TIPO,1000,'','','7570',0,NULL,
      CAST(SUBSTRING(CAST(RAND() AS VARCHAR(10)),4,1) AS INT),NULL,NULL)
END*/

BEGIN TRY
	-- PULISCO TABELLA TEMPORANEA
	DELETE FROM CONTROLLI_DOMANDE_PAGAMENTO_ESTRAZIONE_TEMP WHERE ID_LOTTO=@ID_LOTTO
	-- POPOLO
	INSERT INTO CONTROLLI_DOMANDE_PAGAMENTO_ESTRAZIONE_TEMP (ID_LOTTO,ID_DOMANDA_PAGAMENTO,COD_TIPO,ESTRATTA,
		VALORE_DI_RISCHIO,CLASSE_DI_RISCHIO,ORDINE_CLASSE_DI_RISCHIO,CONTRIBUTO_RICHIESTO,CUAA,CUAA_SUB,RAGIONE_SOCIALE)
	SELECT C.ID_LOTTO,D.ID_DOMANDA_PAGAMENTO,D.COD_TIPO,0,VALORE_DI_RISCHIO,CASE WHEN VALORE_DI_RISCHIO>25 THEN 'A' 
		WHEN VALORE_DI_RISCHIO>15 THEN 'M' ELSE 'B' END,CASE WHEN VALORE_DI_RISCHIO>25 THEN 1 WHEN VALORE_DI_RISCHIO> 15 THEN 2 
		ELSE 3 END,CONTRIBUTO_RICHIESTO,I.CUAA,SUBSTRING(I.CUAA,8,1)+SUBSTRING(I.CUAA,11,1)+SUBSTRING(I.CUAA,7,1)
		+SUBSTRING(I.CUAA,10,1),RAGIONE_SOCIALE
	FROM VIMPRESA I INNER JOIN PROGETTO P ON I.ID_IMPRESA=P.ID_IMPRESA
	INNER JOIN DOMANDA_DI_PAGAMENTO D ON P.ID_PROGETTO=D.ID_PROGETTO
	INNER JOIN CONTROLLI_DOMANDE_PAGAMENTO C ON C.ID_DOMANDA_PAGAMENTO=D.ID_DOMANDA_PAGAMENTO
	WHERE ID_LOTTO=@ID_LOTTO AND C.SELEZIONATA_X_CONTROLLO=0

	--CONTROLLO CHE TUTTE LE DOMANDE ABBIANO IL VALORE DI RISCHIO ASSEGNATO
	IF (SELECT COUNT(*) FROM CONTROLLI_DOMANDE_PAGAMENTO_ESTRAZIONE_TEMP WHERE ID_LOTTO=@ID_LOTTO AND VALORE_DI_RISCHIO IS NULL)>0 BEGIN 
		SET @RETURN_VALUE=-3 
		RETURN
	END
	-- MEMORIZZO IL TOTALE RICHIESTO PER L'INTERO LOTTO
	DECLARE @TOTALE_PAGAMENTO_RICHIESTO_LOTTO DECIMAL(18,2)
	SELECT @TOTALE_PAGAMENTO_RICHIESTO_LOTTO=SUM(CONTRIBUTO_RICHIESTO) FROM CONTROLLI_DOMANDE_PAGAMENTO_ESTRAZIONE_TEMP WHERE ID_LOTTO=@ID_LOTTO
	----------------------------------------------------------		
	-- ESTRAZIONE CON PARAMETRI DI RISCHIO
	DECLARE @SOGLIA_ESTRAZIONE_RISCHIO DECIMAL(18,2)
	SET @SOGLIA_ESTRAZIONE_RISCHIO=ROUND(5*@TOTALE_PAGAMENTO_RICHIESTO_LOTTO/100,2)
	EXEC SpEstraiCampioneDomandeXControlliLocoRischio @ID_LOTTO,@SOGLIA_ESTRAZIONE_RISCHIO
	----------------------------------------------------------
	-- MEMORIZZO I DATI IN TABELLA
	DECLARE @NR_DOMANDE_ESTRATTE INT
	UPDATE D SET SELEZIONATA_X_CONTROLLO=TT.ESTRATTA,D.TIPO_ESTRAZIONE=TT.TIPO_ESTRAZIONE,D.CLASSE_DI_RISCHIO=TT.CLASSE_DI_RISCHIO,
		D.ORDINE_CLASSE_DI_RISCHIO=TT.ORDINE_CLASSE_DI_RISCHIO,DATA_MODIFICA=GETDATE(),OPERATORE=@OPERATORE
	FROM CONTROLLI_DOMANDE_PAGAMENTO_ESTRAZIONE_TEMP TT 
	INNER JOIN CONTROLLI_DOMANDE_PAGAMENTO D ON TT.ID_LOTTO=D.ID_LOTTO AND TT.ID_DOMANDA_PAGAMENTO=D.ID_DOMANDA_PAGAMENTO
	WHERE TT.ID_LOTTO=@ID_LOTTO
	SELECT @NR_DOMANDE_ESTRATTE=COUNT(*) FROM CONTROLLI_DOMANDE_PAGAMENTO_ESTRAZIONE_TEMP WHERE ID_LOTTO=@ID_LOTTO AND ESTRATTA=1
	IF @NR_DOMANDE_ESTRATTE>0
		UPDATE C SET NUMERO_ESTRAZIONI=NUMERO_ESTRAZIONI+1,DATA_ESTRAZIONE=GETDATE(),DATA_MODIFICA=GETDATE(),OPERATORE=@OPERATORE
		FROM CONTROLLI_LOCO_LOTTO C WHERE ID_LOTTO=@ID_LOTTO
	SET @RETURN_VALUE=@NR_DOMANDE_ESTRATTE
	
	--SELECT * FROM CONTROLLI_DOMANDE_PAGAMENTO_ESTRAZIONE_TEMP WHERE ID_LOTTO=@ID_LOTTO
	--ORDER BY ESTRATTA DESC,TIPO_ESTRAZIONE,COD_TIPO DESC,VALORE_DI_RISCHIO DESC,CONTRIBUTO_RICHIESTO DESC
END TRY
BEGIN CATCH
	SET @RETURN_VALUE=-1
END CATCH
