
CREATE PROCEDURE [dbo].[SpEstraiCampioneDomandeXControlliLocoRischio]
(
	@ID_LOTTO INT,
	@SOGLIA_ESTRAZIONE DECIMAL(18,2) -- CONTRIBUTO DA CONTROLLARE IN MODALITA RISCHIO	
)
AS	
	DECLARE @NR_DOMANDE_X_CLASSE_A INT,@NR_DOMANDE_X_CLASSE_M INT,@NR_DOMANDE_X_CLASSE_B INT,@COUNTER INT,@NUMERO_SALDI INT,@NUMERO_SAL INT,
		@IMPORTO_TOTALE_SALDI DECIMAL(18,2),@IMPORTO_TOTALE_SAL DECIMAL(18,2),@ID_DOMANDA_PAGAMENTO INT,
		@CONTRIBUTO_RICHIESTO_DOMANDA DECIMAL(18,2)	
		
	DECLARE @SOGLIA_PARZIALE DECIMAL(18,2)
	-- CLASSE ALTA
	SELECT @SOGLIA_PARZIALE=SUM(CONTRIBUTO_RICHIESTO)/2 FROM CONTROLLI_DOMANDE_PAGAMENTO_ESTRAZIONE_TEMP
	WHERE ID_LOTTO=@ID_LOTTO AND CLASSE_DI_RISCHIO='A' AND ESTRATTA=0
	EXEC SpEstraiCampioneDomandeXControlliLocoRischioSub @ID_LOTTO,@SOGLIA_PARZIALE,'A'
	-- CLASSE MEDIA
	SELECT @SOGLIA_PARZIALE=SUM(CONTRIBUTO_RICHIESTO)/3 FROM CONTROLLI_DOMANDE_PAGAMENTO_ESTRAZIONE_TEMP
	WHERE ID_LOTTO=@ID_LOTTO AND CLASSE_DI_RISCHIO='M' AND ESTRATTA=0	
	EXEC SpEstraiCampioneDomandeXControlliLocoRischioSub @ID_LOTTO,@SOGLIA_PARZIALE,'M'	
	-- CLASSE BASSA
	SELECT @SOGLIA_PARZIALE=SUM(CONTRIBUTO_RICHIESTO)/5 FROM CONTROLLI_DOMANDE_PAGAMENTO_ESTRAZIONE_TEMP
	WHERE ID_LOTTO=@ID_LOTTO AND CLASSE_DI_RISCHIO='B' AND ESTRATTA=0
	EXEC SpEstraiCampioneDomandeXControlliLocoRischioSub @ID_LOTTO,@SOGLIA_PARZIALE,'B'
