CREATE PROCEDURE [dbo].[SpFindComunicazioni]
(
	@ID_BANDO INT,
	@COD_TIPO VARCHAR(3), -- RICERCA CON LIKE
	@ID_PROGETTO INT=NULL,
	@PROVINCIA CHAR(2)=NULL,
	@COD_STATO CHAR(1)=NULL	
)
AS
	SELECT VI.*,VP.COD_TIPO AS COD_TIPO_COMUNICAZIONE, VP.SEGNATURA AS SEGNATURA_COMUNICAZIONE,VP.TIPO_SEGNATURA AS TIPO_SEGNATURA_COMUNICAZIONE 
	FROM vISTRUTTORIA_DOMANDE VI LEFT OUTER JOIN vPROGETTO_SEGNATURE VP ON VI.ID_PROGETTO = VP.ID_PROGETTO AND COD_TIPO LIKE @COD_TIPO+'%' 
	WHERE ID_BANDO = @ID_BANDO AND (@ID_PROGETTO IS NULL OR VI.ID_PROGETTO=@ID_PROGETTO)
		AND (@PROVINCIA IS NULL OR PROVINCIA_ASSEGNAZIONE=@PROVINCIA) AND (@COD_STATO IS NULL OR FILTRO_STATO_ISTRUTTORIA=@COD_STATO)
	ORDER BY ID_PROGETTO

