create PROCEDURE [dbo].[SpGetCertificazioneAntimafiaXImpresa] 
(
	@ID_IMPRESA INT,
	@DATA DATETIME
)
AS
	SELECT TOP 1 * 
	FROM IMPRESA_CERTIFICAZIONE_ANTIMAFIA
	WHERE ID_IMPRESA = @ID_IMPRESA 
	AND DATA_INIZIO_VALIDITA < @DATA 
	AND DATA_FINE_VALIDITA > @DATA
	ORDER BY ID DESC
