CREATE PROCEDURE [dbo].[SpGetAssegnazioneDomande] 
(
	@ID_BANDO INT,
	@PROVINCIA CHAR(2)=NULL,
	@ID_COMUNE INT =NULL
)
AS
	SELECT P.*,PS.DATA AS DATA_PRESENTAZIONE,I.CUAA,I.CODICE_FISCALE,S.RAGIONE_SOCIALE,N.COMUNE,N.SIGLA,N.CAP 
	FROM vPROGETTO P INNER JOIN 
		(SELECT MAX(ID) AS MAX_ID,ID_PROGETTO FROM PROGETTO_STORICO WHERE COD_STATO='L' GROUP BY ID_PROGETTO) AS Q1
		ON P.ID_PROGETTO=Q1.ID_PROGETTO
	INNER JOIN PROGETTO_STORICO PS ON Q1.MAX_ID=PS.ID	
	INNER JOIN IMPRESA I ON P.ID_IMPRESA=I.ID_IMPRESA
	INNER JOIN IMPRESA_STORICO S ON I.ID_STORICO_ULTIMO=S.ID_STORICO_IMPRESA
	INNER JOIN vINDIRIZZARIO N ON I.ID_SEDELEGALE_ULTIMO=N.ID_INDIRIZZARIO
	LEFT JOIN COLLABORATORI_X_BANDO C ON P.ID_PROGETTO=C.ID_PROGETTO AND ATTIVO=1
	WHERE P.ID_BANDO=@ID_BANDO AND P.COD_STATO!='P' AND FLAG_PREADESIONE=0 AND C.ID_COLLABORATORE IS NULL
		AND (@ID_COMUNE IS NULL OR ID_COMUNE=@ID_COMUNE) AND (@PROVINCIA IS NULL OR PROVINCIA_DI_PRESENTAZIONE=@PROVINCIA)
	ORDER BY ID_PROGETTO
