
CREATE PROCEDURE [dbo].[SpGetVariantiPerPrioritaByVariante]
(
	@ID_VARIANTE INT
)
AS
	SELECT R.ID_PRIORITA,P.ID_PROGETTO,V.ID_VARIANTE, PUNTEGGIO,DATA_VALUTAZIONE,G.OPERATORE,G.FLAG_DEFINITIVO,R.DESCRIZIONE,R.COD_LIVELLO,
		R.PLURI_VALORE,R.EVAL,R.FLAG_MANUALE,R.INPUT_NUMERICO,R.MISURA
	FROM VARIANTI V INNER JOIN PROGETTO P ON V.ID_PROGETTO = P.ID_PROGETTO
	INNER JOIN BANDO B ON P.ID_BANDO=B.ID_BANDO
	INNER JOIN SCHEDA_VALUTAZIONE SV ON B.ID_SCHEDA_VALUTAZIONE = SV.ID_SCHEDA_VALUTAZIONE
	INNER JOIN SCHEDA_X_PRIORITA SP ON SV.ID_SCHEDA_VALUTAZIONE = SP.ID_SCHEDA_VALUTAZIONE AND ISNULL(SP.PESO,0)> 0 AND SP.SELEZIONABILE = 0
	INNER JOIN PRIORITA R ON SP.ID_PRIORITA=R.ID_PRIORITA
	LEFT OUTER JOIN VARIANTI_X_PRIORITA G ON SP.ID_PRIORITA = G.ID_PRIORITA AND V.ID_VARIANTE = G.ID_VARIANTE
	WHERE V.ID_VARIANTE=@ID_VARIANTE

