CREATE PROCEDURE [dbo].[SpGetSegnatureVarianti]
(
	@ID_PROGETTO INT
)
AS
	SELECT @ID_PROGETTO AS ID_PROGETTO,Q1.*,U.NOMINATIVO,U.PROVINCIA,U.ID_PROFILO,U.PROFILO,U.COD_ENTE,U.ENTE 
	FROM (
		SELECT ID_VARIANTE,V.COD_TIPO,CASE WHEN V.SEGNATURA IS NULL THEN 'Avvio lavorazione ' ELSE 'Presentazione ' END +
			T.DESCRIZIONE AS TIPO_SEGNATURA,SEGNATURA,DATA_MODIFICA AS DATA,OPERATORE,NULL AS MOTIVAZIONE,APPROVATA AS RIAPRI_DOMANDA
		FROM VARIANTI V INNER JOIN TIPO_VARIANTE T ON V.COD_TIPO=T.COD_TIPO WHERE ID_PROGETTO=@ID_PROGETTO AND V.COD_TIPO!='VI'
		UNION ALL
		SELECT ID_VARIANTE,V.COD_TIPO,TIPO_SEGNATURA=CASE WHEN APPROVATA=1 THEN 'Approvazione '+T.DESCRIZIONE 
			ELSE 'Bocciatura domanda di '+T.DESCRIZIONE END,SEGNATURA_APPROVAZIONE AS SEGNATURA,DATA_APPROVAZIONE AS DATA,
			ISTRUTTORE AS OPERATORE,NULL AS MOTIVAZIONE,APPROVATA AS RIAPRI_DOMANDA 
		FROM VARIANTI V	INNER JOIN TIPO_VARIANTE T ON V.COD_TIPO=T.COD_TIPO
		WHERE ID_PROGETTO=@ID_PROGETTO AND APPROVATA IS NOT NULL AND V.COD_TIPO!='VI'
		UNION ALL
		SELECT ID_VARIANTE,V.COD_TIPO,'Richiesta di annullamento '+T.DESCRIZIONE AS TIPO_SEGNATURA,SEGNATURA_ANNULLAMENTO AS SEGNATURA,
			DATA_ANNULLAMENTO AS DATA,CF_OPERATORE_ANNULLAMENTO AS OPERATORE,NULL AS MOTIVAZIONE,ANNULLATA AS RIAPRI_DOMANDA
		FROM VARIANTI V	INNER JOIN TIPO_VARIANTE T ON V.COD_TIPO=T.COD_TIPO
		WHERE ID_PROGETTO=@ID_PROGETTO AND ANNULLATA=1 AND V.COD_TIPO!='VI'
		UNION ALL
		SELECT V.ID_VARIANTE,S.COD_TIPO,TIPO_SEGNATURA=CASE WHEN S.COD_TIPO='APP' THEN (CASE WHEN RIAPRI_VARIANTE=1 THEN 'Approvazione ' 
			ELSE 'Bocciatura ' END)+(SELECT T1.DESCRIZIONE FROM VARIANTI V1 INNER JOIN TIPO_VARIANTE T1 
			ON V1.COD_TIPO=T1.COD_TIPO WHERE V1.ID_VARIANTE=S.ID_VARIANTE) ELSE TS.DESCRIZIONE END,S.SEGNATURA,DATA,S.OPERATORE,
			MOTIVAZIONE,RIAPRI_VARIANTE AS RIAPRI_DOMANDA 
		FROM VARIANTI V INNER JOIN VARIANTI_SEGNATURE S ON V.ID_VARIANTE=S.ID_VARIANTE 
		INNER JOIN TIPO_SEGNATURA TS ON S.COD_TIPO=TS.COD_TIPO WHERE V.ID_PROGETTO=@ID_PROGETTO	) AS Q1
	INNER JOIN vUTENTI U ON Q1.OPERATORE=U.CF_UTENTE ORDER BY ID_VARIANTE DESC,DATA DESC
