CREATE PROCEDURE [dbo].[SpGetEsitiChecklistByIdProgetto]
(
	@ID_PROGETTO INT,	
	@COD_FASE CHAR(1)
)
AS	
	--DECLARE @ID_PROGETTO INT,@ID_DOMANDA_PAGAMENTO INT,@COD_FASE CHAR(1),@OPERATORE CHAR(16)
	--SET @ID_PROGETTO=515
	--SET @COD_FASE='P'
	--SET @OPERATORE=''
	
	SELECT S.ID_STEP,S.DESCRIZIONE,OBBLIGATORIO,AUTOMATICO,S.URL,S.CODE_METHOD,I.COD_ESITO,ISNULL(E.ESITO_POSITIVO,0) AS ESITO_POSITIVO,
		DATA,CF_OPERATORE,NOTE, I.COD_ESITO_REVISORE, I.REVISORE , I.NOTE_REVISORE , I.DATA_REVISORE 
	FROM PROGETTO P
	INNER JOIN STEP_X_BANDO X ON P.ID_BANDO=X.ID_BANDO AND X.COD_FASE=@COD_FASE
	INNER JOIN CHECK_LIST_X_STEP C ON X.ID_CHECK_LIST=C.ID_CHECK_LIST
	INNER JOIN STEP S ON C.ID_STEP=S.ID_STEP
	LEFT JOIN ITER_PROGETTO I ON P.ID_PROGETTO=I.ID_PROGETTO AND S.ID_STEP=I.ID_STEP
	LEFT JOIN ESITI_STEP E ON I.COD_ESITO=E.COD_ESITO
	WHERE P.ID_PROGETTO=@ID_PROGETTO
	ORDER BY C.ORDINE
