
CREATE PROCEDURE [dbo].[SpGetStepByCodiceQuery]
(
	@CODICE VARCHAR(250)
)
AS
	SELECT S.ID_STEP,C.OBBLIGATORIO,S.DESCRIZIONE AS STEP,S.AUTOMATICO,S.QUERY_SQL,
		   L.DESCRIZIONE AS CHECK_LIST, S.VAL_MASSIMO,S.VAL_MINIMO,S.FASE_PROCEDURALE
	FROM vSTEP S
		LEFT JOIN CHECK_LIST_X_STEP C on C.ID_STEP= S.ID_STEP
		LEFT JOIN CHECK_LIST L on L.ID_CHECK_LIST = C.ID_CHECK_LIST 
	WHERE S.QUERY_SQL LIKE '%'+@CODICE+'%'
	UNION 
	SELECT P.ID_PRIORITA,1,P.DESCRIZIONE AS STEP,P.FLAG_MANUALE,P.EVAL,
		SP.DESCRIZIONE AS CHECK_LIST, '0','0',NULL 
	FROM PRIORITA P
		LEFT JOIN VSCHEDA_X_PRIORITA SP ON SP.ID_PRIORITA = P.ID_PRIORITA 
	WHERE P.EVAL LIKE '%'+@CODICE+'%'