-- usata nella pagine degli invesetimenti a fondo perduto per la option group combo
CREATE PROCEDURE [dbo].[SpGetCategorieInvestimenti]
(@ID_BANDO INT)
AS 
/*
DECLARE @ID_BANDO INT
SET @ID_BANDO=14
*/
CREATE TABLE #CATEGORIE_INVESTIMENTI(CODICE VARCHAR(50), DESCRIZIONE VARCHAR(255),LIVELLO INT,HA_FIGLI BIT)

DECLARE @ID_CODIFICA_TEMP VARCHAR(12)
DECLARE @ID_DETTAGLIO_TEMP VARCHAR(12)

DECLARE @ID VARCHAR(12)
DECLARE @DESCRIZIONE VARCHAR(255)
DECLARE @LIVELLO INT
DECLARE @HA_FIGLI BIT

-- SCORRO LE CODIFICHE
DECLARE CODIFICA CURSOR FOR
(SELECT ID_CODIFICA_INVESTIMENTO,DESCRIZIONE,1,1 FROM CODIFICA_INVESTIMENTO WHERE ID_BANDO=@ID_BANDO)
OPEN CODIFICA
FETCH NEXT FROM CODIFICA INTO @ID,@DESCRIZIONE,@LIVELLO,@HA_FIGLI
WHILE @@FETCH_STATUS = 0
BEGIN
	INSERT INTO #CATEGORIE_INVESTIMENTI SELECT @ID,@DESCRIZIONE,@LIVELLO,@HA_FIGLI
	SET @ID_CODIFICA_TEMP=@ID
	--SCORRO I DETTAGLI
	DECLARE DETTAGLIO CURSOR FOR
	(SELECT ID_DETTAGLIO_INVESTIMENTO,DESCRIZIONE,2,0 AS LIVELLO FROM DETTAGLIO_INVESTIMENTI WHERE ID_CODIFICA_INVESTIMENTO=@ID_CODIFICA_TEMP)
	OPEN DETTAGLIO
	FETCH NEXT FROM DETTAGLIO INTO @ID,@DESCRIZIONE,@LIVELLO,@HA_FIGLI
	WHILE @@FETCH_STATUS = 0
	BEGIN		
		DECLARE @CODICE_TEMP2 VARCHAR(30)
		DECLARE @DETTAGLIO_CON_FIGLI BIT
		SET @DETTAGLIO_CON_FIGLI=0
		SET @CODICE_TEMP2=@ID_CODIFICA_TEMP+'|'+CAST(@ID AS VARCHAR(12))
		INSERT INTO #CATEGORIE_INVESTIMENTI SELECT @CODICE_TEMP2,@DESCRIZIONE,@LIVELLO,@HA_FIGLI
		SET @ID_DETTAGLIO_TEMP=@ID
		-- SCORRO LE SPECIFICHE
		DECLARE SPECIFICA CURSOR FOR
		(SELECT ID_SPECIFICA_INVESTIMENTO,DESCRIZIONE,3,0 AS LIVELLO FROM SPECIFICA_INVESTIMENTI WHERE ID_DETTAGLIO_INVESTIMENTO=@ID_DETTAGLIO_TEMP)
		OPEN SPECIFICA
		FETCH NEXT FROM SPECIFICA INTO @ID,@DESCRIZIONE,@LIVELLO,@HA_FIGLI
		WHILE @@FETCH_STATUS = 0
		BEGIN
			INSERT INTO #CATEGORIE_INVESTIMENTI SELECT @ID_CODIFICA_TEMP+'|'+@ID_DETTAGLIO_TEMP+'|'+CAST(@ID AS VARCHAR(12)),@DESCRIZIONE,@LIVELLO,@HA_FIGLI			
			SET @DETTAGLIO_CON_FIGLI=1
			FETCH NEXT FROM SPECIFICA INTO @ID,@DESCRIZIONE,@LIVELLO,@HA_FIGLI
		END
		CLOSE SPECIFICA
		DEALLOCATE SPECIFICA
		
		UPDATE #CATEGORIE_INVESTIMENTI SET HA_FIGLI=@DETTAGLIO_CON_FIGLI WHERE CODICE= @CODICE_TEMP2
		FETCH NEXT FROM DETTAGLIO INTO @ID,@DESCRIZIONE,@LIVELLO,@HA_FIGLI
	END
	CLOSE DETTAGLIO
	DEALLOCATE DETTAGLIO

	FETCH NEXT FROM CODIFICA INTO @ID,@DESCRIZIONE,@LIVELLO,@HA_FIGLI
END
CLOSE CODIFICA
DEALLOCATE CODIFICA

SELECT * FROM #CATEGORIE_INVESTIMENTI
DROP TABLE #CATEGORIE_INVESTIMENTI
