


CREATE PROCEDURE [dbo].[SpGetComunicazioniNonAmmissibilitaBando]
(
	@ID_BANDO INT,
	@PROVINCIA CHAR(2)=NULL,
	@ID_PROGETTO INT=NULL
)
AS
	SELECT P.ID_PROGETTO,P.STATO,I.CODICE_FISCALE AS PIVA,IST.RAGIONE_SOCIALE,D.COMUNE+' ('+D.SIGLA+') - '+ISNULL(D.CAP,'') AS SEDE,
		C.NOMINATIVO AS ISTRUTTORE,C.PROVINCIA,NAP.SEGNATURA AS NAP_SEGNATURA,NAD.SEGNATURA AS NAD_SEGNATURA,
		S.ID_ATTO,ISNULL(CAST(A.NUMERO AS VARCHAR(10))+'|'+CONVERT(CHAR(10),A.DATA,103)+'|'+A.REGISTRO,'') AS ATTO
	FROM vPROGETTO P INNER JOIN IMPRESA I ON P.ID_IMPRESA=I.ID_IMPRESA
	INNER JOIN IMPRESA_STORICO IST ON I.ID_STORICO_ULTIMO=IST.ID_STORICO_IMPRESA
	INNER JOIN vINDIRIZZARIO D ON I.ID_SEDELEGALE_ULTIMO=D.ID_INDIRIZZARIO
	INNER JOIN (SELECT ID_PROGETTO,MAX(ID) AS MAX_ID FROM PROGETTO_STORICO WHERE COD_STATO='B'
		GROUP BY ID_PROGETTO) AS MST ON P.ID_PROGETTO=MST.ID_PROGETTO
	INNER JOIN PROGETTO_STORICO S ON MST.MAX_ID=S.ID
	INNER JOIN vCOLLABORATORI_X_BANDO C ON C.ID_PROGETTO=P.ID_PROGETTO AND C.ID_BANDO=@ID_BANDO AND C.ATTIVO=1 		
	LEFT JOIN PROGETTO_SEGNATURE NAP ON P.ID_PROGETTO=NAP.ID_PROGETTO AND NAP.COD_TIPO='NAP'
	LEFT JOIN PROGETTO_SEGNATURE NAD ON P.ID_PROGETTO=NAD.ID_PROGETTO AND NAD.COD_TIPO='NAD'
	LEFT JOIN ATTI A ON S.ID_ATTO=A.ID_ATTO
	WHERE P.ID_BANDO=@ID_BANDO AND (@ID_PROGETTO IS NULL OR P.ID_PROGETTO=@ID_PROGETTO)
		AND (@PROVINCIA IS NULL OR C.PROVINCIA=@PROVINCIA)


