CREATE PROCEDURE [dbo].[SpGetValutatoriProgetto]
(
	@ID_PROGETTO_VALUTAZIONE INT
)
AS
	SELECT V.ID, V.ID_PROGETTO_VALUTAZIONE, V.ID_VALUTATORE, V.PRESENTE, U.NOMINATIVO, 
	--B.ORDINE
	--ROW_NUMBER() OVER (ORDER BY B.ORDINE) AS ORDINE
	V.ORDINE
	FROM PROGETTO_VALUTATORI V 
	INNER JOIN BANDO_VALUTATORI B ON V.ID_VALUTATORE = B.ID_VALUTATORE-- AND B.ATTIVO = 1
	INNER JOIN vUTENTI U ON B.ID_UTENTE = U.ID_UTENTE
	WHERE V.ID_PROGETTO_VALUTAZIONE=@ID_PROGETTO_VALUTAZIONE
	ORDER BY V.PRESENTE DESC, V.ORDINE
