CREATE PROCEDURE [dbo].[SpGetStatisticaOperatoriEnte] 
(
	@COD_ENTE VARCHAR(10),
	@PROVINCIA CHAR(2)=NULL
)
AS 
	--USATA NELLA PAGINA GESTIONE ENTE DELLA SEZIONE AMMINISTRAZIONE
	/*
	DECLARE @COD_ENTE VARCHAR(10),@PROVINCIA CHAR(2)
	SET @COD_ENTE='%'*/

	DECLARE @PROGETTI TABLE (ID_UTENTE INT,SEGNATURA VARCHAR(80))
	INSERT INTO @PROGETTI (ID_UTENTE,SEGNATURA)
	SELECT S.OPERATORE,SEGNATURA FROM PROGETTO P
	INNER JOIN (SELECT MAX(ID) AS MAX_ID,ID_PROGETTO FROM PROGETTO_STORICO WHERE COD_STATO IN ('L','P') GROUP BY ID_PROGETTO) Q1
		ON P.ID_PROGETTO=Q1.ID_PROGETTO
	INNER JOIN PROGETTO_STORICO S ON Q1.MAX_ID=S.ID
	WHERE ISNULL(P.ID_PROG_INTEGRATO,P.ID_PROGETTO)=P.ID_PROGETTO AND FLAG_PREADESIONE=0

	DECLARE @DOMANDE_PAGAMENTO TABLE (ID_UTENTE INT,SEGNATURA VARCHAR(100))
	INSERT INTO @DOMANDE_PAGAMENTO (ID_UTENTE,SEGNATURA)
	SELECT ID_UTENTE,SEGNATURA FROM DOMANDA_DI_PAGAMENTO D 
	INNER JOIN PERSONA_FISICA F ON D.CF_OPERATORE=F.CODICE_FISCALE
	INNER JOIN UTENTI U ON F.ID_PERSONA=U.ID_PERSONA_FISICA

	DECLARE @VARIANTI TABLE (ID_UTENTE INT,SEGNATURA VARCHAR(100))
	INSERT INTO @VARIANTI (ID_UTENTE,SEGNATURA)
	SELECT ID_UTENTE,SEGNATURA FROM VARIANTI V
	INNER JOIN PERSONA_FISICA F ON V.OPERATORE=F.CODICE_FISCALE
	INNER JOIN UTENTI U ON F.ID_PERSONA=U.ID_PERSONA_FISICA


	SELECT U.*,Q1.PROGETTI_PROVVISORI,Q2.PROGETTI_DEFINITIVI,D1.PAGAMENTI_PROVVISORI,D2.PAGAMENTI_DEFINITIVI,
	V1.VARIANTI_PROVVISORIE,V2.VARIANTI_DEFINITIVE
	FROM VUTENTI U
	LEFT JOIN (SELECT ID_UTENTE,COUNT(*) AS PROGETTI_PROVVISORI FROM @PROGETTI WHERE SEGNATURA IS NULL
		GROUP BY ID_UTENTE) AS Q1 ON U.ID_UTENTE=Q1.ID_UTENTE
	LEFT JOIN (SELECT ID_UTENTE,COUNT(*) AS PROGETTI_DEFINITIVI FROM @PROGETTI WHERE SEGNATURA IS NOT NULL
		GROUP BY ID_UTENTE) AS Q2 ON U.ID_UTENTE=Q2.ID_UTENTE

	LEFT JOIN (SELECT ID_UTENTE,COUNT(*) AS PAGAMENTI_PROVVISORI FROM @DOMANDE_PAGAMENTO WHERE SEGNATURA IS NULL
		GROUP BY ID_UTENTE) AS D1 ON U.ID_UTENTE=D1.ID_UTENTE
	LEFT JOIN (SELECT ID_UTENTE,COUNT(*) AS PAGAMENTI_DEFINITIVI FROM @DOMANDE_PAGAMENTO WHERE SEGNATURA IS NOT NULL
		GROUP BY ID_UTENTE) AS D2 ON U.ID_UTENTE=D2.ID_UTENTE

	LEFT JOIN (SELECT ID_UTENTE,COUNT(*) AS VARIANTI_PROVVISORIE FROM @VARIANTI WHERE SEGNATURA IS NULL
		GROUP BY ID_UTENTE) AS V1 ON U.ID_UTENTE=V1.ID_UTENTE
	LEFT JOIN (SELECT ID_UTENTE,COUNT(*) AS VARIANTI_DEFINITIVE FROM @VARIANTI WHERE SEGNATURA IS NOT NULL
		GROUP BY ID_UTENTE) AS V2 ON U.ID_UTENTE=V2.ID_UTENTE
	WHERE COD_ENTE=@COD_ENTE AND (@PROVINCIA IS NULL OR U.PROVINCIA=@PROVINCIA)
