CREATE PROCEDURE [dbo].[SpGetComunicazioniEntrataBando]
(
	@ID_BANDO INT,
	@ID_PROGETTO INT=NULL,
	@COD_TIPO CHAR(3)=NULL
)
AS
	SELECT S.* FROM vPROGETTO_SEGNATURE S INNER JOIN PROGETTO P ON S.ID_PROGETTO=P.ID_PROGETTO
	WHERE P.ID_BANDO=@ID_BANDO AND (@ID_PROGETTO IS NULL OR S.ID_PROGETTO=@ID_PROGETTO)
		AND ((@COD_TIPO IS NULL AND COD_TIPO IN ('RID', 'RIN', 'DNT', 'RIC')) OR COD_TIPO=@COD_TIPO)
