CREATE PROCEDURE [dbo].[SpGetPrioritaBySchedaValutazione]
(
	@ID_SCHEDA_VALUTAZIONE INT=NULL,
	@MISURA VARCHAR(20)=NULL,
	@DESCRIZIONE VARCHAR(1000) = NULL
) 
AS
	-- USATA NELLA PAGINA DI DETTAGLIO DELLA SCHEDA DI VALUTAZIONE
	
	--DECLARE @ID_SCHEDA_VALUTAZIONE INT,@MISURA VARCHAR(20);SET @ID_SCHEDA_VALUTAZIONE=91;SET @MISURA='2'
	
	SELECT S.ID_SCHEDA_VALUTAZIONE,S.DESCRIZIONE,S.FLAG_TEMPLATE,P.ID_PRIORITA,P.DESCRIZIONE AS PRIORITA,COD_LIVELLO,ORDINE,PESO,
		VALORE_MAX,VALORE_MIN,AIUTO_ADDIZIONALE,SELEZIONABILE,PLURI_VALORE,EVAL,FLAG_MANUALE,X.IS_MAX,INPUT_NUMERICO,MISURA,
		P.DATETIME,P.TESTO_SEMPLICE, P.TESTO_AREA, P.PLURI_VALORE_SQL, P.QUERY_PLURIVALORE,
		PS.ID_PRIORITA_SELEZIONATA AS ID_PRIORITA_SPECIALE,PS.IS_MAX AS IS_MAX_SPECIALE,ISNULL(X.ORDINE,9999)
	FROM SCHEDA_VALUTAZIONE S INNER JOIN SCHEDA_X_PRIORITA X ON X.ID_SCHEDA_VALUTAZIONE=S.ID_SCHEDA_VALUTAZIONE
	INNER JOIN PRIORITA P ON P.ID_PRIORITA = X.ID_PRIORITA 
	LEFT JOIN PRIORITA_SPECIALE PS ON X.ID_PRIORITA=PS.ID_PRIORITA AND X.ID_SCHEDA_VALUTAZIONE=PS.ID_SCHEDA_VALUTAZIONE	
	WHERE S.ID_SCHEDA_VALUTAZIONE=@ID_SCHEDA_VALUTAZIONE	
	UNION
	SELECT S.ID_SCHEDA_VALUTAZIONE,S.DESCRIZIONE,S.FLAG_TEMPLATE,P.ID_PRIORITA,P.DESCRIZIONE AS PRIORITA,COD_LIVELLO,ORDINE,PESO,
		VALORE_MAX,VALORE_MIN,AIUTO_ADDIZIONALE,SELEZIONABILE,PLURI_VALORE,EVAL,FLAG_MANUALE,X.IS_MAX,INPUT_NUMERICO,MISURA,
		P.DATETIME,P.TESTO_SEMPLICE, P.TESTO_AREA, P.PLURI_VALORE_SQL, P.QUERY_PLURIVALORE,
		PS.ID_PRIORITA_SELEZIONATA AS ID_PRIORITA_SPECIALE,PS.IS_MAX AS IS_MAX_SPECIALE,ISNULL(X.ORDINE,9999)
	FROM PRIORITA P LEFT JOIN SCHEDA_X_PRIORITA X ON P.ID_PRIORITA = X.ID_PRIORITA AND X.ID_SCHEDA_VALUTAZIONE=@ID_SCHEDA_VALUTAZIONE	
	LEFT JOIN PRIORITA_SPECIALE PS ON X.ID_PRIORITA=PS.ID_PRIORITA AND X.ID_SCHEDA_VALUTAZIONE=PS.ID_SCHEDA_VALUTAZIONE
	LEFT JOIN SCHEDA_VALUTAZIONE S ON X.ID_SCHEDA_VALUTAZIONE=S.ID_SCHEDA_VALUTAZIONE
	WHERE (@MISURA IS NULL OR P.MISURA LIKE '%'+@MISURA+'%') AND (@DESCRIZIONE IS NULL OR P.DESCRIZIONE LIKE '%'+@DESCRIZIONE+'%' )
	ORDER BY ISNULL(X.ORDINE,9999),P.ID_PRIORITA

	