CREATE PROCEDURE [dbo].[SpGetDecretilElenchiDiPagamento]
(
	@ID_BANDO INT,
	@ID_ELENCO INT=NULL
)
AS
	--DECLARE @ID_BANDO INT=131

SELECT ID_ELENCO_PAGAMENTO, ID_BANDO_PRINCIPALE, ID_ELENCO_REGIONALE, 
              SEGNATURA, NOMINATIVO_OPERATORE, ID_ATTO_AUTORIZZAZIONE, A.COD_DEFINIZIONE,A.NUMERO AS NUMERO_DECRETO,A.DATA AS DATA_DECRETO,
              A.AW_DOCNUMBER,A.AW_DOCNUMBER_NUOVO, ESPORTATO, DATA_ESPORTAZIONE
FROM vELENCO_DI_PAGAMENTO 
LEFT JOIN ATTI A ON ID_ATTO_AUTORIZZAZIONE=A.ID_ATTO
WHERE PROVINCIA IS NULL AND ID_BANDO_PRINCIPALE = ID_DISPOSIZIONE_ATTUATIVA 
AND ((@ID_ELENCO IS NOT NULL AND ID_ELENCO_PAGAMENTO = @ID_ELENCO) OR (@ID_ELENCO IS NULL))
AND ID_BANDO_PRINCIPALE = @ID_BANDO
ORDER BY ID_ELENCO_PAGAMENTO DESC
