/*************************************************************************************************************************************/
	 
	CREATE PROCEDURE [dbo].[SpGraduatoriaProgetti_sigef_AzioneGPR1]
	(
	@ID_BANDO INT,
	@OPERATORE VARCHAR(16)
	)
AS

DECLARE @ABILITA_FINANZIABILITA_PARZIALE BIT=0
--IF @ID_BANDO IN (327, 416,428,482) SET @ABILITA_FINANZIABILITA_PARZIALE=1

--IMPORTO MASSIMO DEL BANDO TRASVERSALE RISPETTO LE ALTRE MISURE ATTIVATE
DECLARE  @IMPORTO_TOTALE_BANDO DECIMAL(18,2)
SELECT @IMPORTO_TOTALE_BANDO=IMPORTO-IMPORTO*ISNULL(QUOTA_RISERVA,0)/100 FROM VBANDO WHERE ID_BANDO=@ID_BANDO

--SELEZIONO LA LISTA DELLE DOMANDE CON I RELATIVI PUNTEGGI
DECLARE @GRADUATORIA_PROGETTI_T TABLE (ID_PROGETTO INT,PUNTEGGIO DECIMAL(10,6),COSTO_TOTALE DECIMAL(18,2),UTILIZZA_FONDI_RISERVA BIT,
AMMONTARE_FONDI_RISERVA_UTILIZZATO DECIMAL(18,2),ORDINE INT,CONTRIBUTO_TOTALE DECIMAL(18,2),CONTRIBUTO_RIMANENTE DECIMAL(18,2),
FINANZIABILITA CHAR(1),DATA_VALUTAZIONE DATETIME,OPERATORE VARCHAR(16))
INSERT INTO @GRADUATORIA_PROGETTI_T
SELECT ID_PROGETTO,PUNTEGGIO,dbo.calcoloCostoTotaleProgetto(ID_PROGETTO,1,NULL),UTILIZZA_FONDI_RISERVA,AMMONTARE_FONDI_RISERVA_UTILIZZATO,
NULL,NULL,NULL,NULL,NULL,NULL FROM GRADUATORIA_PROGETTI WHERE ID_BANDO=@ID_BANDO

DECLARE @ID_PROGETTO INT,@ORDINE INT,@CONTRIBUTO_PROGETTO DECIMAL(18,2),@FINANZIABILITA CHAR(1), @PUNTEGGIO_FINALE  DECIMAL(10,6)
SET @ORDINE=1
-- IMPOSTO DI DEFAULT LA FINANZIABILITA TOTALE DELLA DOMANDA
SET @FINANZIABILITA='S'
DECLARE PROGETTI CURSOR FOR SELECT ID_PROGETTO , PUNTEGGIO FROM @GRADUATORIA_PROGETTI_T ORDER BY PUNTEGGIO DESC
OPEN PROGETTI
FETCH NEXT FROM PROGETTI INTO @ID_PROGETTO , @PUNTEGGIO_FINALE 
WHILE @@FETCH_STATUS=0 BEGIN
	SET @CONTRIBUTO_PROGETTO=dbo.calcoloContributoTotaleProgetto(@ID_PROGETTO,1,NULL)
	IF @PUNTEGGIO_FINALE = 30 SET @CONTRIBUTO_PROGETTO = 5000
	ELSE IF @PUNTEGGIO_FINALE = 29 SET @CONTRIBUTO_PROGETTO = 4700
	ELSE IF @PUNTEGGIO_FINALE = 28 SET @CONTRIBUTO_PROGETTO = 4400
	ELSE IF @PUNTEGGIO_FINALE = 27 SET @CONTRIBUTO_PROGETTO = 4100
	ELSE IF @PUNTEGGIO_FINALE = 26 SET @CONTRIBUTO_PROGETTO = 3800
	ELSE IF @PUNTEGGIO_FINALE = 25 SET @CONTRIBUTO_PROGETTO = 3500
	ELSE IF @PUNTEGGIO_FINALE = 24 SET @CONTRIBUTO_PROGETTO = 3200
	ELSE IF @PUNTEGGIO_FINALE = 23 SET @CONTRIBUTO_PROGETTO = 2900
	ELSE IF @PUNTEGGIO_FINALE = 22 SET @CONTRIBUTO_PROGETTO = 2600
	ELSE IF @PUNTEGGIO_FINALE = 21 SET @CONTRIBUTO_PROGETTO = 2300
	ELSE IF @PUNTEGGIO_FINALE = 20 SET @CONTRIBUTO_PROGETTO = 2000
	ELSE IF @PUNTEGGIO_FINALE = 19 SET @CONTRIBUTO_PROGETTO = 1700
	ELSE IF @PUNTEGGIO_FINALE = 18 SET @CONTRIBUTO_PROGETTO = 1400
	ELSE IF @PUNTEGGIO_FINALE = 17 SET @CONTRIBUTO_PROGETTO = 1100
	ELSE IF @PUNTEGGIO_FINALE = 16 SET @CONTRIBUTO_PROGETTO = 800
	ELSE IF @PUNTEGGIO_FINALE = 15 SET @CONTRIBUTO_PROGETTO = 500 
	IF @IMPORTO_TOTALE_BANDO<@CONTRIBUTO_PROGETTO BEGIN		
		IF @ABILITA_FINANZIABILITA_PARZIALE=1 AND @IMPORTO_TOTALE_BANDO>0 BEGIN										
			SET @CONTRIBUTO_PROGETTO=@IMPORTO_TOTALE_BANDO
			SET @IMPORTO_TOTALE_BANDO=0
			SET @FINANZIABILITA='P' --FINANZIABILITA PARZIALE
		END
		ELSE BEGIN
			SET @IMPORTO_TOTALE_BANDO=0
			SET @FINANZIABILITA='N' --NON FINANZIABILITA TOTALE
		END
	END
	ELSE SET @IMPORTO_TOTALE_BANDO=@IMPORTO_TOTALE_BANDO-@CONTRIBUTO_PROGETTO
	
	UPDATE @GRADUATORIA_PROGETTI_T SET DATA_VALUTAZIONE=GETDATE(),OPERATORE=@OPERATORE,ORDINE=@ORDINE,
		CONTRIBUTO_TOTALE=@CONTRIBUTO_PROGETTO,CONTRIBUTO_RIMANENTE=@IMPORTO_TOTALE_BANDO,FINANZIABILITA=@FINANZIABILITA
	WHERE ID_PROGETTO=@ID_PROGETTO
	SET @ORDINE=@ORDINE+1
	FETCH NEXT FROM PROGETTI INTO @ID_PROGETTO, @PUNTEGGIO_FINALE 
END	
CLOSE PROGETTI
DEALLOCATE PROGETTI


/*DECLARE @CONTRIBUTO_DA_ASSEGNARE DECIMAL(18,2), @ID_CURSORE_PROGETTI INT,  @PUNTEGGIO_FINALE  DECIMAL(10,6)
SET @CONTRIBUTO_DA_ASSEGNARE = 0
DECLARE CURSORE_PROGETTI CURSOR FOR SELECT ID_PROGETTO FROM GRADUATORIA_PROGETTI WHERE ID_BANDO = @ID_BANDO ORDER BY PUNTEGGIO DESC
OPEN CURSORE_PROGETTI
FETCH NEXT FROM CURSORE_PROGETTI INTO @ID_CURSORE_PROGETTI
WHILE @@FETCH_STATUS=0 BEGIN
	SELECT @PUNTEGGIO_FINALE = PUNTEGGIO FROM GRADUATORIA_PROGETTI WHERE ID_PROGETTO = @ID_CURSORE_PROGETTI 
	IF @PUNTEGGIO_FINALE = 30 SET @CONTRIBUTO_DA_ASSEGNARE = 5000
	ELSE IF @PUNTEGGIO_FINALE = 29 SET @CONTRIBUTO_DA_ASSEGNARE = 4700
	ELSE IF @PUNTEGGIO_FINALE = 28 SET @CONTRIBUTO_DA_ASSEGNARE = 4400
	ELSE IF @PUNTEGGIO_FINALE = 27 SET @CONTRIBUTO_DA_ASSEGNARE = 4100
	ELSE IF @PUNTEGGIO_FINALE = 26 SET @CONTRIBUTO_DA_ASSEGNARE = 3800
	ELSE IF @PUNTEGGIO_FINALE = 25 SET @CONTRIBUTO_DA_ASSEGNARE = 3500
	ELSE IF @PUNTEGGIO_FINALE = 24 SET @CONTRIBUTO_DA_ASSEGNARE = 3200
	ELSE IF @PUNTEGGIO_FINALE = 23 SET @CONTRIBUTO_DA_ASSEGNARE = 2900
	ELSE IF @PUNTEGGIO_FINALE = 22 SET @CONTRIBUTO_DA_ASSEGNARE = 2600
	ELSE IF @PUNTEGGIO_FINALE = 21 SET @CONTRIBUTO_DA_ASSEGNARE = 2300
	ELSE IF @PUNTEGGIO_FINALE = 20 SET @CONTRIBUTO_DA_ASSEGNARE = 2000
	ELSE IF @PUNTEGGIO_FINALE = 19 SET @CONTRIBUTO_DA_ASSEGNARE = 1700
	ELSE IF @PUNTEGGIO_FINALE = 18 SET @CONTRIBUTO_DA_ASSEGNARE = 1400
	ELSE IF @PUNTEGGIO_FINALE = 17 SET @CONTRIBUTO_DA_ASSEGNARE = 1100
	ELSE IF @PUNTEGGIO_FINALE = 16 SET @CONTRIBUTO_DA_ASSEGNARE = 800
	ELSE IF @PUNTEGGIO_FINALE = 15 SET @CONTRIBUTO_DA_ASSEGNARE = 500
	UPDATE GRADUATORIA_PROGETTI SET CONTRIBUTO_TOTALE = @CONTRIBUTO_DA_ASSEGNARE WHERE ID_PROGETTO = @ID_CURSORE_PROGETTI
	
END
CLOSE CURSORE_PROGETTI
DEALLOCATE CURSORE_PROGETTI*/


SELECT G.*,ID_BANDO,SEGNATURA_ALLEGATI,ID_PROG_INTEGRATO,FLAG_PREADESIONE,FLAG_DEFINITIVO,ID_FASCICOLO,ID_IMPRESA,
	PROVINCIA_DI_PRESENTAZIONE,SELEZIONATA_X_REVISIONE 
FROM @GRADUATORIA_PROGETTI_T G INNER JOIN PROGETTO P ON G.ID_PROGETTO=P.ID_PROGETTO
ORDER BY ORDINE

