


CREATE PROCEDURE [dbo].[SpOrdinamentoGraduatoriaIndividuale]
(
	@ID_BANDO INT,
	@CF_OPERATORE VARCHAR(16)
)
AS
	--DECLARE @ID_BANDO INT=244,@CF_OPERATORE VARCHAR(16)
	
	-- RECUPERO IL BUDGET DEL BANDO TOTALE O RIMANENTE E L'ULTIMO ORDINE INSERITO
	DECLARE @LAST_ORDINE INT
	SELECT @LAST_ORDINE=MAX(ORDINE) FROM GRADUATORIA_PROGETTI WHERE ID_BANDO=@ID_BANDO
	IF @LAST_ORDINE IS NULL SET @LAST_ORDINE=0

	--SELEZIONO LA LISTA DELLE DOMANDE CON I RELATIVI PUNTEGGI
	DECLARE PP CURSOR FOR
		SELECT G.ID_PROGETTO FROM GRADUATORIA_PROGETTI G INNER JOIN PROGETTO P ON G.ID_PROGETTO=P.ID_PROGETTO
		INNER JOIN PROGETTO_STORICO S ON P.ID_PROGETTO=S.ID_PROGETTO AND S.COD_STATO='L'
		WHERE G.ID_BANDO=@ID_BANDO AND ORDINE IS NULL ORDER BY S.DATA
	DECLARE @ID_PROGETTO INT,@CONTRIBUTO_PROGETTO DECIMAL(18,2),@COUNTER INT=0
	OPEN PP	
	FETCH NEXT FROM PP INTO @ID_PROGETTO
	WHILE @@FETCH_STATUS=0 BEGIN
		SET @LAST_ORDINE=@LAST_ORDINE+1		
		UPDATE GRADUATORIA_PROGETTI SET DATA_VALUTAZIONE=GETDATE(),OPERATORE=@CF_OPERATORE,ORDINE=@LAST_ORDINE,
			COSTO_TOTALE=dbo.calcoloCostoTotaleProgetto(ID_PROGETTO,1,NULL),
			CONTRIBUTO_TOTALE=dbo.calcoloContributoTotaleProgetto(@ID_PROGETTO,1,NULL)
		--SELECT ID_PROGETTO,dbo.calcoloCostoTotaleProgetto(ID_PROGETTO,1,NULL),@CONTRIBUTO_PROGETTO,@BUDGET_BANDO,@LAST_ORDINE 
		FROM GRADUATORIA_PROGETTI WHERE ID_BANDO=@ID_BANDO AND ID_PROGETTO=@ID_PROGETTO
		SET @COUNTER=@COUNTER+1
		FETCH NEXT FROM PP INTO @ID_PROGETTO
	END	
	CLOSE PP
	DEALLOCATE PP
	SELECT @COUNTER


