CREATE PROCEDURE [dbo].[SpPsrControlloAziendaAbilitataXPresentazioneDomanda] 
(
	@ID_BANDO INT,
	@ID_IMPRESA INT,
	@ID_UTENTE INT
)
AS
	DECLARE @COD_RISULTATO INT,@MESSAGGIO VARCHAR(255)	
	SET @COD_RISULTATO=0 --0: ok, altrimenti messaggio di errore
	-- MESSAGGIO DI ERRORE PREIMPOSTATO
	SET @MESSAGGIO='L`impresa selezionata non è abilitata a presentare domanda per questo bando.'
	
	DECLARE @CUAA VARCHAR(16),@PIVA CHAR(11),@ATTIVA BIT,@DATA_SCADENZA DATETIME,@MULTIPROGETTO BIT,@PROGETTI_PRESENTATI INT,@FIRMA_RICHIESTA BIT
	SELECT @CUAA=CUAA,@PIVA=CODICE_FISCALE,@ATTIVA=ATTIVA FROM VIMPRESA WHERE ID_IMPRESA=@ID_IMPRESA
	SELECT @DATA_SCADENZA=DATA_SCADENZA,@MULTIPROGETTO=MULTIPROGETTO,@FIRMA_RICHIESTA=FIRMA_RICHIESTA FROM vBANDO WHERE ID_BANDO=@ID_BANDO
	
	IF @CUAA IS NULL BEGIN
		SET @COD_RISULTATO=1
		SET @MESSAGGIO='Nessuna impresa valida selezionata. Impossibile continuare.'
	END
	ELSE IF @ATTIVA=0 BEGIN
		SET @COD_RISULTATO=1
		SET @MESSAGGIO='L`impresa selezionata non è più in attività. Impossibile continuare.'
	END
	ELSE IF @DATA_SCADENZA<GETDATE() BEGIN
		SET @COD_RISULTATO=1
		SET @MESSAGGIO='Sono scaduti i termini per la presentazione della domanda di aiuto.'
	END
	ELSE IF @FIRMA_RICHIESTA=0 AND (SELECT COUNT(*) FROM vPERSONE_X_IMPRESE P INNER JOIN vUTENTI U ON P.ID_PERSONA=U.ID_PERSONA_FISICA
		WHERE ID_IMPRESA=@ID_IMPRESA AND P.ATTIVO=1 AND P.POTERE_DI_FIRMA=1 AND U.ID_UTENTE=@ID_UTENTE)=0 BEGIN
		SET @COD_RISULTATO=1
		SET @MESSAGGIO='La tipologia di bando selezionato non prevede l`inserimento di domande da parte di un operatore diverso dal rappresentante legale dell`azienda o da chiunque abbia potere di firma all`interno della compagine aziendale.'
	END
	ELSE BEGIN
		-- Commentato per poter far inserire a piu consulenti domande per lo stesso bando	
		IF @MULTIPROGETTO !=1  BEGIN 
		SELECT @PROGETTI_PRESENTATI=COUNT(DISTINCT P.ID_PROGETTO) 
			 FROM vPROGETTO P WHERE P.ID_IMPRESA=@ID_IMPRESA AND ID_BANDO=@ID_BANDO 
				AND ISNULL(ID_PROG_INTEGRATO,P.ID_PROGETTO)=P.ID_PROGETTO AND FLAG_PREADESIONE=0
				AND COD_STATO NOT IN ('Q','B') -- X BANDI A SPORTELLO L'AZIENDA PUO' RIPRESENTARE DOMANDA IN CASO DI ISTRUTTORIA NEGATIVA
    		 IF @PROGETTI_PRESENTATI>0 BEGIN 		
				SET @COD_RISULTATO=1
				SET @MESSAGGIO='L`impresa ha già una domanda per il bando selezionato. Impossibile continuare.' 
			 END
		END
		
		--IF @MULTIPROGETTO=1  BEGIN 	
		--	-- RECUPERO L'OPERATORE CORRENTE
		--	DECLARE @CF_UTENTE_OPERATORE_CORRENTE CHAR(16),@COD_ENTE_OPERATORE_CORRENTE VARCHAR(10) 	
		--	SELECT @CF_UTENTE_OPERATORE_CORRENTE=CF_UTENTE,@COD_ENTE_OPERATORE_CORRENTE=U.COD_ENTE  
		--	FROM vUTENTI U WHERE ID_UTENTE=@ID_UTENTE	
		--	 -- controllo su univocita di operatore abilitato su domanda PER IL CUAA E IL BANDO	
		--	SELECT @PROGETTI_PRESENTATI=COUNT(DISTINCT P.ID_PROGETTO) 
		--	FROM PROGETTO P INNER JOIN PROGETTO_STORICO PS ON P.ID_PROGETTO=PS.ID_PROGETTO AND COD_STATO in ('L','P')
		--	INNER JOIN vUTENTI V ON PS.OPERATORE=V.ID_UTENTE 
		--	WHERE P.ID_IMPRESA=@ID_IMPRESA AND ID_BANDO=@ID_BANDO AND ISNULL(ID_PROG_INTEGRATO,P.ID_PROGETTO)=P.ID_PROGETTO 
		--		AND FLAG_PREADESIONE=0 AND ((@COD_ENTE_OPERATORE_CORRENTE IS NOT NULL AND ISNULL(V.COD_ENTE,'X')!= @COD_ENTE_OPERATORE_CORRENTE)
		--			OR(@COD_ENTE_OPERATORE_CORRENTE IS NULL AND V.CF_UTENTE != @CF_UTENTE_OPERATORE_CORRENTE))
    	
	 --   	IF @PROGETTI_PRESENTATI>0 BEGIN 
		--		SET @COD_RISULTATO=1
		--		SET @MESSAGGIO='Sono presenti domande di altri operatori per questo CUAA.' 
		--	END
		--END
		--ELSE BEGIN
		--	 SELECT @PROGETTI_PRESENTATI=COUNT(DISTINCT P.ID_PROGETTO) 
		--	 FROM vPROGETTO P WHERE P.ID_IMPRESA=@ID_IMPRESA AND ID_BANDO=@ID_BANDO 
		--		AND ISNULL(ID_PROG_INTEGRATO,P.ID_PROGETTO)=P.ID_PROGETTO AND FLAG_PREADESIONE=0
		--		AND COD_STATO NOT IN ('Q','B') -- X BANDI A SPORTELLO L'AZIENDA PUO' RIPRESENTARE DOMANDA IN CASO DI ISTRUTTORIA NEGATIVA
  --  		 IF @PROGETTI_PRESENTATI>0 BEGIN 		
		--		SET @COD_RISULTATO=1
		--		SET @MESSAGGIO='L`impresa ha già una domanda per il bando selezionato. Impossibile continuare.' 
		--	 END
		--END
	
	END
	-- CONDIZIONI SPECIFICHE PER BANDO
	--IF @COD_RISULTATO=0 BEGIN
	--	IF @ID_BANDO=186 BEGIN
	--			SET @COD_RISULTATO=1
	--			DECLARE @C INT
	--			SELECT @C = COUNT(*) FROM AMMESSI_BANDO_LEGGE_56 WHERE CUAA=@CUAA OR PIVA = @PIVA
	--			IF(@C>0)SET @COD_RISULTATO=0
	--			END
	--	ELSE IF @ID_BANDO=250 BEGIN
	--			SET @COD_RISULTATO=1
	--			IF(@CUAA='01717810442' OR @CUAA='01584420424')SET @COD_RISULTATO=0
	--			END
	--	ELSE IF @ID_BANDO=370 BEGIN
	--			SET @COD_RISULTATO=1
	--			IF(@CUAA='01058860436' OR @CUAA='01058860436')SET @COD_RISULTATO=0
	--	END
			 			 
	--END
	SELECT @COD_RISULTATO AS COD_RISULTATO,@MESSAGGIO AS MESSAGGIO
