
CREATE PROCEDURE [dbo].[SpPsrGetDichiarazioniModelloDomanda]
(
	@ID_MODELLO_DOMANDA INT,
	@MISURA VARCHAR(50)=NULL,
	@DESCRIZIONE VARCHAR(250)=NULL
)
AS
IF(@MISURA IS NOT NULL OR @DESCRIZIONE IS NOT NULL)
	SELECT Q1.*,ID_DOMANDA,ORDINE,OBBLIGATORIO 
	FROM CATALOGO_DICHIARAZIONI AS Q1 
	INNER JOIN DICHIARAZIONI_X_DOMANDA AS Q2 ON Q1.ID_DICHIARAZIONE=Q2.ID_DICHIARAZIONE AND Q2.ID_DOMANDA=@ID_MODELLO_DOMANDA
	UNION 
	SELECT *,NULL AS ID_DOMANDA,NULL AS ORDINE,NULL AS OBBLIGATORIO 
	FROM CATALOGO_DICHIARAZIONI 
	WHERE ((@MISURA IS NULL OR MISURA LIKE  '%' + @MISURA+ '%') AND 
	(@DESCRIZIONE IS NULL OR DESCRIZIONE LIKE  '%' + @DESCRIZIONE + '%'))
	AND ID_DICHIARAZIONE NOT IN (SELECT ID_DICHIARAZIONE FROM DICHIARAZIONI_X_DOMANDA WHERE ID_DOMANDA=@ID_MODELLO_DOMANDA)
	ORDER BY ID_DOMANDA DESC,ORDINE,MISURA,Q1.ID_DICHIARAZIONE,DESCRIZIONE
	
ELSE
    SELECT Q1.*,ID_DOMANDA,ORDINE,OBBLIGATORIO 
	FROM CATALOGO_DICHIARAZIONI AS Q1 
	LEFT OUTER JOIN DICHIARAZIONI_X_DOMANDA AS Q2 ON Q1.ID_DICHIARAZIONE=Q2.ID_DICHIARAZIONE AND Q2.ID_DOMANDA=@ID_MODELLO_DOMANDA 
	ORDER BY ID_DOMANDA DESC,ORDINE,MISURA,Q1.ID_DICHIARAZIONE,DESCRIZIONE