
CREATE PROCEDURE [dbo].[SpPsrRicercaGeneraleDomandaDiAiutoNonProvvisorie]
(
	@ID_PROGETTO INT=NULL,
	@COD_STATO CHAR(1)=NULL,
	@ID_BANDO INT=NULL,
	--@PAROLE_CHIAVE_BANDO VARCHAR(50)=NULL,
	@CUAA VARCHAR(16)=NULL,
	@RAGIONE_SOCIALE VARCHAR(50)=NULL,
	@PROVINCIA CHAR(2)=NULL,
	@ID_PROGRAMMAZIONE INT=NULL,
	@COD_ENTE_BANDO VARCHAR(10)=NULL,
	@ID_ISTRUTTORE INT=NULL,
	@ID_RESP_PROVINCIALE CHAR(16)=NULL,
	@DPAGAMENTO BIT,
	@VARIANTI BIT,
	@AT BIT,
	@IST_CONCLUSA BIT,
	@IST_INCORSO BIT,
	@ANNULLATI BIT
)
AS
	--DECLARE @ID_PROGETTO INT,@COD_STATO CHAR(1),@ID_BANDO INT,@PAROLE_CHIAVE_BANDO VARCHAR(50),@CUAA VARCHAR(16),
	--	@RAGIONE_SOCIALE VARCHAR(50),@PROVINCIA CHAR(2),@ID_PSR INT,@COD_OBIETTIVO INT,@COD_ASSE INT,@COD_MISURA INT,
	--	@COD_ENTE_BANDO VARCHAR(10),@ID_ISTRUTTORE INT,@CF_RESP_PROVINCIALE CHAR(16),@DPAGAMENTO BIT=0,@VARIANTI BIT=0,
	--	@AT BIT=0,@IST_CONCLUSA BIT=0,@IST_INCORSO BIT=0,@ANNULLATI BIT=0
	

	SELECT *,0/*ISNULL(DBO.calcoloCostoTotaleProgetto(ID_PROGETTO,CASE WHEN COD_STATO='P' THEN 0 ELSE 1 END,ID_VARIANTE),0)*/ AS COSTO_PROGETTO,
		0/*ISNULL(DBO.calcoloContributoTotaleProgetto(ID_PROGETTO,CASE WHEN COD_STATO='P' THEN 0 ELSE 1 END,ID_VARIANTE),0)
		+ISNULL(DBO.calcoloPremioContoCapitale(ID_PROGETTO,CASE WHEN COD_STATO='P' THEN 0 ELSE 1 END,ID_VARIANTE),0)*/ AS CONTRIBUTO_PROGETTO
	FROM (
		SELECT DISTINCT P.ID_PROGETTO,P.ID_BANDO,S.COD_STATO,SP.DESCRIZIONE AS STATO,SP.COD_FASE,F.ORDINE AS ORDINE_FASE,P.ID_IMPRESA,
			SL.DATA AS DATA_PRESENTAZIONE,C.SIGLA AS PROVINCIA_SEDELEGALE,I.CODICE_FISCALE AS PIVA,IST.RAGIONE_SOCIALE,
			Z.DESCRIZIONE+' '+PR.CODICE AS PROGRAMMAZIONE/*,V.ID_VARIANTE*/,P.PROVINCIA_DI_PRESENTAZIONE AS PPV
		FROM PROGETTO P INNER JOIN PROGETTO_STORICO S ON P.ID_STORICO_ULTIMO=S.ID
		-- RICERCA PER STATO PROGETTO
		INNER JOIN STATO_PROGETTO SP ON S.COD_STATO=SP.COD_STATO AND SP.COD_STATO != 'P'									
		LEFT JOIN FASI_PROCEDURALI F ON SP.COD_FASE=F.COD_FASE
		-- DATA DI PRESENTAZIONE
		LEFT JOIN PROGETTO_STORICO SL ON P.ID_PROGETTO=SL.ID_PROGETTO AND SL.COD_STATO='L'			
		-- RICERCA PER ID_BANDO, PAROLE CHIAVE, ENTE
		INNER JOIN BANDO B ON P.ID_BANDO=B.ID_BANDO													
		INNER JOIN ENTE E ON B.COD_ENTE=E.COD_ENTE
		INNER JOIN zPROGRAMMAZIONE PR ON B.ID_PROGRAMMAZIONE=PR.ID
		INNER JOIN zPSR_ALBERO Z ON PR.COD_TIPO=Z.CODICE and Z.CODICE LIKE 'POR20142020L%'
		LEFT JOIN COLLABORATORI_X_BANDO CB ON P.ID_PROGETTO=CB.ID_PROGETTO AND CB.ATTIVO=1
		-- RESPONSABILI_X_BANDO PROVINCIALI
		LEFT JOIN BANDO_RESPONSABILI BR ON B.ID_BANDO=BR.ID_BANDO AND BR.ATTIVO=1 AND P.PROVINCIA_DI_PRESENTAZIONE=BR.PROVINCIA
		INNER JOIN IMPRESA I ON P.ID_IMPRESA=I.ID_IMPRESA
		-- RICERCA CUAA,P.IVA, RAG SOCIALE
		INNER JOIN IMPRESA_STORICO IST ON I.ID_STORICO_ULTIMO=IST.ID_STORICO_IMPRESA				
		-- PROVINCIA SEDE LEGALE
		INNER JOIN INDIRIZZARIO N ON I.ID_SEDELEGALE_ULTIMO=N.ID_INDIRIZZARIO
		INNER JOIN INDIRIZZO D ON N.ID_INDIRIZZO=D.ID_INDIRIZZO INNER JOIN COMUNI C ON D.ID_COMUNE=C.ID_COMUNE
		-- COMMENTATA PER ORA INUTILE
		--LEFT JOIN (SELECT MAX(ID_VARIANTE) AS ID_VARIANTE,ID_PROGETTO FROM VARIANTI WHERE APPROVATA=1 GROUP BY ID_PROGETTO) V 
		--	ON ISNULL(P.ID_PROG_INTEGRATO,P.ID_PROGETTO)=V.ID_PROGETTO	
		
		-- RICERCA PER DOMANDE DI PAGAMENTO
		LEFT JOIN (
			SELECT ID_PROGETTO,SUM(CASE WHEN ANNULLATA=1 THEN 1 ELSE 0 END) AS NR_DP_ANNULLATE,
			SUM(CASE WHEN APPROVATA IS NULL AND ANNULLATA=0 THEN 1 ELSE 0 END) AS NR_DP_IST_INCORSO,
			SUM(CASE WHEN APPROVATA IS NOT NULL AND ANNULLATA=0 THEN 1 ELSE 0 END) AS NR_DP_IST_CONCLUSA
			FROM DOMANDA_DI_PAGAMENTO WHERE SEGNATURA IS NOT NULL GROUP BY ID_PROGETTO
		) DP ON P.ID_PROGETTO=DP.ID_PROGETTO
		-- RICERCA PER VARIANTI/A.T.
		LEFT JOIN (
			SELECT ID_PROGETTO,SUM(CASE WHEN COD_TIPO='VA' THEN 1 ELSE 0 END) AS NR_VA,
			SUM(CASE WHEN COD_TIPO='AT' THEN 1 ELSE 0 END) AS NR_AT,
			SUM(CASE WHEN COD_TIPO='VA' AND APPROVATA IS NULL AND ANNULLATA=0 THEN 1 ELSE 0 END) AS NR_VA_IST_INCORSO,
			SUM(CASE WHEN COD_TIPO='AT' AND APPROVATA IS NULL AND ANNULLATA=0 THEN 1 ELSE 0 END) AS NR_AT_IST_INCORSO,
			SUM(CASE WHEN COD_TIPO='VA' AND APPROVATA IS NOT NULL AND ANNULLATA=0 THEN 1 ELSE 0 END) AS NR_VA_IST_CONCLUSA,
			SUM(CASE WHEN COD_TIPO='AT' AND APPROVATA IS NOT NULL AND ANNULLATA=0 THEN 1 ELSE 0 END) AS NR_AT_IST_CONCLUSA,
			SUM(CASE WHEN COD_TIPO='VA' AND ANNULLATA=1 THEN 1 ELSE 0 END) AS NR_VA_ANNULLATE,
			SUM(CASE WHEN COD_TIPO='AT' AND ANNULLATA=1 THEN 1 ELSE 0 END) AS NR_AT_ANNULLATE
			FROM VARIANTI WHERE SEGNATURA IS NOT NULL GROUP BY ID_PROGETTO
		) VA ON P.ID_PROGETTO=VA.ID_PROGETTO
		
		WHERE ISNULL(ID_PROG_INTEGRATO,P.ID_PROGETTO)=P.ID_PROGETTO AND (@COD_STATO IS NULL OR S.COD_STATO=@COD_STATO)
			AND (@ID_PROGETTO IS NULL OR P.ID_PROGETTO=@ID_PROGETTO) AND (@ID_BANDO IS NULL OR P.ID_BANDO=@ID_BANDO) 
			--AND (@PAROLE_CHIAVE_BANDO IS NULL OR B.PAROLE_CHIAVE LIKE '%'+@PAROLE_CHIAVE_BANDO+'%')
			AND (@ID_ISTRUTTORE IS NULL OR CB.ID_UTENTE=@ID_ISTRUTTORE) AND (@CUAA IS NULL OR I.CUAA=@CUAA OR I.CODICE_FISCALE=@CUAA)
			AND (@RAGIONE_SOCIALE IS NULL OR IST.RAGIONE_SOCIALE LIKE '%'+@RAGIONE_SOCIALE+'%')
			AND (@PROVINCIA IS NULL OR C.SIGLA=@PROVINCIA) AND (@COD_ENTE_BANDO IS NULL OR B.COD_ENTE=@COD_ENTE_BANDO)
			AND (@ID_PROGRAMMAZIONE IS NULL OR B.ID_PROGRAMMAZIONE=@ID_PROGRAMMAZIONE)
			AND (@ID_RESP_PROVINCIALE IS NULL OR BR.ID_UTENTE=@ID_RESP_PROVINCIALE)
			AND (@DPAGAMENTO=0 OR (@DPAGAMENTO=1 AND DP.ID_PROGETTO=P.ID_PROGETTO 
				AND (@ANNULLATI=0 OR (@ANNULLATI=1 AND DP.NR_DP_ANNULLATE>0))
				AND (@IST_CONCLUSA=0 OR (@IST_CONCLUSA=1 AND DP.NR_DP_IST_CONCLUSA>0))
				AND (@IST_INCORSO=0 OR (@IST_INCORSO=1 AND DP.NR_DP_IST_INCORSO>0))))
			AND ((@VARIANTI=0 AND @AT=0) OR (VA.ID_PROGETTO=P.ID_PROGETTO
				AND (@VARIANTI=0 OR (@VARIANTI=1 AND VA.NR_VA>0
					AND (@ANNULLATI=0 OR (@ANNULLATI=1 AND VA.NR_VA_ANNULLATE>0))
					AND (@IST_CONCLUSA=0 OR (@IST_CONCLUSA=1 AND VA.NR_VA_IST_CONCLUSA>0))
					AND (@IST_INCORSO=0 OR (@IST_INCORSO=1 AND VA.NR_VA_IST_INCORSO>0))))
				AND (@AT=0 OR (@AT=1 AND VA.NR_AT>0
					AND (@ANNULLATI=0 OR (@ANNULLATI=1 AND VA.NR_AT_ANNULLATE>0))
					AND (@IST_CONCLUSA=0 OR (@IST_CONCLUSA=1 AND VA.NR_AT_IST_CONCLUSA>0))
					AND (@IST_INCORSO=0 OR (@IST_INCORSO=1 AND VA.NR_AT_IST_INCORSO>0))))))
					
	) Q1 ORDER BY ID_PROGETTO DESC
	