CREATE PROCEDURE [dbo].[SpPsrCalcoloMassimaliContributoInvestimentoFondoPerduto]
(	
	@ID_PROGETTO_CORRELATO INT,
	@ID_PROGRAMMAZIONE INT,	
	@ID_VARIANTE INT=NULL,	
	@FASE VARCHAR(10), -- PUO' ASSUMERE I SEGUENTI VALORI: PDOMANDA,IDOMANDA,PVARIANTE,IVARIANTE
	@ID_INVESTIMENTO INT=NULL,
	@CONTRIBUTO_CALCOLATO DECIMAL(18,5)
)
AS
	/*
	DECLARE @ID_PROGETTO_CORRELATO INT,@ID_PROGRAMMAZIONE INT,@ID_INVESTIMENTO INT,@ID_VARIANTE INT,@FASE VARCHAR(10),
	@CONTRIBUTO_CALCOLATO DECIMAL(18,5)
	SET @ID_PROGETTO_CORRELATO=424
	SET @FASE='PDOMANDA'
	--SET @ID_INVESTIMENTO=1237
	SET @ID_PROGRAMMAZIONE=54
	SET @CONTRIBUTO_CALCOLATO=20*/

	-- SELEZIONO IL PIANO INVESTIMENTI RELATIVO ALLA FASE IN QUESTIONE
	DECLARE @PIANO_INVESTIMENTI TABLE (ID_INVESTIMENTO INT,ID_PROGETTO INT,ID_PROGRAMMAZIONE INT,COD_TIPO_INVESTIMENTO INT,COD_STP VARCHAR(10),
		COSTO_INVESTIMENTO DECIMAL(15, 2),SPESE_GENERALI DECIMAL(15, 2),CONTRIBUTO_RICHIESTO DECIMAL(15, 2),
		QUOTA_CONTRIBUTO_RICHIESTO DECIMAL(10, 2),TASSO_ABBUONO DECIMAL(10, 2),ID_SETTORE_PRODUTTIVO INT,ID_PRIORITA_SETTORIALE INT,
		ID_CODIFICA_INVESTIMENTO INT,ID_DETTAGLIO_INVESTIMENTO INT,AMMESSO BIT,ID_INVESTIMENTO_ORIGINALE INT,ID_VARIANTE INT,COD_VARIAZIONE CHAR(1),
		QUOTA_SPESE_GENERALI DECIMAL(15,2))

	IF @FASE='PDOMANDA' BEGIN
		INSERT INTO @PIANO_INVESTIMENTI
		SELECT ID_INVESTIMENTO,ID_PROGETTO,ID_PROGRAMMAZIONE,COD_TIPO_INVESTIMENTO,COD_STP,COSTO_INVESTIMENTO,SPESE_GENERALI,
			CONTRIBUTO_RICHIESTO,QUOTA_CONTRIBUTO_RICHIESTO,TASSO_ABBUONO,ID_SETTORE_PRODUTTIVO,ID_PRIORITA_SETTORIALE,
			I.ID_CODIFICA_INVESTIMENTO,I.ID_DETTAGLIO_INVESTIMENTO,AMMESSO,ID_INVESTIMENTO_ORIGINALE,ID_VARIANTE,
			COD_VARIAZIONE,QUOTA_SPESE_GENERALI 
		FROM PIANO_INVESTIMENTI I LEFT JOIN DETTAGLIO_INVESTIMENTI D ON I.ID_DETTAGLIO_INVESTIMENTO=D.ID_DETTAGLIO_INVESTIMENTO
		WHERE ID_PROGETTO=@ID_PROGETTO_CORRELATO AND AMMESSO IS NULL AND ID_VARIANTE IS NULL AND ID_INVESTIMENTO_ORIGINALE IS NULL 
	END
	ELSE IF @FASE='IDOMANDA' BEGIN
		INSERT INTO @PIANO_INVESTIMENTI
		SELECT ID_INVESTIMENTO,ID_PROGETTO,ID_PROGRAMMAZIONE,COD_TIPO_INVESTIMENTO,COD_STP,COSTO_INVESTIMENTO,SPESE_GENERALI,
			CONTRIBUTO_RICHIESTO,QUOTA_CONTRIBUTO_RICHIESTO,TASSO_ABBUONO,ID_SETTORE_PRODUTTIVO,ID_PRIORITA_SETTORIALE,
			I.ID_CODIFICA_INVESTIMENTO,I.ID_DETTAGLIO_INVESTIMENTO,AMMESSO,ID_INVESTIMENTO_ORIGINALE,ID_VARIANTE,
			COD_VARIAZIONE,QUOTA_SPESE_GENERALI 
		FROM PIANO_INVESTIMENTI I LEFT JOIN DETTAGLIO_INVESTIMENTI D ON I.ID_DETTAGLIO_INVESTIMENTO=D.ID_DETTAGLIO_INVESTIMENTO
		WHERE ID_PROGETTO=@ID_PROGETTO_CORRELATO AND ID_VARIANTE IS NULL AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND AMMESSO IS NOT NULL
	END
	ELSE IF @FASE IN ('PVARIANTE','IVARIANTE') BEGIN
		INSERT INTO @PIANO_INVESTIMENTI
		SELECT ID_INVESTIMENTO,ID_PROGETTO,ID_PROGRAMMAZIONE,COD_TIPO_INVESTIMENTO,COD_STP,COSTO_INVESTIMENTO,SPESE_GENERALI,
			CONTRIBUTO_RICHIESTO,QUOTA_CONTRIBUTO_RICHIESTO,TASSO_ABBUONO,ID_SETTORE_PRODUTTIVO,ID_PRIORITA_SETTORIALE,
			I.ID_CODIFICA_INVESTIMENTO,I.ID_DETTAGLIO_INVESTIMENTO,AMMESSO,ID_INVESTIMENTO_ORIGINALE,ID_VARIANTE,
			COD_VARIAZIONE,QUOTA_SPESE_GENERALI 
		FROM PIANO_INVESTIMENTI I LEFT JOIN DETTAGLIO_INVESTIMENTI D ON I.ID_DETTAGLIO_INVESTIMENTO=D.ID_DETTAGLIO_INVESTIMENTO
		WHERE ID_PROGETTO=@ID_PROGETTO_CORRELATO AND ID_VARIANTE=@ID_VARIANTE AND ISNULL(COD_VARIAZIONE,'X')!='A'
	END
	--
	DECLARE @TOTALE_CONTRIBUTO_INVESTIMENTI DECIMAL(18,5),@IMPORTO_MAX_INTERVENTO DECIMAL(18,2),@ID_DISPOSIZIONI_ATTUATIVE INT,
		@CONTRIBUTO_MAX_DOMANDA DECIMAL(18,2),@CONTRIBUTO_INVESTIMENTO_ORIGINALE DECIMAL(18,2),@CONTRIBUTO_RIMANENTE_MISURA DECIMAL(18,2),
	/*OUTPUT:*/@CONTRIBUTO_TRONCATO DECIMAL(18,5),@COD_TRONCAMENTO CHAR(1)
	SET @CONTRIBUTO_TRONCATO=@CONTRIBUTO_CALCOLATO
	SELECT @ID_DISPOSIZIONI_ATTUATIVE=ID_BANDO FROM PROGETTO WHERE ID_PROGETTO=@ID_PROGETTO_CORRELATO

	IF @FASE IN ('PVARIANTE','IVARIANTE') BEGIN 
		DECLARE @COD_TIPO_VARIANTE CHAR(2)
		SELECT @COD_TIPO_VARIANTE=COD_TIPO FROM VARIANTI WHERE ID_VARIANTE=@ID_VARIANTE
		-- TETTO SULL'INVESTIMENTO ORIGINALE DELLA VARIANTE/AT PRECEDENTE A QUESTA (SOLO X AT)
		IF @COD_TIPO_VARIANTE IN ('AT','VI') BEGIN			
			SELECT @CONTRIBUTO_INVESTIMENTO_ORIGINALE=I.CONTRIBUTO_RICHIESTO FROM PIANO_INVESTIMENTI I 
			INNER JOIN @PIANO_INVESTIMENTI I2 ON I.ID_INVESTIMENTO=I2.ID_INVESTIMENTO_ORIGINALE
			WHERE I2.ID_INVESTIMENTO=@ID_INVESTIMENTO
			
			IF @CONTRIBUTO_TRONCATO>@CONTRIBUTO_INVESTIMENTO_ORIGINALE BEGIN
				SET @CONTRIBUTO_TRONCATO=@CONTRIBUTO_INVESTIMENTO_ORIGINALE
				SET @COD_TRONCAMENTO='P'	
			END
		END
		-- CONTROLLO SUL RICHIESTO, PRIMA DELLE MODIFICHE DI ISTRUTTORIA, EVITA CHE L'AMMESSO PER SINGOLO INVESTIMENTO SIA SUPERIORE
		ELSE IF @FASE='IVARIANTE' AND @COD_TIPO_VARIANTE IN ('AT','VA') BEGIN
			DECLARE @CONTRIBUTO_IN_PRESENTAZIONE DECIMAL(15,2)
			SELECT @CONTRIBUTO_IN_PRESENTAZIONE=dbo.controlloContributoInvestimentoRichiestoVariante(@ID_INVESTIMENTO)
			IF @CONTRIBUTO_TRONCATO>@CONTRIBUTO_IN_PRESENTAZIONE BEGIN
				SET @CONTRIBUTO_TRONCATO=@CONTRIBUTO_IN_PRESENTAZIONE
				SET @COD_TRONCAMENTO='O'	
			END
		END
		-- MASSIMALI X MISURA DA AMMISSIBILITA
		IF @COD_TIPO_VARIANTE!='AR' BEGIN
			SELECT @CONTRIBUTO_RIMANENTE_MISURA=dbo.calcoloContributoRimanenteFinanziabileProgetto(@ID_PROGETTO_CORRELATO,
				@ID_VARIANTE,@ID_INVESTIMENTO)
			IF @CONTRIBUTO_TRONCATO>@CONTRIBUTO_RIMANENTE_MISURA BEGIN
				SET @CONTRIBUTO_TRONCATO=@CONTRIBUTO_RIMANENTE_MISURA
				SET @COD_TRONCAMENTO='M'
			END
		END
	END
	-- CONTROLLO SUL RICHIESTO (SOLO PER ISTRUTTORIA AMMISSIBILITA DOMANDA DI AIUTO)
	IF @FASE='IDOMANDA' BEGIN
		SELECT @CONTRIBUTO_INVESTIMENTO_ORIGINALE=SUM(CASE WHEN ORIGINALE=1 THEN CONTRIBUTO_RICHIESTO ELSE -(CONTRIBUTO_RICHIESTO) END) 
		FROM (
			SELECT I2.ID_INVESTIMENTO,I2.CONTRIBUTO_RICHIESTO,1 AS ORIGINALE FROM @PIANO_INVESTIMENTI I 
			INNER JOIN PIANO_INVESTIMENTI I2 ON I.ID_INVESTIMENTO_ORIGINALE=I2.ID_INVESTIMENTO WHERE I.ID_INVESTIMENTO=@ID_INVESTIMENTO
			UNION ALL
			-- SOTTRAGGO IL CONTRIBUTO AMMESSO NEGLI ALTRI EVENTUALI DUPLICATI
			SELECT I2.ID_INVESTIMENTO,I2.CONTRIBUTO_RICHIESTO,0 FROM @PIANO_INVESTIMENTI I 
			INNER JOIN @PIANO_INVESTIMENTI I2 ON I.ID_INVESTIMENTO_ORIGINALE=I2.ID_INVESTIMENTO_ORIGINALE 
			WHERE I.ID_INVESTIMENTO=@ID_INVESTIMENTO AND I.ID_INVESTIMENTO!=I2.ID_INVESTIMENTO) Q1	
		-- CONTROLLO RIMOSSO PER RILASSAMENTO DURANTE ISTRUTTORIA AMMISSIBILITA 
		DECLARE @STATO_PROG VARCHAR(35)
		SELECT @STATO_PROG=ST.DESCRIZIONE
		FROM PROGETTO PROG 
		INNER JOIN PROGETTO_STORICO STO ON STO.ID = PROG.ID_STORICO_ULTIMO
		INNER JOIN STATO_PROGETTO ST ON ST.COD_STATO = STO.COD_STATO
		WHERE PROG.ID_PROGETTO = @ID_PROGETTO_CORRELATO;
		IF @CONTRIBUTO_TRONCATO>@CONTRIBUTO_INVESTIMENTO_ORIGINALE 
			AND @STATO_PROG != 'Ricevibile' AND @STATO_PROG != 'Acquisito' BEGIN
			SET @CONTRIBUTO_TRONCATO=@CONTRIBUTO_INVESTIMENTO_ORIGINALE
			SET @COD_TRONCAMENTO='O'
		END
	END
	-- MASSIMALI PER BANDO
	SELECT TOP 1 @IMPORTO_MAX_INTERVENTO=ISNULL(IMPORTO,0) FROM BANDO_MASSIMALI
	WHERE ID_PROGRAMMAZIONE=@ID_PROGRAMMAZIONE AND ID_BANDO=@ID_DISPOSIZIONI_ATTUATIVE
	IF @IMPORTO_MAX_INTERVENTO>0 BEGIN
		SELECT @TOTALE_CONTRIBUTO_INVESTIMENTI=SUM(CONTRIBUTO_RICHIESTO-(dbo.SIAR_MIN(SPESE_GENERALI,COSTO_INVESTIMENTO*QUOTA_SPESE_GENERALI/100)
			*QUOTA_CONTRIBUTO_RICHIESTO/100)) FROM @PIANO_INVESTIMENTI I 
		WHERE I.COD_TIPO_INVESTIMENTO=1 AND I.ID_PROGRAMMAZIONE=@ID_PROGRAMMAZIONE 
			AND (@ID_INVESTIMENTO IS NULL OR ID_INVESTIMENTO!=@ID_INVESTIMENTO)
		IF @CONTRIBUTO_TRONCATO>(@IMPORTO_MAX_INTERVENTO-ISNULL(@TOTALE_CONTRIBUTO_INVESTIMENTI,0)) BEGIN
			SET @CONTRIBUTO_TRONCATO=@IMPORTO_MAX_INTERVENTO-ISNULL(@TOTALE_CONTRIBUTO_INVESTIMENTI,0)
			SET @COD_TRONCAMENTO='I'
		END
	END

	-- MASSIMALI DI DOMANDA
	SELECT TOP 1 @CONTRIBUTO_MAX_DOMANDA=ISNULL(IMPORTO_MAX,0) FROM BANDO_TIPO_INVESTIMENTI
	WHERE ID_BANDO=@ID_DISPOSIZIONI_ATTUATIVE AND COD_TIPO_INVESTIMENTO=7
	IF @CONTRIBUTO_MAX_DOMANDA>0 BEGIN
		SELECT @TOTALE_CONTRIBUTO_INVESTIMENTI=SUM(CONTRIBUTO_RICHIESTO) FROM @PIANO_INVESTIMENTI
		WHERE (@ID_INVESTIMENTO IS NULL OR ID_INVESTIMENTO!=@ID_INVESTIMENTO)
		IF @CONTRIBUTO_TRONCATO>(@CONTRIBUTO_MAX_DOMANDA-ISNULL(@TOTALE_CONTRIBUTO_INVESTIMENTI,0))
			SET @COD_TRONCAMENTO='D' -- NON TRONCO DIRETTAMENTE IL CONTRIBUTO MA LO DETRARRO' SUL TOTALE		
	END
	IF @CONTRIBUTO_TRONCATO<0 SET @CONTRIBUTO_TRONCATO=0
	SELECT CAST(ROUND(@CONTRIBUTO_TRONCATO,2) AS DECIMAL(18,2)) AS CONTRIBUTO_TRONCATO,@COD_TRONCAMENTO AS COD_TRONCAMENTO
