CREATE PROCEDURE [dbo].[SpPsrGetPrioritaXInvestimento]
(
	@ID_SCHEDA_VALUTAZIONE INT,
	@ID_INVESTIMENTO INT=NULL
)
AS
	--DECLARE @ID_SCHEDA_VALUTAZIONE INT=44,@ID_INVESTIMENTO INT=1485

	SELECT ID_SCHEDA_VALUTAZIONE,P.DESCRIZIONE,FLAG_TEMPLATE,P.ID_PRIORITA,PRIORITA,COD_LIVELLO,ORDINE,PESO,VALORE_MAX,VALORE_MIN,
		AIUTO_ADDIZIONALE,SELEZIONABILE,PLURI_VALORE,EVAL,FLAG_MANUALE,IS_MAX,INPUT_NUMERICO,MISURA,DATETIME,TESTO_SEMPLICE,TESTO_AREA,PLURI_VALORE_SQL,QUERY_PLURIVALORE,
		I.ID_INVESTIMENTO,I.ID_VALORE,I.SCELTO,I.VALORE,I.VAL_DATA,I.VAL_TESTO,V.DESCRIZIONE AS PLURIVALORE_DESCRIZIONE,
		V.PUNTEGGIO AS PLURIVALORE_PUNTEGGIO
	FROM vSCHEDA_X_PRIORITA P
	LEFT JOIN PRIORITA_X_INVESTIMENTI I ON P.ID_PRIORITA=I.ID_PRIORITA AND I.ID_INVESTIMENTO=@ID_INVESTIMENTO
	LEFT JOIN VALORI_PRIORITA V ON I.ID_VALORE=V.ID_VALORE
	WHERE ID_SCHEDA_VALUTAZIONE=@ID_SCHEDA_VALUTAZIONE AND SELEZIONABILE=1 AND FLAG_TEMPLATE=0 AND COD_LIVELLO IN ('I','Z','M')
	ORDER BY ORDINE,PLURI_VALORE,P.PRIORITA
