CREATE PROCEDURE [dbo].[SpPsrGetLiquidazioniDomandaPagamento]
(
	@ID_DOMANDA_PAGAMENTO INT
)
AS
	SELECT E.BARCODE,E.IMPORTO_AMMESSO,P.TIPO+' '+P.CODICE AS PROGRAMMAZIONE,E.IMPORTO_LIQUIDATO, NULL AS NUM_DECRETO_AGEA,
		NULL AS DATA_DECRETO_AGEA,ER.*
	FROM DOMANDA_DI_PAGAMENTO_ESPORTAZIONE E
	INNER JOIN ELENCO_DI_PAGAMENTO EP ON E.ID_ELENCO_PAGAMENTO=EP.ID_ELENCO_PAGAMENTO
	INNER JOIN VELENCO_DI_PAGAMENTO ER ON EP.ID_ELENCO_REGIONALE=ER.ID_ELENCO_PAGAMENTO
	INNER JOIN BANDO B ON ER.ID_DISPOSIZIONE_ATTUATIVA=B.ID_BANDO
	INNER JOIN VZPROGRAMMAZIONE P ON B.ID_PROGRAMMAZIONE=P.ID
	--LEFT JOIN AGEA_DECRETI AD ON E.ID_DECRETO_AGEA = AD.ID
	WHERE E.ID_DOMANDA_PAGAMENTO=@ID_DOMANDA_PAGAMENTO
	ORDER BY MISURA_PREVALENTE DESC
