
CREATE PROCEDURE [dbo].[SpPsrGetIndicatoriIntervento]
(
	@ID_PROG INT
)
AS

SELECT  zPROGRAMMAZIONE.ID          AS ID_PROGRAMMAZIONE,
        zDIMENSIONI.ID              AS ID_DIMENSIONE, 
        ID_DIM_X_PROGRAMMAZIONE, 
        COD_DIM,
        zPROGRAMMAZIONE.CODICE      AS COD_PROGRAMMAZIONE, 
        zPROGRAMMAZIONE.DESCRIZIONE AS DES_PROGRAMMAZIONE,
        zDIMENSIONI.CODICE          AS COD_DIMENSIONE, 
        zDIMENSIONI.DESCRIZIONE     AS DES_DIMENSIONE, 
        UM, 
        UM AS LIVELLO_PROGRAMMAZIONE 
FROM zDIMENSIONI 
	LEFT OUTER JOIN  
     zDIMENSIONI_X_PROGRAMMAZIONE ON zDIMENSIONI.ID = zDIMENSIONI_X_PROGRAMMAZIONE.ID_DIMENSIONE 
					             AND zDIMENSIONI_X_PROGRAMMAZIONE.ID_PROGRAMMAZIONE = @ID_PROG
	LEFT OUTER JOIN 
    zPROGRAMMAZIONE ON zDIMENSIONI_X_PROGRAMMAZIONE.ID_PROGRAMMAZIONE = zPROGRAMMAZIONE.ID 
-- WHERE COD_DIM in ('IOS', 'IOC', 'D1', 'D2', 'D3', 'D6', 'RG')
ORDER BY CASE zDIMENSIONI_X_PROGRAMMAZIONE.ID_PROGRAMMAZIONE  
                WHEN @ID_PROG THEN 0 
                ELSE 1 
         END, 
         zDimensioni.Ordine,
         COD_DIM