


CREATE PROCEDURE [dbo].[SpPsrFindAttoXComunicazione]
(
	@ID_PROGETTO INT,
	@COD_STATO CHAR(1)	
)
AS
--DECLARE @ID_PROGETTO INT = 1150,@COD_STATO CHAR(1)	= 'F'
DECLARE @RESULT INT= 1

DECLARE @ID_BANDO INT 
SELECT @ID_BANDO =  ID_BANDO FROM PROGETTO WHERE ID_PROGETTO = @ID_PROGETTO
IF(SELECT COUNT(*) FROM BANDO_CONFIG WHERE ID_BANDO = @ID_BANDO AND COD_TIPO = 'ATTGRADBLOCCHI') = 0
		SELECT @RESULT = COUNT(*) 
		FROM BANDO_COMUNICAZIONI 
		WHERE ID_BANDO = @ID_BANDO 
		AND ((COD_TIPO = 'CFI' AND @COD_STATO = 'F') OR (COD_TIPO = 'CFN' AND @COD_STATO = 'N'))
		AND ID_ATTO IS NOT NULL
		
SELECT @RESULT AS RESULT



