
CREATE PROCEDURE [dbo].[SpPsrCalcoloContributoInvestimento]
(
	@ID_INVESTIMENTO INT,
	@FASE VARCHAR(10),
	@QUOTA_PARAMETRO DECIMAL(15,12) = NULL
)
AS
	/* ACTUNG!!! 
		NON SOVRASCRIVERE IN AUTOMATICO LA QUERY SUI 3 DB PER IL CONTROLLO 
		A FONDO PAGINA SU UNO SPECIFICO BANDO CHE E' DIVERSO TRA PRODUZIONE 
		E TEST
		PRODUZIONE -> @IdBando = 164 e ID_PRIORITA = 938
		TEST -> @IdBando = 130 e ID_PRIORITA = 780
	*/
	DECLARE @COSTO_INVESTIMENTO DECIMAL(18,2),@SPESE_TECNICHE DECIMAL(18,2),@QUOTA_AIUTO DECIMAL(15,12),@RICHIEDI_PARTICELLA BIT,
		@QUOTA_SPESE_GENERALI DECIMAL(10,2),@IS_MAX BIT,@ID_PROGETTO INT,@ID_PROGRAMMAZIONE INT,@ID_VARIANTE INT,
		@ID_FASCICOLO INT,@ID_IMPRESA INT,@FASCICOLO_RICHIESTO BIT,@QUERY_SQL VARCHAR(3000),
		@QUOTA_AIUTO_ALTRE_FONTI DECIMAL(15,12) ,@QUERY_SQL_ALTREFONTI VARCHAR(3000) , @IdBando INT
		
	SELECT @COSTO_INVESTIMENTO=COSTO_INVESTIMENTO,@SPESE_TECNICHE=SPESE_GENERALI,@QUOTA_AIUTO=AIUTO_MINIMO,
		@RICHIEDI_PARTICELLA=RICHIEDI_PARTICELLA,@QUOTA_SPESE_GENERALI=ISNULL(QUOTA_SPESE_GENERALI,0),@IS_MAX=IS_MAX,
		@ID_PROGETTO=I.ID_PROGETTO,@ID_PROGRAMMAZIONE=I.ID_PROGRAMMAZIONE,@ID_VARIANTE=I.ID_VARIANTE, 
		@ID_FASCICOLO=ID_FASCICOLO,@ID_IMPRESA=ID_IMPRESA,@FASCICOLO_RICHIESTO=B.FASCICOLO_RICHIESTO , 
		@QUERY_SQL = QUERY_SQL ,@QUOTA_AIUTO_ALTRE_FONTI = ISNULL(AIUTO_MINIMO_ALTREFONTI,0) , @QUERY_SQL_ALTREFONTI = QUERY_SQL_ALTREFONTI ,@IdBando = P.ID_BANDO
	FROM PIANO_INVESTIMENTI I 
		JOIN PROGETTO P ON I.ID_PROGETTO=P.ID_PROGETTO 
		JOIN BANDO B ON P.ID_BANDO=B.ID_BANDO
		JOIN CODIFICA_INVESTIMENTO C ON I.ID_CODIFICA_INVESTIMENTO=C.ID_CODIFICA_INVESTIMENTO
		JOIN DETTAGLIO_INVESTIMENTI D ON I.ID_CODIFICA_INVESTIMENTO=D.ID_CODIFICA_INVESTIMENTO AND I.ID_DETTAGLIO_INVESTIMENTO=D.ID_DETTAGLIO_INVESTIMENTO	
	WHERE I.ID_INVESTIMENTO=@ID_INVESTIMENTO	
	
	IF @QUERY_SQL IS NOT NULL
	BEGIN
		DECLARE @PROVA_TABELLA TABLE(ID INT IDENTITY(1,1) NOT NULL,RISULTATO_QUERY DECIMAL(10,2))
		
		INSERT INTO @PROVA_TABELLA
			exec SpExecQuerySqlInvestimento @QUERY_SQL,@ID_PROGETTO,NULL,NULL, @ID_INVESTIMENTO
			
		SELECT TOP 1 @QUOTA_AIUTO =RISULTATO_QUERY FROM @PROVA_TABELLA ORDER BY ID DESC
	END
	
	IF @QUOTA_PARAMETRO IS NOT NULL AND @QUOTA_PARAMETRO != @QUOTA_AIUTO
		BEGIN
			SET @QUOTA_AIUTO = @QUOTA_PARAMETRO;
		END
	
	IF @QUERY_SQL_ALTREFONTI IS NOT NULL
	BEGIN
		DECLARE @PROVA_TABELLA2 TABLE(ID INT IDENTITY(1,1) NOT NULL,RISULTATO_QUERY DECIMAL(10,2))
		
		INSERT INTO @PROVA_TABELLA2
			exec SpExecQuerySqlInvestimento @QUERY_SQL_ALTREFONTI,@ID_PROGETTO,NULL,NULL, @ID_INVESTIMENTO
			
		SELECT TOP 1 @QUOTA_AIUTO_ALTRE_FONTI =ISNULL(RISULTATO_QUERY,0)
		FROM @PROVA_TABELLA2 
		ORDER BY ID DESC
	END
	
	IF @FASCICOLO_RICHIESTO=1 AND @ID_FASCICOLO IS NULL BEGIN -- IL PROGETTO E' CORRELATO QUINDI PRENDO IL DATO DALL'INTEGRATO
		SELECT @ID_FASCICOLO=P.ID_FASCICOLO 
		FROM PROGETTO P 
			JOIN PROGETTO P2 ON P.ID_PROGETTO=P2.ID_PROG_INTEGRATO
		WHERE P2.ID_PROGETTO=@ID_PROGETTO
		
		IF @ID_FASCICOLO IS NULL BEGIN
			RAISERROR('L`impresa non è titolare di nessun Fascicolo Aziendale in corso di validità.',13,1)
			RETURN
		END
	END	

	-- AGGIUNGO L'EVENTUALE QUOTA CONTRIBUTO DA PRIORITA SE NON HO PASSATO QUOTA_PARAMETRO
	IF (@IS_MAX=0 AND @QUOTA_PARAMETRO IS NULL)
	BEGIN
		DECLARE @PR TABLE (ID_PRIORITA INT,AIUTO_ADDIZIONALE DECIMAL(10,2),SELEZIONABILE BIT,IS_MAX BIT,COD_LIVELLO CHAR(1),
			ID_PRIORITA_SPECIALE_SELEZIONATA INT,IS_MAX_SPECIALE BIT,SELEZIONATA BIT)
			
		INSERT INTO @PR
			SELECT X.ID_PRIORITA,X.AIUTO_ADDIZIONALE,X.SELEZIONABILE,X.IS_MAX,R.COD_LIVELLO,PS.ID_PRIORITA_SELEZIONATA,PS.IS_MAX,
				SELEZIONATA=
					CASE 
						WHEN COD_LIVELLO='D' AND PP.ID_PROGETTO IS NOT NULL 
							THEN 1
						WHEN COD_LIVELLO='I' AND PV.ID_INVESTIMENTO IS NOT NULL 
							THEN 1
						WHEN COD_LIVELLO='S' AND ID_PRIORITA_SETTORIALE IS NOT NULL 
							THEN 1
						WHEN COD_LIVELLO IN ('Z','T') AND SELEZIONABILE=1 AND PV.ID_INVESTIMENTO IS NOT NULL 
							THEN 1
						WHEN COD_LIVELLO='F' AND DI.RICHIEDI_PARTICELLA=1 
							THEN 1
						WHEN COD_LIVELLO='M' AND DI.RICHIEDI_PARTICELLA=0 
							THEN 1
						ELSE 0 
					END
			FROM PIANO_INVESTIMENTI I 
				JOIN PROGETTO P ON I.ID_PROGETTO=P.ID_PROGETTO
				JOIN BANDO B ON P.ID_BANDO=B.ID_BANDO
				JOIN SCHEDA_X_PRIORITA X ON B.ID_SCHEDA_VALUTAZIONE=X.ID_SCHEDA_VALUTAZIONE
				JOIN PRIORITA R ON X.ID_PRIORITA=R.ID_PRIORITA
				LEFT JOIN PRIORITA_SPECIALE PS ON X.ID_SCHEDA_VALUTAZIONE=PS.ID_SCHEDA_VALUTAZIONE AND R.ID_PRIORITA=PS.ID_PRIORITA
				LEFT JOIN PRIORITA_X_PROGETTO PP ON R.ID_PRIORITA=PP.ID_PRIORITA AND PP.ID_PROGETTO=@ID_PROGETTO
				LEFT JOIN PRIORITA_X_INVESTIMENTI PV ON R.ID_PRIORITA=PV.ID_PRIORITA AND I.ID_INVESTIMENTO=PV.ID_INVESTIMENTO		
				LEFT JOIN DETTAGLIO_INVESTIMENTI DI ON I.ID_CODIFICA_INVESTIMENTO=DI.ID_CODIFICA_INVESTIMENTO AND I.ID_DETTAGLIO_INVESTIMENTO=DI.ID_DETTAGLIO_INVESTIMENTO
			WHERE I.ID_INVESTIMENTO=@ID_INVESTIMENTO 
			ORDER BY COD_LIVELLO		     
		
		DECLARE @IS_MAX_PRIORITA BIT
		DECLARE @QUOTA_ADDIZIONALE DECIMAL(10,2)=0
		--	SELECT * FROM @PR		    
		
		-- PRIORITA SPECIALI SELEZIONATE CON MASSIMO CONTRIBUTO
		SELECT TOP 1 @QUOTA_ADDIZIONALE=
			CASE 
				WHEN P2.SELEZIONATA=1 
					THEN ISNULL(P1.AIUTO_ADDIZIONALE,0) 
				ELSE 0 
			END,
			@IS_MAX_PRIORITA = P1.IS_MAX
		FROM @PR P1 
			JOIN @PR P2 ON P1.ID_PRIORITA_SPECIALE_SELEZIONATA=P2.ID_PRIORITA
		WHERE P1.SELEZIONATA=1 
			AND P1.IS_MAX_SPECIALE=1  
		ORDER BY P1.AIUTO_ADDIZIONALE DESC
      
     	IF @@ROWCOUNT=0 OR (ISNULL(@IS_MAX_PRIORITA,0) = 0 AND @QUOTA_ADDIZIONALE=0)   
		BEGIN
			-- PRIORITA NORMALI CON MASSIMO CONTRIBUTO
		 
			SELECT TOP 1 @QUOTA_ADDIZIONALE=ISNULL(AIUTO_ADDIZIONALE,0)
			FROM @PR 
			WHERE SELEZIONATA=1 
				AND IS_MAX=1 
				AND ISNULL(IS_MAX_SPECIALE,0)=0 
			ORDER BY AIUTO_ADDIZIONALE DESC
	 
			IF @QUOTA_ADDIZIONALE=0 
			BEGIN
				-- PRIORITA NORMALI E SPECIALI SENZA MASSIMO
				SELECT @QUOTA_ADDIZIONALE=ISNULL(SUM(CASE 
														WHEN ISNULL(P2.SELEZIONATA,1)=1 
															THEN P1.AIUTO_ADDIZIONALE 
														ELSE 0 
													END),0)
				FROM @PR P1 
					LEFT JOIN @PR P2 ON P1.ID_PRIORITA_SPECIALE_SELEZIONATA=P2.ID_PRIORITA
				WHERE P1.SELEZIONATA=1 
					AND P1.COD_LIVELLO!='Z' 
					AND ISNULL(P1.IS_MAX_SPECIALE,0)=0
				
				--SELECT ISNULL(SUM(CASE WHEN ISNULL(P2.SELEZIONATA,1)=1 THEN P1.AIUTO_ADDIZIONALE ELSE 0 END),0)
				--FROM @PR P1 LEFT JOIN @PR P2 ON P1.ID_PRIORITA_SPECIALE_SELEZIONATA=P2.ID_PRIORITA
				--WHERE P1.SELEZIONATA=1 AND P1.COD_LIVELLO!='Z' AND ISNULL(P1.IS_MAX_SPECIALE,0)=0
				
				-- PRIORITA DI ZONA
				SELECT DISTINCT @QUOTA_ADDIZIONALE+=AIUTO_ADDIZIONALE 
				FROM @PR 
				WHERE SELEZIONATA=1 
					AND COD_LIVELLO='Z'
			END
		END
		SET @QUOTA_AIUTO+=ISNULL(@QUOTA_ADDIZIONALE,0)
	END
	
	DECLARE @MAX_SPESE_TECNICHE DECIMAL(18,2),@CONTRIBUTO_SPESE_TECNICHE DECIMAL(18,2),@CONTRIBUTO_TOTALE DECIMAL(18,2)	
	SELECT @MAX_SPESE_TECNICHE=ROUND(@COSTO_INVESTIMENTO*@QUOTA_SPESE_GENERALI/100,2)
	SELECT @CONTRIBUTO_SPESE_TECNICHE=ROUND(DBO.SIAR_MIN(@MAX_SPESE_TECNICHE,@SPESE_TECNICHE)*@QUOTA_AIUTO/100,2)
	SELECT @CONTRIBUTO_TOTALE=ROUND(@COSTO_INVESTIMENTO*@QUOTA_AIUTO/100,2)+ISNULL(@CONTRIBUTO_SPESE_TECNICHE,0)
		
	DECLARE @RESULT TABLE (CONTRIBUTO_TRONCATO DECIMAL(18,2),COD_TRONCAMENTO CHAR(1))
	INSERT INTO @RESULT
	EXEC SpPsrCalcoloMassimaliContributoInvestimentoFondoPerduto @ID_PROGETTO,@ID_PROGRAMMAZIONE,@ID_VARIANTE,@FASE,@ID_INVESTIMENTO,@CONTRIBUTO_TOTALE
	
	
	DECLARE @CONTRIBUTO_INVESTIMENTO DECIMAL(18,2) = CAST(ROUND(@COSTO_INVESTIMENTO*@QUOTA_AIUTO/100,2) AS DECIMAL(18,2))
	DECLARE @CONTRIBUTO_INVESTIMENTO_ALTRE_FONTI DECIMAL(18,2) = CAST(ROUND(@COSTO_INVESTIMENTO*@QUOTA_AIUTO_ALTRE_FONTI/100,2) AS DECIMAL(18,2))
	DECLARE @CONTRIBUTO_TRONCATO DECIMAL(18,2),@COD_TRONCAMENTO CHAR(1)
	SELECT @CONTRIBUTO_TRONCATO =  CONTRIBUTO_TRONCATO, @COD_TRONCAMENTO = COD_TRONCAMENTO FROM @RESULT
	
	
	IF ((DB_NAME() = 'sigefproduzione' AND @IdBando in (164))
		OR (DB_NAME() = 'sigeftest' AND @IdBando in (130)))
	BEGIN
		DECLARE @CONTRIBUTO_MAX DECIMAL(18,2), @RATING int
		
		SELECT @RATING = COUNT(*) 
		FROM PRIORITA_X_INVESTIMENTI 
		WHERE ID_INVESTIMENTO = @ID_INVESTIMENTO 
			AND ( (DB_NAME() = 'sigefproduzione' AND ID_PRIORITA = 938)
					OR (DB_NAME() = 'sigeftest' AND ID_PRIORITA = 780))
		
		IF (@RATING >0) 
			SET @CONTRIBUTO_MAX = 75000
		ELSE
			SET @CONTRIBUTO_MAX = 50000
		
		IF (@COSTO_INVESTIMENTO*@QUOTA_AIUTO/100 > @CONTRIBUTO_MAX  )
		BEGIN
			
			SET @CONTRIBUTO_INVESTIMENTO = @CONTRIBUTO_MAX
			SET @CONTRIBUTO_TRONCATO = @CONTRIBUTO_MAX

			SET @QUOTA_AIUTO = CAST(ROUND(@CONTRIBUTO_MAX*100/@COSTO_INVESTIMENTO,2) AS DECIMAL(15,12))
			SET @COD_TRONCAMENTO = 'D'
			
		END
	END
	
	
	SELECT /*@COSTO_INVESTIMENTO,@SPESE_TECNICHE,@RICHIEDI_PARTICELLA,@QUOTA_SPESE_GENERALI,@IS_MAX,*/@MAX_SPESE_TECNICHE AS MAX_SPESE_TECNICHE,
		@CONTRIBUTO_INVESTIMENTO AS CONTRIBUTO_INVESTIMENTO,
		@CONTRIBUTO_INVESTIMENTO_ALTRE_FONTI AS CONTRIBUTO_INVESTIMENTO_ALTRE_FONTI,
		@CONTRIBUTO_SPESE_TECNICHE AS CONTRIBUTO_SPESE_TECNICHE,
		@CONTRIBUTO_TOTALE AS CONTRIBUTO_TOTALE,
		@QUOTA_AIUTO AS QUOTA_CONTRIBUTO,
		@QUOTA_AIUTO_ALTRE_FONTI AS QUOTA_CONTRIBUTO_ALTRE_FONTI,
		@CONTRIBUTO_TRONCATO AS CONTRIBUTO_TRONCATO,
		@COD_TRONCAMENTO AS COD_TRONCAMENTO
GO