CREATE PROCEDURE [dbo].[SpPsrGetDatiBandoXProtocollazione]
(
	@ID_BANDO INT,
	@PROVINCIA CHAR(2)='AN'
)

AS
	SELECT TOP 1 A.NUMERO,A.DATA,I.DATA_SCADENZA,P.TIPO+' '+P.CODICE AS PROGRAMMAZIONE,F.FASCICOLO
	FROM BANDO B INNER JOIN vzPROGRAMMAZIONE P ON B.ID_PROGRAMMAZIONE=P.ID
	INNER JOIN FASCICOLO_PALEO F ON F.COD_TIPO=P.COD_TIPO+' '+P.CODICE+' '+CAST(B.ID_BANDO AS VARCHAR(10)) AND F.ATTIVO=1 
		AND B.COD_ENTE=F.COD_ENTE AND F.PROVINCIA=@PROVINCIA
	INNER JOIN BANDO_STORICO S ON B.ID_BANDO=S.ID_BANDO AND S.COD_STATO='L'
	INNER JOIN ATTI A ON S.ID_ATTO=A.ID_ATTO
	INNER JOIN BANDO_INTEGRAZIONI I ON B.ID_INTEGRAZIONE_ULTIMA=I.ID
	WHERE B.ID_BANDO=@ID_BANDO
	ORDER BY F.DATA_INIZIO_VALIDITA DESC,F.COD_TIPO DESC
