CREATE PROCEDURE [dbo].[SpPsrRicercaBandi]
(
	--@DISPOSIZIONI_ATTUATIVE BIT=0,
	@COD_ENTE VARCHAR(10)=NULL,
	@ID_PROGRAMMAZIONE INT=NULL, 
	@DATA_SCADENZA_LEQ DATETIME=NULL,
	@NUMERO_ATTO VARCHAR(10)=NULL,
	@DATA_ATTO DATETIME=NULL,
	--@PAROLE_CHIAVE VARCHAR(50)=NULL,
	@NASCONDI_SCADUTI BIT=1, -- INUTILE C'E' LA INNER JOIN CON LO STATO RILASCIATO
	@MOSTRA_PUBBLICATI BIT=1
)
AS

	SELECT B.*,A.NUMERO AS NUMERO_ATTO,A.DATA AS DATA_ATTO
	FROM vBANDO B LEFT JOIN BANDO_STORICO S ON B.ID_BANDO=S.ID_BANDO AND S.COD_STATO='L'
	LEFT JOIN ATTI A ON S.ID_ATTO=A.ID_ATTO	
	WHERE B.DISPOSIZIONI_ATTUATIVE=0 AND(@COD_ENTE IS NULL OR COD_ENTE=@COD_ENTE) AND 
		(@ID_PROGRAMMAZIONE IS NULL OR ID_PROGRAMMAZIONE=@ID_PROGRAMMAZIONE) AND 
		(@DATA_SCADENZA_LEQ IS NULL OR DATA_SCADENZA<DATEADD(DAY,1,@DATA_SCADENZA_LEQ)) AND
		(@NUMERO_ATTO IS NULL OR A.NUMERO=@NUMERO_ATTO) AND (@DATA_ATTO IS NULL OR A.DATA=@DATA_ATTO) AND	
		(@NASCONDI_SCADUTI=0 OR B.DATA_SCADENZA>GETDATE()) AND (@MOSTRA_PUBBLICATI=0 OR B.ORDINE_STATO>1) /*AND	
	(@PAROLE_CHIAVE IS NULL OR PAROLE_CHIAVE LIKE '%'+@PAROLE_CHIAVE+'%')*/	
	AND
	B.DATA_APERTURA <= GETDATE()
	ORDER BY B.DATA_SCADENZA DESC
