create PROCEDURE [dbo].[SpPsrGetQuadriModelloDomanda]
(
	@ID_MODELLO_DOMANDA INT
)
AS

SELECT Q1.*,ID_DOMANDA,ORDINE 
FROM QUADRO_DOMANDA AS Q1 
LEFT OUTER JOIN QUADRI_X_DOMANDA AS Q2 ON Q1.ID_QUADRO=Q2.ID_QUADRO AND Q2.ID_DOMANDA=@ID_MODELLO_DOMANDA 
ORDER BY ID_DOMANDA DESC,ORDINE
