






CREATE PROCEDURE [dbo].[SpPsrGetProgrammazioneFonti]
(
	@ID_PROG INT
)
AS

	SELECT ID, ID_PROGRAMMAZIONE, F.ID_FONTE AS ID_FONTE,F.PERCENTUALE AS PERCENTUALE_FONTE,P.PERCENTUALE AS PERCENTUALE,
	    DESCRIZIONE, ATTIVA, DATA_INIZIO,OPERATORE_INIZIO,DATA_FINE,OPERATORE_FINE, U1.NOMINATIVO AS NOMINATIVO_INIZIO, 
                         U2.NOMINATIVO AS NOMINATIVO_FINE
	FROM FONTI_FINANZIARIE F 
	LEFT JOIN zPROGRAMMAZIONE_FONTI P ON F.ID_FONTE = P.ID_FONTE AND P.ID_PROGRAMMAZIONE=@ID_PROG AND P.ATTIVA=1
	LEFT JOIN vUTENTI U1 ON P.OPERATORE_INIZIO = U1.ID_UTENTE 
	LEFT JOIN vUTENTI AS U2 ON P.OPERATORE_FINE = U2.ID_UTENTE
	ORDER BY F.ID_FONTE,DATA_INIZIO DESC









