CREATE PROCEDURE [dbo].[SpPsrGetSettoriProduttiviBando]
(
	@ID_BANDO INT
)
AS
	SELECT NULL AS ID_BANDO_X_SETTORE_PRODUTTIVO,NULL AS ID_PRIORITA_SETTORIALE,NULL AS PRIORITA_SETTORIALE,ID_BANDO,ID_SETTORE_PRODUTTIVO,
		SETTORE_PRODUTTIVO
	FROM vBANDO_X_SETTORE_PRODUTTIVO
	WHERE ID_BANDO=@ID_BANDO AND ID_SETTORE_PRODUTTIVO IS NOT NULL		
	GROUP BY ID_BANDO,ID_SETTORE_PRODUTTIVO,SETTORE_PRODUTTIVO ORDER BY SETTORE_PRODUTTIVO
