CREATE PROCEDURE [dbo].[SpRicercaImpresa]
(
	@ID_UTENTE INT,
	@ID_IMPRESA INT=NULL,
	@CUAA VARCHAR(16)=NULL,
	@RAGIONE_SOCIALE VARCHAR(100)=NULL, --LIKE
	@COD_TIPO_MANDATO CHAR(3)=NULL
	
)
AS
	--DECLARE @ID_IMPRESA INT,@CUAA VARCHAR(16),@RAGIONE_SOCIALE VARCHAR(100),@COD_ENTE VARCHAR(10),@CF_UTENTE VARCHAR(16)
	--SET @CUAA='00351040423'
	--SET @COD_ENTE='UNICAA'
	--SET @CF_UTENTE='PTTLNR84C62E388F'--PGNMHL89R63L500N'--CSRZNE30R25F051R'

	DECLARE @COD_ENTE VARCHAR(10),@COD_TIPO_ENTE VARCHAR(10),@ID_PF INT,@PROVINCIA CHAR(2)
	SELECT @COD_ENTE=COD_ENTE,@COD_TIPO_ENTE=COD_TIPO_ENTE,@ID_PF=ID_PERSONA_FISICA,@PROVINCIA=PROVINCIA
	FROM vUTENTI WHERE ID_UTENTE=@ID_UTENTE

	IF @COD_ENTE IS NULL BEGIN
		-- RAPPRESENTANTI LEGALI IMPRESA	
		--SELECT I.ID_IMPRESA,I.CUAA,I.CODICE_FISCALE,I.ID_STORICO_IMPRESA,I.RAGIONE_SOCIALE,I.ID_RAPPRLEGALE_ULTIMO,
		--	I.ID_SEDELEGALE_ULTIMO,ATTIVA
		--FROM vIMPRESA I INNER JOIN PERSONE_X_IMPRESE PXI ON I.ID_RAPPRLEGALE_ULTIMO=PXI.ID_PERSONE_X_IMPRESE		
		--WHERE PXI.ID_PERSONA=@ID_PF AND (@ID_IMPRESA IS NULL OR I.ID_IMPRESA=@ID_IMPRESA) 
		--	AND (@CUAA IS NULL OR I.CUAA=@CUAA OR I.CODICE_FISCALE=@CUAA) AND (@RAGIONE_SOCIALE IS NULL 
		--	OR I.RAGIONE_SOCIALE LIKE '%'+@RAGIONE_SOCIALE+'%')
		SELECT I.ID_IMPRESA,I.CUAA,I.CODICE_FISCALE,I.ID_STORICO_IMPRESA,I.RAGIONE_SOCIALE,I.ID_RAPPRLEGALE_ULTIMO,
			I.ID_SEDELEGALE_ULTIMO,ATTIVA
		FROM vIMPRESA I INNER JOIN PERSONE_X_IMPRESE PXI ON I.ID_IMPRESA=PXI.ID_IMPRESA AND PXI.ATTIVO=1
		WHERE PXI.ID_PERSONA=@ID_PF AND (@ID_IMPRESA IS NULL OR I.ID_IMPRESA=@ID_IMPRESA) 
			AND (@CUAA IS NULL OR I.CUAA=@CUAA OR I.CODICE_FISCALE=@CUAA) AND (@RAGIONE_SOCIALE IS NULL 
			OR I.RAGIONE_SOCIALE LIKE '%'+@RAGIONE_SOCIALE+'%')
		UNION
		-- AGRONOMI/CONSULENTI (NON HANNO IL MANDATO UMA QUINDI NON FACCIO LA DISTINCT)
		SELECT I.ID_IMPRESA,I.CUAA,I.CODICE_FISCALE,I.ID_STORICO_IMPRESA,I.RAGIONE_SOCIALE,I.ID_RAPPRLEGALE_ULTIMO,
			I.ID_SEDELEGALE_ULTIMO,ATTIVA
		FROM vIMPRESA I INNER JOIN MANDATI_IMPRESA M ON I.ID_IMPRESA=M.ID_IMPRESA AND M.ATTIVO=1 
			AND (@COD_TIPO_MANDATO IS NULL OR M.TIPO_MANDATO=@COD_TIPO_MANDATO)
		INNER JOIN UTENTI U ON M.ID_UTENTE_ABILITATO=U.ID_UTENTE WHERE (@ID_IMPRESA IS NULL OR I.ID_IMPRESA=@ID_IMPRESA)
			AND (@CUAA IS NULL OR I.CUAA=@CUAA OR I.CODICE_FISCALE=@CUAA) AND (@RAGIONE_SOCIALE IS NULL 
			OR I.RAGIONE_SOCIALE LIKE '%'+@RAGIONE_SOCIALE+'%') AND M.ID_UTENTE_ABILITATO=@ID_UTENTE
	END
	ELSE BEGIN
		-- ENTI CHE DEVONO RICHIEDERE L'ABILITAZIONE PER L'AZIENDA ALLA REGIONE
		IF @COD_TIPO_ENTE IN ('CAA','IB','CFS') BEGIN	
			SELECT DISTINCT I.ID_IMPRESA,I.CUAA,I.CODICE_FISCALE,I.ID_STORICO_IMPRESA,I.RAGIONE_SOCIALE,I.ID_RAPPRLEGALE_ULTIMO,
				I.ID_SEDELEGALE_ULTIMO,ATTIVA
			FROM vIMPRESA I INNER JOIN MANDATI_IMPRESA M ON I.ID_IMPRESA=M.ID_IMPRESA AND M.ATTIVO=1 
				AND (@COD_TIPO_MANDATO IS NULL OR M.TIPO_MANDATO=@COD_TIPO_MANDATO)
			WHERE M.COD_ENTE=@COD_ENTE AND (@ID_IMPRESA IS NULL OR I.ID_IMPRESA=@ID_IMPRESA) 
				AND (@CUAA IS NULL OR I.CUAA=@CUAA OR I.CODICE_FISCALE=@CUAA)
				AND (@RAGIONE_SOCIALE IS NULL OR I.RAGIONE_SOCIALE LIKE '%'+@RAGIONE_SOCIALE+'%')
		END	
		-- REGIONALI,AMMINISTRAZIONE E ASUR (L'ASSAM VIENE LIMITATA A VEDERE SOLO LE PAGINE DELLE MANIFESTAZIONI DI INTERESSE)
		ELSE IF @COD_TIPO_ENTE IN ('%','RM','AdC','SSR'/*,'ASSAM'*/,'EE') BEGIN
			SELECT ID_IMPRESA,CUAA,CODICE_FISCALE,ID_STORICO_IMPRESA,RAGIONE_SOCIALE,ID_RAPPRLEGALE_ULTIMO,ID_SEDELEGALE_ULTIMO,ATTIVA
			FROM vIMPRESA WHERE (@ID_IMPRESA IS NULL OR ID_IMPRESA=@ID_IMPRESA) AND (@CUAA IS NULL OR CUAA=@CUAA OR CODICE_FISCALE=@CUAA)
				AND (@RAGIONE_SOCIALE IS NULL OR RAGIONE_SOCIALE LIKE '%'+@RAGIONE_SOCIALE+'%')
		END
		-- NUCLEI OPERATIVI DELLA GUARDIA DI FINANZA, VEDONO SOLO QUELLE DELLA LORO PROVINCIA
		ELSE IF @COD_TIPO_ENTE='GDF' BEGIN
			SELECT I.ID_IMPRESA,CUAA,CODICE_FISCALE,ID_STORICO_IMPRESA,RAGIONE_SOCIALE,ID_RAPPRLEGALE_ULTIMO,ID_SEDELEGALE_ULTIMO,ATTIVA
			FROM vIMPRESA I INNER JOIN vINDIRIZZARIO D ON I.ID_SEDELEGALE_ULTIMO=D.ID_INDIRIZZARIO AND D.SIGLA=@PROVINCIA			
			WHERE (@ID_IMPRESA IS NULL OR I.ID_IMPRESA=@ID_IMPRESA) AND (@CUAA IS NULL OR CUAA=@CUAA OR CODICE_FISCALE=@CUAA)
				AND (@RAGIONE_SOCIALE IS NULL OR RAGIONE_SOCIALE LIKE '%'+@RAGIONE_SOCIALE+'%')		
		END
		-- GAL, PROVINCE (VEDONO SOLO LE IMPRESE CHE HANNO ADERITO AI LORO BANDI)
		ELSE IF @COD_TIPO_ENTE IN ('GAL','PR') BEGIN
			SELECT I.ID_IMPRESA,I.CUAA,I.CODICE_FISCALE,I.ID_STORICO_IMPRESA,I.RAGIONE_SOCIALE,I.ID_RAPPRLEGALE_ULTIMO,
				I.ID_SEDELEGALE_ULTIMO,ATTIVA
			FROM vIMPRESA I WHERE I.COD_ENTE=@COD_ENTE AND (@ID_IMPRESA IS NULL OR I.ID_IMPRESA=@ID_IMPRESA)
				AND (@CUAA IS NULL OR I.CUAA=@CUAA OR I.CODICE_FISCALE=@CUAA) 
				AND (@RAGIONE_SOCIALE IS NULL OR I.RAGIONE_SOCIALE LIKE '%'+@RAGIONE_SOCIALE+'%')
			UNION
			SELECT I.ID_IMPRESA,I.CUAA,CODICE_FISCALE,ID_STORICO_IMPRESA,RAGIONE_SOCIALE,I.ID_RAPPRLEGALE_ULTIMO,
				I.ID_SEDELEGALE_ULTIMO,ATTIVA
			FROM vIMPRESA I INNER JOIN (
				SELECT DISTINCT ID_IMPRESA  FROM PROGETTO P INNER JOIN BANDO B ON P.ID_BANDO=B.ID_BANDO AND B.COD_ENTE=@COD_ENTE
				WHERE ISNULL(P.ID_PROG_INTEGRATO,P.ID_PROGETTO)=P.ID_PROGETTO) Q1 ON I.ID_IMPRESA =Q1.ID_IMPRESA  
			WHERE (@ID_IMPRESA IS NULL OR I.ID_IMPRESA=@ID_IMPRESA) AND (@CUAA IS NULL OR I.CUAA=@CUAA OR CODICE_FISCALE=@CUAA)
				AND (@RAGIONE_SOCIALE IS NULL OR RAGIONE_SOCIALE LIKE '%'+@RAGIONE_SOCIALE+'%')
		END
		-- ODC (VEDONO SOLO LE IMPRESE CHE LI HANNO SELEZIONATI NELLA NOTIFICA)
		ELSE IF @COD_TIPO_ENTE='ODC' BEGIN
			SELECT I.ID_IMPRESA,I.CUAA,CODICE_FISCALE,ID_STORICO_IMPRESA,RAGIONE_SOCIALE,I.ID_RAPPRLEGALE_ULTIMO,
				I.ID_SEDELEGALE_ULTIMO,ATTIVA
			FROM vIMPRESA I INNER JOIN (
				/*SELECT DISTINCT ID_IMPRESA FROM BIO_NOTIFICA N INNER JOIN BIO_NOTIFICA_STORICO S ON N.ID=S.ID_NOTIFICA
				WHERE COD_ODC=@COD_ENTE AND S.COD_STATO='L') Q1 ON I.ID_IMPRESA=Q1.ID_IMPRESA*/
				SELECT DISTINCT ID_IMPRESA FROM BIO_NOTIFICA N INNER JOIN BIO_NOTIFICA_STORICO S ON N.ID=S.ID_NOTIFICA
				INNER JOIN (
					SELECT DISTINCT US.COD_ENTE FROM UTENTI_STORICO US INNER JOIN ENTE E ON US.COD_ENTE=E.COD_ENTE 
					WHERE US.ID_UTENTE=@ID_UTENTE AND E.COD_TIPO_ENTE='ODC') Q2 ON N.COD_ODC=Q2.COD_ENTE
				WHERE S.COD_STATO='L') Q1 ON I.ID_IMPRESA=Q1.ID_IMPRESA
			WHERE (@ID_IMPRESA IS NULL OR I.ID_IMPRESA=@ID_IMPRESA) AND (@CUAA IS NULL OR I.CUAA=@CUAA OR CODICE_FISCALE=@CUAA)
				AND (@RAGIONE_SOCIALE IS NULL OR RAGIONE_SOCIALE LIKE '%'+@RAGIONE_SOCIALE+'%')
		END
	END