CREATE PROCEDURE [dbo].[SpRiepilogoCollaboratoriXBando]
(
	@ID_BANDO INT,
	@PROVINCIA CHAR(2) = NULL
)
AS
/*
DECLARE @ID_BANDO INT 
SET @ID_BANDO=17
DECLARE @PROVINCIA CHAR(2)
--SET @PROVINCIA = 'PS'
*/


-- PROGETTI ASSEGNATI E ISTRUITI DA ALTRI
DECLARE @COLLABORATORI_T TABLE (ID_UTENTE INT,NOMINATIVO VARCHAR(255),COD_ENTE VARCHAR(10),PROVINCIA CHAR(2),
PROGETTI_ASSEGNATI INT,PROGETTI_RICEVIBILI INT,PROGETTI_NON_RICEVIBILI INT,PROGETTI_AMMISSIBILI INT,PROGETTI_NON_AMMISSIBILI INT,
PROGETTI_ISTRUITI_DA_ALTRI INT)

INSERT INTO @COLLABORATORI_T
SELECT C.ID_UTENTE,NOMINATIVO,COD_ENTE,C.PROVINCIA,(SELECT COUNT(*) FROM PROGETTO V 
	WHERE C.ID_PROGETTO=V.ID_PROGETTO) AS PROGETTI_ASSEGNATI,0 AS PROGETTI_RICEVIBILI,0 AS PROGETTI_NON_RICEVIBILI,
	0 AS PROGETTI_AMMISSIBILI,0 AS PROGETTI_NON_AMMISSIBILI,(SELECT COUNT(DISTINCT ID_PROGETTO) FROM PROGETTO_STORICO S 
	WHERE C.ID_PROGETTO=S.ID_PROGETTO AND S.OPERATORE!=C.ID_UTENTE AND S.COD_STATO IN ('Q','A','B')) AS PROGETTI_ISTRUITI_DA_ALTRI
FROM COLLABORATORI_X_BANDO AS C INNER JOIN vUTENTI U ON C.ID_UTENTE = U.ID_UTENTE
WHERE C.ID_BANDO=@ID_BANDO AND C.ATTIVO=1 AND (@PROVINCIA IS NULL OR C.PROVINCIA=@PROVINCIA)
ORDER BY NOMINATIVO,C.PROVINCIA

-- ISTRUTTORI DI CAMBIO STATO DISABILITATI
DECLARE @COLLABORATORI2_T TABLE (ID_UTENTE INT,NOMINATIVO VARCHAR(255),COD_ENTE VARCHAR(10),PROVINCIA CHAR(2),
PROGETTI_ASSEGNATI INT,PROGETTI_RICEVIBILI INT,PROGETTI_NON_RICEVIBILI INT,PROGETTI_AMMISSIBILI INT,PROGETTI_NON_AMMISSIBILI INT,
PROGETTI_ISTRUITI_DA_ALTRI INT)

INSERT INTO @COLLABORATORI2_T
SELECT DISTINCT ID_UTENTE,NOMINATIVO,COD_ENTE,'' AS PROVINCIA,0 AS PROGETTI_ASSEGNATI,0 AS PROGETTI_RICEVIBILI,
	0 AS PROGETTI_NON_RICEVIBILI,0 AS PROGETTI_AMMISSIBILI,0 AS PROGETTI_NON_AMMISSIBILI,0 AS PROGETTI_ISTRUITI_DA_ALTRI
FROM vUTENTI U WHERE ID_UTENTE IN (
	SELECT DISTINCT OPERATORE FROM PROGETTO_STORICO S INNER JOIN PROGETTO P ON S.ID_PROGETTO=P.ID_PROGETTO
	WHERE ID_BANDO=@ID_BANDO AND COD_STATO IN ('Q','A','B') AND OPERATORE NOT IN (SELECT DISTINCT ID_UTENTE FROM @COLLABORATORI_T)
	AND (@PROVINCIA IS NULL OR PROVINCIA_DI_PRESENTAZIONE=@PROVINCIA))
ORDER BY NOMINATIVO

-- REGISTRO SU TABELLA GLI STORICI PER VELOCIZZARE
DECLARE @PSTORICO_TMP TABLE(MAX_ID_STORICO INT,ID_PROGETTO INT,COD_FASE CHAR(1))
INSERT INTO @PSTORICO_TMP
SELECT MAX(S.ID) AS MAX_ID_STORICO,P.ID_PROGETTO,COD_FASE FROM PROGETTO P 
INNER JOIN vPROGETTO_STORICO S ON P.ID_PROGETTO=S.ID_PROGETTO WHERE P.ID_BANDO=@ID_BANDO GROUP BY P.ID_PROGETTO,COD_FASE

-- UNION QUERY FINALE
SELECT ID_UTENTE,NOMINATIVO,COD_ENTE,PROVINCIA,SUM(PROGETTI_ASSEGNATI) AS PROGETTI_ASSEGNATI,

	(SELECT COUNT(*) FROM PROGETTO P INNER JOIN PROGETTO_STORICO S ON P.ID_PROGETTO=S.ID_PROGETTO 
	WHERE ID_BANDO=@ID_BANDO AND OPERATORE=ID_UTENTE AND S.COD_STATO='I' AND PROVINCIA=P.PROVINCIA_DI_PRESENTAZIONE) AS PROGETTI_RICEVIBILI,
	
	(SELECT COUNT(*) FROM PROGETTO P INNER JOIN PROGETTO_STORICO S ON P.ID_PROGETTO=S.ID_PROGETTO 
	WHERE ID_BANDO=@ID_BANDO AND OPERATORE=ID_UTENTE AND S.COD_STATO='Q' AND PROVINCIA=P.PROVINCIA_DI_PRESENTAZIONE) AS PROGETTI_NON_RICEVIBILI,
	
	(SELECT COUNT(*) FROM PROGETTO P INNER JOIN PROGETTO_STORICO S ON P.ID_PROGETTO=S.ID_PROGETTO 
		INNER JOIN @PSTORICO_TMP AS T ON S.ID=T.MAX_ID_STORICO WHERE ID_BANDO=@ID_BANDO AND S.OPERATORE=ID_UTENTE 
		AND S.COD_STATO='A' AND PROVINCIA=P.PROVINCIA_DI_PRESENTAZIONE) AS PROGETTI_AMMISSIBILI,

	(SELECT COUNT(*) FROM PROGETTO P INNER JOIN PROGETTO_STORICO S ON P.ID_PROGETTO=S.ID_PROGETTO 
		INNER JOIN @PSTORICO_TMP AS T ON S.ID=T.MAX_ID_STORICO WHERE ID_BANDO=@ID_BANDO AND S.OPERATORE=ID_UTENTE
		AND S.COD_STATO='B' AND PROVINCIA=P.PROVINCIA_DI_PRESENTAZIONE) AS PROGETTI_NON_AMMISSIBILI,
	
	SUM(PROGETTI_ISTRUITI_DA_ALTRI) AS PROGETTI_ISTRUITI_DA_ALTRI
	
FROM @COLLABORATORI_T GROUP BY ID_UTENTE,NOMINATIVO,COD_ENTE,PROVINCIA
UNION
SELECT ID_UTENTE,NOMINATIVO,COD_ENTE,PROVINCIA,SUM(PROGETTI_ASSEGNATI),

	(SELECT COUNT(*) FROM PROGETTO P INNER JOIN PROGETTO_STORICO S ON P.ID_PROGETTO=S.ID_PROGETTO 
	WHERE ID_BANDO=@ID_BANDO AND OPERATORE=ID_UTENTE AND S.COD_STATO='I') AS PROGETTI_RICEVIBILI,

	(SELECT COUNT(*) FROM PROGETTO P INNER JOIN PROGETTO_STORICO S ON P.ID_PROGETTO=S.ID_PROGETTO 
	WHERE ID_BANDO=@ID_BANDO AND OPERATORE=ID_UTENTE AND S.COD_STATO='Q') AS PROGETTI_NON_RICEVIBILI,

	(SELECT COUNT(*) FROM PROGETTO P INNER JOIN PROGETTO_STORICO S ON P.ID_PROGETTO=S.ID_PROGETTO 
		INNER JOIN @PSTORICO_TMP AS T ON S.ID=T.MAX_ID_STORICO WHERE ID_BANDO=@ID_BANDO AND S.OPERATORE=ID_UTENTE 
		AND S.COD_STATO='A') AS PROGETTI_AMMISSIBILI,

	(SELECT COUNT(*) FROM PROGETTO P INNER JOIN PROGETTO_STORICO S ON P.ID_PROGETTO=S.ID_PROGETTO 
		INNER JOIN @PSTORICO_TMP AS T ON S.ID=T.MAX_ID_STORICO WHERE ID_BANDO=@ID_BANDO AND S.OPERATORE=ID_UTENTE 
		AND S.COD_STATO='B') AS PROGETTI_NON_AMMISSIBILI,
	
	SUM(PROGETTI_ISTRUITI_DA_ALTRI) AS PROGETTI_ISTRUITI_DA_ALTRI
	
FROM @COLLABORATORI2_T GROUP BY ID_UTENTE,NOMINATIVO,COD_ENTE,PROVINCIA
ORDER BY PROVINCIA,NOMINATIVO