CREATE PROCEDURE [dbo].[SpRicercaComune]
(
	@TIPO_RICERCA VARCHAR(20),
	@SIGLA_PROVINCIA CHAR(2)=NULL,
	@CAP_COMUNE CHAR(5)=NULL,
	@DENOMINAZIONE_COMUNE VARCHAR(150)=NULL,
	@COD_PROVINCIA CHAR(3)=NULL,
	@ISTAT_COMUNE CHAR(3)=NULL,
	@COD_BELFIORE CHAR(4)=NULL,
	@ATTIVO BIT=0
)
AS

	IF @TIPO_RICERCA='DENOMINAZIONE' BEGIN
		DECLARE @ID_COMUNE INT
		SELECT TOP 1 @ID_COMUNE=ID_COMUNE FROM COMUNI WHERE SIGLA=@SIGLA_PROVINCIA AND DENOMINAZIONE=@DENOMINAZIONE_COMUNE
			AND (@CAP_COMUNE IS NULL OR CAP=@CAP_COMUNE) -- CAP NULLO PER RICERCA COMUNE NASCITA
		ORDER BY ATTIVO DESC,DATA_INIZIO_VALIDITA DESC
		IF @ID_COMUNE IS NULL BEGIN
			-- RICERCO PER SOLO DENOMINAZIONE
			--SELECT TOP 1 @ID_COMUNE=ID_COMUNE FROM COMUNI WHERE DENOMINAZIONE=@DENOMINAZIONE_COMUNE
			--ORDER BY ATTIVO DESC,DATA_INIZIO_VALIDITA DESC
			
			--26/10/2017 Patch di emergenza per trovare il comune di Acquasanta Terme, erroneamente restituito dal ws Anagrafe Tributaria
			--con la denominazione Acquasanta
			SELECT TOP 1 @ID_COMUNE=ID_COMUNE FROM COMUNI WHERE 
			DENOMINAZIONE=CASE 
			WHEN @DENOMINAZIONE_COMUNE = 'ACQUASANTA' THEN 'ACQUASANTA TERME' 
			WHEN @DENOMINAZIONE_COMUNE = 'TOSCOLANO MADERNO' THEN 'TOSCOLANO-MADERNO' 
			WHEN @DENOMINAZIONE_COMUNE = 'REPUBBLICA DI COREA' THEN 'COREA DEL SUD'
			WHEN @DENOMINAZIONE_COMUNE = 'MONTE GRIMANO' THEN 'MONTE GRIMANO TERME'
			ELSE @DENOMINAZIONE_COMUNE END
			ORDER BY ATTIVO DESC,DATA_INIZIO_VALIDITA DESC
			
			/* COMMENTATA 20/04/2016: PER EVITARE AGGIORNAMENTO DEL DB CON I DATI SPORCHI DAL SIAN
			IF @ID_COMUNE IS NOT NULL BEGIN
				-- SE LO TROVO DEVO AGGIORNARE CAP E PROVINCIA
				-- 1. TROVO LA NUOVA PROVINCIA				
				SELECT TOP 1 @COD_PROVINCIA=CODICE FROM PROVINCE WHERE SIGLA=@SIGLA_PROVINCIA
				-- 2. STORICIZZO IL VECCHIO COMUNE
				UPDATE COMUNI SET ATTIVO=0,DATA_FINE_VALIDITA=GETDATE() WHERE ID_COMUNE=@ID_COMUNE
				-- 3 INSERISCO IL NUOVO COPIANDO IL VECCHIO
				INSERT INTO COMUNI (COD_BELFIORE,DENOMINAZIONE,COD_PROVINCIA,SIGLA,CAP,ISTAT,TIPO_AREA,COD_RUBRICA_PALEO,ATTIVO,
					DATA_INIZIO_VALIDITA)
				SELECT COD_BELFIORE,DENOMINAZIONE,@COD_PROVINCIA,@SIGLA_PROVINCIA,@CAP_COMUNE,ISTAT,TIPO_AREA,COD_RUBRICA_PALEO,
					1,GETDATE() FROM COMUNI WHERE ID_COMUNE=@ID_COMUNE
				SELECT @ID_COMUNE=SCOPE_IDENTITY()
			END*/
			
			
			-- SE NON LO TROVO NON FACCIO NIENTE
		END
		IF @ID_COMUNE IS NOT NULL
			SELECT * FROM vCOMUNI WHERE ID_COMUNE=@ID_COMUNE
	END
	ELSE IF @TIPO_RICERCA='ISTAT'
		SELECT TOP 1 * FROM vCOMUNI WHERE COD_PROVINCIA=@COD_PROVINCIA AND ISTAT=@ISTAT_COMUNE
		ORDER BY ATTIVO DESC,DATA_INIZIO_VALIDITA DESC
	ELSE IF @TIPO_RICERCA='GESTIONE'
		SELECT C.* FROM vCOMUNI C INNER JOIN 
			(SELECT COD_BELFIORE,MAX(ID_COMUNE) AS MAX_ID FROM COMUNI GROUP BY COD_BELFIORE) Q1 ON C.ID_COMUNE=Q1.MAX_ID
		WHERE (@COD_PROVINCIA IS NULL OR COD_PROVINCIA=@COD_PROVINCIA)AND (@COD_BELFIORE IS NULL OR C.COD_BELFIORE=@COD_BELFIORE)
			AND (@DENOMINAZIONE_COMUNE IS NULL OR DENOMINAZIONE like '%'+@DENOMINAZIONE_COMUNE+'%')
			AND (@ATTIVO=0 OR (ATTIVO=@ATTIVO))
		ORDER BY C.COD_BELFIORE