CREATE PROCEDURE [dbo].[SpTriggerDuplicaContributoInvestimentiVariante]
(
	@ID_VARIANTE INT
)
AS
	-- USATA ALLA PRESENTAZIONE DELLA VARIANTE, IMPOSTA IL CAMPO DEGLI INVESTIMENTI PER MEMORIZZARSI
	-- IL VALORE ESATTO PRIMA DELLE MODIFICHE DI ISTRUTTORIA

	INSERT INTO PIANO_INVESTIMENTI_BK_VARIANTE (ID_INVESTIMENTO,CONTRIBUTO_RICHIESTO,DATA)
	SELECT ID_INVESTIMENTO,ISNULL(CONTRIBUTO_RICHIESTO,0),GETDATE() FROM PIANO_INVESTIMENTI WHERE ID_VARIANTE=@ID_VARIANTE
