
CREATE PROCEDURE [dbo].[SpZoomCercaAmministrazione]
(
	@PATTERN VARCHAR(50)=NULL,
	@TIPO_AMMINISTRAZIONE CHAR(2)=NULL
)
AS
	IF @TIPO_AMMINISTRAZIONE='CM'
		SELECT TOP 8 ID_COMUNE,NULL AS COD_ENTE,'CM' AS COD_TIPO_ENTE,DESCRIZIONE=C.DENOMINAZIONE+' ('+C.SIGLA+')',
			NULL AS COD_SIAN,1 AS ATTIVO
		FROM COMUNI C WHERE (@PATTERN IS NULL OR C.DENOMINAZIONE LIKE @PATTERN+'%') AND ATTIVO =1
		ORDER BY C.DENOMINAZIONE,SIGLA
	ELSE IF @TIPO_AMMINISTRAZIONE='PR'
		SELECT NULL AS ID_COMUNE,* FROM ENTE WHERE COD_TIPO_ENTE=@TIPO_AMMINISTRAZIONE 
		ORDER BY DESCRIZIONE
	ELSE -- ENTE REGIONE MARCHE
		SELECT NULL AS ID_COMUNE,'RM' AS COD_ENTE,'RM' AS COD_TIPO_ENTE,DESCRIZIONE='Regione Marche',
			NULL AS COD_SIAN,1 AS ATTIVO 
			