CREATE PROCEDURE [dbo].[SpZoomComuniFind]
(
	@DESCRIZIONE VARCHAR(50)=NULL,
	@COD_REGIONE CHAR(2)=NULL
)
AS
	SELECT TOP 8 ID_COMUNE,C.DENOMINAZIONE,C.SIGLA,C.CAP FROM COMUNI C INNER JOIN PROVINCE P ON C.COD_PROVINCIA=P.CODICE
	WHERE (@DESCRIZIONE IS NULL OR C.DENOMINAZIONE LIKE @DESCRIZIONE+'%')
	AND ((@COD_REGIONE IS NULL  AND P.COD_REGIONE IS NOT NULL) OR P.COD_REGIONE=@COD_REGIONE)
	AND ATTIVO =1
	ORDER BY SIGLA,C.DENOMINAZIONE
