CREATE PROCEDURE [dbo].[SpZoomRecuperoDatiBanca]
(
	@ABI CHAR(5),
	@CAB CHAR(5)=NULL
)
AS
	SELECT TOP 1 I.DENOMINAZIONE AS ISTITUTO,--AGENZIA=CASE WHEN C.DENOMINAZIONE IS NULL THEN F.NOTE ELSE 'FILIALE DI '+C.DENOMINAZIONE END,
	'FILIALE DI '+ISNULL(C.DENOMINAZIONE,F.COMUNE) AS AGENZIA,C.ID_COMUNE,C.DENOMINAZIONE AS COMUNE,C.CAP,C.SIGLA AS PROVINCIA
	FROM BANCHE_ISTITUTI I LEFT JOIN BANCHE_FILIALI F ON I.ABI=F.ABI AND F.CAB=@CAB
	LEFT JOIN COMUNI C ON F.ID_COMUNE=C.ID_COMUNE
	WHERE I.ABI=@ABI
