CREATE PROCEDURE [dbo].[SpZoomRicercaImpresa]
(
	@PATTERN VARCHAR(50)=NULL
)
AS
	SELECT TOP 8 * FROM ( 
		SELECT ID_IMPRESA,CUAA,CODICE_FISCALE,RAGIONE_SOCIALE FROM VIMPRESA WHERE RAGIONE_SOCIALE LIKE '%'+@PATTERN+'%'
		UNION
		SELECT ID_IMPRESA,CUAA,CODICE_FISCALE,RAGIONE_SOCIALE FROM VIMPRESA WHERE CUAA LIKE '%'+@PATTERN+'%'
		UNION
		SELECT ID_IMPRESA,CUAA,CODICE_FISCALE,RAGIONE_SOCIALE FROM VIMPRESA WHERE CODICE_FISCALE LIKE '%'+@PATTERN+'%') Q1
