CREATE PROCEDURE SpRipristinoAccorpamentoInvestimenti
(
	@IdAccorpamentoInvestimenti INT
)
AS
	-- ### PIANO INVESTIMENTI ###
	-- INSERISCO LE VOCI ELIMINATE
	SET IDENTITY_INSERT PIANO_INVESTIMENTI ON;
	INSERT INTO PIANO_INVESTIMENTI (ID_INVESTIMENTO, ID_PROGETTO, ID_PROGRAMMAZIONE, DESCRIZIONE, DATA_VARIAZIONE, OPERATORE_VARIAZIONE, COD_TIPO_INVESTIMENTO, COD_STP, ID_UNITA_MISURA, QUANTITA, COSTO_INVESTIMENTO, SPESE_GENERALI, CONTRIBUTO_RICHIESTO, QUOTA_CONTRIBUTO_RICHIESTO, CONTRIBUTO_ALTRE_FONTI, QUOTA_CONTRIBUTO_ALTRE_FONTI, TASSO_ABBUONO, ID_SETTORE_PRODUTTIVO, ID_PRIORITA_SETTORIALE, ID_OBIETTIVO_MISURA, ID_CODIFICA_INVESTIMENTO, ID_DETTAGLIO_INVESTIMENTO, ID_SPECIFICA_INVESTIMENTO, AMMESSO, ISTRUTTORE, ID_INVESTIMENTO_ORIGINALE, DATA_VALUTAZIONE, VALUTAZIONE_INVESTIMENTO, ID_VARIANTE, COD_VARIAZIONE, NON_COFINANZIATO)
	SELECT 
		R.ID_INVESTIMENTO,
		R.ID_PROGETTO,
		R.ID_PROGRAMMAZIONE,
		R.DESCRIZIONE,
		R.DATA_VARIAZIONE,
		R.OPERATORE_VARIAZIONE,
		R.COD_TIPO_INVESTIMENTO,
		R.COD_STP,
		R.ID_UNITA_MISURA,
		R.QUANTITA,
		R.COSTO_INVESTIMENTO,
		R.SPESE_GENERALI,
		R.CONTRIBUTO_RICHIESTO,
		R.QUOTA_CONTRIBUTO_RICHIESTO,
		R.CONTRIBUTO_ALTRE_FONTI,
		R.QUOTA_CONTRIBUTO_ALTRE_FONTI,
		R.TASSO_ABBUONO,
		R.ID_SETTORE_PRODUTTIVO,
		R.ID_PRIORITA_SETTORIALE,
		R.ID_OBIETTIVO_MISURA,
		R.ID_CODIFICA_INVESTIMENTO,
		R.ID_DETTAGLIO_INVESTIMENTO,
		R.ID_SPECIFICA_INVESTIMENTO,
		R.AMMESSO,
		R.ISTRUTTORE,
		R.ID_INVESTIMENTO_ORIGINALE,
		R.DATA_VALUTAZIONE,
		R.VALUTAZIONE_INVESTIMENTO,
		R.ID_VARIANTE,
		R.COD_VARIAZIONE,
		R.NON_COFINANZIATO
	FROM VRECUPERO_INVESTIMENTI R
		LEFT JOIN PIANO_INVESTIMENTI P ON R.ID_INVESTIMENTO = P.ID_INVESTIMENTO
	WHERE 1 = 1
		AND P.ID_INVESTIMENTO IS NULL
		AND ID_ACCORPAMENTO_INVESTIMENTI = @IdAccorpamentoInvestimenti;
	SET IDENTITY_INSERT PIANO_INVESTIMENTI OFF;

	-- RIPRISTINO LE VOCI GIA' PRESENTI
	UPDATE P
	SET  P.DESCRIZIONE = R.DESCRIZIONE,
		P.DATA_VARIAZIONE = R.DATA_VARIAZIONE,
		P.OPERATORE_VARIAZIONE = R.OPERATORE_VARIAZIONE,
		P.COD_TIPO_INVESTIMENTO = R.COD_TIPO_INVESTIMENTO,
		P.COD_STP = R.COD_STP,
		P.ID_UNITA_MISURA = R.ID_UNITA_MISURA,
		P.QUANTITA = R.QUANTITA,
		P.COSTO_INVESTIMENTO = R.COSTO_INVESTIMENTO,
		P.SPESE_GENERALI = R.SPESE_GENERALI,
		P.CONTRIBUTO_RICHIESTO = R.CONTRIBUTO_RICHIESTO,
		P.QUOTA_CONTRIBUTO_RICHIESTO = R.QUOTA_CONTRIBUTO_RICHIESTO,
		P.CONTRIBUTO_ALTRE_FONTI = R.CONTRIBUTO_ALTRE_FONTI,
		P.QUOTA_CONTRIBUTO_ALTRE_FONTI = R.QUOTA_CONTRIBUTO_ALTRE_FONTI,
		P.TASSO_ABBUONO = R.TASSO_ABBUONO,
		P.ID_SETTORE_PRODUTTIVO = R.ID_SETTORE_PRODUTTIVO,
		P.ID_PRIORITA_SETTORIALE = R.ID_PRIORITA_SETTORIALE,
		P.ID_OBIETTIVO_MISURA = R.ID_OBIETTIVO_MISURA,
		P.ID_CODIFICA_INVESTIMENTO = R.ID_CODIFICA_INVESTIMENTO,
		P.ID_DETTAGLIO_INVESTIMENTO = R.ID_DETTAGLIO_INVESTIMENTO,
		P.ID_SPECIFICA_INVESTIMENTO = R.ID_SPECIFICA_INVESTIMENTO,
		P.AMMESSO = R.AMMESSO,
		P.ISTRUTTORE = R.ISTRUTTORE,
		P.ID_INVESTIMENTO_ORIGINALE = R.ID_INVESTIMENTO_ORIGINALE,
		P.DATA_VALUTAZIONE = R.DATA_VALUTAZIONE,
		P.VALUTAZIONE_INVESTIMENTO = R.VALUTAZIONE_INVESTIMENTO,
		P.ID_VARIANTE = R.ID_VARIANTE,
		P.COD_VARIAZIONE = R.COD_VARIAZIONE,
		P.NON_COFINANZIATO = R.NON_COFINANZIATO
	FROM PIANO_INVESTIMENTI P 
		JOIN VRECUPERO_INVESTIMENTI R ON P.ID_INVESTIMENTO = R.ID_INVESTIMENTO;

	-- ### PRIORITA_X_INVESTIMENTI ###
	-- INSERISCO LE PRIORITA' ELIMINATE
	INSERT INTO PRIORITA_X_INVESTIMENTI (ID_PRIORITA, ID_INVESTIMENTO, ID_VALORE, SCELTO, VALORE, VAL_DATA, VAL_TESTO)
	SELECT 
		R.ID_PRIORITA,
		R.ID_INVESTIMENTO,
		R.ID_VALORE,
		R.SCELTO,
		R.VALORE,
		R.VAL_DATA,
		R.VAL_TESTO
	FROM VRECUPERO_PRIORITA_X_INVESTIMENTI R
		LEFT JOIN PRIORITA_X_INVESTIMENTI P ON R.ID_INVESTIMENTO = P.ID_INVESTIMENTO
												AND R.ID_PRIORITA = P.ID_PRIORITA
	WHERE 1 = 1
		AND P.ID_INVESTIMENTO IS NULL 
		AND P.ID_PRIORITA IS NULL
		AND ID_ACCORPAMENTO_INVESTIMENTI = @IdAccorpamentoInvestimenti;

	-- RIPRISTINO LE PRIORITA GIA' PRESENTI
	UPDATE P
	SET P.ID_PRIORITA = R.ID_PRIORITA,
		P.ID_INVESTIMENTO = R.ID_INVESTIMENTO,
		P.ID_VALORE = R.ID_VALORE,
		P.SCELTO = R.SCELTO,
		P.VALORE = R.VALORE,
		P.VAL_DATA = R.VAL_DATA,
		P.VAL_TESTO = R.VAL_TESTO
	FROM PRIORITA_X_INVESTIMENTI P 
		JOIN VRECUPERO_PRIORITA_X_INVESTIMENTI R ON R.ID_INVESTIMENTO = P.ID_INVESTIMENTO
												AND R.ID_PRIORITA = P.ID_PRIORITA;

	-- ### AUT_MODIFICA_PERC_AIUTO ###
	-- INSERISCO LE AUT_MODIFICA_PERC_AIUTO' ELIMINATE
	SET IDENTITY_INSERT AUT_MODIFICA_PERC_AIUTO ON;
	INSERT INTO AUT_MODIFICA_PERC_AIUTO (ID_AUTORIZZAZIONE, DATA_INSERIMENTO, CF_INSERIMENTO, DATA_MODIFICA, CF_MODIFICA, ID_INVESTIMENTO, COSTO_INVESTIMENTO_PRECEDENTE, COSTO_INVESTIMENTO_AUTORIZZATO, QUANTITA_PRECEDENTE, QUANTITA_AUTORIZZATA, PERC_PRECEDENTE, PERC_AUTORIZZATA)
	SELECT 
		R.ID_AUTORIZZAZIONE,
		R.DATA_INSERIMENTO,
		R.CF_INSERIMENTO,
		R.DATA_MODIFICA,
		R.CF_MODIFICA,
		R.ID_INVESTIMENTO,
		R.COSTO_INVESTIMENTO_PRECEDENTE,
		R.COSTO_INVESTIMENTO_AUTORIZZATO,
		R.QUANTITA_PRECEDENTE,
		R.QUANTITA_AUTORIZZATA,
		R.PERC_PRECEDENTE,
		R.PERC_AUTORIZZATA
	FROM VRECUPERO_AUT_MODIFICA_PERC_AIUTO R
		LEFT JOIN AUT_MODIFICA_PERC_AIUTO P ON R.ID_AUTORIZZAZIONE = P.ID_AUTORIZZAZIONE
	WHERE 1 = 1
		AND P.ID_AUTORIZZAZIONE IS NULL
		AND ID_ACCORPAMENTO_INVESTIMENTI = @IdAccorpamentoInvestimenti;
	SET IDENTITY_INSERT AUT_MODIFICA_PERC_AIUTO OFF;

	-- RIPRISTINO LE AUT_MODIFICA_PERC_AIUTO GIA' PRESENTI
	UPDATE P
	SET P.DATA_INSERIMENTO = R.DATA_INSERIMENTO,
		P.CF_INSERIMENTO = R.CF_INSERIMENTO,
		P.DATA_MODIFICA = R.DATA_MODIFICA,
		P.CF_MODIFICA = R.CF_MODIFICA,
		P.ID_INVESTIMENTO = R.ID_INVESTIMENTO,
		P.COSTO_INVESTIMENTO_PRECEDENTE = R.COSTO_INVESTIMENTO_PRECEDENTE,
		P.COSTO_INVESTIMENTO_AUTORIZZATO = R.COSTO_INVESTIMENTO_AUTORIZZATO,
		P.QUANTITA_PRECEDENTE = R.QUANTITA_PRECEDENTE,
		P.QUANTITA_AUTORIZZATA = R.QUANTITA_AUTORIZZATA,
		P.PERC_PRECEDENTE = R.PERC_PRECEDENTE,
		P.PERC_AUTORIZZATA = R.PERC_AUTORIZZATA
	FROM AUT_MODIFICA_PERC_AIUTO P 
		JOIN VRECUPERO_AUT_MODIFICA_PERC_AIUTO R ON R.ID_AUTORIZZAZIONE = P.ID_AUTORIZZAZIONE;

	-- ### CORRETTIVA_RENDICONTAZIONE_SPOSTAMENTI ###
	-- INSERISCO LE CORRETTIVA_RENDICONTAZIONE_SPOSTAMENTI ELIMINATE
	SET IDENTITY_INSERT CORRETTIVA_RENDICONTAZIONE_SPOSTAMENTI ON;
	INSERT INTO CORRETTIVA_RENDICONTAZIONE_SPOSTAMENTI (ID, ID_CORRETTIVA, ID_INVESTIMENTO_DA, ID_INVESTIMENTO_A, IMPORTO_SPOSTATO, CONCLUSO, ANNULLATO, ID_UTENTE, DATA, DESCRIZIONE, ID_JSON_LOG)
	SELECT 
		R.ID,
		R.ID_CORRETTIVA,
		R.ID_INVESTIMENTO_DA,
		R.ID_INVESTIMENTO_A,
		R.IMPORTO_SPOSTATO,
		R.CONCLUSO,
		R.ANNULLATO,
		R.ID_UTENTE,
		R.DATA,
		R.DESCRIZIONE,
		R.ID_JSON_LOG
	FROM VRECUPERO_CORRETTIVA_RENDICONTAZIONE_SPOSTAMENTI R
		LEFT JOIN CORRETTIVA_RENDICONTAZIONE_SPOSTAMENTI P ON R.ID = P.ID
	WHERE 1 = 1
		AND P.ID IS NULL
		AND ID_ACCORPAMENTO_INVESTIMENTI = @IdAccorpamentoInvestimenti;
	SET IDENTITY_INSERT CORRETTIVA_RENDICONTAZIONE_SPOSTAMENTI OFF;

	-- RIPRISTINO LE CORRETTIVA_RENDICONTAZIONE_SPOSTAMENTI GIA' PRESENTI
	UPDATE P
	SET P.ID_CORRETTIVA = R.ID_CORRETTIVA,
		P.ID_INVESTIMENTO_DA = R.ID_INVESTIMENTO_DA,
		P.ID_INVESTIMENTO_A = R.ID_INVESTIMENTO_A,
		P.IMPORTO_SPOSTATO = R.IMPORTO_SPOSTATO,
		P.CONCLUSO = R.CONCLUSO,
		P.ANNULLATO = R.ANNULLATO,
		P.ID_UTENTE = R.ID_UTENTE,
		P.DATA = R.DATA,
		P.DESCRIZIONE = R.DESCRIZIONE,
		P.ID_JSON_LOG = R.ID_JSON_LOG
	FROM CORRETTIVA_RENDICONTAZIONE_SPOSTAMENTI P 
		JOIN VRECUPERO_CORRETTIVA_RENDICONTAZIONE_SPOSTAMENTI R ON R.ID = P.ID;

	-- ### PAGAMENTI_RICHIESTI ###
	-- INSERISCO LE PAGAMENTI_RICHIESTI ELIMINATE
	SET IDENTITY_INSERT PAGAMENTI_RICHIESTI ON;
	INSERT INTO PAGAMENTI_RICHIESTI (ID_PAGAMENTO_RICHIESTO, ID_DOMANDA_PAGAMENTO, ID_INVESTIMENTO, DATA_RICHIESTA_PAGAMENTO, IMPORTO_COMPUTO_METRICO, IMPORTO_RICHIESTO, CONTRIBUTO_RICHIESTO, CONTRIBUTO_RICHIESTO_ALTRE_FONTI, IMPORTO_DISAVANZO_COSTI_AMMESSI, CONTRIBUTO_DISAVANZO_COSTI_AMMESSI, CONTRIBUTO_RICHIESTO_RECUPERO_ANTICIPO, IMPORTO_COMPUTO_METRICO_AMMESSO, IMPORTO_AMMESSO, CONTRIBUTO_AMMESSO, CONTRIBUTO_AMMESSO_ALTRE_FONTI, CONTRIBUTO_AMMESSO_RECUPERO_ANTICIPO, AMMESSO, ISTRUTTORE, DATA_VALUTAZIONE, NOTE_ISTRUTTORE, COD_SANZIONE_VARIAZIONE_INVESTIMENTI)
	SELECT 
		R.ID_PAGAMENTO_RICHIESTO,
		R.ID_DOMANDA_PAGAMENTO,
		R.ID_INVESTIMENTO,
		R.DATA_RICHIESTA_PAGAMENTO,
		R.IMPORTO_COMPUTO_METRICO,
		R.IMPORTO_RICHIESTO,
		R.CONTRIBUTO_RICHIESTO,
		R.CONTRIBUTO_RICHIESTO_ALTRE_FONTI,
		R.IMPORTO_DISAVANZO_COSTI_AMMESSI,
		R.CONTRIBUTO_DISAVANZO_COSTI_AMMESSI,
		R.CONTRIBUTO_RICHIESTO_RECUPERO_ANTICIPO,
		R.IMPORTO_COMPUTO_METRICO_AMMESSO,
		R.IMPORTO_AMMESSO,
		R.CONTRIBUTO_AMMESSO,
		R.CONTRIBUTO_AMMESSO_ALTRE_FONTI,
		R.CONTRIBUTO_AMMESSO_RECUPERO_ANTICIPO,
		R.AMMESSO,
		R.ISTRUTTORE,
		R.DATA_VALUTAZIONE,
		R.NOTE_ISTRUTTORE,
		R.COD_SANZIONE_VARIAZIONE_INVESTIMENTI
	FROM VRECUPERO_PAGAMENTI_RICHIESTI R
		LEFT JOIN PAGAMENTI_RICHIESTI P ON R.ID_PAGAMENTO_RICHIESTO = P.ID_PAGAMENTO_RICHIESTO
	WHERE 1 = 1
		AND P.ID_PAGAMENTO_RICHIESTO IS NULL
		AND ID_ACCORPAMENTO_INVESTIMENTI = @IdAccorpamentoInvestimenti;
	SET IDENTITY_INSERT PAGAMENTI_RICHIESTI OFF;

	-- RIPRISTINO LE PAGAMENTI_RICHIESTI GIA' PRESENTI
	UPDATE P
	SET  P.ID_INVESTIMENTO = R.ID_INVESTIMENTO,
		P.DATA_RICHIESTA_PAGAMENTO = R.DATA_RICHIESTA_PAGAMENTO,
		P.IMPORTO_COMPUTO_METRICO = R.IMPORTO_COMPUTO_METRICO,
		P.IMPORTO_RICHIESTO = R.IMPORTO_RICHIESTO,
		p.CONTRIBUTO_RICHIESTO = R.CONTRIBUTO_RICHIESTO,
		P.CONTRIBUTO_RICHIESTO_ALTRE_FONTI = R.CONTRIBUTO_RICHIESTO_ALTRE_FONTI,
		P.IMPORTO_DISAVANZO_COSTI_AMMESSI = R.IMPORTO_DISAVANZO_COSTI_AMMESSI,
		P.CONTRIBUTO_DISAVANZO_COSTI_AMMESSI = R.CONTRIBUTO_DISAVANZO_COSTI_AMMESSI,
		P.CONTRIBUTO_RICHIESTO_RECUPERO_ANTICIPO = R.CONTRIBUTO_RICHIESTO_RECUPERO_ANTICIPO,
		P.IMPORTO_COMPUTO_METRICO_AMMESSO = R.IMPORTO_COMPUTO_METRICO_AMMESSO,
		P.IMPORTO_AMMESSO = R.IMPORTO_AMMESSO,
		P.CONTRIBUTO_AMMESSO = R.CONTRIBUTO_AMMESSO,
		P.CONTRIBUTO_AMMESSO_ALTRE_FONTI = R.CONTRIBUTO_AMMESSO_ALTRE_FONTI,
		P.CONTRIBUTO_AMMESSO_RECUPERO_ANTICIPO = R.CONTRIBUTO_AMMESSO_RECUPERO_ANTICIPO,
		P.AMMESSO = R.AMMESSO,
		P.ISTRUTTORE = R.ISTRUTTORE,
		P.DATA_VALUTAZIONE = R.DATA_VALUTAZIONE,
		P.NOTE_ISTRUTTORE = R.NOTE_ISTRUTTORE,
		P.COD_SANZIONE_VARIAZIONE_INVESTIMENTI = R.COD_SANZIONE_VARIAZIONE_INVESTIMENTI
	FROM PAGAMENTI_RICHIESTI P 
		JOIN VRECUPERO_PAGAMENTI_RICHIESTI R ON P.ID_PAGAMENTO_RICHIESTO = R.ID_PAGAMENTO_RICHIESTO;

	-- ### PAGAMENTI_BENEFICIARIO ###
	-- INSERISCO LE PAGAMENTI_BENEFICIARIO ELIMINATE
	SET IDENTITY_INSERT PAGAMENTI_BENEFICIARIO ON;
	INSERT INTO PAGAMENTI_BENEFICIARIO (ID_PAGAMENTO_BENEFICIARIO, ID_PAGAMENTO_RICHIESTO, ID_GIUSTIFICATIVO, IMPORTO_RICHIESTO, IMPORTO_AMMESSO, CONTRIBUTO_AMMESSO, QUOTA_CONTRIBUTO_AMMESSO, COD_RIDUZIONE, MOTIVAZIONE_RIDUZIONE, IMPORTO_NONAMM_NONRESP, IMPORTO_AMMESSO_CONTR, IMPORTO_NONAMM_CONTR_NONRESP, SPESA_TECNICA_RICHIESTA, SPESA_TECNICA_AMMESSA, SPESA_TECNICA_AMMESSA_CONTR, COSTITUISCE_VARIANTE, COD_RIDUZIONE_CONTR, MOTIVAZIONE_RIDUZIONE_CONTR)
	SELECT 
		R.ID_PAGAMENTO_BENEFICIARIO,
		R.ID_PAGAMENTO_RICHIESTO,
		R.ID_GIUSTIFICATIVO,
		R.IMPORTO_RICHIESTO,
		R.IMPORTO_AMMESSO,
		R.CONTRIBUTO_AMMESSO,
		R.QUOTA_CONTRIBUTO_AMMESSO,
		R.COD_RIDUZIONE,
		R.MOTIVAZIONE_RIDUZIONE,
		R.IMPORTO_NONAMM_NONRESP,
		R.IMPORTO_AMMESSO_CONTR,
		R.IMPORTO_NONAMM_CONTR_NONRESP,
		R.SPESA_TECNICA_RICHIESTA,
		R.SPESA_TECNICA_AMMESSA,
		R.SPESA_TECNICA_AMMESSA_CONTR,
		R.COSTITUISCE_VARIANTE,
		R.COD_RIDUZIONE_CONTR,
		R.MOTIVAZIONE_RIDUZIONE_CONTR
	FROM VRECUPERO_PAGAMENTI_BENEFICIARIO R
		LEFT JOIN PAGAMENTI_BENEFICIARIO P ON R.ID_PAGAMENTO_BENEFICIARIO = P.ID_PAGAMENTO_BENEFICIARIO
	WHERE 1 = 1
		AND P.ID_PAGAMENTO_BENEFICIARIO IS NULL
		AND ID_ACCORPAMENTO_INVESTIMENTI = @IdAccorpamentoInvestimenti;
	SET IDENTITY_INSERT PAGAMENTI_BENEFICIARIO OFF;

	-- RIPRISTINO LE PAGAMENTI_RICHIESTI GIA' PRESENTI
	UPDATE P
	SET  P.ID_PAGAMENTO_RICHIESTO = R.ID_PAGAMENTO_RICHIESTO,
		P.ID_GIUSTIFICATIVO = R.ID_GIUSTIFICATIVO,
		P.IMPORTO_RICHIESTO = R.IMPORTO_RICHIESTO,
		P.IMPORTO_AMMESSO = R.IMPORTO_AMMESSO,
		P.CONTRIBUTO_AMMESSO = R.CONTRIBUTO_AMMESSO,
		P.QUOTA_CONTRIBUTO_AMMESSO = R.QUOTA_CONTRIBUTO_AMMESSO,
		P.COD_RIDUZIONE = R.COD_RIDUZIONE,
		P.MOTIVAZIONE_RIDUZIONE = R.MOTIVAZIONE_RIDUZIONE,
		P.IMPORTO_NONAMM_NONRESP = R.IMPORTO_NONAMM_NONRESP,
		P.IMPORTO_AMMESSO_CONTR = R.IMPORTO_AMMESSO_CONTR,
		P.IMPORTO_NONAMM_CONTR_NONRESP = R.IMPORTO_NONAMM_CONTR_NONRESP,
		P.SPESA_TECNICA_RICHIESTA = R.SPESA_TECNICA_RICHIESTA,
		P.SPESA_TECNICA_AMMESSA = R.SPESA_TECNICA_AMMESSA,
		P.SPESA_TECNICA_AMMESSA_CONTR = R.SPESA_TECNICA_AMMESSA_CONTR,
		P.COSTITUISCE_VARIANTE = R.COSTITUISCE_VARIANTE,
		P.COD_RIDUZIONE_CONTR = R.COD_RIDUZIONE_CONTR,
		P.MOTIVAZIONE_RIDUZIONE_CONTR = R.MOTIVAZIONE_RIDUZIONE_CONTR
	FROM PAGAMENTI_BENEFICIARIO P 
		JOIN VRECUPERO_PAGAMENTI_BENEFICIARIO R ON P.ID_PAGAMENTO_BENEFICIARIO = R.ID_PAGAMENTO_BENEFICIARIO;

GO