CREATE PROCEDURE [dbo].[SpZoomRicercaFornitoriProgetto]
(
	@PATTERN VARCHAR(50) = NULL,
	@IDPROGETTO INT
)
AS
	SELECT DISTINCT TOP 8
		CF_FORNITORE,
		DESCRIZIONE_FORNITORE
	FROM GIUSTIFICATIVI
	WHERE 1 = 1
		AND ID_PROGETTO = @IDPROGETTO
		AND (CF_FORNITORE LIKE '%'+@PATTERN+'%'
			OR DESCRIZIONE_FORNITORE LIKE '%'+@PATTERN+'%');
GO