CREATE PROCEDURE [dbo].[ZVcruscottoVariantiFindFind]
(
	@IdUtenteIstruttoreequalthis INT, 
	@IdOperatoreFirmaComitatoequalthis INT
)
AS
	declare @sql nvarchar(4000);
	declare @lensql int;
	set @lensql=0;
	SET @sql = 'SELECT ID_BANDO, DESCRIZIONE_BANDO, DATA_SCADENZA_BANDO, ID_PROGETTO, STATO, ID_IMPRESA, IMPRESA, ID_VARIANTE, COD_TIPO, DATA_INSERIMENTO, COD_ENTE, SEGNATURA, SEGNATURA_ALLEGATI, DATA_MODIFICA, SEGNATURA_APPROVAZIONE, APPROVATA, ID_UTENTE_ISTRUTTORE, ISTRUTTORE, NOTE_ISTRUTTORE, TIPO_VARIANTE, NOMINATIVO, PROFILO, ENTE, DATA_APPROVAZIONE, PROVINCIA, DESCRIZIONE, ANNULLATA, SEGNATURA_ANNULLAMENTO, CF_OPERATORE_ANNULLAMENTO, DATA_ANNULLAMENTO, NOMINATIVO_OPERATORE_ANNULLAMENTO, NOMINATIVO_ISTRUTTORE, CUAA_ENTRANTE, ID_FASCICOLO_ENTRANTE, CUAA_USCENTE, ID_FASCICOLO_USCENTE, RAGSOC_USCENTE, ID_ATTO_APPROVAZIONE, COD_DEFINIZIONE, ID_PROGETTO_VALUTAZIONE, ORDINE, ORDINE_FIRMA, ID_OPERATORE_FIRMA_COMITATO, OPERATORE_FIRMA_COMITATO FROM VCRUSCOTTO_VARIANTI WHERE 1=1';
	IF (@IdUtenteIstruttoreequalthis IS NOT NULL) BEGIN SET @sql = @sql + ' AND (ID_UTENTE_ISTRUTTORE = @IdUtenteIstruttoreequalthis)'; set @lensql=@lensql+len(@IdUtenteIstruttoreequalthis);end;
	IF (@IdOperatoreFirmaComitatoequalthis IS NOT NULL) BEGIN SET @sql = @sql + ' AND (ID_OPERATORE_FIRMA_COMITATO = @IdOperatoreFirmaComitatoequalthis)'; set @lensql=@lensql+len(@IdOperatoreFirmaComitatoequalthis);end;
	set @sql = @sql + 'ORDER BY DATA_SCADENZA_BANDO ASC, ID_PROGETTO ASC, ID_VARIANTE ASC';
	set @lensql=@lensql+len(@sql);
	if (@lensql<3000)
	exec sp_executesql @sql,N'@IdUtenteIstruttoreequalthis INT, @IdOperatoreFirmaComitatoequalthis INT',@IdUtenteIstruttoreequalthis , @IdOperatoreFirmaComitatoequalthis ;
	else
		SELECT ID_BANDO, DESCRIZIONE_BANDO, DATA_SCADENZA_BANDO, ID_PROGETTO, STATO, ID_IMPRESA, IMPRESA, ID_VARIANTE, COD_TIPO, DATA_INSERIMENTO, COD_ENTE, SEGNATURA, SEGNATURA_ALLEGATI, DATA_MODIFICA, SEGNATURA_APPROVAZIONE, APPROVATA, ID_UTENTE_ISTRUTTORE, ISTRUTTORE, NOTE_ISTRUTTORE, TIPO_VARIANTE, NOMINATIVO, PROFILO, ENTE, DATA_APPROVAZIONE, PROVINCIA, DESCRIZIONE, ANNULLATA, SEGNATURA_ANNULLAMENTO, CF_OPERATORE_ANNULLAMENTO, DATA_ANNULLAMENTO, NOMINATIVO_OPERATORE_ANNULLAMENTO, NOMINATIVO_ISTRUTTORE, CUAA_ENTRANTE, ID_FASCICOLO_ENTRANTE, CUAA_USCENTE, ID_FASCICOLO_USCENTE, RAGSOC_USCENTE, ID_ATTO_APPROVAZIONE, COD_DEFINIZIONE, ID_PROGETTO_VALUTAZIONE, ORDINE, ORDINE_FIRMA, ID_OPERATORE_FIRMA_COMITATO, OPERATORE_FIRMA_COMITATO
		FROM VCRUSCOTTO_VARIANTI
		WHERE 
			((@IdUtenteIstruttoreequalthis IS NULL) OR ID_UTENTE_ISTRUTTORE = @IdUtenteIstruttoreequalthis) AND 
			((@IdOperatoreFirmaComitatoequalthis IS NULL) OR ID_OPERATORE_FIRMA_COMITATO = @IdOperatoreFirmaComitatoequalthis)
		ORDER BY DATA_SCADENZA_BANDO ASC, ID_PROGETTO ASC, ID_VARIANTE ASC

GO