CREATE TABLE [dbo].[DISPOSIZIONE] (
    [ID_DISPOSIZIONE]          INT            IDENTITY (1, 1) NOT NULL,
    [DATA_INSERIMENTO]         DATETIME       CONSTRAINT [DF_DISPOSIZIONE_DATA_INSERIMENTO] DEFAULT (getdate()) NULL,
    [CF_INSERIMENTO]           VARCHAR (16)   NULL,
    [DATA_MODIFICA]            DATETIME       CONSTRAINT [DF_DISPOSIZIONE_DATA_MODIFICA] DEFAULT (getdate()) NULL,
    [CF_MODIFICA]              VARCHAR (16)   NULL,
    [ID_TIPO_DISPOSIZIONE]     INT            NULL,
    [NUMERO]                   VARCHAR (50)   NULL,
    [ANNO]                     INT            NULL,
    [ARTICOLO_PARAGRAFO]       VARCHAR (50)   NULL,
    [DISPOSIZIONE_NAZIONALE]   VARCHAR (2000) NULL,
    [ID_REGISTRO_IRREGOLARITA] INT            NULL,
	[ID_IRREGOLARITA]			INT           NULL,
	[NAZIONALE] BIT            CONSTRAINT [DF_DISPOSIZIONE_NAZIONALE] DEFAULT 0,
	[REGIONALE] BIT            CONSTRAINT [DF_DISPOSIZIONE_NAZIONALE] DEFAULT 0,
    CONSTRAINT [PK_DISPOSIZIONE] PRIMARY KEY CLUSTERED ([ID_DISPOSIZIONE] ASC),
    CONSTRAINT [FK_DISPOSIZIONE_CODIFICA_GENERICA] FOREIGN KEY ([ID_TIPO_DISPOSIZIONE]) REFERENCES [dbo].[CODIFICA_GENERICA] ([ID]),
    CONSTRAINT [FK_DISPOSIZIONE_REGISTRO_IRREGOLARITA] FOREIGN KEY ([ID_REGISTRO_IRREGOLARITA]) REFERENCES [dbo].[REGISTRO_IRREGOLARITA] ([ID_IRREGOLARITA]),
	CONSTRAINT [FK_DISPOSIZIONE_IRREGOLARITA] FOREIGN KEY ([ID_IRREGOLARITA]) REFERENCES [dbo].[IRREGOLARITA] ([ID_IRREGOLARITA])
);

