-- IRREGOLARITA'
CREATE TABLE IRREGOLARITA
(
	ID_IRREGOLARITA INT IDENTITY (1, 1) NOT NULL PRIMARY KEY,
	CF_INSERIMENTO VARCHAR(16) NOT NULL,
	DATA_INSERIMENTO DATETIME NOT NULL,
	CF_MODIFICA VARCHAR(16) NOT NULL,
	DATA_MODIFICA DATETIME NOT NULL DEFAULT GETDATE(),

	ID_PROGETTO INT NOT NULL, --FK
	ID_TIPO_IRREGOLARITA INT NOT NULL, --FK
	
	-- CAMPI INDIVIDUAZIONE DELL'IRREGOLARITA (EX ORIGINE CONTROLLO)
	ID_CONTROLLO_ORIGINE INT, --FK
	SOSPETTO_FRODE BIT,
	DATA_COSTATAZIONE_AMMINISTRATIVA DATETIME DEFAULT GETDATE(),
	IMPORTO_IRREGOLARE_DA_RECUPERARE BIT,
	SEGNALAZIONE_OLAF BIT,
	DATA_SEGNALAZIONE_OLAF DATETIME, -- SOLO SE SEGNALAZIONE_OLAF = 1
	DATA_SEGNALAZIONE_OLAF_DA DATETIME, -- SOLO SE SEGNALAZIONE_OLAF = 1
	DATA_SEGNALAZIONE_OLAF_A DATETIME, -- SOLO SE SEGNALAZIONE_OLAF = 1
	TRIMESTRE_SEGNALAZIONE_OLAF VARCHAR(MAX), -- SOLO SE SEGNALAZIONE_OLAF = 1
	DATA_PRIMA_INFORMAZIONE DATETIME, -- SOLO SE SEGNALAZIONE_OLAF = 1
	FONTE_PRIMA_INFORMAZIONE VARCHAR(MAX), -- SOLO SE SEGNALAZIONE_OLAF = 1

	-- CAMPI IDENTIFICAZIONE DELLE PERSONE IMPLICATE 
	ID_IMPRESA_COMMESSA_DA INT, --FK
	NOTE_COMMESSA_DA VARCHAR(MAX),
	ID_CATEGORIA INT, --FK
	ID_TIPO INT, --FK,
	ID_CLASSIFICAZIONE INT, --FK
	PRATICHE_UTILIZZATE VARCHAR(MAX),

	-- DISPOSIZIONI TRASGREDITE NELLA TABELLA DISPOSIZIONE

	-- GIUSTIFICATIVI ASSOCIATI IN UNA NUOVA STRUTTURA -> SPESE_IRREGOLARI
	NOTE_GIUSTIFICATIVI VARCHAR(MAX),

	-- IMPATTO FINANZIARIO
	IMPORTO_SPESA DECIMAL(15,2),
	CONTRIBUTO_AMMESSO DECIMAL(15,2),
	CONTRIBUTO_PUBBLICO DECIMAL(15,2),
	CONTRIBUTO_AMMESSO_CERTIFICATO DECIMAL(15,2),
	CONTRIBUTO_PUBBLICO_CERTIFICATO DECIMAL(15,2),
	CONTRIBUTO_PUBBLICO_DA_RECUPERARE DECIMAL(15,2),
	COMMENTI_IMPATTI_FINANZIARIO VARCHAR(MAX),

	-- PROCEDURE DI RECUPERO
	PROCEDIMENTO_AMMINISTRATIVO BIT,
	AZIONE_GIUDIZIARIA BIT,
	AZIONE_PENALE BIT,
	ID_STATO_FINANZIARIO INT, --FK
	STABILITA_OPERAZIONI BIT
);
GO

ALTER TABLE IRREGOLARITA  WITH CHECK ADD CONSTRAINT [FK_IRREGOLARITA_PROGETTO] FOREIGN KEY(ID_PROGETTO)
REFERENCES PROGETTO (ID_PROGETTO)
GO

ALTER TABLE IRREGOLARITA CHECK CONSTRAINT [FK_IRREGOLARITA_PROGETTO]
GO

ALTER TABLE IRREGOLARITA  WITH CHECK ADD CONSTRAINT [FK_IRREGOLARITA_TIPO_IRREGOLARITA] FOREIGN KEY(ID_TIPO_IRREGOLARITA)
REFERENCES TIPO_IRREGOLARITA (ID_TIPO)
GO

ALTER TABLE IRREGOLARITA CHECK CONSTRAINT [FK_IRREGOLARITA_TIPO_IRREGOLARITA]
GO

ALTER TABLE IRREGOLARITA  WITH CHECK ADD CONSTRAINT [FK_IRREGOLARITA_TIPO_IMPRESA] FOREIGN KEY(ID_IMPRESA_COMMESSA_DA)
REFERENCES IMPRESA (ID_IMPRESA)
GO

ALTER TABLE IRREGOLARITA CHECK CONSTRAINT [FK_IRREGOLARITA_TIPO_IMPRESA]
GO

ALTER TABLE IRREGOLARITA  WITH CHECK ADD  CONSTRAINT [FK_IRREGOLARITA_CODIFICA_GENERICA_CONTROLLO_ORIGINE] FOREIGN KEY(ID_CONTROLLO_ORIGINE)
REFERENCES CODIFICA_GENERICA (ID)
GO

ALTER TABLE IRREGOLARITA CHECK CONSTRAINT [FK_IRREGOLARITA_CODIFICA_GENERICA_CONTROLLO_ORIGINE]
GO

ALTER TABLE IRREGOLARITA  WITH CHECK ADD  CONSTRAINT [FK_IRREGOLARITA_CODIFICA_GENERICA_CATEGORIA] FOREIGN KEY(ID_CATEGORIA)
REFERENCES CODIFICA_GENERICA (ID)
GO

ALTER TABLE IRREGOLARITA CHECK CONSTRAINT [FK_IRREGOLARITA_CODIFICA_GENERICA_CATEGORIA]
GO

ALTER TABLE IRREGOLARITA  WITH CHECK ADD  CONSTRAINT [FK_IRREGOLARITA_CODIFICA_GENERICA_TIPO] FOREIGN KEY(ID_TIPO)
REFERENCES CODIFICA_GENERICA (ID)
GO

ALTER TABLE IRREGOLARITA CHECK CONSTRAINT [FK_IRREGOLARITA_CODIFICA_GENERICA_TIPO]
GO

ALTER TABLE IRREGOLARITA  WITH CHECK ADD  CONSTRAINT [FK_IRREGOLARITA_CODIFICA_GENERICA_CLASSIFICAZIONE] FOREIGN KEY(ID_CLASSIFICAZIONE)
REFERENCES CODIFICA_GENERICA (ID)
GO

ALTER TABLE IRREGOLARITA CHECK CONSTRAINT [FK_IRREGOLARITA_CODIFICA_GENERICA_CLASSIFICAZIONE]
GO

ALTER TABLE IRREGOLARITA  WITH CHECK ADD  CONSTRAINT [FK_IRREGOLARITA_CODIFICA_GENERICA_STATO_FINANZIARIO] FOREIGN KEY(ID_STATO_FINANZIARIO)
REFERENCES CODIFICA_GENERICA (ID)
GO

ALTER TABLE IRREGOLARITA CHECK CONSTRAINT [FK_IRREGOLARITA_CODIFICA_GENERICA_STATO_FINANZIARIO]
GO
