-- TABELLA ASSOCIAZIONE SPESE/GIUSTIFICATIVI ALL'IRREGOLARITA
-- DROP TABLE SPESA_IRREGOLARE;
CREATE TABLE SPESA_IRREGOLARE
(
	ID_SPESA_IRREGOLARE INT IDENTITY (1, 1) NOT NULL PRIMARY KEY,
	CF_INSERIMENTO VARCHAR(16) NOT NULL,
	DATA_INSERIMENTO DATETIME NOT NULL,
	CF_MODIFICA VARCHAR(16) NOT NULL,
	DATA_MODIFICA DATETIME NOT NULL DEFAULT GETDATE(),
	
	ID_IRREGOLARITA INT NOT NULL, --FK
	ID_SPESA INT NOT NULL, --FK

	IMPORTO_IRREGOLARE DECIMAL(15,2) NOT NULL
);
GO

ALTER TABLE SPESA_IRREGOLARE  WITH CHECK ADD CONSTRAINT [FK_SPESA_IRREGOLARE_IRREGOLARITA] FOREIGN KEY(ID_IRREGOLARITA)
REFERENCES IRREGOLARITA (ID_IRREGOLARITA)
GO

ALTER TABLE SPESA_IRREGOLARE CHECK CONSTRAINT [FK_SPESA_IRREGOLARE_IRREGOLARITA]
GO

ALTER TABLE SPESA_IRREGOLARE  WITH CHECK ADD CONSTRAINT [FK_SPESA_IRREGOLARE_SPESA] FOREIGN KEY(ID_SPESA)
REFERENCES SPESE_SOSTENUTE (ID_SPESA)
GO

ALTER TABLE SPESA_IRREGOLARE CHECK CONSTRAINT [FK_SPESA_IRREGOLARE_SPESA]
GO