SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[COD_TIPO_TERRITORIO](
	[ID_COD_TIPO_TERRITORIO] [int] NOT NULL,
	[MIN_ABITANTI] [int] NULL,
	[MAX_ABITANTI] [int] NULL,
 CONSTRAINT [PK_COD_TIPO_TERRITORIO] PRIMARY KEY CLUSTERED 
(
	[ID_COD_TIPO_TERRITORIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
