SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[COD_TIPO_NUTS](
	[ID_COD_NUTS] [int] NOT NULL,
	[COD_NUTS] [varchar](50) NOT NULL,
 CONSTRAINT [PK_COD_TIPO_NUTS] PRIMARY KEY CLUSTERED 
(
	[ID_COD_NUTS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO