SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SFC_NACE](
	[ID_SFC_NACE] [int] IDENTITY(1,1) NOT NULL,
	[COD_TIPO_ATECO_2007] [char](9) NOT NULL,
	[COD_NACE] [int] NULL,
 CONSTRAINT [PK_SFC_NACE_1] PRIMARY KEY CLUSTERED 
(
	[ID_SFC_NACE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
