SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SFC_POP_COMUNI](
	[ID_SFC_POP_COMUNI] [int] IDENTITY(1,1) NOT NULL,
	[DENOMINAZIONE] [varchar](max) NOT NULL,
	[ABITANTI] [int] NULL,
	[COD_TERRITORIO] [int] NULL,
	[ID_COMUNE] [int] NULL,
 CONSTRAINT [PK_SFC_POP_COMUNI] PRIMARY KEY CLUSTERED 
(
	[ID_SFC_POP_COMUNI] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[SFC_POP_COMUNI]  WITH CHECK ADD  CONSTRAINT [FK_SFC_POP_COMUNI_COMUNI] FOREIGN KEY([ID_COMUNE])
REFERENCES [dbo].[COMUNI] ([ID_COMUNE])
GO

ALTER TABLE [dbo].[SFC_POP_COMUNI] CHECK CONSTRAINT [FK_SFC_POP_COMUNI_COMUNI]
GO
