CREATE TABLE [dbo].[TIPO_MODIFICA_GENERALE](
	[ID_TIPO_MODIFICA] [INT] IDENTITY(1,1) NOT NULL,
	[DESCRIZIONE] [VARCHAR](MAX) NOT NULL,
	[ATTIVO] [BIT] NOT NULL,
 CONSTRAINT [PK_TIPO_MODIFICA_GENERALE] PRIMARY KEY CLUSTERED 
(
	[ID_TIPO_MODIFICA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[TIPO_MODIFICA_GENERALE] ADD  CONSTRAINT [DF_TIPO_MODIFICA_GENERALE_ATTIVO]  DEFAULT ((1)) FOR [ATTIVO]
GO

/*
INSERT INTO TIPO_MODIFICA_GENERALE
	(DESCRIZIONE, ATTIVO)
VALUES
	('Priorita', 1), --PrioritaXProgetto
	('Indicatori', 1), --ProgettoIndicatori
	('Requisiti', 1); --DomandaPagamentoRequisiti
*/