CREATE VIEW VCRUSCOTTO_VARIANTI
AS 
SELECT 
	BAN.ID_BANDO AS ID_BANDO,
	BAN.DESCRIZIONE AS DESCRIZIONE_BANDO,
	BAN.DATA_SCADENZA AS DATA_SCADENZA_BANDO,
	PROG.ID_PROGETTO AS ID_PROGETTO,
	PROG.STATO,
	IMP.ID_IMPRESA,
	IMP.RAGIONE_SOCIALE AS IMPRESA, 
	VARI.ID_VARIANTE,
	COD_TIPO, 
	VARI.DATA_INSERIMENTO,
	VARI.COD_ENTE, 
	VARI.SEGNATURA, 
	VARI.SEGNATURA_ALLEGATI, 
	VARI.DATA_MODIFICA,
	SEGNATURA_APPROVAZIONE,
	APPROVATA, 
	UT.ID_UTENTE AS ID_UTENTE_ISTRUTTORE,
	ISTRUTTORE, 
	NOTE_ISTRUTTORE, 
	TIPO_VARIANTE, 
	VARI.NOMINATIVO, 
	VARI.PROFILO, 
	VARI.ENTE,
	DATA_APPROVAZIONE, 
	VARI.PROVINCIA, 
	VARI.DESCRIZIONE, 
	ANNULLATA, 
	SEGNATURA_ANNULLAMENTO, 
	CF_OPERATORE_ANNULLAMENTO, 
	DATA_ANNULLAMENTO,
	NOMINATIVO_OPERATORE_ANNULLAMENTO, 
	NOMINATIVO_ISTRUTTORE,
	CUAA_ENTRANTE, 
	ID_FASCICOLO_ENTRANTE,
	CUAA_USCENTE, 
	ID_FASCICOLO_USCENTE, 
	RAGSOC_USCENTE,
	ID_ATTO_APPROVAZIONE, 
	COD_DEFINIZIONE,
	PVALUTATORI.ID_PROGETTO_VALUTAZIONE,
	PVALUTATORI.ORDINE,
	PVALUTAZIONE.ORDINE_FIRMA,
	UTV.ID_UTENTE AS ID_OPERATORE_FIRMA_COMITATO,
	UTV.NOMINATIVO AS OPERATORE_FIRMA_COMITATO
FROM VPROGETTO PROG 
	JOIN vIMPRESA IMP ON IMP.ID_IMPRESA = PROG.ID_IMPRESA
	JOIN VBANDO BAN ON BAN.ID_BANDO = PROG.ID_BANDO
	JOIN VVARIANTI VARI ON VARI.ID_PROGETTO = PROG.ID_PROGETTO
	LEFT JOIN VUTENTI UT ON UT.CF_UTENTE = VARI.ISTRUTTORE
	LEFT JOIN PROGETTO_VALUTAZIONE PVALUTAZIONE ON PVALUTAZIONE.ID_VARIANTE = VARI.ID_VARIANTE
	LEFT JOIN PROGETTO_VALUTATORI PVALUTATORI ON (PVALUTATORI.ID_PROGETTO_VALUTAZIONE = PVALUTAZIONE.ID
												AND PVALUTATORI.ORDINE = (PVALUTAZIONE.ORDINE_FIRMA + 1))
	LEFT JOIN BANDO_VALUTATORI BV ON BV.ID_VALUTATORE = PVALUTATORI.ID_VALUTATORE
	LEFT JOIN VUTENTI UTV ON UTV.ID_UTENTE = BV.ID_UTENTE
WHERE 1 = 1
	AND APPROVATA IS NULL 
	AND VARI.ANNULLATA = 0
;