CREATE VIEW VCRUSCOTTO_BANDI_RUP
AS 
SELECT 
	BAN.ID_BANDO,
	BAN.DESCRIZIONE AS DESCRIZIONE_BANDO, 
	BAN.COD_ENTE AS COD_ENTE_BANDO, 
	BAN.ENTE AS ENTE_BANDO,
	UT.ID_UTENTE AS ID_RUP,
	UT.NOMINATIVO AS RUP,
	UT.CF_UTENTE AS CF_RUP,
	BAN.DATA_APERTURA AS DATA_APERTURA_BANDO,
	BAN.DATA_SCADENZA AS DATA_SCADENZA_BANDO,
	BAN.COD_STATO AS COD_STATO_BANDO,
	BAN.STATO AS STATO_BANDO, 
	BAN.SEGNATURA AS SEGNATURA_BANDO,
	PROG.ID_PROGETTO,
	PROG.COD_STATO AS COD_STATO_PROGETTO, 
	PROG.STATO AS STATO_PROGETTO,
	PROG.SEGNATURA AS SEGNATURA_PROGETTO,
	PROG.ID_IMPRESA AS ID_IMPRESA,
	IMP.RAGIONE_SOCIALE AS IMPRESA,
	IMP.CODICE_FISCALE AS CF_IMPRESA,
	IMP.CUAA AS CUAA_IMPRESA,
	COLL.ID_UTENTE AS ID_ISTRUTTORE_PROGETTO,
	COLL.NOMINATIVO AS ISTRUTTORE_PROGETTO,
	DOM.ID_DOMANDA_PAGAMENTO, 
	DOM.SEGNATURA AS SEGNATURA_DOMANDA_PAGAMENTO, 
	DOM.SEGNATURA_SECONDA_APPROVAZIONE AS SEGNATURA_SECONDA_APPROVAZIONE_DOMANDA_PAGAMENTO, 
	DOM.COD_FASE AS COD_FASE_DOMANDA_PAGAMENTO,
	DOM.FASE AS FASE_DOMANDA_PAGAMENTO, 
	DOM.ANNULLATA, 
	DOM.APPROVATA,
	UT_DOM.ID_UTENTE AS ID_ISTRUTTORE_DOMANDA_PAGAMENTO,
	UT_DOM.NOMINATIVO AS ISTRUTTORE_DOMANDA_PAGAMENTO,
	SUM(PAG.IMPORTO_RICHIESTO) AS IMPORTO_RICHIESTO, 
	CASE 
		WHEN DOM.FASE = 'Anticipo' 
		THEN (SELECT SUM(CONTRIBUTO_RICHIESTO)
				FROM ANTICIPI_RICHIESTI
				WHERE ID_DOMANDA_PAGAMENTO = DOM.ID_DOMANDA_PAGAMENTO) 
		WHEN DOM.FASE = 'Acconto/Sal' 
		THEN SUM(CONTRIBUTO_RICHIESTO) 
			+ ISNULL(dbo.calcoloPremioContoCapitaleDomandaPagamento(DOM.ID_DOMANDA_PAGAMENTO, 0), 0) 
		ELSE SUM(CONTRIBUTO_RICHIESTO) 
	END AS CONTRIBUTO_RICHIESTO,
	SUM(PAG.IMPORTO_AMMESSO) AS IMPORTO_AMMESSO,
	SUM(DOM_ESP.IMPORTO_AMMESSO) AS CONTRIBUTO_AMMESSO, 
	DOM.IN_INTEGRAZIONE, 
	DOM.FIRMA_PREDISPOSTA_RUP
FROM vBANDO BAN
	JOIN vBANDO_RESPONSABILI RESP ON BAN.ID_BANDO = RESP.ID_BANDO
	JOIN vUTENTI UT ON RESP.ID_UTENTE = UT.ID_UTENTE
	LEFT JOIN vPROGETTO PROG ON BAN.ID_BANDO = PROG.ID_BANDO
	LEFT JOIN vIMPRESA IMP ON PROG.ID_IMPRESA = IMP.ID_IMPRESA
	LEFT JOIN vCOLLABORATORI_X_BANDO COLL ON PROG.ID_PROGETTO = COLL.ID_PROGETTO 
	LEFT JOIN vDOMANDA_DI_PAGAMENTO DOM ON PROG.ID_PROGETTO = DOM.ID_PROGETTO 
	LEFT JOIN PAGAMENTI_RICHIESTI PAG ON DOM.ID_DOMANDA_PAGAMENTO = PAG.ID_DOMANDA_PAGAMENTO
	LEFT JOIN vUTENTI UT_DOM ON DOM.ISTRUTTORE = UT_DOM.NOMINATIVO
	LEFT JOIN VDOMANDA_DI_PAGAMENTO_ESPORTAZIONE DOM_ESP ON DOM.ID_DOMANDA_PAGAMENTO = DOM_ESP.ID_DOMANDA_PAGAMENTO
WHERE 1 = 1
	AND RESP.ATTIVO = 1
	AND RESP.PROVINCIA IS NULL
	AND (COLL.ID_UTENTE IS NULL OR COLL.ATTIVO = 1)
GROUP BY 
	BAN.ID_BANDO,
	BAN.DESCRIZIONE, 
	BAN.COD_ENTE, 
	BAN.ENTE,
	UT.ID_UTENTE,
	UT.NOMINATIVO,
	UT.CF_UTENTE,
	BAN.DATA_APERTURA,
	BAN.DATA_SCADENZA,
	BAN.COD_STATO,
	BAN.STATO, 
	BAN.SEGNATURA,
	PROG.ID_PROGETTO,
	PROG.COD_STATO, 
	PROG.STATO,
	PROG.SEGNATURA,
	PROG.ID_IMPRESA,
	IMP.RAGIONE_SOCIALE,
	IMP.CODICE_FISCALE,
	IMP.CUAA,
	COLL.ID_UTENTE,
	COLL.NOMINATIVO,
	DOM.ID_DOMANDA_PAGAMENTO, 
	DOM.SEGNATURA, 
	DOM.SEGNATURA_SECONDA_APPROVAZIONE, 
	DOM.COD_FASE,
	DOM.FASE, 
	DOM.ANNULLATA, 
	DOM.APPROVATA,
	UT_DOM.ID_UTENTE,
	UT_DOM.NOMINATIVO,
	DOM.IN_INTEGRAZIONE, 
	DOM.FIRMA_PREDISPOSTA_RUP
--ORDER BY 
--	BAN.ID_BANDO, 
--	PROG.ID_PROGETTO, 
--	DOM.ID_DOMANDA_PAGAMENTO


GO