CREATE VIEW [dbo].[VCRUSCOTTO_DOMANDE_RAPPRESENTANTE_LEGALE] 
AS
	SELECT 
			BAN.ID_BANDO, 
			BAN.DESCRIZIONE AS DESCRIZIONE_BANDO, 
			BAN.DATA_SCADENZA AS DATA_SCADENZA_BANDO, 
			BAN.COD_ENTE AS COD_ENTE_BANDO,
			BAN.ID_PROGRAMMAZIONE AS ID_PROGRAMMAZIONE_BANDO,
			PROG.ID_PROGETTO, 
			PROG.COD_STATO AS COD_STATO_PROGETTO,
			PROG.STATO AS STATO_PROGETTO,
			PROG.ID_IMPRESA AS ID_IMPRESA,
			IMP.RAGIONE_SOCIALE AS IMPRESA,
			UTR.ID_UTENTE AS ID_UTENTE_RAPPRESENTANTE_LEGALE,
			UTR.NOMINATIVO AS RAPPRESENTANTE_LEGALE
		FROM vBANDO BAN
			JOIN vPROGETTO PROG ON PROG.ID_BANDO = BAN.ID_BANDO 
			JOIN vIMPRESA IMP ON PROG.ID_IMPRESA = IMP.ID_IMPRESA
			JOIN vPERSONE_X_IMPRESE PPI ON IMP.ID_RAPPRLEGALE_ULTIMO = PPI.ID_PERSONE_X_IMPRESE
			JOIN vUTENTI UTR ON UTR.CF_UTENTE = PPI.CODICE_FISCALE
		WHERE 1 = 1
		--AND ID_PROGETTO = 12668;
GO