CREATE VIEW VCRUSCOTTO_DOMANDE
AS
SELECT *
FROM (SELECT 
		BAN.ID_BANDO AS ID_BANDO,
		BAN.DESCRIZIONE AS DESCRIZIONE_BANDO, 
		BAN.COD_ENTE AS COD_ENTE_BANDO, 
		PROG.COD_STATO AS COD_STATO_PROGETTO, 
		BAN.DATA_SCADENZA AS DATA_SCADENZA_BANDO, 
		PROG.ID_PROGETTO, 
		PROG.STATO,
		IMP.ID_IMPRESA, 
		IMP.RAGIONE_SOCIALE AS IMPRESA,
		PAG.ID_DOMANDA_PAGAMENTO, 
		PAG.SEGNATURA AS SEGNATURA_DOMANDA_PAGAMENTO, 
		PAG.FASE AS FASE_DOMANDA_PAGAMENTO, 
		PAG.ANNULLATA, 
		PAG.APPROVATA, 
		R.SELEZIONATA_X_REVISIONE, 
		R.APPROVATA AS APPROVATA_REVISIONE, 
		PAG.SEGNATURA_SECONDA_APPROVAZIONE, 
		RESP.ID_UTENTE AS ID_UTENTE_RUP, 
		RESP.NOMINATIVO AS RUP,
		--(SELECT ID_UTENTE
		--FROM dbo.vUTENTI
		--WHERE NOMINATIVO = PAG.ISTRUTTORE) AS ID_UTENTE_ISTRUTTORE, 
		--PAG.ISTRUTTORE, 
		UTC.ID_UTENTE AS ID_UTENTE_ISTRUTTORE,
		UTC.NOMINATIVO AS ISTRUTTORE,
		SUM(P.IMPORTO_RICHIESTO) AS IMPORTO_RICHIESTO, 
		CASE 
			WHEN PAG.FASE = 'Anticipo' 
			THEN (SELECT SUM(CONTRIBUTO_RICHIESTO)
					FROM ANTICIPI_RICHIESTI
					WHERE ID_DOMANDA_PAGAMENTO = PAG.ID_DOMANDA_PAGAMENTO) 
			WHEN PAG.FASE = 'Acconto/Sal' 
			THEN SUM(CONTRIBUTO_RICHIESTO) 
				+ ISNULL(dbo.calcoloPremioContoCapitaleDomandaPagamento(PAG.ID_DOMANDA_PAGAMENTO, 0), 0) 
			ELSE SUM(CONTRIBUTO_RICHIESTO) 
		END AS CONTRIBUTO_RICHIESTO, 
		SUM(P.IMPORTO_AMMESSO) AS IMPORTO_AMMESSO,
		(SELECT SUM(IMPORTO_AMMESSO)
			FROM DOMANDA_DI_PAGAMENTO_ESPORTAZIONE
			WHERE ID_DOMANDA_PAGAMENTO = PAG.ID_DOMANDA_PAGAMENTO) AS CONTRIBUTO_AMMESSO, 
		PAG.IN_INTEGRAZIONE, 
		PAG.FIRMA_PREDISPOSTA_RUP
    FROM dbo.vPROGETTO PROG 
		INNER JOIN VIMPRESA IMP ON PROG.ID_IMPRESA = IMP.ID_IMPRESA 
		INNER JOIN vBANDO BAN ON BAN.ID_BANDO = PROG.ID_BANDO 
		INNER JOIN vBANDO_RESPONSABILI RESP ON RESP.ID_BANDO = BAN.ID_BANDO 
		INNER JOIN vUTENTI UT ON UT.ID_UTENTE = RESP.ID_UTENTE 
		INNER JOIN vDOMANDA_DI_PAGAMENTO PAG ON PROG.ID_PROGETTO = PAG.ID_PROGETTO 
		LEFT JOIN COLLABORATORI_X_BANDO COLL ON COLL.ID_PROGETTO = PROG.ID_PROGETTO AND COLL.ATTIVO = 1
		LEFT JOIN vUTENTI UTC ON COLL.ID_UTENTE = UTC.ID_UTENTE 
		LEFT JOIN PAGAMENTI_RICHIESTI P ON PAG.ID_DOMANDA_PAGAMENTO = P.ID_DOMANDA_PAGAMENTO 
		--LEFT JOIN REVISIONE_DOMANDA_PAGAMENTO R ON PAG.ID_DOMANDA_PAGAMENTO = R.ID_DOMANDA_PAGAMENTO
		LEFT JOIN CTE_TESTATA_VALIDAZIONE R ON PAG.ID_DOMANDA_PAGAMENTO = R.ID_DOMANDA_PAGAMENTO
    WHERE 1 = 1 
		AND PAG.SEGNATURA IS NOT NULL
		AND PAG.SEGNATURA_APPROVAZIONE IS NULL 
		AND RESP.ATTIVO = 1 
		AND RESP.PROVINCIA IS NULL
    GROUP BY 
		BAN.ID_BANDO,
		BAN.DESCRIZIONE, 
		BAN.DATA_SCADENZA, 
		BAN.COD_ENTE, 
		PROG.COD_STATO, 
		PROG.ID_PROGETTO, 
		PROG.STATO, 
		IMP.ID_IMPRESA, 
		IMP.RAGIONE_SOCIALE,
		PAG.ID_DOMANDA_PAGAMENTO, 
		PAG.SEGNATURA, 
		PAG.FASE, 
        RESP.NOMINATIVO, 
		--PAG.ISTRUTTORE, 
		UTC.ID_UTENTE,
		UTC.NOMINATIVO,
		PAG.IN_INTEGRAZIONE, 
		PAG.FIRMA_PREDISPOSTA_RUP, 
		RESP.ID_UTENTE, 
		PAG.ANNULLATA, 
		PAG.APPROVATA, 
		R.SELEZIONATA_X_REVISIONE, 
        R.APPROVATA, PAG.SEGNATURA_SECONDA_APPROVAZIONE) AS X
GO


