CREATE PROCEDURE [dbo].[VerificaRendicontazionePagamentoSaldo_M431_B106]
(
	@ID_DOMANDA_PAGAMENTO INT
)
AS
 
--DECLARE @ID_DOMANDA_PAGAMENTO INT;SET @ID_DOMANDA_PAGAMENTO=251
--DEFINIZIONI CIAO
DECLARE @ID_VARIANTE INT,@ID_PROGETTO INT,@DATA_MODIFICA_PAGAMENTO DATETIME,@ID_INVESTIMENTO INT,
@IMPORTO_RENDICONTATO_ATTUALE DECIMAL(18,2),@CONTRIBUTO_RENDICONTATO_ATTUALE DECIMAL(18,2),@ID_FASCICOLO INT,
--ESITO VERIFICA
@TIPO_RISULTATO CHAR(1),@MESSAGGIO_RISULTATO VARCHAR(3000)
SET @TIPO_RISULTATO='S'
SET @MESSAGGIO_RISULTATO=''

--TROVO PROGETTO E ULTIMA VARIANTE RELATIVA A QUESTA DOMANDA DI PAGAMENTO
SELECT @DATA_MODIFICA_PAGAMENTO=DATA_MODIFICA,@ID_PROGETTO=D.ID_PROGETTO,@ID_FASCICOLO=ID_FASCICOLO FROM DOMANDA_DI_PAGAMENTO D
	INNER JOIN PROGETTO P ON D.ID_PROGETTO=P.ID_PROGETTO WHERE ID_DOMANDA_PAGAMENTO=@ID_DOMANDA_PAGAMENTO
SELECT @ID_VARIANTE=MAX(ID_VARIANTE) FROM VARIANTI WHERE ID_PROGETTO=@ID_PROGETTO AND APPROVATA=1 AND ANNULLATA=0 
	AND DATA_MODIFICA<@DATA_MODIFICA_PAGAMENTO

--CREO PIANO INVESTIMENTI VIRTUALE
DECLARE @INVESTIMENTI_TEMP TABLE ([ID_INVESTIMENTO] [int] NOT NULL,
	[ID_PROGETTO] [int] NULL,
	[ID_PROGRAMMAZIONE] [int] NULL,
	[DESCRIZIONE] [varchar](2000) NULL,
	[DATA_VARIAZIONE] [datetime] NULL,
	[OPERATORE_VARIAZIONE] [varchar](16) NULL,
	[COD_TIPO_INVESTIMENTO] [int] NULL,
	[COD_STP] [char](2) NULL,
	[ID_UNITA_MISURA] [int] NULL,
	[QUANTITA] [decimal](10, 2) NULL,
	[COSTO_INVESTIMENTO] [decimal](15, 2) NULL,
	[SPESE_GENERALI] [decimal](15, 2) NULL,
	[CONTRIBUTO_RICHIESTO] [decimal](15, 2) NULL,
	[QUOTA_CONTRIBUTO_RICHIESTO] [decimal](10, 2) NULL,
	[TASSO_ABBUONO] [decimal](10, 2) NULL,
	[ID_SETTORE_PRODUTTIVO] [int] NULL,
	[ID_PRIORITA_SETTORIALE] [int] NULL,
	[ID_OBIETTIVO_MISURA] [int] NULL,
	[ID_CODIFICA_INVESTIMENTO] [int] NULL,
	[ID_DETTAGLIO_INVESTIMENTO] [int] NULL,
	[ID_SPECIFICA_INVESTIMENTO] [int] NULL,
	[AMMESSO] [bit] NULL,
	[ISTRUTTORE] [varchar](16) NULL,
	[ID_INVESTIMENTO_ORIGINALE] [int] NULL,
	[DATA_VALUTAZIONE] [datetime] NULL,
	[VALUTAZIONE_INVESTIMENTO] [ntext] NULL,
	[ID_VARIANTE] [int] NULL,
	[COD_VARIAZIONE] [char](1),
	[NON_COFINANZIATO][bit] NULL,
	IMPORTO_TOTALE_RENDICONTATO DECIMAL(18,2),
	CONTRIBUTO_TOTALE_RENDICONTATO DECIMAL(18,2))	

INSERT INTO @INVESTIMENTI_TEMP
SELECT I.*,	dbo.calcoloTotaleImportoRendicontatoInvestimento(I.ID_INVESTIMENTO,@ID_DOMANDA_PAGAMENTO) AS IMPORTO_TOTALE_RENDICONTATO,
	dbo.calcoloTotaleContributoRendicontatoInvestimento(I.ID_INVESTIMENTO,@ID_DOMANDA_PAGAMENTO) AS CONTRIBUTO_TOTALE_RENDICONTATO 
FROM PROGETTO P INNER JOIN PIANO_INVESTIMENTI I ON P.ID_PROGETTO=I.ID_PROGETTO
WHERE ISNULL(P.ID_PROG_INTEGRATO,P.ID_PROGETTO)=@ID_PROGETTO AND
	((@ID_VARIANTE IS NULL AND ID_INVESTIMENTO_ORIGINALE IS NOT NULL AND AMMESSO=1 AND ID_VARIANTE IS NULL) OR
	(ID_VARIANTE=@ID_VARIANTE AND ISNULL(COD_VARIAZIONE,'X')!='A')) ORDER BY COD_TIPO_INVESTIMENTO

/**********************************************************************************************************/
--INIZIO CONTROLLO STEP

DECLARE @COSTO_INVESTIMENTI DECIMAL(18,2), @CUAA VARCHAR(16)
SELECT @COSTO_INVESTIMENTI=SUM(IMPORTO_TOTALE_RENDICONTATO) FROM @INVESTIMENTI_TEMP WHERE COD_TIPO_INVESTIMENTO=1
SELECT @CUAA=IMP.CUAA FROM PROGETTO P INNER JOIN VIMPRESA IMP ON IMP.ID_IMPRESA= P.ID_IMPRESA WHERE ID_PROGETTO =@ID_PROGETTO 
 
------------------------------------------------------------------------------------------------
-- l`aiuto pubblico per la realizzazione del PSL è minore o uguale a 25.000,00 €

DECLARE @COSTO_INVESTIMENTI_PSL DECIMAL(18,2)
IF @COSTO_INVESTIMENTI>0 BEGIN
	SELECT @COSTO_INVESTIMENTI_PSL=SUM(CONTRIBUTO_TOTALE_RENDICONTATO) 
	FROM @INVESTIMENTI_TEMP INV	INNER JOIN DETTAGLIO_INVESTIMENTI DI ON (INV.ID_DETTAGLIO_INVESTIMENTO = DI.ID_DETTAGLIO_INVESTIMENTO)   
	WHERE DI.ID_DETTAGLIO_INVESTIMENTO  = 957
						
	IF @COSTO_INVESTIMENTI_PSL> 25000  BEGIN
		SET @TIPO_RISULTATO='N'
		SET @MESSAGGIO_RISULTATO=@MESSAGGIO_RISULTATO+'<BR /> - L`aiuto pubblico per la realizzazione del PSL supera i 25.000,00 €'
	END
END


-----------------------------------------------------------------------------------------
  -- controllo superamento tetto GAL per spese sottomisura a

DECLARE @QUOTA_CONTRIBUTO_TOTALE_A DECIMAL(18,2), @RESULT_A INT =0
 
IF @COSTO_INVESTIMENTI>0 BEGIN
	SELECT @QUOTA_CONTRIBUTO_TOTALE_A=SUM(CONTRIBUTO_TOTALE_RENDICONTATO) 
	FROM @INVESTIMENTI_TEMP INV	INNER JOIN DETTAGLIO_INVESTIMENTI DI ON (INV.ID_DETTAGLIO_INVESTIMENTO = DI.ID_DETTAGLIO_INVESTIMENTO)   
	WHERE INV.ID_PROGRAMMAZIONE  = 325
	
	IF (@CUAA =  '01119560439' AND @QUOTA_CONTRIBUTO_TOTALE_A  <= 889840.96 )SET @RESULT_A = 1 
	ELSE IF (@CUAA = '01377860414' AND   @QUOTA_CONTRIBUTO_TOTALE_A <= 963110.27 )SET @RESULT_A = 1
	ELSE IF (@CUAA = '01451540437' AND   @QUOTA_CONTRIBUTO_TOTALE_A <= 907999.13 ) SET @RESULT_A = 1
	ELSE IF (@CUAA = '01377760416' AND  @QUOTA_CONTRIBUTO_TOTALE_A <= 609462.70 )SET @RESULT_A = 1
	ELSE IF (@CUAA = '01502360447' AND  @QUOTA_CONTRIBUTO_TOTALE_A <= 700192.16 )SET @RESULT_A = 1
	ELSE IF (@CUAA = '01944950441' AND  @QUOTA_CONTRIBUTO_TOTALE_A <= 668601.57)SET @RESULT_A = 1
					
	IF @RESULT_A=0 BEGIN
		SET @TIPO_RISULTATO='N'
		SET @MESSAGGIO_RISULTATO=@MESSAGGIO_RISULTATO+'<BR /> - Superato il tetto per le spese sottomisura a) .'
	END
END

-----------------------------------------------------------------------------------------
 ----- massimale di aiuto per l'intervento B

 
 DECLARE @QUOTA_CONTRIBUTO_TOTALE_B DECIMAL(18,2), @RESULT_B INT =0
 
 IF @COSTO_INVESTIMENTI>0 BEGIN
	SELECT @QUOTA_CONTRIBUTO_TOTALE_B=SUM(CONTRIBUTO_TOTALE_RENDICONTATO) 
	FROM @INVESTIMENTI_TEMP INV	INNER JOIN DETTAGLIO_INVESTIMENTI DI ON (INV.ID_DETTAGLIO_INVESTIMENTO = DI.ID_DETTAGLIO_INVESTIMENTO)   
	WHERE INV.ID_PROGRAMMAZIONE  = 326
	
	IF (@CUAA = '01119560439' AND @QUOTA_CONTRIBUTO_TOTALE_B <=  593227.31  )
		BEGIN IF((ISNULL(@QUOTA_CONTRIBUTO_TOTALE_B,0) + ISNULL(@QUOTA_CONTRIBUTO_TOTALE_A,0)) <= 1186455.30) SET @RESULT_B = 1 END 
	ELSE IF ((@CUAA = '01377860414' ) AND  @QUOTA_CONTRIBUTO_TOTALE_B   <=  642073.52 )
	    BEGIN IF((ISNULL(@QUOTA_CONTRIBUTO_TOTALE_B,0) + ISNULL(@QUOTA_CONTRIBUTO_TOTALE_A,0)) <= 1284147.03  ) SET @RESULT_B = 1 END 
	ELSE IF (@CUAA = '01451540437'  AND @QUOTA_CONTRIBUTO_TOTALE_B <=  605332.76 )
		BEGIN IF((ISNULL(@QUOTA_CONTRIBUTO_TOTALE_B,0) + ISNULL(@QUOTA_CONTRIBUTO_TOTALE_A,0)) <= 1040803.80 ) SET @RESULT_B = 1 END 
	ELSE IF (@CUAA = '01377760416'   AND  @QUOTA_CONTRIBUTO_TOTALE_B  <=  406308.46   ) 
		BEGIN IF((ISNULL(@QUOTA_CONTRIBUTO_TOTALE_B,0) + ISNULL(@QUOTA_CONTRIBUTO_TOTALE_A,0)) <=  788950.73 ) SET @RESULT_B = 1 END 
	ELSE IF (@CUAA = '01502360447' AND  @QUOTA_CONTRIBUTO_TOTALE_B  <= 466794.77  )  
		BEGIN IF((ISNULL(@QUOTA_CONTRIBUTO_TOTALE_B,0) + ISNULL(@QUOTA_CONTRIBUTO_TOTALE_A,0)) <= 799596.72) SET @RESULT_B = 1 END 
	ELSE IF (@CUAA = '01944950441'   AND  @QUOTA_CONTRIBUTO_TOTALE_B  <= 445734.38  )  
		BEGIN IF((ISNULL(@QUOTA_CONTRIBUTO_TOTALE_B,0) + ISNULL(@QUOTA_CONTRIBUTO_TOTALE_A,0)) <= 869899.13 ) SET @RESULT_B = 1 END 

	IF @RESULT_B=0 BEGIN
		SET @TIPO_RISULTATO='N'
		SET @MESSAGGIO_RISULTATO=@MESSAGGIO_RISULTATO+'<BR /> - Superato il tetto per le spese sottomisura b ) .'
	END
	
END 
 
 

/*********************************************************************************************************/
IF @TIPO_RISULTATO='S' SET @MESSAGGIO_RISULTATO='VERIFICA DI AMMISSIBILITA DEGLI IMPORTI RENDICONTATI CONFERMATA'
ELSE SET @MESSAGGIO_RISULTATO='Si sono riscontrati i seguenti errori:'+@MESSAGGIO_RISULTATO
SELECT @TIPO_RISULTATO AS TIPO_RISULTATO, @MESSAGGIO_RISULTATO AS MESSAGGIO_RISULTATO
