CREATE PROCEDURE [dbo].[Z_CODIFICA_GENERICA_FIND_SELECT]
(
	@IDEQUALTHIS INT, 
	@ID_TIPO_CODIFICAEQUALTHIS INT, 
	@DESCRIZIONEEQUALTHIS NVARCHAR(4000), 
	@CODICE_TXTEQUALTHIS NVARCHAR(255), 
	@VALORE_INT1EQUALTHIS INT, 
	@VALORE_INT2EQUALTHIS INT, 
	@VALORE_DEC1EQUALTHIS DECIMAL(20,2), 
	@VALORE_DEC2EQUALTHIS DECIMAL(20,2), 
	@FLAGEQUALTHIS VARCHAR(255), 
	@DATA_INIZIO_VALIDITAEQUALTHIS DATETIME, 
	@DATA_FINE_VALIDITAEQUALTHIS DATETIME, 
	@ID_PADREEQUALTHIS INT
)
AS
	declare @sql nvarchar(4000);
	declare @lensql int;
	set @lensql=0;
	SET @sql = 'SELECT ID, ID_TIPO_CODIFICA, DESCRIZIONE, VALORE_TXT, CODICE_TXT, VALORE_INT1, VALORE_INT2, VALORE_DEC1, VALORE_DEC2, FLAG, DATA_INIZIO_VALIDITA, DATA_FINE_VALIDITA, ID_PADRE, VALORE_TXT2, VALORE_TXT3 FROM VCODIFICA_GENERICA WHERE 1=1';
	IF (@IDEQUALTHIS IS NOT NULL) BEGIN SET @sql = @sql + ' AND (ID = @IDEQUALTHIS)'; set @lensql=@lensql+len(@IDEQUALTHIS);end;
	IF (@ID_TIPO_CODIFICAEQUALTHIS IS NOT NULL) BEGIN SET @sql = @sql + ' AND (ID_TIPO_CODIFICA = @ID_TIPO_CODIFICAEQUALTHIS)'; set @lensql=@lensql+len(@ID_TIPO_CODIFICAEQUALTHIS);end;
	IF (@DESCRIZIONEEQUALTHIS IS NOT NULL) BEGIN SET @sql = @sql + ' AND (DESCRIZIONE = @DESCRIZIONEEQUALTHIS)'; set @lensql=@lensql+len(@DESCRIZIONEEQUALTHIS);end;
	IF (@CODICE_TXTEQUALTHIS IS NOT NULL) BEGIN SET @sql = @sql + ' AND (CODICE_TXT = @CODICE_TXTEQUALTHIS)'; set @lensql=@lensql+len(@CODICE_TXTEQUALTHIS);end;
	IF (@VALORE_INT1EQUALTHIS IS NOT NULL) BEGIN SET @sql = @sql + ' AND (VALORE_INT1 = @VALORE_INT1EQUALTHIS)'; set @lensql=@lensql+len(@VALORE_INT1EQUALTHIS);end;
	IF (@VALORE_INT2EQUALTHIS IS NOT NULL) BEGIN SET @sql = @sql + ' AND (VALORE_INT2 = @VALORE_INT2EQUALTHIS)'; set @lensql=@lensql+len(@VALORE_INT2EQUALTHIS);end;
	IF (@VALORE_DEC1EQUALTHIS IS NOT NULL) BEGIN SET @sql = @sql + ' AND (VALORE_DEC1 = @VALORE_DEC1EQUALTHIS)'; set @lensql=@lensql+len(@VALORE_DEC1EQUALTHIS);end;
	IF (@VALORE_DEC2EQUALTHIS IS NOT NULL) BEGIN SET @sql = @sql + ' AND (VALORE_DEC2 = @VALORE_DEC2EQUALTHIS)'; set @lensql=@lensql+len(@VALORE_DEC2EQUALTHIS);end;
	IF (@FLAGEQUALTHIS IS NOT NULL) BEGIN SET @sql = @sql + ' AND (FLAG = @FLAGEQUALTHIS)'; set @lensql=@lensql+len(@FLAGEQUALTHIS);end;
	IF (@DATA_INIZIO_VALIDITAEQUALTHIS IS NOT NULL) BEGIN SET @sql = @sql + ' AND (DATA_INIZIO_VALIDITA = @DATA_INIZIO_VALIDITAEQUALTHIS)'; set @lensql=@lensql+len(@DATA_INIZIO_VALIDITAEQUALTHIS);end;
	IF (@DATA_FINE_VALIDITAEQUALTHIS IS NOT NULL) BEGIN SET @sql = @sql + ' AND (DATA_FINE_VALIDITA = @DATA_FINE_VALIDITAEQUALTHIS)'; set @lensql=@lensql+len(@DATA_FINE_VALIDITAEQUALTHIS);end;
	IF (@ID_PADREEQUALTHIS IS NOT NULL) BEGIN SET @sql = @sql + ' AND (ID_PADRE = @ID_PADREEQUALTHIS)'; set @lensql=@lensql+len(@ID_PADREEQUALTHIS);end;
	set @lensql=@lensql+len(@sql);
	if (@lensql<3000)
	exec sp_executesql @sql,N'@IDEQUALTHIS INT, @ID_TIPO_CODIFICAEQUALTHIS INT, @DESCRIZIONEEQUALTHIS NVARCHAR(4000), @CODICE_TXTEQUALTHIS NVARCHAR(255), @VALORE_INT1EQUALTHIS INT, @VALORE_INT2EQUALTHIS INT, @VALORE_DEC1EQUALTHIS DECIMAL(20,2), @VALORE_DEC2EQUALTHIS DECIMAL(20,2), @FLAGEQUALTHIS VARCHAR(255), @DATA_INIZIO_VALIDITAEQUALTHIS DATETIME, @DATA_FINE_VALIDITAEQUALTHIS DATETIME, @ID_PADREEQUALTHIS INT',@IDEQUALTHIS , @ID_TIPO_CODIFICAEQUALTHIS , @DESCRIZIONEEQUALTHIS , @CODICE_TXTEQUALTHIS , @VALORE_INT1EQUALTHIS , @VALORE_INT2EQUALTHIS , @VALORE_DEC1EQUALTHIS , @VALORE_DEC2EQUALTHIS , @FLAGEQUALTHIS , @DATA_INIZIO_VALIDITAEQUALTHIS , @DATA_FINE_VALIDITAEQUALTHIS , @ID_PADREEQUALTHIS ;
	else
		SELECT ID, ID_TIPO_CODIFICA, DESCRIZIONE, VALORE_TXT, CODICE_TXT, VALORE_INT1, VALORE_INT2, VALORE_DEC1, VALORE_DEC2, FLAG, DATA_INIZIO_VALIDITA, DATA_FINE_VALIDITA, ID_PADRE, VALORE_TXT2, VALORE_TXT3
		FROM VCODIFICA_GENERICA
		WHERE 
			((@IDEQUALTHIS IS NULL) OR ID = @IDEQUALTHIS) AND 
			((@ID_TIPO_CODIFICAEQUALTHIS IS NULL) OR ID_TIPO_CODIFICA = @ID_TIPO_CODIFICAEQUALTHIS) AND 
			((@DESCRIZIONEEQUALTHIS IS NULL) OR DESCRIZIONE = @DESCRIZIONEEQUALTHIS) AND 
			((@CODICE_TXTEQUALTHIS IS NULL) OR CODICE_TXT = @CODICE_TXTEQUALTHIS) AND 
			((@VALORE_INT1EQUALTHIS IS NULL) OR VALORE_INT1 = @VALORE_INT1EQUALTHIS) AND 
			((@VALORE_INT2EQUALTHIS IS NULL) OR VALORE_INT2 = @VALORE_INT2EQUALTHIS) AND 
			((@VALORE_DEC1EQUALTHIS IS NULL) OR VALORE_DEC1 = @VALORE_DEC1EQUALTHIS) AND 
			((@VALORE_DEC2EQUALTHIS IS NULL) OR VALORE_DEC2 = @VALORE_DEC2EQUALTHIS) AND 
			((@FLAGEQUALTHIS IS NULL) OR FLAG = @FLAGEQUALTHIS) AND 
			((@DATA_INIZIO_VALIDITAEQUALTHIS IS NULL) OR DATA_INIZIO_VALIDITA = @DATA_INIZIO_VALIDITAEQUALTHIS) AND 
			((@DATA_FINE_VALIDITAEQUALTHIS IS NULL) OR DATA_FINE_VALIDITA = @DATA_FINE_VALIDITAEQUALTHIS) AND 
			((@ID_PADREEQUALTHIS IS NULL) OR ID_PADRE = @ID_PADREEQUALTHIS)
		


GO
EXECUTE sp_addextendedproperty @name = N'backup', @value = NULL, @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'PROCEDURE', @level1name = N'Z_CODIFICA_GENERICA_FIND_SELECT';

