CREATE PROCEDURE [dbo].[Z_CODIFICA_GENERICA_FIND_FPADRE]
(
	@ID_PADREEQUALTHIS INT
)
AS
	declare @sql nvarchar(4000);
	declare @lensql int;
	set @lensql=0;
	SET @sql = 'SELECT ID, ID_TIPO_CODIFICA, DESCRIZIONE, VALORE_TXT, CODICE_TXT, VALORE_INT1, VALORE_INT2, VALORE_DEC1, VALORE_DEC2, FLAG, DATA_INIZIO_VALIDITA, DATA_FINE_VALIDITA, ID_PADRE, VALORE_TXT2, VALORE_TXT3 FROM VCODIFICA_GENERICA WHERE 1=1';
	IF (@ID_PADREEQUALTHIS IS NOT NULL) BEGIN SET @sql = @sql + ' AND (ID_PADRE = @ID_PADREEQUALTHIS)'; set @lensql=@lensql+len(@ID_PADREEQUALTHIS);end;
	set @sql = @sql + 'ORDER BY ID';
	set @lensql=@lensql+len(@sql);
	if (@lensql<3000)
	exec sp_executesql @sql,N'@ID_PADREEQUALTHIS INT',@ID_PADREEQUALTHIS ;
	else
		SELECT ID, ID_TIPO_CODIFICA, DESCRIZIONE, VALORE_TXT, CODICE_TXT, VALORE_INT1, VALORE_INT2, VALORE_DEC1, VALORE_DEC2, FLAG, DATA_INIZIO_VALIDITA, DATA_FINE_VALIDITA, ID_PADRE, VALORE_TXT2, VALORE_TXT3
		FROM VCODIFICA_GENERICA
		WHERE 
			((@ID_PADREEQUALTHIS IS NULL) OR ID_PADRE = @ID_PADREEQUALTHIS)
		ORDER BY ID


GO
EXECUTE sp_addextendedproperty @name = N'backup', @value = NULL, @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'PROCEDURE', @level1name = N'Z_CODIFICA_GENERICA_FIND_FPADRE';

