CREATE PROCEDURE [dbo].[Z_CODIFICA_GENERICA_INSERT]
(
	@ID INT, 
	@ID_TIPO_CODIFICA INT, 
	@DESCRIZIONE NVARCHAR(4000), 
	@VALORE_TXT NTEXT, 
	@CODICE_TXT NVARCHAR(255), 
	@VALORE_INT1 INT, 
	@VALORE_INT2 INT, 
	@VALORE_DEC1 DECIMAL(20,2), 
	@VALORE_DEC2 DECIMAL(20,2), 
	@FLAG VARCHAR(255), 
	@DATA_INIZIO_VALIDITA DATETIME, 
	@DATA_FINE_VALIDITA DATETIME, 
	@ID_PADRE INT, 
	@VALORE_TXT2 NTEXT, 
	@VALORE_TXT3 NTEXT
)
AS
	INSERT INTO CODIFICA_GENERICA
	(
		ID, 
		ID_TIPO_CODIFICA, 
		DESCRIZIONE, 
		VALORE_TXT, 
		CODICE_TXT, 
		VALORE_INT1, 
		VALORE_INT2, 
		VALORE_DEC1, 
		VALORE_DEC2, 
		FLAG, 
		DATA_INIZIO_VALIDITA, 
		DATA_FINE_VALIDITA, 
		ID_PADRE, 
		VALORE_TXT2, 
		VALORE_TXT3
	)
	VALUES
	(
		@ID, 
		@ID_TIPO_CODIFICA, 
		@DESCRIZIONE, 
		@VALORE_TXT, 
		@CODICE_TXT, 
		@VALORE_INT1, 
		@VALORE_INT2, 
		@VALORE_DEC1, 
		@VALORE_DEC2, 
		@FLAG, 
		@DATA_INIZIO_VALIDITA, 
		@DATA_FINE_VALIDITA, 
		@ID_PADRE, 
		@VALORE_TXT2, 
		@VALORE_TXT3
	)


GO
EXECUTE sp_addextendedproperty @name = N'backup', @value = NULL, @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'PROCEDURE', @level1name = N'Z_CODIFICA_GENERICA_INSERT';

