CREATE PROCEDURE [dbo].[Z_CODIFICA_GENERICA_UPDATE]
(
	@ID INT, 
	@ID_TIPO_CODIFICA INT, 
	@DESCRIZIONE NVARCHAR(4000), 
	@VALORE_TXT NTEXT, 
	@CODICE_TXT NVARCHAR(255), 
	@VALORE_INT1 INT, 
	@VALORE_INT2 INT, 
	@VALORE_DEC1 DECIMAL(20,2), 
	@VALORE_DEC2 DECIMAL(20,2), 
	@FLAG VARCHAR(255), 
	@DATA_INIZIO_VALIDITA DATETIME, 
	@DATA_FINE_VALIDITA DATETIME, 
	@ID_PADRE INT, 
	@VALORE_TXT2 NTEXT, 
	@VALORE_TXT3 NTEXT
)
AS
	UPDATE CODIFICA_GENERICA
	SET
		ID_TIPO_CODIFICA = @ID_TIPO_CODIFICA, 
		DESCRIZIONE = @DESCRIZIONE, 
		VALORE_TXT = @VALORE_TXT, 
		CODICE_TXT = @CODICE_TXT, 
		VALORE_INT1 = @VALORE_INT1, 
		VALORE_INT2 = @VALORE_INT2, 
		VALORE_DEC1 = @VALORE_DEC1, 
		VALORE_DEC2 = @VALORE_DEC2, 
		FLAG = @FLAG, 
		DATA_INIZIO_VALIDITA = @DATA_INIZIO_VALIDITA, 
		DATA_FINE_VALIDITA = @DATA_FINE_VALIDITA, 
		ID_PADRE = @ID_PADRE, 
		VALORE_TXT2 = @VALORE_TXT2, 
		VALORE_TXT3 = @VALORE_TXT3
	WHERE 
		(ID = @ID)


GO
EXECUTE sp_addextendedproperty @name = N'backup', @value = NULL, @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'PROCEDURE', @level1name = N'Z_CODIFICA_GENERICA_UPDATE';

