CREATE PROCEDURE [dbo].[ZBilancioAgricoloUpdate]
(
	@IdBilancioAgricolo INT, 
	@IdImpresa INT, 
	@IdProgetto INT, 
	@Anno INT, 
	@DataBilancio DATETIME, 
	@Previsionale BIT, 
	@DataModifica DATETIME, 
	@PlvRicaviNetti DECIMAL(15,2), 
	@PlvRicaviAttivita DECIMAL(15,2), 
	@PlvRimanenzeFinali DECIMAL(15,2), 
	@PlvRimanenzeIniziali DECIMAL(15,2), 
	@VaCostiMatPrime DECIMAL(15,2), 
	@VaCostiAttConnesse DECIMAL(15,2), 
	@VaNoleggi DECIMAL(15,2), 
	@VaManutenzioni DECIMAL(15,2), 
	@VaSpeseGenerali DECIMAL(15,2), 
	@VaAffitti DECIMAL(15,2), 
	@VaAltriCosti DECIMAL(15,2), 
	@PnAmmMacchine DECIMAL(15,2), 
	@PnAmmFabbricati DECIMAL(15,2), 
	@PnAmmPiantagioni DECIMAL(15,2), 
	@RoSalari DECIMAL(15,2), 
	@RoOneri DECIMAL(15,2), 
	@RnPacRicavi DECIMAL(15,2), 
	@RnPacCosti DECIMAL(15,2), 
	@RnPacProventi DECIMAL(15,2), 
	@RnPacPerdite DECIMAL(15,2), 
	@RnPacInteressiAttivi DECIMAL(15,2), 
	@RnPacInteressiPassivi DECIMAL(15,2), 
	@RnPacImposte DECIMAL(15,2), 
	@RnPacContributiPac DECIMAL(15,2), 
	@MnlRedditiFam DECIMAL(15,2), 
	@MnlRimborso DECIMAL(15,2), 
	@MnlPrelievi DECIMAL(15,2), 
	@CfCfTerreni DECIMAL(15,2), 
	@CfCfImpianti DECIMAL(15,2), 
	@CfCfPiantagioni DECIMAL(15,2), 
	@CfCfMiglioramenti DECIMAL(15,2), 
	@CfCaMacchine DECIMAL(15,2), 
	@CfCaBestiame DECIMAL(15,2), 
	@CfIfPartecipazioni DECIMAL(15,2), 
	@CcDfRimanenze DECIMAL(15,2), 
	@CcDfAnticipazioni DECIMAL(15,2), 
	@CcLdCrediti DECIMAL(15,2), 
	@CcLiBanca DECIMAL(15,2), 
	@CcLiCassa DECIMAL(15,2), 
	@FfPcDebitiBreveTermine DECIMAL(15,2), 
	@FfPcFornitori DECIMAL(15,2), 
	@FfPcDebiti DECIMAL(15,2), 
	@FfPcMutui DECIMAL(15,2), 
	@FfMpCapitale DECIMAL(15,2), 
	@FfMpRiserve DECIMAL(15,2), 
	@FfMpUtile DECIMAL(15,2)
)
AS
	--SET @DataModifica=getdate()
	UPDATE BILANCIO_AGRICOLO
	SET
		ID_IMPRESA = @IdImpresa, 
		ID_PROGETTO = @IdProgetto, 
		ANNO = @Anno, 
		DATA_BILANCIO = @DataBilancio, 
		PREVISIONALE = @Previsionale, 
		DATA_MODIFICA = @DataModifica, 
		PLV_RICAVI_NETTI = @PlvRicaviNetti, 
		PLV_RICAVI_ATTIVITA = @PlvRicaviAttivita, 
		PLV_RIMANENZE_FINALI = @PlvRimanenzeFinali, 
		PLV_RIMANENZE_INIZIALI = @PlvRimanenzeIniziali, 
		VA_COSTI_MAT_PRIME = @VaCostiMatPrime, 
		VA_COSTI_ATT_CONNESSE = @VaCostiAttConnesse, 
		VA_NOLEGGI = @VaNoleggi, 
		VA_MANUTENZIONI = @VaManutenzioni, 
		VA_SPESE_GENERALI = @VaSpeseGenerali, 
		VA_AFFITTI = @VaAffitti, 
		VA_ALTRI_COSTI = @VaAltriCosti, 
		PN_AMM_MACCHINE = @PnAmmMacchine, 
		PN_AMM_FABBRICATI = @PnAmmFabbricati, 
		PN_AMM_PIANTAGIONI = @PnAmmPiantagioni, 
		RO_SALARI = @RoSalari, 
		RO_ONERI = @RoOneri, 
		RN_PAC_RICAVI = @RnPacRicavi, 
		RN_PAC_COSTI = @RnPacCosti, 
		RN_PAC_PROVENTI = @RnPacProventi, 
		RN_PAC_PERDITE = @RnPacPerdite, 
		RN_PAC_INTERESSI_ATTIVI = @RnPacInteressiAttivi, 
		RN_PAC_INTERESSI_PASSIVI = @RnPacInteressiPassivi, 
		RN_PAC_IMPOSTE = @RnPacImposte, 
		RN_PAC_CONTRIBUTI_PAC = @RnPacContributiPac, 
		MNL_REDDITI_FAM = @MnlRedditiFam, 
		MNL_RIMBORSO = @MnlRimborso, 
		MNL_PRELIEVI = @MnlPrelievi, 
		CF_CF_TERRENI = @CfCfTerreni, 
		CF_CF_IMPIANTI = @CfCfImpianti, 
		CF_CF_PIANTAGIONI = @CfCfPiantagioni, 
		CF_CF_MIGLIORAMENTI = @CfCfMiglioramenti, 
		CF_CA_MACCHINE = @CfCaMacchine, 
		CF_CA_BESTIAME = @CfCaBestiame, 
		CF_IF_PARTECIPAZIONI = @CfIfPartecipazioni, 
		CC_DF_RIMANENZE = @CcDfRimanenze, 
		CC_DF_ANTICIPAZIONI = @CcDfAnticipazioni, 
		CC_LD_CREDITI = @CcLdCrediti, 
		CC_LI_BANCA = @CcLiBanca, 
		CC_LI_CASSA = @CcLiCassa, 
		FF_PC_DEBITI_BREVE_TERMINE = @FfPcDebitiBreveTermine, 
		FF_PC_FORNITORI = @FfPcFornitori, 
		FF_PC_DEBITI = @FfPcDebiti, 
		FF_PC_MUTUI = @FfPcMutui, 
		FF_MP_CAPITALE = @FfMpCapitale, 
		FF_MP_RISERVE = @FfMpRiserve, 
		FF_MP_UTILE = @FfMpUtile
	WHERE 
		(ID_BILANCIO_AGRICOLO = @IdBilancioAgricolo)
	SELECT @DataModifica;

GO
EXECUTE sp_addextendedproperty @name = N'backup', @value = N'CREATE PROCEDURE [dbo].[ZBilancioAgricoloUpdate]
(
	@IdBilancioAgricolo INT, 
	@IdImpresa INT, 
	@IdProgetto INT, 
	@Anno INT, 
	@DataBilancio DATETIME, 
	@Previsionale BIT, 
	@PlvRicaviNetti DECIMAL(15,2), 
	@PlvRicaviAttivita DECIMAL(15,2), 
	@PlvRimanenzeFinali DECIMAL(15,2), 
	@PlvRimanenzeIniziali DECIMAL(15,2), 
	@VaCostiMatPrime DECIMAL(15,2), 
	@VaCostiAttConnesse DECIMAL(15,2), 
	@VaNoleggi DECIMAL(15,2), 
	@VaManutenzioni DECIMAL(15,2), 
	@VaSpeseGenerali DECIMAL(15,2), 
	@VaAffitti DECIMAL(15,2), 
	@VaAltriCosti DECIMAL(15,2), 
	@PnAmmMacchine DECIMAL(15,2), 
	@PnAmmFabbricati DECIMAL(15,2), 
	@PnAmmPiantagioni DECIMAL(15,2), 
	@RoSalari DECIMAL(15,2), 
	@RoOneri DECIMAL(15,2), 
	@RnPacRicavi DECIMAL(15,2), 
	@RnPacCosti DECIMAL(15,2), 
	@RnPacProventi DECIMAL(15,2), 
	@RnPacPerdite DECIMAL(15,2), 
	@RnPacInteressiAttivi DECIMAL(15,2), 
	@RnPacInteressiPassivi DECIMAL(15,2), 
	@RnPacImposte DECIMAL(15,2), 
	@RnPacContributiPac DECIMAL(15,2), 
	@MnlRedditiFam DECIMAL(15,2), 
	@MnlRimborso DECIMAL(15,2), 
	@MnlPrelievi DECIMAL(15,2), 
	@CfCfTerreni DECIMAL(15,2), 
	@CfCfImpianti DECIMAL(15,2), 
	@CfCfPiantagioni DECIMAL(15,2), 
	@CfCfMiglioramenti DECIMAL(15,2), 
	@CfCaMacchine DECIMAL(15,2), 
	@CfCaBestiame DECIMAL(15,2), 
	@CfIfPartecipazioni DECIMAL(15,2), 
	@CcDfRimanenze DECIMAL(15,2), 
	@CcDfAnticipazioni DECIMAL(15,2), 
	@CcLdCrediti DECIMAL(15,2), 
	@CcLiBanca DECIMAL(15,2), 
	@CcLiCassa DECIMAL(15,2), 
	@FfPcDebitiBreveTermine DECIMAL(15,2), 
	@FfPcFornitori DECIMAL(15,2), 
	@FfPcDebiti DECIMAL(15,2), 
	@FfPcMutui DECIMAL(15,2), 
	@FfMpCapitale DECIMAL(15,2), 
	@FfMpRiserve DECIMAL(15,2), 
	@FfMpUtile DECIMAL(15,2)
)
AS
	UPDATE BILANCIO_AGRICOLO
	SET
		ID_IMPRESA = @IdImpresa, 
		ID_PROGETTO = @IdProgetto, 
		ANNO = @Anno, 
		DATA_BILANCIO = @DataBilancio, 
		PREVISIONALE = @Previsionale, 
		PLV_RICAVI_NETTI = @PlvRicaviNetti, 
		PLV_RICAVI_ATTIVITA = @PlvRicaviAttivita, 
		PLV_RIMANENZE_FINALI = @PlvRimanenzeFinali, 
		PLV_RIMANENZE_INIZIALI = @PlvRimanenzeIniziali, 
		VA_COSTI_MAT_PRIME = @VaCostiMatPrime, 
		VA_COSTI_ATT_CONNESSE = @VaCostiAttConnesse, 
		VA_NOLEGGI = @VaNoleggi, 
		VA_MANUTENZIONI = @VaManutenzioni, 
		VA_SPESE_GENERALI = @VaSpeseGenerali, 
		VA_AFFITTI = @VaAffitti, 
		VA_ALTRI_COSTI = @VaAltriCosti, 
		PN_AMM_MACCHINE = @PnAmmMacchine, 
		PN_AMM_FABBRICATI = @PnAmmFabbricati, 
		PN_AMM_PIANTAGIONI = @PnAmmPiantagioni, 
		RO_SALARI = @RoSalari, 
		RO_ONERI = @RoOneri, 
		RN_PAC_RICAVI = @RnPacRicavi, 
		RN_PAC_COSTI = @RnPacCosti, 
		RN_PAC_PROVENTI = @RnPacProventi, 
		RN_PAC_PERDITE = @RnPacPerdite, 
		RN_PAC_INTERESSI_ATTIVI = @RnPacInteressiAttivi, 
		RN_PAC_INTERESSI_PASSIVI = @RnPacInteressiPassivi, 
		RN_PAC_IMPOSTE = @RnPacImposte, 
		RN_PAC_CONTRIBUTI_PAC = @RnPacContributiPac, 
		MNL_REDDITI_FAM = @MnlRedditiFam, 
		MNL_RIMBORSO = @MnlRimborso, 
		MNL_PRELIEVI = @MnlPrelievi, 
		CF_CF_TERRENI = @CfCfTerreni, 
		CF_CF_IMPIANTI = @CfCfImpianti, 
		CF_CF_PIANTAGIONI = @CfCfPiantagioni, 
		CF_CF_MIGLIORAMENTI = @CfCfMiglioramenti, 
		CF_CA_MACCHINE = @CfCaMacchine, 
		CF_CA_BESTIAME = @CfCaBestiame, 
		CF_IF_PARTECIPAZIONI = @CfIfPartecipazioni, 
		CC_DF_RIMANENZE = @CcDfRimanenze, 
		CC_DF_ANTICIPAZIONI = @CcDfAnticipazioni, 
		CC_LD_CREDITI = @CcLdCrediti, 
		CC_LI_BANCA = @CcLiBanca, 
		CC_LI_CASSA = @CcLiCassa, 
		FF_PC_DEBITI_BREVE_TERMINE = @FfPcDebitiBreveTermine, 
		FF_PC_FORNITORI = @FfPcFornitori, 
		FF_PC_DEBITI = @FfPcDebiti, 
		FF_PC_MUTUI = @FfPcMutui, 
		FF_MP_CAPITALE = @FfMpCapitale, 
		FF_MP_RISERVE = @FfMpRiserve, 
		FF_MP_UTILE = @FfMpUtile
	WHERE 
		(ID_BILANCIO_AGRICOLO = @IdBilancioAgricolo)

', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'PROCEDURE', @level1name = N'ZBilancioAgricoloUpdate';

