CREATE PROCEDURE [dbo].[zCUPGetDescrizioneRealizzAcquistoServiziRicerca]
(
	@IdProgetto INT 
)
AS
BEGIN


SELECT 
P.ID_PROGETTO AS id_progetto,
--IPS.RAGIONE_SOCIALE AS denominazione_progetto,
--IPS.RAGIONE_SOCIALE AS ente,
LEFT(REPLACE(IPS.RAGIONE_SOCIALE,'*',' '),100) AS denominazione_progetto,
LEFT(REPLACE(IPS.RAGIONE_SOCIALE,'*',' '),100) AS ente,
I.CUAA as partita_iva,
--CASE WHEN BRT.TESTO IS NULL  
--THEN LEFT(IPS.RAGIONE_SOCIALE,100) 
--ELSE LEFT(CAST(BRT.TESTO AS VARCHAR(MAX)),100) END AS descrizione_intervento,
LEFT('PROGETTO ID SIGEF ' + CONVERT(VARCHAR(10),P.ID_PROGETTO) + ' POR MARCHE FESR 2014-2020 - Azione ' + ZP.CODICE + ' ' + ZP.DESCRIZIONE, 256) AS descrizione_intervento,
CASE WHEN TIPO_DUG.Descrizione = 'Altro' THEN
LEFT(LP.VIA + ' ' + LP.NUM + ' ' + LP.CAP + ' ' + COMUNI.DENOMINAZIONE,100) ELSE
LEFT(TIPO_DUG.Descrizione + ' ' + LP.VIA + ' ' + LP.NUM + ' ' + LP.CAP + ' ' + COMUNI.DENOMINAZIONE,100) END AS ind_area_rif,
LP.CAP AS cap_area_rif,
LP.NUM AS numero_area_rif
FROM 
vPROGETTO P
INNER JOIN LOCALIZZAZIONE_PROGETTO LP ON
P.ID_PROGETTO = LP.ID_PROGETTO
AND
P.ID_IMPRESA = LP.ID_IMPRESA
INNER JOIN TIPO_DUG ON
LP.DUG = TIPO_DUG.ID_DUG
INNER JOIN COMUNI ON
LP.ID_COMUNE = COMUNI.ID_COMUNE
INNER JOIN IMPRESA I ON
P.ID_IMPRESA = I.ID_IMPRESA
INNER JOIN IMPRESA_STORICO IPS ON
I.ID_STORICO_ULTIMO = IPS.ID_STORICO_IMPRESA
INNER JOIN vBANDO B ON 
P.ID_BANDO = B.ID_BANDO
INNER JOIN zPROGRAMMAZIONE ZP ON
B.ID_PROGRAMMAZIONE = ZP.ID
LEFT OUTER JOIN
(
	SELECT   
	PROGETTO.ID_PROGETTO, 
	PROGETTO.ID_BANDO, 
	dbo.BANDO_RELAZIONE_TECNICA.ORDINE, 
	dbo.PROGETTO_RELAZIONE_TECNICA.TESTO
	FROM         
	dbo.BANDO_RELAZIONE_TECNICA 
	INNER JOIN
	dbo.PROGETTO_RELAZIONE_TECNICA ON 
	dbo.BANDO_RELAZIONE_TECNICA.ID_PARAGRAFO = dbo.PROGETTO_RELAZIONE_TECNICA.ID_PARAGRAFO 
	INNER JOIN
	dbo.vPROGETTO PROGETTO ON 
	dbo.PROGETTO_RELAZIONE_TECNICA.ID_PROGETTO = PROGETTO.ID_PROGETTO
	WHERE 
	dbo.BANDO_RELAZIONE_TECNICA.ORDINE = 1 
	AND 
	PROGETTO.COD_STATO NOT IN ('P','L','A','Q','B','N','I')
) BRT ON
P.ID_PROGETTO = BRT.ID_PROGETTO
WHERE 
P.COD_STATO NOT IN ('P','L','A','Q','B','N','I')
AND
P.ID_PROGETTO = @IdProgetto


END

--SELECT 
--P.ID_PROGETTO as id_progetto,
--IPS.RAGIONE_SOCIALE as denominazione_progetto,
--IPS.RAGIONE_SOCIALE as ente,
--I.CODICE_FISCALE as partita_iva,
----LP.DUG AS tipo_indirizzo,
--IPS.RAGIONE_SOCIALE as descrizione_intervento,
--LP.VIA as ind_area_rifer,
--LP.CAP AS cap_area_rif,
--LP.NUM as numero_area_rif
--FROM 
--PROGETTO P
--INNER JOIN DATI_MONITORAGGIO_FESR DMF ON
--P.ID_PROGETTO = DMF.ID_PROGETTO
--INNER JOIN TIPO_CUP_CATEGORIE TCC ON
--DMF.CUP_CATEGORIA = TCC.COD_CUP_CATEGORIE
--INNER JOIN PROGETTO_STORICO PS ON
--P.ID_PROGETTO = PS.ID_PROGETTO
--INNER JOIN LOCALIZZAZIONE_PROGETTO LP ON
--P.ID_PROGETTO = LP.ID_PROGETTO
--INNER JOIN IMPRESA I ON
--P.ID_IMPRESA = I.ID_IMPRESA
--INNER JOIN IMPRESA_STORICO IPS ON
--I.ID_STORICO_ULTIMO = IPS.ID_STORICO_IMPRESA
----INNER JOIN INDIRIZZARIO IND ON
----I.ID_IMPRESA = IND.ID_IMPRESA 
----AND IND.COD_TIPO_SEDE = 'S'
----AND IND.DATA_FINE_VALIDITA IS NULL 
----AND FLAG_ATTIVO = 1
----INNER JOIN INDIRIZZO ON
----IND.ID_INDIRIZZO = INDIRIZZO.ID_INDIRIZZO
----INNER JOIN COMUNI C ON
----LP.ID_COMUNE = C.ID_COMUNE
--WHERE 
----PS.COD_STATO = 'I' --DA CAMBIARE IN 'F' non appena ci sono domande finanziabili
----AND
--P.ID_PROGETTO = @IdProgetto 
--END
