CREATE PROCEDURE [dbo].[zCUPGetDescrizionePartecipAzionarieConferimCapitale]
(
	@IdProgetto INT 
)
AS
BEGIN


SELECT 
P.ID_PROGETTO AS id_progetto,
--LEFT(IPS.RAGIONE_SOCIALE,100) AS ragione_sociale,
LEFT(REPLACE(IPS.RAGIONE_SOCIALE,'*',' '),100) AS ragione_sociale,
I.CUAA AS partita_iva,
'03' AS finalita,
CASE WHEN TIPO_DUG.Descrizione = 'Altro' THEN
LEFT(LP.VIA + ' ' + LP.NUM + ' ' + LP.CAP + ' ' + COMUNI.DENOMINAZIONE,100) ELSE
LEFT(TIPO_DUG.Descrizione + ' ' + LP.VIA + ' ' + LP.NUM + ' ' + LP.CAP + ' ' + COMUNI.DENOMINAZIONE,100) END AS ind_area_rif,
LP.CAP AS cap_area_rif,
LP.NUM AS numero_area_rif
FROM 
vPROGETTO P
INNER JOIN LOCALIZZAZIONE_PROGETTO LP ON
P.ID_PROGETTO = LP.ID_PROGETTO
AND
P.ID_IMPRESA = LP.ID_IMPRESA
INNER JOIN TIPO_DUG ON
LP.DUG = TIPO_DUG.ID_DUG
INNER JOIN COMUNI ON
LP.ID_COMUNE = COMUNI.ID_COMUNE
INNER JOIN IMPRESA I ON
P.ID_IMPRESA = I.ID_IMPRESA
INNER JOIN IMPRESA_STORICO IPS ON
I.ID_STORICO_ULTIMO = IPS.ID_STORICO_IMPRESA
WHERE 
P.COD_STATO NOT IN ('P','L','A','Q','B','N','I')
AND
P.ID_PROGETTO = @IdProgetto


END

--SELECT 
--P.ID_PROGETTO as id_progetto,
--IPS.RAGIONE_SOCIALE as ragione_sociale,
--I.CODICE_FISCALE as partita_iva,
----LP.DUG AS tipo_indirizzo,
--'03' AS finalita,
--LP.VIA as ind_area_rif,
--LP.CAP AS cap_area_rif,
--LP.NUM as numero_area_rif
--FROM 
--PROGETTO P
--INNER JOIN DATI_MONITORAGGIO_FESR DMF ON
--P.ID_PROGETTO = DMF.ID_PROGETTO
--INNER JOIN TIPO_CUP_CATEGORIE TCC ON
--DMF.CUP_CATEGORIA = TCC.COD_CUP_CATEGORIE
--INNER JOIN PROGETTO_STORICO PS ON
--P.ID_PROGETTO = PS.ID_PROGETTO
--INNER JOIN LOCALIZZAZIONE_PROGETTO LP ON
--P.ID_PROGETTO = LP.ID_PROGETTO
--INNER JOIN IMPRESA I ON
--P.ID_IMPRESA = I.ID_IMPRESA
--INNER JOIN IMPRESA_STORICO IPS ON
--I.ID_STORICO_ULTIMO = IPS.ID_STORICO_IMPRESA
----INNER JOIN INDIRIZZARIO IND ON
----I.ID_IMPRESA = IND.ID_IMPRESA 
----AND IND.COD_TIPO_SEDE = 'S'
----AND IND.DATA_FINE_VALIDITA IS NULL 
----AND FLAG_ATTIVO = 1
----INNER JOIN INDIRIZZO ON
----IND.ID_INDIRIZZO = INDIRIZZO.ID_INDIRIZZO
----INNER JOIN COMUNI C ON
----LP.ID_COMUNE = C.ID_COMUNE
--WHERE 
----PS.COD_STATO = 'I' --DA CAMBIARE IN 'F' non appena ci sono domande finanziabili
----AND
--P.ID_PROGETTO = @IdProgetto 
--END
