CREATE PROCEDURE [dbo].[ZDomandaDiPagamentoEsportazioneFindFind]
(
	@IdDomandaPagamentoequalthis INT, 
	@IdProgettoequalthis INT, 
	@Barcodeequalthis VARCHAR(255)
)
AS
	declare @sql nvarchar(4000);
	declare @lensql int;
	set @lensql=0;
	SET @sql = 'SELECT ID_DOMANDA_PAGAMENTO, ID_PROGETTO, BARCODE, MISURA_PREVALENTE, IMPORTO_AMMISSIBILE, IMPORTO_SANZIONE, IMPORTO_RECUPERO_ANTICIPO, IMPORTO_AMMESSO, IMPORTO_LIQUIDATO, FLAG_LIQUIDATO, ID_DECRETO, COD_TIPO, DATA_INSERIMENTO, CF_OPERATORE, DATA_MODIFICA, COD_ENTE, SEGNATURA, SEGNATURA_ALLEGATI, ID_FIDEJUSSIONE, DATA_CERTIFICAZIONE_ANTIMAFIA, APPROVATA, SEGNATURA_APPROVAZIONE, SEGNATURA_SECONDA_APPROVAZIONE, CF_ISTRUTTORE, DATA_APPROVAZIONE, VALUTAZIONE_ISTRUTTORE, ANNULLATA, SEGNATURA_ANNULLAMENTO, CF_OPERATORE_ANNULLAMENTO, DATA_ANNULLAMENTO, VALIDITA_VERSIONE_ADC, ID_VARIAZIONE_ACCERTATA, PREDISPOSTA_A_CONTROLLO, DATA_PREDISPOSIZIONE_A_CONTROLLO, VISITA_INSITU_ESITO, VISITA_INSITU_NOTE, CONTROLLO_INLOCO_ESITO, CONTROLLO_INLOCO_NOTE, VERIFICA_PAGAMENTI_ESITO, VERIFICA_PAGAMENTI_MESSAGGIO, VERIFICA_PAGAMENTI_DATA, FIRMA_PREDISPOSTA, IN_INTEGRAZIONE FROM VDOMANDA_DI_PAGAMENTO_ESPORTAZIONE WHERE 1=1';
	IF (@IdDomandaPagamentoequalthis IS NOT NULL) BEGIN SET @sql = @sql + ' AND (ID_DOMANDA_PAGAMENTO = @IdDomandaPagamentoequalthis)'; set @lensql=@lensql+len(@IdDomandaPagamentoequalthis);end;
	IF (@IdProgettoequalthis IS NOT NULL) BEGIN SET @sql = @sql + ' AND (ID_PROGETTO = @IdProgettoequalthis)'; set @lensql=@lensql+len(@IdProgettoequalthis);end;
	IF (@Barcodeequalthis IS NOT NULL) BEGIN SET @sql = @sql + ' AND (BARCODE = @Barcodeequalthis)'; set @lensql=@lensql+len(@Barcodeequalthis);end;
	set @lensql=@lensql+len(@sql);
	if (@lensql<3000)
	exec sp_executesql @sql,N'@IdDomandaPagamentoequalthis INT, @IdProgettoequalthis INT, @Barcodeequalthis VARCHAR(255)',@IdDomandaPagamentoequalthis , @IdProgettoequalthis , @Barcodeequalthis ;
	else
		SELECT ID_DOMANDA_PAGAMENTO, ID_PROGETTO, BARCODE, MISURA_PREVALENTE, IMPORTO_AMMISSIBILE, IMPORTO_SANZIONE, IMPORTO_RECUPERO_ANTICIPO, IMPORTO_AMMESSO, IMPORTO_LIQUIDATO, FLAG_LIQUIDATO, ID_DECRETO, COD_TIPO, DATA_INSERIMENTO, CF_OPERATORE, DATA_MODIFICA, COD_ENTE, SEGNATURA, SEGNATURA_ALLEGATI, ID_FIDEJUSSIONE, DATA_CERTIFICAZIONE_ANTIMAFIA, APPROVATA, SEGNATURA_APPROVAZIONE, SEGNATURA_SECONDA_APPROVAZIONE, CF_ISTRUTTORE, DATA_APPROVAZIONE, VALUTAZIONE_ISTRUTTORE, ANNULLATA, SEGNATURA_ANNULLAMENTO, CF_OPERATORE_ANNULLAMENTO, DATA_ANNULLAMENTO, VALIDITA_VERSIONE_ADC, ID_VARIAZIONE_ACCERTATA, PREDISPOSTA_A_CONTROLLO, DATA_PREDISPOSIZIONE_A_CONTROLLO, VISITA_INSITU_ESITO, VISITA_INSITU_NOTE, CONTROLLO_INLOCO_ESITO, CONTROLLO_INLOCO_NOTE, VERIFICA_PAGAMENTI_ESITO, VERIFICA_PAGAMENTI_MESSAGGIO, VERIFICA_PAGAMENTI_DATA, FIRMA_PREDISPOSTA, IN_INTEGRAZIONE
		FROM VDOMANDA_DI_PAGAMENTO_ESPORTAZIONE
		WHERE 
			((@IdDomandaPagamentoequalthis IS NULL) OR ID_DOMANDA_PAGAMENTO = @IdDomandaPagamentoequalthis) AND 
			((@IdProgettoequalthis IS NULL) OR ID_PROGETTO = @IdProgettoequalthis) AND 
			((@Barcodeequalthis IS NULL) OR BARCODE = @Barcodeequalthis)
		


GO
EXECUTE sp_addextendedproperty @name = N'backup', @value = 'CREATE PROCEDURE [dbo].[ZDomandaDiPagamentoEsportazioneFindFind]
(
	@IdDomandaPagamentoequalthis INT, 
	@IdProgettoequalthis INT, 
	@Barcodeequalthis VARCHAR(255)
)
AS
	declare @sql nvarchar(4000);
	declare @lensql int;
	set @lensql=0;
	SET @sql = ''SELECT ID_DOMANDA_PAGAMENTO, ID_PROGETTO, BARCODE, MISURA_PREVALENTE, IMPORTO_AMMISSIBILE, IMPORTO_SANZIONE, IMPORTO_RECUPERO_ANTICIPO, IMPORTO_AMMESSO, IMPORTO_LIQUIDATO, FLAG_LIQUIDATO, ID_DECRETO, COD_TIPO, DATA_INSERIMENTO, CF_OPERATORE, DATA_MODIFICA, COD_ENTE, SEGNATURA, SEGNATURA_ALLEGATI, ID_FIDEJUSSIONE, DATA_CERTIFICAZIONE_ANTIMAFIA, APPROVATA, SEGNATURA_APPROVAZIONE, SEGNATURA_SECONDA_APPROVAZIONE, CF_ISTRUTTORE, DATA_APPROVAZIONE, VALUTAZIONE_ISTRUTTORE, ANNULLATA, SEGNATURA_ANNULLAMENTO, CF_OPERATORE_ANNULLAMENTO, DATA_ANNULLAMENTO, VALIDITA_VERSIONE_ADC, ID_VARIAZIONE_ACCERTATA, PREDISPOSTA_A_CONTROLLO, DATA_PREDISPOSIZIONE_A_CONTROLLO, VISITA_INSITU_ESITO, VISITA_INSITU_NOTE, CONTROLLO_INLOCO_ESITO, CONTROLLO_INLOCO_NOTE, VERIFICA_PAGAMENTI_ESITO, VERIFICA_PAGAMENTI_MESSAGGIO, VERIFICA_PAGAMENTI_DATA, FIRMA_PREDISPOSTA, IN_INTEGRAZIONE FROM VDOMANDA_DI_PAGAMENTO_ESPORTAZIONE WHERE 1=1'';
	IF (@IdDomandaPagamentoequalthis IS NOT NULL) BEGIN SET @sql = @sql + '' AND (ID_DOMANDA_PAGAMENTO = @IdDomandaPagamentoequalthis)''; set @lensql=@lensql+len(@IdDomandaPagamentoequalthis);end;
	IF (@IdProgettoequalthis IS NOT NULL) BEGIN SET @sql = @sql + '' AND (ID_PROGETTO = @IdProgettoequalthis)''; set @lensql=@lensql+len(@IdProgettoequalthis);end;
	IF (@Barcodeequalthis IS NOT NULL) BEGIN SET @sql = @sql + '' AND (BARCODE = @Barcodeequalthis)''; set @lensql=@lensql+len(@Barcodeequalthis);end;
	set @lensql=@lensql+len(@sql);
	if (@lensql<3000)
	exec sp_executesql @sql,N''@IdDomandaPagamentoequalthis INT, @IdProgettoequalthis INT, @Barcodeequalthis VARCHAR(255)'',@IdDomandaPagamentoequalthis , @IdProgettoequalthis , @Barcodeequalthis ;
	else
		SELECT ID_DOMANDA_PAGAMENTO, ID_PROGETTO, BARCODE, MISURA_PREVALENTE, IMPORTO_AMMISSIBILE, IMPORTO_SANZIONE, IMPORTO_RECUPERO_ANTICIPO, IMPORTO_AMMESSO, IMPORTO_LIQUIDATO, FLAG_LIQUIDATO, ID_DECRETO, COD_TIPO, DATA_INSERIMENTO, CF_OPERATORE, DATA_MODIFICA, COD_ENTE, SEGNATURA, SEGNATURA_ALLEGATI, ID_FIDEJUSSIONE, DATA_CERTIFICAZIONE_ANTIMAFIA, APPROVATA, SEGNATURA_APPROVAZIONE, SEGNATURA_SECONDA_APPROVAZIONE, CF_ISTRUTTORE, DATA_APPROVAZIONE, VALUTAZIONE_ISTRUTTORE, ANNULLATA, SEGNATURA_ANNULLAMENTO, CF_OPERATORE_ANNULLAMENTO, DATA_ANNULLAMENTO, VALIDITA_VERSIONE_ADC, ID_VARIAZIONE_ACCERTATA, PREDISPOSTA_A_CONTROLLO, DATA_PREDISPOSIZIONE_A_CONTROLLO, VISITA_INSITU_ESITO, VISITA_INSITU_NOTE, CONTROLLO_INLOCO_ESITO, CONTROLLO_INLOCO_NOTE, VERIFICA_PAGAMENTI_ESITO, VERIFICA_PAGAMENTI_MESSAGGIO, VERIFICA_PAGAMENTI_DATA, FIRMA_PREDISPOSTA, IN_INTEGRAZIONE
		FROM VDOMANDA_DI_PAGAMENTO_ESPORTAZIONE
		WHERE 
			((@IdDomandaPagamentoequalthis IS NULL) OR ID_DOMANDA_PAGAMENTO = @IdDomandaPagamentoequalthis) AND 
			((@IdProgettoequalthis IS NULL) OR ID_PROGETTO = @IdProgettoequalthis) AND 
			((@Barcodeequalthis IS NULL) OR BARCODE = @Barcodeequalthis)
		

', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'PROCEDURE', @level1name = N'ZDomandaDiPagamentoEsportazioneFindFind';

