CREATE PROCEDURE [dbo].[ZFidejussioniInsert]
(
	@Numero VARCHAR(25), 
	@Barcode VARCHAR(11), 
	@DataSottoscrizione DATETIME, 
	@LuogoSottoscrizione VARCHAR(128), 
	@Importo DECIMAL(18,2), 
	@AmmontareRichiesto DECIMAL(18,2), 
	@DataFineLavori DATETIME, 
	@DataScadenza DATETIME, 
	@ProrogaScadenza BIT, 
	@PivaGarante VARCHAR(11), 
	@RagioneSocialeGarante VARCHAR(150), 
	@LocalitaGarante VARCHAR(128), 
	@NumeroRegistroImprese VARCHAR(10), 
	@CognomeRapplegale VARCHAR(30), 
	@NomeRapplegale VARCHAR(20), 
	@CfRapplegale VARCHAR(16), 
	@DataNascitaRapplegale DATETIME, 
	@StampaEffettuata BIT, 
	@DataRichiestaValidita DATETIME, 
	@DataRicevimentoValidita DATETIME, 
	@ProtocolloFaxValidita VARCHAR(100), 
	@DataDecorrenzaGaranzia DATETIME, 
	@CodiceAbiEnteGarante VARCHAR(5), 
	@CodiceCabEnteGarante VARCHAR(5), 
	@BarcodeConfermaValidita VARCHAR(11), 
	@CodTipo CHAR(3), 
	@UfficioApprovazione VARCHAR(120), 
	@NumDecretoApprovazione INT, 
	@DataDecretoApprovazione DATETIME
)
AS
	SET @ProrogaScadenza = ISNULL(@ProrogaScadenza,((0)))
	SET @StampaEffettuata = ISNULL(@StampaEffettuata,((0)))
	INSERT INTO FIDEJUSSIONI
	(
		NUMERO, 
		BARCODE, 
		DATA_SOTTOSCRIZIONE, 
		LUOGO_SOTTOSCRIZIONE, 
		IMPORTO, 
		AMMONTARE_RICHIESTO, 
		DATA_FINE_LAVORI, 
		DATA_SCADENZA, 
		PROROGA_SCADENZA, 
		PIVA_GARANTE, 
		RAGIONE_SOCIALE_GARANTE, 
		LOCALITA_GARANTE, 
		NUMERO_REGISTRO_IMPRESE, 
		COGNOME_RAPPLEGALE, 
		NOME_RAPPLEGALE, 
		CF_RAPPLEGALE, 
		DATA_NASCITA_RAPPLEGALE, 
		STAMPA_EFFETTUATA, 
		DATA_RICHIESTA_VALIDITA, 
		DATA_RICEVIMENTO_VALIDITA, 
		PROTOCOLLO_FAX_VALIDITA, 
		DATA_DECORRENZA_GARANZIA, 
		CODICE_ABI_ENTE_GARANTE, 
		CODICE_CAB_ENTE_GARANTE, 
		BARCODE_CONFERMA_VALIDITA, 
		COD_TIPO, 
		UFFICIO_APPROVAZIONE, 
		NUM_DECRETO_APPROVAZIONE, 
		DATA_DECRETO_APPROVAZIONE
	)
	VALUES
	(
		@Numero, 
		@Barcode, 
		@DataSottoscrizione, 
		@LuogoSottoscrizione, 
		@Importo, 
		@AmmontareRichiesto, 
		@DataFineLavori, 
		@DataScadenza, 
		@ProrogaScadenza, 
		@PivaGarante, 
		@RagioneSocialeGarante, 
		@LocalitaGarante, 
		@NumeroRegistroImprese, 
		@CognomeRapplegale, 
		@NomeRapplegale, 
		@CfRapplegale, 
		@DataNascitaRapplegale, 
		@StampaEffettuata, 
		@DataRichiestaValidita, 
		@DataRicevimentoValidita, 
		@ProtocolloFaxValidita, 
		@DataDecorrenzaGaranzia, 
		@CodiceAbiEnteGarante, 
		@CodiceCabEnteGarante, 
		@BarcodeConfermaValidita, 
		@CodTipo, 
		@UfficioApprovazione, 
		@NumDecretoApprovazione, 
		@DataDecretoApprovazione
	)
	SELECT SCOPE_IDENTITY() AS ID_FIDEJUSSIONE, @ProrogaScadenza AS PROROGA_SCADENZA, @StampaEffettuata AS STAMPA_EFFETTUATA

GO
EXECUTE sp_addextendedproperty @name = N'backup', @value = N'CREATE PROCEDURE [dbo].[ZFidejussioniInsert]
(
	@Numero VARCHAR(25), 
	@Barcode VARCHAR(11), 
	@DataSottoscrizione DATETIME, 
	@LuogoSottoscrizione VARCHAR(128), 
	@Importo DECIMAL(18,2), 
	@AmmontareRichiesto DECIMAL(18,2), 
	@DataFineLavori DATETIME, 
	@DataScadenza DATETIME, 
	@ProrogaScadenza BIT, 
	@PivaGarante VARCHAR(11), 
	@RagioneSocialeGarante VARCHAR(150), 
	@LocalitaGarante VARCHAR(128), 
	@NumeroRegistroImprese VARCHAR(10), 
	@CognomeRapplegale VARCHAR(30), 
	@NomeRapplegale VARCHAR(20), 
	@CfRapplegale VARCHAR(16), 
	@DataNascitaRapplegale DATETIME, 
	@StampaEffettuata BIT, 
	@DataRichiestaValidita DATETIME, 
	@DataRicevimentoValidita DATETIME, 
	@ProtocolloFaxValidita VARCHAR(100), 
	@DataDecorrenzaGaranzia DATETIME, 
	@CodiceAbiEnteGarante VARCHAR(5), 
	@CodiceCabEnteGarante VARCHAR(5), 
	@BarcodeConfermaValidita VARCHAR(11), 
	@CodTipo CHAR(3)
)
AS
	SET @ProrogaScadenza = ISNULL(@ProrogaScadenza,((0)))
	SET @StampaEffettuata = ISNULL(@StampaEffettuata,((0)))
	INSERT INTO FIDEJUSSIONI
	(
		NUMERO, 
		BARCODE, 
		DATA_SOTTOSCRIZIONE, 
		LUOGO_SOTTOSCRIZIONE, 
		IMPORTO, 
		AMMONTARE_RICHIESTO, 
		DATA_FINE_LAVORI, 
		DATA_SCADENZA, 
		PROROGA_SCADENZA, 
		PIVA_GARANTE, 
		RAGIONE_SOCIALE_GARANTE, 
		LOCALITA_GARANTE, 
		NUMERO_REGISTRO_IMPRESE, 
		COGNOME_RAPPLEGALE, 
		NOME_RAPPLEGALE, 
		CF_RAPPLEGALE, 
		DATA_NASCITA_RAPPLEGALE, 
		STAMPA_EFFETTUATA, 
		DATA_RICHIESTA_VALIDITA, 
		DATA_RICEVIMENTO_VALIDITA, 
		PROTOCOLLO_FAX_VALIDITA, 
		DATA_DECORRENZA_GARANZIA, 
		CODICE_ABI_ENTE_GARANTE, 
		CODICE_CAB_ENTE_GARANTE, 
		BARCODE_CONFERMA_VALIDITA, 
		COD_TIPO
	)
	VALUES
	(
		@Numero, 
		@Barcode, 
		@DataSottoscrizione, 
		@LuogoSottoscrizione, 
		@Importo, 
		@AmmontareRichiesto, 
		@DataFineLavori, 
		@DataScadenza, 
		@ProrogaScadenza, 
		@PivaGarante, 
		@RagioneSocialeGarante, 
		@LocalitaGarante, 
		@NumeroRegistroImprese, 
		@CognomeRapplegale, 
		@NomeRapplegale, 
		@CfRapplegale, 
		@DataNascitaRapplegale, 
		@StampaEffettuata, 
		@DataRichiestaValidita, 
		@DataRicevimentoValidita, 
		@ProtocolloFaxValidita, 
		@DataDecorrenzaGaranzia, 
		@CodiceAbiEnteGarante, 
		@CodiceCabEnteGarante, 
		@BarcodeConfermaValidita, 
		@CodTipo
	)
	SELECT SCOPE_IDENTITY() AS ID_FIDEJUSSIONE, @ProrogaScadenza AS PROROGA_SCADENZA, @StampaEffettuata AS STAMPA_EFFETTUATA

', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'PROCEDURE', @level1name = N'ZFidejussioniInsert';

