CREATE PROCEDURE [dbo].[zIgrueInsertMonitSC00]
( 
 @DataDa DATETIME,
 @DataA DATETIME,
 @IdInvio INT,
 @rNumber INT
)
AS
BEGIN

--01	ACQUISTO DI BENI
--02	ACQUISTO O REALIZZAZIONE DI SERVIZI
--03	REALIZZAZIONE DI LAVORI PUBBLICI (OPERE ED IMPIANTISTICA)
--06	CONCESSIONE DI CONTRIBUTI AD ALTRI SOGGETTI (DIVERSI DA UNITA' PRODUTTIVE)
--07	CONCESSIONE DI INCENTIVI AD UNITA' PRODUTTIVE
--08	SOTTOSCRIZIONE INIZIALE O AUMENTO DI CAPITALE SOCIALE (COMPRESI SPIN OFF), FONDI RISCHIO O GARANZIA



WITH AZ AS 
(
SELECT 
PRG.ID AS ID_PROGRAMMAZIONE,
DIM.COD_DIM,
DIM.CODICE, --COD_DIMENSIONE,
PRG.CODICE COD_INTERVENTO
FROM zDIMENSIONI DIM
INNER JOIN zDIMENSIONI_X_PROGRAMMAZIONE ZDP ON 
ZDP.ID_DIMENSIONE = DIM.ID
INNER JOIN zPROGRAMMAZIONE PRG ON
ZDP.ID_PROGRAMMAZIONE = PRG.ID
WHERE DIM.COD_DIM IN ('RG')
),

PRA AS (
SELECT 
P.ID_PROGETTO AS COD_LOCALE_PROGETTO,
'1' AS COD_RUOLO_SOG,
'80008630420' AS CODICE_FISCALE,
'S' AS FLAG_SOGGETTO_PUBBLICO,
'r_marche' AS COD_UNI_IPA,
'Regione Marche' AS DENOMINAZIONE_SOG,
'2.4.10' AS FORMA_GIURIDICA,
NULL AS SETT_ATT_ECONOMICA,
NULL AS NOTE,
NULL AS FLG_CANCELLAZIONE,
'FESR20142020' AS CODICE_FONDO 
FROM vPROGETTO P
INNER JOIN vBANDO B ON
P.ID_BANDO = B.ID_BANDO
--INNER JOIN PROGETTO_STORICO PS ON
--P.ID_PROGETTO = PS.ID_PROGETTO
INNER JOIN BANDO_PROGRAMMAZIONE BP ON
B.ID_BANDO = BP.ID_BANDO
INNER JOIN zPROGRAMMAZIONE PRG ON
BP.ID_PROGRAMMAZIONE = PRG.ID
INNER JOIN zPSR_ALBERO PA ON
PRG.COD_TIPO = PA.CODICE
INNER JOIN zPSR PSR ON
PA.COD_PSR = PSR.CODICE
INNER JOIN vBANDO_PROGRAMMAZIONE VBP ON
B.ID_BANDO = VBP.ID_BANDO
INNER JOIN AZ ON
VBP.ID_PROGRAMMAZIONE = AZ.ID_PROGRAMMAZIONE
INNER JOIN DATI_MONITORAGGIO_FESR DMFSR ON
P.ID_PROGETTO = DMFSR.ID_PROGETTO
WHERE 
P.COD_STATO IN ('F','V','S','O','T','X','C','Y','E','R') 
AND 
PSR.CODICE = 'POR20142020'
AND 
PRG.ID NOT IN (17,18,19)
AND
P.COD_AGEA IS NOT NULL
)


INSERT INTO IGRUE_MONIT.dbo.IGRUE_SC00
(
   COD_LOCALE_PROGETTO,
   COD_RUOLO_SOG,
   CODICE_FISCALE,
   FLAG_SOGGETTO_PUBBLICO,
   COD_UNI_IPA,
   DENOMINAZIONE_SOG,
   FORMA_GIURIDICA,
   SETT_ATT_ECONOMICA,
   NOTE,
   FLG_CANCELLAZIONE,
   --OPERAZIONE,
   ID_INVIO,
   NR_RIGA_INVIO,
   --NR_RIGA_CANCELLAZIONE,
   CODICE_FONDO
)

SELECT 
A.COD_LOCALE_PROGETTO,
A.COD_RUOLO_SOG,
A.CODICE_FISCALE,
--A.COD_REGIA,
--A.CUP_NATURA,
A.FLAG_SOGGETTO_PUBBLICO,
A.COD_UNI_IPA,
A.DENOMINAZIONE_SOG,
A.FORMA_GIURIDICA,
A.SETT_ATT_ECONOMICA,
A.NOTE,
A.FLG_CANCELLAZIONE,
@IdInvio AS ID_INVIO,
ISNULL(@rNumber,0) + ROW_NUMBER() OVER(ORDER BY A.COD_LOCALE_PROGETTO ASC) AS NR_RIGA_INVIO,
A.CODICE_FONDO
FROM (
SELECT 
P.ID_PROGETTO AS COD_LOCALE_PROGETTO,
'1' AS COD_RUOLO_SOG,
'80008630420' AS CODICE_FISCALE,
AZ.CODICE AS COD_REGIA,
'S' AS FLAG_SOGGETTO_PUBBLICO,
'r_marche' AS COD_UNI_IPA,
'Regione Marche' AS DENOMINAZIONE_SOG,
'2.4.10' AS FORMA_GIURIDICA,
NULL AS SETT_ATT_ECONOMICA,
NULL AS NOTE,
DMFSR.CUP_NATURA,
AZ.COD_DIM AS TIPO_CLASS,
AZ.CODICE AS COD_CLASSIFICAZIONE,
NULL AS FLG_CANCELLAZIONE,
'FESR20142020' AS CODICE_FONDO 
FROM vPROGETTO P
INNER JOIN vBANDO B ON
P.ID_BANDO = B.ID_BANDO
INNER JOIN BANDO_PROGRAMMAZIONE BP ON
B.ID_BANDO = BP.ID_BANDO
INNER JOIN zPROGRAMMAZIONE PRG ON
BP.ID_PROGRAMMAZIONE = PRG.ID
INNER JOIN zPSR_ALBERO PA ON
PRG.COD_TIPO = PA.CODICE
INNER JOIN zPSR PSR ON
PA.COD_PSR = PSR.CODICE
INNER JOIN vBANDO_PROGRAMMAZIONE VBP ON
B.ID_BANDO = VBP.ID_BANDO
INNER JOIN AZ ON
VBP.ID_PROGRAMMAZIONE = AZ.ID_PROGRAMMAZIONE
INNER JOIN DATI_MONITORAGGIO_FESR DMFSR ON
P.ID_PROGETTO = DMFSR.ID_PROGETTO
WHERE 
P.COD_STATO IN ('F','V','S','O','T','X','C','Y','E','R') 
AND 
PSR.CODICE = 'POR20142020'
AND 
PRG.ID NOT IN (17,18,19)
AND
P.COD_AGEA IS NOT NULL

UNION ALL


SELECT 
P.ID_PROGETTO AS COD_LOCALE_PROGETTO,
'2' AS COD_RUOLO_SOG,
CASE 
WHEN DMFSR.CUP_NATURA IN ('01','02','03','08') AND AZ.CODICE = 'T' THEN PRA.CODICE_FISCALE
--WHEN DMFSR.CUP_NATURA IN ('01','02','03') AND AZ.CODICE = 'R' THEN PRA.CODICE_FISCALE
ELSE I.CUAA END AS CODICE_FISCALE,
AZ.CODICE AS COD_REGIA,
CASE 
WHEN DMFSR.CUP_NATURA IN ('01','02','03','08') AND AZ.CODICE = 'T' THEN 'S' ELSE
CASE WHEN I.COD_FORMA_GIURIDICA IN
(
--'1.6',
'2',
'2.1',
'2.2',
'2.3.',
'2.4',
'2.4.10',
'2.4.20',
'2.4.30',
'2.4.40',
'2.4.50',
'2.4.60',
'2.5',
'2.6.10',
'2.6.20',
'2.7',
'2.7.11',
'2.7.12',
'2.7.40',
'2.7.51',
'2.7.52',
'2.7.53',
'2.7.54',
'2.7.55',
'2.7.90'
) 
THEN  'S' ELSE 'N' END END AS FLAG_SOGGETTO_PUBBLICO,
CASE 
WHEN DMFSR.CUP_NATURA IN ('01','02','03','08') AND AZ.CODICE = 'T' THEN 'r_marche' ELSE
CASE WHEN I.COD_FORMA_GIURIDICA IN
(
--'1.6',
'2',
'2.1',
'2.2',
'2.3.',
'2.4',
'2.4.10',
'2.4.20',
'2.4.30',
'2.4.40',
'2.4.50',
'2.4.60',
'2.5',
'2.6.10',
'2.6.20',
'2.7',
'2.7.11',
'2.7.12',
'2.7.40',
'2.7.51',
'2.7.52',
'2.7.53',
'2.7.54',
'2.7.55',
'2.7.90'
) THEN IPA.CODICE_AMM 
--WHEN I.COD_FORMA_GIURIDICA = '2.4.10' THEN PRA.COD_UNI_IPA
ELSE NULL END END AS COD_UNI_IPA,
CASE 
WHEN DMFSR.CUP_NATURA IN ('01','02','03','08') AND AZ.CODICE = 'T' THEN PRA.DENOMINAZIONE_SOG
--WHEN DMFSR.CUP_NATURA IN ('01','02','03') AND AZ.CODICE = 'R' THEN PRA.DENOMINAZIONE_SOG
ELSE I.RAGIONE_SOCIALE END AS DENOMINAZIONE_SOG,
CASE 
WHEN DMFSR.CUP_NATURA IN ('01','02','03','08') AND AZ.CODICE = 'T' THEN PRA.FORMA_GIURIDICA
--WHEN DMFSR.CUP_NATURA IN ('01','02','03') AND AZ.CODICE = 'R' THEN PRA.FORMA_GIURIDICA
ELSE ISNULL(I.COD_FORMA_GIURIDICA, '1.3') END AS FORMA_GIURIDICA, --CLAUSOLA TEMPORANEA PER LE IMPRESE SENZA FORMA GIURIDICA
NULL AS SETT_ATT_ECONOMICA,
NULL AS NOTE,
DMFSR.CUP_NATURA,
AZ.COD_DIM AS TIPO_CLASS,
AZ.CODICE AS COD_CLASSIFICAZIONE, 
NULL AS FLG_CANCELLAZIONE,
'FESR20142020' AS CODICE_FONDO 
FROM vPROGETTO P
INNER JOIN vBANDO B ON
P.ID_BANDO = B.ID_BANDO
INNER JOIN BANDO_PROGRAMMAZIONE BP ON
B.ID_BANDO = BP.ID_BANDO
INNER JOIN zPROGRAMMAZIONE PRG ON
BP.ID_PROGRAMMAZIONE = PRG.ID
INNER JOIN zPSR_ALBERO PA ON
PRG.COD_TIPO = PA.CODICE
INNER JOIN zPSR PSR ON
PA.COD_PSR = PSR.CODICE
INNER JOIN vBANDO_PROGRAMMAZIONE VBP ON
B.ID_BANDO = VBP.ID_BANDO
INNER JOIN AZ ON
VBP.ID_PROGRAMMAZIONE = AZ.ID_PROGRAMMAZIONE
INNER JOIN DATI_MONITORAGGIO_FESR DMFSR ON
P.ID_PROGETTO = DMFSR.ID_PROGETTO
INNER JOIN vIMPRESA I ON
P.ID_IMPRESA = I.ID_IMPRESA
LEFT OUTER JOIN CODICI_IPA IPA ON
I.CUAA = IPA.CODICE_FISCALE 
INNER JOIN PRA ON
P.ID_PROGETTO = PRA.COD_LOCALE_PROGETTO
WHERE 
P.COD_STATO IN ('F','V','S','O','T','X','C','Y','E','R') 
AND 
PSR.CODICE = 'POR20142020'
AND 
PRG.ID NOT IN (17,18,19)
AND
P.COD_AGEA IS NOT NULL
) AS A
--26/01/2018
--CLAUSOLA TEMPORANEA PER ESCLUDERE PROGETTO STRUMENTI FINANZIARI ARTIGIANCASSA
WHERE A.COD_LOCALE_PROGETTO <> 13301

SELECT ISNULL(MAX(NR_RIGA_INVIO),0) FROM IGRUE_MONIT.dbo.IGRUE_SC00 WHERE ID_INVIO = @IdInvio

END

--SELECT 
--A.COD_LOCALE_PROGETTO,
--A.COD_RUOLO_SOG,
--A.CODICE_FISCALE,
--A.FLAG_SOGGETTO_PUBBLICO,
--A.COD_UNI_IPA,
--A.DENOMINAZIONE_SOG,
--A.FORMA_GIURIDICA,
--A.SETT_ATT_ECONOMICA,
--A.NOTE,
--A.FLG_CANCELLAZIONE,
--@IdInvio AS ID_INVIO,
--ISNULL(@rNumber,0) + ROW_NUMBER() OVER(ORDER BY A.COD_LOCALE_PROGETTO ASC) AS NR_RIGA_INVIO,
--A.CODICE_FONDO
--FROM (
--SELECT 
--P.ID_PROGETTO AS COD_LOCALE_PROGETTO,
--'1' AS COD_RUOLO_SOG,
--'80008630420' AS CODICE_FISCALE,
--'S' AS FLAG_SOGGETTO_PUBBLICO,
--'r_marche' AS COD_UNI_IPA,
--'Regione Marche' AS DENOMINAZIONE_SOG,
--'2.4.10' AS FORMA_GIURIDICA,
--NULL AS SETT_ATT_ECONOMICA,
--NULL AS NOTE,
--DMFSR.CUP_NATURA,
--AZ.COD_DIM AS TIPO_CLASS,
--AZ.CODICE AS COD_CLASSIFICAZIONE,
--NULL AS FLG_CANCELLAZIONE,
--'FESR20142020' AS CODICE_FONDO 
--FROM vPROGETTO P
--INNER JOIN vBANDO B ON
--P.ID_BANDO = B.ID_BANDO
--INNER JOIN BANDO_PROGRAMMAZIONE BP ON
--B.ID_BANDO = BP.ID_BANDO
--INNER JOIN zPROGRAMMAZIONE PRG ON
--BP.ID_PROGRAMMAZIONE = PRG.ID
--INNER JOIN zPSR_ALBERO PA ON
--PRG.COD_TIPO = PA.CODICE
--INNER JOIN zPSR PSR ON
--PA.COD_PSR = PSR.CODICE
--INNER JOIN vBANDO_PROGRAMMAZIONE VBP ON
--B.ID_BANDO = VBP.ID_BANDO
--INNER JOIN AZ ON
--VBP.ID_PROGRAMMAZIONE = AZ.ID_PROGRAMMAZIONE
--INNER JOIN DATI_MONITORAGGIO_FESR DMFSR ON
--P.ID_PROGETTO = DMFSR.ID_PROGETTO
--WHERE 
--P.COD_STATO IN ('F','V','S','O','T','X','C','Y','E','R') 
--AND 
--PSR.CODICE = 'POR20142020'
--AND 
--PRG.ID NOT IN (17,18,19)
--AND
--P.COD_AGEA IS NOT NULL

--UNION ALL


--SELECT 
--P.ID_PROGETTO AS COD_LOCALE_PROGETTO,
--'2' AS COD_RUOLO_SOG,
--CASE 
--WHEN DMFSR.CUP_NATURA IN ('01','02','03','08') AND AZ.CODICE = 'T' THEN PRA.CODICE_FISCALE
--WHEN DMFSR.CUP_NATURA IN ('01','02','03') AND AZ.CODICE = 'R' THEN PRA.CODICE_FISCALE
--ELSE I.CODICE_FISCALE END AS CODICE_FISCALE,
--CASE WHEN I.COD_FORMA_GIURIDICA IN
--(
----'1.6',
--'2',
--'2.1',
--'2.2',
--'2.3.',
--'2.4',
--'2.4.10',
--'2.4.20',
--'2.4.30',
--'2.4.40',
--'2.4.50',
--'2.4.60',
--'2.5',
--'2.6.10',
--'2.6.20',
--'2.7',
--'2.7.11',
--'2.7.12',
--'2.7.40',
--'2.7.51',
--'2.7.52',
--'2.7.53',
--'2.7.54',
--'2.7.55',
--'2.7.90'
--) THEN  'S' ELSE 'N' END AS FLAG_SOGGETTO_PUBBLICO,
--CASE WHEN I.COD_FORMA_GIURIDICA IN
--(
----'1.6',
--'2',
--'2.1',
--'2.2',
--'2.3.',
--'2.4',
----'2.4.10',
--'2.4.20',
--'2.4.30',
--'2.4.40',
--'2.4.50',
--'2.4.60',
--'2.5',
--'2.6.10',
--'2.6.20',
--'2.7',
--'2.7.11',
--'2.7.12',
--'2.7.40',
--'2.7.51',
--'2.7.52',
--'2.7.53',
--'2.7.54',
--'2.7.55',
--'2.7.90'
--) THEN IPA.CODICE_AMM 
--WHEN I.COD_FORMA_GIURIDICA = '2.4.10' THEN PRA.COD_UNI_IPA
--ELSE NULL END AS COD_UNI_IPA,
--CASE 
--WHEN DMFSR.CUP_NATURA IN ('01','02','03','08') AND AZ.CODICE = 'T' THEN PRA.DENOMINAZIONE_SOG
--WHEN DMFSR.CUP_NATURA IN ('01','02','03') AND AZ.CODICE = 'R' THEN PRA.DENOMINAZIONE_SOG
--ELSE I.RAGIONE_SOCIALE END AS DENOMINAZIONE_SOG,
--CASE 
--WHEN DMFSR.CUP_NATURA IN ('01','02','03','08') AND AZ.CODICE = 'T' THEN PRA.FORMA_GIURIDICA
--WHEN DMFSR.CUP_NATURA IN ('01','02','03') AND AZ.CODICE = 'R' THEN PRA.FORMA_GIURIDICA
--ELSE I.COD_FORMA_GIURIDICA END AS FORMA_GIURIDICA,
--NULL AS SETT_ATT_ECONOMICA,
--NULL AS NOTE,
--DMFSR.CUP_NATURA,
--AZ.COD_DIM AS TIPO_CLASS,
--AZ.CODICE AS COD_CLASSIFICAZIONE, 
--NULL AS FLG_CANCELLAZIONE,
--'FESR20142020' AS CODICE_FONDO 
--FROM vPROGETTO P
--INNER JOIN vBANDO B ON
--P.ID_BANDO = B.ID_BANDO
--INNER JOIN BANDO_PROGRAMMAZIONE BP ON
--B.ID_BANDO = BP.ID_BANDO
--INNER JOIN zPROGRAMMAZIONE PRG ON
--BP.ID_PROGRAMMAZIONE = PRG.ID
--INNER JOIN zPSR_ALBERO PA ON
--PRG.COD_TIPO = PA.CODICE
--INNER JOIN zPSR PSR ON
--PA.COD_PSR = PSR.CODICE
--INNER JOIN vBANDO_PROGRAMMAZIONE VBP ON
--B.ID_BANDO = VBP.ID_BANDO
--INNER JOIN AZ ON
--VBP.ID_PROGRAMMAZIONE = AZ.ID_PROGRAMMAZIONE
--INNER JOIN DATI_MONITORAGGIO_FESR DMFSR ON
--P.ID_PROGETTO = DMFSR.ID_PROGETTO
--INNER JOIN vIMPRESA I ON
--P.ID_IMPRESA = I.ID_IMPRESA
--LEFT OUTER JOIN CODICI_IPA IPA ON
--I.CODICE_FISCALE = IPA.CODICE_FISCALE 
--INNER JOIN PRA ON
--P.ID_PROGETTO = PRA.COD_LOCALE_PROGETTO
--WHERE 
--P.COD_STATO IN ('F','V','S','O','T','X','C','Y','E','R') 
--AND 
--PSR.CODICE = 'POR20142020'
--AND 
--PRG.ID NOT IN (17,18,19)
--AND
--P.COD_AGEA IS NOT NULL
--) AS A
----26/01/2018
----CLAUSOLA TEMPORANEA PER ESCLUDERE PROGETTO STRUMENTI FINANZIARI ARTIGIANCASSA
--WHERE A.COD_LOCALE_PROGETTO <> 13301




