CREATE PROCEDURE [dbo].[zIgrueInsertMonitIN00]
( 
 @DataDa DATETIME,
 @DataA DATETIME,
 @IdInvio INT,
 @rNumber INT
)
AS
BEGIN


WITH IRT AS
(
	SELECT 
	ZP.ID ID_PRG,
	ZP.CODICE COD_PRG,
	ZP.DESCRIZIONE DESC_PRG,
	CASE WHEN ZD.CODICE IN ('IR2','IR4','IR7','IR12') THEN 'DPR' 
	ELSE 'COM' END AS TIPO_INDICATORE_DI_RISULTATO,
	CASE ZD.CODICE
	WHEN 'IR1'	 THEN '148'
	WHEN 'IR3'	 THEN '419'
	WHEN 'IR5'	 THEN '423'
	WHEN 'IR6'	 THEN '434'
	WHEN 'IR6b'	 THEN '424'
	WHEN 'IR8'	 THEN '148'
	WHEN 'IR9'	 THEN '431'
	WHEN 'IR10'	 THEN '161'
	WHEN 'IR11'	 THEN '379'
	WHEN 'IR13'	 THEN '373'
	WHEN 'IR13b' THEN '374'
	WHEN 'IR14'	 THEN '472_C'
	WHEN 'IR15'	 THEN '278'
	WHEN 'IR15b' THEN '387'
	WHEN 'IR16'  THEN '372'
	WHEN 'IR17'	 THEN '105'
	WHEN '467'   THEN '467'
	ELSE ZD.CODICE + '2014IT16RFOP013'
	END AS COD_INDICATORE,
	ZD.COD_DIM,
	ZD.DESCRIZIONE
	FROM 
	zPROGRAMMAZIONE ZP
	INNER JOIN zDIMENSIONI_X_PROGRAMMAZIONE ZDP ON 
	ZP.ID = ZDP.ID_PROGRAMMAZIONE
	INNER JOIN zDIMENSIONI ZD ON 
	ZDP.ID_DIMENSIONE = ZD.ID
	AND 
	ZD.COD_DIM = 'IR'
)


INSERT INTO IGRUE_MONIT.dbo.IGRUE_IN00
(
COD_LOCALE_PROGETTO,
TIPO_INDICATORE_DI_RISULTATO,
COD_INDICATORE,
FLG_CANCELLAZIONE,
--OPERAZIONE,
ID_INVIO,
NR_RIGA_INVIO,
--NR_RIGA_CANCELLAZIONE
CODICE_FONDO
)


SELECT
P.ID_PROGETTO AS COD_LOCALE_PROGETTO,
--'DPR' AS TIPO_INDICATORE_DI_RISULTATO,
IRT.TIPO_INDICATORE_DI_RISULTATO,
--IRT.CODICE + '2014IT16RFOP013' AS COD_INDICATORE, 
IRT.COD_INDICATORE,
NULL AS FLG_CANCELLAZIONE,
@IdInvio AS ID_INVIO,
ISNULL(@rNumber,0) + ROW_NUMBER() OVER(ORDER BY P.ID_PROGETTO ASC) AS NR_RIGA_INVIO,
'FESR20142020' AS CODICE_FONDO   
FROM vPROGETTO P 
INNER JOIN vBANDO B ON
P.ID_BANDO = B.ID_BANDO
INNER JOIN BANDO_PROGRAMMAZIONE BP ON
B.ID_BANDO = BP.ID_BANDO
INNER JOIN zPROGRAMMAZIONE PRG ON
BP.ID_PROGRAMMAZIONE = PRG.ID
INNER JOIN zPSR_ALBERO PA ON
PRG.COD_TIPO = PA.CODICE
INNER JOIN zPSR PSR ON
PA.COD_PSR = PSR.CODICE
INNER JOIN zPROGRAMMAZIONE AZIONI ON
B.ID_PROGRAMMAZIONE = AZIONI.ID
LEFT OUTER JOIN IRT ON
AZIONI.ID = IRT.ID_PRG
WHERE 
P.COD_STATO IN ('F','V','S','O','T','X','C','Y','E','R') 
AND 
PSR.CODICE = 'POR20142020'
AND PRG.ID NOT IN (17,18,19)
AND 
BP.ID_PROGRAMMAZIONE NOT IN (17,18,19)
AND
P.COD_AGEA IS NOT NULL
AND 
IRT.COD_INDICATORE IS NOT NULL
--26/01/2018
--CLAUSOLA TEMPORANEA PER ESCLUDERE PROGETTO STRUMENTI FINANZIARI ARTIGIANCASSA
AND P.ID_PROGETTO <> 13301
--ORDER BY P.ID_PROGETTO


SELECT ISNULL(MAX(NR_RIGA_INVIO),0) FROM IGRUE_MONIT.dbo.IGRUE_IN00 WHERE ID_INVIO = @IdInvio

END


--WITH IRT AS
--(
--SELECT 
--ZP.ID ID_PRG,
--ZP.CODICE COD_PRG,
--ZP.DESCRIZIONE DESC_PRG,
--ZD.CODICE,
--ZD.COD_DIM,
--ZD.DESCRIZIONE
--FROM 
--zPROGRAMMAZIONE ZP
--INNER JOIN zDIMENSIONI_X_PROGRAMMAZIONE ZDP ON 
--ZP.ID = ZDP.ID_PROGRAMMAZIONE
--INNER JOIN zDIMENSIONI ZD ON 
--ZDP.ID_DIMENSIONE = ZD.ID
--AND 
--ZD.COD_DIM = 'IR'
--)


--INSERT INTO IGRUE_MONIT.dbo.IGRUE_IN00
--(
--COD_LOCALE_PROGETTO,
--TIPO_INDICATORE_DI_RISULTATO,
--COD_INDICATORE,
--FLG_CANCELLAZIONE,
----OPERAZIONE,
--ID_INVIO,
--NR_RIGA_INVIO,
----NR_RIGA_CANCELLAZIONE
--CODICE_FONDO
--)


--SELECT
--P.ID_PROGETTO AS COD_LOCALE_PROGETTO,
--'DPR' AS TIPO_INDICATORE_DI_RISULTATO,
--IRT.CODICE + '2014IT16RFOP013' AS COD_INDICATORE, 
--NULL AS FLG_CANCELLAZIONE,
--@IdInvio AS ID_INVIO,
--ISNULL(@rNumber,0) + ROW_NUMBER() OVER(ORDER BY P.ID_PROGETTO ASC) AS NR_RIGA_INVIO,
--'FESR20142020' AS CODICE_FONDO   
--FROM vPROGETTO P 
--INNER JOIN vBANDO B ON
--P.ID_BANDO = B.ID_BANDO
--INNER JOIN BANDO_PROGRAMMAZIONE BP ON
--B.ID_BANDO = BP.ID_BANDO
--INNER JOIN zPROGRAMMAZIONE PRG ON
--BP.ID_PROGRAMMAZIONE = PRG.ID
--INNER JOIN zPSR_ALBERO PA ON
--PRG.COD_TIPO = PA.CODICE
--INNER JOIN zPSR PSR ON
--PA.COD_PSR = PSR.CODICE
--INNER JOIN zPROGRAMMAZIONE AZIONI ON
--B.ID_PROGRAMMAZIONE = AZIONI.ID
--LEFT OUTER JOIN IRT ON
--AZIONI.ID = IRT.ID_PRG
--WHERE 
--P.COD_STATO IN ('F','V','S','O','T','X','C','Y','E','R') 
--AND 
--PSR.CODICE = 'POR20142020'
--AND PRG.ID NOT IN (17,18,19)
--AND 
--BP.ID_PROGRAMMAZIONE NOT IN (17,18,19)
--AND
--P.COD_AGEA IS NOT NULL
--AND 
--IRT.CODICE IS NOT NULL
----26/01/2018
----CLAUSOLA TEMPORANEA PER ESCLUDERE PROGETTO STRUMENTI FINANZIARI ARTIGIANCASSA
--AND P.ID_PROGETTO <> 13301
--ORDER BY P.ID_PROGETTO
----AND
----BR.ATTIVO = 1 AND BR.PROVINCIA IS NULL
----AND
----B.DATA_SCADENZA BETWEEN @DataDa AND @DataA


