CREATE PROCEDURE [dbo].[zIgrueInsertMonitFN07]
( 
 @DataDa DATETIME,
 @DataA DATETIME,
 @IdInvio INT,
 @rNumber INT
)
AS
BEGIN

WITH CLG AS 
(
SELECT 
COD_LIV_GERARCHICO,
VALORE_DATI_RILEVATI,
DESCRIZIONE_CODICE_LIVELLO_GERARCHICO,
COD_STRUTTURA_PROT
FROM 
IGRUE_MONIT.dbo.IGRUE_T_TC36 
WHERE 
DESCRIZIONE_CODICE_LIVELLO_GERARCHICO LIKE '%POR Marche FESR%' 
AND 
COD_STRUTTURA_PROT LIKE '%FN07%'
),

DECRETI_X_DOM_PAG_ESPORTAZIONE2 AS (
SELECT 
APE.ID_DECRETO,
APE.ID_DOMANDA_PAGAMENTO,
DP1.COD_TIPO,
APE.ID_PROGETTO,
DM.CUP_NATURA,
APE.IMPORTO
FROM 
DECRETI_X_DOM_PAG_ESPORTAZIONE APE
INNER JOIN 
DOMANDA_DI_PAGAMENTO_ESPORTAZIONE PE ON
APE.ID_DOMANDA_PAGAMENTO = PE.ID_DOMANDA_PAGAMENTO
INNER JOIN 
DATI_MONITORAGGIO_FESR DM ON
PE.ID_PROGETTO = DM.ID_PROGETTO
INNER JOIN 
DOMANDA_DI_PAGAMENTO DP1 ON
PE.ID_DOMANDA_PAGAMENTO = DP1.ID_DOMANDA_PAGAMENTO
WHERE
NOT EXISTS
(
	SELECT 
	MIN(APE2.ID_DECRETO),
	APE2.ID_DOMANDA_PAGAMENTO,
	APE2.ID_PROGETTO
	FROM 
	DECRETI_X_DOM_PAG_ESPORTAZIONE APE2
	INNER JOIN 
	DATI_MONITORAGGIO_FESR DMFR ON
	APE2.ID_PROGETTO = DMFR.ID_PROGETTO
	INNER JOIN 
	DOMANDA_DI_PAGAMENTO DP ON
	APE2.ID_DOMANDA_PAGAMENTO = DP.ID_DOMANDA_PAGAMENTO
	WHERE 
	(
	 (DMFR.CUP_NATURA <> '07')
	  OR
	 (DMFR.CUP_NATURA <> '07' AND DP.COD_TIPO = 'ANT')
	)
	AND 
	DP.APPROVATA = 1
	AND 
	APE.ID_DOMANDA_PAGAMENTO = APE2.ID_DOMANDA_PAGAMENTO
	GROUP BY 
	APE2.ID_PROGETTO,
	APE2.ID_DOMANDA_PAGAMENTO
)

UNION

SELECT 
	MIN(APE2.ID_DECRETO) ID_DECRETO,
	APE2.ID_DOMANDA_PAGAMENTO,
	DP.COD_TIPO,
	APE2.ID_PROGETTO,
	DMFR.CUP_NATURA,
	CASE WHEN DP.COD_TIPO = 'ANT' THEN
	SUM(APE2.IMPORTO) 
	ELSE 
	DPE.IMPORTO_AMMESSO END
	--APE2.IMPORTO END
	AS IMPORTO
	--NULL AS IMPORTO--APE2.IMPORTO  
	FROM 
	DECRETI_X_DOM_PAG_ESPORTAZIONE APE2
	INNER JOIN 
	DATI_MONITORAGGIO_FESR DMFR ON
	APE2.ID_PROGETTO = DMFR.ID_PROGETTO
	INNER JOIN 
	DOMANDA_DI_PAGAMENTO DP ON
	APE2.ID_DOMANDA_PAGAMENTO = DP.ID_DOMANDA_PAGAMENTO
	INNER JOIN 
	DOMANDA_DI_PAGAMENTO_ESPORTAZIONE DPE ON 
	DPE.ID_DOMANDA_PAGAMENTO = APE2.ID_DOMANDA_PAGAMENTO
	--LEFT OUTER JOIN 
	--(
	--	SELECT 
	--	PR.ID_DOMANDA_PAGAMENTO,
	--	SUM(ISNULL(PR.IMPORTO_AMMESSO,0)) AS IMPORTO_AMMESSO,
	--	SUM(ISNULL(PR.CONTRIBUTO_AMMESSO,0)) AS CONTRIBUTO_AMMESSO
	--	FROM 
	--	PAGAMENTI_RICHIESTI PR
	--	WHERE PR.IMPORTO_AMMESSO IS NOT NULL
	--	GROUP BY 
	--	PR.ID_DOMANDA_PAGAMENTO
	--) PRB ON
	--APE2.ID_DOMANDA_PAGAMENTO = PRB.ID_DOMANDA_PAGAMENTO
	WHERE 
	(
	 (DMFR.CUP_NATURA <> '07')
	  OR
	 (DMFR.CUP_NATURA <> '07' AND DP.COD_TIPO = 'ANT')
	)
	AND 
	DP.APPROVATA = 1
	--AND 
	--APE.ID_DOMANDA_PAGAMENTO = APE2.ID_DOMANDA_PAGAMENTO
	GROUP BY 
	APE2.ID_PROGETTO,
	DP.COD_TIPO,
	APE2.ID_DOMANDA_PAGAMENTO,
	DPE.IMPORTO_AMMESSO,
	DMFR.CUP_NATURA
	--APE2.IMPORTO,
	--PRB.IMPORTO_AMMESSO
	--APE2.IMPORTO
)


INSERT INTO IGRUE_MONIT.dbo.IGRUE_FN07
(
COD_LOCALE_PROGETTO,
COD_PAGAMENTO,
TIPOLOGIA_PAG,
DATA_PAGAMENTO,
COD_PROGRAMMA,
COD_LIV_GERARCHICO,
DATA_PAG_AMM,
TIPOLOGIA_PAG_AMM,
CAUSALE_PAG_AMM,
IMPORTO_PAG_AMM,
NOTE_PAG,
FLG_CANCELLAZIONE,
--OPERAZIONE,
ID_INVIO,
NR_RIGA_INVIO,
--NR_RIGA_CANCELLAZIONE
CODICE_FONDO
)

SELECT
P.ID_PROGETTO AS COD_LOCALE_PROGETTO,
--CASE 
--WHEN DMFR.CUP_NATURA = '07' THEN ATTI.NUMERO
--ELSE DPE.ID_DOMANDA_PAGAMENTO END AS COD_PAGAMENTO,
ATTI.NUMERO AS COD_PAGAMENTO, --VERIFICARE PRESENZA CAMPO
--'P' AS TIPOLOGIA_PAG, --VERIFICARE PRESENZA CAMPO
CASE WHEN BCA.VALORE = '04' THEN 'P-TR'
ELSE 
'P' END AS TIPOLOGIA_PAG,
--CASE 
--WHEN DMFR.CUP_NATURA = '07' THEN dbo.DateToString_Igrue(ATTI.DATA)
--ELSE dbo.DateToString_Igrue(DP.DATA_APPROVAZIONE) END AS DATA_PAGAMENTO,
dbo.DateToString_Igrue(ATTI.DATA) AS DATA_PAGAMENTO,  --VERIFICARE PRESENZA CAMPO
'2014IT16RFOP013' AS COD_PROGRAMMA, --VERIFICARE CON TC4
CLG.COD_LIV_GERARCHICO AS COD_LIV_GERARCHICO, 
dbo.DateToString_Igrue(ATTI.DATA) AS DATA_PAG_AMM,
--'P' AS TIPOLOGIA_PAG_AMM,
CASE WHEN BCA.VALORE = '04' THEN 'P-TR'
ELSE 
'P' END AS TIPOLOGIA_PAG_AMM,
CASE DP.COD_TIPO 
WHEN 'ANT' THEN 'ANT'
WHEN 'SAL' THEN 'INT'
WHEN 'SLD' THEN 'SLD' END AS CAUSALE_PAG_AMM, -- VERIFICARE TC39
--DPE.IMPORTO_AMMESSO AS IMPORTO_PAG_AMM,
DDPE.IMPORTO AS IMPORTO_PAG_AMM,
NULL AS NOTE_PAG,
NULL AS FLG_CANCELLAZIONE,
@IdInvio AS ID_INVIO,
ISNULL(@rNumber,0) + ROW_NUMBER() OVER(ORDER BY P.ID_PROGETTO ASC) AS NR_RIGA_INVIO,
'FESR20142020' AS CODICE_FONDO   
FROM vPROGETTO P 
INNER JOIN vBANDO B ON
P.ID_BANDO = B.ID_BANDO
--INNER JOIN BANDO_PROGRAMMAZIONE BP ON
--B.ID_BANDO = BP.ID_BANDO
INNER JOIN zPROGRAMMAZIONE PRG ON
B.ID_PROGRAMMAZIONE = PRG.ID
INNER JOIN zPSR_ALBERO PA ON
PRG.COD_TIPO = PA.CODICE
INNER JOIN zPSR PSR ON
PA.COD_PSR = PSR.CODICE
INNER JOIN DOMANDA_DI_PAGAMENTO_ESPORTAZIONE DPE ON
P.ID_PROGETTO = DPE.ID_PROGETTO
INNER JOIN DOMANDA_DI_PAGAMENTO DP ON
DPE.ID_DOMANDA_PAGAMENTO = DP.ID_DOMANDA_PAGAMENTO
AND
DP.APPROVATA = 1
AND 
DP.SEGNATURA IS NOT NULL
INNER JOIN 
DECRETI_X_DOM_PAG_ESPORTAZIONE2 DDPE ON
DPE.ID_DOMANDA_PAGAMENTO = DDPE.ID_DOMANDA_PAGAMENTO
LEFT OUTER JOIN 
ATTI ON 
DDPE.ID_DECRETO = ATTI.ID_ATTO
INNER JOIN zOB_MISURA OS ON
B.ID_PROGRAMMAZIONE = OS.ID_PROGRAMMAZIONE
INNER JOIN zPROGRAMMAZIONE AZIONI ON
B.ID_PROGRAMMAZIONE = AZIONI.ID
INNER JOIN zPROGRAMMAZIONE ASSI ON 
AZIONI.ID_PADRE = ASSI.ID
LEFT OUTER JOIN 
(
	SELECT 
	D.CODICE AS COD_PI,
	DP.ID_PROGRAMMAZIONE,
	PPI.CODICE,
	PPI.COD_TIPO 
	FROM zDIMENSIONI D 
	INNER JOIN zDIMENSIONI_X_PROGRAMMAZIONE DP ON
	D.ID = DP.ID_DIMENSIONE 
	INNER JOIN zPROGRAMMAZIONE PPI ON
	DP.ID_PROGRAMMAZIONE = PPI.ID
	WHERE D.COD_DIM = 'PI'
) AS PRI ON
AZIONI.ID = PRI.ID_PROGRAMMAZIONE
LEFT OUTER JOIN 
(
	SELECT 
	D.CODICE AS COD_OT,
	DP.ID_PROGRAMMAZIONE,
	DP.ID_DIM_X_PROGRAMMAZIONE,
	DP.ID_DIMENSIONE,
	PPI.CODICE,
	PPI.COD_TIPO 
	FROM zDIMENSIONI D 
	INNER JOIN zDIMENSIONI_X_PROGRAMMAZIONE DP ON
	D.ID = DP.ID_DIMENSIONE 
	INNER JOIN zPROGRAMMAZIONE PPI ON
	DP.ID_PROGRAMMAZIONE = PPI.ID
	WHERE D.COD_DIM = 'OT'
) AS OT ON
ASSI.ID = OT.ID_PROGRAMMAZIONE
LEFT OUTER JOIN 
(
	SELECT 
	D.CODICE AS COD_OT,
	DP.ID_PROGRAMMAZIONE,
	DP.ID_DIM_X_PROGRAMMAZIONE,
	DP.ID_DIMENSIONE,
	--PPI.CODICE,
	SUBSTRING(D.CODICE,4,1) CODICE,
	PPI.COD_TIPO 
	FROM zDIMENSIONI D 
	INNER JOIN zDIMENSIONI_X_PROGRAMMAZIONE DP ON
	D.ID = DP.ID_DIMENSIONE 
	INNER JOIN zPROGRAMMAZIONE PPI ON
	DP.ID_PROGRAMMAZIONE = PPI.ID
	WHERE D.COD_DIM = 'OT'
) AS OT2 ON
AZIONI.ID = OT2.ID_PROGRAMMAZIONE
LEFT OUTER JOIN  CLG ON
--'2014IT16RFOP013#ERDF#M#'+ASSI.CODICE + CASE WHEN OT.CODICE IS NULL THEN '' ELSE '#0' END + ISNULL(OT.CODICE,'#N.A.') + '#' + ISNULL(PRI.COD_PI,'N.A.') + '#' + REPLACE(OS.CODICE, 'OS ','') = CLG.VALORE_DATI_RILEVATI
'2014IT16RFOP013#ERDF#M#'+ASSI.CODICE + CASE WHEN COALESCE(OT.CODICE, OT2.CODICE) IS NULL THEN '' ELSE '#0' END + ISNULL(COALESCE(OT.CODICE, OT2.CODICE),'#N.A.') + '#' + ISNULL(PRI.COD_PI,'N.A.') + '#' + REPLACE(OS.CODICE, 'OS ','') = CLG.VALORE_DATI_RILEVATI
--AND 
--VPR.ISTRUTTORE IS NOT NULL
--AND 
--VPR.ID_INVESTIMENTO_ORIGINALE IS NOT NULL
--AND
--VPR.AMMESSO = 1 
LEFT OUTER JOIN
DATI_MONITORAGGIO_FESR DMFR ON
P.ID_PROGETTO = DMFR.ID_PROGETTO
LEFT OUTER JOIN 
BANDO_CONFIG BCA ON
B.ID_BANDO = BCA.ID_BANDO 
AND 
BCA.COD_TIPO = 'TPAPPALTO'
AND 
BCA.ATTIVO = 1 
AND 
BCA.VALORE = '04'
WHERE 
P.COD_STATO IN ('F','V','S','O','T','X','C','Y','E','R') 
AND 
PSR.CODICE = 'POR20142020'
AND PRG.ID NOT IN (17,18,19)
AND
P.COD_AGEA IS NOT NULL
--26/01/2018
--CLAUSOLA TEMPORANEA PER ESCLUDERE PROGETTO STRUMENTI FINANZIARI ARTIGIANCASSA
AND P.ID_PROGETTO <> 13301
--CLAUSOLA TEMPORANEA PER TEST INVIO IGRUE
AND ATTI.ID_ATTO IS NOT NULL


SELECT ISNULL(MAX(NR_RIGA_INVIO),0) FROM IGRUE_MONIT.dbo.IGRUE_FN07 WHERE ID_INVIO = @IdInvio

END


--SELECT
--P.ID_PROGETTO AS COD_LOCALE_PROGETTO,
----CASE 
----WHEN DMFR.CUP_NATURA = '07' THEN ATTI.NUMERO
----ELSE DPE.ID_DOMANDA_PAGAMENTO END AS COD_PAGAMENTO,
--ATTI.NUMERO AS COD_PAGAMENTO, --VERIFICARE PRESENZA CAMPO
--'P' AS TIPOLOGIA_PAG, --VERIFICARE PRESENZA CAMPO
----CASE 
----WHEN DMFR.CUP_NATURA = '07' THEN dbo.DateToString_Igrue(ATTI.DATA)
----ELSE dbo.DateToString_Igrue(DP.DATA_APPROVAZIONE) END AS DATA_PAGAMENTO,
--dbo.DateToString_Igrue(ATTI.DATA) AS DATA_PAGAMENTO,  --VERIFICARE PRESENZA CAMPO
--'2014IT16RFOP013' AS COD_PROGRAMMA, --VERIFICARE CON TC4
--CLG.COD_LIV_GERARCHICO AS COD_LIV_GERARCHICO, 
--dbo.DateToString_Igrue(ATTI.DATA) AS DATA_PAG_AMM,
--'P' AS TIPOLOGIA_PAG_AMM,
--CASE DP.COD_TIPO 
--WHEN 'ANT' THEN 'ANT'
--WHEN 'SAL' THEN 'INT'
--WHEN 'SLD' THEN 'SLD' END AS CAUSALE_PAG_AMM, -- VERIFICARE TC39
--DPE.IMPORTO_AMMESSO AS IMPORTO_PAG_AMM,
--NULL AS NOTE_PAG,
--NULL AS FLG_CANCELLAZIONE,
--@IdInvio AS ID_INVIO,
--ISNULL(@rNumber,0) + ROW_NUMBER() OVER(ORDER BY P.ID_PROGETTO ASC) AS NR_RIGA_INVIO,
--'FESR20142020' AS CODICE_FONDO   
--FROM vPROGETTO P 
--INNER JOIN vBANDO B ON
--P.ID_BANDO = B.ID_BANDO
----INNER JOIN BANDO_PROGRAMMAZIONE BP ON
----B.ID_BANDO = BP.ID_BANDO
--INNER JOIN zPROGRAMMAZIONE PRG ON
--B.ID_PROGRAMMAZIONE = PRG.ID
--INNER JOIN zPSR_ALBERO PA ON
--PRG.COD_TIPO = PA.CODICE
--INNER JOIN zPSR PSR ON
--PA.COD_PSR = PSR.CODICE
--INNER JOIN DOMANDA_DI_PAGAMENTO_ESPORTAZIONE DPE ON
--P.ID_PROGETTO = DPE.ID_PROGETTO
--INNER JOIN DOMANDA_DI_PAGAMENTO DP ON
--DPE.ID_DOMANDA_PAGAMENTO = DP.ID_DOMANDA_PAGAMENTO
--AND
--DP.APPROVATA = 1
--AND 
--DP.SEGNATURA IS NOT NULL
--LEFT OUTER JOIN 
--ATTI ON 
--DPE.ID_DECRETO = ATTI.ID_ATTO
--INNER JOIN zOB_MISURA OS ON
--B.ID_PROGRAMMAZIONE = OS.ID_PROGRAMMAZIONE
--INNER JOIN zPROGRAMMAZIONE AZIONI ON
--B.ID_PROGRAMMAZIONE = AZIONI.ID
--INNER JOIN zPROGRAMMAZIONE ASSI ON 
--AZIONI.ID_PADRE = ASSI.ID
--LEFT OUTER JOIN 
--(
--	SELECT 
--	D.CODICE AS COD_PI,
--	DP.ID_PROGRAMMAZIONE,
--	PPI.CODICE,
--	PPI.COD_TIPO 
--	FROM zDIMENSIONI D 
--	INNER JOIN zDIMENSIONI_X_PROGRAMMAZIONE DP ON
--	D.ID = DP.ID_DIMENSIONE 
--	INNER JOIN zPROGRAMMAZIONE PPI ON
--	DP.ID_PROGRAMMAZIONE = PPI.ID
--	WHERE D.COD_DIM = 'PI'
--) AS PRI ON
--AZIONI.ID = PRI.ID_PROGRAMMAZIONE
--LEFT OUTER JOIN 
--(
--	SELECT 
--	D.CODICE AS COD_OT,
--	DP.ID_PROGRAMMAZIONE,
--	DP.ID_DIM_X_PROGRAMMAZIONE,
--	DP.ID_DIMENSIONE,
--	PPI.CODICE,
--	PPI.COD_TIPO 
--	FROM zDIMENSIONI D 
--	INNER JOIN zDIMENSIONI_X_PROGRAMMAZIONE DP ON
--	D.ID = DP.ID_DIMENSIONE 
--	INNER JOIN zPROGRAMMAZIONE PPI ON
--	DP.ID_PROGRAMMAZIONE = PPI.ID
--	WHERE D.COD_DIM = 'OT'
--) AS OT ON
--ASSI.ID = OT.ID_PROGRAMMAZIONE
--LEFT OUTER JOIN  CLG ON
----'2014IT16RFOP013#ERDF#M#'+ASSI.CODICE + '#0' + ASSI.CODICE + '#' + PRI.COD_PI + '#' + REPLACE(OS.CODICE, 'OS ','') = CLG.VALORE_DATI_RILEVATI
--'2014IT16RFOP013#ERDF#M#'+ASSI.CODICE + CASE WHEN OT.CODICE IS NULL THEN '' ELSE '#0' END + ISNULL(OT.CODICE,'#N.A.') + '#' + ISNULL(PRI.COD_PI,'N.A.') + '#' + REPLACE(OS.CODICE, 'OS ','') = CLG.VALORE_DATI_RILEVATI
----AND 
----VPR.ISTRUTTORE IS NOT NULL
----AND 
----VPR.ID_INVESTIMENTO_ORIGINALE IS NOT NULL
----AND
----VPR.AMMESSO = 1 
--LEFT OUTER JOIN
--DATI_MONITORAGGIO_FESR DMFR ON
--P.ID_PROGETTO = DMFR.ID_PROGETTO
--WHERE 
--P.COD_STATO IN ('F','V','S','O','T','X','C','Y','E','R') 
--AND 
--PSR.CODICE = 'POR20142020'
--AND PRG.ID NOT IN (17,18,19)
--AND
--P.COD_AGEA IS NOT NULL
----26/01/2018
----CLAUSOLA TEMPORANEA PER ESCLUDERE PROGETTO STRUMENTI FINANZIARI ARTIGIANCASSA
--AND P.ID_PROGETTO <> 13301
----CLAUSOLA TEMPORANEA PER TEST INVIO IGRUE
--AND ATTI.ID_ATTO IS NOT NULL




--SELECT
--P.ID_PROGETTO AS COD_LOCALE_PROGETTO,
--ATTI.NUMERO AS COD_PAGAMENTO, --VERIFICARE PRESENZA CAMPO
--'P' AS TIPOLOGIA_PAG, --VERIFICARE PRESENZA CAMPO
--dbo.DateToString_Igrue(ATTI.DATA) AS DATA_PAGAMENTO,  --VERIFICARE PRESENZA CAMPO
--'2014IT16RFOP013' AS COD_PROGRAMMA, --VERIFICARE CON TC4
--CLG.COD_LIV_GERARCHICO AS COD_LIV_GERARCHICO, 
--dbo.DateToString_Igrue(ATTI.DATA) AS DATA_PAG_AMM,
--'P' AS TIPOLOGIA_PAG_AMM,
--CASE DP.COD_TIPO 
--WHEN 'ANT' THEN 'ANT'
--WHEN 'SAL' THEN 'INT'
--WHEN 'SLD' THEN 'SLD' END AS CAUSALE_PAG_AMM, -- VERIFICARE TC39
--DPE.IMPORTO_AMMESSO AS IMPORTO_PAG_AMM,
--NULL AS NOTE_PAG,
--NULL AS FLG_CANCELLAZIONE,
--@IdInvio AS ID_INVIO,
--ISNULL(@rNumber,0) + ROW_NUMBER() OVER(ORDER BY P.ID_PROGETTO ASC) AS NR_RIGA_INVIO,
--'FESR20142020' AS CODICE_FONDO   
--FROM vPROGETTO P 
--INNER JOIN vBANDO B ON
--P.ID_BANDO = B.ID_BANDO
----INNER JOIN BANDO_PROGRAMMAZIONE BP ON
----B.ID_BANDO = BP.ID_BANDO
--INNER JOIN zPROGRAMMAZIONE PRG ON
--B.ID_PROGRAMMAZIONE = PRG.ID
--INNER JOIN zPSR_ALBERO PA ON
--PRG.COD_TIPO = PA.CODICE
--INNER JOIN zPSR PSR ON
--PA.COD_PSR = PSR.CODICE
--INNER JOIN DOMANDA_DI_PAGAMENTO_ESPORTAZIONE DPE ON
--P.ID_PROGETTO = DPE.ID_PROGETTO
--INNER JOIN DOMANDA_DI_PAGAMENTO DP ON
--DPE.ID_DOMANDA_PAGAMENTO = DP.ID_DOMANDA_PAGAMENTO
--AND
--DP.APPROVATA = 1
--AND 
--DP.SEGNATURA IS NOT NULL
--LEFT OUTER JOIN 
--ATTI ON 
--DPE.ID_DECRETO = ATTI.ID_ATTO
--INNER JOIN zOB_MISURA OS ON
--B.ID_PROGRAMMAZIONE = OS.ID_PROGRAMMAZIONE
--INNER JOIN zPROGRAMMAZIONE AZIONI ON
--B.ID_PROGRAMMAZIONE = AZIONI.ID
--INNER JOIN zPROGRAMMAZIONE ASSI ON 
--AZIONI.ID_PADRE = ASSI.ID
--LEFT OUTER JOIN 
--(
--	SELECT 
--	D.CODICE AS COD_PI,
--	DP.ID_PROGRAMMAZIONE,
--	PPI.CODICE,
--	PPI.COD_TIPO 
--	FROM zDIMENSIONI D 
--	INNER JOIN zDIMENSIONI_X_PROGRAMMAZIONE DP ON
--	D.ID = DP.ID_DIMENSIONE 
--	INNER JOIN zPROGRAMMAZIONE PPI ON
--	DP.ID_PROGRAMMAZIONE = PPI.ID
--	WHERE D.COD_DIM = 'PI'
--) AS PRI ON
--AZIONI.ID = PRI.ID_PROGRAMMAZIONE
--LEFT OUTER JOIN 
--(
--	SELECT 
--	D.CODICE AS COD_OT,
--	DP.ID_PROGRAMMAZIONE,
--	DP.ID_DIM_X_PROGRAMMAZIONE,
--	DP.ID_DIMENSIONE,
--	PPI.CODICE,
--	PPI.COD_TIPO 
--	FROM zDIMENSIONI D 
--	INNER JOIN zDIMENSIONI_X_PROGRAMMAZIONE DP ON
--	D.ID = DP.ID_DIMENSIONE 
--	INNER JOIN zPROGRAMMAZIONE PPI ON
--	DP.ID_PROGRAMMAZIONE = PPI.ID
--	WHERE D.COD_DIM = 'OT'
--) AS OT ON
--ASSI.ID = OT.ID_PROGRAMMAZIONE
--LEFT OUTER JOIN  CLG ON
----'2014IT16RFOP013#ERDF#M#'+ASSI.CODICE + '#0' + ASSI.CODICE + '#' + PRI.COD_PI + '#' + REPLACE(OS.CODICE, 'OS ','') = CLG.VALORE_DATI_RILEVATI
--'2014IT16RFOP013#ERDF#M#'+ASSI.CODICE + CASE WHEN OT.CODICE IS NULL THEN '' ELSE '#0' END + ISNULL(OT.CODICE,'#N.A.') + '#' + ISNULL(PRI.COD_PI,'N.A.') + '#' + REPLACE(OS.CODICE, 'OS ','') = CLG.VALORE_DATI_RILEVATI
----AND 
----VPR.ISTRUTTORE IS NOT NULL
----AND 
----VPR.ID_INVESTIMENTO_ORIGINALE IS NOT NULL
----AND
----VPR.AMMESSO = 1 
--LEFT OUTER JOIN
--DATI_MONITORAGGIO_FESR DMFR ON
--P.ID_PROGETTO = DMFR.ID_PROGETTO
--WHERE 
--P.COD_STATO IN ('F','V','S','O','T','X','C','Y','E','R') 
--AND 
--PSR.CODICE = 'POR20142020'
--AND PRG.ID NOT IN (17,18,19)
--AND
--P.COD_AGEA IS NOT NULL
----CLAUSOLA TEMPORANEA PER TEST INVIO IGRUE
--AND ATTI.ID_ATTO IS NOT NULL


--AND
--BR.ATTIVO = 1 AND BR.PROVINCIA IS NULL
--AND
--B.DATA_SCADENZA BETWEEN @DataDa AND @DataA


