CREATE PROCEDURE [dbo].[zIgrueInsertMonitPA01]
( 
 @DataDa DATETIME,
 @DataA DATETIME,
 @IdInvio INT,
 @rNumber INT
)
AS
BEGIN
INSERT INTO IGRUE_MONIT.dbo.IGRUE_PA01
(
COD_PROC_ATT,
COD_PROGRAMMA,
IMPORTO,
FLG_CANCELLAZIONE,
--OPERAZIONE,
ID_INVIO,
NR_RIGA_INVIO,
--NR_RIGA_CANCELLAZIONE
CODICE_FONDO
)
SELECT 
--B.ID_BANDO,
BCA.COD_PROCEDURA_ATTIVAZIONE AS COD_PROC_ATT,
'2014IT16RFOP013' AS COD_PROGRAMMA,	--VERIFICARE CON TABELLA DI CONTESTO TC4
B.IMPORTO,
NULL AS FLG_CANCELLAZIONE,
@IdInvio AS ID_INVIO,
ISNULL(@rNumber, 0) + ROW_NUMBER() OVER(ORDER BY B.ID_BANDO ASC) AS NR_RIGA_INVIO,
'FESR20142020' AS CODICE_FONDO
FROM 
vBANDO B
INNER JOIN zPROGRAMMAZIONE PRG ON
B.ID_PROGRAMMAZIONE = PRG.ID
INNER JOIN zPSR_ALBERO PA ON
PRG.COD_TIPO = PA.CODICE
INNER JOIN zPSR PSR ON
PA.COD_PSR = PSR.CODICE
--INNER JOIN BANDO_RESPONSABILI BR ON
--B.ID_BANDO = BR.ID_BANDO
LEFT OUTER JOIN BANDO_CODICI_ATTIVAZIONE BCA ON
B.ID_BANDO = BCA.ID_BANDO
WHERE 
--BR.ATTIVO = 1 AND BR.PROVINCIA IS NULL
--AND 
PSR.CODICE = 'POR20142020'
AND 
B.COD_STATO <> 'P'
AND B.DISPOSIZIONI_ATTUATIVE = 0
--AND
--B.DATA_SCADENZA BETWEEN @DataDa AND @DataA

SELECT ISNULL(MAX(NR_RIGA_INVIO),0) FROM IGRUE_MONIT.dbo.IGRUE_PA01 WHERE ID_INVIO = @IdInvio

END

