CREATE PROCEDURE [dbo].[zIgrueInsertMonitFN03]
( 
 @DataDa DATETIME,
 @DataA DATETIME,
 @IdInvio INT,
 @rNumber INT
)
AS
BEGIN

WITH S AS
(
	SELECT
	PS.ID_PROGETTO,
	MAX(PS.DATA) AS DATA
	FROM PROGETTO_STORICO PS 
	WHERE 
	PS.COD_STATO = 'F'
	GROUP BY 
	PS.ID_PROGETTO,
	PS.COD_STATO
),

VPA AS
(
	SELECT 
	VP.ID_PROGETTO,
	--VP.ID_INVESTIMENTO,
	--VP.CONTRIBUTO_RICHIESTO,
	--DMF.CUP_NATURA,
	--VIC.CODICE_NATURA_CUP,
	--VIC.VOCE_SPESA,
	--vic.DESCRIZIONE_VOCE_SPESA
	SUM(ISNULL(VP.COSTO_INVESTIMENTO,0)) AS IMPORTO_AMMESSO
	FROM
	vPIANO_INVESTIMENTI VP
	INNER JOIN 
	vPROGETTO P ON
	P.ID_PROGETTO = VP.ID_PROGETTO
	WHERE
	--VP.ISTRUTTORE IS NOT NULL
	--AND 
	VP.ID_INVESTIMENTO_ORIGINALE IS NOT NULL
	AND
	VP.ID_VARIANTE IS NULL
	--AND
	--VP.AMMESSO IN (0, 1)
	--AND
	--VP.ID_PROGETTO = 10286
	AND 
	P.COD_STATO IN ('F','V','S','O','T','X','C','Y','E','R')
	GROUP BY 
	VP.ID_PROGETTO
) 


INSERT INTO IGRUE_MONIT.dbo.IGRUE_FN03
(
COD_LOCALE_PROGETTO,
ANNO_PIANO,
IMP_REALIZZATO,
IMP_DA_REALIZZARE,
FLG_CANCELLAZIONE,
--OPERAZIONE,
ID_INVIO,
NR_RIGA_INVIO,
--NR_RIGA_CANCELLAZIONE
CODICE_FONDO
)



SELECT 
P.ID_PROGETTO AS COD_LOCALE_PROGETTO,
DATEPART(YEAR,S.DATA) AS ANNO_PIANO,
0 AS IMP_REALIZZATO,
VPA.IMPORTO_AMMESSO AS IMP_DA_REALIZZARE,
NULL AS FLG_CANCELLAZIONE,
@IdInvio AS ID_INVIO,
ISNULL(@rNumber,0) + ROW_NUMBER() OVER(ORDER BY P.ID_PROGETTO ASC) AS NR_RIGA_INVIO,
'FESR20142020' AS CODICE_FONDO 
FROM vPROGETTO P
INNER JOIN vBANDO B ON
P.ID_BANDO = B.ID_BANDO
--INNER JOIN PROGETTO_STORICO PS ON
--P.ID_PROGETTO = PS.ID_PROGETTO
INNER JOIN BANDO_PROGRAMMAZIONE BP ON
B.ID_BANDO = BP.ID_BANDO
INNER JOIN zPROGRAMMAZIONE PRG ON
BP.ID_PROGRAMMAZIONE = PRG.ID
INNER JOIN zPSR_ALBERO PA ON
PRG.COD_TIPO = PA.CODICE
INNER JOIN zPSR PSR ON
PA.COD_PSR = PSR.CODICE
--INNER JOIN BANDO_RESPONSABILI BR ON
--B.ID_BANDO = BR.ID_BANDO
INNER JOIN S ON
P.ID_PROGETTO = S.ID_PROGETTO
INNER JOIN VPA ON 
P.ID_PROGETTO = VPA.ID_PROGETTO
WHERE 
P.COD_STATO IN ('F','V','S','O','T','X','C','Y','E','R') 
AND 
PSR.CODICE = 'POR20142020'
AND 
PRG.ID NOT IN (17,18,19)
AND
P.COD_AGEA IS NOT NULL
--26/01/2018
--CLAUSOLA TEMPORANEA PER ESCLUDERE PROGETTO STRUMENTI FINANZIARI ARTIGIANCASSA
AND P.ID_PROGETTO <> 13301

SELECT ISNULL(MAX(NR_RIGA_INVIO),0) FROM IGRUE_MONIT.dbo.IGRUE_FN03 WHERE ID_INVIO = @IdInvio

END
