CREATE PROCEDURE [dbo].[zIgrueInsertMonitAP03]
( 
 @DataDa DATETIME,
 @DataA DATETIME,
 @IdInvio INT,
 @rNumber INT
)
AS
BEGIN

WITH AZ AS 
(
SELECT 
INTER.ID AS ID_PROGRAMMAZIONE,
DIM.COD_DIM,
DIM.CODICE, --COD_DIMENSIONE,
PRG.CODICE COD_AZIONE,
INTER.CODICE AS COD_INT
FROM zDIMENSIONI DIM
INNER JOIN zDIMENSIONI_X_PROGRAMMAZIONE ZDP ON 
ZDP.ID_DIMENSIONE = DIM.ID
INNER JOIN zPROGRAMMAZIONE PRG ON
ZDP.ID_PROGRAMMAZIONE = PRG.ID
INNER JOIN zPROGRAMMAZIONE INTER ON
INTER.ID_PADRE = PRG.ID 
WHERE DIM.COD_DIM IN ('RA')
UNION 
SELECT 
PRG.ID AS ID_PROGRAMMAZIONE,
DIM.COD_DIM,
DIM.CODICE, --COD_DIMENSIONE,
PRG.CODICE COD_AZIONE,
PRG.CODICE AS COD_INT
FROM zDIMENSIONI DIM
INNER JOIN zDIMENSIONI_X_PROGRAMMAZIONE ZDP ON 
ZDP.ID_DIMENSIONE = DIM.ID
INNER JOIN zPROGRAMMAZIONE PRG ON
ZDP.ID_PROGRAMMAZIONE = PRG.ID
)

INSERT INTO IGRUE_MONIT.dbo.IGRUE_AP03
(
COD_LOCALE_PROGETTO,
COD_PROGRAMMA,
TIPO_CLASS,
COD_CLASSIFICAZIONE,
FLG_CANCELLAZIONE,
--OPERAZIONE,
ID_INVIO,
NR_RIGA_INVIO,
--NR_RIGA_CANCELLAZIONE
CODICE_FONDO
)

SELECT 
A.COD_LOCALE_PROGETTO,
A.COD_PROGRAMMA,
A.TIPO_CLASS,
A.COD_CLASSIFICAZIONE,
FLG_CANCELLAZIONE,
@IdInvio AS ID_INVIO,
ISNULL(@rNumber,0) + ROW_NUMBER() OVER(ORDER BY A.COD_LOCALE_PROGETTO ASC) AS NR_RIGA_INVIO,
A.CODICE_FONDO

FROM 
(
SELECT 
P.ID_PROGETTO AS COD_LOCALE_PROGETTO,
'2014IT16RFOP013' AS COD_PROGRAMMA,	--VERIFICARE CON TABELLA DI CONTESTO TC4 
--CASE DIM.COD_DIM
CASE AZ.COD_DIM  
WHEN 'D1' THEN 'CI'
WHEN 'D2' THEN 'FF'
WHEN 'D3' THEN 'TT'
WHEN 'D6' THEN 'MET' 
WHEN 'RA' THEN 'RA'
END AS TIPO_CLASS, --VERIFICARE TC11
--DIM.CODICE AS COD_CLASSIFICAZIONE, -- COLLEGARE UNA DELLE TC12.x IN BASE AL VALORE TC11
AZ.CODICE AS COD_CLASSIFICAZIONE, -- COLLEGARE UNA DELLE TC12.x IN BASE AL VALORE TC11 
NULL AS FLG_CANCELLAZIONE,
--@IdInvio AS ID_INVIO,
--ISNULL(@rNumber,0) + ROW_NUMBER() OVER(ORDER BY P.ID_PROGETTO ASC) AS NR_RIGA_INVIO,
'FESR20142020' AS CODICE_FONDO 
FROM vPROGETTO P
INNER JOIN vBANDO B ON
P.ID_BANDO = B.ID_BANDO
--INNER JOIN PROGETTO_STORICO PS ON
--P.ID_PROGETTO = PS.ID_PROGETTO
INNER JOIN BANDO_PROGRAMMAZIONE BP ON
B.ID_BANDO = BP.ID_BANDO
INNER JOIN zPROGRAMMAZIONE PRG ON
BP.ID_PROGRAMMAZIONE = PRG.ID
INNER JOIN zPSR_ALBERO PA ON
PRG.COD_TIPO = PA.CODICE
INNER JOIN zPSR PSR ON
PA.COD_PSR = PSR.CODICE
--INNER JOIN BANDO_RESPONSABILI BR ON
--B.ID_BANDO = BR.ID_BANDO
INNER JOIN vBANDO_PROGRAMMAZIONE VBP ON
B.ID_BANDO = VBP.ID_BANDO
--INNER JOIN zDIMENSIONI_X_PROGRAMMAZIONE DP ON
--VBP.ID_PROGRAMMAZIONE = DP.ID_PROGRAMMAZIONE
--INNER JOIN zDIMENSIONI DIM ON
--DP.ID_DIMENSIONE = DIM.ID
--AND DIM.COD_DIM LIKE 'D%'
INNER JOIN AZ ON
VBP.ID_PROGRAMMAZIONE = AZ.ID_PROGRAMMAZIONE
AND 
--DIM.COD_DIM LIKE 'D%' OR DIM.COD_DIM LIKE 'RA%'
AZ.COD_DIM IN ('D1','D2','D3','D6','RA')
WHERE 
P.COD_STATO IN ('F','V','S','O','T','X','C','Y','E','R') 
AND 
PSR.CODICE = 'POR20142020'
AND 
PRG.ID NOT IN (17,18,19)
AND 
VBP.ID_PROGRAMMAZIONE NOT IN (17,18,19)
AND
P.COD_AGEA IS NOT NULL

UNION ALL

SELECT 
P.ID_PROGETTO AS COD_LOCALE_PROGETTO,
'2014IT16RFOP013' AS COD_PROGRAMMA,	--VERIFICARE CON TABELLA DI CONTESTO TC4 
--CASE DIM.COD_DIM
'AE' AS TIPO_CLASS, --VERIFICARE TC11
--DIM.CODICE AS COD_CLASSIFICAZIONE, -- COLLEGARE UNA DELLE TC12.x IN BASE AL VALORE TC11
DMFSR.ATTIVITA_ECON AS COD_CLASSIFICAZIONE, -- COLLEGARE UNA DELLE TC12.x IN BASE AL VALORE TC11 
NULL AS FLG_CANCELLAZIONE,
--@IdInvio AS ID_INVIO,
--ISNULL(@rNumber,0) + ROW_NUMBER() OVER(ORDER BY P.ID_PROGETTO ASC) AS NR_RIGA_INVIO,
'FESR20142020' AS CODICE_FONDO 
FROM vPROGETTO P
INNER JOIN vBANDO B ON
P.ID_BANDO = B.ID_BANDO
--INNER JOIN PROGETTO_STORICO PS ON
--P.ID_PROGETTO = PS.ID_PROGETTO
INNER JOIN BANDO_PROGRAMMAZIONE BP ON
B.ID_BANDO = BP.ID_BANDO
INNER JOIN zPROGRAMMAZIONE PRG ON
BP.ID_PROGRAMMAZIONE = PRG.ID
INNER JOIN zPSR_ALBERO PA ON
PRG.COD_TIPO = PA.CODICE
INNER JOIN zPSR PSR ON
PA.COD_PSR = PSR.CODICE
--INNER JOIN BANDO_RESPONSABILI BR ON
--B.ID_BANDO = BR.ID_BANDO
INNER JOIN vBANDO_PROGRAMMAZIONE VBP ON
B.ID_BANDO = VBP.ID_BANDO
--INNER JOIN zDIMENSIONI_X_PROGRAMMAZIONE DP ON
--VBP.ID_PROGRAMMAZIONE = DP.ID_PROGRAMMAZIONE
--INNER JOIN zDIMENSIONI DIM ON
--DP.ID_DIMENSIONE = DIM.ID
--AND DIM.COD_DIM LIKE 'D%'
INNER JOIN DATI_MONITORAGGIO_FESR DMFSR ON
P.ID_PROGETTO = DMFSR.ID_PROGETTO
WHERE 
P.COD_STATO IN ('F','V','S','O','T','X','C','Y','E','R') 
AND 
PSR.CODICE = 'POR20142020'
AND 
PRG.ID NOT IN (17,18,19)
AND 
VBP.ID_PROGRAMMAZIONE NOT IN (17,18,19)
AND
P.COD_AGEA IS NOT NULL
) AS A
--26/01/2018
--CLAUSOLA TEMPORANEA PER ESCLUDERE PROGETTO STRUMENTI FINANZIARI ARTIGIANCASSA
WHERE A.COD_LOCALE_PROGETTO <> 13301

--AND
--BR.ATTIVO = 1 AND BR.PROVINCIA IS NULL
--AND
--B.DATA_SCADENZA BETWEEN @DataDa AND @DataA

--CI: Campo di intervento: TC12.1
--FF: Forme Finanziamento: TC12.2 
--TT: Tipo di territorio: TC12.3
--MET:Meccanismi Erogazione Territoriale:  TC12.4

SELECT ISNULL(MAX(NR_RIGA_INVIO),0) FROM IGRUE_MONIT.dbo.IGRUE_AP03 WHERE ID_INVIO = @IdInvio

END

