CREATE PROCEDURE [dbo].[ZImpresaStoricoFindFind]
(
	@IdImpresaequalthis INT
)
AS
	declare @sql nvarchar(4000);
	declare @lensql int;
	set @lensql=0;
	SET @sql = 'SELECT ID_STORICO_IMPRESA, ID_IMPRESA, DATA_INIZIO_VALIDITA, DATA_FINE_VALIDITA, RAGIONE_SOCIALE, CODICE_INPS, COD_FORMA_GIURIDICA, ID_DIMENSIONE, REGISTRO_IMPRESE_NUMERO, REA_NUMERO, REA_ANNO, DIMENSIONE_IMPRESA, FORMA_GIURIDICA, COD_CLASSIFICAZIONE_UMA, ATTIVA, DATA_CESSAZIONE, SEGNATURA_CESSAZIONE, COD_TIPO_CESSAZIONE, COD_ATECO2007 FROM vIMPRESA_STORICO WHERE 1=1';
	IF (@IdImpresaequalthis IS NOT NULL) BEGIN SET @sql = @sql + ' AND (ID_IMPRESA = @IdImpresaequalthis)'; set @lensql=@lensql+len(@IdImpresaequalthis);end;
	set @sql = @sql + 'ORDER BY DATA_INIZIO_VALIDITA DESC';
	set @lensql=@lensql+len(@sql);
	if (@lensql<3000)
	exec sp_executesql @sql,N'@IdImpresaequalthis INT',@IdImpresaequalthis ;
	else
		SELECT ID_STORICO_IMPRESA, ID_IMPRESA, DATA_INIZIO_VALIDITA, DATA_FINE_VALIDITA, RAGIONE_SOCIALE, CODICE_INPS, COD_FORMA_GIURIDICA, ID_DIMENSIONE, REGISTRO_IMPRESE_NUMERO, REA_NUMERO, REA_ANNO, DIMENSIONE_IMPRESA, FORMA_GIURIDICA, COD_CLASSIFICAZIONE_UMA, ATTIVA, DATA_CESSAZIONE, SEGNATURA_CESSAZIONE, COD_TIPO_CESSAZIONE, COD_ATECO2007
		FROM vIMPRESA_STORICO
		WHERE 
			((@IdImpresaequalthis IS NULL) OR ID_IMPRESA = @IdImpresaequalthis)
		ORDER BY DATA_INIZIO_VALIDITA DESC


GO
EXECUTE sp_addextendedproperty @name = N'backup', @value = 'CREATE PROCEDURE [dbo].[ZImpresaStoricoFindFind]
(
	@IdImpresaequalthis INT
)
AS
	declare @sql nvarchar(4000);
	declare @lensql int;
	set @lensql=0;
	SET @sql = ''SELECT ID_STORICO_IMPRESA, ID_IMPRESA, DATA_INIZIO_VALIDITA, DATA_FINE_VALIDITA, RAGIONE_SOCIALE, CODICE_INPS, COD_FORMA_GIURIDICA, ID_DIMENSIONE, REGISTRO_IMPRESE_NUMERO, REA_NUMERO, REA_ANNO, DIMENSIONE_IMPRESA, FORMA_GIURIDICA, COD_CLASSIFICAZIONE_UMA, ATTIVA, DATA_CESSAZIONE, SEGNATURA_CESSAZIONE, COD_TIPO_CESSAZIONE, COD_ATECO2007 FROM vIMPRESA_STORICO WHERE 1=1'';
	IF (@IdImpresaequalthis IS NOT NULL) BEGIN SET @sql = @sql + '' AND (ID_IMPRESA = @IdImpresaequalthis)''; set @lensql=@lensql+len(@IdImpresaequalthis);end;
	set @sql = @sql + ''ORDER BY DATA_INIZIO_VALIDITA DESC'';
	set @lensql=@lensql+len(@sql);
	if (@lensql<3000)
	exec sp_executesql @sql,N''@IdImpresaequalthis INT'',@IdImpresaequalthis ;
	else
		SELECT ID_STORICO_IMPRESA, ID_IMPRESA, DATA_INIZIO_VALIDITA, DATA_FINE_VALIDITA, RAGIONE_SOCIALE, CODICE_INPS, COD_FORMA_GIURIDICA, ID_DIMENSIONE, REGISTRO_IMPRESE_NUMERO, REA_NUMERO, REA_ANNO, DIMENSIONE_IMPRESA, FORMA_GIURIDICA, COD_CLASSIFICAZIONE_UMA, ATTIVA, DATA_CESSAZIONE, SEGNATURA_CESSAZIONE, COD_TIPO_CESSAZIONE, COD_ATECO2007
		FROM vIMPRESA_STORICO
		WHERE 
			((@IdImpresaequalthis IS NULL) OR ID_IMPRESA = @IdImpresaequalthis)
		ORDER BY DATA_INIZIO_VALIDITA DESC

', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'PROCEDURE', @level1name = N'ZImpresaStoricoFindFind';

