CREATE PROCEDURE [dbo].[ZIndirizzoUpdate]
(
	@ID_INDIRIZZO INT, 
	@VIA VARCHAR(500), 
	@LOCALITA VARCHAR(500), 
	@ID_COMUNE INT, 
	@DENOMINAZIONE VARCHAR(255)
)
AS
	UPDATE INDIRIZZO
	SET
		VIA = @VIA, 
		LOCALITA = @LOCALITA, 
		ID_COMUNE = @ID_COMUNE, 
		DENOMINAZIONE = @DENOMINAZIONE
	WHERE 
		(ID_INDIRIZZO = @ID_INDIRIZZO)
