CREATE PROCEDURE [dbo].[ZPersonaFisicaFindFind]
(
	@CodiceFiscaleequalthis VARCHAR(255)
)
AS
	declare @sql nvarchar(4000);
	declare @lensql int;
	set @lensql=0;
	SET @sql = 'SELECT ID_PERSONA, NOME, COGNOME, CODICE_FISCALE, SESSO, DATA_NASCITA, ID_CITTADINANZA, CITTADINANZA, ID_COMUNE_NASCITA, COMUNE, PROVINCIA FROM vPERSONA_FISICA WHERE 1=1';
	IF (@CodiceFiscaleequalthis IS NOT NULL) BEGIN SET @sql = @sql + ' AND (CODICE_FISCALE = @CodiceFiscaleequalthis)'; set @lensql=@lensql+len(@CodiceFiscaleequalthis);end;
	set @sql = @sql + 'ORDER BY COGNOME, NOME';
	set @lensql=@lensql+len(@sql);
	if (@lensql<3000)
	exec sp_executesql @sql,N'@CodiceFiscaleequalthis VARCHAR(255)',@CodiceFiscaleequalthis ;
	else
		SELECT ID_PERSONA, NOME, COGNOME, CODICE_FISCALE, SESSO, DATA_NASCITA, ID_CITTADINANZA, CITTADINANZA, ID_COMUNE_NASCITA, COMUNE, PROVINCIA
		FROM vPERSONA_FISICA
		WHERE 
			((@CodiceFiscaleequalthis IS NULL) OR CODICE_FISCALE = @CodiceFiscaleequalthis)
		ORDER BY COGNOME, NOME

GO
EXECUTE sp_addextendedproperty @name = N'backup', @value = N'





CREATE PROCEDURE [dbo].[ZPersonafisicaFindFind]
(
	@ID_PERSONAEQUALTHIS INT, 
	@CODICE_FISCALEEQUALTHIS VARCHAR(16), 
	@SESSOEQUALTHIS CHAR(1), 
	@ID_COMUNE_NASCITAEQUALTHIS INT, 
	@ID_CITTADINANZAEQUALTHIS INT, 
	@NOMEEQUALTHIS VARCHAR(255), 
	@COGNOMEEQUALTHIS VARCHAR(255)
)
AS
	SELECT * 
	FROM vPersonaFisica
	WHERE 
		((@ID_PERSONAEQUALTHIS IS NULL) OR ID_PERSONA = @ID_PERSONAEQUALTHIS) AND 
		((@CODICE_FISCALEEQUALTHIS IS NULL) OR CODICE_FISCALE = @CODICE_FISCALEEQUALTHIS) AND 
		((@SESSOEQUALTHIS IS NULL) OR SESSO = @SESSOEQUALTHIS) AND 
		((@ID_COMUNE_NASCITAEQUALTHIS IS NULL) OR ID_COMUNE_NASCITA = @ID_COMUNE_NASCITAEQUALTHIS) AND 
		((@ID_CITTADINANZAEQUALTHIS IS NULL) OR ID_CITTADINANZA = @ID_CITTADINANZAEQUALTHIS) AND 
		((@NOMEEQUALTHIS IS NULL) OR NOME = @NOMEEQUALTHIS) AND 
		((@COGNOMEEQUALTHIS IS NULL) OR COGNOME = @COGNOMEEQUALTHIS)

', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'PROCEDURE', @level1name = N'ZPersonaFisicaFindFind';

