CREATE TABLE [dbo].[ESITO_ISTANZA_CHECKLIST_GENERICO] (
    [ID_ESITO_GENERICO]        INT           IDENTITY (1, 1) NOT NULL,
    [ID_VOCE_GENERICA]         INT           NOT NULL,
    [ID_ISTANZA_GENERICA]      INT           NOT NULL,
    [COD_ESITO]                CHAR (2)      NULL,
    [VALORE]                   VARCHAR (100) NULL,
    [DATA_INSERIMENTO]         DATETIME      CONSTRAINT [DF_ESITO_ISTANZA_CHECKLIST_DATA_INSERIMENTO] DEFAULT (getdate()) NULL,
    [CF_INSERIMENTO]           CHAR (16)     NULL,
    [DATA_MODIFICA]            DATETIME      CONSTRAINT [DF_ESITO_ISTANZA_CHECKLIST_DATA_MODIFICA] DEFAULT (getdate()) NULL,
    [CF_MODIFICA]              CHAR (16)     NULL,
    [NOTE]                     NTEXT         NULL,
    [COD_ESITO_REVISORE]       CHAR (2)      NULL,
    [DATA_REVISORE]            DATETIME      NULL,
    [REVISORE]                 VARCHAR (16)  NULL,
    [NOTE_REVISORE]            NTEXT         NULL,
    [ESCLUDI_DA_COMUNICAZIONE] BIT           CONSTRAINT [DF_ESITO_ISTANZA_CHECKLIST_ESCLUDI_DA_COMUNICAZIONE] DEFAULT ((0)) NULL,
    CONSTRAINT [PK_ESITO_ISTANZA_CHECKLIST_GENERICO] PRIMARY KEY CLUSTERED ([ID_ESITO_GENERICO] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_ESITO_ISTANZA_CHECKLIST_ESITI_STEP] FOREIGN KEY ([COD_ESITO]) REFERENCES [dbo].[ESITI_STEP] ([COD_ESITO]),
    CONSTRAINT [FK_ESITO_ISTANZA_CHECKLIST_ISTANZA_CHECKLIST] FOREIGN KEY ([ID_ISTANZA_GENERICA]) REFERENCES [dbo].[ISTANZA_CHECKLIST_GENERICA] ([ID_ISTANZA_GENERICA]),
    CONSTRAINT [FK_ESITO_ISTANZA_CHECKLIST_VOCE] FOREIGN KEY ([ID_VOCE_GENERICA]) REFERENCES [dbo].[VOCE_GENERICA] ([ID_VOCE_GENERICA])
);

