CREATE TABLE FILTRO_CHECKLIST_VOCE (
	ID_FILTRO VARCHAR(200) NOT NULL PRIMARY KEY,
	CF_INSERIMENTO VARCHAR(16) NOT NULL,
	DATA_INSERIMENTO DATETIME NOT NULL,
	CF_MODIFICA VARCHAR(16) NOT NULL,
	DATA_MODIFICA DATETIME NOT NULL DEFAULT GETDATE(),

	DESCRIZIONE VARCHAR(MAX) NOT NULL,
	ORDINE INT NOT NULL
);